feat(ot3): add pipette tip handling CAN messages
OpenTrons/opentrons-api pull request #10038
Opened 2022-04-21 20:41 UTC by Laura-Danielle

# Overview

For now, these messages will be used only to perform 96/384 channel pick up and drop tip commands. In the future, we would like to investigate potentially saving pipette configurations on the microcontroller itself so that we can use this CAN command for all pipette types.

# Changelog

- Added pickup and drop tip request/response messages.

# Risk assessment

None. Not being used currently.

2022-04-21 20:58 UTC, sfoster1 requested changes
couple tiny changes

2022-04-21 20:58 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_bindings/constants.py
> +    pick_up_tip_request = 0x501
can we call this something more specific to this style of pickup, like `do_self_contained_pickup` or something

2022-04-21 20:58 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_bindings/constants.py
> +    drop_tip_request = 0x503
this on the other hand is fine, and may in fact be used to do tip-shroud style ejection

2022-04-21 20:58 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_bindings/messages/message_definitions.py
> +class PickUpTipRequest:  # noqa: D101
```suggestion
@dataclass
class PickUpTipRequest:  # noqa: D101
```

2022-04-22 11:26 UTC, amitlissack commented on hardware/opentrons_hardware/firmware_bindings/messages/payloads.py
> +
Not a huge deal but could these 4 types be reduced to 2? `TipActionRequest` and `TipActionResponse`?

2022-04-22 12:57 UTC, sfoster1 approved these changes
Wouldn't mind the changes @amitlissack mentioned but looks good to me

2022-04-22 15:18 UTC, merged