Primarily results for the bug 8588
OpenTrons/opentrons-api pull request #10052
Opened 2022-04-22 20:32 UTC by aptrons22

# Overview

# Changelog

# Review requests

# Risk assessment

2022-04-27 14:35 UTC, SyntaxColoring requested changes
Progress looks good so far. Here are the next steps, as we discussed in a call.

2022-04-27 14:35 UTC, SyntaxColoring commented on robot-server/robot_server/app_setup.py
> +from .service.task_runner import TaskRunner
Style: Let's move this down just under the existing `from .service ...` import, to match the existing convention. See [PEP8](https://peps.python.org/pep-0008/) for where these conventions are established.

2022-04-27 14:35 UTC, SyntaxColoring commented on robot-server/robot_server/app_setup.py
> +    app.state.task_runner = TaskRunner()
As discussed, let's reorganize things so that two different files don't both have to know that the `TaskRunner` singleton is stored at the `.task_runner` property on `app.state`.

I would follow the pattern set here by `initialize_hardware()` and `cleanup_hardware()`.

`task_runner.py` should expose two new methods:

```python
async def initialize_task_runner(app_state: AppState) -> None:
    """Create a new `TaskRunner` and store it on `app_state`."""
    # [implementation omitted]

async def clean_up_task_runner(app_state: AppState) -> None:
    """Clean up the `TaskRunner` stored on `app_state`."""
    # [implementation omitted]
```

The implementation will involve an `AppStateValue`. Take a look at that class and how it's used in files like `hardware.py` and `protocols/dependencies.py`, for example.

Once those two new methods are in place, use them here instead of manually calling `app.state.task_runner = TaskRunner()` and `app.state.task_runner.cancel_all_and_clean_up()`.

2022-04-27 14:35 UTC, SyntaxColoring commented on robot-server/robot_server/service/task_runner.py
> +
Try `make format` to automatically reformat your files, which will fix things like this extra whitespace.

2022-04-27 14:35 UTC, SyntaxColoring commented on robot-server/robot_server/service/task_runner.py
> -                log.warning(f"Background task {func_name} failed", exc_info=e)
I think these logs were helpful. Let's add 'em back.

2022-04-27 14:35 UTC, SyntaxColoring commented on robot-server/robot_server/service/task_runner.py
> +        self._running_tasks.add(new_ct)
As discussed, as we've implemented this, there's a slow memory leak. `self._running_tasks` will slowly accumulate background tasks, and will only be cleared when the process shuts down.

We need each task to remove itself from `self._running_tasks` just before it completes. A task can retrieve itself with [`asyncio.current_task()`](https://docs.python.org/3/library/asyncio-task.html#asyncio.current_task) and then remove itself from the set by calling [`.remove()`](https://docs.python.org/3.9/library/stdtypes.html#frozenset.remove) on the set.

2022-04-29 17:20 UTC, SyntaxColoring requested changes

2022-04-29 17:20 UTC, SyntaxColoring commented on robot-server/robot_server/service/task_runner.py
> +from hashlib import new
Looks like `hashlib` is unused. You can remove this import.

2022-04-29 17:20 UTC, SyntaxColoring commented on robot-server/robot_server/service/task_runner.py
> +            Use **kwargs to pass to func.
```suggestion
            kwargs: Keyword arguments to pass straight through to `func`.
```

2022-04-29 17:20 UTC, SyntaxColoring commented on robot-server/robot_server/service/task_runner.py
> +    """Clean up the `TaskRunner` stored on `app_state`."""
Docstring suggestion to help prevent misuse:

```suggestion
async def clean_up_task_runner(app_state: AppState) -> None:
    """Clean up the `TaskRunner` stored on `app_state`.
    
    Intended to be called just once, when the server shuts down.
    """
```

2022-04-29 17:20 UTC, SyntaxColoring commented on robot-server/robot_server/service/task_runner.py
> +    """Create a new `TaskRunner` and store it on `app_state`."""
Docstring suggestion to help prevent misuse:

```suggestion
def initialize_task_runner(app_state: AppState) -> None:
    """Create a new `TaskRunner` and store it on `app_state`.
    
    Intended to be called just once, when the server starts up.
    """
```

2022-04-29 17:20 UTC, SyntaxColoring commented on robot-server/robot_server/service/task_runner.py
> +_init_taskrunner = AppStateValue["TaskRunner"]("bg_task_runner")
I would rename this to `task_runner`. I don't think the word "init" makes sense here, and, "task runner" is two words so it should be separated with an underscore.

I would also change the string `"bg_task_runner"` to `"task_runner"`. It doesn't matter for anything, but it's nice if it matches.

2022-04-29 17:20 UTC, SyntaxColoring commented on robot-server/robot_server/service/task_runner.py
> +        """Initialize the TaskRunner by using Python Set"""
This docstring mentioning a Python set is outdated, with your refactors.

I would either delete the docstring, if our linter lets you, or simply make it "Initialize the `TaskRunner`."

2022-04-29 17:20 UTC, SyntaxColoring commented on robot-server/robot_server/service/task_runner.py
> +    async def cancel_all_and_clean_up(self) -> None:
Docstring suggestion:

```suggestion
    async def cancel_all_and_clean_up(self) -> None:
        """Cancel any ongoing background tasks and wait for them to stop.
        
        Intended to be called just once, when the server shuts down.
        """
```

2022-04-29 17:20 UTC, SyntaxColoring commented on robot-server/robot_server/service/task_runner.py
> +        await asyncio.gather(*self._running_tasks, return_exceptions=True)
Another log that might be helpful to have:

```suggestion
        log.debug(
            f"Cancelled {len(self._running_tasks)} background tasks."
            f" Waiting for them to stop."
        )
        await asyncio.gather(*self._running_tasks, return_exceptions=True)
        log.debug("Background tasks stopped.")
```

2022-04-29 17:20 UTC, SyntaxColoring commented on robot-server/robot_server/service/task_runner.py
>  """
We can rewrite this docstring to focus it on being a good introduction to people unfamiliar with this module. Something roughly like:

> Safely run async tasks in the background from FastAPI endpoints.
>
> This replaces `fastapi.BackgroundTasks`. One problem with `fastapi.BackgroundTasks` is that on shutdown, nothing cancels them, and Uvicorn waits for them to finish on their own. Since we have background tasks that can take tens of minutes, this can stall server shutdown.

In particular: 

* This avoids talking about the "refactor" or "previous code base" because these aren't meaningful to a reader coming into this module from the cold.
* This explains the motivation behind this DIY solution in the first place, and why the built-in solutions are insufficient.

2022-04-29 17:20 UTC, SyntaxColoring commented on robot-server/robot_server/service/task_runner.py
> +            # Add the previous logic back
Is there anything left to do for this, or can this comment be removed?

2022-04-29 17:20 UTC, SyntaxColoring commented on robot-server/robot_server/service/task_runner.py
> +def get_task_runner(app_state: AppState = Depends(get_app_state)) -> TaskRunner:
Let's turn this comment into a docstring.

```suggestion
def get_task_runner(app_state: AppState = Depends(get_app_state)) -> TaskRunner:
    """Return the server's `TaskRunner`.
    
    Intended to be used by endpoint functions as a FastAPI dependency,
    like `task_runner = fastapi.Depends(get_task_runner)`.
    """
```

2022-05-02 19:43 UTC, mcous approved these changes
A couple little docstring suggestions, but looks good to me otherwise!

Let me know if you need any help getting this to pass CI

2022-05-02 19:43 UTC, mcous commented on robot-server/robot_server/service/task_runner.py
> +"""
Looks like the docstring title was lost, and this needs to be updated. Maybe something like this?

```py
"""Background task runner.

This module provides interfaces to run asynchronous functions in
the background, outside of normal HTTP request/response sequences.
"""
```

2022-05-02 19:43 UTC, mcous commented on robot-server/robot_server/service/task_runner.py
> +            Kwargs: Keyword arguments to pass straight through to `func`.
```suggestion
            **kwargs: Keyword arguments to pass straight through to `func`.
```

2022-05-02 20:33 UTC, SyntaxColoring approved these changes
I agree with Mike's docstring suggestions. But this looks good to merge as soon as the CI checks pass. Thanks! 🕺

2022-05-02 20:42 UTC, aptrons22 commented
Committing the final code revisions.

2022-05-04 14:09 UTC, merged