feat(hardware): polling support for sensor drivers
OpenTrons/opentrons-api pull request #10083
Opened 2022-04-26 14:45 UTC by caila-marashaj

Was having a lot of trouble with my previous branch, so I decided to just port the changes over to a new one. 

- removed BindSensorResponse message
- added drivers for polling, sending a BindSensorRequest
- added unit tests for new functionality

2022-04-26 14:58 UTC, sfoster1 requested changes
We definitely want a function to remove bindings, and maybe an async context manager for bindings as a whole. Other than that, looks good!

2022-05-09 14:46 UTC, sfoster1 approved these changes
Looks good overall. We should fix that typo and consider putting the bind sync functionality in the base but I'd be happy merging without that (not with the typo tho let's fix that)

2022-05-09 14:46 UTC, sfoster1 commented on hardware/opentrons_hardware/sensors/mmr920C04.py
> +        """Poll the capacitive sensor."""
copy/paste?

2022-05-09 14:46 UTC, sfoster1 commented on hardware/opentrons_hardware/sensors/mmr920C04.py
> +    @asynccontextmanager
seems like we could put this in the base class honestly

2022-05-09 14:59 UTC, Laura-Danielle requested changes
Some small changes. Also agree with @sfoster1 that we can move `bind_output` to `AbstractAdvancedSensor`.

2022-05-09 14:59 UTC, Laura-Danielle commented on hardware/tests/opentrons_hardware/sensors/test_sensor_drivers.py
> +# @pytest.mark.skip("need to fix bind_output")
If this is fixed we can remove this line.

2022-05-09 14:59 UTC, Laura-Danielle commented on hardware/opentrons_hardware/sensors/fdc1004.py
>          scheduler = SensorScheduler()
Missing a replacement of `scheduler` with `_scheduler`

2022-05-09 19:57 UTC, Laura-Danielle commented on hardware/opentrons_hardware/sensors/sensor_abc.py
> +    async def bind_output(
Basic sensors probably won't have this ability, so we should move this down to `AdvancedAbstractSensor` and then keep the actual function implementation in the individual sensor drivers.

2022-05-10 18:40 UTC, Laura-Danielle requested changes
Need to move `scheduler` definition either to all of the subclasses (sensor drivers) or only define it in the ABC.

2022-05-10 18:40 UTC, Laura-Danielle commented on hardware/opentrons_hardware/sensors/sensor_abc.py
> +        self._scheduler = SensorScheduler()
Still have `_scheduler` defined here.

2022-05-10 18:40 UTC, Laura-Danielle commented on hardware/tests/opentrons_hardware/sensors/test_sensor_drivers.py
> +# @pytest.mark.skip("need to fix bind_output")
Still need to remove this comment.

2022-05-12 15:37 UTC, Laura-Danielle approved these changes
Nice lgtm!

2022-05-12 21:15 UTC, merged