initial reorganization
OpenTrons/opentrons-api pull request #10125
Opened 2022-04-28 20:48 UTC by ecormany

# Overview

Preparing for updating the API documentation to accurately reflect how Python protocols will interact with Labware Position Check enhancements.

# Changelog

- Moved several sections from Labware, Building Block Commands, and Pipette pages to form basis of new Control the Robot's Position page.
- several TKs in the wake of those moves

# Review requests

# Risk assessment

2022-05-12 17:48 UTC, ecormany commented
Feedback from Alex Copperman:

> Do you think it'd be possible to link "https://www.w3schools.com/python/python_tuples.asp"  for one of our "Tuples" mentions since it is technically outside of what we write as necessary Python knowledge here "https://docs.opentrons.com/v2/writing.html#python-for-beginners"

Going to maintain this link because it's a native Sphinx `:py:class:` reference to the Python docs.

> There is a bug when you try and use "move_to" that might be worthwhile to note (since it doesn't look like it's going anywhere) 

Will investigate to see whether `force_direct=True` addresses this.

> https://github.com/Opentrons/opentrons/pull/10125/files?short_path=5eda2f8#diff-5eda2f8df058aa78728fb7c05b56197d4396efb9383c3bf5cd85cd626e443b47 --> It looks like it might benefit from a "[Table of Axes" ](https://support.opentrons.com/s/article/SmoothieError-Hard-limit#h_58b2a2b26e)(except B/C are removed because plungers aren't involved)  with each axis.

Current structure aims to build this up linearly: `top()` and `bottom()` only take z arguments, points handle xyz, axis limits handle xyza. Notes mention b and c, but none of the methods covered here can do anything with them (hence link out to Pipettes near the bottom of the page).

2022-06-06 13:46 UTC, alexjoel42 commented
@ecormany 

# Clarity 
Would you be able to add an explanation (or reference documentation) for what protocol.deck.position_for('5') is prior to placing it in the [documentation](https://github.com/Opentrons/opentrons/pull/10125/files#diff-5eda2f8df058aa78728fb7c05b56197d4396efb9383c3bf5cd85cd626e443b47R225-R240)? It is a trickier concept for folks. 

# Clarity Pt. 2 

We should have an [explanation for where point (0,0,0) ](http://sandbox.docs.opentrons.com/docs-lpc-enhancements/v2/robot_position.html#points-vs-locations) is within deck slots, wells, etc. 


#  Unclear if true:
Under [default positions](http://sandbox.docs.opentrons.com/docs-lpc-enhancements/v2/robot_position.html#default-positions) I'm not near a robot, but I would test how [complex commands ](https://docs.opentrons.com/v2/new_protocol_api.html#opentrons.protocol_api.contexts.InstrumentContext.transfer) receive types.location parameters (E.G: pipette.transfer(vol, well.top(), dest.bottom(z=10) )

2022-06-06 14:09 UTC, SyntaxColoring requested changes
Looking at [the implementation for `position_for()`](https://github.com/Opentrons/opentrons/blob/239b15c010ef6aa4680c5bfe36978134802103a4/api/src/opentrons/protocols/geometry/deck.py#L184-L186), it's not clear to me that it's meant to be a public-facing method.

It's missing the [`@requires_version`](https://github.com/Opentrons/opentrons/blob/239b15c010ef6aa4680c5bfe36978134802103a4/api/src/opentrons/protocol_api/instrument_context.py#L131) decorator that public methods usually have. This strongly suggests, but doesn't definitively mean, that it's meant to be private.

(The fact that it's not obvious one way or the other is a symptom of a historically very fuzzy division between public and private methods in the Python Protocol API.)

Did `position_for()` appear in our documentation before? If not, this PR might accidentally be publicizing it. Maybe we should publicize it anyway, but it will take some additional implementation care, like tests and a version bump.

2022-06-06 14:15 UTC, ecormany commented
I agree with @SyntaxColoring: `position_for()` is underdocumented. The code using it in the Gantry Speed section was [already present](https://github.com/Opentrons/opentrons/pull/10125/files#diff-14e4634981a7475ef4ec3458b6a8a43e0e1489bf541375d1ffac3ac7a8184b63L396-L400) but I think the correct remedy for now is to rewrite the example using a well position method or absolute coordinates with a location relative to `None`.

2022-06-06 14:19 UTC, SyntaxColoring commented
Interesting—so, as far as you know, is it correct to say that, historically, this has been the case?

* `position_for()` has appeared in that one unrelated code example about gantry speed
* `position_for()` has not appeared anywhere else
* `position_for()` has not had reference documentation

2022-06-06 14:23 UTC, SyntaxColoring commented
It looks like `position_for()` is also [used in the wild in some protocols written by Applications Engineering](https://github.com/Opentrons/Protocols/blob/24b4fec0e128bf1b84e5e4239384f5e999743808/protocols/04eeb1-part-2/04eeb1-part-2.ot2.apiv2.py#L48).

Given all of this:

* I agree with @ecormany that the move for this PR is to avoid mentioning `position_for()`.
* I will make a separate ticket for formally promoting `position_for()` to a public part of the Python Protocol API.
    * Edit: #10651

2022-06-06 15:25 UTC, ecormany commented
> Under [default positions](http://sandbox.docs.opentrons.com/docs-lpc-enhancements/v2/robot_position.html#default-positions) I'm not near a robot, but I would test how [complex commands ](https://docs.opentrons.com/v2/new_protocol_api.html#opentrons.protocol_api.contexts.InstrumentContext.transfer) receive types.location parameters (E.G: pipette.transfer(vol, well.top(), dest.bottom(z=10) )

@alexjoel42 Confirmed these are equivalent on my robot:
```python
	pipette.transfer(100, plate['A1'].bottom(z=5), plate['A2'].bottom(z=25))

	pipette.well_bottom_clearance.aspirate = 5
	pipette.well_bottom_clearance.dispense = 25
	pipette.transfer(100, plate['A1'], plate['A2'])
```

`transfer()` also happily took `plate['A2'].top()` as a destination argument.

2022-06-06 20:04 UTC, SyntaxColoring approved these changes
Looks good to me to merge.

Here are various suggestions. Feel free to dismiss them or defer them to another PR.

2022-06-06 20:04 UTC, SyntaxColoring commented on api/docs/v2/new_labware.rst
> +        depth = plate['A1'].depth # 10.67
```suggestion
        depth = plate['A1'].depth  # 10.67
```

Very very pedantic, sorry: two spaces before the `#`, per PEP8.

2022-06-06 20:04 UTC, SyntaxColoring commented on api/docs/v2/new_labware.rst
> +        length = plate['A1'].length	# 8.2
```suggestion
        length = plate['A1'].length  # 8.2
```

2022-06-06 20:04 UTC, SyntaxColoring commented on api/docs/v2/new_labware.rst
> +        width = plate['A1'].width	# 71.2
```suggestion
        width = plate['A1'].width  # 71.2
```

2022-06-06 20:04 UTC, SyntaxColoring commented on api/docs/v2/new_labware.rst
> +Use :py:meth:`.Well.width` to get the width of a given well in mm. Width is defined as the distance along the y-axis (front to back). This method only works with rectangular wells. If the well is not
Feel free to not worry about this for this PR, but:

*  Would it be more succinct to combine `length` and `width` under a single heading, using a single code sample?
* A lot of this (units, axis, what `None` means, validity for circular vs. rectangular wells) feels like usage details that might be better organized under the methods' reference documentation?

2022-06-06 20:04 UTC, SyntaxColoring commented on api/docs/v2/robot_position.rst
> +Robot Position
Would something like `Pipette Positioning` be clearer? I often hear people say say "the position of the robot" or "move the robot," but that's always felt kind of weird to me. It's not like they're picking up the entire OT-2 and moving it somewhere else.

Your call. Feel free to ignore.

2022-06-06 20:04 UTC, SyntaxColoring commented on api/docs/v2/robot_position.rst
> +   plate['A1'].top()     # the top center of the well
```suggestion
   plate['A1'].top()  # the top center of the well
```

2022-06-06 20:04 UTC, SyntaxColoring commented on api/docs/v2/robot_position.rst
> +When instructing the OT-2 to move, it's important to consider the difference between the :py:class:`~opentrons.types.Point` and :py:class:`~opentrons.types.Location` types. Points are ordered tuples
We might want to rewrite this as:

> ``Point(10, 20, 30)``, ``Point(x=10, y=20, z=30)``, and ``Point(z=30, y=20, x=10)`` are all equivalent.

Because just `(x=10, y=20, z=30)` without the word `Point` isn't valid Python syntax.

2022-06-06 20:04 UTC, SyntaxColoring commented on api/docs/v2/robot_position.rst
> +Whenever the OT-2 moves to a particular position, it calculates where to move using its `pipette offset and tip length calibration <https://support.opentrons.com/s/article/Get-started-Calibrate-tip-l
Does the note on pipette offset and tip length calibration belong here? It seems like this section is mostly about how to move the robot *without* having to do something like an `aspirate()` at the same time. But pipette offset and tip length calibration apply to every movement, all the time.

If we want to keep the note on calibration, maybe we can lift it up to its own section where it's clear that it applies to movement in general?

2022-06-06 20:04 UTC, SyntaxColoring commented on api/docs/v2/robot_position.rst
> +Position on the Deck
Should this be `Position Relative to the Deck` for parallelism with the prior `Position Relative to Labware` section?

2022-06-06 20:04 UTC, SyntaxColoring commented on api/docs/v2/robot_position.rst
> +Move To
Would this section on `move_to()` fit better under the "Position on the Deck" section?

So we might have an outline like:

* Position Relative to Labware
    * Top
    * Bottom
    * etc.
* Position Relative to the Deck
    * `move_to()`
* Applying offsets to positions [?]
    * `.move()`
    * Points and Locations
* Movement behavior
    * Calibration [?]
    * Speeds

2022-06-06 20:04 UTC, SyntaxColoring commented on api/docs/v2/robot_position.rst
> +In addition to controlling the overall gantry speed, you can set speed limits for each of the individual  axes: ``x`` (gantry left/right motion), ``y`` (gantry forward/back motion), ``z`` (left pipet
```suggestion
In addition to controlling the overall gantry speed, you can set speed limits for each of the individual  axes: ``x`` (gantry left/right motion), ``y`` (gantry forward/back motion), ``z`` (left pipette up/down motion), and ``a`` (right pipette up/down motion). Unlike ``default_speed``, which is a pipette property, axis speed limits are stored in a protocol property :py:obj:`.ProtocolContext.max_speeds`; therefore the ``x`` and ``y`` values affect all movements by both pipettes. This property works like a dictionary, where the keys are axes, assigning a value to a key sets a max speed, and deleting a key or setting it to ``None`` resets that axis's limit to the default:
```

2022-06-06 20:04 UTC, SyntaxColoring commented on api/docs/v2/robot_position.rst
> +In addition to controlling the overall gantry speed, you can set speed limits for each of the individual  axes: ``x`` (gantry left/right motion), ``y`` (gantry forward/back motion), ``z`` (left pipet
Anecdotally, I've seen people say "the instrument" to refer to the entire OT-2. So when referring to pipettes, I think we should either link to the `InstrumentContext` class, or say "pipette."

(In future Python Protocol API versions, we want to rename `load_instrument()` to `load_pipette()`.)

2022-06-06 20:04 UTC, SyntaxColoring commented on api/docs/v2/robot_position.rst
> +Movement Behavior
The heading "Movement Behavior" seems pretty broad to me. Isn't this entire page about movement behavior, in a sense?

I think if we split these two topics into their own sections:

* Changing speeds
* Moving the robot independently of other actions

We could give them more precise headings and the document outline would feel a bit tighter (to me).

2022-06-06 20:04 UTC, SyntaxColoring commented on api/docs/v2/robot_position.rst
> +Points vs. Locations
Do you think we're presenting too much to quickly here? I believe this is the first time the reader is encountering `Point` and `Location`, and we get right into describing the technical differences between them, and their use in `move()`, before they've seen the motivation.

2022-06-06 20:10 UTC, ecormany commented on api/docs/v2/new_labware.rst
> +        depth = plate['A1'].depth # 10.67
the more you knooow 🌠

2022-06-06 20:12 UTC, ecormany commented on api/docs/v2/new_labware.rst
> +Use :py:meth:`.Well.width` to get the width of a given well in mm. Width is defined as the distance along the y-axis (front to back). This method only works with rectangular wells. If the well is not
I agree this feels reference-y. Will make a note of it for when I do a pass through the reference itself.

2022-06-07 14:04 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +Move To
Good call, I'm adopting a variation of this.

2022-06-07 14:58 UTC, merged