refactor(shared-data): update temperature module schema v6 commands
OpenTrons/opentrons-api pull request #10176
Opened 2022-05-02 18:05 UTC by shlokamin

# Overview

This PR updates JSON schema v6 temperature module commands to match our updated interface. All frontend + backend changes to accommodate the schema change should be made in this PR.

# Changelog

-  Update temperature module schema v6 commands

# Review requests

# Risk assessment
Med

2022-05-09 18:29 UTC, shlokamin commented on step-generation/src/commandCreators/atomic/setTemperature.ts
> +    celsius: targetTemperature,
change this only for temp module, this also affects H-S

2022-05-12 21:58 UTC, sanni-t commented
Python changes LGTM!

2022-05-16 15:41 UTC, sanni-t requested changes
Sorry @jbleon95, noticed these a bit late.
We'll also need to update the name of the `await_temperature` test file and update the file's docstring.

2022-05-16 15:41 UTC, sanni-t commented on api/src/opentrons/protocol_engine/commands/temperature_module/wait_for_temperature.py
>      """A command to set a Temperature Module's target temperature."""
Just noticed this docstring

```suggestion
    """A command to wait for a Temperature Module's target temperature."""
```

2022-05-16 15:41 UTC, sanni-t commented on api/src/opentrons/protocol_engine/commands/temperature_module/wait_for_temperature.py
>      """A request to create a Temperature Module's set temperature command."""
```suggestion
    """A request to create a Temperature Module's wait for temperature command."""
```

2022-05-16 15:41 UTC, sanni-t commented on api/tests/opentrons/protocol_engine/commands/temperature_module/test_deactivate.py
> +    assert result == temperature_module.WaitForTemperatureResult()
Oh boy, this is my bad. I guess the test passed since both deactivate and awaitTemperature results were empty objects. Let's improve that test:
```suggestion
    assert result == temperature_module.DeactivateTemperatureResult()
    assert isinstance(result, temperature_module.DeactivateTemperatureResult)
```

2022-05-16 18:59 UTC, sanni-t approved these changes
🌡 Changes look good!

2022-05-16 20:11 UTC, smb2268 approved these changes

2022-05-16 20:32 UTC, b-cooper approved these changes
🦞

2022-05-16 21:18 UTC, merged