Feature/persist engine state
OpenTrons/opentrons-api pull request #10187
Opened 2022-05-03 14:13 UTC by TamarZanzouri

# Overview

Persisting protocol engine state to the DB on run pause and on run update.

# Changelog

- added to task runner a method that accepts a list of methods.
- moved ProtocolRunData to state.py
- added method get_protocol_run_data to StateView
- insert state into DB on route `/runs/{runId}` update to not current
- insert state into DB on route `/runs/{runId}/actions` when calling `engine_store.runner.run()`

# Review requests

- make sure end points `/runs/{runId}/actions` and `/runs/{runId}` return proper data.
- am I missing any tests?
- is the location for ProtocolRunData correct?
- naming makes sense
- task runner - added a method that accepts a list of functions. Does this look ok? 

# Risk assessment

Medium risk management. Need to make sure the end points are not broken and data is returned as expected.

2022-05-03 20:36 UTC, TamarZanzouri commented on robot-server/robot_server/service/task_runner.py
> +    def run_waterfall(self, func_list: List[TaskFuncAll]) -> None:
does this name make sense? is the implementation correct?

2022-05-03 20:39 UTC, TamarZanzouri commented on robot-server/tests/runs/test_run_state_store.py
> +def run_store(sql_engine_fixture: sqlalchemy.engine.Engine) -> RunStore:
Is this a red flag? we have the subject we are testing against but there is another store I need to insert the data for the sake of testing the other store.

2022-05-03 21:28 UTC, aptrons22 requested changes, later dismissed
Regarding persistence.py file I see references to AppStateValue but that has been modified to AppStateAccessor.  Please see https://github.com/Opentrons/opentrons/pull/10185.

2022-05-05 14:32 UTC, mcous reviewed
Looks like we've got some merge conflicts to sort out, and I'm not sure we've quite nailed down our relationship constraints between the main run resources and the run state resources

2022-05-05 14:32 UTC, mcous commented on api/src/opentrons/protocol_engine/state/protocol_run_data.py
> +"""Protocol run data class for storing protocol engine state."""
I'm never quite sure what to do with these module level docstrings, but I don't think we should use the word "store" here given its implications elsewhere in the codebase and the fact that this is a model for giving something a representation of the run state that is stored elsewhere

```suggestion
"""Public protocol run data models."""
```

2022-05-05 14:32 UTC, mcous commented on api/src/opentrons/protocol_engine/state/state.py
> +    def get_protocol_run_data(self) -> ProtocolRunData:
Do we want a unit test for this method?

2022-05-05 14:32 UTC, mcous commented on robot-server/robot_server/persistence.py
> +from sqlalchemy.engine import Engine as SQLEngine
Looks like some unnecessary changes with imports and import ordering, maybe something pycharm did automatically? Could we revert to reduce PR churn and future conflicts?

2022-05-05 14:32 UTC, mcous commented on robot-server/robot_server/persistence.py
> +    ),
Is there any way we can set up this foreign key constraint to enforce a one-to-zero-or-one relationship here? There should never be two rows in this database with the same `run_id`.

Alternatively, would it be a bad idea to re-use the `run_id` as this table's primary key?

2022-05-05 14:32 UTC, mcous commented on robot-server/robot_server/runs/router/base_router.py
> +        insert_engine_state_result = run_state_store.insert(
Will these leave two rows in the table referring to the same `run_id`? It looks like this sequence of events can happen

```mermaid
sequenceDiagram
    Client->>+Server: "play" run
    Server-->>+Background: Run waterfall
    Server->>-Client: action created
    Background->>+Runner: start run
    Runner->>-Background: run finished
    Background->>+Database: insert run state
    Database->>-Background: row created
    deactivate Background

    Client->>+Server: update run
    Server->>+Database: insert run state
    Database->>-Server: row created
    Server->>-Client: run udpated
```

2022-05-05 14:32 UTC, mcous commented on robot-server/robot_server/runs/router/base_router.py
> +                created_at=None,
Why is `created_at` none here? Sort of feels like the `insert` in this method needs to be an `update`

2022-05-05 14:32 UTC, mcous commented on robot-server/robot_server/runs/router/base_router.py
> +        if insert_engine_state_result is not None
Why would the insert as written ever return `None`?

2022-05-05 14:32 UTC, mcous commented on robot-server/robot_server/service/task_runner.py
> +# TODO (tz, 2022-04-29): Should I declare this or should I make the other method async?
I think the `TaskRunner` should deal exclusively in async commands

2022-05-05 14:32 UTC, mcous commented on robot-server/robot_server/service/task_runner.py
> +    def run_waterfall(self, func_list: List[TaskFuncAll]) -> None:
It doesn't look quite right to me:

- If a function in the waterfall raises an exception, the whole waterfall should fail
- The return values of methods should be typed generically using `TypeVar` or loosely using `any` rather than locked to `str`, nor should the result be marked as `Optional`.

This method is really well suited to verification by unit tests. We should add them

2022-05-05 14:32 UTC, mcous commented on robot-server/tests/runs/test_run_state_store.py
> +def run_store(sql_engine_fixture: sqlalchemy.engine.Engine) -> RunStore:
It's probably ok for now, but I think it's something like the tests telling us that the `RunStore` and the `RunStateStore` are actually part of the same unit. Moving forward, that may mean something like combining them or creating a parent class that is the target of our unit tests

2022-05-05 19:56 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/protocol_run_data.py
> +"""Protocol run data class for storing protocol engine state."""
I like that docstring suggestion.

In addition, my hot take is that if a module contains only one class, like this one does, we should feel free to `# noqa` things so that we only have a docstring on the class *or* the module—not both.

If we have both, they'll certainly be redundant in a way that makes the code harder to understand and maintain.

But this is largely a personal pet peeve, and I also think it's reasonable to want to avoid littering our files with `# noqa` comments, so don't take me too seriously. :)

2022-05-05 19:56 UTC, SyntaxColoring commented on robot-server/robot_server/persistence.py
> +    sqlalchemy.Column("created_at", sqlalchemy.DateTime, nullable=False),
What does `created_at` represent here? Is it ever anything different from the `created_at` of the run itself?

2022-05-05 19:56 UTC, SyntaxColoring commented on robot-server/robot_server/persistence.py
> +    ),
Would it be easier to put these columns in the existing `run` table, instead of this separate `run_state` table?

* The state's `id` column would cease to exist
* The state's `created_at` column would merge with the run's existing `created_at` column. (I think; not sure exactly what `created_at` means here; see my other comment)
* The `state` column would become `nullable=True`
* The `engine_status` column would become `nullable=True`
* We could possibly add something like a `CHECK` constraint to make sure `state` and `engine_status` are either both `NULL` or both non-`NULL`

Not sure what's purer from a DB normalization perspective.

2022-05-05 19:56 UTC, SyntaxColoring commented on robot-server/robot_server/runs/dependencies.py
> +    """Get a singleton EngineStateStore to keep track of created state runs."""
```suggestion
    """Get a singleton RunStateStore to keep track of run states."""
```

2022-05-05 19:56 UTC, SyntaxColoring commented on robot-server/robot_server/service/task_runner.py
> +    def run_waterfall(self, func_list: List[TaskFuncAll]) -> None:
Setting aside for a second the implementation (which is being discussed in [another thread](https://github.com/Opentrons/opentrons/pull/10187/files#r864220811), I'm not a huge fan of this interface.

As written, a caller will do this:

```python
task_runner.run_waterfall(
    [engine_store.runner.run, run_state_store.insert]
)
```

But I think instead, we should make the caller do something like this:

```python
async def run_protocol_and_insert_result():
    run_result = await engine_store.runner.run()
    await run_state_store.insert(run_result)

task_runner.run(run_protocol_and_insert_result)
```

The way I see it, this method, as written, is basically reinventing function composition. `TaskRunner` isn't in a good position to do this, and attempting it brings a number of downsides:

<ul>
<li>
It's unusual code that adds indirection and isn't functionally necessary.

As shown above, when a caller wants to run a waterfall of functions through the `TaskRunner`, it can define its own "super-function" and then run that single super-function through the `TaskRunner`.

As far as I know, the super-function is the standard way of solving this problem. Look at Python's standard `threading` module, for example. It doesn't give you a way to run things in a waterfall; it expects you to do that yourself.
</li>

<li>
We lose meaningful type safety.

For example, mistakes like this should be static type-checking errors:

```python
async def f1() -> int:
    ...

async def f2(arg: str) -> None:
    ...

# Wrong: f1 will return an int but f2 will expect a str.
task_runner.run_waterfall([f1, f2])
```

But as this interface is defined, they can't be, since each element of `func_list` is a `Callable[..., Awaitable[Any]]`—"a coroutine accepting anything and returning anything."

Ideally, we'd want to type each element of `func_list` as "a coroutine accepting whatever the previous coroutine returned and returning whatever the next coroutine accepts." But Python's typing system isn't currently powerful enough to express that. (The language feature that solved this in C++ was [variadic templates](https://en.wikipedia.org/wiki/Variadic_template), which Python is getting [in 3.11](https://peps.python.org/pep-0646).)
</li>

<li>
It's limited in power, compared to the super-function approach.

Suppose the waterfall is like this, where different coroutines take different numbers of arguments:

```python
r1 = await f1()
r2 = await f2()
r3 = await f3(r1, r2)
```

Or suppose the caller wants to mix coroutines and regular functions:

```python
r1 = await f1()
r2 = f2(r1)
r3 = await f3(r2)
```

As written, the interface can't handle either of these, and I don't think it could be easily extended to.
</li>
</ul>


One *upside* to the interface as written is that it gives us something precise-looking to mock:

```python
async def test_create_run_action():
    # ...
    decoy.verify(
        mock_task_runner.run_waterfall(
            [mock_runner.run, mock_run_state_store.insert]
        )
    )
```

But I don't think this is worth the downsides. I think we could just as well go with the super-function approach, and change the test to this:

```python
async def test_create_run_action():
    # ...
    decoy.verify(
        mock_task_runner.run(matchers.Anything())
    )
```

Relying on integration tests to ensure that the "anything" that's being run is correct.

If we really find it important to precisely mock what's being run in the background, I suppose we could also do something like this 3rd option, which a addresses the type-safety and extensibility concerns.

<details>

<summary>3rd option</summary>

```python
class ProtocolBackgroundRunner:  # Not a great name, but you get the idea.
    def start_running_and_insert_when_done(
        task_runner: TaskRunner,
        engine_store: EngineStore,
        run_state_store: RunStateStore,
    ) -> None:
        async def waterfall() -> None:
            run_result = await engine_store.runner.run()
            await run_state_store.insert(run_result)
        task_runner.run(waterfall)
```

```python
async def test_protocol_background_runner():
    subject = ProtocolBackgroundRunner()
    
    # ...
    
    task_runner = TaskRunner()
    mock_engine_store = decoy.mock(cls=EngineStore)
    mock_run_state_store = decoy.mock(cls=RunStateStore)
    
    decoy.when(mock_engine_store.runner.run()).then_return(ProtocolRunData(...))
    
    subject.start_running_and_insert_when_done(
        task_runner, mock_engine_store, run_state_store
    )
    
    # This doesn't exist yet; you'd have to add it.
    # But you'd have to add it to unit-test
    # your task_runner.run_waterfall() method, anyway.
    await task_runner.wait_until_complete()
    
    decoy.verify(run_state_store.insert(ProtocolRunData(...)))
```


```python
@app.post(...)
async def create_run_action(
    task_runner: TaskRunner,
    protocol_background_runner: ProtocolBackgroundRunner,
    engine_store: EngineStore,
    run_state_store: RunStateStore,
    ...
):
    # ...
    
    protocol_background_runner.start_running_and_insert_when_done(
        task_runner, engine_store, run_state_store
    )
    
    # ...
```

```python
async def test_create_run_action():
    mock_task_runner = decoy.mock(cls=TaskRunner)
    mock_runs_protocol_and_inserts_results = decoy.mock(cls=RunsProtocolAndInsertsResults)
    
    # ...
    
    await create_run_action(
        runs_protocol_and_inserts_results=mock_runs_protocol_and_inserts_results,
        ...
    )
    
    decoy.verify(
```

</details>

But that feels like a lot to me.

2022-05-06 13:47 UTC, TamarZanzouri commented on robot-server/tests/runs/test_run_state_store.py
> +def run_store(sql_engine_fixture: sqlalchemy.engine.Engine) -> RunStore:
Yes I agree. This prob means we need to combine them to one store.

2022-05-06 13:54 UTC, TamarZanzouri commented on robot-server/robot_server/persistence.py
> +from sqlalchemy.engine import Engine as SQLEngine
Its from the merge :-) I will fix it!

2022-05-06 14:02 UTC, TamarZanzouri commented on robot-server/robot_server/persistence.py
> +    ),
If its one-to-zero-or-one I think we can merge these 2 tables into the run table. I will solve this.

2022-05-06 14:04 UTC, TamarZanzouri commented on robot-server/robot_server/runs/router/base_router.py
> +        insert_engine_state_result = run_state_store.insert(
Nice drawing! You are right. I should override a run state if it exists. The latest state should be persisted. I will fix it

2022-05-06 14:07 UTC, TamarZanzouri commented on robot-server/robot_server/runs/router/base_router.py
> +        if insert_engine_state_result is not None
its an optional prop that we are setting just in case update.current is False. Look at row 352.

2022-05-06 14:17 UTC, TamarZanzouri commented on robot-server/robot_server/service/task_runner.py
> +    def run_waterfall(self, func_list: List[TaskFuncAll]) -> None:
I agree with @SyntaxColoring. I didn't feel calm about this implementation and wanted to talk about it. There is a lot of room for error here. The way @SyntaxColoring suggested was our first implementation but We changed it to move responsibility to task_runner. I feel like bc this is being used in just one place there is no reason to reinvent the wheel. I will change it to a wrapper method like we first discussed.

2022-05-06 14:28 UTC, TamarZanzouri commented on robot-server/robot_server/persistence.py
> +    sqlalchemy.Column("created_at", sqlalchemy.DateTime, nullable=False),
This represents the time the state was persisted. Its not the same as the run created_at. we persist on 'stop' or un-correct. If we are merging these tables I would still want to know at what time the run was created and at what time the state was persisted. I think its important for investigation purposes.

2022-05-06 17:40 UTC, mcous commented on robot-server/robot_server/persistence.py
> +    sqlalchemy.Column("created_at", sqlalchemy.DateTime, nullable=False),
If that's the case, this name is pretty confusing. I think it should be named something like `_updated_at` or similar to say exactly what it is and also that it's an internal property for debugging purposes

2022-05-06 19:51 UTC, TamarZanzouri commented on robot-server/robot_server/persistence.py
> +    sqlalchemy.Column("created_at", sqlalchemy.DateTime, nullable=False),
I agree :-) changed the name!

2022-05-06 20:07 UTC, TamarZanzouri commented on robot-server/robot_server/runs/router/base_router.py
> +
copied over from branch https://github.com/Opentrons/opentrons/pull/10216/commits/adb77d91fcff80cfed5cc2072a37a104e364c20d as a 500 error patch

2022-05-16 15:42 UTC, mcous reviewed
Initial batch of comments

2022-05-16 15:42 UTC, mcous commented on robot-server/tests/integration/http_api/runs/test_persistence.py
> +    assert get_command_response.json()["data"] == expected_command
Move to tavern test

2022-05-16 15:42 UTC, mcous commented on robot-server/tests/integration/http_api/runs/test_persistence.py
> +    assert get_run_response.json()["data"] == expected_run
Move to tavern

2022-05-16 15:42 UTC, mcous commented on robot-server/tests/integration/http_api/runs/test_protocol_run.tavern.yaml
> +
Add `GET /runs/`, `GET /runs/:run_id`, `GET /commands/:run_id/commands/:command_id`

2022-05-16 15:42 UTC, mcous commented on robot-server/tests/integration/http_api/runs/test_persistence.py
> +        run_id=run_id, req_body={"data": {"current": False}}
Add test that checks persistence from run completion (via play action handler in actions router)

2022-05-16 15:42 UTC, mcous commented on robot-server/tests/integration/http_api/runs/test_persistence.py
> +    assert get_all_persisted_runs_response.json()["data"] == [expected_run]
Add tavern test to check regular POST then GET for labware offests and actions, PATCH uncurrent run, so that we can be confident that this test checks persistence

2022-05-16 15:42 UTC, mcous commented on robot-server/tests/integration/protocols/pickup_return_protocol.py
> +from opentrons.protocol_api import ProtocolContext
No used, can remove

2022-05-16 15:42 UTC, mcous commented on robot-server/robot_server/runs/router/base_router.py
> +    except EngineConflictError as e:
Missing a catch from a `ProtocolNotFoundError` due to an integrity error from the SQL database. Add a TODO to figure out a longer term solution

2022-05-16 15:42 UTC, mcous commented on robot-server/robot_server/runs/router/actions_router.py
> +    received. Depedendents should not assume that condition will necessarily
```suggestion
    received. Dependents should not assume that condition will necessarily
```

2022-05-16 15:42 UTC, mcous commented on robot-server/robot_server/runs/router/labware_router.py
> +from .base_router import RunNotFound, RunNotIdle, get_run_data_from_url, RunStopped
Maybe revert for the diff

2022-05-16 19:30 UTC, SyntaxColoring reviewed
Still working my way through this, but here's a couple of comments so far. Neither require action in this PR.

2022-05-16 19:30 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/protocol_runner.py
> +    data: ProtocolRunData
I think things named `data` can be red flags because of the vagueness; *every* variable is data, in some sense.

Alternatives off the top of my head, if either of these appeal to you:

* `state_snapshot`
* `state_summary`

No pressure to change this right now if neither of these feel especially satisfying.

2022-05-16 19:30 UTC, SyntaxColoring commented on robot-server/tests/runs/test_engine_store.py
> +    with pytest.raises(AssertionError):
No change required for this PR, but I see `with pytest.raises(AssertionError)` as a soft red flag.

In my opinion, there are two mutually-exclusive strategies for this kind of thing:

* The contract of a method is "if you try this invalid thing, we will raise this exception."
    * That error case should be spelled out in the method docstring, and it should be tested.
* The contract of a method is "do not try this invalid thing."
    * What happens if you do try the invalid thing is unspecified. Maybe it will raise a nice exception, or maybe it will raise an ugly exception, or maybe it won't raise anything. Maybe it will leave the data in a valid state, or maybe it will corrupt it.
    * Since the ability to do the invalid thing is not part of the method's public interface, this behavior is *usually* not covered by tests.

(I'm sure I'm stealing this opinion from somewhere, but I can't seem to find a reference. Maybe I did make it up.)

So this suggests to me that either:

* Since we didn't feel this was important enough to give its own exception type, it might also not be important enough to cover in tests.
* Since we did feel this was important enough to cover in tests, it might also be important enough to deserve its own exception type.

Again, though, this is a *soft* red flag. I've definitely written code like this myself, and I think it can be fine. Especially for stuff like: "You should never attempt this and I don't want to specify exactly what happens if you, but I want to make a best effort to raise the error for you, just to be nice."

2022-05-16 21:27 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_store.py
> +                return False
Looks like this `NoResultFound` will never actually be raised.

2022-05-16 21:27 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_data_manager.py
> +        engine_store: In-memory store the current run's ProtocolEngine.
```suggestion
        engine_store: In-memory store of the current run's ProtocolEngine.
```

2022-05-16 21:33 UTC, SyntaxColoring approved these changes
Reviewed in-person with @mcous and @TamarZanzouri. Looks good to me to merge once the CI failures are resolved.

2022-05-16 23:19 UTC, mcous reviewed
Last review batch. Almost entirely docstring stuff. Going to fix and merge

2022-05-16 23:19 UTC, mcous commented on api/src/opentrons/protocol_engine/state/state.py
> +        return StateSummary(
```suggestion
        return StateSummary.construct(
```

2022-05-16 23:19 UTC, mcous commented on robot-server/robot_server/runs/router/base_router.py
> +        raise RunAlreadyActive(detail=str(e)).as_error(status.HTTP_409_CONFLICT)
```suggestion
        raise RunAlreadyActive(detail=str(e)).as_error(status.HTTP_409_CONFLICT) from e
```

2022-05-16 23:19 UTC, mcous commented on robot-server/robot_server/runs/run_controller.py
> +            RunActionNotAllowed: The following operation is not allowed
Correct assertions are raised by method, but docstring is out of date.

```suggestion
            RunActionNotAllowed: The requested action type is not currently allowed
```

2022-05-16 23:19 UTC, mcous commented on robot-server/robot_server/runs/run_data_manager.py
> +    run_data = run_data or StateSummary.construct(
Add a TODO here to figure out a persistence strategy that does not require this default summary object

2022-05-16 23:19 UTC, mcous commented on robot-server/robot_server/runs/run_data_manager.py
> +    async def update(self, run_id: str, current: Optional[Literal[False]]) -> Run:
Revert change from `bool` to `Literal[False]` to avoid breaking change to HTTP API

2022-05-16 23:19 UTC, mcous commented on robot-server/robot_server/runs/run_models.py
> +    current: Optional[Literal[False]] = Field(
Revert

2022-05-16 23:19 UTC, mcous commented on robot-server/robot_server/runs/run_store.py
> +            The run resource.
Add `Raises` section with `RunNotFoundError`

2022-05-16 23:19 UTC, mcous commented on robot-server/robot_server/runs/run_store.py
>          """
Add `Raises` section with `RunNotFoundError`

2022-05-16 23:19 UTC, mcous commented on robot-server/robot_server/runs/run_store.py
>          Arguments:
`Args` section out of date, add `Raises` section with `ProtocolNotFoundError`

2022-05-16 23:19 UTC, mcous commented on robot-server/robot_server/runs/run_store.py
>          """
Add `Raises` section

2022-05-16 23:19 UTC, mcous commented on robot-server/robot_server/runs/run_store.py
> +        Returns:
Add `Raises` section

2022-05-16 23:19 UTC, mcous commented on robot-server/tests/runs/test_run_store.py
> +    "input_cursor, input_length, expected_cursor, expected_length, expected_commands_result",  # noqa: E501
- Prefer collections of strings to single comma-delimited string
- I added the `expected_length` parameter to mean "expected length of the slice" so that we wouldn't need an `expected_commands_result` arg

As written, `expected_length` is redundant. I will probably remove it

2022-05-17 00:24 UTC, mcous commented
- Comments on acceptance tests to be handled in new PR
- Found one raised error that was not caught in the router, fixed
    - Run store could raise `RunNotFoundError` on `insert_action`
- Fixed up some docstrings
- Made `protocol_run_data` > `state_summary` rename changes in more places for consistency

Running final smoke tests, and will merge if CI and those tests pass

2022-05-17 05:13 UTC, merged