feat(ot3, api): Add gripper class
OpenTrons/opentrons-api pull request #10278
Opened 2022-05-12 21:53 UTC by ahiuchingau

# Overview
💥💥💥 New instrument alert: the Gripper has arrived, well, not fully, but we're getting there. 💥💥💥

Note: We previously interchange the words "pipette" and "instrument" for the OT1 & OT2. This should no longer be the case for the OT3. Gripper is a type of instrument that we'll be attaching to the OT3; just like we would a pipette.

# Changelog

# Review requests

# Risk assessment

2022-05-12 21:57 UTC, Laura-Danielle commented
![Alt Text](https://media.giphy.com/media/3o6ZtaQfVwxTH6N692/giphy.gif)

2022-05-13 16:24 UTC, amitlissack reviewed
Just a couple questions.

2022-05-13 16:24 UTC, amitlissack commented on api/src/opentrons/hardware_control/gripper.py
> +        self._log.info("updated config: {}={}".format(elem_name, elem_val))
nit: f-strings vs format

2022-05-13 16:24 UTC, amitlissack commented on api/src/opentrons/hardware_control/gripper.py
> +    def as_dict(self) -> "Gripper.DictType":
Why do we need an `as_dict` method?

2022-05-13 16:24 UTC, amitlissack commented on api/src/opentrons/hardware_control/gripper.py
> +        self._name = self._config.name
If we hold a reference to the config, why do we need to have references to members of the config?

2022-05-13 16:42 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/gripper.py
> +    def as_dict(self) -> "Gripper.DictType":
We probably won't need it, I pretty much copied all of these methods from the Pipette class. I will delete it

2022-05-13 16:44 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/gripper.py
> +        self._name = self._config.name
True, i'll delete them

2022-05-13 16:56 UTC, sfoster1 requested changes
This is an awesome step forward! And a really great way to get started by keeping it small.

Can we add some super basic tests - just checking that config and name information is preserved, and checking the current basic critical point implementation - so we begin as we mean to go on?

2022-05-13 16:56 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instrument_abc.py
> +class AbstractInstrument(ABC):
we probably want name, property, and model and so on, right?

2022-05-17 13:40 UTC, sfoster1 approved these changes
Nice, love it.

2022-05-17 17:23 UTC, merged