feat(heater-shaker): add firmware upload capability
OpenTrons/opentrons-api pull request #10307
Opened 2022-05-17 00:02 UTC by pmoegenburg

Updated upload_via_dfu method, which uses the dfu-util tool.

Also updated find_bootloader_port for stm32 modules, which appear as `STM32 BOOTLOADER` once bootloader is entered.

Resolves #9634

2022-05-17 13:01 UTC, sfoster1 requested changes
Couple things I think we should change, but nice!

2022-05-17 13:01 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/update.py
> +async def find_bootloader_port(stm32_module: bool) -> str:
I don't think the changes to this function are necessary. What we have to do is make the STM32 bootloader be symlinked to `/dev/ot_module_heatershaker_bootloader` or whatever (which it [should be](https://github.com/Opentrons/buildroot/blob/8f7996885677e9e8a6db46607eb53fe1d4e56d57/board/opentrons/ot2/rootfs-overlay/etc/udev/rules.d/95-opentrons-modules.rules#L9), and if that's not working we should debug why) and then the same glob works here

2022-05-17 13:01 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/update.py
> +    """Run firmware upload command for heater/shaker.
nit: this will also be used for TC gen2; let's make the comment a more generic "Run firmware upload command for DFU" or something

2022-05-17 13:01 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/update.py
> +    # dfu-util -a 0 -s 0x08000000:leave --dfuse-address 0x08000000
leftover comment? should remove

2022-05-17 13:01 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/update.py
> +    if "File downloaded successfully" in res:
before committing to examining stdout again (I really hate that we have to do this in other places) can we see if `dfu-util` does the thing it _should_ do and sets a return code if it fails? Should be able to check by forcing a failure on linux and then doing [`echo $?`](https://tldp.org/LDP/abs/html/exit-status.html) in the shell right after the command finishes should tell you something non-zero.

2022-05-17 13:01 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/update.py
> +        log.error(f"Failed to update module firmware for {port}: {res}")
please make these just one log statement - if these get parsed by an automated tool, it's better to have a single really long logline than two shorter ones that have to be associated

2022-05-25 18:25 UTC, sfoster1 approved these changes
Looks good to me!

2022-06-10 10:59 UTC, laviera approved these changes

2022-07-12 17:05 UTC, sanni-t commented
Adding info for testing:

1. Grab the latest ot2_system build file associated with https://github.com/Opentrons/buildroot/pull/159 and upload it to the robot.
2. Push this branch to the robot
3. Download the latest firmware zip, extract files. Rename the `.bin` file to `heater-shaker@v0.4.6.bin` and scp it onto the robot's `/usr/lib/firmware/` directory.
4. Restart the robot-server
5. With the heater-shaker connected to the robot, open the app and go to devices->your robot -> pipettes & modules. The heater-shaker entry should say 'firmware update available'. Click on it! 
The update should complete within a minute.

2022-07-14 19:04 UTC, pmoegenburg commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +        await self._poller.stop_and_wait()      # Check if this is really needed
I think it's a good idea to stop sending get_temp/rpm/latch_status messages (via poller) before sending the dfu gcode

2022-07-15 04:40 UTC, pmoegenburg commented on api/src/opentrons/hardware_control/modules/update.py
> +            # This probably needs to be refactored into just a check for empty stdout
shouldn't we check for stderr?

2022-07-15 04:45 UTC, pmoegenburg commented on api/src/opentrons/hardware_control/modules/update.py
> +    # both of them in quick succession. It's a rare case but has happened before.
I think the device serial will change after entering bootloader, making it difficult to check for a specific module. I added a check for multiple bootloader devices (1 module lists 2 devices, so check is for greater than 2 devices). Since `find_dfu_device` checks only for devices in the bootloader state, shouldn't it be rare (or can we make it impossible) for multiple modules to update firmware concurrently?

2022-07-18 13:35 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/update.py
> +    # both of them in quick succession. It's a rare case but has happened before.
definitely a "make it impossible" sort of thing, yeah. could put a lock in the module manager

2022-07-18 14:58 UTC, sanni-t commented on api/src/opentrons/hardware_control/modules/update.py
> +            # This probably needs to be refactored into just a check for empty stdout
You're right. We want to retry only if there is no output and no error.
I don't remember why I wanted to refactor this so we can tag that comment for removal if we don't run into any problems during testing.

2022-07-18 15:07 UTC, sanni-t commented on api/src/opentrons/hardware_control/modules/update.py
> +    # both of them in quick succession. It's a rare case but has happened before.
@pmoegenburg yes, it's rare, but has happened before where an update was initiated on both temp and mag modules in quick succession and that resulted in the mag module getting the temp module's firmware and vice versa. It happened because they both had the same bootloader identity.

@sfoster1 will the lock prevent the firmware from going to the wrong module's bootloader? Or will Peter's check for 2+ DFUs alongwith the lock make it impossible for two modules to switch to the bootloader at the same time?

2022-07-19 13:46 UTC, laviera commented on api/src/opentrons/hardware_control/modules/update.py
> +    # both of them in quick succession. It's a rare case but has happened before.
@pmoegenburg @sfoster1 - The need to close out firmware update for our internal testing (and production build 7/25) is imminent.   Do we know when this will be complete ?

2022-07-20 15:52 UTC, pmoegenburg commented on api/src/opentrons/hardware_control/modules/update.py
> +    # both of them in quick succession. It's a rare case but has happened before.
@sfoster1 what would that lock look like?

2022-07-21 19:47 UTC, sanni-t commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +        await self._poller.stop_and_wait()      # Check if this is really needed
Oh absolutely. I just meant that it might not be required because the poller *might* be implicitly getting stopped because of the module connection closing. But we need to check that definitely happens in order to remove this.

2022-07-22 20:47 UTC, sfoster1 approved these changes
Awesome, looks great to me if it works!

2022-07-26 00:11 UTC, sanni-t approved these changes
Tested and it works!
We should still add unit tests for `send_dfu_command` but I'm fine leaving a TODO for it and adding it later so we can start using the upload feature. Another todo would be to test if the upload lock works by trying to update two heater-shakers at once.

PR is good to merge once the outdated inline comments are removed!

2022-07-27 04:33 UTC, merged