robot-server (feature): added run completed_at timestamp
OpenTrons/opentrons-api pull request #10327
Opened 2022-05-18 16:42 UTC by TamarZanzouri

# Overview

# Changelog

# Review requests

# Risk assessment

2022-05-18 20:50 UTC, mcous reviewed
Answer to the question in your TODO. Looking pretty good!

2022-05-18 20:50 UTC, mcous commented on api/src/opentrons/protocol_engine/state/commands.py
> +            self._state.run_completed_at = self._module_utils.get_timestamp()
These state stores are a loose form of log-based architecture, and as such we want state to purely be a function of the set of actions that have occurred. This pays huge dividends in terms of testability and, by extension, reliability.

As such, generating "random" values in action handlers (reducers, in Redux parlance) should be strictly avoided. The [Redux docs](https://redux.js.org/style-guide/#reducers-must-not-have-side-effects) have some good thoughts on this.

What does that mean for us here? It means the `completed_at` generation **should be a part of the action payload**. That way, the action handler's job becomes simply to pull the timestamp out of the payload and place it in state.

This also answers your above TODO about injecting `ModelUtils`: the state stores should not use `ModelUtils` in any way. Instead:

1. The `ProtocolEngine` instances calls `self._module_utils.get_timestamp()`
2. It takes that result timestamp and places it in the payload of the `HardwareStoppedAction`

2022-05-26 13:51 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/actions/actions.py
> +    completed_at: datetime
this can also be set through the constructor but I noticed we dont do it as much so I a, leaving initialization outside from the constructor

2022-05-26 22:32 UTC, mcous requested changes

2022-05-26 22:32 UTC, mcous commented on api/src/opentrons/protocol_engine/state/commands.py
> +    """The time the run has started.
```suggestion
    """The time the run was started.
```

2022-05-26 22:32 UTC, mcous commented on api/src/opentrons/protocol_engine/state/commands.py
> +    initialized when PlayAction is dispatched.
```suggestion
    Set when the first `PlayAction` is dispatched.
```

2022-05-26 22:32 UTC, mcous commented on api/src/opentrons/protocol_engine/state/commands.py
> +            self._state.run_started_at = action.started_at
Since a `PlayAction` may be issued multiple times (for both start and resume), `self._state.run_started_at` should not be overwritten if it's already set. This also needs to be inside the `if not self._state.run_result` block

2022-05-26 22:32 UTC, mcous commented on api/tests/opentrons/protocol_engine/actions/test_action_dispatcher.py
> +    action = PlayAction(started_at=datetime(year=2021, month=1, day=1))
Since the action type doesn't matter for this test, it might be easier to swap `PlayAction` here for something that doesn't take parameters, like `StopAction`

2022-05-26 22:32 UTC, mcous commented on api/src/opentrons/protocol_engine/actions/actions.py
> +    started_at: datetime
`started_at` might not be the best name here, since `PlayAction` can mean both start and resume. Maybe `requested_at`?

2022-05-26 22:32 UTC, mcous commented on api/src/opentrons/protocol_engine/state/commands.py
> +    initialized when HardwareStoppedAction is dispatched.
```suggestion
    """The time the run completed.

    Set when a `HardwareStoppedAction` is dispatched.
```

2022-05-26 22:32 UTC, mcous commented on api/tests/opentrons/protocol_engine/state/test_command_store.py
> +    subject.handle_action(PlayAction(started_at=datetime(year=2021, month=1, day=1)))
This test doesn't quite make sense, given #10409. I would remove the `PauseAction` from this test

2022-05-26 22:32 UTC, mcous commented on api/tests/opentrons/protocol_engine/state/test_command_store.py
> +    subject.handle_action(PlayAction(started_at=datetime(year=2021, month=1, day=1)))
This test data datetime value is hiding a bug. The datetime in this action should be different than the first datetime, and the original `started_at` should not be overwritten

2022-05-26 22:32 UTC, mcous commented on api/tests/opentrons/protocol_engine/state/test_command_store.py
> +    subject.handle_action(HardwareStoppedAction(completed_at=date))
These two actions should not use the same date value; it does not sufficiently test the functionality. For example, if `PlayAction` erroneously set both `run_started_at` and `run_completed_at`, this test would still pass

2022-05-26 22:32 UTC, mcous commented on api/tests/opentrons/protocol_engine/state/test_command_store.py
> +def test_command_store_save_started_completed_run_timestamp() -> None:
I think this test would be a little bit better if it issued five actions, all with different timestamps:

```py
PlayAction(datetime_1)
PauseAction(datetime_2)
PlayAction(datetime_3)
HardwareStoppedAction(datetime_4)
PlayAction(datetime_5)
```

Then, our expectation would check that `run_started_at == datetime_1` and `run_completed_at == datetime_4`. The other three datetimes should not show up in the result data. The run_result should still be `STOPPED`

2022-05-26 22:32 UTC, mcous commented on api/tests/opentrons/protocol_engine/test_plugins.py
> +    action = PlayAction(started_at=datetime(year=2021, month=1, day=1))
Same comment as above, since the action type doesn't matter here, use a simpler action as test data

2022-05-26 22:32 UTC, mcous commented on api/tests/opentrons/protocol_engine/test_protocol_engine.py
> +            HardwareStoppedAction(completed_at=datetime(2021, 1, 1, 0, 0))
You should not re-use this datetime here; it's being used for the `FinishErrorDetails` expectation. Instead, configure `get_timestamp` to return multiple timestamps. The first call to the dependency will get the first stubbed return value, the second call will get the second value, etc.

```py
decoy.when(model_utils.get_timestamp()).then_return(
    datetime(year=2021, month=1, day=1),
    datetime(year=2022, month=2, day=2),
)

# ...
decoy.verify(
    # ...
    action_dispatcher.dispatch(
        HardwareStoppedAction(
            completed_at=datetime(year=2022, month=2, day=2)
        )
    )
)
```

https://mike.cousins.io/decoy/api/#decoy.Stub.then_return

2022-05-26 22:32 UTC, mcous commented on robot-server/tests/integration/http_api/runs/test_persistence.py
> +    await anyio.sleep(5.0)
5 seconds is a _very_ long time to sleep in a test. Copy the block from line 147 to wait only as long as needed

2022-05-26 22:32 UTC, mcous commented on robot-server/tests/integration/http_api/runs/test_persistence.py
> +    date_of_today = datetime.now().date()
If we're trying to test that `startedAt` and `completedAt` are reasonable values, I don't think checking that the calendar date is correct is sufficient. Suggestions below

2022-05-26 22:32 UTC, mcous commented on robot-server/tests/integration/http_api/runs/test_persistence.py
> +    )
```suggestion
    # persist the run by hitting the actions router
    expected_started_at = datetime.now()
    await client.post_run_action(
        run_id=run_id,
        req_body={"data": {"actionType": "play"}},
    )

    # persist the run by hitting the actions router
    expected_completed_at = datetime.now()
    await client.post_run_action(
        run_id=run_id,
        req_body={"data": {"actionType": "stop"}},
    )
```

2022-05-26 22:32 UTC, mcous commented on robot-server/tests/integration/http_api/runs/test_persistence.py
> +    assert expected_run["startedAt"] != expected_run["completedAt"]
```suggestion
    run_data = get_run_response.json()["data"]

    assert (
        datetime.fromisoformat(run_data["startedAt"]).timestamp()
        == pytest.approx(expected_started_at.timestamp(), abs=2)
    )

    assert (
        datetime.fromisoformat(run_data["completedAt"]).timestamp()
        == pytest.approx(expected_completed_at.timestamp(), abs=2)
    )


    # make sure the times are in order
    assert run_data["startedAt"] < run_data["completedAt"]
```

2022-05-26 22:32 UTC, mcous commented on robot-server/tests/integration/http_api/runs/test_persistence.py
> +    expected_run = dict(get_run_response.json()["data"], current=False)
```suggestion
    run_data = get_run_response.json()["data"]
```

2022-05-26 22:32 UTC, mcous commented on robot-server/tests/integration/http_api/runs/test_persistence.py
> +    are persisted through dev server restart."""
Try to keep docstrings of the format:

```py
"""One single line ending in a period."""

# or, if you need more text

"""One single line ending in a period.

One or more paragraphs, if you need them.
"""
```

Normally the linter will yell at us for this, but this particular directory has docstring linting disabled because it's got too much old code that doesn't adhere to this style convention.

2022-05-27 18:24 UTC, mcous commented on api/tests/opentrons/protocol_engine/state/test_command_store.py
> +    start_time = datetime.now()
I think we should prefer constructing specific datetimes to `datetime.now()`. It ensures that tests are completely deterministic

2022-05-27 18:24 UTC, mcous commented on api/tests/opentrons/protocol_engine/state/test_command_store.py
> +    second_resume_time = datetime.now()
Same comment as above. In addition introducing randomness of input data into the test, which makes assertion failures harder to read when it happens, the accuracy of the test depends on two subsequent calls to `datetime.now()` returning different datetimes.

We should construct distinct values ourselves to ensure the test is giving us the value we need.

```suggestion
    start_time = datetime(year=2021, month=1, day=1)
    hardware_stopped_time = datetime(year=2022, month=2, day=2)
    resume_time = datetime(year=2023, month=3, day=3)
    second_resume_time = datetime(year=2024, month=4, day=4)
```

2022-05-27 18:24 UTC, mcous commented on api/tests/opentrons/protocol_engine/state/test_command_store.py
> +    resume_start_time = datetime.now()
Avoid `datetime.now()` as input data in unit tests

2022-05-27 18:24 UTC, mcous commented on robot-server/tests/integration/http_api/runs/test_persistence.py
> +    expected_started_at = datetime.now()
Just to be explicit about it and contrast the purpose of acceptance tests and unit tests, in this acceptance test `datetime.now()` is exactly what we want!

2022-05-31 16:28 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/test_protocol_engine.py
> +            HardwareStoppedAction(completed_at=datetime(2021, 1, 1, 0, 0))
Very nice catch! Thank you!

2022-05-31 16:43 UTC, mcous approved these changes
🕐 🚀

2022-05-31 18:46 UTC, merged

2022-05-31 19:14 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/runs/test_persistence.py
> +
What's the intent of this change? I don't fully understand our run persistence, but from this test's docstring, it sounds like a run is supposed to be persisted as soon as the play action is received. With this change, we're only testing that the run is persisted by the time it completes.

2022-05-31 19:14 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/runs/test_persistence.py
> +    )
Is this the same test responsibility thing that we tried to rework in #10323? It seems like we're testing timestamp logic here, not persistence logic.

In other words, we already have tests in this file that make sure the "whole run resource" persisted—regardless of what's included in the "whole run resource". And then we have other tests, like the Tavern ones, that make sure that the run resource contains semantically correct data. So should this timestamp check be moved out of this file?

2022-05-31 19:14 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_models.py
> +    )
This would be a good place to be more specific about what we mean by "completed" and "started."

Something like:

> `startedAt`:
> When the first `play` action was issued to this run, if ever.


> `completedAt`:
>
> When this run completed, if ever.
>
> This applies both to runs that finish successfully on their own and runs that encounter a fatal error.
> 
> The completion time is roughly when the hardware stops moving. But the exact details of this, such as whether it includes the automatic home at the end of a protocol, are not guaranteed and you should not rely on them.

2022-05-31 19:24 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/runs/test_persistence.py
> +
[Discussed in person] Nope, my understanding was wrong! The intent of our code today is to persist a run when it completes—either on its own, or by an HTTP action. We do *not* persist on the action itself.

This change fixes a race condition in the `status` field: finishing vs. finished.

I think I was just getting confused by the test name.

2022-05-31 19:24 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/runs/test_persistence.py
> +    )
[Discussed in person]

Yep, there's a little bit of test organization/redundancy stuff here. We can work on it later.