feat(ot3-hardware): support tip action requests in the move group runner
OpenTrons/opentrons-api pull request #10445
Opened 2022-05-25 15:30 UTC by Laura-Danielle

# Overview

Related to #RET-916 and #RET-918.

Adds in TipActionRequest and TipActionResponse to the move group
runner as well as a script to test pick up and drop tip behavior on the 96 channel. For now, holding
off on adding this to the hardware controller until behavior is finalized around using the tip sense
detection.

# Changelog

- Handle tip action request and response in the move group runner
- Add a script for testing pick up and drop tip

# Review requests

- How do we feel about using the tip sense as a a method for detecting whether a move was successful or not? Should that be a higher level error, or is it fine as it is?

# Risk assessment

Low.

2022-05-25 17:36 UTC, sfoster1 reviewed
Is the intent that the firmware will be using the tip-detect switch to actively stop motion, like it moves until the switch changes; or is it that after doing some precalculated motion, the firmware double-checks that the state of the switch is what it expects?

if we're using the switch state to immediately stop motion, I think this is fine; if we're checking it after the fact, I think this isn't how we should do it.

2022-05-25 17:42 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +        elif isinstance(message, TipActionResponse):
time to factor this out into a subfunction, I think - or make tip actions be responded to with a normal move complete message

2022-05-25 17:42 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +            seq_id = message.payload.seq_id.value
need these to be removed from `self._moves` and dropped into `self._completion_queue` probably right

2022-05-25 17:42 UTC, sfoster1 commented on hardware/opentrons_hardware/scripts/high_throughput_tip_handling.py
> +    pipette_type = input("Please list pipette mount (right or left)")
this can only get attached to the right-side mount, correct?

2022-05-25 17:42 UTC, sfoster1 commented on hardware/opentrons_hardware/scripts/high_throughput_tip_handling.py
> +    os.system("cls")
This makes me twitch. Can we not do these two lines, and especially not with `os.system`. If you really want to do deep control of the terminal, use `termios`, and if you don't want to use `termios`, then just roll with whatever the state of the terminal is. This is like pulling out a flamethrower to clean a shoe you got a small dab of mud on

2022-05-25 17:43 UTC, sfoster1 requested changes
Some little stuff we should probably change/improve. Agreed and cool with this implementation if we're using the tip switch to stop movement in a closed loop, but if we're doing prebaked motions and checking the switch afterwards we shouldn't reuse the ack id.

2022-05-25 20:30 UTC, Laura-Danielle commented on hardware/opentrons_hardware/scripts/high_throughput_tip_handling.py
> +    pipette_type = input("Please list pipette mount (right or left)")
That is true. I'll change it.

2022-06-01 14:32 UTC, sfoster1 approved these changes
Looks good, though I think unless you're going to go full TUI and use curses or an actual support package it's better to keep terminal output just dead simple

2022-06-01 14:32 UTC, sfoster1 commented on hardware/opentrons_hardware/scripts/high_throughput_tip_handling.py
> +    return f"\033[92m{str(s)}\033[0m"
Can we not do the raw terminal escapes like this? Drop em in a file level constant or something or as a function or use a package that provides them like colorama or anything

2022-06-01 16:06 UTC, merged