refactor(app): add functionality to Update robot software menu item
OpenTrons/opentrons-api pull request #10546
Opened 2022-05-31 18:35 UTC by jerader

closes #10479

# Overview

This PR adds functionality to the `Update robot software` button in the robot overview overflow menu. It appears only when an update is available.

# Changelog

- edit `robotOverviewOverflowMenu`

# Review requests

- if an update is available, you should be able to see the `Update robot software` button. Clicking on it will launch the Robot software update modal
- if an update is not available, the button menu item will not be there.

# Risk assessment

low

2022-05-31 22:06 UTC, b-cooper requested changes
The logic looks great.  One change that needs to be made is the software update modal component.  The callback and component launched here is the newly-designed/half-implemented modal that we are punting on finishing for 6.0.  This button needs to launch the old update flow as the other robot update callbacks do.

2022-05-31 22:07 UTC, b-cooper commented on app/src/organisms/Devices/RobotOverviewOverflowMenu.tsx
> +  const handleLaunchModal: React.MouseEventHandler = e => {
Can this function be named a little more specifically?  e.g.  `handleClickUpdateRobot`

2022-06-01 12:20 UTC, jerader commented
> The logic looks great. One change that needs to be made is the software update modal component. The callback and component launched here is the newly-designed/half-implemented modal that we are punting on finishing for 6.0. This button needs to launch the old update flow as the other robot update callbacks do.

@b-cooper , which modal is the correct one for the button to launch? Is it `ViewUpdateModal`?

2022-06-02 14:52 UTC, b-cooper approved these changes
Looks good 👍 , thanks for the updates

2022-06-02 14:57 UTC, merged