fix(update-server): Keep name deconflicted with other devices on the network
OpenTrons/opentrons-api pull request #10559
Opened 2022-06-01 13:03 UTC by SyntaxColoring

# Overview

Fixes #10126.

# Changelog

* Expand our code for communicating with the Avahi daemon over D-Bus, to give us the ability to detect when the Avahi service name has collided with another device on the network.
* While `update-server` is running, constantly monitor Avahi for name collisions. When one happens, automatically set a new name, like `My Robot #2`. This is the addition that fixes #10126.
* At all times, keep the machine's 3 human-readable names in sync with each other:
  * The Avahi service name, which Avahi advertises over mDNS + DNS-SD.
  * The name that `update-server` exposes over HTTP via `GET /server/name`, `POST /server/name`, and `GET /server/update`.
  * The *pretty* hostname, which is read [outside of `update-server`](https://github.com/Opentrons/opentrons/blob/8fc1c0c95b38f10eeb3daa1c10bfd07d29782e22/api/src/opentrons/config/__init__.py#L102-L106) and [winds up in `robot-server`'s `/health`endpoint](https://github.com/Opentrons/opentrons/blob/40bc918b82b4de561f8d092708a84966196d21bd/robot-server/robot_server/health/router.py#L39).
  
  All 3 of these names are  used by the discovery client. Keeping them in sync with each other is important to avoid confusing the discovery client, in its current implementation. See #10199.

* The *static*  hostname is unaffected by this PR. It continues to follow the robot's serial number.

# Reviewing

## Recommended code review order

Here is one way to ease into this PR. Working from the outside in:

1. In `name_management/__init__.py`...
    1. Check out the docstring to familiarize yourself with some important terminology.
    2. Check out how the HTTP endpoint functions `set_name_endpoint()` and `get_name_endpoint()` changed.
2. In `name_managemement/name_synchronizer.py`, check out the `NameSynchronizer` interface, which the endpoints now use, and its `RealNameSynchronizer` implementation.
3. In `name_management/avahi.py`, check out `AvahiClient`, a dependency of `NameSynchronizer`.
4. Check out the server initialization code in `buildroot/__main__.py` and `buildroot/__init__.py`. Note that this is heavily duplicated with `openembedded/__main__.py` and `openembedded/__init__.py`.
5. Everything else.

## Testing

### What to test

We need to verify the following properties:

* The robot's DNS-SD instance name is always the same as the name accessible over HTTP.
    * Caveat: The name in `GET /health` may lag behind the one in `GET /server/update/health` sometimes, because of a different bug. See https://github.com/Opentrons/opentrons/issues/10413.
* The name automatically changes to deconflict with other devices on the network

### How to test it

This needs at least one real OT-2.

On macOS, you can synthesize fake devices on the network to create collisions by running:

```bash
dns-sd -R 'My Fake Robot Name' _http._tcp . 31950
```

From there, there are many ways to inspect the OT2s' names:

* You can simply play around on the Opentrons App. You might want to dig into the app's network settings to clear the robot discovery cache to make things cleaner and make it easier to notice anomalies.
* You can use the macOS `dns-sd -B` command to monitor just the DNS-SD instance names. (Pay attention to the `add`/`remove` column!)
* You can use Postman or `curl` to directly check `GET /health`, `GET /server/health`, and `GET /server/name`.
* You can use the Opentrons discovery client command-line interface (`cd discovery-client && yarn run discovery`).
* The macOS `dns-sd -B` command. 

Interesting scenarios to try out:

* Two machines are both online and have different names. You change one of their names so that they match. One of them should notice the conflict and correct it.
* Two machines are both *offline* and have the *same* name. You turn both of them on. One of them should notice the conflict and correct it.
* You give *three* machines the same name. You should see something like `MyRobot`, `MyRobot #2`, and `MyRobot #3`.
* You have one OT-2 connected to your computer over both a wired and wireless connection. It should not conflict with itself or change its name on its own.

## After testing

When you want to go back to `edge` after testing this PR, **do not do `git switch edge && make -C update-server push`.** It will soft-brick your robot because of https://github.com/Opentrons/opentrons/issues/10582. Instead, download an `edge` build of `ot2-system.zip` and push it through the Opentrons App.

# Risk assessment

High.

* Screwing stuff up in this part of the codebase can soft-brick the robot by crashing `update-server`.
* Screwing stuff up in this part of the codebase can soft-brick the robot by by accidentally breaking some nuance of robot discovery.
* This part of the codebase has spotty type-checking and unit testing coverage.
* We're handling interactions with system processes that we don't own and that we can only test manually.

2022-06-01 13:29 UTC, sfoster1 reviewed
won't do a real review since it's in draft but looks great!

2022-06-01 14:08 UTC, TamarZanzouri commented on update-server/otupdate/common/name_management/name_manager.py
> +class NameManager(ABC):
change name to `NameCollisionResolver` or `NameResolver` @jbleon95

2022-06-01 14:29 UTC, SyntaxColoring commented on update-server/otupdate/common/name_management/name_manager.py
> +class NameManager(ABC):
The word "resolve" already means something different in mDNS/DNS-SD land, unfortunately.

Other ideas:

* `NameCollisionFixer`
* `NameSynchronizer` (it keeps the Avahi service name, the HTTP name, and the pretty hostname in sync)

2022-06-02 04:02 UTC, SyntaxColoring commented on update-server/otupdate/common/name_management/name_synchronizer.py
> +class RealNameSynchronizer(NameSynchronizer):
This `RealNameSynchronizer` class is **not covered by unit tests,** which is a big problem considering it's the most important part of this fix.
  
It *is* designed to be easily testable. But I got stuck because `update-server` has neither [Decoy](https://mike.cousins.io/decoy) nor [`AsyncMock`](https://docs.python.org/dev/library/unittest.mock.html#unittest.mock.AsyncMock). We'd have to resort to some [pretty gnarly tricks](https://stackoverflow.com/questions/32480108/mocking-async-call-in-python-3-5?) to cover it with plain old `MagicMock`.
  
  How and when do we want to resolve this?

2022-06-02 04:02 UTC, SyntaxColoring commented on update-server/otupdate/common/name_management/name_synchronizer.py
> +    """
If we keep the way I've deleted `tests/buildroot/test_name_endpoints.py` and rewritten it as `tests/common/name_management/test_http_endpoints.py`, I think this `FakeNameSynchronizer` class is only used for two things now:

1. `tests/buildroot/test_control.py::test_health` and `tests/openembedded/test_control.py::test_health` spin up a server with an overridden name. Then, they make sure that the `/server/health` endpoint contains that same expected name string.
2. Many other tests that use `test_cli` to spin up a server are implicitly relying on the fact that the server startup code sets up a `FakeNameSynchronizer`, even if they don't care about names whatsoever.

  When they start the server up with a `FakeNameSynchronizer`, it means they're *not* starting it up with a `RealNameSynchronizer`, which means they're *not* trying to access `dbus` or Avahi.
  
  If the startup code did set up a `RealNameSynchronizer`, we'd get `dbus` import errors, or the tests would actually connect to the host's Avahi daemon if it happens to have one. So `FakeNameSynchronizer` is sort of acting as a placeholder to not run startup code that can't run in our test environments.

I suppose the central questions here are:

* Do we think there is a place for these integrationey tests in `update-server`, where they spin up a full server process, given the fact that the full server process normally does things that only make sense on an actual OT-2?
* If yes, how should we handle things like `NameSynchronizer`, which are long-running handles to resources that we can only use on actual OT-2s? Should it be an error if a test tries to access *anything* through them (make `get_name()` a `NotImplementedError` in this example)? Or should we go the other way and simulate them as faithfully as we can (implement `set_name()` in this example)?

2022-06-02 04:02 UTC, SyntaxColoring commented on update-server/otupdate/buildroot/__init__.py
> +    async def set_up_and_tear_down(app: web.Application) -> AsyncGenerator[None, None]:
`set_up_and_tear_down()` is an:

* `async`
* `contextlib.contextmanager`-like generator
*  closure

...which is like three different kinds of unreadable. 👍 

I was trying to avoid dredging open a rabbithole of `aiohttp` async resource management, but it definitely backfired and made things more confusing.

The story here is that a `NameSynchronizer` is a resource that needs cleanup, and that cleanup should happen when the server shuts down. Which is a totally solvable problem. There are several ways of doing it:

* Tie the `NameSynchronizer` to the lifetime of the `aiohttp.Application` with [`cleanup_ctx`](https://docs.aiohttp.org/en/stable/web_advanced.html#cleanup-context). This is what I'm doing here. There might be cleaner ways of doing it, though.
* Tie the `NameSynchronizer` to the lifetime of the `aiohttp.Application` with [`on_startup`/`on_cleanup`](https://docs.aiohttp.org/en/stable/web_advanced.html#signals).
    * Strictly worse than `cleanup_ctx`, in my opinon.
* Tie the `NameSynchronizer` to the lifetime of the *process,* in `main()` instead of `get_app()`, "outside" of the `aiohttp.Application` instead of "inside" it. Since `NameSynchronizer` is async, I think we'd replace `aiohttp.web.run_app()` in `main()` with an [`aiohttp.web.ApplicationRunner`](https://docs.aiohttp.org/en/stable/web_advanced.html#application-runners).

In the short term, maybe the move for this PR is to *not* clean up the `NameSynchronizer` on server shutdown, to avoid trying to solve too much in this PR. And just tolerate the "task not awaited" warning for now.

2022-06-02 15:56 UTC, SyntaxColoring commented on update-server/otupdate/common/name_management/name_synchronizer.py
> +        await self.set_name(new_name=alternative_name)
Note that because the new name contains the "special" characters of ` ` (space) and `#`, it technically counts as "dangerous" because of https://github.com/Opentrons/opentrons/issues/10197.

Thankfully, this appears to not cause any problems in practice. And I think this is the best option we have at the moment, especially since it will be moot when #10197 is fixed.

The alternative would be to do our own implementation of `alternative_service_name()` to avoid the "dangerous" characters, but that would bring its own edge cases that I think are worse.

Specifically:

* Appending `#2` to names that are already close to the 63-octet limit
    * Dropping characters to fit in the octet limit without splitting Unicode code points or [modifier sequences](https://unicode.org/emoji/charts/full-emoji-modifiers.html)
* Incrementing properly after doing `#2` (i.e. `#3`, not `#2 #2`)

2022-06-02 16:40 UTC, X-sam commented on update-server/otupdate/buildroot/__init__.py
> +    async def set_up_and_tear_down(app: web.Application) -> AsyncGenerator[None, None]:
I'd really also advocate for atomicity in PRs here- breaking out the cleanup is gonna help make it clearer whats happening if anyone has to figure out why something is the way it is (e.g. via `git blame` in 5-6 years) or if god forbid something goes wrong and we need to walk it back.

2022-06-02 16:53 UTC, X-sam commented on update-server/otupdate/common/name_management/avahi.py
> +        avahi_entry_group_collision = dbus.Int32(3)
nit: should we break this out into a constant so we're not using an inline'd magic number? Even with the comment right there, it feels a _little_ icky...

2022-06-02 19:15 UTC, sotaoverride approved these changes
Mostly looked at parts of the filesystem being used/written to for such name management. should work with the new filesystem overlays I'm setting up for ot3.

2022-06-02 19:21 UTC, SyntaxColoring commented on update-server/otupdate/common/name_management/avahi.py
> +        avahi_entry_group_collision = dbus.Int32(3)
Yeah, maybe. I'm down for whatever y'all prefer. I put it here because it's only used by this method and it's hard to understand what it's for without this surrounding context.

2022-06-02 20:38 UTC, SyntaxColoring commented on update-server/otupdate/buildroot/__init__.py
> +    async def set_up_and_tear_down(app: web.Application) -> AsyncGenerator[None, None]:
Yep. Will cut this down.

2022-06-02 21:33 UTC, mcous reviewed
Testing / organization thoughts! Looks pretty great, will leave more thoughts when I'm able to test this on OT-2 hardware

2022-06-02 21:33 UTC, mcous commented on update-server/otupdate/buildroot/__main__.py
> +    static_hostname = loop.run_until_complete(name_management.set_up_static_hostname())
Not introduced by this PR, bit it feels like this should be...

```python
async def main() -> None:
    ...

if __name__ == "__main__":
    asyncio.run(main())
```

...rather than this `loop.run_until_complete` business

2022-06-02 21:33 UTC, mcous commented on update-server/otupdate/buildroot/__init__.py
> +    async def set_up_and_tear_down(app: web.Application) -> AsyncGenerator[None, None]:
After reading through this and [your comment below](https://github.com/Opentrons/opentrons/pull/10559/files#r887529544), I think option (3) above might be our best bet

1. `def main()` -> `async def main()`
    - See my comment about `loop.run_until_complete` vs `asyncio.run`
    - `main` calls `build_name_synchronizer` or whatever
3. `def get_app(...)` -> `def get_app(..., name_synchronizer: NameSynchronizer)`
    - Or, we could even include cleanup
    - `def get_app(..., name_synchronizer_context: AsyncContextManager[NameSynchronizer])`
4. Move `FakeNameSynchronizer` to `conftest`, inject it in tests

2022-06-02 21:33 UTC, mcous commented on update-server/otupdate/common/name_management/name_synchronizer.py
> +        app[_NAME_SYNCHRONIZER_VARNAME] = self
This couples the `NameSynchronizer` interface to `aiohttp`, and I think we should avoid doing that if we can

2022-06-02 21:33 UTC, mcous commented on update-server/tests/common/name_management/test_http_endpoints.py
> +    return MagicMock(spec=NameSynchronizer)
I think it'd be pretty uncontroversial to pull in the `mock` backports or `decoy` for this PR

2022-06-02 21:33 UTC, mcous commented on update-server/tests/common/name_management/test_http_endpoints.py
> +    )
I'm not sure if this is too magical, but per my comment above, if the `test_cli` fixture injects a `FakeNameSynchronizer`, and that `FakeNameSynchronizer` is itself from a test fixture, then these tests could override that name synchronizer fixture via `pytest.parametrize` to inject a mock cleanly rather than partially monkeypatching the class definition.

Alternatively, this class could also define its own `test_cli` fixture, since it wouldn't be that much duplication

2022-06-02 21:33 UTC, mcous commented on update-server/otupdate/common/name_management/name_synchronizer.py
> +class RealNameSynchronizer(NameSynchronizer):
I'd be in favor of pulling in one of those mocking libraries and having tests in this PR

2022-06-02 21:33 UTC, mcous commented on update-server/otupdate/common/name_management/name_synchronizer.py
> +    """
This is covered in my other comments, but I'd be **strongly** in favor of getting this out of source code (and into `tests`) if possible. I think the `NotImplementedError` is good, though!

2022-06-06 20:28 UTC, SyntaxColoring commented on update-server/tests/common/name_management/test_http_endpoints.py
> +    )
I ended up having `test_cli` inject a Decoy mock of a `NameSynchronizer`, not even a `FakeNameSynchronizer` class.

* Production code can avoid a `NameSynchronizer` interface vs. `NameSynchronizerImplementation` split.
* Tests that intentionally hit the `NameSynchronizer` can adjust its behavior with `decoy.when(...)`. No magic `pytest.parametrize` needed.
* Tests that unintentionally  hit the `NameSynchronizer` will probably hit an error when they get a `None` result back from the unrehearsed Decoy stub.

2022-06-07 23:23 UTC, mcous submitted a review, later dismissed
Code looks great and from my testing, this works completely as advertised (hah). However, when combined with the app, we've got at least a couple show stoppers:

1. Avahi's name conflict resolution strategy does not agree with the naming restrictions the app gives users (alphanumeric, i.e. no spaces, no hashes)
2. Hashes in robot names break the UI quite badly
    - Even with renaming, the app treats names as robot identifiers
    - These identifiers go in URLs, because the app is a web UI
    - Hashes mean something specific in URLs, so robot names with hashes are mangled when routes are parsed, and you will not be able to navigate to the robot in question to fix the name

The UI behaves badly in other ways during a rename-with-a-conflict, but I think those issues outside the scope of this PR.

I'm at a bit of a loss here. I don't relish the thought of implementing custom name deconflicting ourselves, but it's certainly a smaller lift than changing up the app's entire page routing strategy in the 11th hour.

I think to get this PR mergeable, implementing our own deconflict strategy  is our most viable path. Is there something lightweight we can do that isn't necessarily trying to increment anything (e.g. append a random 4 digit number to the end of the name)?

2022-06-08 14:24 UTC, SyntaxColoring commented
> I think to get this PR mergeable, implementing our own deconflict strategy is our most viable path. Is there something lightweight we can do that isn't necessarily trying to increment anything (e.g. append a random 4 digit number to the end of the name)?

I think appending a random 4-digit number is roughly as difficult as incrementing an integer, but yes, totally doable. 👍

2022-06-08 14:53 UTC, sfoster1 commented
could you just url-escape the name avahi gives us?

2022-06-08 15:44 UTC, SyntaxColoring commented
> could you just url-escape the name avahi gives us?

Are you saying do something like this on the server side?

```python
# On collision...
alternative_name = avahi_client.alternative_service_name(current_name)
alternative_name = url_escape(alternative_name)
avahi_client.start_advertising(alternative_name)
persist_pretty_hostname(alternative_name)
```

If so:

* I can test this, but I suspect it will interfere with Avahi's integer sequencing. `alternative_service_name(current_name)` expects `current_name` to be of the form `Base Name #N`, not `Base Name %23N` or whatever. We could URL-*decode* the current name before passing it to `alternative_service_name()`, but at that point it feels more direct to me to implement our own logic instead of fixing up Avahi to get the result that we want.
* We still have technically have a special character problem, with the `%`s.

------

If you mean should the Opentrons App be url-escaping these names: yes, probably.

2022-06-08 18:17 UTC, mcous commented
I experimented with URL encoding the names on the front-end, and it did not go well. We run up against limitations in the [react-router](https://github.com/remix-run/react-router) library that the app relies on, and I don't think that's something that can get thrown on the A&U team's plate right now

2022-06-09 18:03 UTC, mcous requested changes
Custom name conflict logic looks good, but the new de-conflicted name is not returned to the client, resulting in UI bugs

2022-06-09 18:44 UTC, mcous approved these changes
I don't see a great way to consistently return the de-conflicted name to the client. There's a couple not great options we could explore, but I think it'd be a better idea to get this PR in, first.

I think we should also file a ticket so that the app knows the name that the server returns can't necessarily be trusted

2022-06-09 18:58 UTC, mcous commented
I think the best solution we'd have is something like:

1. Request new name
2. Wait for the next conflict poll
    - Probably with some minimum wait time
3. Check the name
4. Return it

In a very brief (and hacky!) experiment, dropping the conflict poll interval to 1s and sleeping for 1s after the name set was enough time to get the de-conflicted name to the client

2022-06-09 19:01 UTC, SyntaxColoring commented
> I don't see a great way to consistently return the de-conflicted name to the client. There's a couple not great options we could explore, but I think it'd be a better idea to get this PR in, first.

Meaning: return the deconflicted name in the response to the initial HTTP `POST /server/name` request? Like, "OK, you told me to change my name to 'MyRobot', but I couldn't do that; my new name is 'MyRobot2' instead"?

Yeah—in the general case, I don't think the server can do that, because name deconfliction isn't necessarily even tied to these HTTP requests in the first place. You could turn on two robots that start out with the same name and they'd silently deconflict with each other without you ever sending either of them a rename request, for example.

> I think we should also file a ticket so that the app knows the name that the server returns can't necessarily be trusted

The way I'd put it is that the client needs to be prepared for a robot's name to change on its own at any time. The name immediately deconflicting, like this...

1. `POST /server/name {"name": "MyRobot"}
2. 200 success
3. Robot immediately deconflicts with something else and changes name to "MyRobot2"

...is one special case of that.

I think that's #10689, but let me know if that's not quite what you mean.

2022-06-09 19:02 UTC, merged

2022-06-09 19:15 UTC, mcous commented
> I think that's https://github.com/Opentrons/opentrons/issues/10689, but let me know if that's not quite what you mean.

I agree, but in the more immediate term, the app _currently_ expects the HTTP returned name to be the new name of the, robot, and does a UI redirect after the request succeeds to go from `/robots/oldname` to `/robots/newname`.

If the name is deconflicted, though, this appears to happen in practice:

1. HTTP API responds with `{ "name": "newname" }
2. UI redirects from `/robot/oldname` to `/robot/newname`
3. UI is wrong in one of two possible ways
    - Conflict source: other OT-2 already named `newname`
        - User is redirected to the settings page of a different robot than the one they renamed
    - Conflict source: a non-OT-2
        - User is now on a completely blank robot page be the DC has no knowledge of a robot named `newname`

2022-06-09 19:24 UTC, SyntaxColoring commented
Oof, okay.

In addition to what you pointed out, I think there's another problem with that UI redirection logic: it assumes *all robots that the app can connect to* have unique names, but that's not necessarily true.

Imagine one robot plugged in over USB and another robot over Wi-Fi both called "MyRobot". They're on different networks with different mDNS collision domains, so they have no idea about each other's existence and they will never deconflict from each other. But the app will try to put them both under the route `/robot/MyRobot`?

2022-06-09 21:27 UTC, SyntaxColoring commented on update-server/otupdate/common/name_management/avahi.py
> +        avahi_entry_group_collision = dbus.Int32(3)
Turns out not to be easy. See https://github.com/Opentrons/opentrons/pull/10706#discussion_r893911444.