feat(hardware): add InstrumentInfoRequest to get info from Pipettes & Gripper
OpenTrons/opentrons-api pull request #10557
Opened 2022-05-31 23:44 UTC by ahiuchingau

# Overview
Since pipette and gripper are technically both robot instrument, I'm adding an InstrumentInfoRequest so both systems can respond to host when prompted. 

This also means we have to update the tool detector class to read the info from both instruments correctly.

# Changelog

# Review requests

# Risk assessment

2022-06-01 13:31 UTC, sfoster1 requested changes
Looks great but can we swap the types a bit

2022-06-01 13:31 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tools/detector.py
> +    ) -> Tuple[Dict[NodeId, PipetteInformation], Dict[NodeId, GripperInformation]]:
can we make a `TypedDict` spec here, optional keys, pipette (and bootloader) node is to pipette info and gripper (and bootloader) node to gripper info?

2022-06-02 19:25 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tools/detector.py
> +    ) -> Tuple[Dict[NodeId, PipetteInformation], Dict[NodeId, GripperInformation]]:
Nevermind - mypy can't do this kind of value constraint

2022-06-02 19:27 UTC, sfoster1 approved these changes
Awesome! Let's just drop in an integration test.

2022-06-02 19:58 UTC, ahiuchingau commented
Opened a new [ticket](https://opentrons.atlassian.net/browse/RET-1040?atlOrigin=eyJpIjoiZTExYzk5NzJjNTcwNGViN2I4N2I3MGJkYzhlNDFjODAiLCJwIjoiaiJ9) on Jira for adding an integration test

2022-06-02 20:15 UTC, merged