fix(app): fix historical protocol run overflow menu bugs
OpenTrons/opentrons-api pull request #10587
Opened 2022-06-02 15:52 UTC by jerader

closes #10404 #10545 #10548

# Overview

This PR addresses multiple bugs and a quick UI change:
1. only 1 overflow menu opens at a time in historical run protocols
2. the historical run record deletes immediately when you select "delete protocol run record"
3. all "run protocol" CTAs are changed to "run a protocol"

# Changelog

- a quick copy change to `protocol_details`
- change in `HistoricalProtocolRunOverflowMenu`
- create test file for `HistoricalProtocolRunOverflowMenu`

# Review requests

- in the Historical protocol run section: click on a kebab and open an overflow menu. Click on another kebab, the 1st overflow menu should close
- in the Historical protocol run, open an overflow menu, click on "delete protocol run record". The run should delete immediately.

# Risk assessment

low

2022-06-03 14:58 UTC, b-cooper commented on app/src/organisms/Devices/HistoricalProtocolRunOverflowMenu.tsx
> +      deleteRun(runId)
what is this useEffect's intention?  This seems like it will always delete a run when the overflow menu is open.

2022-06-03 15:04 UTC, jerader commented on app/src/organisms/Devices/HistoricalProtocolRunOverflowMenu.tsx
> +      deleteRun(runId)
oh yeah, you're right. Thanks for catching that. This addition was to address the bug outlined in ticket 10454. I'll look into another workaround.

2022-06-03 15:23 UTC, koji requested changes
I don't see any weird parts in changes but when clicking the overflow menu button, the app deletes protocol runs. Could you check this? (Maybe my env issue?)

https://user-images.githubusercontent.com/474225/171883781-0afd6b83-420d-442c-8ebf-3865ea892230.mov

2022-06-03 15:23 UTC, koji commented on app/src/assets/localization/en/protocol_details.json
> +  "run_a_protocol": "Run a protocol",
We don't need to add a to the protocol details page.
Please see check the thread on app-ui team channel.

2022-06-03 15:23 UTC, koji commented on app/src/organisms/Devices/HistoricalProtocolRunOverflowMenu.tsx
> +          data-testid={`HistoricalProtoclRunOverflowMenu_${runId}`}
```suggestion
          data-testid={`HistoricalProtocolRunOverflowMenu_${runId}`}
```

2022-06-03 15:26 UTC, jerader commented
> I don't see any weird parts in changes but when clicking the overflow menu button, the app deletes protocol runs. Could you check this? (Maybe my env issue?)

@koji I think this is what Brian mentioned in my comment, it was introduced by the `useEffect` that I added. I am deleting it now. It seems that the bug outlined in ticket 10545 that I thought i was fixing by adding `useEffect`, isn't actually a bug.

2022-06-03 15:27 UTC, jerader commented on app/src/assets/localization/en/protocol_details.json
> +  "run_a_protocol": "Run a protocol",
Yup just saw the thread, thank you!

2022-06-06 18:17 UTC, koji requested changes
Seem that #10404 and #10548 have been solved by PR but still, #10545 isn't solved.

https://user-images.githubusercontent.com/474225/172221201-783c64ed-c0ce-473f-9047-52b1491eedc5.mov

2022-06-06 19:51 UTC, koji approved these changes
🧹 looks good to me and works as expected (after clicking `Delete protocol run record`, the overflow menu is closed)

2022-06-06 19:51 UTC, koji commented on app/src/organisms/Devices/HistoricalProtocolRunOverflowMenu.tsx
>          onClick={() => deleteRun(runId)}
In my understanding, we need to call `closeOverflowMenu(e)` after deleting run logs. Seems that re-run also has the same issue.

2022-06-06 19:51 UTC, koji commented on app/src/organisms/Devices/HistoricalProtocolRunOverflowMenu.tsx
>          onClick={() => deleteRun(runId)}
Probably something like this.

```typescript
const handleDeleteRunClick: React.MouseEventHandler<HTMLButtonElement> = e => {
    deleteRun(runId)
    closeOverflowMenu(e)
}

onClick={handleDeleteRunClick}
```

2022-06-06 19:59 UTC, merged

2022-06-07 13:44 UTC, y3rsh commented
verified fixed