fix(app): robot update Modal CTA fix
OpenTrons/opentrons-api pull request #10592
Opened 2022-06-02 18:23 UTC by jerader

closes #10431

# Overview

When trying to update the robot through the banner in the robot card, it won't properly and will instead redirect you to the robot overview page. This PR fixes that bug.

# Changelog

- add prop to `updateRobotBanner` so opening the `updateBuildroot` modal happens outside of the `onClick` in the flex in `RobotCard`. The `onClick` was causing the issue

- fix all instances of `updateRobotBanner`

# Review requests

run through the 3 ways to access the Robot update modal through the update Robot banner. Make sure it works okay:
1. Robot Card
2. Robot Advanced Settings
3. Robot Overview 

# Risk assessment

low

2022-06-02 23:16 UTC, koji requested changes
Overall changes look good to me.
Need a small update.

2022-06-02 23:16 UTC, koji commented on app/src/organisms/Devices/RobotSettings/AdvancedTab/RobotServerVersion.tsx
>        {autoUpdateAction !== 'reinstall' && robot != null ? (
Currently RobotSettings checks two thing (useCurrentRunId() and useAllSessionsQuery() ) to prevent unexpected issue. This component also needs to check them. 
When the robot isn't used by anyone or by any actions, we can show the banner. 
**Already talked about this with Brian**

```ts
import { useRobot, useIsRobotBusy } from '../../hooks'
const isBusy = useIsRobotBusy()
```

```suggestion
      {autoUpdateAction !== 'reinstall' && robot != null && !isBusy ? (
```

2022-06-02 23:16 UTC, koji commented on app/src/organisms/Devices/RobotCard.tsx
> +import { UpdateBuildroot } from '../../pages/Robots/RobotSettings/UpdateBuildroot'
Should we move this component to `organisms/Devices/RobotSettings` for #10385 ?

CC @b-cooper @brenthagen

2022-06-03 12:33 UTC, jerader commented on app/src/organisms/Devices/RobotSettings/AdvancedTab/RobotServerVersion.tsx
>        {autoUpdateAction !== 'reinstall' && robot != null ? (
Thanks for letting me know! Adding it now

2022-06-06 20:17 UTC, koji approved these changes
🚀 The changes look good!
Thank you for moving `UpdateBuildroot` into `RobotSettings`!

2022-06-06 20:17 UTC, koji commented on app/src/organisms/Devices/RobotOverview.tsx
> +        backgroundColor={C_WHITE}
I guess changing the old color const to the latest would be good.

2022-06-06 20:23 UTC, merged