feat(engine): allow blow out command in Protocol API
OpenTrons/opentrons-api pull request #10623
Opened 2022-06-06 16:26 UTC by TamarZanzouri

# Overview

closes #9524
Added blow out command to PAPI

# Changelog

- Added blow-out command to PE commands
- Added blow_out end point for PAPI and PAPIv3

# Review requests

1. am I missing logic?
2. names make sense?
3. test I need to add?

# Risk assessment

Medium. Add a new command. Should not affect previous logic but should make sure the command works.

2022-06-06 17:36 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/pipettes.py
>              self._state.current_well = CurrentWell(
set pipette volum to 0

2022-06-08 00:26 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/blow_out.py
> +    """Payload required to blow-out to a specific well."""
```suggestion
    """Payload required to blow-out a specific well."""
```

2022-06-08 00:29 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/commands/test_blow_out.py
> +    """A PickUpTipCreate should have an execution implementation."""
```suggestion
    """A BlowOutCreate should have an execution implementation."""
```

2022-06-08 00:30 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/commands/test_blow_out.py
> +    """A BlowOutCreate should have an execution implementation."""
```suggestion
    """Test BlowOut command execution."""
```

2022-06-08 00:31 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/commands/test_blow_out.py
> +    assert isinstance(result, BlowOutResult)
```suggestion
    assert result == BlowOutResult()
```

2022-06-08 13:55 UTC, mcous requested changes

2022-06-08 13:55 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/blow_out.py
> +BlowOutCommandType = Literal["blow-out"]
Needs to match JSONv6

```suggestion
BlowOutCommandType = Literal["blowout"]
```

2022-06-08 13:55 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/blow_out.py
> +    commandType: BlowOutCommandType = "blow-out"
```suggestion
    commandType: BlowOutCommandType = "blowout"
```

2022-06-08 13:55 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/blow_out.py
> +    commandType: BlowOutCommandType = "blow-out"
```suggestion
    commandType: BlowOutCommandType = "blowout"
```

2022-06-08 13:55 UTC, mcous commented on api/tests/opentrons/protocol_engine/commands/test_blow_out.py
> +    )
`field` should only ever be used as a default parameter value for a dataclass

```suggestion
    left_config = cast(PipetteDict, {"name": "p300_single", "pipette_id": "123"})
    right_config = cast(PipetteDict, {"name": "p300_multi", "pipette_id": "abc"})
```

2022-06-08 13:55 UTC, mcous commented on api/tests/opentrons/protocol_engine/commands/test_blow_out.py
> +        ),
This is a [redundant verify](https://mike.cousins.io/decoy/usage/errors-and-warnings/#redundantverifywarning) and decoy is [throwing a warning about it](https://github.com/Opentrons/opentrons/runs/6785154423?check_suite_focus=true#step:8:288). It should be removed.

It's redundant because the stubbing (`decoy.when`) already ensures the test will pass or fail if the dependency is called correctly or incorrectly. If the dependency is called incorrectly, then the stubbing will not be hit, causing `None` to be returned, failing the test (and throwing a [MiscalledStubWarning](https://mike.cousins.io/decoy/usage/errors-and-warnings/#miscalledstubwarning) into the mix).

2022-06-08 13:55 UTC, mcous commented on api/src/opentrons/protocol_engine/state/pipettes.py
> +            self._state.aspirated_volume_by_id[pipette_id] = 0
Missing unit tests for this functionality

2022-06-08 13:55 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/__init__.py
> +    "BlowOut",
Could you move this block such that the module exports remain at the bottom?

2022-06-08 19:24 UTC, mcous reviewed
One last thing for PAPIv3 support. We should also add a blowout test case to `tests/opentrons/protocol_runner/test_json_command_translator.py`

2022-06-08 19:24 UTC, mcous commented on api/src/opentrons/protocol_engine/clients/sync_client.py
> +    def blow_out(
I think we're missing an addition to `src/opentrons/protocol_api_experimental/pipette_context.py` to actually wire this up to PAPIv3. We can leave `PipetteContext.blow_out(location=None)` unimplemented, though, since we haven't dealt with the fixed trash in PAPIv3 yet

2022-06-09 15:36 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/clients/sync_client.py
> +    def blow_out(
@mcous I added the logic but have no idea if I did this right! would love for guidance :-)

2022-06-09 16:23 UTC, mcous commented on api/src/opentrons/protocol_api_experimental/pipette_context.py
> +                # TODO (tz, 2022-06-09): Should this be declared as nullable?
Nope, we want to keep engine interfaces as explicit as possible

2022-06-09 16:23 UTC, mcous commented on api/src/opentrons/protocol_api_experimental/pipette_context.py
> +            raise NotImplementedError()
```suggestion
            raise NotImplementedError(
                "Blowout locations other than Wells are currently unsupported."
            )
```

2022-06-09 16:23 UTC, mcous commented on api/src/opentrons/protocol_engine/clients/sync_client.py
> +    def blow_out(
Looks great! Just missing a test in `tests/opentrons/protocol_api_experimental/test_pipette_context.py`

2022-06-09 17:54 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/clients/sync_client.py
> +    def blow_out(
Sorry about that! will add this now

2022-06-09 21:20 UTC, mcous approved these changes
Some non-essential thoughts, but core logic + tests LGTM

2022-06-09 21:20 UTC, mcous commented on api/src/opentrons/protocol_runner/json_command_translator.py
> -            "blowout",
🥳

2022-06-09 21:20 UTC, mcous commented on api/tests/opentrons/protocol_engine/clients/test_sync_client.py
> +            ),
Same comment as https://github.com/Opentrons/opentrons/pull/10678/files#r893943417: try not to use data for value objects in tests that looks like it might be valid/used if it's not part of the test.

Here, I would simply use `WellLocation`

```suggestion
            wellLocation=WellLocation(),
```

2022-06-09 21:20 UTC, mcous commented on api/tests/opentrons/protocol_engine/clients/test_sync_client.py
> +        ),
```suggestion
        well_location=WellLocation(),
```

2022-06-09 21:20 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/blow_out.py
> +    """blow-out command model."""
Not sure why the linter didn't complain about this, but try to capitalize docstrings

2022-06-09 21:20 UTC, mcous commented on api/tests/opentrons/protocol_engine/state/command_fixtures.py
> +        createdAt=datetime.now(),
Since this is new code, let's try to avoid `datetime.now()` and give an fixed datetime instead

2022-06-09 21:20 UTC, mcous commented on api/tests/opentrons/protocol_runner/test_json_command_translator.py
> +    (
I know that this PR doesn't introduce it, but I'm _very_ confused about what the `INVALID_TEST_PARAMS` list + `test_invalid_commands` test is doing. I could go in and replace either entry in the tuple with something silly like `"hello world"` and all the tests would still pass.

It also does...

```python
    with pytest.raises(AssertionError):
        assert subject.translate(_make_json_protocol(commands=[test_input])) == [
            expected_output
        ]
```

...which I feel like is just trying to do this...

```python
assert subject.translate(_make_json_protocol(commands=[test_input])) != [
    expected_output
]
```

...which doesn't make sense to me given the input data.

While we're touching this test file, could you either:

- Describe the value of the test in the test's docstring so it doesn't confuse anyone again, or
- Delete `INVALID_TEST_PARAMS` and `test_invalid_commands`

2022-06-10 13:59 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_runner/test_json_command_translator.py
> +    (
I agree INVALID_TEST_PARAMS is very confusing. took me a while to understand what I need to do with it. I am removing it!

2022-06-10 14:48 UTC, laviera commented
Question:   This is merging to edge - assuming another alpha build is going to happen - this will be included.   Is QA aware of this addition and prepared to test ?

2022-06-10 14:49 UTC, mcous approved these changes
Approval still stands

2022-06-10 14:50 UTC, merged

2022-06-10 14:52 UTC, mcous commented
> Question: This is merging to edge - assuming another alpha build is going to happen - this will be included. Is QA aware of this addition and prepared to test?

@laviera this code path is not reachable by production code at the moment. It shouldn't have any 6.0.0 testing implications. Ways this code can be hit:

- Client issues an HTTP request for a blowout command
    - The 6.x app does not issue HTTP requests for _any_ liquid handling commands
- Client uploads a JSONv6 protocol that uses a blow out
    - Nothing generates protocols of this format yet