fix(app): fix robot cal blocked when run is idle
OpenTrons/opentrons-api pull request #10655
Opened 2022-06-07 19:56 UTC by jerader

closes #10634

Should probably wait until https://github.com/Opentrons/opentrons/pull/10650 merges

# Overview

This PR fixes the bug where you can not access deck calibration when you upload a run (outlined in ticket)

# Changelog

- instead of using `useIsRobotBusy` to determine if the button is accessible, it now uses `useRunHasStarted` since `useIsRobotBusy` only counts if there is a RUN ID made which there will always be one when you upload a protocol

# Review requests

- delete your deck cal and upload a protocol. Click on the Calibrate button under deck cal, it will redirect you to Robot Calibration settings. Click on the banner `Calibrate now` or the `Calibrate deck` button. They should both work now

# Risk assessment

low

2022-06-08 15:25 UTC, b-cooper requested changes
This removes the problem, but also removes the disabling functionality.

2022-06-08 15:25 UTC, b-cooper commented on app/src/pages/Devices/RobotSettings/index.tsx
> +  const { robotName, robotSettingsTab, runId } = useParams<NavRouteParams>()
Where is this runId coming from? The route that this is rendered into (`/devices/:robotName/settings/:robotSettingsTab`) won't have a runId  associated with it. This won't function as it's currently written.

Maybe instead of passing a `runId` prop down to the `RobotSettingsCalibration` component here, we should contain the logic in that component and have it call `useCurrentRunId` before the call to `hasRunStarted` ?

2022-06-08 16:39 UTC, koji commented on app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx
> +  const isRunHasStartedAAndRobotBusy = useRobotBusyAndRunStarted()
```suggestion
  const isRunHasStartedAndRobotBusy = useRobotBusyAndRunStarted()
```

2022-06-08 16:39 UTC, koji commented on app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx
> +    if (isRunHasStartedAAndRobotBusy) {
```suggestion
    if (isRunHasStartedAndRobotBusy) {
```

2022-06-08 16:58 UTC, jerader commented on app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx
> +  const isRunHasStartedAAndRobotBusy = useRobotBusyAndRunStarted()
whoops, thank you for always catching my spelling errors 😄

2022-06-08 21:29 UTC, koji approved these changes
The changes look good to me.
The app works as what @jerader describes.

2022-06-09 19:02 UTC, koji reviewed
For this undefined issue https://github.com/Opentrons/opentrons/runs/6818796699?check_suite_focus=true#step:8:5874 

probably need to mock `useDeckCalibrationData` in `PipetteOffsetCalibrationItems.test.tsx` and `TipLengthCalibrationItems.test.tsx`

```ts
const mockUseDeckCalibrationData = useDeckCalibrationData as jest.MockedFunction<typeof useDeckCalibrationData>

// sample
mockUseDeckCalibrationData.mockReturnValue({
      deckCalibrationData: {
        matrix: [
          [1.0, -0.0, 0.0],
          [-0.0, 1.0, 0.0],
          [0.0, 0.0, 1.0],
        ],
        lastModified: '2022-06-09T15:16:26.071279+00:00',
        pipetteCalibratedWith: 'P3HSV212021020502',
        tiprack:
          'ed323db6ca1ddf197aeb20667c1a7a91c89cfb2f931f45079d483928da056812',
        type: 'attitude',
      },
      isDeckCalibrated: true,
    })
```

2022-06-09 19:05 UTC, b-cooper approved these changes
✅

2022-06-09 19:37 UTC, merged