feat(engine): touch tip PAPIv3
OpenTrons/opentrons-api pull request #10678
Opened 2022-06-08 18:19 UTC by jbleon95

# Overview
Addresses #9526

Adds touch tip command to protocol engine along with new implementation.

# Changelog
- Add touchTip command to protocol engine
- Add touch_tip method and associated functions to move to edges, get edge points, and get waypoints

# Review requests

- Does the touch tip implementation make sense? Am I making too many assumptions, should I generalize/reuse logic elsewhere.

# Risk assessment
Medium.

2022-06-08 19:06 UTC, mcous reviewed
Looking pretty good! I think the command implementation as written does a little too much work and can be cut down, so I left some comments on how I think you should do that

2022-06-08 19:06 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/touch_tip.py
> +        await self._pipetting.touch_tip(
Same comment as we had in person with the blow out PR earlier in the week. This touch tip functionality does not need to be shared with any other commands, so let's avoid any misdirection we don't need.

Since `execute` is a collaborator (delegates work to dependencies) and `_pipetteing.touch_tip` is a collaborator, let's collapse it down into a single collaborator and put the delegation logic directly here, in `execute`.

2022-06-08 19:06 UTC, mcous commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +    async def touch_tip(
Move the contents of this method to `TouchTipImplementation.execute`, per comment above

2022-06-08 19:06 UTC, mcous commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +        speed: float = 60.0,
Parameters are unused, they should be removed

2022-06-08 19:06 UTC, mcous commented on api/src/opentrons/protocol_engine/state/geometry.py
> +        radius: float = 1.0,
Parameter is unused by callers, should be removed

2022-06-08 19:06 UTC, mcous commented on api/src/opentrons/protocol_engine/state/geometry.py
> +        well_location: Optional[WellLocation],
`well_location` is always used by callers, so it shouldn't be optional

2022-06-08 19:06 UTC, mcous commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +        )
I think we can simplify things and avoid a delegation to `move_to_edges`. In fact, I don't think we need anything other than `state_view.geometry.get_well_edges`, because **we know touch tips always happen within a single well**. (For multi-channel, it's acceptable to think of it from the perspective of the back-most tip).

This will involve declaring `state_view` and `hardware_api` dependencies of `TouchTipImplementation.__init__`. The system will handle injecting them once they're declared.

I think something along these lines is enough to get the job done:

```python
target_well = CurrentWell(
    pipette_id=pipette_id,
    labware_id=labware_id,
    well_name=well_name,
)

# get pipette mount and critical point for our touch tip moves
pipette_location = self._state_view.motion.get_pipette_location(
    pipette_id=pipette_id,
    current_well=target_well,
)

touch_points = self._state_view.geometry.get_well_edges(
    labware_id=labware_id,
    well_name=well_name,
    well_location=well_location,
)

# will handle raising if the thermocycler lid is in a bad state
# so we don't need to put that logic anywhere else
await self._movement_handler.move_to_well(
    pipette_id=pipette_id,
    labware_id=labware_id,
    well_name=well_name,
    well_location=well_location,
)

for position in touch_points:
    await self._hardware_api.move_to(
        mount=pipette_location.mount.to_hw_mount(),
        critical_point=pipette_location.critical_point,
        abs_position=position,
    )
```

2022-06-08 19:06 UTC, mcous commented on api/src/opentrons/protocol_engine/state/motion.py
> +    def get_edge_waypoints(
I don't think this method, nor a call to `get_waypoints` is necessary. We use `get_waypoints` to plan a motion to a destination **when we don't yet know how to get there**. However, since the procedure we're implemented is a touch tip inside a single well, we **already know it's a series of direct movements**, and we've already calculated every point we need to move to via `get_well_edges`.

I'll leave another comment in the command implementation with what I think we should do, instead

2022-06-08 19:37 UTC, mcous commented
I'm digging through the code in `src/opentrons/protocol_api/instrument_context.py`, and I think we want to add in a couple more checks to the implementation:

- Command should be rejected with an error if target labware has quirk `touchTipDisabled`
- Command should be rejected with an error if target labware is a tip rack

2022-06-09 18:59 UTC, jbleon95 commented on api/src/opentrons/protocol_engine/commands/touch_tip.py
> +        await self._pipetting.touch_tip(
Completely understand the reasoning here and I attempted to do so (which can be seen in the commit history) but unfortunately I ran into a circular dependency issue when trying to import CurrentWell into `commands/touch_tip.py`. Rather than trying to wrestle fixing this in this PR, I've moved the logic back to `PipettingHandler`

2022-06-09 20:57 UTC, mcous requested changes
Looking great! One little fix request on the PAPIv3 side, a few testing comments, and one additional test to add:

- [ ] Add a test to `tests/opentrons/protocol_runner/test_json_command_translator.py` to ensure that a JSON v6 `touchTip` command will be correctly mapped to a PE command

2022-06-09 20:57 UTC, mcous commented on api/src/opentrons/protocol_api_experimental/pipette_context.py
> +            raise NotImplementedError("Vertical offset not yet supported in PE.")
Given this a tiny bit more thought, I think we can definitely support `v_offset` right now. See comment below

2022-06-09 20:57 UTC, mcous commented on api/src/opentrons/protocol_api_experimental/pipette_context.py
> +                offset=WellOffset(x=0, y=0, z=1),
I believe this should be `-1` rather than `1`, where `-1` means "1 mm closer to the deck" and `1` means "further from the deck". That being said, let's just throw `v_offset` in there since it should just work™️ 

```suggestion
                offset=WellOffset(x=0, y=0, z=v_offset),
```

2022-06-09 20:57 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/touch_tip.py
> +                f"Labware {params.labwareId} has quirk touchTipDisabled"
```suggestion
                f"Touch tip not allowed on labware {params.labwareId}"
```

2022-06-09 20:57 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/touch_tip.py
> +        await self._pipetting.touch_tip(
If you'd like to give it another shot, moving `CurrentWell` to the common types definitions in `protocol_engine/types.py` is acceptable. It's also fine how it is now

2022-06-09 20:57 UTC, mcous commented on api/tests/opentrons/protocol_api_experimental/test_pipette_context.py
> +                offset=WellOffset(x=0, y=0, z=1),
See comment about `-1` rather than 1. Also, we should add a test case for `v_offset` explicitly specified

2022-06-09 20:57 UTC, mcous commented on api/tests/opentrons/protocol_engine/clients/test_sync_client.py
> +    """It should execute a dispense command."""
```suggestion
    """It should execute a touch tip command."""
```

2022-06-09 20:57 UTC, mcous commented on api/tests/opentrons/protocol_engine/clients/test_sync_client.py
> +            ),
To save some (keyboard) typing, try to avoid irrelevant data in test objects that are just being used as a value to pass around. Alternatively, construct the the value object such that the actual values are obviously meaningless.

`
```suggestion
            wellLocation=WellLocation(),
```

Or maybe

```python
            wellLocation=WellLocation(
                origin=WellOrigin.BOTTOM,
                offset=WellOffset(x=123, y=456, z=789),
            ),
```
You don't want a reader coming in here at a later date and thinking "oh, the thing that's being tested here must care about the value of the well location", which is a risk if `wellLocation` is set to some "reasonable" value.

The [testdouble wiki](https://github.com/testdouble/contributing-tests/wiki/Meaningless-Test-Data) has some great write ups on the subject.

2022-06-09 20:57 UTC, mcous commented on api/tests/opentrons/protocol_engine/execution/test_pipetting_handler.py
> +    edge_points = [Point(x=i, y=i + 1, z=i + 2) for i in range(0, 13, 3)]
Can we unroll this loop and use a lot fewer points (like 2 or 3) to make this test more explicit and reduce the line count?

2022-06-10 18:56 UTC, mcous reviewed
Need to touch tip 1 mm down from the **top** of the well, not the bottom. My bad for not noticing in my previous review. Otherwise good!

2022-06-10 18:56 UTC, mcous commented on api/src/opentrons/protocol_api_experimental/pipette_context.py
> +                origin=WellOrigin.BOTTOM,
Oops, missed this in my first review. Definitely needs to be 1mm down from the **top** of the well, not 1mm down from the bottom of the well, which would not be pretty.

```suggestion
                origin=WellOrigin.TOP,
```

You can see this in the PAPIv2 implementation of this logic, using its slightly different geometry syntax:

https://github.com/Opentrons/opentrons/blob/0e29be3c5775651290a3af3471a4bf7bc8f217c3/api/src/opentrons/protocol_api/instrument_context.py#L547-L549

2022-06-10 18:56 UTC, mcous commented on api/tests/opentrons/protocol_api_experimental/test_pipette_context.py
> +                origin=WellOrigin.BOTTOM,
```suggestion
                origin=WellOrigin.TOP,
```

2022-06-13 13:54 UTC, mcous approved these changes
Good to merge as soon as CI clears! 🚀

2022-06-13 14:33 UTC, merged