docs(api): Heater-Shaker in API reference
OpenTrons/opentrons-api pull request #10686
Opened 2022-06-08 21:25 UTC by ecormany

# Overview

Docstrings for new Heater-Shaker methods and parameters.

# Changelog

- added autoclass to API reference page
- first pass at docstrings

# Review requests

TK

# Risk assessment

Docs only.

2022-08-02 14:01 UTC, laviera commented
@ecormany - is this PR in need of a refresh or is it ready to go ?

2022-08-02 14:39 UTC, ecormany commented
@laviera Still needs another go. The last draft was from before any pipetting restrictions were implemented.

2022-08-03 20:53 UTC, SyntaxColoring commented
Reminder to resolve this `# TODO` in `ProtocolContext.load_module()`:

https://github.com/Opentrons/opentrons/blob/3ba3d781be017859ec1f723a19f968e648aaf0d5/api/src/opentrons/protocol_api/protocol_context.py#L474

2022-08-16 20:12 UTC, Matt-Zwimpfer commented on api/docs/v2/new_modules.rst
> +To allow for proper anchoring and cable routing, the Heater-Shaker should only be loaded in slot 1, 3, 4, 6, 7, or 10.
As outlined in the [handover doc](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/3214770234/H-S+Product+Support+Handover+Doc#Protocol-Designer%3A.1), "Slot 3 and 6 are permitted, but to lock the rear deck slot clamp you need to use the L key (instead of the longer torx driver)". The API reference should mention this detail. As well, there will be a Support article for installing and setting up the heater-shaker, which will mention and demonstrate this process that this API reference can hyperlink.

2022-08-16 20:29 UTC, y3rsh requested changes
Great work.  A couple required changes for linting and consistency, the rest are soft suggestions.

2022-08-16 20:29 UTC, y3rsh commented on api/docs/v2/conf.py
> +language = 'en'
Will fail black formatting.
```suggestion
language = "en"
```

2022-08-16 20:29 UTC, y3rsh commented on api/docs/v2/new_modules.rst
> +Hardware modules are first-party peripherals that attach to the OT-2 to extend its capabilities. The Python API currently supports four modules that attach to the OT-2 deck and are controlled over a
```suggestion
Hardware modules are first-party peripherals that attach to the OT-2 extending its capabilities. The Python API currently supports four modules that attach to the OT-2 and are controlled over a USB connection: the :ref:`Temperature <temperature-module>`, :ref:`Magnetic <magnetic-module>`, :ref:`Thermocycler <thermocycler-module>`, and :ref:`Heater-Shaker <heater-shaker-module>` modules.
```

2022-08-16 20:29 UTC, y3rsh commented on api/docs/v2/new_modules.rst
> +Some modules were added to the Protocol API later than others, and some modules have multiple hardware generations (GEN2 modules have a "GEN2" label on the device). Make sure your protocol's metadata
```suggestion
Some modules were added to the Protocol API later than others and some modules have multiple hardware generations (GEN2 modules have a "GEN2" label on the device). Make sure your protocol's metadata specifies a :ref:`Protocol API version <v2-versioning>` high enough to support all the modules you want to use.
```

2022-08-16 20:29 UTC, y3rsh commented on api/docs/v2/new_modules.rst
> +The GEN2 Temperature Module has a plastic insulating rim around the plate, and plastic insulating shrouds designed to fit over our aluminum blocks.
```suggestion
The GEN2 Temperature Module has a plastic insulating rim around the plate and plastic insulating shrouds designed to fit over our aluminum blocks.
```

2022-08-16 20:29 UTC, y3rsh commented on api/docs/v2/new_modules.rst
> +To allow for proper anchoring and cable routing, the Heater-Shaker should only be loaded in slot 1, 3, 4, 6, 7, or 10.
```suggestion
To allow for proper anchoring and cable routing, the Heater-Shaker may only be loaded in slot 1, 3, 4, 6, 7, or 10. 
```

2022-08-16 20:29 UTC, y3rsh commented on api/docs/v2/new_modules.rst
> +Finally, if you are using an 8-channel pipette, you can't perform pipetting actions in `any` adjacent slots. Attempting to do so will raise a ``PipetteMovementRestrictedByHeaterShakerError``. This pr
```suggestion
Finally, if you are using an 8-channel pipette, you can't perform pipetting actions in `any` adjacent slots. Attempting to do so will raise a ``PipetteMovementRestrictedByHeaterShakerError``. This prevents the pipette ejector from crashing on the module housing or labware latch. There is one exception. To the front or back of the Heater-Shaker, an 8-channel pipette can access tip racks. Attempting to pipette to non-tip-rack labware will also raise a ``PipetteMovementRestrictedByHeaterShakerError``.
```

2022-08-16 20:29 UTC, y3rsh commented on api/docs/v2/new_modules.rst
> +For preparing the deck before running a protocol, use the labware latch controls in the Opentrons App or run these methods in Jupyter notebook.
```suggestion
To prepare the deck before running a protocol, use the labware latch controls in the Opentrons App or run these methods in Jupyter notebook.
```

2022-08-16 20:29 UTC, y3rsh commented on api/docs/v2/new_modules.rst
> +Heating and shaking operations are controlled independently, and are treated differently due to the amount of time they take. Speeding up or slowing down the shaker takes at most a few seconds, so it
There are a few `,` before an `and` I have noticed.
I have called them out but am wondering with the consistency here if this is a preferred style?

2022-08-16 20:29 UTC, y3rsh commented on api/docs/v2/new_modules.rst
> +Here is an example of how to shake a sample for one minute in a blocking manner — no other commands will execute until the minute has elapsed. This can be done with three commands, which start the sh
This comma before the and is expected 😊

2022-08-16 20:29 UTC, y3rsh commented on api/docs/v2/new_modules.rst
> +
3 new lines?

2022-08-16 20:29 UTC, y3rsh commented on api/src/opentrons/protocol_api/module_contexts.py
> +        - ``error`` - The shaking status can't be determined.
Use a `:` like the other changes here?
```suggestion
        - ``holding at target``: The module has reached its target shake speed and is actively maintaining that speed.
        - ``speeding up``: The module is increasing its shake speed towards a target.
        - ``slowing down``: The module was previously shaking at a faster speed and is currently reducing its speed to a lower target or to deactivate.
        - ``idle``: The module is not shaking.
        - ``error``: The shaking status can't be determined.
```

2022-08-16 20:31 UTC, y3rsh commented
> Reminder to resolve this `# TODO` in `ProtocolContext.load_module()`:
> 
> https://github.com/Opentrons/opentrons/blob/3ba3d781be017859ec1f723a19f968e648aaf0d5/api/src/opentrons/protocol_api/protocol_context.py#L474

✅ is done.

2022-08-16 20:44 UTC, ecormany commented on api/docs/v2/conf.py
> +language = 'en'
`black` would change a _lot_ in the conf file (and some older docs files). Maybe it would be best to keep this PR focused on the H-S content and have a separate chore PR to tidy that up.

2022-08-16 20:49 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +To allow for proper anchoring and cable routing, the Heater-Shaker should only be loaded in slot 1, 3, 4, 6, 7, or 10.
A fine distinction, but you can absolutely load a H-S in 2, 5, or 8 as currently implemented in the API. (But you shouldn't!)

2022-08-16 20:54 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +Heating and shaking operations are controlled independently, and are treated differently due to the amount of time they take. Speeding up or slowing down the shaker takes at most a few seconds, so it
My general guidelines:
- Comma before "and" when conjoining full clauses
- No comma before and when conjoining smaller units (verb phrases, noun phrases, etc.)
- No rule is perfect, so default to prosody (how you would say it out loud) and put a comma at a natural pause

I think the most natural resolution here is to add "they" in the second conjunct and leave the comma.

2022-08-16 20:57 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +
🤷 a gap of 2 is probably fine. I find nothing extra before section headings (especially ones with anchors that precede them) to make it very hard to navigate the source.

2022-08-16 21:49 UTC, Matt-Zwimpfer commented on api/docs/v2/new_modules.rst
> +Next, you can’t place tall labware (defined as >53 mm) to the left or right of the Heater-Shaker. This prevents the Heater-Shaker’s latch from colliding with the adjacent labware. Attempting to load
Change it to be "Common labware found in the Opentrons Labware Library" or just "Common Opentrons labware". Want to make sure people know this is referring to Opentrons products.

2022-08-16 22:31 UTC, Matt-Zwimpfer commented on api/docs/v2/new_modules.rst
> +For preparing the deck before running a protocol, use the labware latch controls in the Opentrons App or run these methods in Jupyter notebook.
Will capture this in detail/step-by-step in Support article.

2022-08-16 22:34 UTC, Matt-Zwimpfer commented on api/docs/v2/new_modules.rst
> +Heating and shaking operations are controlled independently, and are treated differently due to the amount of time they take. Speeding up or slowing down the shaker takes at most a few seconds, so it
Is the "perform other pipetting actions while waiting to reach a target temperature" true/confirmed for H-S?

Pipetting while modules perform other actions has been frequently requested for the other modules, so we should be explicit here and say something along the lines of "at this time, pipetting while the module completes a step is only possible with the heater-shaker module and not the other Opentrons hardware modules available".

2022-08-16 22:52 UTC, Matt-Zwimpfer commented on api/docs/v2/new_modules.rst
> +.. code-block:: python
Great example and detail! Wanted to check that we have tested these solutions out before, right? Plan to do some tests myself as well.

2022-08-17 14:21 UTC, ecormany commented on api/docs/v2/conf.py
> +language = 'en'
checked and we don't run lint tests on anything in `api/docs` — on purpose, i presume. we could add the .py files, but the .rst files should be kept out of it for sure, because hard-wrapping prose makes it _harder_ to edit and maintain over time.

2022-08-17 14:40 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +To allow for proper anchoring and cable routing, the Heater-Shaker should only be loaded in slot 1, 3, 4, 6, 7, or 10.
The attachment process is important, but outside the domain of the API docs. Hardware docs and in-app text cover this, in addition to the support article.

2022-08-17 14:42 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +Next, you can’t place tall labware (defined as >53 mm) to the left or right of the Heater-Shaker. This prevents the Heater-Shaker’s latch from colliding with the adjacent labware. Attempting to load
Good point about these examples being Opentrons products. They're in LL, but any labware (including custom) can run afoul of this restriction.

2022-08-17 14:44 UTC, SyntaxColoring commented on api/docs/v2/new_modules.rst
> +Additionally, if you want to pipette while the module is holding at a speed and/or temperature, you need to parallelize the commands yourself. One of the simplest ways to do this is with Python’s ``t
> Additionally, if you want to pipette while the module is holding at a speed and/or temperature, you need to parallelize the commands yourself.

I think this is an overstatement.

Take this code:

```python
hs_mod.set_and_wait_for_shake_speed(1000)
hs_mod.set_and_wait_for_target_temperature(75)
pipette.transfer(100, some_other_well_plate["A1"], some_other_well_plate["A2"])
```

This is "pipetting while the module is holding at a speed and/or temperature," but we don't need to do anything special to manually parallelize here.

It looks like what you're going to trouble to implement here *isn't*:

> Pipetting while the module is holding at a speed and/or temperature.

It's:

> Hold the speed and/or temperature for 1 minute, or as long as it takes to finish pipetting, whichever takes longer.

2022-08-17 14:44 UTC, SyntaxColoring commented on api/docs/v2/new_modules.rst
> +    hs_mod.deactivate_heater()
A few things about this.

First, it's usually subtly wrong to do arithmetic on `time.time()`. People should use `time.monotonic()` instead.

Second, I don't think this needs `protocol.is_simulating()`, nor a `time.sleep()` busy-loop.

```suggestion
    hs_mod.set_and_wait_for_target_temperature(75)
    start_time = time.monotonic()  # set reference time
    pipette.pick_up_tip()   
    pipette.aspirate(50, plate['A1'])
    pipette.dispense(50, plate['B1'])
    pipette.drop_tip()
    protocol.delay(max(0, start_time+60 - time.monotonic()))
    hs_mod.deactivate_heater()
```

The advantage to `protocol.delay()` over `time.sleep()` is that it can be interrupted immediately by the "Cancel protocol" button in the Opentrons App.

A "disadvantage" is that it will cause the true run log to diverge from the predicted run log. I put "disadvantage" in quotes because this is, in a sense, intended behavior; the protocol really is doing something different.

2022-08-17 14:54 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +.. code-block:: python
@sanni-t has tested these approaches.

2022-08-17 15:43 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +Additionally, if you want to pipette while the module is holding at a speed and/or temperature, you need to parallelize the commands yourself. One of the simplest ways to do this is with Python’s ``t
You're right, this needs a qualifier. I'm thinking: `Additionally, if you want to pipette while the module holds at a target for a certain length of time, you need to track the holding time yourself.` and then adopt your non-polling code from the below comment.

2022-08-17 16:05 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +    hs_mod.deactivate_heater()
Taking this suggestion! It has a wrong method name in it (my fault) and I'll add back a comment explaining the `delay` line. And the surrounding text will have to change considerably, but all for the better.

2022-08-17 18:24 UTC, y3rsh approved these changes
:shipit:

2022-08-17 19:37 UTC, SyntaxColoring approved these changes
Changes in `new_modules.rst` since my last review look great. Thanks!

2022-08-17 20:10 UTC, merged

2022-08-30 16:13 UTC, Matt-Zwimpfer commented
@ecormany Could we also add detail about using [multiple of a module](http://sandbox.docs.opentrons.com/docs-api-heater-shaker/v2/new_modules.html#using-multiple-modules-of-the-same-type) for heater-shakers?

2022-08-30 18:58 UTC, ecormany commented
@Matt-Zwimpfer Good catch, I didn't see that the MoaM section listed _supported_ modules rather than just saying that the Thermocycler is _unsupported_. Will address in a separate PR.