fix(app): overflow btn and navbar styling
OpenTrons/opentrons-api pull request #10694
Opened 2022-06-09 13:34 UTC by jerader

closes #10628 

# Overview

Overflow menu button previously had styling and states that didn't match designs. This fixes that along with correcting the `darkBlackHover` color in the constants and fixing the focus state with the navbar.

# Changelog

- change `overflowBtn`, `Navbar`, and the `darkBlackHover` color in the constants.

# Review requests

- look at the overflow menu buttons, do the states match designs?
- look at the navbar menu items, do the states match designs?

# Risk assessment

low

2022-06-09 15:09 UTC, koji requested changes
Attached the current `edge`
https://user-images.githubusercontent.com/474225/172880182-915b5508-6454-42b0-939c-a3ecf627b41f.mov

Could you check one thing about `focus`
As you can see, when we click one of the nav menu items, the app doesn't show focus box-shadow.
On the other hand, this branch shows focus box-shadow when clicking one of the nav menu items.

2022-06-09 15:09 UTC, koji commented on app/src/atoms/MenuList/OverflowBtn.tsx
>      box-shadow: 0 0 0 1px ${COLORS.darkBlack};
I think we don't need box-shadow for active.

![Screen Shot 2022-06-09 at 10 16 24 AM](https://user-images.githubusercontent.com/474225/172877357-fbdb9f35-eefd-48eb-8fa6-8ea0a5a8beab.png)

2022-06-09 15:09 UTC, koji commented on app/src/atoms/MenuList/__tests__/OverflowBtn.test.tsx
> +      `#16212d25`,
probably `#16212d40` would be better.

![Screen Shot 2022-06-09 at 10 59 31 AM](https://user-images.githubusercontent.com/474225/172878866-709a395f-a5c8-46d0-bf5f-5228e8db2d0a.png)


Also, I tried this.
https://rgbacolorpicker.com/rgba-to-hex

2022-06-09 15:09 UTC, koji commented on app/src/atoms/MenuList/__tests__/OverflowBtn.test.tsx
> +      `#16212d15`,
Probably `#16212d26`

2022-06-09 15:09 UTC, koji commented on app/src/atoms/MenuList/__tests__/OverflowBtn.test.tsx
> +      `#16212d15`,
Also, once #10664 gets approval from devs, I will update this to `COLORS.colorName`.

2022-06-09 18:16 UTC, koji commented on app/src/atoms/MenuList/__tests__/OverflowBtn.test.tsx
> +      `#16212d15`,
This gist might be useful to know how to convert opacity into hex.
https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4

2022-06-09 20:01 UTC, jerader commented on app/src/atoms/MenuList/__tests__/OverflowBtn.test.tsx
> +      `#16212d15`,
thanks for that! I forgot that the numbers dont translate 1:1

2022-06-09 20:55 UTC, mmencarelli commented
[Figma annotation space](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=14136%3A276576)

[Loom video explaining feedback for nav](https://www.loom.com/share/8c1666055bc442289c7a3f9108da5fdb)

- Need to update the hover state to our darkGreyHover (#24313F)
- Need to de-couple pressed and focus state. Focus state (orange outline) only appears when the user is tabbing through the links 

Feedback for overflow buttons
- Need to update all the states
- Need to decouple focus state from pressed and active state
- 
<img width="649" alt="Screen Shot 2022-06-09 at 1 54 22 PM" src="https://user-images.githubusercontent.com/54682054/172942822-ac2db0ae-9d92-4ae1-b678-81b02031a705.png">

2022-06-10 16:10 UTC, mmencarelli commented
looking good!!!!

2022-06-10 16:27 UTC, mmencarelli approved these changes

2022-06-10 16:39 UTC, koji commented on app/src/atoms/MenuList/OverflowBtn.tsx
> +    box-shadow: 0 0 0 3px ${COLORS.warning};
I think we need to add `background-color: ${COLORS.transparent};`
Just sent a message to ask about this to Mel.

https://www.figma.com/file/l7BAJAGICr10ELsSqQD0Sr?node-id=2180:85399#209555192

2022-06-10 16:41 UTC, jerader commented on app/src/atoms/MenuList/OverflowBtn.tsx
> +    box-shadow: 0 0 0 3px ${COLORS.warning};
shouldn't it already be transparent since we didn't specify a `background-color` for the default state?

2022-06-10 16:42 UTC, koji approved these changes
Thank you for fixing the focus state thing! ⭐️
Leave one comment on overflow menu focus, but other changes look good to me!

2022-06-10 16:52 UTC, koji commented on app/src/atoms/MenuList/OverflowBtn.tsx
> +    box-shadow: 0 0 0 3px ${COLORS.warning};
Yeah, you are right. We should specify `background-color`.
maybe `COLORS.white` or `COLORS.background` ?

2022-06-10 16:54 UTC, merged

2022-06-10 16:59 UTC, jerader commented on app/src/atoms/MenuList/OverflowBtn.tsx
> +    box-shadow: 0 0 0 3px ${COLORS.warning};
whoops i merged before seeing this reply, sorry. I would want to confirm with Mel what we would want the background color to be - in every usage of the `overflowBtn`, it seems it is being used above a white background but f we add it to something without a white background in the future, maybe we would want the background color to be transparent.