style(app): 10208 60 feedback design qa t1 protocols landing page 10153
OpenTrons/opentrons-api pull request #10726
Opened 2022-06-10 17:00 UTC by aptrons22

# Overview

The PR will fix #10488

- [x] (1) Missing the enabled state (no fill background), and needs a hover state linked up. 
- [x] (2) Remove the white fill from the button
- [x] (3) When I press on the button, i get the orange outline. The orange outline is only the focus state and should only appear when a user tabs through all the links using 'tab' on their keyboard. So remove this please! (Already Done)
- [x] (4) update 'sort by' text to our `darkGreyEnabled`
- [x] (5) Looks like we're missing the hover state for the protocol cards. Check the design system for info 
- [x] (7) Update this text across all cards to our `darkGreyEnabled`
- [x] (8) The columns should have a min-width of 170px so regardless of what content is in them, the columns will always align. These columns should be responsive when the user shrinks the viewport.
- [x] (9) Update both of these so it's our label text in `darkGreyEnabled`. No uppercase here
- [x] (10) Update text should align to the bottom of the other containers to the left. 
- [x] (11) Update to be our `p-semibold`, currently it's bold 
- [x] (12) Update to our `label-semibold` styling. 
- [x] (13) Double check the colour of the text and the icon. They should be the same
- [x] (14) Update the spacing here between header and text below to .25 rem

<img width="641" alt="Screen Shot 2022-06-06 at 2 02 01 PM" src="https://user-images.githubusercontent.com/54682054/172248639-cd7f952c-f2d4-41f8-aca4-fb2911b4702a.png">

# Changelog

- The following list above has been completed.
- Styling of icons has been modified
- Styling of text colors
- Icon behaviors has been revised

# Review requests
Low

# Risk assessment
Low

2022-06-10 21:49 UTC, koji requested changes
Please check Mel's feedback again.

2022-06-10 21:49 UTC, koji commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
> +        as="h5"
According to Figma, p-semibold instead of `h5`

2022-06-10 21:49 UTC, koji commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
> +        role="complementary"
it could be good but at this time we need to align the coding style. So adding this role would be later.

2022-06-10 21:49 UTC, koji commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
> +          css={TYPOGRAPHY.labelSemiBold}
Why don't you use `TYPOGRAPHY.darkLinkPSemiBold`?
If you use it, you don't need to pass color.

2022-06-10 21:49 UTC, koji commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
> +          css={TYPOGRAPHY.labelSemiBold}
same

2022-06-10 21:49 UTC, koji commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
>            fontSize={FONT_SIZE_CAPTION}
According to Figma, this font size is `label`

2022-06-10 21:49 UTC, koji commented on components/src/ui-style-constants/typography.ts
> +    opacity: 0.7;
This should be `1`

2022-06-10 21:49 UTC, koji commented on components/src/ui-style-constants/typography.ts
> +    opacity: 0.7;
Probably you can extend `linkPSemiBold` for this.

```suggestion
export const darkLinkPSemiBold = css`
  ${linkPSemiBold}
  color: ${COLORS.darkBlack};
  opacity: 0.7;

  &:hover {
    opacity: 1;
  }
`   
```

2022-06-10 21:49 UTC, koji commented on components/src/ui-style-constants/typography.ts
> +    opacity: 0.7;
However, you will need to change the font size since the design font size is `label`. Or you can change the name and font size to `label`.

2022-06-10 21:49 UTC, koji commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
>            fontSize={FONT_SIZE_CAPTION}
Icon's opacity is always 0.7 and this should be 1 when the element state is `hover`

2022-06-10 21:49 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +              backgroundColor={COLORS.darkGreyEnabled}
This line should be `transparent`

2022-06-10 21:49 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +                {SortByText[sortBy]}
Why do you use `SortByText` here?

2022-06-10 21:49 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +    borderRadius={SPACING.spacing2}
This should be `border-radius`. But not sure, why do you need to use these css properties? I think Mel's feedback would be about background color if I understood the feedback.

(1) Missing the enabled state (no fill background), and needs a hover state linked up.

2022-06-10 21:49 UTC, koji commented on components/src/primitives/Btn.tsx
> +  &:enabled {
I think we should modify `atoms/buttons` instead of this file.

2022-06-13 15:09 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
> +        as="h5"
I have this update. Thanks

2022-06-13 15:11 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
> +          css={TYPOGRAPHY.labelSemiBold}
Mel wanted me to use labelSemiBold instead so I just passed color in as well.

2022-06-13 16:01 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
>            fontSize={FONT_SIZE_CAPTION}
Hi Koji, do you mean fontSizeLabel?

2022-06-13 16:11 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +                {SortByText[sortBy]}
I did not make that change.  Thanks

2022-06-13 17:36 UTC, koji commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
>            fontSize={FONT_SIZE_CAPTION}
yes, right now we use `TYPOGRAPHY` to change font size, weight, and font height.
If you see something that changes the font props without `TYPOGRAPHY`, you will need to check `typography.ts` except `textTransform` / `text-transform`

2022-06-13 20:56 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
> +              font-style="normal"
we don't do hard-coded properties.
In react a property that includes `-` would be used as `Lower Camel Case`.
text-transform -> `textTransform`
most props are in typography.ts except `textTransform`
textTransform prop should be imported by `@opentrons/components`

2022-06-13 20:58 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +  const SortByText = styled(StyledText)`
still not align with Figma's design
![Screen Shot 2022-06-13 at 4 57 06 PM](https://user-images.githubusercontent.com/474225/173444253-951a5e74-0d3c-43d1-9d7d-516f04b90a38.png)

https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=1297%3A90568

2022-06-13 20:59 UTC, koji commented on components/src/primitives/Btn.tsx
> +    color: ${Styles.C_BLUE};
We should use `COLORS` instead of using an old color const

2022-06-13 21:02 UTC, koji commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
> +          fontSize={TYPOGRAPHY.fontSizeLabel}
There is no `hover` for Link.

2022-06-13 21:05 UTC, koji commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
> +          css={TYPOGRAPHY.labelSemiBold}
I guess what Mel said was about Figma which means that her `labelSemiBold` isn't the same as code's `labelSemiBold`

2022-06-13 21:07 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
> +          fontSize={TYPOGRAPHY.fontSizeLabel}
Hello Koji, I'm not sure what you mean?

2022-06-13 21:08 UTC, koji requested changes
Seems that this branch would need to merge `release-6.0.0` since the focus issue that Jethary fixed isn't included.

2022-06-13 21:16 UTC, closed without merging