feat(shared-data): add gripper specs
OpenTrons/opentrons-api pull request #10722
Opened 2022-06-10 14:42 UTC by ahiuchingau

# Overview
Adding gripper name and model specs to shared data. All of the values are not finalized yet and should be modified based on hardware & electrical changes.

# Changelog

# Review requests

# Risk assessment

2022-06-10 15:14 UTC, mcous reviewed
Some initial thoughts based on having to work with / around the pipette specs.

Was there any reasoning behind sticking with the `...ModelSpecs.json` and `...NameSpecs.json` situation? That's quite an old pattern for pipettes, and it's always been a bit awkward to deal with.

Is there any way the gripper can be more like the modules, with one config file per specific model?

2022-06-10 15:14 UTC, mcous commented on shared-data/python/opentrons_shared_data/gripper/dev_types.py
> +This module should only be imported if typing.TYPE_CHECKING is True.
I don't think this should be a requirement of this (or any of these) modules, especially considering everything works just fine without the `TYPE_CHECKING` guard.

If this comment was copied from another module, I believe it's a holdover from a time before `typing_extensions` was a runtime dependency of the `opentrons` package

2022-06-10 15:14 UTC, mcous commented on shared-data/python/opentrons_shared_data/gripper/dev_types.py
> +]
`Union[Literal[...], Literal[...], ...]` is redundant

```suggestion
ConfigUnit = Literal[
    "amps",
    "hertz",  # PWM frequency
    "percentage",  # Duty cycle
    "volt",  # Reference voltage
]
```

2022-06-10 15:14 UTC, mcous commented on shared-data/python/opentrons_shared_data/gripper/dev_types.py
> +class GripperCustomizableConfigElementFloat(TypedDict):
How sold are we on using `TypedDict`? As a HardwareControlAPI client, they're kind of annoying to work with and similarly annyoing to construct in tests. Could we use `dataclass`es or `typing.NamedTuple`s instead?

2022-06-10 15:14 UTC, mcous commented on shared-data/python/tests/gripper/test_typechecks.py
> +)
I think this is a sign we should either stop using `typeguard` for our tests, stop using `TypedDicts`, or both

2022-06-10 15:14 UTC, mcous commented on shared-data/python/tests/gripper/test_typechecks.py
> +    typeguard.check_type("defdict", defdict, GripperModelSpecs)
Rather than typegaurd, which we know blows up on Python 3.10, I think this test could work with Pydantic, instead

```python
import parse_obj_as from pydantic

def test_model_config_check() -> None:
    defdict = model_config()
    # does not raise
    parse_obj_as(GripperModelSpecs, defdict)
```

2022-06-10 15:14 UTC, mcous commented on shared-data/python/opentrons_shared_data/gripper/dev_types.py
> +GripperModel = NewType("GripperModel", str)
If this is a known value, can it be an string `Enum` instead? Same type checking value, easier to use with as a client

2022-06-10 15:29 UTC, ahiuchingau commented on shared-data/python/opentrons_shared_data/gripper/dev_types.py
> +class GripperCustomizableConfigElementFloat(TypedDict):
I'm always a huge believer of dataclasses. Happy to switch to that.

2022-06-10 15:57 UTC, sfoster1 requested changes
Pretty much agree with @mcous on this stuff, I guess pydantic will work better than typeguard (I think using typeguard predates adding pydantic to shared-data). 

Definitely agree on the thoughts on the structure of the model configs - if we can avoid having one giant `gripperModelConfigs.json` in favor of `gripperV1.json` that would be ideal. 

I think we want to keep a "name specs" vs "model specs" distinction, but having each name spec and each model spec be a separate file - e.g. `definitions/name/gripperGen1.json` and `definitions/model/gripper_1_1.json` or something - but I trust your judgement and nothing is deployed yet so we can change it if we want after the fact.

2022-06-10 16:35 UTC, mcous commented on shared-data/python/opentrons_shared_data/gripper/dev_types.py
> +class GripperCustomizableConfigElementFloat(TypedDict):
Nice! It will be a little more work to read the JSON files into a `dataclass` than a `TypedDict` (since a `TypeDict` is only a type annotation), but we can lean on `parse_obj_as` or `parse_raw_as` from Pydantic in the immediate term, if we want to.

Longer term, we have some concerns with Pydantic over in RS-land, so I'm very in favor of sticking with vanilla `dataclass` over `BaseModel` and only leaning on Pydantic in a way that can be swapped out with something else in the future

2022-06-13 14:45 UTC, ahiuchingau commented
I've decided that we are not going to separate "name" and "model" for the gripper, _for now_. This is because we don't really have a lot of definitions yet to add to the file. 

But we should definitely do a refactor once we have more info to add to the gripper, and make the distinction between "name" and "model". It shouldn't be too difficult since nothing is deployed yet.

2022-06-13 21:00 UTC, ahiuchingau commented
Do we like using `pydantic.dataclasses` instead of the standard dataclasses because it supports extra type-checking? It does require a mypy plugin, but it seems to work. @mcous @sfoster1

2022-06-13 21:02 UTC, mcous commented
> Do we like using pydantic.dataclasses instead of the standard dataclasses because it supports extra type-checking?

No, we do not like using `pydantic.dataclasses`. Very heavy preference towards defining these objects as vanilla `dataclass`es

2022-06-14 16:40 UTC, sfoster1 requested changes
What is present looks good but to actually include the gripper definition files in the shared-data wheel (and thus get them installed on a robot) you'll need to add the gripper subdir to [the list of captured subdirs in setup.py](https://github.com/Opentrons/opentrons/blob/b8c7c8878a8c99ad2f2c5d6bc150faecb0b7f7d4/shared-data/python/setup.py#L24)

2022-06-15 21:44 UTC, mcous reviewed
Love the switch to dataclass. Still got some questions around the shape of the definition itself. It looks like we might be mixing "definition" with "current configuration of a specific gripper". Hopefully it's just a field naming thing, though

2022-06-15 21:44 UTC, mcous commented on shared-data/gripper/definitions/1/gripperV1.json
> +    "units": "volt",
Why are the units `amps` (plural) above but `volt` (singular) here?

2022-06-15 21:44 UTC, mcous commented on shared-data/python/opentrons_shared_data/gripper/__init__.py
> +) -> Optional[GripperDefinitionV1]:
Why is this `Optional`? I would expect a `load_definition` to raise if I gave it bad inputs

2022-06-15 21:44 UTC, mcous commented on shared-data/python/opentrons_shared_data/gripper/dev_types.py
> +    v1 = "gripperV1"
To match existing convention, can enum keys be `ALL_CAPS`?

```python
V1 = "gripperV1"
```

2022-06-15 21:44 UTC, mcous commented on shared-data/python/opentrons_shared_data/gripper/dev_types.py
> +@dataclass
Can all these dataclasses be `frozen`?

2022-06-15 21:44 UTC, mcous commented on shared-data/python/opentrons_shared_data/gripper/dev_types.py
> +    value: float
Why does the gripper definition need affordances for the current value? The current value is configuration, which should be kept separate and away from and definition object.

Should these `value` fields instead be `defaultValue` or similar?

2022-06-16 13:47 UTC, sfoster1 requested changes
Might be a naming thing, but agree with @mcous  - stuff like this doesn't really belong here in my opinion. We have definitions like this for specific, tested values that we always need to use, but that vary between models. On pipettes, that's things like active current, sure, but current is a bad analogy here - the reference voltage and duty cycle for a gripper determine the force it expresses, and are really more akin to the ul/mm functions for the pipettes.

some of this also doesn't really need to be configurable at all. like we don't really need to have the pwm frequency set in code. we have it settable via can, but that's just for convenience. similarly, i don't really think we need values for the duty cycle or reference voltage - those values are uL/mm, or stored in eeprom, or whatever. we can keep them here now for convenience if you really want, but quite honestly i'd almost prefer to have them be constants in code so we know we need to change them.

2022-06-16 13:47 UTC, sfoster1 commented on shared-data/gripper/definitions/1/gripperV1.json
> +  "dutyCycle": {
in addition to the higher level comment, for the gripper there are configurations for both the z actuator and the jaw actuator. if you know the specific electronic architecture already, these config names make sense; but if you don't, it'll be really confusing. Let's use the names of the fields to make it clear what actuator each value corresponds to.

2022-06-22 13:24 UTC, sfoster1 approved these changes
Looks good to me! Very hype

2022-06-22 13:24 UTC, sfoster1 commented on shared-data/python/tests/gripper/test_typechecks.py
> +GRIPPER_DEF = {
given that this is testing the python typechecks rather than specifically the definition itself, you might as well just load the definition from json

2022-06-22 17:39 UTC, merged