feat(protocol-designer): add collision warnings for heater shaker
OpenTrons/opentrons-api pull request #10759
Opened 2022-06-14 16:39 UTC by shlokamin

# Overview
This PR adds new collision warning to the file pipette modal and edit modules modal

closes #10514

# Changelog
- Add collision warnings for heater shaker

# Review requests

Go through ACs in the ticket (#10514)

# Risk assessment

Low

2022-06-14 17:23 UTC, howisthisnamenottakenyet requested changes
In Potential pipette-module collisions
- Bullet 2 "8-Channel pipettes can only access slots in front of or behind a Heater-Shaker Module GEN1 if that labware is a tip rack" should be updated to "...behind a Heater-Shaker Module GEN1 if that slot contains a tip rack". I think that would make the text read more smoothly. I'll update the design to match.
- Bullet 3 "GEN1 8-Channel pipettes..." The whole line is incorrect
- The spacing between lines looks very wrong. Can we increase it?
- The image is really blurry. Is it exported directly from figma?
- When the card is showing just the Heater-Shaker collision warnings there's an empty line space above the text. 

Other functionality
- Right now if you have the Heater-Shaker collision warnings on the file tab then click "remove" on the Heater-Shaker, the collision warnings do not update.

2022-06-14 21:36 UTC, jerader reviewed
Looking good so far. The logic looks correct + smoke test worked as expected. I have a few things:

1. why isn't anything in i18n?
2. the spacing in the below screenshot looks wrong (compared to the warning spacing that show up in the Create a Protocol modal)

<img width="890" alt="Screen Shot 2022-06-14 at 5 33 33 PM" src="https://user-images.githubusercontent.com/66035149/173692930-28dd799a-7c5a-4c5e-9b7e-cd60de6d850f.png">

2022-06-14 21:36 UTC, jerader commented on protocol-designer/src/components/modules/CrashInfoBox.tsx
> +    <React.Fragment>
does this need to be a `React.Fragment` or can it be just a `<>`

2022-06-14 21:36 UTC, jerader commented on protocol-designer/src/components/modules/CrashInfoBox.tsx
> +      </li>
shouldn't all the text be in i18n?

2022-06-14 21:36 UTC, jerader commented on protocol-designer/src/components/modules/CrashInfoBox.tsx
> +    <React.Fragment>
same comment as above

2022-06-14 21:36 UTC, jerader commented on protocol-designer/src/components/modules/__tests__/EditModulesCard.test.tsx
> +      heaterShakerOnDeck: false,
there are probably a few tests that can be added to this file but only if you have time 😄

2022-06-14 21:39 UTC, shlokamin commented on protocol-designer/src/components/modules/CrashInfoBox.tsx
> +    <React.Fragment>
they are the same thing! but `<>` is more succinct good call

2022-06-14 21:40 UTC, shlokamin commented on protocol-designer/src/components/modules/CrashInfoBox.tsx
> +      </li>
yeah, so the thing is PD uses an old version of i18n that doesn't have trans components, so we can't pass in `strong` for i18n to interpolate. in the moment i decided it wasnt worth the effort to upgrade, but you're right that these strings can still be put in i18n and i can do the interpolation myself. thx for keeping me honest lol

2022-06-14 21:45 UTC, jerader commented on protocol-designer/src/components/modules/CrashInfoBox.tsx
> +    <React.Fragment>
cool cool, brian always calls me out for using `React.Fragment` when it isn't needed 😬

2022-06-14 21:46 UTC, jerader commented on protocol-designer/src/components/modules/CrashInfoBox.tsx
> +      </li>
I see, ya you should at least put the strings in lol

2022-06-14 21:48 UTC, shlokamin commented on protocol-designer/src/components/modules/CrashInfoBox.tsx
> +    <React.Fragment>
def bad to include fragments if they are unnecessary, but in this case we need one because we're returning multiple DOM nodes with no parent

2022-06-15 14:46 UTC, shlokamin commented
@howisthisnamenottakenyet i (think) i addressed your comments. to answer your question about the image, i imported it directly from figma

2022-06-15 20:48 UTC, howisthisnamenottakenyet submitted a review, later dismissed
I'm unfortunately still seeing 8-channel < > module collision warnings when only a Single channel and Heater-Shaker are selected.

2022-06-15 20:51 UTC, shlokamin commented
@howisthisnamenottakenyet weiiiird, i can't repro. can you take a screenshare video?

2022-06-17 17:24 UTC, sakibh approved these changes
I tested all the permutations and everything seems to work as expected! The warnings disappear and reappear as expected when the settings are changed.

2022-06-17 17:24 UTC, sakibh commented on protocol-designer/src/components/modules/CrashInfoBox.tsx
> +// type HeaterShakerCollisonProps = Pick<Props, 'heaterShakerOnDeck'>
Do we still need this commented out type?

2022-06-21 13:41 UTC, shlokamin commented on protocol-designer/src/components/modules/CrashInfoBox.tsx
> +// type HeaterShakerCollisonProps = Pick<Props, 'heaterShakerOnDeck'>
lol no, thx sakib!

2022-06-21 17:10 UTC, merged