feat(engine): open and close thermocycler lid
OpenTrons/opentrons-api pull request #10760
Opened 2022-06-14 17:37 UTC by jbleon95

# Overview
Addresses #9556

Adds thermocycler module's open lid and close lid to protocol engine and PAPIv3

# Changelog
- Added openLid to Protocol Engine
- Added closeLid to Protocol Engine
- Added open_lid and close_lid to PAPIv3 thermocycler module context

# Review requests
- Should open/close lid response include the lid state (and should that be kept track of in the module store?)

# Risk assessment
Low, relatively simple additions and does not affect existing code.

2022-06-14 18:42 UTC, mcous requested changes
Both `openLid` and `closeLid` need to ensure the gantry is out of the way before doing anything with the lid. In Protocol API v2, this is done with `ThermocyclerContext._prepare_for_lid_move`.

Looking at what we have available to us, I think a call to `movement_handler.home` before talking to the TC hardware will do the trick:

```python
# move the pipettes and gantry over the trash
# do not home plunger axes because pipettes may be holding liquid
await self._movement.home([
  MotorAxis.X,
  MotorAxis.Y,
  MotorAxis.RIGHT_Z,
  MotorAxis.LEFT_Z,
])
```

2022-06-15 17:34 UTC, sanni-t reviewed
We should mention in command descriptions and docstrings that these will home the gantry before opening/closing lid.

2022-06-15 17:34 UTC, sanni-t commented on api/src/opentrons/protocol_engine/commands/thermocycler/close_lid.py
> +        await self._movement.home(
This looks good and definitely is the most cautious way of making sure the lid doesn't crash into the pipettes but I was wondering if this would get annoying for someone who has a lot of lid open and closes (which I've seen in protocols). Can we look at the gantry position and decide whether it needs homing or not?

2022-06-15 21:15 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/thermocycler/close_lid.py
> +        await self._movement.home(
I agree that this would get annoying, but it's very similar to what's already implemented in PAPIv2: https://github.com/Opentrons/opentrons/blob/6461ec84846151ccc68640cc6a0bbdfb7cf35590/api/src/opentrons/protocol_api/module_contexts.py#L539-L563

Given that this won't be substantially _more_ annoying that the existing PAPIv2 solution, and it will be a little safer, I think I'd like to save any optimizations for another ticket

2022-06-15 21:23 UTC, mcous approved these changes
LGTM. Can someone test this on hardware before merging?

2022-06-15 22:14 UTC, sanni-t commented on api/src/opentrons/protocol_engine/commands/thermocycler/close_lid.py
> +        await self._movement.home(
Oh yes, definitely wasn't a suggestion for this PR

2022-06-15 22:14 UTC, sanni-t commented
I can test it in a few

2022-06-16 00:45 UTC, sanni-t commented
OK, just one thing missing- uncommenting the commands in `robot_server/commands/stateless_commands`. Once that's done, this works perfectly

2022-06-16 04:22 UTC, sanni-t commented
Forgot about JSONv6 earlier, so tested a quick v6 protocol that does the following steps:
- load thermocycler module
- open lid
- perform a transfer to labware in thermocycler
- close lid

Ran across these two problems:
1. PD writes "slotName" as "span7_8_10_11" so the engine gave an error. Prolly needs to be put on App/UI's radar.
Since it's not related to this PR, I changed the slot manually to "7".
2. Then the dispense command gave this error: 
```
  "id": "0151fa99-68e3-415e-b423-a994da59254e",
  "errorType": "ThermocyclerNotOpenError",
  "createdAt": "2022-06-16T03:54:02.541617+00:00",
  "detail": "Thermocycler must be open when moving to labware inside it, but can't confirm Thermocycler's current status."
```
It's an error generated by `ThermocyclerMovementFlagger`. I couldn't tell what's wrong after a quick glance. Seems like there might be a bug in the `_find_containing_thermocycler` method. Not sure if it is relevant to this PR either.

2022-06-16 18:02 UTC, sanni-t commented
Talked to AUI about thermocycler slot name; they'll be changing PD to use slot 7.
Created a bug ticket to figure out the problem with accessing labware in thermocycler.

I think this PR is good to merge!

2022-06-16 18:02 UTC, sanni-t approved these changes

2022-06-16 18:33 UTC, merged