feat(api): heater-shaker: error status setting
OpenTrons/opentrons-api pull request #10765
Opened 2022-06-14 20:17 UTC by pmoegenburg

When an error response comes from the heater-shaker (including in the
background polls, since the module firmware can initiate asynchronous
error states), in addition to passing on any exceptions we need to set a
longer-lasting error state that can be retrieved and reset by higher
levels.

Closes #9644

2022-06-17 13:50 UTC, sfoster1 approved these changes
Looks good to me (other than removing that unused fixture) but we should probably wait to merge on a robot-services review. We might want to add more synchronous error tests for other methods as regression tests too.

2022-06-17 13:50 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/modules/test_hc_heatershaker.py
> +async def simulating_module_poller_patched(simulating_module):
can probably remove this, since it's not used

2022-06-21 20:10 UTC, sanni-t requested changes
Reviewed this with @TamarZanzouri.
Thanks for adding this in! Have some clarification questions and change request for tests.

2022-06-21 20:10 UTC, sanni-t commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +        with self._guard_exc_to_error_state():
Why is `CancelledError` is in the ignoreList for some commands while not in others?

2022-06-21 20:10 UTC, sanni-t commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +    async def clear_error(self) -> None:
I think I see the point of this method.. the ticket calls for being able to reset the error status when there was a transient error that has since been taken care of. Just want to know how you anticipate it being used. Are there any conditions during which it would be harmful/ not recommended to reset the error status? 
Can we add a docstring to help explain the point of this method?

2022-06-21 20:10 UTC, sanni-t commented on api/tests/opentrons/hardware_control/modules/test_hc_heatershaker.py
> +async def test_sync_error_responses(simulating_module_driver_patched):
Can we make this a parametrized test? It's testing a lot of methods. It would be much more readable if it's parametrized to handle one method/ command at one time. Also open to splitting into multiple tests if parametrization is difficult.

2022-06-21 20:10 UTC, sanni-t commented on api/tests/opentrons/hardware_control/modules/test_hc_heatershaker.py
> +        simulating_module_driver_patched.live_data["data"]["errorDetails"] == "RuntimeError()"
This is asserting the same condition as the one on line 187 without checking if the status was reset in between. This could result in the test missing whether it was `set_temperature` or `set_speed` that caused the change in status.
This won't be an issue if we parametrized or split up this test as mentioned in the comment above.

2022-06-21 20:10 UTC, sanni-t commented on api/tests/opentrons/hardware_control/modules/test_hc_heatershaker.py
> +async def test_async_error_response(simulating_module_driver_patched):
We're not sure whether checking the call to `wait_next_poll` results in error is required here. The check for `get_temperature`'s error can happen alongside the other commands' error checks above. This test seems to be testing that the poller calls `get_temperature`, and that's not the aim of this test.

2022-06-21 20:10 UTC, sanni-t commented on api/tests/opentrons/hardware_control/modules/test_hc_heatershaker.py
> +async def test_sync_error_responses(simulating_module_driver_patched):
Also, can we add a docstring here specifying what we're testing?

2022-06-21 20:10 UTC, sanni-t commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +        except Exception:
Is there a specific exception type we can use here?

2022-06-21 20:10 UTC, sanni-t commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +        If specified, catchlist makes this only handle the specified
None of the methods below specify a `catchList`. Do we then need to have this? If yes, can we add the reason to the docstring?

2022-06-23 14:39 UTC, pmoegenburg commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +        with self._guard_exc_to_error_state():
I believe because the function task has been made cancellable or not

2022-06-23 16:44 UTC, pmoegenburg commented on api/tests/opentrons/hardware_control/modules/test_hc_heatershaker.py
> +async def test_async_error_response(simulating_module_driver_patched):
The goal here is to test that the poller detects an error and updates the status. The poller `read` function calls `get_temperature`. One way to introduce an error is to add the error side effect to the `get_temperature` function.

2022-06-23 18:39 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +        except Exception:
Don't think so - just a catchall in case this is a kind of exception that doesn't actually have args.

2022-06-23 18:40 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +        If specified, catchlist makes this only handle the specified
I guess not, but it seems reasonable for future functionality just in case

2022-06-28 19:38 UTC, sanni-t commented
Recap of change requests from meeting w/ @mcous @pmoegenburg @sfoster1 @laviera @TamarZanzouri :
- remove the exception guards to individual commands
- raise the error from within wait for poll and not from the poller
- if the poller fails, set the error status
- if the poller succeeds, set the error status back to none

Let me know if I'm missing/ mis-remembering anything

2022-06-29 17:39 UTC, sfoster1 requested changes
Functionality looks good, let's just reduce the noise a little

2022-06-29 17:39 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +        await self.wait_for_is_running()
can we move these three blocks of code back above the definition of `_wait` to reduce noise

2022-06-29 17:39 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +        await self.wait_for_is_running()
similarly, let's undo the moving of this code to reduce noise

2022-06-29 17:39 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +        await self.wait_for_is_running()
move back

2022-06-29 17:39 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +        await self.wait_for_is_running()
move back

2022-06-30 19:20 UTC, sfoster1 approved these changes
Looks great to me!

2022-07-06 16:30 UTC, mcous submitted a review, later dismissed
I've got a couple minor testing comments around mocking best practices. They don't need to hold up the PR, but hit me up if you'd ever like to talk about unit testing and mocking

2022-07-06 16:30 UTC, mcous commented on api/tests/opentrons/hardware_control/modules/test_hc_heatershaker.py
> +        yield simulating_module
Patching the private `_driver` property of the `HeaterShaker` test subject creates a [contaminated test subject](https://github.com/testdouble/contributing-tests/wiki/Partial-Mock#contaminated-test-subjects), which both reduces the value of this test _and_ couples the test to private implementation details.

Could we create a test subject using the public `driver` arg of `__init__` instead?

```python
    mock_driver = AsyncMock()
    module = HeaterShaker(..., driver=mock_driver, ...)
    try:
        yield module
    finally:
        await module.cleanup()
```

2022-07-06 16:30 UTC, mcous commented on api/tests/opentrons/hardware_control/modules/test_hc_heatershaker.py
> +    simulating_module_driver_patched._driver.get_rpm.side_effect = mock_get_rpm
If you use `AsyncMock`, you don't need to use `side_effect`, you can use `return_value` instead

(Alternatively, we use [Decoy](https://github.com/mcous/decoy) instead of `MagicMock` / `AsyncMock` over in robot-svcs land to preserve type safety and enforce mocking best practices. It's probably not worth pulling into this PR, because there's a learning curve coming from `MagicMock`, which lets you do a lot of silly and/or harmful things)

2022-07-06 17:24 UTC, sanni-t reviewed
Code looks good to me but I just tested a case which should result in an error response and raise an exception but it didn't so trying to figure out what's missing here. 

To test, I just reproduced the error outlined in [this](https://github.com/Opentrons/opentrons/issues/10858) bug report. The set shake command, when used the way outlined in the ticket, results in `ERR111:main motor:unable to move` error but it doesn't get raised. What gets raised is a `NoResponseError` after a response timeout from the serial connection.

2022-07-06 21:42 UTC, sanni-t commented
Did some quick investigation with @mcous on the above issue and narrowed down the problem source to this line in `SerialConnection._send_data`: https://github.com/Opentrons/opentrons/blob/a7c1796360f5a398a546de4b1887792f78c39fe9/api/src/opentrons/drivers/asyncio/communication/serial_connection.py#L163

The check for error happens after the check for ACK. Since H/S error responses don't contain ACKs, the error is never caught. Did a quick test by changing that line to 
```
if self._ack in response or self._error_keyword.encode() in response.lower():
```
and that raised the error but still took quite some time to surface.

2022-07-06 23:40 UTC, pmoegenburg commented
Closed Opentrons/opentrons#10858 with PR Opentrons/opentrons-modules#338, which is included in the newly created Heater-Shaker V0.4.6 release (https://github.com/Opentrons/opentrons-modules/releases/tag/heater-shaker%40v0.4.6). This will prevent the test you ran from throwing an error, but I agree that the underlying issue (sequencing of `_send_data`) still needs to be fixed.

2022-07-07 17:17 UTC, sanni-t commented on api/src/opentrons/drivers/asyncio/communication/serial_connection.py
> +            elif self._error_keyword.encode() in response.lower():
This will miss errors in a response that has an ACK

2022-07-07 18:37 UTC, pmoegenburg commented on api/src/opentrons/drivers/asyncio/communication/serial_connection.py
> +            elif self._error_keyword.encode() in response.lower():
No error responses have an ACK ("OK") in them, so is this alright?

2022-07-07 18:46 UTC, sanni-t commented on api/src/opentrons/drivers/asyncio/communication/serial_connection.py
> +            elif self._error_keyword.encode() in response.lower():
All the other modules have an ACK at the end of their error messages (TC definitely does, not 100% sure about temp and mag mods) . This `_send_data` is used by all so we'll have a problem for the other modules.
Even for heater-shaker, I'd say it leaves space for bugs to creep in if we're not looking for errors in all responses.

2022-07-08 19:55 UTC, pmoegenburg commented on api/src/opentrons/drivers/asyncio/communication/serial_connection.py
> +            elif self._error_keyword.encode() in response.lower():
Ah, good call, changed it to your suggested fix

2022-07-11 17:44 UTC, sanni-t commented on api/src/opentrons/drivers/asyncio/communication/serial_connection.py
> +            if self._ack in response or self._error_keyword.encode() in response.lower():
Wasn't a fan of this change initially but I don't think it should cause any problems. It is non-ideal to have to do these conversions at unexpected places like this and also affects readability but that would require refactoring other parts of this file which might be time-consuming.
@mcous do you have any concerns about `or` condition check?

2022-07-15 17:31 UTC, sanni-t commented
So it's still taking a very long time to detect the error once it's received. Looks to me like the culprit is this line in `_send_data`:
```
response = await self._serial.read_until(match=self._ack)
```
since there's no ack sent in the error message, I'm guessing the serial connection is waiting for ack until the serial timeout and then proceeding. I don't have a good solution for this right now but wondering if you or @sfoster1 do.

2022-07-15 18:08 UTC, sanni-t commented
Steps for testing:
1. Push this branch to a robot, connect h/s.
2. Start monitoring robot logs with `journalctl -b -f`
3. Send commands over HTTP. Make sure to specify `Opentrons-Version: 2` in the header for all commands. You can use the docs interface for sending these commands easily- `http://<your robot ip>:31950/docs`. Look for the `Simple Commands` & `Attached Modules` sections
 
a. Fetch the h/s module ID (different from module serial number) using HTTP `/modules` endpoint:
  ```
  GET http://{{robot_ip}}:31950/modules
  ```
  b. Using the module id fetched above, send an open latch command:
```
POST http://{{robot_ip}}:31950/commands
```
With the body:
```
{
    "data": {
        "commandType": "heaterShaker/openLabwareLatch",
        "waitUntilComplete": true,
        "params": {
            "moduleId": "<your module-id here>"
        }
    }
}
```
  c. Send a shake command:
```
POST http://{{robot_ip}}:31950/commands
```
Body:
```
{
    "data": {
        "commandType": "heaterShaker/setAndWaitForShakeSpeed",
        "waitUntilComplete": true,
        "params": {
            "moduleId": "<your module-id here>",
            "rpm": 600
        }
    }
}
```

You'll see in the robot logs that after the shake command the module doesn't respond for 40 seconds and then raises the expected error.

2022-07-17 21:43 UTC, pmoegenburg commented
Can we make that line `response = await self._serial.read_until()` since we check for self._ack and self._error_keyword in the response two lines later?

2022-07-19 14:29 UTC, sanni-t commented
Thanks for reverting the change on `read_until`. You might have noticed that it would've made the connection wait until timeout occurs while reading each response.

https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial.read_until

If we don't want the errors to have an ACK, I think a solution might be to write a different 'read_until' where we read each line until we see a match for ack while checking for the error keyword. So something like:

```
@dataclass(frozen=True)
class ResponseData:
    response: bytes
    has_ack: bool
    has_error: bool


async def read_until_match_or_error(match: bytes, error_keyword: bytes) -> ResponseData:
    """
    Read until match or error is found.
    """
    return await self._loop.run_in_executor(
            executor=self._executor,
            func=partial(self._self._sync_read_until_match_or_error, match=match, error_keyword=error_keyword),
        )

def _sync_read_until_match_or_error(self, match: bytes, error_keyword: bytes) -> ResponseData:
    """Synchronous method """
    response = b''
    result: ResponseData
    while not timed_out:    # Use an appropriate timeout
        response += self._serial.readline()
        if error_keyword in response:
            return ResponseData(response=response, has_error=True, has_ack=match in response)
        if match in response:
            return ResponseData(response=response, has_error=False, has_ack=True)
        
    # there's no match or error in this response but we still want to return it so that `_send_data` can log it
    # and raise a NoResponseError. Or we can refactor `_send_data` so that it uses this ResponseData more effectively       
    return ResponseData(response=response, has_error=False, has_ack=False)    
```

2022-07-19 18:43 UTC, pmoegenburg commented
Can't we just change the ACK to `\n` in the SerialConnection constructor?

2022-07-19 18:47 UTC, sanni-t commented
> Can't we just change the ACK to `\n` in the SerialConnection constructor?

No, because a full response can contain new lines. In such a case the serial connection will only read a part of the response and exit prematurely.

2022-07-26 16:46 UTC, sanni-t approved these changes
Tested on a robot w/ a heater-shaker on 0.4.7 firmware. Verified that error responses now get detected and are raised immediately.

Not tested: error detection for asynchronous errors. But it might take some time to test that so I'm going to add that as a TODO task for us during testing this week. This PR is good to merge.

2022-07-26 21:32 UTC, merged