style(app): phase II app styling revisions
OpenTrons/opentrons-api pull request #10767
Opened 2022-06-15 03:52 UTC by aptrons22

Phase II app styling revisions

#10488

# Overview

# Changelog

# Review requests

# Risk assessment

2022-06-19 04:46 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
> +              as="h7"
CI error is caused by this line because `h7` doesn't exist in html(h1-h6).
And this should be `label` from the design in Figam

2022-06-22 15:47 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
> +              as="h7"
Corrected.

2022-06-23 07:20 UTC, koji requested changes

2022-06-23 07:20 UTC, koji commented on app/src/molecules/JogControls/index.tsx
> -import {
Why do you need this change?
The current `release_6.0.0` doesn't have `SPACING`. I think what you need to do is to merge `release_6.0.0`

2022-06-23 07:20 UTC, koji commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
> +          css={TYPOGRAPHY.labelSemiBold}
Why don't you use `darkLinkPSemiBold` instead of `labelSemiBold`? If you use that, you don't need to pass `fontSize`, `color` and `opacity`. In addition you don't need to use opacity for `Icon` since Icon is wrapped by `Link`.

Currently `Link` is missing hover.

2022-06-23 07:20 UTC, koji commented on components/src/ui-style-constants/typography.ts
>  export const darkLinkPSemiBold = css`
This name should be `darkLinkLabelSemiBold` since the font size is `label`.
Or you can keep using the name and fontSizeP. Then you will need to pass `fontSize` when you use this for `EmptyStateLinks`

2022-06-23 07:20 UTC, koji commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
> +          <Flex alignItems={ALIGN_CENTER} css={TYPOGRAPHY.labelSemiBold}>
`css` don't need for this since already you added `labelSemiBold`

2022-06-23 07:20 UTC, koji commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
> +          css={TYPOGRAPHY.labelSemiBold}
same as above

2022-06-23 07:20 UTC, koji commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
> +          opacity="0.7"
same as above

2022-06-23 07:20 UTC, koji commented on components/src/primitives/Btn.tsx
> +  &:enabled {
These lines should be added to `atoms/buttons` because we extend this `NewSecondaryBtn` in that component.

2022-06-23 07:20 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +        css={TYPOGRAPHY.pSemiBold}
we don't need css since `EmptyStateLinks` doesn't use this.

2022-06-23 07:20 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +    align-items={TYPOGRAPHY.textAlignCenter}
Mel's feedback is about color so not sure why need this.
Actually `TYPOGRAPHY.textAlignCenter` is `center` but not for `align-items`.

2022-06-23 07:20 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +    align-items={TYPOGRAPHY.textAlignCenter}
same as above.
I think you need to add `background-color` to align with the design.

2022-06-23 07:20 UTC, koji commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
> +        as="label"
According to the design the text p-semiBold.
```suggestion
        as="p"
```

2022-06-23 07:20 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
> +                  css={COLORS.darkGreyEnabled}
```suggestion
                  color={COLORS.darkGreyEnabled}
```

2022-06-23 07:20 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
>                  <StyledText as="h6" marginBottom={SPACING.spacing3}>
This color should be the same as `{t('left_mount'}` so need `color={COLORS.darkGreyEnabled}`

2022-06-23 07:20 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
> +              as="label"
From Figma, L264 also `as=label`

2022-06-23 07:20 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
> +                marginRight={SPACING.spacing1}
We need to keep `spacing4`
![Screen Shot 2022-06-23 at 3 19 15 AM](https://user-images.githubusercontent.com/474225/175239555-41c10808-7a68-49e1-89d8-64fbd261793a.png)

2022-06-23 12:36 UTC, jerader requested changes

2022-06-23 12:36 UTC, jerader commented on app/src/atoms/buttons/index.tsx
> +  &:enabled {
enabled is the default css class, so you can moved `background-color: ${COLORS.transparent};` up to line 92

2022-06-23 12:36 UTC, jerader commented on app/src/molecules/JogControls/index.tsx
> -import {
Yeah, I agree, this change should already be in `release_6.0.0`. You should do a `git log` to see what your history looks like but something doesn't seem right.

2022-06-23 12:36 UTC, jerader commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +    background-color={COLORS.transparent}
same comment as above, this `background-color={COLORS.transparent}` can be moved to line 55

2022-06-23 13:26 UTC, aptrons22 commented on app/src/molecules/JogControls/index.tsx
> -import {
Hello Koji/Jethary, the revised file also does not have SPACING already.  Thanks

2022-06-23 13:43 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
> +          css={TYPOGRAPHY.labelSemiBold}
Corrected.

2022-06-23 13:49 UTC, aptrons22 commented on components/src/ui-style-constants/typography.ts
>  export const darkLinkPSemiBold = css`
Corrected as well.  Thanks

2022-06-23 13:50 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
> +          <Flex alignItems={ALIGN_CENTER} css={TYPOGRAPHY.labelSemiBold}>
Corrected.

2022-06-23 13:51 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
> +        as="label"
Corrected.

2022-06-23 13:53 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
> +                  css={COLORS.darkGreyEnabled}
Corrected as well.

2022-06-23 13:56 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
>                  <StyledText as="h6" marginBottom={SPACING.spacing3}>
Done.  Thanks

2022-06-23 13:57 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
> +              as="label"
Done. Thanks

2022-06-23 13:58 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
> +                marginRight={SPACING.spacing1}
Corrected.

2022-06-23 14:00 UTC, aptrons22 commented on app/src/atoms/buttons/index.tsx
> +  &:enabled {
Done.  Thanks

2022-06-23 14:02 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +    background-color={COLORS.transparent}
Completed as well.  Thanks

2022-06-23 14:03 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx
> +          css={TYPOGRAPHY.labelSemiBold}
Resolved.  Thanks

2022-06-23 14:04 UTC, aptrons22 commented on app/src/molecules/JogControls/index.tsx
> -import {
The current file does not have SPACING.  Thanks

2022-06-23 21:27 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +    align-items={TYPOGRAPHY.textAlignCenter}
Corrected.

2022-06-23 21:28 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +    align-items={TYPOGRAPHY.textAlignCenter}
Resolved.

2022-06-23 21:40 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +        css={TYPOGRAPHY.pSemiBold}
Not sure what you mean here.  In EmptyStateLinks css is referenced.  Thanks

2022-06-23 21:51 UTC, aptrons22 commented on components/src/primitives/Btn.tsx
> +  &:enabled {
Done.  Thanks

2022-06-23 23:14 UTC, mmencarelli commented
**Round 3, T1 Protocols Page**

[Link to annotated frame in Figma](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=14683%3A419033)

- [ ] (1) Button needs some attention. Currently barely visible and the states need updating. *
- [ ] (2) Still missing the enabled state *
- [ ] (3) Still need to update 'sort by' text to our darkGreyEnabled *
- [ ] (4) Still missing missing the hover state for the protocol cards. Check the design system for info *
- [ ] (5) Revert the colour of the subtext to our darkGreyEnabled, only the headline should be #707075
- [ ] (6) Still need to update the spacing here between header and text below to .25 rem *
- [ ] (7) Update the colour of this text to what the design has 
- [ ] (8) Still needs: The columns should have a min-width of 170px so regardless of what content is in them, the columns will always align. These columns should be responsive when the user shrinks the viewport. Maybe align with @koji on this since he's been working on the device cards on the T1 Devices page which should follow the same pattern. *
- [ ] (9) Still needs: Update text should align to the bottom of the other containers to the left. *
- [ ] (10) open menu should be placed 4px below the menu icon, placing a screenshot of what it should look like here
- [ ] (11) Update these links to the colour in our designs 
- [ ] (12) Missing space above the open sort by menu
- [ ] (13) Move updated column further to the right, it should have 1rem of spacing with the right hand side of its container and the card container
- [ ] (14) Update the colour in this text on loading state 
- [ ] (15) Can you let me know what's happening with the skeleton loader? 

I also want to note that 7 of the tasks have been marked with a *. These are tasks that were marked completed but when I check the branch, I cannot see the change. Can you let me know what's going on there? 

<img width="1239" alt="Screen Shot 2022-06-23 at 4 11 54 PM" src="https://user-images.githubusercontent.com/54682054/175429981-05ca8990-3ed3-4f95-a8bc-bd015e194467.png">

<img width="963" alt="Screen Shot 2022-06-23 at 4 12 06 PM" src="https://user-images.githubusercontent.com/54682054/175429999-b9c503b3-4f71-4437-8dcb-5770cdea11ed.png">

<img width="240" alt="Screen Shot 2022-06-23 at 4 12 12 PM" src="https://user-images.githubusercontent.com/54682054/175430004-82e17623-2b63-4dec-a375-3cf3f009fa87.png">

2022-06-23 23:14 UTC, mmencarelli requested changes
Changes requested above

2022-06-23 23:24 UTC, mmencarelli commented
Round 2 feedback on the empty state of the T1 Protocols page. First round can be found on #10208

[Annotated Figma frame link](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=14683%3A419869)

- [ ] (1) Update this text to our h1 style 
- [ ] (2) Add in margin between h1 and p copy 
- [ ] (3) Can you add in our hover state for our blue links for the word "browse"? 
- [ ] (4) I'm assuming fixing these links for the main page would fix these here too
- [ ] (5) Center this entire section to the middle of the page (see purple rectangle)


<img width="755" alt="Screen Shot 2022-06-23 at 4 24 32 PM" src="https://user-images.githubusercontent.com/54682054/175430944-005a6373-3a12-45f1-bf03-8aa043bb54ec.png">

2022-06-27 17:33 UTC, jerader requested changes

2022-06-27 17:33 UTC, jerader commented on app/src/atoms/buttons/index.tsx
> +    box-shadow: none;
I think `enabled` pseudo class can be removed and it's contents (line 116-118) moved up to the default state which is lines 93-99

2022-06-27 17:33 UTC, jerader commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
> +                <StyledText as="p" marginTop={SPACING.spacing2}>
this `marginTop` makes the left and right mount data unevenly aligned. Not sure what the purpose of it is.

<img width="918" alt="Screen Shot 2022-06-27 at 1 24 42 PM" src="https://user-images.githubusercontent.com/66035149/175999582-8a14ea6f-f516-4428-9959-a084c82a2c56.png">

2022-06-27 17:33 UTC, jerader commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
> +                color={COLORS.darkGreyEnabled}
don't add this here, it will make the entire `Right Mount` + the pipette there the same color.

2022-06-27 17:33 UTC, jerader commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
> +                <StyledText as="p" min-width="10.625rem">
this `min-width` doesn't do anything. The correct notation is `minWidth`

2022-06-27 17:33 UTC, jerader commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +   }
this should be:

`alignItems={ALIGN_CENTER}`

remove the `enabled`

2022-06-27 17:33 UTC, jerader commented on components/src/primitives/Btn.tsx
> -  background-color: ${Styles.C_WHITE};
you shouldn't be changing the button component. This button is used all over the place and we might still want the background color to be white in other areas it is used. Instead, change it directly in the component is it being used in.

2022-06-27 18:40 UTC, mmencarelli commented on components/src/primitives/Btn.tsx
> -  background-color: ${Styles.C_WHITE};
wait, are we sure? secondary button will always not have a white background. would be great to make that change app-wide

2022-07-06 21:03 UTC, closed without merging