refactor(app): adjust modal UI and create Confirm CL deletion modal
OpenTrons/opentrons-api pull request #10762
Opened 2022-06-14 18:06 UTC by jerader

closes #10631

# Overview

This PR tweaks a handful of modals mentioned in the ticket and creates the Confirm custom labware deletion modal

# Changelog

- added a new alert icon
- updated screenshot
- edit `Modal`
- create a Custom Labware Overflow menu test

# Review requests

- review figma, does it match designs?

# Risk assessment

low

2022-06-14 19:09 UTC, koji approved these changes
Looks good to me!
I left a couple of comments but they are small things.
I think if we could get one more reviewer, it would be good.

2022-06-14 19:09 UTC, koji commented on app/src/organisms/Devices/RobotSettings/AdvancedTab/AdvancedTabSlideouts/FactoryResetModal.tsx
>                  {t('factory_reset_modal_confirm_button')}
Sorry, there was a miscommunication on this button.
The recent button label is `Yes, clear data and restart robot`

2022-06-14 19:09 UTC, koji commented on app/src/organisms/Labware/CustomLabwareOverflowMenu.tsx
> +                marginTop="24px"
Let's use `SPACING.spacing5`

2022-06-14 19:09 UTC, koji commented on app/src/organisms/Labware/CustomLabwareOverflowMenu.tsx
> +                  fontWeight={TYPOGRAPHY.fontWeightSemiBold}
`TYPOGRAPHY.linkPSemiBold` includes `fontWeightSemiBold` so we don't need this.

2022-06-14 19:09 UTC, koji commented on app/src/atoms/Modal/index.tsx
> +                name="ot-alert"
Do you know the difference between `alert-circle` and `ot-alert`?
I don't find the diff 😂

2022-06-14 19:13 UTC, jerader commented on app/src/organisms/Labware/CustomLabwareOverflowMenu.tsx
> +                marginTop="24px"
oh yup thanks! I forgot that I didn't convert that to our SPACINGs

2022-06-14 19:15 UTC, jerader commented on app/src/atoms/Modal/index.tsx
> +                name="ot-alert"
haha, one of Mel's AC + me staring at the icon convinced me that we didn't add the new alert icon. Maybe there is not a difference, I will ask around to see what others think 😅

2022-06-17 13:06 UTC, vabruzzo approved these changes
looks good to me 👍

2022-06-22 16:46 UTC, mmencarelli commented
r2 feedback on modal's 

**Modal-wide edits**

- [x] (1) Change the padding of `.nkZbU` to: 1rem 1.5rem; (16px top and bottom, 24px r/left). 
- [x] (2) Change the padding of `.hJTtDI` to: 1rem 1.5rem 1.5rem 1.5rem; 
<img width="411" alt="Screen Shot 2022-06-22 at 9 42 56 AM" src="https://user-images.githubusercontent.com/54682054/175092010-2bbb8bf7-c78a-43a9-8381-f5fcfb5a46cb.png">

**Why is this robot unavailable?**
- [x] (1) Missing ")." at the end of content!
<img width="537" alt="Screen Shot 2022-06-22 at 12 30 21 PM" src="https://user-images.githubusercontent.com/54682054/175092736-dd3b1045-736c-4482-9afd-60e6b168a364.png">


**Delete labware def**
- [x] (1) remove the box-shadow from button on hover
<img width="390" alt="Screen Shot 2022-06-22 at 9 43 01 AM" src="https://user-images.githubusercontent.com/54682054/175092038-a85dd48a-73c1-40fc-94cd-a0dd91de4b9a.png">

**Reset to factory settings**
- [x] (1) Woops! Add in 1.5rem spacing between content and button
- [x] (2) remove box-shadow from button on hover

<img width="400" alt="Screen Shot 2022-06-22 at 9 44 56 AM" src="https://user-images.githubusercontent.com/54682054/175092356-b0315761-53b7-46eb-9cef-ec0c381609d9.png">

2022-06-22 16:48 UTC, mmencarelli requested changes, later dismissed
Changes requested above

2022-06-22 18:09 UTC, jerader commented
The round 2 work will be completed in this ticket: https://github.com/Opentrons/opentrons/issues/10866

2022-06-22 18:10 UTC, merged