fix(app): fix connect robot via ip address functionality and style
OpenTrons/opentrons-api pull request #10784
Opened 2022-06-15 20:28 UTC by koji

# Overview
This will fix the timing of `startDiscovery`(#10593) and conditional rendering of the refresh and try again button(#10594). In addition, this PR will fix the styling feedback that is pointed out in #10618

# Changelog
- Add useEffect to run `startDiscovery` when a user opens the slideout
- Fix conditional rendering part for the blue link button 
- Remove unnecessary expect() from test code (This test code was my first test cases and used expect() for text display tests)

# Review requests
- When opening the slideout, startDiscovery starts. (When the app starts, `startDiscovery` is called. To check this, please open the slideout  30s after starting the app
- When adding `localhost` or robot IP address, the status `available` and the slideout `refresh` button
- When adding a non-existing IP address or hostname, the status `not found` and the slideout shows `try again` button.

After checking this, please make sure that the slideout displays `localhost`. If you remove `localhost` from the slideout, the app won't recognize your dev robot-server.

# Risk assessment
- low

2022-06-16 16:05 UTC, jerader reviewed
functionality seems good to me, I just left a few comments about the style.

2022-06-16 16:05 UTC, jerader commented on app/src/organisms/AppSettings/ConnectRobotSlideout.tsx
> +        <IpHostnameList
there's a bit of a weird formatting issue here, the Ip hostname list has a slight left margin compared to the rest of the text in the slideout

<img width="316" alt="Screen Shot 2022-06-16 at 11 58 18 AM" src="https://user-images.githubusercontent.com/66035149/174114197-a31d3561-63a2-4d2e-a308-88b2c471c622.png">

2022-06-16 16:05 UTC, jerader commented on app/src/organisms/AppSettings/ManualIpHostnameForm.tsx
> +  background-color: ${COLORS.white};
maybe there should be a padding around where you enter the text so the cursor isn't at the very end. Also, how come you didn't use the `InputField` component in the Apps folder instead?

<img width="312" alt="Screen Shot 2022-06-16 at 12 02 30 PM" src="https://user-images.githubusercontent.com/66035149/174115102-13ac2b9e-7cb4-4acf-bccc-08d2238da6a9.png">

2022-06-16 16:05 UTC, jerader commented on app/src/organisms/AppSettings/__tests__/ConnectRobotSlideout.test.tsx
> +    findByText('Not Found')
this is cool, I have never used `findByText` before!

2022-06-16 16:08 UTC, koji commented on app/src/organisms/AppSettings/__tests__/ConnectRobotSlideout.test.tsx
> +    findByText('Not Found')
I think when we need to `async` for a test case, `findByText` will be good.

2022-06-17 15:28 UTC, koji commented on app/src/organisms/AppSettings/ManualIpHostnameForm.tsx
> +  background-color: ${COLORS.white};
5.0.2 is using `formik` and Brian recommended to keep using that for this slidout.

2022-06-23 17:58 UTC, jerader approved these changes
you forgot to delete a comment and looks like you have some merge conflicts. But otherwise lgtm!

2022-06-23 17:58 UTC, jerader commented on app/src/organisms/AppSettings/ManualIpHostnameForm.tsx
> +      // setMostRecentAddition(ip)
left over comment here

2022-06-23 21:58 UTC, mmencarelli commented
**Round 2 Feedback on 'Connect a Robot via IP Address' slideout**

Annotated figma frame here. 


- [ ] (1) Increase button size to 24px vs the 20px it's at 
- [ ] (2) Change this font size to our 'label' styling. So it should be 11px vs the 13px it's at 
- [ ] (3) Align the various states for our text field with the design system (image of side by side comparison outlining the differences included in this PR and in figma if you want to go into the designs). Hover, activated, error and focus-visible need some attention
- [ ] (4) Let's have 8px margin-left on the actual input text so it's not so close to the left hand side 
- [ ] (5) Let's remove the margin-top: 4px on the error text actually. 
- [ ] (6) Are we able to get this text to be a countdown? If it's not in scope, then static text is fine. If that's the case, then please confirm that we're capturing that future change for a later release. Don't want it to fall between the cracks. Also, can we capitalize "searching" so it's "Searching"
- [ ] (7) Update colour of spinner to darkGreyEnabled
- [ ] (8) Can we change this text string to "Not Found" 
- [ ] (9) Can we reverse the order of display here, so any available connections automatically appear at the top? The logic on top of that is that it's in order of user search. 
- [ ] (10) Can we add margin: 4px 0px; to `.mWBlO`
- [ ] (11) Missing hover state on the "refresh" button
- [ ] (12) remove the box-shadow from the button
- [ ] (13) increase font size on the button to 11px (currently around 9px) 


<img width="576" alt="Screen Shot 2022-06-23 at 2 57 36 PM" src="https://user-images.githubusercontent.com/54682054/175419899-1bf1d21a-cd7a-4268-bc8d-b0ff9669855a.png">
<img width="680" alt="Screen Shot 2022-06-23 at 2 57 46 PM" src="https://user-images.githubusercontent.com/54682054/175419971-45006067-a342-4c01-92c7-1d57e6926fa6.png">

2022-06-23 21:58 UTC, mmencarelli requested changes
changes requested above!

2022-06-23 22:29 UTC, merged