style(app): Address device landing design feedback
OpenTrons/opentrons-api pull request #10809
Opened 2022-06-16 20:07 UTC by koji

# Overview
This PR will fix #10611 

# Changelog
- Update styling to align with design feedback
- Add SecondaryTertiaryButton to atoms/buttons

# Review requests
- mount and modules
[before]
![device_landing_before](https://user-images.githubusercontent.com/474225/174154660-3e4e687a-4736-4940-845a-8a13ea349b90.png)

[after]
![device_landing_after](https://user-images.githubusercontent.com/474225/174154811-0b53468d-0506-42f1-8b29-11fad8877c79.png)

- `Go to run` button is updated on device landing and device details
https://www.figma.com/file/l7BAJAGICr10ELsSqQD0Sr/Design-System?node-id=1782%3A83236

![Screen Shot 2022-06-16 at 4 06 51 PM](https://user-images.githubusercontent.com/474225/174155237-3005aade-ee92-443f-be3a-318e34d3d91a.png)

![Screen Shot 2022-06-16 at 11 40 51 AM](https://user-images.githubusercontent.com/474225/174154897-904ec131-0da8-4cbd-9bcb-487ea02b31be.png)

# Risk assessment
low

2022-06-20 18:31 UTC, vabruzzo commented on app/src/organisms/Devices/RobotCard.tsx
> +        // marginBottom={SPACING.spacing1}
probably meant to remove?

2022-06-20 18:31 UTC, vabruzzo commented on app/src/pages/Devices/DevicesLanding/NewRobotSetupHelp.tsx
> +// const ACCORDION_STYLE = css``
remove also?

2022-06-20 18:32 UTC, vabruzzo approved these changes
just a couple of comments i think are unnecessary, otherwise looks good!

2022-06-21 17:05 UTC, koji commented on app/src/organisms/Devices/RobotCard.tsx
> +        // marginBottom={SPACING.spacing1}
good catch!

2022-06-22 18:11 UTC, mmencarelli commented
**Devices Landing Page Feedback**

[Link to annotated frame on Figma](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=14570%3A372231)

- [ ] (1) Up this margin to 1.5rem 
- [ ] (2) Update the button overflow icon. Work with @jerader if needed for assistance, they just unlocked it in their most recent work. 
- [ ] (3) Update colour of this text to match designs
- [ ] (4) When I adjust the copy to reflect our longest named pipette, it breaks onto two lines. Should be on one still!
- [ ] (5) Can these columns not go onto 2 lines unless the screen size is very small? There's space on the card still for it to be on one line
- [ ] (6) When I click 'run a protocol', it opens up the slideout but doesn't close the menu 
- [ ] (7) There's a bit of extra space here. Hard for me to figure out what's going on but feel free to compare to the designs below in the figma frame
- [ ] (8) Pop this fixed bottom of frame with a margin-bottom of 40px 
- [ ] (9) Remove box-shadow from primary btn
- [ ] (10) Nix these two (available/unavailable) when in discovery mode 
- [ ] (11) Update styling and location of this link 
- [ ] (12) Update size and colour of the spinner
- [ ] (13) remove the '...' 

<img width="639" alt="Screen Shot 2022-06-22 at 11 09 55 AM" src="https://user-images.githubusercontent.com/5468
<img width="467" alt="Screen Shot 2022-06-22 at 11 10 15 AM" src="https://user-images.githubusercontent.com/54682054/175107189-cbb0b83e-a307-409d-a8fc-bf04084c543f.png">
2054/175107132-511886fa-c6cc-40d9-9930-8b7f2f344754.png">

<img width="535" alt="Screen Shot 2022-06-22 at 11 10 10 AM" src="https://user-images.githubusercontent.com/54682054/175107211-f6e3e541-3170-496f-a55b-96beec000100.png">

<img width="882" alt="Screen Shot 2022-06-22 at 11 10 41 AM" src="https://user-images.githubusercontent.com/54682054/175107293-909076c3-b3fc-4d1d-93d1-40bd88a20a5d.png">

<img width="884" alt="Screen Shot 2022-06-22 at 11 10 46 AM" src="https://user-images.githubusercontent.com/54682054/175107320-640fd65e-8c99-4681-86c8-9e7868596d20.png">
<img width="721" alt="Screen Shot 2022-06-22 at 11 11 16 AM" src="https://user-images.githubusercontent.com/54682054/175107378-b2aa173b-10a3-4fca-b1a8-f0351cbd3e96.png">
<img width="735" alt="Screen Shot 2022-06-22 at 11 11 20 AM" src="https://user-images.githubusercontent.com/54682054/175107393-48415ba5-41a5-4671-882f-c40782640bae.png">

2022-06-22 18:12 UTC, mmencarelli requested changes
changes requested above!

2022-06-23 14:35 UTC, koji commented
![Screen Shot 2022-06-23 at 10 35 11 AM](https://user-images.githubusercontent.com/474225/175325285-2162258d-a784-4a71-9e05-9ff15aefea27.png)

2022-06-23 18:20 UTC, koji commented
(6) needs some modification and Ayana is working on that.

2022-06-23 21:29 UTC, koji commented
The rest, no.5 will be solved in another PR.

2022-06-23 23:06 UTC, merged