style(app): fixed the svg sizing on the protocol card
OpenTrons/opentrons-api pull request #10838
Opened 2022-06-17 20:40 UTC by aptrons22

# Overview

Fixed the svg sizing on the protocol card

PR will resolve #10555

# Changelog

- Fixed the viewport sizing for the svg on the protocol card.

# Review requests

Low

# Risk assessment
Low

2022-06-21 13:54 UTC, koji requested changes
Not centralized
Seems that you would move a thumbnail to the upper right 
https://user-images.githubusercontent.com/474225/174816475-665c869e-de1c-4c93-9dba-f4c52774b23f.mov

2022-06-21 13:56 UTC, jerader requested changes
same comment as Koji: looks like you have some extra space at the bottom of the SVG viewbox causing the overall Protocol card to have extra space.

<img width="136" alt="Screen Shot 2022-06-21 at 9 56 48 AM" src="https://user-images.githubusercontent.com/66035149/174817400-651074f2-fbab-4a5d-80a4-35234aad9637.png">

2022-06-21 18:27 UTC, koji reviewed
` viewBox="-48 -20 550 480"` would be slightly better on a protocol details page.
But let's wait for @mmencarelli 's review.

2022-06-21 18:44 UTC, jerader commented
The viewbox should be adjusted more - in the Protocol Details page if you have a module loaded, it gets cut off.

<img width="349" alt="Screen Shot 2022-06-21 at 2 39 11 PM" src="https://user-images.githubusercontent.com/66035149/174873953-bc431d6c-511d-4f79-9050-56fb3859b550.png">

Let's defer to @mmencarelli but maybe `viewBox="-68 -20 550 480"`? cc: @koji

2022-06-21 19:18 UTC, koji commented
@mmencarelli 
The current code `viewBox="-50 -20 550 480"`
There are other 2 options.
- `viewBox="-48 -20 550 480"`
- `viewBox="-68 -20 550 480"`

If you open the following file by an editor and change line46, you will see them.
app/src/molecules/DeckThumbnail/index.tsx

Maybe this is too much. If so, let us know. We can support you to check all options.

2022-06-21 19:30 UTC, aptrons22 commented
@koji @jerader @mmencarelli Hello All, I think -48 looks the best.  I will post screenshots for -48 and -68. Thanks

Option -48:
![Screen Shot 2022-06-21 at 3 32 44 PM](https://user-images.githubusercontent.com/102996638/174882908-da4b4b02-a49f-42fe-a66e-63bc09b3ba04.png)
![Screen Shot 2022-06-21 at 3 37 21 PM](https://user-images.githubusercontent.com/102996638/174883591-66d1705b-e5e7-4118-893a-1521f31d90a4.png)

Option -68:
![Screen Shot 2022-06-21 at 3 34 31 PM](https://user-images.githubusercontent.com/102996638/174883129-7f5ec64e-fb17-44a0-a052-c0713fb87b01.png)
![Screen Shot 2022-06-21 at 3 35 53 PM](https://user-images.githubusercontent.com/102996638/174883484-c45b42be-3145-4617-8b96-6101cafacc7c.png)

2022-06-21 19:35 UTC, jerader commented
`viewBox="-48 -20 550 480"` cuts off the temperature module on the left side: 

<img width="122" alt="Screen Shot 2022-06-21 at 3 35 17 PM" src="https://user-images.githubusercontent.com/66035149/174883228-d9e7df18-54a5-4026-b015-c266425c542e.png">

2022-06-21 20:46 UTC, mmencarelli commented
Could whoever ends up working on this set up a call with me to work 1-on-1? Think it's a bit too hard to explain with text and screenshots.

2022-06-21 20:55 UTC, aptrons22 commented
@mmencarelli Hello Mel, I'm working on this issue.  I'm available to meet now if you are?  Thanks

2022-06-21 22:01 UTC, aptrons22 commented
@mmencarelli As per Mel we are putting this PR on hold.  Thanks

2022-06-30 23:50 UTC, koji commented
This svg issue will be fixed in another PR.

2022-06-30 23:50 UTC, closed without merging