feat(engine): heater-shaker movement restrictions
OpenTrons/opentrons-api pull request #10861
Opened 2022-06-22 14:52 UTC by jbleon95

# Overview
Addresses #10542

Adds a new class to check if movement is allowed when a heater-shaker is on the deck, raising an error if the movement is not allowed.

# Changelog
- Added new `HeaterShakerMovementFlagger` class, which given a labware (destination) and pipette ID will determine if the movement is allowed
- Added new `HeaterShakerMovementRestrictionError` that is raised if an illegal operation is attempted

# Review requests
- Code is based off of `ThermocyclerMovementFlagger` given that they are accomplishing similar goals. There may be areas of that that don't make sense for this ticket, and I've used my best judgement, but feedback on simplification/better ways of doing things is appreciated.
- Checking if a pipette is multi-channel wasn't a clear operation, I've used checking the `channels` key in the `PipetteDict`, but I'm unsure if that will flag during simulation.
- Name changes/consistency suggestions always appreciated.

# Risk assessment
Med, new code is isolated to a brand new class but it is used for every move to well operation..

2022-06-23 18:18 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/heater_shaker_restriction_flagger.py
> +        heater_shaker_module = next(
We should assume—at this layer, at least—that there can be multiple Heater-Shakers on the deck at once.

2022-06-23 18:18 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/heater_shaker_restriction_flagger.py
> +        if module.location is not None:
What does it mean for a module location to be `None`?

2022-06-23 18:18 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/heater_shaker_restriction_flagger.py
> +            return self._state_store.geometry.get_ancestor_slot_name(module.id)
Looks like we're passing a module ID where a labware ID is needed?

2022-06-23 18:18 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/heater_shaker_restriction_flagger.py
> +                if heater_shaker_hardware.status == HeaterShakerStatus.RUNNING and (
To look into:

1. Should we check `!= IDLE` instead of `== RUNNING` to account for `ERROR`?
2. Can we query Protocol Engine's pure virtual module state, instead of querying the hardware controller? This is how we validate a precondition in `temperatureModule/waitForTemperature`, for example. ([Code](https://github.com/Opentrons/opentrons/blob/fa6bf70fbc2c06c643725fdfca76c1c3e02f94a5/api/src/opentrons/protocol_engine/commands/temperature_module/wait_for_temperature.py#L60-L61).)

2022-06-23 18:18 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/heater_shaker_restriction_flagger.py
> +            # to avoid parsing a JSON definition every time a protocol when a
Typo

2022-06-23 18:18 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/heater_shaker_restriction_flagger.py
> +    """A helper for flagging unsafe movements around a Heater Shaker Module.
@sanni-t This follows the letter of https://github.com/Opentrons/opentrons/issues/10542, but do we also need to catch the inverse cases? For example, do we need to catch the case where a pipette is parked at some dangerous location, and then we activate the shaker?

2022-06-27 17:15 UTC, sanni-t commented on api/src/opentrons/protocol_engine/execution/heater_shaker_restriction_flagger.py
> +    """A helper for flagging unsafe movements around a Heater Shaker Module.
Good catch. I think we definitely want to catch the inverse case as much as the api allows us to, without having to implement a collision prevention functionality. But if it gets too hairy (which I think it might) then create a separate ticket for it to handle later. We can try to use the last known location but I'm worried that it doesn't always represent the current position of the pipette and that might lead to some problem cases.

2022-06-27 22:50 UTC, sanni-t requested changes
I think this is nearly there! Should definitely get the questions around analysis/ simulation of the noted cases tested if it's not clear whether they'll work. We can pair on testing it if needed.

2022-06-27 22:50 UTC, sanni-t commented on api/src/opentrons/protocol_engine/errors/exceptions.py
> +class HeaterShakerMovementRestrictionError(ProtocolEngineError):
I think calling this a "h/s movement restriction" might result in confusion. Can we call it `RestrictedPipetteMovementError` (or any other better names you can think of)?

2022-06-27 22:50 UTC, sanni-t commented on api/src/opentrons/protocol_engine/execution/heater_shaker_restriction_flagger.py
> +            heater_shaker_hardware = await self._find_heater_shaker_by_serial(
Does this simulate well for presence multiple heater-shakers?

2022-06-27 22:50 UTC, sanni-t commented on api/src/opentrons/protocol_engine/execution/heater_shaker_restriction_flagger.py
> +                    dest_east_west or dest_north_south
You cannot move pipette to h/s labware either. So basically just raise the error if H/S is shaking.

2022-06-27 22:50 UTC, sanni-t commented on api/tests/opentrons/protocol_engine/execution/test_heater_shaker_restriction_flagger.py
> +async def test_raises_any_channel_on_restricted_movement(
I think we can split this into latch status based restrictions and shake status based restrictions in order to cover all cases

2022-07-12 16:26 UTC, SyntaxColoring approved these changes
I think there's a couple of simplifications we can make, but this mostly looks good to me. Thanks!

Also, according to the discussion in https://github.com/Opentrons/opentrons/pull/10861#discussion_r907616282, I think we should also ticket the other direction of this problem—for example, raising an error if you park the pipette next to a Heater-Shaker and then start shaking.

2022-07-12 16:26 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/heater_shaker_restriction_flagger.py
> +                        )
If I'm reading this right, we can unindent lines 68-93 to take them out of the enclosing `if`-statement, since the enclosing `if`-statement is redundant with these conditions.

2022-07-12 16:26 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/heater_shaker_restriction_flagger.py
> +            return self._state_store.modules.get_location(module.id).slotName
Because of the way `self._state_store.modules.get_location()` works, I think this code is equivalent to:

```python
    def _resolve_location(self, module: LoadedModule) -> DeckSlotName:
        return self._state_store.modules.get_location(module.id).slotName
```

Also, this will raise `ModuleNotOnDeckError` if the module isn't loaded onto a deck slot.

I just chatted with @mcous, and it sounds like it's okay for us to not handle that exception. The only time the exception could be raised is when we're executing a live module command, outside of a run. (A module's location can't be `None` during Labware Position Check, nor during a protocol run.) And in that case, there are no pipette movements, so this code wouldn't be running, anyway.

*So,* I would simplify this to a call to `get_location()`, and I'd also leave a comment like:

```python
# Would raise ModuleNotOnDeckError if module is not loaded in any slot.
# But that can only happen for live module commands outside of a run,
# where this code will not run, anyway.
```

2022-07-12 17:22 UTC, mcous reviewed
Chatted in person, leaving notes as reminders

2022-07-12 17:22 UTC, mcous commented on api/tests/opentrons/protocol_engine/execution/test_movement_handler.py
> +def heater_shaker_movement_flagger(decoy: Decoy) -> HeaterShakerMovementFlagger:
Are we missing the top-level tests that confirm that this dependency is actually used as intended?

2022-07-12 17:22 UTC, mcous commented on api/tests/opentrons/protocol_engine/execution/test_heater_shaker_restriction_flagger.py
> +    )
I think we should try to restructure the `HeaterShakerMovementFlagger`. Ideally, we have two types of "units":

- Collaborator objects
- Logic objects

Talked about this in person:

- Try to move calls to `state_store` and `hardware_api` out of this unit and into `MovementHandler`
- The more we can make `HeaterShakerMovementFlagger` a logic unit, that consumes value objects and spits out results, the more robot our test suite will be

2022-07-14 16:41 UTC, laviera approved these changes

2022-07-14 19:21 UTC, SyntaxColoring reviewed
Lots of little nitpicky comments, and one more important thing about the tests...

2022-07-14 19:21 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/heater_shaker_movement_flagger.py
> +    is_tiprack: bool,
Suggested rename:

```suggestion
    destination_is_tip_rack: bool,
```

("Destination" for clarity. "Tip rack" being two words is a pedantic pet peeve of mine.)

2022-07-14 19:21 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/heater_shaker_movement_flagger.py
> +    for plate_shaking, latch_closed, heater_shaker_slot_int in heater_shaker_data:
Since `HeaterShakerMovementData` is defined outside this module, I would consider making it a `@dataclass(frozen=True)` instead of a `NamedTuple`, and accessing its attributes explicitly by name, instead of unpacking and relying on attribute order.

2022-07-14 19:21 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/heater_shaker_movement_flagger.py
> +)
I would consider moving these N/E/S/W functions to some shared place outside of `deck_conflict`. This is just a soft preference from me, though.

2022-07-14 19:21 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/heater_shaker_movement_flagger.py
> +                "Cannot move pipette to adjacent slot or Heater-Shaker while module is shaking"
Would this read slightly better?

```suggestion
                "Cannot move pipette to Heater-Shaker or adjacent slot while module is shaking"
```

2022-07-14 19:21 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/heater_shaker_movement_flagger.py
> +                    "Cannot move multi-channel pipette north or south of Heater-Shaker to non-tiprack labware"
Another readability suggestion, not sure if this is better.

```suggestion
                    "Cannot move multi-channel pipette to non-tip-rack labware north or south of Heater-Shaker"
```

2022-07-14 19:21 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/errors/exceptions.py
> +
I would consider scoping this exception name and description more narrowly to just Heater-Shaker restrictions, since we don't use this exception type for Thermocycler restrictions. See `ThermocyclerNotOpenError` above.

2022-07-14 19:21 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/heater_shaker_movement_flagger.py
> +        if is_multi_channel:
```suggestion
        elif is_multi_channel:
```

Just for consistency. This doesn't change the behavior.

2022-07-14 19:21 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/movement.py
> +        if hs_movement_data:
We discussed this in-person and you mentioned avoiding an unnecessary call to `get_hardware_pipette()` if `hs_movement_data` is `[]`.

After thinking about this a little more, I think we should drop this `if` statement. Running this code should be harmless if `hs_movement_data == []`, even if it is unnecessary. And I think if we give this function a uniform execution path, it will make it a little more readable and easier to cover by tests.

2022-07-14 19:21 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/modules.py
> +    def get_heater_shaker_movement_data(self) -> List[HeaterShakerMovementData]:
Brainstorming alternative names to avoid "data":

* `get_heater_shaker_movement_restrictors()`?

2022-07-14 19:21 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/types.py
> +    slot_location: int
Should we rename this to `slot` or `deck_slot`? `slot_location` feels redundant to me.

2022-07-14 19:21 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_engine/execution/test_movement_handler.py
> +async def test_move_to_well_restricted_by_heater_shaker(
It looks like when these tests are run, we will...

1. Call the subject `MovementHandler` production code, which will...
    1. Get data from a mock `ModuleView`, `GeometryView`, etc.
    2. Call the production `raise_if_movement_restricted_by_heater_shaker()` function with that mock data.
    3. Let the exception propagate.
2. Assert that the expected exception was raised.

But as a collaboration test, our pattern should be for it to work like this:

1. Call the subject `MovementHandler` production code, which will...
    1. Get data from a mock `ModuleView`, `GeometryView`, etc.
    2. Call a *mock* `raise_if_movement_restricted_by_heater_shaker()` function.
    3. Let the exception propagate, if any.
2. In the test, either...
    *  Verify that the subject `MovementHandler` called the mock `raise_if_movement_restricted_by_heater_shaker()` before it attempted to do any movements.
    * Or arrange for the mock `raise_if_movement_restricted_by_heater_shaker()` to raise something, and verify that the subject `MovementHandler` propagated that exception and never attempted to do any movements.

See how the other tests in this file work with `ThermocyclerMovementFlagger`, for example. This test should work the same way.

One difference is that since your function is free-standing and not in a class, you'll have to monkey-patch it instead of dependency-injecting it. See how `geometry/test_deck` mocks out `deck_conflict.check()` for an example.

2022-07-14 20:10 UTC, sanni-t reviewed
Looks really good! Just some nitpicks. 
I found the test names a bit confusing but you can ignore my suggestions if you don't agree.

I think testing that we're getting an exception raise due to the expected reasons is important though, since there's a lot happening in the function and it's raising the same error type.

2022-07-14 20:10 UTC, sanni-t commented on api/tests/opentrons/protocol_engine/execution/test_heater_shaker_movement_flagger.py
> +async def test_raises_when_shaking_on_restricted_movement(
```suggestion
async def test_raises_when_moving_to_restricted_slots_while_shaking(
```

2022-07-14 20:10 UTC, sanni-t commented on api/tests/opentrons/protocol_engine/execution/test_heater_shaker_movement_flagger.py
> +async def test_raises_when_latch_open_on_restricted_movement(
```suggestion
async def test_raises_when_moving_to_restricted_slots_while_latch_open(
```

2022-07-14 20:10 UTC, sanni-t commented on api/tests/opentrons/protocol_engine/execution/test_heater_shaker_movement_flagger.py
> +async def test_raises_multi_channel_on_restricted_movement(
```suggestion
async def test_raises_on_restricted_movement_with_multi_channel(
```

2022-07-14 20:10 UTC, sanni-t commented on api/tests/opentrons/protocol_engine/execution/test_heater_shaker_movement_flagger.py
> +        [4, False, pytest.raises(RestrictedPipetteMovementError)],  # east
I think to really make sure that the error is due to the expected reason, we should do a match on the error's text for all these tests.

2022-07-16 00:41 UTC, sanni-t approved these changes
Code looks great!
Tested this on a robot with the following setup and verified that correct errors are raised as described in the ticket!
<img width="973" alt="Screen Shot 2022-07-15 at 20 40 20" src="https://user-images.githubusercontent.com/8520173/179327420-c9346ca3-9ad8-415a-82dc-c7cbccb02495.png">

🙌 🎉🎉🎉🎉 🚢

2022-07-18 14:06 UTC, merged