refactor(engine): add error raising for h/s commands
OpenTrons/opentrons-api pull request #10872
Opened 2022-06-23 12:56 UTC by sanni-t

Closes #10814, Closes #10813

# Overview

Implements raising an error when performing these steps:
- setting a shake while labware latch is open
- opening the labware latch when h/s is shaking

Also updates the stateless module endpoint to use the actual state of the attached module and not a default initial state.

# Changelog

- updated `heaterShaker/openLabwareLatch` and `heaterShaker/setAndWaitForShakeSpeed` commands
- `AddModuleAction` now takes a module `substate` for initializing the module state
- updated `protocol_engine.use_attached_modules()` to fetch attached modules' substates

# Review requests

- Test using a simulator or real hardware and see if the error raises when it should and doesn't when it shouldn't. Check that the tests written by @y3rsh in the bug tickets above now pass. Test for both jsonv6 protocol & stateless commands
- Any code improvement suggestions

# Risk assessment

Low. Mostly tries to fix buggy/ missing behavior of module commands.

2022-06-23 12:58 UTC, sanni-t commented on api/tests/opentrons/protocol_engine/test_protocol_engine.py
> +                ),
Should test adding thermocycler & h/s too

2022-06-23 13:31 UTC, ecormany reviewed
Left some copy suggestions for the error text.

2022-06-23 13:31 UTC, ecormany commented on api/src/opentrons/protocol_engine/state/module_substates/heater_shaker_module_substate.py
> +                f"Cannot perform the module action when labware latch open or in error."
The "or in error" part here is confusing (and I think far less likely to be the case). Since the following line will report the `error` status if that's the actual problem, I think it's better to simplify the language here. Also, I believe this only applies to shakes — you can set the temperature when the latches are open.
```suggestion
                f"The Heater-Shaker can't start shaking while the labware latch is open."
```

2022-06-23 13:31 UTC, ecormany commented on api/src/opentrons/protocol_engine/state/module_substates/heater_shaker_module_substate.py
> +                f"Cannot perform the module action when module is shaking or in error."
Similar to above (this is the converse case)
```suggestion
                f"The Heater-Shaker can't open its labware latch while it is shaking."
```

2022-06-23 13:31 UTC, ecormany commented on api/src/opentrons/protocol_engine/state/module_substates/heater_shaker_module_substate.py
> +                f" Current latch status is: {self.speed_status.value}"
Typo here.
```suggestion
                f" Current shaking status is: {self.speed_status.value}"
```

2022-06-23 21:45 UTC, sanni-t commented
Tested with dev server+ simulated modules and on a robot with a heater-shaker attached and the module state in engine always reflected the true state of the attached module. H/S errors were also raised as expected.

2022-06-27 13:29 UTC, sanni-t commented on api/tests/opentrons/protocol_engine/test_protocol_engine.py
> +async def test_use_attached_tc_and_hs_modules(
Testing all modules in one test would have been a really long test so ended up making this split. It was also a bit difficult to parametrize since each module has different substates.. so different modules would have required stubs of different properties.

2022-06-27 18:29 UTC, mcous requested changes, later dismissed
Can we change this so the module substates don't end up in action payloads? That big if/else ladder in `ProtocolEngine` is a bit of a warning sign

2022-06-27 18:29 UTC, mcous commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +    def _get_module_substate_data(
This is a warning sign to me. The `ProtocolEngine` class should have _very_ little logic defined in it. I think the creation of these module substates is best left to the module store

2022-06-27 18:29 UTC, mcous commented on api/src/opentrons/protocol_engine/actions/actions.py
> +    substate: Optional[ModuleSubStateType]
Module substates are an implementation detail of the `ModuleStore`; I don't think they belong in the actions. Could this be the live data dict from the module's HardwareAPI, instead?

2022-06-27 19:27 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/errors/exceptions.py
> +class CannotPerformModuleAction(ProtocolEngineError):
```suggestion
class ModuleActionNotAllowedError(ProtocolEngineError):
```

2022-06-27 19:30 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +        # This shouldn't happen
did this slip here by mistake? or is this a patch incase there is no matching submodule state? if this needs to stay maybe change the comment?

2022-06-27 19:31 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +        # This shouldn't happen
or raise a not implemented exception ?

2022-06-27 19:33 UTC, sanni-t commented on api/src/opentrons/protocol_engine/actions/actions.py
> +    substate: Optional[ModuleSubStateType]
Hmm... that might work. Giving it a try

2022-06-27 20:41 UTC, y3rsh commented
Having an issue with the happy path on commit `e35b421ff`

### **test steps** 

1. deactivate the heater (validate command 201 and comand status == succeeded)
2. close the latch (validate command 201 and comand status == succeeded)
3. stop shake (validate command 201 and comand status == succeeded)
4. wait 2 seconds
5. get module data
6.  assert shake_speed_in_range(hs_module_data["data"]["currentSpeed"], 0)
7. assert hs_module_data["data"]["temperatureStatus"] == "idle"
8. assert hs_module_data["data"]["labwareLatchStatus"] == "idle_closed"
9. try to shake 400 rpm
Get this error but I shouldn't because just validated the status of the latch is closed.
```log
POST http://192.168.50.89:31950/runs/1819076e-33f6-48e8-8120-b9fb9ec29ea0/commands?waitUntilComplete=true&timeout=59000
0.062104{
    "data": {
        "id": "1bb4bace-ca9e-4879-86f7-3fbcae554ec9",
        "createdAt": "2022-06-27T20:23:28.794737+00:00",
        "commandType": "heaterShaker/setAndWaitForShakeSpeed",
        "key": "1bb4bace-ca9e-4879-86f7-3fbcae554ec9",
        "status": "failed",
        "params": {
            "moduleId": "a83c65e79b3713c851b133533757b10ec8cb2d95",
            "rpm": 400.0
        },
        "error": {
            "id": "6b151e65-7e92-4f55-86d4-e18919e7b670",
            "errorType": "CannotPerformModuleAction",
            "createdAt": "2022-06-27T20:23:28.801133+00:00",
            "detail": "The Heater-Shaker can't start shaking while the labware latch is open. Current latch status is: idle_unknown"
        },
        "startedAt": "2022-06-27T20:23:28.796574+00:00",
        "completedAt": "2022-06-27T20:23:28.801133+00:00",
        "intent": "setup"
    }
}
```

2022-06-27 22:56 UTC, sanni-t commented on api/src/opentrons/protocol_engine/errors/exceptions.py
> +class CannotPerformModuleAction(ProtocolEngineError):
Hmm. That sounds good too. But will need to update this error name in PAPIv2 as well. I'll see if it's a quick change

2022-06-27 22:59 UTC, sanni-t commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +        # This shouldn't happen
No, it's just a comment about the next line that it should never actually execute but helps tie up the if else ladder without leaving any cases unaccounted for. We follow this pattern in a few places in the engine. I'll make the comment clearer. Thanks!

2022-06-29 14:12 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/errors/exceptions.py
> +class CannotPerformModuleAction(ProtocolEngineError):
oh sorry! I did not notice we are already using this is PAPIV2... whatever works :-)

2022-06-29 14:13 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +        # This shouldn't happen
Thank you foe explaining that!

2022-06-30 14:21 UTC, mcous reviewed
One last change request and I think this is good to go. I don't think we should mirror the computed `speedStatus` nor `labwareLatchStatus` fields in the heater shaker substate. Instead, we should follow our existing patterns and use fields that can be explicitly set and unset by ProtocolEngine commands.

So, instead, I think the substate should add:

- Target shake speed (to be later set by `SetTargetSkakeSpeed` and `DeactivateShaker` commands)
- Lid open/closed flag (to be later set by `OpenLabwareLatch` and `CloseLabwareLatch`)

Both these fields can be fed by `liveData` in the same manner, but avoid pitfalls (and potentially misaligned expectations) that we might run into trying to mirror status fields reported by the Hardware API in the engine, especially given the Hardware API _will still error_ if the module is not in the right state

2022-06-30 14:21 UTC, mcous commented on api/src/opentrons/protocol_engine/state/modules.py
> +                plate_target_temperature=live_data["targetTemp"] if live_data else None,  # type: ignore[arg-type]
Can these get wrapped in parentheses for readability? Or maybe this mapping can be moved to helper functions?

Gonna avoid dropping a GitHub "Suggestion" in here due to some other comments I have in this review around not wanting `labware_latch_status` and `speed_status` in the ProtocolEngine state, but comment still applies if we swap these out

2022-06-30 14:21 UTC, mcous commented on api/tests/opentrons/protocol_engine/commands/heater_shaker/test_open_labware_latch.py
>      decoy.verify(await hs_hardware.open_labware_latch(), times=1)
I think it's important to verify call order here:
```suggestion
    decoy.verify(
        hs_module_substate.raise_if_shaking(),
        await hs_hardware.open_labware_latch(),
    )
```

2022-06-30 14:21 UTC, mcous commented on api/tests/opentrons/protocol_engine/commands/heater_shaker/test_set_and_wait_for_shake_speed.py
> +    decoy.verify(hs_module_substate.raise_if_labware_latch_not_closed(), times=1)
Same call order comment here

2022-06-30 14:21 UTC, mcous commented on api/src/opentrons/protocol_engine/state/module_substates/heater_shaker_module_substate.py
> +        if self.speed_status != SpeedStatus.IDLE:
Should we be checking plate target speed instead? It seems to fit in more cleanly with our existing substate (which includes `plate_target_temperature`). Checking the status seems to set this expectation that we'll be trying to mirror the heater shaker status in the ProtocolEngine state, which I'd like to avoid if we can.

This logic as written looks difficult to extend to real protocol runs rather than live commands. Target temperature and target speed, on the other hand, are always set in reaction to protocol commands, so we'd be able to track target speed just like target temperature

2022-06-30 14:21 UTC, mcous commented on api/src/opentrons/protocol_engine/state/module_substates/heater_shaker_module_substate.py
> +        if self.labware_latch_status != HeaterShakerLabwareLatchStatus.IDLE_CLOSED:
Not sure what order these comments are going to show up in, but same comment as my `speed_status` vs `target_shake_speed`. I think the substate should be `labware_latch_closed` (or `..._open`, whatever) so we can set it in reaction to `openLabwareLatch` and `closeLabwareLatch` commands in an actual protocol

2022-06-30 14:22 UTC, sanni-t commented
> Having an issue with the happy path on commit `e35b421ff`
> 

I haven't been able reproduce this issue. I did run into a different issue that indicates that latch commands are returning before the action is completed so if there's a shake-related command immediately following the latch command then the firmware seems to lock up and doesn't provide a response in time. But that is an unrelated issue that is ticketed

2022-06-30 14:28 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/heater_shaker/open_labware_latch.py
> +        hs_module_substate.raise_if_shaking()
Oh oops, forgot this comment. Not a change request for this PR, just something I want us to think about and maybe come back to.

As per usual, I don't love the piling in of side-effects like `raise_if_whatever`. It forces us to do stuff like verify call order (see comment above) to ensure the test is valid. Not a huge deal, but I wonder if this might be incorporated into a data getter function instead.

For example, maybe it could be incorporated into `get_heater_shaker_module_substate` through some sort of expectations argument that will cause the selector to raise if the substate isn't in the requested state. Again, not worth changing at this stage, but I'm curious what people think

2022-06-30 15:31 UTC, sanni-t commented on api/tests/opentrons/protocol_engine/commands/heater_shaker/test_open_labware_latch.py
>      decoy.verify(await hs_hardware.open_labware_latch(), times=1)
Ah, I naively thought that `times=1` is functionally equivalent to not specifying `times` and does call order verification. Now I see why it wouldn't do that

2022-06-30 16:21 UTC, sanni-t commented on api/src/opentrons/protocol_engine/state/module_substates/heater_shaker_module_substate.py
> +        if self.labware_latch_status != HeaterShakerLabwareLatchStatus.IDLE_CLOSED:
Unlike speed status, `labware_latch_status` is the response of latch status gcode; it's not computed by hardware control..

2022-06-30 16:39 UTC, sanni-t commented on api/src/opentrons/protocol_engine/state/module_substates/heater_shaker_module_substate.py
> +        if self.labware_latch_status != HeaterShakerLabwareLatchStatus.IDLE_CLOSED:
Disregard that. I think I get your point. We don't want to mix up the engine's internal state with hardware state and hence we want something other than `labware_latch_status` for use here.

2022-06-30 16:41 UTC, sanni-t commented on api/src/opentrons/protocol_engine/state/module_substates/heater_shaker_module_substate.py
> +        if self.speed_status != SpeedStatus.IDLE:
That's a very good point. This would have resulted in a bug

2022-07-01 15:33 UTC, sanni-t commented on api/src/opentrons/protocol_engine/state/modules.py
> +                is_plate_shaking=False,
Need to fix #10858 for this to work correctly. Going to include the fix in this PR.

2022-07-01 20:04 UTC, sanni-t commented on api/src/opentrons/protocol_engine/state/modules.py
> +                is_plate_shaking=False,
So the above issue was thought to be a problem with deactivate command not waiting until shaking has stopped completely. But after further testing, it looks like the command actually waits until homing has completed and the plate isn't moving anymore. The error seems to be related more to some kind of communication lock-up for some time following a home command. 

Since that issue could only affect testing of this PR in cases where there are consecutive motor-related commands with little or no delay between them, I think it's safe to call this PR ready for review & testing with the above caveat and work on fixing the communication bug separately.

2022-07-05 17:06 UTC, sanni-t commented on api/src/opentrons/protocol_engine/commands/heater_shaker/open_labware_latch.py
> +        hs_module_substate.raise_if_shaking()
Makes sense to me.

2022-07-05 20:35 UTC, SyntaxColoring reviewed
Code makes sense to me.

I tested this with live HTTP commands on a `make dev` server, but I couldn't get it to recognize the labware latch as closed, despite a successful `closeLabwareLatch` command.

```json
{
    "data": {
        "commandType": "loadModule",
        "params": {
            "model": "heaterShakerModuleV1",
            "location": {"slotName": "5"},
            "moduleId": "hs"
        }
    }
}
```

(succeeded)

```json
{
    "data": {
        "commandType": "heaterShaker/closeLabwareLatch",
        "params": {
            "moduleId": "hs"
        }
    }
}
```

(succeeded)

```json
{
    "data": {
        "commandType": "heaterShaker/setAndWaitForShakeSpeed",
        "params": {
            "moduleId": "hs",
            "rpm": 1000
        }
    }
}
```

```json
{
    "data": {
        "id": "cda9ea04-7ee4-47fa-b6a6-8f7446b76efd",
        "createdAt": "2022-07-05T20:31:28.607601+00:00",
        "commandType": "heaterShaker/setAndWaitForShakeSpeed",
        "key": "cda9ea04-7ee4-47fa-b6a6-8f7446b76efd",
        "status": "failed",
        "params": {
            "moduleId": "hs",
            "rpm": 1000.0
        },
        "error": {
            "id": "6c0c659f-d544-4a8c-b9a4-72f6593c7901",
            "errorType": "CannotPerformModuleAction",
            "createdAt": "2022-07-05T20:31:28.608404+00:00",
            "detail": "The Heater-Shaker can't start shaking while the labware latch is open. Current latch status is: idle_unknown"
        },
        "startedAt": "2022-07-05T20:31:28.607879+00:00",
        "completedAt": "2022-07-05T20:31:28.608404+00:00",
        "intent": "setup"
    }
}
```

2022-07-05 20:35 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/modules.py
> +        module_live_data: Optional[LiveData] = None,
Stylistic nitpick: I might remove the `= None` defaults from `slot_name` and `module_live_data` because it doesn't seem like a safe default, given the bug you described in the PR's description. I think the caller should have to think about it and provide `= None` explicitly if that's appropriate.

2022-07-05 20:35 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/modules.py
> +        prev_state: HeaterShakerModuleSubState = hs_substate
Using [`dataclasses.replace`](https://docs.python.org/3/library/dataclasses.html#dataclasses.replace) instead of this `prev_state` variable might make things terser and more readable. I think we'd lose some type safety, though. No strong preference from me either way.

2022-07-06 16:52 UTC, mcous approved these changes
One readability nitpick, but looks good otherwise! No hardware to test on today, but it seems like other folks have that covered

2022-07-06 16:52 UTC, mcous commented on api/src/opentrons/protocol_engine/state/modules.py
> +                else False,
`True if ... else False` can be simplified to just the condition. Also, this is pretty hard to read without parentheses

```suggestion
                is_labware_latch_closed=(
                    live_data is not None
                    and live_data["labwareLatchStatus"] == "idle_closed"
                ),
                is_plate_shaking=(
                    live_data is not None and live_data["targetSpeed"] is not None
                ),
```

2022-07-06 17:29 UTC, ecormany commented
Tested and it properly raises errors for both scenarios in simulation, analysis, and at the offending step if you ignore all warnings and start the protocol on hardware anyway.

2022-07-06 19:20 UTC, merged