feat(api, step-generation): emit and ingest command keys
OpenTrons/opentrons-api pull request #10885
Opened 2022-06-23 20:57 UTC by shlokamin

# Overview

WIP

# Changelog

# Review requests

# Risk assessment

2022-06-27 16:45 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/protocol_engine.py
> -                # TODO(mc, 2021-12-13): generate a command key from params and state
@mcous is it ok I removed this? I figured since we are now consuming the front end key we might not need this anymore

2022-06-27 16:48 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/command.py
> +            "UI command key. This field will help" " protocol analysis for JSON v6."
```suggestion
            "Command key generated by UI and consumed by the api. By adding this field we are enabeling " " protocol analysis for JSON v6."
```

2022-06-30 13:21 UTC, TamarZanzouri commented on robot-server/tests/integration/http_api/runs/test_pause_then_cancel.tavern.yaml
> +#  - name: Wait for the delay to complete
@mcous left this here just to confirm we don't need it

2022-06-30 15:21 UTC, mcous requested changes
I think we're missing a unit test and the change to the tavern acceptance test causes it to miss the cancellation bug

2022-06-30 15:21 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/command.py
> +        ),
Remember that the context of these description is that of a HTTP API user, not of an Opentrons developer.

```suggestion
        description=(
            "A key value, unique in this run, that can be used to track"
            " the same logical command across multiple runs of the same protocol."
            " If a value is not provided, one will be generated."
        ),
```

2022-06-30 15:21 UTC, mcous commented on api/src/opentrons/protocol_engine/state/commands.py
> +                else action.command_id,
Can we use parentheses for readability and preserve the TODO from `protocol_engine.py`?

```suggestion
                key=(
                    action.request.key
                    if action.request.key is not None
                    # TODO(mc, 2021-12-13): generate a command key from params and state
                    # https://github.com/Opentrons/opentrons/issues/8986
                    else action.command_id
                ),
```

2022-06-30 15:21 UTC, mcous commented on api/src/opentrons/protocol_engine/state/commands.py
> +        no_command_queued = self.get_next_queued() is None
I don't see a unit test for this change. Are we missing the test or am I misreading?

2022-06-30 15:21 UTC, mcous commented on robot-server/tests/integration/http_api/runs/test_pause_then_cancel.tavern.yaml
> +#  - name: Wait for the delay to complete
We definitely need it, please revert. If you comment this step out and run the test on `edge`, it will pass. This step ensures the test will fail on edge and catches the bug we observed.

The bug was that a run like this cannot be stopped:

1. Command 1: `status: succeeded`
2. Command 2: `status: queued`

Removing this block changes the test to do this instead:

1. Command 1: `status: running`
2. Command 2: `status: queued`

This second scenario was not exhibiting buggy behavior. If anything we probably need both scenarios in this test file. Could you make that addition?

2022-06-30 15:21 UTC, mcous commented on step-generation/src/utils/index.ts
> +import uuidv1 from 'uuid/v1'
I think we should be using `uuid/v4`. It's more common than v1 in our codebase, and ever so slightly more "safe" (only in the most pedantic technical sense) choice given our use of web workers across the front-end stack

(v1 generates IDs using the system clock and system MAC address, while v4 is "random". You could technically collide v1 IDs with multiple ID producers on the same machine, though the real-life risk is minimal to non-existent in our current use of UUIDs)

2022-06-30 22:00 UTC, SyntaxColoring reviewed
Nice! Some comments and questions on the Python side. 🐍

2022-06-30 22:00 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/commands.py
> +                self._state.queued_command_ids.clear()
What does this do?

I see the unit test for it, but I don't understand the higher-level intent.

2022-06-30 22:00 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/runs/test_pause_then_cancel.tavern.yaml
> +          - status: queued
What do two `status`es mean here?

2022-06-30 22:00 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/runs/test_pause_then_cancel.tavern.yaml
> +  - name: Wait for the delay to complete
This is referring to the "Pause the run" action above, right?

I might reword this as:

```suggestion
  - name: Wait for the first command - waitForDuration - to complete
```

* `delay` means something very different than `pause` in the Python Protocol API. This isn't the Python Protocol API, but nonetheless, being as tight as possible with terminology might help reduce confusion.
* "Wait for the [delay/pause] to complete" can be misread as "wait until the protocol is no longer [delayed/paused]," but I think what we really mean here is that we want to wait for the pause *action* to be *processed,* so the pause is, in a certain sense, active.

2022-07-01 16:28 UTC, mcous commented on robot-server/tests/integration/http_api/runs/test_pause_then_cancel.tavern.yaml
> +  - name: Wait for the delay to complete
@SyntaxColoring it is not, it is waiting for the first command of the protocol (a `waitForDuration`, or a "delay") to complete so that the run ends up paused with its commands in the following state:

1. `waitForDuration` - status: `succeeded`
2. `home` - status: `queued`

2022-07-01 16:30 UTC, mcous commented on robot-server/tests/integration/http_api/runs/test_pause_then_cancel.tavern.yaml
> +          - status: queued
These are the statuses of the protocol's two commands

2022-07-01 16:34 UTC, mcous commented on api/src/opentrons/protocol_engine/state/commands.py
> +                self._state.queued_command_ids.clear()
The selector used to answer the question "is this JSONv6 protocol complete" is `state_view.commands.get_all_complete`. That selector checks logic checks that `state.queued_command_ids` is empty to decide if the run has finished.

Tamar identified a bug where if the stop came in at exactly the wrong time (in between two commands), the run would be left in a state where it would never transition out of `stop-requested`. This was caused by the fact that that `queued_command_ids` would never become empty if previous commands in the queue did not fail.

We didn't notice this before because usually, the `stop` request lands in the middle of a command, which will cause the command to fail due to the `asyncio.CancelledError`, clearing the rest of the queue given existing store logic

2022-07-01 17:07 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/commands.py
> +                self._state.queued_command_ids.clear()
Should I add a comment to make this more clear? I added one but removed it. if this is not clear maybe we should add a comment

2022-07-01 17:12 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/runs/test_pause_then_cancel.tavern.yaml
> +          - status: queued
I see. I think I'm being thrown off by the YAML syntax. No change needed, but if anyone else finds it confusing, I think a comment like this could be helpful.

```suggestion
          # Assert that there's a succeeded command followed by a queued command.
          - status: succeeded
          - status: queued
```

2022-07-01 17:40 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/commands.py
> +                self._state.queued_command_ids.clear()
After that stop comes in, what are the actual and desired `status`es of each command?

This?

1. `succeeded` command
2. `succeeded` command
3. [stop action came in here]
4. `queued` command
5. `queued` command

Or this?

1. `succeeded` command
2. `succeeded` command
3. [stop action came in here]
4. `failed` command
5. `failed` command

`queued_command_ids` is just a cache/index for efficient querying. It's not the actual source of truth for which commands are queued and which ones aren't. So it seems iffy to me that it's being cleared here just by itself; I would have expected it to be paired with something that iterates through `commands_by_id` and changes everything from `queued` to `failed`, for example.

2022-07-05 17:41 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/commands.py
> +                self._state.queued_command_ids.clear()
The status of the queued commands does not change. The run status changes. To your point we might need to clear all_command_ids as well? @mcous

2022-07-05 18:58 UTC, mcous commented on api/src/opentrons/protocol_engine/state/commands.py
> +                self._state.queued_command_ids.clear()
> 1. succeeded command
> 2. succeeded command
> 3. [stop action came in here]
> 4. queued command
> 5. queued command

This is the expected state of the commands after this PR / bugfix. The primary goal here is to make sure **the run itself** doesn't get locked up and is able to gracefully stop and "clean up" its hardware control resources.

> `queued_command_ids` is just a cache/index... It's not the actual source of truth for which commands are queued and which ones aren't.

This isn't quite correct. `queued_command_ids` is where the `QueueWorker` if looking to pick up execution jobs, so if `queued_command_ids` is empty, the `QueueWorker` won't execute anything. This is why `FailedCommandAction` also clears `queued_command_ids`.

> I would have expected it to be paired with something that iterates through commands_by_id and changes everything from queued to failed, for example.

I agree with this, but not for this PR. This bug fix is already a little bit of bloat in terms of the requirements of the ticket. I think our best path forward will be to introduce a `cancelled` command status. Can write that ticket up shortly.

@TamarZanzouri I don't think any more changes to command statuses are required for this PR

2022-07-06 17:44 UTC, shlokamin commented on step-generation/src/utils/index.ts
> +import uuidv1 from 'uuid/v1'
gocha, PD uses `uuid/v1`, so i did the same when i added it to step-generation. 

i'll selfishly bump to v4 in both places so I can feel like I'm a good person who goes out of my way to make the codebase better. you're welcome, world.

2022-07-06 21:21 UTC, mcous approved these changes
🦑

2022-07-06 21:21 UTC, mcous commented on step-generation/typings/global.d.ts
> +  export default uuidv1
```suggestion
  const uuidv4: any
  // eslint-disable-next-line import/no-default-export
  export default uuidv4
```

2022-07-06 21:21 UTC, mcous commented on step-generation/src/utils/index.ts
> +import uuidv1 from 'uuid/v4'
```suggestion
import uuidv4 from 'uuid/v4'
```

2022-07-06 21:21 UTC, mcous commented on step-generation/src/utils/index.ts
> +export const uuid: () => string = uuidv1
```suggestion
export const uuid: () => string = uuidv4
```

2022-07-07 18:01 UTC, merged