refactor(app): warn of out of sync robot version from the choose robo…
OpenTrons/opentrons-api pull request #10895
Opened 2022-06-24 03:52 UTC by b-cooper

# Overview & Changelog

- add "nonviable option" styling to the `MiniCard` component that is use for the warning state of the `AvailableRobotOption` component
- default selected robot to the first available robot in the slideout
- remove the now descoped and unimplemented "filtering of busy robots"
- determine if selected robot's sw version differs from the app and disable the "Proceed to Run CTA" if so

TODO: unit test coverage for additions

# Review requests

confirm the follow acceptance criteria are met when attempting to run a protocol on a robot (that is not on the same sw version as your app) by selecting it in the "Choose a Robot" slideout from the Protocols Landing or Protocol Details pages

 - A warning icon is shown if the robot is running a different software version than the app
 - Clicking on the robot card should reveal a warning message about the robot sw being out of sync
 - Clicking on the "Go to Robot" link should proceed the user to the Robot's device details page
 - If an out of date robot is selected, the "Proceed to setup" CTA button should be inactive
 
# Risk assessment
low

2022-06-24 17:36 UTC, emilywools commented
Can we either remove the link to the robots page or match the color of the rest of the text and underline it?

Can we adjust the styling to be error message styling (instead of warning message styling)? This is more EXTREME than a warning, its a blocking problem.

https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=5196%3A190443

2022-06-24 19:08 UTC, koji requested changes
Left the comment. I see the one issue on MiniCard.
I attached the image. Please take a look at it.

2022-06-24 19:08 UTC, koji commented on app/src/molecules/MiniCard/index.tsx
> +  background-color: ${COLORS.warningBg};
Emily's request

```suggestion
  border: 1px solid ${COLORS.errpr};
  background-color: ${COLORS.errorBg};
```

2022-06-24 19:08 UTC, koji commented on app/src/molecules/MiniCard/index.tsx
> +    background-color: ${COLORS.warningBg};
same as above

2022-06-24 19:08 UTC, koji commented on app/src/organisms/ChooseRobotSlideout/AvailableRobotOption.tsx
> +import { Trans, useTranslation } from 'react-i18next'
This line should be under `styled-components`

2022-06-24 19:08 UTC, koji commented on app/src/organisms/ChooseRobotSlideout/AvailableRobotOption.tsx
> +import { NavLink } from 'react-router-dom'
same as above

2022-06-24 19:08 UTC, koji commented on app/src/organisms/ChooseRobotSlideout/AvailableRobotOption.tsx
> +        {isOnDifferentSoftwareVersion ? (
```suggestion
       {isOnDifferentSoftwareVersion && isSelected ? (
```

without isSelected
![Screen Shot 2022-06-24 at 2 52 35 PM](https://user-images.githubusercontent.com/474225/175648814-a8560502-7c69-4b4d-a7fc-d64a2ad826cd.png)

2022-06-24 19:08 UTC, koji commented on app/src/organisms/ChooseRobotSlideout/AvailableRobotOption.tsx
> +      {isOnDifferentSoftwareVersion ? (
same as above

2022-06-24 19:08 UTC, koji commented on app/src/organisms/ChooseRobotSlideout/AvailableRobotOption.tsx
> +        {isOnDifferentSoftwareVersion ? (
Actually, the alert icon is rendering but there isn't enough space.

![Screen Shot 2022-06-24 at 3 05 01 PM](https://user-images.githubusercontent.com/474225/175649195-37067fed-cb77-4000-85c1-5ec8d43f233e.png)

2022-06-27 12:37 UTC, jerader commented on app/src/molecules/MiniCard/index.tsx
> +      }
this nested ternary is kind of hard to read

2022-06-27 12:37 UTC, jerader commented on app/src/molecules/MiniCard/index.tsx
> +  }
trying to figure out why you have this `hover` defined since the `border` and `background-color` are the exact same as the default styles

2022-06-27 14:03 UTC, b-cooper commented on app/src/molecules/MiniCard/index.tsx
> +  }
these styles get spread on top of the `unselectedOptionStyles` and the `selectedOptionStyles`. In both cases, the case of the selected and the nonviable state, we want to make sure that hover state is the same color as the standard state.

2022-06-27 23:10 UTC, koji approved these changes
⚙️ works as expected.

![Screen Shot 2022-06-27 at 7 07 50 PM](https://user-images.githubusercontent.com/474225/176051721-93c363be-928f-433e-90a1-5bc315c1851a.png)

Left 2 comments but they aren't related to the functionality.

2022-06-27 23:10 UTC, koji commented on app/src/organisms/ChooseRobotSlideout/AvailableRobotOption.tsx
> +          color={COLORS.errorText}
```suggestion
          color={COLORS.errorText}
          marginBottom={SPACING.spacing3}
```

2022-06-27 23:10 UTC, koji commented on app/src/organisms/ChooseRobotSlideout/AvailableRobotOption.tsx
> +              text-decoration: ${TEXT_DECORATION_UNDERLINE};
```suggestion
              text-decoration: ${TYPOGRAPHY.textDecorationUnderline};
```
We can remove `TEXT_DECORATION_UNDERLINE` (L15)

2022-06-28 17:02 UTC, merged