fix(api): always be prepared for aspirate
OpenTrons/opentrons-api pull request #10914
Opened 2022-06-27 15:03 UTC by andySigler

closes #10913

# Overview

Previously, calling `Pipette.aspirate()` for the first time would result in the pipette unexpectedly jumping up to the top of the well (if the tip was already positioned inside the well). This is very bad for when creating planned (slow) approaches for different liquid classes.

# Changelog

Pipette calls `prepare_for_aspirate()` immediately after picking up a tip.

# Risk assessment

I don't see much risk. The plunger position was already technically at `bottom` previously after picking up a tip, so this PR doesn't change actual plunger behavior.

2022-06-27 15:11 UTC, sfoster1 requested changes
Let's do this in the hardware controller instead. The only reason `prepare_for_aspirate` is a separate call is to handle the case where you're already in a well (this is why it jumps up). Like you noticed, it should always be safe to `prepare_for_aspirate` immediately after picking up a tip, so let's add the call to `opentrons.hardware_control.api.API.pick_up_tip` and `opentrons.hardware_control.ot3api.OT3API.pick_up_tip`.

2022-06-27 19:25 UTC, sfoster1 commented
OK, that stuff looks good. The gcode tests need to be updated via the instructions [here](https://github.com/Opentrons/opentrons/tree/edge/g-code-testing#saving-new-comparison-files) but we should probably do some manual protocol testing since this is such core behavior.

2022-06-27 20:30 UTC, sfoster1 requested changes
Talked about this with @mcous  - we want to keep protocol behavior under a given version exactly the same, so this will need a protocol version bump. That means that
- `opentrons.hardware_control.API.drop_tip` (and the OT3API version) should gain a `prep_after: bool = True` default argument
- Calls from protocol api v2 should specify that value to `False`, unless
- The protocol is operating under a [newly-added 2.13 api version](https://github.com/Opentrons/opentrons/blob/21cf6728409857dfd645d6861cf85408c7bcc41f/api/src/opentrons/protocols/api_support/definitions.py#L3) or higher

That's a lot of new changes! We can collaborate on it.

2022-07-06 15:46 UTC, andySigler commented
@sfoster1 made most of those changes. There are two remaining things that I can't quickly do on my own:

1. Testing `APIVersion(2, 12)` versus `APIVersion(2, 13)` behavior re: `.pick_up_tip(prep_after=)`. It's not immediately obvious to me how to test that.
2. Updating g-code comparison. Not really sure what's going on there

2022-07-06 18:36 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +                           for any following calls to `.aspirate()`
Can we add something that mentions the default behavior on >=PAPIv2.13 if unspecified?

2022-07-06 18:36 UTC, mcous commented on api/src/opentrons/protocols/api_support/definitions.py
> +MAX_SUPPORTED_VERSION = APIVersion(2, 13)
CC @ecormany, we're gonna want to update the API docs with this version + feature addition

2022-07-06 18:36 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +        :param prep_after: If the pipette's plunger should be prepared to make
While I'm here, might as well bike shed! After the chat, I think I imagined this API to be a little more geared towards "the default behavior of resetting the plunger is good, and if you mess with this setting, you're doing stuff we don't recommend."

So, for the user-facing portion of this PR, I wonder if a verbose and scary name like `disable_plunger_reset`, that defaults to `False` is better than a `prep_after` option that defaults to `True`. I worry that `prep_after` sounds a little innocuous given that ideally, every user should want to have plunger reset enabled

2022-07-06 18:41 UTC, ecormany commented on api/src/opentrons/protocols/api_support/definitions.py
> +MAX_SUPPORTED_VERSION = APIVersion(2, 13)
👀 Is this going to push H-S support to 2.14? We can take this conversation elsewhere if it's too much to hash out in PR comments.

2022-07-06 19:26 UTC, ecormany commented on api/src/opentrons/protocol_api/instrument_context.py
> +        :param prep_after: If the pipette's plunger should be prepared to make
Something like this?
```
Whether the pipette's plunger should prepare itself to aspirate
immediately after picking up a tip. This defaults to ``True``, which
will cause the pipette to move its plunger position to ``bottom`` in
preparation for any following calls to :py:meth:`.aspirate`. Setting
this to ``False`` may [caveat about aspiration behavior].
```

Up to you to fill in the caveat, since I'm not that well acquainted with this feature.

2022-07-06 20:12 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +
Strictly, we should also forbid people from overriding `prep_after` when their `apiLevel` is lower than 2.13.

Something like this:

```suggestion
        prep_after_added_in = APIVersion(2, 13)
        if prep_after is None:
            prep_after = (self.api_version >= prep_after_added_in)
        elif self._api_version < prep_after_added_in:
            raise APIVersionError(
                f"prep_after is only available in API {prep_after_added_in} and newer,"
                f" but you are using API {self._api_version}."
            )
```

So that if I write a protocol for my robot that uses `prep_after=something`, and then share it with someone who's using outdated software, they get a hopefully helpful API version error instead of a surprise `TypeError`.

2022-07-06 20:12 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +                           for any following calls to `.aspirate()`
Yeah, we should describe:

* [x] What happens when you don't specify this...
    * [x] ...in older API versions (as @mcous said).
    * [x] ...in newer API versions.
* [x] The fact that you *can't* specify this in older API versions.
    * See my other review comment about raising `APIVersionError`.

2022-07-06 20:12 UTC, SyntaxColoring commented on api/src/opentrons/protocols/api_support/definitions.py
> +MAX_SUPPORTED_VERSION = APIVersion(2, 13)
Can we add something like this to `api/docs/v2/versioning.rst`?

```rst
Version 2.12
++++++++++++

- :py:meth:`.InstrumentContext.drop_tip` now has a ``prep_after`` parameter.
```

We'll also need to update the table at the top of that file that lists which overall release supports which Python Protocol API version, but I'm not sure which release that would be. Maybe we can assume it will be 6.1?

CC @ecormany.

2022-07-06 20:12 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +                           for any following calls to `.aspirate()`
I'm not sure how much of that should be right here in the `prep_after` argument docstring, and how much should be put in a  [`..versionchanged` block](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionchanged) at the bottom of the method docstring. Or whether we even need a `..versionchanged` block. @ecormany, do you have an opinion?

2022-07-06 20:12 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +        :param prep_after: If the pipette's plunger should be prepared to make
> So, for the user-facing portion of this PR, I wonder if a verbose and scary name like `disable_plunger_reset`, that defaults to `False` is better than a `prep_after` option that defaults to `True`. I worry that `prep_after` sounds a little innocuous given that ideally, every user should want to have plunger reset enabled

In general, I find things more readable when boolean arguments are named after the positive thing instead of the negative thing: `do_thing = True` instead of `disable_doing_thing = False`. So I prefer `prep_after`, despite it not sounding as scary as we might like.

2022-07-06 20:12 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +        :param prep_after: If the pipette's plunger should be prepared to make
I agree that we should discourage protocol authors from setting `prep_after=False`. Would it be sufficient if we front-loaded that discouragement in the docstring? Iterating on @ecormany's sketch:

> Whether the pipette's plunger should prepare itself to aspirate immediately after picking up a tip.
>
> This is provided for compatibility with older Python Protocol API behavior. You should normally leave this unset.
>
> If ``True``, the pipette will move its plunger position to ``bottom`` in preparation for any following calls to :py:meth:`.aspirate`.
>
> If ``False``, [caveat about aspiration behavior].

2022-07-06 20:43 UTC, ecormany commented on api/src/opentrons/protocols/api_support/definitions.py
> +MAX_SUPPORTED_VERSION = APIVersion(2, 13)
Yes, if this goes into `edge` it should be picked up in 6.1 and _not_ in 6.0. I presume the `release_6.0.0` branch will stick around in case we need an intervening patch.

2022-07-06 20:48 UTC, ecormany commented on api/src/opentrons/protocol_api/instrument_context.py
> +                           for any following calls to `.aspirate()`
If the behavior is different — and it sounds like it is, if this is only settable in 2.13+ — then `..versionchanged` is appropriate. I would separate it as follows:
- The docstring describes _what the supported values do_ (effectively what we have above).
- The `..versionchanged` notice explains _the difference in error handling_ introduced in 2.13. It should refer to `prep_after` by name since the notice applies to the entire method, not just the parameter.

2022-07-06 21:40 UTC, ecormany commented on api/src/opentrons/protocols/api_support/definitions.py
> +MAX_SUPPORTED_VERSION = APIVersion(2, 13)
I'm happy to make the Versioning doc changes. @mcous Should I commit directly to this branch, PR to this branch, or PR to `edge`?

2022-07-12 02:11 UTC, andySigler commented on api/src/opentrons/protocols/api_support/definitions.py
> +MAX_SUPPORTED_VERSION = APIVersion(2, 13)
@SyntaxColoring @ecormany  I added this, not sure if it's what's needed, let me know!

2022-07-12 16:35 UTC, SyntaxColoring approved these changes
Changes since my last review look great to me; all of my review requests about docs and versioning have been addressed. Thanks!

2022-07-12 16:40 UTC, sfoster1 commented
just need the gcode updates here: https://github.com/Opentrons/opentrons/tree/edge/g-code-testing#saving-new-comparison-files

2022-07-12 21:10 UTC, ecormany reviewed
Suggested some RST syntax fixes and some more stylistic changes.

Also, I'm good with the changes to `versioning.rst` but I want to make sure that they don't set up a conflict with getting #11063 deployed before we bump the API version. @andySigler please message me if you have questions with the timing around that.

2022-07-12 21:10 UTC, ecormany commented on api/src/opentrons/protocol_api/instrument_context.py
> +                           during the next call to :py:meth:.aspirate. This is
```suggestion
                           If ``True``, the pipette will move its plunger position to
                           bottom in preparation for any following calls to
                           :py:meth:`.aspirate`.

                           If ``False``, the pipette will prepare its plunger later,
                           during the next call to :py:meth:`.aspirate`. This is
```

Touching up the RST syntax here.

2022-07-12 21:10 UTC, ecormany commented on api/src/opentrons/protocol_api/instrument_context.py
> +            ``APIVersionError`` if ``prep_after=`` is included as an argument.
```suggestion
            Adds the ``prep_after`` argument. In version 2.12 and earlier, the plunger can't prepare
            itself for aspiration during :py:meth:`.pick_up_tip`, and will instead always
            prepare during :py:meth:`.aspirate`. Version 2.12 and earlier will raise an
            ``APIVersionError`` if a value is set for ``prep_after``.
```

Some style and copy suggestions.

2022-07-13 17:47 UTC, ecormany commented
> …I want to make sure that they don't set up a conflict with getting #11063 deployed before we bump the API version. @andySigler please message me if you have questions with the timing around that.

This has been merged and tagged and isn't a conflict anymore.

2022-07-22 14:51 UTC, sfoster1 approved these changes
Looks good to me - updated all the gcode tests and the diffs look fine.

2022-07-25 15:01 UTC, merged