style(app): completed round 2 feedback for protocols landing without any protocol
OpenTrons/opentrons-api pull request #10928
Opened 2022-06-28 02:36 UTC by aptrons22

# Overview
Issue#10907

Completed the following task:
(1) Update this text to our h1 style
(2) Add in margin between h1 and p copy
(3) Can you add in our hover state for our blue links for the word "browse"?
(4) I'm assuming fixing these links for the main page would fix these here too. Fixed on this issue and on PR#10920 but will close this PR once this current one is merged into release_6.0.0
 (5) Center this entire section to the middle of the page (see purple rectangle)

# Changelog

# Review requests

# Risk assessment

2022-06-28 12:20 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolsEmptyState.tsx
> +      <Text role="complementary" as="h1">
We should use `StyledText` instead of `Text`

2022-06-28 12:22 UTC, koji commented on components/src/primitives/Btn.tsx
> +
Shouldn't change this component. We just need to change `atoms/buttons`

2022-06-28 12:22 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +        css={TYPOGRAPHY.pSemiBold}
```suggestion
        
```

2022-06-28 12:28 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
> +                <StyledText as="p" min-width="10.625rem">
```suggestion
                <StyledText as="p" minWidth="10.625rem">
```

2022-06-28 12:32 UTC, koji requested changes
We shouldn't change this component (components/src/primitives/Btn.tsxcomponents/src/primitives/Btn.tsxcomponents/src/primitives/Btn.tsx).

Other changes look good.

2022-06-28 16:24 UTC, aptrons22 commented on components/src/primitives/Btn.tsx
> +
Fixed now. Thanks

2022-06-28 16:49 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +        css={TYPOGRAPHY.pSemiBold}
Nothing to modify here.  Thanks

2022-06-28 16:50 UTC, aptrons22 commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
> +                <StyledText as="p" min-width="10.625rem">
Fixed.

2022-06-28 16:59 UTC, mmencarelli requested changes
Looks good! The only change needed is to center all this content to the center of the page. 

Figma on the left, screenshot on the right. 
<img width="1338" alt="Screen Shot 2022-06-28 at 9 58 55 AM" src="https://user-images.githubusercontent.com/54682054/176239265-0fb53558-d0e6-4ecd-b949-af2cf463b191.png">

2022-06-30 23:48 UTC, koji commented
This has been solved #10950

2022-06-30 23:48 UTC, closed without merging