style(app): fixed the protocols page footer
OpenTrons/opentrons-api pull request #10920
Opened 2022-06-27 19:24 UTC by aptrons22

# Overview

Correct the styling for the three links on the Protocols Landing Page.

# Changelog

# Review requests

# Risk assessment

2022-06-27 19:30 UTC, emilywools commented
hey @aptrons22 thanks for sharing this. The PD link color looks wrong now, all of the text link colors should match.

2022-06-27 19:48 UTC, aptrons22 commented
@emilywools Hello Emily, I'm using the same typography for all three links.  Not sure why they still look off.  I'm going to recommend we keep the links as at the original state.  For now, I'm looking for assistance to see why the styling seems off even though I used the Figma design styling.  Thanks

2022-06-27 19:58 UTC, emilywools commented
im not sure what the problem is but all 3 link's styling needs to match

2022-06-28 12:36 UTC, emilywools commented
this screenshot looks good, thank you

2022-06-28 12:40 UTC, jerader requested changes
The protocol page footer component/changes looks good but there is a lot of additional changes included in this PR that needs to be adjusted.

2022-06-28 12:40 UTC, jerader commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
> +                <StyledText as="p" marginTop={SPACING.spacing2}>
adding this `marginTop={SPACING.spacing2}` seems wrong to me because you're adding an extra spacing to the 1st column in the protocol card that the rest of the columns don't have.

2022-06-28 12:40 UTC, jerader commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
> +                color={COLORS.darkGreyEnabled}
this `color={COLORS.darkGreyEnabled}` should be moved to line 207 because that way, it only changes the `Right Mount` text and not the whole column text

2022-06-28 12:40 UTC, jerader commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
> +                <StyledText as="p" min-width="10.625rem">
this `min-width` doesn't do anything. The correct notation is `minWidth`

2022-06-28 12:40 UTC, jerader commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +   }
```suggestion
    align-items={TYPOGRAPHY.textAlignCenter}

```

2022-06-28 12:40 UTC, jerader commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +                {SortByText[sortBy]}
what does this line do?

2022-06-28 12:40 UTC, jerader commented on components/src/primitives/Btn.tsx
> +
these changes are changing our legacy button components that we shouldn't be messing with. Instead, you should be changing the component that uses the button that you want to change.

2022-06-28 14:45 UTC, koji requested changes
Left a couple of comments.

2022-06-28 14:45 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +        css={TYPOGRAPHY.pSemiBold}
```suggestion
        
```

2022-06-28 14:45 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolList.tsx
> +
You are using `styled` so you need to use `:` instead of `=` and also need to pass properties as a val which means you are missing `$`.

However, I'm not sure what you are trying since Mel's feedback is to align the background color with the Design system.

```suggestion
const SortByText = styled(StyledText)`
  background-color: ${COLORS.transparent};
  font-weight: ${TYPOGRAPHY.pSemiBold};
   &:enabled {
    align-items: ${TYPOGRAPHY.textAlignCenter};
   }
   &:hover {
    align-items: ${TYPOGRAPHY.textAlignCenter};
    }
  `
```

2022-06-28 14:56 UTC, koji commented on app/src/organisms/ProtocolsLanding/ProtocolCard.tsx
> +                <StyledText as="p" min-width="10.625rem">
not 100% sure but tweaking `Flex` would be a good way to align the UI with Mel's feedback instead of adding `minWidth` to StyledText(`p-tag`).

2022-07-05 16:13 UTC, b-cooper commented
Addressed in #10993

2022-07-05 16:13 UTC, closed without merging