refactor(app): protocol details page design qa feedback 1
OpenTrons/opentrons-api pull request #10932
Opened 2022-06-28 17:58 UTC by jerader

closes #10906

# Overview

address design feedback on Protocol Details page: 

<img width="915" alt="Screen Shot 2022-06-28 at 1 56 47 PM" src="https://user-images.githubusercontent.com/66035149/176250589-24f18910-28a5-4933-8e35-2fed7b6b95a5.png">

# Changelog

- changed `ProtocolDetails` and `ProtocolLabwareDetails`

# Review requests

- upload a protocol and click on the protocol card to get the protocol labware details. does it match designs?

# Risk assessment

low

2022-06-28 17:59 UTC, jerader commented on app/src/organisms/ProtocolDetails/ProtocolLabwareDetails.tsx
> +          top="2.3rem"
had to estimate this so the overflow menu appears 4px below the overflow menu button

2022-06-28 17:59 UTC, jerader commented on app/src/organisms/ProtocolDetails/index.tsx
> +    background-color: #eeeeee;
this background color `#eeeeee` isnt a constant, @mmencarelli, should I add it as a constant?

2022-06-28 18:15 UTC, jerader commented on components/src/ui-style-constants/colors.ts
> +export const fundamentalsBackgroundShade = '#eeeeee'
got confirmation from Mel to add this color

2022-06-28 18:16 UTC, jerader commented on app/src/organisms/ProtocolDetails/index.tsx
> +    background-color: #eeeeee;
just added it to our constants as `fundamentalsBackgroundShade`

2022-06-28 21:05 UTC, mmencarelli commented
**Round 2 feedback on T2 Protocol Detail page**

[Link to annotated frame in figma](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=14699%3A293314)

- [ ] (1) Let's get this menu overflow icon to be 4px from top and right hand side of container
- [ ] (2) Can we get the open menu to be 4px from the icon? 
- [ ] (3) Update margin-right on svg to be .25rem
- [ ] (4) Can we fix the tiny SVG when viewport shrinks in width? 
- [ ] (5) Can we fix the copy going weird when viewports shrinks in width? 
- [ ] (6) should this be "loading..." too? 
- [ ] (7) Update margin to this container from 24px margin top and bottom to 16px 
- [ ] (8) Is it possible to remove the 8px margin-bottom on the last child here? idk if it's that that's causing the extra space? Not a huge deal, but if it's easy! 
- [ ] (9) Noticing that these columns aren't hugely responsive? Could we have the columns be flex-width? 
- [ ] (10) that the container as a whole doesn't abide by the 1rem margins on the entire page




<img width="844" alt="Screen Shot 2022-06-28 at 2 02 42 PM" src="https://user-images.githubusercontent.com/54682054/176287656-972467e8-54f4-4426-b068-ce058ff914a0.png">
<img width="607" alt="Screen Shot 2022-06-28 at 2 02 51 PM" src="https://user-images.githubusercontent.com/54682054/176287669-0391a5a4-1f94-4ddc-95b0-bb100505da75.png">
<img width="832" alt="Screen Shot 2022-06-28 at 2 02 56 PM" src="https://user-images.githubusercontent.com/54682054/176287677-e03f686d-1a27-4b10-9cc7-986f5979b636.png">
<img width="795" alt="Screen Shot 2022-06-28 at 2 03 00 PM" src="https://user-images.githubusercontent.com/54682054/176287678-d97aa88d-293b-44d5-b2b7-7aac040b2d66.png">
<img width="714" alt="Screen Shot 2022-06-28 at 2 03 49 PM" src="https://user-images.githubusercontent.com/54682054/176287696-5f6ac203-88e1-4b50-91d3-4e07bdad0014.png">

2022-06-29 21:00 UTC, mmencarelli requested changes
Minor edits! 

- [ ] (1) Lost the left alignment of the second column!
- [ ] (2) just make sure this text is all left aligned
- [ ] (3) I told ya to take off too much margin! Add back in .5rem so we have 1rem margin total. 

<img width="693" alt="Screen Shot 2022-06-29 at 1 59 35 PM" src="https://user-images.githubusercontent.com/54682054/176543894-ec5fdc07-17c7-4ef7-96e4-db1cee8785e1.png">
<img width="897" alt="Screen Shot 2022-06-29 at 2 00 21 PM" src="https://user-images.githubusercontent.com/54682054/176543932-185bd359-e574-4439-a7ae-edfccc45b0c9.png">

2022-06-30 18:10 UTC, mmencarelli approved these changes
weee!!

2022-07-01 14:59 UTC, koji commented on app/src/organisms/ProtocolDetails/ProtocolLabwareDetails.tsx
> +          top="2.3rem"
Yeah, this happens to robot card, labware card, and protocol card.

2022-07-01 16:30 UTC, koji approved these changes
Looks good to me.
Left a couple of comments.

However, there is one concern about the date format. Maybe we should talk about this with the design team?
CC: @b-cooper @brenthagen @vabruzzo 

Details page `June 30, 2022 12:00`
Landing page `6/30/2022` 12:00:00

2022-07-01 16:30 UTC, koji commented on app/src/organisms/ProtocolDetails/ProtocolLabwareDetails.tsx
>            color={COLORS.darkBlack}
we can remove this.

2022-07-01 16:30 UTC, koji commented on app/src/organisms/ProtocolDetails/ProtocolLabwareDetails.tsx
> +        <StyledText as="p" color={COLORS.darkBlack}>
```suggestion
        <StyledText as="p">
```

2022-07-01 16:30 UTC, koji commented on app/src/organisms/ProtocolDetails/ProtocolLabwareDetails.tsx
> +            color={COLORS.darkBlack}
```suggestion
          <StyledText
            as="p"
```

2022-07-01 16:30 UTC, koji commented on app/src/organisms/ProtocolDetails/ProtocolLabwareDetails.tsx
>            right={0}
maybe `right="0"`

2022-07-01 16:30 UTC, koji commented on app/src/organisms/ProtocolDetails/index.tsx
> +  grid-template-columns: 26.6% 26.6% 26.6% 20%;
The total is 99.8%. Is this on purpose?

2022-07-01 16:33 UTC, jerader commented on app/src/organisms/ProtocolDetails/index.tsx
> +  grid-template-columns: 26.6% 26.6% 26.6% 20%;
whoops not on purpose, i just didn't do the math correctly.

2022-07-01 16:35 UTC, jerader commented
> Details page `June 30, 2022 12:00` Landing page `6/30/2022` 12:00:00

@koji good call, I didn't even notice this

2022-07-01 17:28 UTC, koji commented on app/src/organisms/ProtocolDetails/index.tsx
> +  grid-template-columns: 26.6% 26.6% 26.6% 20%;
> > Details page `June 30, 2022 12:00` Landing page `6/30/2022` 12:00:00
> 
> @koji good call, I didn't even notice this - perhaps we can make a follow up ticket for when Mel and Emily are back.

@jerader 
That would be a good idea.

2022-07-01 17:36 UTC, vabruzzo approved these changes
lgtm

2022-07-01 18:59 UTC, jerader commented
made a follow up ticket re: the date display inconsistencies

https://github.com/Opentrons/opentrons/issues/10989

2022-07-02 14:37 UTC, merged