feat(protocol-designer): add custom liquid color picker
OpenTrons/opentrons-api pull request #10958
Opened 2022-06-30 15:13 UTC by sakibh

# Overview

This PR adds a custom liquid color picker and field to the liquids page in Protocol Designer. closes #10573 , closes #10601 

Co-authored by @smb2268 

<img width="720" alt="image" src="https://user-images.githubusercontent.com/14794021/176712692-1959c8b4-056f-4787-9402-e131db8b8506.png">

Note: still working on updating/adding tests

# Changelog

- Added `react-color`
- Added `displayColor` field to liquids page component and redux store
- Updated PD liquids colors

# Review requests

Note: In order to access this new feature, enable the feature flag called `Enable liquid color enhancements`.

- Check that the ACs for both tickets mentioned above are fulfilled.
- Check that you are able to choose any of the predefined colors AND/OR add a custom color via hex code.
- Check that the colors are persisting once you click save.
- Check that when adding liquid to labware, the colors are accurate/persistent.
- Check that when uploading an old protocol, PD prompts you to update the version and the liquid colors should default to new the new color scheme.

# Risk assessment

low, behind FF

2022-07-06 15:51 UTC, mmencarelli commented
hey @sakibh is there any way for me to test this in PD? If not, could you send over a video? Thanks!

2022-07-06 15:57 UTC, sakibh commented
> hey @sakibh is there any way for me to test this in PD? If not, could you send over a video? Thanks!

Hey @mmencarelli, you can access this branch for PD here: http://sandbox.designer.opentrons.com/pd_add-color-picker/

2022-07-06 16:27 UTC, mmencarelli requested changes
Wow, this is amazing! 

K, the only change i can see here is that you have the hover state as the enabled state. So move the box shadow over to only appear on hover!

2022-07-06 18:20 UTC, smb2268 commented on protocol-designer/src/labware-ingred/selectors.ts
> +// import { swatchColors } from '../components/swatchColors'
looks like this can be removed

2022-07-06 18:49 UTC, smb2268 approved these changes
tested this out and it works & looks great!

2022-07-06 19:34 UTC, mmencarelli commented
Could we have the box-shadow appear when the menu is active/open? 

Reference to design [on Figma](https://www.figma.com/file/2xjSLHXquNsKvC1mV9NMjr/Milestone-2?node-id=955%3A145056).

Other than that, looks great!

2022-07-11 15:38 UTC, mmencarelli approved these changes

2022-07-11 18:49 UTC, merged