refactor(shared-data): update load names for h/s labware+adapter definitions
OpenTrons/opentrons-api pull request #10964
Opened 2022-06-30 16:49 UTC by TamarZanzouri

# Overview

closes #10938.
closes #10973.
updated loadNames to suggested names.

# Changelog

- Updated file names in 'shared-data/labware'
- Updated loadModule key
- Updated ts getAdapterName and test

# Review requests

1. did I miss anything? 
2. ts changes look correct? 
3. test on a robot?

# Risk assessment

Medium. changed file names and loadName. could cause adapters not to load if there is a mismatch in names.

2022-06-30 18:19 UTC, skyewindsor approved these changes
The new loadNames look good to me. 
I cannot speak into the ts changes or testing on a robot though

2022-06-30 19:08 UTC, sanni-t reviewed
Looks good. Let's also update the file names to reflect the updated `loadName`s

2022-06-30 19:48 UTC, skyewindsor commented
@TamarZanzouri The `"displayName"`s will need to be updated too. Ticket here: https://github.com/Opentrons/opentrons/issues/10973

2022-07-01 14:22 UTC, TamarZanzouri commented
> @TamarZanzouri The `"displayName"`s will need to be updated too. Ticket here: #10973

updated :-)

2022-07-01 17:53 UTC, sanni-t commented on shared-data/labware/definitions/2/opentrons_universal_flat_adapter_corning_384_wellplate_112ul_flat/1.json
> +    "displayName": "Opentrons Universal Adapter with Corning 384 Well Plate 112 µL Flat",
@skyewindsor should this be "Opentrons Universal Flat Adapter..." to match the load name?

2022-07-05 16:14 UTC, mcous requested changes
- Need space between number and unit in display names to match Opentrons style
- Need to use `µ` in display names, not `u`

2022-07-05 16:14 UTC, mcous commented on shared-data/labware/definitions/2/opentrons_96_deep_well_adapter_nest_wellplate_2ml_deep/1.json
> +    "displayName": "Opentrons 96 Deep Well Adapter with NEST Deep Well Plate 2mL",
```suggestion
    "displayName": "Opentrons 96 Deep Well Adapter with NEST Deep Well Plate 2 mL",
```

2022-07-05 16:14 UTC, mcous commented on shared-data/labware/definitions/2/opentrons_96_pcr_adapter_nest_wellplate_100ul_pcr_full_skirt/1.json
> +    "displayName": "Opentrons 96 PCR Adapter with NEST Well Plate 100ul",
```suggestion
    "displayName": "Opentrons 96 PCR Adapter with NEST Well Plate 100 µl",
```

2022-07-05 17:00 UTC, skyewindsor commented on shared-data/labware/definitions/2/opentrons_universal_flat_adapter_corning_384_wellplate_112ul_flat/1.json
> +    "displayName": "Opentrons Universal Adapter with Corning 384 Well Plate 112 µL Flat",
@sanni-t Yes, that display name should say "Opentrons Universal Flat Adapter with Corning 384 Well Plate 112 µl Flat". @TamarZanzouri are you able to update that? I made a mistake in the ticket

2022-07-05 17:02 UTC, TamarZanzouri commented on shared-data/labware/definitions/2/opentrons_universal_flat_adapter_corning_384_wellplate_112ul_flat/1.json
> +    "displayName": "Opentrons Universal Adapter with Corning 384 Well Plate 112 µL Flat",
@sanni-t nice catch! @skyewindsor please confirm so I can make the change

2022-07-05 17:04 UTC, skyewindsor commented on shared-data/labware/definitions/2/opentrons_universal_flat_adapter_corning_384_wellplate_112ul_flat/1.json
> +    "displayName": "Opentrons Universal Adapter with Corning 384 Well Plate 112 µL Flat",
@TamarZanzouri confirming you can make this change!

2022-07-05 17:23 UTC, mcous approved these changes
Changes LGTM

2022-07-05 19:16 UTC, sanni-t approved these changes
LGTM! Thanks for making the changes. Good to merge once CI clears

2022-07-06 18:59 UTC, merged