feat(api): add gripper grip and release to OT3api
OpenTrons/opentrons-api pull request #10987
Opened 2022-07-01 16:50 UTC by ahiuchingau

# Overview
Adds very basic functions for gripper jaw movements. We can specify a force in Newton and a duration in seconds for the gripper grip and release. Grip would move the gripper jaw inwards to close. Release would move the jaw outwards until the homing switch is triggered.

2022-07-01 17:29 UTC, sfoster1 requested changes
Some feedback some of which is bikeshedding and some of which isn't. Definitely looking good though

2022-07-01 17:29 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3utils.py
> +def create_gripper_move_group(
let's call this `create_gripper_jaw_move_group` or something

2022-07-01 17:29 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/gripper_handler.py
> +    def set_ready_to_grip(self, val: bool) -> None:
might as well make these properties with setters like
```
@property 
def ready_for_grip(self) -> bool:
    gripper = self._verify_gripper
    return gripper.ready_to_grip

@ready_for_grip.setter
def ready_for_grip(self, ready: bool) -> None:
    gripper = self._verify_gripper()
    gripper.ready_to_grip = ready
```

2022-07-01 17:29 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    async def gripper_move(
```suggestion
    async def gripper_move_jaw(
```
?

2022-07-01 17:29 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    async def gripper_home(
```suggestion
    async def gripper_home_jaw(
```
?

2022-07-01 17:29 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +    async def prepare_for_grip(self) -> None:
I don't think we need this - I think we can happily assert that you have to manually release before gripping.

2022-07-01 17:29 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        self._gripper_handler.set_has_gripped(True)
wondering if this state is better served by an enum, like
`GRIPPED` (good grip), `RELEASED` (all the way open), `UNHOMED` (haven't homed yet), `CLOSED` (closed but not gripping), `POSITION_CONTROL` (some intermediate value that's not gripped or closed or opened)

2022-07-06 22:04 UTC, sfoster1 commented
This needs https://github.com/Opentrons/ot3-firmware/pull/402

2022-07-06 22:05 UTC, sfoster1 commented
Changes:
- Removing duration; in general, these commands are force-controlled and move until they apply that force or another condition is met. For now, internally they're going for a set duration, but in the future it'll be controlled
- Removing frequency; this is not something we really need to specify, it should be 32khz all the time.

2022-07-07 14:13 UTC, DerekMaggio commented on api/src/opentrons/config/defaults_ot3.py
> +        OT3AxisKind.Z: 1.4,
Are these defaults found experimentally?

2022-07-07 14:13 UTC, DerekMaggio commented on api/src/opentrons/config/gripper_config.py
> +    """
Would it be helpful to provide a link to the force/duty-cycle function we are using?

2022-07-07 14:13 UTC, DerekMaggio commented on api/src/opentrons/config/gripper_config.py
> +    sub-list in the sequence contains:
This comment doesn't seem finished. What does each sub-list contain?

2022-07-07 14:13 UTC, DerekMaggio commented on api/src/opentrons/hardware_control/ot3api.py
> +                if OT3Axis.G in checked_axes and self._gripper_handler.has_gripper():
Do we modify the OT3Axis enum at Runtime? 
Because looking at [OT3Axis](https://github.com/Opentrons/opentrons/pull/10987/files#diff-3e98a8cae713a483cd2f9b731d8a5c36d5506943c3483bbbf3e6a423f49942f5R115-R124) it looks like `OT3Axis.G` will always exist. If we do not modify the Enum at runtime, I think we can remove the check

2022-07-07 14:13 UTC, DerekMaggio commented on api/src/opentrons/hardware_control/types.py
> +    HOLDING_OPENED = enum.auto()
Why wouldn't we always just home the gripper instead of having an intermediate holding open step?

2022-07-07 14:18 UTC, sfoster1 commented on api/src/opentrons/config/defaults_ot3.py
> +        OT3AxisKind.Z: 1.4,
yeah

2022-07-07 14:20 UTC, sfoster1 commented on api/src/opentrons/config/gripper_config.py
> +    """
like, to the file in shared-data, here? https://github.com/Opentrons/opentrons/blob/a7c1796360f5a398a546de4b1887792f78c39fe9/shared-data/gripper/definitions/1/gripperV1.json#L26-L39

2022-07-07 14:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +                if OT3Axis.G in checked_axes and self._gripper_handler.has_gripper():
The input handling above is:
- If the user provided `axes`, make sure it becomes a list of OT3Axis elements
- if the user provided nothing, use all the axes

So you could call `api.home([OT3Axis.X, OT3Axis.Y])` and only the X and Y axes would be homed. so line 839 has to account for that.

2022-07-07 14:23 UTC, sfoster1 commented on api/src/opentrons/hardware_control/types.py
> +    HOLDING_OPENED = enum.auto()
That's for the future. In this first implementation, we'll definitely be holding the gripper homed. The thing is that the gripper jaw is a DC motor that will need to be actively controlled and will likely jitter a little; so when we add that control loop, we'll want the default position to be like 1mm away from the switch so it doesn't keep bouncing off it.

2022-07-07 14:29 UTC, DerekMaggio commented on api/src/opentrons/config/gripper_config.py
> +    """
Yeah, that is helpful. How did we generate these values? Experimentally again?

2022-07-07 14:30 UTC, DerekMaggio commented on api/src/opentrons/hardware_control/ot3api.py
> +                if OT3Axis.G in checked_axes and self._gripper_handler.has_gripper():
Oh sorry, missed that. Definitely a little rusty after being gone for so long. Thanks for clarifying

2022-07-07 14:34 UTC, DerekMaggio approved these changes
LGTM, besides comment stuff in `piecewise_force_conversion`, but that shouldn't stop it from being merged

2022-07-07 16:49 UTC, sfoster1 commented on api/src/opentrons/config/gripper_config.py
> +    """
Yup

2022-07-07 18:00 UTC, sfoster1 approved these changes
good

2022-07-07 18:18 UTC, Laura-Danielle approved these changes
Most of my comments are around naming stuff. I am still a bit confused around the separation of `XHandlerProvider` classes and `XInstrument` classes where X is either pipette or gripper, though I was late to the game on reviewing this stuff. I don't know why we wouldn't ever have a gripper and/or pipette at the time that those objects are created because it seems like something that should be handled by `cache_instruments`.

I don't think that those concerns need to be addressed by this PR though, so feel free to only address some of the comments I put.

2022-07-07 18:18 UTC, Laura-Danielle commented on api/src/opentrons/config/defaults_ot3.py
> +        OT3AxisKind.Z: 1.4,
Are we switching to tmc2160 for the gripper? If not, this current is kinda high for the 2130.

2022-07-07 18:18 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3utils.py
> +GRIPPER_JAW_GRIP_TIME: float = 1
Should these default configurations live in shared data at some point?

2022-07-07 18:18 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/gripper_handler.py
> +    def has_gripper(self) -> bool:
Why do we need both `has_gripper` and `verify_gripper`?

2022-07-07 18:18 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/gripper_handler.py
> +    def verify_gripper(self) -> Gripper:
It seems very weird to me to return a gripper object from a function called `verify_gripper`. It doesn't seem like this function should return anything.

2022-07-07 18:18 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        return True
I don't see the usage of the boolean anywhere. We should remove it if it's not needed, otherwise we should verify that the message was successful via the can driver.

2022-07-07 18:18 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/gripper_handler.py
>          self._gripper = gripper
I know I am a bit late to the party on reviewing this refactor, but it really doesn't make sense to me to create/have a gripper handler if no gripper is found in cache instruments. Is that something that will be done in a follow-up?

2022-07-07 18:18 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/gripper_handler.py
> +    def get_duty_cycle_by_grip_force(self, newton: Optional[float] = 0) -> float:
Can we make the default `None` here?

2022-07-07 18:18 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +        await self._release()
Can we call this `release_gripper`, otherwise it's a bit generic for me. Technically the 96 channel could also "release" tips.

2022-07-07 18:18 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/constants.py
> +gripper_interrupts_per_sec: Final = 32000
Can we instead call this `brushed_motor_interrupts_per_sec` and `stepper_motor_interrupts_per_sec` since we have a few places where we include `gripper_z` as a way to refer to the Z stepper motor on the gripper?

2022-07-07 18:34 UTC, sfoster1 commented on api/src/opentrons/config/defaults_ot3.py
> +        OT3AxisKind.Z: 1.4,
it's pretty high but unfortunately it's necessary, the axis binds up otherwise. Uh we should probably separate the gripper z axis in axis kinds at some point because it's really separate from the other two.

2022-07-07 18:35 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3utils.py
> +GRIPPER_JAW_GRIP_TIME: float = 1
No because these are only short term workarounds - the gripper will not be moving for a duration, it will be moving either until it sees that it's reached where it wanted to go, or doing force control.

2022-07-07 18:35 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/gripper_handler.py
> +    def has_gripper(self) -> bool:
verify_gripper raises, has_gripper doesn't - they're useful in slightly different cases

2022-07-07 18:35 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/gripper_handler.py
> +    def verify_gripper(self) -> Gripper:
Yeah, what's a better name for it? `get_gripper`?

2022-07-07 18:36 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/gripper_handler.py
>          self._gripper = gripper
Well, it pushes the optional handling down to inside the gripper handler - it's done by analogy with the instrument handler, it's an always-present container for an optionally-present object.

2022-07-07 18:37 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        await self._release()
what about `ungrip`?

2022-07-07 18:39 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/gripper_handler.py
> +    def verify_gripper(self) -> Gripper:
sure that works I suppose

2022-07-07 18:40 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +        await self._release()
sure

2022-07-07 18:56 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/constants.py
> +gripper_interrupts_per_sec: Final = 32000
> Most of my comments are around naming stuff. I am still a bit confused around the separation of `XHandlerProvider` classes and `XInstrument` classes where X is either pipette or gripper, though I was late to the game on reviewing this stuff. I don't know why we wouldn't ever have a gripper and/or pipette at the time that those objects are created because it seems like something that should be handled by `cache_instruments`.

It admittedly makes a bit less sense with the gripper, but with the pipettes it's because the instrument handler exists to commonize a bunch of code that's the same between the ot2 and ot3 implementations, and it's separate from whether there's a pipette or not. The gripper_handler is by analogy to the pipettes, though there's nothing to hold the implementations in common with. I think it's reasonable to simplify these in the future.

2022-07-07 19:03 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        await self._release()
https://github.com/Opentrons/opentrons/pull/10987/commits/3b239614733b5dfc731647b81c3cf6ff0b2f1088

2022-07-07 19:03 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/gripper_handler.py
> +    def get_duty_cycle_by_grip_force(self, newton: Optional[float] = 0) -> float:
https://github.com/Opentrons/opentrons/pull/10987/commits/5c9d433fa3a38ba841cac4c583414387906b8ace

2022-07-07 19:04 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/constants.py
> +gripper_interrupts_per_sec: Final = 32000
> Can we instead call this `brushed_motor_interrupts_per_sec` and `stepper_motor_interrupts_per_sec` since we have a few places where we include `gripper_z` as a way to refer to the Z stepper motor on the gripper?

https://github.com/Opentrons/opentrons/pull/10987/commits/27bb0e4ba8cf1495b3b6881ded51716dc4d16cd5

2022-07-07 19:04 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        return True
https://github.com/Opentrons/opentrons/pull/10987/commits/708c532265cd1706fe6a83a59b1a76327e75a166

2022-07-07 19:08 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/gripper_handler.py
> +    def verify_gripper(self) -> Gripper:
https://github.com/Opentrons/opentrons/pull/10987/commits/e1ab52db0ec7d5ba73c85ff83a6eccf8c44b19e9

2022-07-07 19:15 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/gripper_handler.py
>          self._gripper = gripper
I would argue that there should be a separate 'what instruments are available' class/container to handle that. Especially since this guy has the responsibility of determining state on the gripper itself and grabbing configurations.

But again, something that can be discussed another time and not really relevant to this PR.

2022-07-07 19:15 UTC, Laura-Danielle approved these changes
Changes look good. Let's discuss the instrument handling stuff separately. Def not needed for this PR.

2022-07-07 20:40 UTC, merged