feat(app): Robot Settings Design QA 2 and Create Select App Component
OpenTrons/opentrons-api pull request #11020
Opened 2022-07-06 18:01 UTC by jerader

closes #10893

# Overview

This PR addresses design QA on all 3 tabs in Robot Settings: Advanced, Calibration, and Networking.

Additionally, this PR creates a new shared `Select` and `SelectFields` components to live in the App/Atoms folder

# Changelog

- make changes to `RobotSettingsCalibration`, `RobotSettingsAdvanced` and `RobotSettingsNetworking` and associated components
- create new `Select` and `SelectFields` as well as a `Select.stories`

# Review Requests

- do these pages match the designs?
- go to the networking tab and examine the `Select` component - do the buttons in the menu work as expected? Does it match designs?

# Risk assessment

low

2022-07-07 12:56 UTC, jerader commented on app/src/organisms/Devices/RobotSettings/AdvancedTab/UpdateRobotSoftware.tsx
> +      <Flex width="70%" flexDirection={DIRECTION_COLUMN}>
I changed all these `boxes` to `flexes` throughout `RobotSettingsAdvanced` because when adding the `pSemiBold` to `StyledText` as a `as='pSemibold'`, the `marginBottom` in the `StyledText` wasn't being acknowledged. Later, when running the checks, it turned out that `pSemiBold` needed to be used a different way `(css={TYPOGRAPHY.pSemiBold}` which then allowed for `marginBottom` to work properly. Long story short: I could have kept the `boxes` but I changed them everywhere to `flexes` and didn't go back and revert the change. LMK if I should change them back though

2022-07-07 15:51 UTC, mmencarelli commented
**Round 3 feedback on Robot Settings page**


- [ ] (1) Didn't catch this before, but can we remove the text wrapping for the open menu? We can make this a site-wide thing if it's the same amount of time! 
- [ ] (2) Looks like the open menu overflow isn't closing when you click on the button again? Possible to fix? Loom video showing issue [here](https://www.loom.com/share/5cd410e781674ffa88526faf17441641). 
- [ ] (3) just got a wee bit of extra meat here

<img width="665" alt="Screen Shot 2022-07-07 at 8 43 36 AM" src="https://user-images.githubusercontent.com/54682054/177815530-8a2c42df-2755-40a3-8b63-da58f75e1ccf.png">

- [ ] (1) Have we gotten rid of the green check marks? If so, can you let me know and also move the content to the left to align with the start of "calibration" above? 

<img width="570" alt="Screen Shot 2022-07-07 at 8 45 30 AM" src="https://user-images.githubusercontent.com/54682054/177815976-10b26ffc-05eb-4428-bff8-d5b674d1f60d.png">

- [ ] (1) We just need 40px margin above all the h2's (except the first one). I'm sorry, i know it's not quite clear what is a header and what is a subhead. Something I'm looking to fix in the future! So the h2's that need the 40px margin-top are: "Usage Settings", "Troubleshooting", "Legacy Settings". 
- [ ] (2) Looks like there's some extra meat here 

<img width="701" alt="Screen Shot 2022-07-07 at 8 51 13 AM" src="https://user-images.githubusercontent.com/54682054/177817039-eb2675f2-8c91-45e9-bec0-a8917debc1e8.png">

2022-07-07 15:52 UTC, mmencarelli requested changes
Slight changes left above! Thanks, Jethary, looking great!

2022-07-07 19:17 UTC, koji commented on app/src/atoms/SelectField/Select.tsx
> +  | 'create-option'
react-select exports the same type as [`ActionTypes`](https://github.com/JedWatson/react-select/blob/b0411ff46bc1ecf45d9bca4fb58fbce1e57f847c/packages/react-select/src/types.js#L78).

Can we use `import type` instead of adding a type?

2022-07-07 19:17 UTC, koji commented on app/src/atoms/SelectField/Select.tsx
> +          height={TYPOGRAPHY.lineHeight16}
```suggestion
          height={SIZE_1}
```

2022-07-07 19:17 UTC, koji commented on app/src/atoms/SelectField/index.tsx
> +  value: string | null | undefined
```suggestion
  value?: string | null 
```

2022-07-07 19:17 UTC, koji commented on app/src/atoms/SelectField/index.tsx
> +  error?: string | null | undefined
```suggestion
  error?: string | null 
```

2022-07-07 19:17 UTC, koji commented on app/src/organisms/Devices/RobotSettings/CalibrationDetails/PipetteOffsetCalibrationItems.tsx
> +  border-bottom: ${BORDERS.lineBorder};
When I tried to leave a comment, yours was gone 😂
Maybe we can use `:after`?
like this
https://codesandbox.io/s/heuristic-black-yt6bu1?file=/src/App.tsx

2022-07-07 19:17 UTC, koji commented on app/src/atoms/SelectField/index.tsx
> +        onChange={opt => onValueChange && onValueChange(name, opt?.value || '')}
maybe

```suggestion
        onChange={opt => onValueChange?.(name, opt?.value || '')}
```

2022-07-07 19:17 UTC, koji commented on app/src/atoms/SelectField/index.tsx
> +        onBlur={() => onLoseFocus && onLoseFocus(name)}
same as the above

2022-07-07 19:17 UTC, koji commented on app/src/atoms/SelectField/Select.tsx
> +import ReactSelect, { components, DropdownIndicatorProps } from 'react-select'
`make check-js` shows the following error.

```zsh
make check-js
yarn tsc --build
yarn run v1.22.18
opentrons/node_modules/.bin/tsc --build
app/src/atoms/SelectField/Select.tsx:2:35 - error TS2614: Module '"../../../../node_modules/@types/react-select"' has no exported member 'DropdownIndicatorProps'. Did you mean to use 'import DropdownIndicatorProps from "../../../../node_modules/@types/react-select"' instead?

2 import ReactSelect, { components, DropdownIndicatorProps } from 'react-select'
                                    ~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [Makefile:237: build-ts] Error 1
```

2022-07-07 19:25 UTC, jerader commented on app/src/atoms/SelectField/Select.tsx
> +  | 'create-option'
oh good catch!

2022-07-08 16:37 UTC, mmencarelli requested changes
Looks like this comment didn't get implemented? 

We just need 40px margin above all the h2's (except the first one). I'm sorry, i know it's not quite clear what is a header and what is a subhead. Something I'm looking to fix in the future! So the h2's that need the 40px margin-top are: "Usage Settings", "Troubleshooting", "Legacy Settings".


<img width="1089" alt="Screen Shot 2022-07-08 at 9 37 27 AM" src="https://user-images.githubusercontent.com/54682054/178034094-cdb7482b-069d-4c76-8706-5977b72a0546.png">

2022-07-08 17:27 UTC, mmencarelli approved these changes

2022-07-12 12:51 UTC, jerader commented on components/src/forms/Select.tsx
> +  }),
This was added so the input text appears in between the borders

2022-07-12 12:52 UTC, jerader commented on labware-library/src/labware-creator/components/__tests__/sections/CreateNewDefinition.test.tsx
> +    const labwareTypeDropdown = getByRole('combobox', {
react select version 5 no longer recognizes `textbox` as a role. Instead, it's a `combobox` I think the change actually happened in react select version 4

2022-07-12 13:08 UTC, jerader commented on app/src/organisms/CalibrationPanels/ChooseTipRack.tsx
> +              //  @ts-expect-error(jr 7/11/22): multi select will not happen, resolve this error
I had a hard time trying to fix these ts errors. Mutli select was introduced in version 4 and had a hard time understanding how to make `onChange` only be Single Select

2022-07-12 14:01 UTC, vabruzzo commented on app/src/atoms/SelectField/Select.stories.tsx
> +)
Not necessary for this PR but we can probably add `'**/*.stories.tsx'` to the code coverage ignores

2022-07-12 14:09 UTC, vabruzzo commented on app/src/atoms/SelectField/Select.tsx
> +  clearIndicator: NO_STYLE_FN,
What happens if we just don't assign anything to these values that we don't use? I'm guessing it defaults to some library styles that we don't want?

2022-07-12 14:18 UTC, jerader commented on app/src/atoms/SelectField/Select.tsx
> +  clearIndicator: NO_STYLE_FN,
yup, without that, it defaults to React Select default styling

2022-07-12 14:20 UTC, jerader commented on app/src/atoms/SelectField/Select.stories.tsx
> +)
I agree, definitely a good idea for a follow up pr

2022-07-12 14:24 UTC, vabruzzo commented on app/src/atoms/SelectField/index.tsx
> +  onValueChange?: (name: string, value: string) => unknown
i think we can return void for these two?

2022-07-12 14:25 UTC, vabruzzo commented on app/src/atoms/SelectField/index.tsx
> +        //  @ts-expect-error(jr, 7/6/22): value will never be multi value select option
i believe this ts-expect is unnecessary?

2022-07-12 14:28 UTC, vabruzzo commented on app/src/organisms/CalibrationPanels/ChooseTipRack.tsx
> +              //  @ts-expect-error(jr 7/11/22): multi select will not happen, resolve this error
strangely these are not errors when pull in and look at the code. is it possible a change you made after adding these `ts-expect`s fixed the error?

2022-07-12 14:41 UTC, vabruzzo commented on app/src/organisms/Devices/RobotSettings/AdvancedTab/UpdateRobotSoftware.tsx
> +      <Flex width="70%" flexDirection={DIRECTION_COLUMN}>
I lean towards changing them back to `Box` and only using `Flex` when we are utilizing `Flex`'s unique properties. in principle there are minor differences including a possible negligible performance difference but in practice I don't think we would ever run into these issue, so my opinion is not strongly held. Curious what others think?

The main reason I think we should change back is semantic intent: if someone new to the codebase sees `Flex`s that aren't using flex properties they may be left wondering what problem we were solving using the `Flex` instead of the default `display: block`

2022-07-12 14:47 UTC, vabruzzo commented on app/src/organisms/Devices/RobotSettings/AdvancedTab/UpdateRobotSoftware.tsx
> +      <Flex width="70%" flexDirection={DIRECTION_COLUMN}>
The main reason I think we should change back is semantic intent: if someone new to the codebase sees `Flex`s that aren't using flex properties they may be left wondering what problem we were solving using the `Flex` instead of the default `display: block`

2022-07-12 15:16 UTC, jerader commented on app/src/organisms/Devices/RobotSettings/AdvancedTab/UpdateRobotSoftware.tsx
> +      <Flex width="70%" flexDirection={DIRECTION_COLUMN}>
Just changed all the `flex`es back to using `box`es 👍

2022-07-12 15:46 UTC, mmencarelli commented
Looking great. The only thing I'm catching is that the tertiary button's padding is a bit off. Should be .5rem padding top and bottom with 1rem l/right. It current is 6px top and bottom and 12px l/r. Not sure if it's this PR that should address that.

2022-07-12 21:26 UTC, vabruzzo approved these changes
code here looks good to me 👍  thank you for splitting out the select work!

2022-07-12 21:29 UTC, merged