fix(papi-v2): allow pick_up_tip to pick up from exact location
OpenTrons/opentrons-api pull request #11038
Opened 2022-07-07 15:46 UTC by TamarZanzouri

# Overview

closes #7774.
PAPIv2 documentation mentions picking up tip from a specified location.
The implementation details always moved to top.
If type is `types.Location` and `is_well()` we use specified location.

# Changelog

- Added decoy test file to test instrument_context
- Changed imports in instrument_context to use global imports 
- changed logic when pick_up_tip is called to use location when using types.Location and when the type is Well

# Review requests

1. is it ok I changed to global imports? 
3. Do we write tests for the other scenario's to make sure nothing else is effected? its being tested in the old tests 
4. Are the tests sufficient? 

# Risk assessment

Medium. Changed logic of pick_up_tip end point in PAPIV2. Need to make sure it works and nothing else is effected

2022-07-12 19:56 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/instrument_context.py
> +from .labware import Labware, OutOfTipsError, Well
still need to move this and use the global import for labware

2022-07-13 17:01 UTC, mcous requested changes
Testing thoughts and feedback. I think the changes to the subject are good! Shifting over to module imports gives us more room to test and tweak the design moving forward

2022-07-13 17:01 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +from opentrons.protocol_api import labware
Prefer local imports from the same level

```suggestion
from . import labware
```

2022-07-13 17:01 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +                target: labware.Well = tiprack.next_tip(self.channels)  # type: ignore
I'm having trouble figuring out what `target` is for now that there's a `move_to_location`. Could it be renamed `target_well` or something more descriptive?

Also, can we remove this `# type: ignore` comment?

2022-07-13 17:01 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +from opentrons.protocol_api.labware import next_available_tip
Imports in the test file should match how you do them in the source file. So rather than `from opentrons.protocol_api.labware import next_available_tip`, you should be doing `from opentrons.protocol_api import labware`.

That way, you can use the mocks set up by your fixtures outside of the fixtures themselves, which you need to fully test the functionality. See comment below in the `patch_mock_next_available_tip` fixture

2022-07-13 17:01 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +    return decoy.mock(cls=Well)
Given these fixtures are used simply as values in tests, and it's doesn't change the length of the tests at all, I would simply use `mock_well = decoy.mock(cls=Well)` in the test itself rather than create a fixture

2022-07-13 17:01 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +    mock_next_available_tip = decoy.mock(func=next_available_tip)
Continued comment from above: The problem with importing `next_available_tip` directly like this is that you can't use the mock function outside of the fixture.

Instead, if this becomes `mock_next_available_tip = decoy.mock(func=instrument.next_available_tip)`, this in any test function, you can do:

```python
decoy.when(labware.next_available_tip(...)).then_return(...)
```

2022-07-13 17:01 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +    )
I would move this stubbing to the tests that need it rather than configure it as a default behavior, which forces us to do things like create fixtures for `mock_labware` and `mock_well`, which I think makes these tests harder to follow

2022-07-13 17:01 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +def patch_mock_next_available_tip(
Two things:

- Can we rename this fixture so that it makes it clear our intent is to mock out _all_ functions of the `labware` module, not just `next_available_tip`?
- I saw a convention recently saw that I think we should start doing: name `autouse` fixtures that return `None` (i.e. side-effect only fixtures) with a starting underscore, to differentiate them with fixtures we opt into using

2022-07-13 17:01 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +    )
These two fixtures should be combined. Try to think about these patchings a mocking out all the the entire `instrument` module rather than mocking out the individual functions.

The main risk with this `monkeypatch` business is accidentally creating [partial mocks](https://github.com/testdouble/contributing-tests/wiki/Partial-Mock).

If we continue with this module mocking strategy in general (and I think we will, I think the benefits outweigh the risks), I'd look to create a new `decoy` method to _fully_ mock out a given module object. Something along the lines of:

```python
@pytest.fixture(autouse=True)
def _mock_instrument_module(decoy: Decoy) -> None:
    decoy.replace(instrument)
```

2022-07-13 17:01 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +    decoy.when(subject.channels).then_return(0)
This line should be removed; we cannot mock anything about our test subject, so this is definitely a no-op. Given that this isn't raising an error, it means it's probably messing with a different mock unintentially (due to how Decoy works internally.

Even if we _were_ able to mock out bits of our test subject, we [definitely shouldn't](https://github.com/testdouble/contributing-tests/wiki/Partial-Mock#contaminated-test-subjects)

2022-07-13 17:01 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +@pytest.mark.parametrize(
Given how the subject works, I think we should ditch parameterization here and stick to individual tests. The expected behavior is nuanced enough that even in this case, our test body contains of stubbings that are only for one of these two cases, which confuses the story our tests should be telling us

2022-07-13 17:01 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +    move_to_location = initial_location.move(point=Point(x=-100, y=-100, z=0))
These are the same thing, we don't need both of them

2022-07-13 17:01 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +    decoy.when(subject._ctx._modules).then_return([])
This stubbing should be configured on `mock_protocol_context`, not a private member of the test subject

2022-07-13 17:01 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +    decoy.when(subject._ctx._modules).then_return([])
Do not configure stubbing on private members of the test subject, configure them on the injected dependency

2022-07-13 17:01 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +    decoy.when(subject._ctx._modules).then_return([])
Stub injected dependency, not private member of subject

2022-07-13 17:01 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +    decoy.when(subject._ctx._modules).then_return([])
Same comment

2022-07-13 20:24 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +    decoy.when(subject.channels).then_return(0)
@mcous really good feedback thank you!

2022-07-13 20:37 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +@pytest.mark.parametrize(
@mcous Really good catch!

2022-07-14 20:08 UTC, TamarZanzouri commented
Tested on a robot. Works as expected. I have attached a video of a protocol with a weird Point for documentation and follow-ups.

2022-07-22 15:35 UTC, mcous approved these changes
Code looks really good, appreciate the much needed addition of `test_instrument_context.py`.

What's out on-robot testing status for this PR? I'm happy for this to merge as soon as it's confirmed on hardware

2022-07-22 16:11 UTC, TamarZanzouri commented
> appy for this to merge as soon as it's confirmed on hardwar

@mcous this was tested on a robot and worked as expected!

2022-07-22 16:11 UTC, merged