feat(app): device Details design qa round 2 and fix pipette overflow btn bug
OpenTrons/opentrons-api pull request #11054
Opened 2022-07-08 13:05 UTC by jerader

closes #10892

# Overview

- Address design qa feedback on device details page including module card display, historical protocol run design tweaks, and fixing a bug with the pipette overflow menu not closing when clicking on the button

# Changelog

- change `DeviceDetails` and associated components
- fix bug in `pipetteCard` by adding `MenuOverlay` and using the `useMenuHandleClickOutside` hook
- add some logic for module card `minHeight` depending on viewport size and how many module cards there are

# Review requests

- review Device Details, does it match designs?
- does logic for module card `minHeight` make sense

# Risk assessment

low

2022-07-08 16:47 UTC, mmencarelli requested changes
Just a few things :) 

- [x] (1) Make this 1rem vs .5rem
<img width="1066" alt="Screen Shot 2022-07-08 at 9 43 35 AM" src="https://user-images.githubusercontent.com/54682054/178035107-3e7e51d0-515f-4a7f-9e7b-377b2c10711a.png">

- [ ] (2) The issue of the menu overflow button not closing the open menu on click has been fixed in that 1 module but is still persistent in a majority of places throughout this page. Can we fix? [Loom video](https://www.loom.com/share/6fd2f6b26a0a495ebe172042f814e180)

2022-07-08 16:56 UTC, jerader commented
> [ ] (2) The issue of the menu overflow button not closing the open menu on click has been fixed in that 1 module but is still persistent in a majority of places throughout this page. Can we fix?

@mmencarelli , oh yeah, I see! I only fixed the issue with the pipette cards, not realizing the module cards also had the issue. I'll address that now 😄

2022-07-08 19:42 UTC, mmencarelli requested changes
Problem with the menu overflow button not closing the open menu still persisting on the protocol run section for me?

2022-07-08 21:11 UTC, koji approved these changes
🦾

both overflow menus (Mel pointed out in design feedback and in her comment) work as expected.

2022-07-08 21:11 UTC, koji commented on app/src/organisms/Devices/HistoricalProtocolRunOverflowMenu.tsx
> +          <div
Can we change `div` to `Box`?

2022-07-08 21:11 UTC, koji commented on app/src/organisms/Devices/HistoricalProtocolRunOverflowMenu.tsx
>    }) as React.RefObject<HTMLDivElement>
This is related to #11009

```suggestion
  const protocolRunOverflowWrapperRef = useOnClickOutside<HTMLDivElement>({
    onClickOutside: () => setShowOverflowMenu(false),
  })
```

2022-07-11 14:20 UTC, mmencarelli approved these changes

2022-07-11 14:26 UTC, merged