refactor(app): LPC stop shaking and close labware latch
OpenTrons/opentrons-api pull request #11156
Opened 2022-07-18 14:02 UTC by shlokamin

closes #11126

# Overview

# Changelog

# Review requests

# Risk assessment

2022-07-26 14:28 UTC, jerader approved these changes
code LGTM, how come we are not making sure we are deactivating the heater before LPC? I guess we don't need to since we aren't deactivating the heater for the other modules.

2022-07-26 16:12 UTC, sakibh approved these changes
Looks great!

2022-07-26 21:22 UTC, ecormany requested changes, later dismissed
Tested on H-S hardware running 0.4.4 firmware, 6.0.0 production robot server.

If shaking, H-S stops shaking and homes when starting LPC. Pipette moves to all the right places during LPC.

If the latch is open, the gantry never moves and LPC times out. I got this error message:
```
error_modal_text

Error: movement command id 3c5778a6-3cec-4a4a-913b-f1a326a4a957 failed on the robot
```

The run log was not particularly illuminating:
```json
    {
      "id": "3c5778a6-3cec-4a4a-913b-f1a326a4a957",
      "key": "3c5778a6-3cec-4a4a-913b-f1a326a4a957",
      "commandType": "moveToWell",
      "createdAt": "2022-07-26T21:12:28.301246+00:00",
      "completedAt": "2022-07-26T21:13:10.881735+00:00",
      "status": "failed",
      "params": {
        "labwareId": "labware-0",
        "wellName": "A1",
        "wellLocation": {
          "origin": "top",
          "offset": {
            "x": 0,
            "y": 0,
            "z": 0
          }
        },
        "pipetteId": "pipette-0"
      },
      "intent": "setup"
    },
```

There was a deactivate shaker command a couple entries above this, which also failed (the module wasn't shaking).

2022-07-27 17:53 UTC, ecormany requested changes
New weirdness:
- Properly closes latch when LPC starts.
- If shaking when LPC starts…
    - will fail if shake was started from the Test Shake slideout in the Module Controls tab for that run, with error `Error: movement command with type heaterShaker/setAndWaitForShakeSpeed and id [id] failed on the robot`
    - will succeed (properly stopping the shake) if the module is already shaking when the run is loaded

2022-07-28 16:18 UTC, ecormany approved these changes
Update: toggle labware latch :arrow_right: set shake :arrow_right:  LPC works :white_check_mark:

@shlokamin will ensure that the latch state is correct in a follow-up PR.

2022-07-28 19:14 UTC, merged