feat(g-code-parsing):  Add ability to run multiple PAPI versions
OpenTrons/opentrons-api pull request #11221
Opened 2022-07-26 14:11 UTC by DerekMaggio

# Overview

Added ability to run G-Code Parsing protocols against multiple PAPI versions. 

# Changelog

- Modified `ProtocolGCodeConfirmConfig` to have a `versions` parameter that requires a list of APIVersion objects. This tells the protocol what versions it can run against. 
  - Addresses [RQA-124](https://opentrons.atlassian.net/browse/RQA-124)
- Updated all protocols inside protocol_configurations.py and added APIVersions `2.12` and `2.13`
  - Addresses [RQA-125](https://opentrons.atlassian.net/browse/RQA-125)
- Updated GCodeEngine.run_protocol() to accept a `version` argument to run a specific version
  - Partially addresses [RQA-122](https://opentrons.atlassian.net/browse/RQA-122)
- Ran all protocols against all versions (2.12 & 2.13) and stored their output
  - This addresses the rest of [RQA-122](https://opentrons.atlassian.net/browse/RQA-122) 

# Review requests

- cli.py and g_code_configuration.py are each kind of a mess & not super DRY any suggestions to clean them up?

# Risk assessment

After merging, this will break G-Code tests for PRs that have not pull this in.

2022-07-26 16:55 UTC, DerekMaggio commented
Tested that the new `Verify no missing comparison files` fails when a configuration file is missing. 
Added a version that was not populated, committed, pushed, and made sure it failed. 
Then dropped the commit and force pushed over it to remove it from the history.

2022-07-26 19:58 UTC, sfoster1 requested changes
This makes sense to me but there's a couple of little changes we could make to make the configurations thing a little easier.

I also don't quite see a path for anything where we'd need to change a protocol to match a specific api version - is the idea that you'd just make another protocol e.g. called `2_modules_v2.9.py` and add a new configuration?

Also at some point can we go and remove all the language about s3 and uploading and such?

2022-07-26 19:58 UTC, sfoster1 commented on g-code-testing/README.md
> +protocols/2.12/2_modules
This seems minor but I think it could be a usability win. Let's swap the order of the module name and version: `protocols/2_modules/2.12`. Then, let's allow a wildcard for the version (or not specifying it) - `protocols/2_modules` or `protocols/2_modules/*`. That lets you run all the versions of that protocol. 

Honestly, full wildcard support here might be super useful.

2022-07-26 19:58 UTC, sfoster1 commented on g-code-testing/g_code_test_data/protocol/protocol_configurations.py
>  BASIC_SMOOTHIE = ProtocolGCodeConfirmConfig(
a bit of a nit, but `results_dir` is literally always `DIRECTORY` - can we make this built in to the `ProtocolGCodeConfirmConfig` and save a bunch of typing?

2022-07-26 19:58 UTC, sfoster1 commented on g-code-testing/g_code_test_data/protocol/protocol_configurations.py
>  BASIC_SMOOTHIE = ProtocolGCodeConfirmConfig(
With a custom constructor for the dataclass or a builder, we could even make `name` default to the `basename` of the protocol file and only need to separately set it if it's different from the file

2022-07-26 20:50 UTC, mcous requested changes
Missing `api_version` arg for `ProtocolContextImplementation`.

Broadly, I think this is a good change, but I'm a little stuck on what to do about the `metadata.apiLevel` field in all these source protocols. It's completely ignored, and it takes some digging to find that out.

I wonder if we should do something small to make this clear; e.g. add a comment to all the source protocols' `metadata` dict to note that it's ignored

2022-07-26 20:50 UTC, mcous commented on g-code-testing/g_code_parsing/g_code_engine.py
>                  implementation=ProtocolContextImplementation(sync_hardware=h.sync),
This needs the `api_version` argument, too

2022-07-27 17:41 UTC, DerekMaggio commented on g-code-testing/README.md
> +protocols/2.12/2_modules
https://github.com/Opentrons/opentrons/pull/11221/commits/42a2492ab7736331820e4fb5709dcac615dba2be
Check this out

2022-07-27 17:41 UTC, DerekMaggio commented on g-code-testing/g_code_test_data/protocol/protocol_configurations.py
>  BASIC_SMOOTHIE = ProtocolGCodeConfirmConfig(
> With a custom constructor for the dataclass or a builder, we could even make `name` default to the `basename` of the protocol file and only need to separately set it if it's different from the file

Not sure what you mean by this

2022-07-27 17:42 UTC, DerekMaggio commented on g-code-testing/g_code_test_data/protocol/protocol_configurations.py
>  BASIC_SMOOTHIE = ProtocolGCodeConfirmConfig(
> a bit of a nit, but `results_dir` is literally always `DIRECTORY` - can we make this built in to the `ProtocolGCodeConfirmConfig` and save a bunch of typing?

https://github.com/Opentrons/opentrons/commit/42a2492ab7736331820e4fb5709dcac615dba2be

2022-07-27 17:56 UTC, DerekMaggio commented on g-code-testing/g_code_parsing/g_code_engine.py
>                  implementation=ProtocolContextImplementation(sync_hardware=h.sync),
https://github.com/Opentrons/opentrons/pull/11221/commits/bf85a6078f4de7c60d826049b80ccd540ea27d29

2022-07-27 17:56 UTC, DerekMaggio commented
> Broadly, I think this is a good change, but I'm a little stuck on what to do about the `metadata.apiLevel` field in all these source protocols. It's completely ignored, and it takes some digging to find that out.
> 
> I wonder if we should do something small to make this clear; e.g. add a comment to all the source protocols' `metadata` dict to note that it's ignored

https://github.com/Opentrons/opentrons/pull/11221/commits/0e13a99343f865c9e0d8b7b45d7a827f62ef0735

2022-07-27 18:31 UTC, mcous approved these changes
🚢

2022-07-27 21:10 UTC, DerekMaggio commented
@sfoster1 bd49a7411fabef51e9e3d8277f039924234984fa

2022-07-28 15:40 UTC, sfoster1 approved these changes
Nice! Looks good to me!

2022-07-28 15:40 UTC, merged