feat(app): this will close #11220
OpenTrons/opentrons-api pull request #11232
Opened 2022-07-26 21:46 UTC by koji

# Overview
This PR will replace lookup with search google in electron-context-menu.
fix #11220

https://user-images.githubusercontent.com/474225/181117661-e1ae651f-0e89-4205-b3e6-9b410567e7eb.mov

# Changelog
- update electron-context-menu
- replace lookup method with search google method

# Review requests
- [ ] context menu shows `search with google` instead of `lookup`
- [ ] copy works properly
- [ ] inspect element works properly

# Risk assessment
low

2022-07-27 14:20 UTC, ecormany requested changes
This appears to be incompatible with the React Select update merged in #11104. I get this error when `make setup-js` was most recently done from `edge`:

```
[shell] 10:08:27.956 [main] error: Uncaught:  {
[shell]   error: TypeError: actions.searchWithGoogle is not a function
[shell]       at Object.menu (webpack-internal:///./src/main.ts:74:49)
[shell]       at Object.<anonymous> (/Users/edwardcormany/opentrons/app-shell/node_modules/electron-context-menu/index.js:180:27)
[shell]       at Object.emit (events.js:315:20)
[shell] }
```

The error happens every time I right-click (and no contextual menu appears).

If I do teardown and setup on this branch, everything works as expected.

2022-07-27 14:24 UTC, jerader commented
> This appears to be incompatible with the React Select update merged in #11104. I get this error when `make setup-js` was most recently done from `edge`:
> 
> ```
> [shell] 10:08:27.956 [main] error: Uncaught:  {
> [shell]   error: TypeError: actions.searchWithGoogle is not a function
> [shell]       at Object.menu (webpack-internal:///./src/main.ts:74:49)
> [shell]       at Object.<anonymous> (/Users/edwardcormany/opentrons/app-shell/node_modules/electron-context-menu/index.js:180:27)
> [shell]       at Object.emit (events.js:315:20)
> [shell] }
> ```
> 
> The error happens every time I right-click (and no contextual menu appears).
> 
> If I do teardown and setup on this branch, everything works as expected.

I think @koji might need to rebase edge and then this error might fix itself @ecormany

2022-07-28 14:17 UTC, vabruzzo approved these changes

2022-08-01 23:40 UTC, koji commented on app-shell/src/main.ts
> +      return config.devtools
enabled devtools: copy, search with google, and inspect element
disabled devtools: copy and search with google

2022-08-02 17:15 UTC, ecormany approved these changes
Forgot I had to do `make teardown-js setup-js`…but it's working now! 🚢

2022-08-03 12:14 UTC, merged