refactor(app): remove brackets of string attributes
OpenTrons/opentrons-api pull request #11242
Opened 2022-07-27 22:38 UTC by MichaelMulieri

# Overview
Removed brackets of string attributes in components.
Closes #11211.

# Changelog
- Replace instances of `value={'string prop'}` with `value="string prop"`

# Review requests
Confirm correct replacements. 

# Risk assessment
Low.

2022-07-27 23:24 UTC, MichaelMulieri commented on app/src/organisms/Devices/HeaterShakerWizard/AttachModule.tsx
>                  data-testid={`AttachModule_empty_deck`}
In these changes I noticed what I think are unnecessary string interpolations.  Does that sound right?  If so I opened an issue #11243 that I would be glad to take on.

2022-07-28 00:05 UTC, vabruzzo commented on app/src/organisms/LabwarePositionCheck/DeckMap.tsx
> +                  strokeWidth="3px'"
Extra trailing single quote here to remove

2022-07-28 00:11 UTC, vabruzzo requested changes
Thanks for this contribution, it looks great! There was one small issue with an extra single quote

2022-07-28 14:10 UTC, vabruzzo commented on app/src/organisms/Devices/HeaterShakerWizard/AttachModule.tsx
>                  data-testid={`AttachModule_empty_deck`}
this sounds good to me

2022-07-28 14:53 UTC, koji approved these changes
The changes look good to me ✨
Thank you for your contribution!

2022-07-28 14:55 UTC, vabruzzo approved these changes

2022-07-28 21:10 UTC, merged