fix(app, app-shell): fix python override path select on windows
OpenTrons/opentrons-api pull request #11257
Opened 2022-07-29 03:38 UTC by vabruzzo

# Overview
Refactors Python "Override Path to Python" functionality on Advanced tab of App Settings page. Per @mcous's suggestion in RAUT-61, this refactor mirrors the "select custom labware directory" logic, i.e. this change removes the directory selecting functionality from `app` which now only dispatches an action. `app-shell` then handles the dialog functionality using `electron`'s `dialog`.
Closes RAUT-61.

# Changelog
- Remove dialog functionality from `AdvancedSettings`
- add dialog functionality for `python.pathToPythonOverride` `updateCongiValue` actions in `registerConfig`

# Review requests
- confirm this works on windows now and has not regressed on other OSes
- I've added a test but it fails, the `handleAction` function is undefined because the `registerConfig` function is a mocked function... but I'm not mocking that function or the directory it's in so I'm confused by this, something I haven't run into in our test setup.

# Risk assessment
Medium. This touches some important `app-shell` code.

2022-07-29 03:46 UTC, vabruzzo commented on app-shell/src/config/__tests__/dispatch.test.ts
> +  // eslint-disable-next-line jest/no-disabled-tests
i wanted to add tests here general and copied some patterns from other tests, `handleAction` here is undefined. when i log `registerConfig` up above it appears to be a mocked function. no luck yet figuring out why this function appears to be mocked

2022-07-29 19:14 UTC, koji commented on app-shell/src/config/index.ts
> +          // eslint-disable-next-line @typescript-eslint/no-floating-promises
not sure this is a good way to remove eslint-disable
```suggestion
         shell.openPath(dir).catch(err => {
            log().debug('Error opening python directory', err.message)
          })
```

2022-07-29 19:17 UTC, koji approved these changes
Tested this branch with Windows10 and it worked as expected.
I think getting a code review from Mike or Brian would be great.

2022-08-01 16:39 UTC, b-cooper approved these changes
Functions as expected.  This approach looks sound to me 👍 .

At a quick glance, I can't tell quite why that `registerConfig` import is somehow getting mocked, it's very strange

2022-08-01 16:43 UTC, vabruzzo commented
> Functions as expected. This approach looks sound to me 👍 .
> 
> At a quick glance, I can't tell quite why that `registerConfig` import is somehow getting mocked, it's very strange

Because this is a high priority hotfix im going to leave the skipped test and add a TODO.

2022-08-01 16:44 UTC, mcous requested changes
I think this functionality should be added to the `app-shell/src/protocol-analysis` module; the `config` module should concern itself solely with config storage.

I've also added testing recommendations and thoughts. I didn't dig into figuring out why the test isn't running as you expect, because I think these tests should be moved and their mocking strategy should be reworked

2022-08-01 16:44 UTC, mcous commented on app-shell/src/config/index.ts
> +          path === 'python.pathToPythonOverride'
This functionality should not be added to the `config` module, it should be added to the `protocol-analysis` module. It should also be hooked off its own action (e.g. `SELECT_PYTHON_OVERRIDE_DIRECTORY`) instead of overloading the meaning of the `config:UPDATE_VALUE` action

2022-08-01 16:44 UTC, mcous commented on app-shell/src/config/__tests__/dispatch.test.ts
> +jest.mock('electron')
Setting aside the fact that these tests should not live in `config`:

I know these are copied over from existing tests (that I wrote, to boot!), but mocking `fs-extra` and `electron` is not a good idea. Mocking interfaces that we [don't own](https://github.com/testdouble/contributing-tests/wiki/Don%27t-mock-what-you-don%27t-own):

- Hides bugs caused by our own misunderstandings of these third party interfaces
- Muddies the waters in terms of figuring out what a given test is actually testing

Solutions for both of these issues involve creating or using existing wrappers that we _do_ own and mocking those out instead. See the link above from Test Double about why the wrappers are a better solution than mocking out the third-party dependencies directly.

Solutions for both of these mocks:

- `fs-extra` - Remove this mock and behavior
    - It's not the job of this code to ensure the selected Python directory exists
- `electron` - Mock out `app-shell/src/dialogs`, not `electron`

2022-08-01 16:44 UTC, mcous commented on app/src/pages/AppSettings/AdvancedSettings.tsx
> +    dispatch(Config.updateConfigValue('python.pathToPythonOverride', null))
I think the fact that you have to write a whole comment about this is a red flag. I recommend creating an action for this to make the code self-explanatory

2022-08-01 18:59 UTC, vabruzzo commented on app-shell/src/protocol-analysis/__tests__/protocolAnalysis.test.ts
> +import electron from 'electron'
i have to think more about how to test this without mocking `BrowserWindow`, `registerPython` relies on it

2022-08-01 19:37 UTC, mcous reviewed
This is looking really good. Got some final polish recommendations that we can talk about to get this all buttoned up

2022-08-01 19:37 UTC, mcous commented on app-shell/src/protocol-analysis/index.ts
> +export function registerPython(
Let's call this `registerProtocolAnalysis` to adhere to existing conventions of `register{NameOfModule}`

2022-08-01 19:37 UTC, mcous commented on app/src/redux/protocol-analysis/constants.ts
> +  'protocol-analysis:CHANGE_PYTHON_PATH_OVERRIDE'
I'd be in favor of putting these constants in `actions.ts` instead. I (and others on robot-services) have heavily soured on the idea of a `constants` file; it usually just makes things harder to read

2022-08-01 19:37 UTC, mcous commented on app/src/redux/protocol-analysis/types.ts
> +import * as Constants from './constants'
Same comment as `constants.ts`, since these types are all action types, let's just put them in `actions.ts` so we're not bouncing around between three different files for like 50 LOC total

2022-08-01 19:37 UTC, mcous commented on app/src/redux/types.ts
> +import { ProtocolAnalysisAction } from './protocol-analysis/types'
```suggestion
import type { ProtocolAnalysisAction } from './protocol-analysis/types'
```

2022-08-01 19:37 UTC, mcous commented on app-shell/src/protocol-analysis/index.ts
> +        }
Let's give ourselves another wrapper object here. I think given that our `dialogs` module already has `showOpenDirectoryDialog`, a complimentary function called `openDirectoryInFileExplorer` in that same module would make conceptual sense, allow this [collaborator unit]() to delegate more work, and give us something to mock.

```ts
// app-shell/src/dialogs/index.ts
// ...

export function openDirectoryInFileExplorer(directory: string | null): Promise<void> {
  if (directory == null) return Promise.resolve()

  // ...
}
```

2022-08-01 19:43 UTC, mcous commented on app-shell/src/protocol-analysis/__tests__/protocolAnalysis.test.ts
> +  } as unknown) as electron.BrowserWindow
I think I saw you had a comment about this, but _this_ usage of `electron` is _probably_ OK! We've factored our code so that this `mainWindow` object is more-or-less a "value" that just gets threaded through our various dependencies.

Since it's a value that's being passed around from the standpoint of our code under test, one wouldn't really consider it a "mock" in the same way we would consider `jest.mock('electron')` to be "mocking the Electron dependency"

2022-08-01 20:03 UTC, vabruzzo commented on app-shell/src/protocol-analysis/__tests__/protocolAnalysis.test.ts
> +  } as unknown) as electron.BrowserWindow
ah this makes sense, thanks

2022-08-01 22:03 UTC, mcous reviewed
Pretty sure the code looks good, but as noted by codecov, we're missing test cases in `app-shell/src/protocol-analysis/__tests__/protocolAnalysis.test.ts`

I tested the changes on `Windows` and `macOS`, and the behavior was correct. We should be good to merge once the missing unit tests are in place

2022-08-01 22:03 UTC, mcous commented on app-shell/src/protocol-analysis/__tests__/protocolAnalysis.test.ts
> +  })
We're missing two tests:

- Verify that the resolved directory from `showOpenDirectoryDialog` is passed to `dispatch`
- Verify that `openDirectoryInFileExplorer` is called in response to `OPEN_PYTHON_DIRECTORY`

2022-08-01 22:03 UTC, mcous commented on app-shell/src/protocol-analysis/__tests__/protocolAnalysis.test.ts
> +    showOpenDirectoryDialog.mockResolvedValue([])
I would not configure an unconditional stubbing here; it's hidden the fact that we're missing tests. I have two recommendations:

- Always use `jest-when` to configure conditional stubbings rather than unconditional ones
- Prefer duplicating stubbing in each test over setting them in `beforeEach`, unless it really messes with readability

2022-08-01 22:03 UTC, mcous commented on app-shell/src/protocol-analysis/__tests__/protocolAnalysis.test.ts
> +  it('opens file picker on CHANGE_PYTHON_PATH_OVERRIDE', () => {
We should change the name of this test to note that it's specifically tested that the config is not changed if no directory is returned from `showOpenDirectoryDialog`

2022-08-02 12:23 UTC, mcous approved these changes

2022-08-02 12:23 UTC, mcous commented on app-shell/src/protocol-analysis/__tests__/protocolAnalysis.test.ts
> +      expect(mockShowOpenDirectoryDialog).toHaveBeenCalledWith(mockMainWindow)
This assertion is unnecessary and should be removed. I'm only calling it out because it's a nuanced thing when using conditional stubbing, and it takes a little while to click.

It's unnecessary because we've configured `mockShowOpenDirectoryDialog` to return `path/to/override` _if and only if_ it is called with `mockMainWindow`, and we assert that `updateConfigValue` is called with `path/to/override`.

**The only way that `updateConfigValue` could have access to the expected input is if `mockShowOpenDirectoryDialog` was _also_ passed the correct input.** At best, this makes this `calledWith` assertion on `mockShowOpenDirectoryDialog` redundant. At worst, it's extra coupling that over-constrains our code under test.

We don't use this mocking library at Opentrons, but [testdouble.js](https://github.com/testdouble/testdouble.js) is very similar to [jest-when](https://github.com/timkindberg/jest-when) (they come from the same [mockito](https://site.mockito.org/) background) and their docs have a good explanation of why [redundant call verifications](https://github.com/testdouble/testdouble.js/blob/main/docs/B-frequently-asked-questions.md#why-shouldnt-i-call-both-tdwhen-and-tdverify-for-a-single-interaction-with-a-test-double) should be avoided

2022-08-02 12:24 UTC, merged