fix(app): pipette settings submit bugfix
OpenTrons/opentrons-api pull request #11288
Opened 2022-08-03 19:40 UTC by vabruzzo

# Overview
Closes #11281.
When users edit pipette settings and click submit, the submit button does not handle the submit and no settings are saved. To fix this we added an `id` to the form, and a `form` prop that references the form's `id`. This fixes the submit functionality.

We had a remaining data de-sync issue: we were using redux via `updatePipetteSettings` to mutate the pipette data and `usePipetteSettingsQuery` to retrieve the data. This was causing some data de-syncing. This fixes data sync issues by using a redux selector to retrieve data. There is not yet a way to mutate this data using `ReactQuery`, so using redux as a single source of truth is a quick fix. Presumably we want to extend react-api-client and add a pipette settings mutation query. For hotfix purposes I think using redux makes sense.

# Changelog
- add id to pipette settings form
- add form prop to pipette settings submit button
- use redux selector instead of ReactQuery usePipetteSettings query to display settings

# Review requests
- confirm works as expected
- confirm that this approach is acceptable

# Risk assessment
low

2022-08-03 20:31 UTC, koji commented on app/src/organisms/ConfigurePipette/index.tsx
>    closeModal: () => unknown
```suggestion
  closeModal: () => void
```

2022-08-03 20:34 UTC, koji commented on app/src/organisms/ConfigurePipette/ConfigForm.tsx
> +              <Form id="configurePipetteForm">
L43 we can remove ` closeModal: () => unknown` since this part for the previous modal component and tried on my end and it wouldn't break the app.

2022-08-03 20:35 UTC, koji commented on app/src/organisms/Devices/PipetteCard/PipetteSettingsSlideout.tsx
> +          robotName={robotName}
L31 probably we can change to  `onCloseClick: () => void`

2022-08-03 20:36 UTC, koji commented on app/src/organisms/ConfigurePipette/index.tsx
>            closeModal={closeModal}
I think we can remove this `closeModal={closeModal}`

2022-08-03 20:49 UTC, koji approved these changes
smoke tested and the changes work as expected.
Thank you for fixing this! 🙏
I tried a few things with `usePipetteSettingsQuery` and still haven't found a solution.
I will create a ticket about that on Jira.

2022-08-03 20:50 UTC, jerader approved these changes
smoke tested and works! thanks so much for fixing this!! 🚀

2022-08-04 16:21 UTC, mcous requested changes
Have not smoke tested, but I would like to make sure our unit tests are in better shape since this is a hotfix release and our testing bar needs to be quite high.

This PR makes some serious improvements in that regard, so I'd like to push it just a little further

2022-08-04 16:21 UTC, mcous commented on app/src/organisms/ConfigurePipette/__tests__/ConfigurePipette.test.tsx
> +    getByText('Reset all')
I'd prefer `getByRole` here, according to [testing-library docs](https://testing-library.com/docs/queries/about#priority).

Also, should this test be clicking the reset button and verifying that something happens?

2022-08-04 16:21 UTC, mcous commented on app/src/organisms/ConfigurePipette/__tests__/ConfigurePipette.test.tsx
> +  })
I do not see any `when` mocks used in the file. I would recommend using them, or drop the `resetAllWhenMocks`

2022-08-04 16:21 UTC, mcous commented on app/src/organisms/ConfigurePipette/__tests__/ConfigurePipette.test.tsx
> +    mockGetRequestById.mockReturnValue({
Prefer `when` stubbing to unconditional stubbing, which can hide bugs

2022-08-04 16:21 UTC, mcous commented on app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx
> +    mockGetAttachedPipetteSettingsFieldById.mockReturnValue(
Unconditional mock would hide if `getAttachedPipetteSettingsFieldsById` was called incorrectly

2022-08-04 16:21 UTC, mcous commented on app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx
> +    getByText('Bottom')
Prefer `getByRole('button', {type: 'submit'})` (apologies if I got the exact syntax wrong there, but it's something along those lines)

2022-08-04 16:21 UTC, mcous commented on app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx
> +const mockGetAttachedPipetteSettingsFieldById = getAttachedPipetteSettingsFieldsById as jest.MockedFunction<
Slight mismatch in mock name vs dependency name (missing an `s`)

```suggestion
const mockGetAttachedPipetteSettingsFieldsById = getAttachedPipetteSettingsFieldsById as jest.MockedFunction<
```

2022-08-04 16:21 UTC, mcous commented on app/src/organisms/ConfigurePipette/ConfigForm.tsx
> +              <Form id="configurePipetteForm" data-testid="ConfigForm_form">
I don't think the `id` should be hardcoded like this; it should be passed in as a prop so that the parent that's rendering both the form and the submit button can ensure the IDs match (and also so the ID can be constructed to be more unique, perhaps by including the pipette serial number).

Also, see comment below about why we shouldn't use `data-testid` here

2022-08-04 16:21 UTC, mcous commented on app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx
> +    const form = getByTestId('ConfigForm_form')
Related to comment above: do not use `testid`. We should get this element by the `form` role with a matching `id` that we've passed via props

2022-08-04 16:21 UTC, mcous commented on app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx
> +    const button = getByRole('button', { name: 'Confirm' })
Get by role with type submit

2022-08-04 16:21 UTC, mcous commented on app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx
> +    form.onsubmit = jest.fn()
Do not modify the `form`; this creates a [contaminated test subject](https://github.com/testdouble/contributing-tests/wiki/Partial-Mock#contaminated-test-subjects) and makes this test so it doesn't really test anything.

We need to measure what the form is doing using public props or injected `import` dependencies

2022-08-04 16:32 UTC, vabruzzo commented on app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx
> +    form.onsubmit = jest.fn()
I'm not sure the best way to test this. This tests that the submit button, when clicked, submits the form that matches its `form` id.  this test was not so much about what the form is doing but rather that the submit button is properly wired to the form.

2022-08-04 17:07 UTC, vabruzzo commented on app/src/organisms/ConfigurePipette/__tests__/ConfigurePipette.test.tsx
> +    getByText('Reset all')
this functionality is actually tested by the reset buttons own preexisting unit tests. i can remove this test

2022-08-04 17:29 UTC, vabruzzo commented on app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx
> +    getByText('Bottom')
this `getByText` is grabbing a `p` or `span`, i dont think `getByRole` really works for these as we don't include a `name` for all of these.

2022-08-04 18:52 UTC, vabruzzo commented on app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx
> +    const button = getByRole('button', { name: 'Confirm' })
it seems that this is not supported by the testing-library api: https://github.com/testing-library/dom-testing-library/issues/1012

2022-08-04 19:05 UTC, mcous commented on app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx
> +    getByText('Bottom')
This command may have landed on the long line, sorry about that

2022-08-04 19:13 UTC, mcous commented on app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx
> +    form.onsubmit = jest.fn()
Verify that `dispatchApiRequest` (which is a mock that is already in this suite) is called with the correct action and parameters, probably with some relatively permissive expectations with the actual form values

2022-08-04 19:22 UTC, mcous reviewed
Also getting `Warning: An update to Formik inside a test was not wrapped in act(...).` when running these tests

2022-08-04 19:22 UTC, mcous commented on app/src/organisms/ConfigurePipette/ConfigForm.tsx
> +              <Form id={formId} aria-label="configure_pipette_form">
What's this `aria-label` doing? It looks like it was added for tests, not for user-facing accessibility purposes. I would remove it

2022-08-04 19:22 UTC, mcous commented on app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx
> +    const form = getByRole('form', { name: 'configure_pipette_form' })
There is only one form under test, no need for the `name` filter

```suggestion
    const form = getByRole('form')
```

2022-08-04 19:22 UTC, mcous commented on app/src/organisms/Devices/PipetteCard/PipetteSettingsSlideout.tsx
> +const FORM_ID = 'configurePipetteForm'
Can this ID include the pipette serial number rather than a constant which in the most technical sense will run an ID collision risk?

2022-08-04 21:19 UTC, vabruzzo commented on app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx
> +    form.onsubmit = jest.fn()
@mcous this is what I tried initially, but the test fails and `dispatchApiRequest` does not get called, i believe it has something to do with how Formik is wired, we get the warning `Warning: An update to Formik inside a test was not wrapped in act(...).` but i am wrapping the button click in an `act`:

```
  it('renders confirm button and calls form onsubmit when clicked', () => {
    const { getByRole } = render(props)

    // const form = getByRole('form', { name: 'configure_pipette_form' })
    // form.onsubmit = jest.fn()
    const button = getByRole('button', { name: 'Confirm' })
    act(() => button.click())
    expect(dispatchApiRequest).toHaveBeenCalled()
  })
```

i fear trying to get formik working in the test might lead to a bit of a rabbit hole

2022-08-04 21:28 UTC, vabruzzo commented on app/src/organisms/ConfigurePipette/ConfigForm.tsx
> +              <Form id={formId} aria-label="configure_pipette_form">
this is required by testing-library: https://github.com/testing-library/dom-testing-library/issues/474

2022-08-04 21:29 UTC, vabruzzo commented on app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx
> +    const form = getByRole('form', { name: 'configure_pipette_form' })
yeah this is weird by test-library has a lot of caveats about which elements can be found by role alone: https://github.com/testing-library/dom-testing-library/issues/474

2022-08-04 21:30 UTC, vabruzzo commented on app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx
> +    const form = getByRole('form', { name: 'configure_pipette_form' })
actually, as the issue refers, this is required by the spec, not the library itself

2022-08-05 04:31 UTC, vabruzzo commented
> Also getting `Warning: An update to Formik inside a test was not wrapped in act(...).` when running these tests

fixed with `waitFor`. the `act` that i was using _should_have worked but it is a formik bug as documented here: https://github.com/jaredpalmer/formik/issues/1543

2022-08-05 15:37 UTC, mcous commented on app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx
> +    form.onsubmit = jest.fn()
> i will continue to dig further but might this be acceptable for the hotfix to confirm that the button is wired properly to get the form to submit?

The key reason this is _not_ acceptable is that this test doesn't actually assert that our UI is wired up properly, therefore it does not verify that the user-facing bug is fixed. Because we've modified the `<form>` under test, we're not testing that our form works, we're testing that some partially fake `<form>` is able to submit.

If you wanted to do this specific test ("submit" button is wired to form), you should simply check that the button has a `form` attribute that matches the `form`'s `id` attribute. This would resolve the contaminated test subject problem, **but it would still be insufficient, because we need to verify that form submission results in the correct side effect,** not that form submission happens.

> i fear trying to get formik working in the test might lead to a bit of a rabbit hole

Trying to add tests to code that isn't well tested often results in this feeling. I encourage you to try to start shifting your mentality on these sorts of issues. If you've got this sort of rabbit hole in front of you, instead of saying to yourself:

> These tests are too hard, since everything looks like it's working can we skip the tests?

...try to say to yourself instead...

> This code isn't testable / verifiable, how can I change the code so that testing isn't a rabbit hole?

\</tedtalk>

For the Formik warning issue:

- You do not need to explicitely wrap most testing-library stuff in `act`
    - You should use `fireEvent.click` instead
- You should wrap your expectation in `await waitFor(() => ...` to resolve the `act` warnings


For the issue where the dispatch isn't firing:

- The dispatch isn't firing because the fixture data in `api-client/src/pipettes/__fixtures__/index.ts` that is fed into the form in the test is invalid
- The `top` setting must be greater than the `bottom` setting must be greater than `blowOut` must be greater than `dropTip`

Finally:

- `toHaveBeenCalled()` if _very_ rarely sufficient
- In collaborator tests like these, you should be testing that things are correctly wired up, and that means asserting that dependencies are called **with the correct arguments**

Recommended test:

```ts
// ...

import {
  getAttachedPipetteSettingsFieldsById,
  updatePipetteSettings,
} from '../../../../redux/pipettes'

// ...

const mockUpdatePipetteSettings = updatePipetteSettings as jest.MockedFunction<
  typeof updatePipetteSettings
>

// ...

  it('renders confirm button and calls form onsubmit when clicked', async () => {
    const { getByRole } = render(props)
    const button = getByRole('button', { name: 'Confirm' })

    when(mockUpdatePipetteSettings)
      .calledWith(
        expect.any(String),
        props.pipetteId,
        expect.objectContaining({ top: null, bottom: null })
      )
      .mockReturnValue({
        type: 'pipettes:UPDATE_PIPETTE_SETTINGS',
      } as UpdatePipetteSettingsAction)

    fireEvent.click(button)

    await waitFor(() => {
      expect(dispatchApiRequest).toHaveBeenCalledWith({
        type: 'pipettes:UPDATE_PIPETTE_SETTINGS',
      })
    })
  })
```

2022-08-05 15:40 UTC, mcous commented on app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx
> +    const form = getByRole('form', { name: 'configure_pipette_form' })
This element is not needed for the test. I still think the aria-label should be removed or replaced with something human-readabale

2022-08-05 16:09 UTC, vabruzzo commented on app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx
> +    form.onsubmit = jest.fn()
thank you for this, i greatly appreciate your guidance and mentorship!

2022-08-05 17:19 UTC, mcous approved these changes
Smoke tested the changes in the app against the dev server, looks to be working. Tests around this UI also look much improved, thanks for making that happen

2022-08-05 17:31 UTC, merged