feat(app): feat add copy labware api name feedback
OpenTrons/opentrons-api pull request #11292
Opened 2022-08-04 17:25 UTC by koji

# Overview
This will close [RAUT-65](https://opentrons.atlassian.net/jira/software/c/projects/RAUT/boards/75?modal=detail&selectedIssue=RAUT-65) and [RAUT-72](https://opentrons.atlassian.net/jira/software/c/projects/RAUT/boards/75?modal=detail&selectedIssue=RAUT-72)

# Changelog
- add prop(`width`) to tooltip to align with the design
- add a tooltip to copy the api-name button
- modify copy icon position
- add Pseudo-classes to the copy icon
- remove css from react.fragment

# Review requests
- [ ] when clicking the copy icon, copy the API name and show the tooltip
- [ ] the tooltip will disappear in 2 sec
- [ ] when clicking a labware card, the dev tools console doesn't show a warning that mentions to React.Fragment 

# Risk assessment
low

2022-08-05 17:45 UTC, vabruzzo commented on app/src/atoms/Slideout/index.tsx
> +            <>{title}</>
i think we might be able to remove the `<>` and just render the title?

2022-08-05 17:48 UTC, vabruzzo commented on app/src/organisms/LabwareDetails/index.tsx
> +          onClick={async () => await handleCopy()}
instead of wrapping this in an async function i believe we can just pass in `handleCopy`, since it itself is doing the necessary `await`ing.

2022-08-05 17:50 UTC, vabruzzo requested changes
Made a few small comments, and we should try to get in some test coverage to get the patch code coverage check to pass. Code otherwise looks good 👍

2022-08-05 18:01 UTC, koji commented on app/src/atoms/Slideout/index.tsx
> +            <>{title}</>
I thought that too, but actually removing React.Fragment causes the white screen issue.

`Uncaught Error: Objects are not valid as a React child (found: object with keys {title}). If you meant to render a collection of children, use an array instead.
`

I think removing React.Fragment should be done by another PR.

2022-08-05 18:11 UTC, koji commented
- [ ] add test cases for this

2022-08-08 19:30 UTC, koji commented
@vabruzzo 
Thank you for pointing out the tests. I noticed that LabwareDetails is missing all tests. (I listed above).
The changes are over 200 lines already so I will open another PR for the rest of the tests. ([RAUT-86](https://opentrons.atlassian.net/jira/software/c/projects/RAUT/boards/75?modal=detail&selectedIssue=RAUT-116))

2022-08-08 19:35 UTC, koji commented on app/src/organisms/LabwareDetails/WellProperties.tsx
> +  const { totalLiquidVolume: vol, metadata } =
Added this line to solve the issue that Jest showed `vol, metadata possibly undefined`.

2022-08-08 19:35 UTC, koji commented on app/src/organisms/LabwareDetails/WellProperties.tsx
> +  const { wellBottomShape } = (metadata != null && metadata) || {}
same as the above

2022-08-09 15:07 UTC, vabruzzo approved these changes
🚀

2022-08-09 20:39 UTC, merged