Replaced old font size with TYPOGRAPHY const
OpenTrons/opentrons-api pull request #11291
Opened 2022-08-04 16:30 UTC by MichaelMulieri

# Overview
Replaced old font size with TYPOGRAPHY const where applicable.  

# Changelog
-  Replaced old font sizes that have  mapping to an equivalent TYPOGRAPHY const. 
-  Removed imports of unused variables.
-  Included import of TYPOGRAPHY where needed.

# Review requests

# Risk assessment
Low

2022-08-04 18:43 UTC, vabruzzo commented
Thank you for this contribution! it looks like there is a format error in `app/src/organisms/LabwarePositionCheck/IntroScreen.tsx`, and the title of this pr should be formatted properly, for this it should begin with `refactor(app): replaced`

2022-08-04 21:02 UTC, koji commented
Hi @MichaelMulieri 
Seems that you need to run the following command to fix lint-js error.

```zsh
npx prettier --write app/src/organisms/LabwarePositionCheck/IntroScreen.tsx
```

2022-08-05 14:09 UTC, vabruzzo approved these changes
this looks good to me, thank you for your contribution Mike!

2022-08-05 14:48 UTC, koji commented on app/src/organisms/LabwarePositionCheck/StepDetailText.tsx
> +        fontSize={TYPOGRAPHY.fontSizeCaption}
```suggestion
        fontSize={TYPOGRAPHY.fontSizeH3}
```

2022-08-05 14:48 UTC, koji commented on app/src/organisms/ModuleCard/ThermocyclerModuleData.tsx
> +          fontSize={TYPOGRAPHY.fontSizeH3}
```suggestion
          fontSize={TYPOGRAPHY.fontSizeCaption}
```

2022-08-05 14:49 UTC, koji commented on app/src/organisms/ModuleCard/ThermocyclerModuleData.tsx
> +          fontSize={TYPOGRAPHY.fontSizeH3}
```suggestion
          fontSize={TYPOGRAPHY.fontSizeCaption}
```

2022-08-05 14:49 UTC, koji commented on app/src/organisms/ModuleCard/ThermocyclerModuleData.tsx
> +        <Text title="lid_temp" fontSize={TYPOGRAPHY.fontSizeH3}>
```suggestion
        <Text title="lid_temp" fontSize={TYPOGRAPHY.fontSizeCaption}>
```

2022-08-05 14:49 UTC, koji commented on app/src/organisms/ModuleCard/ThermocyclerModuleData.tsx
> +          fontSize={TYPOGRAPHY.fontSizeH3}
```suggestion
          fontSize={TYPOGRAPHY.fontSizeCaption}
```

2022-08-05 14:49 UTC, koji commented on app/src/organisms/ModuleCard/ThermocyclerModuleData.tsx
> +          fontSize={TYPOGRAPHY.fontSizeH3}
```suggestion
          fontSize={TYPOGRAPHY.fontSizeCaption}
```

2022-08-05 14:49 UTC, koji commented on app/src/organisms/ModuleCard/ThermocyclerModuleData.tsx
> +        <Text title="tc_current_temp" fontSize={TYPOGRAPHY.fontSizeH3}>
```suggestion
        <Text title="tc_current_temp" fontSize={TYPOGRAPHY.fontSizeCaption}>
```

2022-08-05 14:51 UTC, koji requested changes
Thank you for your contribution!
I found some misconverting of the font size and I left commnets.
Please take a look!

2022-08-05 22:36 UTC, MichaelMulieri commented
> @MichaelMulieri, thank you for your contribution! I found some misconverting of the font sizes and I left comments. Please take a look!

Thanks @koji.  I'll check it out.

2022-08-06 19:47 UTC, koji commented on app/src/organisms/LabwarePositionCheck/SectionList.tsx
> +      fontSize={TYPOGRAPHY.fontSizeH3}
```suggestion
      fontSize={TYPOGRAPHY.fontSizeCaption}
```

2022-08-06 19:48 UTC, koji requested changes
Need one more change

2022-08-06 23:37 UTC, koji approved these changes
The changes look good to me.
@MichaelMulieri, thank you for your contribution 🚀🚀🚀

2022-08-07 19:45 UTC, MichaelMulieri commented
> The changes look good to me. @MichaelMulieri, thank you for your contribution 🚀🚀🚀

@koji Excellent. Thank you!

2022-08-08 14:17 UTC, merged