feat(App and api): Map Legacy Commands to JSON v6 commands
OpenTrons/opentrons-api pull request #11296
Opened 2022-08-05 14:31 UTC by jerader

closes #11187 

# Overview

Maps `Aspirate`, `Dispense`, and `Blow_out` to json v6 commands and fixes a bug that was causing labware loaded onto the modules to be inaccessible

# Changelog

- add `Aspirate`, `Dispense`, and `Blow_out` to `legacy_command_mapper` and add coverage to the smoke test
- fix bug that was causing labware loaded onto modules to be inaccessible

# Review requests

- upload a protocol with aspirate, dispense, and blow_out and `console.log` the `protocolData` in `stepText`, you should see the aspirate, dispense and blow_out show up as their correct commands/`commandType` rather than `custom`

# Risk assessment

low

2022-08-09 18:01 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            if flowRate is None:
```suggestion
            assert flowRate is None, "Unknown aspirate rate."
```

2022-08-09 18:12 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            if flowRate is None:
I think assert is more appropriate in these cases. It will raise an assert error with this message.

2022-08-09 18:14 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            if flowRate is None:
same comment ^

2022-08-09 19:08 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_runner/smoke_tests/test_legacy_command_mapper.py
> +    well_plate_1_result_captor = matchers.Captor()
maybe its time to change the method name to `test_legacy_commands`?

2022-08-09 19:22 UTC, TamarZanzouri requested changes, later dismissed
overall code changes look good to me! nice job! just a few small changes. 
I have asked robot services for another review bc I am not familiar with the legacy command mapper.

2022-08-09 22:22 UTC, sanni-t requested changes, later dismissed
I would highly recommend splitting up the `_build_initial_command` method into multiple private methods. You can even group them by theme- tip_handling_commands and liquid_handling_commands; especially since the aspirate and dispense commands share so much of their code. That will make the code much more readable and reduce unnecessary code size. Moreover, such if-else ladders tend to hide bugs with multiple 'redefinitions' of the same variable (e.g., `volume` is defined in both aspirate & dispense. Python linting & error-checking is a little weird/lenient with variable scopes).

Tests won't have to change since they'll all be private methods. So as long as we have public method tests & smoke tests passing, those don't need to be updated.

2022-08-09 22:22 UTC, sanni-t commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            location = command["payload"].get("location")
I'd switch these to accessing directly with keys instead of the `get` method. We've already established that these keys exist in lines 325-327 and those params don't have an optional Nonetype in the aspirate/dispense command message types so we won't have to do the checks for `None` here at all.

2022-08-09 22:22 UTC, sanni-t commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            parentModuleId = self._module_id_by_slot.get(location.labware.first_parent())  # type: ignore
Let's make sure we're passing the correct argument type here. `labware.first_parent()` can be a string or None while `_module_id_by_slot` expects its key to be a `DeckSlotName` type.

First, assert that `first_parent` is not `None`, then cast the string to `DeckSlotName`.

2022-08-10 13:03 UTC, jerader commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            parentModuleId = self._module_id_by_slot.get(location.labware.first_parent())  # type: ignore
Having a bit of troubles. Can you elaborate a bit? I tried the following but getting a lint error:

`           assert location.labware.first_parent() is not None
            firstParent : DeckSlotName = location.labware.first_parent()
            parentModuleId = self._module_id_by_slot.get(firstParent)`

2022-08-10 15:02 UTC, sanni-t commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            parentModuleId = self._module_id_by_slot.get(location.labware.first_parent())  # type: ignore
Try-
```
first_parent = location.labware.first_parent()
assert firstParent is not None, "Labware needs to be associated with a slot
parent_module_id = self._module_id_by_slot.get(DeckSlotName(firstParent))
```

Also, just realized, you'll want to make the variable names lowercase and underscored (it's the convention we follow for all python code)

2022-08-10 15:07 UTC, jerader commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            parentModuleId = self._module_id_by_slot.get(location.labware.first_parent())  # type: ignore
That works, thank you! I will fix the other areas to be the same as well as fixing the variable names.

2022-08-10 15:20 UTC, sanni-t reviewed
We'll also need to add legacy_command_mapper unit tests for aspirate & dispense.

2022-08-10 17:13 UTC, sanni-t commented
> We'll also need to add legacy_command_mapper unit tests for aspirate & dispense.

Paired with @jerader to address the above comments and looks like writing a unit test for mapping pipetting commands is not that straight forward. Smoke tests are basically covering the mapping functionality verification so unit tests don't seem to be strictly required.

2022-08-10 17:59 UTC, mcous requested changes
In addition to these comments below about never doing `raise Exception(...)` in our Python codebase, we're missing tests for the various permutations of the liquid handling commands at different location types and with various parameters specified and unspecified.

We'll need to be pretty confident in our test coverage of this one, because unexpected exceptions during command mapping will not fail gracefully.

I'd recommend writing a Python protocol per command type that executes the PAPIv2 method under test in all possible manner to ensure proper mapping

2022-08-10 17:59 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            raise Exception("Unknown drop_tip location.")
I think this `Exception` was already present, but can it be replaced with an `assert`? It's almost never appropriate to raise a bare `Exception` in our Python codebase, and this looks like it was intended to be a developer check; as in this `else` should never happen

2022-08-10 17:59 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            raise Exception("Unknown pick_up_tip location.")
`assert`, not `Exception`

2022-08-10 17:59 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            raise Exception("Unknown pipetting location.")
`assert`

2022-08-10 17:59 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            raise Exception("Unknown blow out location.")
`assert`

2022-08-10 19:20 UTC, jerader commented on api/tests/opentrons/protocol_runner/smoke_tests/test_legacy_command_mapper.py
> +        pipette_left.aspirate(
I increased test coverage to test for:

`aspirate` & `dispense`:
1. volume, rate, location params specified
2. only volume, location params specified
3. only volume param specified
4. no params specified

`blow_out`:
1. location param specified
2. no params specified

2022-08-11 13:59 UTC, mcous reviewed
Still missing test cases, did a more thorough code review and looks like there's some stuff to clear up in the command mapper itself, too. Concentrate on getting the test cases in place before continuing to change the logic code

2022-08-11 13:59 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            and "rate" in command["payload"]
What are these extra conditions doing? The type definition says these fields must be present. Removing them does not change the test or linting output. If they need to be here, there should be a test that makes sure they're doing their job. If they're not needed, they should be removed

2022-08-11 13:59 UTC, mcous commented on api/tests/opentrons/protocol_runner/test_legacy_command_mapper.py
> +#   TODO(jr, 8/10/22): add PICK_UP_TIP, DROP_TIP, ASPIRATE, and DISPENSE unit tests
This TODO should be addressed in this PR (or removed, if this logic is covered by tests in this PR). Acceptance tests are vital for this logic, but unit tests of the LegacyCommandMapper may not be workable or worth the time, given the spaghetti nature of the PAPIv2 broker messages

2022-08-11 13:59 UTC, mcous commented on api/tests/opentrons/protocol_runner/smoke_tests/test_legacy_command_mapper.py
> +        pipette_left.aspirate(
We'll need tests for the various types of locations that are available. Right now, I only see tests for when `location` is a `Well` object or `None`. Other valid types:

- A `Location`, without any associated labware or well
- A `Location` associated with a well
- A `Location` associated labware

2022-08-11 13:59 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        well = location.labware.as_well()
- Why is this a `.get`; the field must be present according to the message's type definition?
- `location` is typed as a `Well` or `Location`; why are we asserting when we need a `Well`, anyway?

```suggestion
        location = command["payload"]["location"]
        well = (
            location if isinstance(location, LegacyWell) else location.labware.as_well()
        )
```

2022-08-11 13:59 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        slot = DeckSlotName.from_primitive(well.parent.parent)  # type: ignore[arg-type]
Either:

- Switch this to `first_parent`, or
- Add a comment explaining that this type checking suppression assumes the tiprack is not loaded on top of a module (which is valid assumption)

We also may want to consider `assert` rather than a type checking suppressions

2022-08-11 13:59 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        well = _well
Same comment as above

2022-08-11 13:59 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        slot = DeckSlotName.from_primitive(well.parent.parent)  # type: ignore[arg-type]
Same comment: add comment spelling out assumptions, or use an `assert` instead, and/or switch to `first_parent`

2022-08-11 13:59 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        well = location.labware.as_well()
Same comment as above about unnecessary assert when we know location is either a `Location` or a `Well` from the type signature

2022-08-11 13:59 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            labware_id = self._labware_id_by_slot[slot]
```suggestion
        slot = DeckSlotName(first_parent)
        parent_module_id = self._module_id_by_slot.get(slot)
        labware_id = (
            self._labware_id_by_module_id[parent_module_id]
            if parent_module_id is not None
            else self._labware_id_by_slot[slot]
        )
```

2022-08-11 13:59 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        last_location = pipette._ctx.location_cache
We shouldn't be checking `location_cache` ourselves? `InstrumentContext` already does this and places the value in the broker message. We only need to look at `location`

2022-08-11 13:59 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            assert well is None, "Unknown blow_out location."
This assert looks wrong, or at least reads very confusingly. `well is None` is bad and unexpected, so I would not expect to read an assertion that tries to verify that it's the case

2022-08-11 13:59 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        parent_module_id = self._module_id_by_slot.get(DeckSlotName(first_parent))
Same suggestion as above, we are constructing `slot` from `DeckSlotName` twice unnecessarily

2022-08-11 15:51 UTC, jerader commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        last_location = pipette._ctx.location_cache
`location` can be `None`, so I thought we need to access `location_cache` in the event that we don't have a `location`?

2022-08-11 16:57 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        last_location = pipette._ctx.location_cache
Take a look at the code for blow out. The `ProtocolContext` already does this check, and ensure that if the user passed in a `None` location, `location_cache` is what goes into the message.

https://github.com/Opentrons/opentrons/blob/ab6557c792cdc9f2015b35e652fdbb6fb49c935a/api/src/opentrons/protocol_api/instrument_context.py#L458-L465

So if _we_ receive a `None` here, it means that `location_cache` was `None`. Other code in the `blow_out` method will raise before that happens, so we're safe to do an `assert location is not None` instead of what we're doing now

2022-08-11 17:02 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
>              and isinstance(command["payload"]["location"], LegacyWell)
Already present in the code base, but I made a comment about how these looked unnecessary in new code. Are they also unnecessary here (and below) in the old code? If not, would be worth cleaning up

2022-08-11 17:02 UTC, jerader commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        last_location = pipette._ctx.location_cache
I see, got it. Thank you for the explanation!

2022-08-11 17:07 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        well: LegacyWell
Unnecessary declaration, remove

2022-08-11 17:07 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        well: LegacyWell
Unnecessary variable declaration

2022-08-11 17:07 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        slot = DeckSlotName(first_parent)
You can't pass a `Well` object into `DeckSlotName`, this looks wrong. I think you need to grab the well's parent's parent, figure out if it's a slot or a module, and act accordingly

2022-08-11 17:07 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        slot = DeckSlotName(first_parent)
Same bug: you can't pass a `Well` (which `location` may be, according to the type signature) to `DeckSlotName`

2022-08-11 17:16 UTC, SyntaxColoring requested changes

2022-08-11 17:16 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_runner/smoke_tests/test_legacy_command_mapper.py
> +        params=matchers.Anything(),
This test should probably spell out the expected `params`, right? Since one of the big jobs of `LegacyCommandMapper` is to create correct `params` given information from PAPIv2.

2022-08-11 17:16 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        assert first_parent is not None, "Labware needs to be associated with a slot"
I don't think this is a valid assumption. This breaks this valid PAPIv2 protocol:

```python
from opentrons.types import Location, Point

metadata = {
    "apiLevel": "2.11"
}

def run(protocol):
    tip_rack = protocol.load_labware("opentrons_96_tiprack_300ul", 1)
    well_plate = protocol.load_labware("agilent_1_reservoir_290ml", 2)

    pipette = protocol.load_instrument("p300_single_gen2", mount="left", tip_racks=[tip_rack])

    pipette.pick_up_tip()

    pipette.aspirate(300, well_plate["A1"])

    pipette.move_to(Location(point=Point(100, 100, 10), labware=None))
    pipette.blow_out()
```

On `edge`, it successfully analyzes. On this PR, it fails on this assert.

The underlying problem is that the Protocol Engine `blowOut` command demands a well location, which may not make sense in a Python protocol.

Our options for solving this specific thing are:

* Omit `blowOut` commands for now.
    * This will cause them to be dropped from the run log. I don't think we should do this.
* Do not translate `blowOut` commands; leave them as the legacy pass-through, for now.
    * I think this is our best option for this PR. 
* Modify the Protocol Engine `blowOut` command to account for this possibility.
    * In other discussions, we've proposed making the `location` of a Protocol Engine `blowOut` command optional, or having a separate `blowOutInPlace` command.
    * We've discussed this a little while ago and I think we have consensus that it's something we should do.
    * But I don't think it's for this PR.

2022-08-11 17:22 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        assert first_parent is not None, "Labware needs to be associated with a slot"
I think the same problem exists for `aspirate()`ing and `dispense()`ing.

2022-08-11 17:34 UTC, jerader commented on api/tests/opentrons/protocol_runner/smoke_tests/test_legacy_command_mapper.py
> +        params=matchers.Anything(),
Since this is a `loadLabware`, i didn't add expected `params`. In this file, all the `load` commands previously added did not include the expected `params` either

2022-08-11 20:56 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        assert first_parent is not None, "Labware needs to be associated with a slot"
This will assert if `location` is a `Well`, which is valid

2022-08-11 20:59 UTC, mcous commented on api/tests/opentrons/protocol_runner/smoke_tests/test_legacy_command_mapper.py
> +        params=matchers.Anything(),
I think that should be chalked up as a deficiency of the existing tests. We should definitely be checking load params here

2022-08-11 21:02 UTC, mcous commented
I gave `LabwareLike` a read through, and it look like `location.labware.as_well` **may only be used if `location.labware.is_well() is True`. I think a lot of of calls in this PR need to be adjusted, accordingly.

Per @SyntaxColoring's suggestion, I think anything not translatable needs to fall back to the existing `custom` solution, _and_ we need to have tests covering the deficiencies so we know what we need to fill in

2022-08-18 21:14 UTC, SyntaxColoring requested changes
Getting there!

2022-08-18 21:14 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        flow_rate = command["payload"]["rate"]
I don't think this `flow_rate` is right.

In PAPIv2, the `rate` argument to `aspirate()` and `dispense()` is a unitless relative multiplier of the default flow rate. And that's what's we're given in `command["payload"]["rate"]`. But in Protocol Engine, `flowRate` is supposed to be in absolute µL/sec.

(I kind of wish we had named Protocol Engine's field like `ulPerSec` to mitigate this confusion, but that ship has sailed, unfortunately.)

I would do something like:

```python
flow_rate = command["payload"]["rate"] * pipette.flow_rate.aspirate
# or
flow_rate = command["payload"]["rate"] * pipette.flow_rate.dispense
```

Some of your smoke tests are already covering this; they're just expecting the wrong output.

2022-08-18 21:14 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        flow_rate = pipette.flow_rate.blow_out
*This* `flow_rate` is correct (because `blow_out()` doesn't have a `rate` override).

2022-08-18 21:14 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
>                      wellName=well_name,
As this code is currently written, it doesn't pass along the `wellLocation` offset within the well, if the protocol did something like:

```python
aspirate(10, well.top(z=1))
```

I'm not sure whether or not this is acceptable for App+UI needs. If it is, we can certainly leave it like this, but it might be worth a comment noting that it's a deliberate omission for simplicity.

2022-08-18 21:14 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            slot = DeckSlotName(location.labware.first_parent())
A few things about this `if`/`else` section look questionable.

-----

```python
        if isinstance(location, LegacyWell):
            well = location
```

I don't think this code ever actually executes.

I inspected `InstrumentContext.aspirate()` and `InstrumentContext.dispense()` with [`reveal_type()`](https://mypy.readthedocs.io/en/stable/common_issues.html#reveal-type). I also tried running this code with a [`breakpoint()`](https://peps.python.org/pep-0553/). According to that testing, the `location` that we get will always be a `Location`, never a `LegacyWell`. Even if the protocol does something like `pipette.dispense(10, my_well_plate["A1"])`.

So the payload PAPIv2 payload type is misleading.

Note that if this code ever *did* execute, I'm pretty sure it would be a bug, because it leaves `slot` unset.

I think I'm going to open another quick PR to fix the PAPIv2 payload type. For this PR, I think let's just omit this `LegacyWell` check.

-----

```python
        elif isinstance(location, Location):
            if location.labware.is_well:
                well = location.labware.as_well()
            slot = DeckSlotName(location.labware.first_parent())
```

This nested `if` statement is questionable. If `location.labware.is_well` is false, `well` will be undefined, and this function will hit a `NameError` when it tries to access it.

-----

We can write this more robustly by having a final `else` statement handle the legacy fallback case.

```
if command is something that we're sure we can handle smartly:
    handle command smartly
else:
    handle command conservatively with the legacy fallback
```

-----

All together, I would write this section something like this:

```python
if isinstance(location, Location) and location.labware.is_well:
    well = location.labware.as_well()
    slot = DeckSlotName(location.labare.first_parent())
else:
    # TODO:(jr, 15.08.2022): aspirate and dispense commands with no specified labware
    # get filtered into custom. Refactor this in followup legacy command mapping
    return pe_commands.Custom.construct(
        id=command_id,
        key=command_id,
        status=pe_commands.CommandStatus.RUNNING,
        createdAt=now,
        startedAt=now,
        params=LegacyCommandParams.construct(
            legacyCommandType=command["name"],
            legacyCommandText=command["payload"]["text"],
        ),
    )
```

2022-08-18 21:14 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_runner/smoke_tests/test_legacy_command_mapper.py
> +        pipette_left.aspirate(
Orthogonally to all of that, when the location is labware-based, we should also check that we correctly handle the case where the labware is loaded atop a module. Currently, I think we only cover the case where it's loaded directly on a deck slot?

2022-08-19 14:56 UTC, jerader commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        flow_rate = command["payload"]["rate"]
This makes a lot of sense, thank you!

2022-08-26 15:30 UTC, mcous reviewed
Flow rates still aren't quite right, but very close!

2022-08-26 15:30 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        flow_rate = command["payload"]["rate"]
Is this line unnecessary now?

2022-08-26 15:30 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +                    flow_rate = command["payload"]["rate"] * pipette.flow_rate.aspirate
Why is there an `if flow_rate == 1.0:` here? This multiplication still needs happen if the payload is e.g. `0.9` or `1.1`

```suggestion
                flow_rate = command["payload"]["rate"] * pipette.flow_rate.aspirate
```

2022-08-26 15:30 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +                    flow_rate = command["payload"]["rate"] * pipette.flow_rate.dispense
Same comment as above

```suggestion
                flow_rate = command["payload"]["rate"] * pipette.flow_rate.dispense
```

2022-08-26 15:30 UTC, mcous commented on api/tests/opentrons/protocol_runner/smoke_tests/test_legacy_command_mapper.py
> +        pipette_left.aspirate(
Still missing `aspirate` and `dispense` tests for:

- A Location, without any associated labware or well
    - e.g. `location=Location(point=Point(100, 100, 10), labware=None)`
- A Location associated only with a labware
     - Aside: I'm not sure this is a _logical_ construct, but the command mapping at least needs to be ensured to not blow up, since it's possible input
     - e.g. `location=Location(point=Point(100, 100, 10), labware=well_plate_1)`

2022-08-26 15:30 UTC, mcous commented on api/tests/opentrons/protocol_runner/smoke_tests/test_legacy_command_mapper.py
> +            rate=130,
This is not a likely input value. As specified [in the docs](https://docs.opentrons.com/v2/new_protocol_api.html#opentrons.protocol_api.contexts.InstrumentContext.aspirate):

> - **rate** ([_float_](https://docs.python.org/3/library/functions.html#float)) – A relative modifier for how quickly to aspirate liquid. The flow rate for this aspirate will be _rate_ * [`flow_rate.aspirate`](https://docs.opentrons.com/v2/new_protocol_api.html#opentrons.protocol_api.contexts.InstrumentContext.flow_rate). If not specified, defaults to 1.0.

I'd suggest something in the scale of `0.0` - `2.0`

2022-08-26 15:30 UTC, mcous commented on api/tests/opentrons/protocol_runner/smoke_tests/test_legacy_command_mapper.py
> +            flowRate=130,
Same comment as above: `pipiette.aspirate(..., rate=130)` _does not_ map to `flowRate=130` (in µL/s)

2022-08-26 15:44 UTC, SyntaxColoring requested changes, later dismissed

2022-08-26 15:44 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +                    flow_rate = command["payload"]["rate"] * pipette.flow_rate.dispense
Ditto my other comment about not putting this calculation under an if-statement.

2022-08-26 15:44 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +                    flow_rate = command["payload"]["rate"] * pipette.flow_rate.aspirate
Why is this calculation under an if-statement? I'm pretty sure we need to do this calculation no matter the value of `flow_rate`: 1.0, 2.0, 0.5, or anything else.

If `pipette.flow_rate.aspirate` is 123, and the protocol does `pipette.aspirate(volume, rate=2.0)`, I'm pretty sure the absolute flow rate will be 246, so the Protocol Engine `aspirate` command should be constructed with `flowRate=246`. Does that match your understanding?

2022-08-26 15:44 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_runner/smoke_tests/test_legacy_command_mapper.py
> +LEGACY_COMMANDS_PROTOCOL = textwrap.dedent(
The length of this big monolithic test protocol makes it difficult to visually pair input with expected output. We should split this up. I would split it up by PAPIv2 command.

I think @mcous suggested this in an earlier comment, but I'm having trouble finding it.

2022-08-26 15:45 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +                    flow_rate = command["payload"]["rate"] * pipette.flow_rate.aspirate
Yeah, I had the same comment. Moving it here:

> Why is this calculation under an if-statement? I'm pretty sure we need to do this calculation no matter the value of `flow_rate`: 1.0, 2.0, 0.5, or anything else.
> 
> If `pipette.flow_rate.aspirate` is 123, and the protocol does `pipette.aspirate(volume, rate=2.0)`, I'm pretty sure the absolute flow rate will be 246, so the Protocol Engine `aspirate` command should be constructed with `flowRate=246`. Does that match your understanding?

2022-08-26 15:54 UTC, jerader commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +                    flow_rate = command["payload"]["rate"] * pipette.flow_rate.aspirate
Hey yall, thanks! I see Mike's comment below about how `130` isn't a valid `rate`. I thought you could input a `flow_rate` up to the max volume of the pipette for some reason. But maybe this is false knowledge that I always used since it probably caps at the real max `rate`. This makes a lot of sense.

2022-08-26 15:56 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
>                  well = location.labware.as_well()
Let's combine these conditionals.

```suggestion
        if isinstance(location, Location) and location.labware.is_well:
            well = location.labware.as_well()
```

This is important because this line below *requires* `well` to be defined, and this inner conditional is the only place that defines it.

```python
well_name = well.well_name
```

So there's a hazard if `well_name = well.well_name` can ever run without `well = location.labware.as_well()` having run.

2022-08-26 16:05 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        flow_rate = command["payload"]["rate"]
It should be once the suggestions in https://github.com/Opentrons/opentrons/pull/11296#discussion_r956156177 and https://github.com/Opentrons/opentrons/pull/11296#discussion_r956156396 adopted, yeah.

2022-09-13 15:02 UTC, mcous approved these changes
Just some cleanup comments, but nothing that affects functionality

2022-09-13 15:02 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            well = location.labware.as_well()
Can we change this to an assert? The Protocol API ensures that only a well `Location` will ever make it here, so the `if` is a little misleading, because the `else` would be a violation of our internal guarantees 

```suggestion
        assert location.labware.is_well
        well = location.labware.as_well()
```

You can tell this `if` is bad because it's the only place where the `well` variable is assigned a value, but it's used later in the function outside of the `if`

2022-09-13 15:02 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            well = location
Same comment here; the PAPI is supposed to guarantee this, so we should assert rather than branch

```suggestion
        assert isinstance(location, LegacyWell)
        well = location
```

2022-09-13 15:02 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            return pe_commands.Custom.construct(
For readability, it _might_ be worth moving this block to the top. I had a lot of trouble tracing this back to its original `if`

2022-09-13 15:02 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +            if location.labware.is_well:
Should this just be one `if`?

```suggestion
        if isinstance(location, Location) and location.labware.is_well:
```

2022-09-14 15:48 UTC, merged