refactor(discovery-client,app): robust robot model detection
OpenTrons/opentrons-api pull request #11301
Opened 2022-08-05 18:35 UTC by sfoster1

We previously could figure out whether a robot was an OT-2 or OT-3 based
on an element of the robot server health response, sent to us by the
discovery client. However, this isn't robust enough for all the
different places we display information about robots - somtimes we can't
get the health response but still want to display information.

As of https://github.com/Opentrons/opentrons/pull/11295 , robots
advertise their robot model in
- a TXT record attached to their MDNS advertisements
- the health response presented by the update server
in addition to the presentation in the health response from the robot
server.

The discovery client now harvests (and presents proper types for) all
this data and sends it upstream to whatever is listening, with a new
advertisedModel field for the MDNS response, and a proper shape for the
health data from the update server.

We need to coalesce these three data sources into a single robust
presentation of the robot model, which we do in the app's 
discovery-client interface layer. That coalesced data goes in the app's 
redux store.

We coalesce the data by taking the first valid element from the
prioritized list (/health, /server/update/health, mdns) where validity
means that the response is present; the key containing the model is
present; and the model is regex-valid to known models. If any element is
missing or not present, it is skipped. If no element is valid or
present, then for now we default to saying that the robot is an OT-2. In
the future, that might be a decision we want to make at a higher level.

## Review Requests
- It's been a while since I wrote any jslike, and technically this is the first time I've written typescript; please don't hold back on style or anything else
- Similarly, still getting back into the swing of the way things are tested in the app
- Do we want a different style of selector? Do we want a separate hook for this? 
- I think @koji was doing a frontend pr that will work great on top of this, but also I can add some frontend stuff if we want, like changing the displayed model in the devices page

## Testing
- A bit of a pain without any UI given that we don't actually store the coalesced data in redux, that logic is in a selector. Willing to change that, but for now we really just need to make sure nothing crashes I guess.

Closes RCORE-67

2022-08-09 16:47 UTC, brenthagen approved these changes
aside from necessary changes to pass CI, approach makes sense to me and code looks good. i think that adding a hook to encapsulate the `getRobotModelByName` selector is not necessary right now.

2022-08-09 16:47 UTC, brenthagen commented on app/src/organisms/Devices/RobotCard.tsx
>                {/* robot_model can be seen in the health response, but only for "connectable" robots. Probably best to leave as "OT-2" for now */}
comment can be removed

2022-08-09 16:47 UTC, brenthagen commented on app/src/organisms/Devices/RobotStatusBanner.tsx
> +          {robotModel}
comment above can be removed

2022-08-09 16:47 UTC, brenthagen commented on app/src/organisms/Devices/RobotStatusBanner.tsx
> +    getRobotModelByName(state, name)
`getRobotModelByName` needs to be mocked in the test file

2022-08-09 16:47 UTC, brenthagen commented on app/src/organisms/Devices/RobotCard.tsx
> +    getRobotModelByName(state, robot?.name)
same, `getRobotModelByName` needs to be mocked in the test file

2022-08-09 16:47 UTC, brenthagen commented on app/src/redux/discovery/selectors.ts
> +  return robot !=null ? getRobotModel(robot) : null
missing space: `!= null`

2022-08-09 16:51 UTC, koji commented
@brenthagen @sfoster1 
The comments from Brent are what I added. I will address all comments today.

2022-08-09 17:15 UTC, koji commented on app/src/organisms/Devices/RobotCard.tsx
> +    getRobotModelByName(state, robot?.name)
I forgot to add the test case for this.
I will add it.

2022-08-09 17:15 UTC, koji commented on app/src/organisms/Devices/RobotStatusBanner.tsx
> +    getRobotModelByName(state, name)
I forgot to add the test case for this.
I will add it.

2022-08-10 14:31 UTC, mcous requested changes
Only a partial review, but some suggestions so far

2022-08-10 14:31 UTC, mcous commented on app/src/organisms/Devices/RobotCard.tsx
> +  )?.split(' ')[0]
What is this `split` doing? I would recommend including it in the selector itself, where it will be _much_ easier to test

2022-08-10 14:31 UTC, mcous commented on app/src/organisms/Devices/RobotStatusBanner.tsx
> +  )?.split(' ')[0]
Same comment: move common computed state logic to the selector, rather than the component

2022-08-10 14:31 UTC, mcous commented on app/src/organisms/Devices/__tests__/RobotCard.test.tsx
> +    mockGetRobotModelByName.mockReturnValue(ROBOT_MODEL_OT2)
Do not use unconditional return values in test stubs, they hide bugs. Use `when` and ensure proper arguments are passed to the selector

2022-08-10 14:31 UTC, mcous commented on app/src/organisms/Devices/__tests__/RobotCard.test.tsx
> +    mockGetRobotModelByName.mockReturnValue(ROBOT_MODEL_OT3)
Unconditional stubbing

2022-08-10 14:31 UTC, mcous commented on app/src/organisms/Devices/__tests__/RobotStatusBanner.test.tsx
> +    mockGetRobotModelByName.mockReturnValue(ROBOT_MODEL_OT2)
Unconditional stubbing

2022-08-10 14:31 UTC, mcous commented on app/src/organisms/Devices/__tests__/RobotStatusBanner.test.tsx
> +    mockGetRobotModelByName.mockReturnValue(ROBOT_MODEL_OT3)
Unconditional stubbing

2022-08-10 14:31 UTC, mcous commented on app/src/redux/discovery/selectors.ts
> +      null
I don't think this `null` is necessary. If omitted, the initial value of `bestModel` will be `healthModel`, which is what we want

2022-08-10 14:31 UTC, mcous commented on discovery-client/Makefile
> +$(main_out) $(cli_out): src/*.ts src/mdns-browser/*.ts src/store/*.ts package.json webpack.config.js tsconfig.json
I get the motivation here, but given that bundle times are fast for this project and the likelihood of structural refactors making this obsolete and subtly breaking the build, I think we should omit this change

2022-08-10 14:31 UTC, mcous commented on discovery-client/src/mdns-browser/index.ts
> +
I've been trying to move away from reduce in my own code, and it's been pretty rewarding in terms of readability. Here, I would recommend a `map` and a `find`:

```suggestion
const RE_ROBOT_MODEL = /robotModel=(?<robotModel>.*)/

const robotModelFromTxt = (records: string[] | undefined): string | null => {
  records = records ?? []

  const model = records
    .map((e: string) => e.match(RE_ROBOT_MODEL)?.groups?.robotModel)
    .find(maybeModel => maybeModel != null)

  return model ?? null
}
```

2022-08-10 14:51 UTC, koji commented on app/src/organisms/Devices/RobotCard.tsx
> +  )?.split(' ')[0]
Using `split` to get `OT-` part since `getRobotModelByName` returns `OT-2 Standard`/`OT-3 Standard`.

2022-08-10 14:51 UTC, koji commented on app/src/organisms/Devices/__tests__/RobotCard.test.tsx
> +    mockGetRobotModelByName.mockReturnValue(ROBOT_MODEL_OT2)
I will address your feedback.

2022-08-10 15:39 UTC, sfoster1 commented on app/src/redux/discovery/selectors.ts
> +      null
it's to coalesce away from `undefined` as defensive coding, since i don't believe discovery-client actually does that. if we're comfortable, totally can remove

2022-08-10 15:41 UTC, sfoster1 commented on discovery-client/src/mdns-browser/index.ts
> +
oh yeah that looks very nice

2022-08-11 20:06 UTC, mcous commented on app/src/organisms/Devices/RobotCard.tsx
> +  )?.split(' ')[0]
My comment still stands, this common work should be done in the selector, not the React components

2022-08-11 20:06 UTC, mcous commented on app/src/redux/discovery/selectors.ts
> +      null
Didn't read the code properly, my bad

2022-08-11 21:40 UTC, koji commented on app/src/organisms/Devices/RobotCard.tsx
> +  )?.split(' ')[0]
Just pushed code

2022-08-12 18:00 UTC, mcous approved these changes

2022-08-12 18:00 UTC, mcous commented on components/src/testing/utils/renderWithProviders.tsx
> +  store.getState = jest.fn(() => initialState)
Why was this added? And if we're faking out the store entirely (probably a good idea!), why are we calling `createStore` at all? Would this be better?

```ts
const store: Store<State> = {
  getState: jest.fn(() => initialState)
  dispatch: jest.fn()
}
```

Alternatively, it it's not needed, we could revert this addition

2022-08-12 18:07 UTC, koji commented on components/src/testing/utils/renderWithProviders.tsx
> +  store.getState = jest.fn(() => initialState)
without a getState implementation, the mocked store can't return a state object

2022-08-15 14:18 UTC, merged