feature(api+robot-server): Allow loadLiquid commands and liquids support in protocol engine and analysis
OpenTrons/opentrons-api pull request #11310
Opened 2022-08-09 14:21 UTC by TamarZanzouri

# Overview

closes Jira ticket [RLIQ-8](https://opentrons.atlassian.net/browse/RLIQ-8).
this PR gives protocol engine the ability to consume and analyze loadLiquid and store liquids in the engine state.

# Changelog

- Add LoadLiquid command to protocol engine
- Added AddLiquidAction to protocol engine
- Added Liquids dictionary to protocol engine state
- Added Liquids to StateSummery and to Run

# Review requests

1. Did I miss anything?
2. Was not tested on hardware yet
3. Are the test changes sufficient? 

# Risk assessment

Medium. Added a new command, should not effect if not being called. added Liquids to StateSummery and Run data models. need to make sure old logic is not effected.

2022-08-09 15:28 UTC, TamarZanzouri commented on api/src/opentrons/protocol_reader/role_analyzer.py
> +    liquids: Optional[Dict[str, Liquid]] = None
Should I make this not optional and assign it an empty dict?

2022-08-10 15:18 UTC, mcous requested changes
Various suggestions to keep this feature architecturally aligned

2022-08-10 15:18 UTC, mcous commented on api/src/opentrons/protocol_engine/actions/actions.py
> +    liquid: Liquid
It might be better to recreate the parameters rather than tie ProtocolEngine internals to the public JSONv6 schema in this way

```suggestion
    display_name: str
    description: str
    display_color: Optional[str]
```

2022-08-10 15:18 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/__init__.py
> +    "VolumeByWell",
This export doesn't seem to be imported into this file. Is this a copy-paste error?

2022-08-10 15:18 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/command_unions.py
> +    LoadLiquid,
Nitpick: can we move these _above_ the module exports so they sit next to the other protocol-level commands?

2022-08-10 15:18 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +    volumeByWell: Dict[str, int] = Field(
Might rename this here and in JSONv6 to match existing conventions. Also needs to accept a `float`, not an `int`

```suggestion
    volumeByWellName: Dict[str, float] = Field(
```

It's important to be very explicit about what an object's keys represent

2022-08-10 15:18 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +        description="Well and associated liquid volume.",
Can we flesh this out?

```
Volume of liquid, in µL, loaded into each well by name, in this labware.
```

2022-08-10 15:18 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +        pass
Unnecessary `__init__` method can be removed

2022-08-10 15:18 UTC, mcous commented on api/src/opentrons/protocol_engine/state/labware.py
> +    # We rely on Json v6+ preservation of dict insertion order.
JSON objects are not an ordered data structure. What order is important here?

2022-08-10 15:18 UTC, mcous commented on api/src/opentrons/protocol_engine/state/labware.py
> +        return self._state.liquids
This labware state is long, I was assuming we'd  add a liquids substate. Might be nice to have a new substate to start trying new things out, too

2022-08-10 15:18 UTC, mcous commented on api/src/opentrons/protocol_engine/state/state.py
> +            liquids=self._labware.get_liquids(),
We should return a list here, not a dictionary, to match other resources. Load order of resources generally matters, and once a dictionary leaves Python (e.g. via a JSON HTTP response) it is no longer ordered

2022-08-10 15:18 UTC, mcous commented on api/src/opentrons/protocol_engine/state/labware.py
> +    liquids: Dict[str, Liquid]
I think we're going to want out or `Liquid` resource model for the ProtocolEngine / HTTP API that includes an ID, like all other resources. I would name the JSONv6 model a `LiquidCreate`, similar to other models in the schema that provide creation data but not a full resource representation

2022-08-10 15:18 UTC, mcous commented on api/src/opentrons/protocol_engine/state/state_summary.py
> +    liquids: Dict[str, Liquid]
List, not dictionary. Also needs a default value to ensure backwards compatibility with the 6.0 release

2022-08-10 15:18 UTC, mcous commented on api/src/opentrons/protocol_reader/protocol_reader.py
> +            liquids=role_analysis.liquids,
Why are liquids coming out of role analysis?

2022-08-10 15:18 UTC, mcous commented on api/src/opentrons/protocol_reader/role_analyzer.py
> +            liquids=liquids,
`RoleAnalysis` determines what purpose a given file has in a protocol. It is not an appropriate place to add liquid information. These changes should be reverted

2022-08-10 15:18 UTC, mcous commented on api/src/opentrons/protocol_runner/json_command_translator.py
>              "moveToSlot",
`moveToSlot` has been removed from the schema, this whole list can go away

2022-08-10 15:56 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/__init__.py
> +    "VolumeByWell",
I made this class and then regretted it. Ill remove it!

2022-08-10 16:12 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +    volumeByWell: Dict[str, int] = Field(
should I change this in the 6.json as well? @mcous

2022-08-10 16:25 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +    liquids: Dict[str, Liquid]
yes I thought about this too! will make the change

2022-08-10 18:28 UTC, shlokamin commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +    volumeByWell: Dict[str, int] = Field(
if we change to `volumeByWellName` there are several places in the frontend where we'd need to also change. not saying we shouldnt do that, just saying it's gotta be a full stack change or stuff will break

2022-08-11 16:38 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +    )
Was this `LoadLiquidsParams` shape specified anywhere previously, or was it designed in this PR?

I have a few uncertainties about it.

* I don't understand what `liquidId` represents. Is this allowed to be literally any arbitrary string? Will we do any validation to confirm that the `liquidId` refers to something that already exists? If so, how does a protocol make a `liquidId` exist?
* ~~Volumes are currently `int`s. I think they should be `float`s, unless we have a good reason for them to be `int`s?~~
* The ability of this command to scatter liquids across many wells at once seems to be in a weird in-between place, right now.

  Currently, it's like this:

  > A single `loadLiquid` command can load varying amounts of the given liquid into **any selection of wells** within **a single labware.**

  But this strikes me as sort of an unnecessary compromise? I would have expected either:

   > A single `loadLiquid` command loads the specified amount of the given liquid into **a single well.** Use multiple `loadLiquid` commands if you have multiple wells.
   > 
   > (A representation that is neither labware-centric nor liquid-centric.)

   Or:

   > A single `loadLiquid` command can load varying amounts of the given liquid into any selection of wells **across all pieces of labware.**
   > 
   > (A liquid-centric representation.)
    
   [Edit] Or:

   > A single `loadLiquid` command can load varying amounts of the given **liquids** (plural) into any selection of wells **across all pieces of labware.**
   > 
   > (A representation that is neither labware-centric nor liquid-centric. And, it still lets the protocol author gather many manual liquid setup actions into a single Protocol Engine step.)

2022-08-11 16:38 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +
Do we know yet how we expect to adapt this to Python protocols that don't currently have a way to declaratively, statically specify which liquids they'll use? Will we give them a declarative way to do that, or will we have to add an `addLiquid` command, or something else?

2022-08-11 16:45 UTC, mcous commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +
@TamarZanzouri and I have discussed adding a new broker event to the proposed `ctx.create_labware` that will result in this method/`Action` (not command) adding the liquid to the engine state

2022-08-11 16:49 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +    )
> Was this LoadLiquidsParams shape specified anywhere previously, or was it designed in this PR?

Designed previously as a speculative part of the JSONv6 schema. I agree that it needs at least some changes.

> I don't understand what liquidId represents.

`liquidId` represents the identifier of a liquid that has previously been added to ProtocolEngine state, either from the JSON protocol or some as-yet-unwritten PAPIv2 method

> Volumes are currently ints

Typo

> The ability of this command to scatter liquids across many wells at once seems to be in a weird in-between place, right now.

I've come around to this by assuming that this matches how the user is thinking about it. I _imagine_ that a user is physically setting up each labware one at a time (and that's how the UI presents it).

I don't necessarily think this constraint should map to the PAPI, where I think proposed stuff that works on `Well` objects directly is a better path forward, but PAPI can map to N number of `loadLiquid` commands

2022-08-11 16:53 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +    volumeByWell: Dict[str, int] = Field(
Will any _production_ stuff break? I think we tried to communicate pretty explicitly that the backend didn't want to consider the v6 loadLiquid schema baked until we had a chance to get the backend implementation in place

I worry that this field name is confusing if/when we start assigning unique identifiers to wells and the key structure for this dict becomes a lot more ambiguous

2022-08-11 17:58 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +
> this method/Action (not command)

I guess by analogy with the way `add_labware_definition()` is a method, instead of a command?

2022-08-11 19:48 UTC, shlokamin commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +    volumeByWell: Dict[str, int] = Field(
synced with @mcous irl, we agreed not to change name now in favor of doing more changes later. we don't wanna change schema v6 across releases

2022-08-15 18:48 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +    )
> > The ability of this command to scatter liquids across many wells at once seems to be in a weird in-between place, right now.
> 
> I've come around to this by assuming that this matches how the user is thinking about it. I _imagine_ that a user is physically setting up each labware one at a time (and that's how the UI presents it).
> 
> I don't necessarily think this constraint should map to the PAPI, where I think proposed stuff that works on `Well` objects directly is a better path forward, but PAPI can map to N number of `loadLiquid` commands

Hm. After looking at the latest app designs, I'm still skeptical. Physically setting up each labware one-at-a-time is a totally valid way to think about liquid setup, but it's not the *only* way. And—perhaps most crucially—the app is deliberately agnostic as to whether the operator goes labware-by-labware, liquid-by-liquid, or something in between.

I think the app is just going to throw this structure away and replace it with its own. So, I would instead optimize for either:

* API minimalism.
    * I think this would mean: a single `loadLiquid` places a single liquid into a single well.
* Losslessly mapping the intent of the protocol author. Let them structure the liquid setup phase however it makes sense to them.
    * I think this would mean: a single `loadLiquid` may place many liquids into many wells, and those wells can be across multiple pieces of labware.

Ultimately, though, I think this API design is good enough, so I'm happy to move ahead with it if we want to stop thinking about it.

2022-08-15 20:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/actions/actions.py
> +from opentrons.protocol_engine.commands.load_liquid import Liquid
No action needed, just an organizational question and I'm curious about what other people think.

Should `opentrons.protocol_engine.commands` re-export `Liquid` so this import becomes like this?

```python
from opentrons.protocol.engine_commands import Liquid`
```

There are cases, such as here, where an importer of the `LoadLiquid` command must be able to name the `Liquid` type and construct `Liquid` objects. So, strictly, `Liquid` needs to be part of the public interface.

Our import conventions confuse me sometimes, but with the way the code is written now, I think it's importing something that's too deep to be public?

2022-08-15 20:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +        description="Unique identifier generated by the app of instance of liquid to load.",
```suggestion
        description="Unique identifier of the liquid to load.",
```

My understanding is that this identifier will be generated by either:

* Protocol Designer
* The Python Protocol API

And not the Opentrons App.

2022-08-15 20:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +        return LoadLiquidResult()
We're not doing any input validation here. For example, you can do a `loadLiquid` with:

* A `liquidId` that doesn't exist.
* A well that doesn't exist.
* A labware that doesn't exist.

Is that intentional?

2022-08-15 20:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/json_translator.py
> +    assert liquid is not None
```suggestion
```

I don't think this `assert liquid is not None` is doing anything.

If `liquidId` is present in the `protocol.liquids` dict, its type will always be a `liquidCreate` object. Never `None`.

If `liquidId` *isn't* present in the `protocol.liquids` dict, the dict access will raise a `KeyError`, and we won't even reach this `assert`.

It's probably not good that this code will raise an internal `KeyError` for invalid input like that—it should raise a `CommandTranslatorError`, maybe—but that limitation is consistent with other code in this file. (`_translate_labware_command()` does the same thing.)

2022-08-15 20:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/json_translator.py
> +    liquid = protocol.liquids[liquidId]  # type: ignore[index]
We can avoid this `# type: ignore[index]` with:

```suggestion
    assert protocol.liquids is not None
    liquid = protocol.liquids[liquidId]
```

2022-08-15 20:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/json_translator.py
>          for command in commands_to_parse:
Now that we're not filtering anything out of `protocol.commands`, we can simplify this to:

```suggestion
        for command in protocol.commands:
```

2022-08-15 20:01 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +class LiquidCreate(BaseModel):
Why this rename?

2022-08-15 20:06 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/actions/actions.py
> +from opentrons.protocol_engine.commands.load_liquid import Liquid
I think you might be correct. I didn't want to add it to the commands init bc all the classes used there are all of the same shape (params/result...). I can add it to the init file once we decide :-)

2022-08-15 20:08 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +        return LoadLiquidResult()
correct. There should not be any logic done on our end at this point. will prob change in the future but for now they just want the result back.

2022-08-15 20:11 UTC, TamarZanzouri commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +class LiquidCreate(BaseModel):
I created a Liquid class that will contain the Id and will be returned to the client. it made sense to change this to LiquidCreate as the other xxCreate classes.

2022-08-15 20:30 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/json_translator.py
> +    assert liquid is not None
makes total sense! thank you for catching this! I will fix both labware and liquid translations.

2022-08-16 14:00 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +    )
I understand what you are saying. I was following the Json v6 structure and from what I understand its going to be hard to change the shape of a loadLiquid command.

2022-08-16 18:07 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +            raise LiquidNotFoundError()
We can simplify this a little bit with the `in` operator:

```suggestion
        if params.liquidId not in self._state_view.liquid.get_all():
            raise LiquidNotFoundError()
```

Edit: Oops, I misread this line. We can't do this exactly because we're looking at `x.id`, not `x`.

2022-08-16 18:07 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +    pass
Let's move this to `opentrons/protocol_engine/errors/exceptions.py` and subclass it from `ProtocolEngineError`. Since that's what we do for `LabwareNotFoundError` and others.

2022-08-16 18:43 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/actions/actions.py
> +from opentrons.protocol_engine.commands.load_liquid import Liquid
I moved it to protocol_engine.types

2022-08-16 18:56 UTC, TamarZanzouri commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +class LiquidCreate(BaseModel):
I can revert this change and call the new Liquid class LoadedLiquid

2022-08-16 19:56 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/liquids.py
> +    def get_all(self) -> List[Liquid]:
should I add a `get(liquidId)`?

2022-08-16 19:57 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/json_translator.py
> +        raise CommandTranslatorError()
this should prob raise `LabwareNotLoadedError`

2022-08-17 13:38 UTC, mcous requested changes

2022-08-17 13:38 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +            raise LiquidNotFoundError()
All exceptions should have a human-readable message

2022-08-17 13:38 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +from ..errors.exceptions import (
Import from the `..errors` module rather than `..errors.exceptions`

2022-08-17 13:38 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +            liquid.id == params.liquidId for liquid in self._state_view.liquid.get_all()
This is a lot of logic to place in a collaborator method and probably complicates the test. I would add a `liquid.has` selector instead

2022-08-17 13:38 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +                    raise WellDoesNotExistError()
Missing message

2022-08-17 13:38 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +            raise LabwareNotLoadedError()
Missing message

2022-08-17 13:38 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +                if well not in labware_wells:
A `try` around a `for` around an `if` is definitely too much logic for a collaborator. Try to move this logic into state view selectors as much as possible

2022-08-17 13:38 UTC, mcous commented on api/src/opentrons/protocol_engine/state/labware.py
> -
Nit pick, but this newline was here for readability of the comments describing the state fields. Please do not remove it

2022-08-17 13:38 UTC, mcous commented on api/src/opentrons/protocol_engine/state/liquids.py
> +    liquids: List[Liquid]
Typically we store objects in dictionaries by ID in ProtocolEngine states, and map them to lists in state view selectors

2022-08-17 13:38 UTC, mcous commented on api/src/opentrons/protocol_engine/state/liquids.py
> +    def get_all(self) -> List[Liquid]:
Only if something actually needs it

2022-08-17 13:38 UTC, mcous commented on api/src/opentrons/protocol_runner/json_translator.py
> +from opentrons.protocol_engine.types import Liquid
Outside of the `opentrons.protocol_engine` module, try to only import from the top-level

```suggestion
from opentrons.protocol_engine import Liquid
```

2022-08-17 13:38 UTC, mcous commented on api/src/opentrons/protocol_runner/json_translator.py
> +        raise CommandTranslatorError()
Why was the `assert` replaced?

2022-08-17 13:38 UTC, mcous commented on api/src/opentrons/protocol_runner/json_translator.py
> +        return liquids
Prefer for comprehensions

```suggestion
        protocol_liquids = protocol.liquids or {}
        
        return [
            Liquid(
                 id=liquid_id,
                 displayName=liquid.displayName,
                 description=liquid.description,
                 displayColor=liquid.displayColor,
            )
            for liquid_id, liquid in protocol_liquids.items()
        ]
```

2022-08-17 13:38 UTC, mcous commented on api/src/opentrons/protocol_runner/json_translator.py
> +                translated_obj = _translate_liquid_command(protocol, command)
Why is `loadLiquid` a special case here? It looks like `_translate_simple_command` would be able to handle it as written

2022-08-17 13:38 UTC, mcous commented on api/src/opentrons/protocol_runner/protocol_runner.py
> +            self._protocol_engine.add_liquid(liquid=liquid)
I'd add the liquids first, because conceptually the commands are going to be using liquid IDs that are in the `liquids` list. The code will function either way, but I think doing the liquids first communicates the design intent better

2022-08-17 13:38 UTC, mcous commented on api/tests/opentrons/protocol_reader/test_protocol_reader.py
> +        main_file=main_file, labware_files=[], labware_definitions=[]
Unnecessary change in unrelated code

2022-08-17 13:38 UTC, mcous commented on api/tests/opentrons/protocol_reader/test_role_analyzer.py
> +                LabwareDefinition.construct(),  # type: ignore[call-arg]
Unnecessary change in unrelated code

2022-08-17 13:38 UTC, mcous commented on api/tests/opentrons/protocol_runner/test_json_translator.py
> +def test_load_liquid(
Do we need a test that validates liquid translation returns an empty list when the protocol has no `liquids` field?

2022-08-17 13:38 UTC, mcous commented on api/src/opentrons/protocol_engine/state/state_summary.py
> +    liquids: List[Liquid]
Cannot be a required field, as previous versions of `StateSummary` objects are persisted in the database _without_ the `liquids` field, which will cause 500.

`liquids` _must_ use `pydantic.Field` with a `default_factory` to be able to migrate old records up to the new version

2022-08-17 14:31 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/json_translator.py
> +        raise CommandTranslatorError()
Max and I spoke about this. We were checking for a key in a dict that might not exist so it will raise a KeyError.

2022-08-17 15:28 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/state_summary.py
> +    liquids: List[Liquid]
nice catch! thank you!

2022-08-17 16:01 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/json_translator.py
> +                translated_obj = _translate_liquid_command(protocol, command)
nice catch! Should I move over the asserts then?

2022-08-17 16:54 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +                if well not in labware_wells:
the catch should before the for loop

2022-08-17 18:48 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/json_translator.py
> +        raise CommandTranslatorError()
Yeah. My thinking is that this JSON document is external input. So if the input is semantically wrong somehow, an "invalid input" exception is more appropriate than an `AssertionError`.

There are still lots of other `assert`s in this file (including the one right here on line 28), but I think this is a step in the right direction.

If anybody feels that this PR should continue using `assert`s everywhere, and that we should leave the exception refactoring to a different PR, I'd also be down for that.

2022-08-17 19:59 UTC, TamarZanzouri commented on robot-server/robot_server/protocols/analysis_models.py
> +    liquids: Optional[List[Liquid]] = Field(
I made this optional as well but could just change it to a default value. was not sure.

2022-08-17 20:23 UTC, SyntaxColoring approved these changes
Lots of little things, but looks good to me overall. 💧

2022-08-17 20:23 UTC, SyntaxColoring commented on robot-server/tests/runs/test_run_store.py
> +        liquids=[],
I don't want to drag this PR out too much, but if we can, let's add actual `liquids` data here. Through `test_get_state_summary()`, this will test that `liquids` can survive a round trip through the `RunStore`.

2022-08-17 20:23 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_models.py
> +    )
Nitpick, does not block merging:

I would move this right below `labware`, for logical grouping.

2022-08-17 20:23 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_models.py
> +
Style nitpick: This should be combined with the existing `opentrons.protocol_engine` import group starting on line 6.

2022-08-17 20:23 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/analysis_store.py
> +from opentrons.protocol_engine import Liquid
Style nitpick: This should be in the existing `opentrons.protocol_engine` import group starting on line 12.

2022-08-17 20:23 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/analysis_models.py
> +
Style nitpick: Combine with existing `opentrons.protocol_engine` import above.

2022-08-17 20:23 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_runner/test_protocol_runner.py
> +from opentrons.protocol_engine import Liquid
Style nitpick: Combine with import above.

2022-08-17 20:23 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_runner/test_json_translator.py
> +from opentrons.protocol_engine import Liquid
Style nitpick: Combine with import above.

2022-08-17 20:23 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_engine/test_protocol_engine.py
> +
Style nitpick: Combine with import on line 15.

2022-08-17 20:23 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/errors/exceptions.py
> +
Optional naming suggestion, does not block merging:

I would call this `LiquidDoesNotExistError` for consistency with `LabwareDefinitionDoesNotExistError`.

2022-08-17 20:24 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +    )
👍 Let's leave it as-is.

2022-08-17 20:27 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +class LiquidCreate(BaseModel):
I think `ProtocolSchemaV6.liquids` should simply have `Liquid`s, for the same reason `ProtocolSchemaV6.labware` simply has `Labware`s, and `ProtocolSchemaV6.modules` simply has `Module`s.

2022-08-17 20:29 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +class LiquidCreate(BaseModel):
Note that there's no need to give `protocol_schema_v6.Liquid` a different name from `opentrons.api.protocol_engine.Liquid`, if that's what you're worried about. The module namespace gives the necessary context to keep them distinct.

2022-08-17 20:39 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/analysis_models.py
> +    liquids: Optional[List[Liquid]] = Field(
Yeah, I was wondering about this too. I think `Optional` will work. I don't have an informed opinion whether a default value would be better or worse.

2022-08-18 14:37 UTC, mcous requested changes
Still got some outstanding issues

2022-08-18 14:37 UTC, mcous commented on api/src/opentrons/protocol_engine/state/liquids.py
> +        return any(liquid.id == liquid_id for liquid in self.get_all())
```suggestion
        return liquid_id in self._state.liquids_by_id
```

2022-08-18 14:37 UTC, mcous commented on api/src/opentrons/protocol_engine/state/liquids.py
> +    def add_liquid(self, action: AddLiquidAction) -> None:
Make private or remove (a one-line method may not be worth the misdirection)

```suggestion
            self._add_liquid(action)

    def _add_liquid(self, action: AddLiquidAction) -> None:
```

2022-08-18 14:37 UTC, mcous commented on api/src/opentrons/protocol_engine/state/labware.py
> -
Unintentional change in an unrelated file?

2022-08-18 14:37 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +            )
I would raise this error in the selector rather than put a try/except here, where it's harder to test

2022-08-18 14:37 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +            if well not in labware_wells:
I'm still thinking this logic makes more sense to place in a labware selector, where it will be easier to test exhaustively and will have better performance (here looks like it could be `O(N*M)` in the worst case, but inside the labware store, well lookups can be done `O(1)`, making this `O(N)`)

2022-08-18 14:37 UTC, mcous commented on api/src/opentrons/protocol_runner/json_translator.py
> +        raise CommandTranslatorError()
I think I'd rather punt to a separate PR for semantic document validation, that includes acceptance tests showing acceptable errors being raised to the client for an invalid document. I'm not sure errors raised by the translator are acceptably communicated at the moment, but I could be wrong

2022-08-18 14:37 UTC, mcous commented on api/tests/opentrons/protocol_engine/commands/test_load_liquid.py
> +    decoy.when(mock_state_view.liquid.has("no-id")).then_return(False)
Remove unused stubbing to make this test more readable

2022-08-18 14:37 UTC, mcous commented on api/tests/opentrons/protocol_engine/commands/test_load_liquid.py
> +    )
Unused stubbing can be removed

2022-08-18 14:37 UTC, mcous commented on api/tests/opentrons/protocol_engine/commands/test_load_liquid.py
> +        ["A1", "B2"]
(Same comment as above) I think this logic is too hard to test here completely, with mocks in play, and should be moved to a pure-logic unit where we can actually completely test the intersection behavior

2022-08-18 14:37 UTC, mcous commented on api/tests/opentrons/protocol_engine/state/test_labware_view.py
> -
Unintentional whitespace change?

2022-08-18 14:37 UTC, mcous commented on robot-server/robot_server/protocols/analysis_models.py
> +    liquids: Optional[List[Liquid]] = Field(
I would softly prefer a `default_factory` to `Optional`. I think the former will be easier for our code to work with, and communicates intent a little better.

`Optional` says to me that "it's not required to find out liquid information" whereas `default_factory` says "we are migrating this data shape upwards in case the source didn't specify liquid data"

2022-08-18 14:37 UTC, mcous commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +class LiquidCreate(BaseModel):
I agree. We should reserve the name `LiquidCreate` for future HTTP API usage

2022-08-18 19:25 UTC, TamarZanzouri commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +class LiquidCreate(BaseModel):
Sorry, I guess I got confused. I will rollback

2022-08-18 19:34 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +        self._state_view.liquid.has(params.liquidId)
raising the error from the view. Should I call this `validate_liquid()` instead?

2022-08-18 19:48 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/commands/test_load_liquid.py
> +async def test_load_liquid_liquid_not_found(
are these tests redundant now that the logic lives in the state?

2022-08-19 14:17 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/liquids.py
> +    def has(self, liquid_id: str) -> str:
change name

2022-08-19 14:29 UTC, TamarZanzouri commented on robot-server/robot_server/runs/run_models.py
> +    liquids: Optional[List[Liquid]] = Field(
add default_factory instead of optional

2022-08-19 14:37 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/commands/test_load_liquid.py
> +async def test_load_liquid_liquid_not_found(
maybe delete these test

2022-08-19 16:33 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +    def validate_labware_has_wells(
debating about the return value. feels like we shouldn't return anything but its easier to test if we are.

2022-08-19 16:33 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/liquids.py
> +    def validate_has_liquid(self, liquid_id: str) -> str:
same comment ^

2022-08-19 19:14 UTC, Laura-Danielle approved these changes
Overall, looks great :) had a few questions about some things.

2022-08-19 19:14 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/commands/load_liquid.py
> +        self._state_view.labware.validate_labware_has_wells(
We should also check that a labware is not a tiprack -- it doesn't make sense to have liquid in a tiprack.

2022-08-19 19:14 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/state/labware.py
> +    def validate_labware_has_wells(
I guess I'm not really sure what we're trying to do with this check. Doesn't all of our labware have at least one well?

2022-08-19 19:14 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/state/liquids.py
> +    def validate_has_liquid(self, liquid_id: str) -> str:
Can we call this function `validate_liquid_id` or something like that? `validate_has_liquid` implies to me that we are checking a certain labware has a liquid.

2022-08-19 19:14 UTC, Laura-Danielle commented on api/src/opentrons/protocol_runner/json_translator.py
> +        for command in protocol.commands:
should there be a "loadLiquid" command we're checking for here? Is that going to be in a follow-up?

2022-08-19 19:14 UTC, Laura-Danielle commented on shared-data/protocol/fixtures/6/oneTiprack.json
> -      "id": "6",
Why this change?

2022-08-22 15:50 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +    def validate_labware_has_wells(
this is checking against a given labware. in case they supplied a well that does not exist in the given labware. makes more sense?

2022-08-22 15:51 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/json_translator.py
> +        for command in protocol.commands:
this is falling under _translate_simple_command. at first it had its own translator but there was no need bc the simple command does exactly what we need

2022-08-22 15:52 UTC, TamarZanzouri commented on shared-data/protocol/fixtures/6/oneTiprack.json
> -      "id": "6",
moveToSlot no longer used

2022-08-22 21:18 UTC, mcous reviewed
A few final notes. Will approve when I've been able to smoke test against persisted protocols / analyses to make sure we don't have any data migration issues

2022-08-22 21:18 UTC, mcous commented on api/src/opentrons/protocol_engine/state/labware.py
> +            )
I would move this check first to avoid checking wells unnecessarily

2022-08-22 21:18 UTC, mcous commented on api/src/opentrons/protocol_engine/state/labware.py
> +        contains_wells = all(item in labware_wells for item in iter(wells))
```suggestion
        contains_wells = all(well_name in labware_wells for well_name in iter(wells))
```

2022-08-22 21:18 UTC, mcous commented on robot-server/robot_server/runs/run_models.py
> +        default_factory=list,
I don't think it harms anything, but I'm pretty sure `default_factory` is not required for this model

2022-08-22 21:18 UTC, mcous commented on api/tests/opentrons/protocol_engine/commands/test_load_liquid.py
> +    ).then_return(["A1", "B2"])
The code under test does not use these return values, so this test isn't doing anything - you can see this by commenting out both calls in `LoadLiquidImplementation` and watching this test continue to pass. (This is why TDD emphasizes writing failing tests before implementing)

You should either refactor the implementation to use the return values, or rewrite the test to `verify` side-effects rather than stub return values. I think the `verify` option probably makes more sense.

2022-08-23 18:58 UTC, TamarZanzouri commented
Tested on a robot with json v5 and v6 protocols

2022-08-23 19:03 UTC, Laura-Danielle commented on api/src/opentrons/protocol_runner/json_translator.py
> +        for command in protocol.commands:
ok that's fine with me.

2022-08-23 19:09 UTC, mcous approved these changes
Smoke tested with the dev server, did not encounter any data migration issues with persisted protocol / analysis / run / commands data from prior to this PR.

Nice work!

2022-08-23 20:01 UTC, merged