fix(api): make sure instrument serial numbers are either 1 or 0
OpenTrons/opentrons-api pull request #11324
Opened 2022-08-10 20:37 UTC by caila-marashaj

If an instrument's serial number isn't written to the eeprom, it was previously defaulting to `65535`, which would cause a lookup error in `OT3API` and prevent it from being used. 

This code defaults all pipette model numbers to 0, and defaults gripper model numbers to 0 if it otherwise wouldn't be found

2022-08-10 20:42 UTC, sfoster1 requested changes
Rather than making it _always_ 0, we should get the model and _override_ it to 0 if its value is exactly `0xffff` since that indicates "unknown". We should also have a test.

2022-08-11 19:42 UTC, Laura-Danielle requested changes
You want to build a test similar to `opentrons/hardware_control/test_ot3_api.py/test_cache_gripper` or the file that tests ot3 controller: `opentrons/hardware_control/test_ot3_controller.py/test_get_attached_instruments`

2022-08-15 18:37 UTC, caila-marashaj commented
> You want to build a test similar to `opentrons/hardware_control/test_ot3_api.py/test_cache_gripper` or the file that tests ot3 controller: `opentrons/hardware_control/test_ot3_controller.py/test_get_attached_instruments`

I just went and added a model number parameter to  `opentrons/hardware_control/test_ot3_controller.py/test_get_attached_instruments`, because I think this functionality can fit within that test, and being able to access the pipette and gripper config info also confirms that the output of `ot3controller.py/_synthesize_model_name` is what it's supposed to be- otherwise we'd be seeing a `KeyError`

2022-08-16 18:04 UTC, vegano1 commented on api/src/opentrons/config/gripper_config.py
> +    if num not in model_map:
we could do
`return model_map.get(num, GripperModel.V1)`

2022-08-16 18:06 UTC, DerekMaggio commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            unknown_model_num = 65535
Small nitpick. 
You set/use the value multiple times. Pulling it out to a constant in another file can make maintenance easier down the line if this value changes

2022-08-16 18:06 UTC, DerekMaggio commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> +        unknown_model_num = 65535
Use constant value here

2022-08-16 18:06 UTC, DerekMaggio commented on api/tests/opentrons/hardware_control/backends/test_ot3_controller.py
> +model_numbers = [0, 65535]
Use constant value here

2022-08-16 18:06 UTC, DerekMaggio commented on api/src/opentrons/config/gripper_config.py
> +        num = 0
A comment stating why we set it to 0 would be helpful

2022-08-16 18:06 UTC, DerekMaggio commented on api/src/opentrons/config/gripper_config.py
> +        num = 0
Pulling 0 out into a constant could also give context to why it is being set to 0

2022-08-16 18:06 UTC, DerekMaggio commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    async def get_attached_instruments(  # noqa: C901
This function is huge with all the nested functions and super difficult to read.
All these nested functions are pure functions (static) and could be pulled out into a utils file.

2022-08-16 18:38 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    async def get_attached_instruments(  # noqa: C901
We're refactoring how this code works soon which is why we pushed it off.

2022-08-16 18:39 UTC, caila-marashaj commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    async def get_attached_instruments(  # noqa: C901
I believe Laura is about to refactor a lot of the pipette config code, so pretty soon this won't exist as it does now anyway

2022-08-16 18:45 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/backends/test_ot3_controller.py
> +@pytest.mark.parametrize("model", model_numbers)
Let's add a separate test case for when the model number is something outside of 'non-flashed' and 0. For now it should still raise a key error.

2022-08-17 19:24 UTC, closed without merging

2022-08-17 19:27 UTC, sfoster1 commented
Replaced by https://github.com/Opentrons/opentrons/pull/11349