feat(hardware): Load pipette model from pipette serial
OpenTrons/opentrons-api pull request #11349
Opened 2022-08-16 00:02 UTC by sfoster1

On the OT-2, we store the literal serial number of a pipette on its EEPROM. When we detect whether it's connected, we read that serial number and parse it out in python.

We could do that here, but we have access to a lot more smarts on the pipette now, so instead let's parse the serial at flash time and store a binary-packed value for the name and model. The datecode part is still stored literally. 

Locally, we can parse it pretty easily, and use it as the model for the rest of the system (which we more or less already do - not many changes on the read side).

The write side is very different. Let's add a script for writing pipette serials but actually make it part of the system this time.

## Testing
- Write and read some serial numbers! You'll need https://github.com/Opentrons/ot3-firmware/pull/437 on the pipette

## TODO
- [ ] This needs proper integration tests

2022-08-16 16:36 UTC, Laura-Danielle approved these changes
Nice. LGTM once failing tests are fixed. Also, did you do a sanity check on the integration tests to make sure behavior isn't changing?

2022-08-16 17:15 UTC, sfoster1 commented
no, that's the todo

2022-08-17 20:37 UTC, Laura-Danielle requested changes
Unless I am reading this wrong, I don't think the original problem of non-flashed pipettes is fully solved.

2022-08-17 20:37 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            return cast("PipetteModel", f"{name.name}_v{model//10}.{model%10}")
How does this fix the original problem if the pipette is not flashed? It will still give the incorrect model lookup info if I'm reading this correctly.

2022-08-17 20:43 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            return cast("PipetteModel", f"{name.name}_v{model//10}.{model%10}")
that's not what solves it. the concept here is that we previously may have wanted to sort of suppress errors coming from unflashed pipettes, but now we can actually flash them, so instead let's emit a structured error. So, it's the code that catches `KeyErrors` from pipette config and turns them into `UnknownPipetteModel` exceptions that solves the issue.

2022-08-18 19:12 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            return cast("PipetteModel", f"{name.name}_v{model//10}.{model%10}")
Oh the answer to this was: we forgot to commit half the work. Here's the other half that actually does what I said above @Laura-Danielle

2022-08-18 19:34 UTC, Laura-Danielle approved these changes
Looks good, but we should handle unflashed grippers also while we're here.

2022-08-18 19:34 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        serial = attached.serial
We'll need to handle the same problem for the gripper as they will start unflashed, otherwise it will hit a KeyError.

2022-08-18 19:34 UTC, Laura-Danielle commented on hardware/opentrons_hardware/pipettes/serials.py
> +    return f"{model//10}.{model%10}"
So `6553.5` for unflashed pipettes?

2022-08-22 15:15 UTC, merged