refactor(app): update JogControls component styling
OpenTrons/opentrons-api pull request #11350
Opened 2022-08-16 15:31 UTC by sakibh

# Overview

This PR updates the `JogControls` component styling for both the `StepSizeControl` and `DirectionControl` sub-components. closes [RAUT-84](https://opentrons.atlassian.net/browse/RAUT-84?atlOrigin=eyJpIjoiYmUzMmVkNjViOGE2NDE2ZDk4ZjgyYmRhYTYxMGNhMzgiLCJwIjoiaiJ9)

![image](https://user-images.githubusercontent.com/14794021/184919177-2bf58a44-2015-4be3-8aa9-61be663aaedc.png)

# Changelog

- Update styling in `StepSizeControl`, `DirectionControl`, and `ControlContainer`
- Add listener for `Shift` key press to switch axes to vertical/z-axis.
 
# Review requests

- Test the deck recalibration/pipette calibration flows on a real robot to ensure functionality is persistent.
- Press the shift key with the up and down arrow to test the ability to switch axes on the UI.
- Check the styling changes for further optimization

# Risk assessment
low, mostly stylistic

2022-08-17 17:15 UTC, jerader requested changes
Its looking good so far! I left a bunch of styling suggestions. The only thing missing is the responsiveness and I think it would be nice to add `DirectionControl` and `StepSizeControl` to Storybook

2022-08-17 17:15 UTC, jerader commented on app/src/molecules/JogControls/ControlContainer.tsx
> +        fontSize={TYPOGRAPHY.fontSizeH6}
```suggestion
        css={TYPOGRAPHY.h6Default}
```

2022-08-17 17:15 UTC, jerader commented on app/src/molecules/JogControls/ControlContainer.tsx
> +        height="156px"
```suggestion
        width="22.8rem"
        height="9.75rem"
```

2022-08-17 17:15 UTC, jerader commented on app/src/molecules/JogControls/DirectionControl.tsx
> +    subtitle: 'Shift + Arrow keys',
I wonder if we should add these to constants?

2022-08-17 17:15 UTC, jerader commented on app/src/molecules/JogControls/DirectionControl.tsx
> +    subtitle: 'Arrow Keys',
add these to constants too?

2022-08-17 17:15 UTC, jerader commented on app/src/molecules/JogControls/DirectionControl.tsx
> +      background-color: white;
```suggestion
      background-color: COLORS.white;
```

2022-08-17 17:15 UTC, jerader commented on app/src/molecules/JogControls/DirectionControl.tsx
> +                  height="58px"
```suggestion
                  minWidth="9.81rem"
                  height="3.62rem"
```

2022-08-17 17:15 UTC, jerader commented on app/src/molecules/JogControls/DirectionControl.tsx
> +      background-color: white;
```suggestion
      background-color: COLORS.white;
```

2022-08-17 17:15 UTC, jerader commented on app/src/molecules/JogControls/DirectionControl.tsx
> +        border: 1px #16212d40 solid;
```suggestion
        border: 1px ${COLORS.lightGreyHover} solid;
```

2022-08-17 17:15 UTC, jerader commented on app/src/molecules/JogControls/StepSizeControl.tsx
> +    10: 'Large',
these should be added to i18n

2022-08-17 17:15 UTC, jerader commented on app/src/molecules/JogControls/StepSizeControl.tsx
> +      background-color: white;
```suggestion
      background-color: COLORS.white;
```

2022-08-17 17:15 UTC, jerader commented on app/src/molecules/JogControls/StepSizeControl.tsx
> +              color={COLORS.black}
`StyledText` adds `black` as the default text color so you dont need to redefine it

```suggestion
```

2022-08-17 17:15 UTC, jerader commented on app/src/organisms/LabwarePositionCheck/LabwarePositionCheckStepDetail.tsx
> -            isLPC={true}
🎉 so cool that we can remove this now

2022-08-17 17:15 UTC, jerader commented on app/src/molecules/JogControls/StepSizeControl.tsx
> +  const STEP_SIZE_BUTTON_STYLING = css`
Are these Button stylings all the same for this component and `DirectionControl`? If so, I suggest exporting the constant in `DirectionControl` and then importing it here so they can share the same constant.

2022-08-22 19:19 UTC, jerader approved these changes
this is looking great! Good job! 🚀 The story looks good and responsive. The only thing is do we want to center the contents to the grey container? 

<img width="495" alt="Screen Shot 2022-08-22 at 3 16 41 PM" src="https://user-images.githubusercontent.com/66035149/186000991-377c563f-bcda-48cc-9e9f-c01310787408.png">

2022-08-22 20:17 UTC, sakibh commented
> 

I think this is because storybook has no upper bound for the width, whereas the app does. It might be better to make the buttons itself resize with the container. I can address this in a follow up.

2022-08-22 20:17 UTC, merged