fix(heater-shaker): fix async error handling
OpenTrons/opentrons-api pull request #11400
Opened 2022-08-25 21:26 UTC by pmoegenburg

Question: store error(s), raise exception on async error only after gcode response read_until completes?

To-do: update TC2 and TD3 driver SerialConnection constructors

2022-08-26 13:40 UTC, sfoster1 requested changes
What this PR is aiming to do is a little unclear - would you mind putting a high level description of the intended behavior in the PR comment?

Some more inline changes too.

2022-08-26 13:40 UTC, sfoster1 commented on api/src/opentrons/drivers/asyncio/communication/serial_connection.py
> +            while (self._error_keyword.encode() in response.lower() and self._gcode_ack.encode() not in response.lower()):
I think the extra logic here of reading while there's an error isn't really needed. I think this could look like
- Write the gcode
- Read from the serial buffer until you get a response to the gcode, keeping a list of the responses you get
- After you've exhausted the buffer, see if there was an error in the list of responses

That really just boils down to collapsing the initial read on line 223 into the while loop; making the while conditional just `while self._gcode_ack.encode() not in response.lower()`; and having `response` be `responses` and doing `responses.append(await self._serial.read_runtil(match=self._ack))`.

2022-08-26 13:40 UTC, sfoster1 commented on api/src/opentrons/drivers/asyncio/communication/serial_connection.py
> +    async def _send_data_async(self, data: str, retries: int = 0) -> str:
I don't love having very big divergences in behavior depend on an initializer argument like this; maybe there could be an `AsyncResponseSerialConnection(SerialConnection)` that overrides `send_data` instead?

2022-08-30 15:40 UTC, pmoegenburg commented on api/src/opentrons/drivers/asyncio/communication/serial_connection.py
> +            while (self._error_keyword.encode() in response.lower() and self._gcode_ack.encode() not in response.lower()):
Don't we need an initial `response` for the while condition to check (so keep line 223)? Are you recommending making that `responses`, and appending to that in the while loop? This leads into the question in the PR description of what we want to do with errors caught

2022-08-30 15:42 UTC, pmoegenburg commented on api/src/opentrons/drivers/asyncio/communication/serial_connection.py
> +    async def _send_data_async(self, data: str, retries: int = 0) -> str:
So AsyncResponseSerialConnection would be a subclass of SerialConnection? The top method is `send_command`, so have the subclass override that method?

2022-08-30 17:02 UTC, sfoster1 commented on api/src/opentrons/drivers/asyncio/communication/serial_connection.py
> +    async def _send_data_async(self, data: str, retries: int = 0) -> str:
yeah exactly

2022-08-30 18:37 UTC, sfoster1 requested changes
Definitely getting there, love the new keyword change. I think with this implementation we wouldn't raise on async errors though

2022-08-30 18:37 UTC, sfoster1 commented on api/src/opentrons/drivers/asyncio/communication/serial_connection.py
> +            response = await self._serial.read_until(match=self._ack)
I think we need to capture all the responses in a list and raise after the fact if any of them have an error:
```
response: List[str] = []
response.append(await read_until...)
while self._async_error.... in response[-1].lower():
    response.append(await read_until()...)
if any(self._ack in r for r in response):
    raise...
return response[-1] # safe since we stopped reading when we got a non-async response

2022-08-31 20:41 UTC, sfoster1 requested changes
I think this is good - I really like the inheritance model - but we really need tests, this is getting pretty complex. We should test
- just an ack response, no async error
- async error then ack, async error correctly handled
- async error then ack then async error, make sure that last async error doesn't get consumed as expected

2022-09-09 17:55 UTC, sfoster1 approved these changes
The code now looks great to me! Love the tests, love the class inheritance implementation.

We should test on hardware, but otherwise this is good to merge.

2022-09-09 18:21 UTC, merged