wip: add instrument loading to PE PAPIv2 core
OpenTrons/opentrons-api pull request #11402
Opened 2022-08-26 14:00 UTC by mcous

## Overview

WIP

RCORE-102

## Changelog

TODO

## Review requests

Test plan in ticket

## Risk assessment

TODO

2022-08-26 20:02 UTC, mcous reviewed
Comments after review session

2022-08-26 20:02 UTC, mcous commented on api/src/opentrons/protocol_api/protocol_context.py
>          self.equipment_broker.publish(
Will lead to duplicate load pipette commands, resolve in this PR.

Options:

- Teach `ProtocolRunner` to _not_ add a `LegacyContextPlugin` if `enableProtocolEnginePAPICore` FF is enabled
- Address this TODO and move equipment broker into the legacy PAPIv2 core

2022-08-26 20:02 UTC, mcous commented on api/tests/opentrons/protocol_api/test_validation.py
> +    """It should properly map strings and mounts."""
```suggestion
def test_ensure_input_invalid() -> None:
    """It should raise if given invalid mount input."""
```

2022-08-26 20:02 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +        pipette_name = PipetteName(instrument_name)
Decided in review: `instrument_name` should be typed as only accepting an `PipetteName` enum. Will require:

- Changes to ABC
- Changes to legacy impls
- Putting `PipetteName` in a home that isn't limited to `opentrons.protocol_engine`
- Add an `ensure_pipette_name` method to `validation` module

2022-08-26 20:02 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        id: ProtocolEngine ID of the loaded instrument.
```suggestion
        pipette_id: ProtocolEngine ID of the loaded instrument.
```

2022-08-30 17:14 UTC, mcous commented
Current dependencies on/for this PR:
* edge
  * **PR #11402** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11402" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Opentrons/opentrons/11402?utm_source=stack-comment).

2022-08-30 17:36 UTC, mcous commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> +from opentrons_shared_data.pipette.dev_types import PipetteName
Could also replace this with `PipetteNameLiteral`

2022-08-30 18:58 UTC, sfoster1 requested changes
This overall looks like a good change, but the `PipetteName` stuff is freaking me out a little bit - I don't quite get how it's all passing typechecking and tests in the hardware controller since none of that stuff is designed for enums, it all is thinking about strings and doing `cast`s into the literal union.

2022-08-30 18:58 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/pipette/dev_types.py
> +class PipetteName(str, Enum):
this is the cause of the shared data tests breaking. the pipette names were defined as a literal union so they could describe the shape of the json file, and the `name_config()` functions in the `__init__` of this submodule return the `PipetteNameSpecs = Dict[PipetteName, PipetteNameSpec` type defined below, which now would mean that it's an enum map instead of a string map.

We'd need to add an explicit transform in the `__init__` for this, which might be a good idea but honestly I don't really get the value over a literal union

2022-08-30 18:58 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> +from opentrons_shared_data.pipette.dev_types import PipetteName
it's confusing to me that this change works because the `PipetteName`s get passed to various handlers that expect strings, which would have been widening but now isn't since this is an enum

2022-08-30 20:27 UTC, mcous commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> +from opentrons_shared_data.pipette.dev_types import PipetteName
I think it works because `PipetteName` subclasses `str`. FWIW, ProtocolEngine has always been passing `PipetteName` values to the HW API (with a `# type: ignore`) and everything has behaved thus far

2022-08-30 20:27 UTC, mcous commented on shared-data/python/opentrons_shared_data/pipette/dev_types.py
> +class PipetteName(str, Enum):
That's my bad, did not realize the shared-data tests were failing 🫠. Let me see if I can scale back the `PipetteName` stuff a little bit to avoid the leakage into the Hardware API.

The value of the enum is that it work better as a public API; string literals mean API callers have to use magic strings (or define their own constants)

2022-08-30 20:27 UTC, mcous commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> -_FIXED_PIPETTE_ID: str = "P1KSV3120211118A01"
These are ok to remove, right? They look like testing holdovers

2022-08-30 20:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> -_FIXED_PIPETTE_ID: str = "P1KSV3120211118A01"
yeah definitely

2022-08-30 20:46 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> +from opentrons_shared_data.pipette.dev_types import PipetteName
Huh, how about that. I had definitely been assuming that enum concrete data type inheritance did not actually do that. Learn something new every day!

2022-08-30 21:23 UTC, mcous commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> +from opentrons_shared_data.pipette.dev_types import PipetteName
Reverted `PipetteName` to be a union of literals, named the `Enum` type something different

2022-08-30 21:26 UTC, sfoster1 approved these changes
Looks good to me!

2022-08-31 13:16 UTC, Laura-Danielle commented
Am I correct in assuming this PR closes: https://opentrons.atlassian.net/browse/RLIQ-112?

2022-08-31 16:44 UTC, mcous commented
@Laura-Danielle no, this PR does not intend to close RLIQ-112. There is no provision in this PR or the existing code for the 96 channel, and I assume 96-channel support would be a larger cross stack change.

Would you mind fleshing RLIQ-112 out with "acceptance criteria" and "implementation notes" sections? Reading through it (and other tickets in RLIQ-93) I'm a little unclear on what each one actually needs to be called completed.

2022-08-31 19:09 UTC, Laura-Danielle commented
> @Laura-Danielle no, this PR does not intend to close [RLIQ-112](https://opentrons.atlassian.net/browse/RLIQ-112). There is no provision in this PR or the existing code for the 96 channel, and I assume 96-channel support would be a larger cross stack change.
> 
> Would you mind fleshing [RLIQ-112](https://opentrons.atlassian.net/browse/RLIQ-112) out with "acceptance criteria" and "implementation notes" sections? Reading through it (and other tickets in [RLIQ-93](https://opentrons.atlassian.net/browse/RLIQ-93)) I'm a little unclear on what each one actually needs to be called completed.

Yep, I'll flesh it out a bit more. I really just intended for this ticket to encompass work needed in the protocol API to be able to support ot3 pipette models (we probably shouldn't call them gen3, but I don't think we have guidance from product yet about naming), mostly for the purpose of our sept deadline. There are separate tickets for supporting the 96 channel across the stack.

2022-08-31 19:37 UTC, SyntaxColoring approved these changes

2022-08-31 19:37 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/protocol_context.py
> +                      :py:class:`.Mount` or one of the strings `'left'`
Looks like an accidental search+replace change.

```suggestion
                      :py:class:`.types.Mount` or one of the strings `'left'`
```

2022-08-31 19:37 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/protocol_context.py
> +        :type mount: Mount or str
```suggestion
        :type mount: types.Mount or str
```

2022-08-31 19:37 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/validation.py
> +        )
```suggestion
    except ValueError as e:
        raise ValueError(
            f"Cannot resolve {pipette_name} to pipette, must be given valid pipette name."
        ) from e
```

2022-08-31 19:37 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/validation.py
> +            )
```suggestion
        except KeyError as e:
            # TODO(mc, 2022-08-25): create specific exception type
            raise ValueError(
                "If mount is specified as a string, it must be 'left' or 'right';"
                f" instead, {mount} was given."
            ) from e
```

2022-08-31 19:37 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/validation.py
> +def ensure_mount(mount: Union[str, Mount]) -> Mount:
Nice.

In general, if we have a validation function that's used by a whole bunch of public-facing API functions, do you think we should:

* Test the validation function's logic through the top-level function's unit tests. e.g. for every function that deals with a pipette name, test that it rejects an invalid valid pipette name string.
* Mock out the validation function any time we're unit testing a top-level function. Just test that the top-level function calls the mock correctly. Unit-test the validation function separately.
* Something else?

2022-08-31 20:11 UTC, mcous commented on api/src/opentrons/protocol_api/protocol_context.py
> +                      :py:class:`.Mount` or one of the strings `'left'`
It was intentional, but only because I misunderstood what was required for sphinx to understand these. Turns out either works, it just displays differently. Sphinx is weird.

Also, looks like #11379 broke the docs... so that's cool. Will revert docstring changes in this PR and leave docs fixups to another PR

2022-08-31 20:14 UTC, mcous commented on api/src/opentrons/protocol_api/validation.py
> +def ensure_mount(mount: Union[str, Mount]) -> Mount:
If it's a logic unit, and not a collaborator, I'd say the first option is preferable, even if it's reaching into `protocol_api.validation` to do so

Otherwise, if the "public facing API" object in question is a collaborator (like `ProtocolContext`), the second option is preferable

2022-08-31 20:59 UTC, merged