feat(app): wire up WizardHeader and StepMeter in ChangePipette
OpenTrons/opentrons-api pull request #11414
Opened 2022-08-30 19:15 UTC by jerader

closes RLIQ-57 partially closes RLIQ-110

# Overview

this PR wires up the `WizardHeader` component in the `ChangePipette` attach/detach flow. Also does a huge refactor to remove the `WizardHeader` and `ModalShell` from all the child components and into the parent component (`ChangePipette`) This also organizes `ChangePipette` so the deprecate components are organized away from the new components. There is now an easy split to be able to remove the deprecated components when we remove the FF

# Changelog

- refactor all child components to remove the `ModalShell` and `WizardHeader`, remove all associated components such as `currentStep`, `title` and `totalSteps`
- create `ChangePipette` test (still a WIP and might be completed in a followup PR when we remove the FF - this is partially addressing RLIQ-110)
- Change `SimpleWizardModal` to remove the `ModalShell` and `WizardHeader`, fix test and edit story to accommodate that change
- add deprecated tag to `AskForCalibrationBlockModal` because that wil be updated when we update the POC flow

# Review requests

- i sprinkled in a few comments already. A bit of the logic might be hard to read in the `ChangePipette` component, please call out anything that looks weird/seems confusing
- I smoke tested all 4 flows already (attach/detach single/multi pipettes) But would be nice to have a second pair of eyes on this

# Risk assessment

low

2022-08-30 19:19 UTC, jerader commented on app/src/organisms/ChangePipette/index.tsx
> +          pipetteName: wantedPipette != null ? wantedPipette.displayName : '',
this logic is weird. Basically the 1st half of the ternary statement is making sure that `wantedPipette` is always null, so the 2nd half means `wantedPipette` has to not be null. However, if you write line 233 as `pipetteName:  wantedPipette.displayName`, then you get a bunch of warnings in console because it doesn't like that `wantedPipette` can be undefined (which is impossible because of the 1st half of the ternary). This workaround removes those warnings but not sure how else to write this

2022-08-30 19:19 UTC, jerader commented on app/src/organisms/ChangePipette/index.tsx
> +            actualPipette?.displayName || wantedPipette?.displayName || '',
same issue here as above

2022-08-31 17:38 UTC, smb2268 requested changes
This looks great so far!

The refactor makes everything cleaner and will help us when we're adding support for GEN-3 pipettes in this file. I think it's okay if some of the logic to determine which steps to show for the instructions is a little complicated for now since we'll be increasing that complexity soon and can put more thought into how we want to handle it then.

Added a few suggestions but great work overall 🤩

2022-08-31 17:38 UTC, smb2268 commented on app/src/organisms/ChangePipette/index.tsx
> +import { WizardHeader } from '../../molecules/WizardHeader'
Let's organize these imports so that there is a clear demarcation between the ones we want to keep and remove post FF!

2022-08-31 17:38 UTC, smb2268 commented on app/src/organisms/ChangePipette/index.tsx
> +const TOTAL_STEPS = 3
Can we call this SINGLE_CHANNEL_STEPS instead of TOTAL_STEPS and then also create a constant for EIGHT_CHANNEL_STEPS?

2022-08-31 17:38 UTC, smb2268 commented on app/src/organisms/ChangePipette/index.tsx
> +  if (movementStatus !== null && movementStatus === MOVING) {
This can be `if (movementStatus === MOVING)`, no need for the null check since we aren't accessing a nested value.

2022-08-31 17:38 UTC, smb2268 commented on app/src/organisms/ChangePipette/index.tsx
> +          pipetteName: wantedPipette != null ? wantedPipette.displayName : '',
```suggestion
          pipetteName: wantedPipette?.displayName,
```

2022-08-31 17:38 UTC, smb2268 commented on app/src/organisms/ChangePipette/index.tsx
> +          pipetteName: wantedPipette != null ? wantedPipette.displayName : '',
Since we know `wantedPipette` will never be null, I think this is a safe alternative to adding another ternary. It should get rid of all of the errors!

2022-08-31 17:38 UTC, smb2268 commented on app/src/organisms/ChangePipette/index.tsx
> +            actualPipette?.displayName || wantedPipette?.displayName || '',
```suggestion
            actualPipette?.displayName ?? wantedPipette?.displayName,
```

2022-08-31 17:38 UTC, smb2268 commented on app/src/organisms/ChangePipette/index.tsx
> +        : attachWizardHeader
Can you refactor this so it isn't a nested ternary?

2022-08-31 17:38 UTC, smb2268 commented on app/src/organisms/ChangePipette/index.tsx
> +      //  for some reason when the pipette is leveling, the direction is detach BUT should be attach
This one is tricky for me to help debug without a robot but I'll try to look into it - maybe we don't have an `actualPipette.displayName` at that stage for some reason?

2022-08-31 17:38 UTC, smb2268 commented on app/src/organisms/ChangePipette/index.tsx
> +    const attachedWrong = Boolean(!success && wantedPipette && actualPipette)
Can we make this variable a little more specific? If this means we attached a pipette but not the correct one, maybe `attachedIncorrectPipette` or if it is more generic, maybe `attachmentFailure`

2022-08-31 17:38 UTC, smb2268 commented on app/src/organisms/ChangePipette/index.tsx
> +    const launchPOC = (): void => {
For the new `ConfirmPipette`, we no longer want to launch POC when the user wants to calibrate the pipette. We're now going to link them to `RobotSettings/calibration` and once the calibration dashboard is completed, we'll send them there.

2022-08-31 17:49 UTC, jerader commented on app/src/organisms/ChangePipette/index.tsx
> +          pipetteName: wantedPipette != null ? wantedPipette.displayName : '',
I had it as you suggested initially but I got an endless loop of warnings in console. For some reason, i18n doesn't know that `wantedPipette` will never be null?

2022-08-31 18:11 UTC, smb2268 commented on app/src/organisms/ChangePipette/index.tsx
> +          pipetteName: wantedPipette != null ? wantedPipette.displayName : '',
ohh so it's an i18n error and not TS? I'd try `wantedPipette?.displayName ?? ''` but if that doesn't work either it's fine to keep this as is!

2022-08-31 18:50 UTC, jerader commented on app/src/organisms/ChangePipette/index.tsx
> +          pipetteName: wantedPipette != null ? wantedPipette.displayName : '',
oh yup that fixes it! thanks!

2022-08-31 21:55 UTC, smb2268 approved these changes
Updates lgtm! just one final comment :rocket::rocket:

2022-08-31 21:55 UTC, smb2268 commented on app/src/molecules/SimpleWizardModal/index.tsx
> -import { WizardHeader } from '../WizardHeader'
Since this is no longer a modal, can we change the name to `SimpleWizardBody`?

2022-09-01 00:24 UTC, merged