fix(api): Disallow uploading a protocol with non matching references
OpenTrons/opentrons-api pull request #11418
Opened 2022-08-31 17:01 UTC by TamarZanzouri

# Overview

Closes https://opentrons.atlassian.net/browse/RSS-81.
Disallow uploading a protocol when referencing a none existed model Id.

# Changelog

- Added validation method to protocol_reader

# Review requests

1. should I add more validations?
2. is the code clear? 
3. tests sufficient?   

# Risk assessment

Medium. added another step when uploading a protocol.

2022-08-31 17:02 UTC, TamarZanzouri commented on api/src/opentrons/protocol_reader/protocol_reader.py
> +            if isinstance(role_analysis.main_file.data, ProtocolSchemaV6):
should I move this to the validation method?

2022-08-31 17:09 UTC, TamarZanzouri commented on api/src/opentrons/protocol_reader/protocol_reader.py
> +            if isinstance(role_analysis.main_file.data, ProtocolSchemaV6):
should I check against schema version instead of type?

2022-08-31 18:51 UTC, laviera commented on api/src/opentrons/protocol_reader/protocol_reader.py
> +            if isinstance(role_analysis.main_file.data, ProtocolSchemaV6):
@mcous ^^^ - What do u think here ?

2022-08-31 21:49 UTC, SyntaxColoring reviewed
Depending on what the rest of the group thinks, this doesn't necessarily need to happen in this PR, but for the future...

I think a good principle for us to follow here is "parse, don't validate." In this PR, we're doing this:

1. The client uploads a JSON protocol through `POST /protocols`.
    1. With Pydantic, the server makes sure that it's a structurally correct JSON protocol, and parses it into Python objects.
    2. `ProtocolReader` makes sure that the equipment `id`s are semantically correct. **This is the code that you're adding in this PR.**
2. The client creates a run for the protocol with `POST /runs`.
    1. `ProtocolRunner` and `JsonTranslator` read parsed Pydantic objects and convert them to `ProtocolEngine` objects. **This is where the 500 error was happening before. It should no longer 500 because of the validation you've added above.**
3. The client starts the run.

But if we parse instead of validate, we could have this:

1. The client uploads a JSON protocol through `POST /protocols`.
    1. With Pydantic, the server makes sure that it's a structurally correct JSON protocol, and parses it into Python objects.
    2. **`ProtocolReader` translates the JSON commands into Protocol Engine commands. 
In the process, it naturally verifies that the equipment IDs are semantically correct.** It stores the translated Protocol Engine commands in-memory and passes them along.
2. The client creates a run for the protocol with `POST /runs`.
    1. `ProtocolRunner` loads the **pre-translated** commands into the `ProtocolEngine`. Since they have already been translated, there is no real work to do here, so this becomes more robust.
3. The client starts the run.

We can also take things the other way:

1. The client uploads a JSON protocol through `POST /protocols`.
    1. With Pydantic, the server makes sure that it's a structurally correct JSON protocol, and parses it into Python objects.
    2. **No semantic validation of equipment IDs is done at this point.**
2. The client creates a run for the protocol with `POST /runs`.
    1.  **Nothing is done at this point.**
4. The client starts the run.
   1. **At this point, `JsonTranslator` converts JSON objects to Protocol Engine objects.**
   2. If there is a problem with an equipment ID, it becomes a *run error* and gets placed in `run.errors` for the client to retrieve over HTTP.

This second option would expose the error pretty late. But, it would expose it in a nice API-blessed way. And it's conceptually consistent with how we handle semantic errors in *Python* protocols: we let them fail at runtime, and make the client consult a *protocol analysis* if it wants to detect them earlier.

2022-08-31 21:54 UTC, SyntaxColoring commented
Another totally different approach would be to try out [Pydantic validators](https://pydantic-docs.helpmanual.io/usage/validators/).

2022-09-01 18:01 UTC, mcous requested changes, later dismissed
I think this is a good first pass, but needs some structural changes to ensure it's well tested and a scalable solution.

Separately, I, too, would be curious as to what this would look like if it was baked into the Pydantic model itself (I think we talked about this briefly in person). A JSON protocol is semantically invalid if it misuses equipment identifiers in this way, so I think a convincing argument could be made that baking it into the existing model validation makes sense

2022-09-01 18:01 UTC, mcous commented on api/src/opentrons/protocol_reader/protocol_reader.py
> +                )
`ProtocolReader` is a collaborator, but this is non-trivial logic. This logic should be moved to a dependency rather than hung off a static method

2022-09-01 18:01 UTC, mcous commented on api/tests/opentrons/protocol_reader/test_protocol_reader.py
> +async def test_json_protocol_error(
This test is heavily mocked but tests non-trivial logic, which means the mocks compromise the effectiveness of the important logic checking. This is a signal that my comment above applies: this needs to be a separate dependency, not a part of the `ProtocolRunner`

2022-09-01 18:01 UTC, mcous commented on api/src/opentrons/protocol_reader/protocol_reader.py
> +                    f"missing {prop_name} in referencing parent data model."
I think this error message needs to be a lot more detailed to be useful. It should note:

- We attempted to read what looked like a JSON protocol
- Which specific command in the protocol list was invalid
- What specific equipment ID was found in the command and missing in the top-level equipment fields

2022-09-01 18:01 UTC, mcous commented on robot-server/tests/integration/http_api/protocols/test_v6_json_upload_fail.tavern.yaml
> +test_name: Upload, analyze, delete basic_transfer_standalone protocol.
In the interest of making our robot-server test suite run faster, I think there's an argument to be made to not add another integration test for this. **I'm curious what other folks think**

If our unit tests (mocked and otherwise) validate that the dependencies are all in place and that `ProtocolFilesInvalid` errors are mapped to 422 responses, then our existing integration tests already validate that everything is wired up properly.

2022-09-01 18:01 UTC, mcous commented on shared-data/protocol/fixtures/6/simpleV6_fail.json
> +{
This fixture file is way larger than it needs to be to create the kind of failure we're testing for. If we decide to keep the tavern test, could this be cut down?

2022-09-06 20:19 UTC, TamarZanzouri commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +    @validator("commands", always=True)
I can also add the other fields we are checking against to the validator decorator.

2022-09-06 21:24 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +    @validator("commands", always=True)  # noqa: C901
Is `always=True` necessary? From the [docs](https://pydantic-docs.helpmanual.io/usage/validators/#validate-always), it sounds like this makes the validator run when no value is provided to commands. But I don't think we need to do that?

2022-09-06 21:24 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +    def validate_commands(
Does this still work if we make it a private method, like `_validate_commands()`?

2022-09-06 21:24 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +                    )
A couple of things about these `if`-statements:

* `command.params.pipetteId` will evaluate to `False` if `pipetteId` is the empty string, accidentally skipping validation. Let's use `command.params.pipetteId is not None` instead.
* `"pipettes" in values` seems iffy to me. If I understand Pydantic correctly, [it validates fields in order of declaration](https://pydantic-docs.helpmanual.io/usage/validators/#:~:text=Validation%20is%20done%20in%20the%20order%20fields%20are%20defined), so the `pipettes` field *should* always exist here. If it doesn't, that's a bug, and we shouldn't hide it by skipping validation. So I think we should remove the `"pipettes" in values` check.

   For `modules` and `liquids`, this gets more tricky because those fields aren't guaranteed to be present. But if one of those fields isn't present, we *definitely* want to raise a validation error. If there's a `loadModule` command (with a `moduleId`), but there is no top-level `modules` object, that should be a validation error.
* This might be stylistic, but using `set`s feels a little weird to me because we're only dealing with one object at a time.

All together, I would write this as:

```python
if command.params.pipetteId:
    if "pipettes" not in values:
        # No top-level `pipettes` field.
        # For `pipettes` in particular, this isn't actually possible,
        # but it is possible for `modules` and `liquids`.
        raise ValueError("...")
    elif command.params.pipetteId not in values["pipettes"].keys():
        # Top-level `pipettes` field exists, but is missing this specific pipette ID.
        raise ValueError("...")
```

Or, more succinctly:

```python
if command.params.pipetteId:
    if ("pipettes" not in values) or (command.params.pipetteId not in values["pipettes"].keys()):
        raise ValueError("...")
```

2022-09-06 21:33 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +                    )
Or maybe even better:

```python
pipette_ids = set(values["pipettes"].keys()) if "pipettes" in values else set()
# ditto for module_ids, etc.

for command in value:
    if command.params.pipetteId is not None and command.params.pipetteId not in pipette_ids:
        raise ValueError("...")
    # ditto for module_ids, etc.
```

2022-09-07 17:15 UTC, TamarZanzouri commented
tested this with a dev server. uploading an invalid json v6 protocol ends with a `422 Unprocessable Entity`. The exception is caught in the protocol_reader and propagates the error "JSON file ref_fail.json did not match a known Opentrons format".

2022-09-12 17:30 UTC, SyntaxColoring reviewed
Some final notes, but this looks great to me.

-----

> tested this with a dev server. uploading an invalid json v6 protocol ends with a 422 Unprocessable Entity.

Nice.

> The exception is caught in the protocol_reader and propagates the error "JSON file ref_fail.json did not match a known Opentrons format".

In another PR, we might want to reconsider [this code](https://github.com/Opentrons/opentrons/blob/7e61239ab85b5a5b760d84ae6ee588f417d70b61/api/src/opentrons/protocol_reader/file_reader_writer.py#L73-L77) so that the nice messages you've added here propagate all the way up. I wouldn't do it in this PR, though; I think this PR is doing its job solidly.

2022-09-12 17:30 UTC, SyntaxColoring commented on shared-data/protocol/fixtures/6/multipleTipracks.json
> -        "pipetteId": "c235a5a0-0042-11ec-8258-f7ffdf5ad45",
Haha, nice catch.

2022-09-12 17:30 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +    commands: List[Command]
Might be worth a comment:

```suggestion
    # commands must be after pipettes, labware, etc. for its @validator to work.
    commands: List[Command]
```

2022-09-12 17:30 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +        for command in value:
```suggestion
        for index, command in enumerate(value):
```

See my below suggestion about changing the error messages to include the command's index, not just its type.

2022-09-12 17:30 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +                )
I suggest rephrasing this like:

```suggestion
                raise ValueError(
                    f"{command.commandType} command at index {index}"
                    f" references ID {command.params.pipetteId},"
                    f" which doesn't exist."
                )
```

* I removed the note "There seems to be a problem with the uploaded json protocol." I think the context from which this exception is raised—parsing a JSON document into a `ProtocolSchemaV6` object—will make that clear. Also, we don't necessarily know at this level that the protocol was uploaded. We could be parsing a local file.

  I know @mcous [suggested](https://github.com/Opentrons/opentrons/pull/11418#discussion_r960954241) including this note in a prior comment, but that was when this exception was being raised from a different place.

  If anybody else feels strongly the other way,  feel free to add the note back in.
* I added the command's index, in case there are many similar commands.
* I rephrased the "missing [id] in referencing object" part to try to clarify that the top-level `pipettes` object does not have something that this command requires. Otherwise, it sounds like this command is accidentally omitting something.

Same suggestion for the other `raise`s, of course.

2022-09-12 17:30 UTC, SyntaxColoring commented on shared-data/python/tests/protocol/test_protocol_schema_v6.py
> +    print(input_commands)
```suggestion
```

Looks like a stray `print()` left over from debugging?

2022-09-12 17:30 UTC, SyntaxColoring commented on shared-data/python/tests/protocol/test_protocol_schema_v6.py
> +    print(f"file name {defpath}")
```suggestion
```

Looks like stray `print()`s left over from debugging?

2022-09-12 17:30 UTC, SyntaxColoring commented on shared-data/python/tests/protocol/test_protocol_schema_v6.py
> +                ),
Right now, some test parametrizations have 2 commands as input and others have 3. For consistency, I suggest either:

1. Use just one single command—the command that has the bad ID—in each test parametrization.
2. Use one command of each type—a `loadLabware`, a `loadPipette`, a `loadLiquid`, and a `loadMdule`—in each test parametrization.

Personally, I'd do (1). We have other tests that verify that valid commands can be parsed correctly. So we can focus on invalid commands here.

2022-09-12 18:39 UTC, TamarZanzouri commented
Spoke to @mcous about propagating this. He mentioned we might need to update the package for this to happen so this will need to wait for 6.2 release. 

> > The exception is caught in the protocol_reader and propagates the error "JSON file ref_fail.json did not match a known Opentrons format".
> 
> In another PR, we might want to reconsider [this code](https://github.com/Opentrons/opentrons/blob/7e61239ab85b5a5b760d84ae6ee588f417d70b61/api/src/opentrons/protocol_reader/file_reader_writer.py#L73-L77) so that the nice messages you've added here propagate all the way up. I wouldn't do it in this PR, though; I think this PR is doing its job solidly.

2022-09-12 18:59 UTC, SyntaxColoring approved these changes
Code looks great to me, thanks! I'm glad we tried a Pydantic validator here. I think it turned out well.

As @sanni-t suggested in Slack:

> I think there’s a good value in getting into 6.1 since this release is also the first time PD will be using schema v6. Having the validation added by this PR would be quite useful.
>
> I understand it handles improbable cases so if the PR needs more work then we can target it to edge. But if it’s ready to merge by eod, then I think we can target the merge to 6.1.0. We won’t be cutting the next alpha until tomorrow anyway

This looks ready to me, so let's retarget it to 6.1.0, assuming there are no merge conflicts.

2022-09-14 21:36 UTC, mcous approved these changes
Lovely!

2022-09-16 14:10 UTC, TamarZanzouri commented
Was merged to 6.1.0 release branch by [this](https://github.com/Opentrons/opentrons/pull/11457#pullrequestreview-1110743577) PR.

2022-09-20 13:43 UTC, merged