feature(hardware-control): add api function for setting the gripper jaw width
OpenTrons/opentrons-api pull request #11435
Opened 2022-09-06 20:23 UTC by ryanthecoder

# Overview
This PR adds an  api method to set a gripper jaw to a specific width
* It adds gripper jaw min and max to the shared data config
* it adds a can message for moving the gripper a specific distance
* it converts the jaw width request to a linear motion request that tells the gripper jaw motor to move a specific number of micrometers

# Changelog

Add a brushed motor linear move request to can messages
connect the can messages up through the ot3-api
add gripper jaw widths to the shared data config

# Review requests

# Risk assessment
low (new feature)

2022-09-06 21:51 UTC, sfoster1 approved these changes
This looks good to me. Something makes me  feel slightly weird about the way the jaw sizes are defined in config, but we can figure it out as time goes by.

2022-09-07 16:40 UTC, ahiuchingau requested changes
Logic looks good to me!

I think we should use `mm` in the api and let the hardware take care of distances in `um`.

2022-09-07 16:40 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/ot3api.py
> +    async def jaw_width(self, jaw_width_um: int) -> None:
Could we rename `jaw_width` and `_jaw_width` to something that starts with a verb, following the format of the other commands? Like `hold_jaw_width` for example?

2022-09-07 16:40 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/ot3api.py
> +    async def jaw_width(self, jaw_width_um: int) -> None:
We should stick with using `mm` here, and only convert it `um` when we construct the CAN message.

2022-09-21 15:52 UTC, ahiuchingau approved these changes
Looks great to me! 

Just left some nits; feel free to ignore if it actually makes more sense to keep those values in `um` instead!

2022-09-21 15:52 UTC, ahiuchingau commented on api/src/opentrons/config/gripper_config.py
> +    jaw_sizes_um: Dict[str, int]
Nit: could we maybe use mm here?

2022-09-21 15:52 UTC, ahiuchingau commented on shared-data/gripper/schemas/1.json
> +    "jawSizes_um": {
nit: use mm?

2022-09-21 15:52 UTC, ahiuchingau commented on shared-data/python/opentrons_shared_data/gripper/dev_types.py
> +                jaw_sizes_um=data["jawSizes_um"],
same as above

2022-09-22 19:46 UTC, merged