updated test_move_to_coordinates
OpenTrons/opentrons-api pull request #11444
Opened 2022-09-08 14:53 UTC by caila-marashaj

This pr moves the `move_to_coordinates` method into the `MovementHandler` class, and keeps the `MoveToCoordinatesImplementation` command intact. 

The `MoveToCoordinatesImplementation` already requires a `MovementHandler` object, and shares a couple of the same input parameters. Moving this method inside `MovementHandler` will hopefully make it simpler for future protocol engine actions to use the `move_to_coordinates` logic as well as the other movement methods.

2022-09-08 15:30 UTC, SyntaxColoring requested changes
Nice, this change makes sense to me.

2022-09-08 15:30 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_engine/commands/test_move_to_coordinates.py
> -    assert result == MoveToCoordinatesResult()
We'll need to rework these tests a bit to match the refactor in the production code.

* In the new `test_move_to_coordinates.py`, or all of the stuff above line 85 can be deleted, because it was setting up mocks for the old test's `decoy.verify()`.
* The old test's  `decoy.verify()` was testing that `hardware_api.move_to()` was called in the correct sequence. Nothing is testing that now, since you've moved the logic to `MovementHandler`; we're only testing that the method in `MovementHandler` was called correctly, not that it itself did the correct thing. We'll need to add a new test for this in `test_movement_handler.py`. It will mostly be the same as the code you're deleting here (see the bullet point above), but the parameters will be different because it accepts four separate arguments instead of a single `MoveToCoordinatesParams`.

2022-09-09 00:54 UTC, TamarZanzouri approved these changes
Changes look good to me :-)

2022-09-09 13:54 UTC, SyntaxColoring approved these changes
Thanks!

2022-09-09 14:29 UTC, merged