refactor: environment specification for python
OpenTrons/opentrons-api pull request #11469
Opened 2022-09-15 20:58 UTC by sfoster1

Environments are directories containing a bare minimum of infrastructure
to define an execution environment for our python stack. There are five:
- dev, for us running tests locally; you'd point your IDE at this.
- app, for the bundled offline analysis stack
- ot2, for the ot-2
- two for the ot-3, one for update server and one for robot server

By specifying environments that we deploy to rather than test
environments for individual projects, we can drastically simplify
everything and more easily provide testing of shared packages across
multiple projects.

We can integrate these environments into projects by changing their
makefiles to use the new $(run) makefile function.

This way, everything gets to stay locked!

2022-09-19 18:25 UTC, caila-marashaj commented on api/Makefile
> +	$(call python,app) -m mypy src --exclude=.*ot3.*
I just put a pr up with a similar change before I saw your branch. I think mine can just be deleted if you're going to merge this, right?

2022-09-23 19:28 UTC, y3rsh requested changes
Fix

2022-09-23 19:28 UTC, y3rsh commented on .github/actions/python/setup-all-environments/action.yaml
> +    "Cache the pipenv virtual environments"
```suggestion
    "Cache the pipenv virtual environments."
```

2022-09-23 19:28 UTC, y3rsh commented on .github/workflows/api-test-lint-deploy.yaml
> +        uses: './.github/actions/python/setup-all-environments' # already built above for lint so should cache hit and be fast
```suggestion
        uses: './.github/actions/python/setup-all-environments' 
```

2022-09-23 19:28 UTC, y3rsh commented on Makefile
>  NOTIFY_SERVER_DIR := notify-server
Move down.

2022-09-23 19:28 UTC, y3rsh commented on api/Makefile
> +sphinx_build := $(call pipenv,dev) run sphinx-build -W --keep-going
```suggestion
sphinx_build := $(call pipenv,app) run sphinx-build -W --keep-going
```

2022-09-23 19:37 UTC, y3rsh approved these changes

2022-09-23 21:27 UTC, sfoster1 commented on api/Makefile
> +	$(call python,app) -m mypy src --exclude=.*ot3.*
I think so yeah

2022-09-23 21:27 UTC, sfoster1 reviewed
@y3rsh looks like some of these checks are low-key failing

2022-09-23 21:29 UTC, sfoster1 commented
Aside from that t looks really solid, not that I can approve it since I opened it :)

2022-09-23 21:36 UTC, y3rsh commented
> @y3rsh looks like some of these checks are low-key failing

I will re-run/investigate first thing Monday.

2022-09-26 16:54 UTC, mcous reviewed
This is a really positive step for our Python setups! It does, however, make some important day-to-day developer experience slower and more painful, though, and I'd like to figure it out before we merge.

Problem:

It should be easy and fast to run `lint` and `test` when developing locally.

Hypothesis:

The `dev` environment is good enough for local testing / linting / etc. as long as specific environments are used in CI and a local user can opt into the  specific environments

Proposal:
- By default, all (or most) dev tasks should run in the `dev` environment
- The environment that a given task is run in can be changed via an environment variable for both local users and for CI

So, for example, if we look at `make test` in `robot-server`:

```make
.PHONY: test
test:
	$(call pytest,ot-2) $(tests) $(test_opts)
	$(call pytest,ot-3/robot-server) $(tests) $(test_opts)
```

On my (modern, M1) machine, this takes more than 6 minutes to run. I run this test suite before every push, so this slowdown is really frustrating.

Instead, I'd like to see something more along these lines:

```make
# maybe in python.mk or somewhere common
OT_PYTHON_ENV ?= dev

# ...

.PHONY: test
test:
	$(call pytest,$(OT_PYTHON_ENV)) $(tests) $(test_opts)
```

...and **in CI**, we spec something like:

```yaml
- name: robot-server tests on OT-2
  run: make -C robot-server test OT_PYTHON_ENV=ot-2

- name: robot-server tests on OT-3
  run: make -C robot-server test OT_PYTHON_ENV=ot-3/robot-server
```

There's also a set of solutions here that I'm down for involve defining our makefiles so these tests in different environments can run concurrently, but the robot-server tests suite certainly doesn't support this yet due to lack of isolation. It seems like `api/Makefile` in this PR is closest to supporting this sort of flow

2022-09-26 16:54 UTC, mcous commented on environments/dev/Pipfile
>  anyio = "==3.3.0"
Are any of these "production" dips required to be spec'd here in the `dev` Pipfile? Is `Pipenv` smart enough to lock the sub-dependencies from the `setup.py` declarations?

2022-09-26 16:54 UTC, mcous commented on scripts/python.mk
> +pipenv_envvars := SETUPTOOLS_ENABLE_FEATURES=legacy-editable $(and $(CI),PIPENV_IGNORE_VIRTUALENVS=1)
Is this `SETUPTOOLS_ENABLE_FEATURES=legacy-editable` needed given the `export SETUPTOOLS_ENABLE_FEATURES := legacy-editable` directly above?

2022-09-26 16:54 UTC, mcous commented on environments/dev/Pipfile
> -opentrons-hardware = { editable = true, path = "./../hardware" }
Why isn't `opentrons-hardware` in the development environment?

2022-09-26 19:00 UTC, y3rsh commented on environments/dev/Pipfile
>  anyio = "==3.3.0"
You have to pin some since they are ranges in setup.py (like `typing-extensions` and `numpy`) or `pipenv` will lock a version above the robot (as happens in the app environment).  So for clarity it is good to pin them all?

2022-09-26 19:06 UTC, y3rsh commented on scripts/python.mk
> +pipenv_envvars := SETUPTOOLS_ENABLE_FEATURES=legacy-editable $(and $(CI),PIPENV_IGNORE_VIRTUALENVS=1)
I wondered the same thing.  I will take out the export, I think it getting put in the logs everywhere is more helpful.

2022-09-26 19:08 UTC, y3rsh commented on scripts/python.mk
> +pipenv_envvars := SETUPTOOLS_ENABLE_FEATURES=legacy-editable $(and $(CI),PIPENV_IGNORE_VIRTUALENVS=1)
Oh wait the export may be getting used in other things, not just the pipenv command.

2022-09-26 20:50 UTC, mcous commented on environments/dev/Pipfile
>  anyio = "==3.3.0"
I would argue that that's absolutely fine in the dev environment. It can be CI's job to make sure that tests pass when run against the actual locked production dependencies, and we can allow the dev environment to be a much more simple setup.

For me the value of locking the dev environment is _not_ that it matches prod exactly, which we know is impossible given our different prod environments! The value for the dev environment is that it is _compatible_ with our versioning requirements and that it's locked to _something_ such that the dev environment is reproducible.

2022-09-26 20:54 UTC, mcous commented on api/Makefile
> +	wait;
Would it be simpler to define this as such?

```make
.PHONY: lint
lint: black-check flake8 mypy-ot2 mypy-ot3
```

Then, to run concurrently:

```shell
make -j
```

2022-09-26 21:22 UTC, y3rsh commented on api/Makefile
> +	wait;
Well ya 🤣 I did not realize you could do that.

2022-09-27 02:45 UTC, y3rsh commented on scripts/python.mk
> +pipenv_envvars := SETUPTOOLS_ENABLE_FEATURES=legacy-editable $(and $(CI),PIPENV_IGNORE_VIRTUALENVS=1)
Removed to rely on the export and not having any issues.

2022-09-27 13:03 UTC, y3rsh commented on environments/dev/Pipfile
>  anyio = "==3.3.0"
I will simplify dev.

2022-09-27 13:03 UTC, y3rsh commented on environments/dev/Pipfile
> -opentrons-hardware = { editable = true, path = "./../hardware" }
Adding.

2022-10-03 15:22 UTC, Laura-Danielle reviewed
Have a few small comments/questions, but otherwise this refactor looks really good to me. In general, would be great to not have our timeout(s) increase if we can help it.

2022-10-03 15:22 UTC, Laura-Danielle commented on .github/workflows/js-check.yaml
> +      - '**/*.y*ml'
Is there a file type that's not `yaml`, or was the asterisk a typo?

2022-10-03 15:22 UTC, Laura-Danielle commented on .github/workflows/notify-server-lint-test.yaml
> +    timeout-minutes: 30
Is there a way to keep the timeouts the same, or do we expect these tests to take longer in general? We already have to wait an annoyingly long time for CI to pass sometimes.

2022-10-03 15:22 UTC, Laura-Danielle commented on Makefile
> +	$(MAKE) -C $(API_DIR) test-app
Can the `hardware` project tests not run on windows?

2022-10-03 15:22 UTC, Laura-Danielle commented on api/Makefile
> +	$(call python,ot-2) -m mypy src --exclude=.*ot3.*
I already made the change in [this pr]([feat(api): Enable calibrate-pipette command for OT3 hardware (](https://github.com/Opentrons/opentrons/commit/d3d71e3e263b68d07c0c9fa775adfeddd2b4e406)), but I am not a huge fan of relying on "ot3" to be the label for separating out code. I much prefer that we rely more heavily on the pytest markers -- because it also makes things more readable. Right now it's quite tough to figure out which tests will run in both ot3/ot2 environments.

It doesn't have to be in this PR, but we really should audit/separate out which tests are truly dev specific and then probably have 3 test environments. One for ot2-only, one for ot3-only and one with shared tests (so tests that do not have a pytest marker).

2022-10-03 15:22 UTC, Laura-Danielle commented on api/src/opentrons/__init__.py
> +        except (ModuleNotFoundError, ImportError):
Why this change?

2022-10-03 15:22 UTC, Laura-Danielle commented on shared-data/python/Makefile
> +	$(call python,ot-3/robot-server) -m mypy opentrons_shared_data tests
there isn't a separate environment for shared-data on the ot3?

2022-10-03 15:22 UTC, Laura-Danielle commented on api/Makefile
>  .PHONY: test
Is it possible to have a separate directive for ot-3 as well, and then the `test` directive could run both? I've been forgetting to run the `test-ot2` command until getting to CI only to realize it will fail.

2022-10-03 15:22 UTC, Laura-Danielle commented on environments/ot-3/robot-server/Makefile
> +
Why are we sharing the `robot-server` env with both the `api` and `shared-data`? Aren't there quite a number of differing packages for each project?

2022-10-05 10:40 UTC, y3rsh commented on .github/workflows/js-check.yaml
> +      - '**/*.y*ml'
We have a few `.yml` files so was including in lint check now.

2022-10-05 10:56 UTC, y3rsh commented on .github/workflows/notify-server-lint-test.yaml
> +    timeout-minutes: 30
In general the caching makes things much faster, except when the cache is completely busted by a change to a `Pipfile*` or `setup.py`.  With no cache it can take 10-15 minutes to run the `setup-all-environments`.
For notify server this was probably unnecessary since it only runs on Ubuntu, I will change it back.  The workflows that have to run on Ubuntu and Mac needed the increase for the busted cache scenario.

2022-10-05 11:14 UTC, y3rsh commented on Makefile
> +	$(MAKE) -C $(API_DIR) test-app
Correct.  The `dev`,`ot2`, and `ot3` environments'  `Pipfile.lock` are locked against Mac and Linux.  `dev` does not pin any production 3rd party dependencies but the `ot2` and `ot3` are `==` of the package version on the robot.
We could get lucky and prebuilds of everything on Windows could match the robot but that does not happen.  At the least I believe there are no pre-builds for Windows of `python-can` at our version so `make setup` fails.

2022-10-05 11:16 UTC, y3rsh commented on api/Makefile
>  .PHONY: test
Yes

- [ ] @y3rsh fix this.

2022-10-05 11:28 UTC, y3rsh commented on api/Makefile
> +	$(call python,ot-2) -m mypy src --exclude=.*ot3.*
Completely agree.  create a story to not forget this.

2022-10-05 11:32 UTC, y3rsh commented on api/src/opentrons/__init__.py
> +        except (ModuleNotFoundError, ImportError):
@sfoster1 please field this 😊

2022-10-05 11:45 UTC, y3rsh commented on environments/ot-3/robot-server/Makefile
> +
I am not sure I understand the question.  The robot server on the ot3 will have the `api` (`opentrons`) and `shared-data` packages so must also have their 3rd party dependencies.  The `environments/ot-3/robot-server/Pipfile` is locking all the 3rd party dependencies at `==` the ot3 version.

2022-10-05 11:58 UTC, y3rsh commented on shared-data/python/Makefile
> +	$(call python,ot-3/robot-server) -m mypy opentrons_shared_data tests
That environment would not differ from `ot-3/robot-server` would it?  Wondering if there is a nuance of shared-data I am missing.

2022-10-19 18:23 UTC, y3rsh commented on .github/workflows/api-test-lint-deploy.yaml
>          run: make -C api test-ot2
change to have ot2 with coverage.

2022-11-04 19:39 UTC, y3rsh commented
Closing, content into #11682

2022-11-04 19:39 UTC, closed without merging