fix(hardware): avoid floating point rounding errors when calculating Block.final_speed
OpenTrons/opentrons-api pull request #11463
Opened 2022-09-14 21:34 UTC by andySigler

# Overview

Rounding errors would occasionally cause the `Block.final_speed` to be calculated as `NaN`. That is not desired.

# Changelog

Don't give `np.sqrt()` a negative number.

# Review requests

# Risk assessment

2022-09-14 22:18 UTC, ahiuchingau approved these changes

2022-09-14 22:19 UTC, ahiuchingau requested changes
Let's add some tests before we merge.

2022-09-15 13:07 UTC, sfoster1 commented
Yeah let's definitely add some tests for this.

It seems like this could happen when the block is decelerating all the way to 0, which should happen only when at least one moving axis has a `direction_change_max_speed_discontinuity` of 0, right? We should add a case like that to our property-based testing.

We also should probably log or alert on this value being too negative - we dont want to paper over a larger issue if it arises later.

2022-09-16 16:44 UTC, sfoster1 approved these changes
Nice work.

2022-09-20 16:08 UTC, ahiuchingau approved these changes

2022-09-20 17:22 UTC, merged