chore: 6.1.0 beta 1 release notes
OpenTrons/opentrons-api pull request #11466
Opened 2022-09-15 15:27 UTC by ecormany

# Overview

Updating release notes for beta 1.

# Changelog

- Added link and image for Heater-Shaker
- alpha 4 --> beta 1 everywhere

# Review requests

Get these merged to the feature branch before tagging beta 1.

# Risk assessment

Very low, just notes (although they do render in-app and we're adding an image for the first time).

2022-09-15 18:27 UTC, jerader commented
I am not sure if this should be included in bug fixes or if this is just a new feature. But I had a PR merge for `alpha.4` that adds an error banner to the module cards if the TC or H-S overall status errors. Previously, we had no visual indicator in the app letting users know that the module is in error status.

Here is the PR https://github.com/Opentrons/opentrons/pull/11382 and ticket RQA-190 for reference.

2022-09-16 14:37 UTC, mcous requested changes, later dismissed

2022-09-16 14:37 UTC, mcous commented on app-shell/build/release-notes.md
> +<p align="center"><img alt="Isometric view of the Opentrons Heater-Shaker Module GEN1" src="img/hs_with_pcr_adapter.png" width="300" /></p>
I'm almost certain this won't work. The image has to be hosted somewhere on the internet for this markdown to render properly. The currently installed app that's displaying this markdown will not have the image anywhere in its source code, so there's no way for this image path to work

2022-09-16 14:52 UTC, ecormany commented on app-shell/build/release-notes.md
> +<p align="center"><img alt="Isometric view of the Opentrons Heater-Shaker Module GEN1" src="img/hs_with_pcr_adapter.png" width="300" /></p>
Where does the markdown itself come from? It must pass from this repo to a stable URL at some point in the release process, right?

2022-09-16 14:58 UTC, ecormany commented on app-shell/build/release-notes.md
> +<p align="center"><img alt="Isometric view of the Opentrons Heater-Shaker Module GEN1" src="img/hs_with_pcr_adapter.png" width="300" /></p>
I'm guessing it would be bad form to use the `raw.githubusercontent.com` URL as the source, but it is "somewhere on the internet" 🙃

2022-09-19 15:08 UTC, ecormany commented on app-shell/build/release-notes.md
> +<p align="center"><img alt="Isometric view of the Opentrons Heater-Shaker Module GEN1" src="img/hs_with_pcr_adapter.png" width="300" /></p>
ok, going the github route since we're cutting alpha 5. if it's broken in any way, we can try another strategy or pull the image out before b1 and stable.

2022-09-19 19:42 UTC, shlokamin reviewed
the image in this PR is no longer being used right? since it's being hosted on gh

2022-09-19 20:01 UTC, ecormany commented
@shlokamin adding the image in a commit on this branch _is_ how it's publicly hosted. i guess commits are technically forever so if you removed the file and still pointed to that old commit it would still be there? but that seems confusing for future maintenance.

2022-09-21 19:54 UTC, shlokamin approved these changes
LGTM, if we end up not liking this we can make changes before we promote alpha 6

2022-09-21 20:07 UTC, merged