Move to start calibration position
OpenTrons/opentrons-api pull request #11478
Opened 2022-09-19 17:46 UTC by caila-marashaj

New command for moving the gantry before and after calibration. Parameter `CalibrationSetUpPositions` lets the user move either to the middle of the deck for starting to probe, or the front for putting on and taking off the probe attachment. I'm using Deck Slot 2 for the front, and Deck Slot 5 for the middle, can anyone just confirm that these deck slots are the correct ones for those positions?

2022-09-19 17:51 UTC, caila-marashaj commented on api/src/opentrons/protocol_engine/commands/calibration/calibration_set_up_position.py
> +            additional_min_travel_z=0,
How should this parameter be used? I put 0 in there temporarily, but I'm not sure what a reasonable value for this is

2022-09-20 14:01 UTC, Laura-Danielle requested changes
Have a few initial comments. Also, I know we kept changing what the command was actually going to do, but I thought we had landed on making a generalized "move to location" command.

We should probably have this command take in an enum of sorts to specify what location to actual move to i.e.:

1. probe position
2. attach/de-attach probe position

We can add in an optional slot param as well and default to center slot for the probe position specifically. Can pair on this if you want.

2022-09-20 14:01 UTC, Laura-Danielle commented on api/Makefile
> +	$(python) util/plot_session.py $(plot_type) $(plot_type).pdf
Accidental change here?

2022-09-20 14:01 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/commands/calibration/calibration_set_up_position.py
> +        return CalibrationSetUpPositionResult()
I think we want to return a position here, right?

2022-09-20 14:01 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/commands/calibration/calibration_set_up_position.py
> +        slot_center_deck = DeckPoint(x=slot_center.x, y=slot_center.y, z=slot_center.z)
Let's add a safety margin to the z component of the `slot_center_deck`. I think 3mm is probably OK for now.

2022-09-20 14:01 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/commands/calibration/calibration_set_up_position.py
> +            additional_min_travel_z=0,
Since this is an optional param, let's not set it and rely on `motion_planning/` to handle any arc movement z minimums -- which is what this is used for. You can check out `opentrons/motion_planning/` and `protocol_engine/state/motion.py` for further info.

2022-09-20 14:01 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/state/labware.py
> +        print("slot def =", slot_def)
accidentally left print statement here.

2022-09-20 14:04 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/calibration_set_up_position.py
> +CalibrationSetUpPositionCommandType = Literal["CalibrationSetUpPosition"]
```suggestion
CalibrationSetUpPositionCommandType = Literal["calibrationSetUpPosition"]
```

2022-09-20 14:07 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/calibration_set_up_position.py
> +    """Result data."""
```suggestion
    """Result data from the execution of a CalibrationSetUpPosition command."""
```

2022-09-20 14:08 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/calibration_set_up_position.py
> +from opentrons.protocol_engine.commands.pipetting_common import PipetteIdMixin
Can we add a space between opentrons import and external packages import?

2022-09-20 14:09 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/calibration_set_up_position.py
> +"""Home command payload, result, and implementation models."""
```suggestion
"""Calibration set up position command payload, result, and implementation models."""
```

2022-09-20 14:10 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/calibration_set_up_position.py
> +    commandType: CalibrationSetUpPositionCommandType = "CalibrationSetUpPosition"
```suggestion
    commandType: CalibrationSetUpPositionCommandType = "calibrationSetUpPosition"
```

2022-09-20 14:10 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/calibration_set_up_position.py
> +    commandType: CalibrationSetUpPositionCommandType = "CalibrationSetUpPosition"
```suggestion
    commandType: CalibrationSetUpPositionCommandType = "calibrationSetUpPosition"
```

2022-09-20 14:21 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibration_set_up_position.py
> +    with mock.patch.object(
you should use decoy stubbing here. https://mike.cousins.io/decoy/usage/when/
```suggestion
    decoy.when(state_view.labware.get_slot_center_position()).then_return(mock_deck_slot_center) 
```

2022-09-20 14:24 UTC, TamarZanzouri requested changes
Looks great! nice job! a few changes but overall looks great! let me know if you need help

2022-09-20 16:10 UTC, SyntaxColoring submitted a review, later dismissed

2022-09-20 16:10 UTC, SyntaxColoring commented on api/Makefile
> +	$(python) -m mypy -p tests
If the original code here didn't work, I have a hunch that's a side effect of adding `api/__init__.py`. (`api/__init__.py` shouldn't exist because that root `api` directory doesn't represent a Python package—the Python package is at `api/src/opentrons`.) Do things work if we revert all changes to this Makefile, and revert the creation of `api/__init__.py`?

2022-10-04 14:32 UTC, Laura-Danielle requested changes
This is looking really good! Let's pair on the last big change which is utilizing the `LabwareView` class to get the correct coordinates from the deck definition in shared-data.

2022-10-04 14:32 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +        CalibrationPositions.probe_position,
Let's make this a required parameter `Field(..., description=...)`

2022-10-04 14:32 UTC, Laura-Danielle commented on api/Makefile
> +	$(python) util/plot_session.py $(plot_type) $(plot_type).pdf
bump

2022-10-04 14:32 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +    result: Optional[MoveToLocationResult]
when would result be optional?

2022-10-04 14:32 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +        if self.value == 5:
We should use the `LabwareView` class from the protocol engine to get the initial slot coordinates and then apply our own offsets as necessary. `LabwareView` has the functions `get_slot_center_position` and `get_slot_definition` which will be very useful.

We can then be more agnostic about what robot we might be 'moving to'

2022-10-14 14:48 UTC, Laura-Danielle requested changes
Some more changes that should be made. We also need to test this on a robot before merging.

2022-10-14 14:48 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/execution/movement.py
> +    # async def get_gantry_position(self, pipette_id: str) -> Point:
Commented out function, what was the point of this?

2022-10-14 14:48 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/state/labware.py
> +        print("slot def =", slot_def)
Still have a print statement here.

2022-10-14 14:48 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +            return Point(x=float(10), y=float(0), z=float(3))
Why are these wrapped in floats? Also can we make these `DeckPoints` instead (see https://github.com/Opentrons/opentrons/pull/11567/files) where we're trying to avoid types from `hardware controller` or top level types.

2022-10-14 14:48 UTC, Laura-Danielle commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibration_move_to_location.py
> +    """Return a SavedPositionData object."""
As practice, we generally keep mock functions inside the test themselves if it's only being used by one test.

2022-10-14 14:48 UTC, Laura-Danielle commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibration_move_to_location.py
> +probe_position = SavedPositionData(
When you move the test functions, you can also move these global variables to be inside the test as well.

2022-10-17 16:12 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/__init__.py
> +    # calibration/MoveToLocation
```suggestion
    # calibration/moveToLocation
```

2022-10-17 16:13 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +MoveToLocationCommandType = Literal["MoveToLocation"]
```suggestion
MoveToLocationCommandType = Literal["calibration/moveToLocation"]
```

2022-10-17 16:13 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +    deck_slot: CalibrationPositions = Field(
```suggestion
    deckSlot: CalibrationPositions = Field(
```

2022-10-24 15:54 UTC, Laura-Danielle approved these changes
ty for your hard work on this! Excited to see it on the robot.

2022-10-24 16:21 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/__init__.py
> +
accidental extra space?

2022-10-24 16:29 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +            deck_center = self._state_view.labware.get_slot_center_position(
should we extract `self._state_view.labware.get_slot_center_position` before the if condition? not critical for this PR

2022-10-24 16:32 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +            current_position = await self._movement.save_position(
why do we need to call `self._movement.save_position` twice? it might be my misunderstanding

2022-10-24 16:51 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibration_move_to_location.py
> +    with mock.patch.object(movement, "save_position", mock_save_position):
I think we should use https://mike.cousins.io/decoy/usage/when/#returning-a-value here instead just for the sake of consistency with the other tests. I can explain if needed.

2022-10-24 16:52 UTC, TamarZanzouri requested changes
overall looks really good! thank you so much for all your hard work and testing :-). a few small comments and we are done!

2022-10-24 19:19 UTC, caila-marashaj commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +            current_position = await self._movement.save_position(
The first time is just in the case of the `attachOrDetach` position. If we're going here, the code currently maintains whatever height the z axis is at when calling the command, and sends the gantry to slot 2. The second call to `save_position()` saves the x, y, and z coordinates to return as the result.

This raises the question though- do we want to do this, or should we choose a z coordinate to send the mount to when attaching or detaching a pipette?

2022-10-25 18:11 UTC, caila-marashaj commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +            deck_center = self._state_view.labware.get_slot_center_position(
The params don't contain the actual `DeckSlotName` anymore, so we can create a variable that contains which `DeckSlotName` we want to use, but it isn't necessarily decreasing the size of the code

2022-10-25 19:00 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +            current_position = await self._movement.save_position(
We should not choose a z coordinate but rather let the hardware controller decide.

2022-10-25 19:03 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +            current_position = await self._movement.save_position(
Seems like `save_position` is the way to get the current position in the protocol engine. We need the current position to get the robot's current z value.

We call it twice. Once to get the robot's current z value and once to get the final position.

2022-10-25 19:09 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +    probe_position = "probe_position"
sorry for the back and forth about this. can we please change this to:
`PROBE_POSITION = "probePosition"`

2022-10-25 19:11 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibration_move_to_location.py
> +    ).then_return(probe_position)
nice!

2022-10-25 19:11 UTC, TamarZanzouri approved these changes
Amazing work! thank you so much! once the enum is fixed this is good to merge :-)

2022-10-26 14:10 UTC, TamarZanzouri commented
lgtm! once ci passes you can merge

2022-10-26 16:08 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/calibration/__init__.py
> +# param name and optional value
Stray development comment?

```suggestion
```

2022-10-26 16:08 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +from enum import Enum
Style nitpick: `pydantic` should go below the standard library stuff, [since](https://peps.python.org/pep-0008/#imports) it's a 3rd-party library.

```suggestion
from __future__ import annotations

from typing import TYPE_CHECKING, Type, Optional
from typing_extensions import Literal
from enum import Enum

from pydantic import BaseModel, Field
```

2022-10-26 16:08 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +    )
Does this field name and description make sense now that you have an enum with opaque location identifiers?

```json
{
   "commandType": "moveToLocation",
    "params": {"deckSlot": "attachOrDetach"}
}
```

Maybe `location` instead of `deckSlot`?

2022-10-26 16:08 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +            return DeckPoint(x=0, y=0, z=0)
This works, but it seems kind of funky to me that the offset within the deck slot is defined as part of the `CalibrationPositions` enum, whereas the deck slot that that offset belongs to is hard-coded inside `MoveToLocationImplementation.execute()`. It seems like they only make sense together, so they should both be in the same place.

I would put them both inside `MoveToLocationImplementation.execute()` for consistency with other Protocol Engine types, which generally don't have properties on them. (Not that I think there's anything wrong with a property like this, in principle.)

2022-10-26 16:08 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +class CalibrationPositions(str, Enum):
Style nitpick: I think enums are conventionally named for the singular (`CalibrationPosition`), not plural (`CalibrationPositions`).

2022-10-26 16:08 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +    positionId: str = Field(..., description="Deck Point position id")
If I'm reading this correctly, this will be whatever the client passed in as the `params.deckSlot` input field.

1. Why do we need this in `result`? The client can already access it at `params.deckSlot`.
2. If we do need it, why is it a `str`? Should it be your `CalibrationPositions` enum instead?

2022-10-26 16:08 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +        ..., description="Deck Point position after the move command has been executed"
Would this be clearer (and correct)?

```suggestion
        ..., description="Position in deck coordinates after this movement has been executed"
```

In order to clarify that these are global coordinates, not local coordinates relative to the deck slot or anything.

2022-10-26 16:08 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +            direct=True,
Just double-checking that you want this to be a direct movement without any kind of arcing to avoid labware, modules, or the trash bin.

2022-10-26 16:08 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +                pipette_id=params.pipetteId, position_id=params.deckSlot.value
This is partially an artifact of `save_position()` weirdness, but note that `position_id` doesn't actually matter here. Because you're only looking at `current_position.position`, and throwing away `current_position.id`.

Really, the `save_position()` method as it exists isn't a great fit for what you're doing here. It's doing too much. You need it to return the current location, and it's doing that, but it's also got this ID weirdness wrapped up in it. You certainly don't need to fix that in this PR, but I would consider passing `None` as `position_id` in order to simplify your code a little bit.

Same for `new_position`, below.

2022-10-26 16:08 UTC, SyntaxColoring commented on api/Makefile
> +	$(python) util/plot_session.py $(plot_type) $(plot_type).pdf
I would do:

```
git checkout origin/edge api/Makefile
git checkout origin/edge api/src/opentrons/protocol_engine/commands/__init__.py
```

To undo these stray formatting changes.

2022-10-26 17:28 UTC, merged