feat(api): Enable calibrate-pipette command for OT3 hardware
OpenTrons/opentrons-api pull request #11482
Opened 2022-09-19 20:13 UTC by TamarZanzouri

# Overview

closes https://opentrons.atlassian.net/browse/RLIQ-106.
this PR enables calibratePipette command in the protocol engine.
executing this command will take care of both deck calibration and pipette calibration. 

# Changelog

# Review requests

1. Did I miss any validations?
2. Does the validation method make sense in a new file?

# Risk assessment

Low. Introducing a new command that is only applicable for OT3. Will not be executed if not called.

2022-09-19 20:38 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_pipette.py
> +    errors: Optional[List[ErrorOccurrence]] = Field(
this feels redundant? we can get the errors from the StateSummery errors property or we let the errors bubble up

2022-09-19 20:44 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibrate_pipette.py
> +    subject = CalibratePipetteImplementation(hardware_api=ot2_api)
getting a linting error: error: `Argument "hcapi" to "calibrate_mount" has incompatible type "HardwareControlAPI"; expected "OT3API"  [arg-type]`. adding # type: ignore[arg-type] dosnet solve it?

2022-09-20 14:13 UTC, Laura-Danielle approved these changes
Overall, looks good to me. I think we just need to resolve the error handling stuff and the linter error you are getting.

2022-09-20 14:13 UTC, Laura-Danielle commented on api/tests/opentrons/protocol_engine/commands/conftest.py
> +def ot3_api(decoy: Decoy) -> OT3API:
can we call these fixtures `ot3_hardware_api` and `ot2_hardware_api` just so we're more specific about it?

2022-09-20 14:13 UTC, Laura-Danielle commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibrate_pipette.py
> +    subject = CalibratePipetteImplementation(hardware_api=ot2_api)
Can you resolve this by wrapping the execute command in a `try-except` and passing on execution if it receives a `HardwareNotSupported` error? Is the `isinstance` working as expected?

2022-09-20 14:13 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_pipette.py
> +    errors: Optional[List[ErrorOccurrence]] = Field(
I think we definitely don't want errors bubbling up directly from the hardware controller if we can avoid it b/c I was under the impression that the App has much nicer ways to handle errors returned from protocol engine. @b-cooper or @shlokamin, please correct me if I'm wrong here.

What types of errors does the `StateSummary` catch normally?

2022-09-20 14:13 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_pipette.py
> +        ensure_ot3_hardware(self._hardware_api)
Can we add a TODO about better determining how we handle OT-3 and/or OT-2 specific protocol engine commands?

2022-09-20 17:23 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibrate_pipette.py
> +    subject = CalibratePipetteImplementation(hardware_api=ot2_api)
I am raising the error from the validation method and letting in bubble up to the client

2022-09-20 17:47 UTC, SyntaxColoring requested changes, later dismissed

2022-09-20 17:47 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/__init__.py
> +    # calibration module command bundles
```suggestion
    # calibration command bundle
```

Since there's only one bundle of calibration commands.

2022-09-20 17:47 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/calibration/__init__.py
> +"""Calibration Module protocol commands."""
```suggestion
"""Calibration commands."""
```

I wouldn't mention "module" here because it might be confused with 

I would also just say "commands" instead of "protocol commands." They *are* protocol commands in the sense that they're just like any other command in Protocol Engine, but they're not supposed to appear in an actual protocol, so... 🤷

2022-09-20 17:47 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_pipette.py
> +CalibratePipetteCommandType = Literal["calibratePipette"]
Should these literals be `calibration/calibratePipette`, etc.?

2022-09-20 17:47 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_pipette.py
> +    errors: Optional[List[ErrorOccurrence]] = Field(
It is redundant to have an `errors: Optional[List[ErrorOccurrence]]` field. It's nearly exactly what a failed command is, with its `.error` field.

I think we need to identify the particular goals of error reporting here.

* Is there a specific, bounded set of conditions that a client should react and adapt to? Like: "a pipette isn't attached; attach one and try again"?
    * If so, we need to enumerate those conditions more specifically than the generic `ErrorOccurrence` type.
    * We can choose how to report those conditions (here, or via a failed command with an `.error`) based on what those conditions are, specifically. 
* Or do we just want this as a catch-all for "something unexpected happened, so the app should show some kind of error indicator to the user"?
    * If so, we should just use `.error` for this (instead of `params.errors` as currently written).

2022-09-20 18:33 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_pipette.py
> +CalibratePipetteCommandType = Literal["calibratePipette"]
really? I looked at a bunch of commands and I saw this is the convention. can you give me an example?

2022-09-20 18:37 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_pipette.py
> +CalibratePipetteCommandType = Literal["calibratePipette"]
nice catch!

2022-09-20 19:20 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_pipette.py
> +    errors: Optional[List[ErrorOccurrence]] = Field(
We agreed upon removing the error property from the command result. The UI will check if the command was successful. If not it will check the error field.

2022-09-20 19:21 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_pipette.py
> +            hcapi=self._hardware_api, mount=params.mount  # type: ignore[arg-type]
its this type ignore ok? this was added for the test case of an OT-2 api.

2022-09-22 16:03 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/errors/exceptions.py
> +class HardwareNotSupported(ProtocolEngineError):
To match Python convention and the convention of most of the other exceptions in this file, let's rename this `HardwareNotSupportedError`.

2022-09-22 16:03 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/validation.py
> +        raise HardwareNotSupported("This command is supported by OT3 Only.")
```suggestion
        raise HardwareNotSupported("This command is supported by OT-3 only.")
```

2022-09-22 16:03 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/validation.py
> +def ensure_ot3_hardware(hardware_api: HardwareControlAPI) -> OT3API:
This works, but for future reference, you could also implement this as a [type guard](https://mypy.readthedocs.io/en/stable/type_narrowing.html#user-defined-type-guards). I don't think there's any need to do that here, though.

2022-09-22 16:03 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_pipette.py
> +    mount: MountType = Field(..., description="Instrument mount to calibrate.")
I think I'm missing something conceptual about what's going on here, but:

The command is called `calibratePipette` but it's taking a `mount` as input. Are we calibrating a pipette, or a mount? (Maybe there's not a difference?)

Does the calibration behavior depend, in any way, on what kind of  pipette is currently attached to that mount? For example, does the gantry need to move to different places depending on whether a Single-Channel, 8-Channel, or 96-Channel pipette is attached? If so, maybe that means this should take a `pipetteId` instead of a `mount`?

2022-09-22 16:03 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/validation.py
> +"""Validation file for protocol engine."""
I don't have any better ideas right now, but organizationally, we should keep an eye on this file. `translate_mount_to_ot3_mount()` doesn't feel like validation to me.

2022-09-22 16:03 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/validation.py
> +def translate_mount_to_ot3_mount(mount: str) -> OT3Mount:
Can we change this to accept a `MountType` as its argument, instead of a `str`? Then we have one fewer dangerous conversion to worry about inside this function.

2022-09-22 16:03 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/validation.py
> +def ensure_ot3_hardware(hardware_api: HardwareControlAPI) -> OT3API:
Can we add a unit test for `ensure_ot3_hardware()`?

2022-09-22 16:03 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/validation.py
> +def translate_mount_to_ot3_mount(mount: str) -> OT3Mount:
Can we add a unit test for `translate_mount_to_ot3_mount()`?

2022-09-22 16:04 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_pipette.py
> +    mount: MountType = Field(..., description="Instrument mount to calibrate.")
Sorry, I missed Laura's walkthrough on this, so I'm missing some basic background info. Feel free to ignore me if you know better.

2022-09-22 16:07 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/validation.py
> +def ensure_ot3_hardware(hardware_api: HardwareControlAPI) -> OT3API:
I was debating if to use type guard for this. I can try changing it!

2022-09-22 16:07 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/validation.py
> +"""Validation file for protocol engine."""
I want to move this away! added it late last night :-)

2022-09-22 16:46 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_pipette.py
> +    mount: MountType = Field(..., description="Instrument mount to calibrate.")
Nope. We are leaving everything to the hardware controller to figure out. We just need to provide what mount we want to calibrate and the hardware controller will take care of placement/execution.

To be clear, though, we are still just "calibrating" the pipette. We just need to tell the hardware controller _which_ pipette to calibrate which is based on the mount. We already expect that by the time the user gets to the calibration flow, that they have the correct pipettes that they want to calibrate attached.

2022-09-22 20:04 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibrate_pipette.py
> +async def test_calibrate_pipette_implementation_wrong_hardware(
@SyntaxColoring we can probably remove this test now that I added a unit test

2022-09-22 20:18 UTC, Laura-Danielle approved these changes
Thanks for your hardwork and patience! This looks good to me, just one comment about translating between `OT3Mount` and `MountType`

2022-09-22 20:18 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/commands/ot3_translator.py
> +    return OT3Mount[MountType(mount).name]
You should be able to use the helper class method `from_mount` for the OT3Mount class. I think it's fine to add in `MountType` as a Union option in the `from_mount` method of OT3Mount.

2022-09-22 20:18 UTC, Laura-Danielle commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibrate_pipette.py
> +async def test_calibrate_pipette_implementation_wrong_hardware(
Well this is verifying that the calibration implementation will raise an exception if we try to execute it with an OT2 hardware controller. I think it's OK to keep it.

2022-09-22 20:27 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/ot3_translator.py
> +    return OT3Mount[MountType(mount).name]
So much better! thank you for this comment! @Laura-Danielle

2022-09-23 12:48 UTC, SyntaxColoring reviewed
Are the `Pipfile.lock` changes intended to fix the CI errors? If so, I don't think the problem has anything to do with a wrong Pipfile or a wrong environment setup.

The CI errors look like PR #9605 catching a legitimate problem: this PR will not work on an OT-2 because it tries to import `opentrons_hardware`, which only exists on OT-3s.

```
tests/opentrons/conftest.py:50: in <module>
    from opentrons.protocol_api import (
src/opentrons/protocol_api/__init__.py:23: in <module>
    from .create_protocol_context import create_protocol_context
src/opentrons/protocol_api/create_protocol_context.py:15: in <module>
    from opentrons.protocol_engine import ProtocolEngine
src/opentrons/protocol_engine/__init__.py:8: in <module>
    from .create_protocol_engine import create_protocol_engine
src/opentrons/protocol_engine/create_protocol_engine.py:5: in <module>
    from .protocol_engine import ProtocolEngine
src/opentrons/protocol_engine/protocol_engine.py:10: in <module>
    from .commands import Command, CommandCreate
src/opentrons/protocol_engine/commands/__init__.py:21: in <module>
    from . import calibration
src/opentrons/protocol_engine/commands/calibration/__init__.py:3: in <module>
    from .calibrate_pipette import (
src/opentrons/protocol_engine/commands/calibration/calibrate_pipette.py:12: in <module>
    from ..validation import ensure_ot3_hardware
src/opentrons/protocol_engine/commands/validation.py:2: in <module>
    from opentrons.hardware_control.ot3api import OT3API
src/opentrons/hardware_control/ot3api.py:31: in <module>
    from .backends.ot3utils import get_system_constraints
src/opentrons/hardware_control/backends/ot3utils.py:14: in <module>
    from opentrons_hardware.firmware_bindings.constants import NodeId
E   ModuleNotFoundError: No module named 'opentrons_hardware'
=========================== short test summary info ============================
ERROR  - ModuleNotFoundError: No module named 'opentrons_hardware'
```

Something in this import chain needs to be a conditional import so that `opentrons_hardware` isn't imported when this is running on an OT-2.

I don't know how we've been handling this so far, but I imagine it could either be conditional under `if TYPE_CHECKING`, or under something like `if ff.enable_ot3_hardware_controller()`.

2022-09-24 03:05 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibrate_pipette.py
> +    if ot3_hardware_api:
not sure about this. when testing against ot-2 `ot3_hardware_api` is None and this test fails.

2022-09-28 18:42 UTC, laviera approved these changes

2022-09-30 20:13 UTC, merged