chore(release): bump to v6.1.0 alpha.5
OpenTrons/opentrons-api pull request #11481
Opened 2022-09-19 19:57 UTC by shlokamin

# Overview

# Changelog

# Review requests

# Risk assessment

2022-09-19 20:15 UTC, laviera requested changes

2022-09-19 20:15 UTC, laviera commented on shared-data/CHANGELOG.md
> +
should this be removed ... the fix and the revert

2022-09-19 20:59 UTC, shlokamin commented on shared-data/CHANGELOG.md
> +
removed!

2022-09-20 13:39 UTC, sanni-t approved these changes
🏁

2022-09-20 14:11 UTC, laviera approved these changes

2022-09-20 14:13 UTC, merged