feat(thermocycler-gen2): update hardware controller
OpenTrons/opentrons-api pull request #11490
Opened 2022-09-22 02:33 UTC by pmoegenburg

Updates hardware controller to use AsyncResponseSerialConnection

2022-09-22 18:00 UTC, mcous requested changes

2022-09-22 18:00 UTC, mcous commented on api/tests/opentrons/hardware_control/modules/test_hc_thermocycler.py
> +    driver_mock = mock.AsyncMock()
`driver_mock` should be a separate fixture that's injected into this fixture

```python
@pytest.fixture
def mock_driver() -> mock.AsyncMock:
    return mock.AsyncMock(spec=DRIVER_CLASS_HERE)

@pytest.fixture
async def subject_mocked_driver(
    usb_port: USBPort,
    mock_driver: mock.AsyncMock, 
) -> AsyncGenerator[modules.Thermocycler, None]:
    ...
```

2022-09-22 18:00 UTC, mcous commented on api/tests/opentrons/hardware_control/modules/test_hc_thermocycler.py
> +    return ThermocyclerLidStatus.OPEN
These one-line functions to return one-line value objects make these tests harder for me to read. Could the values objects be used directly, instead?

2022-09-22 18:00 UTC, mcous commented on api/tests/opentrons/hardware_control/modules/test_hc_thermocycler.py
> +    subject_mocked_driver._driver.get_plate_temperature.return_value = (
One should never mock out implementation details of a test subject like this. This test should not know that `modules.Thermocycler` has a private `_driver` attribute.

Instead, set the mocks on the driver you're injecting (see comment above about creating a `mock_driver` fixture):

```python
async def test_sync_error_response_to_poller(
    mock_driver: mock.AsyncMock,
    subject_mocked_driver: modules.Thermocycler,
    ...,
):
    ...
    mock_driver.get_plate_temperature.return_value = ( ... )
```

2022-09-27 18:59 UTC, sanni-t commented
I think you want to target this to `edge`

2022-10-21 13:54 UTC, sfoster1 commented
> I think you want to target this to `edge`

No, unfortunately we're continuing to try and develop the TCGEN2 release independent of edge

2022-10-21 18:04 UTC, sfoster1 commented
Okay, we should target this on edge and once merged we'll cherry-pick to https://github.com/Opentrons/opentrons/pull/11607

2022-10-21 18:05 UTC, sfoster1 commented
Or we can target it on https://github.com/Opentrons/opentrons/pull/11607 and it'll come back in when we merge that back

2022-10-24 20:18 UTC, sfoster1 commented
Retargeting to `edge` since everything else for TCGEN2 is in there, and we're cherrypicking anyway.

2022-10-26 13:53 UTC, mcous approved these changes
Appreciate the test changes, LGTM

2022-10-27 18:27 UTC, merged