feat(usb-bridge): configure USB as serial port on startup
OpenTrons/opentrons-api pull request #11506
Opened 2022-09-27 13:35 UTC by fsinapi

# Overview

This PR adds code necessary to configure a device-side USB port as an ACM serial port. The code is tolerant of re-configuration, but relies on the proper kernel modules running before the Python module starts up.

This has been tested on a Raspberry Pi Zero running Debian to test that:
1. The serial port is configured and shows up as `/dev/ttyGS0` after running this application
2. The Raspberry Pi shows up as a serial modem when connected to a host computer over USB
3. The serial port echos back anything sent to it

# Changelog

- Edits to the push-ot3 target to allow pushing to a Linux target
- Added `usb_config` module to configure the Serial Gadget
- Added tests for the serial gadget configuration
- Set up the `main` method to provide echo over the serial port for testing

# Review requests

# Risk assessment

Low, does not affect any code in use elsewhere.

2022-09-27 13:55 UTC, sfoster1 requested changes
There's a lot of arguments to the gadget creator - all the descriptor table entries, really - that only make sense together. The defaults are defined as constants scattered around various files.

Instead, let's make a dataclass that gathers the static configuration and is passed in to the `SerialGadget` initializer. The `SerialGadget` initializer can hold it instead of holding a billion instance attributes - it could even hold a child class of it that adds in other configuration.

Then, you can define a dataclass instance as the "default" either at the main level or in like an `ot3usb.default_configs` module.

2022-09-27 13:55 UTC, sfoster1 commented on usb-bridge/mypy.ini
> +ignore_errors = True
IMO don't do this - having the mypy errors helps you figure out better ways to type things so it's not necessary.

2022-09-27 13:55 UTC, sfoster1 commented on usb-bridge/ot3usb/src/usb_config.py
> +        return self._driver.system(command) == os.EX_OK
why use `system` for this instead of `open(os.path.join(self._basename)).write(contents)`? If python has bindings for a system operation we should use them.

2022-09-27 13:55 UTC, sfoster1 commented on usb-bridge/ot3usb/src/usb_config.py
> +        if self._driver.system(f"ls /sys/class/udc > {self._basename}UDC") != os.EX_OK:
what's this one doing? same as the write, we should avoid using `system` for this if we can.

2022-09-27 13:58 UTC, sfoster1 requested changes
Accidentally submitted that last one too early, sorry - couple more inline reviews

2022-09-27 13:58 UTC, sfoster1 commented on usb-bridge/ot3usb/src/usb_config.py
> +"""Support for configuring USB through Linux ConfigFS."""
Can we add some links to docs on how to configure a gadget in here?

2022-09-27 13:58 UTC, sfoster1 commented on usb-bridge/ot3usb/src/usb_config.py
> +    HANDLE = "/dev/ttyGS0"
can we read this from the created gadget configfs somewhere?

2022-09-27 13:58 UTC, sfoster1 commented on usb-bridge/ot3usb/src/usb_config.py
> +        configFolder = "configs/c.1/"
this probably wants to be in a const ("const") somewhere

2022-09-27 13:58 UTC, sfoster1 commented on usb-bridge/ot3usb/src/usb_config.py
> +        functionFolder = self._basename + "functions/acm.usb0"
probably should be a const

2022-09-27 13:58 UTC, sfoster1 commented on usb-bridge/ot3usb/src/usb_config.py
> +        self._driver.sleep(1)
maybe a polling loop?

2022-09-27 13:59 UTC, fsinapi commented on usb-bridge/ot3usb/src/usb_config.py
> +        if self._driver.system(f"ls /sys/class/udc > {self._basename}UDC") != os.EX_OK:
`/sys/class/udc` contains the id of the available UDC driver, which needs to be written to the file `UDC` in order to attach this gadget configuration to the UDC hardware. Can split this up.

2022-09-27 14:42 UTC, fsinapi commented on usb-bridge/ot3usb/src/usb_config.py
> +    HANDLE = "/dev/ttyGS0"
I'm not really sure? I'm pretty sure that the g_serial driver automatically enumerates device-side tty's with this format, based on the [kernel docs](https://www.kernel.org/doc/Documentation/usb/gadget_serial.txt).

2022-09-27 20:34 UTC, fsinapi commented on usb-bridge/ot3usb/src/usb_config.py
> +        self._driver.sleep(1)
Pretty sure this was entirely unnecessary, will test without it...

2022-09-28 13:51 UTC, fsinapi commented on usb-bridge/ot3usb/src/usb_config.py
> +    HANDLE = "/dev/ttyGS0"
Nevermind, this is totally readable. There's a `port_num` file in the `configs` subfolder.

2022-09-28 16:18 UTC, sfoster1 approved these changes
Looks good to me! Very excited

2022-09-28 16:38 UTC, merged