refactor(calibration-storage): Use pydantic models for data validation, add OT-3 pydantic models
OpenTrons/opentrons-api pull request #11520
Opened 2022-09-29 20:09 UTC by Laura-Danielle

# Overview

Closes RLIQ-118. The objective of this PR is to add pydantic models to support better validation on calibration data in general. Please check out [this confluence doc](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/3391029314/Calibration+Data+Schemas) for more information on the pydantic schemas and this confluence doc for more information on what the file system looks like in general. There are a lot of loose ends that need to be tied up in separate PRs of which I've documented in <INSERT JIRA EPICS>. 

In-memory caching for calibration data will be in a follow-up PR.

# Changelog

- Added two modules under _calibration_storage_ to separate OT-2 and OT-3 calibration types
- Separated instrument calibration data based on OT-2 and OT-3 (pipette(s) will be handled in a follow-up PR which changes the data schema of pipettes to support OT-3 pipette functionality).
- Moved the dataclass objects of the calibration data models (which were only used in the hardware controller) to the hardware controller and converted from the pydantic schemas in the hardware controller once the data was being loaded in.
- Switched to using only pydantic models in the robot-server
- Added more test coverage on the _calibration storage_ module in general
- Modified tests where necessary

# Review requests

Please test this on a robot, let me know if you have any changes you want to the actual data shape as well.

# Test Plan

Please view this confluence document for a more detailed test plan and check list.

- [ ] Run through all OT-2 calibration flows
- [ ] Check that all calibration data endpoints (`calibration/pipette_offset` and `calibation/tip_length`) still work as expected
- [ ] Check that all robot calibrations are still being properly loaded and applied in the hardware controller
- [ ] Check that downgrading the software keeps all calibrations that were calibrated with the new software

# Risk assessment

High. This touches a lot of flakey code and needs a lot of QA eyes. See test plan above.

2022-10-17 19:51 UTC, sfoster1 requested changes
Some smaller things in code review, but one bigger one: I don't really like the use of "Schema" in pydantic model names. They're schemas, but they're also instantiated with data and passed around as data container objects. It's weird to have a function that modifies the data of a schema, it's a mismatch of kind: if you have a function that operates on a schema, i expect the schema to be different afterwards - but here, it's just the data in an instance. We should either use these objects only to verify data but not store it, or call them `Model`s or something

2022-10-17 19:51 UTC, sfoster1 commented on shared-data/LICENSE
> +
do we need this here? it's already in the root

2022-10-17 19:51 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/ot2/mark_bad_calibration.py
> +@typing.overload
it accomplishes the same thing, but I'm a much bigger fan of doing this with a `TypeVar` since it reads more cleanly to me:
```
CalibrationType = TypeVar('CalibrationType', v1.PipetteOffsetCalibration, v1.TipLengthCalibration, v1.DeckCalibrationSchema)  # the extra args here are applying a one-of-these constraint to the typevar. you might also put a bound=SomeClass here if those three descended from a single ancestor

def mark_bad(
     calibration: CalibrationType,
     source_marked_bad: local_types.SourceType
) -> CalibrationType:
    # code goes here
```
it makes it a little clearer that this operates on something and returns the same thing.

2022-10-17 20:15 UTC, Laura-Danielle commented on shared-data/LICENSE
> +
Nope accidental commit.

2022-10-18 17:37 UTC, mcous requested changes
Many of the added tests assert on implementation details (private methods / fields) of the code under test, which is inappropriate and does not actually test that the public API works. Code and/or tests should structured such that behavior can be validated against public, used-in-production methods

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/calibration_storage/file_operators.py
> +    data: typing.Union[BaseModel, typing.Dict[str, typing.Any], typing.Any],
That last `typing.Any` effectively removes any type constraints on this argument. Why is it needed?

```suggestion
    data: typing.Union[BaseModel, typing.Dict[str, typing.Any]],
```

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/calibration_storage/file_operators.py
> +            json.dump(data, f, cls=encoder)
If we're re-writing this, can we prefer pathlib?

```python
json_data = (
    data.json()
    if isinstance(data, BaseModel)
    else json.dumps(data, cls=encoder)
)
Path(filepath).write_text(json_data, encoding="utf-8")
```

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/calibration_storage/file_operators.py
>      filepath: StrPath,
Can this argument be turned into a `Path`?

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/calibration_storage/ot2/deck_attitude.py
> +            except (json.JSONDecodeError, ValidationError):
What does this mean? Should it be logged?

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/calibration_storage/ot2/deck_attitude.py
> +    # TODO(mc, 2022-06-08): this leaves legacy deck calibration backup files in place
Is this TODO still relevant?

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/calibration_storage/ot2/deck_attitude.py
> +    elif cal_status and isinstance(cal_status, v1.CalibrationStatus):
Are the "is truthy?" conditions here redundant due to the `isinstance`? Disregard this comment if it's there to make mypy happy

```suggestion
    if isinstance(cal_status, local_types.CalibrationStatus):
        cal_status_model = v1.CalibrationStatus(**asdict(cal_status))
    elif isinstance(cal_status, v1.CalibrationStatus):
```

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/calibration_storage/ot2/deck_attitude.py
> +    return _deck_calibration()
Why are these split into two separate functions? It seems like we should just have `get_robot_deck_attitude`

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/calibration_storage/ot2/mark_bad_calibration.py
> +    calibration.status = v1.CalibrationStatus(
Can we avoid mutating the input argument and return a new object instead?

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/calibration_storage/ot2/mark_bad_calibration.py
> +        markedBad=True, source=source_marked_bad, markedAt=utc_now()
Deep timestamps generation like this can be frustrating to test. I would recommend accepting the time as an argument so a higher-level collaborator can make the call to `utc_now` as necessary

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/calibration_storage/ot2/pipette_offset.py
> +    pip_dir.mkdir(parents=True, exist_ok=True)
`mkdir` shouldn't leak out of the file operations module. I would incorporate "create any necessary directories" into `save_to_file`

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/calibration_storage/ot2/pipette_offset.py
> +    elif cal_status and isinstance(cal_status, v1.CalibrationStatus):
Same comment about truthy check being possibly redundant

```suggestion
    if isinstance(cal_status, local_types.CalibrationStatus):
        cal_status_model = v1.CalibrationStatus(**asdict(cal_status))
    elif isinstance(cal_status, v1.CalibrationStatus):
```

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/calibration_storage/ot2/pipette_offset.py
> +        mount_type = types.MountType.RIGHT
I would simplify this and/or add a `from_hw_mount` method to `MountType`

```suggestion
    mount_type = types.MountType[mount.name]
```

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/calibration_storage/ot3/pipette_offset.py
> +def _pipette_offset_calibrations() -> PipetteCalibrations:
This feels like it's slightly the wrong layer to split this common functionality out. There are two users of this function:

1. "get all offsets"
2. "get a specific offset, by ID and mount"

I think the second one - "get one offset" should be the common function, and "get all offsets" should call "get one offset" repeatedly. For example:

```python
def get_pipette_offset(pipette_id: str, mount: MountType) -> ...:
    pipette_calibration_dir = config.get_opentrons_path("pipette_calibration_dir")
    pipette_calibration_file = pipette_calibration_dir / mount.value / f"{pipette_id}.json"
    ...

def get_all_pipette_offsets() -> ...:
    pipette_calibration_dir = config.get_opentrons_path("pipette_calibration_dir")
    result = {MountType.LEFT: {}, MountType.RIGHT: {}}
    
    for calibration_file in pipette_calibration_dir.glob("**/*.json"):
        pipette_id = calibration_file.stem
        mount = MountType(calibration_file.parent.stem)
        result[mount][pipette_id] = get_pipette_offset(pipette_id, mount)

    return result
```

"Get all JSON files in directory" should probably move to the file module, if it isn't there already

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/calibration_storage/ot3/pipette_offset.py
> +        return _pipette_offset_calibrations()[mount_type][pipette_id]
See above comment about flipping this around. As written, we have the unfortunate behavior that a call to `get_pipette_offset` will fail if _any_ pipette offset in the directory is bad for some reason

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/calibration_storage/ot3/tip_length.py
> +def _tip_length_calibrations() -> TipLengthCalibrations:
Same comment as pipette offsets; this is probably the wrong layer of commonality and much of it could be replaced by a call to `Path.glob`

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/calibration_storage/ot3/tip_length.py
> +            tip_length_path.unlink()
Why isn't this using the internal `io` module?

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/calibration_storage/types.py
> +GripperId = typing.NewType("GripperId", str)
Do these type aliases serve a specific type narrowing purpose? If not, I would propose removing them and simply using `str`

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/config/reset.py
> +# rather than type ignore an import_module command using importlib.
Is there another option, like export top level `delete_robot_deck_attitude` from `opentrons.calibration_storage` and allowing `calibration_storage` to check the feature flag, instead?

2022-10-18 17:37 UTC, mcous commented on api/tests/opentrons/calibration_storage/test_deck_attitude.py
> +def starting_calibration_data(_deck: ModuleType, ot_config_tempdir: Any) -> None:
The fact that we need all these fixtures to successfully test is also saying to me like we should have top level exports from `calibration_storage` that deal with this rather than shunting it to the caller

2022-10-18 17:37 UTC, mcous commented on api/tests/opentrons/calibration_storage/test_deck_attitude.py
> +    assert deck._deck_calibration() is None
Should not check private attributes to verify functionality. Is there an existing public property or other measurable side effect? (I would also be opposed to adding a "public" property solely for the purpose of testing, since we should never add properties we don't actually use in production)

2022-10-18 17:37 UTC, mcous commented on api/tests/opentrons/calibration_storage/test_deck_attitude.py
> +    if robot_type == "ot3":
`if/else` in tests are a bad sign. Code and/or tests should be refactored to remove the need for them

2022-10-18 17:37 UTC, mcous commented on api/tests/opentrons/calibration_storage/test_deck_attitude.py
> +    assert deck._deck_calibration() != {}
Same comment, testing private properties is not a good idea. Code and/or tests should be refactored so that only public interfaces are used

2022-10-18 17:37 UTC, mcous commented on api/tests/opentrons/calibration_storage/test_gripper_offset.py
> +    assert gripper._gripper_offset_calibrations() != {}
Asserting on private implementation detail (comment applies to whole file)

2022-10-18 17:37 UTC, mcous commented on api/tests/opentrons/calibration_storage/test_pipette_offset.py
> +    assert pipette._pipette_offset_calibrations() != {}
Asserting on private implementation detail

2022-10-18 17:37 UTC, mcous commented on api/tests/opentrons/calibration_storage/test_tip_length.py
> +minimalLabwareDef = {
Can we re-use the existing fixture for this?

2022-10-18 17:37 UTC, mcous commented on api/tests/opentrons/calibration_storage/test_tip_length.py
> +    assert tip_length._tip_length_calibrations() == {}
Asserting on implementation detail

2022-10-18 17:37 UTC, mcous commented on api/src/opentrons/calibration_storage/file_operators.py
>  import json
I don't see any unit tests for this file, which is unfortunate. If this file was fully unit tested (and calling code was disciplined about always delegating to `file_operators`), the tests for the calling code could be written with mocks, which would speed tests up and provide useful implementation design feedback for the calibration data functions

2022-10-21 16:16 UTC, Laura-Danielle commented on api/src/opentrons/calibration_storage/file_operators.py
> +            json.dump(data, f, cls=encoder)
I'm refactoring the file access to anyio in a separate PR/branch (branch is RLIQ-118-file-access-async, ticket is RLIQ-200) which is where I will address the `Path` requests. I'm hoping to be able to finish it up in the next two weeks or so, but I kept getting pulled onto other things. I made a bunch of [follow-up tickets](https://opentrons.atlassian.net/browse/RLIQ-200) that need to be addressed at some point.

I'm trying to make as little changes here as possible since this is already a huge PR.

2022-10-21 20:55 UTC, Laura-Danielle commented on api/src/opentrons/calibration_storage/ot2/deck_attitude.py
> +            except (json.JSONDecodeError, ValidationError):
Sure I'll throw in a log. It effectively means the data is bad.

2022-10-21 20:55 UTC, Laura-Danielle commented on api/src/opentrons/calibration_storage/ot2/deck_attitude.py
> +    # TODO(mc, 2022-06-08): this leaves legacy deck calibration backup files in place
I'm keeping the legacy deck calibration file cleanup here for now. Any data formatting changes and/or things that might affect downgrades (even with low risk) should probably remain. Effectively, yes this todo is still relevant.

2022-10-21 20:55 UTC, Laura-Danielle commented on api/src/opentrons/calibration_storage/ot2/deck_attitude.py
> +    elif cal_status and isinstance(cal_status, v1.CalibrationStatus):
I think I did this to make mypy happy, but I'll double check.

2022-10-21 20:55 UTC, Laura-Danielle commented on api/src/opentrons/calibration_storage/ot2/deck_attitude.py
> +    return _deck_calibration()
Mostly was trying to keep a similar format to the other files, but I can just combine them.

2022-10-21 20:55 UTC, Laura-Danielle commented on api/src/opentrons/calibration_storage/ot2/mark_bad_calibration.py
> +        markedBad=True, source=source_marked_bad, markedAt=utc_now()
I'll add it as a todo and make a ticket since this is not new functionality. I'm trying to avoid changing function signatures in this PR where possible.

2022-10-21 20:55 UTC, Laura-Danielle commented on api/src/opentrons/calibration_storage/ot2/mark_bad_calibration.py
> +    calibration.status = v1.CalibrationStatus(
sure

2022-10-21 20:55 UTC, Laura-Danielle commented on api/src/opentrons/calibration_storage/types.py
> +GripperId = typing.NewType("GripperId", str)
The explicit purpose was to be able to create more verbose types like:
```
PipetteCalibrations = Dict[
    types.MountType, Dict[local_types.PipetteId, v1.InstrumentOffsetSchema]
]
```

And also for readability purposes. I now can tell what "string" is supposed to be without trying to look at the function signature or referencing documentation in confluence.

2022-10-21 20:55 UTC, Laura-Danielle commented on api/src/opentrons/config/reset.py
> +# rather than type ignore an import_module command using importlib.
I'm probably doing something dumb with imports, but because a lot of the locations where `calibration_storage` gets imported explicitly import the modules, it was _really_ hard to test turning the feature flag on/off.

2022-10-21 20:55 UTC, Laura-Danielle commented on api/tests/opentrons/calibration_storage/test_deck_attitude.py
> +def starting_calibration_data(_deck: ModuleType, ot_config_tempdir: Any) -> None:
I have never successfully been able to rely on a feature flag with imports -- it's possible that maybe I'm just doing something incorrectly. I made these fixtures to reduce the number of tests in the file, but I could also just explicitly import everything and create separate tests for ot2 vs ot3 calibration storage.

2022-10-21 20:55 UTC, Laura-Danielle commented on api/tests/opentrons/calibration_storage/test_deck_attitude.py
> +    assert deck._deck_calibration() is None
I could just call the `get` function(s) to check whether the data got saved/deleted correctly.

2022-10-27 14:55 UTC, Laura-Danielle commented on api/src/opentrons/calibration_storage/types.py
> +GripperId = typing.NewType("GripperId", str)
Decided to remove them.

2022-10-27 16:55 UTC, Laura-Danielle commented
I want to get this merged ASAP because it's blocking some other calibration work. Any other clean-ups requested (aside from anything found during testing) will be documented [here](https://opentrons.atlassian.net/browse/RLIQ-199) and addressed after our 'feature freeze'.

2022-10-27 17:01 UTC, sfoster1 approved these changes
Looks good to me! Would love to remove conditional imports at some point but not this PR.

2022-10-27 17:01 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/__init__.py
> +if config.feature_flags.enable_ot3_hardware_controller():
This is fine for now but can we add a todo to make this something that is not based on a feature flag and not conditionally imported at some point? I'd love for fewer decisions to get made during import, and having our code support both machines at runtime is an important thing for offline analysis and general sanity

2022-10-28 16:33 UTC, mcous approved these changes
I'm ok to move forward with this PR and address additional items in a follow up PR for speed, but in order of importance, I'm still concerned about these issues:

1. Conditional imports/exports at the top level of the `calibration_storage` module should be avoided at all costs
2. Tests for `calibration_storage` are written with `if/else`, which seems to suggest that a test suite run will only check OT-2 _or_ OT-3, rather than OT-2 _and_ OT-3
3. File/directory reading/writing concerns still leak out of `file_operators.py`
4. Since `file_operators.py` has test coverage, tests for other `calibration_storage` components could mock out `file_operators` for speed and useful design feedback, but they do not
    - Tests will be slower because there will be a lot of hitting the filesystem
    - We have redundant test coverage of file operations

2022-10-28 16:33 UTC, mcous commented on api/src/opentrons/calibration_storage/__init__.py
> +if config.feature_flags.enable_ot3_hardware_controller():
I agree. If we do need to check a feature flag, it should be done at function run time, not import time. This global `config` singleton that needs to be initialized in order for _imports_ to work is an antipattern in our codebase

If it's too much for this PR, that's fine, but I was imagining a lightweight facade in my earlier review:

```python
def save_robot_deck_attitude(...) -> ...:
    if is_ot3:
        from .ot3 import deck_attitude as ot3_deck_attitude
        ot3_deck_attitude.save_robot_deck_attitude(...)
    else:
        ...
```

2022-10-28 16:33 UTC, mcous commented on api/src/opentrons/calibration_storage/ot2/deck_attitude.py
> +    elif cal_status and isinstance(cal_status, v1.CalibrationStatus):
If you managed to confirm that it was to make mypy happy, feel free to mark these comments as resolved

2022-10-28 16:33 UTC, mcous commented on api/src/opentrons/calibration_storage/ot2/pipette_offset.py
> +    offset_dir = Path(config.get_opentrons_path("pipette_calibration_dir"))
`get_opentrons_path` is typed as returning a `Path`, is this extra wrapper redundant?

2022-10-28 16:33 UTC, mcous commented on api/src/opentrons/calibration_storage/ot2/pipette_offset.py
> +    for filepath in pipette_calibration_dir.glob("**/*.json"):
Would recommend moving to a `io.get_json_files_from_directory` or something similar for testability

2022-10-28 16:33 UTC, mcous commented on api/src/opentrons/calibration_storage/ot2/tip_length.py
> +            )
Should this be going through `io.read_json_file` or similar?

2022-10-28 16:33 UTC, mcous commented on api/src/opentrons/calibration_storage/ot3/deck_attitude.py
> +                pass
If we already know the full expected path, why are we using `os.scandir`?

2022-10-28 16:33 UTC, mcous commented on api/tests/opentrons/calibration_storage/test_deck_attitude.py
> +    importlib.reload(opentrons.calibration_storage)
This is a warning sign, is it due to all the conditional importing and re-exporting? An explicit facade would avoid this problem.

`importlib.reload`, in my experience, is not terribly reliable or intuitive

2022-10-28 16:33 UTC, mcous commented on api/tests/opentrons/calibration_storage/test_deck_attitude.py
> +    if robot_model == "OT-3 Standard":
`if/else` in tests should almost always be avoided. Can this be parametrized, instead?

2022-10-28 16:33 UTC, mcous commented on api/tests/opentrons/calibration_storage/test_deck_attitude.py
> +def starting_calibration_data(
Should we write these tests as isolated unit tests and mock out `file_operators` instead, given that `file_operators` has unit tests?

2022-10-28 18:36 UTC, Laura-Danielle commented
> I'm ok to move forward with this PR and address additional items in a follow up PR for speed, but in order of importance, I'm still concerned about these issues:
> 
> 1. Conditional imports/exports at the top level of the `calibration_storage` module should be avoided at all costs
> 2. Tests for `calibration_storage` are written with `if/else`, which seems to suggest that a test suite run will only check OT-2 _or_ OT-3, rather than OT-2 _and_ OT-3
> 3. File/directory reading/writing concerns still leak out of `file_operators.py`
> 4. Since `file_operators.py` has test coverage, tests for other `calibration_storage` components could mock out `file_operators` for speed and useful design feedback, but they do not
>    
>    * Tests will be slower because there will be a lot of hitting the filesystem
>    * We have redundant test coverage of file operations

Will hopefully get to all of this next week!

2022-10-28 19:30 UTC, merged