feat(protocol-designer): add OT-3 pipettes, tip racks, and robot model
OpenTrons/opentrons-api pull request #11525
Opened 2022-10-03 15:27 UTC by sakibh

# Overview

This PR adds the OT-3 pipettes, tip racks and robot model to Protocol Designer and schema V6. closes RLIQ-178, closes RLIQ-179, closes RLIQ-180

# Changelog

- Add GEN3 pipettes and tip racks behind feature flag
- Update `PipetteSelect` component to take in optional `filteredOptions` prop.
- Update `PipetteFields` to filter dropdown based on pipette GEN3.
- Updated various tests and constants

# Review requests

1. Create a new protocol, try to add new pipettes and select tip racks. OT-3 pipettes and tip racks should NOT show.
2. Toggle Enable OT-3 support feature flag.
3. Create a new protocol, try to add new pipettes and select tip racks. OT-3 GEN3 pipettes and tip racks should show up.
4. In either the left or right mount, select a GEN3 pipette. Then try to add a pipette in the opposite mount, it should only show GEN3 pipette options.
5. Add GEN3 pipette(s) to your protocol and export the protocol. In the JSON file the `robot` key should have an updated model with the OT3 for both the model and deckId.

# Risk assessment
low, behind FF

2022-10-03 15:28 UTC, sakibh commented on protocol-designer/src/file-data/selectors/fileCreator.ts
> +    ): {
Any thoughts on where we can best move this interface and utility function?

2022-10-03 15:29 UTC, sakibh commented on shared-data/js/pipettes.ts
> +  return (
Not necessary in this PR, but this utility is used in the app side pipette change flow. I can revert it if we anticipate there could be any issues downstream.

2022-10-03 17:41 UTC, sakibh commented on shared-data/pipette/definitions/pipetteNameSpecs.json
> -    "displayCategory": "GEN2",
I assumed this was a typo. But if anyone knows otherwise, please let me know.

2022-10-04 13:56 UTC, jerader approved these changes
Good job! All the PD functionality is there, with & without the FF turned on, and I did some smoke testing in the app.

2022-10-04 13:56 UTC, jerader commented on shared-data/js/pipettes.ts
> +  return (
I didn't know that we will have to level ot3 8-channel pipettes?

2022-10-04 13:57 UTC, jerader commented on shared-data/pipette/definitions/pipetteNameSpecs.json
> -    "displayCategory": "GEN2",
I agree that this seems like a typo

2022-10-04 14:08 UTC, Laura-Danielle approved these changes
lgtm. Thanks for adding in the 50ul tiprack to the block list.

2022-10-04 14:08 UTC, Laura-Danielle commented on components/src/instrument/PipetteSelect.tsx
> +  GEN3,
Just so you know, we will be changing the names of the pipettes probably. Unsure, yet, how we're going to address this in code.

2022-10-04 14:08 UTC, Laura-Danielle commented on shared-data/js/pipettes.ts
> +  return (
TBD @jerader. I'm trying to confirm with hardware.

2022-10-04 14:08 UTC, Laura-Danielle commented on shared-data/pipette/definitions/pipetteNameSpecs.json
> -    "displayCategory": "GEN2",
It's a typo, but also the name is going to change, so it doesn't matter _that_ much.

2022-10-04 17:14 UTC, smb2268 commented on components/src/instrument/PipetteSelect.tsx
> +  const gen30options = specsByCategory[GEN3].map(specToOption).filter(allowlist)
This should be `gen3Options`, not `gen30options`

2022-10-04 17:50 UTC, smb2268 requested changes
This is looking really good! One change request though - currently this filters when you select a Gen3 pipette first, but can we add functionality so that if they select a gen1 or gen2 pipette first they can't select a gen3 in the second drop down?

2022-10-04 21:16 UTC, sakibh commented on shared-data/js/pipettes.ts
> +  return (
I will remove this change in the PR then. If it is needed it can be added in later.

2022-10-04 21:17 UTC, sakibh commented on components/src/instrument/PipetteSelect.tsx
> +  const gen30options = specsByCategory[GEN3].map(specToOption).filter(allowlist)
Nice catch! Perhaps we'll have a gen 30 in a few centuries.

2022-10-06 17:35 UTC, smb2268 approved these changes
Looks great 🚀🚀

2022-10-07 15:40 UTC, merged