refactor(app): remove dependence on key/value structure for pipette key
OpenTrons/opentrons-api pull request #11535
Opened 2022-10-05 15:24 UTC by jerader

closes RAUT-230

# Overview

This removes the dependence of the key/value structure for the top level pipette key in the `SchemaV6Adapter`. 

# Changelog

- change `SchemaV6Adapter` and the few affected areas: `getPrimaryPipetteId` + `getPrimaryPipetteId.test`

# Review requests

- smoke test the app to make sure everything works as expected
- make sure the schemaV6 adapter pipette key output matches the input

# Risk assessment

low

2022-10-05 15:27 UTC, jerader commented on app/src/organisms/LabwarePositionCheck/utils/getPrimaryPipetteId.ts
> +  if (pipettesById[1] == null) {
LPC white screens because `id` doesn't exist. Not sure how to prevent that unless we want `pipettesById` to be a different `type`?

2022-10-13 17:07 UTC, smb2268 requested changes
This looks good so far, but let's refactor a few things to make them less brittle!

2022-10-13 17:07 UTC, smb2268 commented on api-client/src/protocols/utils.ts
>    const rightPipette = commands.find(
Based on the convo we had in standup on Tuesday about whether we want to get rid of the `byId` pattern everywhere or just stop making this conversion in the schemaV6Adapter, I don't think we should make this change. In this case, constructing the `pipetteById` format from the commands makes this a little cleaner and this function isn't being affected by data that was previously manipulated by the adapter.

2022-10-13 17:07 UTC, smb2268 commented on app/src/organisms/Devices/hooks/useRunPipetteInfoByMount.ts
> +  return Object.entries(pipettes).reduce((acc, pipette) => {
This `pipettes` key should be an array, not an object. So we should be able to say `pipettes.reduce` instead of `Object.entries(pipettes).reduce`. Once this change is made, you should be able to clean up some of the logic below. You'll now have one `pipette` with a `pipette.Id` and `pipette.pipetteName` for each iteration of this reduce, which will make it easier to mimic the previous logic

2022-10-13 17:07 UTC, smb2268 commented on app/src/organisms/LabwarePositionCheck/DeprecatedComponents/DeprecatedLabwarePositionCheckStepDetail.tsx
> +    protocolData.pipettes[0].id === pipetteId
We shouldn't access the elements of an array by an arbitrary index in case it doesn't exist. Instead, we can do something like `pipetteName = protocolData.pipettes.find(pipette => pipette.id === pipetteId).name`

2022-10-13 17:07 UTC, smb2268 commented on app/src/organisms/LabwarePositionCheck/LabwarePositionCheckStepDetail.tsx
> +    protocolData.pipettes[0].id === pipetteId
same comment as above -- we should use Array functions `find` or `findIndex` instead of assuming there will be a [0] and [1] index here

2022-10-13 17:07 UTC, smb2268 commented on app/src/organisms/LabwarePositionCheck/getLabwarePositionCheckSteps.ts
> +        Object.values(pipettesById)[0].id !== primaryPipetteId
let's change this name since the pipettes will no longer be `pipettesById` and use `find` to grab the correct pipette instead of an index.

2022-10-13 17:07 UTC, smb2268 commented on app/src/organisms/LabwarePositionCheck/utils/getPrimaryPipetteId.ts
> +  if (pipettesById[1] == null) {
let's keep this as a length check, pipettesById.length === 1

2022-10-13 18:30 UTC, jerader commented on app/src/organisms/LabwarePositionCheck/DeprecatedComponents/DeprecatedLabwarePositionCheckStepDetail.tsx
> +    protocolData.pipettes[0].id === pipetteId
Oof thank you! That way is a lot cleaner!

2022-10-13 20:22 UTC, smb2268 approved these changes
Smoke tested this in the app with a dev server and all works as expected!

2022-10-13 20:26 UTC, merged