refactor(app): remove dependence on key/value structure for labware key
OpenTrons/opentrons-api pull request #11544
Opened 2022-10-07 17:37 UTC by jerader

closes RAUT-245

# Overview

This changes the key/value structure for labware key, to eventually remove the `schemaV6Adapter`: We are waiting on backend to add `displayName`

# Changelog

- changes in `SchemaV6Adapter`
- touched a bunch of components and their tests:
1. `createSnippet`
2. `StepText`
3. `getLabwareDefinitionUri`
4. `useRunPipettesInfoByMount`
5. `DeprecatedLabwarePositionCheckStepDetail` and `LabwarePositionCheckStepDetail`
6. `DeprecatedStepDetailText` and `StepDetailText`
7. `getLabwarePositionCheckStep`
8. `useLabwarePositionCheck`
9. `useLabwareOffsets`
10. `doesPipetteVisitAllTipracks`
11. `getOnePipettePositionCheckSteps`
12. `getPipetteWorkflow`
13. `labware`
14. `useOffsetCandidatesForCurrentRun`
15. `useClearAllOffsetsForCurrentRun`

# Review requests

- smoke test in the app including LPC, creating a snippet, applying and deleting offset data

# Risk assessment

low

2022-10-07 18:51 UTC, jerader commented on app/src/organisms/Devices/hooks/useRunPipetteInfoByMount.ts
> +            const tipRack = labware.find(
this will cause a white screen in the app until we fix the `storedProtocolAnalysis` type

2022-10-10 18:53 UTC, jerader commented on app/src/organisms/ReapplyOffsetsModal/hooks/useOffsetCandidatesForCurrentRun.ts
> +      .filter(labware => labware.id !== 'fixedTrash')
Not sure if its correct to filter out the trash id here. Originally, the `schemaV6Adapter` filters it out but I removed it because we will be removing the adapter eventually anyway. So I had to filter it out here.

2022-10-13 17:31 UTC, smb2268 requested changes
This is looking great so far! I made a couple suggestions, and will do another round of review/smoke testing once everything is addressed.

2022-10-13 17:31 UTC, smb2268 commented on api-client/src/protocols/utils.ts
> -export function parseInitialLoadedLabwareById(
Same thing here as with pipettes -- since this is pulling from the commands list not from the labware entity key, we can continue using the`ById` type here.

2022-10-13 17:31 UTC, smb2268 commented on app/src/organisms/Devices/hooks/useRunPipetteInfoByMount.ts
> +            const tipRack = labware.find(
does the whitescreen happen even if we say `const tipRack = labware?.find(`

2022-10-13 17:31 UTC, smb2268 commented on app/src/organisms/LabwarePositionCheck/StepDetailText.tsx
> +  const labwareDefId = protocolData.labware.find(item => item.id === labwareId)
let's rename this to `labwareDefUri`!

2022-10-13 17:31 UTC, smb2268 commented on app/src/organisms/LabwarePositionCheck/getLabwarePositionCheckSteps.ts
> +      omitBy(
I think that `omitBy` will be expecting an object type here, but we're passing it `protocolData.labware` as an array. We should be able to accomplish this same thing using Array.filter and inverting the omitBy logic.

2022-10-13 18:31 UTC, jerader commented on app/src/organisms/Devices/hooks/useRunPipetteInfoByMount.ts
> +            const tipRack = labware.find(
oops i think i forgot to remove this comment. I'm pretty sure this is fixed now but I will double check!

2022-10-13 20:33 UTC, smb2268 commented on app/src/organisms/LabwarePositionCheck/getLabwarePositionCheckSteps.ts
> +        )
I think this logic is different -- 
the previous logic is saying omit this labware if:
labware is a tiprack AND there is NO pickup tip command associated with that labware id

the new logic says --
filter this array down to only labware that:
is a tiprack OR there is no pickup tip command associated with that labware id

We can either update this to use `labware.values.omitBy` like you used with pipettes, or change this to be 
```    const labware = protocolData.labware.filter(
      //  @ts-expect-error
      labware =>
        !protocolData.labwareDefinitions[labware.definitionUri]?.parameters
          .isTiprack ||
        (protocolData.labwareDefinitions[labware.definitionUri]?.parameters
          .isTiprack &&
        protocolData.commands.some(
          command =>
            command.commandType === 'pickUpTip' &&
            command.params.labwareId === labware.id
        ))```

either way, let's each log this locally to make sure the outcome is as expected

2022-10-13 20:36 UTC, smb2268 commented on app/src/organisms/LabwarePositionCheck/getLabwarePositionCheckSteps.ts
> +        )
`omitBy` filters out items that match the criteria, while `filter` keeps items that match. So to change this to use filter, we need to say:
If labware IS NOT a tiprack OR (labware IS a tiprack AND has a corresponding pick up tip command)

which should be the exact inverse of the previous omitBy logic

2022-10-17 13:02 UTC, jerader commented on app/src/organisms/LabwarePositionCheck/getLabwarePositionCheckSteps.ts
> +        )
Thank you! i was getting really confused by what the logic was supposed to be

2022-10-18 20:58 UTC, smb2268 commented on api-client/src/protocols/utils.ts
> -export function parseInitialLoadedLabwareById(
Sorry if this comment was confusing -- what I meant here was since this function doesn't touch the output of `protocolData.labware`, we shouldn't make any changes to it for this PR. We can continue constructing an object that looks like `  [labwareId: string]: {
    definitionUri: string
    displayName?: string
  }` we just won't be doing so with the result of the top level entity key.

2022-10-19 19:42 UTC, smb2268 approved these changes
🚀🚀🚀

2022-10-19 19:46 UTC, merged