feat(api): Enable OT3 protocol contexts from opentrons.execute/simulate
OpenTrons/opentrons-api pull request #11554
Opened 2022-10-11 00:26 UTC by andySigler

# Overview

Adds ability for `opentrons.execute` and `opentrons.simulate` to return an OT3-enable `ProtocolContext`.

# Changelog

# Review requests

# Risk assessment

2022-10-13 13:41 UTC, sfoster1 requested changes
This is a good thing to do but I think we should alter the approach in two ways:
- First, in both `execute` and `simulate`, there's starting to be a little too much logic in the `_THREAD_MANAGED_HW` creation. Let's factor that into a function so you can do `if not _THREAD_MANAGED_HW: _THREAD_MANAGED_HW = build_thread_managed_simulator()` and put the logic in the function.
- Second, we've got `should_use_ot3`, but then you'd have to manually switch between ot3 and ot2 separately from the script (as you're doing in enable_ot3_hardware.py) every time. Let's add a new command line flag to the execute/simulate scripts that is like `--machine=[ot2, ot3]`. That argument should take priority over the persistent setting, but not change the persistent setting. If you specify `--machine=ot3` the script always runs for ot3 no matter the setting; if you specify `--machine=ot3` the script always runs for ot2 no matter the setting. If not specified, use the persistent configuration.

2022-10-21 13:53 UTC, sfoster1 approved these changes
Nice, looks good to me! Thanks for making the changes.

2022-10-27 19:35 UTC, sfoster1 requested changes
I think the conditional import needs to be actually in the function where you build the OT3 hardware controller - it needs to be import if _either_ somebody has requested the machine be ot3 _and/or_ the feature flag is set, and right now it's only if the feature flag is set.

2022-10-27 19:35 UTC, sfoster1 commented on api/src/opentrons/simulate.py
> +        return ThreadManager(OT3API.build_hardware_simulator)
I think you need to do the import here rather than at the top - if you specify with the command line flag but the feature flag isn't set this will fail with a `NameError`

2022-10-27 19:35 UTC, sfoster1 commented on api/src/opentrons/execute.py
> +            _THREAD_MANAGED_HW = ThreadManager(OT3API.build_hardware_controller)
this needs to have the OT3API import in here because if `should_use_ot3()` is `False` then it won't have been imported but if `machine == "ot3"` we'll try to use it anyway

2022-11-02 17:11 UTC, andySigler commented on api/src/opentrons/simulate.py
> +        return ThreadManager(OT3API.build_hardware_simulator)
👍

2022-11-02 17:11 UTC, andySigler commented on api/src/opentrons/execute.py
> +            _THREAD_MANAGED_HW = ThreadManager(OT3API.build_hardware_controller)
👍

2022-11-09 21:50 UTC, sfoster1 approved these changes
Looks good to me!

2022-11-09 22:21 UTC, merged