feat(app): organize LabwareSetup to add map vs list view
OpenTrons/opentrons-api pull request #11576
Opened 2022-10-14 20:38 UTC by jerader

closes RCORE-140 RCORE-141

# Overview

With the `liquid setup` FF turned on, you should see a toggle with the labware map view vs list view, with LPC at the bottom and proceed to next step button for both views

<img width="826" alt="Screen Shot 2022-10-14 at 4 20 09 PM" src="https://user-images.githubusercontent.com/66035149/195938411-647b2fa8-55f1-4acf-a2cd-80c1d7acd5b1.png">

# Changelog

This is structured the same way liquid setup is for map/list views
- create a folder `SetupLabware`, create `SetupLabwareList` and `SetupLabwareMap` components.
- `SetupLabware` has both the list and map components + LPC and the proceed to next step button
- `SetupLabwareMap` should be as usual, showering extra attention banners at the top and a deck map with labware and modules
- `SetupLabwareList` should show labware render, display name, nick name (if applicable), slot number, module name (if applicable), extra attention module info (if applicable). Clicking on the extra attention module info renders the correct modal

# Review requests

- turn `Enable Liquid Setup` FF on
- upload a protocol and go to the Labware setup. YOu should see a toggle for Map vs List view. The Map view should be as usual and the list view should contain 1 row of labware info for every labware in the protocol. If its on a module with extra attention needed, it should show the extra attention information (for Thermocycler and Magnetic modules - Heater shaker extra attention information is out of scope)
- clicking on the extra attention information should render the correct modal
- toggle FF off, you should not see any new information about list view, only showing map view

Note: Additional labware section is not included in this PR, H-S extra attention information is out of scope for this PR

# Risk assessment

low

2022-10-14 22:18 UTC, koji commented on app/src/organisms/Devices/ProtocolRun/SetupLabware/SetupLabwareList.tsx
> +  border-radius: 4px;
```suggestion
  border-radius: ${BORDERS.radiusSoftCorners};
```

2022-10-14 22:19 UTC, koji commented on app/src/organisms/Devices/ProtocolRun/SetupLabware/SetupLabwareList.tsx
> +  text-align: left;
probably we can use const from typography.

2022-10-14 22:19 UTC, koji commented on app/src/organisms/Devices/ProtocolRun/SetupLabware/SetupLabwareList.tsx
> +  text-align: left;
TYPOGRAPHY.textAlignLeft

2022-10-14 22:47 UTC, koji commented on app/src/organisms/Devices/ProtocolRun/SetupLabware/SetupLabwareList.tsx
> +            key={index}
maybe use one item from command for key
`command.something`-`index`?

2022-10-14 22:53 UTC, koji commented on app/src/organisms/Devices/ProtocolRun/SetupLabware/SetupLabwareList.tsx
> +      mod => mod === moduleType
mod may remind someone of `%`. probably extraAttentionMod or something would be good.

2022-10-17 20:19 UTC, koji commented on app/src/organisms/Devices/ProtocolRun/SetupLabware/SetupLabwareList.tsx
> +            <Flex flex-Direction={DIRECTION_ROW}>
```suggestion
            <Flex flexDirection={DIRECTION_ROW}>
```

2022-10-17 20:26 UTC, jerader commented on app/src/organisms/Devices/ProtocolRun/SetupLabware/SetupLabwareList.tsx
> +            <Flex flex-Direction={DIRECTION_ROW}>
whooops what i have probably doesn't do anything 😆 thanks for catching this!

2022-10-17 20:29 UTC, koji commented on app/src/organisms/Devices/ProtocolRun/SetupLabware/SetupLabwareList.tsx
> +            <LabwareListItem
This is happing because LabwareListItem is under table but it is using `div` (Flex). div should be replaced by `tr` and `td`.

![Screen Shot 2022-10-17 at 4 27 07 PM](https://user-images.githubusercontent.com/474225/196276557-bda50bd5-eda4-4e5f-8a1a-0f9a8304cd7e.png)

2022-10-17 20:31 UTC, koji requested changes
after turning on FF, the toggle button shows up and it works as expected, however there are 2 warning in dev tool console.
I left the comments on them.

2022-10-18 16:31 UTC, koji commented on app/src/organisms/Devices/ProtocolRun/SetupLabware/__tests__/SetupLabwareList.test.tsx
> +import { renderWithProviders } from '@opentrons/components'
not sure about the order of `_protocolWithMagTempTC` and `renderWithProviders` but i18n should be after them, right?

```suggestion
import { renderWithProviders } from '@opentrons/components'
import _protocolWithMagTempTC from '@opentrons/shared-data/protocol/fixtures/6/transferSettings.json'
import { i18n } from '../../../../../i18n'
```

2022-10-18 16:36 UTC, koji commented on app/src/organisms/Devices/ProtocolRun/SetupLabware/index.tsx
> +import { map } from 'lodash'
probably

```ts
import map from 'lodash/map'
```

2022-10-18 16:49 UTC, koji commented on app/src/organisms/Devices/ProtocolRun/SetupLabware/utils.ts
> +import { reduce } from 'lodash'
```suggestion
import reduce from 'lodash/reduce'
```

2022-10-18 16:52 UTC, koji approved these changes
I don't see any warnings 👍. The changes look good to me.
I just left a few comments on import statements.

2022-10-18 16:55 UTC, jerader commented on app/src/organisms/Devices/ProtocolRun/SetupLabware/index.tsx
> +import { map } from 'lodash'
oops, you're right! thank you! i forgot this is how we should import stuff from lodash

2022-10-18 16:56 UTC, jerader commented on app/src/organisms/Devices/ProtocolRun/SetupLabware/__tests__/SetupLabwareList.test.tsx
> +import { renderWithProviders } from '@opentrons/components'
Yes, i agree with you. good catch. I am unsure where the `_protocolWithMagTempTC` should go but before i18n makes sense

2022-10-18 19:12 UTC, sakibh approved these changes
Left a couple comments but it looks and works great!

2022-10-18 19:12 UTC, sakibh commented on app/src/organisms/Devices/ProtocolRun/SetupLabware/SetupLabwareList.tsx
> +                <RobotWorkSpace
It looks like in certain viewports the SVG size of the labware seem to vary.

![image](https://user-images.githubusercontent.com/14794021/196521993-4da52d1c-ad12-4a20-b389-78cfc10b1374.png)

2022-10-18 19:12 UTC, sakibh commented on app/src/organisms/Devices/ProtocolRun/SetupLabware/__tests__/SetupLaware.test.tsx
>  import {
Just a typo here: the file name should be `SetupLaware.test.tsx` -> `SetupLabware.test.tsx`

2022-10-19 12:44 UTC, merged