Rlab 161 add capacitive probe functions for gripper in the hardware controller
OpenTrons/opentrons-api pull request #11616
Opened 2022-10-25 01:09 UTC by ahiuchingau

# Overview

# Changelog

# Review requests

# Risk assessment

2022-11-03 19:24 UTC, sanni-t commented on api/src/opentrons/hardware_control/scripts/repl.py
> +    def calibrate_gripper(api: ThreadManager[OT3API], probe: GripperProbe) -> Point:
There isn't anything in the steps that would need customization, is there? Like changing the grip force, or performing some manual step in between these steps? Because if not, then we can make `calibrate_gripper` a part of the hardware control API. That way the engine can directly call that method too, and if needed, we can still have the cli script- which would also call the same `calibrate_gripper`.

2022-11-04 20:13 UTC, SyntaxColoring requested changes
Thanks! Assorted questions and comments:

2022-11-04 20:13 UTC, SyntaxColoring commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +    sensor_id: Optional[SensorId] = None,
Do we need this `Optional`, or could we do:

```suggestion
    sensor_id: SensorId = SensorId.S0,
```

2022-11-04 20:13 UTC, SyntaxColoring commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +    )
To match making `sensor_id` non-`Optional`: 

```suggestion
    sensor_info = SensorInformation(SensorType.capacitive, sensor_id, tool)
```

2022-11-04 20:13 UTC, SyntaxColoring commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +    )
Also, this is moot if we're going to adopt the above suggestion, but as a general rule: I think we should avoid expressions like `sensor_id or SensorId.S0`. Instead, we should do `sensor_id if sensor_id is not None else sensor_id`.

The `or` trick is more compact, but it makes it too easy to introduce bugs related to falsey values. For example, we've had bugs in the Python API where checks that were meant for `volume=None` accidentally trigger on `volume=0.0`. And, here, imagine if some future refactor changed the default from `SensorId.S0` to `SensorId.S1`. Then there would be a bug where passing `sensor_id=SensorId.S0` would erroneously default to `SensorId.S1`.

2022-11-04 20:13 UTC, SyntaxColoring commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +    sensor_id: Optional[SensorId] = SensorId.S0,
This looks like a redundant `Optional`.

```suggestion
    sensor_id: SensorId = SensorId.S0,
```

2022-11-04 20:13 UTC, SyntaxColoring commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +        node_id=tool,
To match making `sensor_id` non-`Optional`:

```suggestion
        sensor_type=SensorType.capacitive, sensor_id=sensor_id, node_id=tool
```

2022-11-04 20:13 UTC, SyntaxColoring commented on api/tests/opentrons/hardware_control/test_ot3_api.py
> -        CriticalPoint.XY_CENTER,
Why is this parametrization being removed?

2022-11-04 20:13 UTC, SyntaxColoring commented on api/src/opentrons/hardware_control/types.py
> +    point. This is the same as the GRIPPER_JAW_CENTER for grippers.
I don't really understand our critical point system, so I could be missing something, but this seems like a red flag? Should we either:

* Say that it's an error for calling code to use `XY_CENTER` for a gripper; calling code must use `GRIPPER_JAW_CENTER` instead
* Remove `GRIPPER_JAW_CENTER` and say that calling code should use `XY_CENTER` instead

2022-11-04 20:13 UTC, SyntaxColoring commented on api/src/opentrons/hardware_control/types.py
> +    point. This is the same as the GRIPPER_JAW_CENTER for grippers.
I think the fundamental thing that's confusing me here is that the members of this enum are not actually mutually substitutable. It will never make sense to provide `GRIPPER_FRONT_CALIBRATION_PIN` to a pipette movement function, for example. Should we move gripper stuff to its own enum?

2022-11-04 20:13 UTC, SyntaxColoring commented on api/src/opentrons/hardware_control/ot3api.py
> +        print(f"current target_position: {target_position}")
Left-over debugging statement?
```suggestion
```

2022-11-04 20:13 UTC, SyntaxColoring commented on api/src/opentrons/hardware_control/ot3api.py
> +        print(f"current machine_pos: {machine_pos}")
Another left-over debugging statement?

```suggestion
```

2022-11-04 20:13 UTC, SyntaxColoring commented on api/src/opentrons/hardware_control/instruments/ot3/gripper_handler.py
> +        self._log = self.GH_LOG.getChild(str(id(self)))
Just a question, I don't have a strong opinion either way:

Why do we go to the trouble of setting up a separate logger for each instance? Is the typical module-level `logging.getLogger(__name__)` insufficent?

2022-11-04 20:13 UTC, SyntaxColoring commented on api/src/opentrons/hardware_control/instruments/ot3/gripper_handler.py
> +    async def add_probe(self, probe: GripperProbe) -> None:
It looks like `add_probe()` and `remove_probe()` can be `def`, not `async def`.

2022-11-04 20:13 UTC, SyntaxColoring commented on api/src/opentrons/hardware_control/ot3api.py
> +        start_fresh: bool = False,
Is `start_fresh` used anywhere?

2022-11-04 20:13 UTC, SyntaxColoring commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        sensor_id: Optional[SensorId] = None,
Introducing a new `Optional[SensorId]` parameter doesn't seem good for for these `capacitive_probe()` and `capacitive_pass()` methods. It seems too low-level. And since this class has historically told callers that they don't need to care about the sensor ID, introducing it now would make this class a leaky abstraction.

If anything, it looks like these methods should take a `GripperProbe` instead of a `SensorId`?

I would write it like:

```python
@overload
async def capacitive_probe(
    self,
    mount: Literal[OT3Mount.LEFT, OT3Mount.RIGHT]
    moving: OT3Axis,
    distance_mm: float,
    speed_mm_per_s: float,
    sensor_threshold_pf: float,
    # No gripper probe should be specified for pipette mounts.
):
    pass

@overload
async def capacitive_probe(
    self,
    mount: Literal[OT3Mount.GRIPPER]
    moving: OT3Axis,
    distance_mm: float,
    speed_mm_per_s: float,
    sensor_threshold_pf: float,
    gripper_probe: GripperProbe,
):
    pass

async def capacitive_probe(
    self,
    mount: OT3Mount
    moving: OT3Axis,
    distance_mm: float,
    speed_mm_per_s: float,
    sensor_threshold_pf: float,
    gripper_probe: Optional[GripperProbe] = None,
):
    # Implementation here.
```

Or you could do separate `pipette_capacitive_probe()`/`gripperr_capacitive_probe()` functions, if you prefer that over the `@overload`s.

2022-11-04 20:13 UTC, SyntaxColoring commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    return result
* Where does the magic number `20` come from? Should that be in a named constant or a JSON setting somewhere?
* The first first `hcapi.grip(20)` should be inside the `try`, right?
* Both `hcapi.grip(20)` calls seem to be missing `await`s.
* The `add_gripper_probe()` and `remove_gripper_probe()` calls also seem to be missing `await`s, but I don't think they need to be `async def` in the first place. See my other comment.

2022-11-07 19:35 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/ot3api.py
> +        start_fresh: bool = False,
Artifact from testing, will remove.

2022-11-07 20:02 UTC, ahiuchingau commented on api/tests/opentrons/hardware_control/test_ot3_api.py
> -        CriticalPoint.XY_CENTER,
Because `XY_CENTER` actually makes sense for the gripper as well, it's just the same as the gripper jaw center. See `CriticalPoint` class.

2022-11-08 18:48 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/instruments/ot3/gripper_handler.py
> +        self._log = self.GH_LOG.getChild(str(id(self)))
The log looks more [clear](https://stackoverflow.com/questions/42388844/where-to-configure-logging) to me.

2022-11-08 19:56 UTC, sfoster1 requested changes
Looks really good overall but I think we should make the backend methods take the `GripperProbe` instead of the raw sensor id, and do the conversion in the backend itself as we do with axes.

2022-11-08 19:56 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    return 1 / 2 * (front + rear)
kind of a nit but writing it this way is kind of hard to read for me - can we make it either `0.5 * (front + rear)` or `(front+rear)/2`

2022-11-08 19:56 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    hcapi.grip(20)
some of these seem to be missing `await`s i think?

2022-11-08 19:56 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    hcapi.grip(20)
also can we make the `20` a constant somewhere

2022-11-08 19:56 UTC, sfoster1 commented on api/src/opentrons/hardware_control/types.py
> +    point. This is the same as the GRIPPER_JAW_CENTER for grippers.
@SyntaxColoring It's an interesting question! I also don't love having these enum entries not apply in certain situations. 

The thing is though that the statement "It will never make sense to provide `GRIPPER_FRONT_CALIBRATION_PIN` to a pipette movement function" does not make sense because there are no pipette movement functions - there are only _movement functions_, that can operate on any movable part of the robot. So a function like `move` really should be able to use both the pipette mounts and the gripper mounts as nouns.

Properly expressing the concept 
- if you call this function with `mount.RIGHT` or `mount.LEFT`, you use a `PipetteCriticalPoint`
- if you call this function with `mount.GRIPPER` you use a `GripperCriticalPoint`
requires a certain amount of interplay between value constraints and type constraints that are difficult to express in python's type system, especially without resorting to `Literal`s everywhere. It would certainly require breaking the gripper mount into its own `enum`, and this starts to make all the rest of the code much more complex because now you have to bounce between different mount types.

I think this is something we should put more thought to in the future, but for now, having our code paths properly raise exceptions if they get the wrong kind of critical point is enough.

2022-11-08 19:56 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +    )
True in general yes, but these are enums:
```
>>> class E(enum.Enum):
...   zero = 0
...   one = 1
... 
>>> E.zero
<E.zero: 0>
>>> bool(E.zero)
True
```

No element of `SensorId` is falsy, so this isn't a problem.

2022-11-08 19:56 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        sensor_id: Optional[SensorId] = None,
I agree - `ot3controller` and `ot3simulator` backends are typically the place where we make the transition between hardware controller concepts and `opentrons_hardware` concepts. backend interfaces methods don't take `NodeId`s as arguments and don't return them; they deal with `OT3Axis` elements instead.

2022-11-08 20:44 UTC, SyntaxColoring commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +    )
`SensorId.S0` is falsey because `SensorId` subclasses `int`.

```python
>>> from opentrons_hardware.firmware_bindings.constants import SensorId
>>> bool(SensorId.S0)
False
```

2022-11-08 20:48 UTC, SyntaxColoring commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +        hcapi.grip(20)
After fixing the missing `await`s and testing this on a robot, it seems to be having trouble with this second `grip()` call.

```
Traceback (most recent call last):
 File "/opt/opentrons-robot-server/opentrons/protocol_engine/execution/command_executor.py", line 88, in execute
   result = await command_impl.execute(command.params)  # type: ignore[arg-type]
 File "/opt/opentrons-robot-server/opentrons/protocol_engine/commands/calibration/calibrate_gripper.py", line 70, in execute
   result = await ot3_calibration.calibrate_gripper(
 File "/opt/opentrons-robot-server/opentrons/hardware_control/ot3_calibration.py", line 462, in calibrate_gripper
   await hcapi.grip(20)
 File "/opt/opentrons-robot-server/opentrons/hardware_control/thread_manager.py", line 78, in wrapper
   return await call_coroutine_threadsafe(loop, attr, *args, **kwargs)
 File "/opt/opentrons-robot-server/opentrons/hardware_control/thread_manager.py", line 46, in call_coroutine_threadsafe
   return await wrapped
 File "/opt/opentrons-robot-server/opentrons/hardware_control/ot3api.py", line 1098, in grip
   self._gripper_handler.check_ready_for_grip()
 File "/opt/opentrons-robot-server/opentrons/hardware_control/instruments/ot3/gripper_handler.py", line 121, in check_ready_for_grip
   raise GripError("Gripper is already gripping")
opentrons.hardware_control.instruments.ot3.gripper_handler.GripError: Gripper is already gripping
```

2022-11-09 16:48 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +        hcapi.grip(20)
Oops this should be ungrip

2022-11-16 20:06 UTC, ahiuchingau commented
So I've decided to add a new enum called `InstrumentProbeType` that the backend will take as an argument. 

This enum is used to differentiate capacitive sensors by ID, `InstrumentProbeType.PRIMARY` will always be mapped to `SensorId.S0` and `InstrumentProbeType.SECONDARY` to `SensorId.S1`.

The `Gripper` class will only handle `GripperProbe`. `OT3API` will handle the conversion the gripper probe to `InstrumentProbeType` and pass it down to the backends.

2022-11-16 20:43 UTC, sfoster1 approved these changes
Looks great to me!

2022-11-16 20:46 UTC, SyntaxColoring reviewed
I'm not qualified to assess all the hardware control state-tracking changes, but this looks good to me.

2022-11-16 20:47 UTC, SyntaxColoring approved these changes

2022-11-16 21:02 UTC, merged