refactor(api): engine based heater-shaker module core
OpenTrons/opentrons-api pull request #11625
Opened 2022-10-26 18:48 UTC by TamarZanzouri

# Overview

part of https://opentrons.atlassian.net/browse/RCORE-257.
implement temp deck PAPI via PE commands.

# Changelog

- Added missing sync_client methods.
- Implemented TemeratureModuleCore methods

# Review requests

Implementation makes sense? 

# Risk assessment

Low. will use this implementation when ff is on.

2022-10-26 19:39 UTC, mcous requested changes

2022-10-26 19:39 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +        ).get_plate_target_temperature()
Read target temperature from hardware, not engine state, to preserve existing PAPI behavior for now

2022-10-26 19:39 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +        self._state = engine_client.state.modules
I'm not super confident this is safe, can we revert?

2022-10-26 19:39 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +        return self._state.get_location(self.module_id).slotName
Same comment about going through the full `_engine_client` path

2022-10-26 19:40 UTC, mcous commented on api/tests/opentrons/protocol_api/core/engine/test_temperature_core.py
> +"""Test temperature module core."""
Can we rename this file to match the class name? i.e. `test_temperature_module_core.py`

2022-10-27 00:58 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/temperature_module/set_target_temperature.py
> +    commandType: SetTargetTemperatureCommandType = (
```suggestion
    commandType: SetTargetTemperatureCommandType = "temperatureModule/setTargetTemperature"
```

2022-10-27 00:58 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/temperature_module/set_target_temperature.py
> +    )
```suggestion
```

2022-10-27 00:58 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/temperature_module/set_target_temperature.py
> +        "temperatureModule/setTargetTemperature"
```suggestion
```

2022-10-27 21:22 UTC, mcous approved these changes
Minor method naming and testing for consistency with the magnetic module and other module tests. Looks great, though!

2022-10-27 21:22 UTC, mcous commented on api/src/opentrons/protocol_engine/clients/sync_client.py
> +    def temperature_set_target_temperature(
```suggestion
    def temperature_module_set_target_temperature(
```

2022-10-27 21:22 UTC, mcous commented on api/src/opentrons/protocol_engine/clients/sync_client.py
> +    def temperature_wait_for_target_temperature(
```suggestion
    def temperature_module_wait_for_target_temperature(
```

2022-10-27 21:22 UTC, mcous commented on api/src/opentrons/protocol_engine/clients/sync_client.py
> +    def temperature_deactivate(
```suggestion
    def temperature_module_deactivate(
```

2022-10-27 21:22 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +        self._engine_client.temperature_set_target_temperature(
```suggestion
        self._engine_client.temperature_module_set_target_temperature(
```

2022-10-27 21:22 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +        self._engine_client.temperature_deactivate(module_id=self.module_id)
```suggestion
        self._engine_client.temperature_module_deactivate(module_id=self.module_id)
```

2022-10-27 21:22 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +        self._engine_client.temperature_wait_for_target_temperature(
```suggestion
        self._engine_client.temperature_module_wait_for_target_temperature(
```

2022-10-27 21:22 UTC, mcous commented on api/tests/opentrons/protocol_api/core/engine/test_temperature_module_core.py
> +        mock_engine_client.temperature_set_target_temperature(
```suggestion
        mock_engine_client.temperature_module_set_target_temperature(
```

2022-10-27 21:22 UTC, mcous commented on api/tests/opentrons/protocol_api/core/engine/test_temperature_module_core.py
> +        mock_engine_client.temperature_wait_for_target_temperature(
```suggestion
        mock_engine_client.temperature_module_wait_for_target_temperature(
```

2022-10-27 21:22 UTC, mcous commented on api/tests/opentrons/protocol_api/core/engine/test_temperature_module_core.py
> +    decoy.verify(mock_engine_client.temperature_deactivate(module_id="1234"))
```suggestion
    decoy.verify(mock_engine_client.temperature_module_deactivate(module_id="1234"))
```

2022-10-27 21:22 UTC, mcous commented on api/tests/opentrons/protocol_api/core/engine/test_temperature_module_core.py
> +        )
We should add `times=1` to all these `verify` calls that are checking a single call rather than a sequence of calls

2022-10-27 21:22 UTC, mcous commented on api/tests/opentrons/protocol_engine/clients/test_sync_client.py
> +    result = subject.temperature_set_target_temperature(
```suggestion
    result = subject.temperature_module_set_target_temperature(
```

2022-10-27 21:22 UTC, mcous commented on api/tests/opentrons/protocol_engine/clients/test_sync_client.py
> +def test_temperature_set_target_temperature(
```suggestion
def test_temperature_module_set_target_temperature(
```

2022-10-27 21:22 UTC, mcous commented on api/tests/opentrons/protocol_engine/clients/test_sync_client.py
> +def test_temperature_wait_for_target_temperature(
```suggestion
def test_temperature_module_wait_for_target_temperature(
```

2022-10-27 21:22 UTC, mcous commented on api/tests/opentrons/protocol_engine/clients/test_sync_client.py
> +    result = subject.temperature_wait_for_target_temperature(
```suggestion
    result = subject.temperature_module_wait_for_target_temperature(
```

2022-10-27 21:22 UTC, mcous commented on api/tests/opentrons/protocol_engine/clients/test_sync_client.py
> +def test_temperature_deactivate(
```suggestion
def test_temperature_module_deactivate(
```

2022-10-27 21:22 UTC, mcous commented on api/tests/opentrons/protocol_engine/clients/test_sync_client.py
> +    result = subject.temperature_deactivate(module_id="module-id")
```suggestion
    result = subject.temperature_module_deactivate(module_id="module-id")
```

2022-10-28 17:50 UTC, jbleon95 approved these changes

2022-10-31 18:41 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/conftest.py
> +
```suggestion
@pytest.fixture

```

2022-10-31 20:57 UTC, TamarZanzouri commented
tested on an OT-2 works fine!

2022-10-31 21:03 UTC, mcous approved these changes
🚢

2022-11-01 13:35 UTC, merged