refactor(api): engine based magnetic module core
OpenTrons/opentrons-api pull request #11629
Opened 2022-10-27 02:33 UTC by TamarZanzouri

# Overview

# Changelog

# Review requests

# Risk assessment

2022-10-27 21:49 UTC, mcous reviewed
Early feedback to cut down some stuff that might be giving you grief

2022-10-27 21:49 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +        if height_from_home is not None and height_from_base is not None:
I think we should make a game time decision here and simplify our lives by doing two things:

- Leave `height_from_home` unimplemented in the engine core
    - End goal: deprecate the public `height_from_home` usage of the Magnetic Module context
- Pass `height_from_base` directly to the engine
    - Do not pass go, do not call `calculate_magnet_height`
    - Punt any half-mm and/or offset value weirdness to the hardware API via RET-1242


So, this method ends up something like this:

```python
def engage(
    self,
    height_from_base: Optional[float] = None,
    height_from_home: Optional[float] = None,
) -> None:
    ...
    if height_from_home is not None:
        raise NotImplementedError("MagneticModuleCore.engage with height_from_home not implemented")

    assert(height_from_base is not None, "Expected engage height")
    
    self._engine_client.magnetic_module_engage(
        module_id=self._module_id, engage_height=height_from_base
    )

```

2022-10-27 21:49 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +    }
This should be part of the selector logic in the `LabwareView`, not here in the core

2022-10-27 21:49 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +        )
Since this entire block is just stringing together calls to different `ProtocolEngine` state selectors, you could replace it with a single call to a single (yet to be written) selector. That selector probably won't fit cleanly into one of the stores, so it should likely go into one of the collaborator views, like `GeometryView`

```python
height_from_base = self._engine_client.geometry.get_default_magnet_engage_height(
    module_id=self._module_id,
    offset=offset,
)
```

From there, that call to `get_default_magnet_engage_height` would break down into roughly the same procedure this code already does:

1. Get definition of labware loaded on the given module
2. Read default engage height out of definition
3. Tweak height if definition in that annoying `_MAGDECK_HALF_MM_LABWARE` list
4. Apply `offset`

2022-10-28 17:54 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/geometry.py
> +            self._labware.is_mag_deck_uri_in_half_mil(labware_id)
```suggestion
          self._labware.is_magnetic_module_uri_in_half_millimeters(labware_id)
```

2022-10-28 17:55 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +    def is_mag_deck_uri_in_half_mil(self, labware_id: str) -> bool:
```suggestion
    def is_magnetic_module_uri_in_half_millimeter(self, labware_id: str) -> bool:
```

2022-10-28 18:42 UTC, mcous requested changes
Some organizational requests to simplify the source by getting rid of things we don't need and improve the testability

2022-10-28 18:42 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +                preserve_half_mm=preserve_half_mm,
Let's ignore `preserve_half_mm` in the engine cores; it's there to support old API versions that the engine cores will not need to support

2022-10-28 18:42 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +        )
These three selector calls can be combined into one call if we modify. `get_default_magnet_engage_height` a little We can do this because:

- We're not worrying about half-mm in the engine core, the engine itself will deal with that in the command implementation
    - This means we don't need `module_model`
- With the arguments we're using, all that `calculate_magnet_height` is doing is added `offset` to `default_height`
    - This _also_ means we don't need `module_model`
- Any information from the `ModulesView` or `LabwareView` that we need, the `GeometryView` can compose itself

Really, all we're doing is:

1. Get the engage height in `mm` from the labware definition
2. Add `offset` to that engage height
3. Pass that engage height to the `engage` command

The selectors we call should communicate that intent

```suggestion
        calculated_height = (
            self._engine_client.state.geometry.get_default_magnet_engage_height(
                module_id=self.module_id,
                offset_from_labware_default=offset,
            )
        )
```

2022-10-28 18:42 UTC, mcous commented on api/src/opentrons/protocol_engine/state/geometry.py
> +            )
I'm pretty sure this is the only usage of `get_id_by_module`, so I would make `get_id_by_module` raise some error (e.g. `NoLabwareOnModuleError`) if no labware is found rather than returning `None`.

Also, putting these usage instructions about the Protocol API (`height` and `height_from_base` are Protocol API parameters) all the way down here in the `ProtocolEngine` is inappropriate. If we want to show this error message to the user, the core or the PAPI should catch the engine error and re-raise a `ValueError` or something

2022-10-28 18:42 UTC, mcous commented on api/src/opentrons/protocol_engine/state/geometry.py
> +            )
Same comment on both points

- Raise from `get_default_magnet_height`, not from here
- Do not put details about the PAPI in error messages generated in the ProtocolEngine; it doesn't make sense to all callers of the ProtocolEngine

2022-10-28 18:42 UTC, mcous commented on api/src/opentrons/protocol_engine/state/geometry.py
> +            return default_height / 2.0
This logic should happen in `LabwareView.get_default_magnet_height`, not the `GeometryView` calculator. here's no need to leak "this labware has a weird definition" outside of the `LabwareView`

2022-10-28 18:42 UTC, mcous commented on api/tests/opentrons/protocol_engine/state/test_geometry_view.py
> +    assert result == 3.0
The existing selectors in `GeometryView` are pretty bad about this, so it's not immediately obvious when you're working in here, but rule on thumb: writing a test like this that tests arithmetic on the outputs of several mocks is a sign that something in the code under test should probably be re-organized.

In this case, I might think about making `offset` an argument of `labware_view.get_default_magnet_height`

2022-10-30 01:16 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +    def get_default_magnet_height(self, module_id: str, offset: float) -> float:
Should I change the name to: `get_calculated_magnet_height` ?

2022-10-30 01:17 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
>          """Return a labware's default Magnetic Module engage height.
```suggestion
        """Return a labware's default Magnetic Module engage height with added offset, if supplied.
```

2022-10-31 13:42 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_api_experimental/module_contexts/test_magnetic_module_context.py
> +        subject.engage(offset=input_offset)
not sure why this has a linting issue. its set to Optional[float] in the subject as well

2022-10-31 13:46 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_api_experimental/module_contexts/test_magnetic_module_context.py
> +        subject.engage(offset=input_offset)
not sure why lint is complaining about this. its expecting an Optional[float] and that is what I am giving it?

2022-10-31 13:57 UTC, jbleon95 commented on api/src/opentrons/protocol_engine/state/labware.py
> +        for (key, value) in self.state.labware_by_id.items():
Parentheses unnecessary here. Also, more explicit variable names would read better here
```suggestion
        for labware_id, labware in self.state.labware_by_id.items():
```

2022-10-31 21:08 UTC, mcous approved these changes
🧲

2022-11-01 18:10 UTC, TamarZanzouri commented
Tested all commands on an OT-2. tested with loaded labware as well. Works as expected

2022-11-01 19:13 UTC, merged