feat(ot3): save pipette offset calibrations
OpenTrons/opentrons-api pull request #11649
Opened 2022-10-31 20:09 UTC by Laura-Danielle

## Overview

Closes #RLIQ-78. We should reset the pipette offsets to zero during the calibrate_mount and then save the result of this function afterwards. **Note** there are some refactors that will make this work much nicer which will be addressed in follow-ups that I've listed below.

Refactors:
- Fix imports for calibration storage (in progress)
- Create an `InstrumentCalibrationProvider` class (similar to the `RobotCalibrationProvider`)
- Have the user flows directly use `save_instrument_calibration` and `reset_instrument_calibration` through the api (low priority)
- Tease out the `Pipette` class to better differentiate between an OT2 or OT3 instrument (will be addressed in the next few weeks)

2022-10-31 22:38 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/instruments/ot2/instrument_calibration.py
> +        save_pipette_calibration(
When would we want to call save pipette offset calibration without a pip id?

2022-11-01 17:07 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/ot2/instrument_calibration.py
> +        save_pipette_calibration(
If we want to reset to defaults which is used in the ot-2 calibration flows and also to reset the pipette calibration to factory defaults.

2022-11-08 16:50 UTC, sfoster1 requested changes
Changes mostly look good although the ot2 vs ot3 behavior is pretty confusing as you've noted, can't wait til that gets fixed. 
I think we should add a couple tests around the higher-level offset management behavior in ot3-calibration - make sure that the reset and save offset functions get called at appropriate times

2022-11-08 16:50 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +    async def reset_instrument_offset(
need some tests for these two to check proper mount dispatching

2022-11-08 16:50 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/test_ot3_calibration.py
>          find_deck.return_value = 10
we should test that the offsets get reset before the call and either set to their new values if the calibration succeeds, or set back to their old ones if it fails, after the call

2022-11-08 16:50 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/instrument_calibration.py
> +    if gripper_id and ff.enable_ot3_hardware_controller():
do we need this feature flag check? when could this be called if the flag was off?

2022-11-08 16:50 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot2/pipette_handler.py
> +        Tempoarily rest the pipette offset to default values.
```suggestion
        Temporarily reset the pipette offset to default values.
```

2022-11-10 17:14 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/ot3/instrument_calibration.py
> +    if gripper_id and ff.enable_ot3_hardware_controller():
We don't need it, but theoretically you could import this guy anywhere and call it.

2022-11-14 23:08 UTC, sfoster1 approved these changes
Looks good to me!

2022-11-15 16:04 UTC, merged