Fix/load pipette schema change
OpenTrons/opentrons-api pull request #11658
Opened 2022-11-01 20:30 UTC by TamarZanzouri

# Overview

# Changelog

# Review requests

# Risk assessment

2022-12-07 21:54 UTC, shlokamin approved these changes
JS changes LGTM 😄

2022-12-07 21:54 UTC, shlokamin commented on app/src/organisms/PipetteWizardFlows/BeforeBeginning.tsx
> +            pipetteName: attachedPipette[mount].name,
ooooo we can get rid of this ts expect error if we check to see if `attachedPipette[mount].name` exists with the other null checks on lime 41

2022-12-08 22:00 UTC, SyntaxColoring requested changes

2022-12-08 22:00 UTC, SyntaxColoring commented on shared-data/protocol/schemas/6.json
> +                    "description": "Unique identifier of pipette to load"
I don't think this correctly describes a v6 JSON protocol file.

Protocol Engine `loadPipette` commands, as visible in HTTP endpoints like `GET /runs/{id}/commands`, *do* have a mandatory `pipetteName` field.

But `loadPipette` objects in v6 JSON protocol documents *are different from those Protocol Engine `loadPipette` commands.* Instead of having a `pipetteName`, they have a `pipetteId` that references the document's top-level `pipettes` object, and *that* object has the `pipetteName`. Doing that lookup and resolving this discrepancy is the job of `JsonTranslator` in our Python code.

2022-12-09 20:09 UTC, TamarZanzouri commented
Thanks to @SyntaxColoring attention this change should not be made. Json protocols should not have pipetteName bc they are looking for the pipetteName in the top level pipette dict by pipetteId.

2022-12-09 20:09 UTC, closed without merging