Rcore 306 handle ot3 system update file
OpenTrons/opentrons-api pull request #11685
Opened 2022-11-06 15:37 UTC by vegano1

# Overview
The update-server runs on both the OT2 and OT3 however they have different implementations because the underlying system is different. In order to support this we have an interface that both the OT2 and OT3 use to be able to communicate this updated information both in its internal API and to the clients (electron) apps as well. This adds a new "systemUpdate" capabilities for the openembedded class (OT3) and buildroot class (OT2).

# Changelog
- Added systemUpdate capabilities to buildroot/openemdedded health_endpoints
- Added UPDATE_PKG_BR and UPDATE_PKG_OE to know which file upload fields are accepted by the different updaters
- Added verification of the update using the new robot_model flag in the VERSION.json file so we only install updates whose robot_model matches the running instance.
- Added InvalidPKGName to tell clients if the field name they sent is invalid
- Added InvalidRobotModel to tell clients that the robot_model in the VERSION.json file is invalid
- Renamed openembedded updater to OT3UpdateActions for consistency
- Use context manager when opening hashfile so we dont leave behind open file descriptors
- Moved load_version_file to common so it is shared between the updaters

IMPORTANT: MAKE SURE ANY BREAKING CHANGES ARE PROPERLY COMMUNICATED
-->

# Review requests

# Risk assessment

2022-11-07 14:14 UTC, sfoster1 reviewed
Code looks good to me, but haven't tested yet so won't approve (and we want the extra tests as you noted in the PR description of course)

2022-11-07 14:14 UTC, sfoster1 commented on update-server/otupdate/common/file_actions.py
> +        logging.exception(f"Could not load version file - {version_file}")
```suggestion
        LOG.exception(f"Could not load version file - {version_file}")
```

2022-11-11 20:41 UTC, sfoster1 requested changes
Couple nits about logging, and also a debug print; functionality looks good though!

2022-11-11 20:41 UTC, sfoster1 commented on update-server/otupdate/common/update.py
> +    body called 'system-update.zip' or 'ot2-system.zip'.
[nit] we should just call out `system-update.zip` here, with maybe a note that ot2s will also support `ot2-system.zip`

2022-11-11 20:41 UTC, sfoster1 commented on update-server/otupdate/common/update.py
> +            LOG.info(f"Downloading {part.name}")
[nit] i really don't like the use of "downloading" here - imo "downloading" means a server->client data transfer, and this is a client->server.

also, it really is just writing this data. let's remove some of these log changes.

2022-11-11 20:41 UTC, sfoster1 commented on update-server/tests/common/test_update.py
> +        print("YOO", body)
debug print

2022-11-15 19:46 UTC, shlokamin approved these changes
Tested OT-2 + OT-3 system updates and this works like a charm!

Only thing to note is that my capabilities map for the OT-2 looks like this: 

```
"capabilities": {"systemUpdate": "/server/update/begin", "buildrootUpdate": "/server/update/begin", "restart": "/server/restart"}

```

which is slightly different than this: 

> - [x] Make sure OT2 reports buildroot/systemUpdate capabilities in **server/update/health** endpoint

2022-11-15 21:23 UTC, vegano1 commented
> Tested OT-2 + OT-3 system updates and this works like a charm!
> 
> Only thing to note is that my capabilities map for the OT-2 looks like this:
> 
> ```
> "capabilities": {"systemUpdate": "/server/update/begin", "buildrootUpdate": "/server/update/begin", "restart": "/server/restart"}
> ```
> 
> which is slightly different than this:
> 
> > * [ ]  Make sure OT2 reports buildroot/systemUpdate capabilities in **server/update/health** endpoint

yep, forgot to update the comment but that looks good!

2022-11-16 15:37 UTC, sfoster1 approved these changes
Looks awesome to me!

2022-11-16 17:38 UTC, merged