Refactor/dispense papi pe
OpenTrons/opentrons-api pull request #11689
Opened 2022-11-07 20:07 UTC by TamarZanzouri

# Overview

# Changelog

# Review requests

# Risk assessment

2022-11-07 21:21 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/instrument_context.py
> +            well_parent = location.parent.parent
I can maybe implement this logic in PE and in the legacy if its better

2022-11-08 16:41 UTC, jbleon95 commented on api/src/opentrons/protocol_api/instrument_context.py
> +            well_parent = location.parent.parent
this should be `location.parent`

2022-11-09 18:11 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/well.py
> +        """Check if well is a fixed trash."""
```suggestion
        """Check if given well is a fixed trash."""
```

2022-11-09 18:12 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/protocol_api/well.py
> +
```suggestion
```

2022-11-09 18:49 UTC, jbleon95 commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        rate: float,
For consistency with aspirate we should add a flow_rate argument here so we are only calling `get_absolute_dispense_flow_rate` once in the public context

2022-11-09 18:50 UTC, jbleon95 commented on api/src/opentrons/protocol_api/core/protocol_api/instrument_context.py
> +        self.move_to(location=location, well_core=well_core)
well_core argument does not need to be included here

2022-11-09 20:05 UTC, mcous requested changes
This is looking pretty good, but we need to revert the change to the public `Well` API

2022-11-09 20:05 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +    ) -> None:
Can we add a docstring with argument descriptions, especially noting that `rate` is not used? Looks like we're missing that on `aspirate`, too, if it's easy to add at once

2022-11-09 20:05 UTC, mcous commented on api/src/opentrons/protocol_api/labware.py
> +    def is_fixed_trash(self) -> bool:
We should not be adding methods to the public protocol APIs, of which `Well` is one

2022-11-09 20:05 UTC, mcous commented on api/src/opentrons/protocol_api/core/well.py
> +        ...
Reading through this, it seems like method would be more appropriate on the labware core, not the well core, because it's got nothing to do with the well

2022-11-09 20:05 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +            if location.is_fixed_trash():
Same comment: do not add new methods to the public `Well` class. Go through the cores, e.g.

```python
if well.parent._implemenation.is_fixed_trash():
    ...
```

2022-11-09 20:05 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +                dest = location.top()
Can we avoid abbreviated variable names like this in new code? The existing code is riddled with `dest` and `loc` and other little variables that, for me, make the data flows really tough to figure out.

I'd suggest either `location` or `move_to_location`. It looks like `aspirate` is suffering the same problem, even after #11667, too

2022-11-09 20:59 UTC, mcous approved these changes
Unable to test on a device because at home, but code LGTM!

2022-11-09 20:59 UTC, mcous commented on api/src/opentrons/protocol_api/core/simulator/instrument_context.py
> +        self.move_to(location=location, well_core=well_core)
`well_core` not needed here

2022-11-09 20:59 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +    )
Are we missing a test for no location given (i.e. going of the location cache)?

2022-11-09 21:11 UTC, TamarZanzouri commented
Tested on an OT3! works as expected!

2022-11-09 21:11 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +    )
I will!

2022-11-09 21:12 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/simulator/instrument_context.py
> +        self.move_to(location=location, well_core=well_core)
yep but just after I merge edge into this branch

2022-11-10 15:36 UTC, mcous reviewed
Code still looks good, new docstrings should be written [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html), though

2022-11-10 15:36 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        """
Please use Google-style doc strings in internal classes, per our flake8 config.

Eventually we'll be able to move the docstrings of the public classes over to this style, too.

```suggestion
        """Aspirate a given volume of liquid from the specified location.

        Args:
            volume: The volume of liquid to aspirate, in microliters.
            location: The exact location to aspirate from.
            well_core: The well to aspirate from, if applicable.
            rate: Not used in this core.
            flow_rate: The flow rate in µL/s to aspirate at.
        """
```

2022-11-10 15:36 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        """
Google-style docstrings to follow latest docstring conventions, including those used by other methods in this file

```suggestion
        """Dispense a given volume of liquid into the specified location.

        Args:
            volume: The volume of liquid to dispense, in microliters.
            location: The exact location to dispense to.
            well_core: The well to dispense to, if applicable.
            rate: Not used in this core.
            flow_rate: The flow rate in µL/s to dispense at.
        """
```

2022-11-10 15:36 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/labware.py
> +        """Check if given well is a fixed trash."""
```suggestion
        """Whether the labware is a fixed trash."""
```

2022-11-10 16:07 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/protocol_api/labware.py
> +        """Check if given well is a fixed trash."""
```suggestion
        """Whether the labware is fixed trash."""
```

2022-11-10 16:52 UTC, merged