feat(hardware): add other sensors to monitor_sensors
OpenTrons/opentrons-api pull request #11693
Opened 2022-11-08 16:36 UTC by caila-marashaj

Just adds arguments for pressure and environment sensors to `monitor_sensors.py` to allow streaming sensor values to terminal- this should be all we need to send the correct `BindSensorOutput` messages

2022-11-08 16:36 UTC, sfoster1 approved these changes

2022-11-08 16:43 UTC, Laura-Danielle requested changes
The environment sensor has two outputs (humidity and temperature) so we'll need to adjust the output based on that.

I think it would also be good to also print the raw output of each sensor for debugging purposes.

2022-11-14 17:36 UTC, fsinapi approved these changes
Tested these changes on a robot and LGTM! The environment sensor just prints out a different line for humidity and temperature.

2022-11-14 19:18 UTC, Laura-Danielle approved these changes
Fine to merge for now. Will put up a separate PR to use the sensor driver in this script.

2022-11-14 19:58 UTC, merged