feat(ot3): add shared data support for ot3 pipettes
OpenTrons/opentrons-api pull request #11704
Opened 2022-11-09 19:32 UTC by Laura-Danielle

# Overview

We need a better way to encapsulate the new functionality that ot3 pipettes has, as well as the
types of pipettes available. I will be splitting up this work into a series of bits of work ticketed [here](https://opentrons.atlassian.net/browse/RLIQ-249).

# Changelog

- Bump the schema version on the pipettes (for now only GEN 3s are supported)
- Split out the pipette schemas into more "reasonable" sections that are also easier to use

# Review requests

- Can someone make sure my js tests are all actually running correctly?
- Anything else you think is missing from the schemas?
- Anything you don't like about the schemas as they are set-up now?

# Risk assessment

Low. Not being used yet.

2022-11-09 21:46 UTC, sfoster1 requested changes, later dismissed
This is so much nicer!

That said,
- let's get the new schema data in the README
- can you say a little more in the README and/or pr description about what the 3d files are for?
- can you say a little more in the README and/or pr description about what the `T200`/`T50` things are for and how they'll be used?

2022-11-09 21:46 UTC, sfoster1 commented on shared-data/pipette/definitions/2/geometry/eight_channel/p50/1.json
> +  "pathTo3D": "pipette/definitions/2/eight_channel/p1000/placeholder.gltf",
?

2022-11-10 21:18 UTC, koji commented on shared-data/js/__tests__/pipetteSchemaV2.test.ts
> +    const filename = path.parse(liquidPath).base
As CI says, you don't use `filename`. Maybe just remove this line?

2022-11-11 15:07 UTC, andySigler requested changes
Went through and checked config values based off values we're currently using in testing

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/single_channel/p50/1.json
> +    "opentrons/opentrons_96_tiprack_20ul/1",
If this file represents the GEN3 p50, then I believe this pipette is only compatible with the newer generation of tips, so the tips listed here would not work. The default tiprack would be `opentrons_ot3_96_tiprack_50ul`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/single_channel/p50/1.json
> +    "defaultAspirateFlowRate": 20,
`defaultAspirateFlowRate` and `defaultDispenseFlowRate` should be `8`, and `defaultBlowoutFlowRate` is `4`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/single_channel/p1000/1.json
> +    "defaultAspirateFlowRate": 20,
`6`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/single_channel/p1000/1.json
> +    "defaultDispenseFlowRate": 20,
`6`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/single_channel/p1000/1.json
> +    "defaultBlowOutFlowRate": 20,
`80`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/single_channel/p1000/1.json
> +    "defaultAspirateFlowRate": 20,
aspirate/dispense/blowout speeds for T200 on the P1000 are all `80`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/single_channel/p1000/1.json
> +    "defaultAspirateFlowRate": 20,
aspirate=`160`
dispense=`160`
blowout=`80`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/single_channel/p1000/1.json
> +    "opentrons/opentrons_96_tiprack_20ul/1",
same as P50, the GEN3 P1000 is only compatible with:
- `opentrons_ot3_96_tiprack_1000ul`
- `opentrons_ot3_96_tiprack_200ul`
- `opentrons_ot3_96_tiprack_50ul`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/geometry/single_channel/p50/1.json
> +  "nozzleOffset": [-0.5, -22.0, -259.15]
`"nozzleOffset": [-8.0, -22.0, -259.15]`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/geometry/single_channel/p1000/1.json
> +  "nozzleOffset": [-0.5, -22.0, -259.15]
`"nozzleOffset": [-8.0, -22.0, -259.15],`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/geometry/eight_channel/p50/1.json
> +  "nozzleOffset": [-0.5, -16.0, -259.15]
`"nozzleOffset": [-8.0, -16.0, -259.15],`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/geometry/eight_channel/p1000/1.json
> +  "nozzleOffset": [-0.5, -16.0, -259.15]
`"nozzleOffset": [-8.0, -16.0, -259.15],`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/general/single_channel/p50/1.json
> +    "current": 0.4,
`"current": 0.15,` (yes this is different than what is currently in `edge` but we know that `0.15` is a better value than `0.25`)

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/general/single_channel/p1000/1.json
> +    "current": 0.4,
`"current": 0.15`, (yes this is different than what is currently in `edge` but we know that `0.15` is a better value than `0.25`)

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/general/single_channel/p1000/1.json
> +    "increment": 0.5,
`"increment": 0.0,`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/general/single_channel/p1000/1.json
> +    "distance": 1.0
`"distance": 13.0`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/general/single_channel/p50/1.json
> +    "increment": 0.5,
`"increment": 0.0,`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/general/single_channel/p50/1.json
> +    "distance": 1.0
`"distance": 13.0`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/general/eight_channel/p50/1.json
> +    "current": 0.4,
`"current": 0.5,`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/general/eight_channel/p50/1.json
> +    "increment": 0.5,
`"increment": 0.0,`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/general/eight_channel/p50/1.json
> +    "distance": 1.0
`"distance": 13.0`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/general/eight_channel/p50/1.json
> +    "drop": 90.5
`"drop": 92.5`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/general/eight_channel/p1000/1.json
> +    "current": 0.4,
`"current": 0.5,`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/general/eight_channel/p1000/1.json
> +    "increment": 0.5,
`"increment": 0.0,`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/general/eight_channel/p1000/1.json
> +    "distance": 1.0
`"distance": 13.0`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/general/eight_channel/p1000/1.json
> +    "drop": 90.5
`"drop": 92.5`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/eight_channel/p1000/1.json
> +    "defaultAspirateFlowRate": 20,
aspirate=`6`
dispense=`6`
blowout=`80`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/eight_channel/p1000/1.json
> +    "defaultAspirateFlowRate": 20,
aspirate=`80`
dispense=`80`
blowout=`80`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/eight_channel/p1000/1.json
> +    "defaultAspirateFlowRate": 20,
aspirate=`160`
dispense=`160`
blowout=`80`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/eight_channel/p1000/1.json
> +    "opentrons/opentrons_96_tiprack_20ul/1",
this pipettes is only compatible with tipracks:

- `opentrons_ot3_96_tiprack_50ul`
- `opentrons_ot3_96_tiprack_200ul`
- `opentrons_ot3_96_tiprack_1000ul`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/eight_channel/p50/1.json
> +    "defaultAspirateFlowRate": 20,
aspirate=`8`
dispense=`8`
blowout=`4`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/eight_channel/p50/1.json
> +    "opentrons/opentrons_96_tiprack_20ul/1",
this pipette is only compatible with `opentrons_ot3_96_tiprack_50ul`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/ninety_six_channel/p1000/1.json
> +    "defaultAspirateFlowRate": 20,
aspirate=`6`
dispense=`6`
blowout=`80`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/ninety_six_channel/p1000/1.json
> +    "defaultAspirateFlowRate": 20,
aspirate/dispense/blowout all = `80`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/ninety_six_channel/p1000/1.json
> +    "defaultAspirateFlowRate": 20,
aspirate/dispense=`160`
blowout=`80`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/ninety_six_channel/p1000/1.json
> +  "defaultTipracks": []
This pipette is only compatible with:

- `opentrons_ot3_96_tiprack_50ul`
- `opentrons_ot3_96_tiprack_200ul`
- `opentrons_ot3_96_tiprack_1000ul`

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/general/ninety_six_channel/p1000/1.json
> +    "top": 1,
top=`0`
bottom=`66`
blowout=`71`
drop=`null` (???)

2022-11-11 15:07 UTC, andySigler commented on shared-data/pipette/definitions/2/general/ninety_six_channel/p1000/1.json
> +  "pickUpTipConfigurations": {
I'm not sure where exactly to find the correct motor currents, but I bet you've got access to them from your work on 96head FW

2022-11-14 22:45 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/liquid/single_channel/p1000/1.json
> +    "defaultBlowOutFlowRate": 20,
Is this actually the correct value? Seems significantly higher than defaults for aspirate/dispense flow rate.

2022-11-14 22:49 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/general/single_channel/p50/1.json
> +    "increment": 0.5,
Is the current also 0.15 for the p50 single?

2022-11-14 22:59 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/general/ninety_six_channel/p1000/1.json
> +  "pickUpTipConfigurations": {
Will probably adjust these values in a separate PR.

2022-11-15 16:18 UTC, mcous reviewed
I've got a couple tiny comments with an eye towards RCORE-382 and some yet-to-be-written PAPI tickets for 96-channel support, but otherwise this looks really solid and a vast improvement over the old configs

2022-11-15 16:18 UTC, mcous commented on shared-data/pipette/schemas/2/pipetteLiquidPropertiesSchema.json
> +      "^T[0-9]{2,4}": {
A couple notes:

- Pattern properties are not easy to to map into Pedantic and other runtime models
- I would softly prefer lowercase identifiers to upper or mixed-case

Could this be a list instead with a string field for the `t50` (or whatever) portion?

2022-11-15 16:18 UTC, mcous commented on shared-data/pipette/schemas/2/pipettePropertiesSchema.json
> +    },
This specific capabilities list is a little hard to understand coming in blind. Can we make one of both of these changes?

- Change to a list so we can define new sensors without changing the schema?
- Do something like `pressure: { count: number }` rather than `pressure: number` to make it more obvious what's going on when reading the data?

As an aside, how is the sensor count data used?

2022-11-15 16:49 UTC, Laura-Danielle commented on shared-data/pipette/schemas/2/pipettePropertiesSchema.json
> +    },
It is not currently used, but it will be used in the expanded pipette object class for ot3 pipettes to know how many sensor objects to build (will mainly be used for liquid sensing purposes)

2022-11-15 17:15 UTC, Laura-Danielle commented on shared-data/pipette/schemas/2/pipetteLiquidPropertiesSchema.json
> +      "^T[0-9]{2,4}": {
I can definitely make it a list of objects.

2022-11-15 18:30 UTC, andySigler approved these changes

2022-11-15 20:15 UTC, Laura-Danielle commented on shared-data/pipette/schemas/2/pipettePropertiesSchema.json
> +    },
@mcous what do you think about this:

Available sensors is still an object that contains:

- A list of available sensors (can be anything)
- A pattern property which is keyed by sensor type and the object it contains is `{count: number}`

Then, an available sensors object might look like:
```
availableSensors: {
   sensors: ["pressure", "capacitive", "environment"],
   "pressure": {count: 2},
    "capacitive": {count: 1},
    "environment": {count: 1}
}
```

2022-11-15 20:23 UTC, Laura-Danielle commented on shared-data/pipette/schemas/2/pipetteLiquidPropertiesSchema.json
> +      "^T[0-9]{2,4}": {
@mcous could I wrap the tip types in a top level key instead? I.e.:

```
supportedTips: {
  t50 {...},
  t200 {...},
}
```
etc? That way I can load the pydantic models based on the guaranteed keys inside each nested "tip" object and then I can use the top level pattern property keys to create a look-up table.

2022-11-16 15:57 UTC, sfoster1 approved these changes
Looks awesome!

2022-11-16 16:16 UTC, merged