feat(engine): grip at the end of labware movement, home gripper instead of moving up
OpenTrons/opentrons-api pull request #11751
Opened 2022-11-16 22:35 UTC by sanni-t

Addresses RLAB-210

# Overview

# Changelog

# Review requests

# Risk assessment

2022-11-17 01:01 UTC, SyntaxColoring approved these changes
Thanks! Protocol Engine changes look good to me if we figure out the deal with the integration test failure. I'm not totally following the `ot3api.py` changes, so I'll leave that to other reviewers, or we can talk about it in person.

2022-11-17 15:20 UTC, Laura-Danielle requested changes

2022-11-17 15:20 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +        if mount != OT3Mount.GRIPPER:
I'm not sure why we need this change in cache and retract.

2022-11-17 15:20 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/execution/labware_movement.py
> +        #       Remove once collisions & recovery are fixed.
*note* this will not be fixed soon. I think the ultimate solution is to add an encoder to this axis which will require another board rev. We should create a spike ticket, if we haven't already.

2022-11-17 15:20 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/execution/labware_movement.py
> +        # await ot3api.move_to(
Why is this commented out?

2022-11-17 15:20 UTC, Laura-Danielle commented on api/tests/opentrons/protocol_engine/execution/test_labware_movement_handler.py
> +        # await ot3_hardware_api.move_to(
Can we also not have commented out code here and/or put it in a nice codeblock with an explanation that we should revert back to this change afterwards.

2022-11-17 15:20 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +        if mount != OT3Mount.GRIPPER:
And if you want this to be a default behavior during a "retract", we should add this check in the `def retract` function.

Although, I was hoping we could keep this at a protocol level (i.e. put a grip at the beginning of all gripper protocols right now) because I'm worried we'll forget about this otherwise. If we absolutely want to have it here, we should also create a spike ticket to track this.

2022-11-17 17:58 UTC, sanni-t commented on api/src/opentrons/protocol_engine/execution/labware_movement.py
> +        # await ot3api.move_to(
Because it's being replaced by the home call. It's commented out instead of completely removing because we might want to go back to using it.

2022-11-17 18:01 UTC, sanni-t commented on api/src/opentrons/hardware_control/ot3api.py
> +        if mount != OT3Mount.GRIPPER:
Putting it at the beginning of protocols will only solve the collision problem for movements during a protocol run. It won't prevent them during LPC or direct http command usage.

2022-11-18 15:41 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +        if (
can we add this logic in the `retract` function rather than `_cache_and_maybe_retract_mount`?

2022-11-18 17:57 UTC, sanni-t commented on api/src/opentrons/hardware_control/ot3api.py
> +        if mount != OT3Mount.GRIPPER:
Good call on creating a ticket to track these changes and revert later if needed (separate from the collision recovery or motion planning tickets). Creating one.

2022-11-21 05:30 UTC, sanni-t commented on api/src/opentrons/hardware_control/ot3api.py
> +        if (
`retract` function is called only to retract the last used mount when it's not the current mount while we want the jaws to grip as long as the current mount isn't the gripper. So we'll have to update the signature of the `retract` function a little in order to use it for this purpose. But you are right that the logic feels a bit out of place in the `cache_and_maybe_retract` function so I moved it to  its own private `_move_gripper_to_idle_position` function. This also makes it easy to remove later if required. Let me know if that works for you.

2022-11-21 14:57 UTC, sanni-t commented on shared-data/python/opentrons_shared_data/gripper/constants.py
> +IDLE_STATE_GRIP_FORCE: float = 10  # Newtons
We found that a force of 5N was enough to keep the jaws held in gripped position, however, such a low force corresponded to the jaws moving to the gripped position too slowly. Ideally we would move the jaws to a fixed distance with full speed and then reduce the gripping force to a lower value. But this works as a quick fix.

2022-11-21 15:03 UTC, sanni-t commented
Tested on an OT3 and verified that pipetting from TC to slots to 11 & 8 and to trash completed without collision, also was able to move an idle gripper between TC & adjacent slots without collision. @b-cooper tested that LPC succeeded without issues and the following protocol completed successfully:
```
from opentrons.protocol_api import ProtocolContext
from opentrons.types import Mount

######### Initial Deck Setup #########
# Slot 1: Tiprack- opentrons_ot3_96_tiprack_50ul
# Slot 5: Armadillo 96 wellplate loaded here
# Slot 8: Armadillo 96 wellplate moved here
# Slot 11: Armadillo 96 wellplate moved here
# Slot 7: Thermocycler, Armadillo 96 wellplate loaded here. 
# Slot 4: Armadillo 96 wellplate moved here from thermocycler
# 
######################################

metadata = {
    "name": "Gripper collision avoidance test protocol",
}

requirements = {
    "robotType": "OT-3",
    "apiLevel": "2.13",
}


def run(protocol: ProtocolContext) -> None:
    """Simple gripper test protocol."""
    tip_rack = protocol.load_labware(
        "opentrons_ot3_96_tiprack_50ul",
        location="1",
    )
    well_plate_1 = protocol.load_labware(
        "armadillo_96_wellplate_200ul_pcr_full_skirt",
        location="5",
    )

    pipette = protocol.load_instrument("p50_single_gen3", mount=Mount.RIGHT, tip_racks=[tip_rack])
    thermocycler = protocol.load_module("thermocyclerModuleV2")
    well_plate_2 = thermocycler.load_labware("armadillo_96_wellplate_200ul_pcr_full_skirt")

    thermocycler.open_lid()
    pipette.pick_up_tip()
    pipette.aspirate(10, well_plate_1['A1'])
    pipette.dispense(10, well_plate_2['A1'])

    protocol.move_labware(
        labware=well_plate_1,
        new_location="8",
        use_gripper=True,
    )

    pipette.aspirate(10, well_plate_1['A1'])
    pipette.dispense(10, well_plate_2['A1'])

    protocol.move_labware(
        labware=well_plate_1,
        new_location="11",
        use_gripper=True,
    )
    pipette.aspirate(10, well_plate_1['A1'])
    pipette.dispense(10, well_plate_2['A1'])

    pipette.aspirate(10, well_plate_2['A1'])
    pipette.blow_out()

    # Uncomment this to test if the gripper is able to keep moving after a collision
    protocol.move_labware(
        labware=well_plate_2,
        new_location="4",       # Empty slot
        use_gripper=True,
    )
```

2022-11-21 15:13 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +        if (
yes that works as well.

2022-11-21 15:13 UTC, Laura-Danielle approved these changes
nice looks good to me.

2022-11-21 15:37 UTC, ahiuchingau requested changes
Since we will need to re-evaluate this collision measure further for future gripper builds, let's contain the changes in HCApi.

2022-11-21 15:37 UTC, ahiuchingau commented on api/src/opentrons/protocol_engine/execution/labware_movement.py
> +        await ot3api.grip(force_newtons=IDLE_STATE_GRIP_FORCE)
Rather than calling `grip()` here and import `IDLE_STATE_GRIP_FORCE` in protocol engine, could we contain this temporary fix in hardware controller and make `ot3api.move_gripper_to_idle_position()` a public method and use it here instead?

2022-11-21 16:04 UTC, sanni-t commented on api/src/opentrons/protocol_engine/execution/labware_movement.py
> +        await ot3api.grip(force_newtons=IDLE_STATE_GRIP_FORCE)
True, we definitely want as much of hardware-specific behavior to be contained in HCapi. However, the `_move_gripper_to_idle_position()` function is very specific to moving jaws before any other mount moves. We can create a different public method that just moves the gripper to idle position unconditionally and have the above private function delegate to it. But I would rather punt that to later when we address these things-
1. Move fast to the grip position and then switch to a lower grip force for idle position
2. Have two separate gripping functions- one for labware gripping and other for idle gripping so that we won't have to specify the default grip force in protocol engine.

I'll create a ticket to handle this if it sounds good to you

2022-11-21 17:14 UTC, sanni-t commented on api/src/opentrons/protocol_engine/execution/labware_movement.py
> +        await ot3api.grip(force_newtons=IDLE_STATE_GRIP_FORCE)
https://opentrons.atlassian.net/browse/RLAB-217

2022-11-21 18:04 UTC, ahiuchingau approved these changes

2022-11-21 19:29 UTC, merged