feat (api, shared_data): Allow loading a 96 channel pipette in a protocol
OpenTrons/opentrons-api pull request #11767
Opened 2022-11-21 19:10 UTC by TamarZanzouri

# Overview

closes [RLIQ-260](https://opentrons.atlassian.net/browse/RLIQ-260).
Allow 96 channel pipette to load when using load_instrument in python public api/protocol engine.

# Changelog

- Added pipette name to `PipetteName`, `PipetteNameType`
- Added corresponding objects with dummy data to shared_data `pipette/definitions/pipetteNameSpecs.json` and `pipette/definitions/pipetteModelSpecs.json`
- Added conditions to public python api to validate 96 channel pipette load.

# Review requests

I was not able to to accommodate loading a 96 channel pipette without adding a value in `PipetteNameType`.
1. does the changes make sense?
2. is there a better way to accommodate this change?
3. am I missing tests? 

# Risk assessment

medium. added a new pipette definition. need to smoke test and test on a robot. This was tested on a dev server with OT3 FF on and off. analysis passes.

2022-11-22 19:51 UTC, TamarZanzouri commented
Tested on an OT-3. Analysis passed!

2022-11-22 19:52 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +            if isinstance(pipette.pipetteName, PipetteNameType)
should probably check against str type instead of importing.

2022-11-22 20:42 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/protocol_context.py
> +from .core.engine.protocol import ProtocolCore as EngineCore
```suggestion
from .core.engine.protocol import ProtocolCore as ProtocolEngineCore
```

2022-11-22 20:43 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/protocol_context.py
> +        if is_96_channel and isinstance(self._implementation, EngineCore):
```suggestion
        if is_96_channel and isinstance(self._implementation, ProtocolEngineCore):
```

2022-11-22 20:44 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +                else "p1000_96"
```suggestion
                else pipette_name
```

2022-11-23 15:04 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/protocol_context.py
>          checked_mount = validation.ensure_mount(mount)
move this into the not 96 channel

2022-11-23 15:07 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/protocol_context.py
> +        if is_96_channel:
remove this condition and set the mount

2022-11-23 15:13 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/clients/sync_client.py
> +            params=commands.LoadPipetteParams.construct(
remove construct

2022-11-23 15:14 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/load_pipette.py
> +    pipetteName: Union[PipetteNameType, Literal["p1000_96"]] = Field(
add todo

2022-11-23 15:16 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/types.py
> +    pipetteName: Union[PipetteNameType, Literal["p1000_96"]]
add todo

2022-11-23 15:20 UTC, TamarZanzouri commented on shared-data/python/opentrons_shared_data/pipette/dev_types.py
> +    "p1000_96",
add todo

2022-11-23 15:22 UTC, mcous approved these changes

2022-11-23 16:30 UTC, Laura-Danielle requested changes
Some small and larger change requests. Let me know if you have questions.

2022-11-23 16:30 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +        from opentrons.protocol_api import Labware
what typing errors is this causing that you can't directly do a top level import, out of curiosity?

2022-11-23 16:30 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        return (
We should put a TODO that this can be reverted to the previous method once the pipette configuration/data models are done (which I am actively working on).

2022-11-23 16:30 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +        self, instrument_name: Union[PipetteNameType, Literal["p1000_96"]], mount: Mount
Same here about adding a TODO. Eventually we shouldn't need this Union.

2022-11-23 16:30 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/protocol_context.py
> +        is_96_channel = instrument_name == "p1000_96"
Why aren't we adding this to the `ensure_pipette_name` validation function?

2022-11-23 16:30 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/protocol_context.py
> +            self._instruments[Mount.RIGHT] = instrument
I am a little concerned about this approach moving into the future. Ideally we should "disable" the right mount completely if a 96 channel is loaded into a protocol. The right mount does not move at all (in fact it is free spinning in the 96 channel configuration) and we should only command actions with the left mount.

2022-11-23 16:30 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +            cache_request[other_mount.to_hw_mount()] = (
Shouldn't we raise an error here rather than modify the request to be a 96 channel? This behavior seems confusing/unexpected otherwise.

2022-11-23 16:30 UTC, Laura-Danielle commented on api/tests/opentrons/protocol_api_old/test_context.py
> -def test_load_instrument(name, ctx):
why did we delete this test?

2022-11-23 16:30 UTC, Laura-Danielle commented on shared-data/pipette/definitions/pipetteModelSpecs.json
> +      "name": "p1000_96",
Do you need this change for tests to pass, otherwise I would default to leaving it out.

2022-11-23 16:30 UTC, Laura-Danielle commented on shared-data/pipette/definitions/pipetteModelSpecs.json
> +      "name": "p1000_96",
If you are worried about things not being fully supported when going into edge, you can merge this into my feature branch: `RLIQ-131-support-96-channel`

2022-11-23 16:51 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +        from opentrons.protocol_api import Labware
This is to solve a circular dependency now that we are importing engine core in the public api

2022-11-23 16:55 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/protocol_context.py
> +        is_96_channel = instrument_name == "p1000_96"
I tired to avoid changing methods that support PipetteNameType and left 96 channel changes as transparent as I can bc we are going to remove these changes once the refactor is done.

2022-11-23 16:57 UTC, TamarZanzouri commented on shared-data/pipette/definitions/pipetteModelSpecs.json
> +      "name": "p1000_96",
Had to add these changes so that the HC layer wont fail when trying to to load a 96 channel pipette. if `RLIQ-131-support-96-channel` contains the changes needed for that I can totally remove these changes.

2022-11-23 18:38 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +            cache_request[other_mount.to_hw_mount()] = (
nice catch! I agree! if the other pipette is set and we are loading a 96 channel pipette we should probably raise an exception

2022-11-23 18:42 UTC, mcous commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +            cache_request[other_mount.to_hw_mount()] = (
Can we punt this to a TODO? This will not be our production 96 channel logic, and the only reason we have to pass in whatever else is attached is because the hardware API doesn't give us a better API than `cache_instruments` to say say "verify that this pipette is attached to this mount"

2022-11-23 18:48 UTC, mcous commented on api/tests/opentrons/protocol_api_old/test_context.py
> -def test_load_instrument(name, ctx):
I'm guessing due to the addition of the temporary 96 channel config, which won't load on the right.

Everything in `api/tests/opentrons/protocol_api_old` is being replaced by new tests in `api/tests/opentrons/protocol_api`. Pipette loading behavior is already being covered by new tests.

In general, we've been preserving the old suite where it is easy to do so, and deleting tests when it is not. Eventually, the entire `protocol_api_old` suite will likely be deleted

2022-11-23 18:50 UTC, mcous commented on api/src/opentrons/protocol_api/protocol_context.py
> +            self._instruments[Mount.RIGHT] = instrument
This is not where that logic will live in the future. This general approach of this PR is "do as little as possible so the happy path of loading a 96 channel pipette will work"

2022-11-23 18:54 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_api_old/test_context.py
> -def test_load_instrument(name, ctx):
its raising an exception bc there is no matching 96 channel pipette in `PipetteNameType` enum and bc its the old tests and we have new ones it was ok to remove.

2022-11-23 19:05 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/clients/sync_client.py
> +            params=commands.LoadPipetteParams.construct(
```suggestion
            params=commands.LoadPipetteParams(
```

2022-11-23 19:23 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/protocol_context.py
> +            self._instruments[Mount.RIGHT] = instrument
removed the condition. now we will only set the left mount

2022-11-23 19:26 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +            cache_request[other_mount.to_hw_mount()] = (
added a todo for now

2022-11-23 20:10 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +            # TODO (tz, 11-23-22): remove this assigment change when refactoring load_pipette for 96 channels.
```suggestion
            # TODO (tz, 11-23-22): remove 96 channel assignment when refactoring load_pipette for 96 channels.
```

2022-11-23 20:19 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +            cache_request[other_mount.to_hw_mount()] = (
@mcous is whatever the protocol engine needs from the hardware controller for this ticketed somewhere?

2022-11-23 20:19 UTC, Laura-Danielle approved these changes
fine to merge this now.

2022-11-23 20:38 UTC, merged