feat(robot-server): Analyze protocols depending on their declared `robotType`
OpenTrons/opentrons-api pull request #11770
Opened 2022-11-21 22:17 UTC by SyntaxColoring

# Overview

# Changelog

# Review requests

# Risk assessment

2022-11-22 02:51 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/protocols/test_upload_robot_type_rejection.tavern.yaml
> +test_name: Upload, analyze, delete basic_transfer_standalone protocol.
Copy-paste error

2022-11-22 02:51 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +        ).as_error(status.HTTP_422_UNPROCESSABLE_ENTITY)
Need to add this to `responses` in the FastAPI decorator for proper OpenAPI generation.

2022-11-22 02:51 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/resources/deck_data_provider.py
> +        # a protocol is running on.
Reminder.

2022-11-22 22:19 UTC, vegano1 commented on api/src/opentrons/protocol_runner/create_simulating_runner.py
> +    if robot_type == "OT-2 Standard":
this should be a variable, so if we need to change the value it's easier.

2022-11-28 15:38 UTC, sfoster1 requested changes
Looking good, but we have this exact robot type literal union defined in shared data already. if we want it to be an enum let's change it to be an enum, but we can at least use the shared data one.

2022-11-28 15:38 UTC, sfoster1 commented on api/src/opentrons/protocol_runner/create_simulating_runner.py
> +# TODO(mm, 2022-11-17): Make this a shared enum somewhere.
we should put it here: https://github.com/Opentrons/opentrons/blob/b370caeb5c92b6ad834ba2805e751d17983092b9/shared-data/python/opentrons_shared_data/robot/dev_types.py#L9 or just use that literal union for now

2022-12-07 19:06 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/create_simulating_runner.py
> +# TODO(mm, 2022-11-17): Make this a shared enum somewhere.
Oh sweet, thanks for the pointer. I didn't know that literal existed.

2022-12-12 21:18 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/resources/deck_data_provider.py
> +        # a protocol is running on.
Punting this to another PR because it turns out to be kind of a lot.

2022-12-12 21:21 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/create_simulating_runner.py
> +    if robot_type == "OT-2 Standard":
I think this is resolved by using the `Literal` from `shared_data`, but let me know if you meant something else.

2022-12-19 16:27 UTC, TamarZanzouri commented on api/src/opentrons/protocol_reader/protocol_source.py
>      # TODO(mm, 2022-10-21): Make this an enum once we figure out where to put it.
we can remove this TODO?

2022-12-19 17:26 UTC, TamarZanzouri commented on robot-server/robot_server/protocols/router.py
> +class ProtocolForDifferentRobotType(ErrorDetails):
nitpick should we change the name? ExpectedDifferentProtocolRobotType maybe?

2022-12-19 17:48 UTC, TamarZanzouri commented on robot-server/tests/protocols/test_analysis_store.py
> +            metadata={},
redundant change?

2022-12-19 17:52 UTC, TamarZanzouri commented on robot-server/mypy.ini
> +    | tests/integration/protocols
why was this added? just for me to understand

2022-12-19 17:54 UTC, TamarZanzouri approved these changes
a few questions\nitpicking but besides that looks good!

2022-12-19 18:20 UTC, SyntaxColoring commented on robot-server/mypy.ini
> +    | tests/integration/protocols
Our CI was trying to enforce that the `empty_ot3.py` file I added had type annotations. But I don't want that file to be treated like the rest of our code, since it's just test input. I wanted it to be a bare minimum protocol, with nothing fancy or unusual inside it.

2022-12-19 18:21 UTC, SyntaxColoring commented on api/src/opentrons/protocol_reader/protocol_source.py
>      # TODO(mm, 2022-10-21): Make this an enum once we figure out where to put it.
Thanks!

2022-12-19 18:22 UTC, SyntaxColoring commented on robot-server/tests/protocols/test_analysis_store.py
> +            metadata={},
Oops, yes.

2022-12-19 18:26 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +class ProtocolForDifferentRobotType(ErrorDetails):
Yeah...

`ExpectedDifferentProtocolRobotType` does feel a bit better, but it also feels long.

Maybe these?

* `UnsupportedRobotType`?
* `RobotTypeMismatch`?

2022-12-19 20:07 UTC, TamarZanzouri commented on robot-server/robot_server/protocols/router.py
> +class ProtocolForDifferentRobotType(ErrorDetails):
yes! I love them both! thank you!

2022-12-20 15:13 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +class ProtocolForDifferentRobotType(ErrorDetails):
I'll go with `RobotTypeMismatch`.

2022-12-21 15:34 UTC, sfoster1 approved these changes
Looks good to me as-is, but I would love to see `simulate` and `execute` upgraded as noted in todos.

2022-12-21 15:34 UTC, sfoster1 commented on api/src/opentrons/execute.py
> +    #  * I don't think it would ever make sense to call this function with anything
definitely agree with this. let's go ahead and do that - ignore this param and use the host machine type.

2022-12-21 15:34 UTC, sfoster1 commented on api/src/opentrons/simulate.py
> +    # TODO(mm, 2022-12-14): Now that protocols declare their target robot types
can we do that here?

2022-12-21 15:34 UTC, sfoster1 commented on robot-server/robot_server/protocols/analysis_models.py
> -    # TODO(mm, 2022-10-21): Make this an enum when we figure out where it should live.
:raised_hands:

2022-12-21 16:59 UTC, SyntaxColoring commented
I'll merge this as-is to clear my plate while I work on hotfix stuff. I've just ticketed those upgrades to `simulate` and `execute` in RCORE-469 to do in another PR. Thanks!

2022-12-21 17:42 UTC, merged