fix(gripper-defs): update critical point and add helper offsets
OpenTrons/opentrons-api pull request #11773
Opened 2022-11-22 17:09 UTC by ryanthecoder

# Overview

# Changelog

# Review requests

# Risk assessment

2022-11-22 18:48 UTC, ahiuchingau commented on shared-data/gripper/definitions/1/gripperV1.json
> +    "z": -76.475
oh no! Have we been using the wrong value this whole time?

2022-11-28 15:33 UTC, sfoster1 requested changes
Gotta `make format` in shared-data to get the json formatted I think.

Also please put some content in the PR description talking about why we need the change.

2022-11-28 15:33 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/gripper/constants.py
> +GRIPPER_DECK_DROP_OFFSET: GripperOffset = GripperOffset(-0.5, -0.5, -1.5)
are these used somewhere?

2022-11-28 16:10 UTC, ryanthecoder commented on shared-data/gripper/definitions/1/gripperV1.json
> +    "z": -76.475
we used the right measurements, testing just found that it works better when the critical point is the top edge of the pad instead of the center of the pad.

2022-11-28 16:12 UTC, ryanthecoder commented on shared-data/python/opentrons_shared_data/gripper/constants.py
> +GRIPPER_DECK_DROP_OFFSET: GripperOffset = GripperOffset(-0.5, -0.5, -1.5)
removing this from the PR. this is a temp fix for EVT-testing and will be implemented differently in protocol engine for edge

2022-11-30 16:56 UTC, SyntaxColoring requested changes
Some organizational questions and suggestions.

-----

> Testing found that the gripper works better if we use the center of the top edge of the gripper pads as the critical point.

Is it equivalent to say: testing found that the gripper works better if we grip labware 2 mm below where we were gripping labware before?

If so, why are we choosing to treat this as an adjustment to the gripper definition, instead of the code that chooses where to grip?

-----

* If we're really going to make this adjustment here, I think we need to rename the field to something other than `jawCenterOffsetFromBase`. `jawCenterOffsetFromBase` implies, to me, either the actual geometric center of the cushy pads, or the actual geometric center of the metal jaws.
* Whatever we end up with, I think we need a detailed description for this field in `shared-data/gripper/schemas/1.json`.

2023-01-04 14:21 UTC, sfoster1 approved these changes
my change requests were solved by removing stuff

2023-01-20 17:03 UTC, ryanthecoder commented
No longer needed

2023-01-20 17:03 UTC, closed without merging