fix(api): separate calibrate pipette from mount
OpenTrons/opentrons-api pull request #11786
Opened 2022-11-29 00:21 UTC by ahiuchingau

Since the calibration process for the pipettes and the gripper are rather different, it makes sense for us to call `calibrate_pipette` and `calibrate_gripper` separately so we can easily define the set up and clean up actions for individual instrument type.

# Changelog

#### 1. `calibrate_pipette()`
* For pipettes only
* Adds a tip (the calibration probe) before calling `calibrate_mount`
* Saves pipette offset to the file system and reload pipette offset if calibration succeeded without raising any errors
* Cleans up after calibration by removing the attached tip

#### 2. `calibrate_gripper()`
* Gripper only
* Adds a probe (front or rear probe) before calling `calibrate_mount`
* Calibrate the offset of the specified calibration probes on the gripper
* Does not save offset to the file system because we will need both the front probe offset and the rear probe offset in order to get the accurate gripper offset
* After calling `calibrate_gripper` twice, one on each probe, you can then use `gripper_pin_offsets_mean()` to get the actual gripper offset and save that value
* Cleans up after calibration by removing the attached probe

 3. Fix the problem where the try... except... else... finally... block in `calibrate_mount` was swallowing exceptions `InaccurateNonContactSweepError`, `EarlyCapacitiveSenseTrigger` because we were calling `return` in the finally clause (see [clean-up-actions](https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions))
 4. `center` value returned by `calibrate_mount` was not actually the offset, but in fact, the calibrated center of the edge sensing slot, therefore we have been passing the wrong value to protocol engine

2022-11-29 15:27 UTC, Laura-Danielle requested changes
I'm neutral about this change.

There are two things we should make sure of:

1. That Max knows about this change since he's working on gripper cal protocol engine stuff
2. Pls change where we re-raise the exception and handle returning the `center` value from calibrate mount
3. Should we now make `calibrate_mount` "private" since the public facing functions are `calibrate_pipette` and `calibrate_gripper`?
4. Pls add doc strings to the new functions you created.

2022-11-29 15:27 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +        raise
I think this raise should be in the `except clause`. Then we can probably change that `else` to a `finally` and put all that center calculation stuff in there to return the center.

2022-11-29 15:27 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/test_ot3_calibration.py
> +    calibrate_pipette,
Did @SyntaxColoring 's changes get in for protocol engine calibrate gripper stuff? If not, we should make sure he knows about this change.

2022-11-29 15:53 UTC, ahiuchingau commented on api/tests/opentrons/hardware_control/test_ot3_calibration.py
> +    calibrate_pipette,
This changes the calibrate pipette behavior, not gripper

2022-11-30 23:47 UTC, Laura-Danielle approved these changes
nice!

2022-12-01 02:01 UTC, merged