Refactor(api): Allow gantry move by mount
OpenTrons/opentrons-api pull request #11788
Opened 2022-11-29 18:05 UTC by TamarZanzouri

# Overview

closes https://opentrons.atlassian.net/browse/RLIQ-268.
Change `calibration/moveToLocation` to accept `mount` instead f `pipetteId`.

# Changelog

- Refactored `MoveToLocationParams` to accept `mount` instead of `pipetteId`.
- Refactored `MoveToLocationResult` to not return current position in the result.
- Refactored `MoveToLocationImplementation` to act as a collaborator and moved logic into `LabwareView`.
- Added new method to `LabwareView` to get calibration coordinates and critical point.

# Review requests

changes make sense? 

# Risk assessment

Low. Should react the same as the only implementation. will test on an OT-2 and OT-3.

2022-11-29 18:06 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +        description="Gantry mount to move.",
```suggestion
        description="Gantry mount to move to location.",
```

2022-11-29 18:08 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibration_move_to_location.py
> +    argnames=["slot_name", "critical_point_result"],
```suggestion
    argnames=["input_position", "critical_point_result"],
```

2022-11-29 18:08 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibration_move_to_location.py
>      slot_name: CalibrationPosition,
```suggestion
    input_position: CalibrationPosition,
```

2022-11-29 18:08 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibration_move_to_location.py
>          location=slot_name,
```suggestion
        location= input_position,
```

2022-11-29 18:08 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibration_move_to_location.py
> +        state_view.labware.get_calibration_coordinates(location=slot_name)
```suggestion
        state_view.labware.get_calibration_coordinates(location= input_position)
```

2022-11-29 18:39 UTC, mcous requested changes, later dismissed
This is a vast improvement, let's double check the Z value for the pipette attach location and continue cleaning stuff up

2022-11-29 18:39 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
>      """Result data from the execution of a CalibrationSetUpPosition command."""
```suggestion
    """Result data from the execution of a MoveToLocation command."""
```

2022-11-29 18:39 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_location.py
> +        hardware_mount = MountType.to_hw_mount(params.mount)
`to_hw_mount` is an instance method, not a class method

```suggestion
        hardware_mount = params.mount.to_hw_mount()
```

2022-11-29 18:39 UTC, mcous commented on api/src/opentrons/protocol_engine/types.py
> +    coordinates: Point
Use the engine-specific `DeckPoint` to represent absolute coordinates in the engine rather than `opentrons.types.Point`

```suggestion
    coordinates: DeckPoint
```

2022-11-29 18:39 UTC, mcous commented on api/src/opentrons/protocol_engine/types.py
> +from opentrons.types import MountType, DeckSlotName, Point
```suggestion
from opentrons.types import MountType, DeckSlotName
```

2022-11-29 18:39 UTC, mcous commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibration_move_to_location.py
>  async def test_calibration_set_up_position_implementation(
```suggestion
async def test_calibration_move_to_location_implementation(
```

2022-11-29 18:39 UTC, mcous commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibration_move_to_location.py
>  )
Since this unit is now properly a collaborator, this parameterization is unnecessary and can be removed. The only job this test now has is to ensure that the input `CalibrationPosition` value object is passed along to `state_view.labware.get_calibration_coordinates`. The actual value is irrelevant for this test

2022-11-29 18:39 UTC, mcous commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibration_move_to_location.py
>          )
```suggestion
        ),
        times=1
```

2022-11-29 18:39 UTC, mcous commented on api/src/opentrons/protocol_engine/types.py
> +    ATTACH_OR_DETACH = "attachOrDetach"
Let's rename these to be more consistent while we're here moving stuff around:

- If the enum is called `CalibrationPosition`, the value shouldn't have "position" in its name too; it's redundant
- Gripper attach location may be different than the pipette attach position

I'd suggest:

```suggestion
    PIPETTE_PROBE_ATTACH = "pipetteProbeAttach"
    PIPETTE_ATTACH = "pipetteAttach"
```

This leaves space for both `GRIPPER_PROBE_ATTACH` and `GRIPPER_ATTACH` if we need them. I don't think it's really necessary to spell out "attach or detach" here; if you're detaching, it's likely to attach a new pipette, so it's basically the same thing

2022-11-29 18:39 UTC, mcous commented on api/tests/opentrons/protocol_engine/state/test_labware_view.py
> +            Point(x=196.5, y=43.0, z=0.0),
`z=0.0` looks potentially incorrect for an attach position. On the OT-2, the attach/detach Z value for positioning via `CriticalPoint.MOUNT` is `30`; I'd expect something in this neighborhood for the OT-3 as well.

Someone from the embedded team should be able to give us a good value for the proper value

2022-11-29 18:39 UTC, mcous commented on api/src/opentrons/protocol_engine/types.py
> +    z: float
`DeckSlotOffsetVector` is used entirely internally in one state view method; we shouldn't add a Pedantic-based model for internal usage like this

2022-11-29 18:39 UTC, mcous commented on api/src/opentrons/protocol_engine/state/labware.py
> +_PROBE_DECK_SLOT_OFFSET = DeckSlotOffsetVector(x=10, y=0, z=3)
Same comment, there's no need to create a new class for this. I might move the "magic slot" up here, too.

```suggestion
_PIPETTE_PROBE_ATTACH_SLOT = DeckSlotName.SLOT_5
_PIPETTE_PROBE_ATTACH_X_OFFSET_FROM_SLOT = 10.0
_PIPETTE_PROBE_ATTACH_Z_OFFSET_FROM_SLOT = 3.0

_PIPETTE_ATTACH_SLOT = DeckSlotName.SLOT_2
```

2022-11-29 18:39 UTC, mcous commented on api/src/opentrons/protocol_engine/state/labware.py
> +            )
```suggestion
            target_center = self.get_slot_center_position(_PIPETTE_PROBE_ATTACH_SLOT)
            result = CalibrationCoordinates(
                coordinates=Point(
                    x=target_center.x + _PIPETTE_PROBE_ATTACH_X_OFFSET_FROM_SLOT,
                    y=target_center.y,
                    z=target_center.z + _PIPETTE_PROBE_ATTACH_Z_OFFSET_FROM_SLOT,
                ),
                critical_point=None,
            )
```

2022-11-29 18:39 UTC, mcous commented on api/src/opentrons/protocol_engine/state/labware.py
> +            target_center = self.get_slot_center_position(DeckSlotName.SLOT_2)
```suggestion
            target_center = self.get_slot_center_position(_PIPETTE_ATTACH_SLOT)
```

2022-11-29 18:39 UTC, mcous commented on api/tests/opentrons/protocol_engine/state/test_labware_view.py
> +    subject = get_labware_view(deck_definition=standard_deck_def)
Rather than using the `standard_deck_def` here, it may be worth using a (partial) test-specific deck definition value object to make the calculations more obvious. As written, the expectation values are very magical and hard to verify

2022-11-29 19:04 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/types.py
> +    coordinates: Point
The reason I choose Point is bc `get_slot_center_position` is returning `Point`. and hardware_api.move_to is expecting `Point`

2022-11-29 19:13 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/types.py
> +    ATTACH_OR_DETACH = "attachOrDetach"
Made sure with Laura and Linda that the position for attach/detach a gripper is the same as the pipette.

2022-11-29 19:40 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/state/test_labware_view.py
> +            Point(x=196.5, y=43.0, z=0.0),
What if we call `hardware_api.gantry_position()` with the `CriticalPount.Mount` / `None` to get the z height?

2022-11-29 20:20 UTC, Laura-Danielle commented on api/tests/opentrons/protocol_engine/state/test_labware_view.py
> +            Point(x=196.5, y=43.0, z=0.0),
We have no reason to lower the pipettes anymore below the "shroud" because there is no shroud and users need access to the front screws so we should ideally keep the mount at the home position.

At some point there might be a small offset requested from design and/or hardware for ergnomic purposes and we might want to do something different specifically for the 96 channel. However, I think if anything we should have a static offset value (that for now remains 0) that we can add to the current Z value.

2022-11-29 20:23 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/types.py
> +    ATTACH_OR_DETACH = "attachOrDetach"
`INSTRUMENT_PROBE_ATTACH` seems fine to me.

2022-11-29 21:10 UTC, mcous commented on api/tests/opentrons/protocol_engine/state/test_labware_view.py
> +            Point(x=196.5, y=43.0, z=0.0),
- The `0` here is an absolute coordinate, not an offset, so I'm pretty sure it's wrong because `0` means "at deck level"
- I don't think we should bring the "current Z value" into the mix either, because the pipette could be starting from any height, so it seems unsafe to introduce indeterminism to this command in that way

If the correct Z height is the z-home or something close to it, then that's the absolute z value that needs to be used here, right?

2022-11-29 21:30 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/state/test_labware_view.py
> +    subject = get_labware_view(deck_definition=cast(DeckDefinitionV3, slot_definitions))
```suggestion

    subject = get_labware_view(deck_definition=cast(DeckDefinitionV3, slot_definitions))
    
```

2022-11-29 21:31 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/types.py
> +from opentrons.types import MountType, DeckSlotName, Point
Consulted Mike. leaving this as Point for now

2022-11-30 02:00 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/state/test_labware_view.py
> +@pytest.mark.parametrize(
How can I test this with OT-2 hardware and OT-3 hardware?

2022-11-30 15:38 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +                if should_use_ot3
use deck definition instead

2022-11-30 15:42 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +_INSTRUMENT_PROBE_ATTACH_SLOT = DeckSlotName.SLOT_5
why are we using 2 slots and not 1 for maintenance

2022-11-30 15:54 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +_INSTRUMENT_PROBE_ATTACH_SLOT = DeckSlotName.SLOT_5
are we moving the gantry when calibrating? for gripper we are moving the correct slot. should we use 1 slot and move the slot calibration to the calibrate method? create a new ticket for this.

2022-11-30 19:25 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_maintenance_position.py
> +        """Move the requested pipette to a given deck slot."""
```suggestion
        """Move the requested instrument to a given deck slot."""
```

2022-11-30 19:26 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_maintenance_position.py
> +    """Result data from the execution of a MoveToLocation command."""
```suggestion
    """Result data from the execution of a MoveToMaintenancePosition command."""
```

2022-11-30 19:27 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_maintenance_position.py
> +"""Calibration Move To Location command payload, result, and implementation models."""
```suggestion
"""Calibration Move To Maintenance Location command payload, result, and implementation models."""
```

2022-11-30 19:28 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +
```suggestion
```

2022-11-30 19:29 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibration_move_to_maintenance_position.py
> +        call Movement.move_to_coordinates with the correct input."""
```suggestion
    """Command should get a move to target location and critical point and should verify move_to call."""
```

2022-11-30 19:34 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/calibration/__init__.py
>      # calibration/moveToLocation
```suggestion
    # calibration/moveToMaintenancePosition
```

2022-11-30 19:36 UTC, mcous approved these changes
LGTM pending on hardware test!

2022-11-30 19:36 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/calibration/move_to_maintenance_position.py
> +    from opentrons.protocol_engine.state.state import StateView
Prefer relative imports for ProtocolEngine internals

```suggestion
    from ..state import StateView
```

2022-11-30 21:07 UTC, TamarZanzouri commented
Tested on an OT-3! works as expected!

2022-11-30 21:13 UTC, Laura-Danielle approved these changes
lgtm

2022-12-01 19:33 UTC, jbleon95 commented
Tested this on an OT-3 and can confirm it only moved on the x/y axis and not the z-axis, and moved correctly over slot 2.

2022-12-01 19:55 UTC, merged