feature(hardware): refactor hardware controller to watch for valid responses and error messages
OpenTrons/opentrons-api pull request #11789
Opened 2022-11-29 19:05 UTC by ryanthecoder

[RET-1250](https://opentrons.atlassian.net/browse/RET-1250)
[RET-1251](https://opentrons.atlassian.net/browse/RET-1251)

# Overview
This will let the hardware controller listen for and handle error messages in addition to regular acks
This also implements timeouts for messages that previously didn't respond. now there is a timeout if they don't respond with an Acknowledgment for those messages

# Changelog

# Review requests

# Risk assessment

2022-11-29 20:38 UTC, sfoster1 requested changes
Couple refactor suggestions and typos and stuff but looks good overall

2022-11-29 20:38 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            log.error("move group runner failed")
this isn't really a helpful error without more detail - let's either get rid of this `except/raise` and let higher levels handle it, or make this a `log.exception` that will automatically print the execption

2022-11-29 20:38 UTC, sfoster1 commented on hardware/opentrons_hardware/drivers/can_bus/can_messenger.py
> +    """Helper clas for CanMessenger to listen for Acks back from commands."""
```suggestion
    """Helper class for CanMessenger to listen for Acks back from commands."""
```

2022-11-29 20:38 UTC, sfoster1 commented on hardware/opentrons_hardware/drivers/can_bus/can_messenger.py
> +        if message.payload.message_index == self._message.payload.message_index:
can we massage things around a bit and maybe move this `if` to `__call__` or make it `if not (...): return` or something? it's tough to deal with long indented blocks

2022-11-29 20:38 UTC, sfoster1 commented on hardware/opentrons_hardware/drivers/can_bus/can_messenger.py
> +        if message.payload.message_index == self._message.payload.message_index:
In fact let's factor this into another function or set of functions honestly

2022-11-29 20:38 UTC, sfoster1 commented on hardware/opentrons_hardware/drivers/can_bus/can_messenger.py
> +            raise RuntimeError("Async firmware error", str(err_msg))
let's make a new exception type for this that can hold the code and so on

2022-11-29 20:38 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/current_settings.py
> +                f"recieved error {str(error)} trying to set currents for {str(node)}"
```suggestion
                f"received error {str(error)} trying to set currents for {str(node)}"
```

2022-11-29 20:38 UTC, sfoster1 commented on hardware/opentrons_hardware/drivers/can_bus/can_messenger.py
> +        if error_payload.severity == ErrorSeverity.warning:
maybe make this block a `log_error` function?

2022-11-29 20:38 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +        if message.payload.severity.value == ErrorSeverity.warning:
could reuse that log function here

2022-11-29 20:38 UTC, sfoster1 commented on hardware/tests/opentrons_hardware/drivers/can_bus/test_can_messenger.py
> +    print(message.payload.message_index.value.to_bytes(4, "big"))
don't want to check in prints

2022-11-30 16:38 UTC, ryanthecoder commented on hardware/opentrons_hardware/drivers/can_bus/can_messenger.py
> +        if message.payload.message_index == self._message.payload.message_index:
didn't show up in these few lines of diff, but I broke it out into much nicer looking functions

2022-12-02 16:51 UTC, sfoster1 approved these changes
Looks good to me!

2022-12-02 17:17 UTC, Laura-Danielle approved these changes
this also lgtm

2022-12-02 17:22 UTC, merged