feat(shared-data): properly load new pipette configurations from shared data
OpenTrons/opentrons-api pull request #11795
Opened 2022-11-30 18:31 UTC by Laura-Danielle

## Overview 
We have a completely new shape for pipette configurations that need to be loaded in. Loading in major and minor versions for pipettes will be addressed in a fast follow-up (and also changes required for the xfail test here). I wanted to avoid making the diff confusing by making changes to the json again.

The hope for this refactor is that `ot3_pipette_config.py` will replace `pipette_config.py` once we can support OT2 pipettes in this new configuration format.

# Changelog
- Added pydantic models in shared data to actually load the definition into
- Added dataclasses in the python api side to handle loading an `OT3PipetteConfiguration` model.

# To-Do in follow-ups
- support major/minor version
- add in better support for the sensor key (tbd on what this looks like and is low priority)

# Review requests

Does this look OK? Missing doc strings/tests etc?

# Risk assessment
Low. Still not being used in the hardware controller yet. That is for a follow-up PR.

2022-11-30 19:28 UTC, sfoster1 approved these changes
This looks pretty good, but why have both the pydantic definitions and the dataclass definitions?

2022-11-30 19:28 UTC, sfoster1 commented on api/src/opentrons/config/ot3_pipette_config.py
> +    tip_length: float  # TODO(seth): remove
hey wait why are you dragging me into this?!?!?!

2022-11-30 19:29 UTC, Laura-Danielle commented on api/src/opentrons/config/ot3_pipette_config.py
> +    tip_length: float  # TODO(seth): remove
LOL the comment is still relevant!

2022-11-30 19:30 UTC, Laura-Danielle commented
We tend to stick to using dataclasses (and pythonic snake case) in the hardware controller + objects used in the hardware controller.

That's the main reason I'm loading in the pydantic model and then reformatting to a dataclass.

2022-12-01 17:24 UTC, mcous requested changes
Ditching the Pydantic / dataclass duplication is great. Doesn't look like config loading is working, though, because the `PipetteModelType` enum values match the directory paths rather than the JSON values

2022-12-01 17:24 UTC, mcous commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +    geometry_dict = _geometry(version)[channels][max_volume]
Could `channels` and `max_volume` be arguments instead of dictionary keys so this whole dictionary of every pipette isn't loaded unnecessarily?

2022-12-01 17:24 UTC, mcous commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +def load_definition(
Can we make filesystem reads `async` via [anyio](https://anyio.readthedocs.io/en/stable/fileio.html) so they run in a thread pool rather than blocking the main thread?

2022-12-01 17:24 UTC, mcous commented on shared-data/python/opentrons_shared_data/pipette/types.py
> +            )
Since we already have an `Enum`, could we make the values `int`'s instead of strings? This feels like unnecessary coupling between channel counts and how we choose to store those configurations on the filesystem, which IMO should be an implementation detail of configuration loading

2022-12-01 17:24 UTC, mcous commented on shared-data/python/tests/pipette/test_load_data.py
> +    # test as expected fail.
This does not appear to be the reason the tests are failing. It looks like there's a mismatch between `PipetteModelType` and what's actually in the `model` field of the `general/**/*.json` files

2022-12-01 17:24 UTC, mcous commented on shared-data/python/tests/pipette/test_types.py
> +    print(conversion_test)
Leftover debugging code?

2022-12-01 17:24 UTC, mcous commented on shared-data/python/opentrons_shared_data/pipette/types.py
> +        return cls[model.upper()]
Is this necessary? If the value coming in is `p50` / `p1000` (lowercase), then this can be replaced with `PipetteModelType(lowercase_model)`

2022-12-01 17:24 UTC, mcous commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +    return _build_configuration_dictionary("pipette/definitions/2/geometry", version)
Could the `pipette/definitions/2` prefix be part of the base configuration loader rather than forcing all these callers to duplicate it?

2022-12-01 17:24 UTC, mcous commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +    return _dict
Related to my other comment in this file, it seems like given the actual usage none of the directory walking is necessary.

```suggestion
def _get_configuration_dictionary(
    config_type: Union["general", "geometry", "liquid"],
    channels: types.PipetteChannelType,
    max_volume: types.PipetteModelType,
    version: types.PipetteVersionType,
) -> LoadedConfiguration:
    config_path = (
        get_shared_data_root()
        / "pipette"
        / "definitions"
        / "2"
        / config_type
        / channels.value
        / max_volume.value
        / f"{version.major}.json"
    )

    return json.loads(load_shared_data(config_path))
```

2022-12-01 17:24 UTC, mcous commented on shared-data/python/tests/pipette/test_load_data.py
> +@pytest.mark.xfail
My request for this PR is to remove the `xfail` and make sure our tests are working, but in general, can we always make sure to either:

- `xfail(strict=True)`, or
- a comment for why the xfail isn't strict (e.g. flakey test)

2022-12-01 17:29 UTC, mcous commented on shared-data/python/opentrons_shared_data/pipette/constants.py
> +PipetteModelMinorVersion = Literal[0, 1, 2, 3]
I've personally soured on the idea of a `constants.py` / `constants.ts` file in modules; it just makes things harder to find IMO. Could any of these things move elsewhere?

2022-12-01 17:29 UTC, mcous commented on shared-data/python/opentrons_shared_data/pipette/types.py
> +class PipetteTipType(Enum):
These classes seem pretty inherently tied to the definitions in `pipette_definition.py`. Can they move there, instead, to make things easier to read / find?

2022-12-01 20:48 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +def load_definition(
This will be a bigger refactor that would affect any functions which use `load_shared_data`. I will make a ticket to track this work and can try to tackle it at the end of the year -- I already have a branch started for this related to making file io async for the `calibration_storage` read/writes.

2022-12-01 20:51 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/constants.py
> +PipetteModelMinorVersion = Literal[0, 1, 2, 3]
I can move it into the `pipette_definition` file for now. I had created this file with the intention of sticking random things like 'quirks' and 'mutable_configs' in here that are only relevant for OT2 pipettes. I could probably call that file a different name at that point in time.

2022-12-01 20:56 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +def load_definition(
Ticket here: https://opentrons.atlassian.net/jira/software/c/projects/RLIQ/boards/150?modal=detail&selectedIssue=RLIQ-251&assignee=60343207783a4600685f4759

2022-12-01 21:08 UTC, mcous approved these changes
Nice! Continuing the testing conversation from the previous PR; implementation details are still leaking into the configuration loading test

2022-12-01 21:08 UTC, mcous commented on shared-data/python/tests/pipette/test_load_data.py
> +    assert pipette_config.channels.as_int == general["channels"]
I think calling `load_shared_data` inside the test muddies the test. I think we should either have:

1. An integration test, that knows nothing about how the pipette configuration files are stored
    - Value of this test: test that the unit probably works
    - Non-value: this test would provide no design feedback to unit internals
    - How to get there: replace the expected values with hardcoded literals in the test
3. A collaborator test:
    - Value of this test: design feedback for unit internals and that the unit is wired up to other units as we expect
    - Non-value: this test would not validate that the unit works, due to the use of mocks
    - How to get there: stub out `load_shared_data`, check that it's called with the correct path

What's currently written tries to split the difference between (1) and (2), which ends up compromising both and causing other problems (like tests failing for unclear reasons if/when we change things).

Given this unit's role, I would recommend option (1)

2022-12-01 22:43 UTC, merged