feat(hardware-testing): calibration testing script
OpenTrons/opentrons-api pull request #11807
Opened 2022-12-01 20:54 UTC by ahiuchingau

# Overview
Testing script for OT3 instrument auto calibration.

2022-12-01 20:58 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +
Aren't these changes from your other branch?

2022-12-02 14:24 UTC, Laura-Danielle reviewed
Will approve after we discuss the points I made about re some code changes in ot3_calibration directly.

2022-12-02 14:24 UTC, Laura-Danielle commented on api/src/opentrons/config/defaults_ot3.py
> +        plus_x_pos=(237, 148, 0),
Isn't this just to accommodate the dial indicators? Could we keep the defaults the same and modify it using the script?

2022-12-02 14:24 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    here = await hcapi.gantry_position(mount)
This is also to accommodate not hitting the dial indicators right? Could we at least put a todo comment that it can be removed once that testing is done?

2022-12-02 14:24 UTC, Laura-Danielle commented on hardware-testing/hardware_testing/scripts/auto_calibration_ot3.py
> +        curses.endwin()
nice that we can easily use curses on the ot3. I remember this being a problem awhile back for ot2 accuracy testing 😄

2022-12-02 16:25 UTC, ahiuchingau commented on api/src/opentrons/config/defaults_ot3.py
> +        plus_x_pos=(237, 148, 0),
Not just to accommodate the dial indicators; the defaults were actually not correct because the probe would touch the deck instead of the calibration square (on the x) and we also wanted to dodge the circular pins on the calibration square.

2022-12-02 16:28 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    here = await hcapi.gantry_position(mount)
I should've clarify - not planning on merging this anytime soon! This PR will be cleaned up before we're ready to merge. By then, the testing team should have solidified the entire calibration process, and those changes should be merged to edge.

2023-02-07 18:17 UTC, sfoster1 requested changes
I think that it's a little overly aggressive to fully move away from the binary search - I think that algorithm still has a tremendous amount to offer. However, I appreciate that the new sort of staged-linear search algorithm we've got implemented is what we have a lot of testing in.

What if, instead of _replacing_ the binary search implementation with the staged-linear search, we add the staged-linear search side-by-side with some configuration - maybe even a variable in the file - about which to use, so that we preserve the binary search and can use it easily if we want; and when we do the next stage of testing that we'll be doing anyway, we can test the binary search and fix any issues in it, because I think it will prove to be the better choice.

2023-02-07 20:46 UTC, caila-marashaj commented on api/src/opentrons/config/types.py
> +        if not (overrun_tolerance_mm <= pass_settings.max_overrun_distance_mm):
can probably say 

```suggestion
        if (overrun_tolerance_mm > pass_settings.max_overrun_distance_mm):
```

for a little more readability

2023-02-07 21:11 UTC, ahiuchingau commented on api/src/opentrons/config/types.py
> +        if not (overrun_tolerance_mm <= pass_settings.max_overrun_distance_mm):
ha good call!

2023-02-07 22:50 UTC, caila-marashaj commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +            in_search_direction,
In what case are we taking a stride with `in_search_direction = False`?

2023-02-08 16:36 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +            in_search_direction,
When we're searching for the +X and +Y edges and moving in the opposite directions (negative) and vice versa

2023-02-08 20:19 UTC, sfoster1 approved these changes
Okay, this all looks good now! Let's do it!

2023-02-08 21:08 UTC, Laura-Danielle approved these changes
Some suggestions about logging that are mainly just nits.

Am curious as to how we can maybe incorporate some of those defaults in `ot3_calibration.py` into `defaults_ot3.py`. I think as a team we should probs come to a decision about where things are gonna live.

I think it makes sense to get the calibration insert info from deck definition, but everything else feels like a hardware controller concern to me. Doesn't need to be addressed in this PR, but maybe we should make a spike ticket in jira at least so we don't forget about it.

2023-02-08 21:08 UTC, Laura-Danielle commented on api/src/opentrons/config/types.py
> +        object.__setattr__(self, "overrun_tolerance_mm", overrun_tolerance_mm)
curious why we're using `__setattr__` here

2023-02-08 21:08 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/ot3/gripper.py
> +        self._log.info(f"Got a new gripper offset: {delta}")
probs don't need both logs in this function

2023-02-08 21:08 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/ot3/gripper_handler.py
> +        self._log.info(f"Saving gripper {gripper.gripper_id} offset: {delta}")
Same here, don't think we really need this log message.

2023-02-08 21:08 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +REPEATABLE_STRIDES: List[float] = [1.0, 0.25, 0.1, 0.025]
curious why these aren't in `defaults_ot3.py`?

2023-02-08 21:59 UTC, ahiuchingau commented on api/src/opentrons/config/types.py
> +        object.__setattr__(self, "overrun_tolerance_mm", overrun_tolerance_mm)
Created a ticket for this - https://opentrons.atlassian.net/browse/RET-1331

2023-02-09 00:41 UTC, merged

2023-02-09 19:54 UTC, sanni-t commented
🎉🎉🎉