refactor(api): load instrument config into Protocol Engine
OpenTrons/opentrons-api pull request #11802
Opened 2022-12-01 18:08 UTC by jbleon95

# Overview

# Changelog

# Review requests

# Risk assessment

2022-12-01 22:44 UTC, mcous reviewed
Most of the engine stuff looks good, but a big part of the reason we want to add to the Hardware API is so that we _don't_ have to do the "other mount dict" thing.

CC @sfoster1 for thoughts on the Hardware API here

2022-12-01 22:44 UTC, mcous commented on api/src/opentrons/hardware_control/api.py
> +    async def cache_and_get_instrument(
I don't like the concept of the "instrument cache" leaking out of the Hardware API; the fact that it's cached should be an implementation detail.

This is a long winded way of saying "let's call this `ensure_instrument`" or something

2022-12-01 22:44 UTC, mcous commented on api/src/opentrons/hardware_control/api.py
> +        other_mount_dict: Optional[Dict[top_types.Mount, PipetteName]] = None,
This should not be part of the API of this method, it should happen internally

2022-12-01 22:44 UTC, mcous commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +                other_mount_dict=other_mount_dict,
Remove per other comment. We just want to know if the pipette we're trying to load is attached; we don't care (nor want to need to fetch) what's attached on the other mount

2022-12-02 17:03 UTC, sfoster1 requested changes, later dismissed
I don't love the change from the `hardware_control` perspective. I'd prefer either
- Add the return value to `cache_instruments`. Pass a dict containing only the mount you're interested in, and only access the mount you're interested in from the return value.
- A new function that is fully mount-agnostic and takes an equipment list, then returns the current state

The hardware control api is already really long, really complex, and occasionally duplicative. Adding `cache_and_get_instrument` as it currently is kind of adds to all those issues.

2022-12-02 17:03 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +    async def cache_and_get_instrument(
I don't love this addition because it feels really redundant with `cache_instruments`. The idea is to request one mount at a time, right? I'd prefer us to use `cache_instruments` for that by only specifying some of the mounts in the `require` dict, and add the return value.

2022-12-02 19:23 UTC, mcous commented on api/src/opentrons/hardware_control/api.py
> +    async def cache_and_get_instrument(
> I don't love this addition because it feels really redundant with `cache_instruments`

My bad for not adding necessary context! We would like this to _replace_ `cache_instruments`, not exist alongside it. Chatted with @Laura-Danielle about this today, but we have two main pipette needs from a Hardware API user perspective:

- During pipette load, validate that a given pipette is attached and fetch its static configuration (e.g. how many channels does it have?)
- While running, get mutable state of a given pipette (e.g. is there a tip on right now)

`cache_instruments` doesn't serve either of those needs particularly well, nor do I think its legacy usage of "force a refresh of the OT-2's attached instrument cache because of how the OT-2 works" is going to be particularly needed moving forward, _especially_ once pipette swap moves to the ProtocolEngine

2022-12-05 19:44 UTC, mcous approved these changes

2022-12-05 19:44 UTC, mcous commented on api/src/opentrons/protocol_engine/execution/equipment.py
>              else pipette_name
```suggestion
            mount.to_hw_mount(): (
                pipette_name.value
                if isinstance(pipette_name, PipetteNameType)
                else pipette_name
            )
```

2022-12-05 21:34 UTC, merged