feat(api): Support the new pipette configurations and 96 channel in the hardware controller
OpenTrons/opentrons-api pull request #11830
Opened 2022-12-06 00:00 UTC by Laura-Danielle

# Overview
This PR is an initial pass at supporting the new pipette configurations from shared data in the hardware controller. As a result of this, we also get to control the 96 channel  in the hardware controller. Another benefit is that the ot3 api can now switch between pipetting functions depending on the working volume of the pipette.

A lot of the work in this PR will require refactoring once we have the ot2 pipettes in the new pipette configuration.

# Changelog

-

# Review requests

# Risk assessment

2022-12-07 17:21 UTC, sfoster1 requested changes
Couple inline changes; some are critical, like using `float`s for versions - we really shouldn't do that.

There's also a whole lot of tests that effectively get mark-skipped for the ot3. Is there any way at all we can avoid that? IMO we really shouldn't check in PRs that disable swathes of tests like this.

Are the ot3 variants of `pipette` and `pipette_handler` straight copies of the ot2 variants? if not, can you point at where they're different?

2022-12-07 17:21 UTC, sfoster1 commented on api/src/opentrons/config/ot3_pipette_config.py
> +def convert_version_to_float(version: str) -> float:
definitely don't do this. it will make checking that versions are equal much harder. If you consider versions to be a `Tuple[major, minor, patch]` then [tuple comparison](https://stackoverflow.com/questions/5292303/how-does-tuple-comparison-work-in-python) will make things work like you want.

2022-12-07 17:21 UTC, sfoster1 commented on api/src/opentrons/config/ot3_pipette_config.py
> +def convert_pipette_name(name: PipetteName) -> Tuple[str, int, float]:
this `Tuple[str, int, float]` is used in a couple places - can we maybe make it a `PipetteDetails` dataclass?

2022-12-07 17:21 UTC, sfoster1 commented on api/src/opentrons/config/ot3_pipette_config.py
> +def convert_pipette_name(name: PipetteName) -> Tuple[str, int, float]:
or the dataclasses below?

2022-12-07 17:21 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    def _convert_channels_to_int(channels: str) -> int:
if we make a basically one-use dataclass or even typed dict that has channels, serial, and name then we can make these all one function and if we make it one function we can have a data-parametrized test that just zips through it and it'll be a bit clearer what it does

2022-12-07 17:21 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> +            pipette_spec: OT3PipetteSpec = {
is this because there's no "empty" version of a `PipetteSpec`? could we make this return `Union[OT3PipetteSpec, GripperSpec, None]`?

2022-12-07 17:21 UTC, sfoster1 commented on api/src/opentrons/hardware_control/dev_types.py
> +    model: Union[PipetteModel, None]
rather than allowing `model` to be `None`, we could allow passing `None` instead of `OT3PipetteSpec` where relevant. If this is instead to allow `OT3PipetteSpec` to constrain possible pipettes - i.e. if you ask for a `None` model spec and `8` channels, you get some default kind of pipette - then we should probably use key presence in the typed dict by allowing incomplete instances or an explicit sentinel value to stand for "anything".

2022-12-07 17:21 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot2/pipette.py
> +    def reset_state(self) -> None:
is there anything that is not included in this? there's so many little things here that it might be better to split some of these properties into sub-objects so it's easier to notice if we miss one.

2022-12-07 17:21 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot2/pipette_handler.py
> +            if isinstance(m, OT3Mount):
the linter will also be satisfied if you make `reset_pipette_offset` generic across mount

2022-12-07 17:21 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +                # with self._backend.save_current():
?

2022-12-07 17:21 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/test_instruments.py
> +    new_plunger_pos = 71.212208
why did these positions change? because we're using p1000s? can we not make that change, it adds a bunch to this pr

2022-12-07 17:21 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/test_instruments.py
> +    instruments = {
we should have a version of this for ot2 and ot3, since those are now separate pieces of code

2022-12-07 17:21 UTC, sfoster1 commented on api/tests/opentrons/protocols/advanced_control/test_transfers.py
> +@pytest.mark.ot2_only
are these changes to every tests in these files? i think we can do this on the file level

2022-12-07 17:30 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +                # with self._backend.save_current():
oppa forgot to delete that.

2022-12-07 17:35 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/ot2/pipette.py
> +    def reset_state(self) -> None:
This `reset_state` will be a lot easier to implement once we separate out static and stateful pipette properties/configurations/whatever you want to call it.

I didn't spend much time on this reset because it's going to be re-written shortly.

2022-12-07 17:42 UTC, Laura-Danielle commented on api/tests/opentrons/protocols/advanced_control/test_transfers.py
> +@pytest.mark.ot2_only
yeah we can. A lot of these tests are mostly written as integration since they don't mock out the hardware controller and they happen to use invalid pipettes for the OT3 hardware controller. I chose to mark them as `ot2_only` rather than modify the type of pipettes they used.

2022-12-07 17:44 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/test_instruments.py
> +    new_plunger_pos = 71.212208
This test was using the plunger positions we created for the frankenstein pipettes. Now that we're pulling in valid configurations for the p1000s, we should change the plunger position to the expected values.

2022-12-07 17:48 UTC, Laura-Danielle commented
```
Are the ot3 variants of pipette and pipette_handler straight copies of the ot2 variants? if not, can you point at where they're different?
```

The main differences include:
1. some new static properties to make is easier to look up things like plunger positions and pick up configurations
2. the shape of the pipette configurations passed in

Other than that both of those files are straight copies that I hope to be able to merge back together once the OT2 pipette configurations are ported over.

2022-12-07 21:40 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> +            pipette_spec: OT3PipetteSpec = {
Changing the return value for some of the helper functions in `ot3_pipette_config` should have resolved the need for this and we no longer need the `OT3PipetteSpec`.

2022-12-08 16:21 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/ot2/pipette_handler.py
> +            if isinstance(m, OT3Mount):
All of the code is separated -- including calibration stuff right now. Would rather address this when I'm recombining all the `instruments` code.

2022-12-08 16:28 UTC, sfoster1 approved these changes
This looks good as a first step to me, yeah. I think your refactor plans will help the other stuff I like less.

2022-12-08 16:28 UTC, sfoster1 commented on api/src/opentrons/config/ot3_pipette_config.py
> +def version_from_int(version: int) -> PipetteVersionType:
When do we end up using this?

2022-12-08 19:37 UTC, merged