refactor(app, shared-data): calibration/moveToLocation to calibration/moveToMaintenancePosition
OpenTrons/opentrons-api pull request #11849
Opened 2022-12-08 17:12 UTC by smb2268

fix RLIQ-265

# Overview

Refactor calibration/moveToLocation to calibration/moveToMaintenancePosition to adhere with https://github.com/Opentrons/opentrons/pull/11788

# Changelog

1. Rename calibration/moveToLocation to calibration/moveToMaintenancePosition
2. Change param from `pipetteId` to `mount`
3. Remove position from result
4. Update usage in calibration and attach/detach pipette flows, including removing home commands before calibration commands as they are no longer needed

# Review requests

Verify that these changes match the python changes and that the calibration flows look good

# Risk assessment

Low

2022-12-08 21:25 UTC, TamarZanzouri commented on app/src/organisms/PipetteWizardFlows/BeforeBeginning.tsx
> +            location: 'attachOrDetach',
you can lose this `location` argument we are not expecting it anymore. it will always move to slot 2

2022-12-08 21:25 UTC, TamarZanzouri commented on app/src/organisms/PipetteWizardFlows/__tests__/AttachProbe.test.tsx
> +          params: { mount: 'left', location: 'attachOrDetach' },
same comment as above

2022-12-08 21:26 UTC, TamarZanzouri commented on shared-data/protocol/schemas/7-draft.json
> +                "required": ["mount", "location"],
remove location from the required and from the params description

2022-12-08 21:28 UTC, TamarZanzouri requested changes
Thank you for addressing these changes! overall looks good! just need to remove the location property from the params. we are no longer expecting it. we are moving to slot 2 for attach/detach pipette/gripper and probe.

2022-12-08 21:51 UTC, jerader approved these changes
yay! lgtm!!

2022-12-12 16:18 UTC, TamarZanzouri commented on shared-data/protocol/schemas/7-draft.json
> +                "required": ["mount", "location"],
I guess we still need to do this change? @smb2268

2022-12-12 16:19 UTC, TamarZanzouri requested changes
One final change! all looks good just need to update the `7-draft.json`

2022-12-12 20:23 UTC, smb2268 commented on shared-data/protocol/schemas/7-draft.json
> +                "required": ["mount", "location"],
oops, thanks for catching!!

2022-12-12 21:09 UTC, TamarZanzouri approved these changes
looks good! thank you for addressing these changes :-)

2022-12-13 16:39 UTC, merged