Rliq 7 papi load liquid
OpenTrons/opentrons-api pull request #11920
Opened 2022-12-21 21:12 UTC by TamarZanzouri

# Overview

closes https://opentrons.atlassian.net/browse/RLIQ-7.
Add a `add_liquid` and `load_liquid` in PAPI.

# Changelog

# Review requests

# Risk assessment

2023-01-13 16:13 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/protocol_api/well.py
> +            "Creating a liquid is not supported in this API version."
```suggestion
            "Loading a liquid into a well is not supported in this API version."
```

2023-01-13 16:14 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/labware.py
> +        Load a liquid into a labware.
```suggestion
        Load a liquid into a well.
```

2023-01-13 18:01 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_api/core/engine/test_well_core.py
> +    """It should load a liquid into a labware."""
```suggestion
    """It should load a liquid into a well."""
```

2023-01-13 18:11 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/labware.py
> +        :param volume: Volume of liquid to load into.
```suggestion
        :param volume: Volume in uL of liquid to load into.
```

2023-01-13 18:27 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +        model_utils = ModelUtils()
should I use DI instead?

2023-01-13 18:29 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/well.py
> +
```suggestion
```

2023-01-13 18:29 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/well.py
> +        """Load liquid into a labware."""
```suggestion
        """Load liquid into a well."""
```

2023-01-13 18:30 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/well.py
> +        """Load liquid into a labware."""
```suggestion
        """Load liquid into a well."""
```

2023-01-13 18:31 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/protocol.py
> +        """Add a liquid to load into a labware."""
```suggestion
        """Add a liquid to load into a well."""
```

2023-01-13 18:31 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/protocol_api/protocol_context.py
> +        """Add a liquid to load on a labware."""
```suggestion
        """Add a liquid to load into a well."""
```

2023-01-13 18:32 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/protocol_api/well.py
> +        """Load liquid into a labware."""
```suggestion
        """Load liquid into a well."""
```

2023-01-13 18:34 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/labware.py
> +
```suggestion
```

2023-01-13 18:58 UTC, ecormany commented on api/src/opentrons/protocol_api/labware.py
> +        :param volume: Volume of liquid to load into.
Hi, parachuting in for docstrings 🪂 I'd go with: 
```
         :param liquid: The type of liquid to load into the well.
         :param volume: The volume of liquid to load, in µL.
```
Since this is ultimately display text for the docs, not code, I strongly prefer "µL" over "uL".

2023-01-13 20:59 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/labware.py
> +        :param volume: Volume of liquid to load into.
```suggestion
         :param liquid: The type of liquid to load into the well.
         :param volume: The volume of liquid to load, in µL.
```

2023-01-17 18:54 UTC, ecormany requested changes
Docstrings look good with a couple changes. 

Two bigger things for docs:
1. I don't control versioning decisions but it seems like this has to be a separate minor version (2.14), even if there are no breaking changes.
2. I think we need an article on these features (or at least a section of an existing article, perhaps [Labware](https://docs.opentrons.com/v2/new_labware.html) or [Building Block Commands](https://docs.opentrons.com/v2/new_atomic_commands.html)). Would love to collaborate on what needs to be said there. We should also create some code snippets and eventually show what this will support in the app.

2023-01-17 18:54 UTC, ecormany commented on api/src/opentrons/protocol_api/labware.py
> +        :param volume: Volume in uL of liquid to load into.
```suggestion
        :param liquid: The type of liquid to load into the well.
        :param volume: The volume of liquid to load, in µL.
```
Looks like this didn't get added from previous comment.

2023-01-17 18:54 UTC, ecormany commented on api/src/opentrons/protocol_api/protocol_context.py
> +        :param str display_name: An human-readable name for this liquid.
```suggestion
        :param str display_name: A human-readable name for this liquid.
```

2023-01-17 18:54 UTC, ecormany commented on api/src/opentrons/protocol_api/protocol_context.py
> +        :param str display_color: An optional Hex color code, with hash included, to represent the specified liquid. Standard three-value, four-value, six-value, and eight-value syntax are all accept
```suggestion
        :param str display_color: An optional hex color code, with hash included, to represent the specified liquid. Standard three-value, four-value, six-value, and eight-value syntax are all acceptable.
```

2023-01-17 23:07 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/liquid.py
> +class LoadedLiquid:
Since `LoadedLiquid` is going to be a public type, some thoughts on import organization.

We'll want to:

* Allow users to access it as `opentrons.protocol_api.LoadedLiquid`.
* *Prevent* users from accessing it as `opentrons.protocol_api.liquid.LoadedLiquid`.

In other words, the existence of an `opentrons.protocol_api.liquid` module should be considered a private implementation detail.

So I think we should reexport `LoadedLiquid` through `opentrons/protocol_api/__init__.py`, and prefix this module with an underscore (`_liquid.py`).

I know underscore-prefixed modules aren't an official Opentrons convention at this point, but the Python Protocol API is especially sensitive to this kind of thing. If Sphinx-generated HTML or an example protocol somewhere accidentally uses the internal module name, we'll want it to be obvious. @Opentrons/robot-svcs what do we think?

2023-01-17 23:07 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/liquid.py
> +class LoadedLiquid:
Naming question: Should this be `LoadedLiquid`, or just `Liquid`? By comparison, we don't call it a `LoadedLabware`.

2023-01-17 23:07 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/liquid.py
> +    id: str
Because this `LoadedLiquid` dataclass is going to be a public type, we should think hard about whether to expose this `id` attribute. What does it mean? What can a user do with it? It seems internal to me.

If we agree that it's internal, how might we avoid exposing it to users?

Also, I'm wary of making this public-facing type a dataclass. I worry that it's a stronger guarantee than necessary, and that it will make things harder to rework down the line. I'd consider making this a plain Python `class`, with `@property`s for `display_name`, `description`, and `display_color`.

2023-01-17 23:07 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/protocol_context.py
> +    @requires_version(2, 13)
Definitely yes, should be 2.14. You can leave a comment that this depends on RCORE-537.

2023-01-17 23:07 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/protocol_context.py
> +        self, display_name: str, description: str, display_color: Optional[str]
I'm just now realizing that `description` is mandatory (both here and in Protocol Engine). I don't have an informed opinion for how users think about liquids, but a mandatory description seems like an unnecessary hurdle to me. What if I just want to load some `water`? Do I really need to come up with a description for that?

2023-01-17 23:07 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/protocol_context.py
> +        self, display_name: str, description: str, display_color: Optional[str]
Does anyone have an opinion for whether `display_name` should just be `name`? `display_name` is a useful disambiguation phrase for things like labware, which also have `load_name`s. But liquids don't have that.

2023-01-17 23:07 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +        model_utils = ModelUtils()
Hmm. Can we leave the ID blank here and have Protocol Engine generate it internally? That would be consistent with how `loadLabware`, `loadPipette`, and `loadModule` work.

2023-01-18 20:55 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +        model_utils = ModelUtils()
Json protocols supply a liquid ID that is then referenced via the loadLiquid command. python protocol dont supply it so we need to generate it. Not sure how to make this change without adding a check for the protocol type? any thoughts?

2023-01-18 20:59 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +        model_utils = ModelUtils()
I guess I can generate it if its empty and then the loadLiquid command will fail if there is no liquid match

2023-01-18 21:08 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/liquid.py
> +class LoadedLiquid:
We use `LoadedLabware` in the PE and it's part of the `StateSummery` but not used in PAPI. I can totally change this

2023-01-18 21:14 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/protocol_context.py
> +        self, display_name: str, description: str, display_color: Optional[str]
totally agree! I will change it

2023-01-18 21:58 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/liquid.py
> +    id: str
the id is being used in the load_liquid command. it is a ref to the loaded liquid. In PE we expected the loaded liquid id but in PAPI we supply the whole LoadedLiquid. I can add the `id` to the `load_liquid` PAPI end point but I followed `load_labware` and `load_module` returned object.

2023-01-18 22:00 UTC, TamarZanzouri commented
@ecormany this will be covered as part of https://opentrons.atlassian.net/browse/RCORE-537. tagging @anthonywilleee to git this ticketed out
> 2. I think we need an article on these features (or at least a section of an existing article, perhaps [Labware](https://docs.opentrons.com/v2/new_labware.html) or [Building Block Commands](https://docs.opentrons.com/v2/new_atomic_commands.html)). Would love to collaborate on what needs to be said there. We should also create some code snippets and eventually show what this will support in the app.

2023-01-19 16:31 UTC, mcous requested changes
Not a complete review because I'm jumping into a meeting, but got some change requests

2023-01-19 16:31 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +        model_utils = ModelUtils()
ID should be generated inside protocol engine, the same way it's done for adding a command or adding a labware offset

2023-01-19 16:31 UTC, mcous commented on api/src/opentrons/protocol_api/core/protocol_api/protocol_context.py
> +        raise UnsupportedAPIError(
Use `APIVersionError`. Could you also change the other instance of `UnsupportedAPIError` in this file to `APIVersionError`?

2023-01-19 16:31 UTC, mcous commented on api/src/opentrons/protocol_api/core/protocol_api/well.py
> +from opentrons.protocols.api_support.util import UnsupportedAPIError
```suggestion
from opentrons.protocols.api_support.util import APIVersionError
```

2023-01-19 16:31 UTC, mcous commented on api/src/opentrons/protocol_api/core/protocol_api/well.py
> +        raise UnsupportedAPIError(
```suggestion
        raise APIVersionError(
```

2023-01-19 16:31 UTC, mcous commented on api/src/opentrons/protocol_api/labware.py
> +    # TODO (tz, 12-19-22): Should the api version be 2.14
```suggestion
    # TODO (tz, 12-19-22): Limit to API version 2.14
```

2023-01-19 16:31 UTC, mcous commented on api/src/opentrons/protocol_api/labware.py
> +    def load_liquid(self, liquid: LoadedLiquid, volume: float) -> None:
I don't think `LoadedLiquid` is a good name for a liquid that has been created, but not loaded. I suggest simply calling it `Liquid`

2023-01-19 16:32 UTC, TamarZanzouri commented
Tested on Dev server with Core ff on, works as expected! Tested with ff off and getting the error expected.

2023-01-19 17:05 UTC, mcous reviewed
Second half of my review

2023-01-19 17:05 UTC, mcous commented on api/src/opentrons/protocol_api/liquid.py
> +    id: str
Let's make this `_id` and treat it as "protected"

2023-01-19 17:05 UTC, mcous commented on api/tests/opentrons/protocol_api/core/engine/test_well_core.py
> +    mock_liquid = decoy.mock(cls=LoadedLiquid)
Do not mock value object

2023-01-19 17:05 UTC, mcous commented on api/tests/opentrons/protocol_api/test_protocol_context.py
> +    )
Since both `subject.add_liquid` and `core.add_liquid` return values; this test should be using `decoy.when`, not `decoy.verify`

2023-01-19 17:05 UTC, mcous commented on api/tests/opentrons/protocol_api/test_well.py
> +    mocked_liquid = decoy.mock(cls=LoadedLiquid)
Do not mock value objects

2023-01-19 17:05 UTC, mcous commented on api/tests/opentrons/protocol_api/test_well.py
> +    mocked_well = decoy.mock(cls=Well)
`Well` is the class under test, never mock the class under test. This mock also doesn't appear to be used

2023-01-19 17:05 UTC, mcous commented on api/tests/opentrons/protocol_api/test_well.py
> +    decoy.when(mocked_well._impl.get_name()).then_return("A1")
What is this doing? It looks like it should be removed

2023-01-19 17:47 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/liquid.py
> +class LoadedLiquid:
Another reason to call this just `Liquid` is that it avoids confusing usage of the word "load".

As currently written:

* `add_liquid()` returns a `LoadedLiquid`
* `load_liquid()` *takes a `LoadedLiquid` as input,* which doesn't really make sense.

2023-01-19 17:49 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/protocol_context.py
> +    def add_liquid(
Sorry for the late suggestion, but I think `define_liquid()` would be clearer. `add_liquid()` can sound like it makes the robot physically add the liquid to some place.

2023-01-19 18:06 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +        model_utils = ModelUtils()
Right. If we're following the pattern set by `loadLabware`, `loadPipette`, and `loadModule`, I think it should look something like this:

* In the Protocol Engine `LoadLiquidParams` model, `liquidId` should be optional.
* When Protocol Engine executes a `LoadLiquid` command without a `liquidId`, it should generate a `liquidId` automatically.
* Protocol Engine should return the `liquidId` in `LoadLiquidResult`.
* The JSONv6 schema should remain how it is. JSONv6 protocols will continue to specify liquid IDs in the top-level `liquids` object, and commands will continue to refer to those `id`s mandatorily.
* The PAPI implementation should leave the `id` blank.

2023-01-20 16:35 UTC, ecormany commented on api/src/opentrons/protocol_api/protocol_context.py
> +        :param str description: A optional description of this liquid.
```suggestion
        :param str description: An optional description of this liquid.
```

2023-01-20 18:52 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_api/test_well.py
> +    mocked_well = decoy.mock(cls=Well)
nice catch! its probably left overs from doing it via protocol_context

2023-01-20 19:05 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +        model_utils = ModelUtils()
I am generating the `id` if it's None at the `add_liquid` before dispatching an action (same as labware offsets). what Max is proposing is different. He is proposing we generate the id while running the `load_liquid` command. Tre is a problem with this approach is that the `id` wont represent an existing liquid id.

2023-01-23 16:20 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +        """create a liquid to load into a labware."""
```suggestion
        """create a liquid to load into a well."""
```

2023-01-23 16:26 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/protocol_context.py
> +    # TODO (tz, 12-19-22): Should the api version be 2.14
```suggestion
    # TODO (tz, 12-19-22): Limit to api version 2.14.
```

2023-01-24 17:43 UTC, TamarZanzouri commented
Tested on OT-2 with core ff on. tested json/python protocols. works as expected.

2023-01-24 19:26 UTC, ecormany reviewed
Couple comments on docstrings including 1 typo.

2023-01-24 19:26 UTC, ecormany commented on api/src/opentrons/protocol_api/protocol_context.py
> +        :param str name: An human-readable name for this liquid.
```suggestion
        :param str name: A human-readable name for this liquid.
```

2023-01-24 19:26 UTC, ecormany commented on api/src/opentrons/protocol_api/protocol_context.py
> +    # TODO (tz, 12-19-22): Limit to api version 2.14.
When is this version bump going to be done? After this PR?

2023-01-24 19:26 UTC, ecormany commented on api/src/opentrons/protocol_api/core/legacy/legacy_protocol_core.py
> +        raise APIVersionError("Adding a liquid is not supported in this API version.")
Should this be "Defining a liquid…"?

2023-01-24 19:26 UTC, ecormany commented on api/src/opentrons/protocol_api/core/legacy/legacy_well_core.py
> +        raise APIVersionError("Creating a liquid is not supported in this API version.")
Should this be "Loading a liquid…"?

2023-01-24 20:44 UTC, mcous commented on api/src/opentrons/protocol_api/protocol_context.py
> +    # TODO (tz, 12-19-22): Limit to api version 2.14.
Yes, see RCORE-537

2023-01-24 20:59 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/labware.py
> +        )
Heads-up: this will be a merge conflict with #12045 that Git might auto-resolve incorrectly. You might want to merge `edge` into this PR and double-check that this uses `self._core` here before you merge this into `edge`.

2023-01-24 20:59 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +        )
Could you explain this change?

It looks like we're constructing a `Liquid` in the exact same way here, in `LiquidStore`, and in `ProtocolRunner`. Why shouldn't `AddLiquidAction` continue to take an already-constructed `Liquid`?

2023-01-24 21:03 UTC, mcous requested changes

2023-01-24 21:03 UTC, mcous commented on api/src/opentrons/protocol_api/_liquid.py
> +class Liquid:
Can we add a docstring for this class and its public properties?

2023-01-24 21:03 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +)
Can this unrelated formatting change be reverted?

```suggestion
from opentrons.types import DeckSlotName, Location, Mount, MountType, Point
```

2023-01-24 21:03 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +            else None,
Please use parentheses for readability when doing these `if/else` assignments. I think newer `black` will add this formatting

```suggestion
            display_color=(
                loaded_liquid.displayColor.__root__
                if loaded_liquid.displayColor
                else None
            ),
```

2023-01-24 21:03 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +        loaded_liquid = self._engine_client.add_liquid(
I don't think `loaded_liquid` is a very good name here. Let's make it `liquid` or `engine_liquid` or something that doesn't collide with the `load_liquid` method

2023-01-24 21:03 UTC, mcous commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +        )
I think this should be doing something like `self.state.liquids.get(id)` rather than constructing a `Liquid`, which is currently happening twice (once here, and once in the liquids store)

2023-01-24 21:03 UTC, mcous commented on api/src/opentrons/protocol_engine/state/liquids.py
> +            displayColor=HexColor(__root__=action.color) if action.color else None,
This validation needs to happen earlier. An `AddLiquidAction` should not be able to be constructed with an invalid color string

2023-01-24 21:03 UTC, mcous commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +        color: Optional[str] = None,
Per other comment, an easy way we could for validation to happen sooner would be to type this argument as an optional HexColor rather than string

2023-01-24 21:03 UTC, mcous commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +        id: Optional[str] = None,
While `color` and `description` should definitely be optional, I don't they should have default argument values, as our production code never omits these parameters

2023-01-24 21:03 UTC, mcous commented on api/tests/opentrons/protocol_api/core/engine/test_protocol_core.py
> +        id=matchers.IsA(str),
Value objects used as return values should _never_ use `matchers`. Use an actual dummy string.

`matchers` are _only_ for loosening assertions. In practice, given how we tend to write assertions, they may only appear in objects on the right side of an `==`

2023-01-24 21:03 UTC, mcous commented on api/tests/opentrons/protocol_api/core/engine/test_protocol_core.py
> +        _id="water-id",
Correct ID is not checked by this test due to improper usage of `matchers.IsA(str)` above in the return value from the `add_liquid` stub

2023-01-25 21:54 UTC, ecormany requested changes, later dismissed
Just a couple docstring typos.

2023-01-25 21:54 UTC, ecormany commented on api/src/opentrons/protocol_api/_liquid.py
> +        display_color: A optional display color of the liquid.
```suggestion
    """A liquid to load into a well.

    Attributes:
        name: A human-readable name for the liquid.
        description: An optional description.
        display_color: An optional display color for the liquid.
```

2023-01-25 21:54 UTC, ecormany commented on api/src/opentrons/protocol_api/protocol_context.py
> +        :param str display_color: A optional hex color code, with hash included, to represent the specified liquid. Standard three-value, four-value, six-value, and eight-value syntax are all accepta
```suggestion
        Define a liquid within a protocol.

        :param str name: A human-readable name for the liquid.
        :param str description: An optional description of the liquid.
        :param str display_color: An optional hex color code, with hash included, to represent the specified liquid. Standard three-value, four-value, six-value, and eight-value syntax are all acceptable.
```

2023-01-27 17:52 UTC, TamarZanzouri commented
Tested on dev server with core ff on, python protocols and json protocols. works as expected!

2023-01-27 17:58 UTC, mcous approved these changes
LGTM

2023-01-27 19:33 UTC, merged