Rliq 69 hardware control liquid sense
OpenTrons/opentrons-api pull request #11926
Opened 2022-12-22 20:59 UTC by caila-marashaj

2023-01-04 23:56 UTC, caila-marashaj commented on api/src/opentrons/hardware_control/ot3api.py
> +        slot_num: int,
Should we take in a slot number here, or just take in a `Point` location instead? Asking for the slot number requires us to figure out where the slot is, which is something I'm not sure if we want to recreate in the hardware controller

2023-01-05 19:13 UTC, sfoster1 requested changes
I think that we should take a step back and consider what we want out of this API.
The goal is that
- Assuming
   - the pipette is already in the correct XY position
- Given
   - a suspected nominal location for the top of the liquid
   - a range of possibilities for the height of the liquid
   - a pipette (with a tip) to use to check the height of the liquid
- Determine
   - either the height of the liquid
   - or that the height of the liquid cannot be found

To me, that means that we need to change the signature of this function somewhat. For instance
- It should return the height of the liquid in deck coordinates
- It should take a range of possibilities for the height of the liquid
- it should perform hardware state safety checks

It should figure out on its own where to move the pipette in z to determine this. We don't want the hardware control layer to have to understand things about labware, so we should rely on higher layers to tell us information about where the liquid will probably be found. For instance, the caller can give us maximum and minimum absolute heights in deck coordinates corresponding to the top and bottom of the well being tested. This function can then use its configuration to move to an appropriate position above the top of the range and move to an appropriate position around the bottom of the range. That probably means we'll have to change the config to contain things like a margin above the top of the liquid that is required for the move to spool up, and a margin below the bottom of the liquid that is required to safely stop, rather than absolute positions. The hardware control layer in `ot3api` can then determine the distance to move the pipette and the mount.

It should also perform its own safety checks. For instance, it should raise an exception if a tip isn't present, because when it moves around it will need to do so based on the length of the tip. It should check that the aspirated volume is 0, since it'll need to raise the plunger to prepare, which would be dangerous if the tip contained liquid.

We probably may also want this configuration to live in pipette settings, since pressures at least will likely be very different based on pressure chamber and probably tip geometry, but that could be in a follow up PR.

2023-01-05 19:13 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    def get_slot_center_pos(self, slot_num: int) -> OT3AxisMap[float]:
this doesn't seem to be used and doesn't really belong in this layer anyway, maybe get rid of it?

2023-01-05 19:13 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +        primary_mover = movers[0]
the time should be the same for all the movers, right? so we could always just do this

2023-01-24 14:42 UTC, sfoster1 requested changes
This is awesome and getting there! Couple more things we should change in the hardware control layer.

2023-01-24 14:42 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> +        return
since you're rebasing on edge anyway, you should add an `@ensure_yield` decorator to this from #12024

2023-01-24 14:42 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        After moving the mount the distance specified by starting_mount_height in the
```suggestion
        After moving the mount to the z-position specified by starting_mount_height in the
```
right?

2023-01-24 14:42 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +            self._current_position.clear()
do we need to clear the position? the liquid sensing part failed, sure, we don't know where the _liquid_ is - but we certainly should still know where the _pipette_ is.

2023-01-24 14:42 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +                self._current_position.clear()
same question with this clear position - we still know where the pipette is, even if we don't know where the liquid is

2023-01-24 14:42 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +            await self.home_plunger(mount)
here, do we need to home (meaning that we don't know the position) or is this more of a park (just getting everything out of the way)? I think it might be a good idea to _not_ home the pipette, because frequently you're gonna want to
- sense liquid height
- move the pipette clear of the liquid
- prep the plunger for aspiration
- move the pipette down to the liquid
- aspirate
Homing _or_ parking the mount isn't really necessary and just sort of wastes time.

What might be a good idea instead is recovering up to the prep position specified by the liquid sense settings and then homing the plunger.

2023-01-24 14:42 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        home the mount and plunger to avoid collision, and return the height at
let's avoid using words like "height" here - this is the z position, in deck coordinates, in mm, of the position of the top of the liquid.

2023-01-24 14:42 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +            final_mount_pos_um: float = positions[head_node_for_mount(mount)][0]
I think this section has some unit confusion. Is this value really in micrometers? or is it converted to millimeters by `opentrons_hardware`? if it _is_ in um, then you definitely can't directly subtract the starting mount height from it, since that's in mm, and you should convert it back into mm before returning it. If it's in mm, then you should change the variable name.

2023-02-09 16:07 UTC, Laura-Danielle requested changes
Mostly cleanup requests. Looking good in general.

2023-02-09 16:07 UTC, Laura-Danielle commented on api/src/opentrons/config/defaults_ot3.py
> +    read_only=False,
what's the difference between `log_pressure` and `read_only`? To me they mean essentially the same thing. We should pick only one config to keep here.

2023-02-09 16:07 UTC, Laura-Danielle commented on api/src/opentrons/config/defaults_ot3.py
> +    max_z_distance=40,
Let's keep the max/min z for now, but can we put a comment that we may want to think a little more about how we can cleanly handle triggering "early" or triggering "late"

2023-02-09 16:07 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            ax: -1 * self.phony_bounds[ax][1] - self.phony_bounds[ax][0]
Why do we have this change?

2023-02-09 16:07 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    def get_slot_center_pos(self, slot_num: int) -> OT3AxisMap[float]:
^ bump here, this needs to be removed.

2023-02-09 16:07 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        return {
What is the purpose of this change?

Can we put it in a separate PR if it's unrelated to liquid sensing?

2023-02-09 16:07 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        head_node = head_node_for_mount(OT3Mount(mount.value))
Use: `OT3Axis.by_mount(Mount)`

2023-02-09 16:07 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        tool = sensor_node_for_mount(OT3Mount(mount.value))
Use `axis_to_node` after getting the correct `OT3Axis` value from the line above.

2023-02-09 16:07 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        starting_mount_height: float,
Shouldn't this value be used in `ot3api.py` to actually move the pipette to the prep distance? I don't think that should be a concern of the tool sensor `liquid_probe` function.

2023-02-09 16:07 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        pos_axes = dict()
what is this `pos_axes` actually used for?

2023-02-09 16:07 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3utils.py
> +def head_node_for_mount(mount: Union[OT3Mount, Mount]) -> NodeId:
We have functions that do this already. See my comments in `ot3controller.py`. We should remove this code.

2023-02-09 16:07 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +        bounds = self._backend.phony_bounds
again, why are we changing to `phony_bounds`?

2023-02-09 16:07 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +            probe_settings.home_plunger_at_start
If this is only true when we're doing "aspirate_while_sensing", do we need both settings?

2023-02-09 16:07 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +            self._log.exception("Liquid Sensing failed- threshold never reached.")
We should probably clear current position too if this happens.

2023-02-09 16:07 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +                raise ThresholdReachedTooEarly
If we're throwing the exception, we can put the log message in `ThresholdReachedTooEarly`. See `EarlyCapacitiveSenseTrigger` and we should probably make sure this inherits directly from `RunTimeError`.

2023-02-09 16:07 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/backends/test_ot3_controller.py
> +#   move this test into test_ot3_calibration or some other file, and make
Is this comment still needed?

2023-02-09 16:07 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/backends/test_ot3_controller.py
> +    breakpoint()
Lots of breakpoints in here that need to be removed.

2023-02-09 16:07 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/backends/test_ot3_controller.py
> +    mock_move_group_run,
I don't see where you're mocking tool sensors.

2023-02-09 16:07 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/backends/test_ot3_controller.py
> +    # mock tool_sensors liquid_probe
Can we also note what test cases this test should be testing?

2023-02-09 16:07 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/test_ot3_api.py
> +        AsyncMock(
Do we need these mock functions if we're already mocking the `_move` and/or `home` function which should get called by both of these?

2023-02-09 16:07 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/test_ot3_api.py
> +            {head_node: (102, 102, True, True), pipette_node: (102, 102, True, True)},
It's a little hard to read imo when you set the side effect to be a list.

We should break out the side effect for each test case. You can do that w a small comment as to which test case you're expecting to happen on which line.

2023-02-09 16:07 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +class ThresholdReachedTooEarly(ValueError):
Let's have this inherit from `RunTimeError`. See my other comments about putting a string in here.

2023-02-09 16:07 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +                if ack_id == 1:
If we're not throwing a different error, can't we just rely on the rest of the move group runner to throw a `MoveConditionNotMet`?

2023-02-09 16:07 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +        if self.new_file_created:
FYI, you can just have one "open" command for the `data_file`.

As per the [docs](https://docs.python.org/3/library/functions.html#open), "a" or append will create the file if it doesn't exist.

You should probably keep the conditional statement so that you can write a heading to the file or continue to append.

2023-02-09 16:07 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +    """Capture incoming sensor messages."""
Can we put this class in a better place, like a `utils.py` or something?

2023-02-09 16:07 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +class SensorLog:
```suggestion
class LogListener:
```

2023-02-09 16:07 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +    async with sensor_driver.bind_output(messenger, pressure_sensor, binding):
nice, much cleaner :D

2023-02-09 16:07 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +    if read_only:
yea not quite sure what this `read_only` stuff is for? If they want standalone pressure readings, they should use the capture_sensor script or whatever it's called rather than this function.

2023-02-09 16:07 UTC, Laura-Danielle commented on hardware/tests/opentrons_hardware/hardware_control/test_tool_sensors.py
> +) -> None:
imo we should mock `sensor driver` or `sensor_scheduler` here and make sure the correct CAN messages are being called in the order that we expect.

2023-02-09 16:20 UTC, caila-marashaj commented on api/src/opentrons/config/defaults_ot3.py
> +    read_only=False,
`read_only` sets the sensor to `report` instead of `sync`, so someone who uses this can just take a bunch of readings without necessarily stopping or having an error thrown. I put this in here so the testing team can use it, I think it can be restructured to be clearer though

2023-02-16 15:11 UTC, sfoster1 submitted a review, later dismissed
This is looking really strong! There's some stuff to fix up still but it's all details that don't affect higher level functionality.

2023-02-16 15:11 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    def get_slot_center_pos(self, slot_num: int) -> OT3AxisMap[float]:
bump

2023-02-16 15:11 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        return {
also wonder this

2023-02-16 15:11 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        prep_move_speed: float,
agree with the `starting_mount_height` thing, and this is part of that too right? We should pull that out

2023-02-16 15:11 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> +    def get_slot_center_pos(self, slot_num: int) -> OT3AxisMap[float]:
This should go away as it should in ot3controller

2023-02-16 15:11 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> +        """Get the axis bounds."""
Still don't quite get the point of this change

2023-02-16 15:11 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +            probe_settings.home_plunger_at_start
Do we ever intend to use `aspirate_while_sensing`?

This is something the hardware team requested for testing, we might end up taking it out later but they wanted this option

2023-02-16 15:11 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    async def liquid_probe(
IMO we should make this return the position dict of where we ended up. Definitely keep the position update too, but this will let us simplify calling code.

2023-02-16 15:11 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> +        return
might want to have this update the position to idk somewhere halfway through the commanded sense range

2023-02-16 15:11 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        if not self._current_position:
IMO we should raise `MustHomeError` here, we should really get away from just salting in random homes

2023-02-16 15:11 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        if not self._current_position:
or in fact rely on the call to gantry position and move to do that

2023-02-16 15:11 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        direction = -1 if probe_settings.aspirate_while_sensing else 1
maybe make it a little more clear that this is the _plunger_ direction here

2023-02-16 15:11 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +            machine_pos = await self._backend.update_position()
if `OT3Controller.liquid_probe` returns the position dict, then we won't need this call anymore

2023-02-16 15:11 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/test_ot3_api.py
> +        # scenario - aspirate while sensing
we should not have multiple scenarios in a single test. It makes the test function gigantic and it makes it so you can't see if _all_ tests fail or just _one_ test fails and prevents the others from running. Let's make these scenarios separate tests.

2023-02-16 15:11 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +        super().__init__(f"Liquid threshold not found, max travel allowed = {max_z}")
ditto here - we should make this absolute deck coordinates once this exception class is moved.

2023-02-16 15:11 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +class EarlyLiquidSenseTrigger(RuntimeError):
These exceptions appear to only ever be referenced in the hardware control library, so let's put them there - in `opentrons.hardware_control.errors` (if this PR has that file) or `opentrons.hardware_control.types`.

2023-02-16 15:11 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +    def __init__(self, triggered_at: float, min_z: float) -> None:
since we're moving this to the hardware controller, we can make these two elements be absolute positions in deck coordinates, which I think will make them much more helpful to users who experience the error.

2023-02-16 15:11 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +    # use any node present to calculate duration of the move, assuming the durations
this comment IMO either should be a docstring describing the function, or be down right next to where we build the duration

2023-02-16 15:11 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +    # move the mount and pipette simultaneously
this comment should be part of the function docstring

2023-02-16 15:11 UTC, sfoster1 commented on hardware/opentrons_hardware/sensors/sensor_driver.py
> +        if type(binding) == list:
tldr: let's just make this function take `binding: Sequence[SensorOutputBinding]` and change functions that use it to pass a one-element list or tuple if they had been passing just one binding.

the long part:

There's a couple things that should change about this code.

First, it's almost always a bad idea to use `if type(...) == ...` in python, for a couple reasons. It doesn't work with inheritance - the version that does is `if isinstance(binding, list)`, which would also pass something that was a subclass of list - and it doesn't really conform to python's approach to duck typing/structural subclassing. For instance, there's no real reason you couldn't pass a tuple of bindings in here, after changing the type to accept a `Sequence` - _to this function_, list and tuple there are identical. You can index-access, you can iterate, you're not trying to modify it, it's the same. But even checking `isinstance` rather than `type` won't let you accept this unless you're listing out every single kind of sequence or using `abc` or something.

The second big thing that should change, though, is that doing type-based logic like this is kind of a code smell in python anyway. There's a lot of python code out there that does it, that's, shall we say, overly ambitious about supporting every possible way you could call a function, but it makes the interface more complicated for little benefit.

If, instead, this becomes `binding: Optional[Sequence[SensorOutputBinding]] = None`, then you don't have this problem anymore, and this code can go away. Still need to none-check, but that's a different issue.

2023-02-16 15:11 UTC, sfoster1 commented on hardware/opentrons_hardware/sensors/sensor_driver.py
> +        ] = SensorOutputBinding.sync,
This default should be `None`, unfortunately. It's always a bad idea to bind a function-default to a real value in python, because the binding happens when the file is parsed, so if it's ever modified the modification sticks around between calls.

2023-02-16 15:11 UTC, sfoster1 commented on hardware/opentrons_hardware/sensors/sensor_driver.py
> +        z_velocity: float,
this stuff is a little overly specific to the liquid sense case. this code can have two things change:
- first, instead of taking metadata that doesn't change and isn't written to every row, like velocities, directly, let's take a `Sequence[str]` of metadata that gets written to the first row
- second, let's take a slightly more general "data descriptor" argument that is a string that is just the label for the sensor data we're capturing. After all, this code will work perfectly well with whatever kind of sensor you want to capture.

2023-02-16 15:11 UTC, sfoster1 commented on hardware/opentrons_hardware/sensors/sensor_driver.py
> +        threshold_pascals: float,
also this function really needs to take the file path to write to as an argument. as it is, you can never use this class in a test without lots of mocking.

2023-02-17 20:50 UTC, caila-marashaj commented on api/src/opentrons/hardware_control/ot3api.py
> +        position = deck_from_machine(
I'm adding a call to `axis_convert` in here since `deck_from_machine` wants an `AxisType` dict and not `NodeId`

2023-02-17 21:56 UTC, Laura-Danielle approved these changes
BEAUTIFUL! Excited to get this in.

2023-02-21 17:17 UTC, merged