feature (makefile): Add legacy flag to scp option for newer versions of openSSH
OpenTrons/opentrons-api pull request #11932
Opened 2022-12-28 16:51 UTC by TamarZanzouri

# Overview

For openSSH versions larger the 8.9 there is no longer use of `SFTP protocol`.
in order to support SFTP protocol in newer versions we need to add the -O flag to the `scp` push command.

# Changelog

- Check the openSSH version. if larger or equal 9.0, add the -O flag in `push.mk` file. 

# Review requests

- It this sufficient? Is there a better way to do this?
- need to smoke test `make push` on an OT-3 and an OT-2 with different OS's.

# Risk assessment

Medium. need to make sure this doesn't effect other OS's and doesn't effect `make push`
on an OT-3.

2022-12-30 17:38 UTC, TamarZanzouri commented on scripts/push.mk
> +scp -i $(2) $(if $(need-scp-option),"-o") $(3) "$(4)" root@$(1):/data/$(notdir $(4))
```suggestion
scp -i $(2) $(if $(need-scp-option),"-O") $(3) "$(4)" root@$(1):/data/$(notdir $(4))
```

2023-01-03 15:19 UTC, sfoster1 requested changes
I think this is the right place and the right general path to go down, but we should use the filter-function variant rather than the embedded shell pipeline variant.

2023-01-03 15:19 UTC, sfoster1 commented on scripts/push.mk
> +need-scp-option = $(shell if [ "$(shell ssh -V 2>&1 | grep -o "[0-9]*\.[0-9]*" | grep -oe '[0-9]' | head -1)" -ge $(need-scp-option-from-version) ]; then echo 1; fi)
I think we should go with the text-function version for two reasons:
1. this is very hard to read. make text-functions are also very hard to read, but I think less so than a big shell pipeline mixed with make functions
2. `grep` doesn't exist on powershell unless you specifically install it

Output redirection does work on powershell, so something like  `ssh-version-output = $(shell ssh -V 2>&1)` should work cross-platform. on windows it will give you something like this:
```
PS C:\Users\sethfoster> ssh -V 2>&1
ssh : OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3
At line:1 char:1
+ ssh -V 2>&1
+ ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (OpenSSH_for_Win... LibreSSL 3.4.3:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
this can probably be simplified with some other powershell commandlets or options but then we'd have system-specific behavior which we don't want. we can probably get around this by properly structuring our filter function to handle the trailing output.

2023-01-03 19:38 UTC, sfoster1 requested changes
Looks good, but let's add a warning if we couldn't parse the ssh output and a couple more comments about what the ssh flag does and why.

2023-01-03 19:38 UTC, sfoster1 commented on scripts/push.mk
> +ssh-version-number=$(subst ., ,$(firstword $(subst p, ,$(ssh-version-label))))
after this, let's add something that prints an error if we couldn't find a version, like
`$(if $(ssh-version-number),,"$(warning Could not find ssh version from $(ssh-version-output), flags may be wrong"))`

2023-01-03 19:38 UTC, sfoster1 commented on scripts/push.mk
> +scp-legacy-option-flag = $(if $(is-in-version),,-O)
add a quick note either here or where we define `allowed-ssh-versions` about what this flag is and why we're doing it

2023-01-05 18:07 UTC, sfoster1 approved these changes
Awesome! Nice work

2023-01-05 18:17 UTC, TamarZanzouri commented
Will merge after testing make push on an OT-2

2023-01-10 20:33 UTC, TamarZanzouri commented
Tested make push with a Mac, worked as expected. Tried pushing with a windows machine, was not able to push, got a permission denied error. @josh to test this on a windows machine to make sure the error I got is not related to the changes.

2023-01-10 22:58 UTC, y3rsh approved these changes
>  @y3rsh to test this on a windows machine to make sure the error I got is not related to the changes.

Make push from Windows would require successful `make setup` in `api, update-server, shared-data/python, robot-server, notify-server` with python 3.7.  This does not work, there are not available Windows versions of 3rd party dependencies in the version range.

I tested it on Ubuntu WSL and it worked.

2023-01-12 22:08 UTC, y3rsh commented
> > @y3rsh to test this on a windows machine to make sure the error I got is not related to the changes.
> 
> ~Make push from Windows would require successful `make setup` in `api, update-server, shared-data/python, robot-server, notify-server` with python 3.7. This does not work, there are not available Windows versions of 3rd party dependencies in the version range.~
> 
> ~~The above is true~~ but I do have success on Windows with this command in api at least `python -m pipenv run python setup.py -q bdist_wheel`
> 
> The issue I am looking into on Windows is ~ expansion failing. Will update.

I am actually not having any issues with any of the building commands on Windows though I thought I had previously.

On my machine I am having issues when make is running.  It is diving down /usr/bin in my WSL and using that `ssh`. 😵‍💫 
Instead of 
![image](https://user-images.githubusercontent.com/502770/212191280-5485f615-4506-4a52-8f6f-9cb579360c2a.png)

@TamarZanzouri and I will test together Tuesday 1/17.

2023-01-18 16:22 UTC, sfoster1 approved these changes
Looks great! Thank you!

2023-01-18 17:27 UTC, merged