feat(ot3): add separate motor control CAN messages for the tip motors of the 96 channel
OpenTrons/opentrons-api pull request #11934
Opened 2022-12-30 17:42 UTC by Laura-Danielle

## Overview

Rather than having a specific node id for the tip motors on the 96 channel, I decided to create specific CAN messages for certain motor functionalities. Unlike the gripper, the tip motors are pretty intrinsic to the rest of the pipetting functionality and these CAN messages are only used in very specific instances.

See the firmware side [here](url).

2023-01-04 14:12 UTC, sfoster1 requested changes
Hm, in action having multiple messages is a little rougher than expected since it gets integrated into the same python calls as everything else, but I still think it's the right design.

That said I think there's some stuff we can clean up a bit.

2023-01-04 14:12 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/current_settings.py
> +        if use_tip_motor_message and node == NodeId.pipette_left:
I don't think it's appropriate to check the node id here alongside the `use_tip_motor_message`. We want this layer to be less informed about semantic concepts like "what kind of pipette is this". 

Also, doing the logic this way means that the boolean flag could be ignored sometimes; that's not something I love because boolean args like this feel more like overrides, where a higher layer knows what should happen because it has more information and it's not for the lower layer to contravene that decision.

2023-01-04 14:12 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/current_settings.py
> +        else:
might be a little cleaner to separate the decision of what message to use from the function that does the sending, by making a little helper function like
```python
def _motor_current_message_for(tip_motor: bool) -> Union[Type[GearWriteMotorCurrentRequest], Type[WriteMotorCurrentRequest]]:
    if tip_motor: return GearWriteMotorCurrentRequest
    else: return WriteMotorCurrentRequest

def set_currents(..., use_tip_motor_message: bool = False) -> None:
    message_class = _motor_current_message_for(use_tip_motor_message)
    error = await can_messenger.ensure_send(..., message=message_class(payload=...))
```

2023-01-04 19:40 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/current_settings.py
> +        if use_tip_motor_message and node == NodeId.pipette_left:
We want it to be ignored unless the node we're sending over matches the pipette id since this function accepts a dictionary of nodes to currents. I could push up the looping to the `controller` layer instead, but that's basically why I'm checking this here.

2023-01-04 19:56 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/current_settings.py
> +        if use_tip_motor_message and node == NodeId.pipette_left:
Ohhh that makes sense I hadn't noticed. What about making that parameter a list of nodeids? `use_tip_motor_message_for: List[NodeId]` and check if the node's in the list?

2023-01-06 15:45 UTC, sfoster1 approved these changes
Looks awesome!

2023-01-13 21:00 UTC, merged