Rcore 425 implement labware parent on engine core
OpenTrons/opentrons-api pull request #11949
Opened 2023-01-04 21:33 UTC by TamarZanzouri

# Overview

# Changelog

# Review requests

# Risk assessment

2023-01-04 21:42 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/labware.py
> +        protocol_core: Optional[ProtocolCore] = None,
@mcous I know you will have something to say about this ;-)

2023-01-04 22:17 UTC, mcous requested changes
Two things to do here:

- Make sure all `ProtocolEngine` interfaces are contained to the engine-based cores, and do not leak out to the abstract core definitions nor the Protocol API interfaces
- Run `LabwareLike.parent` to ground to make sure we don't break anything unexpected (I'll get to work on this)

2023-01-04 22:17 UTC, mcous commented on api/src/opentrons/protocol_api/core/protocol.py
> +        """Get Module core for a given module id."""
`module_id` is ProtocolEngine specific, but this is a method on the abstract (common) interface. I think it should be combined with the method below:

```python
def get_labware_location(...) -> Union[DeckSlotName, ModuleCoreType]:
```

2023-01-04 22:17 UTC, mcous commented on api/src/opentrons/protocol_api/core/protocol_api/protocol_context.py
> +        )
Remove per comment above, `module_id` is not applicable here

2023-01-04 22:17 UTC, mcous commented on api/src/opentrons/protocol_api/core/protocol.py
> +    def get_labware_location(self, labware_core: LabwareCoreType) -> LabwareLocation:
Similar to comment above: `LabwareLocation` is too engine-specific to be a return type of the common protocol core interface

2023-01-04 22:17 UTC, mcous commented on api/src/opentrons/protocol_api/core/protocol_api/protocol_context.py
> +from opentrons.protocol_engine import LabwareLocation
Importing a `protocol_engine` type into the non-protocol-engine core is a warning sign

2023-01-04 22:17 UTC, mcous commented on api/src/opentrons/protocol_api/labware.py
> +    def parent(self) -> Optional[Union[str, ModuleTypes]]:
Very small style suggestion: put `None` in the `Union` rather than using `Optional`

```suggestion
    def parent(self) -> Union[str, ModuleTypes, None]:
```

2023-01-04 22:17 UTC, mcous commented on api/src/opentrons/protocol_api/labware.py
> +        protocol_core: Optional[ProtocolCore] = None,
Yeah I'd love to avoid this if at all possible, but it may not be. We could potentially type them as required, and then in the few weird places where we construct `Labware` objects outside of `load_labware`, we could add type ignores and a note

2023-01-04 22:17 UTC, mcous commented on api/src/opentrons/protocols/api_support/labware_like.py
> +        return LabwareLike(parent)  # type: ignore[arg-type]
We'll need to be pretty careful with this one, and check out where this `LabwareLike.parent` is used to make sure this is safe

2023-01-04 22:17 UTC, mcous commented on api/src/opentrons/protocol_api/labware.py
> +            )
Same comment as above: this leaks `ProtocolEngine`-specific types and concepts, like `moduleId`, into the public Protocol API classes.

Rather than two calls to `self._protocol_core`, I would collapse this into a single call to `self._protocol_core` that returns either a `DeckSlotName` (simple enum) or `ModuleCore`

2023-01-05 19:07 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/protocol_api/protocol_context.py
> +    ) -> Union[DeckSlotName, legacy_module_core.LegacyModuleCore]:
```suggestion
    ) -> Union[DeckSlotName, legacy_module_core.LegacyModuleCore, None]:
```

2023-01-06 14:41 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +            return self._module_cores_by_id[module_id]
change this to get?

2023-01-06 14:59 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +        """Get Module core for a given module id."""
```suggestion
```

2023-01-09 17:42 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +    def _get_module_core_item(self, module_id: str) -> Optional[ModuleCore]:
Let's remove this method, I don't think it really makes a difference for readability

```python
self._get_module_core_item(module_id)
# vs
self._module_cores_by_id.get(module_id)
```

2023-01-09 17:42 UTC, mcous commented on api/src/opentrons/protocol_api/labware.py
> +            )
Let's make this an `assert`, getting into this `if` would certainly be a bug on our part, not something the user could change.

```suggestion
        assert self._protocol_core and self._core_map, "Labware initialized incorrectly"
```

2023-01-09 17:42 UTC, mcous commented on api/src/opentrons/protocol_api/module_contexts.py
> +        return self._core.get_deck_slot()
```suggestion
        return self._core.get_deck_slot().value
```

2023-01-09 17:42 UTC, mcous commented on api/src/opentrons/protocol_api/module_contexts.py
> +        """The parent of this labware. Usually a slot name."""
```suggestion
        """The name of the slot the module is on."""
```

2023-01-09 17:42 UTC, mcous commented on api/src/opentrons/protocols/api_support/labware_like.py
> +    MODULE_CONTEXT = auto()
We should treat a `ModuleContext` as a `MODULE` type, not add a new type. This probably will need to change the type annotation of `as_module` to `Union[ModuleContext, ModuleGeometry]`, which is a little silly, but `as_module` isn't actually used outside of tests so we're probably fine

2023-01-09 21:32 UTC, mcous approved these changes
LGTM

2023-01-09 21:32 UTC, mcous commented on api/src/opentrons/protocol_api/module_contexts.py
> +    # TODO (tz, 1-7-23): change this to version 2.14?
TODO is correct but should remain a TODO for this PR since the decorator will complain right now if you attempt to change it

2023-01-09 21:32 UTC, mcous commented on api/src/opentrons/protocols/api_support/labware_like.py
>          elif isinstance(self._labware_like, ModuleGeometry):
```suggestion
        elif isinstance(self._labware_like, (ModuleGeometry, ModuleContext)):
```

2023-01-09 21:38 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/module_contexts.py
> +    # TODO (tz, 1-7-23): change this to version 2.14?
```suggestion
    # TODO (tz, 1-7-23): change this to version 2.14
```

2023-01-09 22:02 UTC, merged