fix(api): OT3 recover previous loc after making sure the robot is ready for movement
OpenTrons/opentrons-api pull request #11970
Opened 2023-01-09 22:21 UTC by ahiuchingau

# Overview
We now conditionally home all axes that are about to move before a move execution to make sure the stepper motor positions are accurate (see #11752). 

What I forgot to do is to get the robot to move back to the original position after homing, fixing it here now.

2023-01-10 14:54 UTC, sfoster1 requested changes
I think this is gonna lead to weird and erratic movements, and now we have (or really soon will) the encoder stuff. I think rather than doing this, we should refresh the positions from the encoders for axes where that's relevant, and home only those that don't have encoders.

2023-01-10 14:54 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        origin = await self.gantry_position(mount, refresh=True)
if we're homing because the axis position was wrong, then we can't really use the axis position, right?

2023-01-10 19:17 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/ot3api.py
> +        origin = await self.gantry_position(mount, refresh=True)
I completely forgot we were updating the position based on move complete message. Might have to completely redo this

2023-02-16 20:39 UTC, ahiuchingau commented
Not fixing it this way!

2023-02-16 20:39 UTC, closed without merging