refactor(api): implement labware parent on engine core #11949
OpenTrons/opentrons-api pull request #11977
Opened 2023-01-10 19:11 UTC by TamarZanzouri

# Overview

closes [RCORE-425](https://opentrons.atlassian.net/browse/RCORE-425). 
Implement Labware.parent on engine core

# Changelog

- Addes `ProtocolCore` and `LoadedCoreMap` DI to `engine/protocol`.
- Added `get_labware_location` to `engine/core`.
- Changed return type of PAPI `Labware.parent` to `Union[str, ModuleContext,None]`
- Legacy parent runs through the legacy implementation. engine core runs through the new logic.
- Added `isinstance` check to `LabwareLike` in case on a `ModuleContext`.
- Changed return type for `LabwareLike.as_module` to use `ModuleContext`
- Added `ModuleContext.parent`

# Review requests

1. did I miss tests?
2. `LabwareLike.parent` feel safe with the related changed?
3. did I miss DI when constructing `Labware`?

# Risk assessment

Medium. Legacy code should not change. Changed return type of parent. need to smoke test to make sure nothing has been effected. Need to smoke test `Location` and `LabwareLike`.

[RCORE-425]: https://opentrons.atlassian.net/browse/RCORE-425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-01-10 22:32 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/labware.py
> +    def parent(self) -> Union[str, ModuleTypes, None]:
`Union[str, ModuleTypes, None]` is definitely what this return type should be, but I'm wondering what our API versioning obligations are?

Maybe we should leave a note in the public docstring that says on API versions <2.14, `.parent` when loaded on a module will not be a usable object?

2023-01-11 18:58 UTC, mcous commented on api/src/opentrons/protocol_api/labware.py
>          """The parent of this labware. Usually a slot name."""
Following up on Max's suggestion for this docstring

```suggestion
        """The parent of this labware.
        
        If the labware is on the deck, a `str` deck slot name will be returned.
        If on a module, the parent :py:class:`ModuleContext` will be returned.
        If off deck, `None` will be returned.
        
        .. versionchanged:: 2.14
            Return type for module parent changed to :py:class:`ModuleContext`.
            Prior to this version, an internal geometry interface is returned.
        """
```

2023-01-11 19:45 UTC, TamarZanzouri commented
Tested on an OT-2 with core ff on and off. works good after fixing the `ModuleContext.__repr__`

2023-01-12 18:19 UTC, mcous requested changes
Looks great! I have some final changes to request on the module repr. Let me know if you want to pair on them

2023-01-12 18:19 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +        return f"{self._engine_client.state.modules.get_definition(self.module_id).displayName} on {self.get_deck_slot()}"
Can we shuffle some stuff around a little between here and the `ModuleContext` for clarity?

```suggestion
        return self._engine_client.state.modules.get_definition(self.module_id).displayName
```

2023-01-12 18:19 UTC, mcous commented on api/src/opentrons/protocol_api/core/protocol_api/legacy_module_core.py
> +        return f"{self.get_model()} on {self.get_deck_slot()}"
`get_model` is different than "display name". Let's tweak `ModuleGeometry` a little so we can do this:

```suggestion
        return self._geometry.display_name
```

Where `ModuleGeometry.display_name` is set to the already existing `__init__` arg called `display_name`. This will require a slight tweak to move some logic in `ModuleGeometry.__init__` to `ModuleGeometry.__repr__`, which we can walk through together if you like

2023-01-12 18:19 UTC, mcous commented on api/src/opentrons/protocol_api/module_contexts.py
>          )
Per comment above, I want to move the common `on {slot}` part of the repr into `__repr__` rather than burying / duplicating it in `ModuleCore.get_display_name`. Also, we should update this to use an f-string while we're in here. Later, as part of RCORE-542, I want to see if we can ditch this `self.__class__.__name__` silliness

```python
class_name = self.__class__.__name__
display_name = self._core.get_display_name()
location = self._core.get_slot_name().value

return f"{class_name} at {display_name} on {location} lw {self.labware}"
```

2023-01-12 20:56 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/module_contexts.py
>          )
this change will make it easier to debug as well!

2023-01-13 16:20 UTC, mcous commented on api/src/opentrons/protocol_api/core/protocol_api/legacy_module_core.py
> +        return self._geometry._display_name
Do not access private parameters; add a public `display_name` property to module geometry, instead

2023-01-13 16:20 UTC, mcous commented on api/src/opentrons/protocol_api/core/protocol_api/module_geometry.py
> +        return f"{self._display_name}{' on '+str(self.parent) if self.parent else ''}"
Lets try to avoid f-string weirdness like this. Use variables to avoid the quirky stuff that Python [hasn't fixed yet](https://peps.python.org/pep-0701/) 

```suggestion
        location = f" on {self.parent}" if isinstance(self.parent, str) else ""
        return f"{self._display_name}{location}"
```

2023-01-13 16:20 UTC, mcous commented on api/src/opentrons/protocol_api/core/protocol_api/module_geometry.py
> +        self._display_name = display_name
Add public display name property

```python
@property
def display_name(self) -> str:
    return self._display_name
```

2023-01-13 16:51 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/protocol_api/legacy_module_core.py
> +        return self._geometry._display_name
```suggestion
        return self._geometry.display_name
```

2023-01-13 18:02 UTC, mcous approved these changes
Just some test feedback, otherwise looks good

2023-01-13 18:02 UTC, mcous commented on api/tests/opentrons/protocol_api/test_module_context.py
> +    assert subject.parent == DeckSlotName.SLOT_1
Make sure this method is returning a plain string

```suggestion
    assert subject.parent == "1"
    assert not isinstance(subject.parent, DeckSlotName)
```

2023-01-13 18:02 UTC, mcous commented on api/tests/opentrons/protocol_api/test_labware.py
> +from opentrons.protocol_api.module_contexts import TemperatureModuleContext
Import from `opentrons.protocol_api` directly, instead, to match existing conventions

2023-01-13 18:02 UTC, mcous commented on api/tests/opentrons/protocol_api/core/engine/test_module_core.py
> +    mock_definition = decoy.mock(cls=ModuleDefinition)
`ModuleDefinition` is a value object; do not mock it. Instead, return an actual instance. It's ok for it to be partial.

```python
module_definition = ModuleDefinition.construct(  # type: ignore[call-arg]
    displayName="abra kadabra",
)
```

As a rule of thumb, it's almost never a good idea to mock a dataclass or Pydantic model

2023-01-13 20:52 UTC, merged

2023-01-13 23:58 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_api/test_module_context.py
> +    assert subject.parent == DeckSlotName.SLOT_1
Because `DeckSlotName` inherits from `str`, an `== "1"` check isn't sufficient to make sure the subject is returning a plain string.

```python
>>> from enum import Enum
>>> class MyEnum(str, Enum):
...     MY_VALUE = "abc"
...
>>> MyEnum.MY_VALUE == "abc"
True
>>> isinstance(MyEnum.MY_VALUE, str)
True
```

If this is important, I would do something like:

```python
assert type(subject.parent) == str
assert subject.parent == "1"
```