refactor(app): copy updates in the 96-channel flows
OpenTrons/opentrons-api pull request #11974
Opened 2023-01-10 17:28 UTC by jerader

closes RLIQ-276

# Overview

A bunch of copy updates in the 96-channel flows (attach, detach, calibrate). Note: this is not design QA so the images, formatting, etc might not match figma, only the text should match.

# Changelog

- make 96-channel flow header dynamic when attaching with other pipettes that need to be removed
- make text dynamic for 96-channel option in `ChoosePipette`
- make edits throughout all the 96-channel flow components and update the tests

# Review requests

- should match the text in figma and retain full functionality 

# Risk assessment

low

2023-01-10 20:03 UTC, ecormany requested changes
Just a few small changes. Double check if any of them impacted tests.

2023-01-10 20:03 UTC, ecormany commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "next": "next",
```suggestion
  "next": "Next",
```
I think this is button text, so it should be sentence case.

2023-01-10 20:03 UTC, ecormany commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "loose_detach": "Loosen Screws and Detach {{pipetteName}}, {{volume}}uL",
Won't the capacity be included in `pipetteName`? Either way, I don't think we'll use µL units here (like with GEN2 pipettes, we have the P300 which maxes out at 300 µL, but it doesn't have "µL" in the name).

2023-01-10 20:03 UTC, ecormany commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "connect_mounting_plate": "Attach Mounting Plate",
String name here is a little confusing, given the copy change. Maybe `attach_mounting_plate` here and `attach_mounting_plate_instructions` on the next line.

2023-01-10 20:03 UTC, ecormany commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "secure_pipette": "Hold the pipette so it does not fall. Then loosen the four captive screws on the front of the pipette. Once all the screws are loosened, slowly remove the pipette by sliding the
```suggestion
  "secure_pipette": "Hold the pipette so it does not fall. Then loosen the four captive screws on the front of the pipette. Once all the screws are loosened, slowly remove the pipette by sliding it towards the front of the robot, off the supporting pins.",
```

2023-01-10 20:03 UTC, ecormany commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "attach_pip": "attach pipette",
button text?
```suggestion
  "attach_pip": "Attach pipette",
```

2023-01-10 20:07 UTC, jerader commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "next": "next",
thanks for noticing this, it will be capitalized in the component! I think the best practice is to not capitalize anything in the i18n strings and have the component capitalize it but we do a pretty bad job of sticking with that.

2023-01-10 20:12 UTC, jerader commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "attach_pip": "attach pipette",
this button text will also be capitalized the same way I mentioned above!

2023-01-10 20:28 UTC, jerader commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "secure_pipette": "Hold the pipette so it does not fall. Then loosen the four captive screws on the front of the pipette. Once all the screws are loosened, slowly remove the pipette by sliding the
oops thanks for catching this!

2023-01-10 21:38 UTC, ecormany commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "attach_pip": "attach pipette",
cool. as an editor i'm always skeptical of whether case transformations will work the way i want…this would be an excellent thing to build into tests: the string is stored as `attach` but we look for `Attach` on the button itself.

2023-01-10 21:39 UTC, ecormany approved these changes
Copy changes are good, thanks!

2023-01-12 19:01 UTC, smb2268 approved these changes
looks good!!

2023-01-12 19:10 UTC, merged