refactor(api): load labware in engine core without explicit namespace or version
OpenTrons/opentrons-api pull request #11983
Opened 2023-01-11 19:29 UTC by jbleon95

# Overview

Closes RCORE-524.

This PR adds being able to load labware without explicitly giving the namespace and/or version in `ProtocolContext.load_labware`. The ProtocolEngine `LabwareView` will attempt to find the missing parameters based on what is already loaded into state. This implementation is different from the legacy, which would only try the `opentrons` and `custom_beta` namespaces if a namespace wasn't provided, and always default to version `1`.

New errors will be raised and propagated up to the user if
- There are multiple labware that much the given criteria
- There is only labware that partially matches the given criteria.

If no matching labware can be found in state, namespace and version will be defaulted to `opentrons` and `1` respectively.

# Changelog

- refactored engine core `load_labware` to attempt to find namespace or version if they are not provided
- added `find_labware_params` to `LabwareView` which will look through state for any unambiguously matching labware and return the appropriate parameters
- added `NonExistentLabwareError` and `AmbiguousLoadLabwareParamsError` to `ProtocolEngine`

# Review requests

Tested analyzing and loading custom labware as described in the ticket.

# Risk assessment

Low, changes are isolated to the engine core implementation, and worst case will use the same parameters as before.

2023-01-11 21:15 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +class LabwareLoadParams(NamedTuple):
niptick can we change this to:
```suggestion
class LoadLabwareParams(NamedTuple):
```

2023-01-11 21:15 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/errors/exceptions.py
> +class NonExistentLabwareError(ProtocolEngineError):
niptick can we change this to:
```suggestion
class LabwareDoesNotExistError(ProtocolEngineError):
```

2023-01-11 21:21 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +    def find_labware_params(
niptick? not sure about this name
```suggestion
    def get_labware_definition_params(
```

2023-01-11 21:29 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +            raise errors.AmbiguousLoadLabwareParamsError(
Should this be a different error type? or should we change this raised error to match both cases? its ok to leave it as is as well

2023-01-11 21:31 UTC, TamarZanzouri approved these changes
LGTM! small tiptick changes :-)

2023-01-12 00:26 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/labware.py
> +            raise errors.AmbiguousLoadLabwareParamsError(
I agree; this feels like "labware not found" to me.

2023-01-12 00:26 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/labware.py
> +        if namespace is not None and version is None:
To avoid needing an explicit `if` block for the different combinations, what do you think about this alternative implementation?

```python
def find_labware_params(
    self,
    load_name: str,
    namespace: Optional[str],
    version: Optional[int],
) -> LabwareLoadParams:
    def is_acceptable(definition: LabwareDefinition) -> bool:
        has_acceptable_load_name = definition.parameters.loadName == load_name
        has_acceptable_namespace = (
            namespace is None or definition.namespace == namespace
        )
        has_acceptable_version = version is None or definition.version == version

        return (
            has_acceptable_load_name
            and has_acceptable_namespace
            and has_acceptable_version
        )

    matching_definitions = [
        definition
        for definition in self._state.definitions_by_uri.values()
        if is_acceptable(definition)
    ]

    if len(matching_definitions) == 0:
        raise NonExistentLabwareError("...")
    elif len(matching_definitions) > 1:
        raise AmbiguousLoadLabwareParamsError("...")
    else:
        found_definition = matching_definitions[0]
        return LabwareLoadParams(
            load_name=load_name,
            namespace=found_definition.namespace,
            version=found_definition.version,
        )
```

2023-01-12 00:26 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/labware.py
> +    def find_labware_params(
"Find" feels appropriate to me here because it's an $O(n)$ search. To me, "get" connotes a cheap $O(1)$ retrieval.

And instead of "definition," what about `find_labware_load_params()` (or `find_load_labware_params()`) to match the name of the return type?

2023-01-12 00:26 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/labware.py
> +        if namespace is not None and version is None:
Note that if all params are specified explicitly *and they don't point to any valid labware,* my implementation will raise an error. This departs from this behavioral spec proposed in the ticket:

> If all params specified explicitly, simply return them

But I think this departure is okay. The `loadLabware` command that immediately follows the call to this function would have raised a similar error, anyway.

2023-01-12 00:26 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/errors/exceptions.py
> +class NonExistentLabwareError(ProtocolEngineError):
Agreed. `...DoesNotExist` is consistent with `LabwareDefinitionDoesNotExistError` and `LabwareOffsetDoesNotExistError`.

2023-01-12 00:26 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/errors/exceptions.py
> +class NonExistentLabwareError(ProtocolEngineError):
However:

* I don't think it's strictly correct to call this a `Labware`. A `Labware`, to me, means a specific loaded instance, as opposed to a labware definition. The new search function added in this PR searches through a set of labware definitions, not loaded instances.
* We already have `LabwareDefinitionDoesNotExistError`. `loadLabware` raises it when it can't find anything with the provided `loadName`+`namespace`+`version`. Should we just reuse that?

2023-01-12 00:26 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/labware.py
> +class LabwareLoadParams(NamedTuple):
As long as there's no danger of confusion with the `LoadLabwareParams` Pydantic model. No strong preference from me, either way.

2023-01-12 14:55 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +class LabwareLoadParams(NamedTuple):
same. no strong preference!

2023-01-12 15:42 UTC, jbleon95 commented on api/src/opentrons/protocol_engine/state/labware.py
> +        if namespace is not None and version is None:
There's another subtle difference with this approach, and that being that a "partial" match (i.e. `load_name` matches a definition but not a given `namespace` and/or `version`) would raise a "LabwareDefinitionDoesNotExistError ` not found from this method, which would **not** propagate to the user, but instead get caught in the engine core and use the default namespace and version.

Realistically this would still most likely fail later in `loadLabware`, so I'm not against this approach, but it's something to consider as far as how we want to communicate this to the end user.

2023-01-19 17:40 UTC, mcous requested changes

2023-01-19 17:40 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/engine_param_validation.py
> +from .exceptions import AmbiguousLoadLabwareParamsError
Little comment, but let's define this exception here, where it's raised. I don't think there's much value to putting it in a file called `exceptions.py` just because it's an exception

2023-01-19 17:40 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/engine_param_validation.py
> +def resolve_load_labware_params(
Lets rename this file to reflect what its job is. Something like `load_labware_params.py`

2023-01-19 17:40 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/engine_param_validation.py
> +    custom_load_labware_params: List[LabwareLoadParams],
Something that confused me the first time I read this is that, as written, this list of `LabwareLoadParams` all have the same `load_name`, so in the context of this function, it's unused data.

I have a suggestion in the `LabwareView` changes to address this

2023-01-19 17:40 UTC, mcous commented on api/src/opentrons/protocol_engine/state/labware.py
> +            and matches_params(definition)
When I heard this solution described out loud, I had imagined:

- ProtocolEngine selector that returns _all_ non-Opentrons load params in state
- A protocol API core unit to filter on all params

I think that makes the intent a little more clear (see my comment above), so I would suggest moving this `matches_params` filter to the PAPI core unit

2023-01-19 17:40 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +        )
(Comment 3 of 3) I think the core logic pipeline is good, we should just shuffle some stuff around:

```suggestion
        custom_labware_params = (
            self._engine_client.state.labware.get_all_custom_labware_load_params()
        )
        namespace, version = engine_param_validation.resolve_load_labware_params(
            load_name=load_name,
            namespace=namespace,
            version=version,
            custom_labware_params=custom_labware_params,
        )
```

2023-01-20 16:59 UTC, mcous approved these changes

2023-01-20 16:59 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/load_labware_params.py
> +        load_name:
```suggestion
        load_name: Load name of the labware.
```

2023-01-20 18:45 UTC, merged