feat(hardware-testing, shared-data): DVT pipettes in shared-data; HW assembly qc test script
OpenTrons/opentrons-api pull request #11995
Opened 2023-01-12 19:51 UTC by andySigler

# Overview

This PR adds `pipette_assembly_qc_ot3` script to hardware-testing, and makes some other changes to facilitate that script.

NOTE: have not yet tested on an unmodified DVT pipette. But this script works and was tested on an EVT ot3 with:
- EVT single-channel pipettes
- EVT pipettes with DVT serial numbers
- electrically modified DVT pipettes

# Changelog

- adds `v3.4` model pipette to shared data
- fixes bug in shared-data where pick-up-tip-speed was too high (`10` instead of `5`)
- adds script `hardware_testing.production_qc.pipette_assembly_qc_ot3` to test fully assembled DVT pipettes
- adds script `hardware_testing.production_qc.pipette_current_speed_qc_ot3` to test partially assembled DVT pipettes
  - this script is ran on a fixture, not a fully assembled OT3, that is why it does not use `OT3API` at the moment
- adds pressure-fixture Arduino firmware source files to `./opentrons/hardware-testing/firmware` folder
- adds pressure-fixture driver

# Review requests

# Risk assessment

2023-01-12 19:57 UTC, Laura-Danielle requested changes
If we want to differentiate between `v3_3` and `v3_4`, we should add an additional version called `3_4.json` (in `pipette/definitions/2/**`). Once I add GEN1/GEN2 pipettes to the new configuration then we will fully support versioning in the v2 schema version of pipettes.

Would be _great_ to not have to keep adding to v1 of the schema version for pipette QC. Let us know what we can do to support that transition.

2023-01-12 19:57 UTC, Laura-Danielle commented on hardware-testing/hardware_testing/production_qc/pipette_current_speed_qc_ot3.py
> +    "p1000_single_v43": None,
Is it possible to stop using v3 versus v4 to denote which tip size we're using? Otherwise it's gonna get real confusing. We already support different tip functions for the same pipette model.

2023-01-14 20:49 UTC, andySigler commented on hardware-testing/hardware_testing/production_qc/pipette_current_speed_qc_ot3.py
> +    "p1000_single_v43": None,
I removed the line from the `pipette_current_speed_qc_ot3.py` script, but I'm not quite sure what your requesting re: shared-data. I don't see pipette model versions specified in the `pipette/definitions/2/**`, so I don't see what I should be mimicking.

2023-01-24 14:56 UTC, sfoster1 requested changes
extra request-changes to prevent merging and not what has to be changed before merge (branch currently has a hack to work around DVT pipette mount detection not working)

2023-01-24 14:56 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tools/detector.py
> -            attached_status_request = message_definitions.AttachedToolsRequest()
Note for future: Remove this a) before merging b) once https://github.com/Opentrons/ot3-firmware/pull/551 is merged c) once all hardware is DVT or has its mount id stuff reworked as mentioned in that pr

2023-02-28 18:46 UTC, Laura-Danielle approved these changes
This lgtm now.

2023-03-08 14:30 UTC, sfoster1 approved these changes
- that `hardware-testing/build_fw.sh` is empty
- not sure if we need the new entry in the schema v1 pipette defs

Other than that looks good and won't block on those since they're not _wrong_, per se

2023-03-08 14:30 UTC, sfoster1 commented on shared-data/pipette/definitions/1/pipetteModelSpecs.json
> +    "p1000_single_v3.4": {
@Laura-Danielle do we need this entry?

2023-03-08 15:46 UTC, Laura-Danielle commented on shared-data/pipette/definitions/1/pipetteModelSpecs.json
> +    "p1000_single_v3.4": {
We do not.

2023-03-08 17:09 UTC, merged