feat(system-server): add system-server to buildroot
OpenTrons/opentrons-api pull request #12021
Opened 2023-01-18 16:55 UTC by fsinapi

# Overview

In order to include the system-server project in the OT-2 buildroot build, we need a Config.in and a systemd system file.

# Test Plan

Make a companion buildroot PR that adds the system-server project, and then:

- [ ] Ensure that the two branches (buildroot & monorepo) build an update image
- [ ] Upload the image to an OT-2
- [ ] Check that systemctl is running the `system-server` application
- [ ] Open a python repl and verify that `PyJWT` is available

# Changelog

- Added buildroot configuration files for the system-server project

# Review requests

# Risk assessment

Medium. This is going to be added into the OT-2 image, so it's important to verify that the robot still functions with this running the background for now.

2023-01-18 17:40 UTC, sfoster1 requested changes
A small change needed - and also this won't get built unless you add it to the defconfig in buildroot

2023-01-18 17:40 UTC, sfoster1 commented on system-server/Config.in
> +  bool "python-opentrons-robot-server"
```suggestion
  bool "python-opentrons-system-server"
```

2023-01-18 17:42 UTC, sfoster1 approved these changes
Looks good to me pending testing.

2023-01-18 17:51 UTC, vegano1 commented
config-wise this looks good

2023-01-18 17:52 UTC, vegano1 approved these changes

2023-01-19 18:34 UTC, fsinapi commented
Added systemd notification integration and tested on an OT-2. Confirmed that the notification gets sent to systemd.

2023-01-19 18:56 UTC, sfoster1 approved these changes
Looks good!

2023-01-19 19:42 UTC, merged