feature(hardware): add mechanism that raises exception if a firmware update is required.
OpenTrons/opentrons-api pull request #12058
Opened 2023-01-25 19:10 UTC by vegano1

# Overview

If the OT3 requires an update to one of the firmware submodules (head, gantry, pipettes, etc) then we dont want the user to be able to use the robot until the updates are all complete. We want this to insure uniformity between releases so we know what a submodule should be running.

This will add an internal flag and decorator mechanism to be used for functions that send can messages, while we only want firmware updates and deviceInfoRequests/Response messages to go out. This decorator currently always defaults to False so nothing happens, but the next ticket will drive this based on whether a firmware update is required or not.

Closes [RCORE-475](https://opentrons.atlassian.net/browse/RCORE-475)
Merge after [RCORE-476](https://github.com/Opentrons/opentrons/pull/12035)

# Test Plan
- [ ] Make sure the robot server service starts up on the OT3
- [ ] Make sure this change does not affect functionality in any way, as it always defaults to false for now.

# Changelog

- Added requires_update decorator along with an internal flag that raises FirmwareUpdateRequired if the internal flag is True
- Added requires_update decorator to functions in the OT3Controller class which sends can messages.

# Review requests

- Any reason why we would not want to raise an exception here?

# Risk assessment

Low, OT3 only, and functionality is disabled by default

2023-01-26 15:58 UTC, sfoster1 requested changes
The decorator looks good. I think we should move where the exception is defined, and we should drop in a test to make sure the decorator raises an exception properly.

2023-01-26 15:58 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_update/errors.py
> +class FirmwareUpdateRequired(FirmwareUpdateException):
I think this wants to live in `hardware_control/types.py` (or split that file into `hardware_control/types.py` and `hardware_control/errors.py`). This exception will have to be handled by layers above the `opentrons` module, and we don't want them to have to import this module to get at the exception class.

2023-01-27 17:37 UTC, sfoster1 approved these changes
Looks great to me!

2023-01-27 18:08 UTC, fsinapi approved these changes
Nice!

2023-01-30 14:53 UTC, merged