feat(hardware_control): Added firmware update mechanism for submodules
OpenTrons/opentrons-api pull request #12076
Opened 2023-01-27 21:18 UTC by vegano1

# Overview

We need to be able to update the firmware on attached submodules when the system starts up, this pr works off [RCORE-475](https://opentrons.atlassian.net/browse/RCORE-475), and [RCORE-476](https://opentrons.atlassian.net/browse/RCORE-476) to make this happen.

Closes [RCORE-477](https://opentrons.atlassian.net/browse/RCORE-477)

# Test Plan

- The robot-server starts up
- The `/usr/lib/firmware/opentrons-manifest.json` file is serialized into a dict of FirmwareUpdateType and UpdateInfo.
- The DeviceInfoCache is queried from all nodes on the network and cached in the NetworkInfo class instance.
- The OT3Controller class drives and checks if any subsystem is out of date and returns a list of submodules to be updated
- If any submodules need to be updated the _update_requied flag is set to True and subsequent calls to move the motors or anything not pertaining to firmware updates will raise a `FirmwareUpdateRequired` exception.
- The firmware will start to get installed on all out-of-date modules.

# Changelog

- Added firmware_manifest.py module that will handle serializing the opentrons-firmware.json manifest file
- Added a mechanism to OT3Controller which checks individual subsystems and determines if they need to be updated based on the `shortsha`
- Starts firmware updates for all out-of-date subsystems on the network.

# Review requests

- Does this make sense? Is there anything im overlooking?

# Risk assessment

Mid, this will raise a new exception if the firmware is out of date and we attempt to move the gantry/gripper/etc so we will need to handle that.

# Todo:
- Add code coverage for new functionality
- Switch to the method that updates multiple nodes at once

2023-01-27 21:50 UTC, sfoster1 requested changes
The functionality looks good (except for the not-running-the-update-coroutine) but in my opinion this is too much functionality for `OT3Controller` specifically. I think that
- The behavior in `check_firmware_updates` and `get_update_type` should be pushed down to `opentrons_hardware`, where they can be free functions that get lists of node ids or something
- The decision point about when to do a firmware update at boot should be pushed _up_ to the package initializer `opentrons.__init__`, which pulls it out of a specific really annoying point to debug and makes it more like other startup behaviors
- If we use https://github.com/Opentrons/opentrons/blob/5a224b0e4c4c0614ac1d5af2091b32219ec7579a/api/src/opentrons/hardware_control/types.py#L266 as an intermediate type, we can push the functionality of `do_firmware_updates` up to `ot3api`
- Also, I think this would help us avoid having `OT3Controller._attached_tools`, which is a duplicate cache of pretty complex functionality in `ot3api` - we should feed that information from the cache at the higher level

I do agree with pretty much everything you've done, just not necessarily _where_ you've done it - and that's just context with the codebase.

2023-01-27 21:50 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        elif "pipette" in node_id.name:
I have the feeling this function should be pushed down into `opentrons_hardware`, and be a function that takes the current set of node IDs and `self._attached_tools`. All the data types that the function consumes or returns are from opentrons_hardware, and the functionality is pretty straight lookup.

2023-01-27 21:50 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            return FirmwareUpdateType.from_string(node_id.name)
would be much more comfortable not involving strings here anywhere and just looking this up from the node id

2023-01-27 21:50 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +                log.error(f"Unknown firmware update type {update_type}")
should also log the node id this message is about

2023-01-27 21:50 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +                    f"Subsystem {node} requires an update '{version_cache.shortsha} != {update_info.shortsha}'"
let's label in the logs which is the version cache and which is from the node

2023-01-27 21:50 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    def check_firmware_updates(
I think this, too, can be pushed down to `opentrons_hardware` for basically the same reason - its input and output types are all defined in `opentrons_hardware`. 

That would have the interesting side effect of pushing all handling of the manifest down into `opentrons_hardware`, which would be nice IMO because that way everything about the updates is in there, except for starting. It pushes `opentrons_hardware` farther toward "a collection of functionality that higher levels can pick from"

2023-01-27 21:50 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        self.do_firmware_updates()
this won't quite do what you want - it will create a coroutine to do the updates, but never schedule it to run, and nothing would know it exists.

I also think that, in contrast to a lot of other comments in this PR that are variants of "let's push this down a level", the decision on _when_ to do updates should be pushed _up_ a level or two. I think the hardware controller, the code in `ot3api`, should have a method that says "go do the firmware updates you currently find important", and I think that method should be called very specifically here: https://github.com/Opentrons/opentrons/blob/5a224b0e4c4c0614ac1d5af2091b32219ec7579a/api/src/opentrons/__init__.py#L161

That's because anything that happens inside 
- The `OT3Controller` constructor 
- The builder function for `OT3Controller` [here](https://github.com/Opentrons/opentrons/blob/5a224b0e4c4c0614ac1d5af2091b32219ec7579a/api/src/opentrons/hardware_control/ot3api.py#L238-L262)
- The contructor for `OT3API`

actually, in the real system, occurs in this annoying separate thread [here](https://github.com/Opentrons/opentrons/blob/5a224b0e4c4c0614ac1d5af2091b32219ec7579a/api/src/opentrons/hardware_control/thread_manager.py#L177-L196) and it's _incredibly_ annoying to find and debug an error that occurs in any of them.

Also, that first place I linked in the package `__init__` method is where we do other startup behaviors, like z-homing.

2023-02-06 15:40 UTC, sfoster1 reviewed
Looking really solid. I think `OT3Controller` is still doing a little too much, but overall good!

2023-02-06 15:40 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +                pipettes[node_id] = pipette.get("channels", 0)
I think that rather than checking the channel count, which is an artifact of a higher level - it's data established and controlled by `ot3api` and meant for consumption largely by the protocol engine - we should massage the data in `ot3api` where this is called _from_ - so we just give it `pipette_kind: Dict[OT3Mount, PipetteType]` where `PipetteType` is from somewhere or other, maybe write it new

2023-02-06 15:40 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_bindings/messages/fields.py
> +    NUM_BYTES = 8
Is this a change to the number of bytes on the wire, or were we incorrectly not parsing the 8th byte before?

2023-02-06 17:59 UTC, vegano1 commented on hardware/opentrons_hardware/firmware_bindings/messages/fields.py
> +    NUM_BYTES = 8
we were not parsing the 8th byte

2023-02-08 16:04 UTC, sfoster1 requested changes
There's a couple smaller things I have in there about what the right way to present an optional is and what default arguments should be, but I think there's one other problem which is layer violations and intermingling of types.

In my opinion, `channel_count` shouldn't ever be exposed to `opentrons_hardware` and it shouldn't make decisions on it. Instead, those decisions should be made in the hardware controller with some mapping from pipette types or channels to `opentrons_hardware` firmware update details and sent down that way. Using channels implicitly binds in data about pipette functionality that `opentrons_hardware` otherwise doesn't need to know, and it's worth adding a couple more layers of indirection to keep `opentrons_hardware` as a leaf module that consumes no information from `opentrons`.

2023-02-08 16:04 UTC, sfoster1 commented on api/src/opentrons/__init__.py
> +        if ff.enable_ot3_firmware_updates():
[nit]: let's push the feature flag check inside `_do_updates` in parallel with `should_use_ot3` so the high-level behavior of startup is more similar when the flag is or isn't enabled - create the task either way. It creates one less thing that can fail in one configuration but not the other.

2023-02-08 16:04 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        nodes: Optional[Set[NodeId]] = set(),
I think this should default `None` if it's going to be optional, unless empty-set and `None` have different behavior. If they do, we should still default this to none and change it if we ever modify this argument, because of the unsafety of binding objects as default arguments in python - `set()` will be evaluated at parse time, and the resulting instance stored on the class, so if this function is called with the default argument for `nodes` and it's modified, that modification will be present on subsequent calls too.

2023-02-08 16:04 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +                pipettes[node_id] = pipette.get("channels", 0)
I don't think this was resolved - we're still checking the channel count directly here.

2023-02-08 16:04 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            node_id = sensor_node_for_mount(mount)
let's not reuse `sensor_node_for_mount` directly - what if we end up wanting to change it in the future and use a different node id for sensors? let's try going from mount to subsystem and then subsystem to node id, should be more flexible.

2023-02-08 16:04 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            if node_id != NodeId.gripper:
at that point we can make decisions like this based on subsystem rather than node ID which I think is a little nicer

2023-02-08 16:04 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        force = False
i'm always a little suspicious of function-scope variables like this that act as flags, I think it's a little easy to mess them up. What if instead we do something like
```
if nodes:
    force_device_info = {node: cache_info ...}
    firmware_updates = firmware_update.check_firmware_updates(force_device_info, pipettes, force=True)
else:
    firmware_updates = firmware_update.check_firmware_updates(self._network_info.device_info, pipettes, force=False)
```

we could even factor the above into its own little helper function, maybe even defined inside the body of `update_firmware`, so that we could eventually do `firmware_updates = get_firmware_updates(pipettes, nodes)`

2023-02-08 16:04 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        if firmware_updates:
sort of a nit, but if we invert this:
```
if not firmware_updates:
    log.info("No firmware updates required")
    self.update_required = False
    return

log.info("Firmware updates are available.")
self.update_required = True
...
```
then it's a bit easier to read the rest of the function since you no longer have to keep in mind that you're in the scope of the `if`.

2023-02-08 16:04 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        attached_pipettes: Dict[OT3Mount, PipetteDict],
I'm still a little uncomfortable about this being passed in. I think this data just doesn't belong in `ot3controller`. What if we have this function take a list of "peripheral subsystems to check"?

2023-02-08 16:04 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
>          pass
this probably wants a yield

2023-02-08 16:04 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        attached_pipettes = self._pipette_handler.get_attached_instruments()
what if we transform this into a list of "attached tool subsystems" and pass _that_ into `update_firmware`?

2023-02-08 16:04 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_update/utils.py
> +    firmware_manifest: Union[str, Path] = str(),
we shouldn't use empty-string as a default here, both because it means the default variable could end up being mutated and because semantically it's unclear from the function signature. Instead, let's use `Union[str, Path, None]` or even better just pick `Optional[Path]` and `=None` to indicate that it's optional.

2023-02-08 16:04 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_update/utils.py
> +    if not os.path.exists(opentrons_firmware):
[nit]: imo we should just immediately try and open it, and catch and reformat exceptions

2023-02-08 16:04 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_update/utils.py
> +    force: Optional[bool] = False,
if we're going to have this be `Optional` it should default to `None`

2023-02-08 16:04 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_update/utils.py
> +        if attached_pipettes and node in [NodeId.pipette_left, NodeId.pipette_right]:
This is definitely too far down to push channel-count data and math. It's a concern for the hardware controller, and the hardware controller should be informing this function just what kind of pipette we're dealing with by ideally passing in a `FirmwareUpdateType` or something.

2023-02-08 16:04 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_update/utils.py
> +            update_info.filepath = list(update_info.files_by_revision.values())[0]
I think this will cause problems with https://github.com/Opentrons/oe-core/pull/53 , let's maybe always pull `update_info.files_by_revision["rev1"]` instead

2023-02-08 16:04 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/network.py
> +        self, expected: Optional[Set[NodeId]] = set(), timeout: float = 1.0
if we want a default value here it should be `None` since this is `Optional`

2023-02-08 16:47 UTC, sfoster1 requested changes
Love this refactor but I think we can tease the hardware control and opentrons_hardware layers apart just slightly farther

2023-02-08 16:47 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +                    pipettes[node_id] = channel_to_pipette_type(channels)
Love this refactor, but one little thing is that we try and keep imports from `opentrons_hardware` specifically to `ot3controller`. This does make things a little painful, but the benefit is that it makes it a little easier to massage optional python dependencies. I think the appropriate interface here might be
- Make a new enum in `opentrons_hardware.types` called like `OT3UpdatableSubsystem` that has entries of like `gantry_x`, `gantry_y`, `head`, `pipette_single`, `pipette_multi`, `pipette_96`, `gripper`
- This function builds a `Dict[OT3Mount, OT3UpdatableSubsystem]` and passes it to `OT3Controller.update_firmware`
- `OT3Controller.update_firmware` transforms it into a `Dict[NodeId, PipetteType]`
This is obviously more code, more work, more layers of indirection, but what it _does_ do is cleanly separate the two. If we push hardware control stuff down at some point, or get `opentrons_hardware` onto the OT2, we can remove the redundancy since we won't need the split.

2023-02-08 16:47 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        attached_pipettes: Dict[NodeId, PipetteType],
as mentioned in the comment on `ot3api`, I think the ideal case here is that this argument is specifically a `Dict[OT3Mount, OT3UpdatableSubsystem]` where `OT3UpdatableSubsystem` is pretty much the same thing as the device type enum in `opentrons_hardware`. That keeps the translation between "hardware controller concept" and "`opentrons_hardware` concept" directly in this file, and therefore they remain nice and separated.

2023-02-08 16:47 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        firmware_updates = firmware_update.check_firmware_updates(
we'd insert a transformation before this line to turn the `Dict[OT3Mount, OT3UpdatableSubsystem]` into `Dict[NodeId, PipetteType]` here

2023-02-09 20:58 UTC, sfoster1 requested changes
This is looking awesome! Couple small changes but definitely almost there

2023-02-09 20:58 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        current_tools = dict(OT3Controller._generate_attached_instrs(attached_tools))
nit: returns a dict already right

2023-02-09 20:58 UTC, sfoster1 commented on hardware/manifest.json
> +{"manifest_version": 1, "subsystems": {"head": {"version": 2, "shortsha": "25755efd", "files_by_revision": {"rev1": "head-rev1.hex"}}}}
is this test data? if so it should go in the test area.

2023-02-09 20:58 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_bindings/constants.py
> +    pipette_384 = 4
we should pull this one for now - it's too much future proofing

2023-02-09 20:58 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_update/run.py
> +            print("Subsystem update file not found {filepath}")
should be a `log.error`

2023-02-09 20:58 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_update/run.py
> +        with open(filepath) as f:
similar to the thing with doing `if not <x>: return` to make a function easier to read, can we either factor the content that's inside the `with` into a separate function that takes a `fileio`, or change this back to taking an opened file?

2023-02-09 20:58 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_update/utils.py
> +    pipettes_384 = 7
let's pull this out for now

2023-02-09 21:08 UTC, vegano1 commented on hardware/manifest.json
> +{"manifest_version": 1, "subsystems": {"head": {"version": 2, "shortsha": "25755efd", "files_by_revision": {"rev1": "head-rev1.hex"}}}}
local testing, removed

2023-02-09 21:20 UTC, vegano1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        current_tools = dict(OT3Controller._generate_attached_instrs(attached_tools))
weird looks like I just renamed this to attached_tools while testing, reverting this back to edge.
this is converting a tuple of [OT3Mount, OT3AttachedInstruments] to Dict.

2023-02-09 22:25 UTC, sfoster1 requested changes
Couple testing things

2023-02-09 22:25 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/backends/test_ot3_controller.py
> +async def test_update_firmware(controller: OT3Controller) -> None:
I think really big tests like this that cover multiple cases are better implemented as multiple smaller tests that each cover one case. That means that something that causes all those cases to fail can be detected as such, rather than fixing one case -> on to the next one and now _that_ one's failing, so on and so forth

2023-02-09 22:25 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/backends/test_ot3_controller.py
> +                assert False, "update_firmware raised an exception."
won't this already be raising an exception? why the catch and assert?

2023-02-09 22:25 UTC, sfoster1 commented on hardware/tests/opentrons_hardware/firmware_update/test_utils.py
> +    # test that the file written to disk can be serialized
```suggestion
    # test that the file written to disk can be deserialized
```
(nit)

2023-02-09 22:25 UTC, sfoster1 commented on hardware/tests/opentrons_hardware/firmware_update/test_utils.py
> +def test_load_firmware_manifest_failure(mock_manifest: Dict[str, Any]) -> None:
this is another of those really big tests that test multiple things. we should refactor that into multiple smaller tests so one test failing doesn't block others. in general, these tests where you have multiple blocks of code each with a comment that says what it tests can and should be split at the comments.

2023-02-09 22:25 UTC, sfoster1 commented on hardware/tests/opentrons_hardware/firmware_update/test_utils.py
> +def test_check_firmware_updates_available(mock_manifest: Dict[str, Any]) -> None:
split this

2023-02-10 04:19 UTC, vegano1 commented on api/tests/opentrons/hardware_control/backends/test_ot3_controller.py
> +                assert False, "update_firmware raised an exception."
This specific method wont raise an exception, this is just testing that.

2023-02-10 14:31 UTC, sfoster1 approved these changes
Looks excellent to me once lint passes!

2023-02-10 15:18 UTC, merged