refactor(api): Allow aspirate, dispense and blow-out in place
OpenTrons/opentrons-api pull request #12105
Opened 2023-02-06 17:08 UTC by TamarZanzouri

# Overview

closes https://opentrons.atlassian.net/browse/RCORE-540.
Allow PE and PAPI via engine core to preform aspirate, dispense and blow-out in place.

# Test Plan

Test on an OT-2 with core ff on or on an OT-3.
upload the following protocol:

```
from opentrons import protocol_api, types

metadata = {
    "apiLevel": "2.12",
}

def run(ctx: protocol_api.ProtocolContext) -> None:
    tip_rack = ctx.load_labware("opentrons_96_tiprack_300ul", 6)
    labware = ctx.load_labware("nest_96_wellplate_100ul_pcr_full_skirt", 3)
    pipette = ctx.load_instrument("p20_single_GEN2", types.Mount.RIGHT, [tip_rack])
    well = tip_rack.wells()[0]
    
    # offset the well to something obvious
    # to observe that the offset is not respected
    well_offset = types.Point(x=9, y=-9, z=0)

    pipette.pick_up_tip(well.top().move(well_offset))
    location_no_well = types.Location(point=labware["A1"].top().point, labware=None)
    pipette.move_to(location_no_well)
    pipette.aspirate()
    pipette.blow_out()
    pipette.dispense()
    pipette.drop_tip()
```
- make sure the pipette does an in-place command without a move to.

# Changelog

- Add PE aspirate and blow-out in place commands.
- Added sync_client methods to aspirate, dispense and blow-out in place.
- Wired up engine/core aspirate, dispense and blow-out to use in-place commands when well_core is None.

# Review requests

Does the changes make sense?
Did I forget anything for the PE commands?

# Risk assessment

Low. Should act the same as the legacy papi. Should test with core ff on and off to make sure it behaves the same

2023-02-07 19:23 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/instrument_context.py
> +
```suggestion
```

2023-02-07 19:25 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/aspirate_in_place.py
> +# TODO(mm, 2022-08-15): This command is not yet in the JSON protocol schema.
still need to do this

2023-02-07 19:27 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/aspirate_in_place.py
> +"""Aspirate-in-place command request, result, and implementation models."""
```suggestion
"""Aspirate in place command request, result, and implementation models."""
```

2023-02-07 19:28 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/blow_out_in_place.py
> +"""Blow-out-in-place command request, result, and implementation models."""
```suggestion
"""Blow-out in place command request, result, and implementation models."""
```

2023-02-07 19:33 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +    async def aspirate_in_place(
I should move this logic to the implementation class

2023-02-07 19:37 UTC, TamarZanzouri commented
Tested the aspirate-in-place and dispense-in-place on an OT2 with core ff on. will test blow-out-in-place

2023-02-08 16:48 UTC, TamarZanzouri commented
Tested blow-out in place on an OT2 with ff on. tested dispense in place on dev server. need to test on a robot before merging

2023-02-09 20:53 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        elif location is not None:
```suggestion
        elif location:
```

2023-02-09 20:53 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +            if location is not None:
```suggestion
            if location:
```

2023-02-09 20:55 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/legacy_simulator/legacy_instrument_core.py
> +                        "cause overz aspiration if the previous command is a "
```suggestion
                        "cause over aspiration if the previous command is a "
```

2023-02-09 20:56 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/instrument_context.py
> +        if self._api_version >= APIVersion(2, 14):
I can move this to a function

2023-02-09 20:59 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +            raise ValueError(
```suggestion
            raise RuntimeError(
```

2023-02-09 21:01 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/execution/test_pipetting_handler.py
> +        ValueError,
```suggestion
        RuntimeError,
```

2023-02-10 19:28 UTC, mcous requested changes
A couple little changes, but I think I'd like to get this in pretty close to as-is, pending on-device testing

There's _so_ much cleanup and simplification that we can (and should) do in `InstrumentContext`, but I'm worried about this dragging out. So let's get the behavior in and then rework

2023-02-10 19:28 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +        if self._api_version >= APIVersion(2, 14):
Yeah, let's get it in a private method at least, and use `.core.engine.ENGINE_CORE_API_VERSION`

2023-02-10 19:28 UTC, mcous commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +            raise RuntimeError(
Do not raise a bare `RuntimeError`, create a new specific ProtocolEngine error type

2023-02-10 19:28 UTC, mcous commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +                "blow_out."
Let's simplify this message:

```suggestion
                "Pipette cannot aspirate in place because of a previous blow out."
                " The first aspirate following a blow-out must be from a specific well"
                " so the plunger can be reset in a known safe position."
               
```

2023-02-10 19:28 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +                mount=types.Mount.string_to_mount(self.mount)
```suggestion
                mount=self._core.get_mount()
```

2023-02-15 20:24 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/legacy/legacy_instrument_core.py
> +        print(self._protocol_interface.get_last_location())
```suggestion
```

2023-02-15 20:54 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/legacy/legacy_instrument_core.py
> +        print(self._protocol_interface.get_last_location())
```suggestion
```

2023-02-15 20:55 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/instrument_context.py
> +                location=move_to_location or last_location,  # type: ignore[arg-type]
```suggestion
                location=move_to_location
```

2023-02-15 20:57 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/validation.py
> +    """"""
```suggestion
    """Error representing that no location was supplied."""
```

2023-02-15 20:57 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/validation.py
> +    """"""
```suggestion
    """Error representing that the location supplied is of different expected type."""
```

2023-02-15 22:37 UTC, mcous reviewed
Initial batch of comments on the Protocol API side. Will follow up with the engine-side tomorrow

2023-02-15 22:37 UTC, mcous commented on api/src/opentrons/protocol_api/core/instrument.py
> -            move_to_well: If pipette should be moved before blow-out.
Rework docstring for new argument name + behavior rather than remove

2023-02-15 22:37 UTC, mcous commented on api/src/opentrons/protocol_api/core/legacy_simulator/legacy_instrument_core.py
> +        if location and self.get_current_volume() == 0:
```suggestion
        if self.get_current_volume() == 0:
```

2023-02-15 22:37 UTC, mcous commented on api/src/opentrons/protocol_api/core/legacy_simulator/legacy_instrument_core.py
> +        elif location:
```suggestion
        elif location != self._protocol_interface.get_last_location():
```

2023-02-15 22:37 UTC, mcous commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        in_place: bool = False,
Default parameter value appears to be unused in the actual code, let's make the parameter required

2023-02-15 22:37 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +            )
Raise always remove `"".format` if you're touching code

```suggestion
        except validation.LocationTypeError as e:
            raise TypeError(
                f"location should be a Well or Location, but it is {location}"
            ) from e
```

2023-02-15 22:37 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +        except validation.NoLocationError:
```suggestion
        except validation.NoLocationError as e:
```

2023-02-15 22:37 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
>              )
```suggestion
            ) from e
```

2023-02-15 22:37 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +            )
```suggestion
        except validation.LocationTypeError as e:
            raise TypeError(
                f"location should be a Well or Location, but it is {location}"
            ) from e
```

2023-02-15 22:37 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +        except validation.NoLocationError:
```suggestion
        except validation.NoLocationError as e:
```

2023-02-15 22:37 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
>              )
```suggestion
            ) from e
```

When re-raising, always add `from ...` to the raise:

```python
except validation.NoLocationError as e:
    raise RuntimeError(
        ...
    ) from e
```

This way, Python knows we're continuing a chain of raises rather than messing something up and causing an unrelated error inside the `except` block

2023-02-15 22:37 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +                )
Slight regression in behavior: this "is trash? then use top" should only be applicable if `target.location is None`

```suggestion
            if target.location:
                move_to_location = target.location
            elif well.parent._core.is_fixed_trash():
                move_to_location = target.well.top()
            else:
                move_to_location = target.well.bottom(
                    z=self._well_bottom_clearances.dispense
                )
```

2023-02-15 22:37 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +        except validation.NoLocationError:
```suggestion
        except validation.NoLocationError as e:
```

2023-02-15 22:37 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
>              )
```suggestion
            ) from e
```

2023-02-15 22:37 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +            )
```suggestion
        except validation.LocationTypeError as e:
            raise TypeError(
                f"location should be a Well or Location, but it is {location}"
            ) from e
```

This particular error message is exactly the same between aspirate, dispense, and blow out. I'd be open to moving the message into the original `raise LocationTypeError` and then letting it propagate without an `except`

2023-02-15 22:37 UTC, mcous commented on api/src/opentrons/protocol_api/validation.py
> +    raise LocationTypeError()
Given that we now have a good unit test suite for this function, we can take a refactor pass to combine common logic and improve readability

```suggestion
    target_location = location or last_location

    if target_location is None:
        raise NoLocationError()

    if not isinstance(target_location, (Location, Well)):
        raise LocationTypeError()

    if isinstance(target_location, Well):
        return WellTarget(well=target_location, location=None)

    _, well = target_location.labware.get_parent_labware_and_well()
    in_place = target_location is last_location

    return (
        WellTarget(well=well, location=target_location)
        if well is not None
        else PointTarget(location=target_location, in_place=in_place)
    )
```

2023-02-16 16:27 UTC, TamarZanzouri commented
Test on OT2 with apiLevel 2.14 and 2.12. works as expected!

2023-02-16 21:41 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +            in_place: whether this an in-place command.
```suggestion
            in_place: whether this is an in-place command.
```

2023-02-16 21:42 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +            in_place: whether this an in-place command.
```suggestion
            in_place: whether this is a in-place command.
```

2023-02-16 21:43 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +            in_place: whether this an in-place command.
```suggestion
            in_place: whether this is a in-place command.
```

2023-02-16 21:45 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/legacy_simulator/legacy_instrument_core.py
> +        if location != self._protocol_interface.get_last_location():
```suggestion
        if not in_place:
```

2023-02-16 22:30 UTC, mcous approved these changes
I've just got minor docstring and test comments here. Code and behavior look correct.

Looks like CI is also complaining about formatting, `make format` before committing and pushing should do the trick

2023-02-16 22:30 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +        aspirate_in_place = target.in_place
```suggestion
```

2023-02-16 22:30 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +                in_place=aspirate_in_place,
```suggestion
                in_place=target.in_place,
```

2023-02-16 22:30 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +        dispense_in_place = target.in_place
```suggestion
```

2023-02-16 22:30 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +                in_place=dispense_in_place,
```suggestion
                in_place=target.in_place,
```

2023-02-16 22:30 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +        blow_out_in_place = target.in_place
```suggestion
```

2023-02-16 22:30 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +                in_place=blow_out_in_place,
```suggestion
                in_place=target.in_place,
```

2023-02-16 22:30 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
>          well: Optional[labware.Well]
```suggestion
        well: Optional[labware.Well] = None
```

2023-02-16 22:30 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +            well = None
```suggestion
```

2023-02-16 22:30 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +            well = None
```suggestion
```

2023-02-16 22:30 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
>          well: Optional[labware.Well]
```suggestion
        well: Optional[labware.Well] = None
```

2023-02-16 22:30 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +            well = None
```suggestion
```

2023-02-16 22:30 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +    def _get_last_location_by_api_version(self) -> Optional[types.Location]:
```suggestion
    def _get_last_location_by_api_version(self) -> Optional[types.Location]:
        """Get the last location accessed by this pipette, if any.
        
        In pre-engine Protocol API versions, this call omits the pipette mount.
        This is to preserve pre-existing, potentially buggy behavior.
        """
```

2023-02-16 22:30 UTC, mcous commented on api/src/opentrons/protocol_api/validation.py
> +    """
```suggestion
    """Validate a given location for a liquid handling command.
    
    Args:
        location: The input location.
        last_location: The last location accessed by the pipette.
    
    Returns:
        A `WellTarget` if the input location represents a well.
        A `PointTarget` if the input location is an x, y, z coordinate.
    
    Raises:
        NoLocationError: The is no input location and no cached loaction.
        LocationTypeError: The location supplied is of unexpected type.
    """
```

2023-02-16 22:30 UTC, mcous commented on api/src/opentrons/protocol_api/validation.py
> +            "location should be a Well or Location, but it is {}".format(location)
Always prefer f-strings

```suggestion
            f"location should be a Well or Location, but it is {location}"```

2023-02-16 22:30 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/aspirate_in_place.py
> +# TODO(mm, 2022-08-15): This command is not yet in the JSON protocol schema.
This TODO can be removed! It is officially covered by the command schema v7 autogeneration

2023-02-16 22:30 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/blow_out_in_place.py
> +
```suggestion
```

2023-02-16 22:30 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/aspirate_in_place.py
> +
```suggestion
```

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api/core/engine/test_instrument_core.py
> +        ),
```suggestion
        ),
        mock_protocol_core.set_last_location(location=location, mount=Mount.LEFT),
```

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api/core/engine/test_instrument_core.py
> +        ),
```suggestion
        ),
        mock_protocol_core.set_last_location(location=location, mount=Mount.LEFT),
```

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api/core/engine/test_instrument_core.py
> +def test_blow_out_in_place(
```suggestion
def test_blow_to_coordinates(
```

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api/core/engine/test_instrument_core.py
> +
Add missing `test_blow_out_in_place` where `in_place` is `True`

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api/core/engine/test_instrument_core.py
> +def test_dispense_in_coordinates(
```suggestion
def test_dispense_to_coordinates(
```

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +def test_aspirate_in_place(
This test looks the same as the one above, let's get rid of it

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +            in_place=False,
Let's switch this condition to `True` just to make the data pipeline a hair easier to follow

```suggestion
    ).then_return(PointTarget(location=input_location, in_place=True))
    decoy.when(mock_instrument_core.get_aspirate_flow_rate(1.23)).then_return(5.67)

    subject.aspirate(volume=42.0, location=input_location, rate=1.23)

    decoy.verify(
        mock_instrument_core.aspirate(
            location=input_location,
            well_core=None,
            in_place=True,
```

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +        subject.aspirate(location=None)
Given that we're not catching and re-raising the `LocationTypeError` anymore, I don't think we need this test

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +    point_target = PointTarget(location=input_location, in_place=False)
Same comment as above, I think we should switch this to `True` to make the pipeline easier to follow, and then we can get rid of `test_blow_out_in_place` below, because there's no difference between "at coordinates" and "in place" at the InstrumentContext level; it's just passing values through

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +def test_blow_out_raises_wrong_location_value(
Same comment: we can remove this test I think

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +def test_dispense_in_place(
Unnecessary test, see same comment on aspirate and dispense

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +    ).then_return(PointTarget(location=input_location, in_place=False))
Go with `in_place=True` here instead

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +def test_dispense_raises_wrong_location_value(
Can delete this test

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api/test_validation.py
> +    """Should return a WellTarget with no location."""
```suggestion
    """Should return an `in_place` PointTarget."""
```

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api/test_validation.py
> +    """Should return a PointTarget for none in_place commands."""
```suggestion
    """Should return a PointTarget for a non-Well Location."""
```

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api/test_validation.py
> +    """Should return a PointTarget for in_place commands."""
```suggestion
    """Should return a PointTarget for non-Well previous Location."""
```

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api/test_validation.py
> +
Let's add one more `in_place=True` test that checks `input_location` equal to `last_location`.

Make sure we construct two equal `Location` instances for this test rather than passing the same instance to `location` and `last_location`

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api_old/core/simulator/test_instrument_context.py
> +            in_place=False,
```suggestion
            in_place=True,
```

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api_old/core/simulator/test_instrument_context.py
> +    subject.home()
`move_to_well=False` should change to `in_place=True`. If we do that, is the `subject.home()` needed?

```suggestion
```

2023-02-16 22:30 UTC, mcous commented on api/tests/opentrons/protocol_api_old/core/simulator/test_instrument_context.py
> +        in_place=False,
```suggestion
        in_place=True,
```

2023-02-17 17:41 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_api_old/core/simulator/test_instrument_context.py
> +    subject.home()
nice catch!

2023-02-17 19:04 UTC, mcous approved these changes
Still LGTM!

2023-02-17 19:13 UTC, merged