docs(api): Officially remove the `height` parameter of `MagneticModuleContext.engage()`
OpenTrons/opentrons-api pull request #12114
Opened 2023-02-07 17:30 UTC by SyntaxColoring

# Overview

`magnetic_module.engage(height=...)` has long been discouraged in favor of `.engage(height_from_base=...)`.

In our current implementation of PAPIv2.14, using `height=...` raises a `NotImplementedError`. I'm surmising that at this point, we have no intention of supporting `height=...` in PAPIv2.14. So, this PR formally removes it.

This work is while I'm in the neighborhood for RCORE-539.

# Changelog

* Update the docs so they say the `height` parameter was removed in PAPIv2.14, instead of "will be deprecated in a future release."
* If someone tries to use the `height` parameter in PAPIv2.14, make sure it raises `APIVersionError` instead of `NotImplementedError`.

# Test Plan

# Review requests

Have I correctly surmised our intent for the PAPIv2.14 release? Is this the correct thing for us to do?

# Risk assessment

Low.

2023-02-07 19:01 UTC, ecormany reviewed
This all looks fine in principle, but we need to integrate it into the broader 2.14 docs release.

I also checked and there are no remaining instructions on how to use `height` on the Hardware Modules page, so we're good to go there.

2023-02-07 19:01 UTC, ecormany commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +                " apiLevel 2.14. Use `offset` or `height_from_base` instead."
Where will this error be displayed? Are the backticks useful?

2023-02-07 19:01 UTC, ecormany commented on api/docs/v2/versioning.rst
> +- The ``height`` parameter of :py:meth:`.MagneticModuleContext.engage` will be deprecated. Use ``offset`` or ``height_from_base`` instead.
The content here is fine, but we should incorporate the significant changes to this section underway in #12106 and change the language to past tense in preparation for deployment.

2023-02-07 19:02 UTC, mcous commented on api/docs/v2/versioning.rst
> +- The ``height`` parameter of :py:meth:`.MagneticModuleContext.engage` will be deprecated. Use ``offset`` or ``height_from_base`` instead.
Since I've got #12106 open that overhauls `versioning.rst`, should I incorporate this change in that PR instead, and we can avoid a merge conflict?

2023-02-07 19:07 UTC, SyntaxColoring commented on api/docs/v2/versioning.rst
> +- The ``height`` parameter of :py:meth:`.MagneticModuleContext.engage` will be deprecated. Use ``offset`` or ``height_from_base`` instead.
Yes, let's do that. Removing this change from this PR.

2023-02-07 19:08 UTC, SyntaxColoring commented on api/docs/v2/versioning.rst
> +- The ``height`` parameter of :py:meth:`.MagneticModuleContext.engage` will be deprecated. Use ``offset`` or ``height_from_base`` instead.
👍 See https://github.com/Opentrons/opentrons/pull/12114#discussion_r1099080409.

2023-02-07 19:12 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +                " apiLevel 2.14. Use `offset` or `height_from_base` instead."
In practice, the app will probably show this somewhere as a regular plain text error message—i.e., not in a monospace typeface, and without any rich text formatting. The backticks won't make it behave like Markdown or anything.

I wasn't really sure what do do here. I'm happy to remove the backticks if you think this message is readable without them. Or maybe replace them with double-quotes (`"`)?

2023-02-07 20:35 UTC, mcous commented on api/tests/opentrons/protocol_api/core/engine/test_magnetic_module_core.py
> +    with pytest.raises(APIVersionError):
Something I struggled with a little on #12106 was where to put these `APIVersionError` raises. I landed on: if possible, raise them in the top-level contexts rather than the cores.

What would you think about doing the same, here? I don't think we're 100% consistent yet, so it's not a hugely important question

2023-02-07 20:45 UTC, mcous commented on api/src/opentrons/protocol_api/module_contexts.py
> +             .. versionchanged:: 2.14
```suggestion
             .. deprecated:: 2.14
```

2023-02-07 20:45 UTC, mcous commented on api/src/opentrons/protocol_api/module_contexts.py
>          their order of precedence is ``height``, then ``height_from_base``, then ``offset``.
Should we remove `height` from this list?

2023-02-07 20:45 UTC, mcous commented on api/src/opentrons/protocol_api/module_contexts.py
>          if height is not None:
Same comment as elsewhere: for consistency, should we do the version check + raise here?

2023-02-07 20:45 UTC, ecormany commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +                " apiLevel 2.14. Use `offset` or `height_from_base` instead."
this seems legible to me: 
```
The height parameter of MagneticModuleContext.engage() was removed in
API version 2.14. Use offset or height_from_base instead.
```

2023-02-07 20:47 UTC, ecormany commented on api/src/opentrons/protocol_api/module_contexts.py
>          their order of precedence is ``height``, then ``height_from_base``, then ``offset``.
i'd say leave it as an explanation of earlier behavior.

2023-02-07 22:55 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_api/core/engine/test_magnetic_module_core.py
> +    with pytest.raises(APIVersionError):
I'd also prefer to do that, in principle, but I wasn't sure exactly how.

Would the core method just do an `assert` or `NotImplementedError` that we expect to never be hit in production, and the top-level method has an `if apiLevel < ...` guard with the `raise APIVersionError` to make that the case?

2023-02-07 23:02 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/module_contexts.py
> +             .. versionchanged:: 2.14
@ecormany Do you have an opinion here? This is the same sort of "removed" vs. "deprecated" terminology question that we've seen elsewhere. Does it make more sense for the docs to say:

> Deprecated in version 2.14: This parameter has been removed.

Or:

> Changed in version 2.14: This parameter has been removed.

I'm leaning towards "changed in" because it seems less incorrect. This parameter had been discouraged (i.e. deprecated) since before v2.14.

In the future, we could install https://pypi.org/project/sphinx-removed-in/ to give us `.. removed-in::`.

2023-02-07 23:04 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/module_contexts.py
>          their order of precedence is ``height``, then ``height_from_base``, then ``offset``.
Agreed that we should leave it in as an explanation of earlier behavior. Since docs.opentrons.com isn't just for writing new protocols; it's also for understanding (and maybe porting) old protocols. In the future, maybe we could have some kind of version selector in the header like https://docs.python.org.

2023-02-07 23:04 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/module_contexts.py
>          if height is not None:
👀 Discussing in https://github.com/Opentrons/opentrons/pull/12114#discussion_r1099208466.

2023-02-07 23:37 UTC, ecormany commented on api/src/opentrons/protocol_api/module_contexts.py
> +             .. versionchanged:: 2.14
@SyntaxColoring I tend to agree with your reasoning. "Deprecated" is too specific here; we killed it. Putting a message to that effect under a change notice is perfectly good for now and we can discuss (after this PR) if there's a better future solution for this type of situation.

2023-02-08 16:00 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +            raise APIVersionError(
Follow up from the comment bellow. I think we should leave this as a not implemented exception and move this error to the context. I did this for the presses and increment change:
```
        if presses is not None and self._api_version >= _PRESSES_INCREMENT_REMOVED_IN:
            raise APIVersionError(
                f"presses is only available in API versions lower than {_PRESSES_INCREMENT_REMOVED_IN},"
                f" but you are using API {self._api_version}."
            )
```

2023-02-08 16:01 UTC, TamarZanzouri requested changes
overall looks good! just a small comment :-)

2023-02-08 19:27 UTC, mcous commented on api/tests/opentrons/protocol_api/core/engine/test_magnetic_module_core.py
> +    with pytest.raises(APIVersionError):
That wouldn't be the worst

2023-02-09 16:02 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/module_core.py
> +            raise APIVersionError(
Agreed in https://github.com/Opentrons/opentrons/pull/12114#discussion_r1099194904. Made this change.

2023-02-09 17:11 UTC, TamarZanzouri approved these changes
Thank you! LGTM!

2023-02-09 17:35 UTC, merged