feat(app): pipette wizard steps for flows accessed through run setup
OpenTrons/opentrons-api pull request #12127
Opened 2023-02-10 12:20 UTC by jerader

closes RLIQ-315

# Overview

Created 2 utils to used to help determine the steps needed for accessing pipette flows through protocol run setup. Utils are: `getRequiredPipetteForProtocol` and `getPipetteWizardStepsForProtocol`

# Test Plan

- utils are not plugged in anywhere so review the different flows and make sure I included all possible cases that can exist
- also review the props added to make sure they are appropriate - the prop type for `pipetteInfoByMount` is based on the output of `useRunPipetteInfoByMount` which is the hook used throughout the run setup work such as `SetupPipetteCalibration`. I think that is the correct type to use here to easily be able to plug it in rather than using the `AttachedPipetteByMount` prop

# Changelog

- created `getRequiredPipetteForProtocol` and `getPipetteWizardStepsForProtocol` and created tests for each of them as well

# Review requests

- review the 2 utils and make sure they cover all cases and that the props make sense.

# Risk assessment

low

2023-02-10 12:23 UTC, jerader commented on app/src/organisms/PipetteWizardFlows/getPipetteWizardStepsForProtocol.ts
> +  pipetteInfoByMount: { [mount in Mount]: PipetteInfo | null },
Is this the correct type to use here to get the attached pipette info by mount? This type is based off of the output in `useRunPipetteInfoByMount` which is the hook used throughout the run setup work such as in `SetupPipetteCalibration` in order to get the pipette info by mount. I think this will make it much easier to plug this util in. Alternatively, i could be using type `AttachedPipetteByMount` which is the type we use for the other ot-3 pipette flow work. LMK your thoughts though!

2023-02-15 22:01 UTC, smb2268 requested changes

2023-02-15 22:01 UTC, smb2268 commented on app/src/organisms/PipetteWizardFlows/getPipetteWizardStepsForProtocol.ts
> +  //    return no steps if correct pipette is attached or protocol doesn't require pipette on mount
If the correct pipette is attached, let's check if it needs to be calibrated and return the calibration steps if so

2023-02-15 22:01 UTC, smb2268 commented on app/src/organisms/PipetteWizardFlows/getPipetteWizardStepsForProtocol.ts
> +  pipetteInfoByMount: { [mount in Mount]: PipetteInfo | null },
I think we have a few options here:

1. Take both `AttachedPipetteByMount ` and `pipetteInfoByMount ` as props and get rid of the `protocolData` prop. `AttachedPipetteByMount` will correspond to the pipettes that are currently on the gantry. `useRunPipetteInfoByMount` gives us the information about the pipettes we need to attach for a specific protocol run, similar to what you're doing in `getRequiredPipetteForProtocol` but with extra fields, like `requestedPipetteMatch` which tells us whether the pipette attached is suitable to run the protocol.

2. Leave the `protocolData` prop and usage of `getRequiredPipetteForProtocol` but add a little more functionality to this util so it can tell us whether the correct pipette is attached but needs to be calibrated. Change the other prop to be `AttachedPipetteByMount` since that tells us about the pipettes currently on the gantry while `pipetteInfoByMount` is for pipettes used in the protocol.

Let me know if you have questions about that! I think either of these approaches can work well.

2023-02-16 12:34 UTC, jerader commented on app/src/organisms/PipetteWizardFlows/getPipetteWizardStepsForProtocol.ts
> +  //    return no steps if correct pipette is attached or protocol doesn't require pipette on mount
Oh ya, oops i forgot about calibration!

2023-02-16 14:11 UTC, jerader commented on app/src/organisms/PipetteWizardFlows/getPipetteWizardStepsForProtocol.ts
> +  pipetteInfoByMount: { [mount in Mount]: PipetteInfo | null },
Got it, i definitely thought things were backwards thinking `pipetteInfoByMount` was the attached pipette info 🤦 . Working on a refactor now - probably will go with option one!

2023-02-23 20:01 UTC, smb2268 approved these changes
this looks good!! thanks for refactoring

2023-02-24 14:01 UTC, merged