feat(ot3, api): implement a park function for gantry axes
OpenTrons/opentrons-api pull request #12142
Opened 2023-02-13 17:53 UTC by ahiuchingau

# Overview
One of the shortcomings of the OT-2 robot is that homing takes a significant amount of time – axes are programmed in a constant velocity to trigger the limit switches at the axis ends to avoid crashing. 

An improvement made to the next-gen robot is to accompany each axis motor with a rotary encoder. This way we can be better at keeping track of the motors position without the need to home the axes all the time. 

But sometimes, we do want the ability to move the gantry axes out of the way in the home position, e.g. when the thermocycler lid is moving. Since we know the motor encoder position, we can command the motors to move to the home position (where the encoder position is at 0) with acceleration, which is a much faster approach than moving at constant velocity. We are calling this function `park()` in the hardware controller.

#### What `park()` Does:
1. Checks to see if the encoder positions are okay * (i.e. if the axes have been homed since the system first booted up)
2. Updates motor estimation for the gantry axes only: `X, Y, Z_L, Z_R, Z_G` ** (see #11962 for functionality)
3. Moves axes in a specific order using `OT3Axis.home_order()` to their 0 mm positions
4. Refreshes new motor and encoder positions

*: If none of the axes has never been homed, raise `MustHomeError` because all axes must be homed at least once first
**: If an axis has homed but the encoder status is not okay (a collision has occurred), we shouldn't block other axes from parking, so home the problematic axes instead

# Review requests
Does that make sense? Ideally this will replace the `fast_home()` function – do you foresee any potential issues with that? 

Tested on the OT-3.

# Risk assessment
Low – new feature for the OT-3.

2023-02-13 20:07 UTC, sfoster1 commented
I think it's reasonable to home axes that have not yet been homed automatically.

2023-02-13 20:15 UTC, sfoster1 requested changes
Some inline changes though on the whole it looks good to me!

2023-02-13 20:15 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        if not (self._current_position and self._encoder_position):
Shouldn't we be checking the status flags here rather than the existence of the dicts?

2023-02-13 20:15 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +    def _apply_deck_transform(
let's name this like `self._deck_from_machine` or something since `apply_deck_transform` requires you to remember which direction the deck transform goes. we can also have `self._machine_from_deck` if we want.

2023-02-13 20:15 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        await self._cache_current_position()
any reason not to use `self.refresh_positions()`?

2023-02-13 20:15 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> -        self._move_manager.update_constraints(
why not update constraints here?

2023-02-13 20:15 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +                await self._cache_current_position()
why not `self.refresh_positions()`?

2023-02-13 20:15 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +                    await self._cache_current_position()
why not `self.refresh_positions()`?

2023-02-13 20:23 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/ot3api.py
> +        await self._cache_current_position()
No reason other than trying to minimize the changes to functions other than `park()` – I was going to open a new PR to update other functions so they would be all using `self.refresh_positions()`.

2023-02-13 20:26 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/ot3api.py
> -        self._move_manager.update_constraints(
I figured that since we already update the constraints when we cache instruments, this might be redundant? Happy to add it back in, though.

2023-02-13 20:49 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/ot3api.py
> +        if not (self._current_position and self._encoder_position):
YES!

2023-02-13 21:06 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        await self._cache_current_position()
but isn't `_cache_current_position` also doing that? I guess what I'm seeing is there's all these changes to those functions anyway, might as well convert them

2023-02-13 21:06 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> -        self._move_manager.update_constraints(
No, I think you're right

2023-02-13 21:08 UTC, sfoster1 approved these changes
Approved with a nit and subject to testing!

2023-02-13 21:08 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        get_stat: Callable[
nit: i feel like it's a little more reasonable to do
```
def check_ready_for_parking(...):
    def _get_status(ax: OT3Axis) -> Iterator[bool]:
       return (self_motor_status.get(axis_to_node(a)) for a in ax)
```
means you wouldn't have to use `Callable` like that

2023-02-13 22:05 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/ot3api.py
> +        await self._cache_current_position()
`_cache_position` and `_cache_encoder_position` only get those info from the values stored in the backend and don't currently issue a get motor status request to the firmware, I think.

2023-02-14 15:51 UTC, andySigler requested changes

2023-02-14 15:51 UTC, andySigler commented on api/src/opentrons/hardware_control/ot3api.py
> +                    await self._update_position_estimation([axis])
we should not ever do this, unless we EXPECT an axis stalled (like during pick-up-tip)

2023-02-14 15:56 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +                    await self._update_position_estimation([axis])
I think it's reasonable to update the positions from encoder _for axes whose stepper position has failed_ here

2023-02-16 20:47 UTC, sfoster1 approved these changes
This looks nice to me once tested! Couple nits but overal good

2023-02-16 20:47 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        assert axis not in [OT3Axis.G, OT3Axis.Q]
add an error message probably

2023-02-16 20:47 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +                target_pos[axis] += 20.00
should be a configuration value

2023-02-17 22:45 UTC, Laura-Danielle approved these changes
Few questions/suggestions. Looks like a good refactor in general tho :)

2023-02-17 22:45 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        return any(
curious why `any` axis is valid rather than `all` when checking the encoder status?

2023-02-17 22:45 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> -    async def update_position(self) -> OT3AxisMap[float]:
why did we change this from async to sync?

2023-02-17 22:45 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> +    def update_position(self) -> OT3AxisMap[float]:
curious why we decided to make all these funcs synchronous.

2023-02-17 22:45 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/test_moves.py
> +    assert ot3_hardware._current_position[OT3Axis.G] == 20
Accidental change from X -> G? You're checking G pos twice here.

2023-02-17 22:45 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +                    if axis == OT3Axis.G:
Food for thought. It is a bit weird to throw a gripper not attached error at the _end_ of trying to home the axis. If we're worried about this state, should we check before we attempt to home the G axis?

2023-02-21 16:53 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> +    def update_position(self) -> OT3AxisMap[float]:
My thought is that we'd want to wait until `self._position` is done updating (for example, after handling a MoveComplete message) before we return the position value to the API.

2023-02-21 16:58 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        return any(
Because we want `home()` to complete as fast as it is physically possible. This means that we can move the axis/axes with ok encoder status to the limit switch, and just regularly home the rest of the inaccurate axes.

2023-02-22 19:06 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/ot3api.py
> +                    if axis == OT3Axis.G:
What this block is doing is to update the jaw displacement if we have commanded the G to home and ignore if a gripper is not attached.

2023-02-27 15:52 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> +    def update_position(self) -> OT3AxisMap[float]:
that doesn't quite line up to me - anything involving waiting should probably be async, right?

2023-02-28 14:52 UTC, andySigler approved these changes

2023-03-10 18:29 UTC, Laura-Danielle approved these changes
Did a quick sanity check. My last remaining comment is that I think we should keep those funcs that were async previously as asynchronous.

2023-03-10 18:29 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/test_moves.py
> +    assert ot3_hardware._current_position[OT3Axis.G] == 20
You have two lines that are doing the same check here in this test FYI

2023-03-10 18:29 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> +    def update_position(self) -> OT3AxisMap[float]:
bump on the async q here. I agree with Seth that I think it should maybe stay async.

2023-03-10 18:29 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        return any(
logic ✅  out!

2023-03-10 21:28 UTC, fsinapi commented on api/src/opentrons/hardware_control/ot3api.py
> +            await self._update_position_estimation([axis])
If the axis is not enabled when `_home_axis` is called, this line is going to fail. We should explicitly enable the axis here since the intention of the function is always to turn the motor on and home it.

2023-03-13 16:45 UTC, merged