feat(hardware) add a python driver for the rear panel mcu
OpenTrons/opentrons-api pull request #12194
Opened 2023-02-24 16:11 UTC by ryanthecoder

# Overview
Functioning just like the CanMessenger this new driver uses the underling serial port comms to communicate over USB to the rear-panel

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-02-27 16:00 UTC, sfoster1 requested changes
Looks good but let's change that comment.

Also add a test for the async-read interface in `bin_serial`

2023-02-27 16:00 UTC, sfoster1 commented on hardware/opentrons_hardware/drivers/binary_usb/binary_messenger.py
> +"""Can messenger class."""
```suggestion
"""Binary USB messenger class."""
```

2023-02-28 18:17 UTC, sfoster1 approved these changes
Approving because it looks good in structure but let's fix some last little nitpicks before merging

2023-02-28 18:17 UTC, sfoster1 commented on hardware/opentrons_hardware/drivers/binary_usb/bin_serial.py
> +from typing import Optional, Type  # , Any
```suggestion
from typing import Optional, Type
```

2023-02-28 18:17 UTC, sfoster1 commented on hardware/opentrons_hardware/drivers/binary_usb/bin_serial.py
> +                return None
does this happen often? when it does, is it an incomplete read or garbage data?

2023-02-28 18:17 UTC, sfoster1 commented on hardware/opentrons_hardware/drivers/binary_usb/binary_messenger.py
> +            del self._listeners[listener]
let's make this `self._listeners.remove(listener)` or something, don't love `del` in this case

2023-03-01 15:56 UTC, ryanthecoder commented on hardware/opentrons_hardware/drivers/binary_usb/bin_serial.py
> +                return None
I hadn't seen it happen but I figured its a good guard against random noise or something on the line

2023-03-01 16:03 UTC, merged