feat(robot-server): hash protocol + labware contents to avoid duplicate entries
OpenTrons/opentrons-api pull request #12193
Opened 2023-02-24 15:48 UTC by shlokamin

# Overview

WIP

closes RCORE-614

# Test Plan

- Used postman to `POST` to the `/protocols` endpoint multiple times with the same protocol
- Validated that the first `POST` returned a 201 status, and all subsequent returned 200s
- Validated that when hitting `GET` `/protoocls` I only got one entry back

# Changelog

- Hash protocol and labware contents to avoid duplicate entries 

# Review requests

# Risk assessment

Med/high — this touches a core API, and one that the app heavily depends on

2023-02-24 16:03 UTC, shlokamin commented on api/src/opentrons/protocol_reader/protocol_reader.py
> -    async def read_and_save(
i got rid of `read_and_save`, and instead added a `save` function that takes in list of buffered files (rather than a file representing an IO stream).

the reason i did this is because once the `read_and_save` function reads the IO stream, the stream is modified and can't be read again (cleanly). 

the new flow requires us to read files coming from a client and:

1. read the file stream into memory, hash the contents, and verify if protocol already exists on the server
2. if it does not, save the file

because i need to read the file BEFORE saving it to accomplish (1), I had to break up this function. 

to be honest though, i think it was doing too much in the first place.

2023-02-24 16:10 UTC, shlokamin commented on robot-server/robot_server/protocols/router.py
> +    )
i had way too much fun creating this dict of content hashes to protocol ids...

i discovered it is not very "Pythonic" (lmfao) to use map functions on stack overflow. so this is what i came up with. 

roast me.

2023-02-24 16:10 UTC, shlokamin commented on robot-server/robot_server/protocols/router.py
> +    )
i think `protocol_store.get_all()` is pretty quick (looks like its a lru cache), and this shouldn't be more than 25 elements, so i think performance wise we are okay?

2023-02-24 16:10 UTC, shlokamin commented on robot-server/robot_server/protocols/router.py
> +    file_reader_writer: FileReaderWriter = Depends(get_file_reader_writer),
even though `protocol_reader` has a `file_reader_writer`, i decided the router should have access to its own instance of a `FileReaderWriter` because it felt wrong for the router to reach into protocol_reader like this:

`protocol_reader._file_reader_writer.read()`

2023-02-24 18:40 UTC, shlokamin commented on robot-server/robot_server/protocols/router.py
> +            )
this exception should really never happen (since we know the protocol exists on the robot server), but if for some reason it can't be found, we will return a 500 error (since it is an internal server error at that point)

2023-02-27 18:18 UTC, sfoster1 requested changes
I regret to announce I have unicode-based nitpicks

2023-02-27 18:18 UTC, sfoster1 commented on api/src/opentrons/protocol_reader/file_hasher.py
> +        sorted_files = sorted(files, key=lambda x: x.name)
This might cause problems with unicode filenames and python/js interpretation:

- `sorted` will compare individual elements of strings by [numerically comparing the unicode codepoint of the element](https://docs.python.org/3/reference/expressions.html#id12) 
- js `Array.sort` [sorts by numerically comparing UTF-16-encoded data](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort)

The two will therefore handle unicode characters that are not representable in ascii differently. We can therefore either:
- On the python side, use the key `lambda x: x.encode('UTF-16')` which should have the same behavior as the js default
- On the python side; use `key=lambda x: unicodedata.normalize(x.name)` and on the js side use a comparator function that does something like: `Array.from(name.normalize().foreach(char => char.codePointAt(0)))` so you're sorting an array of arrays of codepoints

What we definitely shouldn't do is use anything that varies with the locale, since the robot's locale that python picks up will almost certainly not be the locale of the js environment on the user's computer.

2023-02-27 18:18 UTC, sfoster1 commented on robot-server/robot_server/protocols/router.py
> +    )
you can also use a dict comprehension for this: `= {p_resource.source.content_hash: p_resource.protocol_id for p_resource in protocol_store.get_all()}`

2023-02-27 18:18 UTC, sfoster1 commented on robot-server/robot_server/protocols/router.py
> +    content_hash2protocol_id: Dict[str, str] = dict(
[nit]: something about the naming of this is breaking my brain

2023-02-27 18:35 UTC, shlokamin commented on robot-server/robot_server/protocols/router.py
> +    content_hash2protocol_id: Dict[str, str] = dict(
yeah its kinda weird, i used this as a reference for naming: https://bagrow.com/blog/2020/10/02/naming-things-python-dictionary-ed./

2023-02-27 18:36 UTC, shlokamin commented on api/src/opentrons/protocol_reader/file_hasher.py
> +        sorted_files = sorted(files, key=lambda x: x.name)
im not sure i follow, sorting will always be done on the python side:
- when the system boots (storing protocol files in memory)
- when `POST`ing protocols 

why does JS array sort come into play?

2023-02-27 18:50 UTC, sfoster1 commented on api/src/opentrons/protocol_reader/file_hasher.py
> +        sorted_files = sorted(files, key=lambda x: x.name)
Oh yeah you're totally right I had it in my head that the client was going to be comparing hashes for things.

Imo I still think it's a good idea to have the key be `lambda x: unicodedata.normalize(x.name)` just because more normal more better, but nowhere near as big an issue as I thought.

2023-02-27 18:50 UTC, shlokamin commented on robot-server/robot_server/protocols/router.py
> +    )
oh dope thanks or this

2023-02-28 21:19 UTC, SyntaxColoring requested changes
Thank you! This is looking great so far. 🥔 #️⃣

2023-02-28 21:19 UTC, SyntaxColoring commented on api/src/opentrons/protocol_reader/file_hasher.py
> +    def hash(files: List[BufferedFile]) -> str:
I haven't tested this, but I suspect hashing a bunch of files is going to be computationally expensive enough that we should offload it to a thread, to avoid blocking the event loop.

I would do it like this:

1. Move this implementation to a private function. Call it `_hash_sync()` or something.
2. Make a new async public function `async def hash(files: List[BufferedFile]) -> str`.
3. In the new async public function, do `return await anyio.to_thread.run_sync(self._hash_sync, files)`. (You'll need to `import anyio`.)

See `file_format_validator.py` for an example.

Making it the responsibility of `FileHasher` to do this offloading is a somewhat arbitrary interface choice. We could instead expect the *caller* to do `anyio.to_thread.run_sync()`. But the existing convention within the `protocol_reader` module is that it's responsible for the offloading, so I figure we should continue that.

2023-02-28 21:19 UTC, SyntaxColoring commented on api/src/opentrons/protocol_reader/file_hasher.py
> +            md5_hasher.update(file.contents)
I think this implementation will unintentionally return the same hash for file sets that are meaningfully different.

We need to address at least two things:

## File contents can migrate across the concatenation

The current implementation will return the same hash for this file set:

file_1.txt contents:
```
a
b
```
file_2.txt contents:
```
c
```

...as for this file set:

file_1.txt contents:
```
a
```
file_2.txt contents:
```
b
c
```

This is unlikely to matter for protocol files or labware definitions. But imagine a protocol that's uploaded with two `.csv` files that list wells names, for example.

## File names are ignored

The current implementation will return the same hash for this file;

hello_world.txt
```text
hello, world
```

...as for this file:

hello_world.csv
```csv
hello, world
```

-----

I think something like this would work:

```python
file_digests = [
    # normalize_file_name() is something else we'd have to write 
    md5(normalize_file_name(file.name)).digest() + md5(file.contents).digest()
    for file in buffered_files
]

overall = b"".join(sorted(file_digests))

# This final md5() is just to get output in a convenient size.
# Returning `overall` raw would otherwise be practically equivalent.
return md5(overall).hexdigest()
```

2023-02-28 21:19 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/dependencies.py
> +
Because of FastAPI 𝓶𝓪𝓰𝓲𝓬, we don't actually need to define these functions.

Instead of doing this:

```python
file_hasher = Depends(get_file_hasher)
```

...the endpoint function can do this:

```python
file_hasher = Depends(FileHasher)
```

2023-02-28 21:19 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +    content_hash2protocol_id: Dict[str, str] = dict(
`key2value` is interesting. I don't think I've ever seen that before in the wild. I usually do `values_by_key`. So this would be `protocol_ids_by_content_hash`.

2023-02-28 21:19 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +            )
Hmm. I haven't looked into this deeply, but I would have expected this to cause an HTTP 500 error even if you hadn't added this explicit `except`/re-`raise`.

2023-02-28 21:19 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +        source = await protocol_reader.save(
As written, when a protocol gets uploaded, I think we're redundantly hashing the files twice:

1. Once up above in this endpoint function.
2. A second time inside this `protocol_reader.save()` call.

It seems like we should do something like make `protocol_reader.save()` *not* do any content hashing internally. Instead, pass `content_hash` in as a parameter here?

2023-02-28 21:19 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +    )
> i think `protocol_store.get_all()` is pretty quick (looks like its a lru cache), and this shouldn't be more than 25 elements, so i think performance wise we are okay?

Instead of basing this implementation on `protocol_store.get_all()`, can we add a new method to `ProtocolStore` like `.get_id_by_hash() -> Optional[str]`?

Operations like `.get_all()` *are* significantly quicker as of v6.2.1 (#11891). Nevertheless, I think it's too big of a hammer to use here.

* `.get_all()` returns stuff for *every* stored protocol. Whenever we get around to implementing pagination on `GET /protocols`, using `.get_all()` here would negate many of the benefits of that pagination. This could be easy to miss later on.
* Because of what it includes in its output, `.get_all()` requires that the robot has, at some point, done JSON parsing of *every* .json file across *all* protocols. That includes labware definition files as well as JSON protocol files.

For the scope of this PR, I think we can keep the implementation of `.get_id_by_hash()` the same as what you have here, just a simple search through `.get_all()`. But it would provide a convenient place in the future to swap out the implementation for something more lightweight.

it's still more intensive than I'm comfortable with, unfortunately. Most worryingly to me, the data present in its output implies that *every .json file across all protocols* has to have been parsed.

2023-03-01 15:47 UTC, shlokamin commented on api/src/opentrons/protocol_reader/file_hasher.py
> +    def hash(files: List[BufferedFile]) -> str:
good call i like this, thanks max!

2023-03-01 15:52 UTC, shlokamin commented on api/src/opentrons/protocol_reader/file_hasher.py
> +            md5_hasher.update(file.contents)
the file name part if this makes sense, you actually called it out earlier i just forgot to do this 🙃 thanks for the call out!

i don't follow this part though:

> This is unlikely to matter for protocol files or labware definitions. But imagine a protocol that's uploaded with two .csv files that list wells names, for example.

the file hasher just takes in a list of buffered files, sorts them, and hashes them. i don't follow why a main protocol file with two csv files would cause issues

2023-03-01 15:52 UTC, shlokamin commented on robot-server/robot_server/protocols/dependencies.py
> +
love me some magic

2023-03-01 15:55 UTC, shlokamin commented on robot-server/robot_server/protocols/router.py
> +        source = await protocol_reader.save(
hmm... that is a fair critique. this means he hoist the responsibility of hashing to all future callers.

i think that is fair, and it logically separates the code better. nice! i shall do this

2023-03-01 16:08 UTC, shlokamin commented on robot-server/robot_server/protocols/router.py
> +    )
> Most worryingly to me, the data present in its output implies that every .json file across all protocols has to have been parsed.

i think i follow this, but want to clarify some stuff. lets sync irl when you get in!

> Instead of basing this implementation on protocol_store.get_all(), can we add a new method to ProtocolStore like .get_id_by_hash() -> Optional[str]

i think it would have to be `.get_id_by_hash() -> dict[str, str]` right?

2023-03-06 22:45 UTC, sfoster1 approved these changes
I like it, it looks like it'll work great!

I'm a little worried about the sheer extent of the `create_protocol` route handler but given how many different values that block needs I guess it's tough to reasonably refactor.

One nit is some of the utility classes like `ProtocolHasher` could probably have their arguments be [Sequence](https://docs.python.org/3.8/library/typing.html#typing.Sequence) rather than `List`, or even [Iterable](https://docs.python.org/3.8/library/typing.html#typing.Iterable), just to define the outer boundary of what the function accepts.

2023-03-06 22:45 UTC, sfoster1 commented on api/src/opentrons/protocol_reader/protocol_reader.py
> +        self, files: List[BufferedFile], directory: Path, content_hash: str
this probably wants to be a `Sequence` just for niceness

2023-03-06 22:45 UTC, sfoster1 commented on api/src/opentrons/protocol_reader/file_hasher.py
> +    async def hash(files: List[BufferedFile]) -> str:
these probably want to take a `Sequence[BufferedFile]` rather than a `List`

2023-03-07 16:31 UTC, SyntaxColoring requested changes
This is coming along, thanks!

The big things for me at this point are the hashing algorithm, and the `Delete the prototcol` test additions.

2023-03-07 16:31 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/protocol_store.py
> +            return None
This is just a matter of style, but I'd personally just write this procedurally, to avoid having to do the quirky `except StopIteration` thing.

```suggestion
        for protocol in self.get_all():
            if p.source.content_hash == hash:
                return p.protocol_id
        return None
```

-----

A separate point, if you want to keep the `next`/`StopIteration`-based implementation:

The naming here might be a little confusing. `p_source` is a `ProtocolResource`, not a `ProtocolSource` as you might expect from its name. (Our names `ProtocolResource` and `ProtocolSource` are themselves not very good. Sorry.)

2023-03-07 16:31 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/protocols/test_v6_json_upload.tavern.yaml
> +      status_code: 200
What are these test additions for?

Is it something like: state was leaking across tests, so you had to add these new steps so each test would clean up after itself?

If that's the case, this worries me a bit because there's no guarantee the test won't fail at an earlier step and skip this cleanup, which would then cause confusing and distracting failures in other tests.

It seems like we'd either have to:

* Do cleanup more robustly, via some kind of [Tavern hook](https://tavern.readthedocs.io/en/stable/basics.html).
* Write the tests to be less sensitive to their world being polluted by the tests that came before them. For example, ensure they all use unique protocol file names.

2023-03-07 16:31 UTC, SyntaxColoring commented on api/src/opentrons/protocol_reader/file_hasher.py
> +            md5_hasher.update(file.contents)
Continuing this thread and our in-person discussions, the implementation in the PR is now:

```python
def _hash_sync(files: List[BufferedFile]) -> str:
    md5_hasher = md5()
    sorted_files = sorted(files, key=lambda x: unicodedata.normalize("NFC", x.name))
    for file in sorted_files:
        md5_hasher.update(file.name.encode("utf-8") + file.contents)
    return md5_hasher.hexdigest()
```

This solves the problem of ignoring file names, thanks.

However, we still have problems with different file sets hashing to the same thing, because of the way we're concatenating their parts.

For example, these file sets will hash to the same thing:

* File set 1:
  * **file_foo.txt**
    ```
    bar
    ```
* File set 2:
  * **file_f**
    ```
    oo.txtbar
    ```

And so will these:

* File set 1:
  * **file_foo.txt**
    ```
    foo
    ```
  * **file_bar.txt**
    ```
    bar
    ```
* File set 2:
  * **file_foo.txt**
    ```
    foo
    file_bar.txtbar
    ```

A general rule to avoid this kind of thing is that the input to a hash function should never be a concatenation of logically separate things—but it *can* be a concatenation of *hashes* of logically separate things.

The snippet in [my last comment](https://github.com/Opentrons/opentrons/pull/12193/files/a39a490e5f4be34893cff86d8ee18fec09fbe6ee#r1120632019) tries to account for this. What do you think of that implementation?

2023-03-07 16:31 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +            )
Yeah, I just tested this. If something raises `ProtocolNotFoundError` unexpectedly, it will correctly propagate to the HTTP client as a 500 error with the appropriate details, without you needing to re-raise anything explicitly. Let's get rid of this `try`/`except` block.

2023-03-07 17:11 UTC, shlokamin commented on robot-server/tests/integration/http_api/protocols/test_v6_json_upload.tavern.yaml
> +      status_code: 200
yeah they are for test cleanup because state is leaking across tests. i saw mike established a pattern of deleting records after creating them so i followed that,

in my experience writing integration tests that touch a server, its really impotant to do clean up for this reason. and it's also been a cultural buy in that devs just do, which i think we should also do here.

im happy to swap out test fixtures to avoid the issue now, but my point above still stands. the same issue would arise eventually if folks in the future write tests using duplicate artifacts and forget to clean up.

so i guess the point im trying to make is that we should be explicitly cleaning up our integration tests, and we should hold each other accountable to do so in order to avoid unexpected test failures do to leaky state.

@y3rsh curious what you think

2023-03-07 17:23 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/protocols/test_v6_json_upload.tavern.yaml
> +      status_code: 200
> yeah they are for test cleanup because state is leaking across tests. i saw mike established a pattern of deleting records after creating them so i followed that,

Oh interesting. Do you remember where where that was?

2023-03-07 17:39 UTC, shlokamin commented on api/src/opentrons/protocol_reader/file_hasher.py
> +            md5_hasher.update(file.contents)
im not sure these things would evaluate to the same thing because ordering here matters. i.e. 
```py
md5_hasher = md5()
md5_hasher.update('file_foo.txt'.encode("utf-8") + 'bar'.encode("utf-8"))
md5_hasher.hexdigest() # evaluates to  '3ac248af4954c915dff09df6e618fc9a'

md5_hasher2 = md5()
md5_hasher2.update('bar'.encode("utf-8") + 'file_foo.txt'.encode("utf-8"))
md5_hasher2.hexdigest() #evaluates to ''2166d42bca603a6e3d6aa46d538fa275''
```

your point is still valid though, because these evaluate to the same things:

```py
md5_hasher = md5()
md5_hasher.update('file_foo.json'.encode("utf-8") + 'bar'.encode("utf-8"))
md5_hasher.hexdigest() # evaluates to  '0aeb794d80b0a98ca3f119bc69c23cb5'

md5_hasher2 = md5()
md5_hasher2.update('file_foo'.encode("utf-8") + '.jsonbar'.encode("utf-8"))
md5_hasher2.hexdigest() #evaluates to '0aeb794d80b0a98ca3f119bc69c23cb5''
```

2023-03-07 19:48 UTC, shlokamin commented on robot-server/tests/integration/http_api/protocols/test_v6_json_upload.tavern.yaml
> +      status_code: 200
`tests/integration/http_api/protocols/test_upload.tavern.yaml`

@y3rsh may have actually established and mike may have followed

2023-03-08 16:15 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/protocols/test_v6_json_upload.tavern.yaml
> +      status_code: 200
I see. I don't read that deletion as incidental cleanup. I read it as testing that the `DELETE /protocols/{id}` endpoint works.

2023-03-08 16:40 UTC, shlokamin commented on robot-server/tests/integration/http_api/protocols/test_v6_json_upload.tavern.yaml
> +      status_code: 200
line 107 looks like clean up. 

regardless, does the point im trying to make make sense? if we don't clean up then other folks who write tests in the future will have to always make new test fixtures. it's a common practice to clean up server state in integration tests for this reason.

2023-03-08 17:42 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/protocols/test_v6_json_upload.tavern.yaml
> +      status_code: 200
@shlokamin Discussed in-person. The options we considered were:

1. Make sure, somehow, that no two tests upload identical sets of files.
2. Have each Tavern test explicitly clean up after itself with `DELETE /protocols/{id}`.
3. Implicitly clean up after each Tavern test with a Tavern hook.
4. Broaden the test assertions to permit `201` *or* `200` return codes.
5. Add server-side logic to make this auto-reuse behavior opt-in. For example, introduce a `?reuseExistingUploadIfFilesAreIdentical=<bool>` query parameter that defaults to `false`.

@shlokamin and I are favoring option (3). We can use our existing `RobotClient` test helper.

2023-03-15 18:11 UTC, jbleon95 commented on robot-server/tests/integration/http_api/protocols/test_v6_json_upload.tavern.yaml
> +                displayColor: '#7332a8'
newline missing at EOF

2023-03-15 18:12 UTC, jbleon95 commented on api/src/opentrons/protocol_reader/file_hasher.py
> +def _hash_sync(files: Sequence[BufferedFile]) -> str:
Can we have a docstring for this function as well?

2023-03-15 18:14 UTC, jbleon95 approved these changes
The changes LGTM, besides my minor comments.

2023-03-16 14:15 UTC, shlokamin commented on api/src/opentrons/protocol_reader/file_hasher.py
> +def _hash_sync(files: Sequence[BufferedFile]) -> str:
I followed the pattern @SyntaxColoring pointed out in [this comment](https://github.com/Opentrons/opentrons/pull/12193#discussion_r1120565136) that references `file_format_validator` — it doesnt look like we normally have doc strings for async private methods that are not meant to be exposed as a public api. instead we document the public method that delegates to an async method. 

Ex the `validate` method in `file_format_validator` just delegates to private async methods that actually do the work, but we put the docstring in the public method anyways

2023-03-16 16:34 UTC, SyntaxColoring approved these changes
Looks great. Thanks for pushing this through!

Here's a few fixups that I think should be uncontroversial and should be able to be applied in-place. Looks good to merge otherwise (assuming CI passes).

2023-03-16 16:34 UTC, SyntaxColoring commented on robot-server/tests/conftest.py
> +def clean_server_state() -> Iterator[None]:
```suggestion
def clean_server_state(run_server: object) -> Iterator[None]:
```

Depending on the `run_server` fixture ensures that Pytest will wait to tear down `run_server` until after this fixture runs its teardown. Without this, I think there's theoretically a hazard of this fixture running too late and running into "connection refused" errors, depending the order in which Pytest chooses to run fixtures, which I think is undefined when there are no explicit dependency relationships.

2023-03-16 16:34 UTC, SyntaxColoring commented on api/src/opentrons/protocol_reader/file_hasher.py
> +    return name_content_hasher.hexdigest()
This looks good. Here are a couple of suggested changes:

* Normalize the file name both when we're sorting, *and* when we're hashing. If we expect normalization to be necessary, then it only makes sense to do it for both, not just one or the other, right?
* Leave a comment explaining why we're doing this normalization.

```suggestion
def _hash_sync(files: Sequence[BufferedFile]) -> str:
    def normalized_name(file: BufferedFile) -> str:
        # Normalize the file's name in case there would be differences in its
        # form between the robot's filesystem and the HTTP upload.
        # This is precautionary; we're not actually aware of any differences.
        return unicodedata.normalize("NFC", file.name)

    sorted_files = sorted(files, key=normalized_name)
    name_content_hasher = md5()
    for file in sorted_files:
        name_hash = md5(normalized_name(file).encode("utf-8")).digest()
        contents_hash = md5(file.contents).digest()
        name_content_hasher.update(name_hash + contents_hash)
    return name_content_hasher.hexdigest()
```

2023-03-16 16:34 UTC, SyntaxColoring commented on api/src/opentrons/protocol_reader/protocol_reader.py
> +                in this list once they've been passed to the ProtocolReader.
```suggestion
            files: List of buffered files
```

Since you've changed the interface to accept `BufferedFile`s instead of `AbstractInputFile`s, we don't need this quirky warning about file reuse anymore. This had to do with file `.seek()`ing, but we don't need to worry about that with `BufferedFile`s.

2023-03-16 16:34 UTC, SyntaxColoring commented on robot-server/tests/integration/fixtures.py
> +
Is this left over from development? I don't see it used anywhere?

```suggestion
```

2023-03-17 17:13 UTC, shlokamin commented
great! im gonna merge this and address the last comments in a follow up

2023-03-17 17:14 UTC, merged