feat(system-server): add GET /system/connected
OpenTrons/opentrons-api pull request #12207
Opened 2023-02-28 16:30 UTC by fsinapi

# Overview

This PR adds in a route `GET /system/connected` that will return information about all of the currently connected clients. In order to implement this, an `AuthorizationTracker` class keeps track of the clients that obtain a token through the `POST /system/authorize` route.

Closes RCORE-520 and RCORE-515

Requires #12198, will change the base branch to `edge` once that is merged

# Test Plan

Tested on a Dev server & through integration testing:

- Register a client, then ping /system/connected and ensure _nothing_ pops up (registration does not count as connecting)
- Authorize that client, ping /system/connected, ensure that the correct Registrant info shows up
- Authorize the client again, ping /system/connected, ensure the same info comes back (no duplication)
- Register & authorize a second client, ping /system/connected, ensure _both_ sets of Registration info come back correctly

# Changelog

- Added `AuthorizationTracker` class that maintains a list of authorizations & their expiration datetimes
- Added `expiration_from_jwt` function to extract the expiration time from a JWT
- Added functionality in `POST /system/authorize` to add authorizations to a singleton tracker
- Added `GET /system/connected` route that extracts authorizations from the singleton tracker
- Modified the dev server fixture to run a new instance for each test - this increases test time a bit, but establishes a clean server state after each test.

# Review requests

# Risk assessment

Low

2023-02-28 17:37 UTC, sfoster1 requested changes
Structure looks great, couple nits around altering collections while iterating through them

2023-02-28 17:37 UTC, sfoster1 commented on system-server/system_server/connection/authorization_tracker.py
> +                self._connections.remove(c)
this alters `self._connections` while iterating through it which is not a good idea. Maybe put the found value in your pocket and remove it after the end of the iteration, or do a filtered list copy

2023-02-28 17:37 UTC, sfoster1 commented on system-server/system_server/connection/authorization_tracker.py
> +                self._connections.remove(c)
same deal - this alters `_connections` while iterating through it, may be better as `self._connections = [c for c in self._connections if c.expiration > now]`

2023-02-28 17:37 UTC, sfoster1 commented on system-server/system_server/jwt/system_jwt.py
> +    print(f"Timestamp: {exp}")
should be a `log` or removed

2023-02-28 17:37 UTC, sfoster1 commented on system-server/system_server/jwt/system_jwt.py
> +    return datetime.fromtimestamp(float(exp))
`float` doesn't seem right here, shouldn't this be an int?

2023-02-28 17:37 UTC, sfoster1 commented on system-server/system_server/persistence/__init__.py
> +_authorization_tracker_lock = Lock()
at some point we should refactor so these locks are held in application state

2023-02-28 22:53 UTC, SyntaxColoring commented on system-server/system_server/persistence/__init__.py
> +_authorization_tracker_lock = Lock()
Yep, this has been bothering me in `robot-server` too. It's a good candidate for some kind of reusable util.

2023-03-03 14:48 UTC, sfoster1 approved these changes
Looks good to me!

2023-03-21 13:58 UTC, merged