feat(api): add internal xy belt calibration method
OpenTrons/opentrons-api pull request #12204
Opened 2023-02-28 02:09 UTC by pmoegenburg

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-02-28 14:54 UTC, sfoster1 requested changes
Think we've got a couple math issues here, put it inline. 

We should also maybe make `calibrate_belts` use `opentrons.util.linal.solve_attitude`, but this implementation once fixed will also work. However, if we want to keep this implementation, we should refactor lines 882-889 into their own function that takes a list of actual points and a list of nominal points and returns the attitude and test it... which is basically `linal.solve_attitude`

2023-02-28 14:54 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +        ((point_b.x - point_a.x) / nominal_y),
This doesn't look correct, right? It doesn't make sense to divide an x distance by a y distance, or a y distance by an x distance.

2023-02-28 14:54 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    ), (((point_c.y - point_a.y) / nominal_x), ((point_b.y - point_a.y) / nominal_y))
same here

2023-03-14 15:42 UTC, sfoster1 approved these changes
Okay, this looks good to me once tested!

2023-03-15 16:11 UTC, Laura-Danielle requested changes
In general, I think the math looks good. However, if you want to utilize the capacitive probe to perform these functions, you'll actually need to add the probe length before doing that.

Take a look at `calibrate_pipette` for reference. Also @sfoster1 , I am assume we'll want to make sure we're not baking in any offsets from instrument calibration?

If this is the case, we should also make sure to reset the instrument offset (which again can be found in the `calibrate_pipette` function.

2023-03-15 16:11 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    z_height = await find_deck_height(hcapi, mount, nominal_center)
Are we using a pipette to find the deck height? As this stands now, the probe length is not taken into account in this function.

2023-03-15 16:29 UTC, Laura-Danielle commented
If this test should only be performed using the pipette mounts, we should also throw an error if a gripper mount is passed in.

2023-03-15 18:12 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    await hcapi.move_to(mount, here._replace(z=BELT_CAL_TRANSIT_HEIGHT))
try `move_rel` for this?

2023-03-16 18:00 UTC, sfoster1 requested changes
Looking good, couple more things though.

2023-03-16 18:00 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    try:
rather than have a whole bunch of stuff inside a try block, let's put all that stuff in a function and just call the function in a try block

2023-03-16 18:00 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +        await hcapi.reset_instrument_offset(mount)
I have three problems with this:

First, if we want to reset instrument offset to default, we need to pass `to_default=True` here; otherwise, this will just reload the current saved instrument offset.
Second, if we want to reset the instrument offset to default before calibration, we need to reload it from disk afterwards with an `await hcapi.reset_instrument_offset(mount)` in the finally-block.
Finally, we don't actually need to do reset the instrument offset here because we're calculating a linear transform, so any offset applied equally to all points will fall out.

I think on balance we should just remove this call, but if we want to keep it we need to fix the `to_default` and not resetting it afterwards thing.

2023-03-16 18:03 UTC, ahiuchingau requested changes

2023-03-16 18:03 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +        await hcapi.move_rel(mount, Point[0, 0, BELT_CAL_TRANSIT_HEIGHT])
```suggestion
        await hcapi.move_rel(mount, Point(0, 0, BELT_CAL_TRANSIT_HEIGHT))
```

2023-03-16 18:03 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +        await hcapi.reset_instrument_offset(mount)
if you reset instrument offset here, you might want to reload instrument offsets again after this call is over?

2023-03-17 13:43 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    z_height = await find_deck_height(hcapi, mount, nominal_center)
That should be handled by the machine->deck transformation right? Or is this an old comment

2023-03-17 13:43 UTC, sfoster1 approved these changes
Okay, this looks good to me!

2023-03-17 13:55 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    z_height = await find_deck_height(hcapi, mount, nominal_center)
This is specifically regarding probing the deck w/ a capacitive probe.

2023-03-17 13:56 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    z_height = await find_deck_height(hcapi, mount, nominal_center)
And yes it's taken care of now in `calibrate_belts`

2023-03-17 13:57 UTC, Laura-Danielle approved these changes
Looks good. Agree w / Seth re: instrument cal stuff not being necessary :)

2023-03-20 20:18 UTC, ahiuchingau approved these changes

2023-03-20 20:18 UTC, merged