add BaselineSensorResponse as polling return val
OpenTrons/opentrons-api pull request #12216
Opened 2023-03-01 16:39 UTC by caila-marashaj

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-03-02 17:44 UTC, sfoster1 requested changes
See the inline comment - I think it makes sense to have a baseline response like this, but it does _not_ make sense to replace `run_poll` with it. Sometimes we'd like to run a poll, and we should really continue to support that.

2023-03-02 17:44 UTC, sfoster1 commented on hardware/opentrons_hardware/sensors/scheduler.py
> +            self._create_filter(sensor_info.node_id, BaselineSensorResponse.message_id),
Wait a second - this really seems like a step back here. The point of `run_poll` is actually exactly to stream data back to the host, mostly for development tasks. That's why the data goes into a big list that gets returned at the end. If we replace that by having a single list element that's the average of all the data, we lose that functionality.

Having a `BaselineSensorResponse` that is used _when baselining the sensor_, e.g. as one of the steps before a normal calibration step or liquid sense step, makes sense, but we should make a new method for that here so we can keep `run_poll` around, which is really useful still.

2023-03-02 17:52 UTC, Laura-Danielle commented on hardware/opentrons_hardware/sensors/scheduler.py
> +            self._create_filter(sensor_info.node_id, BaselineSensorResponse.message_id),
`run_poll` was never used to stream data. The baseline sensor request takes in a set number of read requests and is the perfect candidate imo to do auto-zeroing.

We rely on `bind_sync` to stream data which I'm fine with. Happy to modify the name of this function and call it something more like `auto_zero` or `base_read` etc.

2023-03-02 20:11 UTC, caila-marashaj commented on hardware/opentrons_hardware/sensors/scheduler.py
> +            self._create_filter(sensor_info.node_id, BaselineSensorResponse.message_id),
I think some name changes are in order anyway.

`get_baseline` takes in a `poll_for_ms` parameter, which is passed into the `BaselineSensorRequest` as `sample_rate`, when I think in the case of both sensors it's just used to determine how many total readings are going to be taken from the sensor.


I do think a new method is in order either way though if we want to keep limited polling available from the Python side. It's just a matter of either leaving this function intact and creating something new for auto-zeroing, or making this the function for auto-zeroing and writing new code for limited polling for dev purposes.

2023-03-07 15:03 UTC, sfoster1 commented on hardware/opentrons_hardware/sensors/scheduler.py
> +            self._create_filter(sensor_info.node_id, BaselineSensorResponse.message_id),
Okay understood and agree with @Laura-Danielle here, i think i'm good with that change

2023-03-07 15:06 UTC, sfoster1 approved these changes
Okay, this looks good to me once tested!

2023-03-16 21:21 UTC, Laura-Danielle approved these changes
This looks great too :D

2023-03-16 21:47 UTC, merged