feat(hardware): add a update routine and script for rear-panel
OpenTrons/opentrons-api pull request #12214
Opened 2023-03-01 16:27 UTC by ryanthecoder

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-03-01 18:10 UTC, sfoster1 requested changes
I think we need to integrate this a little more tightly into the already-existing update machinery. While we don't have to go all the way to making it perfect in this PR, adding infrastructure like this means it'll be deleted in the next PR, so let's add it as new internal functions to existing classes.

2023-03-01 18:10 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_update/run.py
> +                serial = line[(line.find("serial=") + 7) :]
can we do all the filtering by serial? do we know how the serial is established?

2023-03-01 18:10 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_update/run.py
> +    a port. The firmware upload utility, dfu-util, looks for the specific module
remove the "module" references

2023-03-01 18:10 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_update/run.py
> +        await asyncio.sleep(1)
We should not do this - we should wait for the message to come back. We can use an asyncio.event or asyncio.queue for this.

2023-03-01 18:10 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_update/run.py
> +    async def run_update(self) -> bool:
This process should look a lot more like the process for canbus connected devices, since it will run in similar ways. I would argue, in fact, that because this process will happen at the same time as all the other updates it should be just another method of the existing updater class, that takes a status queue and emits progress updates just as a canbus updater does.

2023-03-01 18:10 UTC, sfoster1 commented on hardware/opentrons_hardware/scripts/update_rpfw.py
> +"""Firmware update script for the rear panel."""
Similarly, let's make this handled by the already-existing update script.

2023-03-03 16:01 UTC, sfoster1 approved these changes
Generally looking good if tested and works!

2023-03-03 16:01 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_update/run.py
> +        logger.info(f"received version info from device {message}")
if this doesn't do anything, is there a reason to have it?

2023-03-06 16:24 UTC, ryanthecoder commented on hardware/opentrons_hardware/firmware_update/run.py
> +        logger.info(f"received version info from device {message}")
I can take it out, this was how I was making sure that the flashing was successful and the reporting a new version

2023-03-07 22:14 UTC, ryanthecoder commented
Fully tested now with both the update_fw and update_fws scripts

2023-03-07 22:18 UTC, merged