fix(api): Raise an error when trying to aspirate more than max volume
OpenTrons/opentrons-api pull request #12221
Opened 2023-03-03 18:54 UTC by TamarZanzouri

# Overview

closes https://opentrons.atlassian.net/browse/RCORE-667.

# Test Plan

upload a protocol that is trying to aspirate more than the working volume. 
analysis should fail with the error:` Cannot aspirate more than pipette max volume`

```
from opentrons.types import Mount, Location, Point
from opentrons.protocol_api import ProtocolContext

metadata = {
    "protocolName": "aspirate after blow-out",
    "apiLevel": "2.14",
}

PIPETTE = "p20_single_gen2"
PIPETTE_MOUNT = Mount.RIGHT
TIP_RACK = "opentrons_96_tiprack_20ul"
TIP_RACK_SLOT = "5"

def run(protocol: ProtocolContext) -> None:
    tip_rack = protocol.load_labware(TIP_RACK, TIP_RACK_SLOT)
    well_plate = protocol.load_labware("biorad_96_wellplate_200ul_pcr", "2")
    pipette = protocol.load_instrument(PIPETTE, PIPETTE_MOUNT, [tip_rack])
    location = Location(point=Point(9, 9, 9), labware=None)
    pipette.pick_up_tip()
    pipette.move_to(location)
    pipette.aspirate(25)
```

# Changelog

- Added a method to the pipetting abstract interface that validates working volume and aspirated volume.
- Implemented for virtual only.

# Review requests

1. is the assertion error enough or do we want it to raise a PE error? 
2. location for calling this method good?

# Risk assessment

low. raising an error for analysis only. worked for 2.13, supporting 2.14 for the next release.

2023-03-03 18:56 UTC, TamarZanzouri commented
Tested on dev server. works as expected.

2023-03-03 22:20 UTC, SyntaxColoring requested changes

2023-03-03 22:20 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +        assert volume <= working_volume, "Cannot aspirate more than pipette max volume"
Yeah, let's make this a full Protocol Engine error instead of an `assert`. I don't think it was correct for the old Python Protocol API to use `assert` for this.

2023-03-03 22:20 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +        self._validate_aspirated_volume(pipette_id=pipette_id, volume=volume)
I'm not sure this is correct?

`self._state_view.pipettes.get_working_volume()` looks to me like the total maximum volume that can be in the tip. But in `aspirate_in_place()`, `volume` is the *additional* volume that you want to aspirate, right?

So if you have a sequence like this:

```
aspirate 100 µL in place
aspirate 100 µL in place
aspirate 100 µL in place
aspirate 100 µL in place
```

It won't be an error for a 300 µL pipette even though you're aspirating 400 µL.

2023-03-03 22:21 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +        assert volume <= working_volume, "Cannot aspirate more than pipette max volume"
Maybe `PipettingVolumeInvalidError`, so we can reuse it for dispense?

2023-03-06 22:56 UTC, SyntaxColoring reviewed
Thanks for fixing the volume logic. This looks good to me to merge once linting and tests pass.

2023-03-06 22:56 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +        current_volume = self._state_view.pipettes.get_aspirated_volume(pipette_id=pipette_id) or 0
For my edification, when can `get_aspirated_volume()` return `None`? Can we describe that in its documentation?

2023-03-07 15:04 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +        current_volume = self._state_view.pipettes.get_aspirated_volume(pipette_id=pipette_id) or 0
sure! in blow_out and drop-tip we set it to None. I'll add documentation.

2023-03-08 16:12 UTC, SyntaxColoring approved these changes

2023-03-08 17:39 UTC, merged