refactor(calibration): update calibration algorithm
OpenTrons/opentrons-api pull request #12243
Opened 2023-03-07 18:08 UTC by ahiuchingau

# Overview

This PR updates the binary search algorithm and removes the linear search method.

## Binary Search Flow Changes
1. We were using the wrong initial stride size – instead of 8 mm, it should be half of that, which is 4 mm.
2. Instead of starting the first probe position on the deck, our first search should be at the edge nominal position.
3. We used to have the `search_direction` param, but the name doesn't really make sense. Instead, we're renaming it `direction_if_hit` to indicate the direction we should be searching next if the we've hit the deck at the probe location.
4. Add a method to verify the edge we found is valid. We do this by probing two locations equidistant from the edge in opposite direction along the search axis. If we actually found the edge, we should see that the probe would hit the deck on one side and miss on the other. 
5. The verify method will only log a warning like this and not raise an error
```
2023-03-23 21:35:35,181 opentrons.hardware_control.ot3_calibration INFO Deck hit at check pos: (222.09375, 150.0, -0.2510000000000332)
2023-03-23 21:35:35,182 opentrons.hardware_control.ot3_calibration WARNING Edge -X could not be verified at 0.0625 mm resolution.
2023-03-23 21:35:35,182 opentrons.hardware_control.ot3_calibration INFO Found -x edge at 220.03125mm
```
As of right now, 0.0625 mm resolution works most of the time with our current robot settings. But i think once we do more testings, we can then raise an error instead of just showing a warning.

2023-03-07 19:11 UTC, sfoster1 approved these changes
The structure for this looks really solid, good with it when tested!

2023-03-07 20:08 UTC, Laura-Danielle approved these changes
We love a good deleting sesh. Code and configs look good as earlier discussed.

2023-03-07 21:09 UTC, andySigler requested changes
We should test it together and also with @andy-g-calderon , and I have a couple of things I noticed in thinking ahead to that testing

2023-03-07 21:09 UTC, andySigler commented on api/src/opentrons/hardware_control/ot3_calibration.py
>  EDGES = {
looking at the `EDGES` dict, is seems like we're saying the nominal position is 10mm from the center of the square. However, because the probe's diameter is 4mm, the nominal position is 8mm from the center of the square so that the probe and square are contacting edge-to-edge.

we could update this dict to that each enter is `(CALIBRATION_SQUARE_SIZE * 0.5) +/- PROBE_RADIUS` (+/- depending on which edge)

2023-03-07 21:09 UTC, andySigler commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    return checking_pos
a comment for line `154` above:
`checking_pos += search_axis.set_in_point(Point(0, 0, 0), stride)`
After each time we update `checking_pos`, can we check that it is not farther away from `slot_edge_nominal` than the configured `search_initial_tolerance_mm`, then raise an out-of-bounds error if that happen? If we are farther than 8mm from the edge of the square, than we should not do any probing anymore.

2023-03-08 19:23 UTC, Laura-Danielle requested changes
Actually need to modify the configs more.

2023-03-08 19:23 UTC, Laura-Danielle commented on api/src/opentrons/config/defaults_ot3.py
> +            prep_distance_mm=4.0,
We'll need to adjust these configs more. I'll report back after testing.

2023-03-17 18:44 UTC, Laura-Danielle approved these changes
lgtm

2023-03-21 14:08 UTC, sfoster1 requested changes
This looks great but I think we have one smaller step to make fixing the binary calibration algo, comment inline

Also since we're now fixing that bug, could you put a more in-depth description of what this PR's up to in the description and resulting squash commit?

2023-03-21 14:08 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    stride = edge_settings.search_initial_tolerance_mm * search_direction * 2
I think that we don't need this now that we're correctly starting in the center. Consider the following situation:
- our search tolerance is 8mm
- we're capable of taking 4 steps
- the slot edge is actually on the edge of what we can detect, 8mm to right
If we remove the `*2` here, then
- we'll start out at nominal position and miss the deck
- move (8/2=4)mm to the right to (0+4=4)mm
- miss the deck
- move (4/2=2)mm to right right to (4+2=6)mm
- miss the deck
- move (2/2=1)mm to the right to (6+1=7)mm
- miss the deck
- move (1/2=0.5)mm to the right to (7+0.5=7.5)mm
- miss the deck
- conclude the position is 7.75mm, as close as we can get

In general, the doubling had to be there because we were incorrectly starting on one edge of the search range. When we're starting in the middle we actually _do_ want to zeno's paradox ourselves!

2023-03-21 14:08 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +        if to_travel > edge_settings.search_initial_tolerance_mm:
If we do the thing above where we don't initially double the stride, then we'll be mathematically unable to hit this case

2023-03-21 14:08 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    return checking_pos
This is something that we can mathematically prevent from ever happening - we shouldn't have started on the edge, and if we set our stride right we'll only asymptotically approach the edge of the allowable range

2023-03-22 13:52 UTC, sfoster1 approved these changes
This looks great to me once tested!

2023-03-22 13:52 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
>  EDGES = {
@andySigler this is resolved now, right? the dict doesn't have the radius but it's used later

2023-03-22 13:52 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    return checking_pos
@andySigler the above should now hold, and we're verifying the edge afterwards - I think this is resolved

2023-03-23 23:38 UTC, andySigler approved these changes

2023-03-24 16:37 UTC, merged