feat(api): enable the auto update process for the rear-panel board
OpenTrons/opentrons-api pull request #12270
Opened 2023-03-10 20:45 UTC by ryanthecoder

# Overview
Tested on EVT and DVT bots, this PR lets will automatically try to update the rear-panel board if the rearPanelIntegration flag is set in the feature flags

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-03-10 20:58 UTC, sfoster1 requested changes
The changes to the `present_nodes` stuff in the controller is a little confusing, because `motor_nodes` doesn't necessarily adequately describe what that function returns - it's all canbus nodes including those without motors.

What might make more sense at this point is to have something like `present_devices: Set[FirmwareTarget]` that contains the rear panel and _just the nodes that response to GetDeviceInfo_, aka don't do the replacement of `head` with `head_l` and `head_r`; and a new property called `motor_nodes` that will return a new set with the replacements done: map `head` to `head_l` and `head_r`, map `gripper` to `gripper_z` and `gripper_g`, strip out anything that's a bootloader, do whatever @Laura-Danielle says for the 96 pipette, and return the rest. That can then be used for all the motor commands and it should be resilient to a future where we add more canbus nodes that aren't motors.

At that point, `present_devices`  can be passed into the firmware update mechanism much more easily.

Everything else looks really good, though!

2023-03-10 20:58 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    def _motor_nodes(self) -> Set[NodeId]:
this is a problematic name because it could return things that aren't motor nodes - for instance, bootloader nodes, the `head` and `gripper` nodes.

2023-03-10 20:58 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        self._present_nodes: Set[FirmwareTarget] = set()
it might be a better idea to keep this and the rear-panel presence distinct, but even if we want to mix them we should call this something like `attached_devices` or something - this now contains more than just nodes on the canbus

2023-03-10 21:22 UTC, vegano1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        self._network_info = NetworkInfo(self._messenger, self._usb_messenger)
We already instantiate NetworkInfo when we create the OT3Controller object, instead of re-creating it here we should be able to instantiate the usb_messenger before creating the NetworkInfo class and pass this usb_messenger into it.

Then all we would need to do here is call probe_network to get the usb targets.

2023-03-10 21:28 UTC, vegano1 commented on api/src/opentrons/hardware_control/ot3api.py
>          backend = await OT3Controller.build(checked_config)
why not pass the `use_usb_bus` flag here so we can create usb_messenger when the OT3Controller object is created?

2023-03-14 16:57 UTC, sfoster1 approved these changes
Okay, this looks good to me once tested. I think we need to cache more calls to `_motor_nodes`, but that's pretty minor.

2023-03-14 16:57 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        assert len(self._motor_nodes())
unfortunately with motor nodes getting a little more costly, callsites like this might want to look like
```
motor_nodes = self._motor_nodes()
assert len(motor_nodes)
response = await get_motor_position(self._messenger, self._motor_nodes())
```

2023-03-14 16:57 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        # remove pipette_left, pipetter_right and gripper
```suggestion
        # remove pipette_left, pipette_right and gripper
```

2023-03-14 16:57 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        # add pipette_left, pipeette_right and gripper if present
```suggestion
        # add pipette_left, pipette_right and gripper if present
```

2023-03-14 16:57 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            self._motor_nodes()
cache motor nodes

2023-03-14 16:57 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        self._present_devices |= core_present
we don't want a union here because if `core_present` isn't complete then we won't remove the missing nodes; in theory this will raise if that happens, but let's make sure it works even if that isn't true. I think that would be something like
```
present_core = self._present_devices.intersect(core_nodes)
present_no_code = self._present_devices - present_core
self._present_devices |= core_present
```

2023-03-14 19:17 UTC, merged