feat(api): Add module calibration mechanism to find square center on arbitrary position.
OpenTrons/opentrons-api pull request #12271
Opened 2023-03-13 14:23 UTC by vegano1

# Overview

The geometries of modules vary from unit to unit, and even though when installed they are fastened to the deck there are variations that cause inaccuracies when performing actions around the deck. This is why we need to calibrate the position of the modules relative to the deck, to ensure accuracy, especially when moving labware around with the gripper.

Closes [RCORE-609](https://opentrons.atlassian.net/browse/RCORE-609)

This pull request starts to add the mechanism required to start a module calibration on the deck, where

* We find the nominal square of that slot
* We apply the offset from the module calibration definition given a specific module, which will apply the x, y, and z offset of the calibration square, NOTE: actual offsets will be added once we have the definitions.
* We use one of our `find_square_center` methods to find the center of the given module calibration square.

# Test Plan

* Make sure we can call `calibrate_module` from ot3repl
* Make sure we can start module calibration on any slot on the deck

# Changelog

- Separate loading of the nominal position of the calibration square given a slot from finding the actual position of that square on the deck. 
- This lets us find the calibration square center at an arbitrary position which is required for module calibration since the modules have different shapes and sizes and their calibration square might not be in-line with the deck slot calibration square.
- Able to start module calibration from ot3repl

# Review requests

- We don't yet have the module calibration labware, but this will be added in a future ticket
- Does this make sense?
- Is there anything I'm missing?

# Risk assessment

Low, Flex work

2023-03-13 17:32 UTC, sfoster1 requested changes
Structure looks good and I like the refactor but definitely don't reset the instrument offset

2023-03-13 17:32 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    LOG.info(f"Found deck at {z_height}mm")
nit but this is "module plate height" rather than "deck" right?

2023-03-13 17:32 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +        await hcapi.reset_instrument_offset(mount)
we do this when calibrating instruments because otherwise the offset we find will be an offset from the old offset, instead of an offset from 0 (and, since we're recalibrating the instrument, the old offset is probably wrong).

Here, we want this instrument offset to be the one that we've calibrated. Because of the way we implement instrument offsets, they apply to all logical deck coordinates: if you have a target deck position 200 that normally is machine position 200, and your offset is +10mm, then you'll move to machine position 210 instead of 200 when moving to the deck position. And if you're moving to deck 300, then you'll move to machine 310 just the same: offset +10 means that all motions end up +10, it's an offset.

Now let's bring in modules. Say the nominal position of a module is X=200. Say that its real position is X=210, so we should store that the module's calibration offset is +10. And say that deck=>machine is the identity + a 10mm offset (so deck 200 = machine 210 ideally).

Now say that you have an instrument offset of 0, as you do after this reset. When you go to start calibration, you look up the module nominal and you get deck 200. Since your offset is 0, you turn that into machine 200, and move there. The thing is, in reality you're now at deck 190, since you haven't added those 10mm.

At deck 190, you'll run calibration and say, "ah, this module is actually +20 of where I expected it", and save the a calibration of +20, because the instrument offset applies to everything.

Finally, after restoring the old offset, you might load up the calculated module offset, and go 10mm too far.

All in all, don't reset the instrument offset here.

2023-03-13 18:22 UTC, vegano1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +        await hcapi.reset_instrument_offset(mount)
This is actually critical, thanks for pointing this out.

2023-03-14 15:26 UTC, sfoster1 requested changes
A couple things - first, there's a pretty straightforward issue with the way the z height is stored, but second, looking at the way we had to implement the position lookup here is making me a little uncomfortable. The hardware control API doesn't really have any concept of geometry systems, sort of on purpose; this feels like a bad place to do the stackup. Having it know the deck layout is kind of on the edge, though it is bolted on so maybe it's ok; but having it know about module _geometries_ like this, as opposed to module behavior, feels like too much.

What if we do one more stage of refactor in the following way:
- Make a method called like `find_calibration_structure_position(hcapi, mount, nominal_center) -> Point` that calls `find_deck_height` and `find_slot_center` (maybe rename that to `find_calibration_structure_height` and `find_calibration_structure_center`
- replace basically all the body of `_calibrate_module` and `_calibrate_mount` with a call to this method
- hoist the position determination stuff as high as it will go, ideally to the top-level `calibrate_module` call (i guess we don't have to change it for the mounts yet)
This puts us in a pretty good position for the next PR that integrates this more fully to actually do the geometry calculation somewhere else: in the engine command that drives module calibration. At that time, we change the signature of `calibrate_module` to be `calibrate_module(hcapi, mount, nominal_center)`; we get the nominal center in the engine from loading a module geometry and loading a calibration plate onto the module and asking for its center.

Ideally we'll also do a refactor for a similar thing in the mount calibration commands since they also use the engine, but that can be later, and we'll be out of the business of geometry calculations in the hardware controller again.

2023-03-14 15:26 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    nominal_center = nominal_center._replace(z=z_height)
we should make this `test_center = nominal_center._replace(z=z_height)` rather than altering `nominal_center` because...

2023-03-14 15:26 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    offset = nominal_center - found_center
since `nominal_center` has its z coordinate replaced with the detected z position of the plate, the z coordinate here will always be 0. if instead we make `test_center = nominal_center._replace(z=z_height)` and then `found_center = await find_slot_center(..., test_center, ...)` we won't have this problem

2023-03-16 17:53 UTC, sfoster1 approved these changes
Looks awesome! Nice work.

2023-03-21 14:58 UTC, Laura-Danielle requested changes
Mostly just some quick copy clean-up and one larger question about whether we should restrict calibrating modules with pipettes only.

2023-03-21 14:58 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +async def find_calibration_structure_height(
Can we change the doc string description here if we're going to be using this to find other things besides deck height?

2023-03-21 14:58 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +async def find_calibration_structure_height(
We should change the error too inside this function.

2023-03-21 14:58 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    if method == CalibrationMethod.LINEAR_SEARCH:
We're removing `LINEAR_SEARCH` (see [alise's pr](https://github.com/Opentrons/opentrons/pull/12243#pullrequestreview-1350559702)) so we should remove this option and default to BINARY.

2023-03-21 14:58 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    test_center = nominal_center._replace(z=z_height)
can we maybe call this `initial_center` or something?

2023-03-21 14:58 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    block placed in the module slot. The robot should be homed.
```suggestion
    block placed in the module slot.
    
    The robot should be homed before calling this function.
```

2023-03-21 14:58 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +        if mount == OT3Mount.GRIPPER:
Wait, are we going to need to use the gripper to calculate module offsets? Why can't we restrict to pipettes only to get the module offset? (cc @sfoster1 )

2023-03-21 15:21 UTC, vegano1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +        if mount == OT3Mount.GRIPPER:
I agree that a user is most likely to have a pipette than a gripper, but this is mostly for flexibility.

2023-03-22 13:34 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +        if mount == OT3Mount.GRIPPER:
Yeah I guess the answer is "there's no reason for the restriction so why add it"

2023-03-22 13:35 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +        if mount == OT3Mount.GRIPPER:
yeah I guess I'm just thinking from a user-flow perspective. Since we're going to be most likely restricting deck calibration to pipettes, I think we should do the same to module calibration until told otherwise.

2023-03-22 13:44 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +class StructureNotFoundError(RuntimeError):
```suggestion
class StructureNotFoundError(RuntimeError):
```

2023-03-22 13:44 UTC, Laura-Danielle approved these changes
Changes look good, but make sure to coordinate with Alise before merging this.

2023-03-22 15:54 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    if method == CalibrationMethod.LINEAR_SEARCH:
I agree with Laura here - I think we should just remove this right now and have the default method be `BINARY_SEARCH`

2023-03-22 18:24 UTC, merged