fix(api): Update liquid setup docstrings
OpenTrons/opentrons-api pull request #12276
Opened 2023-03-13 18:28 UTC by TamarZanzouri

# Overview

closes https://opentrons.atlassian.net/browse/RQA-545.
clarified docstrings for `load_liquid`, `define_liquid` and `Liquid`.

# Changelog

changed docstrings for `load_liquid`, `define_liquid` and `Liquid`.

# Review requests

Any better suggestions? 

# Risk assessment

None. just changed docstrings.

2023-03-13 19:50 UTC, ecormany requested changes
Couple little fixes, plus suggestion to roll back one of these changes.

2023-03-13 19:50 UTC, ecormany commented on api/src/opentrons/protocol_api/_liquid.py
> +    New in version 2.14.
```suggestion
    .. versionadded:: 2.14
```
sphinx-ified

2023-03-13 19:50 UTC, ecormany commented on api/src/opentrons/protocol_api/labware.py
> +        :param volume: a float that represents the volume of liquid to load, in µL.
I think we should leave these as they were before. The function definition above indicates that it takes a Liquid and a float.

2023-03-13 19:50 UTC, ecormany commented on api/src/opentrons/protocol_api/protocol_context.py
> +            liquid.
```suggestion
        :return: A :py:class:`~opentrons.protocol_api.Liquid` object representing the specified liquid.
```
fix and shorten cross-reference

2023-03-13 19:57 UTC, ecormany commented on api/src/opentrons/protocol_api/labware.py
> +        :param volume: a float that represents the volume of liquid to load, in µL.
Actually I just looked at the ticket and _this_ is the annotation we need:
```suggestion
        :param Liquid liquid: The liquid to load into the well.
        :param str volume: The volume of liquid to load, in µL.
```

2023-03-13 19:58 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/labware.py
> +        :param str volume: The volume of liquid to load, in µL.
```suggestion
        :param float volume: The volume of liquid to load, in µL.
```

2023-03-13 20:05 UTC, ecormany approved these changes
All looks good in sandbox! 🏖️🚢

2023-03-16 09:55 UTC, sanni-t approved these changes
LGTM!
Curious as to why underscored `_liquid` & `_id`? What

2023-03-16 14:01 UTC, merged

2023-03-16 20:08 UTC, SyntaxColoring commented
@sanni-t Those underscores were my suggestions.

**My thinking behind the underscore in the `_liquid` module name:**

The proper import path for this class is `opentrons.protocol_api.Liquid`. The presence of an `opentrons.protocol_api._liquid` module should be treated as an unstable implementation detail.

We can and have reorganized classes between modules in the past. Without underscores, it's difficult to discern which import paths are meant to be customer-facing (like `opentrons.execute`) and which are not (like `opentrons.protocol_api.module_validation_and_errors`).

We alternatively could have made the canonical path `opentrons.protocol_api.liquid.Liquid`, and not supported `opentrons.protocol_api.Liquid`. It just would have been longer and more redundant.

**Underscore for the `_id` attribute name:**

The notion of "a liquid ID" and how it relates to Protocol Engine is an internal implementation detail that customers shouldn't see.