fix(api): Add set_calibration not implemented to versioning doc
OpenTrons/opentrons-api pull request #12274
Opened 2023-03-13 17:07 UTC by TamarZanzouri

# Overview

closes https://opentrons.atlassian.net/browse/RQA-544. 
Added a not implemented explantation to the version doc. 

# Test Plan

Uploading this protocol should raise a not implemented error.

```
# Test protocol
from opentrons import protocol_api
from opentrons.types import Point

metadata = {
    "protocolName": "2.14 test for Labware and Well now adhere to the protocol's API level setting. Prior to this version, they incorrectly ignored the setting.",
    "author": "Opentrons Engineering <engineering@opentrons.com>",
    "source": "Software Testing Team",
    "description": ("Labware and Well"),
    "apiLevel": "2.14",
}

def run(protocol: protocol_api.ProtocolContext) -> None:
    """This method is run by the protocol engine."""
    # Labware
    plate = protocol.load_labware(
        "corning_96_wellplate_360ul_flat", location="2", label="plate_label"
    )
    plate.set_calibration(delta=Point(x=0.10, y=0.01, z=-1.01))
```

# Changelog

Added to the versioning doc under Known limitations.

# Review requests

Do we feel good about this change? 

# Risk assessment

low. just added an explanation to the docs.

2023-03-13 18:17 UTC, sanni-t reviewed
This is good but we should also update the docstring for `set_calibration` to say that it's deprecated in 2.14.

I think that docstring needs some attention anyway since it's not super clear. It almost sounds like that method was intended to be used only internally but ended up being a public interface by chance. Either way, we need to update it.

2023-03-13 20:12 UTC, ecormany reviewed
Quick Q about future status of `set_offset` and `set_calibration`.

2023-03-13 20:12 UTC, ecormany commented on api/docs/v2/versioning.rst
> +  - :py:meth:`.Labware.set_calibration` is not supported on this API version.
is `set_calibration` ever going to be supported again? should it go in the removals section, even if it's thematically linked to `set_offset`?

2023-03-13 20:12 UTC, ecormany commented on api/src/opentrons/protocol_api/labware.py
> +        An internal, deprecated method Called by set_offset in order to update the offset on the object.
```suggestion
        An internal, deprecated method called by ``set_offset`` in order to update the offset on the object.
```

2023-03-14 14:59 UTC, sanni-t requested changes
From slack conversation, we are deciding to remove `set_calibration` from the public API. So let's making it a private method, update the docstring and move the versioning notice in the removals section as @ecormany mentioned.

2023-03-14 17:00 UTC, TamarZanzouri commented
After further conversation with the team we have decided we will deprecate `set_calibration` for versions 2.14 and above and we will continue supporting versions less than 2.14.

2023-03-14 17:52 UTC, TamarZanzouri commented on api/docs/v2/versioning.rst
> +  - :py:meth:`.Labware.set_calibration` is not supported on this API version.
you are right @ecormany we should probably move it to the removals section. I will do that change

2023-03-14 19:38 UTC, sanni-t commented on api/docs/v2/versioning.rst
> +
I think we can just mention this method on line 299 above which already talks about removed calibration methods in 2.14

2023-03-16 14:59 UTC, sanni-t commented on api/docs/v2/versioning.rst
> +    Setting a labware's calibration after it's been loaded is not supported.
So I was thinking more on the lines of-
```suggestion
  - ``Labware.separate_calibration``, :py:meth:`.Labware.set_calibration` and ``ModuleContext.separate_calibration`` were removed, since they were holdovers from a calibration system that no longer exists.
```

2023-03-16 19:32 UTC, TamarZanzouri commented on api/docs/v2/versioning.rst
> +    Setting a labware's calibration after it's been loaded is not supported.
```suggestion
  - ``Labware.separate_calibration`` and :py:meth:`.Labware.set_calibration` were removed,
    since they were holdovers from a calibration system that no longer exists.
```

2023-03-16 19:43 UTC, sanni-t approved these changes

2023-03-16 19:58 UTC, merged