refactor(api): do not force home after pickup & drop tip for OT3
OpenTrons/opentrons-api pull request #12280
Opened 2023-03-13 20:19 UTC by ahiuchingau

# Overview
Will need tests 

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-03-16 13:54 UTC, andySigler commented on api/src/opentrons/hardware_control/ot3api.py
> +        await self._update_position_estimation(
There is inconsistency from HWE on what the desired behavior is here. The plunger motors are spec'd to be 3x stronger than what a drop-tip would require, and so if there is skipping here it would likely mean a hardware issue. I'll check with ME team, and if that's the case then we would want to remove this re-alignment after drop-tip and have it raise an Error if a stall is detect.

2023-03-16 13:54 UTC, andySigler commented on api/src/opentrons/hardware_control/ot3api.py
> +        self, mount: Union[top_types.Mount, OT3Mount], home_after: bool = False
woo!

2023-03-17 17:20 UTC, sfoster1 requested changes
Gotta remove a print, looks good otherwise

2023-03-17 17:20 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +        print(f"what is target: {target}, {type(target)}")
need to remove this one

2023-03-17 20:33 UTC, Laura-Danielle commented
Testing on a robot:

- Pick up tip ✅ 
- Drop tip ❌ 
Getting a weird error after drop tip on this branch:

```
>>> api.drop_tip(OT3Mount.LEFT)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/opentrons-robot-server/opentrons/hardware_control/adapters.py", line 65, in call_coroutine_sync
    return fut.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/opt/opentrons-robot-server/opentrons/hardware_control/ot3api.py", line 1671, in drop_tip
    await self._update_position_estimation(
  File "/opt/opentrons-robot-server/opentrons/hardware_control/execution_manager.py", line 128, in replace
    return await decorated(inst, *args, **kwargs)
  File "/opt/opentrons-robot-server/opentrons/hardware_control/ot3api.py", line 637, in _update_position_estimation
    await self._backend.update_motor_estimation(checked_axes)
  File "/opt/opentrons-robot-server/opentrons/hardware_control/backends/ot3controller.py", line 396, in update_motor_estimation
    raise MustHomeError(f"Axis {node} has invalid encoder position")
opentrons.hardware_control.errors.MustHomeError: Axis 33 has invalid encoder position
```

2023-03-21 14:24 UTC, sfoster1 approved these changes
Looks good to me once we test and fix the issue @Laura-Danielle found!

2023-03-21 18:11 UTC, caila-marashaj approved these changes
nice!!

2023-03-22 16:55 UTC, merged