refactor(api): do not home pipette plungers unless necessary
OpenTrons/opentrons-api pull request #12282
Opened 2023-03-13 21:15 UTC by ahiuchingau

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-03-17 17:23 UTC, sfoster1 requested changes
Let's get this one a little more coordinated with https://github.com/Opentrons/opentrons/pull/12280 - it kind of seems like the only thing in here should be the `home_plunger` changes?

2023-03-17 17:23 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        if not self._backend.check_motor_status([OT3Axis.by_mount(realmount)]):
wait this should be part of https://github.com/Opentrons/opentrons/pull/12280 right? doesn't involve the plunger

2023-03-17 17:23 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        if not self._backend.check_motor_status([OT3Axis.by_mount(realmount)]):
or really it conflicts, we remove the retract there I think

2023-03-17 20:36 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +        if not self._backend.check_motor_status([OT3Axis.by_mount(realmount)]):
yeah it should be removed here.

2023-03-17 20:38 UTC, Laura-Danielle reviewed
Hardware said they aren't comfortable having this behavior be the default right now :( They wanted to run some more tests.

2023-03-20 21:54 UTC, ahiuchingau commented
Waiting for HW to confirm whether or not we want this behavior, closing the PR for now

2023-03-20 21:54 UTC, closed without merging