feat(api): add calibrate module command to protocol engine.
OpenTrons/opentrons-api pull request #12306
Opened 2023-03-16 21:33 UTC by vegano1

# Overview

Module calibration is just another type of calibration similar to instrument/deck calibration, this pull request adds the module calibration commands to the protocol engine.

# Test Plan

- [ ] Make sure we can start the module calibration protocol engine command by creating a simple protocol run.
- [ ] Make sure we are loading in the corresponding geometries based on the module type

# Changelog

- Add ModuleCalibration and corresponding commands to the protocol engine
- Moves calibration-related deck geometry from the hardware controller to shared-data module
- Change the definition of calibrate_module so it takes a nominal_position: Point, with the idea that the protocol engine will pass in the nominal location of the calibration square for the hardware controller to probe.

# Review requests

- Does this make sense?
- Missing anything?

# Risk assessment

- Low, OT3 only

# Todo

- [ ] add unit tests
- [ ] add deck height offset
- [ ] add module height offset

2023-03-21 18:12 UTC, caila-marashaj approved these changes, later dismissed

2023-03-27 19:09 UTC, sfoster1 requested changes
This is looking good but I think we can take the refactor of moving calibration square details to shared-data one slight step farther by making the new `get_calibration_square_center()` function be `get_calibration_square_details()` or something, which returns a dataclass that includes the offset of both the center of the calibration square and its edges, and its z check position - basically, all the stuff that's currently in constants. We can then pass that into the hardware control function.

This seems like it will make the repl worse, but we can real quick drop some wrapper functions in there.

2023-03-27 19:09 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/deck/__init__.py
> +    assert s["id"] == str(slot)
I think this is a bad idea for several reasons.

First, it's checking a precondition ("you gave me a valid slot") by checking a postcondition ("the slot that I loaded has a correct ID"). 
Second, it's gonna be a pretty rough error message: `AssertionError: "2" != "1"` doesn't really tell you a whole lot.
Third, we sort of want to change the ids to be like "A1" and "B2", and that will definitely make this check fail.

Instead, I think we want to rely on the `KeyError` from line 61.

2023-03-27 19:09 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/deck/__init__.py
> +    deck = load("ot3_standard", version=3)
I think that this function should not do its own deck definition loading. Instead, let's make it take the deck definition as an argument. The engine should have access to the deck definition and can feed it in. This is then more like an accessor on the deck definition without having to build in assumptions like what deck it's for.

Also makes it easier to test since you can test it with more minimal deck defs.

2023-03-27 19:09 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/deck/__init__.py
> +def get_calibration_square_position_in_slot(slot: int) -> Offset:
I wonder if we can fix a couple problems at once by making this return more than just the center of the square. Instead, we can make a dataclass that says
- the center of the square
- the keypoints for all the edges of the square
- the depth and "size" of the square
- where you should probe z for this square
and return that.

That will let us remove some of these exported and reused constant values above, which is good because if we ever need to make them dynamic it's nicer that they're already returned from a function rather than implemented.

2023-03-27 19:09 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +REPEATABLE_STRIDES: List[float] = [1.0, 0.25, 0.1, 0.025]
Once the `get_calibration_square_details()` (or whatever we call it) function returns a dataclass as mentioned in comments in the shared-data changes, we can remove these and pass the details into the hardware control calls.

2023-03-27 19:09 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_module.py
> +        module_offset = await calibration.calibrate_module(
the idea with the suggested refactor to `get_calibration_square_position` would be that you call it _here_, and you pass the dataclass into `calibrate_module` (or the other calibrate_* functions) as an argument, and they then curry out the information they need.

2023-03-27 20:33 UTC, sanni-t requested changes
I don't think we need to go through creating labware geometry accessors in `shared_data`. There is one missing step in the assumption of the process of calibrating modules and that is loading the calibration block 'labware'. 
Please correct me if I am missing something, but this is how I imagine the process would be-
1. Client creates an empty run.
2. Client sends a `loadModule` request to load a module in a particular slot. Engine loads it and creates a module ID.
3. Client sends a `loadLabware` request to load the calibration block labware on top of the previously loaded module. Engine loads it and creates a labware ID for it.
4. Client sends a `calibrateModule` request and specifies the calibration block labware ID, the module ID and the mount to use.
    - Engine command executor does something like
    ```
    ot3_api = ensure_ot3_hardware(
            self._hardware_api,
        )
    ot3_mount = OT3Mount.from_mount(params.mount)
    # Is the plan to associate the module's calibration offset using a slot location & serial number?
    slot = self._state_view.modules.get_location(params.moduleId).slotName.as_int()
    module_serial = self._state_view.modules.get(params.moduleId).serialNumber
    
    # If needed, we can verify here whether the labware id belongs to a calibration block
    
    # If the nominal position needs to be something offset from well A1 position, then we can provide this offset in the `get_well_position` selector too.
    nominal_position = self._state_view.get_well_position(
            labware_id=params.labwareId,
            well_name="A1",
        )
    # start the calibration
    module_offset = await calibration.calibrate_module(
        ot3_api, ot3_mount, slot, module_serial, nominal_position
        )
    return ModuleOffsetVector(
                x=module_offset.x, y=module_offset.y, z=module_offset.z
        )
    ```

2023-03-27 20:33 UTC, sanni-t commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_module.py
> +            params.moduleId
`get_labware_origin_position` takes a labware ID. You are passing a module ID to it.

2023-03-27 21:06 UTC, vegano1 commented on shared-data/python/opentrons_shared_data/deck/__init__.py
> +    deck = load("ot3_standard", version=3)
Agreed,
However, instrument calibration methods in the `ot3_calibration.py` still use this function to get the slot nominal position, I think that would be a good change to make in a follow-up pr.

2023-03-27 21:15 UTC, vegano1 commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_module.py
> +            params.moduleId
Yeah this is a good observation
1. The shared-data change is only needed right now because the instrument calibration methods still use the slot geometries directly. There will be a follow-up pr to completely remove any handling of geometries from the hardware_controller, so all the calibrate_ methods will instead get a `nominal_position: Point` arg to start the calibration. For now, this is step one to start that decoupling.
2. Agreed on the missing step, thank you for pointing that out.

2023-03-28 14:10 UTC, vegano1 commented on shared-data/python/opentrons_shared_data/deck/__init__.py
> +    deck = load("ot3_standard", version=3)
@sfoster1 
Once we move calibration methods to use `nominal_position: Point`from protocol engine the suggested change would make more sense.

2023-03-28 14:30 UTC, sfoster1 commented
>     1. Client creates an empty run.
> 
>     2. Client sends a `loadModule` request to load a module in a particular slot. Engine loads it and creates a module ID.

totally, this sounds good
>     3. Client sends a `loadLabware` request to load the calibration block labware on top of the previously loaded module. Engine loads it and creates a labware ID for it.
> 
>     4. Client sends a `calibrateModule` request and specifies the calibration block labware ID, the module ID and the mount to use.

The degree to which this needs a very _particular_ labware that is unique to the module makes this feel redundant. There's one labware definition that will be used here, for each module. If we make the client be the one that knows what that labware is, we're spreading out the implementation knowledge required, for very little gain. I think the engine should load the labware on its own; it could maybe provide the ID it loaded for the client to specify later, but now that's a fully roundtripped piece of information that is again redundant.

>        * Engine command executor does something like
>        
>        ```
>        ot3_api = ensure_ot3_hardware(
>                self._hardware_api,
>            )
>        ot3_mount = OT3Mount.from_mount(params.mount)
>        # Is the plan to associate the module's calibration offset using a slot location & serial number?

Just the serial. This is a calibration for how the module sits in its cradle, not how the cradle sits in the slot.

>        slot = self._state_view.modules.get_location(params.moduleId).slotName.as_int()
>        module_serial = self._state_view.modules.get(params.moduleId).serialNumber
>        
>        # If needed, we can verify here whether the labware id belongs to a calibration block
>        
>        # If the nominal position needs to be something offset from well A1 position, then we can provide this offset in the `get_well_position` selector too.
>        nominal_position = self._state_view.get_well_position(
>                labware_id=params.labwareId,
>                well_name="A1",
>            )
Well, kind of. we need more than one offset; we need some understanding of more structure than just the offset. One way to think about it would be "the position of the center of each edge of this rectangular well", and "some other feature called the z offset point". So we could add selectors for the well edges, and add a second dummy "well" for the z offset position. Actually that's a good idea for #12351 
>        # start the calibration
>        module_offset = await calibration.calibrate_module(
>            ot3_api, ot3_mount, slot, module_serial, nominal_position
>            )
>        return ModuleOffsetVector(
>                    x=module_offset.x, y=module_offset.y, z=module_offset.z
>            )
>        ```

2023-03-28 14:38 UTC, sfoster1 commented
So after @sanni-t 's comment here https://github.com/Opentrons/opentrons/pull/12306#pullrequestreview-1359751136 and @vegano1 's  comment here: https://github.com/Opentrons/opentrons/pull/12306#discussion_r1150687852 I think I'm wrong about these suggested refactors. 

IMO we should 
1. get consensus on the API and whether the client has to load a labware
2. have that api in here, but wait on essentially implementing that functionality for a second PR
3. Merge #12351 with the z-offset position added
4. Add a new PR that makes "deck calibration" labware that represents the physical deck items; maybe this is in the deck def but _maybe_ it's a dummy labware that has a well z position of 0 assuming nothing prevents that
5. In all the protocol engine implementations for calibration, derive the key points of the calibration structures from (a) the well center of the calibration well; (b) the edges of the calibration well, via new accessors; (c) the z-offset well

At that point we'll be fully free of magic numbers in config.

2023-03-28 21:12 UTC, vegano1 commented
@sfoster1 

After speaking to Sanniti, Protocol Engine (PE) API expects to run PE commands and return a `CommandResult` which sets various command-specific states within PE. Right now PE expects to load labware from the `LoadLabware` PE command, which registers the labware and ultimately allows PE to do the geometry stack-up with the module.

From that perspective, it makes sense to let the client tell us what labware to load.

2023-03-30 20:17 UTC, sanni-t approved these changes
This looks good to me! Good to merge once CI passes.
Just a few nitpicks from me.

2023-03-30 20:17 UTC, sanni-t commented on api/src/opentrons/protocol_engine/types.py
> +    """Module Offset from home position to robot deck."""
```suggestion
    """Offset, in deck coordinates, from nominal to actual position of labware on a module."""
```

2023-03-30 20:17 UTC, sanni-t commented on api/tests/opentrons/protocol_engine/commands/calibration/test_calibrate_module.py
> +from opentrons.hardware_control.api import API
```suggestion
from opentrons.hardware_control.api import API as OT2API
```

2023-03-30 20:17 UTC, sanni-t commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_module.py
> +            labware_id=params.labwareId, well_name="A1"
Just want to make sure that the calibration process expects to receive A1's coordinates and not B1's.

2023-03-30 20:42 UTC, sanni-t commented
> The degree to which this needs a very particular labware that is unique to the module makes this feel redundant. There's one labware definition that will be used here, for each module. If we make the client be the one that knows what that labware is, we're spreading out the implementation knowledge required, for very little gain. I think the engine should load the labware on its own; it could maybe provide the ID it loaded for the client to specify later, but now that's a fully roundtripped piece of information that is again redundant.

Got it. Hmm, I'm not fully convinced that it's a bad idea to spread out the knowledge of module <> calibration block pairing because it actually does require a user and a client to know which block to use with which module. Having the command require a labware id feels safer to me than letting a client start the process after only specifying the module. I'm thinking from the perspective of a third party client too.

That said, I'm not totally opposed to having `calibrateModule` command pick the appropriate block for the module. But the structure of the engine doesn't allow one command to call another so loading a labware inside of this command would require a little more effort than this proof-of-concept ticket probably wants to spend so I'll still advocate this method for now. Eventually we could duplicate some labware loading logic to calculate the absolute location of the calibration point.

2023-03-31 16:17 UTC, vegano1 commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_module.py
> +            labware_id=params.labwareId, well_name="A1"
it should be B1, just fixed it, thank you

2023-03-31 20:34 UTC, sfoster1 approved these changes
Very happy with it! Saw it work too.

2023-03-31 20:34 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +CALIBRATION_MIN_VALID_STRIDE: Final[float] = 0.1
I think these are no longer necessary after switching to binary search?

2023-03-31 20:36 UTC, vegano1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +CALIBRATION_MIN_VALID_STRIDE: Final[float] = 0.1
correct

2023-03-31 20:51 UTC, merged