feat(robot-server): add API version 5 with authentication checking for most endpoints
OpenTrons/opentrons-api pull request #12307
Opened 2023-03-17 14:05 UTC by fsinapi

# Overview

This PR adds communication from the Robot Server to the System Server for verification of authentication tokens from clients.

This adds a new API version (5). The only difference from version 4 to 5 is the addition of a new header, `authenticationBearer`. In any `Opentrons-Version` below 5, the new header is ignored; if the version is set to `5` or `*`, the token is verified before executing a command. If the authentication fails, a response of `HTTP 403 FORBIDDEN` is sent.

The robot-server will send a `GET /system/authorize` request to the system server, attaching that token. A response code of `200` means the token is authorized, and any other code means that the token is invalid.

Closes [RCORE-516](https://opentrons.atlassian.net/browse/RCORE-516) and [RCORE-517](https://opentrons.atlassian.net/browse/RCORE-517)

# Test Plan

I've tested this by running the robot-server + the system-server. If the system server is running and you specify API version 5, you need to provide a _valid_ auth token to access non-health endpoints. If the system server is not running, or the token is invalid, you get an error.

Failed & successful authentication workflows are included in integration testing.

To test the timing impact, I set up a script that sends a `GET /SETTINGS` request (this was before I removed authentication from GET endpoints) 1000 times and ran it on API versions 4 and 5.
* Time without authentication: 82.85 seconds
* Time with authentication: 110.34 seconds

Impact is **27.49** seconds across 1000 requests, so **~27.5 milliseconds** for every API call.

# Changelog

- Added an API version 5 accepted by the robot-server
- Added `aiohttp` package (at the same version as the update-server) for HTTP client purposes
- Added an HTTP header "authenticationBearer" that accepts an (optional) string
- Added connection to the System Server with aiohttp.
- Added errors for authentication failure - _need to get these into the docs_!
- Updated integration tests to run the System Server & get auth tokens where appropriate
- Added integration tests that check for working & nonworking authentication scenarios
- Added authentication error documentation to relevant endpoints
- Removed authentication checks from GET endpoints

# Review requests

- Even with putting this behind an API version bump, this could cause issues for clients that use the `*` api version. It may also be frustrating when using a Dev server, since you'd theoretically have to launch a dev System Server as well.
  - We could add a feature flag to disable it
  - We could add an option where, if the system server IP setting is set to a certain value, authentication is disabled
- I set this up using aiohttp because it's already on the robots, but it's an ancient version. It should do the job fine, but is there a motivation to use a different package (`httpx`?) that isn't tied to the Update Server?
- Legacy routes! I don't know the context for the name! is there motivation to leave these routes alone, or is it fine to add the authenticationBearer here as well?
- This adds 20-30 milliseconds to every API call. On simpler endpoints this is up to a 25% increase. Is that acceptable?
  - Per Seth's suggestion, changed this to completely ignore authentication on any GET endpoints.

# Risk assessment

Since the app specifies an actual HTTP version, it should not be difficult to gain confidence that this won't affect app compatibility. However, any other HTTP clients that may use the `*` version setting will be affected. If we're concerned about that, we should have a mechanism to disable this (with a Feature Flag I assume); if there _aren't_ other notable clients (other than CI integration), it isn't a big deal.

[RCORE-516]: https://opentrons.atlassian.net/browse/RCORE-516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RCORE-517]: https://opentrons.atlassian.net/browse/RCORE-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-04-03 14:52 UTC, vegano1 commented on robot-server/robot_server/authentication/_dependencies.py
> +        return
do we want to explicitly raise an error here with an unsupported API version or similar?

2023-04-03 15:43 UTC, fsinapi commented on robot-server/robot_server/authentication/_dependencies.py
> +        return
I think we specifically want to have backwards compatibility, at least to start. The `MIN_API_VERSION` in versioning.py handles the cutoff of errors for old API versions.

2023-04-05 15:07 UTC, shlokamin reviewed
this approach makes sense to me, would be good to get RSS eyes on this though

2023-04-05 15:07 UTC, shlokamin commented on robot-server/robot_server/authentication/_dependencies.py
> +        return ClientSession()  # type: ignore
seems like we should either try to upgrade or start migrating to a newer package, but ill defer to the robot sever code owners @sanni-t  @SyntaxColoring @jbleon95

2023-04-27 13:42 UTC, sfoster1 requested changes
Is there some kind of higher-up-the-dependency-tree place to inject a Depends()? Seems like we'd have to add it to literally every route which is... annoying.

Also if we're concerned about authentication overhead, I think it would be reasonable to pull the auth requirement from `GET`s, or at least from _general_ `GET`s like listiing all runs, etc.

2023-04-27 13:42 UTC, sfoster1 commented on robot-server/robot_server/authentication/_dependencies.py
> +        return ClientSession()  # type: ignore
We should, but unfortunately this is one of those cases where on an OT-2 this is set by buildroot...

2023-04-27 13:42 UTC, sfoster1 commented on robot-server/robot_server/authentication/_dependencies.py
> +        return ClientSession()  # type: ignore
I think if we're that concerned about it we should use `requests` in a worker thread with an asyncio interface.

2023-04-27 13:42 UTC, sfoster1 commented on robot-server/robot_server/authentication/_dependencies.py
> +        raise AuthenticationFailed(detail=str(e)).as_error(status.HTTP_403_FORBIDDEN)
while usually it's good practice to have _any_ error in an auth flow have identical outcomes to prevent probing, here we're only kind of using this for auth and it's two internal clients. I think this should be a 502 or something.

2023-04-27 13:42 UTC, sfoster1 commented on robot-server/robot_server/versioning.py
> +5. Introduced in v6.4 (???) of the Opentrons software
Let's annotate this with a TODO

2023-06-23 17:58 UTC, sfoster1 approved these changes
Looks good to me, though I assume since it's been a while we'll need some fixups

2023-10-20 17:52 UTC, closed without merging