chore(app-shell): migrate usb detection
OpenTrons/opentrons-api pull request #12311
Opened 2023-03-17 17:26 UTC by brenthagen

since `usb-detection` is [now deprecated](https://github.com/MadLittleMods/node-usb-detection), an initial attempt at migration to `usb`.

TODO:
 - adjust `UsbDevice` type
 - make necessary realtek adapter detection changes

2023-03-22 14:34 UTC, sfoster1 requested changes
We should continue to hold this out of ODD builds - we'll have the same problem with cross compilation, and ODD just doesn't need it at all.

2023-03-22 14:34 UTC, sfoster1 commented on app-shell-odd/Makefile
> -	NO_USB_DETECTION=true OT_APP_DEPLOY_BUCKET=opentrons-app OT_APP_DEPLOY_FOLDER=builds OPENTRONS_PROJECT=ot3 $(builder) --linux --arm64
we almost certainly still need to hold this out of ODD builds. it's a native node extension that forms a thing wrapper around libusb, but it still will have the problems with cross-compilation that usb-notifications had.

2023-03-22 14:34 UTC, sfoster1 commented on app-shell-odd/Makefile
> -	NO_USB_DETECTION=true OT_APP_DEPLOY_BUCKET=opentrons-app OT_APP_DEPLOY_FOLDER=builds OPENTRONS_PROJECT=ot3 $(builder) --linux --arm64
Or is this because it's unnecessary since there was never an `app-shell-odd` dep on `usb-detection` in the first place?

2023-03-22 15:21 UTC, brenthagen commented on app-shell-odd/Makefile
> -	NO_USB_DETECTION=true OT_APP_DEPLOY_BUCKET=opentrons-app OT_APP_DEPLOY_FOLDER=builds OPENTRONS_PROJECT=ot3 $(builder) --linux --arm64
yes exactly, i think it's unnecessary since `app-shell-odd` doesn't have the dep

2023-03-28 14:40 UTC, sfoster1 approved these changes
Never mind, didn't understand the app-shell-odd situation

2023-05-15 21:01 UTC, closed without merging