utilize legacy deck transform save/load mechanisms
OpenTrons/opentrons-api pull request #12381
Opened 2023-03-29 15:33 UTC by pmoegenburg

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-03-30 14:52 UTC, sfoster1 requested changes
Definitely on the right track!

2023-03-30 14:52 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +        return expected, actual  # need to return anything?
yeah i think we should keep the return, it's good to have

2023-03-30 14:52 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    z = abs(curr_cal[2][-1])
this isn't a good thing to check and this function appears to assume an affine transform. we should remove the `outofrange` check, and make sure that `identity_deck_transform` is giving us I_3

2023-03-30 14:52 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +def migrate_affine_xy_to_attitude(
don't need, never had an affine transform here

2023-03-30 14:52 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    gantry_cal = get_legacy_gantry_calibration()
don't need this legacy stuff

2023-03-30 14:52 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +            attitude=default_deck_calibration(),
make sure this is the right default

2023-03-30 14:52 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +            tiprack=calibration_data.tiprack,
don't need tiprack data

2023-03-30 14:52 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    )
probably should add a `RobotCalibrationProvider` so we can pull functionality out of ot3api

2023-05-03 18:31 UTC, sfoster1 requested changes
This is looking good in structure, and because it's so limited in functionality (which is good!) I think there's not much in the way of tests that are missing either. However, what we do need is
- A more in-depth set of comments about how this calibration data works and is structured, particularly around what the difference between deck and belt calibration is and how it all works
- A double check of whether there's stuff that was useful in the OT-2 that isn't useful here
- A general pass to remove copy-paste artifacts

2023-05-03 18:31 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +            belt_attitude = await _determine_transform_matrix(hcapi, mount)
we should reset the belt calibration while this method is executing

2023-05-03 18:31 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +def apply_machine_transform(
let's add a docstring about what this does and why it's there.

2023-05-03 18:31 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +def save_belt_attitude_matrix(
this doesn't really seem to do anything, do we need it?

2023-05-03 18:31 UTC, sfoster1 commented on api/src/opentrons/config/robot_configs.py
>  def default_deck_calibration() -> List[List[float]]:
We now are calling this from different places - can we split it into two functions and remove the feature flag check?

2023-05-03 18:31 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    TODO(lc, 8/10/2020): Expand on this method, or create
expand on this so it's not just a copied comment please.

2023-05-03 18:31 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +def load() -> DeckCalibration:
maybe we can remove this function and just call `load_attitude_matrix()`?

2023-05-03 18:31 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +            deck_calibration=load(),
small: we do this creation of OT3Transforms 3 different times; let's factor it out into a single function.

2023-05-03 18:31 UTC, sfoster1 commented on api/tests/opentrons/calibration_storage/test_deck_attitude.py
>      if robot_model == "OT-3 Standard":
at these point these do different things with different values and mean different things. Just make this two tests and import at the top.

2023-05-03 18:31 UTC, sfoster1 commented on api/tests/opentrons/calibration_storage/test_deck_attitude.py
> +        from opentrons.calibration_storage import (
make this two tests

2023-05-03 18:31 UTC, sfoster1 commented on api/tests/opentrons/calibration_storage/test_deck_attitude.py
> +        from opentrons.calibration_storage.ot3.models.v1 import (
make this two tests

2023-05-03 18:31 UTC, sfoster1 commented on api/tests/opentrons/calibration_storage/test_deck_attitude.py
> +    if robot_model == "OT-3 Standard":
make this two tests

2023-05-03 18:31 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +        self._hardware = cast(OT2HardwareControlAPI, hardware)
let's add a todo (or just write the code) to raise `HardwareNotSupportedError` here

2023-05-03 18:31 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +        self._hardware.set_robot_calibration(
IMO we should keep this as `self.hardware` now that it's typed correctly

2023-05-03 18:31 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +class OT3RobotCalibrationProvider:
Let's put a docstring in this class that talks about what the different offsets and such are.

2023-05-03 18:32 UTC, sfoster1 commented
We also need a pretty in-depth test plan for running this on hardware.

2023-05-09 21:40 UTC, pmoegenburg commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +            belt_attitude = await _determine_transform_matrix(hcapi, mount)
I interpreted this as `delete_robot_belt_attitude()`

2023-05-09 21:40 UTC, pmoegenburg commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +class OT3RobotCalibrationProvider:
Need help with this

2023-05-09 21:40 UTC, pmoegenburg commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +            deck_calibration=load(),
more work than it's worth imo

2023-05-09 21:40 UTC, pmoegenburg commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    TODO(lc, 8/10/2020): Expand on this method, or create
Attempted

2023-05-10 15:26 UTC, sfoster1 requested changes
This is overall looking good, though I think we need to alter the way we make sure that the previous belt calibration is not loaded during the belt calibration process.

2023-05-10 15:26 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +            belt_attitude = await _determine_transform_matrix(hcapi, mount)
I think this isn't quite right. We're only removing the transform _after the calibration process_. That means that during the calibration process, our movements are affected by the old calibration, which is what we want to avoid.

What we want is to reset the loaded calibration - without affecting what's saved on disk - _before_ we call `_determine_transform_matrix`. After we call that, we should save over what's on disk. And in the `finally`, we should _reload_ the calibration from disk, whatever it is. if calibration succeeded, then it'll be the new calibration; if it failed, it'll be the old one.

2023-05-10 15:26 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +class OT3RobotCalibrationProvider:
- carriage_offset: the vector from the deck origin to the bottom center of the gantry carriage when the gantry is homed
- mount offset (per mount): the vector from the carriage origin (bottom center) to the mount origin (centered on the top peg of the mount flush with the mating face)

2023-05-10 15:26 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3_calibration.py
> +    This converts belt attitude matrix to machine attitude matrix, which is inverted, by applying a negative identity matrix
Maybe a better way of thinking about this and phrasing it is that it applies the belt attitude matrix on top of the machine attitude matrix (which happens to be a negative identity) to form the deck attitude matrix.

2023-05-22 20:35 UTC, sfoster1 approved these changes
All right! I think this great and we should get it merged! Nice work, I know its been in progress for a while.

2023-05-22 21:02 UTC, merged