feat(hardware-testing): DVT Gripper assembly QC test
OpenTrons/opentrons-api pull request #12387
Opened 2023-03-29 19:40 UTC by andySigler

# Overview

DVT gripper assembly qc script functional. Will need updates in a week or so for new force-gauge fixture, but this is working as-is.

This script tests:
- Gripper Z-axis currents/speeds, comparing estimated motor position to encoder
- Desired jaw force vs measured force using force gauge
- Desired jaw width vs measured jaw with using gauge blocks
- Capacitive probe values in air, with probe, and touching the deck

# Test Plan

# Changelog

### API
- Decreases gripper Z max speed from 100 to 50 mm/sec
- Increases gripper Z acceleration from 20 to 150 mm/sec^2
- Allow jaw encoder to sometime report negative value, no need to raise error
- Include updating the gripper Jaw width inside `OT3API._cache_encoder_position()`
- Add `OT3API.jaw_width` property to report the calculated jaw width

### Hardware-Testing
- Adds gripper assembly qc script

# Review requests

# Risk assessment

2023-03-29 21:27 UTC, sfoster1 requested changes
Glad for the tests, but let's split this up to get the functional changes to the hardware controller into a different PR. I think we also need to change the way that get-gripper-jaw api works; it really should be a function that takes a mount, or maybe an attribute of the return value of `get_instruments()`, or another axis that's in current_position or something - this kind of folding it into a function on the main object is not really the style of the rest of the API.

2023-03-29 21:27 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +    def jaw_width(self) -> Optional[float]:
This isn't really the right place for this API. We should expose this through something on the gripper handler that you'd access by doing `get_instruments()` or something, or maybe make sure we're returning it in `current_position()`. We generally avoid having functions like this that give you details about an instrument on the main object without an arguments.

2023-03-31 01:09 UTC, andySigler commented
@sfoster1 same as #12386, I'd like to leave this here for a day or two full test is settled IRL, then will make said changes before a merge 👍

2023-04-04 13:13 UTC, sfoster1 approved these changes
nice!

2023-04-05 00:26 UTC, merged