add migrate_new_blowout_configs function
OpenTrons/opentrons-api pull request #12384
Opened 2023-03-29 17:43 UTC by caila-marashaj

2023-04-05 17:24 UTC, Laura-Danielle reviewed
Initial comments, but in general looking good! Very proud of you for tackling this :D

Later this afternoon I'll go through the #s in more detail to confirm that everything looks right, but I just wanted to give you something to work on for now.

2023-04-05 17:24 UTC, Laura-Danielle commented on api/src/opentrons/config/pipette_config.py
> +    default_blow_out_volume: float
You shouldn't need to edit `pipette_config.py` since we're gonna be porting over all the pips to be using `ot3_pipette_config.py` in the next two weeks or so.

2023-04-05 17:24 UTC, Laura-Danielle commented on shared-data/pipette/definitions/1/pipetteModelSpecs.json
> +    "quirks",
Let's also not add this value to pipette model specs

2023-04-05 17:24 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/general/eight_channel/p1000/3_0.json
> +  "displayName": "Flex 8-Channel 1000 \u03bcL",
typo in display name here

2023-04-05 17:24 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/general/eight_channel/p1000/3_3.json
> +  "displayName": "Flex 8-Channel 1000 \u03bcL",
typo here too

2023-04-05 17:24 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/general/eight_channel/p50/3_0.json
> +  "displayName": "Flex 8-Channel 50 \u03bcL",
typo here

2023-04-05 17:24 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/general/eight_channel/p50/3_3.json
> +  "displayName": "Flex 8-Channel 50 \u03bcL",
typo here

2023-04-05 17:24 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/general/ninety_six_channel/p1000/3_0.json
> +  "displayName": "Flex 96-Channel 1000 \u03bcL",
typo here

2023-04-05 17:24 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/general/ninety_six_channel/p1000/3_3.json
> +  "displayName": "Flex 96-Channel 1000 \u03bcL",
typo here

2023-04-05 17:24 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/general/single_channel/p1000/3_0.json
> +  "displayName": "Flex 1-Channel 1000 \u03bcL",
typo here

2023-04-05 17:24 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/general/single_channel/p1000/3_3.json
> +  "displayName": "Flex 1-Channel 1000 \u03bcL",
typo here

2023-04-05 17:24 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/general/single_channel/p50/3_0.json
> +  "displayName": "Flex 1-Channel 50 \u03bcL",
typo here

2023-04-05 17:24 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/general/single_channel/p50/3_3.json
> +  "displayName": "Flex 1-Channel 50 \u03bcL",
typo here

2023-04-05 17:24 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/liquid/eight_channel/p300/1_3.json
> +  "defaultBlowoutVolume": 29.452
This key is gonna vary from tip size to tip size so it needs to be nested in the `supportTips ->`<tip_size>` ` config.

2023-04-05 17:24 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/scripts/build_json_script.py
> +    for pipette_gen in range(1, 4):  # gen 1, gen 2, gen 3
So this part of the function is for "new" pip values right? It should have its own separate function.

We also talked about adding this into the excel sheet that can be passed to this script. We should make sure that functionality works.

2023-04-10 16:57 UTC, sfoster1 reviewed
Those problems with the display names aren't typos they're bugs in the script - that's the unicode code point notation for https://www.compart.com/en/unicode/U+03BC . something somewhere isn't doing unicode output correct, possibly outputting to ascii instead of utf-8, with the error handling set to [namereplace](https://docs.python.org/3/library/codecs.html#codec-base-classes). where exactly this is... well that'll be fun.

2023-04-10 16:57 UTC, sfoster1 commented on shared-data/pipette/definitions/2/general/eight_channel/p1000/3_0.json
> +  "displayName": "Flex 8-Channel 1000 \u03bcL",
This isn't a typo this is a bug in the script

2023-04-12 12:13 UTC, Laura-Danielle requested changes
In general looks good, but:

1. You need to figure out why the display name is still messed up for all the v3+ models. Did you possibly use the commandline input at one point specifically for the v3 models? Maybe you can try to generate a fake config again using that pathway to see if the same thing happens. Regardless, you need to fix the files that are affected so the display name is not messed up.
2. The partialTipPickup configuration is an item on the general pipette configs and should stay that way.

2023-04-12 12:13 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/pipette_definition.py
> +    partial_tip_configurations: Optional[PartialTipDefinition] = Field(
This is not a liquids property.

2023-04-12 20:30 UTC, Laura-Danielle approved these changes
lgtm!

2023-04-12 21:25 UTC, merged