build(docs): generate opengraph tags on API docs
OpenTrons/opentrons-api pull request #12406
Opened 2023-03-31 22:38 UTC by ecormany

# Overview

Uses https://github.com/wpilibsuite/sphinxext-opengraph to add Opengraph tags to PAPI docs pages.

# Test Plan

Check sandbox output on opengraph.xyz

# Changelog

WIP

# Review requests

# Risk assessment

low-ish, affects docs build in CI

2023-04-03 19:30 UTC, jwwojak commented on api/docs/v2/index.rst
@ecormany My comment is less about the Opengraph changes, which I'm 100% for, and more about the summary text.

If we're going to add these tags, is there an opportunity to review, reconsider, and revise the short text summary for the index page? I generally get a little uneasy by text that promises things like "makes it easy" (or fun, or simple, etc.) to do something. Perhaps we could consider a wee rewrite here. 2 suggestions for consideration:

- The Opentrons Python Protocol API is a Python framework that helps you write automated biology lab protocols that use Opentrons robots and hardware modules.

- The Opentrons Python Protocol API helps you write automated biology lab protocols that use Opentrons robots and hardware modules.

Word count:
- Original: 26 words
- 1st option: 24 words
- 2nd option: 19 words

The 2nd option removes the "Python" repetition. If the summary includes "Opentrons Python Protocol API" the reader already knows this is a Python API. Calling it "a Python framework" is extra that the summary doesn't need.

2023-04-03 19:34 UTC, jwwojak commented on api/docs/v2/new_complex_commands.rst
Similar to my comments about the index.rst summary, I'd suggest hedging in this summary by adding "help". My italics just to make identifiable in text.

- Complex liquid-handling commands for Opentrons robots _helps_ make it easier to handle large groups of . . . "

2023-04-03 19:36 UTC, jwwojak commented on api/docs/v2/new_protocol_api.rst
Instead of "make up" could we replace that with "comprise"? 

Though this replaces simple words with one that might be considered more complex.

2023-04-03 19:38 UTC, jwwojak commented on api/docs/v2/robot_position.rst
Another description/summary revision idea:

- How to define positions within an Opentrons robot and alter its speed and trajectory.

2023-04-03 19:41 UTC, jwwojak commented on api/docs/v2/tutorial.rst
Perhaps another opportunity for a description revision?

- A guide to creating a Python protocol and running it on an Opentrons robot.
- A guide to creating a new Python protocol and running it on an Opentrons robot.

You could also insert "file" after "protocol" in each suggestion, but the text works without it too.

2023-04-03 19:45 UTC, jwwojak commented on api/docs/v2/versioning.rst
A final set of revision suggestions for this description:

- How to understand and choose the right Python API version for your protocol.
- Choose the right Python API version for your protocol.
- Understand and choose the right Python API version for your protocol.

2023-04-04 13:54 UTC, sfoster1 requested changes
Couple technical changes we should do before deploy

2023-04-04 13:54 UTC, sfoster1 commented on api/Pipfile
> +sphinxext-opengraph = "*"
don't want this here, just in the `dev-packages`. This is for two reasons:
- First, we keep the "production" package requirements to those packages required for core functionality of the system; generating docs is a dev task, whose dependencies live in `dev-packages`
- Second, since `pipenv` doesn't actually generate package metadata when building a wheel, `packages` are all specified in setup.py and pipenv installs them when doing the local install of the package

2023-04-04 13:54 UTC, sfoster1 commented on api/Pipfile
> +sphinxext-opengraph = "*"
Should be able to fix by removing these three lines and rerunning `pipenv lock`

2023-04-04 13:54 UTC, sfoster1 commented on api/docs/v2/conf.py
> +ogp_image = "https://opentrons.com/wp-content/uploads/2023/02/PythonAPI.png"
can we drop this image in the media section here so it's hosted on `docs.opentrons.com`? This link should work because it's from subdomain to domain, but depending on another site's CMS content gives me the willies

2023-04-05 20:50 UTC, ecormany commented on api/Pipfile
> +sphinxext-opengraph = "*"
honestly don't even know where this came from…i don't think i added these lines by hand. will try your suggestion.

2023-04-05 21:07 UTC, ecormany commented on api/docs/v2/conf.py
> +ogp_image = "https://opentrons.com/wp-content/uploads/2023/02/PythonAPI.png"
put it in `static` since items in `img` only get built if there's a reference to them on a docs page.

2023-04-06 15:59 UTC, ecormany commented on api/docs/v2/conf.py
> +ogp_image = "https://opentrons.com/wp-content/uploads/2023/02/PythonAPI.png"
…and manually added it to the target location in AWS so we can test before this is merged 🥷 

it will be handled by the build+deploy process in the future.

2023-04-06 17:43 UTC, ecormany commented on api/docs/v2/index.rst
`easy` has been on this page since its inception (2019) so I think we're good to leave it for now!

2023-04-06 17:45 UTC, ecormany commented on api/docs/v2/new_complex_commands.rst
shortening even further.

2023-04-10 13:59 UTC, sfoster1 approved these changes
Looks good to me!

2023-04-10 14:03 UTC, merged