fix(api): Slow down prepare-for-aspirate following a blowout
OpenTrons/opentrons-api pull request #12412
Opened 2023-04-02 18:28 UTC by andySigler

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-04-04 13:48 UTC, sfoster1 requested changes
This is a good refactor and functionality change, but part of what makes it a good refactor is that it isolates some behavior in a more testable way - and that means we need to refactor the tests around it.

Before merging this PR, we should
- Separate out the part of the home tests that move the plunger to the bottom, and replace them in the home tests with checking that `_move_to_plunger_bottom` was called
- Ditto for other tests that move the plunger to the bottom
- Move those tests into tests for `_move_to_plunger_bottom` that cover the (nice and well-written!) contexts in which `_move_to_plunger_bottom` can be called

2023-05-03 19:28 UTC, Laura-Danielle approved these changes
Two clarifying questions around the tests, otherwise looks good to me.

2023-05-03 19:28 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/test_ot3_api.py
> +    pip_ax = OT3Axis.of_main_tool_actuator(mount)
should we have a test that aspirates and then calls `home_plunger` verifying that it raises an error?

2023-05-03 19:28 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/test_ot3_api.py
> +    speed_aspirate = ot3_hardware._pipette_handler.plunger_speed(
I'm confused as to what specific test case we're checking here, can you add a little more description? I thought if we had liquid in the tip then we would throw an error.

2023-05-19 13:50 UTC, Laura-Danielle approved these changes
updates lgtm.

2023-05-19 15:42 UTC, sfoster1 approved these changes
Okay, this looks good to me, but let's get a more descriptive PR description and thus commit message for when this is merged.

2023-05-19 17:25 UTC, merged