refactor(app_odd): copy update throughout Opentrons Flex pipette flows
OpenTrons/opentrons-api pull request #12420
Opened 2023-04-03 18:13 UTC by jerader

closes RLIQ-329

# Overview

Copy updates throughout the OT3 pipette flows, should now be up to date with design.

# Test Plan

- look through the flows/i18n file and make sure the string match what is in figma. Note: I tried to start using the new `i18n` format function when changing the values, that is why there is no capitalization on the majority of the strings I touched. There are a lot of copy updates so please make sure I didn't miss any!

# Changelog

- change a bunch of the i18n key values throughout the `PipetteWizardFlow` work
- updated the affected tests
- used the i18n format function, replacing `capitalize` from lodash in some areas as well as removing the capitalize CSS attribute
- also added an optional `recalibrate` prop and onto the `PipetteWizardFlow` type so we can tell the difference between `recalibrate` and `calibrate`

# Review requests

- see test plan

# Risk assessment

low

2023-04-03 19:17 UTC, ecormany requested changes
A bunch of little fixes: a couple typos (one my fault!), but mostly about using the new capitalization framework. This is a really good test case to make sure that we get it right!

2023-04-03 19:17 UTC, ecormany commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "remove_labware_to_get_started": "<block>To get started, remove labware from the deck and clean up the working area to make calibration easier. Also gather the needed equipment shown to the right.<
my bad, this typo was in Figma. fixed there too.
```suggestion
  "remove_labware_to_get_started": "<block>To get started, remove labware from the deck and clean up the working area to make calibration easier. Also gather the needed equipment shown to the right.</block><block>The calibration probe is included with the robot and should be stored on the front pillar of the robot.</block>",
```

2023-04-03 19:17 UTC, ecormany commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "install_probe": "Take the calibration probe from its storage location. Make sure its latch is in the unlocked (straight) position. Press the probe firmly onto the pipette nozzle and then lock the
probe design has changed so this text will change in the future, but OK for this PR.

2023-04-03 19:17 UTC, ecormany commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "remove_probe": "unlatch the calibration probe, remove it from the  nozzle, and return it to its storage location.",
```suggestion
  "remove_probe": "unlatch the calibration probe, remove it from the nozzle, and return it to its storage location.",
```
double space, was probably left in due to a sneaky soft wrap

2023-04-03 19:17 UTC, ecormany commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "remove_labware": "<block>To get started, remove labware from the deck and clean up the working area to make attachment and calibration easier. Also gather the needed equipment shown to the right.<
same as above, `the front pillar`

2023-04-03 19:17 UTC, ecormany commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "get_started_detach": "<block>To get started, remove labware from the deck and clean up the working area to make calibration easier. Also gather the needed equipment shown to the right.</block>",
looks like this should still be `detachment` given the key

2023-04-03 19:17 UTC, ecormany commented on app/src/organisms/PipetteWizardFlows/__tests__/BeforeBeginning.test.tsx
> +        'The calibration probe is included with the robot and should be stored on front pillar of the robot.'
update test to match typo fix

2023-04-03 19:17 UTC, ecormany commented on app/src/organisms/PipetteWizardFlows/constants.ts
> +    'Provided with the robot. Using another size can strip the instruments’s screws.',
```suggestion
    'Provided with the robot. Using another size can strip the instrument's screws.',
```
This typo shows up a lot in tests. Also, do we want straight or curly quote in the string?

2023-04-03 19:17 UTC, ecormany commented on app/src/organisms/PipetteWizardFlows/__tests__/DetachPipette.test.tsx
> +    getByText('Loosen screws and detach flex 1-channel 1000 μl')
should be testing for `Flex 1-Channel 1000 μL` to make sure case is properly transformed

here and a few more instances below

2023-04-03 19:17 UTC, ecormany commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "connect_96_channel": "connect and attach 96 channel pipette",
should either be `96-channel pipette` (describing the type of pipette) or `96-Channel Pipette` (giving product name). hyphen either way.

2023-04-03 19:17 UTC, ecormany commented on app/src/organisms/PipetteWizardFlows/__tests__/Results.test.tsx
> +    getByText('Flex 1-channel 1000 μl successfully recalibrated')
capitalization: `Flex 1-Channel 1000 μL` here and several other times in this test file

2023-04-04 13:14 UTC, jerader commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "remove_probe": "unlatch the calibration probe, remove it from the  nozzle, and return it to its storage location.",
omg i was trying to figure out why when testing this string, it kept failing and it is because i missed that there was the double space. thanks!

2023-04-04 13:24 UTC, jerader commented on app/src/organisms/PipetteWizardFlows/constants.ts
> +    'Provided with the robot. Using another size can strip the instruments’s screws.',
We use `’` instead of `'` for apostrophes in strings because we using the `'` around the string. There are probably more reasons why we use it. I think visually, they look the same in the UI since no one from design has mentioned it. If we want to make the switch over going over, I guess we _could_ but thats a conversation to be had with the team :D

2023-04-04 13:34 UTC, jerader commented on app/src/organisms/PipetteWizardFlows/__tests__/DetachPipette.test.tsx
> +    getByText('Loosen screws and detach flex 1-channel 1000 μl')
Yeah, i guess we can't use the format function here because this isn't a true capitalize or titleCase since we need the pipette name capitalized but not `screws` and `detach`

2023-04-04 13:41 UTC, ecormany commented on app/src/organisms/PipetteWizardFlows/__tests__/DetachPipette.test.tsx
> +    getByText('Loosen screws and detach flex 1-channel 1000 μl')
hmm, do those functions downcase input? i would expect:
`do the thing on Flex` -> sentence case -> `Do the thing on Flex`

2023-04-04 13:43 UTC, jerader commented on app/src/organisms/PipetteWizardFlows/__tests__/DetachPipette.test.tsx
> +    getByText('Loosen screws and detach flex 1-channel 1000 μl')
yeah, it does downcase input

2023-04-04 13:54 UTC, jerader commented on app/src/organisms/PipetteWizardFlows/__tests__/DetachPipette.test.tsx
> +    getByText('Loosen screws and detach flex 1-channel 1000 μl')
I am gonna look into a function that keeps the input as is, if not, i will try to make it. I don't like the idea of only being able to use the format function for some strings.

2023-04-04 15:21 UTC, ecormany commented on app/src/organisms/PipetteWizardFlows/__tests__/DetachPipette.test.tsx
> +    getByText('Loosen screws and detach flex 1-channel 1000 μl')
or do [extremely pseudo-code i don't know typescript lol]: `transform('some static string') + '{dynamicString}'` instead of `transform('some string with a {dynamicPiece}')`

2023-04-05 16:09 UTC, jerader commented on app/src/organisms/PipetteWizardFlows/__tests__/DetachPipette.test.tsx
> +    getByText('Loosen screws and detach flex 1-channel 1000 μl')
Yeah, I put the 1st half of the string `Loosen screws and detach` into the formatter and then the 2nd half, I left alone. This works for now, maybe in the future we can create a util that does all the work for us, esp if the pipette name is in the middle of the string or if there were multiple constants in the string.

2023-04-05 17:20 UTC, ecormany approved these changes
double check the one instance of `detachment` vs `calibration`, otherwise this all looks good.

2023-04-05 17:20 UTC, ecormany commented on shared-data/js/titleCase.ts
> +const SMALL_WORDS = /\b(?:an?d?|a[st]|because|but|by|en|for|i[fn]|neither|nor|o[fnr]|only|over|per|μL|so|some|tha[tn]|the|to|up|upon|vs?\.?|versus|via|when|with|without|yet)\b/i
yes! perfect way to handle this.

2023-04-05 17:20 UTC, ecormany commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "detach_z_axis_screw_again": "detach the z-axis screw before attaching the 96-Channel pipette.",
i think this line could be reverted, though if tests are passing it won't affect the output in this case.

2023-04-05 17:20 UTC, ecormany commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "get_started_detach": "<block>To get started, remove labware from the deck and clean up the working area to make calibration easier. Also gather the needed equipment shown to the right.</block>",
bump

2023-04-05 17:44 UTC, jerader commented on app/src/assets/localization/en/pipette_wizard_flows.json
> +  "get_started_detach": "<block>To get started, remove labware from the deck and clean up the working area to make calibration easier. Also gather the needed equipment shown to the right.</block>",
whoops, good catch! def a copy and paste error on my part.

2023-04-06 15:10 UTC, smb2268 requested changes
One small change is needed for the `recalibration` variable, but otherwise this looks great!

2023-04-06 15:10 UTC, smb2268 commented on app/src/organisms/PipetteWizardFlows/getPipetteWizardSteps.ts
> +          recalibrate: true,
I don't think we can assume that anytime a calibration flow is launched independently it's a recalibration - the user could exit between attach and calibration or attach the pipette without going through the flow. Instead, let's check for calibration data for the attached pipette to set this boolean

2023-04-06 16:20 UTC, smb2268 commented on app/src/organisms/PipetteWizardFlows/index.tsx
> +          currentStep.recalibrate != null && currentStep.recalibrate === true
this is a redundant check -- currentStep.recalibrate === true is sufficient!

2023-04-06 16:20 UTC, smb2268 commented on app/src/organisms/PipetteWizardFlows/getPipetteWizardSteps.ts
> +  const pipCalibrationsByMount = useAttachedPipetteCalibrations()
you can't call a hook in a util so let's move this portion of the logic out of `getPipetteWizardSteps` -- since it's only used in `Results` maybe we should move it there and take it out of the step data? If you think it should be a part of the steps, you can move the hook call to `index` and pass the result into this function as a prop.

2023-04-06 16:34 UTC, smb2268 approved these changes
looks good!! thanks for updating

2023-04-06 20:45 UTC, merged