refactor(api): remove `fail_on_not_homed` param in OT-3
OpenTrons/opentrons-api pull request #12445
Opened 2023-04-07 01:58 UTC by ahiuchingau

# Overview
Now that we have encoders on the OT-3, we can find out whether or each axis has been homed by checking the encoder status. With this additional information, the hardware control API can figure out when we need to raise a MustHomeError without having to rely on the `fail_on_not_homed` param.

Theoretically, each axis equipped with an encoder should only need to home _once_ between power cycles. This means we can do the following on the OT-3 safely during:

### A. a movement command (`move_to`, `move_rel`)
After powering up, an axis MUST first home to prepare for motion. If the hardware controller encounters a move command before any of the axes has a chance to home, instead of blocking the move, the robot can just home itself and proceed with the move. 

However, if the robot has homed before but the motor position is no longer accurate, we should raise an MustHomeError and block the move because it can cause a crash. In order to proceed, user intervention is required to determine the course of actions.

### B. a position-retrieval command (`encoder_position`, `gantry_position`)
We should always raise the daunting MustHomeError if (1) the robot has not been homed, or (2) if the positions are not accurate. In both cases, there's nothing worth reporting and we just should let the user know. 

# Review Request
Am I missing something? Could this cause any catastrophic failure that I didn't think of?

2023-04-07 20:23 UTC, Laura-Danielle approved these changes
One tiny little logic change request. Otherwise looks good to me!

2023-04-07 20:23 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> -        # TODO(mc, 2021-11-15): combine with `refresh` for more reliable
Is this comment not still relevant?

2023-04-07 20:23 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +            self._current_position and self._backend.check_motor_status(position_axes)
```suggestion
            self._current_position or self._backend.check_motor_status(position_axes)
```

2023-04-07 20:23 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +            self._backend.check_motor_status(position_axes) and self._encoder_position
```suggestion
            self._backend.check_motor_status(position_axes) or self._encoder_position
```

2023-04-10 13:57 UTC, sfoster1 requested changes
Agree generally, need to remove a print though

2023-04-10 13:57 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +            self._current_position and self._backend.check_motor_status(position_axes)
Wait I disagree with this.
With the `and`, what this is saying is "i have to have my internal knowledge of the position (for planning) and that position has to be valid"; and that's true, because 
- if the position's valid but you don't know it, then there's not much point
- if you know the position but it's not valid, then it's not valid

2023-04-10 13:57 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +            self._backend.check_motor_status(position_axes) and self._encoder_position
same as above here

2023-04-10 13:57 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/test_ot3_api.py
> +    print(ot3_hardware._current_position)
missed this one

2023-04-10 15:27 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +            self._current_position and self._backend.check_motor_status(position_axes)
Yeah agree. I was reading the statement as `if not self._current position and self._backend.check_motor_status(position_axes)` rather than `if not (self._current_position and self._backend.check_motor_status(position_axes))`.

@ahiuchingau Can we make this a little clearer by doing something like:

`valid_motor_position = self._current_position and self._backend.check_motor_status(position_axes)`
`if not valid_motor_position`

2023-04-10 16:26 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/ot3api.py
> -        # TODO(mc, 2021-11-15): combine with `refresh` for more reliable
Not relevant anymore because it was referring to the `fail_on_not_homed` param

2023-04-10 18:08 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/ot3api.py
> +        position_axes = [OT3Axis.X, OT3Axis.Y, z_ax, tool_ax]
This doesn't work for gripper because OT3Axis.G would never report position ok

2023-04-10 18:52 UTC, Laura-Danielle approved these changes
ty!

2023-04-17 17:05 UTC, sfoster1 approved these changes
Looks good to me!

2023-04-17 17:07 UTC, merged