chore(build): Make sure machine is reachable before attempting to scp files.
OpenTrons/opentrons-api pull request #12449
Opened 2023-04-07 21:30 UTC by vegano1

# Overview

Fixes misleading message printed when the push command fails because of a network error.

# Test Plan

- [ ] Make sure `make push-ot3 host=<ip-addr>` still works for OT3
- [ ] Make sure `make push host=<ip-addr>` still works for OT2
- [ ] Make sure make push still works on Windows, Mac, and Linux
- [ ] Make sure we print "Machine <ip-addr> is unreachable" if robot is offline.

# Changelog

- add assert-online function to check if the machine responds to ping

# Review requests

- Make sure this works for you

# Risk assessment
Low

2023-04-10 14:32 UTC, SyntaxColoring commented on scripts/push.mk
> +$(assert-online)
Should we use `$(call assert-online,$(1))` instead of just `$(assert-online)` to decouple the positional argument order between `assert-online` and `push-python-package`?

2023-04-10 14:32 UTC, SyntaxColoring commented on scripts/push.mk
> +
I think we should try to avoid using `ping` for this, for a few reasons.

1. Anecdotally, on the office Wi-Fi, I've seen pings to robots take more than one second, and I've seen ping packet loss. When SSH connects, TCP retransmissions normally paper over those transient connection problems. I worry that doing this ping check up front will subvert that, and make more connections fail than necessary.
2. This can't address the common cases of wrong `ssh` credentials, mismatched host keys, or unsupported encryption algorithms.
3. This introduces a dependency on a Unixy `ping` and `/dev/null`. I'm fine with this, but does anybody depend on running these Makefiles on Windows without WSL? Maybe the factory?

Is there a path that doesn't rely on a separate `ping` command? For example, could we check exit codes more specifically in `is-ot3`? [ssh](https://linux.die.net/man/1/ssh#:~:text=ssh%20exits%20with%20the%20exit%20status%20of%20the%20remote%20command%20or%20with%20255%20if%20an%20error%20occurred.) and [systemctl](https://www.man7.org/linux/man-pages/man1/systemctl.1.html#EXIT_STATUS) both document their possible exit codes, so it should be possible for that command to distinguish an `ssh` connection error from a `systemctl` "service not found" error.

2023-04-10 14:47 UTC, sfoster1 requested changes
I think we should either remove the extra ping output handling or switch this over to an ssh echo to check that auth configuration is correct, and kind of prefer the second one.

2023-04-10 14:47 UTC, sfoster1 commented on scripts/push.mk
> +
Yeah for my money this should be like `$(if $(shell ssh $(1) echo "ok"),,$(error Could not reach machine))`

2023-04-10 14:47 UTC, sfoster1 commented on scripts/push.mk
> +$(assert-online)
Yeah in general this is a good idea

2023-04-10 14:47 UTC, sfoster1 commented on scripts/push.mk
> +
However you could also get rid of the issue by removing the shell redirect and pipe (e.g. just `ping -t 1 $(1)`) which I think should work on windows.

2023-04-10 17:51 UTC, vegano1 commented
@sfoster1 
@SyntaxColoring 

Im using ssh instead of ping is a much better approach, thank you for the feedback!
ssh lets us provide how long to wait for a connection + how many times to attempt a connection.
Which speeds up the failure case where the device is offline or has an invalid key, etc.

I'm also using the `error` logging function in the failure case which not only prints a message,
 but also exits the program without needing to explicitly exit the program.

2023-04-10 22:53 UTC, SyntaxColoring commented
Tested this:

* I'm getting the intended error now when I do `make push host=doesnotexist.local` or `make push-ot3 host=doesnotexist.local`
* I'm getting the intended error when I do `make push` to an OT-3



However, if I do `make push-ot3` to an OT-2, I get:

```
root@bitter-wood.local: Permission denied (publickey).
Makefile:179: *** Machine bitter-wood.local might be offline.  Stop.
```

Which I guess makes sense. It's probably not providing any key because it thinks it's connecting to an OT-3, which doesn't need one. Hmmm. I'm not sure what to do about this. Go back to `ping`? Supply an OT-2 key even to hosts that are claimed to be OT-3s? Grep on the stderr string? Just tweak the error message to mention this as a possible failure mode?

2023-04-12 13:43 UTC, sfoster1 commented on scripts/push.mk
> +$(assert-online)
@vegano1 this conversation isn't resolved, I think. What we're talking about here is using the [call function](https://www.gnu.org/software/make/manual/html_node/Call-Function.html) which lets you define `assert-online`'s positional arguments directly, rather than having it inherit them from the context of the location in which it's expanded. This is a really good idea because you have to be explicit about things. For instance, this would look like

```
# argument 1 is the host
# argument 2 is ...
define assert-online
$(if $(shell ssh...
endef
```
and then
```
define push-python-package
$(call assert-online,$(1),$(2),$(3))
...
```
which makes it a little easier to use assert-online in some new context.

2023-08-21 20:35 UTC, closed without merging