draft - action for HTTP API reference
OpenTrons/opentrons-api pull request #12480
Opened 2023-04-12 19:57 UTC by ecormany

# Overview

The goal of this PR is to generate the same Redoc HTTP API reference as is accessible on robots, and then deploy it online on the docs.opentrons.com subdomain.

# Test Plan

TK

# Changelog

- Python file to generate openapi.json with FastAPI
- `make docs` command pointing to that .py file
- github action to run the `make` command and deploy to AWS sandbox 🚧 still broken

# Review requests

Am I going about this at all the right way? I think so but I need a CI expert.

# Risk assessment

Low to mid. Adds a new CI action that will be triggered on any changes within `robot-server/`

2023-04-13 13:42 UTC, sfoster1 requested changes
This is looking really close to what we want it to be eventually, but I think we need to specify what docs.opentrons.com wants to look like a little more closely, because this will drop the http api stuff in the root of that site, and we probably want it at like docs.opentrons.com/http or something right?

2023-04-13 13:42 UTC, sfoster1 commented on .github/workflows/http-docs-build.yaml
> +      - 'robot-server/**'
should this include the python api docs aka `- 'api/**'`

2023-04-13 13:42 UTC, sfoster1 commented on .github/workflows/http-docs-build.yaml
> +          destPrefix: ${{ env.OT_BRANCH }}
What URL do you want the http docs to end up at on docs.opentrons.com?

2023-04-13 13:49 UTC, sfoster1 commented on robot-server/robot_server/spec_generator.py
> +
```suggestion
os.makedirs('docs/build', exist_ok=True)
```

2023-04-13 13:49 UTC, sfoster1 commented on robot-server/robot_server/spec_generator.py
> +import json
```suggestion
import json
import os
```

2023-04-13 17:44 UTC, ecormany commented on .github/workflows/http-docs-build.yaml
> +      - 'robot-server/**'
i don't think so. the notion is that the sphinx-based action for PAPI will build and sync those docs, and this redoc-based action for HTTP will also build and sync. since they wrap everything up inside of subdirectories, they shouldn't clobber each other.

2023-04-17 17:35 UTC, sfoster1 approved these changes
Looks good to me, and it seems like a good idea, and it works - let's do it!

2023-04-17 20:48 UTC, merged