add changes to ot2 code
OpenTrons/opentrons-api pull request #12534
Opened 2023-04-20 21:39 UTC by caila-marashaj

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-04-24 16:55 UTC, sfoster1 requested changes
Let's make the name of the argument consistent and then we definitely need some tests with volumes set, on both ot2 and ot3, checking that
- we appropriately raise the error if you blow out too much
- spot checking, maybe with `hypothesis`, intermediate values

2023-04-24 16:55 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        self, mount: top_types.Mount, microliters: Optional[float] = None
```suggestion
        self, mount: top_types.Mount, volume: Optional[float] = None
```

Keeps it consistent with other functions that take volumes

2023-04-24 20:47 UTC, Laura-Danielle reviewed
Agree with all of seth's comments. Have a few additional comments as well. In general, looking good!

2023-04-24 20:47 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +        blowout_spec = self.plan_check_blow_out(mount, microliters)
the `plan_check_blow_out` should be calculating the distance required to move and throwing an error if the blow out distance calculated is _greater_ than the max blowout position.

2023-04-24 20:47 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +        if blowout_distance < max_blowout_pos:
`if blowout_distance > max_blowout_pos` right?

2023-04-24 20:47 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/ot2/pipette_handler.py
> +    def plan_check_blow_out(self, mount, microliters: Optional[float] = None):  # type: ignore[no-untyped-def]
should also be volume.

2023-04-24 20:47 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/ot2/pipette_handler.py
> +        if microliters:
can you put a TODO about this following the flex logic once the ticket I linked you before is done?

2023-04-24 20:47 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/dev_types.py
> +    # defaultBlowOutVolume: float
Accidentally commented out? Do these need to be moved somewhere else?

2023-04-24 20:56 UTC, SyntaxColoring commented on api/src/opentrons/hardware_control/instruments/ot2/pipette_handler.py
> +        if microliters:
Should this be `if microliters is None`? Right now, it looks like this will use the default value if you specify `microliters=0`, which I would find surprising.

2023-04-24 20:56 UTC, SyntaxColoring commented on api/src/opentrons/hardware_control/instruments/ot3/pipette_handler.py
> +            or self.get_attached_instrument(mount)["default_blow_out_volume"]
Same deal with `0` being just as falsey as `None`.

2023-05-01 15:05 UTC, sfoster1 requested changes
Looking good! Agree with laura and max, got this last bit of commented code still

2023-05-01 15:05 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/test_ot3_api.py
> +# async def mock_pick_up_tip(ot3_hardware: ThreadManager[OT3API]) -> Iterator[AsyncMock]:
need to uncomment

2023-05-01 15:05 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/test_ot3_api.py
> +        load_configs: Dict[str, Union[int, str, Tuple[int, int]]],
might be a little more readable if we make these dataclasses or something

2023-05-03 14:11 UTC, Laura-Danielle requested changes
couple small changes, but this is looking really good. Nice job w the hypothesis test.

2023-05-03 14:11 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +        blowout_spec = self.plan_check_blow_out(mount, microliters)
This should be 'volume' not 'microliters'

2023-05-03 14:11 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +        self, mount: top_types.Mount, microliters: Optional[float] = None
This should be 'volume' not 'microliters'

2023-05-03 14:11 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/protocols/liquid_handler.py
> +    async def blow_out(self, mount: Mount, microliters: Optional[float] = None) -> None:
this should be 'volume' not 'microliters'

2023-05-03 14:11 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/test_ot3_api.py
> +@given(blowout_volume=strategies.floats(min_value=1, max_value=200))
Curious how much this slows down this test suite. I know that using strategies.<whatever> usually generates around 100 elements by default.

We should specify `@settings(max_examples=10)` or something similar so that we don't re-run this test so many times. If there are certain edge cases you definitely want to test, then you can specify with: `@example(<value>)`.

2023-05-03 18:18 UTC, sfoster1 approved these changes
This is pretty awesome, I love to have this kind of testing in hardware.

2023-05-03 18:18 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        # start at the bottom position and move additional distance det. by plan_check_blow_out
nit: just use two lines instead of abbreviating

2023-05-03 18:18 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +                f"Blow out distance exceeds plunger position limit\n blowout dist = {blowout_distance}"
nit: don't put newline literals in here

2023-05-03 19:11 UTC, Laura-Danielle approved these changes
lgtm

2023-05-04 14:18 UTC, SyntaxColoring commented on api/Pipfile
> +hypothesis = "~=6.36.1"
Oooh, very excited to try this.

Note that the version specifier `~=6.36.1` pins us to the `.36` minor version of Hypothesis, [equivalent to](https://peps.python.org/pep-0440/#compatible-release) `>=6.36.1, <6.37`. (I hate that `~=` works like this. It's really surprising and annoying.)

Since Hypothesis [uses semver](https://hypothesis.readthedocs.io/en/latest/supported.html), I think we should pin to the major version instead, by writing either of these:

* `~=6.36`
* `>=6.36,<7` (my personal soft preference because `~=` is confusing)

2023-05-04 17:09 UTC, merged