Protocol designer OT-3 development
OpenTrons/opentrons-api pull request #12540
Opened 2023-04-21 10:21 UTC by akshay-dighe

# Overview
•	Landing page added with three buttons.
•	Implement pipette and tip rack selection based on the Figma design.
•	Implement nav pill form according to the Figma design.
•	Create new routes based on the Figma design.
•	Note: this is ongoing development

Implementation details
•	Implement routing for the new routes using React Router.
•	OT-2 Button navigates previous OT-2 platform.
•	Create appropriate route components and configure routing paths.
•	Added new components for form data collection.
•	Added new components for pipette and tip rack selection.
•	For the nav pill form state management Formik state management and props
•	Added new components for the nav pill form.
•	Showing dynamic module selection (not added gripper and trash chute)

# Test Plan
Working on JSON creations, right now unable to test.

# Changelog
•	Implement routing for the new routes using React Router.
•	OT-2 Button navigates previous OT-2 platform.
•	Create appropriate route components and configure routing paths.
•	Added new components for form data collection.
•	Added new components for pipette and tip rack selection.
•	For the nav pill form state management Formik state management and props
•	Added new components for the nav pill form.
•	Showing dynamic module selection (not added gripper and trash chute)

# Review requests

# Risk assessment
Medium:  form validation/module selection development is ongoing and OT3 JSON creation not completed yet.

2023-05-01 15:24 UTC, jerader requested changes
This is off to a good start. Here are a summary of my comments:

1. a handful of props and return types are typed as `any`, since we are using typescript, lets avoid typing things as `any` as much as possible.
2. I see that there are some const and component files that are copied over from `@opentrons/components` directory. I think I contradicted myself when I mentioned in the past to not import anything from `app` directory. `components` directory is meant to be a shared directory for all of our applications. So files such as `colors.ts` and `typography.ts` can be deleted and you can use the import from `@opentrons/components` instead.
3. I am still looking into the check-js errors, I think it is related to dependencies since you added `react-router-dom`. I will get back to you on this.
4. Are you planning to write unit tests for the components in jest? It would be great if we could do so.
5. it looks like some of your files don't match our `prettier` formatting. There is a `prettier` extension you can download on VSCode. When you run `make lint-js`, at the end, it gives you info on which files don't match `prettier`.

2023-05-01 15:24 UTC, jerader commented on protocol-designer/src/flex-components/LandingPage.tsx
> +interface Props {
Maybe rename this to `NavDataProps` so it is easier to tell what the Props are for.

```suggestion
interface NavDataProps {
```

2023-05-01 15:24 UTC, jerader commented on protocol-designer/src/flex-components/LandingPage.tsx
> +function ButtonGroup(props: any): any {
lets avoid typing things as `any` since we are using typescript. `props` should be `Prop[]` up above on line 8 (or `NaveDataProps[]` if you change it). The return type should be `JSX.Element`

2023-05-01 15:24 UTC, jerader commented on protocol-designer/src/flex-components/LandingPage.tsx
> +  return Boolean(nav)
why is nav a boolean?

2023-05-01 15:24 UTC, jerader commented on protocol-designer/src/flex-components/LandingPage.tsx
> +    ? nav.map((item: any, index: string) => {
if you add a type on line 42, the `nav` will have a type so you shouldn't have to typecast `item` and `index`. But type here should be `Prop` or `NavDataProp` if you change the name on line 8.

2023-05-01 15:24 UTC, jerader commented on protocol-designer/src/flex-components/constant/colors.ts
> +// colors fundamentals
rather than making this new file that is an exact copy of `colors.ts` in components, you should be able to import the `colors.ts` from `components` directory. So the import would look something like `import { COLORS } from '@opentrons/components'

2023-05-01 15:24 UTC, jerader commented on protocol-designer/src/flex-components/constant/typography.ts
> +// Font Sizes
same here as the `colors.ts` file. You can use the one in `components` directory and import like `import { typography } from '@opentrons/components`

2023-05-01 15:24 UTC, jerader commented on protocol-designer/src/flex-components/protocol-editor/FlexModules.tsx
> +import { ModuleDiagram } from 'protocol-designer/src/components/modules'
lets clean up these imports a bit:

```suggestion
import { ModelModuleInfo } from '../../components/EditModules'
import { ModuleDiagram } from '../../components/modules'
import type { ModuleOnDeck } from '../../step-forms/types'
```

2023-05-01 15:24 UTC, jerader commented on protocol-designer/src/flex-components/protocol-editor/FlexModules.tsx
> +  console.log('selectedModulesselectedModules', selectedModules)
forgotten console.log

```suggestion
```

2023-05-01 15:24 UTC, jerader commented on protocol-designer/src/flex-components/protocol-editor/FlexProtocolEditor.tsx
> +            {(props: any) => (
we shouldn't type `props` as `any`, I think this should be `FormikProps<values>` imported from `formik`

2023-05-01 15:24 UTC, jerader commented on protocol-designer/src/flex-components/protocol-editor/FlexProtocolName.tsx
> +function FlexProtocolNameComponent(formProps: any): JSX.Element {
lets type `formProps` as `FormikProps<values>`

2023-05-01 15:24 UTC, jerader commented on protocol-designer/src/flex-components/protocol-editor/RadioSelect.tsx
> +  pipetteType,
lets type these! And the return type should be JSX.Element

2023-05-01 15:24 UTC, jerader commented on protocol-designer/src/flex-components/protocol-editor/RadioSelect.tsx
> +export const RadioSelect = ({
can you use `RadioGroup` from `components? `import {RadioGroup} from @opentrons/components`?

2023-05-01 15:24 UTC, jerader commented on protocol-designer/src/flex-components/protocol-editor/RoundTab.tsx
> +export const RoundTabs: React.FC<RoundTabsProps> = ({
can you use `RoundTab` from `components? `import {RoundTab} from `@opentrons/components`?

2023-05-01 15:24 UTC, jerader commented on protocol-designer/src/flex-components/protocol-editor/SelectPipette.tsx
> +const checkSelectedPipette = (pipetteName: any): any => {
can we type pipetteName as `string` and return type as `boolean`?

2023-05-01 15:24 UTC, jerader commented on protocol-designer/src/flex-components/protocol-editor/SelectPipette.tsx
> +const channel96SelectionNote = (is96ChannelSelected: boolean): any => {
return type here can be `JSX.Element | null`

2023-05-01 15:24 UTC, jerader commented on protocol-designer/src/flex-components/protocol-editor/SelectPipette.tsx
> +const SelectPipetteMount = ({ propsData, pipetteName }: any): JSX.Element => {
lets type `propsData` and `PipetteName` here.

2023-05-01 15:24 UTC, jerader commented on protocol-designer/src/flex-components/protocol-editor/SelectPipette.tsx
> +  const handleNameChange = (selected: string[]): any => {
the return type here i think is `void`

2023-05-02 21:31 UTC, b-cooper requested changes
In addition to Jethary's comments about typescript usage. I've called out a few recommended changes

2023-05-02 21:31 UTC, b-cooper commented on components/src/icons/icon-data.ts
> +  'ot-flex-logo': { // todo_aditya need to take new svg with blue shade in logo
The Logo on the Landing Page should be imported as a rasterized image. (e.g.  `.png`). This Icon component is not the right place for this image.  Let's use an `img` tag

2023-05-02 21:31 UTC, b-cooper commented on protocol-designer/src/flex-components/LandingPage.tsx
The `flex-components` directory should not exist.  It's contents should be clearly named and  placed into the correct existing directories within `protocol-designer/src`. For example, all react components in the app are in `protocol-designer/src/components`. This file should be `protocol-designer/src/components/LandingPage.tsx`

2023-05-02 21:31 UTC, b-cooper commented on protocol-designer/src/flex-components/LandingPage.tsx
> +  return Boolean(nav)
This ButtonGroup component is unnecessary.  The view has three buttons with the same style (`OutlineButton`) on top of each other.  This implementation groups the first two buttons into a custom abstraction, but keeps the third button separate.  It would be much clearer to duplicate the JSX across the three instances. The `ButtonGroup` abstraction as written only obfuscates. e.g. 
```
      <OutlineButton Component="label" className={styles.flex_landing_button} onClick={() => history.push('target_route')}>
          <StyledText as="h4">
           ...
          </StyledText>
       </OutlineButton>
       ....
       <OutlineButton Component="label" className={styles.flex_landing_button}>
          <StyledText as="h4">
            {i18n.t('flex.landing_page.import_protocol')}
          </StyledText>
          <input type="file" />
       </OutlineButton>
```

2023-05-02 21:31 UTC, b-cooper commented on protocol-designer/src/flex-components/index.tsx
> +export const router = createBrowserRouter([
These routes need to be renamed to match our naming elsewhere and to accurately describe the contents of that route.  "ot-flex" -> "new-flex-file-form",  "ot-2" -> "protocol-editor". 

I would suggest going one step further and removing the usage of react-router entirely. This file creation experience is not a great match for a router. We want the `ProtocolEditor` component  to be present whenever there is a file loaded, regardless of robot type. If we keep this router approach, it will be our responsibility to manage redirecting from route to route and handling empty states, even though they should never have been accessible to a user.  

A cleaner approach here would be to remove the `react-router-dom` dependency and instead render the `<FlexForm/>` (also needs a new name e.g. CreateFlexFileForm ) as a modal on top of the `<LandingPage/>`  that is managed by local react state.  The top level react parent should then switch between rendering the `LandingPage` or `ProtocolEditor` depending only on the presence or absence of a loaded (created or imported) protocol.

2023-05-23 16:39 UTC, jerader reviewed
I left a few comments for areas that can be cleaned up. One big thing to note is to not change the `schemaV6` types. The `deckId` key that was added to the `protocolMetadata` object is unnecessary since the key already exists in the `robot` key. 

Additionally, when are you planning to write the unit tests?

2023-05-23 16:39 UTC, jerader commented on components/src/__tests__/__snapshots__/icons.test.tsx.snap
> +exports[`icons ot-flex-logo renders correctly 1`] = `
please remove this snapshot since you removed the icon you created previously.

2023-05-23 16:39 UTC, jerader commented on protocol-designer/package.json
> +    "react-router-dom": "^6.9.0",
please remove this dependency since it is no longer needed

2023-05-23 16:39 UTC, jerader commented on protocol-designer/src/components/FlexProtocolEditor/CreateFlexFileForm.tsx
> +            continueButtonName={'Cancel New Protocol'}
these strings can be added to i18n.

2023-05-23 16:39 UTC, jerader commented on protocol-designer/src/components/FlexProtocolEditor/FlexFileDetails/FlexFileDetails.tsx
> +            continueButtonName={'Cancel New Protocol'}
please add these to i18n

2023-05-23 16:39 UTC, jerader commented on yarn.lock
> +"@remix-run/router@1.5.0":
you shouldn't need any of these yarn.lock changes after you remove the `react-router-dom` dependency from the `package.json`

2023-05-23 16:39 UTC, jerader commented on shared-data/protocol/types/schemaV6/index.ts
> +    deckId?: string | null | undefined
`deckId` is already included in the value in the `robot` key down below on line 39. We shouldn't need to add it here.

2023-05-23 16:39 UTC, jerader commented on shared-data/js/types.ts
> +  deckId?: string | null
this should not be added to the `ProtocolMetadata`. `deckId` is found in the `robot` key object

2023-05-23 17:46 UTC, jerader commented on shared-data/js/types.ts
> +  | GripperModel
Let's not add this here, instead you can create a new `ModuleModel` type and add it to the `protocol-designer` directory, rather than the `shared-data` directory. You can name it something that encompasses modules and gripper such as `InstrumentModel`. The reason we don't want to add it here is because the gripper isn't like the other modules and is not placed on the deck. This `ModuleModel` type is used all over our application so the concern with adding `GripperModel` here is that it could cause some bugs or issues in our app.

2023-05-24 19:21 UTC, jerader reviewed
looking good, thanks for addressing a lot of my comments. I think the next big step is being able to successfully export a protocol that creates a json file with the Opentrons Flex robot for the robot type and the Flex pipettes.

2023-05-24 19:21 UTC, jerader commented on components/src/molecules/RoundTab.stories.tsx
> +          {'Instrument Selection'}
why did you make this change? since its a story, let's change it back to `Pipette Selection`.

2023-05-24 19:21 UTC, jerader commented on protocol-designer/src/labware-defs/utils.ts
> +  console.log('PD_DO_NOT_LIST', PD_DO_NOT_LIST)
I think you forgot to delete this console.log

2023-05-24 19:21 UTC, jerader commented on protocol-designer/src/containers/ConnectedTitleBar.tsx
> +  console.log('robotModelName', robotModelName)
another forgotten `console.log` here.

2023-05-24 19:21 UTC, jerader commented on protocol-designer/src/components/ProtocolEditor.css
> +  /* overflow-y: scroll; */
should this commented out line be deleted?

2023-05-30 19:17 UTC, jerader reviewed
I left some questions about why things are commented out. If you are going to use something in a follow up PR that is currently commented out, please leave a short comment describing what the purpose of it is, that makes it easier to review.

Additionally, the changes made to the `labware-defs/utils` affects OT2 PD. We should keep OT2 PD functionality the same. Probably the best solution is to modify the util to work for both OT2 and OT3

2023-05-30 19:17 UTC, jerader commented on protocol-designer/src/labware-defs/utils.ts
> +      return PD_DO_NOT_LIST_OT3.includes(def.parameters.loadName)
is there a reason why you're changing this to only handle OT3? With this change, it breaks the drop down options for PD OT2.

2023-05-30 19:17 UTC, jerader commented on protocol-designer/src/containers/ConnectedTitleBar.tsx
> +  //     : uiLabwareSelectors.getLabwareNicknamesById(state)
is this going to be used in follow up PRs? if so, please leave a comment indicating that.

2023-05-30 19:17 UTC, jerader commented on protocol-designer/src/configureStore.ts
> +      // action.type === 'CREATE_NEW_PROTOCOL' ||
i am assuming this is temporarily commented out?

2023-05-30 19:17 UTC, jerader commented on protocol-designer/src/configureStore.ts
> +      // action.type === 'CREATE_NEW_PROTOCOL' ||
if yes, please leave a comment indicating why

2023-05-30 19:17 UTC, jerader commented on protocol-designer/src/components/FlexProtocolEditor/typography.ts
> +// `
can this be deleted?

2023-05-30 19:17 UTC, jerader commented on protocol-designer/src/components/FlexProtocolEditor/FlexPillForm/TipRackList.tsx
> +  // }, [customTipRackProps])
can this be deleted?

2023-05-30 19:17 UTC, jerader commented on protocol-designer/src/components/FlexProtocolEditor/FlexPillForm/TipRackList.tsx
> +    // setCustomTipRackProps([...updatedCustomTipRackProps])
can this be deleted?

2023-05-31 04:47 UTC, akshay-dighe commented on protocol-designer/src/labware-defs/utils.ts
> +      return PD_DO_NOT_LIST_OT3.includes(def.parameters.loadName)
I had previously implemented the code for this functionality. However, the PD_DO_NOT_LIST_OT3 variable is no longer relevant or necessary. Therefore, in the next PR, I will keep the code in the utility function unchanged.

2023-05-31 04:49 UTC, akshay-dighe commented on protocol-designer/src/containers/ConnectedTitleBar.tsx
> +  //     : uiLabwareSelectors.getLabwareNicknamesById(state)
I had previously implemented the code for this functionality. However, the **getLabwareNicknamesByIdForOT3** is no longer relevant or necessary. Therefore, in the next PR, I will keep the code in the utility function unchanged.

2023-05-31 04:52 UTC, akshay-dighe commented on protocol-designer/src/components/FlexProtocolEditor/typography.ts
> +// `
Yes. In the next pull request, all irrelevant code or non-essential elements will be removed.

2023-05-31 04:52 UTC, akshay-dighe commented on protocol-designer/src/components/FlexProtocolEditor/FlexPillForm/TipRackList.tsx
> +  // }, [customTipRackProps])
Yes. In the next pull request, all irrelevant code or non-essential elements will be removed.

2023-05-31 04:53 UTC, akshay-dighe commented on protocol-designer/src/components/FlexProtocolEditor/FlexPillForm/TipRackList.tsx
> +    // setCustomTipRackProps([...updatedCustomTipRackProps])
Yes. In the next pull request, all irrelevant code or non-essential elements will be removed.

2023-05-31 04:55 UTC, akshay-dighe commented on protocol-designer/src/configureStore.ts
> +      // action.type === 'CREATE_NEW_PROTOCOL' ||
We are removing this specific action type from here due to the re-rendering and modification of the default state. This is causing the state to take on the robot type "OT2" instead of the intended flex protocol.

2023-05-31 04:59 UTC, akshay-dighe commented on components/src/molecules/RoundTab.stories.tsx
> +          {'Instrument Selection'}
Done.

2023-05-31 18:13 UTC, b-cooper commented on protocol-designer/src/components/App.tsx
> +import React from 'react'
is there a reason why the react import statement needed to be changed here?

2023-05-31 18:21 UTC, b-cooper commented on shared-data/js/constants.ts
> +export const GRIPPER_MODULE_TYPE: 'gripperModuleType' = 'gripperModuleType'
This line needs to be removed.

2023-05-31 18:33 UTC, b-cooper commented on protocol-designer/src/localization/en/modules.json
> +    "gripperModuleType": "Gripper"
This looks unnecessary. It should be removed

2023-05-31 18:36 UTC, b-cooper commented on protocol-designer/src/load-file/actions.ts
> +export const setRobotName = (
RobotName is another concept within our system. Can all added usage of "robotName" within protocol-designer be changed to RobotType or something like that?

2023-05-31 18:45 UTC, b-cooper commented on protocol-designer/src/constants.ts
> +export const MODELS_FOR_FLEX_MODULE_TYPE: Record<
This duplication of the mapping from module type to view layer data is unnecessary.  Instead we should be filtering the valid modules to display for each given robot type closer to the view layer.

2023-05-31 18:55 UTC, b-cooper commented on protocol-designer/src/configureStore.ts
> +      // action.type === 'CREATE_NEW_PROTOCOL' ||
This is an important preprocessing step in setting up the redux store. The `CREATE_NEW_FILE` action case should not be removed here.  The reason you are seeing the default to "OT2", is because of the way that you set up the new `robot` sub-branch of the `file-data` branch of the redux store.  

The robot type does not belong within that branch of the redux store at all.

2023-05-31 18:56 UTC, b-cooper commented on protocol-designer/src/components/modals/NewFileModal/index.ts
why are these functions being exported?

2023-06-01 04:48 UTC, akshay-dighe commented on protocol-designer/src/components/modals/NewFileModal/index.ts
To prevent duplicating the `mapStateToProps` and `mapDispatchToProps` functions in the `flexProtocolEditor` components, a possible solution is to create a helper function or a combined function. This function would contain the shared code, and it can be called from each component to reuse the mapping logic. By doing so, we can avoid redundancy and improve code organization.

2023-06-01 04:56 UTC, akshay-dighe commented on protocol-designer/src/components/App.tsx
> +import React from 'react'
I will revert the change in this component since it is not necessary.

2023-06-02 05:51 UTC, akshay-dighe commented on shared-data/js/constants.ts
> +export const GRIPPER_MODULE_TYPE: 'gripperModuleType' = 'gripperModuleType'
done.

2023-06-02 05:51 UTC, akshay-dighe commented on protocol-designer/src/localization/en/modules.json
> +    "gripperModuleType": "Gripper"
done.

2023-06-02 05:51 UTC, akshay-dighe commented on protocol-designer/src/load-file/actions.ts
> +export const setRobotName = (
done.

2023-06-02 05:53 UTC, akshay-dighe commented on protocol-designer/src/constants.ts
> +export const MODELS_FOR_FLEX_MODULE_TYPE: Record<
As per the suggestions, I made the following changes.

2023-06-02 12:31 UTC, akshay-dighe commented on protocol-designer/src/components/ProtocolEditor.css
> +  /* overflow-y: scroll; */
deleted.

2023-06-14 09:11 UTC, akshay-dighe commented on components/src/icons/icon-data.ts
> +  'ot-flex-logo': { // todo_aditya need to take new svg with blue shade in logo
removed from this file and png image added.

2023-06-14 09:12 UTC, akshay-dighe commented on protocol-designer/src/flex-components/index.tsx
> +export const router = createBrowserRouter([
`react-router-dom` removed

2023-08-21 20:34 UTC, closed without merging