feat(hardware-testing): Create a way of storing patches in hardware-testing
OpenTrons/opentrons-api pull request #12630
Opened 2023-05-04 14:40 UTC by ryanthecoder

# Overview
Hardware-testing gravimetric tests need certain things patched in the api and shared-data directories
before we kept a seperate DO-NOT-MERGE branch around and had to rebase onto to make changes to the script than create another branch off of that to merge those changes to edge and it was pretty clunky. This allows testing to create, and apply patches easily in the main trunk without needing to maintain an extra branch

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-05-04 17:34 UTC, andySigler approved these changes

2023-05-05 13:46 UTC, sfoster1 requested changes
ah, this is way better than maintaining a separate branch. i have two requests, however:
- let's add a CI flow triggered on changes to the things the patches change that tries to apply the patches and yells at you if it fails, so we don't end up having problems where suddenly other changes broke the patches and thus the gravimetric test process
- spelling

2023-05-05 13:46 UTC, sfoster1 commented on hardware-testing/Makefile
> +.PHONY: push-ot3-gravametric
```suggestion
.PHONY: push-ot3-gravimetric
```

2023-05-05 13:46 UTC, sfoster1 commented on hardware-testing/Makefile
> +.PHONY: push-ot3-gravametric
and so on

2023-05-08 15:08 UTC, sfoster1 approved these changes
Okay, looks good to me!

2023-05-15 20:17 UTC, merged