feat(protocol-designer): update deploy scripts
OpenTrons/opentrons-api pull request #12664
Opened 2023-05-09 16:43 UTC by jerader

# Overview

change PD deployment scripts

# Test Plan

n/a - PD 6.2.1 used this configuration and it worked

# Changelog

- change time zones to match the s3 buckets
- change the arn in the yaml file for Ci to match the PL prod arn

# Review requests

make sure changes look good

# Risk assessment

low

2023-05-09 17:06 UTC, sfoster1 requested changes
Let's put the role back in the repo secrets just for cleanliness

2023-05-09 17:06 UTC, sfoster1 commented on .github/workflows/pd-test-build-deploy.yaml
> +          aws configure set role_arn arn:aws:iam::043748923082:role/administrator --profile deploy
Uh can we put this back in the repo secrets

2023-05-10 19:57 UTC, sfoster1 approved these changes
Looks great!

2023-05-15 13:55 UTC, shlokamin reviewed
this looks good! probably best to keep arns behind gh secrets as a best practice tho. while arns alone wont give others access to our aws accounts, i think we may as well err on the side of caution since we already have infra set up

2023-05-15 13:55 UTC, shlokamin commented on scripts/deploy/promote-to-production.js
> +        RoleArn: 'arn:aws:iam::043748923082:role/administrator',
this should be a secret

2023-05-15 13:55 UTC, shlokamin commented on scripts/deploy/promote-to-production.js
> +        const productionCloudfrontArn = `arn:aws:cloudfront::043748923082:distribution/E20OHY6J3BRVIF`
this too

2023-05-15 13:55 UTC, shlokamin commented on scripts/deploy/promote-to-staging.js
> +        const stagingCloudfrontArn = `arn:aws:cloudfront::043748923082:distribution/EB2QTLE7OJ8O6`
this too

2023-05-15 13:55 UTC, shlokamin commented on scripts/deploy/promote-to-staging.js
> +stagingAssumeRole()
seems like we could make a generic `assumeRole` fn that takes in staging/prod params

2023-05-15 13:55 UTC, shlokamin commented on scripts/deploy/promote-to-staging.js
> +        return cloudfront.createInvalidation(cloudFrontParams).promise()
same thing here, seems like we can create a generic `createInvalidation` fn

2023-05-15 17:44 UTC, merged