fix(api): Exclude existing module offsets when running subsequent module calibrations
OpenTrons/opentrons-api pull request #12667
Opened 2023-05-09 19:06 UTC by vegano1

# Overview

Module Calibrations were failing because the calibration starting position was being shifted by the previous module calibration value for the given module, which meant that eventually the starting position would be way off-center and would not be able to find the calibration square. This PR addresses this issue and fixes another issue with non-connected modules (magnetic block) where we would throw `ModuleNotConnectedError` when trying to get the labware well position.

Closes: [RCORE-738](https://opentrons.atlassian.net/browse/RCORE-738)

# Test Plan

- [ ] Make sure subsequent module calibrations start at the same position for each module type
- [ ] Make sure we don't throw `ModuleNotConnectedError` when getting the position for labware on top of the magnetic block.

# Changelog

- Fixed an issue where the starting point for module calibrations would be off by the previous module offset causing subsequent module calibrations to fail.
- Fixed a potential issue in get_module_offset if the module is a non-connected module where just getting the well position would throw ModuleNotConnectedError, instead, we want to return the offset without the calibrated offset value.
- Added get_raw_module_offset so we can get the loaded module offsets without transforms
- Refactored the calibrate_module test script so it handles needing to home after robot-server restart, resetting states, and generally handling failure cases better.

# Review requests

Make sure we are comfortable with the get_module_changes which affect get_well_position

# Risk assessment

medium, while this affects module calibration directly any changes to get_module_offset also affect get_well_position

2023-05-09 19:16 UTC, sfoster1 requested changes
The functionality looks good but I'm a little nervous doing this `get_raw_module_offset` and then subtracting it thing. It makes the code in the calibration command depend on the internal behavior of other modules. We're now depending on the implicit contract that the only offset from nominal in the well position is whatever `get_raw_module_offset` returns, which is a contract across two separate modules.

What if instead we have `get_nominal_well_position`, which probably internally depends on a `get_nominal_module_position` (and maybe raises `NotImplementedError` if you ask it for the nominal position of a well that's not something on a labware)? Now we've made the contract explicit: if you ask for `get_nominal_well_position()`, it _must_ take into account nothing but the predefined geometry.

I think that would be a little more robust to regressions.

2023-05-09 19:16 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/modules.py
> +    def get_raw_module_offset(self, module_id: str) -> ModuleOffsetVector:
if we're modifying PE for this, I think it's probably more straightforward to add like `get_nominal_well_position` and `get_nominal_module_position`.

2023-05-09 19:16 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_module.py
> +        current_offset = self._state_view.modules.get_raw_module_offset(params.moduleId)
The problem with this is that it's doomed to break if we add more offsets somewhere in the future. What if we instead add a `get_nominal_well_position` and `get_nominal_module_position`, which don't apply calibration offsets?

2023-05-09 19:34 UTC, sanni-t commented on api/src/opentrons/protocol_engine/state/modules.py
> +    def get_raw_module_offset(self, module_id: str) -> ModuleOffsetVector:
I like that!

2023-05-09 20:44 UTC, vegano1 commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_module.py
> +        current_offset = self._state_view.modules.get_raw_module_offset(params.moduleId)
you're absolutely correct, good feedback

2023-05-12 18:23 UTC, sfoster1 approved these changes
This looks great to me aside from those couple nits! Nice work!

2023-05-12 18:23 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/modules.py
> +    def get_module_offset_vector(self, module_id: str) -> ModuleOffsetVector:
nit: can we call this `get_module_calibration_offset`? i'm getting confused by having both this and `get_module_offset`

2023-05-12 18:23 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +        return Point(
nit: could do `return parent_pos + origin_offset + well_def + Point(x=0, y=0, z=well_def.depth)` but it's up to you whether that's clearer or not

2023-05-12 18:45 UTC, SyntaxColoring approved these changes
Code makes sense to me. Thanks!

The overall approach also makes sense to me, but with a caveat: it only protects `loadModule` commands. That means, in the module calibration flows, we'll have to be careful that the app doesn't issue any other commands that would visit this module.

For example, if the app did a `moveToWell` command, it would still use the module's old calibration. The app *does* issue other commands like this during Labware Position Check, so we should make sure it doesn't need to do that for module calibration.

2023-05-12 18:45 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/modules.py
> +    def get_module_offset_vector(self, module_id: str) -> ModuleOffsetVector:
Agreed. The only reason *`get_labware_offset_vector()`* is named like it is is because people have been very persnickety about Labware Position Check saving *labware offsets,* not *labware calibrations.* (🤷) But "calibration" is more specific than just "offset," so it's nice to say "calibration" when we can.

2023-05-12 18:52 UTC, sanni-t approved these changes
LGTM! 
Just the two naming suggestions similar to @sfoster1 's

2023-05-12 18:52 UTC, sanni-t commented on api/src/opentrons/protocol_engine/state/geometry.py
> +    def get_labware_parent_origin_position(self, labware_id: str) -> Point:
I would keep this `get_labware_parent_position` or make it `get_labware_parent_nominal_position`..

2023-05-12 18:52 UTC, sanni-t commented on api/src/opentrons/protocol_engine/state/geometry.py
> +    def get_labware_parent_position(self, labware_id: str) -> Point:
..and change this to `get_labware_parent_calibrated_position`

2023-05-12 19:09 UTC, sanni-t commented
> The overall approach also makes sense to me, but with a caveat: it only protects `loadModule` commands. That means, in the module calibration flows, we'll have to be careful that the app doesn't issue any other commands that would visit this module.
> 
> For example, if the app did a `moveToWell` command, that would still use the module's old calibration, right? The app _does_ issue other commands like `moveToWell` during Labware Position Check. So we should make sure it doesn't need to do that for module calibration.

Am I understanding your concern correctly that if a `moveToWell` command was issued immediately after a module calibration, in the same run, then the instrument might end up going to a position that was calculated with the calibration offsets that were loaded before the most recent module calibration (unless the module is reloaded or a new run is started after the calibration)? If so, then that's actually not what would happen. There is indeed a state update handler that would update the particular module's calibration offset in state after a successful module calibration so we'll start using the new offset right away for all moveTo commands.

2023-05-12 21:23 UTC, vegano1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +    def get_labware_parent_position(self, labware_id: str) -> Point:
kept it as is for consistency

2023-05-12 21:52 UTC, SyntaxColoring commented
> Am I understanding your concern correctly that if a moveToWell command was issued immediately after a module calibration, in the same run, then the instrument might end up going to a position that was calculated with the calibration offsets that were loaded before the most recent module calibration (unless the module is reloaded or a new run is started after the calibration)? If so, then that's actually not what would happen. There is indeed a state update handler that would update the particular module's calibration offset in state after a successful module calibration so we'll start using the new offset right away for all moveTo commands.

No—my concern is that if a `moveToWell` command is issued *before* the `calibrateModule` command, the `moveToWell` command will use an old, possibly bad offset, while the `calibrateModule` command will use the nominal position. Ideally, I think they'd both use the nominal position.

For example, imagine if the app had a step where it did `moveToWell` and then said "OK user, I'm about to calibrate here." And then it...didn't calibrate there.

2023-05-15 12:52 UTC, merged