feat(api): add extension mount and axes to top level types
OpenTrons/opentrons-api pull request #12671
Opened 2023-05-10 13:18 UTC by sanni-t

Closes RLAB-219 & RLAB-231

# Overview

Adds Extension mount and its axes to `Mount`, `MountType` & `Axis` in `opentrons.types`.

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-05-10 17:54 UTC, sfoster1 requested changes
Couple hardware-specific changes I'd like to see unfortunately

2023-05-10 17:54 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +            ), "Received a non-OT2 axis for homing."
I think this is correct modulo using a more specific exception than `AssertionError` - I think we want like a `NotSupportedByHardware` error

2023-05-10 17:54 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/simulator.py
> +            for m in types.Mount  # Check if addition of extension Mount creates issues for this
feels like we should just use `ot2_mounts` here?

2023-05-10 17:54 UTC, sfoster1 commented on api/src/opentrons/hardware_control/types.py
> +    A = 3  # right pipette mount Z
I don't want to change the ot3 stuff to use `Z`/`A`/`B`/`C`. I think we should handle `Z_L`, `Z_R`, `P_L`, `P_R`. I think this can be handled in one of two ways:
- Just add them. Add per-machine iterators `ot2_axes` and `flex_axes` like we have for the mounts. It's non-unique now, that's fine.
- Make it two types again but now they're top-level and have some sort of equivalence relationship

2023-05-10 19:45 UTC, sanni-t commented on api/src/opentrons/hardware_control/types.py
> +    A = 3  # right pipette mount Z
Sorry, not sure which change you are talking about here. There are still two different axis types- `Axis` and `OT3Axis`, and OT3Axis uses `Z_L, Z_R, etc`. Here I've only added comments and Gripper Z & Jaw to the existing `Axis` type.

2023-05-11 21:12 UTC, sfoster1 approved these changes
Ok, looks good to me based on a convo - let's merge Axis and OT3Axis in a followup!

2023-05-17 21:00 UTC, merged