feat(app): error handling for wrong pip attached
OpenTrons/opentrons-api pull request #12706
Opened 2023-05-16 12:20 UTC by jerader

# Overview

When attaching a pipette in run setup, if you attach the wrong pipette, the results page now renders the error modal ([designs](https://www.figma.com/file/0hYQ4lFJbAAI33jQMRt1Di/Release%3A-Opentrons-App-w-Flex?type=design&node-id=4244-89424&t=puyJ3UtUhsrZYz3V-0)). When you click `detach and retry` it goes back to detach and reattach the correct pipette.

# Test Plan

test this flow on a robot to make sure it works as expected

# Changelog

- add error logic to `Results` page and add test cases

# Review requests

see test plan

# Risk assessment

low

2023-05-16 16:51 UTC, smb2268 requested changes

2023-05-16 16:51 UTC, smb2268 commented on app/src/organisms/PipetteWizardFlows/Results.tsx
> +        buttonText = i18n.format(t('detach_and_retry'), 'capitalize')
We need to change `iconColor` and  `isSuccess` fields so that this isn't shown as a green check mark
```suggestion
        buttonText = i18n.format(t('detach_and_retry'), 'capitalize')
        iconColor = COLORS.errorEnabled
        isSuccess = false

2023-05-16 16:51 UTC, smb2268 commented on app/src/organisms/PipetteWizardFlows/Results.tsx
> +      goBack()
This takes us back to the before you begin screen which I'm not sure makes sense from a user perspective - on the OT-2 flows we just have the `CheckPipetteButton` here in this case, so we recheck for attachment of the correct pipette instead of rerouting the user through the flow again which might make more sense?

2023-05-16 17:32 UTC, jerader commented on app/src/organisms/PipetteWizardFlows/Results.tsx
> +        buttonText = i18n.format(t('detach_and_retry'), 'capitalize')
oops thanks!

2023-05-16 17:39 UTC, jerader commented on app/src/organisms/PipetteWizardFlows/Results.tsx
> +      goBack()
I wonder if we should add a subheader that says which pipette is the correct one to attach?

2023-05-19 20:45 UTC, smb2268 approved these changes
Tested this and it worked as expected!

2023-05-19 20:45 UTC, smb2268 commented on app/src/organisms/PipetteWizardFlows/Results.tsx
> +  if (
can we make this an `else if`?

2023-05-20 00:28 UTC, merged