refactor(app-shell): add usb bad request handler on detach
OpenTrons/opentrons-api pull request #12769
Opened 2023-05-23 18:32 UTC by brenthagen

# Overview

after detaching a usb-connected robot, the device details page will continue making a handful of requests via `appShellRequestor`. without a handler, these requests log errors in both the renderer and main processes and prevent re-adding a handler on usb re-attach. this adds a "bad request" handler to handle those requests, and removes any existing handler on usb attach. the "bad request" status code is only relevant for the remaining robot-api rxjs requests.

re RCORE-763

# Test Plan

 - manually confirmed usb attach/detach adds and removes handlers.

# Changelog

 - Adds usb bad request handler on detach

# Review requests

is this a reasonable approach?

# Risk assessment

low

2023-05-23 19:46 UTC, sfoster1 requested changes
Looks good if it wont' mess up those callers but let's make the error message nicer

2023-05-23 19:46 UTC, sfoster1 commented on app-shell/src/usb.ts
> +              statusText: 'Bad Request',
```suggestion
              statusText: 'USB robot disconnected',
```

just to make somebody's future wtf a little more easily answered

2023-05-23 21:35 UTC, brenthagen commented on app-shell/src/usb.ts
> +              statusText: 'Bad Request',
makes sense to me

2023-05-24 16:58 UTC, sfoster1 approved these changes
lgtm, thank you!

2023-05-24 17:47 UTC, merged