fix(api): update USB port & hub mapping logic for Flex
OpenTrons/opentrons-api pull request #12775
Opened 2023-05-23 23:01 UTC by pmoegenburg

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-05-25 15:40 UTC, sfoster1 requested changes
I think the structure is good but we need some changes.
- We should test the new code.
- We should make sure we can still handle someone plugging an external hub into one of the USB ports on the OT3
- We should make the port group type an Enum
- We should make sure we understand how this new data is represented via HTTP

2023-05-25 15:40 UTC, sfoster1 commented on api/src/opentrons/drivers/rpi_drivers/types.py
> +    port_group: str = ""
I think we really want this to be an enumeration since it has a fixed number of possible values. We'll need to represent it as a string eventually in the HTTP layer, but we can cross that bridge when we come to it. We should make the enum handle the left, the right, and "main" (for OT-2) and probably even "front" (for OT-3 - just in case).

2023-05-25 15:40 UTC, sfoster1 commented on api/src/opentrons/drivers/rpi_drivers/types.py
> +    ) -> Tuple[Optional[int], str, int]:
this would be a good place for us to return the enum

2023-05-25 15:40 UTC, sfoster1 commented on api/src/opentrons/drivers/rpi_drivers/types.py
> +            # what will hub look like??
what does it look like?

2023-05-26 17:43 UTC, sfoster1 requested changes
This is looking really good! I think we should make the revision name for the OT-3 variants include that it's an ot3 - honestly, this driver code should probably leave the `rpi_drivers` section but we don't need to do that in this PR - and maybe add some comments noting in more depth what's going on with the usb string splitting in `map_to_revision`.

Also, let's add some tests that explicitly check that strings captured from a running OT-3 prase properly, for left and right with no hubs and left and right with hubs

2023-05-26 17:43 UTC, sfoster1 commented on api/src/opentrons/drivers/rpi_drivers/types.py
> +            hub_port: Optional[int] = int(port_info[3])
this would want to be `port_info[-1]` maybe?

2023-05-26 17:43 UTC, sfoster1 commented on api/src/opentrons/hardware_control/types.py
> +    B2 = enum.auto()
can we maybe make this `FLEX_B2` or something?

2023-06-02 14:40 UTC, sfoster1 reviewed
Looks good to me once we fix up the tests!

2023-06-05 16:55 UTC, sfoster1 approved these changes
Looks great to me if tests all pass, but let's make sure @sanni-t or another RSS person gets a glance - possibly an in-person demo?

2023-06-06 20:17 UTC, pmoegenburg commented on robot-server/tests/integration/test_modules.tavern.yaml
> +              hub: !anyint
@sfoster1 will this become an int? It is a bool in the `api`

2023-06-06 20:41 UTC, sfoster1 commented on robot-server/tests/integration/test_modules.tavern.yaml
> +              hub: !anyint
When sent via http, the type is expressed as determined in the [response model](https://github.com/Opentrons/opentrons/blob/4445d808e5401c9283c8af780bb7e1ddee65a162/robot-server/robot_server/service/legacy/models/modules.py#L96) which would also have to change. that would then be a breaking change, which would be rough.

2023-06-06 20:42 UTC, sfoster1 commented on robot-server/tests/integration/test_modules.tavern.yaml
> +              hub: !anyint
You can see there that the `hub` field is optional in the model and setup by this data: https://github.com/Opentrons/opentrons/blob/4445d808e5401c9283c8af780bb7e1ddee65a162/robot-server/robot_server/service/legacy/routers/modules.py#LL36C51-L36C51

2023-06-07 18:04 UTC, sfoster1 approved these changes
Looks good pending seeing what this breaks in app interactions if anything

2023-06-08 18:45 UTC, sanni-t reviewed
This looks good mostly. Just some minor comments. 
I tested this on a flex and it works great! Didn't test on ot2 but I'm assuming it'll have similar app-side change requirements due to the hub/port structure (& type) change? (and that'll be a slight breaking change/ introduce incompatibility with older app).
As for the app changes, this is how the app shows usb ports with your change-

<img width="855" alt="Screenshot 2023-06-07 at 4 03 33 PM" src="https://github.com/Opentrons/opentrons/assets/8520173/453a7c62-a620-4195-b03e-9dc67a0288c3">

<img width="1039" alt="Screenshot 2023-06-07 at 4 03 23 PM" src="https://github.com/Opentrons/opentrons/assets/8520173/7cd25cc4-79b6-404e-9251-c07c810ae037">

2023-06-08 18:45 UTC, sanni-t commented on robot-server/robot_server/service/legacy/models/modules.py
> +                                },
We want to make sure the example structure is valid acc to the defined models-

```suggestion
                                "usbPort": {
                                    "hub": 1,
                                    "port": 1,
                                    "portGroup": 1,
                                    "hubPort": None,
                                },
```
If we change port group to have string values, then will need to update that here too.

2023-06-08 18:45 UTC, sanni-t commented on api/src/opentrons/drivers/rpi_drivers/types.py
> +    LEFT = enum.auto()
Can we make these have string values? So-

```suggestion
    MAIN = "main"
    LEFT = "left"
```
This way, the robot server's responses (which currently would show `portGroup` as a number) would show the string value instead, which is a more helpful response.

2023-06-08 18:45 UTC, sanni-t commented on robot-server/robot_server/service/legacy/models/modules.py
> +    hub_port: typing.Optional[int] = Field(
```suggestion
    portGroup: PortGroup = Field(
        ...,
        description="The physical USB port bank the module is plugged into.",
    )
    hubPort: typing.Optional[int] = Field(
```

2023-06-08 18:45 UTC, sanni-t commented on robot-server/robot_server/service/legacy/models/modules.py
> +                                },
Also, I think the "port" field above "usbPort" might have been added here by mistake. We should remove it since a real response can't contain both 'port' (virtual port) and a 'usbPort'.

2023-06-08 18:45 UTC, sanni-t commented on robot-server/robot_server/modules/module_models.py
> +    hub_port: Optional[int] = Field(
```suggestion
    portGroup: PortGroup = Field(
        ...,
        description=("The physical USB port bank the module is plugged into."),
    )

    hub: bool = Field(
        ...,
        description=("If the module is connected via a USB hub."),
    )

    hubPort: Optional[int] = Field(
```

2023-06-14 22:02 UTC, merged