Update DEV_SETUP.md
OpenTrons/opentrons-api pull request #12790
Opened 2023-05-25 21:44 UTC by alexjoel42

# Overview

3.7.15 came out and we recommend 3.7.13. 

Also added some quick Pyenv instructions. 

# Test Plan

# Changelog
change all instances of 3.7.13 to 3.7.15. 

Then I couldn't get Pyenv working so I added how to use pye

# Review requests

Unclear.

# Risk assessment

Please check if 3.7.13 causes errors for other folks before updating. It could be specific to my system setup because it's a bit quirky.

2023-05-25 22:08 UTC, koji approved these changes
Thank you for updating this!
tested `make setup` with python 3.7.15 and it worked as expected

2023-05-26 02:22 UTC, ecormany requested changes
Spotted a syntax error we ought to fix before merging. All the other prose suggestions are optional.

2023-05-26 02:22 UTC, ecormany commented on DEV_SETUP.md
> +3. If you aren't seeing `python --version` for an M1 Mac outputing the right value, try running `pyenv init` then run `pyenv local 3.7.15` and see if it works this time when you select `python -versi
```suggestion
3. Run `python --version` to confirm your chosen version. If you get the incorrect version and you're using an Apple silicon Mac, try running `pyenv init` and then `pyenv local 3.7.15`. Then check `python --version` again.
```
You don't have to take this whole suggestion, but at least get the double dash flag on `python --version` at the very end. `python -version` will produce an error.

"Apple silicon" is to future-proof. We already have M1 and M2 and we can't list all the Ms forever into the future.

2023-05-26 15:30 UTC, alexjoel42 commented
I added a small thing to fix my [ 'pyenv init' ](https://stackoverflow.com/questions/33321312/cannot-switch-python-with-pyenv) error. 

Somehow when I PR I feel like I cause problems while trying to fix them haha.

2023-05-26 21:12 UTC, ecormany approved these changes

2023-05-26 22:20 UTC, koji commented
@alexjoel42 
We use [commitizen](https://github.com/commitizen/cz-cli)

For the next time please follow ↓
https://github.com/Opentrons/opentrons/blob/edge/CONTRIBUTING.md#making-your-commit

If you have any question on opening a PR, feel free to ask questions #software-team channel in Slack.

2023-05-30 14:37 UTC, merged