feat(hardware): add limit switch backoff to home sequence
OpenTrons/opentrons-api pull request #12824
Opened 2023-05-31 22:15 UTC by ahiuchingau

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-06-01 21:04 UTC, sfoster1 requested changes
errant `C` I think

2023-06-01 21:04 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_bindings/constants.py
> +    limit_switch_backoff = 0x4C0
```suggestion
    limit_switch_backoff = 0x40
```
?

2023-06-01 21:08 UTC, ahiuchingau commented on hardware/opentrons_hardware/firmware_bindings/constants.py
> +    limit_switch_backoff = 0x4C0
ugh

2023-06-02 18:27 UTC, sfoster1 approved these changes
Looks good to me!

2023-06-07 19:56 UTC, sfoster1 approved these changes
Looks good but would love to see the stop condition checking be its own function

2023-06-07 19:56 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +                stop_cond
Let's factor this into an `acceptable_stop_condition()` predicate function that checks this and can be extended to other stuff IMO

2023-06-07 20:00 UTC, ahiuchingau commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +                stop_cond
Yes! That's the next step i was gonna take, to do a refactor on the move runner completion message and make sure we're actually responding timeout correctly, but will be a next PR

2023-06-08 15:21 UTC, merged