refactor(api): merge OT3Axis into Axis
OpenTrons/opentrons-api pull request #12834
Opened 2023-06-01 18:46 UTC by sanni-t

# Overview

This is a follow-up PR to #12671 and merges the two different axis types- Axis and OT3Axis into one.

# Test Plan

Test a couple of protocol flows- including running attach/detach flows and LPC on both OT2 & OT3 to make sure nothing breaks.

# Changelog

- Made `OT3Axis` enum the new `Axis` with aliases for the old OT2 Axis members. So the formal members of `Axis` are now: `X, Y, Z_L, Z_R, Z_G, P_L, P_R, Q, G` with aliases for OT2 axes of `Z, A, B, C`.
- Any and all changes relating to making the above change and making sure OT2 code still works and the smoothie driver gets the correct 'translated' old Axis 

# Review requests

- Check if there's any silly auto-refactor changes like `Union[OT3Axis, Axis]` -> `Union[Axis, Axis]`
- Any changes I've missed or made incorrectly? esp. in `motion_utilities.py`

# Risk assessment

High. Changes very low level code for OT2. 
Not much detrimental for OT3 other than making sure all scripts are updated correctly (ones in this repo and any testing/ factory scripts in use).

2023-07-11 17:13 UTC, sanni-t commented on api/src/opentrons/hardware_control/motion_utilities.py
> -def target_position_from_absolute(
I am not sure if I should have kept the overloads for the `target_position_from_absolute` function since the TODO at the top says that `offset_for_mount` should be an overloaded function in the first place. But it didn't seem like the implementation, as it stands right now, is utilizing any overload features so I decided to remove it. Let me know if I should revert this change.

2023-07-11 19:28 UTC, sanni-t commented on robot-server/robot_server/service/legacy/models/motors.py
> +    g: typing.Optional[EngagedMotor]
This is a breaking change for expected response of `/motors/engaged` endpoint. But the app doesn't use this endpoint anywhere so I think it's okay?

2023-07-11 19:29 UTC, sanni-t commented on robot-server/tests/service/legacy/routers/test_motors.py
> +    # assert res0.status_code == 200
```suggestion
    assert res0.status_code == 200
```

2023-07-11 19:33 UTC, sfoster1 requested changes
- Would love to see us get rid of the parametrization on `Axis` in the hardware controller protocols
- Doesn't have to be now but we should move the "machine-shape" accessors (like ot2_mounts) to the hardware controller
- Can we switch the way this works in `hardware-testing` to be changign what backs up `hardware_testing.opentrons_api.types.OT3Axis` to just be `Axis`? It would keep the diff down.

2023-07-11 19:33 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +                k: v for k, v in max_speeds.items()  # (spp): is this even needed?
uhhhh probably not

2023-07-11 19:33 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +    HardwareControlInterface[OT3Transforms, Axis],
Can we remove the parametrization over axis types entirely?

2023-07-11 19:33 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +    HardwareControlInterface[OT3Transforms, Axis],
I know it's a lot to add but it's The Thing

2023-07-11 19:33 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot2/pipette_handler.py
> +AxisType = TypeVar("AxisType", bound=Axis)
Can we remove this type parametrization entirely?

2023-07-11 19:33 UTC, sfoster1 commented on api/src/opentrons/hardware_control/motion_utilities.py
> -@overload
ahhh im so glad to see this

2023-07-11 19:33 UTC, sfoster1 commented on api/src/opentrons/hardware_control/protocols/motion_controller.py
> +AxisType = TypeVar("AxisType", bound=Axis)
Can we get rid of it?

2023-07-11 19:33 UTC, sfoster1 commented on api/src/opentrons/hardware_control/types.py
> +    def ot2_mount_axes(cls) -> Tuple["Axis", "Axis"]:
Doesn't have to be in this pr, but we probably want to get `Axis` out of this business and drop these methods on the hardware controller classes or something. They're properties of the machine, and the hardware controller ultimately represents that.

2023-07-11 19:34 UTC, sanni-t commented on robot-server/tests/service/legacy/routers/test_pipettes.py
> +            "plunger_axis": "p_r",
Shoot! Forgot about this. I think this should return the old names of axes to prevent a breaking change for the client. I'm going to make that change unless anyone disagrees.

2023-07-14 15:20 UTC, sanni-t commented
> * Would love to see us get rid of the parametrization on `Axis` in the hardware controller protocols

Done

> * Doesn't have to be now but we should move the "machine-shape" accessors (like ot2_mounts) to the hardware controller

Left todo comments on all such accessors.

> * Can we switch the way this works in `hardware-testing` to be changign what backs up `hardware_testing.opentrons_api.types.OT3Axis` to just be `Axis`? It would keep the diff down.

That is certainly a smart idea that I did not think of when doing the refactor the first time. But now that they're all changed to Axis, it's a bit of a pain to go back and rename all the references, specially since some files in hardware-testing import Axis directly from hardware control. Can we just keep the change now? 😬

2023-07-14 20:30 UTC, sanni-t commented
Tested simple transfer protocols on both OT2 & Flex to confirm I didn't break anything. Also tested calibration on OT-2 to make sure the pipette offset endpoints return expected responses.

2023-07-17 15:33 UTC, sfoster1 approved these changes
This is awesome, thank you!

2023-07-17 18:07 UTC, merged