fix(api): home plunger & mount axis properly after drop tip
OpenTrons/opentrons-api pull request #12857
Opened 2023-06-05 20:10 UTC by ahiuchingau

# Overview
Pipette plunger and mount were not homed properly in `ot3api.drop_tip()` function.

2023-06-06 12:53 UTC, Laura-Danielle requested changes
Why are we defaulting to homing again after drop tip? Can we not rely on the head encoders?

2023-06-07 01:57 UTC, andySigler commented
we should discuss with HWE before merging this

2023-06-14 19:48 UTC, Laura-Danielle approved these changes
ok looks fine to me

2023-06-14 20:12 UTC, sfoster1 approved these changes
okay. we should really make this not required tho

2023-06-14 20:35 UTC, merged