feat(api): Monitor for overpressure on pipetting commands
OpenTrons/opentrons-api pull request #12864
Opened 2023-06-06 16:58 UTC by Laura-Danielle

# Overview

Although a low chance, we should monitor whether the pressure sensor ever exceeds its max rated value.

# TODO

- [x] Finish tests for `tool_sensors`
- [x] Finish tests for `ot3controller`
- [x] Add a check in the blow out function

# Test Plan

- [x] Execute a protocol with a few pipetting functions (i.e. aspirate/dispense/blowout/drop tip) and verify via the serial log or CAN logs that a bind request for max threshold is sent. To ease testing, you can also tell the request to log so you can see the pressure values being print to screen.
- [x] Using monitor sensors, determine a sufficient occlusion material (maybe a piece of cloth?) to get it to exceed 3.9kpa. This should cause the firmware to throw and error and stop all movement.

# Changelog

- Added tests at all levels from scheduler, tool_sensors and up to ot3controller
- Added a context manager that will throw an error if it receives an error message from firmware
- This currently only monitors 1 pressure sensor for a given pipette, we should figure out a nice way to monitor both sensors and can maybe tackle it as part of the partial tip pick up project.

# Review requests

Not a huge fan of the partial function workaround, but I wanted the ot3controller to have an actual context manager so we could nest specific moves inside the pipetting functions without pushing it down to `tool_sensors.py`. If anyone has better suggestions, I am definitely open.

Also please let me know if I missed any high risk pipetting functions!

# Risk assessment

Ideally low, but this could have unforeseen consequences regarding anything utilizing the i2c bus (for example the eeprom). We should closely monitor in the coming weeks.

2023-06-15 15:38 UTC, sfoster1 requested changes
I think we should add a try/finally and, bowing to the wisdom of history, I think we might want to add a feature flag that lets you turn this off juuuust in case

2023-06-15 15:38 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            yield
this probably wants to have a try/finally so the cleanup always (at least tries to) happen

2023-06-15 15:38 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            raise RuntimeError(
let's get a custom exception for this

2023-06-16 14:09 UTC, sfoster1 requested changes
One more step to error handling, I think it'll be pretty quick.

2023-06-16 14:09 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +                finally:
Not quite, I think. As implemented, we'll now correctly do whatever cleanup we need but we'll also swallow and blackhole the exception. We need to put the `_pop_queue` definition and call _inside_ the `finally` block so that it both runs even if there's an exception _and_ lets that exception bubble up afterward.

2023-06-16 14:09 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +                yield
conversely here we don't need this `try`/`finally` at all

2023-06-16 14:17 UTC, sfoster1 approved these changes
Ok looks good now if it passes tests though shouldn't we raise on sensor config errors?

2023-06-16 14:17 UTC, sfoster1 commented on hardware/opentrons_hardware/sensors/scheduler.py
> +                f"recieved error {str(error)} trying to bind sensor output on {str(target_sensor.node_id)}"
shouldn't we raise here?

2023-06-16 14:17 UTC, sfoster1 commented on hardware/opentrons_hardware/sensors/scheduler.py
> +                log.error(
shouldn't we raise here?

2023-06-16 14:19 UTC, Laura-Danielle commented on hardware/opentrons_hardware/sensors/scheduler.py
> +                f"recieved error {str(error)} trying to bind sensor output on {str(target_sensor.node_id)}"
We don't raise anywhere else that we receive an error from the sensor tasks so I decided not to add that here. Can do that in a follow-up PR if you want. I will not be merging this until the andys have a chance to test it.

2023-06-16 14:19 UTC, Laura-Danielle commented on hardware/opentrons_hardware/sensors/scheduler.py
> +                log.error(
See above.

2023-06-21 13:33 UTC, sfoster1 commented on hardware/opentrons_hardware/sensors/scheduler.py
> +                f"recieved error {str(error)} trying to bind sensor output on {str(target_sensor.node_id)}"
ah ok

2023-06-21 13:40 UTC, andySigler approved these changes
Test on a bot and works as expected 👍 . Couple of comments for a followup PR:

There are two scenarios where pressure should be monitored but it is not yet as currently implemented:

- prepare for aspirate
- api.home()

Might be easier to manage all these cases if the pressure monitoring was instead happening inside `OT3Controller.home()` and `OT3Controller.move()`, and it's called whenever a plunger axis is passed in as an argument, but we could save that for a followup PR.

2023-06-21 13:53 UTC, merged