feat(api): check if a tip is present on a pipette in the hardware controller
OpenTrons/opentrons-api pull request #12886
Opened 2023-06-09 14:56 UTC by Laura-Danielle

# Overview
We have tip presence ability on pipettes and so we should use it to inform the user of an error if a tip fails to pick up. This is the very beginning of tip presence handling and so it does **not**:

- continuously check to see if the tip state has changed while running a protocol
- re-try picking up or dropping a tip (although we can do that in a follow-up PR once we figure out a number here)

# Test Plan

Create a protocol that picks up and drops tip a few times. On the robot, you should have a tiprack that is missing some tips so that when a pick up tip fails to detect the tip and error raises. This will stop the protocol. You can do the same thing for drop tip by simply removing a tip after it has successfully picked up. I would suggest adding pauses between pick up/drop tip to make this easier to test.

- [ ] Check that pick up tip will fail in a protocol if it does not pick up a tip
- [ ] Check that drop tip will fail in a protocol if it does not drop an existing tip (we will have to fake this by removing the tip beforehand)
- [ ] Check that LPC can handle a failed pick up or drop gracefully
- [ ] Once we have done the above, run a regular (short) protocol to check the reliability

# Changelog

- Add a command you can use in the hardware controller to query the tip state
- Raises an error if the state does not match the expected value when you're picking up or dropping tip.

# Review requests

Might've flipped the state. Please check me on this.

# Risk assessment

Medium/high. Could potentially be disruptive to ABR work.

2023-06-15 15:30 UTC, sfoster1 approved these changes
Looks good though I'd love to see the enum entries change names

2023-06-15 15:30 UTC, sfoster1 commented on api/src/opentrons/hardware_control/types.py
> +    DROP = False
kind of a nit but the name is `State` and the elements are actions. Can we make these `PRESENT` and `ABSENT` or somethign

2023-06-15 15:33 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/types.py
> +    DROP = False
yeah actually agree. Will make that change.

2023-06-21 13:22 UTC, sfoster1 requested changes
Looks like the changes to make the tip state query return a bool don't match the way the function is called anymore so the checks don't do much

2023-06-21 13:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        # TODO change to enum
not a todo anymore right?

2023-06-21 13:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        await self._backend.get_tip_present(realmount, TipStateType.PRESENT)
this code seems to be written as if `self._backend.get_tip_present()` will raise if the tip state doesn't match, but it now returns a bool instead, so the call doesn't do anything

2023-06-21 13:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        # TODO change to enum
ditto both re: todo and re: exception/bool return

2023-06-21 13:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/types.py
> +    ABSENT = False
something about this makes me feel gross... maybe just use `enum.auto()`?

2023-06-21 14:54 UTC, sfoster1 commented
- [x] Check that pick up tip will fail in a protocol if it does not pick up a tip
- [x] Check that drop tip will fail in a protocol if it does not drop an existing tip (we will have to fake this by removing the tip beforehand)
- [x] Check that LPC can handle a failed pick up or drop gracefully

2023-06-21 14:57 UTC, sfoster1 commented
- [x]  Once we have done the above, run a regular (short) protocol to check the reliability

2023-06-21 17:06 UTC, sfoster1 approved these changes
Looks good to me!

2023-06-21 17:06 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        await self._backend.get_tip_present(realmount, TipStateType.PRESENT)
no wait it does raise

2023-06-21 18:19 UTC, sfoster1 commented
We'll rework the remaining pipettes with the misplaced photointerrupter flag.

2023-06-21 18:20 UTC, sfoster1 approved these changes
Looks good to me, I think we're all set!

2023-06-21 18:22 UTC, merged