feat(engine): load and stack labware on adapters in engine
OpenTrons/opentrons-api pull request #12928
Opened 2023-06-16 13:59 UTC by jbleon95

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-06-16 14:07 UTC, jbleon95 commented on api/src/opentrons/protocol_engine/commands/load_adapter.py
> +    displayName: Optional[str] = Field(
consider removing this

2023-06-16 14:20 UTC, jbleon95 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +            module_model = self._modules.get_connected_model(module_id)
this won't work for magnetic block, find a different way to get the module model's name

2023-06-16 14:25 UTC, jbleon95 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +        self, labware_id: str, location: LabwareLocation
look into splitting this up to check definition related checks in another function

2023-06-16 20:04 UTC, jbleon95 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +            module_model = self._modules.get_connected_model(module_id)
correction: this will work for magnetic block, the method is just named inaccurately

2023-06-20 14:02 UTC, b-cooper approved these changes
The logic makes sense to me. Looks good 👍

2023-06-20 14:02 UTC, b-cooper commented on api/src/opentrons/protocol_engine/state/geometry.py
> +            module_model = self._modules.get_connected_model(module_id)
Is it possible to at least add this "*NOTE despite the mag block not really being connected, this method will return all physically loaded modules, including mag block". to the docstring of `get_connected_model`. that way the next person will be less confused by the same confusing naming convention. Alternatively you could change the name to something more appropriate.

2023-06-20 14:56 UTC, vegano1 commented on api/src/opentrons/protocol_api/core/engine/deck_conflict.py
> +        # TODO(jbl 2023-06-08) check if we need to do any logic here or if this is correct
still need this todo?

2023-06-20 15:25 UTC, vegano1 commented on api/src/opentrons/protocol_engine/state/labware.py
> +    def raise_if_labware_cannot_be_stacked(
There is a physical limit to how many things can be stacked on top of each other defined by the top of the deck to the critical point of the instrument - maybe I'm missing it or another part of the system is taking care of this but I don't see this being taken into account.

2023-06-20 16:01 UTC, vegano1 commented
Nice, looks good but left a question.
Also, this affects the basic functions we use for module calibration so we should probably make sure that still works.
You can use [this](https://github.com/Opentrons/opentrons/blob/edge/hardware-testing/hardware_testing/scripts/module_calibration.py) HTTP script to perform a full module calibration as if you were the client.

2023-06-21 18:15 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +            if not labware_validation.validate_definition_is_adapter(below_definition):
this might be bc of indentation but I am a bit confused. why do we need to validate if a `ModuleLocation` is an adapter?

2023-06-21 18:26 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/modules.py
>      def get_connected_model(self, module_id: str) -> ModuleModel:
maybe we should change this to 
```suggestion
    def get_loaded_model(self, module_id: str) -> ModuleModel:
```

2023-06-21 18:30 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/types.py
> +    """The location of something placed atop another labware."""
is this something or a labware?

2023-06-21 18:35 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/types.py
> +            return NotImplemented
can we add a description for this exception?

2023-06-21 18:49 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +    def raise_if_labware_is_not_on_top(self, labware_id: str) -> None:
can we change this method name? I find this very confusing. maybe we can do something like:
```suggestion
    def raise_if_labware_has_labware_on_top(self, labware_id: str) -> None:
```

really hard finding names for this PR ;-)

2023-06-21 18:53 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +    def raise_if_labware_is_not_on_top(self, labware_id: str) -> None:
```suggestion
    def raise_if_labware_has_labware_above(self, labware_id: str) -> None:
```

!!!

2023-06-21 18:58 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/move_labware.py
>          empty_new_location = self._state_view.geometry.ensure_location_not_occupied(
sorry for the nip but it can also be a OnLabwareLocation correct? can we change the var name to `move_location` or something like that?
```suggestion
        empty_new_location = self._state_view.geometry.ensure_location_not_occupied(
```

2023-06-21 20:39 UTC, TamarZanzouri requested changes
didn't finish it all but its a good start. these changes are really really good! just a bunch of questions/suggestions.

2023-06-22 13:46 UTC, jbleon95 commented on api/src/opentrons/protocol_engine/state/labware.py
> +            if not labware_validation.validate_definition_is_adapter(below_definition):
It's validating if the labware that's sitting on a module is an adapter, for the reason that the only two "labware" you can place in a module is a labware on top of an adapter. This logic prevents two labwares from being placed on a module. The below check will prevent two labware from sitting on an adapter

2023-06-22 13:59 UTC, jbleon95 commented on api/src/opentrons/protocol_engine/types.py
> +            return NotImplemented
It's not an exception, it's returning a built-in that's recommend for dunder methods https://docs.python.org/3.7/library/constants.html#NotImplemented

2023-06-22 14:57 UTC, jbleon95 commented on api/src/opentrons/protocol_api/core/engine/deck_conflict.py
> +        # TODO(jbl 2023-06-08) check if we need to do any logic here or if this is correct
this will be addressed in the PAPI implementation ticket/PR

2023-06-22 14:59 UTC, jbleon95 commented on api/src/opentrons/protocol_engine/state/labware.py
> +    def raise_if_labware_cannot_be_stacked(
There's currently no designated hard limit, but the current shared definition data does not have any labware that can stack with itself, i.e. any arbitrarily tall stacking, only labware on top of specific adapters. A limit, whether it is a set number of labware and/or based on labware height, will be added when that feature is officially added.

2023-06-22 15:14 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +            if not labware_validation.validate_definition_is_adapter(below_definition):
This makes more sense! thank you for explaining that!

2023-06-22 15:16 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/types.py
> +            return NotImplemented
good to know! thank you!

2023-06-22 15:33 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +                display_name = None
is this meant to be None? can we not use the labware definition display name? I just wonder what this used for in the UI

2023-06-22 15:35 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +        if isinstance(parent, OnLabwareLocation):
Nice!

2023-06-22 15:39 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/modules.py
>      def get_connected_model(self, module_id: str) -> ModuleModel:
not for this pr

2023-06-22 15:42 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/commands/test_move_labware.py
> +        state_view.labware.raise_if_labware_is_not_on_top("my-even-cooler-labware-id"),
hahaha

2023-06-23 08:04 UTC, sanni-t approved these changes
This looks really great! I'm good with merging this so that the API work is unblocked.
I have a few minor suggestions coming up (mostly naming & comments) but we can address them in a later PR.

2023-06-23 08:04 UTC, sanni-t commented on api/src/opentrons/protocol_engine/commands/load_adapter.py
> +            )
Hmm, it sucks that we have to do this validation *after* the labware is loaded. Let's leave a comment to see if we can validate before loading

2023-06-23 14:17 UTC, TamarZanzouri approved these changes
Beautiful! Thank you for your changes!

2023-06-23 14:41 UTC, merged