feat(harwdare): add acceleration to pick up tip for 96 channel
OpenTrons/opentrons-api pull request #12944
Opened 2023-06-21 18:00 UTC by caila-marashaj

2023-06-23 15:01 UTC, Laura-Danielle requested changes
We talked on slack about it, but you need to make sure you're essentially mimicking what `ot3_utils::create_move_group` does for the tip action steps. Otherwise you won't be moving the motors correctly.

2023-06-23 15:01 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +            for block in blocks:
we should pass moves into the backend tip action

2023-07-07 15:37 UTC, Laura-Danielle requested changes
Initial comments.

2023-07-07 15:37 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        self._gear_motor_position: float
why doesn't this default to anything?

2023-07-07 15:37 UTC, Laura-Danielle commented on hardware/opentrons_hardware/firmware_bindings/messages/payloads.py
> +    current_position: utils.UInt32Field
We can still have position flags here imo, it would just be related to boot-up only.

2023-07-07 15:37 UTC, Laura-Danielle commented on hardware/opentrons_hardware/firmware_bindings/messages/payloads.py
> +    seq_id: utils.UInt8Field
This should all be included in the `MoveCompletedPayload` so we don't need these values.

2023-07-07 15:37 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/motion.py
> -    stop_condition = (
This change isn't really necessary.

2023-07-07 15:37 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +            print(f"expected tip motors = {self._expected_tip_action_motors}")
print statement here.

2023-07-07 15:37 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +            print(f"removing {node_id}, {seq_id}")
print statement here

2023-07-07 15:37 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/motor_position_status.py
> +                # TipActionResponse.message_id,
accidental add here?

2023-07-07 15:37 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/motor_position_status.py
> +                float(response.payload.current_position.value),
accidental change?

2023-07-07 15:37 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/motor_position_status.py
> +    with WaitableCallback(can_messenger, _listener_filter) as reader:
You can use `MultipleMessagesWaitableCallback`. See `get_motor_position` above. It will make the code much cleaner.

2023-07-07 15:37 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/motor_position_status.py
> +                raise RuntimeError(
I think we should only be checking for a timeout error in this function. We should ensure that the motor position flag is set to `not OK` if the two gear motor positions don't match though.

2023-07-07 15:37 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> -            if isinstance(completion, TipActionResponse):
We need this there otherwise it will mess up the plunger position. We will have to keep track of the tip action positions separately.

2023-07-07 15:37 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +                    self._expected_tip_action_motors.append(
this change is also not necessary.

2023-07-07 15:37 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        if updated_successfully:
This function shouldn't return anything, only update `_gear_motor_position`

2023-07-07 15:37 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> -        if OT3Axis.Q in checked_axes:
We should be updating the position here and also why did we remove the tip action from the home command? We need to handle the use-case where a home command is called without any parameters.

2023-07-07 15:37 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    ) -> None:
imo this should still just be one function. Let the utility function handle any difference between passing acceleration or not.

2023-07-19 11:19 UTC, Laura-Danielle reviewed
Some more comments.

Mainly, it looks like you aren't handling the multiple types of responses you can now get from the 96 channel and there is some general code structure cleanup requests.

You should also make this PR not a draft and add a PR description please once you've finished those requests.

2023-07-19 11:19 UTC, Laura-Danielle commented on hardware/tests/opentrons_hardware/hardware_control/test_move_group_runner.py
> +async def test_tip_action_move_runner_receives_response(
We are still receiving multiple responses from the tip action request. We should have a test that captures that.

In fact, we should expand on this test to mimic all the varying responses you can get from a tip action (i.e. if it's an acceleration move, then 3 responses for each motor) or if it's a regular home then just two responses.

2023-07-19 11:19 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +            self._expected_tip_action_motors[seq_id].remove(gear_id)
Didn't you need to modify this to handle the varying responses you'd get back from the gear motors?

2023-07-19 11:19 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/motor_position_status.py
> +    with WaitableCallback(can_messenger, _listener_filter) as reader:
Bump on this comment.

2023-07-19 11:19 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/motor_position_status.py
> +                raise RuntimeError(
Bump on this comment.

2023-07-19 11:19 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/test_ot3_api.py
> +        # await ot3_hardware.cache_instruments()
is this comment meant to be here, or did this somehow leak in from a rebase maybe?

2023-07-19 11:19 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/test_ot3_api.py
> +        # await ot3_hardware.cache_instruments()
This is what the test looks like in edge:

```
    with patch.object(
        ot3_hardware.managed_obj._backend,
        "get_tip_present",
        AsyncMock(spec=ot3_hardware.managed_obj._backend.get_tip_present),
    ) as tip_present:
        pipette_config = load_pipette_data.load_definition(
            PipetteModelType("p1000"),
            PipetteChannelType(96),
            PipetteVersionType(3, 3),
        )
        instr_data = AttachedPipette(config=pipette_config, id="fakepip")
        await ot3_hardware.cache_pipette(OT3Mount.LEFT, instr_data, None)
        await ot3_hardware._configure_instruments()
        await ot3_hardware.pick_up_tip(OT3Mount.LEFT, 60)

        tip_present.assert_not_called()
 ```

2023-07-19 11:19 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/test_ot3_api.py
> +        if configs["channels"] == 96:
why do we need this change?

2023-07-19 11:19 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/test_ot3_api.py
> +        if configs["channels"] == 96:
same here

2023-07-19 11:19 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +                drop_target_dict = {Axis.Q: move.target_position}
nit: this is in pick up tip so should be called `pickup_target` etc

2023-07-19 11:19 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +                await self.home_gear_motors()
Let's not use this function. We should be able to use tip action just like we previously did in this function just with kwargs now instead.

For example, 

```
  await self._backend.tip_action(
      [Axis.of_main_tool_actuator(mount)],
      distance=move.target_position + move.home_buffer,
      velocity=move.speed,
      tip_action="home")
```

2023-07-19 11:19 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +    async def home_gear_motors(self) -> None:
We should remove this function completely.

2023-07-19 11:19 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +            await self.home_gear_motors()
Same feedback applies here as in `pick_up_tip`.

2023-07-19 11:19 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +                Axis.P_L
You should change Axis.P_L to -> `[Axis.of_main_tool_actuator(mount)]`. Gives us wiggle room in the off chance hardware decides to change what mount this can attach to.

2023-07-19 11:19 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +        if self._gantry_load == GantryLoad.HIGH_THROUGHPUT:
This check should only be in `def refresh_positions`.

2023-07-19 11:19 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> +    async def home_gear_motors(
We shouldn't need this function.

2023-07-19 11:19 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            assert moves is not None
You should almost never do asserts in runtime code. It's very confusing when it raises as an error.

Here we should instead check that you have either moves or distance/velocity (with if checks). If it's distance/velocity then you need to modify the speed to be negative one.

2023-07-26 16:53 UTC, ahiuchingau requested changes

2023-07-26 16:53 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        moves: Optional[List[Move[Axis]]] = None,
What happens when this function is called without moves nor distance/velocity? 

Instead of making these three args optional, we should probably separate them into two functions, one requiring moves and the other both distance and velocity

2023-07-26 18:01 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        moves: Optional[List[Move[Axis]]] = None,
We could also just raise an error.

2023-07-26 18:29 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        moves: Optional[List[Move[Axis]]] = None,
That's fine by me

2023-07-26 18:32 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        moves: Optional[List[Move[Axis]]] = None,
Let's just raise an error for now but fix it Soon

2023-07-26 19:21 UTC, fsinapi requested changes
We should definitely rename the `UpdateGearMotorPositionEstimation` command and make sure the implementation of it just pulls the current position.

2023-07-26 19:21 UTC, fsinapi commented on hardware/opentrons_hardware/firmware_bindings/messages/message_definitions.py
> +class UpdateGearMotorPositionEstimationRequest(EmptyPayloadMessage):  # noqa: D101
I really don't think we should have these message definitions. The point of the `UpdateMotorPositionEstimation` message for the other axes is to set the open loop stepper accumulator based on the encoder position. Since there's no encoder on the gear motors, there's no benefit to having a dedicated message for this.

If the goal is just to be able to read the motor position, we should rename this to something like `GearMotorPositionRequest`

2023-07-27 14:15 UTC, sfoster1 approved these changes
A couple nitpicks but really solid!

2023-07-27 14:15 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
>      async def tip_action(
add a TODO to split this up pls

2023-07-27 14:15 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        assert any([moves, distance and velocity])
this allows all three to be set, which we don't want. you really want `bool(moves) xor (bool(distance) and bool(velocity))`

2023-07-27 14:15 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        if NodeId.pipette_left in positions:
if it isn't in positions then something's gone wrong, right? we should log that

2023-07-27 16:54 UTC, merged