feat(build): update the VERSION.json file whenever we manually push.
OpenTrons/opentrons-api pull request #12949
Opened 2023-06-21 20:51 UTC by vegano1

# Overview

It can get confusing knowing what version of each python package the flex has whenever we are developing, to keep things in sync this pr will update the `/etc/VERSION.json` file whenever a package is pushed to the robot.

# Test Plan

- [ ] Make sure top-level and individual target push works on MacOS
- [ ] Make sure top-level and individual target push works on Linux
- [ ] Make sure top-level and individual target push works on Windows
- [ ] Make sure openembedded builds are not affected by this change
- [ ] Make sure that buildroot builds are not affected by this change

# Changelog

- Added `sync-version-file` function to push.mk to update the VERSION.json file with a new entry
- Updated all packages to use new `sync-version-file` function
- Updated `scripts/python_build_utils.py` so it now gets the branch name if available

# Review requests

- Does this make sense?
- Anything that stands out?

# Risk assessment
Med, 
- The `scripts/python_build_utils.py` script is used by both openembedded and buildroot build systems and needs to be tested
- The push.mk script is used as part of the development workflow and needs to be tested across all supported platforms

2023-06-22 14:06 UTC, sfoster1 requested changes
Looks good overall but we have those extra files checked in and i'm a little nervous about the `python_build_utils` change - we sould make sure it doesn't break buildroot.

2023-06-22 14:06 UTC, sfoster1 commented on api/somefile.test
> +{robot_type: OT-3 Standard, build_type: develop, openembedded_version: v0.2.4-15-gcb31ffd, openembedded_sha: cb31ffdb18882dd9db6642630a983a2a2f2b43d9, openembedded_branch: store-logs-better-changes,
accidental checkins?

2023-06-22 14:06 UTC, sfoster1 commented on notify-server/Makefile
> +	$(call restart-server,$(host),,$(ssh_opts),"opentrons-robot-server")
this wants the version file change too right?

2023-06-22 14:06 UTC, sfoster1 commented on scripts/python_build_utils.py
> +    branch_name = subprocess.check_output(
see the comment below - this code is used in, among other places, the buildroot build process for the OT-2. that process runs inside aws codebuild, where we're in a detached-HEAD state and there is no branch information. you can simulate this by doing a `git checkout` of a commit hash. we should make sure that this function behaves sanely in this case

2023-06-22 14:46 UTC, vegano1 commented on scripts/python_build_utils.py
> +    branch_name = subprocess.check_output(
yep, that's why we are now checking for this case explicitly
if we are in a detached head then we won't have a branch name and then nothing changes
if we are not in a attached head branch_name will be populated, then we try and match it on line 115

2023-06-22 18:56 UTC, vegano1 commented on notify-server/Makefile
> +	$(call restart-server,$(host),,$(ssh_opts),"opentrons-robot-server")
yeah this happens on `push-no-restart-ot3` (line 138)

2023-06-23 17:55 UTC, sfoster1 approved these changes
Looks great to me!

2023-06-23 20:00 UTC, merged