feat(shared-data): Support quirks, mount and mutable configs in v2 pipettes
OpenTrons/opentrons-api pull request #12966
Opened 2023-06-23 13:40 UTC by Laura-Danielle

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-06-27 13:13 UTC, sfoster1 requested changes
I don't think I agree with putting the quirks in code like this. It means if we ever want to add some new model we have to add it in conceptually separate places. If we can drop it in configs then we're back to the same system and I think we're fine.

2023-06-30 14:10 UTC, sfoster1 requested changes
This overall looks, well, like something we have to do, but I really want to avoid duplicating that `IS_ROBOT` bool - I think that will eternally bite us if we duplicate it.

2023-06-30 14:10 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/pipette/file_operation_helpers.py
> +    IS_ROBOT = bool(
I don't think it's a good idea to duplicate this logic here - it's already complicated and messy and I don't want to have to remember an extra place to put it. I think that this function shouldn't exist and the things that call it should instead take a base dir as an argument. Yes, that makes the calls messier, but if we can provide a consistent place to get that information - i.e., `opentrons.config` - then it'll be okay enough that it's worth not duplicating.

2023-06-30 14:10 UTC, sfoster1 commented on robot-server/robot_server/service/legacy/routers/settings.py
> +    # need model and name?
won't this break without it?

2023-06-30 14:10 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +def load_serial_lookup_table() -> Dict[str, str]:
Oof, but what are you gonna do

2023-06-30 14:10 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/pipette/mutable_configurations.py
> +    # FIXME remove the validation here for the file save and rely
i guess we can do this by passing down a full pydantic model at this point?

2023-07-03 13:16 UTC, Laura-Danielle commented on robot-server/robot_server/service/legacy/routers/settings.py
> +    # need model and name?
Not sure which is why I want to test on a robot. I don't know why it _would_ break because the app only deals with the model for this feature.

2023-07-03 13:16 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +def load_serial_lookup_table() -> Dict[str, str]:
big oof.

2023-07-03 13:19 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/file_operation_helpers.py
> +    IS_ROBOT = bool(
big oof.

2023-07-06 16:56 UTC, sfoster1 requested changes
Okaym, I really like the changes to get the base directory passed in and decided elsewhere, the lack of duplication is great. I think the last thing I'd really want to see is fixes to the HTTP API and the tavern tests. Those tests are for detecting regressions, and I think that this PR introduces changes both of value and of kind (not having names) that we really need to investigate and probably fix.

2023-07-06 16:56 UTC, sfoster1 commented on robot-server/robot_server/service/legacy/routers/settings.py
> +    # need model and name?
Can we add it anyway? Regardless of whether it's _needed_, this is in theory a controlled API and this would represent a change.

2023-07-06 16:56 UTC, sfoster1 commented on robot-server/tests/integration/test_settings_pipettes.tavern.yaml
> +# I tried to timebox this and couldn't come up with a good solution.
What we have done in other cases is make a separate fixture used by tavern. I think we really want this test in before we merge.

2023-07-06 16:56 UTC, sfoster1 commented on robot-server/tests/integration/test_settings_pipettes.tavern.yaml
>  stages:
Why did all these values change? The same issue with directories not being respected?

2023-07-06 19:43 UTC, Laura-Danielle commented on robot-server/tests/integration/test_settings_pipettes.tavern.yaml
> +# I tried to timebox this and couldn't come up with a good solution.
So that fixture actually doesn't work across tests. It just so happens to be OK for the other tavern tests even though they are accessing the file system locally.

For this test specifically, the folder it's checking for already has a lot of junk (including pipette serial numbers that would never exist in the folder). I could raise an error in this case, rather than a KeyError, but the test would still fail all the same.

So essentially all of these tavern tests relying on a tmp dir aren't actually doing that. I tried figuring out a way to manipulate the env variable for tavern and couldn't successfully do that. The ultimate problem is that tavern does not see the modifications to the environment variables from pytest fixtures so even though we're adding OT_CONFIG_DIR in the pytest fixture, it doesn't exist at the time of the `GET` request.

2023-07-06 19:46 UTC, Laura-Danielle commented on robot-server/tests/integration/test_settings_pipettes.tavern.yaml
>  stages:
I changed the ID to be a realistic ID since we have to look up the configs by valid pipette names rather than the random test names we've been using.

2023-07-07 16:31 UTC, sfoster1 approved these changes
Awesome! Looks really good

2023-07-10 18:37 UTC, sanni-t approved these changes
Tested on an OT-2 and confirmed that pipette settings & quirks changes from app are propagated correctly to the settings files on the robot and the app reads file contents correctly. Also verified that all changes are correctly reset to default with 'Reset All'.

2023-07-11 12:25 UTC, merged