fix(hardware): clear move group when the expected stall is detected
OpenTrons/opentrons-api pull request #12986
Opened 2023-06-26 21:46 UTC by ahiuchingau

# Overview
The expected-stall move group times out whenever a stall is detected before the final move block, even though this is an acceptable behavior. This fixes it by clearing and finishing the move group whenever a move block is completed with a stall.

2023-06-27 11:09 UTC, Laura-Danielle requested changes
This check looks good, but is there a way we could add a quick test for this scenario?

2023-06-27 13:28 UTC, fsinapi requested changes
I really think this should just clear out the one single _node_ from the move group, and still wait until every node has reported that it's done. The way this is written, other axes could still be moving after the one axis reports its stall, and the robot could move on and start a new move before they stop moving.

2023-06-27 20:57 UTC, sfoster1 requested changes
The more I think about it, I think we don't want to do this _only_ if the stop condition is stall - I think this should happen any time we're `stopped_by_condition` no matter what the condition is

2023-06-27 20:57 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +                and ack_id == MoveAckId.stopped_by_condition
I think we might want this to just be `ack_id == MoveAckId.stopped_by_condition` whether or not the stop condition is stall; I think you're going to get similar behavior from home commands, including the home backoffs, and the tip action motors, and definitely the stop-on-sync commands from calibration

2023-06-27 20:58 UTC, fsinapi approved these changes
Nice, LGTM!

2023-06-27 21:00 UTC, ahiuchingau commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +                and ack_id == MoveAckId.stopped_by_condition
You're right!

2023-06-27 22:06 UTC, sfoster1 approved these changes
Nice, thank you!

2023-06-28 08:01 UTC, Laura-Danielle approved these changes
ty looks good to me!

2023-06-29 16:56 UTC, merged