feat(hardware): Hardware error codes
OpenTrons/opentrons-api pull request #13009
Opened 2023-06-28 20:58 UTC by sfoster1

Now that we can express error codes in all our client interfaces, let's start raising them.

This PR makes the `opentrons_hardware` module use the new exceptions that have the new error codes. There's a couple new error codes, but mostly all this does is raise different exceptions in the same places.

The two exception is in the can messenger and the movegrouprunner.

### CAN Messenger
The CAN messenger has this asyncio task that reads stuff asynchronously from the bus and passes it to registered listeners. In addition, if a message is an error message it would raise an exception. But, it's a task, so that exception doesn't go anywhere. #12963 made this exception just logged and swallowed but, like... why does it exist? So we removed it.

### MoveGroupRunner
A similar issue happens in MoveGroupRunner, where a background task accumulates responses and then pops them on over to the caller. This works the same now, but we can also move the move stop condition checking inside that loop. We can also now properly handle having multiple errors in a move group!

**Note**: You need to run `make setup-py` again since now hardware depends on shared-data.

## Review Requests
- Give a skim over most stuff
- Look more in-depth at MoveGroupRunner and at CANMessenger

## Testing
- [ ] Cause some errors and maek sure it doesn't break in new ways.

2023-06-30 15:07 UTC, ahiuchingau requested changes
Some general questions and i think we need to raise an extra TimeourError in the MoveScheduler

2023-06-30 15:07 UTC, ahiuchingau commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +        raise CanbusCommunicationError(
Just a general question: We are raising the `CommandTimedOutError` in the send threshold listener if the sensor scheduler didn't get a response back. Are we expecting to see both the `CommandTimedOutError` and `CanbusCommunicationError` if the listener does time out?

2023-06-30 15:07 UTC, ahiuchingau commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +                raise MoveConditionNotMetError(detail={"group-id": str(group_id)})
I don't think we'll need to raise `MoveConditionNotMetError` there as we have already appended it to`self._errors` in `_handle_move_completed()`

2023-06-30 15:07 UTC, ahiuchingau commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
>                  )
This TimeoutError should be raised now (I got it in internal-release_0.13.0 but not edge)

2023-06-30 15:07 UTC, ahiuchingau commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +                        "Motion failed with multiple errors", wrapping=self._errors
AMAZING

2023-06-30 15:07 UTC, ahiuchingau commented on hardware/opentrons_hardware/drivers/can_bus/can_messenger.py
> +                        handled = True
Is it possible that we could get in a state where a listener accepts an error message but for whatever reason, it doesn't have an error handling method and hence not raise it? 

In that case, would this error message just be thrown away since the can messenger thinks it was handled by a listener?

2023-06-30 15:16 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +        raise CanbusCommunicationError(
No, you'd only see the timeout error since we're not catching and ignoring it. I think the only time you'd see this getting raised is if the microcontroller responded with `threshold=0`

2023-06-30 15:18 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +                raise MoveConditionNotMetError(detail={"group-id": str(group_id)})
Then this code won't run, right? because `if self._errors` will run? I think this clause might not necessarily have to exist or at least be a weird generic catchall though, maybe it should just be a general error

2023-06-30 15:21 UTC, sfoster1 commented on hardware/opentrons_hardware/drivers/can_bus/can_messenger.py
> +                        handled = True
Yup. All I can really say is, like, "don't do that"

2023-06-30 15:28 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
>                  )
I think that I don't want to _add_ that in this PR - I want your commit in its entirety. So I think that either we can merge this now as is and re-add it after yours merges (and, we're going to have a lot of fixups for errors added since 0.13.0 diverged from edge, so it won't be unique) or wait on this PR until 0.13.0 gets merged back.

2023-07-05 13:32 UTC, vegano1 commented on hardware/opentrons_hardware/drivers/can_bus/can_messenger.py
> +        try:
What restarts this task now if we have an exception?

2023-07-05 14:07 UTC, vegano1 commented on hardware/opentrons_hardware/firmware_update/run.py
> +                USBTarget.rear_panel,
is this guaranteed to always be the rear panel?
maybe so, since its the only USB update target for now

2023-07-05 14:23 UTC, vegano1 approved these changes
This is great!
Is there a follow-up pr on the robot-server side to handle any of these errors getting propagated?

2023-07-06 16:59 UTC, sfoster1 commented on hardware/opentrons_hardware/drivers/can_bus/can_messenger.py
> +        try:
Huh good catch I guess this PR was old enough that it missed those changes

2023-07-06 16:59 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_update/run.py
> +                USBTarget.rear_panel,
Right now yeah... I should really rework it to not do this though

2023-07-06 16:59 UTC, sfoster1 commented
> This is great! Is there a follow-up pr on the robot-server side to handle any of these errors getting propagated?

Nope, that one was already merged. All the structures to forward these errors should already be in place in robot server and protocol engine.

2023-07-06 18:34 UTC, sfoster1 commented on hardware/opentrons_hardware/drivers/can_bus/can_messenger.py
> +        try:
Should be fixed @vegano1

2023-07-10 20:56 UTC, ahiuchingau approved these changes

2023-07-10 21:09 UTC, merged