Rqa 601 protocol cancelled by estop gets stuck
OpenTrons/opentrons-api pull request #13008
Opened 2023-06-28 20:51 UTC by TamarZanzouri

# Overview

closes https://opentrons.atlassian.net/browse/RQA-601.
raise an e-stop activated from the hardware layer and catch it in PE. 

# Test Plan

- Tested with python protocols and json protocols on an OT-3. works as expected. 
- Need to raise a runtime exception somehow on an OT-2 and make sure the error handling has not changed.

# Changelog

- Raise an `EStopActivatedError` from `hardware_controller`.
- Raise an `PE_EStopActivatedError` from the `command_executer` when we catch an exception while running a command.
- Wrap the child thread exception with a `_ErrorOccurrenceFromChildThread` and add logic to extract the Exception from it in the `CommandsView`. 

# Review requests

Do you have a better name for `_ErrorOccurrenceFromChildThread`?
Changes make sense?
Add more tests? 
Are you concerned from the errors raised now. 

# Risk assessment

Medium. changing the way we bubble up python/json protocol exceptions. need to smoke test on OT-2 and OT-3.

2023-07-11 18:38 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/actions/actions.py
> +    error: Union[ProtocolEngineError, EnumeratedError]
use EnumeratedError

2023-07-11 18:41 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/execution/command_executor.py
> +            elif not isinstance(error, EnumeratedError):
strip the pythonExcption message

2023-07-11 18:44 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/commands.py
> +                error=ProtocolCommandFailedError(
do not wrap in the error in ProtocolCommandFailedError

2023-07-11 20:29 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/errors/error_occurrence.py
> +class ProtocolCommandFailedError(ProtocolEngineError):
I hate that this has to move bc of circular dependencies. should we just add a new error?

2023-07-11 20:30 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/commands.py
> +
```suggestion
```

2023-07-11 20:32 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/commands.py
> +                        self._state.errors_by_id[error_id] = error_occurrence
```suggestion
                        self._state.errors_by_id[error_id] = action.error_details.error.original_error
```

2023-07-11 21:37 UTC, sfoster1 requested changes
Some small things to change but overall looks great.

I think the followup we should do is to get rid of this thing where we have to wrap `ErrorOccurence` instances in exceptions. THat's the cause of a lot of annoying wrapping and breaking of the structured exception metaphor, and it feels wasteful anyway because after those exceptions do their immediate jobs (i.e. stopping python protocol execution) they get... turned right back into error occurrences, except now with a lot of missing detail.

Let's (as you have commented) make `get_all_commands_final()` return some tristate enum of `RUNNING`, `STOPPED_OK`, `STOPPED_ERROR` or even `None` (running), `True` (done ok), and `False` (done with error) and have callers check for errors on the stored commands afterwards. This isn't a TOCTOU or race because it only returns these statuses once we're in `stopped` and we can't go back. It means we don't have to make this exception anymore, and we don't need to smush it in there.

Let's also do something similar at the layer above the python protocol execution, so we can take the contextual information out of the exception that we raise from the transport - including in the command line runners. The exception needs to exist to interrupt execution, sure, but as long as it's a stable type we can catch it special and go and investigate the state store for the actual error from there.

And that will rule! And fix the last little weird things in here. But again, overall looks good.

2023-07-11 21:37 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/errors/error_occurrence.py
> +class ProtocolCommandFailedError(ProtocolEngineError):
As we talked about in offline review - I think we should refactor this in another PR so `ProtocolCommandFailedError` doesn't need to carry the ErrorOccurrence with it, which will fix the circular error

2023-07-11 21:37 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/errors/exceptions.py
> +        """Build a PIpetteNotAttachedError."""
```suggestion
        """Build an EStopActivatedError."""
```

2023-07-11 21:37 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +                    ErrorCodes.E_STOP_ACTIVATED.value.code == wrapped_error.errorCode
this seems like a good thing to factor into a free function in `opentrons_shared_data.errors` - like a `def code_in_exception_stack(exc: EnumeratedError)`, I could see us using it in more places (and having a typescript equivalent, eventually)

2023-07-11 21:37 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/commands.py
> +                    # TODO(tz, 7-11-23): avoid raising an error and return the status instead
💯

2023-07-11 21:37 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +    def _raise_exception_from_error(
This shouldn't be necessary I think. It's handled by the call to [`raise_from_error_message`](https://github.com/Opentrons/opentrons/blob/edge/hardware/opentrons_hardware/errors.py#L77)  [here](https://github.com/Opentrons/opentrons/blob/5394203ff9e6e225dcb59bc5b608b4b30e1ec157/hardware/opentrons_hardware/hardware_control/move_group_runner.py#L414)

2023-07-11 21:37 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +                    self._raise_exception_from_error(group_id=group_id, error=self._errors[0])
ditto here - should be handled by `raise_from_error_message` putting an exception instance into `self._errors`, and then getting raised from here anyway.

2023-07-11 21:37 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/errors/exceptions.py
> +            message="\n".join(format_exception_only(type(exc), exc)).strip(),
yessss

2023-07-12 00:47 UTC, TamarZanzouri commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +    def _raise_exception_from_error(
nice! I believe this was introduced in your pr :-)

2023-07-12 18:58 UTC, sfoster1 requested changes
Looks good though we need to get rid of that `print` hence the change request.

2023-07-12 18:58 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +            print(error)
stray diagnostic print

2023-07-12 18:58 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +    # TODO(tz, 7-12-23): move this to shared data when we dont relay on ErrorOccurrence
maybe make a note on the definition of `ProtocolCommandFailedError` to move this when we change that exception class?

2023-07-12 18:58 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/commands.py
> +                        if not isinstance(
nit: could flip these cases and then lose the explicit annotation and have only positive conditions

2023-07-12 19:00 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +            print(error)
```suggestion
```

2023-07-12 19:00 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +            print(error)
thank you!

2023-07-12 19:01 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +    # TODO(tz, 7-12-23): move this to shared data when we dont relay on ErrorOccurrence
yessssss good call!

2023-07-12 19:01 UTC, sfoster1 approved these changes
Looks good! Nice work!

2023-07-13 21:07 UTC, merged