feat(api): load adapter and load/move labware onto adapters in PAPI
OpenTrons/opentrons-api pull request #13016
Opened 2023-06-29 15:18 UTC by jbleon95

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-07-05 14:11 UTC, sanni-t commented on api/src/opentrons/protocol_api/protocol_context.py
> +            will be loaded from the same given namespace, but version will be automatically chosen.
```suggestion
        :param adapter: Load name of an adapter to load the labware on top of. The adapter
            will be loaded from the same given namespace, but version will be automatically chosen.
```

2023-07-05 14:11 UTC, sanni-t commented on api/src/opentrons/protocol_engine/errors/exceptions.py
> +
Is there a reason why we can't use `LabwareNotLoadedError` for such an error case? It doesn't seem like we raise this error when the labware we are trying to access exists but it's not on top of the labware it should be. I guess the error name is a bit confusing. No strong opinions here, just trying to understand why this error (as well as `LabwareNotLoadedOnModuleError`) was necessary.

2023-07-05 14:24 UTC, jbleon95 commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +    def _convert_non_stacked_location(
Look into refactoring this to remove duplicated code

2023-07-05 14:26 UTC, jbleon95 commented on api/src/opentrons/protocol_api/labware.py
> +    def labware(self) -> Optional[Labware]:
maybe rename?

2023-07-05 14:34 UTC, jbleon95 commented on api/src/opentrons/protocols/api_support/instrument.py
> +    location: types.Location, reject_module: bool, check_for_adapter: bool
update docstrings with arguments

2023-07-05 14:41 UTC, jbleon95 commented on api/src/opentrons/protocol_api/instrument_context.py
> +                check_for_adapter=self.api_version >= APIVersion(2, 15),
leave a comment about potential ability to do a 2.14 load labware of adapter definition and then be able to aspirate/dispense to adapter

2023-07-05 14:49 UTC, jbleon95 commented on api/src/opentrons/protocol_api/protocol_context.py
> +        elif isinstance(new_location, ModuleContext):
these two lines can be combined

2023-07-05 14:52 UTC, jbleon95 commented on api/tests/opentrons/conftest.py
> +            api_version=APIVersion(2, 15),
make this MAX_SUPPORTED_API

2023-07-05 15:24 UTC, ecormany requested changes, later dismissed
A few typos and tweaks for docstrings that publish to the PAPI docs site.

2023-07-05 15:24 UTC, ecormany commented on api/src/opentrons/protocol_api/labware.py
> +    def labware(self) -> Optional[Labware]:
`child` or `child_labware`?

2023-07-05 15:24 UTC, ecormany commented on api/src/opentrons/protocol_api/labware.py
> +                          Opentrons app.
```suggestion
                          Opentrons App.
```
🧐

2023-07-05 15:24 UTC, ecormany commented on api/src/opentrons/protocol_api/module_contexts.py
> +        :returns: The initialized and loaded labware object.
`adapter object`?

2023-07-05 15:24 UTC, ecormany commented on api/src/opentrons/protocol_api/protocol_context.py
> +        :param adapter_def: The adapter's labware definition to load
```suggestion
        :param adapter_def: The adapter's labware definition.
```
maybe

2023-07-05 15:24 UTC, ecormany commented on api/src/opentrons/protocol_api/protocol_context.py
> +        to collapse the two stages of adapters initialization (creating
```suggestion
        to collapse the two stages of adapter initialization (creating
```

2023-07-05 15:24 UTC, ecormany commented on api/src/opentrons/protocol_api/protocol_context.py
> +        to the location specified by `location`.
```suggestion
        This function loads the adapter definition specified by ``adapter_def``
        to the location specified by ``location``.
```
arr ess teeeeeeee

2023-07-07 16:32 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +        load_location = self._convert_non_stacked_location(location=location)
sorry for the nip but can we call this `_get_non_stacked_location`? this name is very confusing to me

2023-07-07 17:51 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/labware.py
> +    def child_labware(self) -> Optional[Labware]:
I feel like `.labware` makes more sense in being consistent with ModuleContext. what if we call in `.child`? I feel like this makes more sense in the relationship with `.parent` and is also being used in other common languages

2023-07-07 18:57 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/labware.py
> +    def get_id_by_labware(self, labware_id: str) -> str:
should this be `get_loaded_labware_id` ? not critical we can leave as is

2023-07-07 18:59 UTC, TamarZanzouri commented on api/src/opentrons/protocols/api_support/instrument.py
> +    location: types.Location, reject_module: bool, check_for_adapter: bool
sorry one more nitpick! can we change `check_for_adapter` to `reject_adapter` for consistent?

2023-07-07 19:03 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_api/core/engine/test_labware_core.py
> +@pytest.mark.parametrize(
lets add one more that is not an adapter?

2023-07-07 19:11 UTC, TamarZanzouri requested changes
beautiful work! I am ready to approve this! a few small suggestions but this is good to go!

2023-07-10 19:34 UTC, TamarZanzouri approved these changes
Thank you for addressing the changes. love it!

2023-07-10 19:35 UTC, merged