feat(api): support overpressure monitoring for multiple mounts
OpenTrons/opentrons-api pull request #13021
Opened 2023-06-30 10:33 UTC by Laura-Danielle

# Overview

This is a follow-up PR to the comments on #12864 regarding a few edge cases that were missed. Specifically from @andySigler:

> There are two scenarios where pressure should be monitored but it is not yet as currently implemented:

> prepare for aspirate
> api.home()
> Might be easier to manage all these cases if the pressure monitoring was instead happening inside OT3Controller.home() and OT3Controller.move(), and it's called whenever a plunger axis is passed in as an argument, but we could save that for a followup PR.

# TODO

- Add support for different sensor ids

# Test Plan

- [ ] Execute a protocol with a few pipetting functions (i.e. aspirate/dispense/blowout/drop tip) and verify via the serial log or CAN logs that a bind request for max threshold is sent. To ease testing, you can also tell the request to log so you can see the pressure values being print to screen.
- [ ] Using monitor sensors, determine a sufficient occlusion material (maybe a piece of cloth?) to get it to exceed 3.9kpa. This should cause the firmware to throw and error and stop all movement.

# Changelog

- Move the monitor sensor check to the `home` command and the `move` command. We should make sure that aspirate/dispense/blowout/drop tip still throw errors in addition to prepare for aspirate and `home()`. 

# Review requests

Anything seem particularly weird and/or gross?

# Risk assessment

Medium. Modifying the behavior of monitor over pressure.

2023-06-30 14:14 UTC, sfoster1 requested changes
I think that at this point `monitor_overpressure` doesn't have to be a public method anymore; and if it's not a public method, it doesn't have to speak `Mount`s. Instead, we can make it take a list of nodes and figure stuff out itself.

Also am I missing/forgetting about from a previous PR/misreading things or where are we doing the monitoring while moving the _plunger_?

2023-06-30 14:14 UTC, sfoster1 commented on hardware/opentrons_hardware/sensors/scheduler.py
> +            # FIXME we don't quite have a way to access the sensor id
don't we have the lexically-captured `target_sensors` list?

2023-07-03 11:47 UTC, Laura-Danielle commented
@sfoster1 , @andySigler wants us to just always be monitoring the pressure sensors whenever the plunger motors are moving (regardless of tip status).

Unless I am misunderstanding your question?

2023-07-03 11:49 UTC, Laura-Danielle commented on hardware/opentrons_hardware/sensors/scheduler.py
> +            # FIXME we don't quite have a way to access the sensor id
Error messages do not contain sensor ids. If an error message is coming from the same node id (which it potentially could for the 8/96 channel) then we have no way of knowing whether the error is coming from say the back nozzle vs the front nozzle.

Make sense?

2023-07-06 15:39 UTC, andySigler approved these changes
tested on grav bot running protocol with normal tip and sealed tip. Sealed tip triggered over-pressure at expected plunger position.

2023-07-06 18:22 UTC, sfoster1 approved these changes
Looks good to me!

2023-07-06 18:22 UTC, sfoster1 commented on hardware/opentrons_hardware/sensors/scheduler.py
> +            # FIXME we don't quite have a way to access the sensor id
yup! thank you!

2023-07-07 10:23 UTC, merged