docs(api): tutorial.rst revisions for Flex
OpenTrons/opentrons-api pull request #13046
Opened 2023-07-05 18:50 UTC by jwwojak

# Overview

Suggested revisions to the [Tutorial docs](https://docs.opentrons.com/v2/tutorial.html) (`tutorial.rst` file) to include Flex code and examples. Changes include:

- Minor text revisions.
- New section "Requirements" covering the `requirements` code block.
- Using the Sphinx `..tabs::` directive to include and display OT-2 and Flex code samples and text in a compact manner.

# Test Plan

Verify that the API load name for the Flex pipette is accurate.

Requesting reviews.

# Changelog

**Hardware and Labware section**
Original uses 3 bullets and with nested bullets under a labware bullet. I think we can get rid of the nested bullets.

**Create a Protocol File**
Suggesting revision to the 1st paragraph after the `opentrons import` code sample. Trying to simplify it.

**Metadata**
Added a "Note" at the end about using the `requirements` code block.

**Requirements**
New section describes the `requirements` code block with Flex and OT-2 examples. 

**Labware**
Using tabs to display similar Flex and OT-2 information. Needs Flex deck image.

**Pipettes**
Add Flex code sample/example.

**Commands**
Add Flex code sample/example. Not updating the animated gif as it's valid for both robots.

**8-Channel Pipette**
Add Flex code sample/example.

# Review requests

- Check Flex code for accuracy.
- Give the Requirements section some attention. The info there is my best understanding of what this code block is and when it is needed. It's written as a hard requirement for the conditions described, but may not be an absolute, hard requirement (putting the API version in `requirements` instead of `metadata`).

# Risk assessment

Low. This is a change to a single docs section/page. It doesn't touch other production code.

2023-07-05 20:59 UTC, ecormany requested changes
This is good progress towards getting the Tutorial working for both Flex and OT-2! I think in general it's best to make it so when we have different code snippets for different robots, it's due to a meaningful difference — not just a different pipette variable name. Once we have all the snippets sorted, we should update the existing full protocol files and add Flex variants to the Try Your Protocol section.

2023-07-05 20:59 UTC, ecormany commented on api/docs/v2/tutorial.rst
> +- **Flex users** should review Chapter 2: Installation and Relocation (**LINK TBD**) in the instruction manual. Specifically, see the pipette information in the Instrument Installation and Calibratio
Let's just link `instruction manual` for now. And to mirror what we have for OT-2 (and to be as specific as possible), we can link to the shop page for the 1-channel. I've also updated it to use the official short name. 
```suggestion
- **Flex users** should review Chapter 2: Installation and Relocation in the `instruction manual <https://insights.opentrons.com/hubfs/Products/Flex/Opentrons%20Flex%20Manual.pdf>`_. Specifically, see the pipette information in the Instrument Installation and Calibration section. You can use either a 1-channel or 8-channel pipette for this tutorial. Most Flex code examples will use a `Flex 1-Channel 1000 μL pipette <https://shop.opentrons.com/opentrons-flex-1-channel-pipette/>`_.
```

2023-07-05 20:59 UTC, ecormany commented on api/docs/v2/tutorial.rst
> +The Flex and OT-2 use the same labware for serial dilution. The tutorial code will use the following labware definitions, but as long as you have labware of each type you can modify the code to run w
the tip racks are different for Flex/OT-2. we should either factor that out to the robot-specific sections above or load all that info into the one bullet below.

2023-07-05 20:59 UTC, ecormany commented on api/docs/v2/tutorial.rst
> +Throughout this documentation, you’ll see protocols that begin with the ``opentrons import`` statement shown above. It identifies your code as an Opentrons protocol. This statement is not required, b
`opentrons import` is not idiomatic for python users. either
```the ``import`` statement```
or
```the ``from opentrons import`` statement```

2023-07-05 20:59 UTC, ecormany commented on api/docs/v2/tutorial.rst
> +.. Suggest simplifying this paragraph
looks good, can delete the temporary comment

2023-07-05 20:59 UTC, ecormany commented on api/docs/v2/tutorial.rst
> +The ``requirements`` code block appears after the ``metadata`` code block in a Python protocol. It defines the robot model (e.g. ``Flex`` or ``OT-2``) and the API version you're using.
technically these blocks can go just about anywhere. but this is good form, so saying "it goes here" is 👍

2023-07-05 20:59 UTC, ecormany commented on api/docs/v2/tutorial.rst
> +OT-2 users working with API v2.15 (or higher) also need to specify the API version in the ``requirements`` instead of in the ``metadata``. For example:
as of right now, you can specify any `apiLevel` in metadata. the only required key in requirements is `robotType`. but we should check if that's the long-term plan.

2023-07-05 20:59 UTC, ecormany commented on api/docs/v2/tutorial.rst
> +You may notice that these deck maps don't show where the liquids will be at the start of the protocol. Liquid definitions aren’t required in Python protocols, unlike protocols made in `Protocol Desig
i think it's too advanced to put liquid defs in the tutorial, but we should link to that section of the Python docs. (it didn't exist when the Tutorial was first published!)

2023-07-05 20:59 UTC, ecormany commented on api/docs/v2/tutorial.rst
> +Next you’ll specify what pipette to use in the protocol. Loading a pipette is done with the :py:meth:`.load_instrument` method, which takes three arguments: the name of the pipette, the mount it’s in
```suggestion
Next you’ll specify what pipette to use in the protocol. Loading a pipette is done with the :py:meth:`.load_instrument` method, which takes three arguments: the name of the pipette, the mount it’s installed in, and the tip racks it should use when performing transfers. Load whatever pipette you have installed in your robot by using its :ref:`standard pipette name <new-pipette-models>`. Here’s how to load the pipette in the left mount:
```
can simplify

2023-07-05 20:59 UTC, ecormany commented on api/docs/v2/tutorial.rst
> +Since the pipette is so fundamental to the protocol, it might seem like you should have specified it first. But there’s a good reason why pipettes are loaded after labware: you need to have already l
if you think explaining the different variable names like this is awkward, we could use something like `left_pipette` instead for both robots.

2023-07-05 20:59 UTC, ecormany commented on api/docs/v2/tutorial.rst
> +Since the pipette is so fundamental to the protocol, it might seem like you should have specified it first. But there’s a good reason why pipettes are loaded after labware: you need to have already l
this will have the added benefit of letting some of the code snippets below be robot-agnostic, instead of having to provide two one-line snippets that don't really differ in function at all.

2023-07-05 20:59 UTC, ecormany commented on api/docs/v2/tutorial.rst
> +.. Possible short text to explain the animation uses OT-2 code but applies to Flex as well?
ah, dang. i have the source file and could fairly easily update the animations.

2023-07-05 20:59 UTC, ecormany commented on api/docs/v2/tutorial.rst
> +Simulation doesn’t require having a robot to your computer. You just need to install the ``opentrons`` Python module using ``pip``. This will give you access to the ``opentrons_simulate`` command-lin
```suggestion
Simulation doesn’t require having a robot connected to your computer. You just need to install the ``opentrons`` Python module using ``pip``. This will give you access to the ``opentrons_simulate`` command-line utility (``opentrons_simulate.exe`` on Windows). To see a text preview of the steps the OT-2 will take, ``cd`` to the directory where you saved your protocol file and run:
```

2023-07-05 20:59 UTC, ecormany commented on api/docs/v2/tutorial.rst
> +The simplest way to run your protocol on a Flex or OT-2 is to use the `Opentrons App <https://opentrons.com/ot-app>`_. Once you’ve installed the app and connected to your robot, navigate to the **Pro
on line 369 below: `Protocol Steps` are now called `Run Preview`. we should change the term here.

2023-07-06 13:34 UTC, jwwojak commented on api/docs/v2/tutorial.rst
> +.. Possible short text to explain the animation uses OT-2 code but applies to Flex as well?
It isn't too late. Do you want to update the animation? 

Maybe that isn't required. Even though the code here uses the OT-2 pipette variable name, the concept is the same for both robots.  Creating 2 separate image files may be more work than needed to convey the idea showing stepwise transfer of liquids. Instead, we could try some disclaimer text like this:

"The following animated images use OT-2 code, but the concepts apply to how a Flex and OT-2 transfer liquids in this tutorial."

Something like that maybe? 

There are 5 animated gifs here. Making separate images for Flex creates a total of 10 images and also multiple tabs (if we put images in those). That's a lot of extra files to maintain and more tabs may make the page look busy.

2023-07-06 13:35 UTC, jwwojak commented on api/docs/v2/tutorial.rst
> +.. Suggest simplifying this paragraph
Will remove the comment.

2023-07-06 13:40 UTC, jwwojak commented on api/docs/v2/tutorial.rst
> +Throughout this documentation, you’ll see protocols that begin with the ``opentrons import`` statement shown above. It identifies your code as an Opentrons protocol. This statement is not required, b
Will replace with "the `import` statement" as in the original.

2023-07-06 13:43 UTC, ecormany commented on api/docs/v2/tutorial.rst
> +.. Possible short text to explain the animation uses OT-2 code but applies to Flex as well?
i meant that if we went with a single pipette variable name, e.g. `left_pipette`, i could make one set of updated images. same overall complexity. just updating that little bit of text and re-exporting.

2023-07-06 14:34 UTC, jwwojak commented on api/docs/v2/tutorial.rst
> +The simplest way to run your protocol on a Flex or OT-2 is to use the `Opentrons App <https://opentrons.com/ot-app>`_. Once you’ve installed the app and connected to your robot, navigate to the **Pro
Ok. Will change to `Run Preview`.

2023-07-06 15:04 UTC, jwwojak commented on api/docs/v2/tutorial.rst
> +Since the pipette is so fundamental to the protocol, it might seem like you should have specified it first. But there’s a good reason why pipettes are loaded after labware: you need to have already l
Ah, now I understand. Yes, instead of `p300` or `p1000`, let's use `left_pipette` for the variable name. And this transfers over to the animated gif. Will update.

2023-07-06 15:27 UTC, jwwojak commented on api/docs/v2/tutorial.rst
> +.. Possible short text to explain the animation uses OT-2 code but applies to Flex as well?
Fixing this now. Change `p300` and `p1000` to `left_pipette` so we can use one code example for both robots and the animated image.

2023-07-06 16:02 UTC, jwwojak commented on api/docs/v2/tutorial.rst
> +The Flex and OT-2 use the same labware for serial dilution. The tutorial code will use the following labware definitions, but as long as you have labware of each type you can modify the code to run w
Ohhhhh, right! The 200 ul Flex tips are in the shop site but not on the labware page. URLs for the Flex and OT-2 will be different: Flex goes to "shop.opentrons.com" and OT-2 will go to "labware.opentrons.com". 

We'll use the correct API load name for each: 

- opentrons_flex_96_tiprack_200ul
- opentrons_96_tiprack_300ul

2023-07-06 18:43 UTC, jwwojak commented on api/docs/v2/tutorial.rst
> +The ``requirements`` code block appears after the ``metadata`` code block in a Python protocol. It defines the robot model (e.g. ``Flex`` or ``OT-2``) and the API version you're using.
Max suggested putting the `requirements` first, before `metadata` but also indicated order doesn't matter.

2023-07-06 18:51 UTC, jwwojak commented on api/docs/v2/tutorial.rst
> +You may notice that these deck maps don't show where the liquids will be at the start of the protocol. Liquid definitions aren’t required in Python protocols, unlike protocols made in `Protocol Desig
Good point! Will revise and update with [Labelling Liquids in Wells](https://docs.opentrons.com/v2/new_labware.html#labeling-liquids-in-wells).

2023-07-06 19:18 UTC, jwwojak commented on api/docs/v2/tutorial.rst
> +Since the pipette is so fundamental to the protocol, it might seem like you should have specified it first. But there’s a good reason why pipettes are loaded after labware: you need to have already l
Updated with `left_pipette`

2023-07-10 20:25 UTC, ecormany approved these changes
Made a couple final proofreading changes and updated some descriptions of the app UX to reflect the current version. :shipit:

2023-07-10 21:00 UTC, merged