feat(hardware): added a script write and interact with the Flex eeprom.
OpenTrons/opentrons-api pull request #13054
Opened 2023-07-06 18:27 UTC by vegano1

# Overview

We need to store the serial information for the Flex on the eeprom, this script will be used to write and verify that value along with any other data we might want to write to the eeprom.

# Test Plan

- [ ] Write the serial number a Flex and verify that the value is stored after reboot

# Changelog

- added eeprom_writter.py script to read/write/print eeprom data on the Flex

# Review requests

- usage should be straightforward but let me know if there's anything we might need

# Risk assessment

Low

2023-07-06 18:43 UTC, sfoster1 requested changes
`eeprom_writer` not `eeprom_writter` and some nits, ut otherwise looks good!

2023-07-06 18:43 UTC, sfoster1 commented on hardware/opentrons_hardware/scripts/eeprom_writter.py
> +"""This script is able to read/write to/from the Flex EEPROM.
nit: all of the detail about what arguments do should be in the argument help text instead of here so we don't have to write them twice

2023-07-06 18:43 UTC, sfoster1 commented on hardware/opentrons_hardware/scripts/eeprom_writter.py
> +        exit(1)
nit: in a script i generally prefer to get most things being exceptions rather than `sys.exit` so the functions are usable elsewhere

2023-07-06 20:56 UTC, vegano1 commented on hardware/opentrons_hardware/scripts/eeprom_writter.py
> +"""This script is able to read/write to/from the Flex EEPROM.
We print out this module doc string using the __doc__ variable as part of the argParser description whenever we pass in --help.

2023-07-07 14:58 UTC, laviera commented on hardware/opentrons_hardware/scripts/eeprom_writer.py
> +            data = b"\xff" * DEFAULT_READ_SIZE
this "data= " statement should be outside of the for loop

2023-07-07 14:59 UTC, laviera commented on hardware/opentrons_hardware/scripts/eeprom_writer.py
> +        msg = f"Error writting to eeprom: Could not clear eeprom - {msg}"
nit pick - spelling writting == writing

2023-07-07 16:29 UTC, laviera commented
@vegano1 - Should there be a "print raw" - allowing us to just dump the raw eeprom

2023-07-07 17:11 UTC, sfoster1 commented on hardware/opentrons_hardware/scripts/eeprom_writter.py
> +"""This script is able to read/write to/from the Flex EEPROM.
Yeah but `--help` will also print out the helpstring for each argument on its own, so itll be duplicated

2023-07-07 17:12 UTC, sfoster1 approved these changes
Looks good overall!

2023-07-07 17:45 UTC, merged