feat(api): use new '_flex' pipette names in engine
OpenTrons/opentrons-api pull request #13082
Opened 2023-07-11 21:27 UTC by sanni-t

# Overview

#12966 updated the Flex's pipette names from `.._gen3` to `.._flex` which created a conflict with pipette names expected by the engine & PAPI. This PR updates the engine to switch to using the new names, while adding a *temporary* backwards compatible shim to python API to convert the old names to new ones.
 
# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-07-11 21:39 UTC, SyntaxColoring approved these changes
Code changes make sense to me.

> This approach would cause existing analyses & run logs on the robot to raise errors. It would require users to reset their database. Is it okay to have to do that?

👍 Yeah, this is the same sort of thing as with #12571. If we have to have a breaking API change like this, we may as well rip off the band-aid while it's still internal.

2023-07-11 22:05 UTC, shlokamin reviewed
when running analysis on a protocol that uses a pipette load name of `p1000_single_flex` i get the following analysis error: 

```
ProtocolEngineError [line 28]: Error 4000 GENERAL_ERROR (ProtocolEngineError): UnexpectedProtocolError: 'p1000_single_flex_v1'
```

2023-07-12 08:02 UTC, Laura-Danielle requested changes
Since you already have this PR open, can you go ahead and do the requirements listed in [this ticket](https://opentrons.atlassian.net/browse/RSS-261)?

Make sure the "gen3" version of the pipettes get passed into the hardware controller.

2023-07-12 18:33 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/dev_types.py
> +    "p50_single_flex",
Let's keep the `gen3` in these dev types for now and also test on a robot w/ app to see if we need to additionally add the `_flex` models to schema v1 for pipettes (hopefully we do not).

2023-07-12 18:34 UTC, Laura-Danielle approved these changes
Approving for now, but see comment I added.

2023-07-13 18:07 UTC, sanni-t reviewed
Successfully tested pipette attach, calibration, LPC & running python protocol with `flex_8channel_1000` & `p50_single_gen3` pipettes without any issues!

2023-07-13 18:17 UTC, merged