docs(api): new_labware.rst revisions for Flex
OpenTrons/opentrons-api pull request #13096
Opened 2023-07-12 22:20 UTC by jwwojak

# Overview

Suggested text and code example revisions to the [Labware](https://docs.opentrons.com/v2/new_labware.html) API docs (`new_labware.rst` file) to include Flex code and code examples.

# Test Plan

- Checked links and cross-references to make sure they work.
- Code changes are minor. For example, adding new code samples to show labware in a Flex deck slot is just a change from `1` (OT-2) to `D1` (Flex).

# Changelog

- Added a new page introduction
- Added and revised text to define default and custom labware
- Style elements to improve content display.

**Note:** We had considered including `adapter`, a new argument for `load_labware` in this revision. After looking at it, that seems like an awkward fit and this feature might be better and more thoroughly handled by it's own page. See RLAB-343 and PR https://github.com/Opentrons/opentrons/pull/13016.

# Review requests

@ecormany 

# Risk assessment

Low risk. Code changes are minor, mostly deck slot coordinates and text.

2023-07-13 20:21 UTC, ecormany requested changes
Looking good so far! I haven't done a detailed read below Accessing Wells in Labware, but I get the sense that not much has changed there. Will do a top-to-bottom read when this is marked ready for review.

2023-07-13 20:21 UTC, ecormany commented on api/docs/v2/new_labware.rst
> +Labware are the consumable items that you work with, reuse, or discard while running a protocol on a Flex or OT-2. Items such as pipette tips, well plates, tubes, and reservoirs are all examples of l
Since we're using the language from the manual here, I think "durable or consumable" is appropriate. The `Labware` class includes things like aluminum adapters, which you definitely shouldn't throw out!

2023-07-13 20:21 UTC, ecormany commented on api/docs/v2/new_labware.rst
> +From the example in the :ref:`overview-section-v2`, we used the :py:meth:`.ProtocolContext.load_labware` method to load Flex and OT-2 labware as shown below.
```suggestion
Following the example in the :ref:`overview-section-v2`, here is how to the :py:meth:`.ProtocolContext.load_labware` method to load labware on either Flex or OT-2. 
```
Something like this, mostly to avoid the noun-noun compound "Flex and OT-2 labware"

2023-07-13 20:21 UTC, ecormany commented on api/docs/v2/new_labware.rst
> +After the ``load_labware`` method loads labware into your protocol, it returns a :py:class:`opentrons.protocol_api.labware.Labware` object.
"When" the method loads labware? I think this is considered to be simultaneous, or nearly so. But maybe check with a Python guru…

2023-07-13 20:21 UTC, ecormany commented on api/docs/v2/new_labware.rst
> +.. Recommend a call-out instead of a section (H2, H3) for "label." It's more a "pro tip" nice-to-have rather than
Yes, this is fine, the bit of content is so short. Maybe we should give it a label so it can be cross-referenced easily.

2023-07-13 20:21 UTC, ecormany commented on api/docs/v2/new_labware.rst
> +Labware are the consumable items that you work with, reuse, or discard while running a protocol on a Flex or OT-2. Items such as pipette tips, well plates, tubes, and reservoirs are all examples of l
Maybe also "when creating a protocol for your robot." Saying "to create" makes it sound like those are the only tools you need.

2023-07-13 20:21 UTC, ecormany commented on api/docs/v2/new_labware.rst
> +Custom labware is labware that is not listed the Labware Library. If your protocol needs something that's not in the library, you can create it with the `Opentrons Labware Creator <https://labware.op
```suggestion
Custom labware is labware that is not listed the Labware Library. If your protocol needs something that's not in the library, you can create it with the `Opentrons Labware Creator <https://labware.opentrons.com/create/>`_. However, before using the Labware Creator, you should take a moment to review the support article, `Creating Custom Labware Definitions <https://support.opentrons.com/s/article/Creating-Custom-Labware-Definitions>`_.
```
stray space

2023-07-13 20:21 UTC, ecormany commented on api/docs/v2/new_labware.rst
> +    * - Flex tiprack
"tip rack", with a space, in prose

2023-07-14 16:52 UTC, ecormany commented on api/docs/v2/new_labware.rst
> +From the example in the :ref:`overview-section-v2`, we used the :py:meth:`.ProtocolContext.load_labware` method to load Flex and OT-2 labware as shown below.
oops, it would help if i didn't suggest typos 🤦‍♂️ 
"here is how to **use** the … method"

2023-07-19 03:33 UTC, ecormany requested changes
A few mechanical (English and RST) comments, and a few structural comments. Biggest change will be getting `load_adapter()` fully documented in the Loading Labware on Adapters section.

2023-07-19 03:33 UTC, ecormany commented on api/docs/v2/new_labware.rst
> +Default labware is everything listed in the `Opentrons Labware Library <https://labware.opentrons.com/>`_. When used in a protocol, your Flex or OT-2 knows how to work with default labware. However,
Would be good to link the method here, but keep the clean, short name.
```suggestion
Default labware is everything listed in the `Opentrons Labware Library <https://labware.opentrons.com/>`_. When used in a protocol, your Flex or OT-2 knows how to work with default labware. However, you must first inform the API about the labware you will place on the robot’s deck. Search the library when you’re looking for the API load names of the labware you want to use. You can copy the load names from the library and pass them to the :py:meth:`~.ProtocolContext.load_labware` method in your protocol.
```

2023-07-19 03:33 UTC, ecormany commented on api/docs/v2/new_labware.rst
> +Custom labware is labware that is not listed the Labware Library. If your protocol needs something that's not in the library, you can create it with the `Opentrons Labware Creator <https://labware.op
```suggestion
Custom labware is labware that is not listed the Labware Library. If your protocol needs something that's not in the library, you can create it with the `Opentrons Labware Creator <https://labware.opentrons.com/create/>`_. However, before using the Labware Creator, you should take a moment to review the support article `Creating Custom Labware Definitions <https://support.opentrons.com/s/article/Creating-Custom-Labware-Definitions>`_.
```
not an appositive

2023-07-19 03:33 UTC, ecormany commented on api/docs/v2/new_labware.rst
> +When the ``load_labware`` method loads labware into your protocol, it returns a :py:class:`opentrons.protocol_api.labware.Labware` object.
```suggestion
When the ``load_labware`` method loads labware into your protocol, it returns a :py:class:`~opentrons.protocol_api.labware.Labware` object.
```
tilde trick to shorten this cross-reference

2023-07-19 03:33 UTC, ecormany commented on api/docs/v2/new_labware.rst
> +            location= 'D1',  # Flex deck slot
can remove comment here, since slots are cross-compatible

2023-07-19 03:33 UTC, ecormany commented on api/docs/v2/new_labware.rst
> +The the previous section demonstrates loading labware directly into a deck slot. But, the ``load_labware`` method also includes the ``adapter`` argument. This parameter lets you stack labware on top
```suggestion
The previous section demonstrates loading labware directly into a deck slot. But, the ``load_labware`` method also includes the ``adapter`` argument. This parameter lets you stack labware on top of a compatible adapter and work with them as a single unit in a protocol. For example, you can use an adapter as a simple labware holding device or when you need to use a labware/adapter combination with a module. The ability to combine labware with adapters adds functionality and flexibility to your robot and protocols. 
```
☝️ typo fix

additionally, i think this section could shift in approach. loading modules in examples starts to overcomplicate things — especially since we can do this all directly on the deck now. i'd propose instead of…
- On the Deck
- On a Module
…to have subsections for…
- Using `load_labware`
- Using `load_adapter`

we definitely need to document `load_adapter()` and this seems like the place. load an adapter straight on the deck, then add labware on top. then cross reference to Modules page for more complex examples that do that on top of a module.

2023-07-19 03:33 UTC, ecormany commented on api/docs/v2/new_labware.rst
> +        location= "D1", #Flex deck slot
```suggestion
        location= "D1",
```

2023-07-19 03:33 UTC, ecormany commented on api/docs/v2/new_labware.rst
> +
include versionadded here too (the parameter is new)

2023-07-19 03:33 UTC, ecormany commented on api/docs/v2/new_labware.rst
> -    Examples in this section expect the following
Too much context removed…the code blocks are floating free below the image. How about:

```
The code in this section assumes that ``plate`` is a 24-well plate. For example:
<block loading the corning plate into D1>
```
then skip the OT-2 block that's only 1 character different.

2023-07-19 03:33 UTC, ecormany commented on api/docs/v2/new_labware.rst
> +
we could move (or copy) this further up the page, wherever we do this first.

2023-07-19 03:33 UTC, ecormany commented on api/docs/v2/new_labware.rst
>  +-------------------------------------+-------------------------------------------------------------------------------------------------------------------+
now might be a good opportunity to refactor this into a 3-column list-table.

2023-07-19 15:33 UTC, jwwojak reviewed
I think I've got all the corrections and changes. Made some locally and will commit to the PR.

2023-07-19 15:33 UTC, jwwojak commented on api/docs/v2/new_labware.rst
> +Labware are the consumable items that you work with, reuse, or discard while running a protocol on a Flex or OT-2. Items such as pipette tips, well plates, tubes, and reservoirs are all examples of l
Thanks, Ed. I had "durable" in here from the manual, but (as you noticed) removed it. Was probably over-thinking it to stay focused on the disposable items. Putting it back in. Will change text in 2nd sentence too.

2023-07-19 15:33 UTC, jwwojak commented on api/docs/v2/new_labware.rst
> +Custom labware is labware that is not listed the Labware Library. If your protocol needs something that's not in the library, you can create it with the `Opentrons Labware Creator <https://labware.op
oops!

2023-07-19 15:33 UTC, jwwojak commented on api/docs/v2/new_labware.rst
> +    * - Flex tiprack
Change "tiprack" to "tip rack", except in code.

2023-07-19 15:33 UTC, jwwojak commented on api/docs/v2/new_labware.rst
> +After the ``load_labware`` method loads labware into your protocol, it returns a :py:class:`opentrons.protocol_api.labware.Labware` object.
An easy enough change to make, but does it really make a difference to an average user? There are 2 actions here:

1. Method loads labware
2. API returns an object

That this happens almost immediately isn't relevant to the purpose of the text and intended audience, though it might matter to an engineer. Visions of angels dancing on the head of a pin swim before my eyes. Will change to "when" nonetheless.

2023-07-19 15:33 UTC, jwwojak commented on api/docs/v2/new_labware.rst
> +.. Recommend a call-out instead of a section (H2, H3) for "label." It's more a "pro tip" nice-to-have rather than
added a label. Here's the whole call-out:

```
.. _labware-label:

.. Tip::
    
    The ``load_labware`` method includes an optional ``label`` argument. You can use it to identify labware with a descriptive name. If used, the label value is displayed in the Opentrons App. For example::
        
        tiprack = protocol.load_labware(
            load_name= 'corning_96_wellplate_360ul_flat',
            location= 'D1',  # Flex deck slot
            label= 'any-name-you-want')
```

2023-07-19 15:33 UTC, jwwojak commented on api/docs/v2/new_labware.rst
> +
Moved to top, under the intro, and shortened.

```
.. note::

Code snippets use alphanumeric Flex deck slot locations (e.g. ``D1``, ``D2``, etc.). 
If you have an OT-2, replace the Flex deck slot coordinate with its OT-2 equivalent.
For example, Flex slot D1 corresponds to slot 1 on an OT-2. See :ref:`deck-slots` for more information.
```

2023-07-19 15:33 UTC, jwwojak commented on api/docs/v2/new_labware.rst
>  +-------------------------------------+-------------------------------------------------------------------------------------------------------------------+
Trying a table. The `code formatting` takes a lot of space. Text is going to break across a line.

2 columns might be fine. 2nd column: definition, line break and then example.

Here's the revised 3 col table

```
.. list-table::
   :widths: 20 30 50
   :header-rows: 1

   * - Method
     - Returns
     - Example
   * - :py:meth:`.Labware.wells`
     - List of all wells.
     - ``[labware:A1, labware:B1, labware:C1...]``
   * - :py:meth:`.Labware.rows`
     - List of a list ordered by row.
     - ``[[labware:A1, labware:A2...], [labware:B1, labware:B2..]]``
   * - :py:meth:`.Labware.columns`
     - List of a list ordered by column.
     - ``[[labware:A1, labware:B1..], [labware:A2, labware:B2..]]``
   * - :py:meth:`.Labware.wells_by_name`
     - Dictionary with well names as keys.
     - ``{'A1': labware:A1, 'B1': labware:B1}``
   * - :py:meth:`.Labware.rows_by_name`
     - Dictionary with row names as keys.
     - ``{'A': [labware:A1, labware:A2..], 'B': [labware:B1, labware:B2]}``
   * - :py:meth:`.Labware.columns_by_name`
     - Dictionary with column names as keys.
     - ``{'1': [labware:A1, labware:B1..], '2': [labware:A2, labware:B2..]}``
   ```

2023-07-19 15:33 UTC, jwwojak commented on api/docs/v2/new_labware.rst
> +Default labware is everything listed in the `Opentrons Labware Library <https://labware.opentrons.com/>`_. When used in a protocol, your Flex or OT-2 knows how to work with default labware. However,
Committing change.

2023-07-19 15:33 UTC, jwwojak commented on api/docs/v2/new_labware.rst
>  +-------------------------------------+-------------------------------------------------------------------------------------------------------------------+
Will resolve pending commit.

2023-07-19 15:33 UTC, jwwojak commented on api/docs/v2/new_labware.rst
> +
Will resolve pending commit.

2023-07-19 15:33 UTC, jwwojak commented on api/docs/v2/new_labware.rst
> +
Added

2023-07-19 15:33 UTC, jwwojak commented on api/docs/v2/new_labware.rst
> -    Examples in this section expect the following
Fixed. Assuming "then skip the OT-2 block" means remove it. Makes sense. Revised note at top tells readers the samples use Flex deck slots and links to the deck slot doc. Will resolve and commit.

2023-07-24 01:25 UTC, ecormany approved these changes
I give the 👍 on the prose. I mostly made style edits, although I rewrote the Loading Labware on Adapters section. @jwwojak, I'd appreciate your feedback there.

For code stuff, especially the new ``load_adapter()`` behavior, adding @jbleon95 as a reviewer and waiting for his 2¢ before merging.

2023-07-24 13:28 UTC, jwwojak reviewed
@ecormany Regarding this text in Loading Labware (my italics):

> But you can also load labware on top of an adapter that either fits on a module or goes directly on the deck. _Compatible labware then sits atop the adapter_.

That second sentence seems redundant. The previous already suggests labware on top of an adapter. Can this be removed?

Also, word choice:  "atop"? I get it. This lets us avoid using "on top of" twice, but still something about it. It works but it reminds me of using a close matching SAE socket on a metric bolt.

But these are minor and shouldn't stop you from merging.

2023-07-25 17:27 UTC, jbleon95 approved these changes
Adapter and labware loading onto adapters looks good.

2023-07-25 17:42 UTC, merged