feat(api): Support V2 pipette configs in the OT-2 and Protocol Engine
OpenTrons/opentrons-api pull request #13104
Opened 2023-07-14 14:47 UTC by Laura-Danielle

# Overview

Well..uh I am sorry in advance. This PR touches _a lot_ of code. The most important things to check out are the changes to `pipette_data_provider.py` and `ot2/pipette.py`. There are few small changes in the `shared-data/python` code that could also use some eyes. Luckily some of our older tests caught some mistakes in the pipette configs which was great (and hence why there are a lot of shared-data data changes).

I think I'll still need to do one more follow-up PR in Protocol Engine to support dynamically changing fallback tip length during run-time but I decided not to do that for this PR.

# To-Do
There is one more failing test related to supporting "old" and "new aspirate functions on super old pipettes. I haven't yet decided how to handle this, but it would not block folks from beginning to test the PR so I decided to just put this up for review.

# Test Plan

This PR needs to be _thoroughly_ tested on both an OT-2 and Flex. It touches a lot of core functionality including:

- pipette quirks
- pipette backwards compatibility
- tip length lookup
- return tip height
- Aspiration functions
- Current changing

At a minimum we need to test on both an OT2/Flex:

- [x] Attaching pipettes
- [x] Loading pipettes in a protocol (with both old and new Flex names)
- [x] Analyzing a protocol
- [x] Running a protocol on the robot
- [x] Simulating a protocol in the App

Specific to OT-2
- [x] another quick check of mutable configs on the OT2

# Changelog
- Lots of small shared-data data changes (sorry about that)
- Update OT-2 configs to use new shared-data pipette configs
- Update Protocol Engine to grab data from the V2 configs
- Additional helper functions in shared-data to support the two points above
- Small fix to mutable configurations

# Review requests

Please look closely at changes to `ot2/pipette` and `pipette_data_provision.py`.  Make sure I did not miss any critical components in Protocol Engine for loading pipette configs.

# Risk assessment

High. This PR affects a critical part of the stack. Please see the test plan above.

2023-07-14 18:02 UTC, sfoster1 requested changes
I think this is gonna be rough but important to do, but I think there's some things we can do to make it a bit less of a bitter pill to swallow.

Couple inline questions and some larger stuff:

### subtle but probably important distinctions
I don't quite get the difference between `pipette.active_tip_settings.default_return_height` and 
### small changes, lots and lots of small consequences
 There's a lot of changes that are sometimes almost the only changes in the file that are the consequence of a little type change that we can avoid by changing the new types or changing the upstreams. For instance, if you define `opentrons_shared_data.pipette.pipette_definitions.PipetteChannelType` as `PipetteChannelType(int, Enum)` then you get int comparisons for free:
```python
Python 3.7.17 (default, Jun 27 2023, 10:52:02)
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from enum import Enum
>>> class PipetteChannelType(int, Enum):
...  SINGLE_CHANNEL = 1
...  EIGHT_CHANNEL = 8
...  NINETY_SIX_CHANNEL = 96
...
>>> PipetteChannelType.SINGLE_CHANNEL
<PipetteChannelType.SINGLE_CHANNEL: 1>
>>> PipetteChannelType.SINGLE_CHANNEL ==1
True
>>> PipetteChannelType.SINGLE_CHANNEL == 8
False
>>> PipetteChannelType.EIGHT_CHANNEL == 8
True
>>> PipetteChannelType.EIGHT_CHANNEL == 1
False
```
Combine that, maybe a custom comparison operator (if it's even needed, may get that for free too) to sort them, and some handling for the `PipetteInfo` model in the old calibration stuff to build its `channels` element from the enum, and a lot of the changes in `robot_server.robot.calibration` fall away.

This seems like not so big a win, but one of the reasons prs like this are tough to deal with is that git(hub) has no way of emphasizing or separating parts of the diff, and so stuff that's complete boilerplate like adding `as_int` everywhere is presented on the same level as stuff that's more important. Let's cut down on some of those boilerplate changes.

2023-07-14 18:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/simulator.py
> +            m: _sanitize_attached_instrument(attached_instruments.get(m))  # type: ignore
what's this suppressing?

2023-07-14 18:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/instrument_abc.py
> +def piecewise_volume_conversion(
this really should not be here. we should avoid touching it if we possibly can and if we can't we should just move it once

2023-07-14 18:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot2/pipette.py
> +        self._aspirate_flow_rates_lookup = (
i'm suspicious of these parentheses I think there might be a syntax problem here

2023-07-14 18:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot2/pipette.py
> +            PipetteTipType(int(self._working_volume))
do we definitely have configurations for all the pipettes for all the working volumes they use, including the ot2 filter tips?

2023-07-14 18:02 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/resources/pipette_data_provider.py
> +        nominal_tip_overlap=config.tip_overlap_dictionary,
don't you have to modify `get_pipette_static_config` too?

2023-07-14 18:02 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +            if self.hw_pipette.config.channels.as_int == 8
change can go away if `PipetteChannelType` is `class PipetteChannelType(int, Enum)`

2023-07-14 18:02 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +                    channels=pip.config.channels.as_int,
change can go away if `PipetteInfo` can be build from a `PipetteChannelType` (or in fact is automatically so built if it descends from `int`)

2023-07-14 18:02 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +            or right_pip.config.channels.as_int > left_pip.config.channels.as_int
change can go away with a custom ordering operator or indeed just for free if this descends from `int`

2023-07-14 18:02 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +            tipLength=self.hw_pipette.active_tip_settings.default_tip_length,
why's this different from line 538 above?

2023-07-14 18:02 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +                self.hw_pipette.tip_overlap.get(
wonder if we might benefit from a helper on `hw_pipette` called like `tip_overlap_for()` that does the defaulting for you

2023-07-14 18:02 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +                self._hw_pipette.tip_overlap.get(
i guess not if we want to default to 0

2023-07-14 18:02 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +                tipLength=hw_pip.current_tip_length,
is this right? this changes based on the last call to `pick_up_tip`, right? it didn't used to

2023-07-14 18:02 UTC, sfoster1 commented on shared-data/pipette/definitions/2/general/eight_channel/p10/1_0.json
>      "increment": 0.0,
Let's drop a lot of these json changes into another pr. certainly anything that doesn't change structure, maybe all of it. it'll be a lot easier to read.

2023-07-14 18:02 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +    max_volume: PipetteModelType,
i don't love this match of argname and argtype. The point of this pr is to continue to tease apart the overloaded concepts that were smushed into pipette names and models into structured data; this conflates two of them again. let's call it `model` or something and get the max volume from the model def.

2023-07-14 18:02 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +def _change_to_camel_case(c: str) -> str:
oh no

2023-07-14 18:02 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +    # Tiny helper function to convert to camelCase.
i would almost infinitely prefer an explicit map of old to new keys

2023-07-14 18:02 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/pipette/pipette_definition.py
> +# TODO (lc 12-5-2022) Ideally we can deprecate this
honestly i think this sort of class is entirely reasonable

2023-07-14 18:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +                    {checked_axis: instr.plunger_motor_current.run}
honestly wondering if, just for the sake of this pr, we mapped at least some of the new values to the old names. most of the time we wouldn't use them, but it would prevent us from needing a million changes that have no semantic meaning but just need different letters in sequence

2023-07-17 11:17 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/simulator.py
> +            m: _sanitize_attached_instrument(attached_instruments.get(m))  # type: ignore
Just moved the #type: ignore from the internal function to have that be slightly better typed. It's suppressing a `TypeDict` type.

2023-07-17 11:17 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/instrument_abc.py
> +def piecewise_volume_conversion(
okay. I'll leave them both in their respective `pipette.py` files.

2023-07-17 11:18 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/ot2/pipette.py
> +        self._aspirate_flow_rates_lookup = (
I think this is what the formatter did but I'll double check.

2023-07-17 11:18 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/resources/pipette_data_provider.py
> +        nominal_tip_overlap=config.tip_overlap_dictionary,
No because I kept the old names mapped in the pipette dict.

2023-07-17 11:21 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +            tipLength=self.hw_pipette.active_tip_settings.default_tip_length,
Do you mean `hw_pip.current_tip_length`? That's the tip length of the pipette currently attached. I only replaced things that were mapped to their respective pipette config. It's possible there are bugs in this code.

2023-07-17 11:21 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +                self.hw_pipette.tip_overlap.get(
Possibly, but not sure we should do that for this PR since we weren't doing that previously.

2023-07-17 11:22 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +                tipLength=hw_pip.current_tip_length,
Good catch.

2023-07-17 11:23 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +def _change_to_camel_case(c: str) -> str:
😆

2023-07-17 11:23 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +    # Tiny helper function to convert to camelCase.
*sigh* Okayyyy

2023-07-17 11:24 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/pipette_definition.py
> +# TODO (lc 12-5-2022) Ideally we can deprecate this
I suppose it could be, but ideally we move away from this being an external concept entirely. You truly should be able to request a certain pipette size/channels without having to worry about generation of the pipette.

2023-07-17 11:26 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +                    {checked_axis: instr.plunger_motor_current.run}
in the config itself? Otherwise if we mapped it in the `Pipette` class there would still be a million changes. Plus mapping in a Pydantic model will get confusing since it's supposed to server as a schema.

2023-07-17 11:27 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/general/eight_channel/p10/1_0.json
>      "increment": 0.0,
There will be test failures if we do this. Unless I rebase the this branch onto the json PR change.

2023-07-17 11:27 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/general/eight_channel/p10/1_0.json
>      "increment": 0.0,
and some of it changed the structure of the schema

2023-07-17 11:28 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +            tipLength=self.hw_pipette.active_tip_settings.default_tip_length,
good catch

2023-07-17 11:31 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/ot2/pipette.py
> +            PipetteTipType(int(self._working_volume))
Will double check

2023-07-17 11:52 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +    max_volume: PipetteModelType,
Not sure what you're asking for here. Do you just want me to call the `max_volume`, `model` instead? I guess it ultimately doesn't matter to me. I would also make the change in the `load_data` function in this file since it's using the same nomenclature.

2023-07-17 12:53 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot2/pipette.py
> +        self._aspirate_flow_rates_lookup = (
Oh okay, I just see that a lot when there's a missing comma or somethign so the formatter groups statements wrong

2023-07-17 12:54 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +    max_volume: PipetteModelType,
Yeah that makes sense to me

2023-07-17 13:03 UTC, sfoster1 approved these changes
Okay, this structure looks good to me. We obviously need to fix up tests and such, and run some protocols on a machine with this, but in particular we should pay close attention to anything going on with hardware testing - they poke into internals a lot and I'm a bit worried.

2023-07-17 18:17 UTC, SyntaxColoring reviewed
Makin' my way downtown. I still have a way left to go, but here are some questions so far, and a couple requests. 🕺

2023-07-17 18:17 UTC, SyntaxColoring commented on shared-data/pipette/schemas/2/pipetteLiquidPropertiesSchema.json
> +        "valuesByApiLevel": { "type": "object", "required": [] }
Can we flesh out this schema documentation for `default` and `valuesByApiLevel`? I'm confused about what's correct when, for example, we have something like this:

```
"default": 6,
"valuesByApiLevel": {
    "2.14": 7
}
```

If we're using `apiLevel` *2.15,* is the correct flow rate 6, or 7?

2023-07-17 18:17 UTC, SyntaxColoring commented on shared-data/pipette/definitions/2/liquid/single_channel/p50/1_4.json
> +        "valuesByApiLevel": { "2.0": 25 }
Question:

It looks like for all (?) the pipette definitions so far,`valuesByApiLevel` always has one key that's equal to the `default`. Is it functionally necessary to specify both, or is it just a hint for future extension?

2023-07-17 18:17 UTC, SyntaxColoring commented on shared-data/pipette/schemas/2/pipetteLiquidPropertiesSchema.json
> +    },
Hmm, what makes tip overlap different from flow rate, tip length, and tip height? Tip overlap is specified here as a dict that's keyed on labware URIs, but those other things are specified as a dict that's keyed on a "tip type" like "t300."

2023-07-17 18:17 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +def update_pipette_configuration(
You might just not have gotten to this yet, but this function seems like a high-value target for unit test coverage, since it has a type-unsafe `Dict[str, Any]` parameter and it's doing legacy name mapping and stuff.

2023-07-17 18:17 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +    # to perform this workaround.
Out of curiosity, what was the problem here?

2023-07-17 18:17 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/pipette/model_constants.py
> +        "single": RobotMountConfigs(768, 220, 30),
Can we make these keys `PipetteChannelType`s instead of plain `"single"`/`"multi"` strings?

2023-07-17 18:17 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/pipette/model_constants.py
> +    "GEN1": {
Can we make these keys `PipetteGenerationType`s instead of plain `"GEN1"`/`"GEN2"`/`"FLEX"` strings?

2023-07-17 18:17 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/pipette/pipette_definition.py
> +class PipetteChannelType(int, Enum):
As a general practice, I don't think we should subclass `Enum`s from other types unless we really need to. And I don't think we need to, here?

https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/3479896162/Don+t+subclass+Python+enums+from+str+proposed

2023-07-17 18:17 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/pipette/pipette_definition.py
> +class PipetteModelVersionType:
Question:

What does the `Type` suffix signify? What kind of Python type *isn't* a `Type`? I've seen this in other places in our codebase, too.

2023-07-17 18:17 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/pipette/pipette_definition.py
> +# TODO (lc 12-5-2022) Ideally we can deprecate this
> I suppose it could be, but ideally we move away from this being an external concept entirely. You truly should be able to request a certain pipette size/channels without having to worry about generation of the pipette.

Hmm. Even in a world where protocol authors request pipettes like that, it seems like this concept would still exist in HTTP. Something would still need to tell the app what pipettes the user needs to attach in order to run a protocol, and the app would still need to determine whether the pipettes that are already attached are a match.

Or is your vision that those would get reported as a fine-grained list of models? Like: "You can attach a `p1000_single_1_0`, or `p1000_single_1_3`, or `p1000_single_1_4`, or ..." etc.

2023-07-17 20:01 UTC, Laura-Danielle commented on shared-data/pipette/schemas/2/pipetteLiquidPropertiesSchema.json
> +        "valuesByApiLevel": { "type": "object", "required": [] }
The flowrate would be 6 and yes I can add more details.

2023-07-17 20:02 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/liquid/single_channel/p50/1_4.json
> +        "valuesByApiLevel": { "2.0": 25 }
hint for future extension. There are some models that do indeed have multiple values.

2023-07-17 20:05 UTC, Laura-Danielle commented on shared-data/pipette/schemas/2/pipetteLiquidPropertiesSchema.json
> +    },
It was was previously used. I made it match the V1 schema for sake of not touching a bunch more code. Protocol Engine and other users of this data still pass in LabwareUri to get this data.

The tip length imo should also eventually be removed from the schema all together because it doesn't make sense to be there.

You can think of the top level `t...` keys as being notation for representing _all_ tips under the 300ul volume which may infact have different properties. That is why right now we're keying the aspirate/dispense by labware uri as well. Unfortunately don't have a fully fleshed out future yet for Liquid classes but you can imagine this type of stuff expanding when we get there.

2023-07-17 20:09 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +    # to perform this workaround.
when you convert the model (with the nested values) to a dict, it's still using the enum as keys but the pydantic model is expecting strings to be converted to keys.

Pydantic doesn't really want you patching data in this way unfortunately which is why things can get ugly.

2023-07-17 20:10 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +    # to perform this workaround.
And we shouldn't be updating static configs dynamically as we are! But that is the legacy code we struggle with today. My ideal case is completely destroying the pipette dict to replace it with a stateful pipette dict/class/whatever and a static pipette dict/class/whatever.

2023-07-17 20:11 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/model_constants.py
> +        "single": RobotMountConfigs(768, 220, 30),
Sure

2023-07-17 20:11 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/model_constants.py
> +    "GEN1": {
Sure

2023-07-17 20:12 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/pipette_definition.py
> +class PipetteChannelType(int, Enum):
We need to for direct int comparison (which happens a lot with this class). See Seth's initial comment in this PR.

2023-07-17 20:14 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/pipette_definition.py
> +class PipetteModelVersionType:
In this instance, I did it to try and distinguish as much as possible from the `PipetteModel`/`PipetteName` dev_types we already have in our code base.

Normally in the past, it's been used when we have type defines at the top of the file. IMO I think it just sounds nicer. For example in my most recent PR, I had a type called something to the effect of `OverrideType`.

2023-07-17 20:19 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/pipette_definition.py
> +# TODO (lc 12-5-2022) Ideally we can deprecate this
In my ideal world, the app shouldn't have to determine if pipettes match at all or not. The robot server/protocol engine should just say 'hey this doesn't match what's currently on the robot'.

For simulation, we should have something that sends back a list of compatible _generations_ (like we kinda talked about in the partial tip meeting). We haven't -- and probably won't in the future -- cared about the functionality between models.

2023-07-17 22:09 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +    # to perform this workaround.
Makes sense. Thanks for the explanation.

2023-07-18 13:06 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/load_data.py
> +def update_pipette_configuration(
yep, thanks for the reminder though :D

2023-07-20 17:50 UTC, jbleon95 commented
Successfully smoke tested, for Flex and OT-2, attaching single and multi-channel pipettes, loading pipettes in protocols (with both GEN-3 and user facing names for Flex), analyzing on both app and robot and running protocols on robot. Additionally confirmed that mutable configs were functioning on OT-2.

2023-07-20 18:07 UTC, jbleon95 approved these changes

2023-07-20 20:43 UTC, merged