feat(shared-data): alphabetizes orderedSlots in Flex deck def
OpenTrons/opentrons-api pull request #13126
Opened 2023-07-18 19:06 UTC by jerader

closes RQA-1077

# Overview

In PD, it is hard to tell which slot you want to add a module to since the Flex deck slots were ordered the way the Ot-2 slots are ordered. But since the flex slots are prefaced with a letter, that way of ordering is confusing. So this PR alphabetizes the ordered Slots.

# Test Plan

Do some smoke testing in app/odd and PD to make sure everything works as expected

# Changelog

- change the flex deck definition `orderedSlots` to be in alphabetical order 

# Review requests

see test plan

# Risk assessment

low

2023-07-18 19:50 UTC, SyntaxColoring requested changes
I don't think we can make this change without some additional cleanup work, and even then it's risky. Some things scattered about are assuming that you can map slots between an OT-2 and Flex by their index in this list. Let me see if I can dig up some specifics.

2023-07-18 20:24 UTC, SyntaxColoring commented
Okay, here's what I was thinking of:

https://github.com/Opentrons/opentrons/blob/0c52b1e96d275855bfe761384e5731765c5e791b/shared-data/python/opentrons_shared_data/deck/__init__.py#L69-L73

https://github.com/Opentrons/opentrons/blob/0c52b1e96d275855bfe761384e5731765c5e791b/hardware-testing/hardware_testing/opentrons_api/helpers_ot3.py#L859-L863

There might be more, not sure.

I think these are fixable by changing the things that call them to [not use integers anymore](https://opentrons.atlassian.net/browse/RLAB-345), or, at least, change the integer-based array lookup into an [explicit map](https://github.com/Opentrons/opentrons/blob/edge/api/src/opentrons/types.py#L341-L354). The former requires some case-by-case thinking, and the latter might run into [frustrating database hazards](https://opentrons.atlassian.net/browse/RSS-98). Definitely possible, but for your purposes of fixing the Protocol Designer sorting, you'll probably have a better time if you do the sort locally in PD?

2023-07-18 20:25 UTC, jerader commented
> I don't think we can make this change without some additional cleanup work, and even then it's risky. Some things scattered about are assuming that you can map slots between an OT-2 and Flex by their index in this list. Let me see if I can dig up some specifics.

thanks @SyntaxColoring , lmk if you dig up any specifics. On the frontend, we map based off of the `id` and i haven't seen anything weird in my smoke testing in app/pd/odd

2023-07-18 20:26 UTC, jerader commented
> Definitely possible, but for your purposes of fixing the Protocol Designer sorting, you'll probably have a better time if you do the sort locally in Protocol Designer?

Oops posted my last comment before i saw this @SyntaxColoring, thanks for digging this up! Yeah, sorting locally might be better. Will look into it!

2023-07-19 15:10 UTC, jerader commented
As @SyntaxColoring pointed out, there are a few instances that rely on the slot indexes to map the same way as the OT-2. For now, the best approach is to alphabetize locally in PD

2023-07-19 15:10 UTC, closed without merging