feat(hardware-testing): Added hardware testing usb package
OpenTrons/opentrons-api pull request #13140
Opened 2023-07-20 15:58 UTC by vegano1

# Overview

The hardware-testing package is used for testing various parts of the Flex, however in order to use it you have to have a computer that has all of our packages, and dependencies and has been set up to run our software. This poses some friction as it requires a lot to get up and running. This pr solves this problem by creating a hardware-testing package, that can be run from a USB drive plugged directly into the Flex.

# Test Plan

- [ ] Use `make -C hardware-testing setup-usb-module` and make sure it generates a **/dist/hardware_testing_usb-0.0.1.tar.gz** file
- [ ] Use `make -C hardware-testing setup-usb-module usb_dir="<usb dir>"` and make sure a **hardware_testing_usb** dir is extracted to the usb dir specified.
- [ ] Make sure you can run hardware-testing scripts after running `./setup.sh` from the Flex
- [ ] Make sure you can run hardware-testing scripts even after reboots
- [ ] Make sure you cant run hardware-testing scripts if the USB thumb drive has been removed.
- [ ] Make sure you cant run hardware-testing scripts after running `./setup teardown` and re-login.

# Changelog

- Added `setup-usb-module` to hardware-testing Makefile, which creates a USB package
- Added hardware-testing entry to scripts/python_build_utils.py so we can get the package version

# Review requests

- If we want to have hardware-testing logging go to the thumb drive that should be a separate pr.
- Anything I might be missing?

# Risk assessment

Low, internal tooling

2023-07-20 16:06 UTC, sfoster1 requested changes
This will print the error message in the console _at login_ if the usb drive isn't plugged in, right? We shouldn't do that because it will happen every time if we forget to remove it before shipping a robot. In that case it should either silently fail or silently teardown.

2023-07-20 16:06 UTC, sfoster1 commented on hardware-testing/Makefile
>  sdist_file = dist/hardware_testing-0.0.1.tar.gz
this probably wants to pattern capture the version

2023-07-20 16:06 UTC, sfoster1 commented on hardware-testing/Makefile
> +usb_file = dist/hardware_testing_usb-0.0.1.tar.gz
as does this

2023-07-20 16:06 UTC, sfoster1 commented on hardware-testing/hardware_testing/tools/usb-package/setup.sh
> +	echo "################## WARNING ##################"
I think we should consider having this case auto-teardown. The reason is that this will be used on the line, and if the line forgets to run `teardown` on a robot then it'll ship with it installed and printing this on every new ssh login which customers will see. If instead we disable it, all that has to happen is they have to run `setup` again.

2023-07-20 16:35 UTC, vegano1 commented on hardware-testing/hardware_testing/tools/usb-package/setup.sh
> +	echo "################## WARNING ##################"
good call!

2023-07-21 17:06 UTC, sfoster1 approved these changes
Nice, looks great!

2023-07-24 14:25 UTC, andySigler approved these changes

2023-07-24 14:30 UTC, merged