docs(api): new_modules.rst revsions for Flex
OpenTrons/opentrons-api pull request #13143
Opened 2023-07-20 18:44 UTC by jwwojak

# Overview

Suggested text and code example revisions to the [Modules](https://docs.opentrons.com/v2/new_modules.html) API docs (new_modules.rst file) to include Flex code and code examples.

# Test Plan

- Checked links and cross-references to make sure they work.
- Code changes are minor. For example, adding new code samples to show labware in a Flex deck slot is just a change from 1 (OT-2) to D1 (Flex).
- Some anchors and other links depend on changes pending in [PR 13096](https://github.com/Opentrons/opentrons/pull/13096).

# Changelog

- Adds Flex and OT-2 code samples to the docs.
- Some new subsections.

# Review requests

Check for proper Python usage and writing/style.

# Risk assessment

Low, documentation changes and code samples only.

2023-07-24 17:25 UTC, ecormany requested changes
Tons of comments, but this is coming along nicely. I think our big question is whether this has gotten too unwieldy for a single page and we want to split it in this PR.

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +    Most of the following code examples use alphanumeric Flex deck slot locations (e.g. ``D1``, ``D2``, etc.). If you have an OT-2 and are using API version 2.14 or earlier, replace the Flex deck slo
```suggestion
    Most of the following code examples use coordinate deck slot locations (e.g. ``'D1'``, ``'D2'``), like those found on Flex. If you have an OT-2 and are using API version 2.14 or earlier, replace the coordinate with its numeric OT-2 equivalent. For example, slot D1 on Flex corresponds to slot 1 on an OT-2. See :ref:`deck-slots` for more information.
```
This is the exact language from the latest revision of Labware.

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +            requirements = {"robotType": "Flex", "apiLevel": "|apiLevel|"}
If we're going all the way up to the requirements block we might as well include `from opentrons import protocol_api` too.

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +                # Load a Heater-Shaker in deck slot D1.
```suggestion
                # Load a Heater-Shaker Module GEN1 in deck slot D1.
```
for parallelism

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +Some modules were added to our python API later than others, and others span multiple hardware generations. When writing a protocol that requires a module, make sure your ``requirements`` or ``metada
```suggestion
Some modules were added to our Python API later than others, and others span multiple hardware generations. When writing a protocol that requires a module, make sure your ``requirements`` or ``metadata`` code block specifies a :ref:`Protocol API version <v2-versioning>` high enough to support all the module generations you want to use.
```
🐍 🆙

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +Some modules were added to our python API later than others, and others span multiple hardware generations. When writing a protocol that requires a module, make sure your ``requirements`` or ``metada
Do we need to add another table or list here to indicate which modules are usable on Flex vs. OT-2? Expanding this table out to 5 columns would be a bit 😵‍💫 

Leaning towards list because we can say "Flex supports HS, Temp 2, TC 2, and Mag Block only. OT-2 supports everything except Mag Block"

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +            "Temperature-Controlled Tubes",
i think keep `label=` here for clarity. add `load_name=` too if you like.

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +When you load labware on a module, you don’t need to specify the deck slot. In the above example, the ``load_module`` method already includes a location (e.g. ``location= "D1"``).
```suggestion
When you load labware on a module, you don’t need to specify the deck slot. In the above example, the ``load_module()`` method already specifies where the module is on the deck: ``location= "D1"``.
```

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +.. Should the section below be a warning?
note or separate section is good. i don't think anything really bad come of it. the pipettes should clear whatever stack you create, and if you exceed max z-height you should get an analysis error.

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +- :py:meth:`.MagneticBlockContext.load_labware`
Shorter possibility:
`The ``load_labware()`` methods of all powered modules accept these additional parameters.`
Then we won't have to maintain this list ad infinitum.

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +The examples in this section use a Temperature Module loaded in Flex deck slot D3, which corresponds to deck slot 3 on the OT-2.
style: avoid noun-noun compounds like `Flex deck slot`. 
```suggestion
The examples in this section use a Temperature Module loaded in deck slot D3 on Flex, which corresponds to deck slot 3 on OT-2.
```

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +To properly align the module relative to the robot, make sure its exhaust, power, and USB ports face outward, away from the center of the deck. This keeps the exhaust port clear and helps make cable
This is more of hardware/installation guidance. I think we can omit it in API docs.

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +.. put in a note: This module works with the OT-2 only. You cannot use it on a Flex liquid handling robot.
cross-ref link to Magnetic Block in the note (TK) would be great!

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +      mag_mod.engage(offset= -2)              # 15.5 mm
```suggestion
      mag_mod.engage(height_from_base= 13.5)  # 13.5 mm
      mag_mod.engage(offset= -2)              # 15.5 mm
```
this is [incorrect Black style](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADJAHxdAD2IimZxl1N_WmBarQbnJKfJtIiEZbSAyV_cJCwarvC4do0Z4CBOrjeOmGnW-IXv2gdAh840JGP1gTNhTZB0OpUT2meM6-XntRvriff8iaCxc_5HgEwuWhrbzjOeqVheRu19KZgG0hjXj2IYhTKkmNJPbGT-Z9-sxNR8-eYAx11zQzGycj0AAZgBygEAABYNMhexxGf7AgAAAAAEWVo=). there should be no spaces between a parameter and its value.

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +The GEN2 Magnetic Module uses smaller magnets than the GEN1 version. This change helps mitigate an issue with the magnets attracting beads from their retracted position, but it also takes longer for
```suggestion
The GEN2 Magnetic Module uses smaller magnets than the GEN1 version. This change helps mitigate an issue with the magnets attracting beads from their retracted position, but it also takes longer for the GEN2 module to attract beads. The recommended attraction time is 5 minutes for liquid volumes up to 50 µL and 7 minutes for volumes greater than 50 µL. If your application needs additional magnetic strength to attract beads within these timeframes, use the available `Adapter Magnets <https://support.opentrons.com/s/article/Adapter-magnets>`_.
```
I think "within these timeframes" is important — the weaker magnets will still attract the beads _eventually_, but time may be of the essence in a particular application.

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +            tc_mod.set_block_temperature(72, hold_time_seconds= 60, block_max_volume= 32)
revert

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
>  Placement Restrictions
Just confirmed with Sanniti: All of the placement restrictions (adjacent stuff, pipetting nearby) are only for OT-2. The caddy and deck border design of Flex means you can put whatever you want next to H-S.

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +Like with all modules, use the Heater-Shaker’s :py:meth:`~.HeaterShakerContext.load_labware` method to specify what you will place on the module. For the Heater-Shaker, you must use a definition that
soften language here — you no longer "must" us a combination adapter. and on the Labware page, i suggested _not to_, if you're on 2.15+. 

i also added a `labware-on-adapters` anchor that we can cross-reference from here.

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +Custom Flat-Bottom Labware
this can roll up into the standalone adapters section. you don't need a custom labware definition anymore.

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +Here is an example of how to use a blocking command and shake a sample for one minute. No other commands will execute until a minute has elapsed. For example, the three commands in this code sample s
```suggestion
Here is how to use a blocking command and shake a sample for one minute. No other commands will execute until a minute has elapsed. The three commands in this example start the shake, wait for one minute, and then stop the shake::
```
tighten prose, avoid repeating "example/sample"

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +Deactivating the heater and shaker are done separately using the :py:meth:`~.HeaterShakerContext.deactivate_heater` and :py:meth:`~.HeaterShakerContext.deactivate_shaker` respectively. There is no me
might as well go for:
```suggestion
Deactivate the heater and shaker separately with the :py:meth:`~.HeaterShakerContext.deactivate_heater` and :py:meth:`~.HeaterShakerContext.deactivate_shaker` respectively. There is no method to deactivate both simultaneously, so call the two methods in sequence if you need to stop both heating and shaking.
```

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +*****************************
```suggestion
**********************
Using a Magnetic Block
**********************
```
it's a module but it's name is Magnetic Block ~Module~ 🤪

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +The Magnetic Block is an unpowered, 96-well plate that holds labware close to its high-strength neodymium magnets. It is suitable for many magnetic bead-based protocols, but unlike the Magnetic Modul
not just recommended. it is not for use on anything except Flex.

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +Because the Magnetic Block is unpowered, neither your robot nor the Opentrons App aware of this module. You control it via protocols that use the `Opentrons Flex Gripper <https://shop.opentrons.com/o
generally include empty parentheses when referring to methods by name: `load_module()`

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +.. load something on the magnetic block here example.
can be part of the above snippet. it uses `load_labware()` like all other module contexts.

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +See :ref:`Moving Labware` for more information.
```suggestion
See :ref:`moving-labware` for more information.
```
anchor. link text will read "Moving Labware" once all is merged.

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +In order to send commands to the correct module on the deck, you need to load the modules in your protocol in a specific order. Whenever you call :py:meth:`.load_module` for a particular module type,
the notion here was to have the "higher" number slot load first. so maybe D1 first, then C1, or something like that. (there's less of an obvious ordering with coordinate slots than numeric slots)

2023-07-24 17:25 UTC, ecormany commented on api/docs/v2/new_modules.rst
> +.. Does the support article apply to Flex?
let's check with support.

2023-07-24 20:48 UTC, jwwojak commented on api/docs/v2/new_modules.rst
> +In order to send commands to the correct module on the deck, you need to load the modules in your protocol in a specific order. Whenever you call :py:meth:`.load_module` for a particular module type,
Yes, this is a good idea. I will try to make it more clear in the text. As you note, it is tricky with Flex because of the alphanumeric deck system. Visually row D is first or closest to the user, followed by C, but C comes before D in the alphabet. I will use an example with a module in D3/usb 2 and C1 usb 6 (to match the usb connections on the image) to show how a module on D3 would load before C1 because of the usb port number.

2023-07-25 17:28 UTC, jwwojak commented on api/docs/v2/new_modules.rst
> +Some modules were added to our python API later than others, and others span multiple hardware generations. When writing a protocol that requires a module, make sure your ``requirements`` or ``metada
Ouch, a 5-column table would be too much.

2023-07-25 17:29 UTC, jwwojak commented on api/docs/v2/new_modules.rst
> +In order to send commands to the correct module on the deck, you need to load the modules in your protocol in a specific order. Whenever you call :py:meth:`.load_module` for a particular module type,
Pushed revisions to draft this morning.

2023-07-25 17:41 UTC, jwwojak commented on api/docs/v2/new_modules.rst
> +.. Does the support article apply to Flex?
Checking in Slack: https://opentrons.slack.com/archives/C0JLZLPL3/p1690306874357039

2023-07-25 17:53 UTC, jwwojak commented on api/docs/v2/new_modules.rst
> +See :ref:`Moving Labware` for more information.
Github says changes are outdated. Will resolve for now.

2023-07-25 17:54 UTC, jwwojak commented on api/docs/v2/new_modules.rst
> +Because the Magnetic Block is unpowered, neither your robot nor the Opentrons App aware of this module. You control it via protocols that use the `Opentrons Flex Gripper <https://shop.opentrons.com/o
Fixed in upcoming in-progress draft.

2023-07-25 18:06 UTC, jwwojak commented on api/docs/v2/new_modules.rst
> +            requirements = {"robotType": "Flex", "apiLevel": "|apiLevel|"}
Will do.

2023-07-25 18:06 UTC, jwwojak commented on api/docs/v2/new_modules.rst
> +            "Temperature-Controlled Tubes",
Yikes, overlooked that. Will fix.

2023-07-25 18:17 UTC, jwwojak commented on api/docs/v2/new_modules.rst
> +- :py:meth:`.MagneticBlockContext.load_labware`
Revised to use the recommended shorter text.

2023-07-25 18:17 UTC, jwwojak commented on api/docs/v2/new_modules.rst
> +The examples in this section use a Temperature Module loaded in Flex deck slot D3, which corresponds to deck slot 3 on the OT-2.
Added to batch commit.

2023-07-25 18:21 UTC, jwwojak commented on api/docs/v2/new_modules.rst
> +      mag_mod.engage(offset= -2)              # 15.5 mm
Will fix and push change.

2023-07-25 18:23 UTC, jwwojak commented on api/docs/v2/new_modules.rst
> +            tc_mod.set_block_temperature(72, hold_time_seconds= 60, block_max_volume= 32)
Reverted. Will push changes.

2023-07-27 19:14 UTC, ecormany commented
Closing in favor of #13183 🚚

2023-07-27 19:14 UTC, closed without merging