feat(app) hook up estop modals to desktop app and touchscreen app
OpenTrons/opentrons-api pull request #13178
Opened 2023-07-27 17:06 UTC by koji

# Overview
hook up estop modals to desktop app and touchscreen app

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-07-28 00:18 UTC, koji commented
- [ ] update E-stop missing modal
- [ ] fix E-stop modals' rendering priority
- [ ] add tests

2023-08-01 13:48 UTC, koji commented
- [ ] banner for running protocol page

2023-08-08 18:00 UTC, shlokamin reviewed
lookin good! left some comments. still not able to get the desktop app rendering the e stop modals but im looking into why

2023-08-08 18:00 UTC, shlokamin commented on app/src/App/DesktopApp.tsx
> +// }
leftover comment

2023-08-08 18:00 UTC, shlokamin commented on app/src/App/__tests__/DesktopApp.test.tsx
> +// import { mockConnectedRobot } from '../../redux/discovery/__fixtures__'
leftover imports

2023-08-08 18:00 UTC, shlokamin commented on app/src/App/__tests__/DesktopApp.test.tsx
> +    // mockUseRobot.mockReturnValue(mockConnectedRobot)
leftover comment

2023-08-08 18:00 UTC, shlokamin commented on app/src/organisms/EmergencyStop/EstopMissingModal.tsx
> +  setIsDismissedModal?: (isDismissedModal: boolean) => void
how come these are both optional? it looks like they are always provided. if they are required, the logic in this component below can be simplified

2023-08-08 18:00 UTC, shlokamin commented on app/src/organisms/EmergencyStop/EstopTakeover.tsx
> +
this `useEffect` seems a bit dangerous because we are unconditionally setting state. how come we need to do `setIsDismissedModal(isDismissedModal)`  on line 62? `setIsDismissedModal` and `isDismissedModal` both come from the same provider, so this shouldn't be necessary right?

i'm also not following why this is necessary either: 

```js
   if (!isDismissedModal) {
      setShowEstopModal(true)
    }
```

why do we need two boolean variables to determine whether to show the modal? we have both `isDismissedModal` and `showEstopModal`. it seems like we should always show the an estop modal if the estop is not disengaged _unless_  `isDismissedModal` is true. not sure why we need the other boolean

2023-08-08 18:00 UTC, shlokamin commented on app/src/organisms/EmergencyStop/EmergencyStopContext.ts
> +  setIsDismissedModal: (isDismissedModal: boolean) => void
can we name these variables something more explicit to indicate this is the stop modal and not just any modal? maybe `isEmergencyStopModalDismissed` and `setIsEmergencyStopModalDismissed` or something?

2023-08-08 18:00 UTC, shlokamin commented on app/src/organisms/EmergencyStop/EstopTakeover.tsx
> +  const targetEstopModal = (): JSX.Element | null => {
this is a fn that returns `JSX.Element | null`, why not just make it a react component?

```js
 const TargetEstopModal = (): JSX.Element | null => {}

// and then use it
<TargetEstopModal />
```

2023-08-08 18:08 UTC, shlokamin commented
ah! the reason i cant see the modal on desktop is because `useIsUnboxingFlowOngoing` is returning `true` because on desktop `unfinishedUnboxingFlowRoute` is ` '/welcome'`

2023-08-08 18:12 UTC, koji commented
> ah! the reason i cant see the modal on desktop is because `useIsUnboxingFlowOngoing` is returning `true` because on desktop `unfinishedUnboxingFlowRoute` is ` '/welcome'`

oh I see.

2023-08-08 18:26 UTC, koji commented on app/src/organisms/EmergencyStop/EstopTakeover.tsx
> +
`showEstopModal` to display the modal or not.
`isDismissedModal` to handle banner display and modal display.

2023-08-08 18:54 UTC, shlokamin commented on app/src/organisms/EmergencyStop/EstopTakeover.tsx
> +
> showEstopModal to display the modal or not.

hmm but we just forward along `isEmergencyStopModalDismissed` to `showEstopModal `
```js
if (!isEmergencyStopModalDismissed) {
      setShowEstopModal(true)
    }
```
so if `isEmergencyStopModalDismissed` changes, so does `showEstopModal` right?

2023-08-08 19:00 UTC, koji commented on app/src/organisms/EmergencyStop/EstopTakeover.tsx
> +
you are right, we could remove setShowEstopModal.
Tested the code and it worked as expected.

2023-08-08 19:38 UTC, koji commented
- [ ] check the modal with Windows app

2023-08-09 20:33 UTC, shlokamin requested changes
left some comments but nothing code wise that blocks merging. 

what does block merging, unfortunately, is that we either need to get more estops or implement some kind of override which might not even be in compliance. so we gotta sit tight till this gets resolved: https://opentrons.slack.com/archives/C049WNGU22H/p1691508733660019

2023-08-09 20:33 UTC, shlokamin commented on app/src/App/OnDeviceDisplayApp.tsx
> +  const robotName = localRobot?.name ?? 'no name'
if there is no `robotName` we shouldn't try to render the `EstopTakeover` at all since it needs it. 

maybe instead `EstopTakeover` doesnt need to have `robotName` passed in via props and instead it can use the `getLocalRobotSelector`

2023-08-09 20:33 UTC, shlokamin commented on app/src/pages/Devices/DeviceDetails/index.tsx
> +function RenderDeviceDetails({
i think we should either call this `DeviceDetailsComponent` or inline this new logic in the body of `DeviceDetails`

2023-08-09 20:33 UTC, shlokamin commented on app/src/organisms/EmergencyStop/EstopPressedModal.tsx
> +    setEstopPhysicalStatus(null, {
how come `setEstopPhysicalStatus` needs to take in `null` as an argument? looking at `useSetEstopPhysicalStatusMutation`: 

```js
 const mutation = useMutation<EstopStatus, AxiosError, null>(
    [host, 'robot/control/acknowledgeEstopDisengage'],
    (newStatus: null) =>
      setEstopPhysicalStatus(host as HostConfig, newStatus)
        .then(response => response.data)
        .catch(e => {
          throw e
        }),
    options
  )
```

`newStatus` is always `null`, so there doesnt seem to be a need to have there be an input to the function at all. 

drilling down further into `setEstopPhysicalStatus`:

```js
export function setEstopPhysicalStatus(
  config: HostConfig,
  data: null
): ResponsePromise<EstopStatus> {
  return request<EstopStatus, null>(
    PUT,
    '/robot/control/acknowledgeEstopDisengage',
    data,
    config
  )
}

```
this endpoint doesnt set the status to anything, it only sets the status to disengaged. maybe we can rename this to `acknowledgeEstopDisengage`?

2023-08-09 20:33 UTC, shlokamin commented on app/src/App/__tests__/DesktopApp.test.tsx
> +// const mockUseRobot = useRobot as jest.MockedFunction<typeof useRobot>
leftover comment

2023-08-09 21:43 UTC, koji commented on app/src/pages/Devices/DeviceDetails/index.tsx
> +function RenderDeviceDetails({
I will export this as a component since this needs to be wrapped by `ApiHostProvider` so inline might not work or make codes messy.

2023-08-10 19:27 UTC, shlokamin commented on app/src/organisms/EmergencyStop/EstopPressedModal.tsx
> +    e.stopPropagation()
do we need these?

2023-08-10 19:47 UTC, shlokamin approved these changes

2023-08-10 19:54 UTC, koji commented on app/src/organisms/EmergencyStop/EstopPressedModal.tsx
> +    e.stopPropagation()
removed

2023-08-10 21:08 UTC, merged