refactor(shared-data): p1000 flex minimum volumes
OpenTrons/opentrons-api pull request #13200
Opened 2023-07-31 17:13 UTC by jerader

closes RAUT-578

# Overview

Change `p1000` pipette minimum volumes to 5uL

# Test Plan

just review code. you can also verify that a move liquid step in PD volume doesn't error if you put a volume down to 5uL when using a p1000 single or multi pipette.

# Changelog

- change `minVolume` key values to `5` in `pipetteNameSpecs`

# Review requests

I only changed this in `pipetteNameSpecs`. Does anywhere else need changing?

# Risk assessment

low

2023-07-31 18:35 UTC, koji approved these changes
5️⃣

2023-07-31 19:09 UTC, Laura-Danielle requested changes
Can you pls update these in the v2 schema as well?

It's located in the `liquid` folder. I think some of the defs are correct and some are not.

2023-07-31 19:15 UTC, jerader commented
> Can you pls update these in the v2 schema as well?
> 
> It's located in the `liquid` folder. I think some of the defs are correct and some are not.

@Laura-Danielle , are you referring to `shared-data/pipette/schemas/2/pipetteLiquidPropertiesSchema.json`?

2023-08-01 12:15 UTC, Laura-Danielle approved these changes
nice. lgtm

2023-08-01 12:30 UTC, merged