docs(api): new_pipette.rst revisions for Flex
OpenTrons/opentrons-api pull request #13218
Opened 2023-08-02 17:43 UTC by jwwojak

# Overview

Suggested text and code example revisions to the [Pipette](https://docs.opentrons.com/v2/new_pipette.html) API docs (new_pipette.rst file) to include Flex text and code examples.

# Test Plan

- Checked links and cross-references to make sure they work.
- Asking reviewers to check doc code changes. Revisions replace sample code showing OT-2 examples in favor of Flex examples.   

# Changelog

Changes include:

- Extensive text re-writing throughout.
- Some new headers and reorganization.
- Removed some references or text to OT-2 GEN1 pipettes. Emphasis is on OT-2 GEN2 and Flex pipettes.
- Sample code changes from OT-2 examples to Flex.
- Simplifying flow rate data. Remove duplicated info, use tables for better info display.

# Review requests

Please 2x check the code samples.

Also, perhaps @SyntaxColoring could take a look at the section titled "Loading a Flex 96-Channel Pipette." The example puts the 96 channel in the left slot( `mount='left'`). It's a simple `load_instrument` example, but maybe there's more to add or a better example to give users. Any input would be appreciated.

# Risk assessment

Low. Documentation changes only. Any removed OT-2 GEN1 pipette info has been saved separately in case we need to restore it.

2023-08-03 18:59 UTC, ecormany requested changes
Whew, this page is in fact _a lot_! It's definitely organized better than before. I did leave several comments on improving structure further. Another pass through and this should be good.

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +Similar to working with labware and modules, you must inform the robot about the pipettes you want to use in your protocol. Even if you don't use the pipette anywhere else in your protocol, the Opent
this language, "you must inform the robot about the pipettes you want to use in your protocol", repeats the opening sentence too closely. the rest of the info in this ¶ is good.

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +This code sample loads a Flex 8-Channel Pipette in the left slot along with a Flex 1-Channel Pipette and two tip racks in the right slot. Both pipettes are 1000 µL.
makes it sound like the tip racks are in the right pipette mount! either remove that detail, or move it to a second sentence.

also, to avoid confusion, always use _mount_ for pipette locations. _slots_ are on the deck.

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +            tip_racks=[tiprack1, tiprack2])
it's a little weird to assign no tip racks to one pipette and two to the other — this isn't best practice, so it's a little weird to neutrally present it as the first example of `load_instrument()`. i think it would be far better to have 1 rack per pipette.

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +.. version added, 2.15??
yes, that seems right. `flex_96channel_1000` is a valid load name in 2.15.

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +This code sample loads a 8-channel, P300 GEN2 pipette in the left slot and a single-channel, P1000 GEN2 pipette with two tip racks in the right slot.
use standard product name order:
- P300 8-Channel GEN2
- P100 Single-Channel GEN2

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +    metadata = {'apiLevel': '2.14'}
nothing stopping this from being `|apiLevel|` that i know of

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +            tip_racks=[tiprack1, tiprack2])
mirror any change to tip rack loading in Flex example above.

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
>  .. code-block:: python
```suggestion
Because there is only one motor in a multi-channel pipette, these pipettes always aspirate and dispense on all channels simultaneously. For instance, to aspirate from the first column of a 96-well plate::
```
i'm not a big fan of the "you would write" type constructions. i prefer the concision of "To do X: code for X".

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +        # Load a tiprack for 1000uL tips
```suggestion
        # Load a tip rack for 1000 µL tips
```
let's clean these up to match house style

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
>          # Load a wellplate
```suggestion
        # Load a well plate
```
here too

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +        right.dispense(volume=300, location=plate['A3'].top())
These long code comments are hard to read. I'd rather break up the snippet than make people read dark grey monospace on light grey.

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +In general, you should specify wells in the first row of a well plate when using multi-channel pipettes. One exception to this rule is when using 384-well plates. The limited space between the wells
it's not that the space is "limited" — kind of the opposite. 384 plates have double the density (horizontal and vertical) of 96 plates.

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +        # Load an 8-channel Multi GEN2 on the right mount
```suggestion
        # Load a P300 8-Channel GEN2 on the right mount
```

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +        right.aspirate(volume=100, location=plate['A1'])
good catch! 300 µL doesn't fit in a 384-well plate.

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +        | Flex 8-Channel Pipette  + 0.5–50 µL + ``flex_8channel_50``    |
min volume of smaller Flex pipettes is 1 µL, not 0.5

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +        | P1000 GEN2 (single channel) | 100-1000 µL        | ``p1000_single_gen2`` |
reorder, capitalize, and hyphenate names: e.g. P20 Single-Channel GEN2

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +.. list-table::
as i read the formatted table, i find that my eye glances right past the volume figures. what if we had three columns: GEN2 Pipette, GEN1 Pipette, GEN1 min. vol.?

the first row then would say P20 Single GEN2, P10 Single GEN1, 1 µL

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +The ``load_instrument()`` method includes the optional argument, ``tip_racks``. This parameter accepts a list of tip rack labware objects, which lets you to specify as many tip racks as you want. The
```suggestion
The ``load_instrument()`` method includes the optional argument ``tip_racks``. This parameter accepts a list of tip rack labware objects, which lets you to specify as many tip racks as you want. The advantage of using ``tip_racks`` is twofold. First, associating tip racks with your pipette allows for automatic tip tracking throughout your protocol. Second, it removes the need to specify tip locations in the :py:meth:`.InstrumentContext.pick_up_tip` method. For example::
```
not an appositive. i will die on this hill 😆

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +    # You must specify the tip location for the left pipette, which was
i'd also like to split these comments out into body paragraphs.

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +Pipettes aspirate or dispense at different rates measured in units of µL/second. You can change the flow rate on a loaded :py:class:`.InstrumentContext` by altering the :py:obj:`~.InstrumentContext.f
probably `µL/s` or `microliters per second`. this feels like a hybrid.

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
>  should only be used if you have a specific need.
Docs cover all versions, up through the latest and greatest (2.15). It's totally valid to use older versions on OT-2, even into the future. But this was _removed for a good reason_ so we should probably caution users against it fairly strongly. Something like:

```
.. note::
    In API version 2.13 and earlier, :py:obj:`.InstrumentContext.speed` offered similar functionality. It attempted to set the plunger speed in mm/s. Due to technical limitations, that speed could only be approximate. You must use ``.flow_rate`` in version 2.14 and later, and you should consider replacing older code that sets ``.speed``.
```

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +| Pipette                         | Aspirate      | Dispense      | Blow-out      |
I don't think we need the split header cell here. But we may want to split volume into its own column, since it comes at the end of every entry under Pipette. So:
Pipette | Volume range | Aspirate, dispense, blow-out rate

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +.. what is head speed, is it important/significant? applies to gantry movement or pipette? need to find out.
based on the following line, i think that's the speed that the gantry moves the pipette around at.

2023-08-03 18:59 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +Additionally, all OT-2 GEN2 pipettes have a default head speed of 400 mm/second and a well bottom clearance of 1mm for aspirate and dispense actions.
```suggestion
Additionally, all OT-2 GEN2 pipettes have a default head speed of 400 mm/second and a well bottom clearance of 1 mm for aspirate and dispense actions.
```
🧐

2023-08-03 19:30 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +| Pipette                         | Aspirate      | Dispense      | Blow-out      |
or just "Flow rate" for the third column

2023-08-07 19:11 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +Additionally, all OT-2 GEN2 pipettes have a default head speed of 400 mm/second and a well bottom clearance of 1mm for aspirate and dispense actions.
Committing and resolving.

2023-08-07 19:12 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +| Pipette                         | Aspirate      | Dispense      | Blow-out      |
Went with "Flow Rates (uL/s)". Including the units in header for extra reinforcement/reminder.

2023-08-07 19:13 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
>  should only be used if you have a specific need.
Committing in next push.

2023-08-07 19:15 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +Pipettes aspirate or dispense at different rates measured in units of µL/second. You can change the flow rate on a loaded :py:class:`.InstrumentContext` by altering the :py:obj:`~.InstrumentContext.f
Committing in next push.

2023-08-07 19:17 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +This code sample loads a 8-channel, P300 GEN2 pipette in the left slot and a single-channel, P1000 GEN2 pipette with two tip racks in the right slot.
Replacing with correct product names.

- Flex 1-Channel Pipette
- Flex 8-Channel Pipette

2023-08-07 19:17 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +.. version added, 2.15??
Added version.

2023-08-07 19:18 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +            tip_racks=[tiprack1, tiprack2])
Code samples from original, OT-2 version. Revising to use 1 rack per pipette, changing to load 1 one channel and 8 channel.

2023-08-07 19:19 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +This code sample loads a Flex 8-Channel Pipette in the left slot along with a Flex 1-Channel Pipette and two tip racks in the right slot. Both pipettes are 1000 µL.
Replacing "slot" with "mount."

2023-08-07 19:23 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +Similar to working with labware and modules, you must inform the robot about the pipettes you want to use in your protocol. Even if you don't use the pipette anywhere else in your protocol, the Opent
Removing that paragraph and incorporating into 2nd paragraph of 1st section. 
 
> Similar to working with labware and modules, you must inform the robot about the pipettes you want to use in your protocol. As noted above, the:py:meth:`~.ProtocolContext.load_instrument` method provides this capability. It also requires the :ref:`pipette's API load name <new-pipette-models>`, its left or right mount position, and (optionally) a list of associated tip racks. Even if you don't use the pipette anywhere else in your protocol, the Opentrons App and the robot won't let you start the protocol run until all pipettes loaded by ``load_instrument()`` are attached properly.

2023-08-07 19:25 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +    metadata = {'apiLevel': '2.14'}
Revised as:

> metadata = {'apiLevel': |apiLevel|}

2023-08-07 19:27 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +            tip_racks=[tiprack1, tiprack2])
These have changed and mirror each other.

- loading tip racks 1st
- loading instruments after

2023-08-07 19:30 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
>  .. code-block:: python
The example after this text, I've separated into two H3 sections. Seem to work better as there's a lot of info being conveyed here. New outline is:

- H2 Multi-Channel Pipettes and Well Plates
- H3 8-Channel, 96-Well Plate Example
- H3 8-Channel, 384-Well Plate Example

This was also the big code sample including extensive multi-line comments. Broke it up. Took comments out of code and incorporated into text with short code examples.

2023-08-07 19:31 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
>          # Load a wellplate
Fixed throughout.

2023-08-07 19:33 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +In general, you should specify wells in the first row of a well plate when using multi-channel pipettes. One exception to this rule is when using 384-well plates. The limited space between the wells
Revised to remove "limited."

> The greater well density means the nozzles of a multi-channel pipette can only accesses every other well in a column.

2023-08-07 19:34 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +        # Load an 8-channel Multi GEN2 on the right mount
This is fixed in a recent draft push.

2023-08-07 19:36 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +        | Flex 8-Channel Pipette  + 0.5–50 µL + ``flex_8channel_50``    |
Fixing minimum volume in next push.  Change to 1-50 uL

2023-08-07 19:37 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +        | P1000 GEN2 (single channel) | 100-1000 µL        | ``p1000_single_gen2`` |
Fixed to use proper pipette names e.g.

- P20 Single-Channel GEN2
- Flex 1-Channel Pipette

2023-08-07 19:38 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +.. list-table::
Fixed to show GEN2 name, GEN1 name, GEN1 volume.

2023-08-07 19:39 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +The ``load_instrument()`` method includes the optional argument, ``tip_racks``. This parameter accepts a list of tip rack labware objects, which lets you to specify as many tip racks as you want. The
No need to die. Removing comma.

2023-08-07 19:39 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +    # You must specify the tip location for the left pipette, which was
Yes, new changes break up the code and move revised comments to regular text.

2023-08-07 20:01 UTC, jwwojak commented
Turning this into a regular PR and re-requesting review.

2023-08-08 18:56 UTC, ecormany requested changes
Great, only a few things that didn't land in their final spot or needed a little cleanup. 🔜

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +Similar to working with labware and modules, you must inform the robot about the pipettes you want to use in your protocol. As noted above, the:py:meth:`~.ProtocolContext.load_instrument` method prov
```suggestion
Similar to working with labware and modules, you must inform the robot about the pipettes you want to use in your protocol. As noted above, the :py:meth:`~.ProtocolContext.load_instrument` method provides this capability. It also requires the :ref:`pipette's API load name <new-pipette-models>`, its left or right mount position, and (optionally) a list of associated tip racks. Even if you don't use the pipette anywhere else in your protocol, the Opentrons App and the robot won't let you start the protocol run until all pipettes loaded by ``load_instrument()`` are attached properly.
```
syntax fix

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +When you load a pipette in this way, you are declaring that you want the specified pipette to be attached to the robot. Even if you don't use the pipette anywhere else in your protocol, the Opentrons
can delete, this is covered in the intro.

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +If you're writing a protocol that uses the Flex Gripper, you might think that this would be the place in your protocol to declare that. However, the gripper doesn't require ``load_instrument``! Wheth
should go up in the Flex section

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +Multi-Channel Pipettes and Well Plates
check the cross-references to make sure this won't add the text "and Well Plates" to links elsewhere.

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +        location='D1')
fix indents here, Python will consider this a syntax error

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +    right.pick_up_tip(tiprack1['A1'])
the code sets up tip tracking for this pipette. so i'd expect just `right.pick_up_tip()`. 

if you want to be explicit about the location on the tip rack, leave this line as is and remove the `tip_racks` parameter from `right = protocol.load_instrument(...`

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +After picking up a tip, let's tell the robot to aspirate 300 ul from the well plate at location ``A2``::
```suggestion
After picking up a tip, let's tell the robot to aspirate 300 µL from the well plate at location ``A2``::
```
unit style. there's a few of these to find and replace.

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +With the backmost pipette tip above location A2 on the well plate, all eight channels are above the eight wells in column 1.
```suggestion
With the backmost pipette tip above location A2 on the well plate, all eight channels are above the eight wells in column 2.
```

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +In general, you should specify wells in the first row of a well plate when using multi-channel pipettes. An exception to this rule is when using 384-well plates. The greater well density means the no
```suggestion
In general, you should specify wells in the first row of a well plate when using multi-channel pipettes. An exception to this rule is when using 384-well plates. The greater well density means the nozzles of a multi-channel pipette can only access every other well in a column. Specifying well A1 accesses every other well starting with the first (rows A, C, E, G, I, K, M, and O). Similarly, specifying well B1 also accesses every other well, but starts with the second (rows B, D, F, H, J, L, N, and P).
```
`can only access` or `only accesses`

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +    right.pick_up_tip(tiprack1['A1'])
make same changes to tip tracking as in 96-channel example

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +Because of the limited clearance between wells, the eight pipette channels will only aspirate from every other well in the column (e.g. A1, C1, E1, G1, I1, K1, M1, O1).
```suggestion
The eight pipette channels will only aspirate from every other well in the column: A1, C1, E1, G1, I1, K1, M1, O1.
```
text above explains this well enough, i think

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +Because of the limited clearance between wells, the eight pipette channels will only dispense into every other well in the column (e.g. B1, D1, F1, H1, J1, L1, N1, P1).
simplify in same way as line 179

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +        load_name='opentrons_flex_96_tiprack_200ul', location='1')
Flex labware, OT-2 deck slot. (nice that it doesn't matter!)

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +Next, let's specify the tip rack location for the left pipette, which was loaded without a ``tip_racks`` argument::
This explanation makes it sound like the `pick_up_tip` command will associate the tip rack with the pipette for the future, not just for that one action. Maybe something like `Let's pick up a tip with the left pipette. We need to specify the location as an argument of ``pick_up_tip()``, since we loaded the left pipette without a ``tip_racks`` argument.`

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +
the below code block is a great place to use inline comments to show the effect of a command. always put two spaces before the comment.

```
right_pipette.pick_up_tip()  # picks up from A2
right_pipette.drop_tip()
right_pipette.pick_up_tip()  # picks up from A3
right_pipette.drop_tip()
```

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +        pipette.aspirate(200, plate['A1'])
another good spot for comments
```
pipette.aspirate(200, plate['A1'])  # 160 µL/s
pipette.dispense(200, plate['A2'])  # 160 µL/s
pipette.blow_out()                  #  80 µL/s
```
here it makes sense to do some creative spacing with the last one for readability

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +        pipette.aspirate(200, plate['A1'])
like above
```
pipette.aspirate(200, plate['A1'])  #  50 µL/s
pipette.dispense(200, plate['A2'])  # 100 µL/s
pipette.blow_out()                  #  75 µL/s
```

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +| Flex 1-Channel Pipette  | 1-50        | 8                                 | 4               |
wiiiiiide boi. let's list it twice: 8, 8, 4 and 160, 160, 80

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +Additionally, all Flex pipettes have a well bottom clearance of 1mm for aspirate and dispense actions.
```suggestion
Additionally, all Flex pipettes have a well bottom clearance of 1 mm for aspirate and dispense actions.
```
😇

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +The following table provides data on the default aspirate, dispense, and blow-out flow rates (in µL/s) for OT-2 GEN2 pipettes. Because the flow rates are the same across types, we've consolidated the
maybe `across all three actions` just so people don't think we're talking types of pipette.

2023-08-08 18:56 UTC, ecormany commented on api/docs/v2/new_pipette.rst
>  Additionally, all OT-2 GEN2 pipettes have a default head speed of 400 mm/second and a well bottom clearance of 1mm for aspirate and dispense actions.
`mm/s` and `1 mm` here…and then everything is neat and tidy!

2023-08-08 19:43 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +When you load a pipette in this way, you are declaring that you want the specified pipette to be attached to the robot. Even if you don't use the pipette anywhere else in your protocol, the Opentrons
oops. fat finger. Fixing this locally. Will change and push.

2023-08-08 19:46 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +If you're writing a protocol that uses the Flex Gripper, you might think that this would be the place in your protocol to declare that. However, the gripper doesn't require ``load_instrument``! Wheth
Yikes. Yes it should. Fixing locally and will push.

2023-08-08 19:48 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +Multi-Channel Pipettes and Well Plates
Let's go back to the original, "Multi-Channel Pipettes."  I didn't really like the extra I added on -- too long.

2023-08-08 19:50 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +        location='D1')
2x yikes. Fixing locally. Will push revisions.

2023-08-08 20:01 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +| Flex 1-Channel Pipette  | 1-50        | 8                                 | 4               |
It is a wide load. We'll have to repeat the 160 and 80 three times because these have the flow rates for the 5-1000 uL pipettes:

- Flex 1-channel
- Flex 8-channel
- Flex 96-channel

With the revision, the only metrics that get the row spans are the volumes for the pipettes. Will fix and push.

2023-08-08 20:01 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +Additionally, all Flex pipettes have a well bottom clearance of 1mm for aspirate and dispense actions.
Fixing locally. Will push.

2023-08-08 20:02 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +The following table provides data on the default aspirate, dispense, and blow-out flow rates (in µL/s) for OT-2 GEN2 pipettes. Because the flow rates are the same across types, we've consolidated the
Yes, I thought this was wonk-a-doo weird. Will revise.

2023-08-08 20:03 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
>  Additionally, all OT-2 GEN2 pipettes have a default head speed of 400 mm/second and a well bottom clearance of 1mm for aspirate and dispense actions.
Fixing locally. Will push.

2023-08-08 20:30 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +    right.pick_up_tip(tiprack1['A1'])
Hey, thanks for pointing that out. I had a TIL moment with this further down in the flow rate section. Let's go with `right.pick_up_tip()` because we've got that specified already.

2023-08-08 20:30 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +After picking up a tip, let's tell the robot to aspirate 300 ul from the well plate at location ``A2``::
Doing a search and replace now.

2023-08-08 20:34 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +With the backmost pipette tip above location A2 on the well plate, all eight channels are above the eight wells in column 1.
Fixing locally. Will push.

2023-08-08 20:35 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +In general, you should specify wells in the first row of a well plate when using multi-channel pipettes. An exception to this rule is when using 384-well plates. The greater well density means the no
My god, I am illiterate. Fixing locally. Will commit.

2023-08-08 20:38 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +Because of the limited clearance between wells, the eight pipette channels will only aspirate from every other well in the column (e.g. A1, C1, E1, G1, I1, K1, M1, O1).
Fixing locally. Will commit.

2023-08-08 20:38 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +Because of the limited clearance between wells, the eight pipette channels will only dispense into every other well in the column (e.g. B1, D1, F1, H1, J1, L1, N1, P1).
Fixing locally.

2023-08-08 20:40 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +        load_name='opentrons_flex_96_tiprack_200ul', location='1')
Found 2 locations. Fixing slots 1 & 2 to D1 & D2.

2023-08-08 20:43 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +Next, let's specify the tip rack location for the left pipette, which was loaded without a ``tip_racks`` argument::
Great recommendation. Fixing.

2023-08-08 20:44 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +
Fixing locally. Taking note on comment spacing too.

2023-08-08 20:46 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +        pipette.aspirate(200, plate['A1'])
Fixing locally.

2023-08-08 20:46 UTC, jwwojak commented on api/docs/v2/new_pipette.rst
> +        pipette.aspirate(200, plate['A1'])
Fixing locally.

2023-08-09 14:53 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +.. _pipette:
this is a very generic anchor name. it doesn't seem that we're linking here from anywhere, so we can remove it.

2023-08-09 15:00 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +    metadata = {'apiLevel': |apiLevel|}
need the quotes here. the value has to be a string, or it raises an error.

2023-08-09 15:03 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +.. code-block:: python
maybe include `requirements` here. the previous example is OT-2.

2023-08-09 15:05 UTC, ecormany commented on api/docs/v2/new_pipette.rst
> +    tiprack_left = protocol.load_labware(
\+ indent level for everything under `def run`

2023-08-09 17:35 UTC, ecormany approved these changes
GTG. Massive improvement and lots of new info for Flex on this page. :shipit: 🦾

2023-08-09 18:48 UTC, merged

2023-08-09 18:48 UTC, jwwojak commented
This one was a _monster!_ Thanks, @ecormany!