feat(shared-data): add a current scale for partial tip configurations
OpenTrons/opentrons-api pull request #13231
Opened 2023-08-04 14:16 UTC by Laura-Danielle

## Overview

Once we have concrete data for a current scale on different pipette models, we can add those values to the configuration file. For now, we can load everything in with a default value.

RLIQ-423

# Risk assessment

None. Un-used parameter right now.

2023-08-08 13:59 UTC, sfoster1 requested changes
What's the intended use of this? That a partial tip pickup of N tips on an M channel pipette would set current `N/M * current_scale * tip_pickup_current`? Or something else? If that's what it is, 0.5 seems like a weird default.

We should also at least establish these values in the schema and definitions right, even if we have to change them later?

2023-08-08 13:59 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/pipette/pipette_definition.py
> +        description="A current scale for pick up tip in a parital tip configuration",
```suggestion
        description="A current scale for pick up tip in a partial tip configuration",
```

2023-08-08 14:11 UTC, Laura-Danielle commented
> What's the intended use of this? That a partial tip pickup of N tips on an M channel pipette would set current `N/M * current_scale * tip_pickup_current`? Or something else? If that's what it is, 0.5 seems like a weird default.
> 
> We should also at least establish these values in the schema and definitions right, even if we have to change them later?

@sfoster1, no it's intended to be => 0.5 * (N % 8) where N is number of tips. And yeah I guess we can add it to the definition. I was mostly trying to avoid merge conflicts between this and the other branch (+ we don't have exact numbers yet).

I could go either way adding them to the definition now or not. I just wanted to make sure this value was available while working on the tip manager class.

2023-08-08 17:02 UTC, sfoster1 commented
> > What's the intended use of this? That a partial tip pickup of N tips on an M channel pipette would set current `N/M * current_scale * tip_pickup_current`? Or something else? If that's what it is, 0.5 seems like a weird default.
> > We should also at least establish these values in the schema and definitions right, even if we have to change them later?
> 
> @sfoster1, no it's intended to be => 0.5 * (N % 8) where N is number of tips. And yeah I guess we can add it to the definition. I was mostly trying to avoid merge conflicts between this and the other branch (+ we don't have exact numbers yet).
> 
> I could go either way adding them to the definition now or not. I just wanted to make sure this value was available while working on the tip manager class.

Oh can we call it something else then? like `perTipPickupCurrent` or something?

I'd really prefer if we added the value to the configs before merging this.

2023-08-14 13:57 UTC, sfoster1 approved these changes
cool!

2023-08-14 22:11 UTC, merged