feat(api, robot-server): stop protocol engine if estop is pressed
OpenTrons/opentrons-api pull request #13257
Opened 2023-08-08 21:07 UTC by fsinapi

# Overview

It is important that runs are invalidated when the estop is pressed. This was already provided implicitly if the estop was pressed during a run _while the gantry is moving_, but if a protocol is paused and then the estop is pressed then the run is actually still valid.

This PR adds callbacks to the Robot Server that ensure all protocol engines are invalidated if the estop is pressed.

* For a normal protocol run, every pending command is marked as failed with an Estop error. The Protocol Runner will then implicitly clean up the run with the `finish` function.
* For a maintenance run, the run is stopped and a `HardwareStoppedAction` ensures that the protocol has a stopped_at point. This ensures that the app cannot send any more commands to that protocol, and that the maintenance run endpoints will be able to clean up the engine.

# Test Plan

Run a bunch of protocols and hit the estop at various points! Tested hitting the estop:
* While the gantry is moving
* After pausing the protocol between movements
* During LPC
* During attach flow
* During pipette/gripper calibration

In all of the above cases, the run is marked as failed and the robot does _not_ try to home the gantry. There is an issue during pipette calibration that has an open fix PR so it is not a blocker.

Additionally, if you hit the estop during the initial home before the protocol technically starts, it does _not_ trash the run (because there is not a running command yet). This seems appropriate because the gantry is just preparing to be able to start the run, and it will not move again until the user hits the Play button and the gantry tries to home again.

# Changelog

# Review requests

The mechanism here is possibly a little kludgy but I don't think it seems risky - it will reliably clear the status on the protocol engine such that it can be cleared by the robot server. Is there any reason I'm wrong about that?

# Risk assessment

Medium - this could result in annoying user experience if the implementation is bugged, but also it will only happen when someone hits the estop.

2023-08-09 17:14 UTC, sfoster1 requested changes
I think we're missing a state case in the estop handling but other than that looks good to me.

2023-08-09 17:14 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +            self._queue_worker.cancel()
I think we need an `else` here to prevent an (unlikely) race condition because we're dealing with threads, so we could be in a state where we don't have an active command but do have an active engine. I'm not sure what to put in the `else`, though.

2023-08-09 17:14 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +                wrapped.errorCode == code.value.code
I think we want this to be recursive, right?

2023-08-09 17:48 UTC, fsinapi commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +            self._queue_worker.cancel()
Yeah very good point. I think what we need to do is check if the run was started. From there, my thinking is:

* If it has not been started:
  * We shouldn't have to do anything here, the run is either waiting to be `play`'d or was in the midst of the homing step before it first starts
  * In the latter case, what happens now is the Protocol Runner task exits with an exception and it's like the protocol never started. The user can hit the Play button (once the estop is released) and it should continue homing from where it was and start the run like normal.
* If it _has_ been started:
  * The `StopAction` should be reconfigured such that, if the stop is from an Estop event, every queued command is marked failed and removed from the queue (just like with the `FailCommandAction` except we don't need to provide an active command).
  * If we do that, the Protocol Runner should pick up that it failed and then handle the cleanup.

2023-08-09 22:25 UTC, fsinapi commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +            self._queue_worker.cancel()
okay I was overthinking it but fix is in e032f1cc5c9dbdfc25df8b027b2bc6b9f04fe3bb

2023-08-09 22:25 UTC, fsinapi commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +                wrapped.errorCode == code.value.code
indeed cd63dfeb070da67b0a80f16075ec014edf5a4a2a

2023-08-10 17:53 UTC, sfoster1 commented
FYI https://github.com/Opentrons/opentrons/pull/13254 will make estop during the pre-protocol home trash the run I think

2023-08-10 17:53 UTC, sfoster1 commented
Which is good

2023-08-10 17:56 UTC, sfoster1 approved these changes
This makes sense to me, nice. I think we should have a log in that `else` case still but the precondition argument carries me.

2023-08-10 17:56 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +
Okay, that makes sense. Can we just drop a log here in the (not currently present) straight-up `else` case just in case?

2023-08-10 18:01 UTC, fsinapi commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +
yeeep 2464f3b4c8712fbbb4b0fb1250bfb37dd539245f

2023-08-10 21:09 UTC, merged