add sensor id param to tip presence query
OpenTrons/opentrons-api pull request #13277
Opened 2023-08-10 18:06 UTC by caila-marashaj

Accompanying Python changes for [this firmware branch](https://github.com/Opentrons/ot3-firmware/pull/713)- just adds a `sensor_id` parameter to the `TipStatusQueryRequestPayload`.

2023-08-10 18:14 UTC, sfoster1 approved these changes
Looks good but I think either
- we should allow and document that you can send this _without_ the new parameter, in which case the pipette will respond with data for all the sensors it has
or
- we should add an ALL entry to the enum
or
- we should just keep it payload free

2023-08-11 13:25 UTC, sfoster1 requested changes
Looks good (although I think we're going to remove the `TipStatusQueryRequest` payload change?) but we should probably make this parse ok if the sensor id field is missing just in case.

2023-08-11 13:25 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_bindings/messages/payloads.py
> +    sensor_id: SensorIdField
we probably want to handle this being not present, or at least test with an old firmware, because when you attach a pipette with an out of date firmware it will boot and might send a notification without this early.

2023-08-14 19:46 UTC, caila-marashaj commented on hardware/opentrons_hardware/firmware_bindings/messages/payloads.py
> +    sensor_id: SensorIdField
the newest commit now works with old firmware 👍

2023-08-14 20:09 UTC, sfoster1 approved these changes
Looks good to me, thanks!

2023-08-14 20:51 UTC, merged