docs(api): Revisions to Positions Within the OT-2
OpenTrons/opentrons-api pull request #13287
Opened 2023-08-11 17:17 UTC by jwwojak

# Overview

This is a revision to the API doc, [Positions Within the OT-2](https://docs.opentrons.com/v2/robot_position.html) (`robot_position.rst`).

We're revising this doc to include Flex and make it more generic to cover both robot types.

# Test Plan

- Review text for grammar, style, accuracy.
- Check code samples for accuracy.
- Sandbox: http://sandbox.docs.opentrons.com/position-within-robot-revisions/v2/

# Changelog

- Title change to "Labware and Deck Positions" (suggested) from "Positions Within the OT-2", which is too robot-specific.
- Check and fix all section header styles.
- Text and code changes throughout.
- Removing mentions of specific models in favor of more general terminology  like "robot," "the robot," "your robot" etc.

# Review requests

No particular requests. Appreciate any comments and corrections as always.

# Risk assessment

Low. Text changes only.

2023-08-14 20:59 UTC, ecormany requested changes
This generally integrates Flex behavior into what was a very "OT-2" article before. There's a couple factual points to clean up, and I'll have a separate go at the Jupyter section.

2023-08-14 20:59 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +The API automatically determines how the robot needs to move when working with the instruments and labware in your protocol. But sometimes you need direct control over these activities. The API lets
"working area" instead of "enclosure"?

2023-08-14 20:59 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +##########################
asterisks for H1

2023-08-14 20:59 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +When the robot positions itself relative to a piece of labware, the labware definition determines movement, distance, height, offsets, and the actions it can perform. This section describes how these
This over-collapses these concepts. The labware definition determines only a portion of the behavior.
- LPC determines labware offsets
- "type of action the robot will perform" determines whether the tip goes to the top or bottom of the well — it differs for aspirate and dispense.

2023-08-14 20:59 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +Every well on every piece of labware has three addressable positions: top, bottom, and center. The position is determined by the labware definition and whether the labware is on a module or in a deck
```suggestion
Every well on every piece of labware has three addressable positions: top, bottom, and center. The position is determined by the labware definition and what the labware is loaded on top of. You can use these positions as-is or calculate other positions relative to them.
```
Something like this? Generalizes now that we have the module/adapter split and `load_adapter()`.

2023-08-14 20:59 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +As an example, let's look at the :py:meth:`.Well.top` method. It returns a position level with the top of the well, centered in both horizontal directions.
I don't think the "As an example" text does much besides making this longer to read.

2023-08-14 20:59 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +This is a good position to for :ref:`aspirating liquid <new-aspirate>` or an activity where you want the tip to contact the liquid. Similar to the ``Well.top()`` method, you can adjust the height of
```suggestion
This is a good position for :ref:`aspirating liquid <new-aspirate>` or an activity where you want the tip to contact the liquid. Similar to the ``Well.top()`` method, you can adjust the height of this position with the optional argument ``z``, which is measured in mm. Positive ``z`` numbers move the position up, negative ``z``` numbers move it down.
```

2023-08-14 20:59 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +All positions relative to labware are adjusted automatically based on the labware's x, y, z axis offset. The best way to calculate and apply these offsets is by using Labware Position Check when you
Let's make this cover Flex and the touchscreen as well.
```suggestion
All positions relative to labware are adjusted automatically based on labware offset data. Calculate labware offsets by running Labware Position Check during protocol setup, either in the Opentrons App or on the Flex touchscreen. Version 6.0.0 and later of the robot software can apply previously calculated offsets on the same robot for the same labware type and deck slot, even across different protocols.
```

2023-08-14 20:59 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +You shouldn't adjust labware offsets in your Python code if you plan to run your protocol in the app. However, if you are running your protocol in Jupyter notebook or with ``opentrons_execute``, the
```suggestion
You should only adjust labware offsets in your Python code if you plan to run your protocol in Jupyter notebook or with ``opentrons_execute``. This is because you can't run Labware Position Check from Jupyter or the command line. For these applications, calculate and apply labware offsets by:
```

touchscreen makes this confusing. could add something about it but then it gets wordy. cutting to the chase instead.

2023-08-14 20:59 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +To prepare code written for Jupyter notebook and run it in the app, you need to specify an API level (see the :ref:`tutorial`) and put your commands in a ``run()`` function. To enable the Labware Pos
could also link to "Specifying Versions". would require adding an anchor to versioning.rst

2023-08-14 20:59 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +To prepare code written for Jupyter notebook and run it in the app, you need to specify an API level (see the :ref:`tutorial`) and put your commands in a ``run()`` function. To enable the Labware Pos
we basically never use the definite article "the" with "Labware Position Check" 📱

2023-08-14 20:59 UTC, ecormany commented on api/docs/v2/robot_position.rst
> -.. code-block:: python
We definitely need to keep this code block. This is the requisite "dummy protocol", without which you can't run LPC. 

I'm going to have a think about the broader purpose and structure of this section. I may put together an alternative in a gist or something.

2023-08-14 20:59 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +The robot's base coordinate system is known as *deck coordinates*. Many API functions use this coordinate system, and you can also reference it directly. It is a right-handed coordinate system always
I'm double-checking that this system is the same for Flex and OT-2.

2023-08-14 20:59 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +The :py:meth:`.InstrumentContext.move_to` method moves a pipette to any reachable location on the deck. If the pipette has picked up a tip, it will move the end of the tip to that position; if it has
Let's strike the last sentence here. It's different for Flex and I don't think this level of detail is particularly illuminating. The prior sentence explains the behavior completely.

2023-08-14 20:59 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +	These default speeds were chosen because they're the maximum speed Opentrons knows will work with the gantry. Your robot may be able to move faster, but you shouldn't increase this value unless inst
```suggestion
	These default speeds were chosen because they're the maximum speeds that Opentrons knows will work with the gantry. Your robot may be able to move faster, but you shouldn't increase this value unless instructed by Opentrons Support.
```
agreement + overt clause boundary

2023-08-14 20:59 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +	protocol.max_speeds['x'] = 50    # limit x-axis to 50 mm/s
yes, this spacing is better!

2023-08-14 21:13 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +The robot's base coordinate system is known as *deck coordinates*. Many API functions use this coordinate system, and you can also reference it directly. It is a right-handed coordinate system always
Confirmed with Seth, they're the same at the level of PAPI.

2023-08-15 15:23 UTC, ecormany commented
I made a gist with a possible rewrite of the Jupyter LPC instructions here. I think this is much more understandable. _Howeva_, I think this probably belongs better on Advanced Control, with a link from here. If we decide to do that, it can/should be part of this PR.

https://gist.github.com/ecormany/cdb8e512e5dc2cab561554d056c344a7

2023-08-15 19:43 UTC, jwwojak commented on api/docs/v2/robot_position.rst
> +The API automatically determines how the robot needs to move when working with the instruments and labware in your protocol. But sometimes you need direct control over these activities. The API lets
Yes! Great suggestion. Adding that.

2023-08-15 19:49 UTC, jwwojak commented on api/docs/v2/robot_position.rst
> +When the robot positions itself relative to a piece of labware, the labware definition determines movement, distance, height, offsets, and the actions it can perform. This section describes how these
Ah, rereading this, I understand now. Will revise, something akin to the original:

> When the robot positions itself relative to a piece of labware, where it moves is determined by the labware definition, the actions you want it to perform, and the labware offsets for a specific deck slot. This section describes how these positional components are calculated and how to change them.

2023-08-17 17:05 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +You should only adjust labware offsets in your Python code if you plan to run your protocol in Jupyter notebook or with ``opentrons_execute``. This is because you can't run Labware Position Check fro
@jwwojak Here is where to link to Advanced Control (replacing the remainder of this section). Then take the text from my gist and put it in `new_advanced_running.rst` between the Running a Previously Written Protocol and Using Custom Labware sections.

2023-08-18 14:46 UTC, ecormany approved these changes
Looks good. There's one stray backtick and a little redundancy in the transfer of the one section to Advanced Control. I'll make one last push to clean that up and then :shipit:

2023-08-18 15:42 UTC, merged