Rss 308 rebased on 7.0
OpenTrons/opentrons-api pull request #13365
Opened 2023-08-22 20:45 UTC by TamarZanzouri

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-08-23 07:59 UTC, Laura-Danielle reviewed
It's a bit annoying, but imo we should have the defaultPushOutVolume be an optional pydantic field.

It should default to 0.

2023-08-23 13:21 UTC, Laura-Danielle requested changes
- We don't need plunger positions to be in the protocol engine for the push_out feature
- You have some labware changes that snuck into this branch related to trash validation -- I think we need to move it
- Have some other smaller requests as well as the comment above this change request comment.

2023-08-23 13:21 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
>          rate: float = 1.0,
Could we make push_out the last parameter here?

2023-08-23 13:21 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/protocols/liquid_handler.py
> +        push_out: Optional[float],
Same here, can we put this parameter at the end? Also it's nice to default to `None` if we're making an optional parameter.

2023-08-23 13:21 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +            push_out: The amount to push the plunger bellow bottom position.
`below`

2023-08-23 13:21 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/commands/load_labware.py
> +        if (
Accidental change here?

2023-08-23 13:21 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +            push_out < 0 or push_out > hw_pipette.config["plunger_positions"].bottom
I'm very confused. Push out is a volume, so why are we comparing it to the plunger position which is a mm value?

2023-08-23 19:22 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/resources/pipette_data_provider.py
> +    plunger_positions_for_liquid_class: pipette_definition.PlungerPositions
can remove

2023-08-23 20:36 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +            push_out < 0 or push_out > hw_pipette.config["plunger_positions"].bottom
create a ticket for a floating method to get this value (bottom poistion + default blow out converted to ul)

2023-08-25 10:47 UTC, Laura-Danielle requested changes
I think you still have some accidental changes in this branch that needs to be cleaned up. I'd like to rebase on top of this, but I'll hold off for now.

2023-08-25 19:52 UTC, andySigler approved these changes
shared-data changes look good to me, other than the older-generation pipettes getting a few non-zero push-out volumes but those have no affect on an OT2 anyways so looks good to me.

2023-08-25 19:52 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/single_channel/p1000/default/2_2.json
> +      "defaultPushOutVolume": 20
I think we want to leave all GEN2 pipettes alone, so this should be `0` I believe

2023-08-25 19:52 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/single_channel/p1000/default/2_1.json
> +      "defaultPushOutVolume": 20
same here

2023-08-25 19:52 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/single_channel/p1000/default/2_0.json
> +      "defaultPushOutVolume": 20
same here

2023-08-25 19:52 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/single_channel/p1000/default/1_5.json
> +      "defaultPushOutVolume": 20
same here

2023-08-25 19:52 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/single_channel/p1000/default/1_4.json
> +      "defaultPushOutVolume": 20
same here

2023-08-25 19:52 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/single_channel/p1000/default/1_3.json
> +      "defaultPushOutVolume": 20
same here

2023-08-25 19:52 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/single_channel/p1000/default/1_0.json
> +      "defaultPushOutVolume": 20
same here

2023-08-25 19:52 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/eight_channel/p50/default/1_4.json
> +      "defaultPushOutVolume": 2
same here

2023-08-25 19:52 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/eight_channel/p50/default/1_3.json
> +      "defaultPushOutVolume": 2
same here

2023-08-25 19:52 UTC, andySigler commented on shared-data/pipette/definitions/2/liquid/eight_channel/p50/default/1_0.json
> +      "defaultPushOutVolume": 2
same here

2023-08-28 14:43 UTC, sfoster1 requested changes
Agree with @andySigler about leaving gen2 and gen1 alone, let's keep those all 0. other than that looks great, thank you!

2023-08-28 14:43 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/dispense_in_place.py
> +        None, description="perform a small blow out for accurate dispensing"
```suggestion
        None, description="push the plunger a small amount farther than necessary for accurate low-volume dispensing"
```
i guess? @andySigler what do you think

2023-08-28 18:22 UTC, Laura-Danielle approved these changes
nice, lgtm!

2023-08-28 19:52 UTC, sfoster1 approved these changes
Looks good to me!

2023-08-28 21:47 UTC, merged

2023-08-29 17:49 UTC, SyntaxColoring reviewed
Tested Python and a JSON protocol. Mostly looks good to me, but a couple of notes/questions.

2023-08-29 17:49 UTC, SyntaxColoring commented on shared-data/command/schemas/7.json
> +          "type": "number"
I think we also need this new argument in `JsonTranslator`. Currently, it's getting silently discarded from `dispense` and `dispenseInPlace` commands in JSON protocols.

2023-08-29 17:49 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +        # TODO (tz, 8-23-23): add a check for push_out not larger that the max volume allowed when working on this https://opentrons.atlassian.net/browse/RSS-329
You might already have this in mind, but I think we *also* need to add a check for `push_out` only being present when we're not expecting any liquid to be left in the tip. (If my memory from in-person conversations is correct.)

2023-08-29 18:09 UTC, TamarZanzouri commented on shared-data/command/schemas/7.json
> +          "type": "number"
Thank you Max! Ill add it!

2023-08-30 01:36 UTC, TamarZanzouri commented on shared-data/command/schemas/7.json
> +          "type": "number"
added a fix for this in the embedded pr. https://github.com/Opentrons/opentrons/pull/13422

2023-08-30 13:02 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +        # TODO (tz, 8-23-23): add a check for push_out not larger that the max volume allowed when working on this https://opentrons.atlassian.net/browse/RSS-329
Agree. Will do in a followup