new pipette current configs
OpenTrons/opentrons-api pull request #13372
Opened 2023-08-23 20:46 UTC by caila-marashaj

2023-08-24 16:57 UTC, vegano1 commented
Nice!
Let's retarget this for the 7.0.0 release branch

2023-08-24 18:58 UTC, vegano1 commented on shared-data/python/opentrons_shared_data/pipette/dev_types.py
> +    plungerHomingCurrent: float
should probably make this the same as `PipetteCustomizableConfigElementFloat`

2023-08-24 20:45 UTC, vegano1 commented on shared-data/pipette/definitions/2/general/eight_channel/p1000/1_0.json
> +  "displayName": "Flex 8-Channel 1000 \u03bcL",
Not sure how this was generated but should be μL

2023-08-25 10:35 UTC, Laura-Danielle requested changes
1. Gotta update the json schema to reflect the new change to plunger positions
2. Don't forget to make sure we remove the auto-generated junk that replaced `uL` in some of the pipette definitions.

2023-08-25 10:35 UTC, Laura-Danielle commented on shared-data/python/opentrons_shared_data/pipette/scripts/build_json_script.py
> +        homing = model_configurations["plungerHomingCurrent"]["value"]
In this instance, you wouldn't use the `build_json_script.py` but the `update_configuration_files.py` when you're updating files. (Just for future reference).

2023-08-25 10:35 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/general/single_channel/p50/3_3.json
> +  "displayName": "Flex 1-Channel 50 \u03bcL",
This was probably accidentally generated by the script that you used. We should make sure to fix the areas that this happened.

2023-08-25 10:35 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +                if instr is not None:
`if instr` is cleaner.

2023-08-25 10:35 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +                    await self._backend.set_active_current(
```suggestion
async with self._backend.restore_current():
                    await self._backend.set_active_current(
```

(The home will also need to be wrapped in this)

2023-08-28 14:32 UTC, sfoster1 requested changes
agree with laura's comments, need to fix that mu. probably can do it with find and replace in your editor.

2023-08-28 14:32 UTC, sfoster1 commented on shared-data/pipette/definitions/2/general/eight_channel/p1000/3_0.json
> +  "displayName": "Flex 8-Channel 1000 \u03bcL",
whoa buddy

2023-08-28 15:59 UTC, andySigler requested changes

2023-08-28 15:59 UTC, andySigler commented on api/src/opentrons/hardware_control/ot3api.py
>          else:
`homing` current should be used for all homing actions, not just the initial homing motion. This is because the static friction issue can happen regardless of if the pipette is powered on or off, it just needs to be still for the problem to happen.

Because non-initial homing motions include that faster move to get close to the endstop, we'll need a per-pipette homing-speed that is used as a motion constraint for the plunger axis during this faster movement.

The currently used default max-speed for 1ch/8ch plungers is `70` while 96ch is `15`. So for example, during homing we can instead constrain these to be `30` for 1ch/8ch and `5` for 96ch

2023-08-28 15:59 UTC, andySigler commented on shared-data/pipette/definitions/2/general/ninety_six_channel/p1000/3_5.json
> +    "homing": 0.8
let's set this to `2.2` then test on a few 96ch to see if it needs changing. Ideally we can use the motor's max rated current so we can get the most torque out of it to overcome any static-friction that may have built up.

Same goes for the `v3_4.json` 96ch

2023-08-28 15:59 UTC, andySigler commented on shared-data/pipette/definitions/2/general/single_channel/p10/1_0.json
> +    "homing": 1
I don't remember what the OT2 does for homing, but ideally this PR doesn't affect it at all and the configurations don't describe values that aren't accurate.

2023-08-28 16:06 UTC, andySigler commented on api/src/opentrons/hardware_control/ot3api.py
>          else:
Oh and we should also be setting the pipette's `run` current during all other plunger motions, which right now does not include the movement that happens inside `OT3API._move_to_plunger_bottom()` but it should.

2023-08-29 16:28 UTC, closed without merging