docs(api): Refactor liquid control section
OpenTrons/opentrons-api pull request #13396
Opened 2023-08-28 13:19 UTC by jwwojak

# Overview

This PR is for managing changes made to the "Liquid Control" section of the doc, [Building Block Commands](https://docs.opentrons.com/v2/new_atomic_commands.html). 

Following the plan laid out in [this Figma file](https://www.figma.com/file/WsKj7gklIgDx68DkzegdaN/Commands-PAPI-docs-merge-strategies?type=whiteboard&node-id=0%3A1&t=souDTlzeZ3A0tmOj-1). This PR is for the second small branch section in Merge Strategy 1 of the Figma file.

The original manipulating tips section has 6 parts:

- Aspirate
- Dispense
- Blow out
- Touch tip
- Mix
- Air gap

 # Test Plan

- Check code in the Black formatter and use that style.
- Make sure links work.
- The usual grammar, style, clarity stuff.

# Changelog

TBD. Will add summary when revision is complete and ready for review.

# Review requests

The usual suspects.

# Risk assessment

Low, docs changes only.

2023-08-30 16:41 UTC, ecormany requested changes
Lots of little stuff but in general this section covers what it needs to!

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +After attaching a tip, your robot is ready to aspirate, dispense, and perform other liquid handling tasks. The API provides the following methods that help you manipulate liquids in your protocols. T
Some thoughts on this list…

- Either `the following methods` _or_ `These include` depending on whether this list is exhaustive — it at least appears to be w.r.t. what this page covers.
- For the list itself, we probably shouldn't repeat `InstrumentContext.` every time, for readability. 
- I'm torn on whether each item should link directly to the reference, or whether it should link down this page. Each subsection begins with a `:py:meth:` link to the reference, for anyone who's looking for reference entries rather than prose explanations.

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +To draw liquid up into a pipette tip, call the :py:meth:`~.InstrumentContext.aspirate` method. This method lets you specify the aspiration volume in µL, the well location, and pipette flow rate. Othe
`remove 200 µL from well location A1`
Probably trying to not repeat "aspirate" over and over here, but I think the repetition is OK. Or to paraphrase, something like `draw 200 µL into the tip` may be more precise than `remove`.

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +    pipette.aspirate(100)     # aspirate 100 uL from current position
```suggestion
    pipette.aspirate(100)     # aspirate 100 µL from current position
```
pedantry

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +**By Well**
oh no, we're down into H5 territory or something. but that won't be the case when this become its own page. all the headers will get promoted up a level (Liquid Control will be an H1) so this can be an H4 then. but it will show in the sidebar.

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +    pipette.well_bottom_clearance.aspirate=2 # place tip 2 mm above well bottom
```suggestion
    pipette.well_bottom_clearance.aspirate = 2 # place tip 2 mm above well bottom
```
⬛️

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +If you specify a well, like ``plate['A1']``, the pipette will aspirate from a default position 1 mm above the bottom center of that well. To change the default clearance, you would call :py:obj:`.wel
technically not a call because clearance is an attribute 🙃 
```suggestion
If you specify a well, like ``plate['A1']``, the pipette will aspirate from a default position 1 mm above the bottom center of that well. To change the default clearance, set :py:obj:`.well_bottom_clearance`:
```

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +See also, :ref:`new-default-op-positions` for information about controlling pipette height for a particular well.
```suggestion
See also, :ref:`new-default-op-positions` for information about controlling aspiration height for a particular pipette.
```
…since this is a pipette parameter.

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +You can also aspirate from a point along the center vertical axis within a well using the :py:obj:`.Well.top` and :py:meth:`.Well.bottom` methods. These methods move the pipette to a specified distan
use `obj` or `meth` (probably the latter) for both. this currently renders:
>[Well.top](http://sandbox.docs.opentrons.com/docs-liquid-control/v2/new_protocol_api.html#opentrons.protocol_api.Well.top) and [Well.bottom()](http://sandbox.docs.opentrons.com/docs-liquid-control/v2/new_protocol_api.html#opentrons.protocol_api.Well.bottom)

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +See also, :ref:`position-relative-labware` for information about on controlling pipette height from within a well.
worth linking to section on `move_to()` in case users need to change X or Y position for aspirate?

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +    pipette.aspirate(100)     # aspirate 100 uL from current position
```suggestion
    pipette.dispense(100)     # dispense 100 µL at current position
```
📋 🍝

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +    pipette.aspirate(200, plate['B1'])
```suggestion
    pipette.dispense(200, plate['B1'])
```

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +To blow an extra amount of air through the pipette's tip, call the :py:meth:`~.InstrumentContext.blow_out` method. You can use a specific well in a well plate or reservoir as the blow out location. I
`blowout` as a modifier? i think so. so `blowout location`.

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +    pipette.blow_out(plate['B1']) # blow out into well B1
probably also useful to demonstrate 
```
pipette.blow_out(protocol.fixed_trash['A1'])  # blow out into the trash
```
i think it's a pretty common use case.

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +    We recommend changing your API version to 2.4 (or higher) to take advantage of new ``touch_tip()``
i think this level of detail could be saved for the reference. 2.4 is pretty old too.

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +    pipette.touch_tip(plate['B1'],
kinda weird this is on 3 lines, it'll fit on 1. the snippet gets a little dense then, but we could put blank lines between each comment–command pair.

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +    pipette.touch_tip(plate['B1'],
it would also be nice to figure out why adjusting radius is helpful. it's not self-explanatory to me. if you reduce it, might the tip not actually touch? unless there are big droplets maybe? 🤷

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +The :py:meth:`.InstrumentContext.mix` method performs a series of aspirate and dispense on a single location. It's designed to help mix the contents of a well together using a single command rather t
possibility for first sentence: 
```suggestion
The :py:meth:`~.InstrumentContext.mix` method aspirates and dispenses repeatedly in a single location. It's designed to help mix the contents of a well together using a single command rather than using multiple ``aspirate()`` and ``dispense()`` calls. This method includes arguments that let you specify the number of times to mix, the volume (in µL) of liquid, and the well that contains the liquid you want to mix.   
```

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +    # mix 2 times, use the pipette's max volume, current location
maybe split this out as a separate snippet and explain this behavior in a sentence (in addition to the comment)

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +    In API Versions 2.2 and earlier, during a mix, the pipette moves up and out of the target well. In API Version 2.3 and later, the pipette does not move between aspirate and dispense mixing action
downcase `version` — feels like old style (or lack thereof)

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
>  Air Gap
`uL` -> `µL` throughout this section

2023-08-30 16:41 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +The :py:meth:`.InstrumentContext.air_gap` method tells the pipette to aspirate some air after a liquid. Creating an air gap can help prevent a liquid from leaking out of the pipette after drawing it
maybe `aspirate air instead of liquid`. it typically comes after aspirating liquid but doesn't have to. i've heard that FAS uses "pre-air-gapping" as a technique for certain applications.

2023-08-31 13:22 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +    pipette.touch_tip(plate['B1'],
and on the flip side, we should probably have a `.. warning::` about large values of `radius` 💥

2023-08-31 14:32 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +To draw liquid up into a pipette tip, call the :py:meth:`~.InstrumentContext.aspirate` method. This method lets you specify the aspiration volume in µL, the well location, and pipette flow rate. Othe
I was trying to avoid over-use of "aspirate." Will put it back in that last sentence.

> For example, this snippet tells the robot to aspirate 200 µL from well A1.

2023-08-31 14:35 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +    pipette.aspirate(100)     # aspirate 100 uL from current position
No no, not  pedantry at all. An important style issue/consideration. Thank you for highlighting that. I usually fix these closer to the end of the drafting process. I think all the instances of "uL" have been replaced by "µL". 

Same with any occurrences of other measurement units and numbers (2mm vs 2 mm).

2023-08-31 14:56 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +**By Well**
Oh no indeed!  I will re-write to remove the bold headers. Didn't realize these would be H5s, which is horrible.

2023-08-31 15:19 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +After attaching a tip, your robot is ready to aspirate, dispense, and perform other liquid handling tasks. The API provides the following methods that help you manipulate liquids in your protocols. T
I was uncomfortable with the bullet list too. Let's try something different, a bit more general without links to methods or page sections. I will summarize what the page covers and let the section headers and table of contents do the work of links in a bullet list.

2023-08-31 15:52 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +    pipette.touch_tip(plate['B1'],
> kinda weird this is on 3 lines, it'll fit on 1.

I want to put all these in a table, so you're lucky we get this. haha!

2023-08-31 15:52 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
>  Air Gap
These have been fixed already.

2023-09-01 14:13 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +    # mix 2 times, use the pipette's max volume, current location
Yes, will use separate sentences and code samples and replace the large code block/comments combo.

2023-09-01 16:03 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +To blow an extra amount of air through the pipette's tip, call the :py:meth:`~.InstrumentContext.blow_out` method. You can use a specific well in a well plate or reservoir as the blow out location. I
fixed

2023-09-01 16:40 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +    pipette.aspirate(100)     # aspirate 100 uL from current position
fixed

2023-09-01 17:04 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +    pipette.blow_out(plate['B1']) # blow out into well B1
great use case. Adding.

2023-09-01 17:09 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +    We recommend changing your API version to 2.4 (or higher) to take advantage of new ``touch_tip()``
Removed

2023-09-01 17:31 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +    pipette.touch_tip(plate['B1'],
Updating text, added warning, and checking around about _why_ set the radius to less than 1.

2023-09-01 18:31 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +    pipette.touch_tip(plate['B1'],
Added warning, revised text and code samples to put them more with/in text.

2023-09-01 18:34 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +The :py:meth:`.InstrumentContext.mix` method performs a series of aspirate and dispense on a single location. It's designed to help mix the contents of a well together using a single command rather t
Adopted

2023-09-01 18:38 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +The :py:meth:`.InstrumentContext.air_gap` method tells the pipette to aspirate some air after a liquid. Creating an air gap can help prevent a liquid from leaking out of the pipette after drawing it
Let's try this maybe:

> The :py:meth:`.InstrumentContext.air_gap` method tells the pipette to draw in air before or after a liquid.

2023-09-01 18:45 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +If you specify a well, like ``plate['A1']``, the pipette will aspirate from a default position 1 mm above the bottom center of that well. To change the default clearance, you would call :py:obj:`.wel
Fixed.

2023-09-01 18:46 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +You can also aspirate from a point along the center vertical axis within a well using the :py:obj:`.Well.top` and :py:meth:`.Well.bottom` methods. These methods move the pipette to a specified distan
fixed

2023-09-01 18:46 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +See also, :ref:`position-relative-labware` for information about on controlling pipette height from within a well.
added shortcut to `move_to()`

2023-09-01 18:48 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +See also, :ref:`new-default-op-positions` for information about controlling pipette height for a particular well.
Revisions include suggested change.

2023-09-06 15:14 UTC, ecormany reviewed
This is a straightforward section, and it's definitely cleaner than before. A few more touchups and it'll be good to go!

2023-09-06 15:14 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +If the pipette doesn't move, you can also specify an additional aspiration action without including a location. To demonstrate, lets pause the protocol, automatically resume it, and aspirate a second
Maybe `If you don't want the pipette to move` or `If you want to aspirate at the pipette's current location`. Current phrasing makes it sound like the pipette or the API is in control, not the protocol author.

Also a li'l format fix:
```suggestion
If the pipette doesn't move, you can also specify an additional aspiration action without including a location. To demonstrate, lets pause the protocol, automatically resume it, and aspirate a second time from ``plate['A1']``).
```

2023-09-06 15:14 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +    protocol.delay(seconds=5) # pause for 5 seconds
Here and everywhere, two spaces before the `#` that begins an inline comment. Because Black.

2023-09-06 15:14 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +If you specify a well, like ``plate['A1']``, the pipette will aspirate from a default position 1 mm above the bottom center of that well. To change the default clearance, you would call :py:obj:`.wel
```suggestion
If you specify a well, like ``plate['A1']``, the pipette will aspirate from a default position 1 mm above the bottom center of that well. To change the default clearance, first set the ``aspirate`` attribute of :py:obj:`.well_bottom_clearance`:: 
```
Adding a little clarity on how `well_bottom_clearance` operates and the importance of ordering here.

2023-09-06 15:14 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +- :ref:`position-relative-labware` for formation about controlling pipette height from within a well.
```suggestion
- :ref:`position-relative-labware` for information about controlling pipette height from within a well.
```

2023-09-06 15:14 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +Flex and OT-2 pipettes aspirate at :ref:`default flow rates <new-plunger-flow-rates>` measured in µL/s. Adding a number to the ``rate`` parameter multiplies the flow rate by that value. As a best pra
```suggestion
Flex and OT-2 pipettes aspirate at :ref:`default flow rates <new-plunger-flow-rates>` measured in µL/s. Specifying the ``rate`` parameter multiplies the flow rate by that value. As a best practice, don't set the flow rate higher than 3x the default. For example, this code causes the pipette to aspirate at twice its normal rate::
```
To avoid confusion with arithmetic addition.

2023-09-06 15:14 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +If the pipette doesn’t move, you can also specify an additional dispense action without including a location. To demonstrate, lets pause the protocol, automatically resume it, and dispense a second t
Mirror changes to language in Aspirate § above (here and in following paragraphs).

2023-09-06 15:14 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +    pipette.blow_out(protocol.fixed_trash['A1'])
This works fine on both robots for now, but we should monitor progress of RSS-290. Ticketed on our side as RTC-333.

2023-09-06 15:14 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +When ``radius=1``, the robot moves the centerline of the pipette’s plunger axis to the exact edge of the well. Sometimes this means a pipette tip may hit the well wall or edge first and bends inwards
Maybe a chance for some levity here, along the lines of:
"The purpose of `touch_tip` is to _touch_ the edges of the well, not to crash into them. Using a smaller radius and lower speed produces gentler motion. Droplets of different types of liquid behave differently, so test out these parameters in a single well before performing a full protocol run."

2023-09-06 15:14 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +.. there was a recommendation to remove the note
we could compress the note rather than removing it:
```suggestion
.. versionchanged:: 2.4
    Lowered minimum speed to 1 mm/s.
```

2023-09-06 15:14 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
> +    pipette.air_gap(volume=200)
200 is a biiiiiiig air gap. Maybe use 20, like the existing example.

2023-09-06 15:14 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
Check for `lets` --> `let's` throughout.

2023-09-06 17:36 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
Lets as in 3rd person singular is ok, right? As in giving you the ability, capability, or permission to do whatever it is. This method "allows you to do the thing"


> This method lets you . . .  
not

> This method let's you . . .

2023-09-06 17:40 UTC, ecormany commented on api/docs/v2/new_atomic_commands.rst
Yeah, not one for find and replace! Regular expressions can't save you here 🤪

2023-09-06 17:56 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +    pipette.air_gap(volume=200)
The section is based on, and linked to, those sample protocol files on another page. I selected 200 b/c the linked examples use a 1000 uL pipette. Drawing 20 ul of air from a 1000 ul pipette doesn't seem like a good example (or even accurately possible). That's why this uses such a large amount of air.

From the section intro:

> The examples used here assume that you've loaded the pipettes and labware from the basic `:ref:protocol template <protocol-template>.`

2023-09-06 18:05 UTC, jwwojak commented on api/docs/v2/new_atomic_commands.rst
> +When ``radius=1``, the robot moves the centerline of the pipette’s plunger axis to the exact edge of the well. Sometimes this means a pipette tip may hit the well wall or edge first and bends inwards
Ooof, that's what passes for humor? Borscht Belt here we come! Time for some Pocono Palaver. Tip your waitstaff, enjoy the veal, I'm here all week. badum tsssss.

I'd like to keep some of Seth's explanation in here. How about trying to combine some of these:

"The purpose of `touch_tip` is to help the pipette gently touch the edges of the well, not to crash into them. For example, when `radius=1`, the robot moves the centerline of the pipette’s plunger axis to the exact edge of the well. Sometimes this means a pipette tip may hit the well wall or edge first and bends inwards. Using a smaller radius helps avoid hitting the well wall prematurely and a lower speed produces gentler motion. Droplets of different types of liquid behave differently, so test out these parameters in a single well before performing a full protocol run."

2023-09-07 18:15 UTC, ecormany approved these changes
New changes look good, this is ready to merge into the feature branch.

2023-09-07 20:09 UTC, merged