feat(api): Rotate the calibrated module offset if the module was physically moved and rotated.
OpenTrons/opentrons-api pull request #13441
Opened 2023-08-31 20:07 UTC by vegano1

# Overview

When a module is calibrated, the generated module offset vector is valid for the current location the module is in. However, if the module is physically moved and rotated across the deck then the original calibrated offset vector is no longer valid. So we need to apply a rotation of 180 degrees to the calibrated module offset vector if the module was ever moved and rotated.

# Test Plan

- [ ] Make sure we can still perform a module calibration on all supported modules (temp, heater-shaker, thermocycler)
- [ ] Make sure we are correctly saving/loading the calibrated module offset data
- [ ] Make sure we now return the location data along with the vector offset when executing the `CalibrateModule` PE command over HTTP.
- [ ] Make sure this does not make well positions and labware grip points less accurate

# Changelog

- Added new `ModuleOffsetData` pydantic model to contain `ModuleOffsetVector` and `DeckSlotLocation` data.
- The `CalibrateModuleResult` PE command now returns `ModuleOffsetData` to be used in `ModuleStore`.
- The `ModuleStore` now uses `ModuleOffsetData` instead of `ModuleOffsetVector` since we want to store both the offset and the deck slot location.
- The `get_module_calibration_offset` function now rotates the calibrated module offset by 180 degrees if the module was physically moved and rotated to a qualifying deck slot different from the original calibrated location.
- Make the `slot` member in the `ModuleCalibrationOffset` class into a required field since you won't have an offset without performing a calibration.
- Refactor module calibration loading mechanism so we don't need to pass in a slot arg as this is loaded from disk and will always be present.
- Loading module calibration now returns `Optional[ModuleCalibrationOffset]` instead of a default object, as some modules just haven't been calibrated yet and we don't want to assume the slot they were calibrated in.

# Review requests

- I'm a bit iffy on the implementation for the `_needs_rotation` function as this is a fixed set of locations we use to determine if a rotation is needed or not, so it feels rather brittle. I would love some feedback on this, maybe there's a better way of doing this.

# Risk assessment
- Low, module calibration has not been exposed yet.

2023-09-01 19:29 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/modules.py
> +
Re your review request:

Theoretically, I think the "proper" way to do this would be use the module definitions' `slotTransforms`. We would do something like `new_offset = new_slot_transform * (old_slot_transform^-1) * original_offset`. (I *think* that's how the matrix math works, anyway?)

2023-09-01 20:43 UTC, SyntaxColoring reviewed
[Lookin' good.](https://www.youtube.com/watch?v=PGNiXGX2nLU)

2023-09-01 20:43 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_module.py
> +
Beware that this will break things if robot-server's database has any stored runs with `CalibrateModuleResult`s. Fortunately, I don't think this is the case. If anything, these will be in special non-persisted maintenance runs, not regular runs. Is that correct?

2023-09-01 20:43 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/types.py
> +
Is this ever exposed over HTTP or stored on the filesystem? If not, we can make this a standard Python `@dataclass` instead of an icky `BaseModel`. :)

2023-09-01 20:43 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/modules.py
> +    B = (DeckSlotName.SLOT_D3, DeckSlotName.SLOT_C3, DeckSlotName.SLOT_B3)
If we do stick with this basic idea of implementing `_needs_rotation()` with a fixed set of locations, can we:

1. Change `A` and `B` to `COL_1` and `COL_3`? "A" and "B" are confusing to me because they look like they're referring to row A and row B.
2. Add `DeckSlotName.SLOT_A3`, where the fixed trash currently is? I don't want us to forget it when the trash is made movable, and I think it should be harmless to add it now.

2023-09-01 20:43 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/modules.py
> +        return offset
Could we add a unit test to cover this conditional rotation logic?

2023-09-06 15:57 UTC, sfoster1 requested changes
Can we use the slot transform for this? That would simplify a lot of the logic. The explicit "which slots need rotation" considerations are baked into the module definitions (though they may need added entries for flex-style names).

The slot transforms in the module definitions are 3d affine transforms in encoded matrix form; you can either use them as-is by augmenting the calibration offset to 1x4 with a `0` to get only the linear-transform-part or deaugment the affine transforms back to 3d linear transforms and multiply as normal.

2023-09-06 15:57 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/modules.py
> +
yeah this is what the slot transform is for. the general case fix would be to make the offset be `saved_offset * (original slot transform)^-1 * (new slot transform)`, basically what max said but the last multiplication is the new transform not the offset

2023-09-06 15:57 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/modules.py
> +                    rotation_vector = array([[-1, 0, 0], [0, -1, 0], [0, 0, 1]])
Yeah I would really prefer using the slot transform here

2023-09-07 18:10 UTC, vegano1 commented on api/src/opentrons/protocol_engine/commands/calibration/calibrate_module.py
> +
Yeah, this is correct, we have not exposed module calibration yet.

2023-09-27 20:51 UTC, sanni-t commented
> Can we use the slot transform for this? That would simplify a lot of the logic. The explicit "which slots need rotation" considerations are baked into the module definitions (though they may need added entries for flex-style names).
> 
> The slot transforms in the module definitions are 3d affine transforms in encoded matrix form; you can either use them as-is by augmenting the calibration offset to 1x4 with a `0` to get only the linear-transform-part or deaugment the affine transforms back to 3d linear transforms and multiply as normal.

Discussed in person with @vegano1 and @sfoster1 : we can't use slot transforms for rotating the calibration offset since that's not what the slot transforms are used as. The slot transforms are entities that will convert the default `labwareOffsetVector` to one appropriate for a particular slot on a particular machine. It will include rotational components only if the default vector needs to be rotated, which is not true of all modules on the OT2 and not true of any modules on the Flex since the module caddies take care of it for the modules that can be placed in multiple locations (temperature & H/S modules).

So the decision is to apply a separate rotation to just the calibration offset if the saved calibration was done on a slot in a different column than the current location. Then this rotated calibration offset will be added to the nominal, slot transformed module offset to get the final, calibrated offset vector for a labware on the module.

2023-10-02 17:20 UTC, sfoster1 approved these changes
Looks good once we get some tests for the rotation process and logic in there!

2023-10-02 17:20 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +        if offset_data:
can we invert this so it's like `if not offset_data: return offset` and then dedent the rest of the function

2023-10-02 17:20 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +            assert set([calibrated_slot_column, current_slot_column]).issubset(
should be, or be caught by, an enumerated error

2023-10-02 17:20 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/module_calibration.py
> +    if module_offset_data:
if we invert this logic so it's `if not module_offset_data: return None`, then we can `return ModuleCalibrationOffset(...)` directly

2023-10-02 20:11 UTC, sanni-t approved these changes
LGTM!
As @sfoster1 mentioned, we should add a test that tests the rotation of the offsets.

2023-10-02 20:11 UTC, sanni-t commented on api/src/opentrons/hardware_control/ot3api.py
> +            return None
Nice

2023-10-02 20:11 UTC, sanni-t commented on api/src/opentrons/hardware_control/modules/module_calibration.py
> +            slot=module_offset_data.slot,
Saving the slot data in module calibration is already implemented in 7.0.0, ya? Just making sure that there won't be any calibration files in the field that don't have the slot field which could lead to file parsing errors.

2023-10-02 20:11 UTC, sanni-t commented on api/src/opentrons/protocol_engine/state/geometry.py
> +            assert set([calibrated_slot_column, current_slot_column]).issubset(
I think an assertion is fine because this will never be false since you can't load connected modules in any columns other than 1 & 3. The only way I can think of making this assertion fail is by messing with the saved calibration file.

The assertion here is just making super sure that the data is relevant for the calculation that follows since we don't do this check anywhere in calibration flow. Also in a way, it also provides a context as to why we're performing rotation.

(We usually use asserts instead of explicit errors when we are either just placating mypy or when the condition we are asserting is practically impossible but is only implied so from other parts of the code)

2023-10-02 20:11 UTC, sanni-t commented on api/src/opentrons/protocol_engine/state/modules.py
> +    def get_calibration_module_offset(
Just a nitpick (feel free to discard), but I think this should be called `get_module_calibration_offset`. 

This is how these two sound to me-
`calibration_module_offset` -> offset of a calibration module
`module_calibration_offset` -> offset from a module calibration process

2023-10-04 20:06 UTC, merged