feat(api) Add ability to configure liquid class in Protocol Engine
OpenTrons/opentrons-api pull request #13459
Opened 2023-09-04 20:54 UTC by Laura-Danielle

# Overview

This should encapsulate some of the work required to add an additional command to update the liquid class in the protocol engine. I did not edit the user facing API yet because I thought that would be better suited in a follow-up PR, though I expect it to be a much faster follow-up than this PR.

# To Do

- [ ] Fix failing tests (which might be due to bug in code I wrote)
- [ ] Rebase on latest 7.0.0
- [ ] Ensure that the command for updating liquid class is in all the correct places without being utilized by `core` yet

# Test Plan
Make sure you can still successfully simulate and run a protocol

# Changelog

- Add the ability to change the liquid class type in `prepare_for_aspirate`
- Add a `model_version` in the pipette dict so that the protocol engine can use that value to look up static configs
- Modified the static configs to pass in the liquid class and look up the rest of the data in the `state/pipettes.py` file

# Review requests

Check that the code makes sense and such.

# Risk assessment

Medium-ish. Theoretically there should be no information change (aside from updating the run-time static config).

2023-09-05 14:25 UTC, sfoster1 requested changes
I think we should use https://github.com/Opentrons/opentrons/pull/13452 with some changes for the hardware side of this - i'll change its `configure_for_volume` implementation to take a liquid class by name.

i think this PR looks ok on the PE side of things but in my opinion the big thing we should change is: let's not hold the active liquid class and tip settings in PE state. doing that means we duplicate state and logic with the hardware controller while running pipettes. instead, let's have hardware handle it as in the other PR, and i'll refactor that other pr to have some reusable statics that we can implement in the pipette data provider.

2023-09-05 14:25 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/pipettes.py
> +            liquid_class = LiquidClasses.default
wait so doing a pipette settings override implicitly swaps back to the default liquid class?

2023-09-05 14:25 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/pipettes.py
> +            liquid_class = LiquidClasses.default
and default tip setting?

2023-09-05 14:25 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/pipettes.py
> +                    liquid_class, liquid_class.max_volume
this probably wants to be some default value since a liquid class's max volume might not be that of a valid tip

2023-09-05 14:25 UTC, sfoster1 commented on api/src/opentrons/hardware_control/dev_types.py
> +    liquid_properties: Dict[
I really don't like dumping the entire property set in here. I know that we need some of the data available upstream especially for the whole PE-only analysis thing but this is feeling like a whole lot, especially since it doesn't even say _which_ liquid class is active.

2023-09-05 14:25 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot2/pipette.py
> +        if liquid_class:
we should not handle an `optional` like this. either this argument should not be `optional` or this function should have a fallback if the argument isn't specified.

2023-09-05 14:25 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/pipettes.py
> +            new_liquid_properties = config.liquid_properties[liquid_class]
The more I read this the more I think this stuff shouldn't live in state directly. I think this command should be calling the liquid class switcher, and since it's separate I think the liquid class switcher should _not_ be prepare for aspirate, and which liquid class is currently active should be remembered by hardware and mirrored in the data provider

2023-09-05 18:08 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/state/pipettes.py
> +            liquid_class = LiquidClasses.default
You can only override settings with the new `UpdateLiquidClass` setting. Otherwise this is always a 'fresh start' command if you will.

2023-09-06 16:12 UTC, closed without merging

2023-09-06 16:12 UTC, Laura-Danielle commented
Closing this in favor of a different branch.