Configure liquid class protocol engine
OpenTrons/opentrons-api pull request #13473
Opened 2023-09-06 16:36 UTC by Laura-Danielle

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-09-06 18:27 UTC, sfoster1 requested changes
I don't think this is quite what we want. We want an action that changes the liquid class by sending over the new name, and is handled by calling the `set_liquid_class` method in hardware and then updating the loaded pipette config from hardware (or calling an equivalent function when simulating).

2023-09-06 18:27 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/actions/actions.py
> +    serial_number: str
the serial number definitely shouldn't be in here - that would make it impossible for the action to exist in a json protocol that won't know the serial number

2023-09-06 18:27 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/actions/actions.py
> +    config: pipette_data_provider.LoadedStaticPipetteData
This also doesn't seem right - the payload here should be the liquid class name and not much else. That will get executed by being passed down to the hardware.

2023-09-07 18:35 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/configure_for_volume.py
> +    pipetteId: str = Field(
why do we need the pipetteId in the result?

2023-09-07 18:37 UTC, sfoster1 requested changes
Looks like exactly what we want, save the copypasta in the command implementation, sharing the logic, and fixing that one hysteresis logic defn

2023-09-07 18:37 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/pipette.py
> +            if volume < (self.liquid_class.max_volume * 0.5):
I think this wants to be < than half the max volume of the low volume default

2023-09-07 18:37 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +        # TODO (spp, 2023-05-10): either raise error if using MountType.EXTENSION in
copypasta

2023-09-07 18:37 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +            pipette_dict = self._hardware_api.get_attached_instrument(
don't need to do this

2023-09-07 18:37 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +                await self._hardware_api.cache_instruments(cache_request)
don't need this

2023-09-07 18:37 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +            other_mount = mount.other_mount()
don't need the other mount and cache pipette stuff

2023-09-07 18:37 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +            if volume < 5 and is_p50_flex_pipette:
we should use the exact same logic - maybe make `liquid_class_for_volume` a free function taking 
- the requested volume
- the current liquid class
and reutrning a liquid class, that can get called both here and in hardware?

2023-09-07 18:42 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +                    else other_pipette.pipetteName
as we spoke about in the morning call. I guess we can extract this logic to a method bc we are doing the same for the `load_pipette`?

2023-09-07 18:56 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +                    else other_pipette.pipetteName
we don't need to do this logic in here at all I think

2023-09-08 13:52 UTC, TamarZanzouri commented on api/src/opentrons/hardware_control/instruments/ot3/pipette_handler.py
> +            return
do we want to raise here instead?

2023-09-08 14:12 UTC, TamarZanzouri approved these changes
thank you for the changes! this looks great to me!

2023-09-11 14:47 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/command_unions.py
> +CommandPrivateResult = Union[None, LoadPipettePrivateResult]
are we missing `ConfigureForVolumePrivateResult` ?

2023-09-11 15:48 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/pipettes.py
> +                    tip_configuration = list(
do we want to leave a comment about defaulting?

2023-09-11 15:55 UTC, TamarZanzouri commented
looks great to me! had a few questions but overall love the private setting change :-)

2023-09-11 16:05 UTC, jbleon95 approved these changes
Reviewed the Protocol Engine portions of this PR, all look good to me outside of minor comments and fixing up the failing CI tests. Really like the private result addition, we can definitely use that in the future to clean up some result cruft.

2023-09-11 16:05 UTC, jbleon95 commented on api/src/opentrons/protocol_engine/commands/command.py
> +    """Abstract command creation and execution implementation.
Doc strings for this new Abstract Implementation should be updated to not just be copypasta'd from above.

2023-09-11 16:05 UTC, jbleon95 commented on api/src/opentrons/protocol_engine/commands/configure_for_volume.py
> +    pipetteId: str = Field(
Is there a reason why were are returning pipetteId in the result, because unless it's changing I don't think it should be included.

2023-09-11 16:05 UTC, jbleon95 commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +            pipette_id: An optional identifier to assign the pipette. If None, an
Not optional for this method

2023-09-11 16:05 UTC, jbleon95 commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +            serial_number = self._model_utils.generate_id(prefix="fake-serial-number-")
the fact that we are regenerating serial number here for the simulated case feels a bit iffy even though in practice I don't believe it will have any actionable impact on how we do analysis. The only place we are using serial number is for `get_calibrated_tip_length` which already is referencing a fake serial number in the first place. Still just calling it out here for maybe a comment or not explaining this.

2023-09-11 16:05 UTC, jbleon95 commented on api/tests/opentrons/protocol_engine/execution/test_equipment_handler.py
> +    monkeypatch.setattr(
Since `VirtualPipetteDataProvider` is now a class we should avoid monkeypatching it here and instead make the below pytest fixture a decoy mock of that class, unless there is some functional reason why we are doing it this way.

2023-09-11 16:40 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/commands/configure_for_volume.py
> +    pipetteId: str = Field(
All the pipette commands include the pipette id.

2023-09-11 16:51 UTC, Laura-Danielle reviewed
Cannot approve my own pull request but I like the private results update a lot.

2023-09-11 18:50 UTC, SyntaxColoring reviewed
Generally looks great to me. Thanks!

2023-09-11 18:50 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/configure_for_volume.py
> +    pipetteId: str = Field(
Mm, `loadPipette` has a `result.pipetteId` because that's the thing that creates the `pipetteId`. Other pipetting commands, like `aspirate` and `blowOut`, do not. (They instead take a `pipetteId` as input, in `params`.)

I agree with @jbleon95—let's remove `pipetteId` from this result model.

2023-09-11 18:50 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/command.py
> +
Low-priority nitpick: I would not bind this to `BaseModel`, because `BaseModel` is for stuff that's serialized, and private results are deliberately never serialized.

And I guess I'd make `ConfigureForVolumePrivateResult` a `@dataclass` instead of a `BaseModel`.

2023-09-11 18:50 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/load_pipette.py
> +        )
Nitpick for slightly faster analysis:
 
```suggestion
        return LoadPipetteResult.construct(
            pipetteId=loaded_pipette.pipette_id
        ), LoadPipettePrivateResult.construct(
            pipette_id=loaded_pipette.pipette_id,
            serial_number=loaded_pipette.serial_number,
            config=loaded_pipette.static_config,
        )
```

2023-09-11 19:29 UTC, sfoster1 approved these changes
get rid of my own negative review

2023-09-11 19:29 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/configure_for_volume.py
> +    pipetteId: str = Field(
we don't really, might remove it

2023-09-11 19:29 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/pipette_handler.py
> +            return
yeah probably

2023-09-11 19:30 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/command_unions.py
> +CommandPrivateResult = Union[None, LoadPipettePrivateResult]
we were!

2023-09-11 19:33 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/configure_for_volume.py
> +    pipetteId: str = Field(
done

2023-09-11 19:39 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/command.py
> +
that's a good point, there's no reason for it to be like that

2023-09-11 19:39 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/command.py
> +
honestly there's not really a reason to have a bound at all in that case tbh

2023-09-11 20:25 UTC, merged