feat(backend): allow variable number of tip presence messages
OpenTrons/opentrons-api pull request #13478
Opened 2023-09-06 19:01 UTC by caila-marashaj

## Overview
Currently, the hardware controller is only able to process one tip presence notification. This changes `tip_presence.py` to wait for and return either 1 or 2 notifications, as a `List[int]` rather than an `int`. 

At the hardware controller level, we check that both responses are the same, and then handle the tip presence status as a single value.

2023-09-06 19:21 UTC, sfoster1 approved these changes
Looks good, though I would like to change the name of the backend argument - I feel like ideally it's just the hardware controller that knows about the 96

2023-09-06 19:21 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        is_ninety_six_channel: bool = False,
i'd love to see this changed to like `expect_multiple_responses` or something

2023-09-06 19:41 UTC, Laura-Danielle requested changes, later dismissed
We should still not be checking tip presence for the 96 chan until we implement the motor routine.

2023-09-06 19:41 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +        if ff.tip_presence_detection_enabled():
we're not quite ready to enable 96 channel tip presence. We need the motor routine to do this.

2023-09-06 20:11 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    async def get_tip_present_state(
Imo I don't think we should return a list. We should `AND` the result if there are two values in the list. And then we can keep the rest of the logic.

Otherwise, you'll have to do some funky stuff with getting the correct state for `pipette_state_for_mount`

2023-09-06 20:12 UTC, caila-marashaj commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    async def get_tip_present_state(
agree, that makes sense

2023-09-07 13:51 UTC, ahiuchingau approved these changes
One nit otherwise looks good to me!

2023-09-07 13:51 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    async def get_tip_present(
I know this func was created before this PR, but if it's not too much work we really should rename this function since it's not returning a value

2023-09-07 14:13 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    async def get_tip_present(
can call it `check_for_tip_presence` or something

2023-09-11 13:32 UTC, sfoster1 approved these changes
Looks good once @Laura-Danielle 's changes are addressed, some nitpicks/improvements

2023-09-11 13:32 UTC, sfoster1 commented on api/src/opentrons/hardware_control/types.py
> +class UnmatchedTipStates(RuntimeError):
We should make this an enumerated error - something new in the 1xxx series of errors in `shared-data/errors/exceptions` and codes and such.

2023-09-11 13:32 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            raise UnmatchedTipStates()
this exception should contain the two conflicting states explicitly

2023-09-11 13:32 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        if res[0] != res[-1]:
i like this, it's elegant. however, i think it's better to be explicit here and check that all responses are the same value by doing something like `if not all([r == res[0] for r in res])`

2023-09-11 13:32 UTC, sfoster1 commented on api/src/opentrons/hardware_control/types.py
> +        """Iniitialize FailedTipStateCheck error."""
```suggestion
        """Initialize FailedTipStateCheck error."""
```

2023-09-11 13:32 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tip_presence.py
> +    expected_responses: int = 1,
one thing we might want to consider here is typing this function with overloads like this:
```python
@typing.overload
async def get_tip_ejector_state(can_messenger: .., node: Literal[...], expected_responses: Literal[1] timeout: ...) -> Tuple[int]
    ...

@typing.overload
async def get_tip_ejector_state(can_messenger: ..., node: Literal[...], expected_responses: Literal[2], timeout: ...) -> Tuple[int, int]:
    ...

async def get_tip_ejector_state(): ...code...
```

This makes it explicit that callers can expect the same length return value as the number they fed in.

2023-09-13 19:06 UTC, sfoster1 requested changes
Couple more small changes, only really important one is the error code

2023-09-13 19:06 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        tip_present_state = bool(vals[0]) and bool(vals[-1])
at this point we know all entries in `vals` are the same (if not, we would have raised the exception) so we can just do `bool(vals[0])`

2023-09-13 19:06 UTC, sfoster1 commented on shared-data/errors/definitions/1/errors.json
> +      "category": "roboticsControlError"
if this is in the `roboticsControlerror` category, its error number should be in that category's error number - presumably 2012, as befits its apocalyptic nature

2023-09-13 19:06 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/errors/codes.py
> +    UNMATCHED_TIP_PRESENCE_STATES = _code_from_dict_entry("4004")
`2012` probably, or matching whatever you change it to above

2023-09-13 20:59 UTC, sfoster1 approved these changes
Noice! Looks good to me if tests pass.

2023-09-13 21:17 UTC, merged