Add usb rsa key
OpenTrons/opentrons-api pull request #13509
Opened 2023-09-11 13:51 UTC by vegano1

# Overview

The Flex does not use a link-local connection to the host computer so we cannot use `curl` to add a public SSH rsa key via the `/server/ssh_keys` endpoint like we do for the OT-2. Ideally, we have a mechanism that will formulate an add-key request and send that to the Flex via the usb-bridge connection where it will be handled as a normal HTTP request. However, we don't yet have that feature setup and we need to disable root password logins for the Yocto builds. So let's add an alternative way to securely add SSH-RSA keys that still require local access to the robot in order to add an SSH key. 

This PR accomplishes this by adding a new server utility intended to run from Jupyter Notebook that, scans for USB thumb drives on the Flex, finds any .pub files, validates, and then adds them to the `~/.ssh/authorized_keys` file.

# Test Plan

- [ ] Connect a USB thumb drive to a Flex containing a valid public rsa key file file, start Jupyter Notebook run the `add_ssh_keys_from_usb` method, and make sure the pub key is added to the `~/.ssh/authorized_keys` file.
- [ ] Connect a USB thumb drive to a Flex with invalid .pub files, no keys should be added to the `~/.ssh/authorized_keys` file.
- [ ] Disable SSH password logins by adding the '-s' arg to `DROPBEAR_EXTRA_ARGS` and make sure we can't SSH without first adding a valid public key using this utility. 

# Changelog

- Added `ssh_keys.py` module to server_utils package so we can add SSH rsa keys from thumb drives using Jupyter Notebook.

# Review requests

# Risk assessment
Low

2023-09-11 14:02 UTC, sfoster1 requested changes
Can we bind this to a route somewhere, like `POST /server/ssh_keys/from_local` or something in the update server? That way it's easy to make a button that does it in the ui and we can still get people to `curl` it. We don't need to limit where they can `curl` from because it will only handle things from devices physically plugged in to the machine.

Also, let's refactor this so that it raises exceptions or returns a string status or something rather than printing - when it prints like this we can't really reuse it in other code.

2023-09-11 16:31 UTC, vegano1 commented
> Can we bind this to a route somewhere, like `POST /server/ssh_keys/from_local` or something in the update server? That way it's easy to make a button that does it in the ui and we can still get people to `curl` it. We don't need to limit where they can `curl` from because it will only handle things from devices physically plugged in to the machine.
> 
> Also, let's refactor this so that it raises exceptions or returns a string status or something rather than printing - when it prints like this we can't really reuse it in other code.

This is the way

2023-09-11 19:29 UTC, sfoster1 approved these changes
Would love to see this using python for the directory search rather than subprocess but looks good!

2023-09-11 19:29 UTC, sfoster1 commented on update-server/otupdate/common/ssh_key_management.py
> +    pub_keys = (
imo we should use `os.path.walk` rather than shelling out but this will also work

2023-09-12 14:15 UTC, sfoster1 approved these changes
Looks good to me, thank you!

2023-09-12 14:23 UTC, merged