feat(app, shared-data, protocol-designer, step-generation): frontend low volume support
OpenTrons/opentrons-api pull request #13526
Opened 2023-09-12 17:00 UTC by jerader

closes RAUT-714

# Overview

This adds low volume front-end support

# Test Plan

in PD:

- create a Flex protocol with a p50 pipette (single or 8-channel). 
- Add a transfer step and make the volume > 1uL, see that in the dispense advance settings, the `push out` option is disabled with a tooltip explaining why.
- go back and change the volume = 1uL, see that the "push out" setting is available and clickable. Click it.
- save and download the protocol and open up the json file. see that `configure_for_volume` command occurs before the `aspirate` with the correct commands. See that the `dispense` command has the `pushOut` param with the correct volume (volume should be 1, which matches the aspirate volume).
- go back and create a new PD protocol for the ot-2, see in the transfer form that the `push out` option is not available.

in the App:

This is not testable yet since there are no backend changes in `chore_release-7.0.0` yet. But just review the `commandText` for the `configureForVolume` and `dispense` command.

# Changelog

in shared-data:
- add the types for `ConfigureForVolumeCreateCommand` and ConfigureForVolumeRunTimeCommand`, add the optional `pushOut` param to `dispense` command

in app:
- add logic in `commandText` and add test cases

in PD:
- add the `dispense_pushOut` value to `transfer` form
- add logic for when the advanced setting in transfer are disabled, adding tooltip as well
- add to the migration file to migrate all `transfer` stepTypes to include the `pushOut` boolean value
- fix cypress e2e tests to include the `pushOut` value 

in Step-generation:
- create new `configureForVolume.ts` atomic command, add test for it
- add logic for emitting the command in `transfer.ts` before an `aspirate` happens and volume is 1uL and with the correct pipettes.

# Review requests

see test plan

# Risk assessment

low

2023-09-12 17:01 UTC, jerader commented on app/src/assets/localization/en/protocol_command_text.json
> +  "configure_for_volume": "Configure {{volume}} µL for aspirating with {{pipette}}",
@ecormany , this is the commandText in the run log for configure_for_volume, does it make sense to you?

2023-09-12 17:01 UTC, jerader commented on app/src/assets/localization/en/protocol_command_text.json
> +  "dispense_push_out": "Dispensing {{volume}} µL into well {{well_name}} of {{labware}} in {{labware_location}} at {{flow_rate}} µL/sec with push out volume {{push_out_volume}} µL",
@ecormany and this is the commandText for dispensing with the pushOut param

2023-09-12 17:11 UTC, jerader commented on step-generation/src/commandCreators/compound/transfer.ts
> +          const configureForVolumeCommand: CurriedCommandCreator[] =
note: this command is emitted every time the volume is 1uL and the pipette is a p50 gen3. But that is unnecessary and we want to only emit it if the previous aspirate with the pipette is not 1uL. 

I'm probably being dumb but I am not sure how to do that because the only way to get the `savedStepForms` is by grabbing the PD selector which i think would result in a circular dependency? I don't think step-generation uses redux at all. IDK i have to think about how to accomplish this more 🤔

2023-09-12 19:17 UTC, sfoster1 commented
App command render looks good!

2023-09-12 20:33 UTC, ecormany commented on app/src/assets/localization/en/protocol_command_text.json
> +  "configure_for_volume": "Configure {{volume}} µL for aspirating with {{pipette}}",
To be really useful, I would like the run log text to say what _mode_ the pipette is placed in. I chatted some with @andySigler about this yesterday, although I don't think we came to a final decision re: run log.

If, at least at this point, the run log is just going to report the arguments passed to `configureForVolume`, then I'd suggest `Configure {{pipette}} to aspirate {{volume}} µL`

2023-09-12 20:47 UTC, ecormany commented on app/src/assets/localization/en/protocol_command_text.json
> +  "dispense_push_out": "Dispensing {{volume}} µL into well {{well_name}} of {{labware}} in {{labware_location}} at {{flow_rate}} µL/sec with push out volume {{push_out_volume}} µL",
oof this is long but i dunno that there's much we can do…
```suggestion
  "dispense_push_out": "Dispensing {{volume}} µL into well {{well_name}} of {{labware}} in {{labware_location}} at {{flow_rate}} µL/sec and pushing out {{push_out_volume}} µL",
```
do we need to state the push-out flow rate or is it constant?

2023-09-12 21:06 UTC, mjhuff approved these changes
It's hard for me to tell if conceptually these changes are correct (since I'm still learning PD), but I tested per your instructions and everything works. The JS lgtm as well! 🚀

2023-09-12 21:17 UTC, jerader commented on app/src/assets/localization/en/protocol_command_text.json
> +  "configure_for_volume": "Configure {{volume}} µL for aspirating with {{pipette}}",
Oh wow, that order of words makes way more sense than what I had 😅

2023-09-12 21:35 UTC, sfoster1 requested changes
Stuff from initial testing
- ✅ app rendering of configure looks good 
   - ❓  though it says "Configuring 1 ul for aspiration with <blah blah pipette>" and maybe it should say "Configuring <blah blah> pipette to aspirate 1ul"
- ❌ PD UI for push out needs to change; we should either not
   - not have push out UI at all (my pref) because specifying it is complex (see below) and not emit the arg in step-generation so it uses default settings or
   - have push out be a check box _that defaults to checked_, such that when it's checked step-generation doesn't emit the push out arg and when it's not checked step-generation emits it with a 0 value
   - have push out be the same "default or set value" ui field that we have elsewhere where defaulted is null/not present in s-g, and a real value is set to that value. note that here it can only be shown on full dispenses and the limits for the value have to be computed from the liquid settings as (bottom-blow_out)*plunger_surface_area
- [ ] haven't tested the actual generated protocol yet though

2023-09-12 21:49 UTC, sfoster1 requested changes
`configureForVolume` needs to be emitted more frequently. right now it's emitted only before 1ul aspirates, which means the pipette could never switch out of the low volume mode. we need to, on flex 50ul pipettes, emit before each aspirate that starts with the plunger empty, with the total volume we'll aspirate until the next time the plunger is empty

2023-09-13 15:17 UTC, sfoster1 approved these changes
- [x] made a protocol in PD branch with 50ul 1 and 8 channels
   - [x] with a variety of transfer volumes, always saw configure for volume
   - [x] protocol analyzed successfully in app branch
   - [x] ODD and app runlog displayed configures successfully
   - [x] configures executed properly traced through to api logs
- [x] made protocol with mix in PD branch
   - [x] saw configure before mix multistep
- [x] made protocol with 1000ul pipettes and saw no configure for volumes

Looks good to me in my dev testing!

2023-09-13 15:21 UTC, merged