Rliq 425 tip configuration manager
OpenTrons/opentrons-api pull request #13582
Opened 2023-09-18 20:56 UTC by Laura-Danielle

# Overview

With this PR you will now be able to configure your pipette to have different nozzle configurations to support partial tip in the hardware controller. The one thing it does _not_ handle right at this moment is modifying current based on configuration. I realized during this PR that having a current scalar does not work -- especially with a 96 channel -- because it will quickly exceed max current.

# TODO

- [ ]  Fix failing tests. It's possible that I'm no longer grabbing the 'exact' same location for the XY_CENTER locations -- will look more into this tomorrow.
- [ ]  Decide if it still makes sense to support `NOZZLE` overrides when a tip is attached to a pipette.

# Test Plan

Please verify that all of the following operations still work as expected:
- [ ]  attaching/de-attaching pipettes
- [ ] Dropping tip in trash
- [ ] Moving to labware during LPC
- [ ] Attaching a pipette probe and performing auto-calibration

# Changelog

- Adds a nozzle configuration manager
- Adds functions in hw pipette/hw controller to update the nozzle configuration

# Review requests

Let me know if anything seems weird to you aside from physical testing on the robot. Is the interface for nozzle names OK as well?

# Risk assessment

High. This touches a critical component of the code which affects robot positioning.

2023-09-21 13:45 UTC, sfoster1 requested changes
I like where this is going but I think there's some stuff we should change.

First, on the critical point thing - XY_CENTER is the geometric center of the pipette footprint, that's it and that's all. It doesn't, can't, and shouldn't align to the position of a specific nozzle because it's not _about_ a nozzle - it's about the pipette as a whole. It should remain that geometric center, which the nozzle manager can tell you about because you've encoded nozzle maps such that (0,0) is the geometric center.

Second, there's a number of things in nozzle manager that I don't love - like keeping the nozzles as a list of values plus list of keys rather than a dict, for instance - that seem to be done to keep a concept of a logically-linear arrangement of tips. For instance, you pick up tips starting at some nozzle and continuing for a number of tips; you set a nozzle configuration with a starting tip and a number of tips. I think a lot of that gets simpler if you instead define nozzle configurations as oriented rectangles of nozzles, and store the back-left and front-right. 

This gives you a couple good features:
- it's very easy to do something like "upper left quadrant" as a configuration, or "left two columns but not bottom row" with pretty intuitive interfaces
- you're storing the nozzle locations of semantic relevance in the back-left and front-right, which means that if you want to know their positions (e.g. for critical points) you don't have to do calculations based on a hardcoded row/column number, you just look it up from the config
- we will at some point need to treat these nozzle configurations this way anyway on some layer so we can do collision checks with tips

This does come at the cost of having more complex code to think in terms of rectangles rather than lists but I really think it's worth it.

2023-09-21 13:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +class IncompatibleNozzleConfiguration(Exception):
should be an enumerated error

2023-09-21 13:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +        self._nozzle_map: List[Tuple[str, List[float]]] = list(
feels like internally we should keep the nozzle offsets as `Point`s

2023-09-21 13:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +        self._nozzle_map_key_lookup = list(nozzle_map_ordered_dict.keys())
can't we just store the nozzle map as an ordered dict rather than as an array of values plus an array of keys with identical ordering? feels kind of fragile

2023-09-22 15:23 UTC, sfoster1 requested changes
Liking this a lot more now; I think we can tighten up some naming stuff and we would benefit from a sort of first-class nozzlemap class though.

2023-09-22 15:23 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +    def _get_nozzle_for(self, critical_point: CriticalPoint) -> Point:
nit: this really isn't returning a nozzle, this is returning a point, call it something else maybe?

2023-09-22 15:23 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +                message=f"Starting nozzle {back_left_nozzle} must not be greater than the ending nozzle {front_right_nozzle}.",
can we phrase this differently it's very weird from a user perspective to consider "H1" as "greater than" "A1"

2023-09-22 15:23 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +    def update_nozzle_with_tips(
should this be called this? it doesn't really seem to have anything to do with tips, it just sets the nozzle config

2023-09-22 15:23 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +    def update_nozzle_with_critical_point(
this doesn't really update anything, right? it just calculates and returns the critical point

2023-09-22 15:23 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +        self._current_nozzle_configuration = nozzle_configuration
should this or its `.configuration` be accessible somewhere as like a property?

2023-09-22 15:23 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +    configuration: NozzleConfigurationType
looking at what `NozzleConfigurationType` means, maybe this should be a property?

2023-09-22 15:23 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +            # TODO gotta fix this to be a real nozzle
I think this might benefit from `nozzlemap` being its own class that you build from a dict, that has accessors like "back_left` and `front_right` and `front_left` and `configuration` (i.e. row/column/rectangle).

At that point, `NozzleManager` can hold two `NozzleMap`s - the `physical` and the `current`. `NozzleManager.__init__` takes a `NozzleMap`, and this builder becomes `build_from_nozzledict` and just builds a map and then passes it in.

2023-09-22 15:23 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +    def nozzle_offset(self) -> Point:
can we call this like `standard_nozzle_offset` or something, IMO it needs a further identification than just "nozzle" because the point of this class is to handle having multiple nozzles

2023-09-22 15:23 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +        if back_left_nozzle > front_right_nozzle:
IMO these checks want to be a free function somewhere or on that `NozzleMap` class

2023-09-22 15:30 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +        self._current_nozzle_configuration = nozzle_configuration
yeah, I am doing that in the follow-up current setting PR because we're not currently using it here.

2023-09-25 06:51 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +    def update_nozzle_with_critical_point(
technically it updates the critical point with the tip length, but I can change the name a little bit.

2023-09-25 16:35 UTC, sfoster1 approved these changes
I haven't yet tested, this is just about the code.

I think this code is good to merge (once I test it) but I think pretty soon we should follow up with a refactor that treats the physical layout from the defs of the nozzles as the basis of data and gets away from the internozzle distance. If we can encode the row/column layout in the pipette general def and make decisions about backleft/front right from those rather than playing around with nozzle offsets i think the code will be cleaner

2023-09-25 16:35 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +        :param nozzle_difference: the difference between
incomplete sentence?

2023-09-25 16:35 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +        nozzle_difference: Point,
I think this logic works but it really feels like it should be about nozzle names rather than points, i dunno

2023-09-25 16:35 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +    def xy_nozzle(self) -> Point:
I really don't like having it called this because it doesn't actually represent the position of any nozzle. can we call it `xy_center` or something?

2023-09-25 16:35 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +    def front_nozzle(self) -> Point:
maybe front nozzle offset?

2023-09-25 16:43 UTC, Laura-Danielle commented
@sfoster1 I'll make a ticket to track those changes, but I think it should be low priority as compared to the rest of the partial tip feature set.

No rush on the testing also. We really shouldn't pick up tips until my follow-up current PR.

2023-09-25 16:44 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +        :param nozzle_difference: the difference between
yes will fix.

2023-09-25 16:45 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +        nozzle_difference: Point,
we can't determine the actual configuration unless we had all four corners of the square, which would still require some type of logic similar to this.

2023-09-25 18:40 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/pipette.py
> +            self.current_tip_length if cp_override != CriticalPoint.NOZZLE else 0.0,
let's preserve the behavior from before where this is
```
if not self.has_tip or cp_override == CriticalPoint.NOZZLE
    tip_length = 0
else:
    tip_length = self.current_tip_length
```
and then pass that in. that way we're insulated from someone forgetting to explicitly reset the tip length to 0

2023-09-26 19:46 UTC, ahiuchingau approved these changes
Sick nozzle manager, can't wait to see partial tip pickup in action

2023-09-26 20:25 UTC, sfoster1 approved these changes
Tested LPC and protocols on a flex with a reservoir and a plate, looks good to me!

2023-09-29 14:15 UTC, merged