fix(hardware-testing): Change 96ch pipette name in photometric calibration protocols
OpenTrons/opentrons-api pull request #13620
Opened 2023-09-21 19:30 UTC by meh-di

Calibration protocols for the 96ch pipette were using `p1000_96` as the name. This needs to be changed to `flex_96channel_1000`.

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-09-21 19:30 UTC, vegano1 approved these changes
nice

2023-09-21 19:32 UTC, andySigler requested changes
Can you go through all the protocols while you're at it and make sure they all have the correct names?

2023-10-24 05:11 UTC, andySigler approved these changes

2023-10-24 05:14 UTC, andySigler commented
this PR might be outdated now

2024-02-12 14:33 UTC, merged