feat(api) Support changing current based on tip configuration
OpenTrons/opentrons-api pull request #13660
Opened 2023-09-26 20:42 UTC by Laura-Danielle

# Overview

With this PR, we should now be able to perform partial tip configuration movements in the hardware controller. 

# Test Plan

- Check that the following works:
- [ ] Full configuration pick-ups
- [ ] Single pick ups (8 channel and 96 channel)
- [ ]  Column pick ups (96 channel only)
- [ ] Quadrant pick ups (96 channel only)

We should also check that these movements persist for liquid handling functions as well.

# Changelog

- Change the current scalar in the pipette configurations to be a current map
- Utilize this new current map to determine the pick up current only (HW folks, not sure if anything should _also_ change for drop tip. Please let me know).

# Review requests

HW folks, please comment and tell me what the partial currents should _actually_ be. I made up numbers here.
SW folks, let me know if anything seems weird/gross/whatever.

# Risk assessment

Medium. We should ensure that normal configuration tip pick-ups have not deviated from normal.

2023-09-26 20:52 UTC, sfoster1 requested changes
The code looks good to me! Will have to test on a machine though

2023-09-26 20:52 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +        pick_up_current_map: Optional[Dict[int, float]] = None,
in what situations would we not have a `pick_up_current_map`? does it have to be `= None`?

2023-09-26 20:53 UTC, sfoster1 approved these changes
Review now with appropriate resolution selected

2023-09-29 14:04 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +        pick_up_current_map: Optional[Dict[int, float]] = None,
single channels do not have a pick up current map.

2023-10-02 13:43 UTC, andySigler commented on shared-data/pipette/definitions/2/general/eight_channel/p1000/3_5.json
> +      "8": 0.9
are these real values? if not let's get those

2023-10-02 13:44 UTC, andySigler commented on shared-data/pipette/definitions/2/general/eight_channel/p1000/3_5.json
> +      "8": 0.9
Also is the current value defined in the `pickUpTipConfigurations` being used anywhere anymore?

2023-10-05 17:14 UTC, sfoster1 requested changes
From HW:
Let's change the values for the `perTipPickupCurrent` configurations such that:
- For 1-channel pickups, the current is the same as the pickup current for the single-channel version of the pipette
- For 2-7 channel pickups inclusive, the current is `Ntips / Nchannels` times the as-of-now 8channel pickup current
- For 8 channel pickups, the current is the same is the as-of-now 8channel pickup current

These will be good for the OT-2 pipettes (the different nozzle geometry means the overlap positioning won't change much), and they'll be good starting points for more in-depth testing of the Flex configurations.

From me:
We also should probably get rid of `pickUpTipConfigurations.current`.

2023-10-06 15:01 UTC, Laura-Danielle commented on shared-data/pipette/definitions/2/general/eight_channel/p1000/3_5.json
> +      "8": 0.9
no these are not real numbers. `pickUpTipConfigurations` current will not be used anymore.

2023-10-11 17:47 UTC, sfoster1 reviewed
Code looks good, will try and get this tested!

2023-10-11 17:47 UTC, sfoster1 commented on shared-data/pipette/definitions/2/general/eight_channel/p1000/1_0.json
> +  "displayName": "Flex 8-Channel 1000 \u03bcL",
```suggestion
  "displayName": "Flex 8-Channel 1000 μL",
```

2023-10-11 17:47 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +            len(self._current_nozzle_configuration.map_store)
nit: i would love it if the nozzle configuration objects had like `tip_count` property that did this or something but it's ok if it works

2023-10-11 18:20 UTC, caila-marashaj approved these changes
looks good on hardware!

2023-10-11 20:33 UTC, sfoster1 approved these changes
Ah, looks like @caila-marashaj did some in person testing so we're good - let's just fix that malformed mu

2023-10-12 13:38 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/instruments/nozzle_manager.py
> +            len(self._current_nozzle_configuration.map_store)
sure can do that

2023-10-16 16:51 UTC, merged