refactor(api): split 96 pickup and dropoff
OpenTrons/opentrons-api pull request #13669
Opened 2023-09-27 17:31 UTC by caila-marashaj

2023-09-27 18:17 UTC, ahiuchingau requested changes
MoveManager can take in a list of targets, i think we can make use of that here

2023-09-27 18:17 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/instruments/ot3/pipette_handler.py
> +                    "distance": instrument.pick_up_configurations.prep_move_distance,
Since we have a fixed set of keys, we should make use of dataclass here

2023-09-27 18:17 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/instruments/ot3/pipette_handler.py
> +                {
Same as above

2023-09-27 18:17 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/ot3api.py
> +                    origin={Axis.Q: gear_origin_float}, target_list=[move_target_start]
Instead of using separate move group runners to execute this, why not include both targets to the target_list?

2023-09-28 15:46 UTC, sfoster1 approved these changes
Looks good iif it works, thoguh I'm wondering if maybe we're beyond the point of `plan_check_drop_tip` handling both motor and force drop being helpful

2023-10-03 14:25 UTC, caila-marashaj commented
> Looks good iif it works, thoguh I'm wondering if maybe we're beyond the point of `plan_check_drop_tip` handling both motor and force drop being helpful

I was thinking of doing a little refactoring just for cleanliness in a separate pr. can definitely add this to that

2023-10-12 18:51 UTC, sfoster1 requested changes
I like the impulse to refactor this code, but this has lost a lot of management of motor currents.

For force-pickup, we use a much lower current than normal; we need to set the low current (`uinstrument.pick_up_configurations.current` on the Z axis when pressing into the tip, and the default Z run current when raising out of the tip, because the low current may not be enough to move the Z.

For force-drop, we need to be using a much higher current on the plunger when interacting with the shroud (`instrument.drop_configurations.current`)

2023-10-12 18:51 UTC, sfoster1 commented on shared-data/pipette/definitions/2/general/ninety_six_channel/p1000/3_0.json
> +  "connectTiprackDistanceMM": "7.0",
we should add these to the schema

2023-10-12 18:51 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        async with self._backend.motor_current(
We can't set the current like this, I think (know). We purposefully set the current of the Z much lower than normal when driving into tips to pick them up so we can use the motors as a force clutch. We should _not_ use the same current when we're going back up after the main press.

2023-10-12 18:51 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/pipette_handler.py
>                      ): instrument.plunger_motor_current.run
this current isn't the right one - in pick up tip, for force pickups, it's the current of the _z_ that's important, not the current of the plunger. Note that after this refactor, there's no reference to `instrument.pick_up_configurations.current` outside of `Axis.Q`.

2023-10-12 18:51 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/pipette_handler.py
> +            Axis.of_main_tool_actuator(mount): instrument.plunger_motor_current.run
this current is wrong; when dropping tip, we use a much higher current on the plunger motor than normal because we need to apply enough force to pip the tips off. That's `instrument.drop_configurations.current`.

2023-10-18 18:02 UTC, sfoster1 requested changes
Comments inline. Two big things
- We definitely are not getting the currents correct, still. During a force press pickup, the _z current_ is what defines the tip attach force and what we need to control during the downward stroke. During a force tip drop, the plunger current defines the applied force and what we need to control during the plunger downward stroke
- We're doing this thing where we decide if the pipette is a 96 twice, separately, in ot3api and in the pipette handler. We should do it in only one of those places and I think the right place is the ot3api, by gantry load. Then, let's make the functions in the pipette handler separate - one for 96, one for low throughput. One fewer place to change if we ever need to.

2023-10-18 18:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/pipette_handler.py
> +    shake_off_moves: List[Tuple[top_types.Point, Optional[float]]]  # this is the same
the same as what?

2023-10-18 18:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/pipette_handler.py
> +    z_distance_to_tiprack: Optional[float] = None
can these be moves?

2023-10-18 18:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/pipette_handler.py
> +                            pipette_axis: instrument.pick_up_configurations.current
shouldn't this be for the z axis?

2023-10-18 18:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/pipette_handler.py
> +                        currents={pipette_axis: instrument.plunger_motor_current.run},
shouldn't this be the z axis?

2023-10-18 18:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/pipette_handler.py
> +            tip_motor_moves = self._build_tip_motor_moves(
might be a lot easier if `_build_tip_motor_moves` took a `TipClassHandlingConfiguration` so this could be `self._build_tip_motor_moves(instrument.pick_up_configurations)`

2023-10-18 18:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/pipette_handler.py
> +        if is_96_chan:
nit: better to have this be `if instrument.channels == 96` if this isn't used anywhere else

2023-10-18 18:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/pipette_handler.py
> +                        ): instrument.plunger_motor_current.run,
this needs to be the higher drop-tip current, since it's where we're driving the plunger to pop the tips off

2023-10-18 18:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        if check_current_vol and instrument.current_volume > 0:
Why add this? Won't the current volume always be 0 after dropping a tip?

2023-10-18 18:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +            move_targets = []
`move_targets = [MoveTarget.build(position={Axis.Q: move_segment.distance}, max_speed=move_segment.speed) for move_segment in pipette_spec]` ?

I generally like using list comprehensions to make a transformation like this look like an assignment, rather than looking like mutating something

2023-10-19 15:42 UTC, sfoster1 approved these changes
Okay, I'm liking this a bit more, but I think we need to establish some test criteria. Why don't we say:

- Pick up a tip on a single and multi and check the canbus logs to make sure we're setting the current from config
- Drop a tip on a single and multi and check the canbus logs to make sure we're setting the current from config
- Check that 96 pickup and drop works with the segmented moves

I'm most concerned about LT regressions as you can probably tell.

2023-10-19 15:42 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/pipette_handler.py
> +    def plan_ht_pick_up_tip(self, mount) -> TipActionSpec:
```suggestion
    def plan_ht_pick_up_tip(self, mount: OT3Mount) -> TipActionSpec:
```
? 
heck it might not even need the mount

2023-10-19 15:42 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/pipette_handler.py
> +                        currents=None,
probably wants to set the default run current here

2023-10-19 20:10 UTC, caila-marashaj commented on api/src/opentrons/hardware_control/instruments/ot3/pipette_handler.py
> +                        currents=None,
I'm using the `None` to pass into `backend.motor_current`, which will set all the axes to their default run currents if it gets a `None`

2023-10-20 16:00 UTC, ahiuchingau approved these changes

2023-10-20 17:41 UTC, merged