refactor(api): only restore changed currents
OpenTrons/opentrons-api pull request #13683
Opened 2023-09-28 22:20 UTC by ahiuchingau

# Overview
This PR updates the `ot3controller.restore_current` function so it can optionally take in run currents and hold currents. Instead of unconditionally restoring _all_ current settings for every present axis, now this function can intelligently restore only the ones that were changed.

2023-09-29 13:03 UTC, sfoster1 approved these changes
Looks good with a nit

2023-09-29 13:03 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    async def restore_current(
kind of a nit i guess but really this isn't `restore_current` anymore, can we call it like `motor_current` or something

2023-10-03 18:32 UTC, fsinapi requested changes
I really like this change!!! Some of the hardware-testing scripts just need to be updated to use the new function correctly.

2023-10-03 18:32 UTC, fsinapi commented on hardware-testing/hardware_testing/production_qc/z_stage_qc_ot3.py
> +                async with api._backend.motor_current():
The `set_active_current` call below should be merged into here

2023-10-03 18:32 UTC, fsinapi commented on hardware-testing/hardware_testing/production_qc/ninety_six_assembly_qc_ot3/test_droplets.py
> +    async with api._backend.motor_current():
The `set_active_current` call below should be merged into here

2023-10-03 18:32 UTC, fsinapi commented on hardware-testing/hardware_testing/opentrons_api/helpers_ot3.py
> +        async with api._backend.motor_current():
The `set_active_current` call below should be merged into here

2023-10-03 18:32 UTC, fsinapi commented on hardware-testing/hardware_testing/opentrons_api/helpers_ot3.py
> +        async with api._backend.motor_current():
The `set_active_current` call below should be merged into here

2023-10-03 20:45 UTC, caila-marashaj approved these changes

2023-10-03 21:28 UTC, fsinapi approved these changes
nice

2023-10-03 21:32 UTC, merged