Feature deck def v4
OpenTrons/opentrons-api pull request #13686
Opened 2023-09-29 18:20 UTC by TamarZanzouri

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-09-29 21:03 UTC, b-cooper commented on shared-data/fixture/schemas/1.json
> +      "description": "Real-world fixfure that the definition is modeled from and/or compatible with"
```suggestion
      "description": "Real-world fixture that the definition is modeled from and/or compatible with"
```

2023-10-05 20:11 UTC, sfoster1 requested changes
Couple things about minutiae of slot definitions.

Also, I think that either we should make the inline SVG correct in this PR, or we should make it as empty an element as it can get so it's more obvious we haven't set it up yet.

2023-10-05 20:11 UTC, sfoster1 commented on shared-data/deck/definitions/4/ot3_standard.json
> +          "zDimension": 0
sort of tough to decide, but should the slot addressable area bounding boxes include the clips?

2023-10-05 20:11 UTC, sfoster1 commented on shared-data/deck/schemas/4.json
> +    "cutoutSlot": {
I don't think we want this in here explicitly because these are as much a part of data as anything else. Putting this in the schema _requires_ that every deck definition fit its slot names into this enum. I think it's much better to leave this as a string.

The proper way to type ids of this kind is that the things that refer to them need valid references to something else in the document; I don't think jsonschema can do that, and in the absence of that capability I think we should keep the schema loose.

2023-10-05 20:11 UTC, sfoster1 commented on shared-data/deck/schemas/4.json
> +        "singleStandardSlot",
Same here - I do not think these should be controlled. In general, I think schemas should constrain values only if those values are discriminators in heterogeneous unions.

2023-10-05 20:11 UTC, sfoster1 commented on shared-data/deck/schemas/4.json
> +              "position": {
can we make this `offsetFromCutoutFixture` or something

2023-10-05 20:11 UTC, sfoster1 commented on shared-data/deck/schemas/4.json
> +                    "magneticModuleType",
I think we should take these out (they were also defined like this in v3, and I think they shouldn't have been there either)

2023-10-09 15:02 UTC, SyntaxColoring reviewed
Looks good to me, pending @sfoster1's comments and the `@overload` thing you mentioned in-person. Thank you!

2023-10-09 15:02 UTC, SyntaxColoring commented on shared-data/deck/schemas/4.json
> +        "singleStandardSlot",
This will be moot if this is turned into a plain `string` instead of an `enum`, per @sfoster1's point, but: it looks like `singleStandardSlot` is unused, replaced by `singleLeftSlot`/`singleCenterSlot`/`singleRightSlot`?

2023-10-09 15:02 UTC, SyntaxColoring commented on shared-data/deck/schemas/4.json
> +                    "magneticModuleType",
If we take these out, can we document where to find the valid strings?

2023-10-09 15:02 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/deck/__init__.py
> +
Here's a patch that fixes the `@overload` problems, I think.

https://github.com/Opentrons/opentrons/compare/feature-deck-def-v4...feature-deck-def-v4-fix-overload

If this doesn't work out, happy for it to be worked around with a separate function or something, like you said.

2023-10-09 18:46 UTC, sfoster1 approved these changes
All right, looks great to me! Thanks!

2023-10-09 18:46 UTC, sfoster1 commented on shared-data/deck/definitions/4/ot3_standard.json
> +          "zDimension": 0
decide: no

2023-10-10 14:15 UTC, SyntaxColoring approved these changes
🛹

2023-10-10 17:27 UTC, merged