Tip presence check routine
OpenTrons/opentrons-api pull request #13703
Opened 2023-10-02 22:39 UTC by caila-marashaj

2023-10-03 14:21 UTC, sfoster1 requested changes
I think we need to get the clamp back to fully-clamped after the action.

I'm also a little worried about what happens if we do this when we have a rack of tips clamped in place - does it mess up the seals? Does the sensor work the same?

2023-10-03 14:21 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        except UnmatchedTipPresenceStates:
as it is, this try/except isn't really doing anything, but I think we want it to: specifically, we want to move the tip motors back to their neutral positions if we get either no error, or an `UnamtchedTipPresenceStates` (since that's sort of an "expected" error that doesn't indicate that something larger is wrong). If we get another error, we can just pass it through.

2023-10-03 14:21 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        if high_throughput:
is it safe to do this if we have a rack of tips clamped? will it cause the seal on the tips to get messed up if we drop and come back?

2023-10-05 19:24 UTC, sfoster1 requested changes
Couple little changes

2023-10-05 19:24 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/backends/test_ot3_utils.py
> +    breakpoint()
accidentally checked in?

2023-10-05 19:24 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +            # FIXME: tip presence responses from the 96 channel hardware need to be inverted
can we just fix this, right now, in firmware?

2023-10-05 20:11 UTC, caila-marashaj commented on api/src/opentrons/hardware_control/ot3api.py
> +            # FIXME: tip presence responses from the 96 channel hardware need to be inverted
yeah I can just invert that in firmware

2023-10-06 14:56 UTC, sfoster1 approved these changes
Looks good but let's remove that try/except

2023-10-06 14:56 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        except Exception:
we should remove this try/except entirely, it's not doing anything except adding another layer of indentation

2023-10-06 15:07 UTC, fsinapi requested changes, later dismissed
Coupla small things

2023-10-06 15:07 UTC, fsinapi commented on api/tests/opentrons/hardware_control/backends/test_ot3_utils.py
> +    for block in moves[0].blocks:
Is this change related to the PR?

2023-10-06 15:07 UTC, fsinapi commented on api/src/opentrons/hardware_control/ot3api.py
> +        await self.home_gear_motors()
Assuming that this function is supposed to work on low-throughput pipettes as well, we should only `home_gear_motors()` if `high_throughput == True`

2023-10-06 18:09 UTC, merged