fix(hardware-testing): Flag pipette as not ready to aspirate after pushing out air
OpenTrons/opentrons-api pull request #13728
Opened 2023-10-05 19:15 UTC by andySigler

# Overview

Set `ready_to_aspirate = False` if a push-out volume is used during dispense. The plunger would then be below the `bottom` position, and so would not be ready to aspirate.

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-10-05 19:24 UTC, sfoster1 requested changes
Also we should add a test

2023-10-05 19:24 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +            if push_out or dispense_spec.instr.push_out_volume:
probably better for this to just be this since it's what actually controls things
```suggestion
            if dispense_spec.instr.push_out_volume:
```

2023-10-06 17:30 UTC, andySigler commented on api/src/opentrons/hardware_control/ot3api.py
> +            if push_out or dispense_spec.instr.push_out_volume:
if caller sets `push_out=0` then the pipette is still ready-to-aspirate, so we need to either check this argument or we could specify what push-out volume was used within the `dispense_spec` and check that instead

2023-10-12 15:59 UTC, ryanthecoder commented on api/src/opentrons/hardware_control/ot3api.py
> +            if (push_out is not None and push_out > 0) or plunger_target_pos > bottom:
Can we change this to just the `plunger_target_pos > bottom` ? that should be the only condition we care about if i'm thinking about this right

2023-10-13 00:26 UTC, andySigler commented on api/src/opentrons/hardware_control/ot3api.py
> +            if (push_out is not None and push_out > 0) or plunger_target_pos > bottom:
makes sense to me

2023-10-13 14:19 UTC, ryanthecoder approved these changes

2023-10-18 13:31 UTC, sfoster1 approved these changes
Looks good to me!

2023-10-18 13:53 UTC, merged