feat(server-utils): add logging configuration to server_utils to be used by servers.
OpenTrons/opentrons-api pull request #13787
Opened 2023-10-13 21:29 UTC by vegano1

# Overview

We want to split up the hardware_controller from the opentrons package, we are configuring the logs for each server independently. We would like to have that configuration in a common location, so let's throw it into server-utils and some other useful variables.

Closes: [RET-1381](https://opentrons.atlassian.net/browse/RET-1381)

# Test Plan

- [ ] Make sure buildroot builds succeed with this change
- [ ] Make sure oe-core builds succeed with this change
- [ ] Make sure the OT-2 and the Flex boot and all servers are started correctly
- [ ] Make sure we are correctly logging for each server

# Changelog

- Move common logging config code out of each server and keep it in server-utils
- Import server-utils to update/robot/system/ot3usb servers to configure logging
- Adds pydantic to update-server Pipfile to support ServerSettings

# Review requests
# Risk assessment

2023-10-17 13:19 UTC, fsinapi reviewed
My initial thought is that, if we're just going to have hard-coded configurations in here, there's little benefit over just keeping everything hard-coded in each package. I think we should either 

1. Set up a single, common config that applies to everything (including the full breadth of loggers/handlers)
2. Have a function that can be called with a set of configurable handlers & loggers to be supplied by the caller

...or option 3 is that this isn't a useful refactor because it's a minimal amount of duplicated code to set this up independently in each server. I'll leave that up to your judgement 😄

2023-10-17 13:19 UTC, fsinapi commented on server-utils/server_utils/__init__.py
> +print("Im importing server_utils")
debugging line?

2023-10-17 21:04 UTC, sfoster1 requested changes
Inline comments, and I think I'm on Frank's side that this isn't quite a useful enough refactor yet. Specifically, it's weird to me that we have these fully qualified package names in server utils, you know? The configurations are so incredibly specific to these other servers that it's strange to have them in server-utils which is in theory a common-use library.

The thing is though that if we make this general enough that `server-utils` doesn't contain fully qualified package names (which I think is a good bar for "general enough"), then what _does_ it contain on the logging front? It's already pretty terse.

I like getting `config` out of the opentrons package but as discussed in person I think that's only useful if we can keep `opentrons` from having a dependency on `server_utils`, which I think needs a little more refactoring before it can happen.

2023-10-17 21:04 UTC, sfoster1 commented on server-utils/server_utils/__init__.py
> +print("Im importing server_utils")
debug print

2023-10-17 21:04 UTC, sfoster1 commented on api/src/opentrons/__init__.py
> +    # TODO (ba, 2023-10-12): Remove log init once the opentrons_hardware process is up and running
we could remove it now if we put the logging config for the hardware controller in server utils

2023-10-17 21:04 UTC, sfoster1 commented on system-server/system_server/__main__.py
> +    log.info(f"Starting system server on {args.host}:{args.port}")
this now won't be logged, right? since the logging is set up when we invoke uvicorn now

2023-10-17 21:04 UTC, sfoster1 commented on update-server/Pipfile
> +pydantic = "==1.8.2"
is this necessary? on the flex, that's a full second copy of pydantic and all its transitive deps in `update-server`

2023-10-18 15:30 UTC, closed without merging

2023-10-18 15:33 UTC, vegano1 commented
Agreed,
The only required change to move the logging config will happen once the hardware controller is in its own package.
So for now I think ill skip this refactor.