app(feat): launch drop tip wizard logic
OpenTrons/opentrons-api pull request #13818
Opened 2023-10-20 15:29 UTC by mjhuff

Closes RAUT-795

# Overview

This PR adds logic for wiring up the drop tip modal in additional locations. It also refactors the nice-modal-react context providers to the appropriate app/ODD locations to take advantage of top-level context. It includes some drive by refactoring as well - primarily adding missing tests.

A few notes of interest/controversy:
1) Because the OT-2 provides no way to validate that a tip has been removed, and we probably shouldn't always assume the Flex sensor is accurate for determining whether a tip is attached, the banner/ODD modal logic assumes that once a user begins the drop tip flow that the tip will be removed or the user is no longer interested with tip removal (and therefore the alert should be removed). 
2) If a user has tips on both the left and right pipettes and chooses not to skip the drop tip wizard (clicks dismiss on the dekstop banner or presses skip on the ODD), BUT the user exists a drop tip wizard flow prematurely, the banner/modal popup will still exist for the second pipette. 
3) The one optimization for getPipettesWithTipAttached is if both pipettes are used in a run, check for tip status for both pipettes on the same command loop iteration. 

### Protocol Header Entrypoint 
<img width="922" alt="Screenshot 2023-10-20 at 11 18 29 AM" src="https://github.com/Opentrons/opentrons/assets/64858653/8a532328-535a-4d69-9d8c-1e53092317b2">

### ODD InstrumentDetail Entrypoint
<img width="728" alt="Screenshot 2023-10-20 at 11 18 09 AM" src="https://github.com/Opentrons/opentrons/assets/64858653/b69e6d57-63c7-4080-9da6-2f9691648baf">

### ODD RunSummary Entrypoint

<img width="509" alt="Screenshot 2023-10-20 at 11 17 48 AM" src="https://github.com/Opentrons/opentrons/assets/64858653/fc92d8f4-7705-46a0-b45a-10d3257a5212">

# Test Plan

Protocols That May Be Useful:
[pick_up_tip.py.zip](https://github.com/Opentrons/opentrons/files/13055798/pick_up_tip.py.zip)
[Just Pipettes.py.zip](https://github.com/Opentrons/opentrons/files/13055797/Just.Pipettes.py.zip)

- Place tips on one/both of the pipettes and run the just pipettes protocol. After the run the banner should appear (Desktop) or clicking return to dashboard/run again will open the modal (ODD).
- Dismissing the banner will cause the drop tip modal not to render if it is not clicked in a few seconds. Clicking "skip" on the ODD will cause the drop tip banner on the desktop app to disappear. 
- Run the pick up tip protocol and press the estop some time AFTER the tip has attached. Verify the banner/ODD modal appears. 
- Run the pick up tip protocol and press the estop BEFORE the tip has attached (but before the pickUpTip command has been performed). Verify there is no banner/ODD modal.

# Changelog
- Added ODD overflow menu on the InstrumentDetail page.
- Wired up the drop tip wizard on the Desktop & ODD apps.

# Review requests
Test on a physical robot, please! AppUI is configured for these protocols.

# Risk assessment
low

2023-10-23 19:20 UTC, koji commented on app/src/assets/localization/en/drop_tip_wizard.json
nit
recommend run sort on VSCode.

2023-10-23 19:24 UTC, koji commented on app/src/assets/localization/en/run_details.json
> -  "run": "Run",
Generally this change makes sense but currently we are using sort lines asc on VSCode and it sorts like below

run_failed
run

instead of 

run
run_failed

I think we can solve this after 7.1.0 release.

2023-10-23 19:24 UTC, koji commented on app/src/atoms/MenuList/index.tsx
> +      width="max-content"
thanks!

2023-10-23 19:26 UTC, koji commented on app/src/organisms/Devices/ProtocolRun/ProtocolDropTipBanner.tsx
> +        <StyledText as="p" fontWeight={FONT_WEIGHT_SEMIBOLD}>
we can use `TYPOGRAPHY.fontWeightSemiBold` instead of `FONT_WEIGHT_SEMIBOLD`

```suggestion
        <StyledText as="p" fontWeight={TYPOGRAPHY.fontWeightSemiBold}>
```

2023-10-23 19:31 UTC, koji commented on app/src/organisms/Devices/ProtocolRun/ProtocolDropTipBanner.tsx
> +            fontSize={TYPOGRAPHY.fontSizeP}
Do we need this?
StyledText uses `as="p"`

2023-10-23 19:51 UTC, koji commented on app/src/organisms/DropTipWizard/TipsAttachedModal.tsx
> +import type { PipetteModelSpecs, RobotType } from '@opentrons/shared-data'
nit

```suggestion
import type { PipetteData } from '@opentrons/api-client'
import type { PipetteModelSpecs, RobotType } from '@opentrons/shared-data'
import type { ModalHeaderBaseProps } from '../../molecules/Modal/types'
```

2023-10-23 19:57 UTC, koji commented on app/src/organisms/DropTipWizard/TipsAttachedModal.tsx
> +  robotType: RobotType
Question
Do we need robotType?  From import statements, this modal is for the touchscreen app which means robotType is always "OT-3 Standard".

Will this component be used for OT-2?

2023-10-23 19:59 UTC, koji commented on app/src/organisms/DropTipWizard/TipsAttachedModal.tsx
> +                buttonType="primary"
nit
buttonType can be removed since the default is primary.

```suggestion
                
```

2023-10-23 20:00 UTC, koji commented on app/src/organisms/DropTipWizard/TipsAttachedModal.tsx
> +              onCloseClick?.((pipettesWithTip: any[]) => {
Can we avoid using `any[]`?

2023-10-23 20:02 UTC, koji commented on app/src/organisms/DropTipWizard/__tests__/TipsAttachedModal.test.tsx
> +import { LEFT } from '@opentrons/shared-data'
this line can be right after `renderWithProviders`

2023-10-24 04:09 UTC, koji commented
For a test of time, you may need to call a convert function in test.

2023-10-24 12:56 UTC, mjhuff commented on app/src/assets/localization/en/drop_tip_wizard.json
Discussed w/ Nick. His PR (which will be merged in alongside mine) will fix this!

2023-10-24 12:57 UTC, mjhuff commented on app/src/assets/localization/en/run_details.json
> -  "run": "Run",
Totally agree - IDK why my VSCode sorts opposite yours, but we should enforce some sort of standard.

2023-10-24 13:03 UTC, mjhuff commented on app/src/organisms/DropTipWizard/TipsAttachedModal.tsx
> +  robotType: RobotType
Yep! We do need it for DropTipWizard. It's a bit hard to see, but I spread in the props on L94.

2023-10-24 13:21 UTC, mjhuff commented
> For a test of time, you may need to call a convert function in test.

Thanks for noticing. I think I'll remove the exact time testing, since the clock functionality is tested elsewhere and I'm just testing for the existing of elements on a page 👍

2023-10-24 14:22 UTC, mjhuff commented
Note: The PD test failure appears unrelated to this PR 👍

2023-10-25 16:17 UTC, mjhuff commented
@sanni-t Here are the python-sided changes we discussed in our sync on Monday.

2023-10-25 16:28 UTC, koji commented
> Note: The PD test failure is unrelated to this PR.

Shlok's PR to fix PD and LL is in edge already. I think once this PR takes that, the CI issue will be gone.

2023-10-25 18:28 UTC, b-cooper commented on app/src/pages/OnDeviceDisplay/RunSummary.tsx
> +        ROBOT_MODEL_OT3,
This should really be `FLEX_ROBOT_TYPE` from shared data, that ROBOT_MODEL_OT3 happens to be the same string, but it's a deprecated const

2023-10-25 18:31 UTC, b-cooper approved these changes
Changes look good 🪶

2023-10-25 20:00 UTC, sanni-t requested changes
The robot server change in this PR will block you from creating maintenance runs before a protocol is started. That means no LPC or calibrations during protocol run setup. Added suggestions for fixing this.

2023-10-25 20:00 UTC, sanni-t commented on robot-server/robot_server/maintenance_runs/router/base_router.py
> +    if not protocol_run_is_terminal:
This will change the behavior so that you can only create maintenance runs once a protocol run is completed. You want to also allow starting maintenance runs when a protocol run has been created but not played.

2023-10-25 20:00 UTC, sanni-t commented on api/src/opentrons/protocol_engine/state/commands.py
> +
You can check this same condition with just a `self._state.run_result is not None`

2023-10-25 20:00 UTC, sanni-t commented on robot-server/robot_server/runs/dependencies.py
> +    return protocol_run_state.commands.get_is_terminal()
You can change this to something like:

```
async def get_is_okay_to_create_maintenance_run(
    engine_store: EngineStore = Depends(get_engine_store),
) -> bool:
    """Whether a maintenance run can be created if a protocol run already exists. """
    try:
        protocol_run_state = engine_store.engine.state_view
    except AssertionError:
        return False
    return not protocol_run_state.commands.has_been_played() or protocol_run_state.commands.get_is_terminal()
```

2023-10-25 22:19 UTC, mjhuff commented
@sanni-t I retested with these changes and things seem to be working as expected. No issue with calibration/LPC/maintenance runs now 👍 

@b-cooper Can confirm the useEffect in ProtocolRunHeader isn't firing egregious network requests 👍

2023-10-26 18:45 UTC, sanni-t approved these changes
🙌 🧙‍♂️ Thanks for making the changes!

2023-10-26 19:11 UTC, merged