feat(hardware): read tip update from firmware whenever a notification is received
OpenTrons/opentrons-api pull request #13822
Opened 2023-10-20 19:53 UTC by ahiuchingau

# Overview
FLEX pipettes have tip sensing ability (thanks to tip presence sensors!); it would be nice if we could get real-time status of the attached tip from the pipette while the hardware controller is running.

This PR does it by creating a TipPresenceManager in the hardware controller that monitors tip updates from the pipettes. The tip presence manager is in charge of building a TipDetector dedicated to an attached pipette and pass any tip notification from the CAN bus to any of its listeners. 

The tip presence manager currently serves the two following purposes:
(1) prompting the firmware to confirm tip presence after pick up and drop tip actions
(2) caching the latest tip update from the detectors, and presenting that info to the `/instruments` endpoint

# Changelog
* the `has_tip` property of the OT3 pipette does not in fact reflect whether or not a tip is currently attached, but if a tip length has been added so we're changing the logic there
* removing the `tip_presence_detection_enabled` feature flag and make it the default behavior for all FLEX pipettes 

# What's next
This opens up an opportunity for the protocol engine to listen to the unexpected tip change during a protocol and issue the appropriate proper error/warning to the user.

2023-10-23 16:45 UTC, sfoster1 requested changes
This is awesome. I think there's two bigger changes we should make, and then I have some inline comments.

First, I think the debounce logic is slightly wrong. The thing we want to do is ignore bouncing around within a timeout. When we see the first tip change happen, we start a timer; we keep collecting tip state changes; and the end result is the _last tip state value when the timer expires_, everything _before_ that is ignored. What we have here is that any tip state change is ignored if it changes after the first time.

Consider: the goal here is that if you take your finger and like flick the tip ejector shroud upwards and then it falls down, we don't tell the engine that a tip was removed and replaced within like 800 ms. We'd want to
- see the "tip removed" event and start the timer
- keep capturing events during the timer; the last one will be the "tip added" event as the shroud falls down, maybe bounces a couple times, and then settles
- and so the result, a second later, will be "no change" because the sensor went from present to present.

2. While we don't have to add the engine subscribing to the tip state in this PR, I think we _should_ add the framework to route events up out of the hardware controller - add it to the hardware events type, have `ot3api` add a listener to the tip state detector, pass it through ot3controller, etc

2023-10-23 16:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    async def update_tip_detector(self, mount: OT3Mount, sensor_count: int) -> None:
probably want a way to remove one when a pipette is removed, right?

2023-10-23 16:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/tip_presence_manager.py
> +class TipDetectorNotFoundError(Exception):
make it enumerated probably

2023-10-23 16:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/tip_presence_manager.py
> +class TipDetectorNotFoundError(Exception):
some kidn of itnernal error code

2023-10-23 16:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/tip_presence_manager.py
> +        if not sensor_count > 0:
```suggestion
        if sensor_count <= 0:
```
nit, makes it easier to read for me

2023-10-23 16:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/tip_presence_manager.py
> +TipDetectorByMount = Dict[OT3Mount, Optional[TipDetector]]
we've done this a couple other places and it's been sort of normalized, but for my money 
- if you have a dynamic store of data with a consistent key type and a consistent value type, _but no restriction on what value of key may be present_, that should be a `Dict`
- if you have a store of data with a consistent key type and a consistent value type, and you want to look up keys programmatically with strings, and some keys always need to be there, that should be a `TypedDict` with keys as literals
- If you have a store of data where you don't need to access things programatically, that's a dataclass

So for both `_detectors` and `_last_state`, where there has to be keys for all mounts - though really it's just the pipette mounts - at all times but the value can vary, to me that should be a `TypedDict` with key literals

2023-10-23 16:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/pipette.py
>          self._current_tip_length = 0.0
nit: if we're going to do "has_tip_length" let's make the internal variable an optional rather than checking for value == 0.0

2023-10-23 16:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/pipette_handler.py
> +            result["tip_presence_responses"] = instr.tip_presence_responses
don't love exposing this here - can we avoid it?

2023-10-23 16:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +    async def _high_throughput_tip_action(self) -> AsyncIterator[None]:
```suggestion
    async def _high_throughput_check_tipsself) -> AsyncIterator[None]:
```
maybe? `tip_action` is sort of nonspecific

2023-10-23 16:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        await self.verify_tip_presence(realmount, TipStateType.PRESENT)
Honestly I think we should remove this call and the one in drop tip for low-throughput pipettes, and maybe for high-throughput pipettes, where we can run the commanded action regardless of whether things are present. Let the engine worry about it

2023-10-23 16:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        await self.verify_tip_presence(realmount, TipStateType.ABSENT)
see the note above - I don't think we need to be doing this, since the engine does

2023-10-23 16:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/tip_presence_manager.py
> +    def add_listener(self, listener: TipListener) -> None:
do we call this anywhere?

2023-10-23 16:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/tip_presence_manager.py
> +    def add_listener(self, listener: TipListener) -> None:
also we typically implement these functions like `add_listener()` to return a function instance you can call that will remove the listener:
```
def add_listener(self, listener: TipListener) -> Callable[[],None]:
    self._listeners.append(listener)
    def remove():
        self._listeners.remove(listener)
    return remove
```

2023-10-23 16:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/tip_presence_manager.py
> +    def __init__(self, can_messenger: CanMessenger) -> None:
maybe take an initial set of listeners?

2023-10-23 16:45 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tip_presence/detector.py
> +    def __del__(self) -> None:
I think we probably do not want this to be in a `__del__` magicmethod. The `__del__` magic method is called [only when an object's reference counts hit 0 or it's garbage collected](https://docs.python.org/3/reference/datamodel.html#object.__del__) making it really only useful for cleaning up resources the interpreter doesn't know about. 

Trying to use `__del__` to remove _other python objects_ will probably just result in the object never being cleaned up. The tasks in `self._tasks` hold references to the object because they're bound methods that hold references to `self`. Unless the objects in tasks are explicitly destroyed, those references will remain live.

So I'm pretty sure that `__del__` will never be called as-implemented, because even if this object is popped out of the `OT3Controller` and gets decref'd there, the tasks will still hold refs, and the object won't be gc'd.

I think the right thing to do is have a `def cleanup():` method that `OT3Controller` calls explicitly when we remove detectors, which cancels the tasks, which removes the references from the tasks, which will result (implicitly) in the object getting gc'd.

2023-10-23 16:45 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tip_presence/detector.py
> +    async def _broadcast(
I don't love `_broadcast` as a name because broadcast is also a thing you do to can messages, I had to read this a couple times before I realized it was "broadcast to subscribers above me". can we call this like `_update_subscribers()` or something

2023-10-23 16:45 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tip_presence/detector.py
> +    def remove_subscriber(self, subscriber: TipChangeListener) -> None:
can we implement this as a function object returned from `add_subscriber()`

2023-10-23 16:45 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tip_presence/detector.py
> +            asyncio.wait_for(fut, timeout=1.0)
the `1.0` probably wants to be an instance variable called like `debounce_time`

2023-10-23 16:45 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tip_presence/detector.py
> +            # this tip change is rejected, end the task here
it's less that we want to _reject_ the change, and more that we want the final result to be _the last thing we get_ during the debounce time. The debounce can never really end early.

2023-10-23 18:43 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    async def update_tip_detector(self, mount: OT3Mount, sensor_count: int) -> None:
When it pipette is removed, we'll pass sensor_count as 0, which then removes the attached detector

2023-10-23 18:44 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/backends/tip_presence_manager.py
> +TipDetectorByMount = Dict[OT3Mount, Optional[TipDetector]]
Yea that makes sense

2023-10-23 18:46 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/backends/tip_presence_manager.py
> +    def add_listener(self, listener: TipListener) -> None:
Not currently being called, but i imagine the protocol engine can make use of this to listen to the tip change event

2023-11-01 21:31 UTC, sfoster1 approved these changes
Looks really good to me!

2023-11-01 22:20 UTC, merged