feat(api): Add protocol api support for partial tip configurations
OpenTrons/opentrons-api pull request #13838
Opened 2023-10-24 23:32 UTC by Laura-Danielle

# Overview

This pull request adds support for partial tip configuration in the python protocol api. It handles and closes three separate tickets (RSS-302, RSS-354, RSS-355). After this work is complete, a user should be able to configure their pipette in a partial tip mode. **The TODO list needs to be addressed before this PR can be tested, but the general structure is ready for review.**

# TODO
- [ ]  Finish cleaning up/adding tests
- [ ] Add better handling around column/row use-cases in choosing the ending pipette
- [ ] Expose `NozzleMap` better in the hardware API

# Test Plan

It's another big 'un but we can strategize and choose to only test the MVP use-cases for single tip pick up and full column pick up. When this PR is finished, it should be able to

- [ ] Perform single tip pick up on 8 channel using 'A1'
- [ ] Perform single tip pick up on 8 channel using 'H1'
- [ ] Perform column pick up on 96 channel using 'A1'
- [ ] Perform column pick up on 96 channel using 'A12' (or 'H12'?)
- [ ] Perform single tip pick up on 96 channel using 'A1'
- [ ] Perform single tip pick up on 96 channel using 'H12'

All of the above configurations should also be run in a small protocol re-verify everything is still moving to the right place.
We should also test the 8 channel on the OT-2.

# Changelog
- Add a new protocol engine command to configure the pipette nozzle layout
- Add a new state field which saves the current nozzle map configuration by pipette id
- Add a new protocol api function which takes in dataclasses described in `_nozzle_map.py` to configure a nozzle state

# Review requests

Originally wanted to separate out the commits better, but it ended up being kind of a mess. Devs please review all. You can split it up into `protocol_engine` files and `protocol_api` files to more easily review. 

@ecormany you only need to review `instrument_context.py` and the docstrings there. I am definitely sure there are a bunch of edits we'll need to make. Ping me if you have questions.

# Risk assessment

Low. Adding a new feature (yay).

2023-10-25 15:00 UTC, sfoster1 requested changes
I really think we should change the protocol API interface, but the big thing for me is that we gotta think about where those `NozzleMap` and `NozzleConfigurationType` types live if they're going to be part of the hardware controller's external interface. They shouldn't be defined so deep in the tree, they should be at the top level. That's true just for good practice reasons, but it's also true because we want to move a lot of hardware controller to a different package that the api can run without, so we'll need it to be in a typing stub kind of place, and we should put it there now. Even just `hardware_control.types` would be a good place.

2023-10-25 15:00 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +        self, requested_nozzle_layout: Optional[NozzleLayoutBase]
I think that using a dataclass like this is kind of a lot for our intended users. I think using keywords is a lot better, something like
```
def configure_nozzle_layout(self, style='column'|'row'|'quadrant'|'full', starting_nozzle: str)
```

is a lot easier for a user to understand rather tha having to build an intermediate object. These aren't programmers.

We could make some of those magic strings imported constants like `OFF_DECK` if we wanted, I guess, but I think even that's pushing it.

2023-10-25 15:00 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +        if self._core.has_tip():
Organizationally I'm pretty sure this stuff should be in the engine if it's this important to check. I don't think we can enforce it with schemas or typechecking so the engine will have to make sure json-formatted protocols get it right also

2023-10-25 15:00 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +        if self._core.has_tip():
and by "this stuff" i mean
- checking if we already have a tip, definitely something the engine has to do
- checking that we're only requesting columns on 8s and 96s
- checking that we're only requesting quadrants or rows on 96s

2023-10-25 15:00 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/configure_nozzle_layout.py
> +
like, here is where we should do the validation probably

2023-10-25 15:00 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/configure_nozzle_layout.py
> +            *params.configuration_params,
let's do kwarg expansion with `**` if possible IMO, varargs expansion with * can lead to surprises if things change

2023-10-25 15:00 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/configuring_common.py
> +from opentrons.hardware_control.instruments.nozzle_manager import (
If `nozzle_manager` is going to be an element of hardware control's upward interface rather than just an implementation detail, it needs to live somewhere a lot less deep in the tree.

2023-10-25 15:35 UTC, ecormany commented on api/src/opentrons/protocol_api/instrument_context.py
> +        self, requested_nozzle_layout: Optional[NozzleLayoutBase]
I agree, it's very easy to document "This parameter is a string. There are four good ones. If you pass a different string, the API raises an error."

Also, if we can be judicious in the use of the word `nozzle` it will make protocol code much more readable. I ceased to perceive it as an English word by the time I finished reading this line 😅 
```
instr.configure_nozzle_layout(SingleNozzleLayout(primary_nozzle="A1")
```

2023-10-25 17:14 UTC, sanni-t commented on api/src/opentrons/protocol_api/instrument_context.py
> +        self, requested_nozzle_layout: Optional[NozzleLayoutBase]
Ya I agree with @sfoster1 's suggestion. I do prefer imported constants like `OFF_DECK`, rather than magic strings as a developer, but I can understand the pains that could cause for a protocol writer so fully magical strings are fine too.

2023-10-25 17:40 UTC, sanni-t commented on api/src/opentrons/protocol_api/instrument_context.py
> +        self, requested_nozzle_layout: Optional[NozzleLayoutBase]
Also, imported constants allow us to selectively provide public interface to the configurations so that in 7.1.0, we can only provide interface for 'column'. But internally we can still use the api for row/ single tip etc by using private accessors.

2023-10-25 22:18 UTC, sanni-t commented on api/src/opentrons/protocol_engine/commands/configure_nozzle_layout.py
> +            pipette_id=params.pipetteId,
I don't think pipette_id is needed in the result

2023-10-26 20:50 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/commands/configure_nozzle_layout.py
> +            pipette_id=params.pipetteId,
We need it to save the layout so that it is keyed by pipette id and so that we can look it up later.

2023-11-01 20:54 UTC, sanni-t commented on api/src/opentrons/protocol_engine/state/pipettes.py
> +                private_result.pipette_id
You can use `command.params.pipetteId` to get the pipette ID for this command. So you won't need to include `pipettte_id` in the results

2023-11-01 21:20 UTC, CaseyBatten approved these changes
Ran this on RSS flex with most recent changes and was able to successfully do partial tip pickup, perform aspirations and dispenses, drop tips, reconfigure for whole 96 channel pickup and repeat.
**However important note:**
Under the shared-data pipette json definitions for the 96 channel, the "presses" parameter under the "pickUpTipConfigurations" has to be changed from a 0.0 to a 1.0 in order to successfully pick up the tips, otherwise the 96-channel would not make contact with the tips.

2023-11-02 14:08 UTC, sfoster1 approved these changes
Sure, sounds good to merge I guess. We really need to fix the gcode tests.

2023-11-02 14:13 UTC, merged

2023-11-02 14:23 UTC, jwwojak reviewed
@Laura-Danielle   Added a small suggestion for your consideration. Don't let me be a blocker to moving forward. We can always edit docstrings at a later date.

2023-11-02 14:23 UTC, jwwojak commented on api/src/opentrons/protocol_api/instrument_context.py
> +        robot moves in the set nozzle layout.
Here's a suggestion for the start of the description:

> Configure a pipette to pick up less than the tip's maximum rated capacity. The pipette will continue to aspirate in this reduced capacity until ``configure_nozzle_layout`` is called again with no arguments.

I don't know enough about what this method does to understand part of the last sentence in _italics:_

> All subsequent pipetting calls will execute with the new nozzle layout _meaning that the pipette will perform robot moves in the set nozzle layout_.

Just a reminder, even though this is a python file with a .py file extension, our docs and docstrings are rendered by Sphinx. This means to get `code` type font, you need to put two single quotes `` around the code snippet. For example:

> Certain pipettes are restricted to a subset of ``` ``NozzleLayout`` ``` types.