refactor(api, robot-server, shared-data): replace v3 deck definition with v4 in protocol api and engine
OpenTrons/opentrons-api pull request #13854
Opened 2023-10-26 19:32 UTC by jbleon95

# Overview

This PR switches the majority of references of `DeckDefinitionV3` to `DeckDefinitionV4`, besides a few legacy places in the code and tests. Additionally, the old fixed trash definitions were re-added to the new deck definition under a new name to reflect that it's a legacy feature. This has been hooked up to protocol engine to only load them if a flag is set in the `create_protocol_engine` function, with a helper `should_load_fixed_trash` function used to determine if it should. The criteria for that is being associated with a Python protocol of API level 2.15 and below, and a JSON protocol with schema version 7 and below.

A new basic `DeckConfigurationProvider` class was also added to protocol engine, with some first starts at some functionality to read in a deck configuration and provide the allowed addressable areas.

Some temporary workaround code has been used to transform the data in the new deck definition to `SlotDefV3` which mirrors the old `orderedSlots` data. The same has been used in the `Deck` class, which will need further refactor or replacement to work with the new deck configuration paradigm where slots are not guaranteed.

# Test Plan

Running this branch on the app and on the robot for basic sanity tests of not breaking anything. Unit tests and integration tests should cover basic functional equivalence throughout the stack.

# Changelog

- Switched most references of `DeckDefinitionV3` to `DeckDefinitionV4`
- Added a `DeckConfigurationProvider` class to protocol engine that uses the new deck definition
- Added in some temporary shim code to provide slot data and definitions using the new definition
- Put fixed trash data back into deck definition under the renamed property `legacyFixtures`
- ProtocolEngine will no longer automatically load fixed trash unless a flag is set in `create_protocol_engine`
- Added helper function `should_load_fixed_trash` which if associated with a protocol, will set the above flag to True if the API level is 2.15 and below, or schema version 7 and below

# Review requests

Does the logic and assumptions with legacy fixed trash loading make sense, are we okay with some of the temporary code added, and does the shape of `DeckConfigurationProvider` mesh with our expectations.

# Risk assessment

Medium.

2023-10-27 13:43 UTC, sfoster1 reviewed
Looking really good, just letting you know json protocols have a deck id entry

2023-10-27 13:43 UTC, sfoster1 commented on api/src/opentrons/protocols/api_support/deck_type.py
> +# TODO(jbl 2023-10-26) potentially replace using schema version in JSON protocols with another/new field
json protocols actually have a [`deckId` field in the robot-identification section](https://github.com/Opentrons/opentrons/blob/086b9c7eb144f643553bdd81109a558bec16e154/shared-data/protocol/schemas/7.json#L217-L221) that we can use for exactly this (and we'll preserve it in jp8 #13848 )

2023-10-27 15:54 UTC, jbleon95 commented on api/src/opentrons/protocols/api_support/deck_type.py
> +# TODO(jbl 2023-10-26) potentially replace using schema version in JSON protocols with another/new field
The current `deckId` field does not have a deck version property. As we discussed, that can be added to v8 and this logic can be updated then, and a relevant TODO comment has been added.

2023-10-27 20:51 UTC, SyntaxColoring reviewed
This great. Thanks for slogging through this. I think this takes care of one of the major scary parts of this release.

My comments so far are mostly minor:

2023-10-27 20:51 UTC, SyntaxColoring commented on api/src/opentrons/execute.py
> +            load_fixed_trash=api_version <= LOAD_FIXED_TRASH_GATE_VERSION_PYTHON,
Let's move this `<=` check to be defined in the same place as your `should_load_fixed_trash()` function. You could either add a separate function that takes an `APIVersion` instead of a `ProtocolSource`, or you could have that one function accept a `Union`.

2023-10-27 20:51 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/deck/__init__.py
> +DEFAULT_LEGACY_DECK_DEFINITION_VERSION: Final = 3
I think we should keep `DEFAULT_LEGACY_DECK_DEFINITION_VERSION` as a constant in `opentrons.protocol_api.core.legacy`.

Just for separation-of-concerns reasons, basically. "Legacy" here means "JSONv≤5 and PAPIv≤2.13," which are higher-level concepts that deck definitions are unaware of.

And now that I'm thinking about it, `DEFAULT_DECK_DEFINITION_VERSION` should probably be spelled `LATEST_DECK_DEFINITION_VERSION`. Otherwise, it's like, for whom is this the correct default? But that's a separate thing.

2023-10-27 20:51 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/legacy/legacy_protocol_core.py
> +        assert False, "get_deck_definition only supported on engine core"
```suggestion
        assert False, "get_slot_definition only supported on engine core"
```

2023-10-27 20:51 UTC, SyntaxColoring commented on api/src/opentrons/protocols/api_support/deck_type.py
> +    # TODO(jbl 2023-10-27), when schema v8 is out, use a new deck version field to support fixed trash protocols
Hmm, I'm not sure about this. Let me think things through and I'll open a thread in Slack.

2023-10-27 20:51 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/resources/deck_data_provider.py
> +        for fixture in deck_definition["locations"]["legacyFixtures"]:
Good call renaming this key to anything but `fixtures`, lol.

2023-10-27 20:51 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/resources/deck_configuration_provider.py
> +    # TODO maybe make the key a DeckSlot enum?
Nah, I think we should be careful to draw a distinction between deck slots and cutouts. They're named identically ("A3", "C2", ...), but they're different namespaces.

Staging area slots like C4 will *potentially* be in the `DeckSlotName` enum, and if they are, those values certainly won't make sense as keys for this dict.

2023-10-27 20:51 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/resources/deck_configuration_provider.py
> +    slot_location: DeckSlotName
Is this the slot location that this cutout fixture is providing, or the cutout that it's mounted onto? If it's the latter, see my other comment about drawing a distinction between `DeckSlotName`s and cutout names.

2023-10-27 20:51 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/resources/deck_configuration_provider.py
> +        # TODO need to decide whether an invalid combo should raise an error or just return empty list
Raise an error, in my opinion. "You've placed a fixture here and the fixture has provided nothing" seems semantically distinct from "you cannot place that fixture there."

But the way we expect this to be used, I think we can probably get it to work either way, so it's a matter of style.

2023-10-27 20:51 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/resources/deck_configuration_provider.py
> +    ) -> List[str]:
Also purely a matter of style, but I would consider having all of this stuff operate on `Set` inputs and outputs instead of `List`. There isn't an order to a deck configuration, and a deck configuration never has duplicate elements.

2023-10-27 20:51 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/labware.py
> +        if slot.id == "12":
Hmm, what's the weirdness that this hard-coding is working around?

2023-10-27 20:51 UTC, SyntaxColoring commented on api/src/opentrons/simulate.py
> +            load_fixed_trash=api_version <= LOAD_FIXED_TRASH_GATE_VERSION_PYTHON,
Ditto my comment in `execute.py`.

2023-10-30 14:50 UTC, jbleon95 commented on api/src/opentrons/protocol_engine/state/labware.py
> +        if slot.id == "12":
A combination of two things. One is that there is no addressable area named `12` for the new OT2 deck definitions, only `fixedTrash`, reflecting that there is no actual slot 12. The other related thing is that `fixedTrash` bounding box now reflects the dimension of the trash, not the generic ANSI slot dimensions. To preserve existing behavior, I added this hard-coding. When we fully move to new slot and deck logic, this can all go away.

2023-10-30 15:51 UTC, SyntaxColoring commented on shared-data/deck/definitions/4/ot2_standard.json
> +      }
For OT-2s, how does this interact with the "new" `fixedTrash` fixture in the `fixtures` key?

2023-10-30 15:51 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/runs/test_run_queued_protocol_commands.tavern.yaml
> +          labware: []
Hmm. For existing protocols, I don't think we want this change.

These existing protocols are going to continue interacting with the fixed trash as a labware, not a fixture. They have `dropTip` commands that say `labwareId: "fixedTrash"`, for example. So it's correct for this field to say that there is a `"fixedTrash"` labware loaded in the run and referenceable by its commands.

If anything, I think we want to move in the opposite direction. These protocols have had `"fixedTrash"` entries in the `labware` list, but no corresponding `loadLabware` commands. To be internally consistent, they should have corresponding `loadLabware` commands. RSS-250

@sanni-t Does this match your expectations?

2023-10-30 15:51 UTC, SyntaxColoring commented on api/tests/opentrons/conftest.py
> +        load_fixed_trash=True,  # TODO change how this works, make a new one?
Yeah...I suspect things would get easier if, instead of a global `ctx` fixture that has to get configured through sub-fixtures, we just gave tests a helper function to let them directly construct the kind of `ProtocolContext` that they actually need.

Hard-coding `load_fixed_trash=True` seems fine for now, until something needs a setup where it's `False`. And then we'll have to figure it out there.

2023-10-30 19:22 UTC, jbleon95 commented on shared-data/deck/definitions/4/ot2_standard.json
> +      }
The `legacyFixtures` fixed trash will only be loaded for protocols 2.15 and below. For anything higher, we will use the new fixed trash addressable area in code. Even though OT-2 will have only one valid deck configuration (at least for this first iteration of deck config), it'll use the same addressable area/cutout fixture system as Flex for code simplicity.

2023-10-30 19:23 UTC, jbleon95 commented on robot-server/tests/integration/http_api/runs/test_run_queued_protocol_commands.tavern.yaml
> +          labware: []
This specific test has an empty run created, which is one of the cases where we shouldn't be automatically loading fixed trash. When a run is created with a protocol and that is below schema v8 or API level 2.16, fixed trash will be loaded automatically as a labware like it used to be.

2023-10-31 14:19 UTC, sfoster1 requested changes
Couple little things about changes to the python protocol API.

Also, how downgrade-safe are stored runs and analyses with this change?

2023-10-31 14:19 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +    def trash_container(self) -> Optional[labware.Labware]:
These are API changes, and I don't think we should make them. Instead, I think we should have this raise `NoTrashDefinedError` if there is no trash defined and keep the return type not optional. This should result in no change in behavior in API versions too low to alter the trash, which is what we want, and if we want to provide a way for someone to get the trash if present and None if not we should add a new call with an appropriate added-in version.

2023-10-31 14:19 UTC, sfoster1 commented on api/src/opentrons/protocol_api/protocol_context.py
> +    def fixed_trash(self) -> Optional[Labware]:
see the note on `InstrumentContext.trash_container`

2023-10-31 14:19 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +    def trash_container(self, trash: Optional[labware.Labware]) -> None:
This is an API change also. It's probably fine because it's more permissive rather than less, but it probably should raise an exception if the api version is below that version in which we added the possibility for this to be none. I think it's probably also a fine idea to not make this change, since I don't quite get why someone would want to explicitly remove a trash from a pipette, or have a different API for that.

2023-10-31 14:19 UTC, sfoster1 commented on api/src/opentrons/protocols/api_support/deck_type.py
> +class NoTrashDefinedError(Exception):
make this an enumerated error

2023-10-31 19:21 UTC, sfoster1 approved these changes
Looks good to me!

2023-10-31 20:27 UTC, SyntaxColoring approved these changes
yea boiii

2023-10-31 20:29 UTC, SyntaxColoring commented
> Also, how downgrade-safe are stored runs and analyses with this change?

There's always going to be a hazard with RSS-98, but if we had problems in this particular PR, I'm like 95% sure our integration persistence tests would detect them.

2023-10-31 20:29 UTC, merged