feat(hardware-testing): Autofind hw testing devices
OpenTrons/opentrons-api pull request #13975
Opened 2023-11-13 21:52 UTC by ryanthecoder

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-11-14 11:36 UTC, andySigler requested changes

2023-11-14 11:36 UTC, andySigler commented on hardware-testing/hardware_testing/drivers/pressure_fixture.py
> +def connect_to_fixture(
if something unexpected happened, raise an error, don't pass

2023-11-14 11:36 UTC, andySigler commented on hardware-testing/hardware_testing/drivers/asair_sensor.py
> +def BuildAsairSensor(simulate: bool, autosearch: bool = True) -> AsairSensorBase:
if something unexpected happened, raise an error, don't pass

2023-11-14 14:09 UTC, sfoster1 requested changes
This doesn't look like the right approach. It looks like what you're trying to do is
for each sensor,
- iterate through comports
- try to talk to that sensor
- if it doesn't respond right, it's not that sensor

But what if some sensor has coincidentally the same feedback? What if there's a different kind of error than "didn't respond right?"

If these sensors are running their own usb interfaces, we should filter on their vid/pid. If they're not, if all they have is identical-looking serial connections and you cannot tell from the host side which is which, I guess this is ok but I'd be much more strongly looking at instead having a guided flow where you start with everything disconnected and connect them one by one or something.

2023-11-14 15:46 UTC, ryanthecoder commented
The issue with using VID/PID is that these devices use serial adapters, and the adapters are the VID/PID that show up. The factory/Dumbo do not use consistent adapters either, so they aren't consistent and/or multiple devices show up as the same vid/pid.
There is currently a flow where the operator gets a list of the connected devices on the terminal and just has to remember which one is which and they absolutely hate this and if they select the wrong one it causes the script to fail and they need to restart the process.

We can't have them connect/disconnect because in the gravimetric/photometric setups they cannot reach the USB ports when the enclosure is over the robot.

I went through the datasheets for the sensors to ensure that these discovery messages won't interfere with each other. I tested this code on a bot that had all of them connected and tried connected to them in several orders to ensure that they don't block up or anything. Not Ideal but kind of the only option.

2023-11-14 19:12 UTC, sfoster1 approved these changes
ok, looks good if we raise an error when we don't find anything

2023-11-15 16:39 UTC, andySigler approved these changes

2023-11-15 18:46 UTC, merged