ci(app): deploy app artifacts to build number prefixed folder
OpenTrons/opentrons-api pull request #13970
Opened 2023-11-13 20:13 UTC by shlokamin

# Overview

**DO NOT MERGE UNTIL AFTER 7.1 IS RELEASED**

This PR deploys app builds to a folder prefixed by build number. This is so we don't overwrite historical build artifacts so we can route electron updater to previous non revoked builds if the latest build has been revoked.

Related to https://github.com/Opentrons/robot-stack-infra/pull/34
 
# Changelog

- Deploy app artifacts to build number prefixed folder 

# Review requests
This one is hard to test without pushing actual internal release/release tags, we'll have to battle test this during the next alpha process after 7.1 gets released to production

# Risk assessment

High, this touches critical release artifact infrastructure

2023-11-13 20:14 UTC, shlokamin commented on .github/workflows/app-test-build-deploy.yaml
> +             echo "folder=${{env._APP_DEPLOY_FOLDER_OT3}}" >> $GITHUB_OUTPUT
i think this was straight up just wrong before and we never noticed because we were using top level env vars to deploy below.

2023-11-14 14:45 UTC, sfoster1 commented on .github/workflows/app-test-build-deploy.yaml
> +             echo "folder=${{env._APP_DEPLOY_FOLDER_OT3}}" >> $GITHUB_OUTPUT
yup https://github.com/Opentrons/opentrons/pull/13966

2023-11-14 14:53 UTC, sfoster1 requested changes
inline notes

2023-11-14 14:53 UTC, sfoster1 commented on .github/workflows/app-test-build-deploy.yaml
> +          OT_APP_DEPLOY_FOLDER: ${{ steps.project.outputs.folder }}/${{OT_BUILD}}
I don't think this is right because there's two places that need the `OT_BUILD` to not be included:
1. Below (see comment) we upload `releases.json` to `OT_APP_DEPLOY_FOLDER`, and `releases.json` needs to be in `/app` not `/app/$OT_BUILD`
2. this environment variable configures the electron-updater's target URL, and we want electron-updater to continue to look at `/app/`

2023-11-14 14:53 UTC, sfoster1 commented on .github/workflows/app-test-build-deploy.yaml
> +        if: contains(fromJSON(needs.determine-build-type.outputs.variants), 'release')
this definitely is wrong - `internal-release` contains `release` so it will fire on both. I think this won't do anything though because [the code above](https://github.com/Opentrons/opentrons/pull/13970/files#diff-61f587522c94a184b8acd038347c1bec0809206cdab7756d0d6655329b36ce7aR326-R333) creates one subdir for release artifacts and one subdir for internal-release artifacts and sorts them, so `to_upload_release/` would be empty if this was an internal release (this is also why these steps were not `if`-gated before)

2023-11-14 14:53 UTC, sfoster1 commented on .github/workflows/app-test-build-deploy.yaml
> +          aws --profile=deploy s3 cp s3://${{ env._APP_DEPLOY_BUCKET_OT3 }}/${{ env.OT_APP_DEPLOY_FOLDER }}/releases.json ./to_upload_internal-release/releases.json
`releases.json` still wants to stay in `builds.opentrons.com/app/`, not `/app/$BUILDNUMBER` - this is one of the reasons I don't think we can just append the build id to the environment variable above

2023-11-14 16:10 UTC, shlokamin commented on .github/workflows/app-test-build-deploy.yaml
> +        if: contains(fromJSON(needs.determine-build-type.outputs.variants), 'release')
lol yes that if statement is useless, good catch. i still think its worth correcting the if statement and including it though, even though one of the subdirs would be empty i think it makes things easier to follow

2023-11-14 16:11 UTC, shlokamin commented on .github/workflows/app-test-build-deploy.yaml
> +          aws --profile=deploy s3 cp s3://${{ env._APP_DEPLOY_BUCKET_OT3 }}/${{ env.OT_APP_DEPLOY_FOLDER }}/releases.json ./to_upload_internal-release/releases.json
beep boop beep yes releases.json needs to be at the top level. ill remove the build number from the env variable and only use it for app artifact deploys

2023-11-14 16:25 UTC, shlokamin commented on .github/workflows/app-test-build-deploy.yaml
> +          OT_APP_DEPLOY_FOLDER: ${{ steps.project.outputs.folder }}/${{OT_BUILD}}
oopsy didnt realize that env var is used by the app shell and app shell odd, thanks!

2025-01-22 16:27 UTC, shlokamin commented
oops i let this get very stale, going to close this for now. we can reopen later if we want to pursue this

2025-01-22 16:27 UTC, closed without merging