feat(api): add wastechute trashbin support
OpenTrons/opentrons-api pull request #14060
Opened 2023-11-29 22:55 UTC by ncdiehl11

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2023-11-30 18:38 UTC, ecormany reviewed
Some docstring comments.

I think the spot that will need the most editing/explanation is the new behavior of `trash_container`, how it's determined, and whether its return value could be a breaking change when updating `apiLevel` on existing protocols.

2023-11-30 18:38 UTC, ecormany commented on api/src/opentrons/protocol_api/instrument_context.py
> +        """The trash container(s) associated with this pipette.
```suggestion
        """The trash containers associated with this pipette.
```
Always favor the plain plural over `(s)`.

If we want to be even more explicit about this object, and further moot the plural issue: `The list of any trash containers...`

2023-11-30 18:38 UTC, ecormany commented on api/src/opentrons/protocol_api/instrument_context.py
> +        core's set of disposal locations for the first valid location if it exists.
If at all possible, we should avoid mentioning the API core at all in docs. Users shouldn't really have to worry about how we've implemented the API.

As for the new behavior, how does the search proceed? Does it find all trash containers? This description makes it sound like it stops after it finds one. But what's the slot order, and does it differ between OT-2 and Flex?

Finally, we decided to list Flex first in docs whenever applicable, so I'd go back to that order in the first sentence.

2023-11-30 18:38 UTC, ecormany commented on api/src/opentrons/protocol_api/protocol_context.py
> +    # TODO: Confirm official naming of "trash bin".
Confirming: it is _trash bin_.

2023-11-30 18:38 UTC, ecormany commented on api/src/opentrons/protocol_api/validation.py
> +            f'Valid slots: {",".join(valid_trash_bin_slots)}')
Instead of listing these, sometimes we say "The trash bin can go in any slot in column 1 or 3."

2023-11-30 19:10 UTC, ncdiehl11 commented on api/src/opentrons/protocol_api/instrument_context.py
> +        core's set of disposal locations for the first valid location if it exists.
I think it's a good call to avoid mentioning the core. 

As far as hierarchy, we have decided for the time being on accessing the first _loaded_ disposal location (trash bin or waste chute), regardless of slot position. If a user implicitly calls `drop_tip` on an OT-2 OR on a Flex running API version < 2.16, we auto drop in the presumed fixed trash.

I'll fix the order of Flex vs OT-2!

2023-11-30 20:13 UTC, ecormany commented on api/src/opentrons/protocol_api/instrument_context.py
> +            Adds the support for TrashBin and WasteChute objects.
Great! This suggestion is mostly formatting cleanup. (RST double backticks, sigh…) Also clarifying that it doesn't return anything because it's a property, not a method.

```suggestion
        On a Flex running a protocol with API version 2.16 or higher, ``trash_container`` is
        the first ``TrashBin`` or ``WasteChute`` object loaded in the protocol.
        On a Flex running a protocol with API version 2.15, ``trash_container`` is
        a single-well fixed trash labware in slot D3.
        On a an OT-2, ``trash_container`` is always a single-well fixed trash labware
        in slot 12.

        .. versionchanged:: 2.16
            Added support for ``TrashBin`` and ``WasteChute`` objects.
```

2023-11-30 20:17 UTC, ecormany commented on api/src/opentrons/protocol_api/instrument_context.py
> +            - As a :py:class:`.TrashBin`. This uses a default location relative to the
Will we be making these classes public? If not, let's use descriptive terms instead of a cross-reference. And I think we can drop the examples:
`- As a trash bin or waste chute object. This uses a default location relative to the object.`

And add the same ``..versionchanged`` statement from `trash_container`

2023-11-30 21:57 UTC, ncdiehl11 commented on api/src/opentrons/protocol_api/instrument_context.py
> +            - As a :py:class:`.TrashBin`. This uses a default location relative to the
To my knowledge, both `TrashBin` and `WasteChute` will be private classes (cc: @SyntaxColoring). I'll make this change.

2023-12-01 17:39 UTC, SyntaxColoring reviewed
This is coming along great. Thank you for your help!

Various comments here and there. I know this is still a draft so you might already be addressing some of these.

2023-12-01 17:39 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/instrument.py
>          # this?
[We can delete this `# TODO`](https://opentrons.slack.com/archives/CSPMY9048/p1701197302581729?thread_ts=1701194571.926949&cid=CSPMY9048) while we're here.

```suggestion
```

2023-12-01 17:39 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +
```suggestion
```

Your call, but I think it's okay to leave this note out because we're in `InstrumentContext`, which isn't expected to accommodate the gripper in general. (PAPI's `InstrumentContext` is just for pipettes, despite the gripper also being called an "instrument" elsewhere in our product.)

2023-12-01 17:39 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        }
Let's deduplicate this with `ensure_trash_bin_location()` to avoid the hazard of a `KeyError` if the sets of allowed locations ever get out of sync with each other.

`ensure_trash_bin_location()` would either:

* Raise, if the location is invalid.
* Return a string like `movableTrashA1` if the location is valid. The returned string would correspond to the input location.

Then I guess `load_trash_bin()` would store the returned string in the new `TrashBin()` object. By the time we reach here, that lets this method simply do `disposal_location._addressable_area_name` instead of having to do its own mapping.

2023-12-01 17:39 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +                'offset': AddressableOffsetVector(64.0, 21.91, 144.0)
Let's delete the `offset` keys from `map_waste_chute_addressable_areas`. These numbers (which I think you got from [here](https://github.com/Opentrons/opentrons/blob/b540785a43f7c1ed4a8e3ea67c9852e4645d29c9/shared-data/deck/definitions/4/ot3_standard.json#L371)) are already known to Protocol Engine and built in to the `moveToAddressableArea` command.

2023-12-01 17:39 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +            slot_name = DeckSlotName.SLOT_D3
This `slot_name` variable looks unused.

2023-12-01 17:39 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +            miminum_z_height = _waste_chute_dimensions.ENVELOPE_HEIGHT + 5.0
Let's delete this `minimum_z_height` override now.

From the comment in the old code, this override *reduced* the margin by which we overfly obstacles on the deck. But:

* That was only necessary because of inconvenient hardware dimensions, which we are changing (RSS-394).
* According to [this description](https://github.com/Opentrons/opentrons/blob/b540785a43f7c1ed4a8e3ea67c9852e4645d29c9/api/src/opentrons/protocol_engine/commands/pipetting_common.py#L56-L63) of Protocol Engine's `minimumZHeight` field, it can only increase the margin, not reduce it.

2023-12-01 17:39 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +                return self
Looks like this code is conflicting with the code on line 981?

2023-12-01 17:39 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +            - As a :py:class:`.TrashBin`. This uses a default location relative to the
I've been going back and forth and I can see it going either way.

In favor of public:

* Eventually we may need to support custom offsets like `drop_tip(waste_chute.top(z=10))`. (RSS-391.) Then, the `.top()` method needs to be documented somewhere.
* These classes will show up in various method signatures.
* For user code to be able to annotate the type of `TrashBin` and `WasteChute` variables, the `TrashBin` and `WasteChute` types need to be public.

In favor of private:

* General uncertainty and YAGNI.

I lean towards making them public.

2023-12-01 17:39 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +            - As a :py:class:`.TrashBin`. This uses a default location relative to the
(Note: If we do make them private, we need to remove the re-exports from `protocol_api/__init__.py`.)

2023-12-01 17:39 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +        """The trash containers associated with this pipette.
Sorry for the back-and-forth: this should just say "The trash container", singular. It only returns one.

2023-12-01 17:39 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
>          if self._trash is None:
Can we rename `self._trash` to `self._user_specified_trash`?

2023-12-04 15:46 UTC, ncdiehl11 commented on api/src/opentrons/protocol_api/instrument_context.py
> +                return self
How so? We enter the block beginning line 956 if `drop_tip` is called without a location argument, and we check to see if there's a valid loaded disposal_location on the protocol core. The block beginning line 981 executes if the explicitly passed argument for `drop_tip` `location` is an instance of `TrashBin` or `WasteChute`

2023-12-04 16:21 UTC, ncdiehl11 commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        }
great point. making that change.

2023-12-04 16:22 UTC, ncdiehl11 commented on api/src/opentrons/protocol_api/instrument_context.py
> +            - As a :py:class:`.TrashBin`. This uses a default location relative to the
@ecormany if we settle on public (seems like we will), should we restore the examples in the docstring?

2023-12-04 16:42 UTC, ecormany commented on api/src/opentrons/protocol_api/instrument_context.py
> +            - As a :py:class:`.TrashBin`. This uses a default location relative to the
I think we can leave the examples out of the reference entry here. "Specify location…as a `TrashBin`" gives all the information contained in `location=trash_bin` — plus that variable name could be anything depending on how the user loads it.

The "as a Well" and "as a Location" examples are more useful, because they show how to reference a well or location inline with a method, not premade and saved in a variable. And `reservoir` and `tip_rack` are defined in our [Protocol Template](https://docs.opentrons.com/v2/new_examples.html#protocol-template).

2023-12-04 17:08 UTC, CaseyBatten commented on api/src/opentrons/protocol_api/protocol_context.py
> +        waste_chute = WasteChute(with_staging_area_slot_d4=with_staging_area_slot_d4)
Waste Chute Object probably need modifying (not in this PR but before release) to no longer utilize this staging area slot parameter. This information is inferred from any referential call to the staging area slots elsewhere.

2023-12-04 17:14 UTC, CaseyBatten commented on api/src/opentrons/protocol_api/validation.py
> +    if robot_type == 'OT-2 Standard':
Are we sure this is how we want to do this? Currently the thinking is that OT-2 will have two deck configurations, an OT-2 deck with all slots and an OT-2 deck with a trash. How do we differentiate the deck config types for a v2.16 OT-2? Would doing something like ctx.load_trash_bin('ot2_short_trash', 12) not be a valid way to let us differentiate the decks?

2023-12-04 17:19 UTC, CaseyBatten commented on api/src/opentrons/protocol_api/instrument_context.py
> +            - As a :py:class:`.TrashBin`. This uses a default location relative to the
> * Eventually we may need to support custom offsets like `drop_tip(waste_chute.top(z=10))`. ([RSS-391](https://opentrons.atlassian.net/browse/RSS-391).) Then, the `.top()` method needs to be documented somewhere.

This is also in line with what is discussed int the [RSS-404](https://opentrons.atlassian.net/browse/RSS-404) requirements and the initial [PAPI documentation regarding deck configuration](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/3887759414/Deck+configuration+Python+Protocol+API), so the public facing methodology would be most in-line with our planned behavior so far.

2023-12-04 22:02 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +            - As a :py:class:`.TrashBin`. This uses a default location relative to the
Discussed in-person. We'll make them public.

2023-12-04 22:05 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/waste_chute.py
Sorry for the back-and-forth: this should still be named `_waste_chute.py` because we only want people to be able to do `from opentrons.protocol_api import WasteChute`, not `from opentrons.protocol_api.waste_chute import WasteChute`.

2023-12-04 22:05 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/trash_bin.py
Ditto my other comment about keeping this file named `_trash_bin.py` instead of `trash_bin.py`.

2023-12-04 22:09 UTC, SyntaxColoring requested changes

2023-12-04 22:09 UTC, SyntaxColoring commented on api/src/opentrons/protocols/advanced_control/transfers.py
> +                    )
This change looks a bit dangerous. If the trash isn't a labware, we're skipping the blowout.

We should either:

* Get this code to support non-labware trashes in this PR.
* Leave a `# TODO`, raise a `NotImplementedError`, and come back to this in another PR before launch.

2023-12-04 22:20 UTC, SyntaxColoring reviewed
Pinning the test to APIv2.15 seems good but let's explain what that's doing.

2023-12-04 22:20 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_api/core/engine/test_protocol_core.py
> +@pytest.mark.parametrize("api_version", [APIVersion(2, 15)])
```suggestion
# APIv2.15 because we're expecting a fixed trash.
@pytest.mark.parametrize("api_version", [APIVersion(2, 15)])
```

2023-12-04 22:20 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_api/core/engine/test_protocol_core.py
> +@pytest.mark.parametrize("api_version", [APIVersion(2, 15)])
```suggestion
# APIv2.15 because we're expecting a fixed trash.
@pytest.mark.parametrize("api_version", [APIVersion(2, 15)])
```

2023-12-04 22:20 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_api/core/engine/test_protocol_core.py
> +@pytest.mark.parametrize("api_version", [APIVersion(2, 15)])
```suggestion
# APIv2.15 because we're expecting a fixed trash.
@pytest.mark.parametrize("api_version", [APIVersion(2, 15)])
```

2023-12-04 22:20 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_api/core/engine/test_protocol_core.py
> +@pytest.mark.parametrize("api_version", [APIVersion(2, 15)])
```suggestion
# APIv2.15 because we're expecting a fixed trash.
@pytest.mark.parametrize("api_version", [APIVersion(2, 15)])
```

2023-12-05 00:12 UTC, CaseyBatten commented
Worked through various issues live and ran a protocol with loaded trash and loaded waste chute live, testing for the following cases:
Default trash drop tip, Specified trash drop tip, pipette trash container variable empty drop tip, transfer command default trash drop tip, multiple loaded movable trashes.

2023-12-05 22:21 UTC, SyntaxColoring commented on api/src/opentrons/protocols/advanced_control/transfers.py
> +                    )
https://opentrons.atlassian.net/browse/RSS-414

2023-12-05 23:19 UTC, SyntaxColoring approved these changes
Good to merge if we need to unblock v7.1.0 alpha testing. We will need to come back to this and add tests covering PAPI. The timing-out G-code tests are also concerning; we need to confirm whether those are the fault of this PR.

2023-12-06 15:10 UTC, merged