fix(app): do not redundantly check labware in LPC
OpenTrons/opentrons-api pull request #14079
Opened 2023-12-01 16:43 UTC by shlokamin

# Overview

RAUT-889

# Test Plan
Tested on an OT-2 (tip based LPC) just to make sure nothing broke
Tested on a Flex (probe based LPC) just to make sure nothing broke

# Changelog

- Do not redundantly check labware in LPC

# Risk assessment

Low./med

2023-12-01 17:45 UTC, sfoster1 requested changes

2023-12-01 17:45 UTC, sfoster1 commented on app/src/organisms/LabwarePositionCheck/utils/getTipBasedLPCSteps.ts
> +      (outerLabwareLocationCombo, _index, nonDupedLabwareLocationCombos) => {
```suggestion
      (outerLabwareLocationCombo, _index, nonDeDupedLabwareLocationCombos) => {
```
?

2023-12-01 17:45 UTC, sfoster1 commented on app/src/organisms/LabwarePositionCheck/utils/getTipBasedLPCSteps.ts
> +        return nonDupedLabwareLocationCombos.some(
talked in person but i don't think is right for the following reasons:
- this returns `true` if the labware+position combo _is_ duplicated when I think it should be the reverse
- this will always detect the labware+position combo as duplicated because it's checking the whole of the list we're iterating through, so the element we're currently checking will always be in that list

2023-12-04 21:49 UTC, sfoster1 approved these changes
Looks good to me, way simpler than I was thinking

2023-12-04 21:52 UTC, b-cooper approved these changes
🪑

2023-12-04 22:05 UTC, merged