fix(app): check firmware update status in instrument cards
OpenTrons/opentrons-api pull request #14110
Opened 2023-12-06 18:00 UTC by smb2268

# Overview
Improve accuracy of instrument status available on instrument card and fix bug where firmware update modal was never popping up on ODD

# Test Plan
Without going through an attachment flow, attach a pipette that will need a firmware update to a robot. See that the firmware update needed modal pops up on ODD. Initiate update via ODD and simultaneously watch the steps that occur on the corresponding instrument card via the desktop app. The card should show "Update in progress..." until about 5 seconds after the update is completed. Then, the instrument card should populate with the attached pipette

# Changelog
1. Add migration from stale `/dashboard` config value to `null` - this was preventing the firmware update modal from popping up on ODD because we rely on a `null` value to tell us that the unboxing flow is not in progress
2. Update poll for subsystem endpoint to continue until after the status of an update is `done`. Use that same value to determine when to start showing the attached instrument card, as this should give the `/instruments` endpoint enough time to reliably report what is attached

# Review requests
Look over changes (especially the config migration - did I cover everything?) & run through the test plan if you can 

# Risk assessment
Low

2023-12-06 18:05 UTC, sfoster1 requested changes

2023-12-06 18:05 UTC, sfoster1 commented on app/src/organisms/GripperCard/index.tsx
> +      subsystemUpdateData.status === 'done'
```suggestion
      subsystemUpdateData.updateStatus === 'done'
```

2023-12-06 18:25 UTC, koji commented on app/src/organisms/GripperCard/index.tsx
> +      }, 5000)
Can we define a new const for `5000`ms?

2023-12-06 18:29 UTC, koji commented
I think when we update config, we will need to update `app-shell` and `app-shell-odd`.

2023-12-06 18:36 UTC, koji commented on app/src/organisms/GripperCard/index.tsx
> +      subsystemUpdateData.status === 'done'
updated this to test the PR.

`subsystemUpdateData.data.updateStatus`

2023-12-06 18:38 UTC, koji commented on app/src/organisms/Devices/PipetteCard/index.tsx
> +      subsystemUpdateData.status === 'done'
```suggestion
      subsystemUpdateData.data.updateStatus === 'done'
```

2023-12-12 15:46 UTC, koji commented on app/src/organisms/FirmwareUpdateModal/FirmwareUpdateTakeover.tsx
> +              setIndexToUpdate(indexToUpdate + 1)
maybe

```ts
setIndexToUpdate(prevIndexToUpdate => prevIndexToUpdate  + 1)
```

2023-12-12 15:49 UTC, koji commented on app/src/organisms/Devices/PipetteCard/index.tsx
> +const POLL_DURATION = 5000
nit

```suggestion
const POLL_DURATION_MS = 5000
```

2023-12-12 15:50 UTC, koji commented on app/src/organisms/GripperCard/index.tsx
> +const POLL_DURATION = 5000
nit
same as the above

2023-12-12 19:07 UTC, koji approved these changes
Followed the test plan and it worked as expected!
The changes look good to me.

2023-12-13 19:22 UTC, sfoster1 approved these changes
Looks good to me!

2023-12-13 19:25 UTC, merged