fix(api): OT2 fixed trash load fix and API 2,15 support for new trash container structure
OpenTrons/opentrons-api pull request #14145
Opened 2023-12-07 22:05 UTC by CaseyBatten

# Overview
This seeks to close:
https://opentrons.atlassian.net/browse/RSS-417
https://opentrons.atlassian.net/browse/RQA-2022

Also seeks to add coverage for API 2.15 protocols expected fixed trash behavior.

# Test Plan

- Ensure no analysis failures!
- Test a 2.16 Protocol on OT2, it should execute correctly
- Test a 2,16 protocol on Flex with multiple trashes
- Test a 2.15 protocol with trashing behavior on OT2 and Flex, legacy trash behavior should be expected.

2023-12-07 22:23 UTC, ecormany reviewed
Thanks for the quick fix!

I pulled the branch and simulated the protocol included in RSS-417. Works as expected. 🚀 

Will let others test the rest and inspect the code.

2023-12-07 23:29 UTC, SyntaxColoring commented
> This seeks to close [...] https://opentrons.atlassian.net/browse/RQA-2022

Are we sure that this closes that? That looks like something from within Protocol Engine, unrelated to PAPI. Notice how the error message complains about a missing `fixedTrash` (camelCase), not a missing `fixed_trash` (snake_case).

2023-12-07 23:39 UTC, SyntaxColoring commented
Unfortunately I don't think this fully resolves RSS-417. Try this:

```python
requirements = {
    # "apiLevel": "2.15",  # Works
    "apiLevel": "2.16",  # Does not work
    "robotType": "OT-2",
}


def run(protocol):
    # Note: ProtocolContext.fixed_trash, not InstrumentContext.trash_container.
    # 
    # This raises NoTrashDefinedError.
    protocol.fixed_trash
```

I caught this by running this against the tests in #14142. I'm going to pull those into this PR.

2023-12-07 23:39 UTC, SyntaxColoring requested changes
Unfortunately I don't think this fully resolves RSS-417. Try this:

```python
requirements = {
    # "apiLevel": "2.15",  # Works
    "apiLevel": "2.16",  # Does not work
    "robotType": "OT-2",
}


def run(protocol):
    # Note: ProtocolContext.fixed_trash, not InstrumentContext.trash_container.
    # 
    # This raises NoTrashDefinedError.
    protocol.fixed_trash
```

I caught this by running this against the tests in #14142. I'm going to pull those into this PR.

2023-12-08 18:18 UTC, CaseyBatten commented on api/src/opentrons/protocol_api/protocol_context.py
> +        if self._api_version >= APIVersion(2, 16):
This newly added section to should provide handling for the issue Max identified and has tests implemented for. The following behavior is to be expected as a result:
v2.16 OT2 Protocol will identify protocol.fixed_trash as a TrashBin object
v2.16 Flex Protocol will raise an error on protocol.fixed_trash, notifying that for the Flex fixed trash does not exist on API version 2.16 and above.

2023-12-08 21:52 UTC, CaseyBatten reviewed
Changes integrated to cover requested issue regarding protocol context fixed trash references.

2023-12-08 21:55 UTC, SyntaxColoring approved these changes
This looks like it'll work and I'm satisfied with our test coverage now. Thanks for seeing this through!

Here are some code organizational suggestions. ~~I'd like us to resolve the `NoTrashDefinedError` vs. `APIVersionError` thing before merging, because it seems easy enough. We can leave the harder ones to later, if we need to move on to other things.~~ [EDIT: Ehh we can leave it all to later if we need to.]

2023-12-08 21:55 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/protocol_context.py
> +        # protocols after 2.16 expect trash to exist as either a TrashBin or WasteChute object.
Can this comment be broken up, or shortened, for readability? I'm having trouble parsing it.

2023-12-08 21:55 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/protocol_context.py
>          self._load_fixed_trash()
It looks like some trash initialization code already existed in `self._load_fixed_trash()`. Organizationally, it seems like we should be adding our new code there.

2023-12-08 21:55 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/protocol_context.py
> +            self._core.append_disposal_location(_fixed_trash_trashbin)
I think this is showing us that we need to rename or rework `should_load_fixed_trash_for_python_protocol()`.

I'm not super familiar with that code, but I'm inferring from this usage that it currently works like "should we load a fixed trash *labware*," not "should we load *any form of fixed trash at all.*"

So:

* We call `should_load_fixed_trash_for_python_protocol()`.
    * If it returns yes: Load a fixed trash as a `Labware`.
    * If it returns no:
        *  Do our own check for whether we should load a fixed trash.
            * If yes: Load a fixed trash as a `TrashBin`.
                * **This is what's confusing to me.** It reads like we just asked `should_load_fixed_trash_for_python_protocol()` a question, then ignored its answer and did things our own way anyway.

@jbleon95 Any opinions?

2023-12-08 21:55 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/protocol_context.py
> +            self._api_version >= APIVersion(2, 16)
As far as I can tell, this `self._api_version >= APIVersion(2, 16)` check is not doing anything. We can only reach here if `self._api_version >= APIVersion(2, 16)`, because there's a similar version check in the call to `should_load_fixed_trash_for_python_protocol()`, above.

I see where this is coming from, but I think we should leave this `_api_version` check out. I'm worried about accidentally leaving a gap between `should_load_fixed_trash_for_python_protocol()`'s maximum `APIVersion`, which defines the latest version where the fixed trash is a `Labware`, and this `APIVersion`, which defines the earliest version where the fixed trash is a `TrashBin`. If there's a gap, we'd be left with versions where OT-2 protocols accidentally have no fixed trash.

I would just write this as `elif self._core.robot_type == "OT-2 Standard"`.

2023-12-08 21:55 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/protocol_context.py
> +                )
Let's raise `NoTrashDefinedError` instead of `APIVersionError`. Whether `protocol.fixed_trash` is available is a question of more than just the `apiLevel`; it has to do with the robot type, too.

```suggestion
                raise NoTrashDefinedError(
                    "Fixed Trash is not supported on Flex protocols in API Version 2.16 and above."
                )
```

2023-12-08 21:55 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/protocol_context.py
> +
This is a bit confusing to me because it looks like we now have two competing ways of keeping track of the fixed trash: `AbstractProtocol.fixed_trash`, and `AbstractProtocol.get_disposal_locations()`.

`AbstractProtocol.append_disposal_location()`/`.get_disposal_locations()` were really only added specifically to keep track of the user's explicit calls to `ProtocolContext.load_waste_chute()` and `ProtocolContext.load_trash_bin()`. They *could* also keep track of the fixed trash, like you have here, but if we do that, we need to do it consistently.

In other words, I think we need to choose between:

* `AbstractProtocol.get_disposal_locations()` returns the fixed trash *or* the user's explicitly-loaded trashes.
  * Then, we would delete `self._core.fixed_trash` from our codebase.
* `AbstractProtocol.get_disposal_locations()` returns only the user's explicitly-loaded trashes, and `AbstractProtocol.fixed_trash` returns only the Opentrons standard fixed trash, if there is one.
  * Then, when a user accesses `ProtocolContext.fixed_trash`, we would not do `self._core.get_disposal_locations()[0]`. Instead, we would do `self._core.fixed_trash`.

2023-12-08 23:34 UTC, merged