Components Library Bundle Fixes for Distribution
OpenTrons/opentrons-api pull request #14281
Opened 2024-01-04 15:47 UTC by b-cooper

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-01-05 15:32 UTC, b-cooper commented on components/src/hardware-sim/BaseDeck/BaseDeck.tsx
> -  /** user defined name for this instance of the labware */
these `displayName` props were unused and are redundant with the the `children` props

2024-01-08 16:23 UTC, b-cooper commented on app/src/resources/deck_configuration/hooks.ts
@brenthagen could you 👁️ this change?

2024-01-08 16:30 UTC, b-cooper commented on components/src/hardware-sim/Module/index.tsx
> +      lidMotorState: 'open' as const,
if lidMotorState is not explicitly passed down as "unknown", "closed", or "open", default to "open" as it is the most responsible default

2024-01-08 16:59 UTC, b-cooper commented on components/src/hardware-sim/Module/index.tsx
> +      lidMotorState: 'open' as const,
if lidMotorState is not explicitly passed down as "unknown", "closed", or "open", default to "open" as it is the most responsible default

2024-01-08 17:01 UTC, jerader reviewed
mainly focused on reviewing PD components + smoke testing PD, lgtm!

2024-01-08 19:03 UTC, smb2268 commented on components/src/hardware-sim/Module/Thermocycler/ThermocyclerGEN1.tsx
> +  console.log('led', props.ledLightColor)
console statement can be removed

2024-01-08 19:09 UTC, smb2268 requested changes
Started to test this out, but hit a white screen when attempting to setup a protocol. Details in the comments!

2024-01-08 19:09 UTC, smb2268 commented on components/src/hardware-sim/ProtocolDeck/index.tsx
>    const robotType = protocolAnalysis.robotType ?? FLEX_ROBOT_TYPE
When testing this out, I pressed "run a protocol" from the device overflow menu, and got a white screen. The error is: 

> getAddressableAreasInProtocol.ts?0529:94 Uncaught TypeError: Cannot read properties of undefined (reading 'some')
>     at getAddressableAreasInProtocol (getAddressableAreasInProtocol.ts?0529:94:46)
>     at getSimplestDeckConfigForProtocol (getSimplestFlexDeckConfig.ts?14e7:46:38)
>     at ProtocolDeck

And then: 

> The above error occurred in the <ProtocolDeck> component:

    at ProtocolDeck (webpack-internal:///../components/src/hardware-sim/ProtocolDeck/index.tsx:37:32)

This was reproducible each time I tested

2024-01-08 19:27 UTC, brenthagen approved these changes
smoke tested various components and app flows. i'll try loading more protocols and see if issues emerge.

2024-01-08 19:27 UTC, brenthagen commented on components/src/hardware-sim/Deck/RobotCoordsForeignDiv.tsx
> +  outerProps?: any
think this is `React.SVGProps<SVGForeignObjectElement>`

2024-01-08 19:27 UTC, brenthagen commented on components/src/hardware-sim/Deck/DeckFromLayers.tsx
>  /**
could change the component description to something like "a component that renders a collection of deck layers as svg elements"

2024-01-08 19:27 UTC, brenthagen commented on components/src/hardware-sim/Labware/labwareInternals/StyledWells.tsx
> +    fill: `${COLORS.blueEnabled}33`, // 20% opacity
we have opacity constants defined in COLORS (`opacity20HexCode`)

2024-01-08 19:27 UTC, brenthagen commented on components/src/hardware-sim/ProtocolDeck/index.tsx
> +  const labwareByLiquidId = getLabwareInfoByLiquidId(protocolAnalysis.commands)
perhaps a TODO, we should at some point compare the processing here to what we do for protocol run setup. particularly `SetupLiquidsMap` - at a minimum there we're using deprecated `parseLabwareInfoByLiquidId` and duplicating a `getWellFillFromLabwareId` utility.

2024-01-08 19:27 UTC, brenthagen commented on protocol-designer/src/components/labware/SelectableLabware.tsx
> +import { WellMouseEvent, WellGroup } from '@opentrons/components'
`import type`

2024-01-08 19:27 UTC, brenthagen commented on protocol-designer/src/utils/index.ts
> +import { INTERACTIVE_WELL_DATA_ATTRIBUTE } from '@opentrons/components/src/hardware-sim/Labware/labwareInternals/Well'
can this be exported from the root of `components`?

2024-01-08 20:25 UTC, smb2268 commented on components/src/hardware-sim/ProtocolDeck/index.tsx
>    const robotType = protocolAnalysis.robotType ?? FLEX_ROBOT_TYPE
Tracked down the issue and it will be fixed in https://opentrons.atlassian.net/browse/RAUT-923?atlOrigin=eyJpIjoiNmZmMDFmZjhhNmZhNGE0ZDkxNjZlY2JjOWZhODY4M2UiLCJwIjoiaiJ9

2024-01-08 20:26 UTC, smb2268 approved these changes

2024-01-08 21:16 UTC, merged