Abr scale
OpenTrons/opentrons-api pull request #14333
Opened 2024-01-19 22:33 UTC by rclarke0

# Overview

Adding script to take and analyze scale measurements.

# Test Plan

I did not take any testing steps because this script is not used by any of the robots.

# Changelog

# Review requests

Double check that changes to the drivers on the scale do not break anything else.

# Risk assessment
low risk

2024-01-25 14:26 UTC, andySigler requested changes
thank you for this! let's sit down together and go through what needs change before a merge 👍

2024-02-01 19:51 UTC, rclarke0 reviewed
LGTM

2024-02-04 14:02 UTC, andySigler approved these changes
Looks ready to merge, other than that one file that seems empty other than the commented out pieces

2024-02-04 14:02 UTC, andySigler commented on hardware-testing/hardware_testing/scripts/abr_asair_sensor.py
> +# from hardware_testing import data
You can remove commented things. If it's commented out, then it should just be deleted.

2024-02-04 14:02 UTC, andySigler commented on hardware-testing/hardware_testing/scripts/abr_asair_sensor.py
> +# from hardware_testing import data
also should this file be a part of the PR? It's empty

2024-02-05 15:44 UTC, merged