fix(app): Fix improper transitioning run status in protocol runs
OpenTrons/opentrons-api pull request #14459
Opened 2024-02-08 21:21 UTC by mjhuff

Closes [RQA-2291](https://opentrons.atlassian.net/browse/RQA-2291), [RQA-2307](https://opentrons.atlassian.net/browse/RQA-2307), [RQA-2306](https://opentrons.atlassian.net/browse/RQA-2306), [RQA-2304](https://opentrons.atlassian.net/browse/RQA-2304)

# Overview

This PR fixes a bug on the app side in which the incorrect property React Query was used. In order to prevent _any_ refetches, staleTime is the correct choice. Certain useRunQuery and useAllRunQuery hooks that were not updating properly now update as expected. Also, the removed `RUN_STATUS_STOP_REQUESTED` is added back to useRunStatus(), since its removal was causing bug RQA-2306. 

The python side changes are all sanity check changes - nothing new here. A new push is added to the remove method, since we want to push on every new CRUD. I don't know if this was causing bugs, but it should be fixed. 

# Test Plan
- Run through the bug tickets and make sure they now work.

# Changelog
- Fixed modals/buttons not updating correctly related to protocol runs.

# Risk assessment
low

[RQA-2291]: https://opentrons.atlassian.net/browse/RQA-2291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RQA-2307]: https://opentrons.atlassian.net/browse/RQA-2307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RQA-2306]: https://opentrons.atlassian.net/browse/RQA-2306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RQA-2304]: https://opentrons.atlassian.net/browse/RQA-2304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-02-08 21:45 UTC, sfoster1 requested changes
couple small change requests for python style and robustness

2024-02-08 21:45 UTC, sfoster1 commented on robot-server/robot_server/service/notifications/publishers/runs_publisher.py
> +            asyncio.create_task(
rather than having both a bool and a task, let's just store the task object in an optional member and only create one if it's none:
```
if self._poller is None:
    self._poller = asyncio.create_task(self._poll_engine_store(...))
```

2024-02-08 21:45 UTC, sfoster1 commented on robot-server/robot_server/service/notifications/publishers/runs_publisher.py
> +        self._isPollingAlready = False
```suggestion
        self._poller: Optional[asyncio.Task[None]] = None
```
(see below)

2024-02-08 21:53 UTC, mjhuff commented on robot-server/robot_server/service/notifications/publishers/runs_publisher.py
> +            asyncio.create_task(
🧠

2024-02-09 15:56 UTC, sfoster1 requested changes

2024-02-09 15:56 UTC, sfoster1 commented on robot-server/robot_server/service/notifications/publishers/runs_publisher.py
> +        self._poller = None
This will not actually stop the task, it will just orphan it. Instead, explicitly call `self._poller.cancel()` first

2024-02-09 16:25 UTC, mjhuff commented on robot-server/robot_server/service/notifications/publishers/runs_publisher.py
> +        self._poller = None
Ah, thanks!

2024-02-09 19:22 UTC, sfoster1 approved these changes
Looks good to me!

2024-02-09 19:42 UTC, merged