docs: update docs to reflect node v18 is current
OpenTrons/opentrons-api pull request #14467
Opened 2024-02-11 19:33 UTC by strangemonad

# Overview

There's already a .nvmrc file but if someone is just manually following the docs, there are references to node v16 and then either `make setup` will fail if you forced the current node version to be v16 or the setup docs will be confusing.

# Test Plan
Ran locally with both `nvm` and `nvs` in both auto mode and manual mode
- nvs auto changes to v18 when I cd into the dirrectory
- `nvm install` and `nvm use` also work as expected.

# Changelog
- Updated dev setup docs to reflect that the project depends on Node v18

# Review requests

n/a

# Risk assessment
n/a

2024-02-12 06:23 UTC, koji commented
Hi @strangemonad, thank you for opening a PR!

2024-02-12 06:24 UTC, koji reviewed
LGTM (node version parts)

@ecormany, could you check this PR?

2024-02-12 23:23 UTC, ecormany requested changes
Thanks for this addition! I made some minor suggestions, mostly to make sure that the text renders well on GitHub.

2024-02-12 23:23 UTC, ecormany commented on DEV_SETUP.md
> +Now we can use `nvs` to install the currently required Node.js version set in `.nvmrc`. We think it's easiest if you switch on `auto` mode which will make sure the correct version of Node.js is used
```suggestion
Now we can use `nvs` to install the currently required Node.js version set in `.nvmrc`. We enable `auto` mode to use the correct version of Node.js any time we're in the `opentrons` project directory. Without `auto` mode, we would have to manually run `use` or `install` each time we work on the project.
```
Markdown footnotes don't render inline in GitHub, which is where most users will read this. So I would remove that syntax. Plus some light prose edits.

2024-02-13 16:50 UTC, koji commented on DEV_SETUP.md
> +Now we can use `nvs` to install the currently required Node.js version set in `.nvmrc`. We think it's easiest if you switch on `auto` mode which will make sure the correct version of Node.js is used
I think we'd like to remove "mode" from use `nvs` auto mode since it is a command or switching the word from mode to command would be better.

https://github.com/jasongin/nvs?tab=readme-ov-file#command-reference

2024-02-13 17:07 UTC, ecormany commented on DEV_SETUP.md
> +Now we can use `nvs` to install the currently required Node.js version set in `.nvmrc`. We think it's easiest if you switch on `auto` mode which will make sure the correct version of Node.js is used
How about:
```
The `auto` command selects the correct version of Node.js any time we're in the `opentrons` project directory.
Without `auto`, we would have to manually run `use` or `install` each time we work on the project.
```

2024-02-13 23:00 UTC, koji commented on DEV_SETUP.md
> +Now we can use `nvs` to install the currently required Node.js version set in `.nvmrc`. We think it's easiest if you switch on `auto` mode which will make sure the correct version of Node.js is used
I think `the correct version` -> `the long-term support (LTS) version` would be accurate.
what do you think about that, @ecormany ?

2024-02-14 14:52 UTC, ecormany commented on DEV_SETUP.md
> +Now we can use `nvs` to install the currently required Node.js version set in `.nvmrc`. We think it's easiest if you switch on `auto` mode which will make sure the correct version of Node.js is used
I used "correct" just to mean "it will work" 😁 

I don't think we have to be more precise here. (And I don't know enough about how `nvs` behaves to be more precise.)

2024-02-14 15:04 UTC, koji commented on DEV_SETUP.md
> +Now we can use `nvs` to install the currently required Node.js version set in `.nvmrc`. We think it's easiest if you switch on `auto` mode which will make sure the correct version of Node.js is used
For nvs/nvm, we set 18 in `.nvmrc` so if someone uses `nvs auto` or `nvm use`, nvs/nvm will install LTS version of nodejs. Right now it is v 18.19.0.

2024-02-19 17:30 UTC, strangemonad commented on DEV_SETUP.md
> +Now we can use `nvs` to install the currently required Node.js version set in `.nvmrc`. We think it's easiest if you switch on `auto` mode which will make sure the correct version of Node.js is used
@ecormany @koji any final thoughts on this as to the final version of the wording? I don't have strong feelings so happy to follow whatever you settle on as best

2024-02-19 23:38 UTC, koji commented on DEV_SETUP.md
> +Now we can use `nvs` to install the currently required Node.js version set in `.nvmrc`. We think it's easiest if you switch on `auto` mode which will make sure the correct version of Node.js is used
Hi @strangemonad 

If you adopted the following Ed's suggestion, that would be great. 
```
The `auto` command selects the correct version of Node.js any time we're in the `opentrons` project directory.
Without `auto`, we would have to manually run `use` or `install` each time we work on the project.
```

2024-03-12 16:47 UTC, koji commented
@strangemonad 
I will close this PR since the PR hasn't been updated for 3 weeks.
We love your addition, and we'd like to add that as soon as possible.
I opened a new PR to follow up this PR.

We really appreciate your contribution!

2024-03-12 16:47 UTC, closed without merging