feat(api,hardware): add hepa/uv config/control commands to api.
OpenTrons/opentrons-api pull request #14489
Opened 2024-02-13 22:56 UTC by vegano1

# Overview

We added can messages to control the hepa/uv in this pr [(Opentrons/opentrons:#14452)](https://github.com/Opentrons/opentrons/pull/14452), now we want to use those messages from the hardware controller and API. This pr adds the hooks to these can messages so they can be used from repl.

# Test Plan

- [ ] Make sure we can control the hepa/uv module using ot3api from repl
- [ ] Make sure we can query the hepa/uv module using ot3api from repl

# Changelog

- Added hooks to OT3API and OT3Controller to enable control/query of Hepa/UV state.

# Review requests

# Risk assessment

low, unreleased

# Todo

- [ ] Add unit tests

2024-02-14 15:56 UTC, sfoster1 requested changes
Functionality looks good but let's get some tests on the hepa_uv_settings.py

2024-02-14 15:56 UTC, sfoster1 requested changes
Also we need some stubs in `ot3simulator`

2024-02-14 16:20 UTC, caila-marashaj commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        res = await get_hepa_uv_state_fw(self._messenger)
Are you not just returning res here because of linter complaining?

2024-02-14 16:48 UTC, caila-marashaj approved these changes

2024-02-14 21:19 UTC, pmoegenburg commented on api/src/opentrons/hardware_control/ot3api.py
> +        self, turn_on: bool = False, timeout_s: int = 900
Do we need this long of a timeout?

2024-02-15 21:36 UTC, vegano1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        self, turn_on: bool = False, timeout_s: int = 900
yeah 900s (15m) is the default uv light timeout

2024-02-15 21:38 UTC, vegano1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        res = await get_hepa_uv_state_fw(self._messenger)
its to separate opentrons_hardware dataclasses from opentrons.hardware_control ones.

2024-02-16 16:00 UTC, sfoster1 approved these changes
Looks good to me, though I agree with Peter that we maybe need a better name for `timeout` - it looks at first glance like it's a time-before-error parameter like other timeouts.

2024-02-16 16:00 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        self, turn_on: bool = False, timeout_s: int = 900
can we call it like `dose_duration` or something?

2024-02-16 17:37 UTC, merged