docs(api): section on Position Relative to Trash Containers
OpenTrons/opentrons-api pull request #14593
Opened 2024-03-04 19:18 UTC by ecormany

# Overview

Follow up to further explain behavior introduced in #14560.

# Test Plan

- [sandbox](http://sandbox.docs.opentrons.com/docs-trash-offsets/v2/robot_position.html#position-relative-to-trash-containers)
- simulated snippets in 2.16 / `edge`

# Changelog

- new § on Labware and Deck Positions page
- updated description and example for `move_to()` to cover new acceptable `location`s
- version added statements for `TrashBin`, `WasteChute`, and their methods in API Reference 

# Review requests

- double check code snippets. not only simulate, but do what i say they do?
- confirm version added for the methods. it feels like we may need to gate this to 2.17, because otherwise there will be a big functionality gap between robot system 7.1 (which can't do any of this) and 7.2 (which can). the classes are unambiguously _New in version 2.16._

# Risk assessment

low…but see API version gate caveat above.

2024-03-04 19:59 UTC, jwwojak commented on api/docs/v2/robot_position.rst
> +You can adjust the position of the pipette center with the :py:meth:`.TrashBin.top` and :py:meth:`.WasteChute.top` methods. These methods allow adjustments along the x-, y-, and z-axes (in constrast
Spelling typo: "constrast" --> contrast

Wondering about the parenthetical comparison to the `Well.top` method. Could the contrast be stronger if this became its own sentence? Make it stand out some.  "By contrast, the `Well.top` method only allows z-axis adjustments."

Or something like that.

2024-03-05 14:53 UTC, jbleon95 requested changes

2024-03-05 14:53 UTC, jbleon95 commented on api/docs/v2/robot_position.rst
> +    pipette.drop_tip()  # drop in waste chute, 5 mm lower than default
This isn't the case with this right now, since currently if you provide no arguments to drop tip, tip drop alternation overrides any set offset. Its only if you explicitly provide that offseted disposal location that we use that.

2024-03-05 14:53 UTC, jbleon95 commented on api/src/opentrons/protocol_api/disposal_locations.py
> +    .. versionadded:: 2.16
This is targeted for 2.18 in the future 7.3 release (or whatever we end up calling it)

2024-03-05 14:57 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +    pipette.drop_tip()  # drop in waste chute, 5 mm lower than default
🙏 Thank you for flagging this. I wasn't sure if I had overextended here, since neither simulation nor run preview say anything about offsets — just the parent object the offset is applied to.

I'll remove this bit.

2024-03-05 14:59 UTC, ecormany commented on api/src/opentrons/protocol_api/disposal_locations.py
> +    .. versionadded:: 2.16
So, the _class_ is added in 2.16, since we're already using it.

The `top()` method isn't going to be in the next API version though? That would be 2.17.

2024-03-06 21:10 UTC, ecormany commented on api/src/opentrons/protocol_api/disposal_locations.py
> +    .. versionadded:: 2.16
Update: 2.17 indeed went with robot system 7.2.0. So I'll bump these to 2.18. And target this on a new docs feature branch.

2024-03-07 17:23 UTC, ecormany commented
OK, after a near-miss rebasing this onto `docs_release.2-18`, this is ready for another review. Not much prose has changed (except some added in the API reference). Version added/changed notices have changed and moved around quite a bit — make sure I've tagged everything properly, especially related features added _prior_ to 2.18.

2024-03-07 18:28 UTC, jwwojak commented on api/docs/v2/robot_position.rst
> +In API version 2.15 and earlier, trash containers are :py:class:`.Labware` objects that have a single well. Use the above techniques for labware to adjust position relative to trash containers in pro
Word choice: "techniques" stands out as unusual to me. The content referred to are methods.

Might it make sense to write something like, "Use the labware _methods_ above to adjust position relative to trash containers ..."

2024-03-07 18:42 UTC, jwwojak commented on api/docs/v2/robot_position.rst
> +
I'm putting a comment here because this refers to the intro sentences to the first 2 paragraphs, lines 126 and 128.

While the intros are clear, each paragraph tells the reader that the API treats trash containers differently depending on the API verison. I wonder if we're softening two very important pieces of information by discussing them in simple, unadorned paragraphs. The differences may get lost or overlooked by someone hastily browsing through the docs looking for an answer.

One way to resolve this, and make the 2 paragraphs stand, out is to put them in a table with the version in one column and a description in another. However, this is unusual compared to current practice in the API docs and I can see that it might not be desirable.

Maybe this section needs a short intro sentence immediately following the section title. Something simple like, "Depending on the API version, the API treats trash containers as either generic labware objects or distinct trash bin or waste chute objects." Something to prime the reader along the lines of, "hey you, pay attention here! you might not see the distinctions being made in these paragraphs and you need to."

While the text is fine as is, I still wonder about what could be done to make the differences between these 2 paragraphs pop more.

2024-03-07 18:43 UTC, jwwojak reviewed
Added review comments for consideration. Defer to others re: go/no go approvals.

2024-03-07 21:58 UTC, jbleon95 commented on api/src/opentrons/protocol_api/instrument_context.py
> +            .. versionchanged:: 2.18
This and the other methods in instrument context can accept TrashBin and WasteChute starting in version 2.16

2024-03-07 21:58 UTC, jbleon95 approved these changes

2024-03-07 22:02 UTC, ecormany commented on api/src/opentrons/protocol_api/instrument_context.py
> +            .. versionchanged:: 2.18
I knew I had confused something. Thanks for checking!

2024-03-07 22:33 UTC, ecormany commented on api/docs/v2/robot_position.rst
> +
Went for a restructure here. Re-requesting a review…

(Also, you can comment on multiple lines. Click the first line, shift-click the last line, then click the `+` _also on the last line_. It's a little fussy, but it works!)

2024-03-08 13:32 UTC, jwwojak commented on api/docs/v2/robot_position.rst
> +
Ed, Yes to the changes here! Great revision. This aligns the text with the latest version functionality. Nice fix. LGTM.

2024-03-08 13:32 UTC, jwwojak approved these changes
Great revision.

:shipit:

2024-03-08 16:27 UTC, merged