Script to use raw LLD data to test new algorythms
OpenTrons/opentrons-api pull request #14595
Opened 2024-03-04 21:49 UTC by ryanthecoder

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-03-06 19:04 UTC, sfoster1 requested changes

2024-03-06 19:04 UTC, sfoster1 commented on hardware/opentrons_hardware/scripts/lld_data_script.py
> +import numpy
already have that above right

2024-03-06 19:04 UTC, sfoster1 commented on hardware/opentrons_hardware/scripts/lld_data_script.py
> +        # print(running_avg_derivative)
IMO just keep these prints in

2024-03-08 19:36 UTC, ryanthecoder commented on hardware/opentrons_hardware/scripts/lld_data_script.py
> +        # print(running_avg_derivative)
Changed it so that derivative is part of the graph instead

2024-03-11 16:17 UTC, merged