feat(shared-data): create util so FE apps can access pip schema v2 defs
OpenTrons/opentrons-api pull request #14605
Opened 2024-03-07 17:09 UTC by jerader

closes AUTH-51

# Overview

Note: need to wait until Vite migration merges in before testing this since it relies on vite's `import.meta.glob`.

This PR creates a new util for the FE apps to grab the pipette schema v2 definitions. There are some keys in the v2 definitions that PD will need to have access to. 

In a follow up PR, I am going to plug this new util into every instance of `getPipetteNameSpecs` in PD

# Test Plan

Review the util and types. 

If you want, find a place where `getPipetteNameSpecs` is being used and plug it in the new util and test it to see that it works as expected! A component i've been testing with is `PipetteTypeTile` and plugging `    console.log('pip specs', getPipetteSpecsV2(o.value))` into line 174 and checking that it logs correctly.

# Changelog

- create new types that match the json shapes
- create a new `getPipetteSpecsV2` util. It takes in the same props as `getPipetteNameSpecs` and `getPipetteModelSpecs` and using the prop info, parsing out the matching pipette v2 definition file paths. Then it filters through all the json files in the given paths to return 3 json files that match the pipetteName's specs. Finally, it combines the 3 json files into 1 and the utility returns that combined object.

# Review requests

see test plan

# Risk assessment

low

2024-03-07 17:55 UTC, sfoster1 requested changes
Two things -
- If we're going to export the liquid specs, we should definitely export both the default and low volume specs
- Do we have a test or lint job or something that will fail if the ts types don't match the jsons?

2024-03-07 17:55 UTC, sfoster1 commented on shared-data/js/pipettes.ts
> +          (type === 'liquid' &&
We should export all the "liquid class" liquid definitions, not just default

2024-03-07 18:31 UTC, jerader commented on shared-data/js/pipettes.ts
> +          (type === 'liquid' &&
Oh, i didn't realize there was a `lowVolumeDefault` folder, thanks! Yes I should definitely add that in. Since the keys are the same as the `Default`, i wonder if i should add an optional prop to the util to allow for returning either default or low volume.

2024-03-07 18:32 UTC, jerader commented
> * Do we have a test or lint job or something that will fail if the ts types don't match the jsons?

@sfoster1, that is a good point, thank you! I will add a test.

2024-03-07 19:52 UTC, sfoster1 commented on shared-data/js/pipettes.ts
> +          (type === 'liquid' &&
Yeah I think that would be fine, or have it be a mapping. In theory we will add more kinds of liquid classes.

2024-03-07 19:53 UTC, sfoster1 requested changes

2024-03-07 19:53 UTC, sfoster1 commented on shared-data/js/pipettes.ts
> +  lowVolume: boolean
Could we do something like `liquidClass?: 'default' | 'lowVolume'` with unspecified meaning default or something? or even `liquidClass?: string`

2024-03-07 19:53 UTC, jerader commented on shared-data/js/pipettes.ts
> +          (type === 'liquid' &&
oh mapping makes a lot of sense actually and could accommodate more liquid classes as we make them. Okay i'm gonna do that instead. thanks!

2024-03-07 22:19 UTC, jerader commented
- [ ] write test after vite migration merges into edge

2024-03-08 15:08 UTC, sfoster1 approved these changes
Looks great to me! Thank you!

2024-03-08 15:08 UTC, sfoster1 commented on shared-data/js/pipettes.ts
> +const LIDUID_TYPES = ['default', 'lowVolumeDefault']
can we discover these dynamically from what directories are present or do we have to list them here?

2024-03-08 18:23 UTC, b-cooper commented on shared-data/js/pipettes.ts
> +  const generalGeometricCombined = Object.assign({}, ...matchingJsons)
This should probably be wrapped into the reduce for clarity?

2024-03-08 18:25 UTC, koji commented on shared-data/js/pipettes.ts
> +  const nameSplit = name.split('_')
nit

```ts
const {[0]: pipetteModel, [1]: pipetteChannel, [2]: pipetteGen } = name.split('_')
```

2024-03-08 18:28 UTC, b-cooper commented on shared-data/js/pipettes.ts
> +      const path = Object.keys(liquid)[index]
You should be able to remove some redundant code if you reduce `Object.entries` instead of creating `liquidJsons`?

2024-03-08 18:30 UTC, koji commented on shared-data/js/__tests__/pipettes.test.ts
> +              'opentrons/opentrons_flex_96_tiprack_1000ul/1': 10.5,
nit
maybe define as const?

2024-03-08 18:38 UTC, koji commented on shared-data/js/types.ts
> +  orderedRows: any
Can we switch the type from any to a specific type?
I guess Brent upgraded the TypeScript version so now defining a type would be more flexible than before.

2024-03-08 18:40 UTC, koji commented on shared-data/js/types.ts
> +  $otSharedSchema: string
question

`$otSharedSchema`.  Do you know why we use `$` in an object item name?

2024-03-08 19:52 UTC, jerader commented on shared-data/js/pipettes.ts
> +  const nameSplit = name.split('_')
some of the names don't have a pipetteGen (like `p10_single`)  so i'm not sure if this makes it more clear or not

2024-03-08 19:56 UTC, jerader commented on shared-data/js/types.ts
> +  $otSharedSchema: string
it represents the schema, i thought about removing it because i don't think we care about them in the frontend

2024-03-11 16:43 UTC, koji approved these changes
LGTM!

2024-03-11 17:30 UTC, sanni-t commented on shared-data/js/pipettes.ts
> +  }
Maybe it's my lack of js code comprehension but does this handle the 96-channel correctly? We load it using the `p1000_96` name in engine and I'm guessing that's what is used in the client side. Is that case covered here?

2024-03-11 18:08 UTC, jerader commented on shared-data/js/pipettes.ts
> +  }
Yup! The 96 channel will fall under the `nameSplit.length === 2` case since `p1000_96` will be split up into an array of 2.

2024-03-11 18:10 UTC, sanni-t commented on shared-data/js/pipettes.ts
> +  }
But it looks like it'll always default to using the `1_0` version?

2024-03-11 18:13 UTC, jerader commented on shared-data/js/pipettes.ts
> +  }
Oh, should it be defaulting to the `3_0` version?

2024-03-11 18:22 UTC, b-cooper commented on shared-data/js/pipettes.ts
> +  }
It depends on this function's purpose. Right now the function takes in either a `model` or a `name`.  If a name is given you're going to end up giving the user version specific information, do the front-ends actually want the most modern version specific information?  If so, then the logic here should specifically find the most modern model of a given pipette name. 

It might be helpful to organize this by splitting the internals of this function on how it handles `pipetteName` vs. `pipetteModel`?

2024-03-11 18:29 UTC, jerader commented on shared-data/js/pipettes.ts
> +  }
the specific version will be taken care of in the `else`.

If you have the `pipetteName`, it is either something like `p10_single` or `p10_single_gen1`. If it has the gen attached, then the version will be `1_0` for gen1, `2_0` for gen2, `3_0` for flex. If it doesn't have the gen, then i've been defaulting to `1_0` (since not having the gen means it is a gen1 pipette, except for the 96-channel). But seems like the 96-channel, even though it is a gen1, needs to use `3_0`.

2024-03-11 18:43 UTC, sanni-t commented on shared-data/js/pipettes.ts
> +  }
> do the front-ends actually want the most modern version specific information?

Sorry, this is what I'm trying to understand too. The 96 channel does have a `1_0` definition as default. But ya for non-default we'll have to use the `3_..` versions. 
Checking what we do in python.

Where does the app get pipette model/ version from? Is that from `/instruments`? 
And I guess the question of default values is more relevant to PD since PD won't know exact versions of pipettes to use?

2024-03-11 18:46 UTC, jerader commented on shared-data/js/pipettes.ts
> +  }
> And I guess the question of default values is more relevant to PD since PD won't know exact versions of pipettes to use?

Correct, PD will always get the specs from the pipetteName.

> Checking what we do in python.

looks like in python in` version_from_generation`, we are defaulting to `3_0`, `2_0`, or `1_0`. - looks like 96-channel is using `1_0`?

2024-03-11 19:00 UTC, sanni-t commented on shared-data/js/pipettes.ts
> +  }
Got it. Sorry about the confusion.

As for the question of whether we should use the latest version of a pipette as default, this was brought up previously but I'm not sure if there was a decision made. I'll check and post an update somewhere relevant later.

2024-03-11 19:00 UTC, sanni-t approved these changes
LGTM! This is really awesome

2024-03-11 19:01 UTC, jerader commented on shared-data/js/pipettes.ts
> +  }
no worries, and thank you!

2024-03-12 16:24 UTC, merged