refactor(robot-server): Utilize unsubscribe flags for dynamic topics
OpenTrons/opentrons-api pull request #14620
Opened 2024-03-11 13:04 UTC by mjhuff

Closes [EXEC-305](https://opentrons.atlassian.net/browse/EXEC-305)

# Overview

This PR adds unsubscribe flags for dynamic notification topics, e.g. "/runs/:runId". 

Now that the dust has settled around what our push notification can (and can’t) do, it’s clear that the burden of unsubscribing should be on the robot-server, specifically for dynamic topics. 

In other words, it’s ok for the app to connect to a broker and remain subscribed to topics that will never change, ex. “/maintenance_runs/current_run” (and be subscribed to those topics as long as the app is connected). Dynamic topics, such as “/runs/:runId”, should tell the app to unsubscribe however, as theoretically requiring the broker to stores these topics increases memory load on the robot server during long-lived sessions. 

This model is much easier to reason about as opposed to the component interest model that we use now. Bug surface is reduced, too.

# Test Plan
- Start up postman and start a protocol run using the desktop app's dev mode. You'll notice in the app-shell logs a lot of subscribe requests to a /run/:runId. Make note of that runId and in postman, subscribe to /runs/<that run Id>.
- After the run concludes, start another protocol run. Verify that the previous run (the run you're subscribed to in Postman), receives a message containing `unsubscribe: true`. 

# Risk assessment
low

2024-03-11 14:00 UTC, DerekMaggio reviewed
Unsubscribing from the run after it is finished makes sense to me, as that run shouldn't be receiving any updates, so it makes no sense to keep listening for events.

2024-03-11 14:00 UTC, DerekMaggio commented on robot-server/robot_server/service/notifications/publishers/runs_publisher.py
>              self._run_data_manager_polling.set()
Doing some research, there are other ways that a CancelledError can be triggered. The ones we might encounter would be: timeouts or when an asyncio task is awaiting another task that gets canceled.

To handle this, should all of the `= None` statements inside `stop_polling_engine_store()` be moved to inside the `except asyncio.CancelledError`? This way we ensure, regardless of what raises the `CancelledError`, we are fully cleaning up the RunPublisher?

2024-03-11 15:43 UTC, mjhuff commented on robot-server/robot_server/service/notifications/publishers/runs_publisher.py
>              self._run_data_manager_polling.set()
This makes a whole lot of sense. Good catch!

2024-03-11 16:43 UTC, DerekMaggio commented on robot-server/robot_server/service/notifications/publishers/runs_publisher.py
> +            await self._client.publish_async(topic=Topics.RUNS_CURRENT_COMMAND)
More on error handling.
Do we also need a catch-all `except` to handle any other errors thrown in the while loop? 
Something like, 

```python
except Exception as e:
    log.error(e)
    await self.stop_polling_engine_store()

    # Not sure if we should restart or not.
    # Seems like it could be prone to getting stuck in an infinite loop 
    # of stopping and restarting if it keeps hitting the 
    # same error over and over
    await self.begin_polling_engine_store() 
```

2024-03-11 16:56 UTC, mjhuff commented on robot-server/robot_server/service/notifications/publishers/runs_publisher.py
> +            await self._client.publish_async(topic=Topics.RUNS_CURRENT_COMMAND)
I think I'll add an Exception and just log the error. That's not a bad idea. I'm not too keen on touching this logic extensively because it's temporary. This polling logic won't exist by the next release. It's only a few ticket items down the list for me to tackle. If I can avoid breaking anything or sinking time covering weird edge-cases, I'm cool with that. 

Here's [the epic if you're interested](https://opentrons.atlassian.net/browse/EXEC-157). I just added the [PE refactor ticket to it](https://opentrons.atlassian.net/browse/EXEC-310).

2024-03-11 17:45 UTC, DerekMaggio commented on robot-server/robot_server/service/notifications/publishers/runs_publisher.py
> +            await self._client.publish_async(topic=Topics.RUNS_CURRENT_COMMAND)
Oh, perfect.
Just logging sounds perfect then. I saw the Epic but wasn't sure when it was being addressed.

2024-03-11 18:21 UTC, DerekMaggio approved these changes

2024-03-11 19:21 UTC, sfoster1 requested changes
I think we should refactor this so we don't have a function with a boolean flag that drastically alters its semantics.

2024-03-11 19:21 UTC, sfoster1 commented on robot-server/robot_server/service/json_api/response.py
> +
I do not think `NotifyUnsubscribeBody` should inherit from `NotifyRefetchBody` like this. I think these messages have different semantic meanings and having them both be in the same message kind of encourages the sort of functions I object to later in the review. _In practice_, I think that clients maybe should use the reception of a `NotifyUnsubscribe` as a cue to refetch as well as cut the connection, but I think it's a separate meaning.

2024-03-11 19:21 UTC, sfoster1 commented on robot-server/robot_server/service/notifications/notification_client.py
> +    async def publish_async(self, topic: str, should_unsubscribe: bool = False) -> None:
This function, and its synchronous cousin, are functions that do two completely different things - semantically - based on a boolean parameter. 

With the parameter `False` or unspecified, this causes a refetch advice notification; with the parameter `True`, it also causes the client to hang up forever. Those are two very different things. It's also true of the message definitions (see above).

This is something we try and avoid as much as we possibly can. I think we should avoid it here.

For now, I'd advice having a `publish_advise_unsubscribe()` method or something; maybe even change the general `publish()` to `publish_advise_refetch()`. As (if) we get more messages that can send via the notifications channel, we may want to refactor this into something that takes a message object, but hey we may end up refactoring that back into a function-like interface too eventually.

2024-03-11 19:21 UTC, sfoster1 commented on robot-server/robot_server/service/notifications/publishers/runs_publisher.py
> +    def publish_runs(self, run_id: str, should_unsubscribe: bool = False) -> None:
I think this is the same problem as the other message - does something different, for one of its subtopics, depending on a flag like this. Let's factor it into two methods.

2024-03-11 19:21 UTC, sfoster1 commented on robot-server/robot_server/service/notifications/publishers/runs_publisher.py
> +            while not self._run_data_manager_polling.is_set():
more of a nit but if we're going to do a top-level catchall handler, I think we should make another function we call out to inside the `try/except`

2024-03-11 19:21 UTC, sfoster1 commented on robot-server/robot_server/service/notifications/publishers/runs_publisher.py
> +                await asyncio.sleep(1)
we should make this a global constant tunable while we're here

2024-03-12 14:21 UTC, sfoster1 approved these changes
Thanks for making the changes, LGTM!

2024-03-12 15:12 UTC, mjhuff commented
Will merge alongside https://github.com/Opentrons/opentrons/pull/14633

2024-03-12 19:54 UTC, merged