Rss 497 extend test simulator to allow a mo m
OpenTrons/opentrons-api pull request #14628
Opened 2024-03-11 21:34 UTC by TamarZanzouri

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-03-11 21:43 UTC, sfoster1 reviewed
Looks great, maybe just make it `sim_serial_number` just to be super clear

2024-03-11 21:43 UTC, sfoster1 commented on api/src/opentrons/hardware_control/module_control.py
> +        serial_number: Optional[str] = None,
maybe call this `sim_serial_number` just to be clear that it's simulation only

2024-03-11 21:43 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/utils.py
> +    serial_number: Optional[str] = None,
here too, `sim_serial_number`

2024-03-11 21:43 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +        serial_number: Optional[str] = None,
on these too, `sim_serial_number`

2024-03-13 12:23 UTC, TamarZanzouri commented on api/src/opentrons/hardware_control/module_control.py
> +        serial_number: Optional[str] = None,
```suggestion
        sim_serial_number: Optional[str] = None,
```

2024-03-13 12:24 UTC, TamarZanzouri commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +        serial_number: Optional[str] = None,
```suggestion
        sim_serial_number: Optional[str] = None,
```

2024-03-13 12:24 UTC, TamarZanzouri commented on api/src/opentrons/hardware_control/modules/utils.py
> +    serial_number: Optional[str] = None,
```suggestion
    sim_serial_number: Optional[str] = None,
```

2024-03-19 18:56 UTC, sfoster1 requested changes
Couple things to fix about the way the module calls work but otherwise looking pretty good!

2024-03-19 18:56 UTC, sfoster1 commented on api/src/opentrons/hardware_control/simulator_setup.py
> +        for module in modules:
This will call all of the module-calls from the setup json on each attached module of the same type. For instance, in the current flex.json, this would make 4 total calls (the two for each instance) on each instance of the hardware controller module

2024-03-19 18:56 UTC, sfoster1 commented on api/src/opentrons/hardware_control/simulator_setup.py
> +        for module in modules:
I think we can fix this by grabbing the module instance that also has the right serial number

2024-03-19 18:56 UTC, sfoster1 commented on robot-server/simulators/test-flex.json
> +        "items": [
can we make this `calls` rather than `items`

2024-03-19 19:35 UTC, TamarZanzouri commented on robot-server/simulators/test-flex.json
> +        "items": [
```suggestion
        "calls": [
```

2024-03-19 19:35 UTC, TamarZanzouri commented on api/src/opentrons/hardware_control/simulator_setup.py
> +    items: List[ModuleCall] = field(default_factory=list)
```suggestion
    calls: List[ModuleCall] = field(default_factory=list)
```

2024-03-21 02:01 UTC, TamarZanzouri commented on api/src/opentrons/hardware_control/module_control.py
> +
```suggestion
```

2024-03-21 02:02 UTC, TamarZanzouri commented on api/src/opentrons/hardware_control/simulator_setup.py
> +# Name and kwargs for a module function
```suggestion
```

2024-03-21 13:28 UTC, sfoster1 approved these changes
Looks good to me, nice change!

2024-03-21 16:44 UTC, merged