givet tool sensors output options
OpenTrons/opentrons-api pull request #14673
Opened 2024-03-15 16:16 UTC by caila-marashaj

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-03-18 13:50 UTC, sfoster1 requested changes
Couple small things to change like removing prints and making a function invocation kwargs. I think I would have done the split of the CSV stuff slightly differently but I think this way will work and I'm interested to see how it turns out.

2024-03-18 13:50 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            OutputOptions.none,
The sheer number of arguments here was OK when everything was passed through with its semantic variable name, but I think once we're passing in stuff like two variants of `None` it's time to switch this call to be by keyword arg

2024-03-18 13:50 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_bindings/messages/message_definitions.py
> +class SendAccumulatedPressureDataRequest(BaseMessage):
what response message does this use?

2024-03-18 13:50 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +    print(f"Move group for probe {move_group}")
accidentally checked in?

2024-03-18 13:50 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +    print(f"Move group for probe {move_group}")
accidentally checked in?

2024-03-18 15:18 UTC, caila-marashaj commented on hardware/opentrons_hardware/firmware_bindings/messages/message_definitions.py
> +class SendAccumulatedPressureDataRequest(BaseMessage):
this prompts all of the `ReadFromSensorResponse` messages to be dumped from the array the firmware accumulates during liquid probe

2024-03-18 15:19 UTC, ryanthecoder commented on hardware/opentrons_hardware/firmware_bindings/messages/message_definitions.py
> +class SendAccumulatedPressureDataRequest(BaseMessage):
It sends the same ReadFromSensorResponse as we did before

2024-03-18 20:38 UTC, ryanthecoder commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +async def run_pass_output_to_csv(
We still need a way to gate the behavior here to see if we want to use the stream can messages to csv behavior we had before, or the new buffer-on-pipette then write we need. 
the way we run the move group runner is different with the custom firmware. 

the new custom firmware needs this logic

       messenger.add_listener(sensor_capturer, None)

        async with sensor_capturer:
            print("starting move group runner")
            positions = await sensor_runner.run(can_messenger=messenger)
            await messenger.send(
                node_id=tool,
                message=SendAccumulatedPressureDataRequest(
                    payload=SendAccumulatedPressureDataPayload(
                        sensor_id=SensorIdField(sensor_id)
                    )
                ),
            )
            await asyncio.sleep(10)
            messenger.remove_listener(sensor_capturer)
        await messenger.send(
            node_id=tool,
            message=BindSensorOutputRequest(
                payload=BindSensorOutputRequestPayload(
                    sensor=SensorTypeField(SensorType.pressure),
                    sensor_id=SensorIdField(sensor_id),
                    binding=SensorOutputBindingField(SensorOutputBinding.none),
                )
            ),
        )

and the normal firmware needs what you have here

2024-03-18 21:02 UTC, ryanthecoder commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            output_format=OutputOptions.none,
we need to hook this up one more layer to ot3_api,
and if the Output Options chosen is the one that needs the custom firm we should assert here that 
 `self._subsystem_manager.device_info[SubSystem.of_mount(mount)].revision.tertiary == "1"`

2024-03-19 15:28 UTC, ryanthecoder commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +        stop_condition=MoveStopCondition.sensor_report,
This also needs to be gated on using the custom firmware or not, the normal firmware cannot process this stop condition

2024-03-25 16:10 UTC, ryanthecoder approved these changes

2024-03-25 18:43 UTC, sfoster1 approved these changes
Okay, looks good to me!

2024-03-25 20:07 UTC, merged