fix(robot-server): ensure robot-server starts after mosquitto
OpenTrons/opentrons-api pull request #14729
Opened 2024-03-25 20:17 UTC by mjhuff

Closes [EXEC-351](https://opentrons.atlassian.net/browse/EXEC-351)

# Overview

@SyntaxColoring brought up the valid point that we should ensure mosquitto starts before the robot server, since the robot-server assumes this is true. This doesn't appear to be an issue in practice (so far), but let's fix it. 

# Risk assessment
low

2024-03-25 20:43 UTC, SyntaxColoring approved these changes
LGTM once this has been tested with [the buildroot changes.](https://github.com/Opentrons/buildroot/pull/227)

2024-03-25 20:43 UTC, SyntaxColoring commented on robot-server/opentrons-robot-server.service
> +After=mosquitto.service
Do we also want to add `Wants=mosquitto.service`?

If we omit that, and we only have `After=mosquitto.service`, the sequencing will be correct any time systemd starts both services, but systemd won't necessarily know that it has to start both services. Concretely, if you're in a state where nothing is started, and then you do `systemctl start opentrons-robot-server`, it won't also start `mosquitto.service`.

I'm not sure if this will matter in practice, since `mosquitto.service` is started by `multi-user.target`.

2024-03-25 21:12 UTC, mjhuff commented on robot-server/opentrons-robot-server.service
> +After=mosquitto.service
Hm, I don't feel strongly about it, but I could see that behavior as being potentially confusing. As long as mosquitto is guaranteed to start on boot (which I believe is always the case), then I think we're good. 

If you feel like it should be there, I don't mind adding it.

2024-03-25 22:31 UTC, sfoster1 requested changes

2024-03-25 22:31 UTC, sfoster1 commented on robot-server/opentrons-robot-server.service
> +After=mosquitto.service
Please do also add `Wants` it's good practice. systemd is a general-purpose constraint solver and so if another, tighter constraint is active this wants will have no effect, but it's always a good idea to express intent in unit files like this.

2024-03-26 13:38 UTC, sfoster1 approved these changes

2024-03-26 13:54 UTC, merged