fix(modules): use parse from packaging module
OpenTrons/opentrons-api pull request #14732
Opened 2024-03-25 22:29 UTC by caila-marashaj

Fix for https://github.com/Opentrons/opentrons/pull/14712.

We were using parse_version from `pkg_resources,` which can raise an `InvalidVersionError`, and importing `InvalidVersionError` from a separate packaging module. This imports the `parse` function from the same module the error would be raised from.

2024-03-26 13:37 UTC, sfoster1 requested changes
Let's get some tests of the version handling by forcing it to evaluate some invalid versions. This was a very weird issue that happened because of packaging minutia lol

2024-03-27 15:36 UTC, DerekMaggio approved these changes
LGTM!

2024-03-27 15:36 UTC, DerekMaggio commented on api/src/opentrons/hardware_control/modules/mod_abc.py
> +def parse_fw_version(version: str) -> Version:
Was wondering what the difference is when using parse as opposed to instantiating a Version object directly. 
The answer is nothing, absolutely nothing. 
https://github.com/pypa/packaging/blob/main/src/packaging/version.py#L47-L56

2024-03-27 19:36 UTC, caila-marashaj commented on api/src/opentrons/hardware_control/modules/mod_abc.py
> +def parse_fw_version(version: str) -> Version:
yeah, I was mostly using it here to detect a bad version name so we can default it to 0.0.0

2024-03-27 20:25 UTC, DerekMaggio commented on api/src/opentrons/hardware_control/modules/mod_abc.py
> +def parse_fw_version(version: str) -> Version:
No, your function is totally good. What I mean is all `packaging.version.parse(string_version)` does is call `Version(string_version)` under the hood. Ignore me lol

2024-03-28 17:00 UTC, sfoster1 requested changes
The test looks good but it should really be in like `api/tests/opentrons/hardware_control/`, not all the way over in the robot server

2024-03-28 17:00 UTC, sfoster1 commented on robot-server/tests/modules/test_router.py
> +async def test_catch_invalid_fw_version(
this should be next to the actual code it's testing

2024-04-01 15:31 UTC, sfoster1 approved these changes
remove the rest of the diff from the robot server and we're good, nice!

2024-04-01 16:02 UTC, merged