feat(api): Pause-on-error for Python protocols
OpenTrons/opentrons-api pull request #14753
Opened 2024-03-28 20:24 UTC by SyntaxColoring

# Overview

Closes EXEC-346.

# Test Plan

To do.

# Changelog

To do.

# Review requests

To do.

# Risk assessment

To do.

2024-03-29 14:30 UTC, DerekMaggio commented
@SyntaxColoring, https://github.com/Opentrons/opentrons/pull/14748 contains some error recovery protocols if you need any test cases.

2024-04-01 14:25 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +    ) -> None:
I'm open to ideas on better names for this.

Or maybe make it a `wait_for_recovery: bool` argument on the existing `add_and_execute()` method.

2024-04-01 17:20 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/commands.py
> +    def get_command_recovery_complete(self, command_id: str) -> bool:
can we call this like `get_command_recovery_not_needed()` or something? as your docstring calls out this will definitely return true if even there was no recovery to complete, so let's just avoid the confusion

2024-04-01 17:20 UTC, sfoster1 commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        # FIX BEFORE MERGE?: If the pickUpTip fails, the tip tracker (which is sort of
as discussed in person - I think we are going to have to determine this sort of stuff command by command. we should make our decision based on "what's the most likely physical cause", and then handle the possibility of surprising states by being conservative and defensive about querying PE state explicitly rather than explicitly or implicitly caching.

2024-04-01 17:20 UTC, sfoster1 commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        # FIX BEFORE MERGE: We should probably only set_last_location() if the
I disagree - I think there are three answers each of which is honestly reasonable, but one which is the best (and also hardest). As a preamble, we should probably push last-location down to the engine.

1. the best and hardest is, base the decision of setting last location on when the error occurred (during which action) and what the error is. For instance, if you got a stall while moving to the tiprack, we should clear the last location since position is now indeterminate; but if we failed our tip-state consistency check after the pickup, we should set the last location to the rack.
2. the simplest and most robust is, always clear the last location on any error
3. and a slightly more optimistic version is to always set it on any error since the most likely causes of failure will in fact leave the gantry in the specified location

2024-04-02 17:44 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +                # this action is only legal if the command is running, not queued.
This is my fault; in #14726, I neglected to account for what this `estop()` method was doing. I'm going to have to fix this in another PR.

2024-04-02 17:48 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +                # this action is only legal if the command is running, not queued.
I think a lot of this `estop()` method is due for a rethink. Like, I don't really get why it needs to be so different from `stop()`, and why it needs to be messing with things like `FailCommandAction`s itself.

2024-04-03 16:08 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/commands.py
> +    def get_command_recovery_complete(self, command_id: str) -> bool:
Replaced with the negation, `get_recovery_in_progress_for_command()`.

2024-04-08 14:44 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        # FIX BEFORE MERGE: We should probably only set_last_location() if the
After looking at this closer, I think it's appropriate to call this `set_last_location()` unconditionally. See this comment:

https://github.com/Opentrons/opentrons/blob/6b79625f761910a61eca33dae2c9571bd88ef3e5/api/src/opentrons/protocol_api/core/engine/instrument.py#L412-L423

2024-04-08 16:43 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/clients/transports.py
> +        # We might access these from different threads,
Nice

2024-04-08 16:46 UTC, sfoster1 requested changes
This looks good overall, but a couple points:
- I'm a bit concerned about the "last command to fail" logic in the command store. Can we instead save the command id when it fails recoverably and we enter `AWAITING_RECOVERY` and make that state more explicit?
- Something feels slightly off about the checks in `ProtocolEngine.add_and_execute_command_wait_for_recovery` since they check two different pieces of state in tight sequence

2024-04-08 16:46 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/clients/transports.py
> +            raise ProtocolCommandFailedError(
let's make this its own unique exception type and code so that we can programmatically differentiate it from other errors

2024-04-08 16:46 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +            # TODO(mm, 2024-04-02): Is it possible for the next queued command to
sure, this could be a maintenance run

2024-04-08 16:46 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/commands.py
> +        command_is_most_recent_to_fail = (
this is a little gross to me, could we save the command we're currently recovering from explicitly? like, what happens if a fixit command fails, wouldn't it instantly make this `False`?

2024-04-08 16:46 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/tips.py
> +            # TODO(mm, 2024-04-01): We're logically removing the tip from the tip rack,
It is not really inconsistent and confusing once we're in the world of being aware of possible errors. The tip is not usable; the tip is also not on the pipette. We may want to do various error handling cases where we treat the pipette as if it has a tip, and we'll need the data then; we also may want to do cases where the pipette does not have a tip. We have to be able to handle that, and I think that this is a great way to implement it.

Part of what we get out of the separated states like this _is_ that separation, and we're taking advantage of it here, and I'm glad.

2024-04-08 16:46 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +        await self._state_store.wait_for_not(
it kind of feels like we want to gate this on a synchronous call to whether we're now in recovery for the command, but this in general feels a little race condition-y because of the separation between command state and run state. Specifically,
- `wait_for_command` returns on the asyncio spin after a `FailCommandAction` or a `SucceedCommandAction` for this command (we can neglect the queued-and-stopping part for now)
- but the `get_recovery_in_progress_for_command` predicate is based on the queue status being awaiting-recovery

Do we guarantee mechanically that the queue status will be set before the asyncio spin after the command terminal action is dispatched? Are we sure this won't occasionally race and return early?

2024-04-08 16:59 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/execution/command_executor.py
> +                    running_command=running_command,
I guess I am wondering why we need this in the action? dont we have the failed command stored in PE already?

2024-04-08 17:59 UTC, TamarZanzouri reviewed
overall looks good, added a question and a bit confused about the `wait_for_not` although I get what its doing but the logic around it is a bit confusing to me. besides that looks great!

2024-04-08 18:38 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +        await self._state_store.wait_for_not(
Yes, if I understand your concern correctly:

When `await self.wait_for_command(command_id=queued_command.id)` returns, we are guaranteed that the action that finalized the command has already been fully processed, and that `get_recovery_in_progress_for_command()` will see its results on the state.

When we handle an action, we [send it to each of the substores in a loop](https://github.com/Opentrons/opentrons/blob/bd14851425538ebdd10f26dc773a0f898ea59c31/api/src/opentrons/protocol_engine/state/state.py#L208-L211). Only after that's done do we [notify subscribers](https://github.com/Opentrons/opentrons/blob/bd14851425538ebdd10f26dc773a0f898ea59c31/api/src/opentrons/protocol_engine/state/state.py#L355-L357) like this one.

2024-04-08 20:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/command_executor.py
> +                    running_command=running_command,
It's a hack, we probably don't need it. See this comment:

https://github.com/Opentrons/opentrons/blob/bd14851425538ebdd10f26dc773a0f898ea59c31/api/src/opentrons/protocol_engine/actions/actions.py#L177-L180

2024-04-08 20:18 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/commands.py
> +        command_is_most_recent_to_fail = (
Changed in a880096260.

2024-04-08 20:29 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/commands.py
> +
Adding this as an orthogonal attribute is quick and dirty. Ideally, this ID would not exist at all when `QueueStatus` is anything other than `AWAITING_RECOVERY`. We could do that by retructuring this state so it's closer to a union of dataclasses instead of a dataclass of unions.

2024-04-08 20:30 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +            # TODO(mm, 2024-04-02): Is it possible for the next queued command to
Ugh, yep, good call.

2024-04-08 21:25 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/clients/transports.py
> +            raise ProtocolCommandFailedError(
187693a49e975fc986f117e677fe19e75ebb8649

2024-04-08 21:43 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/tips.py
> +            # TODO(mm, 2024-04-01): We're logically removing the tip from the tip rack,
Discussed in-person:

I think this is inconsistent and confusing today, but it will be much less so if we treated the different tip pickup failure modes (tip consumed vs. not; tip attached vs. not, ...) as distinct, explicit `pickUpTip` results models.

For now, replacing the to-do comment with a neutral note.

2024-04-09 15:39 UTC, sfoster1 approved these changes
Looks great, thank you for the changes!

2024-04-09 15:58 UTC, merged