Exec 352 do not enqueue json protocol commands
OpenTrons/opentrons-api pull request #14759
Opened 2024-03-29 20:20 UTC by TamarZanzouri

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-03-29 20:57 UTC, sfoster1 approved these changes
Looks great to me! Nice work.

2024-04-01 15:21 UTC, mjhuff commented
After pushing all the backend code and restarting the bot, it appears to be failing protocol analysis:

<img width="1021" alt="Screenshot 2024-04-01 at 11 19 45 AM" src="https://github.com/Opentrons/opentrons/assets/64858653/dda07305-2142-4659-adc3-050e4c9dbf8a">

2024-04-01 15:27 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/runs/test_json_v6_protocol_run.tavern.yaml
> GET run /commands will not return the full list of commands if the run did not start - its a change we are doing to make json protocols run like python protocols. are we ok with this?

Is the long-term plan for JSON protocols to not have an HTTP-visible queue anymore, or is this just temporary until some future PR adds it back?

2024-04-01 15:27 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_runner/test_protocol_runner.py
> +        task_queue.set_run_func(func=json_runner_subject._add_command_and_execute),
To avoid testing internal methods, I think we want to do something like this:

https://github.com/Opentrons/opentrons/blob/459f14d5f78d064991ba6a195c1de55d750f12e5/api/tests/opentrons/protocol_runner/test_protocol_runner.py#L481-L504

2024-04-01 15:27 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/protocol_runner.py
> +
Ignoring queued commands for a moment, this doesn't look like it matches the existing implementation based on `QueueWorker`+`get_next_to_execute()`. This does not have:

* Special handling of `RunStoppedError` to `break` instead of raising an error
* Yielding to the event loop on each command
* Pausing on recoverable errors (added in #14646)
* Prioritization of `"intent": "setup"` commands
    * But according to the tests, this is still working, somehow?

Do we need to handle those things, or are they already handled elsewhere in some way that I'm missing?

2024-04-01 15:47 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/protocol_runner.py
> -            await _yield()
Are we intentionally removing this yield?

Actually, wait, do we still need to `.append()` one-by-one? Would it work to just do `self._queued_commands = commands`?

2024-04-01 15:50 UTC, mjhuff approved these changes
Disregard my terrifying comments, tested and this does work. App & ODD don't appear to be affected as well!

2024-04-01 16:22 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/protocol_runner.py
> -            await _yield()
woops :-)

2024-04-01 16:23 UTC, TamarZanzouri commented on robot-server/tests/integration/http_api/runs/test_json_v6_protocol_run.tavern.yaml
The goal is to match python protocols so yes, we will need to document this change

2024-04-01 17:42 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/runs/test_json_v6_protocol_run.tavern.yaml
👍 Discussed with @sfoster1 in-person. Recap:

The downside of this change is that it makes it more difficult for a simple client, uploading simple JSON protocols, to render a run log.

The upsides of this change are that it brings uniformity with Python protocols, and that it *forces* clients to acknowledge the possibility that the queue will change—which, with fixup commands and retries, it will more often.

We'll make this change.

2024-04-01 19:13 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/protocol_runner.py
> +
This will be fixed in a follow up pr. looking into the other comments
> Prioritization of "intent": "setup" commands
But according to the tests, this is still working, somehow?

2024-04-01 21:20 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/protocol_runner.py
> +
> I do not think we need this bc add_and_execute_command is async and add_command is synch but I will test this to make sure we hare not blocking anything.

We do need it, unfortunately, for the reasons described in this comment in the old implementation:

https://github.com/Opentrons/opentrons/blob/93226572668e81d111e49ea99b9a7663b3effb63/api/src/opentrons/protocol_engine/execution/queue_worker.py#L80-L83

. [Unlike JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#:~:text=Even%20when%20the%20used%20promise%20is%20already%20fulfilled%2C%20the%20async%20function%27s%20execution%20still%20pauses%20until%20the%20next%20tick.), Python's `await` isn't guaranteed to yield to the event loop.

2024-04-02 01:29 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/protocol_runner.py
> +
I see. I tested this by adding a background task that prints, then `time.sleep(3)` and was able to see the printing sequence while executing the commands. so this test is not efficient? @SyntaxColoring @sfoster1

2024-04-02 01:39 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_runner/test_protocol_runner.py
> +        task_queue.set_run_func(func=json_runner_subject._add_command_and_execute),
So much better!

2024-04-02 14:05 UTC, sfoster1 requested changes

2024-04-02 14:05 UTC, sfoster1 commented on api/src/opentrons/protocol_runner/protocol_runner.py
> +        print(self._queued_commands)
accidentally committed?

2024-04-02 14:14 UTC, sfoster1 commented on api/src/opentrons/protocol_runner/protocol_runner.py
> +
I don't think we need the await because, crucially, what we're talking about here is in a different async stack than the lines you linked to @SyntaxColoring . This PR does _not_ replace or even touch the execution queue worker.

The way the engine works, just so we agree, is that there's fundamentally at least three async stacks: the execution stack, which is controlled by the execution queue linked above and owned by the engine, and `await`s command implementations; the runner task-queue stack, which is what is changed here and owned by the runner, and (now) dispatches commands via `add_and_execute_command`; and the stack that calls the runner's primary interface, which is I think owned by the server's run data manager.

The execution stack, as you mention, definitely needs to have an explicit yield in case it's running a bunch of commands that have no yield points... so it does, it's in what you linked above, which is still what's used and which this PR does not touch.

The server stack does not need to have an explicit yield as long as the runner uses the task queue, since if the runner uses a task queue it `await self._task_queue.join()`, which awaits a future, which is a yield point.

The task queue stack (which is what's changed here) does not need to have an explicit yield if it's using something that eventually uses `wait_for` because `wait_for` `await (asyncio.Event())`s, which is a sync point.

2024-04-02 14:50 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/protocol_runner.py
> +
Ah, that makes sense. I missed that this was still going through the `QueueWorker` under the hood.

2024-04-02 14:58 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/protocol_runner.py
> +
Which means I was also wrong about this:

> Special handling of RunStoppedError to break instead of raising an error

Per the documentation of `ProtocolEngine.add_and_execute()`, if the run is stopped, it actually *doesn't* raise a `RunStoppedError`—it returns the command still `queued`.

2024-04-02 16:50 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/protocol_runner.py
> +        print(self._queued_commands)
I left this for my testing :-) still working on adding tests

2024-04-02 16:53 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/protocol_runner.py
> +
> Which means I was also wrong about this:
I had a feeling but I wanted to prove that through a test I am trying to add :-)

2024-04-04 02:14 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/protocol_runner.py
> +
@SyntaxColoring I added e2e tests to prove that python and json protocols now behave the same

2024-04-04 13:34 UTC, sfoster1 approved these changes
Looks excellent!

2024-04-04 14:46 UTC, SyntaxColoring approved these changes
This looks good to me to merge, thanks. Here are some comments on the tests that we've talked about in Slack.

2024-04-04 14:46 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/runs/test_play_stop_papi.tavern.yaml
> +      status_code: 201
We can't be sure where in the protocol this `stop` action will come in. For example, this might stop the run before or after the initial home command. The reason this matters is that we're asserting a specific sequence of commands in the "Get run commands" stage, down below, so this will be flaky depending on timing.

Ideally, we would wait for a specific command (a `waitForResume` or long-running `waitForDuration`) to be active before issuing the `stop` action. This might be easier to do in Python than in Tavern.

2024-04-04 14:46 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/runs/test_play_stop_papi.tavern.yaml
> +    delay_after: 0.2
* I don't think this `delay_after` is doing anything, is it? You might have meant `delay_before`—but even then, the stage above has already made sure that the run is stopped.

2024-04-04 15:46 UTC, SyntaxColoring approved these changes
Nice, TY!

2024-04-04 15:46 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/runs/test_play_stop_papi.tavern.yaml
> +  - name: Wait for the run to complete
```suggestion
  - name: Wait for the command to run
```

2024-04-04 16:09 UTC, SyntaxColoring commented
Oh, and I renamed this from `chore: ...` to `feat: ...` because it's a deliberate change in the HTTP API, and we'll have to remember to describe it in the release notes.

2024-04-04 17:29 UTC, merged