refactor(robot-server): runsPublisher utilizes PublisherNotifier
OpenTrons/opentrons-api pull request #14777
Opened 2024-04-02 14:57 UTC by mjhuff

Closes [EXEC-310](https://opentrons.atlassian.net/browse/EXEC-310)

# Overview

Removes polling logic from `RunsPublisher`, making use of the new protocol engine event bubbling via `PublisherNotifier`.

# Test Plan
- General smoke test of running a protocol is sufficient. Verify that notifications still work.

# Risk assessment
low

2024-04-03 14:41 UTC, sfoster1 requested changes
I think a cleanup thing app side and a small refactor server side are needed but as a whole looks great!

2024-04-03 14:41 UTC, sfoster1 commented on app/src/organisms/RunTimeControl/hooks.ts
> +      !([RUN_STATUS_FAILED, RUN_STATUS_SUCCEEDED] as RunStatus[]).includes(
`RUN_STATUS_STOPPED` also - `STOPPED` is the terminal state for a protocol that was stopped by user action, e.g. cancelled.

2024-04-03 14:41 UTC, sfoster1 commented on robot-server/robot_server/service/notifications/publishers/runs_publisher.py
> +        self._run_id: Optional[str] = None
recommend binding these into an object, a dataclass maybe, that can be initialized or not as a whole. for instance
```
@dataclass
class RunHooks:
    run_id: str
    get_current_command: Callable[[str], Optional[CurrentCommand]]
    get_state_summary: Callable[[str], Optional[StateSummary]]

class RunsPublisher:
    def __init__(...):
        self._run_hooks: Optional[RunHooks] = None
        ...
    ...
    async def initialize(...):
        self._run_hooks = RunHooks(run_id, ...)
```

This means you don't need quite as many assert statements, and you get to express the semantics that you either have all of those three or none of them. 

You could do a similar thing with the the previous-element caches if you want.

2024-04-03 14:43 UTC, mjhuff commented on robot-server/robot_server/service/notifications/publishers/runs_publisher.py
> +        self._run_id: Optional[str] = None
Good idea, thanks

2024-04-03 14:44 UTC, mjhuff commented on app/src/organisms/RunTimeControl/hooks.ts
> +      !([RUN_STATUS_FAILED, RUN_STATUS_SUCCEEDED] as RunStatus[]).includes(
Oh duh, good catch

2024-04-05 15:27 UTC, sfoster1 approved these changes
Looks good to me, nice!

2024-04-05 15:30 UTC, merged