feat(hardware): add csv file logging capability to capacitive_probe method
OpenTrons/opentrons-api pull request #14785
Opened 2024-04-03 03:20 UTC by pmoegenburg

# Overview

This PR adds csv file logging capability to the capacitive_probe ot3api method.

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-04-12 17:24 UTC, sfoster1 requested changes
Looking good but definitely some stuff to change.

2024-04-12 17:24 UTC, sfoster1 commented on .gitignore
> +hardware/.npm-cache/_update-notifier-last-checked
```suggestion
.npm-cache/
```

2024-04-12 17:24 UTC, sfoster1 commented on .gitignore
> +hardware/.npm-cache/_cacache/content-v2/sha512/e0/f2/0b78b807658be0f5790f7dfcb48708e26a9ed3a9632250264215afa1e5a04fee513f603e12351fcbd1e18e9c6d553cac9858275e1b00cb6d3a049ab6a435
and remove these

2024-04-12 17:24 UTC, sfoster1 commented on api/src/opentrons/config/defaults_ot3.py
> +            output_option=OutputOptions.stream_to_csv,
This should absolutely not be the default. This will set every single calibration pass on every single machine to stream data to a csv. This is not something we should do in production.

2024-04-12 17:24 UTC, sfoster1 commented on api/src/opentrons/config/defaults_ot3.py
> +            data_file="/var/capacitive_sensor_data.csv",
see above

2024-04-12 17:24 UTC, sfoster1 commented on api/src/opentrons/config/types.py
> +# str enum so it can be json serializable
this is not a str enum. remove the comment or make it one

2024-04-12 17:24 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            output_option.value & OutputOptions.sync_buffer_to_csv.value
bitwise checks are only really meaningful if the enum is an `IntFlag` enum, and `OutputOptions` appears to just be an `int` enum

2024-04-12 17:24 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +    async def capacitive_probe(  # careful with changes, this is what calibration uses
accidental comment?

2024-04-12 17:24 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +                sensor_type=SensorTypeField(SensorType.pressure),
this function's getting to be a lot, maybe let's split it up into three subfunctions depending on the `step.move_type`?

2024-04-12 17:24 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +    stop_condition: MoveStopCondition = MoveStopCondition.sync_line,  # does this need to be pressure_sync_line? Same for elsewhere
accidental comment?

2024-04-12 17:24 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +    ]  # include gripper firmware in capacitive data collection?!
accidental pass step? The answer to the comment is yes probably

2024-04-12 17:24 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +    ]  # what do sync and report do?
accidental comment?

2024-04-12 17:24 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +    ):  # does this do try as __enter__ and finally as __exit__? Yes!
accidental comment?

2024-04-12 17:24 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +        )  # bind_output seems to trigger continuous responses from firmware
accidental comment?

2024-04-12 17:24 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +        print("starting move group runner")
accidental print?

2024-04-12 17:24 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +    ):  # does this do try as __enter__ and finally as __exit__? Yes!
accidental comment?

2024-04-12 17:24 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tool_sensors.py
> +        )  # bind_output seems to trigger continuous responses from firmware
accidental comment?

2024-06-03 17:49 UTC, DerekMaggio commented on api/src/opentrons/config/types.py
> +    sync_only = 0x8
Can you provide some comments on what each of the options does please? 
Like when you stream_to_csv, do we still send to the CAN bus?

2024-06-04 19:33 UTC, ryanthecoder commented on api/src/opentrons/config/types.py
> +    stream_to_csv = 0x1         # compile sensor data stream into a csv file (not working), in addition to can_bus_only behavior
When you say not working, is that just for capacitive? this was working for pressure so it should work for the cap sensor since you're re-using the same code

2024-06-04 20:55 UTC, sfoster1 approved these changes
Looks good to me, nice!

2024-06-05 14:16 UTC, ryanthecoder approved these changes
LGTM

2024-06-05 19:50 UTC, merged