chore: create performance metrics project
OpenTrons/opentrons-api pull request #14806
Opened 2024-04-04 19:14 UTC by DerekMaggio

# Overview

Basic setup of Performance Metrics project

2024-04-04 21:08 UTC, sfoster1 requested changes
Let's keep the tooling we use in monorepo python projects consistent, with flake8, mypy, black, and so on at the same versions as the other projects. This eases everybody's ability to context switch.

2024-04-05 13:28 UTC, sfoster1 requested changes

2024-04-05 13:28 UTC, sfoster1 commented on performance-metrics/pyproject.toml
> +[tool.ruff]
need to remove this one too - we're still using `setup.py`

2024-04-05 14:58 UTC, DerekMaggio commented on performance-metrics/pyproject.toml
> +[tool.ruff]
https://github.com/Opentrons/opentrons/pull/14806/commits/71cb58415df045e67a42063338f3080048836b43 should fix it

2024-04-08 16:30 UTC, sfoster1 approved these changes
lgtm!

2024-04-08 16:31 UTC, merged