feat(shared-data, api): add uiMaxFlowRate key to pipette definitions
OpenTrons/opentrons-api pull request #14859
Opened 2024-04-10 18:26 UTC by jerader

closes AUTH-328

# Overview

This PR add max flow rate values to each GEN2 and GEN3 pipette model definition to be used for FE applications, based off of the calculations [here](https://github.com/Opentrons/opentrons/blob/chore-calculate-max-flow-rate-per-pipette-model/hardware-testing/hardware_testing/scripts/calculate_plunger_flow_rates.py )

Rather than having a max flow rate for every pipette's supported tip's volume for aspirate and dispense, we have only 1 max flow rate for every pipette's supported tip that is. That value is based off of the lowest volume minus 2% to account for safety. 

For example:
`p1000_single_v3.6` has a `minVolume` of 5uL. The `t50` tips has a max flow rate at volume 5uL of `801.3`. So the `uiMaxFlowRate` value is 98% of that which is `785.2` 

The new key in the definition is called `uiMaxFlowRate` because it is limited to the lowest volume's max flow rate, which will be used for FE applications only (Quick transfer and PD)

🔈  Additionally, the `lowVolumeDefault` default flow rates for `aspirate`, `dispense`, and `blowout` have been changed to match the `uiMaxFlowRate`. This DOES NOT result in a physical change behavior and the change is needed for ui purposes.

# Test Plan

Review the additions to the definitions
Review the pytest

# Changelog

- add `uiMaxFlowRate` key to each pipette liquid definitions's supported tips
- change the `lowVolumeDefault` flowrates to match the `uiMaxFlowRate`
- add to JS type and add to schema
- make a pytest that asserts that the ui max flow rate value is less than all the max flow rate values for aspirate and dispense for that pipette's supported tip
- create new `ul_per_mm` python file and copy over the `piecewise_volume_conversion` fn from the api hardware directory, removing the old version
# Review requests

see test plan

# Risk assessment

low-ish, nothing is using these new values yet

2024-04-10 19:38 UTC, jerader commented
Spoke with @sanni-t , I am going to add the max values to the pipette definitions in a `maxFlowRate` key and will modify my util to just read the information from the definitions.

2024-04-10 21:17 UTC, koji commented on shared-data/pipette/definitions/2/liquid/eight_channel/p1000/default/3_3.json
> +        "9": 898,
question

898 instead of `898.0`, is this intend?

2024-04-10 21:20 UTC, jerader commented on shared-data/pipette/definitions/2/liquid/eight_channel/p1000/default/3_3.json
> +        "9": 898,
these max flow rates are all a result from the equation [here](https://github.com/Opentrons/opentrons/blob/chore-calculate-max-flow-rate-per-pipette-model/hardware-testing/hardware_testing/scripts/calculate_plunger_flow_rates.py)! We are rounding to 
1 decimal value if any decimal values exist. I think if there are no decimals values, it won't show it. Since this data is backend, i think for the frontend, we can expose another decimal value to make everything match.

2024-04-10 21:24 UTC, koji commented on shared-data/js/__tests__/pipettes.test.ts
> +    const mockMaxFlowRate: Record<string, number> = {
maybe create a fixture?

2024-04-16 14:00 UTC, sfoster1 requested changes
Looks great overall, but a couple things
- Definitely need to call out the actual `lowVolumeDefault` changes in the description a bit more; as we discussed, they're fine because they won't result in actual changed physical behavior, but they should be highlighted
- This is less significant of an opinion - it could also be a followup - but we need to switch the python over to importing `ul_per_mm` from the new location at some point

2024-04-16 14:00 UTC, sfoster1 commented on shared-data/pipette/definitions/2/general/ninety_six_channel/p1000/3_6.json
> +      "speed": 10.0,
this is going to cause issues when merged and is because this is based on an old edge - may want to merge recent edge into this

2024-04-16 14:00 UTC, sfoster1 commented on shared-data/pipette/definitions/2/liquid/eight_channel/p50/lowVolumeDefault/3_4.json
> +        "default": 32.6,
Let's call this out in the PR description and thus the eventual commit message a little  more please

2024-04-16 14:00 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/pipette/ul_per_mm.py
> +from typing import List, Tuple
We prooobably should change the code that imports this to import it from here also

2024-04-16 14:10 UTC, jerader commented on shared-data/pipette/definitions/2/general/ninety_six_channel/p1000/3_6.json
> +      "speed": 10.0,
oops i did not catch this when i merged edge in, thank you!

2024-04-16 15:23 UTC, sanni-t commented on shared-data/pipette/schemas/2/pipetteLiquidPropertiesSchema.json
> +                "type": "string",
```suggestion
                "type": "number",
```
or probably better is to use a reference to the existing `positiveNumber`

2024-04-17 18:12 UTC, sfoster1 approved these changes
Looks good to me!

2024-04-17 18:34 UTC, merged