Exec 285 add fixit commands
OpenTrons/opentrons-api pull request #14908
Opened 2024-04-15 20:25 UTC by TamarZanzouri

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-04-17 20:43 UTC, sfoster1 requested changes
Looks very good structurally, but I think we want a couple defensive programming enhancements and we should enforce that failed command ids only exist for fixits

2024-04-17 20:43 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/hash_command_params.py
> +    # We avoid Python's built-in hash() function because it's not stable across
IMO we should defensively say 
```
if create.intent != CommandIntent.PROTOCOL:
     return None
```

2024-04-17 20:43 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +        self, request: commands.CommandCreate, failed_command_id: Optional[str] = None
we should probably document and verify with an assert that `failed_command_id` is only provided if the intent is `FIXIT`

2024-04-17 20:43 UTC, sfoster1 commented on robot-server/robot_server/runs/router/commands_router.py
>          raise CommandNotAllowed.from_exc(e).as_error(status.HTTP_409_CONFLICT)
should add explicit handling and `400` errors if this was a non-fixit command that specified a failed command id

2024-04-18 14:53 UTC, SyntaxColoring reviewed
Looks good so far!

2024-04-18 14:53 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/commands.py
> +            self._state.command_history.clear_fixit_queue()
Given that you can't `resume-from-recovery` while there are fixit commands in the queue, does this do anything?

2024-04-18 14:53 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/commands.py
>          if self._state.queue_status != QueueStatus.PAUSED and next_setup_cmd:
Not directly related to your changes, but is this still correct? If we're in `AWAITING_RECOVERY`, and there is no fixit command, but there is a setup command, we'll run the setup command?

2024-04-18 14:53 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/commands.py
> +                )
TY!

2024-04-18 14:53 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_engine/state/test_command_history.py
> +
Can we avoid calling private methods in any new tests in this file? The existing tests that are doing that were grandfathered in from the old `CommandStore` tests.

2024-04-18 14:53 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/commands_router.py
> +    ),
Curious why we want a dedicated server-supported field for this instead of making it a `notes` entry.

2024-04-18 19:44 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/commands.py
> +            self._state.command_history.clear_fixit_queue()
probably not but this is just to be on the safe side.

2024-04-18 19:45 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/commands.py
>          if self._state.queue_status != QueueStatus.PAUSED and next_setup_cmd:
should only run fixit commands. I will fix this

2024-04-19 19:27 UTC, sfoster1 requested changes
Looks really good except for the one sneaky little `print`!

2024-04-19 19:27 UTC, sfoster1 commented on robot-server/robot_server/runs/router/commands_router.py
> +    print(failed_command_id)
remove before committing

2024-04-19 19:27 UTC, sfoster1 commented on robot-server/robot_server/runs/router/commands_router.py
> +    ),
`notes` are ideally not things machines take action on

2024-04-19 20:49 UTC, TamarZanzouri commented on api/tests/opentrons/protocol_engine/test_protocol_engine.py
> +    print(result)
```suggestion
```

2024-04-19 20:49 UTC, TamarZanzouri commented on robot-server/robot_server/runs/router/commands_router.py
> +    print(failed_command_id)
```suggestion
```

2024-04-19 20:57 UTC, sfoster1 approved these changes
Looks good to me!

2024-04-22 16:41 UTC, SyntaxColoring reviewed
A few small things. And I think CI tests are failing, maybe because of the `raise` in `pickUpTip`. Otherwise, looks great, thanks!

2024-04-22 16:41 UTC, SyntaxColoring commented on shared-data/fixture/schemas/1.json
Is this file some kind of merge or rebase error?

2024-04-22 16:41 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/command.py
> +    )
This should be camel-case `failedCommandId`, right?

2024-04-22 16:41 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/pick_up_tip.py
> +
Reminder to remove this before merging.

2024-04-22 17:02 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/command.py
> +    )
nice catch

2024-04-22 18:07 UTC, SyntaxColoring approved these changes
LGTM if CI passes, thank you!

2024-04-22 19:44 UTC, merged