Getting performance metrics to work on robot
OpenTrons/opentrons-api pull request #15008
Opened 2024-04-25 15:10 UTC by DerekMaggio

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-04-26 15:51 UTC, y3rsh commented
As is high risk, l would like this to not merge to edge until 5/2 post code freeze for 7.3.0.
If there is a counterargument that this will in some way enhance the 7.3.0 release please let me know.

2024-04-26 15:53 UTC, DerekMaggio commented
Nope, will mark do not merge.

2024-04-26 18:12 UTC, sfoster1 requested changes
Okay, I see what we're going for here and accept that you want to change it soon, but I really think we should start as we mean to go on: just don't have `store_each`, and have the analysis tracker explicitly store once in a `finally` after the analysis ends. `store_each` would mean a disk hit after every tracked function call and totally kill perf, and I think it's equally clear to just have it at the end of the analyze call.

2024-04-26 19:04 UTC, SyntaxColoring commented on performance-metrics/src/performance_metrics/robot_context_tracker.py
> +        self._store_each = store_each
Could we have a docstring somewhere for what `store_each` does? It's not clear to me when you'd want it to be `False` vs. `True`.

2024-04-26 19:04 UTC, SyntaxColoring commented on performance-metrics/Makefile
> +add-performance-metrics-ff:
Nitpick, feel free to ignore: I might call this `set-performance-metrics-ff` or `enable-performance-metrics-ff`.

2024-04-26 19:04 UTC, SyntaxColoring commented on performance-metrics/Makefile
> +	ssh -i $(ssh_key) $(ssh_opts) root@$(host) "touch /data/robot.env && \
Would it work to implement this via a `curl` request like we do for `set-debug-log-level`?

2024-04-26 19:06 UTC, DerekMaggio commented on performance-metrics/Makefile
> +	ssh -i $(ssh_key) $(ssh_opts) root@$(host) "touch /data/robot.env && \
It wasn't working. I think it is because so much of this is ran at import time, I couldn't set the ff to true before the robot-server started. 

I can look into this more if you want

2024-04-26 19:06 UTC, DerekMaggio commented on performance-metrics/src/performance_metrics/robot_context_tracker.py
> +        self._store_each = store_each
Currently working on removing this.

2024-04-26 19:24 UTC, SyntaxColoring commented on robot-server/tests/protocols/test_protocol_analyzer.py
> +context_tracker._should_track = True  # type: ignore[attr-defined]
Okay, so as far as I can tell:

* Our performance tracking code is global, for the same reason that logging is global: ease of access.
* Our performance tracking code has import-time logic, for performance reasons. (To avoid having to check `if running_on_robot: ...` every time it's called.)
* As we're beginning to see here, both of the above are going to make it very annoying and icky to test that the code under measurement calls the performance tracking code correctly, 

To "fix" this, I would support just not having unit tests like this. We just won't check that the code under measurement emits metrics. By analogy, we're also okay with not checking that the code under test emits logs. It's not worthwhile to test because it's noncritical and also not error-prone.

2024-04-26 19:29 UTC, SyntaxColoring commented on performance-metrics/Makefile
> +	ssh -i $(ssh_key) $(ssh_opts) root@$(host) "touch /data/robot.env && \
Oh, that makes sense, thanks. No need to keep looking.

2024-06-03 13:47 UTC, DerekMaggio commented
Closing in favor of, https://github.com/Opentrons/opentrons/pull/15289

2024-06-03 13:47 UTC, closed without merging