fix(api): pass the calibrated jaw max offset value when we resetting instrument
OpenTrons/opentrons-api pull request #15032
Opened 2024-04-26 21:33 UTC by ahiuchingau

# Overview
We really only need to calibrate the gripper's max jaw offset once every time we attach a new gripper. This means that when we call `ot3api.reset()`, which is pretty often because it's called by `ot3api.stop()`, we should just reuse the calibrated value so we don't see the jaw opening and closing all the time.

2024-04-26 21:42 UTC, sfoster1 requested changes
Okay but let's get some tests please.

2024-04-26 23:29 UTC, vegano1 commented on api/src/opentrons/hardware_control/instruments/ot3/gripper.py
> +                    if attached_instr.has_jaw_width_calibration
`has_jaw_width_calibration` just checks if `_jaw_max_offset` is not None
so we can just pass in `_jaw_max_offset` directly without checking.

2024-04-26 23:30 UTC, vegano1 commented on api/src/opentrons/hardware_control/instruments/ot3/gripper_handler.py
> +            if og_gripper.has_jaw_width_calibration
same as above

2024-04-29 19:18 UTC, sfoster1 approved these changes
lgtm!

2024-04-29 21:15 UTC, merged