RDEVOPS-84 Opetrons AI Server foundation
OpenTrons/opentrons-api pull request #15086
Opened 2024-05-03 15:52 UTC by y3rsh

# Overview

This is the base of the tooling for the backend of the Opentrons AI project

## Test Plan

## Review requests

## Risk assessment

2024-05-03 18:15 UTC, y3rsh commented on .github/workflows/ai-server-lint-test.yaml
> +# This workflow runs lint on pull requests that touch anything in the app-testing directory
```suggestion
# This workflow runs lint on pull requests that touch anything in the opentrons-ai-server directory
```

2024-05-03 18:16 UTC, y3rsh commented on opentrons-ai-server/Makefile
> +ALLOWED_ENVS := sandbox-opentrons-ai-api dev-opentrons-ai-api
need to change this.  switch to just `sandbox` and `dev` for now

2024-05-03 18:17 UTC, y3rsh commented on opentrons-ai-server/api/models/todo.py
> +    pass
I don't actually know if this works 🤣

2024-05-03 18:19 UTC, y3rsh commented on opentrons-ai-server/requirements.txt
I like checking this in too, this is only the prod requirements.  In infra we use the powertools layer, that is why it is a dev dependency.

2024-05-06 18:07 UTC, koji commented on opentrons-ai-server/README.md
> +1. select the node version `nvs` currently 18.\*
```suggestion
1. select the node version `nvs` currently 18.19\*
```

2024-05-06 18:10 UTC, koji commented on opentrons-ai-server/README.md
> +`python -m pipenv install pytest==8.2.0 --dev`
Seems other python projects are using v7. Is there any big diff between v7 and v8?

2024-05-06 18:14 UTC, koji commented on opentrons-ai-server/api/domain/todo.py
> +from api.models.todo import Todo, Todos
Question is there any rule for import statements' order?

in frontend we use the following order rule.
1. 3rd party packages
2. internal packages (components, shared-data)
3. local packages/components/functions
4. types (types follows 1-3)
5. css

2024-05-06 19:53 UTC, y3rsh commented on opentrons-ai-server/README.md
> +`python -m pipenv install pytest==8.2.0 --dev`
There are, lots of bug fixes and breaking changes so want to use the latest since we are not locked into 7 with the rest of the stack.
<https://docs.pytest.org/en/8.0.x/changelog.html>

2024-05-06 19:58 UTC, y3rsh commented on opentrons-ai-server/api/domain/todo.py
> +from api.models.todo import Todo, Todos
We are using [ruff ](https://docs.astral.sh/ruff/settings/#lint_isort_order-by-type) for this, I like going with their default but we could investigate the settings to see if we could change it.

2024-05-07 14:11 UTC, sfoster1 commented on opentrons-ai-server/README.md
> +`python -m pipenv install pytest==8.2.0 --dev`
v8 wasn't released when we did dep upgrades last. it might actually be fine, I don't think we've evaluated it

2024-05-07 14:36 UTC, y3rsh commented on opentrons-ai-server/api/settings.py
> +        # These map to the the environment variables defined and set in teh
finish this comment

2024-05-07 14:38 UTC, y3rsh commented on opentrons-ai-server/api/settings.py
> +    def fetch_secret(secret_name: str) -> SecretStr:
think about this more, should this be in integrations? Probably

2024-05-07 14:50 UTC, sfoster1 requested changes
The structure looks good and I agree with the handler/domain/integration separation, but I think we can tune up a lot about the more full-featured stuff in here like the http client wrapper and the deploy script.

2024-05-07 14:50 UTC, sfoster1 commented on opentrons-ai-server/api/settings.py
> +        # These map to the the environment variables defined and set in teh
unfinished sentence?

2024-05-07 14:50 UTC, sfoster1 commented on opentrons-ai-server/requirements.txt
> +-i https://pypi.org/simple
is this for the lambda package? it's a bit odd to have both this and pipenv in use at the same time, could/should we generate this and gitignore it?

2024-05-07 14:50 UTC, sfoster1 commented on opentrons-ai-server/deploy.py
> +    DEPLOYMENT_TIMEOUT = 60  # seconds
nit: imo this could be `DEPLOYMENT_TIMEOUT_S` and then the comment isn't necessary

2024-05-07 14:50 UTC, sfoster1 commented on opentrons-ai-server/deploy.py
> +class DeploymentConfig:
sort of nit, sort of more - with this arrangement where everything is in the same bag-of-data dataclass, it's easy and not statically analyzable to accidentally return the wrong one of e.g. `DEV_S3_BUCKET` and `SANDBOX_S3_BUCKET`. if instead there's a `DeploymentConfig` dataclass that has just e.g. `S3_BUCKET`, `FUNCTION_NAME`, and `ZIP_PATH` and no defaults, then you create three of them with the appropriate defaults and pass it around as needed

2024-05-07 14:50 UTC, sfoster1 commented on opentrons-ai-server/deploy.py
> +            print(f"Failed to update Lambda function: {e}")
nit: can't we just let this expression raise and print something out at a higher level? then this function doesn't have to return `| None`, and we don't have to check its return at the callsite

2024-05-07 14:50 UTC, sfoster1 commented on opentrons-ai-server/deploy.py
> +    def wait_for_lambda_status(self, version: str) -> None:
this function really needs to indicate that an error occurred somehow. right now you'd have to look at what it prints since if it times out it just returns and it swallows all exceptions. Let's let this raise, and let's raise on a timeout, and have a higher level format nice error prints and `sys.exit(1)` at least.

2024-05-07 14:50 UTC, sfoster1 commented on opentrons-ai-server/deploy.py
> +    def invoke_lambda(self, version: str) -> None:
same here - if this is for a gut-check that the lambda is actually healthy, it really needs to be able to fail in a way that's machine checkable. It should raise if the invocation fails.

2024-05-07 14:50 UTC, sfoster1 commented on opentrons-ai-server/api/integration/http_client.py
> +            logger.error(f"An error occurred while requesting {e.request.url!r}.")
do we need to log things twice like this? can't we just do the exception logger? the way it works in python is if you `logger.exception('some message')` it logs the message and if there's an active exception logs the exception info. it's basically exactly for this.

2024-05-07 14:50 UTC, sfoster1 commented on opentrons-ai-server/api/integration/http_client.py
> +        except httpx.HTTPStatusError as e:
As far as I can tell, `httpx` will only raise an `HTTPStatusError` if you call `response.raise_for_status()`:
> The HTTPStatusError class is raised by response.raise_for_status() on responses which are not a 2xx success code. These exceptions include both a .request and a .response attribute.

(per [their quickstart](https://www.python-httpx.org/quickstart/) which unfortunately doesn't allow deeplinks). So I don't think this is possible to do.

2024-05-07 14:50 UTC, sfoster1 commented on opentrons-ai-server/api/integration/http_client.py
> +            logger.exception(e)
Handling this exception like this, with an `except (e):` that does nothing but log, swallows the error fully and won't raise it further. In both exception cases (though as below, I don't think the second one can happen) that means that this function will return `None` implicitly because the exception will happen before the return clause, which is both not as annotated and probably not what you want. I think these exception clauses should reraise.

2024-05-07 14:50 UTC, sfoster1 commented on opentrons-ai-server/api/integration/http_client.py
> +            except httpx.RequestError as e:
Same comments as for the synchronous method.

2024-05-07 14:50 UTC, sfoster1 commented on opentrons-ai-server/api/integration/http_client.py
> +            self.client.close()
is there a solid reason to close after every request? in theory, one of the hooks of httpx is that it has implicit connection pooling.

2024-05-07 14:50 UTC, sfoster1 commented on opentrons-ai-server/api/integration/http_client.py
> +class HTTPClient:
I think this class may be on the wrong side of the balance of effort vs usefulness. It's capturing three parameters so you don't have to specify them every time, which is useful, but in return you have to go reimplement every httpx client interaction method that you want to use elsewhere and either tediously type out the same function signatures because mypy doesn't have `typeof` or do as you did an `**kwargs: Any` type-erase the result. I'd love to see a bit more of a balance in terms of preserving the information `httpx` provides, maybe via annotating these methods with `functools.wrap` on the client methods or something.

2024-05-07 14:50 UTC, sfoster1 commented on opentrons-ai-server/api/integration/http_client.py
> +        timeout: float = 10.0,
nit: could be `timeout_s` and `connect_timeout_s` and need a little less docs

2024-05-07 14:50 UTC, sfoster1 commented on opentrons-ai-server/api/handler/function.py
> +def handler(event: dict[Any, Any], context: LambdaContext) -> dict[Any, Any]:
wait do we really not get python types of lambda events out of using this lambda powertool thing? jeez

2024-05-07 14:50 UTC, sfoster1 commented on opentrons-ai-server/api/handler/function.py
> +    return Response(status_code=HTTPStatus.OK, content_type=content_types.APPLICATION_JSON, body={"version": "0.0.1"})
obv haven't implemented the full versioning thing yet, but maybe have a `__version__.py` that starts out handwritten and will be generated in the future and import that here for this response?

2024-05-07 17:15 UTC, y3rsh commented on opentrons-ai-server/api/settings.py
> +        # These map to the the environment variables defined and set in teh
yes, fixed

2024-05-07 17:15 UTC, y3rsh commented on opentrons-ai-server/requirements.txt
> +-i https://pypi.org/simple
yes... it felt awkward, made it part of the build, removed the tracking

2024-05-07 17:17 UTC, y3rsh commented on opentrons-ai-server/deploy.py
> +class DeploymentConfig:
yes this is better

2024-05-07 17:20 UTC, y3rsh commented on opentrons-ai-server/deploy.py
> +            print(f"Failed to update Lambda function: {e}")
:heart yes.

2024-05-07 17:22 UTC, y3rsh commented on opentrons-ai-server/deploy.py
> +    def wait_for_lambda_status(self, version: str) -> None:
like much better.

2024-05-07 17:26 UTC, y3rsh commented on opentrons-ai-server/deploy.py
> +    def invoke_lambda(self, version: str) -> None:
yes.

2024-05-07 18:09 UTC, y3rsh commented on opentrons-ai-server/deploy.py
> +    DEPLOYMENT_TIMEOUT = 60  # seconds
fixed

2024-05-07 18:12 UTC, y3rsh commented on opentrons-ai-server/api/integration/http_client.py
> +            logger.error(f"An error occurred while requesting {e.request.url!r}.")
yup not needed.

2024-05-07 18:14 UTC, y3rsh commented on opentrons-ai-server/api/integration/http_client.py
> +            self.client.close()
no

2024-05-07 18:14 UTC, y3rsh commented on opentrons-ai-server/api/integration/http_client.py
> +        except httpx.HTTPStatusError as e:
removed

2024-05-07 18:14 UTC, y3rsh commented on opentrons-ai-server/api/integration/http_client.py
> +            logger.exception(e)
ya again not needed

2024-05-07 18:14 UTC, y3rsh commented on opentrons-ai-server/api/integration/http_client.py
> +            except httpx.RequestError as e:
got it.

2024-05-07 18:26 UTC, y3rsh commented on opentrons-ai-server/api/integration/http_client.py
> +class HTTPClient:
Ya, I was trying to get some reasonable defaults.  This will need to be used for huggingface unless they have a client like openai, I have not looked.  See if the new version is a little better.

2024-05-07 18:27 UTC, y3rsh commented on opentrons-ai-server/api/integration/http_client.py
> +        timeout: float = 10.0,
fixed

2024-05-07 18:41 UTC, y3rsh commented on opentrons-ai-server/api/integration/http_client.py
> +class HTTPClient:
This was totally unnecessary.  Removed it. httpx typing is great.

2024-05-07 18:42 UTC, y3rsh commented on opentrons-ai-server/api/handler/function.py
> +    return Response(status_code=HTTPStatus.OK, content_type=content_types.APPLICATION_JSON, body={"version": "0.0.1"})
yes for sure will be dynamic and able to be tied to code, will do in a separate PR

2024-05-07 18:50 UTC, y3rsh commented on opentrons-ai-server/api/handler/function.py
> +def handler(event: dict[Any, Any], context: LambdaContext) -> dict[Any, Any]:
I think we can, I did not dig in enough on the event.  Ours will always be 1 type of event as things are now but all their examples allow events from multiple services and I left it.

2024-05-08 13:52 UTC, sfoster1 approved these changes
Looks good! What's up with the logic in the `if` blocks in the workflow? I can't quite see like what the purpose of the `always()` is and why we'd want to run the subsequent steps if the install was skipped?

2024-05-08 13:52 UTC, sfoster1 commented on .github/workflows/ai-server-lint-test.yaml
> +        if: always() && steps.install.outcome == 'success' || steps.install.outcome == 'skipped'
what's going on with this logic?

2024-05-08 15:02 UTC, y3rsh commented on .github/workflows/ai-server-lint-test.yaml
> +        if: always() && steps.install.outcome == 'success' || steps.install.outcome == 'skipped'
The use of always() combined with the outcomes of the install step ensures that the step will always run if install was either successful or skipped, but not if install failed. 

So the step runs even if a previous step failed except if the install step fails.

2024-05-08 15:02 UTC, merged