feat(hardware): implement multipass lld
OpenTrons/opentrons-api pull request #15122
Opened 2024-05-07 19:32 UTC by ryanthecoder

# Overview
Due to limits on how far the z stage can move depending on a combination of factors including z speed, plunger speed and labware depth we may need to run the probe multiple times in order to find the liquid. 

This PR lets the liquid probe script handle when the liquid is not found and start a new pass that starts at the z height the the previous pass stopped at.

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-05-07 20:11 UTC, sfoster1 requested changes
Let's begin as we mean to go on and get that error as a proper enumerated error defined in shared data; otherwise, lgtm

2024-05-07 20:11 UTC, sfoster1 commented on api/src/opentrons/hardware_control/types.py
>  class LiquidNotFound(RuntimeError):
Definitely needs to be an `EnumeratedError` with its own code in shared-data

2024-05-07 20:29 UTC, sfoster1 requested changes

2024-05-07 20:29 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        print(f"positions {positions}")
stray

2024-05-07 21:14 UTC, ryanthecoder commented on api/src/opentrons/hardware_control/types.py
>  class LiquidNotFound(RuntimeError):
Alright I think I did this right?

2024-05-08 13:53 UTC, sfoster1 approved these changes
Nice, thanks! I could see arguments for this either being 2-series or 3-series but I'm not super bothered about it.

2024-05-08 13:54 UTC, sfoster1 commented
@ryanthecoder I think you have to run format-js to format the error codes json file

2024-05-10 19:08 UTC, merged