build(fix): add the pyusb to dev-packages in api/Pipfile.
OpenTrons/opentrons-api pull request #15206
Opened 2024-05-16 19:21 UTC by vegano1

# Overview

Commit [#15167](https://github.com/Opentrons/opentrons/pull/15167) added support for the plate reader, which required a `pyusb` a Python dependency. The device works as expected on the robot, but we also use parts of the Python stack for robot analysis on the app and ci, which uses API dev-packages. So let's add `pyusb` to the dev-packages section in the api/Pipfile file.

# Test Plan

- [ ] Make sure that protocol analysis passes in CI
- [ ] Make sure that protocol analysis passes in the desktop app

# Changelog

- add `pyusb` dep to dev-packages for api project

# Review requests
# Risk assessment
low

2024-05-17 14:05 UTC, sfoster1 requested changes
If this dep is required for analysis then it also needs to be in the setup.py install_requires so that people installing from pypi won’t have broken installs.

2024-05-22 19:47 UTC, vegano1 commented
@sfoster1 

Analyses Snapshot Test is no longer failing because of the missing pyusb dependency.
It's not failing because the snapshots are no longer valid and need to be updated.

https://github.com/Opentrons/opentrons/actions/runs/9197098594/job/25297114720

2024-05-23 13:53 UTC, y3rsh commented on app-testing/Pipfile
> +pyusb = "==1.2.1"
### This should not be needed.
The packages here are not a part of the environment where analysis is run.
A docker container
https://github.com/Opentrons/opentrons/blob/edge/app-testing/citools/Dockerfile
Mimics the build of the app. 
https://github.com/Opentrons/opentrons/blob/edge/app-shell/scripts/before-pack.js
> [!NOTE]
> If the analysis does not run in this container then I don't think it would in the app.
> Somehow `pyusb` must be a part of the packages that get bundled with the app.
> Adding it to /api should do that.

> Let us remove just this change to `app-testing/Pipfile` and run the analysis snapshot again.  It did get work in https://github.com/Opentrons/opentrons/pull/15212 run

2024-05-24 15:15 UTC, sfoster1 approved these changes
Shouldn't be needed as much after https://github.com/Opentrons/opentrons/commit/ccc944efb238a0f9a5d32f04aeeb308018993c97

2024-06-04 16:25 UTC, ahiuchingau commented
Do we still need this?

2024-07-11 20:12 UTC, closed without merging