fix(api): monitor the pressure sensor more
OpenTrons/opentrons-api pull request #15246
Opened 2024-05-22 14:20 UTC by ryanthecoder

# Overview
This will allow us to monitor the pressure sensor more, specifically it should help us catch and differentiate cases where the tip collides with the labware by monitoring it during the z movement in addition to the plunger movement. 
Should help diagnose:
RABR-319
RABR-305
RABR-304

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-05-22 14:27 UTC, sfoster1 requested changes

2024-05-22 14:27 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
>          async with self._monitor_overpressure(mounts_moving):
i don't think this can handle mount axis nodes

2024-05-22 18:54 UTC, ryanthecoder commented on api/src/opentrons/hardware_control/backends/ot3controller.py
>          async with self._monitor_overpressure(mounts_moving):
Yup, added a new util function and fixed that

2024-05-22 20:31 UTC, caila-marashaj commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> -        mounts_moving = [
nitpick here, but we can maybe rename this variable now to `pipettes_to_monitor` or something to that effect

2024-05-22 20:32 UTC, caila-marashaj approved these changes
nice. I like this.

2024-05-24 15:11 UTC, sfoster1 approved these changes
Okay, but let's add tests at least for `moving_pipettes_in_move_group` please

2024-05-28 15:37 UTC, merged