refactor(shared-data, robot-server, api): Pipette configuration architecture refactor to organize by nozzle map and tip type
OpenTrons/opentrons-api pull request #15250
Opened 2024-05-22 21:52 UTC by CaseyBatten

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-05-23 16:58 UTC, sfoster1 requested changes
Quick glance, looks like the right path but there's some stuff I'd like to see changed

2024-05-23 16:58 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot2/pipette.py
> +                self._nozzle_manager.current_configuration.map_store.keys()
this is a whole lot to be doing just here, and it adds this error category. instead of doing this, let's tell the nozzle manager what map key it's using and then we can look up the configuration based on that directly.

2024-05-23 16:58 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/pipette.py
> +        for map_key in self._valid_nozzle_maps.maps.keys():
see the ot2 comment

2024-05-23 16:58 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot3/pipette.py
> +                    [
maybe simplify this by putting `config.configuration_by_nozzle_map[approved_map]` in an intermediate

2024-05-23 16:58 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/resources/pipette_data_provider.py
> +                raise ValueError(
should be a protocol engine error that descends from an enumerated error

2024-05-28 19:41 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot2/pipette.py
> +        except KeyError:
we should have these errors be enumerated errors defined in shared data using an error code, like a new 4000-series "missing configuration data" or something

2024-05-28 19:41 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot2/pipette.py
> +            default = config.configuration_by_nozzle_map[
Could this be a free function in a shared area? I think it's an identical implementation for the two machines

2024-05-28 19:41 UTC, sfoster1 commented on api/src/opentrons/hardware_control/instruments/ot2/pipette.py
> +            ].get("default")
and actually generally the task of "get data from the unified structure" might be able to be commonized further

2024-06-07 13:53 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/errors/exceptions.py
> +    """An error indicating that provided configurationd ata is missing or invalid.
```suggestion
    """An error indicating that provided configuration data is missing or invalid.
```

2024-06-10 20:42 UTC, b-cooper approved these changes
Talked through in person and collected a list of comments offline.  After those are addressed and Seth's comments too, this looks good to merge!

2024-06-11 17:03 UTC, sfoster1 approved these changes
Looks like it will work, and good job - this was pretty hairy! Would love to see the virtual static pipette checks raise enumerated errors and I think there's a solid followup that takes some of these functions that have like 3 layers of try/except logic and factors them into using some intermediate accessors, though.

2024-06-11 17:03 UTC, sfoster1 commented on api/src/opentrons/hardware_control/nozzle_manager.py
> +            if valid_nozzle_maps.maps[map_key] == list(map_store.keys()):
are these sorted explicitly

2024-06-11 17:03 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/resources/pipette_data_provider.py
> +                raise ValueError(
still need this one

2024-06-11 18:09 UTC, CaseyBatten commented on api/src/opentrons/hardware_control/nozzle_manager.py
> +            if valid_nozzle_maps.maps[map_key] == list(map_store.keys()):
Validated maps are ordered from the smallest validated configuration to the largest in our definitions, with nozzle sets in each map following a Column then Row mapping order, the same as our map store.

2024-06-11 19:10 UTC, merged