feat(scripts): migrate AWS-SDK from v2 to v3
OpenTrons/opentrons-api pull request #15267
Opened 2024-05-28 14:03 UTC by jerader

closes [RDEVOPS-96](https://opentrons.atlassian.net/browse/RDEVOPS-96)

# Overview

this PR migrates from using AWS-SDK v2 to v3 and updates all our web deployment scripts (`promote-to-staging`, `promote-to-production`, `rollback`) and the utils used

NOTE: v3 does support typescript and i tried to update the scripts to using typescript but ran into a bunch of TS compiler issues 🫠. Seemed much easier to just stick with JS. Additionally, v2 is supposed to be deprecated as early as September 8th this year so figured it was better to update to v3 and still use JS than update to v3 and use TS (for now).

# Test Plan

Only someone with the proper aws creds can test this. But should be tested for docs, PD, and LL with promote to staging, promote to production, and rollback dry runs.

for promote to staging: `node ./scripts/deploy/promote-to-staging project tag` (PD tag is `protocol-designer@8.0.0`)

for promote to prod: `node ./scripts/deploy/promote-to-production project`

rollback: `node ./scripts/deploy/rollback project environment`

# Changelog

- install appropriate dependencies (aws-sdk v3 uses modules now)
- update all the deploy utils
- update staging, prod, and rollback scripts

# Review requests

see test plan

# Risk assessment

medium - we have no more releases that will use these anytime soon. The dry runs all seem to work! 

[RDEVOPS-96]: https://opentrons.atlassian.net/browse/RDEVOPS-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-05-29 13:58 UTC, sfoster1 requested changes
Couple small things to change but thanks for doign this!

2024-05-29 13:58 UTC, sfoster1 commented on scripts/deploy/promote-to-production.js
> +    await getDeployMetadata(s3Client, stagingBucket)
it seems like `getDeployMetadata` used to be here to get something called `current` that was then logged, and not really any other purpose. This PR moves the log above `getDeployMetadata` and removes the use of its return, so maybe we should just get rid of `getDeployMetadata`

2024-05-29 13:58 UTC, sfoster1 commented on scripts/deploy/promote-to-production.js
> +    getCreateInvalidation(productionCredentials, cloudfrontArn)
needs to be `await`-ed i think

2024-05-29 13:58 UTC, sfoster1 commented on scripts/deploy/promote-to-production.js
> +    process.exit(0).catch(err => {
I don't think we need this `catch`, if it's the equivalent of the `catch` on the old line 100 then that functionality is covered by the function-wide `try/catch`

2024-05-29 16:23 UTC, jerader commented on scripts/deploy/promote-to-production.js
> +    process.exit(0).catch(err => {
oops yes this is not needed there. thanks!

2024-05-31 14:42 UTC, y3rsh requested changes
Let us try and fix the invalidations.

2024-05-31 14:42 UTC, y3rsh commented on scripts/deploy/promote-to-production.js
>  const { checkCurrentAWSProfile } = require('./check-current-profile')
Cannot comment on the not edited collapsed lines but all the arns for all CloudFront distributions in this file and in the promote-staging.js are incorrect.  This is why we have had to do them manually?

2024-06-03 12:43 UTC, jerader commented on scripts/deploy/promote-to-production.js
>  const { checkCurrentAWSProfile } = require('./check-current-profile')
ooh, thanks Josh. i thought we haven't had to do them manually since i added the cloud invalidations to these scripts. But did the cloudfront arns change when we added the new administrator role arn last year?

2024-06-04 17:40 UTC, y3rsh approved these changes

2024-06-04 17:40 UTC, y3rsh commented on scripts/deploy/promote-to-production.js
>  const { checkCurrentAWSProfile } = require('./check-current-profile')
Sorry PD CloudFront ARN are correct.  I think LL, static, docs may be off but are not relevant to this PR.

2024-06-05 19:35 UTC, sfoster1 approved these changes
Looks good, I think. There is that one weird `Promise.resolve()` that I don't think needs to be there but good otherwise

2024-06-05 19:35 UTC, sfoster1 commented on scripts/deploy/create-invalidation.js
> +  if (dryrun) return Promise.resolve()
I think you can just `return` here since it's `async function` not `function(...): Promise`

2024-06-05 19:51 UTC, jerader commented on scripts/deploy/create-invalidation.js
> +  if (dryrun) return Promise.resolve()
ooooh ya good point thank you!

2024-06-05 20:33 UTC, merged