feat(api): add new pick up tip function
OpenTrons/opentrons-api pull request #15275
Opened 2024-05-28 18:54 UTC by caila-marashaj

## Overview
This is a follow-up to https://github.com/Opentrons/opentrons/pull/15143.

In order to support error recovery, we should restructure some of our api functions so that they _only_ do the motor routines necessary to do what they say to do, without any additional movements or information caching. This creates a new function that change to `pick_up_tip`, and still leaves the original `pick_up_tip` in place.

## Changelog
- create an `execute_pick_up_tip` function that leaves out both of the pipette plunger moves at the beginning and end, and does not add the tip
- add some tests
- have `pick_up_tip` call this new function

2024-05-28 19:12 UTC, SyntaxColoring approved these changes
Makes sense to me TY. Just a few suggestions.

2024-05-28 19:12 UTC, SyntaxColoring commented on api/src/opentrons/hardware_control/ot3api.py
> +    ) -> None:
1. Does this also need to exist on the OT-2 `API` class so the two classes can be substituted for each other?
2. Could we have docstrings defining what this does and how it's different from `pick_up_tip()`?
3. I feel like there could be a more specific name for this, but I don't know what. `pick_up_tip_bare()` or `just_pick_up_tip()` or `pick_up_tip_motions()` or something else?

2024-05-28 19:16 UTC, caila-marashaj commented on api/src/opentrons/hardware_control/ot3api.py
> +    ) -> None:
Yeah thats a good point, I'll make another commit with some changes.

2024-05-28 19:32 UTC, sfoster1 requested changes
Looks good overall, just a couple little things!

2024-05-28 19:32 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +    ) -> None:
`pick_up_tip_in_place`? I think at some poitn we're going to want to get it out of this file anyway

2024-05-28 19:32 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +            )
we need to do the simulator state update thing that's on line 2159 too, this:
```python
if isinstance(self._backend, OT3Simulator):
     self._backend._update_tip_state(realmount, True)
```

2024-05-28 21:20 UTC, SyntaxColoring commented on api/src/opentrons/hardware_control/ot3api.py
> +    ) -> None:
I wouldn't use `_in_place` because in Protocol Engine, `_in_place` is used to roughly mean "do the operation without moving X/Y," whereas here, *neither* function moves in X/Y, and the difference has to do with tip-state and volume-state setting.

2024-05-28 21:27 UTC, caila-marashaj commented on api/src/opentrons/hardware_control/ot3api.py
> +            )
Why do we want this? My impression was that we want to leave any kind of state updates to the caller

2024-05-29 14:16 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +            )
This specifically is a hack to get the simulated tip presence sensors returning the right thing - that's why it's checking the backend. You're right in general, but this is an exception

2024-05-29 15:27 UTC, sfoster1 reviewed
Looks good to me once we remove the simulator change from the old function

2024-05-29 15:27 UTC, sfoster1 approved these changes
last review was meant to be an approval

2024-05-29 15:55 UTC, SyntaxColoring approved these changes
🛻

2024-05-29 17:44 UTC, merged