fix(shared-data): Re-apply update tip overlap values for Flex Pipettes (#15147)
OpenTrons/opentrons-api pull request #15284
Opened 2024-05-29 18:14 UTC by sfoster1

This is #15147 again but this time outside the context of an extremely imminent release. 

While this code needs to be merged, we should carefully consider how we do so. We can't ship this until we can separate this behavior by API level so that customers who may have tuned in offsets  based on the old incorrect tip offsets won't have their protocols invalidated - this data needs to be loaded by API level.

2024-06-03 14:27 UTC, SyntaxColoring approved these changes
Approved previously in #15147, looks good if and when the versioning considerations are solved.

2024-06-05 17:33 UTC, Carlos-fernandez approved these changes
All looks correct! Good to go!

2024-06-05 17:36 UTC, DerekMaggio requested changes

2024-06-05 17:36 UTC, DerekMaggio commented on api/tests/opentrons/protocol_api/core/engine/test_overlap_versions.py
> +
Can you add a test to verify that a bump to the major version is evaluated correctly, please? So something like `APIVersion(3, 12)` 
I can imagine this being something missed because a 3.x would likely be years from now and subsequently breaking everything.

2024-06-05 17:45 UTC, DerekMaggio commented on api/tests/opentrons/protocol_api/core/engine/test_overlap_versions.py
> +
Actually I might be incorrect, it looks like the underlying versions_between would throw an assertion error https://github.com/Opentrons/opentrons/blob/3643682c0c213286b8c31666f5aabfefeadab705/api/tests/opentrons/protocol_api/__init__.py#L102C1-L104C75
If that is true, I will change to approval

2024-06-05 18:33 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/engine/__init__.py
> +
snuck in there

2024-06-05 18:37 UTC, TamarZanzouri approved these changes
Nice! LGTM!

2024-06-05 18:42 UTC, skowalski08 approved these changes
tested 2.18,2.19, and json -lgtm

2024-06-05 18:59 UTC, sfoster1 commented on api/tests/opentrons/protocol_api/core/engine/test_overlap_versions.py
> +
Yes, that's true @DerekMaggio

2024-06-05 19:10 UTC, DerekMaggio approved these changes

2024-06-05 19:15 UTC, merged