fix(opentrons-ai-client): add conditional for user prompt
OpenTrons/opentrons-api pull request #15308
Opened 2024-05-31 19:52 UTC by koji

# Overview
add conditional for user prompt

### before
![Screenshot 2024-05-31 at 3 36 48 PM](https://github.com/Opentrons/opentrons/assets/474225/97b5d598-af2e-41bf-9bc2-7c5c643c7db2)

### after

![Screenshot 2024-05-31 at 3 50 45 PM](https://github.com/Opentrons/opentrons/assets/474225/4532882a-3641-4d30-9404-7171ee43f098)

close AUTH-433

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-05-31 20:35 UTC, shlokamin requested changes
i get this error from react markdown when using one of the example buttons: 

```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

```

<img width="1499" alt="Screenshot 2024-05-31 at 4 34 32 PM" src="https://github.com/Opentrons/opentrons/assets/5788529/2238470a-c53d-4f53-a4b5-41133e4fa61e">

2024-05-31 20:36 UTC, shlokamin commented
i don't think react markdown likes `undefined`

2024-05-31 20:49 UTC, koji commented
> i don't think react markdown likes `undefined`

change `undefined` to paragraph text.

2024-06-03 09:52 UTC, Elyorcv commented on opentrons-ai-client/src/molecules/ChatDisplay/index.tsx
> +            code: isUser ? ParagraphText : CodeText,
If I understand correctly, only `user` needs to be wrapped.

But, we need to wrap both `user` and `assistant` with markdown.

2024-06-03 14:12 UTC, koji commented on opentrons-ai-client/src/molecules/ChatDisplay/index.tsx
> +            code: isUser ? ParagraphText : CodeText,
what do you mean `wrapped`?

2024-06-03 14:21 UTC, Elyorcv commented
> > i don't think react markdown likes `undefined`
> 
> change `undefined` to paragraph text.

does it behave differently for `user` vs. `assistant`?

2024-06-03 14:42 UTC, koji commented
> > > i don't think react markdown likes `undefined`
> > 
> > 
> > change `undefined` to paragraph text.
> 
> does it behave differently for `user` vs. `assistant`?

yes because of conditional rendering.

2024-06-03 15:49 UTC, Elyorcv requested changes
No it is not behaving correctly. See the image below, when user sends info with backtick, it renders as a block.

<img width="907" alt="image" src="https://github.com/Opentrons/opentrons/assets/24993718/cfecd64d-cace-4088-bfe5-ee2bc162bc8e">

2024-06-03 15:53 UTC, koji commented
> No it is not behaving correctly. See the image below, when user sends info with backtick, it renders as a block.
> 
> ```
> 
> Write a protocol using the Opentrons Python Protocol API v2 for OT-2 robot according to the following description:
>   
> Labware:
> - Source Labware: `Thermo Scientific Nunc 96 Well Plate 1300 uL` in slot 9
> - Destination Labware: `Opentrons 96 Flat Bottom Adapter with NEST 96 Well Plate 200 uL Flat` in slot 10
> - `Opentrons 96 Filter Tip Rack 1000 uL` in slot 8
> - `Opentrons 96 Tip Rack 1000 uL` in slot 3
> 
> Pipette mount:
> - P1000 Single-Channel GEN2 is mounted on the left
> - P1000 Single-Channel GEN2 is mounted on the right
> 
> Commands:
> 1. Use the left-mounted P1000 Single-Channel GEN2 pipette to transfer 196 uL of reagent from wells A7, A6, A5, A2, A3 
> of the source labware to the corresponding wells A5, A9, A1, A10, A2 of the destination labware. Use a new tip for each transfer.
> 2. Use the right-mounted P1000 Single-Channel GEN2 pipette to transfer 8 uL of liquid from wells A9, A12, A6, A10, A3 
> of the source labware to the corresponding wells A7, A11, A6, A3, A9 of the destination labware. Use the same tip for all transfers.
> ```
> 
> <img alt="image" width="907" src="https://private-user-images.githubusercontent.com/24993718/336141003-cfecd64d-cace-4088-bfe5-ee2bc162bc8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MzAxOTIsIm5iZiI6MTcxNzQyOTg5MiwicGF0aCI6Ii8yNDk5MzcxOC8zMzYxNDEwMDMtY2ZlY2Q2NGQtY2FjZS00MDg4LWJmZTUtZWUyYmMxNjJiYzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDE1NTEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNzQ1MTNjMTcwYTg1ZjBkNTQ5NGQyMWRlM2JkMDhhZWM2ODNiY2ZjZmNmYTFkOGM4YTgwM2RhZTI1NTk4ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Yzpw4OtIoTQkmYJrJzaoSgU3jjXkV6YSnTuHOzgQYE">

not completely align with that since we use react-mark down and it take some time.
this pr is to fix the margin and no black background in user prompt

2024-06-03 16:06 UTC, Elyorcv commented
> > No it is not behaving correctly. See the image below, when user sends info with backtick, it renders as a block.
> > ```
> > 
> > Write a protocol using the Opentrons Python Protocol API v2 for OT-2 robot according to the following description:
> >   
> > Labware:
> > - Source Labware: `Thermo Scientific Nunc 96 Well Plate 1300 uL` in slot 9
> > - Destination Labware: `Opentrons 96 Flat Bottom Adapter with NEST 96 Well Plate 200 uL Flat` in slot 10
> > - `Opentrons 96 Filter Tip Rack 1000 uL` in slot 8
> > - `Opentrons 96 Tip Rack 1000 uL` in slot 3
> > 
> > Pipette mount:
> > - P1000 Single-Channel GEN2 is mounted on the left
> > - P1000 Single-Channel GEN2 is mounted on the right
> > 
> > Commands:
> > 1. Use the left-mounted P1000 Single-Channel GEN2 pipette to transfer 196 uL of reagent from wells A7, A6, A5, A2, A3 
> > of the source labware to the corresponding wells A5, A9, A1, A10, A2 of the destination labware. Use a new tip for each transfer.
> > 2. Use the right-mounted P1000 Single-Channel GEN2 pipette to transfer 8 uL of liquid from wells A9, A12, A6, A10, A3 
> > of the source labware to the corresponding wells A7, A11, A6, A3, A9 of the destination labware. Use the same tip for all transfers.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="907" src="https://private-user-images.githubusercontent.com/24993718/336141003-cfecd64d-cace-4088-bfe5-ee2bc162bc8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MzAxOTIsIm5iZiI6MTcxNzQyOTg5MiwicGF0aCI6Ii8yNDk5MzcxOC8zMzYxNDEwMDMtY2ZlY2Q2NGQtY2FjZS00MDg4LWJmZTUtZWUyYmMxNjJiYzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDE1NTEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNzQ1MTNjMTcwYTg1ZjBkNTQ5NGQyMWRlM2JkMDhhZWM2ODNiY2ZjZmNmYTFkOGM4YTgwM2RhZTI1NTk4ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Yzpw4OtIoTQkmYJrJzaoSgU3jjXkV6YSnTuHOzgQYE">
> 
> not completely align with that since we use react-mark down and it take some time. this pr is to fix the margin and no black background in user prompt.
> 
> https://opentrons.slack.com/archives/C074KKV6SRK/p1717189125167839

black background is coming from rendering of backtick. Although it is not black anymore, the backtick is still considered as a block rather than inline. Maybe we need to change this PR to account for only fixing margin.

2024-06-03 16:48 UTC, koji commented
> > > No it is not behaving correctly. See the image below, when user sends info with backtick, it renders as a block.
> > > ```
> > > 
> > > Write a protocol using the Opentrons Python Protocol API v2 for OT-2 robot according to the following description:
> > >   
> > > Labware:
> > > - Source Labware: `Thermo Scientific Nunc 96 Well Plate 1300 uL` in slot 9
> > > - Destination Labware: `Opentrons 96 Flat Bottom Adapter with NEST 96 Well Plate 200 uL Flat` in slot 10
> > > - `Opentrons 96 Filter Tip Rack 1000 uL` in slot 8
> > > - `Opentrons 96 Tip Rack 1000 uL` in slot 3
> > > 
> > > Pipette mount:
> > > - P1000 Single-Channel GEN2 is mounted on the left
> > > - P1000 Single-Channel GEN2 is mounted on the right
> > > 
> > > Commands:
> > > 1. Use the left-mounted P1000 Single-Channel GEN2 pipette to transfer 196 uL of reagent from wells A7, A6, A5, A2, A3 
> > > of the source labware to the corresponding wells A5, A9, A1, A10, A2 of the destination labware. Use a new tip for each transfer.
> > > 2. Use the right-mounted P1000 Single-Channel GEN2 pipette to transfer 8 uL of liquid from wells A9, A12, A6, A10, A3 
> > > of the source labware to the corresponding wells A7, A11, A6, A3, A9 of the destination labware. Use the same tip for all transfers.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > <img alt="image" width="907" src="https://private-user-images.githubusercontent.com/24993718/336141003-cfecd64d-cace-4088-bfe5-ee2bc162bc8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MzAxOTIsIm5iZiI6MTcxNzQyOTg5MiwicGF0aCI6Ii8yNDk5MzcxOC8zMzYxNDEwMDMtY2ZlY2Q2NGQtY2FjZS00MDg4LWJmZTUtZWUyYmMxNjJiYzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDE1NTEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNzQ1MTNjMTcwYTg1ZjBkNTQ5NGQyMWRlM2JkMDhhZWM2ODNiY2ZjZmNmYTFkOGM4YTgwM2RhZTI1NTk4ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Yzpw4OtIoTQkmYJrJzaoSgU3jjXkV6YSnTuHOzgQYE">
> > 
> > 
> > not completely align with that since we use react-mark down and it take some time. this pr is to fix the margin and no black background in user prompt.
> > https://opentrons.slack.com/archives/C074KKV6SRK/p1717189125167839
> 
> black background is coming from rendering of backtick. Although it is not black anymore, the backtick is still considered as a block rather than inline. Maybe we need to change this PR to account for only fixing margin.

because the response from backend includes pre tag(backtick)

https://github.com/Opentrons/opentrons/assets/474225/9e3b562f-cac4-4bd8-ae8c-3dfb1e09b3c9

2024-06-03 19:10 UTC, Elyorcv approved these changes
LGTM, I created another ticket to solve `backtick` rendering https://opentrons.atlassian.net/browse/AUTH-465

2024-06-03 19:34 UTC, shlokamin approved these changes

2024-06-03 19:35 UTC, merged