chore: configure project to go on robot
OpenTrons/opentrons-api pull request #15316
Opened 2024-06-03 16:12 UTC by DerekMaggio

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-06-24 16:06 UTC, SyntaxColoring requested changes
Changes requested for performance-metrics/Makefile and robot-server/Pipfile (unless I'm missing something). Other than that, LGTM. Thanks!

2024-06-24 16:06 UTC, SyntaxColoring commented on performance-metrics/Makefile
> +	$(call restart-service,$(host),$(ssh_key),$(ssh_opts),"opentrons-robot-server")
~~This target is `push-no-restart` but it looks like the recipe will restart `opentrons-robot-server`?~~ nvm, I misread this.

2024-06-24 16:06 UTC, SyntaxColoring commented on performance-metrics/Makefile
> +update-robot-version:
Nitpick: I might call this `set-robot-version` or `mark-robot-version` to make it clearer that it's not actually "updating the robot" in the sense of, like, a normal user-facing software update from v7.2 to v7.3.

2024-06-24 16:06 UTC, SyntaxColoring commented on performance-metrics/setup.cfg
Why do we have both setup.cfg and setup.py? Does something merge their contents, or is one overriding the other?

I only have a tenuous understanding of all of this, so it's definitely possible I'm missing something.

2024-06-24 16:06 UTC, SyntaxColoring commented on robot-server/Pipfile
> -performance-metrics = {file = "../performance-metrics", editable = true}
Wasn't this the thing that installs performance-metrics into robot-server's dev environment, so it's available when you do `make -C robot-server dev`? How are we allowed to delete it?

2024-06-24 16:06 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +        @TrackingFunctions.track_getting_cached_protocol_analysis
This looks like it'll work for now, but it seems like it's turning out that we want the trackers to work as context managers instead of decorators, right? In other words, we shouldn't have to turn a chunk of code into an inner function just for the sake of packaging it up and handing to `track_getting_cached_protocol_analysis()`.

2024-06-24 16:06 UTC, SyntaxColoring commented on performance-metrics/README.md
> +Performance metrics usage is hidden behind a feature flag. To enable it run the following command (assumes you have the `host` environment variable set):
Looks like the following commands set `host` explicitly and don't assume that you have it set as an environment variable?

2024-06-24 16:06 UTC, SyntaxColoring commented on performance-metrics/README.md
> +Go to your app -> Settings -> General and find your app version
Just so I'm clear, this isn't specifically a performance-metrics thing, right? It's a thing in general when you're using a stable app to interact with a dev-tainted robot?

2024-06-24 16:17 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +        @TrackingFunctions.track_getting_cached_protocol_analysis
I also think you and @sfoster1 have been trying hard to avoid `performance_metrics` introducing even small overhead. I'm not sure if this is what we're doing now, but, for example, at one point you were checking the feature flag once on first import to avoid the overhead of an `if`/`else` every time the function under measurement was called. Is that still a goal?

2024-06-24 18:48 UTC, DerekMaggio commented on robot-server/Pipfile
> -performance-metrics = {file = "../performance-metrics", editable = true}
`robot-server` doesn't directly use the `performance-metrics` library. The `api` project does, and it is setup as an editable dev dependency there.

2024-06-24 19:11 UTC, DerekMaggio commented on performance-metrics/README.md
> +Go to your app -> Settings -> General and find your app version
Correct, I will clarify a bit. Also, "dev-tainted" made me chuckle

2024-06-24 19:12 UTC, DerekMaggio commented on performance-metrics/README.md
> +Performance metrics usage is hidden behind a feature flag. To enable it run the following command (assumes you have the `host` environment variable set):
Oh yeah, I added the host and forgot to change that. Thank you

2024-06-24 19:12 UTC, SyntaxColoring commented on robot-server/Pipfile
> -performance-metrics = {file = "../performance-metrics", editable = true}
But `robot-server`'s dev environment is separate from `api`'s dev environment. Dev dependencies of `api` are not automatically installed as dev dependencies of `robot-server`.

After doing a fresh clone and `make setup`, I just tried:

```
cd robot-server
pipenv run python -c 'import performance_metrics'
```

And I got an `ImportError` because `performance_metrics` is not in `robot-server`'s dev environment. Even though this works:

```
cd api
pipenv run python -c 'import performance_metrics'
```

2024-06-24 19:19 UTC, DerekMaggio commented on robot-server/robot_server/protocols/router.py
> +        @TrackingFunctions.track_getting_cached_protocol_analysis
@SyntaxColoring 

> This looks like it'll work for now, but it seems like it's turning out that we want the trackers to work as context managers instead of decorators, right? In other words, we shouldn't have to turn a chunk of code into an inner function just for the sake of packaging it up and handing to track_getting_cached_protocol_analysis().

See https://github.com/Opentrons/opentrons/pull/14834#discussion_r1556175599 for a previous discussion about this. Let me know what you think.

2024-06-24 19:31 UTC, DerekMaggio commented on robot-server/robot_server/protocols/router.py
> +        @TrackingFunctions.track_getting_cached_protocol_analysis
> I also think you and @sfoster1 have been trying hard to avoid `performance_metrics` introducing even small overhead. I'm not sure if this is what we're doing now, but, for example, at one point you were checking the feature flag once on first import to avoid the overhead of an `if`/`else` every time the function under measurement was called. Is that still a goal?

@SyntaxColoring, you're correct that it should not be checking every time. But because `_should_track` is evaluated at import time you have to restart the robot-server if you ever want to update. Should I set the ff restart_required to True maybe?

2024-06-24 19:51 UTC, DerekMaggio commented on robot-server/Pipfile
> -performance-metrics = {file = "../performance-metrics", editable = true}
But I never directly import anything from performance_metrics in `robot-server`
All the wire up logic is in `api/util/performance_helpers.py` and `robot-server` imports stuff from there

2024-06-24 20:41 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +        @TrackingFunctions.track_getting_cached_protocol_analysis
Thank you for the background!

So to back up, you've gone to pains in the design of `performance_metrics` to avoid introducing overhead. But then it looks like the overhead is getting added here anyway?

Specifically—and I have not profiled this, but—if every call to `create_protocol()` defines an inner function `_get_cached_protocol_analysis()`, and then decorates it, and then calls it, I'm skeptical that all of that will be cheaper than it would have been to just enter and exit a context manager. Note that this particular decoration does *not* run at file parse time the way https://github.com/Opentrons/opentrons/pull/14834#discussion_r1556175599 describes. It runs every time this block of `_get_cached_protocol_analysis()` runs.

You could avoid this by refactoring the `_get_cached_protocol_analysis()` inner function to be a module-level private function, and then the decoration really would only run once at module parse time.

But my larger point, which I've broached before and which I still believe, is: Are these pains really worth it? Are simpler approaches, like entering context managers and accessing `os.environ` "too frequently," really not good enough? I mean, we're measuring protocol analysis here. The latency of starting the background thread alone is probably going to drown out whatever microseconds we shaved by doing the decorator thing. I believe there are use cases where it could matter, but I can easily live without them, personally.

2024-06-24 20:49 UTC, SyntaxColoring commented on robot-server/Pipfile
> -performance-metrics = {file = "../performance-metrics", editable = true}
> But I never directly import anything from performance_metrics in robot-server
All the wire up logic is in api/util/performance_helpers.py and robot-server imports stuff from there.

Yeah. But the behavior of `api/util/performance_helpers.py` depends on whether `performance_metrics` is installed. And I don't think it will be if we remove this line.

> I tested performance metrics using the dev server for both ot-2 and flex initially

Uhh hm, that's weird. Have you tried that on a fresh clone in a separate directory? I'm not sure why it would work for you but not me.

2024-06-25 18:06 UTC, DerekMaggio commented on performance-metrics/setup.cfg
So the bdist_wheel option makes it compatible with python 2 and 3, which we don't need.
But our wheel naming logic in scripts/python_build_utils.py outputs a name with support for both python 2 and 3.
Python packaging is really not my forte so I don't want to mess with it. Especially not in this PR.

2024-06-25 18:59 UTC, DerekMaggio commented on robot-server/Pipfile
> -performance-metrics = {file = "../performance-metrics", editable = true}
https://github.com/Opentrons/opentrons/pull/15316/commits/44907382e38df0fd1c8ef3c970cc86b25fd5df9d

2024-06-25 18:59 UTC, DerekMaggio commented on performance-metrics/README.md
> +Performance metrics usage is hidden behind a feature flag. To enable it run the following command (assumes you have the `host` environment variable set):
https://github.com/Opentrons/opentrons/pull/15316/commits/5b8d813fccc6d263a8cae9fb50c230b70fcea1f0

2024-06-25 18:59 UTC, DerekMaggio commented on performance-metrics/Makefile
> +update-robot-version:
https://github.com/Opentrons/opentrons/pull/15316/commits/5b8d813fccc6d263a8cae9fb50c230b70fcea1f0

2024-06-25 19:37 UTC, SyntaxColoring approved these changes
Yay, thank you!

2024-06-25 19:50 UTC, sfoster1 commented on robot-server/robot_server/protocols/router.py
> +        @TrackingFunctions.track_getting_cached_protocol_analysis
I think that I'm in both camps. I think the default approach, and the structural approach to implementing the reusable analysis side, should be oriented towards zero-cost abstractions even if they're inconvenient. But I think that at the point of integration, i.e. right here, sometimes it's okay to say "this is not zero-cost but the cost is marginal". For instance, here it's not zero-cost - like @SyntaxColoring says, you're creating an inner function each call - but this is not a hotpath; it's the top level call that will last a long time, not something called many times in a loop. We would jump through many more hoops than this to keep a zero-cost integration in some core protocol engine function, for a counterexample. And we need to have those hoops available to jump through, which is why we designed the metrics system as a function transformer that can run at import time.

I think it is reasonable to set restart_required to true for the feature flag for the general case.

2024-06-25 19:59 UTC, DerekMaggio commented on robot-server/robot_server/protocols/router.py
> +        @TrackingFunctions.track_getting_cached_protocol_analysis
To make sure I understand. Leave the creation of the inner function as is because it is not something we call a whole lot, and even if we did it is a call that takes a while so the impact would be negligible.
If we were wrapping some logic that is called many times then the wrapping of the logic should be done in a way that is as performant as possible.

2024-06-25 20:11 UTC, merged