feat(api): implement liquid probe protocol engine command
OpenTrons/opentrons-api pull request #15351
Opened 2024-06-05 21:51 UTC by pmoegenburg

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-06-06 13:54 UTC, sfoster1 requested changes
Aside from fixing what's already failing tests, please either draft this or take a pass to remove note to self comments and write some tests. They can be pretty simple for now since this command doesn't do much, but they should be present.

2024-06-10 20:18 UTC, ryanthecoder commented on api/src/opentrons/protocol_engine/commands/liquid_probe.py
> +    mount: MountType = Field(..., description="Instrument mount to liquid probe with.")
We are going to want the well we are using so we can get the well's max depth

2024-06-10 20:21 UTC, ryanthecoder commented on api/src/opentrons/protocol_engine/commands/liquid_probe.py
> +        z_pos = ot3_api.liquid_probe(mount=ot3_mount)  # anything else?
We are going to want to pass an Instance of LiquidProbeSettings.
we can get a copy of the defaults from ot3_api.config().liquid_sense
We are going to want to change the starting mount height and the max_z_distance based on the well we are probing

2024-06-11 20:49 UTC, caila-marashaj commented on api/src/opentrons/protocol_engine/commands/liquid_probe.py
> +            public=LiquidProbeResult(
I think it might just be worth a comment somewhere that the `position` here is the position at the well where the probe starts, and `z_pos` is after the probe

2024-06-11 20:56 UTC, caila-marashaj approved these changes
Nice!

2024-06-17 16:11 UTC, ryanthecoder commented on api/src/opentrons/hardware_control/ot3api.py
> -        total_z_travel = probe_settings.max_z_distance
If we're not going to use this value from probe_settings. Lets remove it from that data struct so we don't confuse anything or miss any references using it in hardware-testing

2024-06-17 16:55 UTC, sfoster1 requested changes
Couple last little changes but almost there!

2024-06-17 16:55 UTC, sfoster1 commented on api/src/opentrons/hardware_control/protocols/liquid_handler.py
> +        mount : Mount.LEFT or Mount.RIGHT
should have `max_z_dist` explained too

2024-06-17 16:55 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/liquid_probe.py
> +    z_position: float = Field(..., description="Z position of the found liquid.")
worth mentioning here that
- This is the _absolute_ z position, as in from the deck, not the relative height from the bottom of the well
- It is in mm

2024-06-17 16:55 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +        return 0.0  # fix
let's either do the fix now or let's make it a better formatted TODO comment

2024-06-18 20:18 UTC, sfoster1 approved these changes
Very nice, love the changes, looks good to me!

2024-06-18 20:19 UTC, merged