feat(hardware control): create logic to detect if tip has hit bottom …
OpenTrons/opentrons-api pull request #15389
Opened 2024-06-11 20:07 UTC by aaron-kulkarni

…of well or liquid

Creates a new file called sensor_utils.py. Introduces new error type for tip hitting bottom of the well when searching for liquid. Creates a function that detects whether the tip has hit a liquid or the bottom of the well based on pressure data.

fix EXEC-517

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-06-12 13:57 UTC, sfoster1 requested changes
Great job with the enumerated error! I think there's some things to fix up about the functions though.

2024-06-12 13:57 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/sensor_utils.py
> +def detectLiquidOrBlockage(
our style is `snake_case` for python, so this should be `detect_liquid_or_blockage`, same with the variables (sorry!)

2024-06-12 13:57 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/sensor_utils.py
> +) -> None:
I think we want this function to return a `bool`, and probably have the function be _named_ in a way that can be answered with true or false - i.e., `did_hit_well_bottom(...) -> bool` or something. 

The reason to make it return a bool is that a function that returns a bool is more generally useful. A function that either raises or returns can't be used for anything else without doing some exception-as-control-flow mechanics we don't like doing; but if the function returns a bool, the caller can raise if the bool is false

2024-06-12 13:57 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/sensor_utils.py
> +    #take derivative of pressureReadings with respect to dx
This comment and the variables names talk about derivatives, but this is a discrete gradient and thus operates in terms of _difference_. It could be quite relevant, given that when you're living in discrete world with noise, differencing amplifies noise. Let's phrase things as differences to keep that in mind.

I also think this comment is duplicative with the next line; if you know what `dx` and a gradient are, you can understand the next line, and if you don't then this comment doesn't tell you anything new.

2024-06-12 13:58 UTC, sfoster1 commented
Also, the thing with the commit titles is 
- they want to have a type that is correct (which this is)
- but the scope, i.e. what's inside the parens, actually has to be exactly the name of a subdirectory of the monorepo 

So here it would be exactly `feat(hardware):`

2024-06-12 15:39 UTC, sfoster1 requested changes
I think we need to handle the length of the list in some way - either gracefully degrade under 5 samples, or raise an error

2024-06-12 15:39 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/sensor_utils.py
> +    pressure_difference = np.gradient(pressure_readings[-5:], 1)
What happens if there's fewer than 5 readings in the list?

2024-06-12 15:56 UTC, ryanthecoder commented on hardware/opentrons_hardware/hardware_control/sensor_utils.py
> +    pressure_difference = np.gradient(pressure_readings[-5:], 1)
there should always be a minimum of 100 in the future implementation but a check here makes sense, maybe we can raise a LiquidNotFoundError if there isn't enough data

2024-06-12 19:47 UTC, sfoster1 requested changes
The code looks good to me, so now we just need to get the static analysis passing. You should autoformat the code with `make -C api format`, and see what `make -C api lint` gives you; same with `make -C shared-data/python format` and `make -C shared-data/python lint` (and a top level `make format-js` to get the errors.json file autoformatted)

2024-06-13 15:06 UTC, sfoster1 approved these changes
Looks good to me! Nice work. Future stuff will require tests but here we're making exactly one call to numpy so I think it would be a little much :)

2024-06-13 15:24 UTC, merged