feat(shared-data): add schema definitions for minimumHeight and minim…
OpenTrons/opentrons-api pull request #15444
Opened 2024-06-17 20:44 UTC by aaron-kulkarni

…umWellVolume

The definitions of minimumHeight and minimumWellVolume are for all non tip rack labware. They will be used in LLD.

fix EXEC-518

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-06-18 17:36 UTC, sfoster1 requested changes, later dismissed
I think we need to change the structure a little to handle heterogenous-well labware like the 15/50 tuberack.

2024-06-18 17:36 UTC, sfoster1 commented on shared-data/labware/schemas/2.json
> +        "minimumHeight:": {
this unfortunately needs to be more than just one number to handle labwares that have multiple different kinds of wells like the 15/50 combo tube rack. there's two options here:
1. It's part of the well datastructure, for each well
2. instead of containing a number, this is an array of objects that have a `value` member that is a number and an `appliesToWells` member that is an array of well names or something

Goes for both `minimumHeight` and `minimumWellVolume`.

2024-06-18 18:13 UTC, ryanthecoder commented
I'd also like to see these be a joined object like
` "LiquidProbeSettings: {
            "minimumHeight": 0.5,
            "minimumWellVolume": 0,
  }`

2024-06-21 16:02 UTC, ryanthecoder approved these changes
Looks good to me

2024-06-21 16:04 UTC, merged