refactor(api): wire protocol engine pick_up_tip to new hardware control function
OpenTrons/opentrons-api pull request #15469
Opened 2024-06-20 15:55 UTC by caila-marashaj

2024-06-20 18:06 UTC, sfoster1 requested changes
Tests tests tests! But it lookks good to me otherwise.

2024-06-24 15:03 UTC, DerekMaggio commented on api/tests/opentrons/protocol_engine/execution/test_tip_handler.py
> +        from opentrons.hardware_control.ot3api import OT3API
You only need to wrap the import statement in the try. The rest of the test logic can be outside the try-except.
Also, is this how we normally run Flex-only tests? Or should the `ot3_only` mark be used and it can be expected the import will always work?

2024-06-24 15:12 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/tip_handler.py
> +        if self._state_view.config.robot_type == "OT-3 Standard":
Could you explain why we need to do this `if`/`else` on `robot_type`? Does the OT-2 HWAPI not behave the same way as the OT-3 HWAPI?

2024-06-24 15:18 UTC, caila-marashaj commented on api/src/opentrons/protocol_engine/execution/tip_handler.py
> +        if self._state_view.config.robot_type == "OT-3 Standard":
no, we don't want to run `verify_tip_presence` for an ot2. We pretty much just want to run the old `pick_up_tip` if we have an ot2, and then unconditionally cache a tip.

2024-06-24 15:19 UTC, sfoster1 requested changes
I think we can make the ot-2 stuff more similar to the flex stuff which will reduce complexity

2024-06-24 15:19 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +    async def _tip_pickup_moves(
I think this can be a public function, no reason not to really

2024-06-24 15:19 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +    async def _tip_pickup_moves(
does this have a `cache_tip` already also? if not, should add that too

2024-06-24 15:19 UTC, sfoster1 commented on api/tests/opentrons/protocol_engine/execution/test_tip_handler.py
> +        from opentrons.hardware_control.ot3api import OT3API
try it with the `ot3_only` mark, yeah

2024-06-24 16:34 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/tip_handler.py
> +        if self._state_view.config.robot_type == "OT-3 Standard":
But this code *is* calling `verify_tip_presence()` on an OT-2, isn't it? Down on line 197?

2024-06-24 21:18 UTC, caila-marashaj commented on api/src/opentrons/protocol_engine/execution/tip_handler.py
> +        if self._state_view.config.robot_type == "OT-3 Standard":
yeah you're right I think this actually is compatible with ot2

2024-06-25 16:09 UTC, sfoster1 approved these changes
Looks good to me, nice!

2024-06-25 19:45 UTC, merged