feat(api): add liquid presence detection to load_instrument()
OpenTrons/opentrons-api pull request #15482
Opened 2024-06-20 20:40 UTC by pmoegenburg

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-06-21 17:21 UTC, sfoster1 requested changes
Couple changes needed to support the API level distinctions (and we should test them also)

2024-06-21 17:21 UTC, sfoster1 commented on api/src/opentrons/protocol_api/protocol_context.py
> +        :param bool liquid_presence_detection: If ``True``, enable liquid presence detection for instrument.
This should be noted as only being acceptable if the API version is above some level. It should also default to `None`, so that we can later raise an exception if the API level is below that value and the argument isn't None

2024-06-21 17:21 UTC, sfoster1 commented on api/src/opentrons/protocol_api/protocol_context.py
> +            liquid_presence_detection=liquid_presence_detection,
Before passing it in, we should check that if we're below the API level we added it in then the value is `None`. if it is, though, then `None` should become `False` when we pass to lower levels.

2024-06-21 17:21 UTC, sfoster1 commented on api/tests/opentrons/protocol_engine/state/test_pipette_view.py
> +    liquid_presence_detection_by_id: Optional[Dict[str, Optional[bool]]] = None,
why `Optional[bool]` rather than just `bool`?

2024-06-24 17:50 UTC, pmoegenburg commented on api/tests/opentrons/protocol_engine/state/test_pipette_view.py
> +    liquid_presence_detection_by_id: Optional[Dict[str, Optional[bool]]] = None,
The LoadPipetteParams liquidPresenceDetection is Optional

2024-06-24 20:36 UTC, sfoster1 requested changes
Couple other nits

2024-06-24 20:36 UTC, sfoster1 commented on api/src/opentrons/protocol_api/protocol_context.py
> +            self._api_version < APIVersion(2, 19)
oh, this will be 2.20 - 2.19 is being added in 7.3.1

2024-06-24 20:36 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/pipettes.py
> +    liquid_presence_detection_by_id: Dict[str, Optional[bool]]
let's make this non-optional. The argument to the `LoadPipette` command is optional, but let's reify that into a bool the same way we do in protocol context to make this just a bool

2024-06-24 20:36 UTC, sfoster1 commented on api/src/opentrons/protocol_api/protocol_context.py
> +            raise ValueError("Liquid presence detection only available on Flex robot.")
This should be an enumerated error of some kind, not just a plain value error

2024-06-24 20:36 UTC, sfoster1 commented on api/src/opentrons/protocol_api/protocol_context.py
> +            raise APIVersionError(
This check should happen _before_ the flex-only check, because we want a protocol running on an ot-2 on 2.18 to raise the version error, while an ot-2 on 2.20 would raise the robot error

2024-06-25 17:09 UTC, sfoster1 requested changes
Couple last small things but looking good

2024-06-25 17:09 UTC, sfoster1 commented on api/src/opentrons/protocol_api/protocol_context.py
> +                "Liquid Presence Detection is only supported on Flex protocols in API Version 2.20 and above."
```suggestion
                "Liquid Presence Detection is only supported on Flex protocols in API Version 2.20 and above."
```
```suggestion
                "Liquid Presence Detection is only supported in API Version 2.20 and above."
```

2024-06-25 17:09 UTC, sfoster1 commented on api/src/opentrons/protocols/api_support/util.py
> +class RobotTypeError(Exception):
Looks like we've found some exceptions that need to be `EnumeratedError`s and aren't yet. We should make this exception inherit from [UnsupportedHardwareError](https://github.com/Opentrons/opentrons/blob/217268511518e3074ce4ca661739bc192099dd5e/shared-data/python/opentrons_shared_data/errors/exceptions.py#L968)

2024-06-25 17:09 UTC, sfoster1 commented on api/src/opentrons/protocols/api_support/util.py
> +
we should probably add a new api version error with a new code in shared-data  for APIVersionError, and make `UnsupportedAPIError` use [ApiRemoved](https://github.com/Opentrons/opentrons/blob/217268511518e3074ce4ca661739bc192099dd5e/shared-data/python/opentrons_shared_data/errors/exceptions.py#L900) or something (but look at how `UnsupportedApiError` is actually used, might be inappropriate). We can do this in a followup though.

2024-06-25 20:23 UTC, sfoster1 requested changes, later dismissed
Last thing - API verison 2.20 doesn't exist yet. We'll need to add it, which will be pretty easy, but https://github.com/Opentrons/opentrons/pull/15507 should probably get merged first. So we can treat this as done for now and fix it up once that happens in the next day or two.

2024-06-25 20:49 UTC, ryanthecoder approved these changes
lgtm

2024-06-26 19:27 UTC, merged