feat(api): change liquid_probe to respect min well height
OpenTrons/opentrons-api pull request #15488
Opened 2024-06-21 17:29 UTC by aaron-kulkarni

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-06-24 15:22 UTC, sfoster1 requested changes, later dismissed
Couple small issues, but the big one is: this needs testing. The state getter should have tests that make sure the right thing is returned in all 5 of the optional cases (no info, key but no values, one height requirement, full height requirement).

2024-06-24 15:22 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/labware.py
> +        """Get's the minimum distance that a liquid probe must stop away from the bottom of a well.
```suggestion
        """Gets the minimum distance that a liquid probe must stop away from the bottom of a well.
```

2024-06-24 15:22 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/labware.py
> +            ):  # A "custom" default value will have "applicableWells" set to []
will it? or will it have `applicableWells` set to a list of all the wells?

2024-06-26 19:56 UTC, ryanthecoder approved these changes
I Think this looks good

2024-06-26 20:28 UTC, merged