fix(api): inherit protocol api errors from enumerated errors
OpenTrons/opentrons-api pull request #15516
Opened 2024-06-25 19:29 UTC by pmoegenburg

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-06-25 19:51 UTC, SyntaxColoring approved these changes

2024-06-25 19:51 UTC, SyntaxColoring commented on api/src/opentrons/protocols/api_support/util.py
> +class UnsupportedAPIError(APIRemoved):
It looks like this exception is currently unused, so it doesn't really matter, but note that "API removed" is not the only thing that could be meant by "a protocol attempts to use an unsupported API." It could also mean that the protocol attempts to use an API that's too new, like if you tried to use `"apiLevel": "2.19"` on robot software v5.0. (We're currently [just raising `ValueError` for that](https://github.com/Opentrons/opentrons/blob/fe022795bf2a071d30c04dd7fccf07ecc3d1a45e/api/src/opentrons/protocol_api/create_protocol_context.py#L86), but we probably shouldn't be.)

I wonder if we want just a generic code and exception for any protocol API version error. I'm not sure it's worth having 3 separate things for "too old," "too new," and "supported but invalid."

2024-06-26 13:15 UTC, sfoster1 requested changes
Looks good but you'll have to change the way you create the exception - take a look at the exception definition in shared-data for how to do that. You'll also have to add the code to the underlying json file in `shared-data/errors`.

2024-06-27 13:43 UTC, ecormany commented on api/src/opentrons/protocols/api_support/util.py
> +class UnsupportedAPIError(APIRemoved):
Three is probably too many, yes. Two is probably good, breaking down into:
- Something is wrong with the combination of your code and API version.
- Your code used to be good but isn't anymore and furthermore that feature is never coming back ever ever so don't get your hopes up.

2024-06-27 14:51 UTC, SyntaxColoring commented on api/src/opentrons/protocols/api_support/util.py
> +class UnsupportedAPIError(APIRemoved):
But my point is that that specific breakdown of 2 is not sufficient to cover the case where your code *is* good, you just need to update your robot. That breakdown is covering problems like `protocol_apilevel < MIN_SUPPORTED_VERSION` and `not feature_available_in(protocol_apilevel)`, but is not covering the problem of `protocol_apilevel > MAX_SUPPORTED_VERSION`.

2024-07-02 17:01 UTC, sfoster1 approved these changes
Looks good once you clean up dev comments

2024-07-02 17:01 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/errors/exceptions.py
> +        # make this cleaner?!
Remove or make a proper todo comment (I think the code is fine as is though)

2024-07-02 18:40 UTC, ecormany commented on api/src/opentrons/protocol_api/deck.py
> +                until_version="2.15",
Wait, was `del deck[1]` actually broken in 2.14? I don't think we ever documented that.

2024-07-03 13:25 UTC, sfoster1 commented on api/src/opentrons/protocol_api/deck.py
> +                until_version="2.15",
Yes, definitely

2024-07-03 13:41 UTC, ecormany commented on api/src/opentrons/protocol_api/deck.py
> +                until_version="2.15",
Yeah, all we have is this:
> Changed in version 2.14: Includes the Thermocycler in all of the slots it occupies.
>
> Changed in version 2.15: `del` sets the corresponding labware’s location to `OFF_DECK`.

We could update the versionchanged notice…or not.

2024-07-09 17:13 UTC, sfoster1 approved these changes
Nice work!

2024-07-09 18:37 UTC, merged