feat(api): create instr ctx methods for checking liquid presence
OpenTrons/opentrons-api pull request #15555
Opened 2024-07-01 15:55 UTC by aaron-kulkarni

Added detect_liquid and require_liquid to instrument_context. The two methods both check for liquid in a specific well, but one returns true/false and the other raises exceptions.

re EXEC-544, re EXEC-545

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-07-01 15:55 UTC, aaron-kulkarni commented
still need to test

2024-07-01 19:45 UTC, ryanthecoder commented on api/src/opentrons/protocol_api/instrument_context.py
> +            raise WellDoesNotExistError
You're returning the TYPE WellDoesNotExistError here, not an instance. you should call it like
`raise WellDoesNotExistError()`

2024-07-01 19:58 UTC, ryanthecoder commented on api/src/opentrons/protocol_api/instrument_context.py
> +        except Exception:
I think we should only explicity catch LiquidNotFoundException if we're going to handle them. If there is some other issue that results in an error this could let that go undetected

2024-07-02 13:23 UTC, sfoster1 requested changes
Couple changes we should make to the API. Also, if you merge edge into this PR it should get rid of the snapshot problem.

2024-07-02 13:23 UTC, sfoster1 commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        ):  # this should probably only happen in testing with mock components
No, we shouldn't do this. If we're using mock components, those mock components should return data in the same way the real things do even if they get it from somewhere else - this is why we have mocks.

2024-07-02 13:23 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +            raise WellDoesNotExistError("Well type was none.")
```suggestion
            raise WellDoesNotExistError("You must provide a well to check.")
```

2024-07-02 13:23 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +        if well is None:
```suggestion
        if not isinstance(well, labware.Well):
```

2024-07-02 13:23 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +        if well is None:
```suggestion
        if not isinstance(well, labware.Well):
```

2024-07-02 13:23 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +            raise WellDoesNotExistError()
this error should take the same form as the same check in the other methods

2024-07-02 13:23 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +            return 0
is this really an appropriate return value? Remember, this function returns a height in absolute deck coordinates, in which z=0 is the level of the deck. So this function can sometimes return, without indicating an error, that the liquid level is at the height of the deck. That doesn't make much sense to me.

I think this function should just let the `PipetteLiquidNotFoundError` through.

2024-07-02 13:24 UTC, sfoster1 requested changes, later dismissed

2024-07-02 13:24 UTC, sfoster1 commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        result = self._engine_client.execute_command_without_recovery(
```suggestion
        result = self._engine_client.execute_command(
```
we definitely want to recover from this command

2024-07-02 15:53 UTC, ryanthecoder commented on api/src/opentrons/protocol_api/instrument_context.py
> +            return 0
I agree we should pass this through. The only api call that shouldn't raise errors is detect_liquid

2024-07-02 20:05 UTC, SyntaxColoring reviewed
Thanks, this is coming along! Agreed with the existing comments.

2024-07-02 20:05 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +    def require_liquid(self, well: labware.Well) -> None:
The name `require_liquid` matches what the ticket specifies, but is the ticket correct? [The proposal](https://opentrons.atlassian.net/wiki/spaces/PER/pages/4210491403/Proposal+Liquid+Presence+Verification+Syntax+and+Semantics) says `require_liquid_presence`.

2024-07-02 20:05 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +    def detect_liquid(self, well: labware.Well) -> bool:
The name `detect_liquid` matches what the ticket specifies, but is the ticket correct? [The proposal](https://opentrons.atlassian.net/wiki/spaces/PER/pages/4210491403/Proposal+Liquid+Presence+Verification+Syntax+and+Semantics) says `detect_liquid_presence`.

2024-07-02 20:05 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        result = self._engine_client.execute_command_without_recovery(
I think the problem here is that one of this method's callers, `InstrumentContext.get_liquid_height()`, is returning the probed height. And if the `liquidProbe` command fails and we let the frontend drive error recovery, there *isn't* a probed height in the general case. The client can choose to skip to the next command without retrying the failed `liquidProbe`.

We can certainly solve this for *`InstrumentContext.require_liquid()`*. Just, yeah, call `execute_command()` (with recovery) and discard the `liquidProbe` result. A successful `liquidProbe`, or a failed-but-recovered `liquidProbe`, will return from `execute_command()`. A failed-and-not-recovered `liquidProbe` will raise from `execute_command()`, and we should let that propagate up.

But for `InstrumentContext.get_liquid_height()` and `InstrumentContext.detect_liquid_presence()`, it's unclear to me what we would even want to happen.

2024-07-02 20:05 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +        :returns: A float representing the height of the liquid.
A guideline on documentation in general:

We don't need to say that this returns a float, because that should be self-evident from the method signature. (Our documentation generator automatically includes method signatures, e.g. [like this](https://docs.opentrons.com/v2/new_protocol_api.html#opentrons.protocol_api.Well.diameter)).

What we *do* need to say is how to interpret the float. What units? (mm.) From what origin? (The bottom of the well, or the bottom of the deck?)

2024-07-02 20:05 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +    def get_liquid_height(self, well: labware.Well) -> float:
The name `get_liquid_height` is what the ticket specifies, but I would consider naming this something like `measure_liquid_height()` or `probe_liquid_height()` to emphasize that it will *actually make the robot move*—it's not a typical getter/setter that merely returns some preexisting variable.

2024-07-02 20:09 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +            raise WellDoesNotExistError
`raise ExceptionType` is in fact valid Python, equivalent to `raise ExceptionType()`, but it is discouraged so your point still stands.

2024-07-02 20:23 UTC, aaron-kulkarni commented on api/src/opentrons/protocol_api/instrument_context.py
> +    def require_liquid(self, well: labware.Well) -> None:
Different parts of the proposal say different things. At the top, under the "design" header, it says:

A dedicated raise-if-not-present command: pipette.require_liquid(well: Well)

But below that in the more detailed sections it does say: 
pipette.require_liquid_presence(well: Well).

It seems like require_liquid was the one-off error, though, and the correct version is require_liquid_presence. I'll change it but we might want to also edit the proposal to correct that error.

2024-07-02 20:24 UTC, aaron-kulkarni commented on api/src/opentrons/protocol_api/instrument_context.py
> +    def detect_liquid(self, well: labware.Well) -> bool:
Same as above.

2024-07-02 20:26 UTC, aaron-kulkarni commented on api/src/opentrons/protocol_api/instrument_context.py
> +    def get_liquid_height(self, well: labware.Well) -> float:
I agree that measure_liquid_height probably is better. I'll change it for now but if anyone has strong opinions I don't mind changing it back.

2024-07-03 16:55 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +    def require_liquid(self, well: labware.Well) -> None:
TY, proposal edited.

2024-07-03 17:09 UTC, aaron-kulkarni commented
I implemented the changes that we discussed in standup as I understood them. Probably forgot something or misunderstood it so if I did just let me know

2024-07-03 17:49 UTC, ryanthecoder approved these changes
lgtm

2024-07-03 18:05 UTC, merged

2024-07-03 18:08 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/clients/sync_client.py
> +
I think we should remove this new `execute_command_with_result()` method for now. It seems like it's contributing to confusion about the tradeoff between returning a result and allowing for error recovery.

Thankfully, we shouldn't need it for the behavior that we want to implement right now. See my other comment.

2024-07-03 18:08 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        result = self._engine_client.execute_command_without_recovery(
Recap of in-person discussion. Looks like you've already done some of this by the time I'm posting this comment.

## `InstrumentContext.require_liquid_presence()`

We want this method to give the client the opportunity for error recovery, but raise an exception if that ultimately fails. That's what `SyncClient.execute_command()`, so under the hood, this should be implemented using that. If that raises an exception, we should just let it propagate.

## `InstrumentContext.detect_liquid_presence()`

We want this method to straight-up return `True`/`False` *without* giving the client the opportunity for error recovery. So, under the hood:

* We should implement it via `SyncClient.execute_command_without_recovery()`.
* If the probe detects no liquid, `execute_command_without_recovery()` will raise that as an exception. We should look for that and translate it into a `False` return.

  We can catch `ProtocolCommandFailedError`, and then check if `exception.original_error` is an instance of [`LiquidNotFoundError`](https://github.com/Opentrons/opentrons/blob/6ba97194fc65349a91a24b41b5c244c69bb8e6ed/api/src/opentrons/protocol_engine/commands/pipetting_common.py#L150). If so, we should translate it into a `False` return. Otherwise, we should re-raise the exception to let it propagate.

I think this will expose a bug where the robot will mistakenly go into error recovery mode (because "the command failed") *and* try to keep running the protocol (because we're catching the exception, translating it to `False`, and letting the protocol continue). We can take that on in a separate PR: EXEC-598.

## `InstrumentContext.measure_liquid_height()`

We want to keep this internal and experimental for now and keep our options open for the future. So:

* We should say in its docstring that it's internal and experimental, and exclude it from the public docs.opentrons.com website. [Here is an example of how to exclude it from docs.opentrons.com.](https://github.com/Opentrons/opentrons/blob/6ba97194fc65349a91a24b41b5c244c69bb8e6ed/api/src/opentrons/protocol_api/disposal_locations.py#L207-L214)
* We should implement this via `SyncClient.execute_command_without_recovery()`. So if no liquid is detected, it will raise an exception. We should just let that propagate.

The reason we want to keep this internal and experimental is that we haven't really fleshed out how to support error recovery on PAPI methods that return results. Does the UI flow need to have a step to retry the failed probe? Should we just raise some documented exception for the protocol author to catch and deal with how they please?

2024-07-03 18:08 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +        :returns: The height, in mm, of the liquid from the deck.
For API usability, I think we would ideally have this return the height from the bottom of the well, instead of from the deck. That seems more relevant because it wouldn't be coupled to the labware offsets that the operator happened to choose at the beginning of the run.

This doesn't need to happen right now as long as we're marking this method internal and experimental.

2024-07-03 18:08 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        )
I think this gets a lot cleaner if you split this into two methods:

1. One that does `SyncClient.execute_command()`.
2. One that does `SyncClient.execute_command_without_recovery()`.

`SyncClient` is drawing a distinction those two fundamentally modes of operation, representing a tradeoff between having a command result and allowing for error recovery, and representing that tradeoff with two different method signatures. Those map cleanly to the public `InstrumentContext` behaviors that we want to implement, if we maintain the two-method distinction through `InstrumentCore`.