refactor(hardware control): start liquid probe 2mm higher, refactor z moves
OpenTrons/opentrons-api pull request #15564
Opened 2024-07-01 21:04 UTC by caila-marashaj

2024-07-02 16:28 UTC, y3rsh commented
> A PR has been opened to address analyses snapshot changes. Please review the changes here: #15565

FYI this change is in edge so if you merge in edge this test will pass 😊

2024-07-05 20:06 UTC, sfoster1 requested changes
Couple little things but looking good overall

2024-07-05 20:06 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +                await self._move_to_plunger_bottom(checked_mount, rate=p_prep_speed)
do we still need this switch to flip? would it actually work if we flipped it at this point?

2024-07-05 20:06 UTC, sfoster1 commented on hardware/tests/opentrons_hardware/hardware_control/test_tool_sensors.py
> +    # problem is with tool_sensors somewhere
?

2024-07-08 19:17 UTC, ryanthecoder commented on api/src/opentrons/hardware_control/ot3api.py
> +                await self._move_to_plunger_bottom(checked_mount, rate=p_prep_speed)
Should still work, don't know if we want the ability to use it in the future or not

2024-07-08 20:57 UTC, sfoster1 approved these changes
Looks good, please make sure the eventual commit message has a more in-depth description that mentions the change to specifying moves by the plunger distance though

2024-07-08 20:57 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +                await self._move_to_plunger_bottom(checked_mount, rate=p_prep_speed)
can we add a TODO to remove it at some point

2024-07-08 21:23 UTC, merged