refactor(api): edit 3 instr context methods for liquid probe
OpenTrons/opentrons-api pull request #15578
Opened 2024-07-03 19:19 UTC by aaron-kulkarni

Edit detect_liquid_presence, require_liquid_presence, and measure_liquid_height as per the standup today.

# Overview

# Test Plan

# Changelog

# Review requests

Accidentally merged #15555 too soon, this is a continuation of that PR.

# Risk assessment

2024-07-03 19:49 UTC, SyntaxColoring requested changes
This looks great. Thanks for the quick follow-up. A few adjustments:

2024-07-03 19:49 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +                return False
This `isinstance()` check needs to be against [`opentrons.protocol_engine.commands.pipetting_common.LiquidNotFoundError`](https://github.com/Opentrons/opentrons/blob/34d92b78bf3cb2ac4961853fe54ad222e651c316/api/src/opentrons/protocol_engine/commands/pipetting_common.py#L150), not `opentrons_shared_data.errors.exceptions.PipetteLiquidNotFoundError`. The latter is a lower-level thing that gets wrapped into the former by the time it gets here.

2024-07-03 19:49 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
>              return False
I don't think this `except PipetteLiquidNotFoundError` will ever run—that's not something that `SyncClient` will currently raise. I think we can delete this `except` block unless there's something I'm missing.

2024-07-03 19:49 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
>              raise e
Catching an `Exception` and then re-raising it is effectively a no-op. We can delete this.

2024-07-03 19:49 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +            return True
Instead of:

```python
try:
    do_something()
    return True
except SomeError:
    return False
```

It can sometimes be clearer to write:

```python
try:
    do_something()
except SomeError:
    return False
else:
    return True
```

Because it tightens the `try` block and puts both returns in parallel branches of the control flow tree, if that makes sense.

100% a stylistic thing, totally up to you.

2024-07-03 19:49 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +    def find_liquid_presence_with_recovery(self, well_core: WellCore) -> None:
Totally optional nitpick, but I might name these `liquid_probe_with_recovery()` and `liquid_probe_without_recovery()` to avoid introducing a new phrase, "find liquid," whose meaning might not be clear to the reader.

2024-07-03 19:49 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
>          return float(height)
This is a nitpick and doesn't have to do with this PR, but `height` is already a float, so I think we can remove this `float()` cast.

2024-07-03 19:49 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_api/test_instrument_context.py
>      ).then_raise(PipetteLiquidNotFoundError())
You're running into a limitation of our mocking library here: it's letting you set up the mock to raise a `PipetteLiquidNotFoundError()`, but that's not quite what the real code will actually raise. (See my other comment.)

I think you'll have to change this to something roughly like:

```python
.then_raise(
    # Full import paths spelled out for clarity. Probably don't actually write it this verbosely.
    opentrons.protocol_engine.errors.ProtocolCommandFailedError(
       original_error=opentrons.protocol_engine.commands.pipetting_common.LiquidNotFoundError(
            ...
        )
    )
)
```

2024-07-03 20:09 UTC, sfoster1 reviewed
Before we merge, let's
- Change the subject line of the PR to be an indication of what the changes _do_, rather than what the changes _are_ (for instance, `refactor(api): better names for liquid probe commands`, or `refactor(api): handle errors in liquid probe commands`)
- Since the subject line is too small to have enough information, use the description to go into more depth, even if that depth is just a bullet list about changing names and handling errors

2024-07-03 20:51 UTC, aaron-kulkarni commented on api/tests/opentrons/protocol_api/test_instrument_context.py
>      ).then_raise(PipetteLiquidNotFoundError())
I'm trying to implement this, and so far I have the code below:
```
errorToRaise = ProtocolCommandFailedError(
        original_error=LiquidNotFoundError,
        message=f"{LiquidNotFoundError.errorType}: {LiquidNotFoundError.detail}" 
)
decoy.when(mock_instrument_core.liquid_probe_with_recovery(mock_well._core))
subject.require_liquid_presence(mock_well)
decoy.when(
         mock_instrument_core.liquid_probe_with_recovery(mock_well._core)
).then_raise(errorToRaise)
```

But when running `make -C api lint`, I'm getting:
```
Argument "original_error" to "ProtocolCommandFailedError" has incompatible type "type[LiquidNotFoundError]"; expected "ErrorOccurrence | None"
```

Not sure how to cast from LiquidNotFoundError to ErrorOccurrence

2024-07-03 20:57 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_api/test_instrument_context.py
>      ).then_raise(PipetteLiquidNotFoundError())
You're passing the class `LiquidNotFoundError` itself as the argument to `original_error`, but we want to instantiate `LiquidNotFoundError` and pass the resulting object as the argument.

The mypy error message is a bit confusing if you haven't seen it before, but that's what it means by `type[LiquidNotFoundError]`. In other words, in `x=123`, `x` is of type `int`; whereas in `x=int`, `x` is of type `type[int]`.

2024-07-03 22:01 UTC, aaron-kulkarni commented on api/tests/opentrons/protocol_api/test_instrument_context.py
>      ).then_raise(PipetteLiquidNotFoundError())
ah got it thanks

2024-07-05 15:03 UTC, SyntaxColoring requested changes
* Here are a couple of test fixups.
* Let's try to fill in the "test plan" and "risk assessment" sections of the PR description.

  I think I overheard you and @ryanthecoder talk about writing some Python protocols to play around with it. That sounds like a good idea, and you can describe that as the test plan. Just make it clear whether you're going to do that before or after merging this.

Other than that, looks great.

P.S. Here is the bug that I'm predicting will be exposed by this, which I alluded to in the last PR. EXEC-598. (It's my fault, not yours. 🙂)

2024-07-05 15:03 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_api/core/engine/test_instrument_core.py
>          assert True
Oh, sorry for not noticing this in the last PR—you're trying to make sure `subject.liquid_probe_with_recovery()` raises an exception on an empty well, which is correct, but this code does not do that.

If the subject does not raise any exception, the test will erroneously pass. The potentially surprising reason is that to fail a test, an exception has to propagate out of it. If a test runs and it just doesn't `assert` anything, that does not, on its own, constitute a test failure.

The correct way to test that the subject raises an exception is with [`pytest.raises`](https://docs.pytest.org/en/7.1.x/how-to/assert.html#assertions-about-expected-exceptions), which it looks like you're already using in some of the other tests.

Ditto for `test_liquid_probe_without_recovery()`.

2024-07-05 15:03 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_api/test_instrument_context.py
>      assert isinstance(result, bool)
I think we should go a little further here and also do `assert not result`, i.e. assert that the subject returned `False`, not just any `bool`. That's how I view the work that this subject is doing: it's receiving an exception (possibly) and translating it into a `True` or `False` result, and we want to test that translation.

2024-07-05 15:03 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_api/test_instrument_context.py
> +    assert pcfe.value.original_error.errorType == "liquidNotFound"
Optional nitpick:

I think we could make this a little more concise and clear by doing `assert pcfe.value is errorToRaise` instead. We want to test that if the inner function call raises an exception, the subject raises that same exception untouched.

Ditto for `test_measure_liquid_height()`.

2024-07-05 15:56 UTC, aaron-kulkarni commented on api/tests/opentrons/protocol_api/core/engine/test_instrument_core.py
>          assert True
Actually, I thought about it some more and shouldn't `liquid_probe_with_recovery` not error? Because presumably it'll get a PipetteLiquidNotFoundError and then recover from that, at which point it will not raise the error.

But definitely yes for `liquid_probe_without_recovery`. I've edited that one to use pytest.raises

2024-07-05 16:30 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_api/core/engine/test_instrument_core.py
>          assert True
Uhh maybe. Let me think about that and get back to you.

2024-07-05 16:51 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_api/core/engine/test_instrument_core.py
>          assert True
OK, yes, I think you're on to the right thing.

`liquid_probe_with_recovery()` should just call `SyncClient.execute()` without doing anything special to convert its result.  If `SyncClient.execute()` raises an exception, `liquid_probe_with_recovery()` should propagate it as-is.

So, the way to test that, then, is just the `decoy.verify()` that you already have. We *could* get more sophisticated with Decoy's `then.raise()` and Pytest's `pytest.raises`, but we generally don't consider that worthwhile in cases like this.

So we can get rid of the `try`/`except` blocks in `test_liquid_probe_with_recovery()` and just leave the `decoy.verify()`.

2024-07-08 16:28 UTC, SyntaxColoring approved these changes
This looks good to me to merge once the `print()` statement is removed.

One note about `test_liquid_probe_without_recovery()` for future reference, but I think we can move on for now.

2024-07-08 16:28 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        print("I got here")
Print statement left over from debugging?

```suggestion
```

2024-07-08 16:28 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_api/core/engine/test_instrument_core.py
> +    with pytest.raises(PipetteLiquidNotFoundError):
This `pytest.raises` is covering a `raise` that we're saying should never happen (your `# should never get here` comment), and which is happening only because this test didn't set up the mock `self._engine_client.execute_command_without_recovery()` call to return a realistic result.

I think this test should:

1. Rehearse (using `decoy.when()`) `mock_engine_client.execute_command_without_recovery()` to return a realistic result. Like [this outline in the Decoy documentation](https://michael.cousins.io/decoy/usage/when/#configuring-a-stub).
2. Call `subject.liquid_probe_without_recovery()`
3. Assert that the return value matches what we expect: that the subject has pulled the proper data out of the realistic result that we fed it
4. *Not* do `decoy.verify()`, because it's redundant if we're doing `decoy.when()`, so [Decoy doesn't want us to do that](https://michael.cousins.io/decoy/usage/errors-and-warnings/#redundantverifywarning).

2024-07-08 18:27 UTC, aaron-kulkarni commented on api/tests/opentrons/protocol_api/core/engine/test_instrument_core.py
> +    with pytest.raises(PipetteLiquidNotFoundError):
After discussion in slack, test has been edited to cover both error and success cases. Also, the raise error at the end has been deleted since it's unnecessary.

2024-07-08 18:40 UTC, merged