feat(robot-server): add protocol_kind query arg to GET protocols endpoint.
OpenTrons/opentrons-api pull request #15589
Opened 2024-07-06 18:47 UTC by vegano1

# Overview

The client app needs to filter out protocols based on their kind, this pull request allows that at the server side by adding a `protocol_kind` query arg to the `GET /protocols` endpoint.

Closes: [PLAT-330](https://opentrons.atlassian.net/browse/PLAT-330)

# Test Plan

- [ ] Make sure that omitting the 'protocol_kind' query arg returns ALL protocols
- [ ] Make sure that only `standard` protocols are returned when `protocol_kind=standard`
- [ ] Make sure that only `quick-transfer` protocols are returned when `protocol_kind=quick-transfer`
- [ ] Make sure that we return a 400 when the `protocol_kind` is invalid

# Changelog

- Add `protocol_kind` query arg to the `GET /protocols` endpoint

# Review requests

# Risk assessment

Low, unreleased feature

2024-07-08 13:46 UTC, sfoster1 approved these changes
Looks good but I think the mention in the docstring is redundant

2024-07-08 13:46 UTC, sfoster1 commented on robot-server/robot_server/protocols/router.py
> +    You can provide the kind of protocol with the `protocol_kind` query arg
This I think is automatically documented in the openapi spec and doesn't need to be repeated here

2024-07-08 13:46 UTC, sfoster1 commented on robot-server/robot_server/protocols/router.py
> +        Note: all protocols will be provided if the `protocol_kind` query arg is ommited.
```suggestion
        Note: all protocols will be provided if the `protocol_kind` query arg is omitted.
```

2024-07-08 14:53 UTC, ahiuchingau approved these changes
LGTM!

2024-07-08 16:01 UTC, SyntaxColoring requested changes
TY!

2024-07-08 16:01 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +    protocol_kind: Optional[ProtocolKind] = Query(
Camel case `protocolKind`, please. (We updated our [guidelines](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/575078506/HTTP+API+style) recently.)

2024-07-08 16:01 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +        - `quick-transfer` for Quick Transfer protocols
Can we make this `quickTransfer` instead of `quick-transfer` (following [our recently updated guidelines](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/575078506/HTTP+API+style)), or will that be a database pain for you at this point?

2024-07-08 16:01 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +        if (protocol_kind in [None, r.protocol_kind])
Can we move this filtering into SQL? i.e. add a `protocol_kind` parameter to `ProtocolStore.get_all()`?

This can happen in another PR if it needs to, but it's generally easier to fix stuff like this earlier rather than later.

2024-07-09 19:26 UTC, SyntaxColoring approved these changes
TY!

2024-07-09 19:26 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +        if (protocol_kind in [None, r.protocol_kind])
Discussed in person and I think you mentioned you'll look into this in another PR.

2024-07-10 13:06 UTC, merged