feat(app): Add Aspirate and Dispense for Quick Transfer advanced settings.
OpenTrons/opentrons-api pull request #15593
Opened 2024-07-07 21:57 UTC by vegano1

# Overview

Adds the Aspirate and Dispense settings to the Quick Transfer Advanced Settings tab, which lets you change the specific behavior of the quick transfer protocol for precise control of the protocol generated.

Closes: [PLAT-222](https://opentrons.atlassian.net/browse/PLAT-222) [PLAT-223](https://opentrons.atlassian.net/browse/PLAT-223)

# Test Plan

- [ ] Make sure that the Quick Transfer protocol file generated reflects the advanced settings chosen when it was created.
- [ ] Run the Quick Transfer protocol and make sure that the "Pipette path" option is respected based on the transfer type.
- [ ] Run the Quick Transfer protocol and make sure that the "Blowout" option is respected.
- [ ] Make sure that the input limits are being followed for all the various options.

# Changelog

- Refactored the Quick Transfer Advanced Settings tab so the components are on one page instead of having "BaseSettings", "AspirateSettings", and "DispenseSettings" components as this led to component rendering issues.
- Added "TipPosition", "Blowout", "FlowRate", "AirGap", "TouchTip", "PipettePath", "Mix", and "Delay" components.
- The above components are shared between aspirate and dispense settings, as they render differently based on the kind.

# Review requests

- Any styling issues?
- Does this make sense?
- Please take a look at the range mins and max as right now they are placeholders, where can I find this data?
- Please also take a look at the options and point out which options would invalidate another.

# Risk assessment

Low, unreleased feature.

# TODO:
- [ ] Add min/max ranges for various options, need to find data.
- [ ] Add disabling of options based on the combination of settings, I'm not sure what all the combinations are yet.
- [ ] Add snackbar for disabled options, need to find data of when options are disabled

2024-07-08 14:03 UTC, jerader commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/TouchTip.tsx
> +export function TouchTip(props: TouchTipProps): JSX.Element {
touch tip is only allowed if the labware does not have `touchTipDisabled` included in the labware's quirks.

2024-07-08 14:06 UTC, jerader commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/AirGap.tsx
> +  const volumeRange = { min: 1, max: 100 }
the max here should depend on the volume left in the tip after aspirating.

2024-07-08 14:08 UTC, jerader commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/Delay.tsx
> +      : null
these errors seems like a lot of repeated logic, i recommend pulling it out into a util that each component can import and use.

2024-07-08 14:09 UTC, jerader commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/Mix.tsx
> +  const maxVolume = 100
these min and max volumes should match the tip's min and max volumes

2024-07-08 14:10 UTC, jerader commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/Mix.tsx
> +  const maxReps = 100
do we need a max here? 😅

2024-07-08 14:41 UTC, jerader commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/Delay.tsx
> +  const positionRange = { min: 1, max: 100 }
this range should be based off of the height of the labware i think? like we don't want the user to smash into the labware if its too low or move too high above the labware

2024-07-08 14:42 UTC, jerader commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/TipPosition.tsx
> +  const tipPositionRange = { min: 1, max: 2 } // TODO: set this based on range
range should be based off the height of the labware i think.

2024-07-08 14:43 UTC, jerader commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/TouchTip.tsx
> +  const positionRange = { min: 1, max: 100 }
same here, should be based off of the height of the labware

2024-07-08 14:44 UTC, jerader reviewed
i did a quick read through and it looks good so far! nice work! i also did some smoke testing (only with n:n transfers so far) and from what i can tell, the commands are generated as expected 🎉

2024-07-08 19:09 UTC, jerader commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/Delay.tsx
> +  const positionRange = { min: 1, max: 100 }
thinking about this value more and digging into step-generation, I don't think delay position is actually wired up in step-generation?

2024-07-08 19:14 UTC, jerader commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/Delay.tsx
> +  const positionRange = { min: 1, max: 100 }
whooops nevermind it totally is! my bad

2024-07-09 14:17 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/AirGap.tsx
> +    if (selectedOption === 'Enabled') {
I think instead of having a string "enabled" as the option, we should have this be a boolean that maps `true` to "enabled" text and `false` to "disabled"

2024-07-09 14:18 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/AirGap.tsx
> +  let Action:
action here should be lowercase - we use camel case for all variable names and capitalize the first letter for typescript types!

2024-07-09 14:25 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/AirGap.tsx
> +  const volumeRange = { min: 1, max: 100 }
yep! I think you'll need to replicate some of the logic in `getVolumeRange` here, but we should only need to grab the pipette and tip capacity, and take the lesser of the two. The and then if `state.path` is single the max would be ((lesser of pipette and tip capacity)- state.volume), if it's multi we'd have to do ((lesser of pipette and tip capacity)- (state.volume * 2))

2024-07-09 14:27 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/BlowOut.tsx
> +    if (selectedOption === 'Enabled') {
same comments as above apply throughout for making the option a boolean and Action lowercase!

2024-07-09 14:29 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/BlowOut.tsx
> +          {displayItems.map(option => (
```suggestion
          {displayItems.map(displayItem => (
```
would make this a little more readable so we don't have `option.option` below!

2024-07-09 14:34 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/BlowOut.tsx
> +  const blowOutLocationItems = [
We need to grab the trash bin and waste chute location items from the user's deck config -- you can see this done in the `TipDropLocation` options as a reference! That way we can display to the user a _specific_ trash bin or waste chute instead of trying to find one later on. The type for this may need to change to `source_well` | `dest_well` | CutoutConfig

2024-07-09 14:36 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/Delay.tsx
> +  const delayRange = { min: 1, max: 100 }
I don't know that we need a specific range for these values, I would imagine we let them delay for however long they want.

2024-07-09 14:40 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/Delay.tsx
> +  const positionRange = { min: 1, max: 100 }
Yeah it looks like the default and min is 1 mm from bottom of the well, and we can allow them to enter a value 2x the height of the well which can be grabbed from the labware def!

2024-07-09 14:42 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/Mix.tsx
> +  const maxVolume = 100
I think the max here should be the lesser of the max value from `getMinVolumeRange` and `state.volume` and then min can be the same as the min from `getMinVolumeRange`

2024-07-09 14:43 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/Mix.tsx
> +  const maxReps = 100
looks like PD does not have a max!

2024-07-09 14:45 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/Mix.tsx
> +    (mixVolume !== null && (mixVolume < minVolume || mixVolume > maxVolume)) ||
Lets separate this out so that it's based on the currentStep -- 
if (currentStep === select_volume) error =  mixVolume !== null && (mixVolume < minVolume || mixVolume > maxVolume)

2024-07-09 14:47 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/PipettePath.tsx
> +    state.blowOut ?? 'trashBin'
Same comment applies here about grabbing a `trashBin` or `wasteChute` if there is one configured in the deck config

2024-07-09 14:47 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/PipettePath.tsx
> +        console.log({ selectedOption, volume, blowOutLocation })
leftover console statement!

2024-07-09 14:48 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/PipettePath.tsx
> +  const volumeRange = { min: 1, max: 100 }
Comments from `BlowOut.tsx` about volume range apply here too!

2024-07-09 14:51 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/PipettePath.tsx
>    if (state.sourceWells.length === 1 && state.destinationWells.length > 1) {
we also need to take in consideration the volume here -- I think this logic should be:

```suggestion
    if (
    state.transferType === 'consolidate' &&
    volumeLimits.max >= state.volume * 2
  ) {
    allowedPipettePathOptions.push('multiDispense')
  } else if (
    state.transferType === 'distribute' &&
    volumeLimits.max >= state.volume * 2
  ) {
    allowedPipettePathOptions.push('multiAspirate')
  }
```

2024-07-09 14:53 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/AirGap.tsx
> +  const volumeRange = { min: 1, max: 100 }
actually for multiAspirate we'd do volume*2 but for multiDispense it'd be volume*3

2024-07-09 14:56 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/PipettePath.tsx
> +  const setSaveOrContinueButtonText = (): string => {
```suggestion
  const setSaveOrContinueButtonText =  selectedOption === 'multiAspirate' && currentStep < flowSteps.length - 1
        ? t( 'shared:continue')
        : t('shared:save')
```

2024-07-09 14:59 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/TipPosition.tsx
> +  const tipPositionRange = { min: 1, max: 2 } // TODO: set this based on range
yep looks like for PD the logic here is that the min and default are both 1 and the max is 2x the height of the well

2024-07-09 15:01 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/TouchTip.tsx
> +  const positionRange = { min: 1, max: 100 }
yep here it looks like the default should be (height of well - 1) and the range should be (half height - height)

2024-07-09 15:02 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/index.tsx
> +import { useToaster } from '../../../organisms/ToasterOven'
this import can be removed

2024-07-09 15:02 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/index.tsx
> +import { useTranslation } from 'react-i18next'
this import should be moved to the top of the list!

2024-07-09 15:07 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/index.tsx
> +      enabled: true,
Your logic below uses this `enabled` field to determine whether to show the arrow icon, so for this field we'll need to have an exception. Maybe we keep this as true but below change the logic so the icon doesn't appear for this line

2024-07-09 15:08 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/reducers.ts
> +    case 'SET_VOLUME': {
What was this case added for? we have a `SET_VOLUME` above

2024-07-09 15:11 UTC, smb2268 requested changes
The UX here looks great! This has been a ton of work, thanks for digging into all of it. I added in comments with what I think the logic should be at each step. It may be tricky because many are based on the height of the well which means they won't be consistent between aspirate and dispense - let me know if you want to go over any of this!

2024-07-09 15:13 UTC, smb2268 commented
Situations in which we should disable certain settings from felix:
If transfer type = distribute, disable mix and blowout, add disposal volume
If transfer type = consolidate, disable mix
If labware = reservoir, disable touch tip

2024-07-11 18:00 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/Delay.tsx
> +        state.source !== null ? state.source.wells[well].depth : 0
This should be != null, which checks for both `null` and `undefined`

2024-07-11 18:00 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/BlowOut.tsx
> +  type DeckConfiguration,
let's separate this import out to a separate line at the bottom of the import list

2024-07-11 18:00 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/Delay.tsx
> +        destLabwareDefinition !== null ? destLabwareDefinition.wells[well].depth : 0
This should also be != instead of !==

2024-07-11 18:00 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/TipPosition.tsx
> +        state.source !== null ? state.source.wells[well].depth : 0
same here and below!

2024-07-11 18:00 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/TouchTip.tsx
> +        state.source !== null ? state.source.wells[well].depth : 0
Same here

2024-07-11 18:00 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/index.tsx
> +      enabled: state.sourceWells.length > 1,
This check isn't sufficient to determine whether a labware is a reservoir since a user can also select just 1 well in a well plate and there are reservoirs with more than 1 well. Instead we should use `state.source.metadata.displayCategory !== 'reservoir'`

and for destination we'll need to do the same thing but make sure we have the correct labware definition:
`const destinationLabwareDef = state.destination === 'source' ? state.source | state.destination`
`destinationLabwareDef.metadata.displayCategory !== 'reservoir'`

2024-07-11 18:08 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/reducers.ts
> +    case 'SET_VOLUME': {
This can be removed! I added to the SET_PIPETTE_PATH action to accept the disposal volume and blowout location

2024-07-11 18:08 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/types.ts
> +  blowOut?: BlowOutLocation // trashBin or wasteChute or 'SOURCE_WELL' or 'DEST_WELL'
let's remove this comment since it's no longer accurate

2024-07-11 18:08 UTC, brenthagen commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/index.tsx
> +      enabled: true,
should probably disable if max available capacity is 0:

<img width="1136" alt="Screen Shot 2024-07-11 at 1 52 38 PM" src="https://github.com/Opentrons/opentrons/assets/29845468/cee1528a-8289-4474-8660-3696dee15cc1">

2024-07-11 18:09 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/utils/generateQuickTransferArgs.ts
> +  CutoutConfig,
this needs to be imported as a type on a separate line at the bottom of the imports

2024-07-11 18:13 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/index.tsx
> +      enabled: true,
That's a good call out - I can tackle this in a follow on since it'd involve separating out some of the volume range logic into a util

2024-07-11 18:36 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/index.tsx
> +      enabled: !isReservoir,
```suggestion
      enabled: state.source.metadata.displayCategory !== 'reservoir',
```

2024-07-11 18:37 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/index.tsx
> +      enabled: !isReservoir,
We should only disable touchTip aspirate if the source labware is a reservoir and touchTip dispense if the destination labware is a reservoir!

2024-07-11 18:38 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/utils/generateQuickTransferArgs.ts
> +    sourceLabware: sourceLabwareEntity?.id!,
I'm not familiar with the `!` at the end - is that a replacement for type casting?

2024-07-11 18:40 UTC, vegano1 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/index.tsx
> +      enabled: !isReservoir,
The `isReservoir` const checks if both the source and destination are reservoir which should be sufficient here no?

2024-07-11 18:40 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/utils/generateQuickTransferArgs.ts
> +    sourceLabware: sourceLabwareEntity?.id!,
ah I see, cool - https://stackoverflow.com/questions/42273853/in-typescript-what-is-the-exclamation-mark-bang-operator-when-dereferenci

2024-07-11 18:43 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/index.tsx
> +      enabled: !isReservoir,
This would disable `touchTip` for _both_ aspirate and dispense if _either_ source or destination labware is a reservoir. We should only disable it for the action that is directly involving the reservoir! So that if the source labware is a well plate and dest labware is a reservoir, `touchTip` will be enabled for aspirate but disabled for dispense

2024-07-11 18:45 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/index.tsx
> +      enabled: !isReservoir,
so you'll want that change and then on line 267 you should have 
` enabled: destinationLabwareDef.metadata.displayCategory !== 'reservoir',`

2024-07-11 18:47 UTC, vegano1 commented on app/src/organisms/QuickTransferFlow/utils/generateQuickTransferArgs.ts
> +    sourceLabware: sourceLabwareEntity?.id!,
The non-null assertion operator states that even if the variable can be `undefined`, it should never be undefined by this point so tell the compiler to ignore it. It seems like this was added by auto-fixing with eslint. Regardless I think I still need to cast to string here.

2024-07-11 18:47 UTC, vegano1 commented on app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/index.tsx
> +      enabled: !isReservoir,
gotcha! that makes sense

2024-07-11 18:50 UTC, smb2268 approved these changes
once the reservoir change is in and tests are passing this is good to merge 🚀

2024-07-11 18:52 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/types.ts
> +  | SetVolumeAction
If you remove this unused `SetVolumeAction` type the ts error in the `reducers` file should go away!

2024-07-11 18:59 UTC, smb2268 commented on app/src/organisms/QuickTransferFlow/utils/generateQuickTransferArgs.ts
> +    sourceLabware: sourceLabwareEntity?.id!,
Yeah looks like our linter has `Forbidden non-null assertion` errors for these so if you switch them back tests should pass!

2024-07-11 20:00 UTC, merged