fix(api): change error checks in liquid_probe
OpenTrons/opentrons-api pull request #15594
Opened 2024-07-08 14:28 UTC by aaron-kulkarni

# Overview

Delete the error checks in execute and replace them with individual, specific checks for tip presence, working volume, and pipette position

fix EXEC-591

# Test Plan

Plan is to edit the unit tests in test_liquid_probe.py and make sure the proper errors are being raised.

# Changelog

Changes are so far contained to the execute function in liquid_probe.py

# Review requests

I'm not sure how to do the working volume check in this function without breaking some layer of abstraction or by editing other classes.

# Risk assessment

Low.

2024-07-08 20:54 UTC, sfoster1 requested changes
Definitely looks good as a whole but there's some stuff we can improve!

2024-07-08 20:54 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/liquid_probe.py
> +        # throw error if pipette has no tip
Comments like these that exactly duplicate functionality aren't necessary and mostly end up as out-of-date confusion elements. Comments should really only exist if they are some of:
- Explaining something that is sufficiently not explained by the code itself that there's no overlap in the words used between the two
- TODO comments, explicitly with TODO in them
- explaining the _why_ of something

2024-07-08 20:54 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/liquid_probe.py
> +        # throw error if plunger isn't in valid position
same with this comment - `valid position` is a sequence of words that's also in the code this comment is for

2024-07-09 15:50 UTC, ryanthecoder commented on api/src/opentrons/protocol_engine/commands/liquid_probe.py
> +            PositionUnknownError: if the plunger is not in a valid position
You're raising a MustHomeError below so just update the error here

2024-07-09 15:51 UTC, ryanthecoder approved these changes
Looks good just a few comment tweaks

2024-07-09 17:12 UTC, sfoster1 approved these changes
Nice work!

2024-07-09 17:18 UTC, merged