fix(hardware_control): Fixing liquid probe bugs found in end to end testing
OpenTrons/opentrons-api pull request #15619
Opened 2024-07-10 21:34 UTC by ryanthecoder

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-07-10 21:56 UTC, sfoster1 requested changes, later dismissed
Some style and consistency stuff to fix up. Also, let's get a nicer description in here.

2024-07-10 21:56 UTC, sfoster1 commented on api/lldfunctionexamples.py
> +from opentrons import protocol_api, types
We shouldn't check this in, I think. I don't think this is a good location for it.

2024-07-10 21:56 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        # if output_option == OutputOptions.sync_buffer_to_csv:
Delete rather than checking in commented otu code

2024-07-10 21:56 UTC, sfoster1 commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        loc = Location(well_core.get_top(10), "Well")
let's get this value from some config instead of it being a specific number literal

2024-07-10 21:56 UTC, sfoster1 commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        loc = Location(well_core.get_top(10), "Well")
same here, but actually we can just reuse the `loc` value, it's the same well correct?

2024-07-10 22:29 UTC, SyntaxColoring requested changes

2024-07-10 22:29 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        )
Why do we need to do this? Doesn't the `liquidProbe` Protocol Engine command already move to the target well?

2024-07-10 22:29 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        )
We probably do need to update PAPI's logical "current well" bookkeeping, though. Like how `aspirate()` and `dispense()` do `self._protocol_core.set_last_location()`.

2024-07-10 22:29 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        loc = Location(well_core.get_top(10), "Well")
I'm also just noticing that our public `InstrumentContext` methods don't have a way of specifying an X/Y/Z offset, but the `liquidProbe` Protocol Engine command does (although [it's a work in progress](https://opentrons.slack.com/archives/C06M9F26YGH/p1719937084438019)).

Is the difference intentional?

CC @pmoegenburg since you were working on the Protocol Engine side.

2024-07-10 22:29 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        loc = Location(well_core.get_top(10), "Well")
`Location(well_core.get_top(10), "Well")` doesn't look like a valid way to construct a `Location`. It's trying to set the `.labware` attribute to a deck slot named `"Well"`. You might have intended to provide an actual instance of the `Well` class, or another value that's valid [per the types of this union](https://github.com/Opentrons/opentrons/blob/edge/api/src/opentrons/types.py#L111-L117).

Also keep in mind that `InstrumentContext` can be the thing that calls `InstrumentCore.move_to()`. I suspect that will be easier because you'll have better access to the things you'll need to build a `location` argument.

2024-07-11 15:45 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        )
Discussed in-person. This is working around a weird problem with path planning, which we're looking into.

2024-07-12 17:35 UTC, ryanthecoder commented on api/src/opentrons/protocol_engine/commands/liquid_probe.py
> +            TipNotEmptyError: if the tip starts with liquid in it(AKA it's wet and unusable for LLD)
So a tip can theoretically be wet and also empty, if we've used it before and then emptied it. So lets leave out that AKA part

2024-07-12 17:38 UTC, aaron-kulkarni commented on api/src/opentrons/protocol_api/core/engine/instrument.py
> +        )
Fixed, we were setting CurrentWell incorrectly in liquidProbe

2024-07-15 20:16 UTC, ryanthecoder commented on api/src/opentrons/protocol_api/instrument_context.py
> +            if isinstance(e.original_error, LiquidNotFoundError) or isinstance(
I'm not sure we should catch Stall's here, that's something that needs to be recovered from and if we've caused a stall then we've done something else wrong

2024-07-15 20:38 UTC, SyntaxColoring approved these changes
This all looks good to me assuming others' pending comments have been resolved. Some small final notes:

2024-07-15 20:38 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +            self.prepare_to_aspirate()
Do we need this `self.prepare_to_aspirate()` call? It looks like this is [currently being handed in the `opentrons.protocol_engine` layer?](https://github.com/Opentrons/opentrons/blob/8b88dda01afa364464de3f1506763b1ec08adc6d/api/src/opentrons/protocol_engine/commands/aspirate.py#L104) Did you find that this was necessary for it to work?

2024-07-15 20:38 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/liquid_probe.py
> -
Ah, yep, that'd do it. Nice catch.

2024-07-15 20:38 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +        return self._state_view.pipettes.get_aspirated_volume(pipette_id) == 0
Does the docstring here need to be updated?

2024-07-15 20:38 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +        return self._state_view.pipettes.get_aspirated_volume(pipette_id) == 0
Does the docstring here need to be updated?

2024-07-15 20:45 UTC, aaron-kulkarni commented on api/src/opentrons/protocol_api/instrument_context.py
> +            self.prepare_to_aspirate()
Yes, I thought it should be unnecessary too. But if I didn't have this prepare_to_aspirate, it was not aspirating any liquid at all after liquid probing.

2024-07-15 20:46 UTC, aaron-kulkarni commented on api/src/opentrons/protocol_engine/execution/pipetting.py
> +        return self._state_view.pipettes.get_aspirated_volume(pipette_id) == 0
Yes, thanks for noticing that.

2024-07-15 21:34 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +            self.prepare_to_aspirate()
OK, let's keep it for now to unblock testing, but let's keep looking into it. Might be worth leaving a `# todo` comment.

2024-07-16 12:59 UTC, merged