refactor(robot-server): move run time params to their own DB table
OpenTrons/opentrons-api pull request #15650
Opened 2024-07-15 14:59 UTC by sanni-t

Closes AUTH-527

# Overview

This PR moves primitive RTPs to their own table and changes the order of the analysis-generation process.

Destailed description coming up

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-07-16 15:27 UTC, SyntaxColoring requested changes
Working my way through this, looks great, thanks! Here are some requests.

2024-07-16 15:27 UTC, SyntaxColoring commented on robot-server/robot_server/persistence/_files_and_directories.py
> +"""Files and directories in persistent storage."""
Good idea, thanks.

2024-07-16 15:27 UTC, SyntaxColoring commented on robot-server/robot_server/persistence/tables/schema_5.py
> +        "parameter_variable_name",
~~It might make sense to throw in [`unique=True`](https://docs.sqlalchemy.org/en/20/core/constraints.html#unique-constraint) on the `parameter_variable_name` column.~~

Whoops, no, sorry, definitely not just on the `parameter_variable_name` column. It would need to be on the `"analysis_id", "parameter_variable_name"` combination.

This is just a nice-to-have.

2024-07-16 15:27 UTC, SyntaxColoring commented on robot-server/robot_server/persistence/_migrations/v4_to_v5.py
> +  as part of the completed analysis blob.
I think schema 5 is widely distributed enough, and these changes are fundamental enough to what schema 5 "is," that we should move to a fresh directory instead of continuing to use `5/`.

If any of the bots that are currently on schema 5 (SW dev bots, QA bots, maybe ABR?) upgrade to these changes, things will break because `analysis_primitive_type_rtp_table` will be missing, and the server won't know that it needs to run a migration.

I think we could still call this "schema 5" and just change the directory from `5/` to, say, `5.1/`:

https://github.com/Opentrons/opentrons/blob/2ff941786feff0b20d9df3d475db96d7f9a88c92/robot-server/robot_server/persistence/persistence_directory.py#L54

So in other words, we'd be replacing `3/ -> 4/ -> 5/` with `3/ -> 4/ -> 5.1/`.

This would pull everyone's run and protocol history back in time to what it was in schema 4, which is unfortunate and which we'll have to communicate, but it's better than the alternatives, I think.

2024-07-16 15:27 UTC, SyntaxColoring commented on robot-server/robot_server/persistence/tables/schema_5.py
<strike>This is completely unrelated to your work, but @vegano1 and I noticed that `protocol_table` is missing an index on its `protocol_kind` column, now that the HTTP API is querying it. If you end up making a schema break anyway, it might make sense to throw that in with your changes.

[Edit] And I remember now that the `protocol_kind` column also does not have to be nullable, and it can be [an enum](https://github.com/Opentrons/opentrons/pull/15650#discussion_r1679579117).

But don't worry about it if it complicates anything.</strike>

Off-topic for this PR.

2024-07-16 15:27 UTC, SyntaxColoring commented on robot-server/robot_server/persistence/tables/schema_5.py
> +        sqlalchemy.String,
Can we use a [`sqlalchemy.Enum`](https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Enum) for `parameter_type` instead of a plain `sqlalchemy.String`, to make this more self-documenting and to make it harder to store incorrect values in the future?

We haven't used `sqlalchemy.Enum` before, so we'll need to set the pattern. I suggest:

* We should use a new `Enum` class that's just for the database, and not reused from the HTTP API, and explicitly map back and forth. This is a pretty soft opinion, so definitely feel free to share one enum if you think that turns out better. I guess I'm worried about entangling Pydantic+FastAPI with SQLAlchemy any more than necessary.
* We should not inherit the enum class from `str`, but we should still give each enum value a string representation, like `FOO = "bar"`.
* We should use [`values_callable`](https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Enum.params.values_callable) to get SQLAlchemy to store the enum values (`"bar"`) instead of their names (`FOO`). I don't know about you, but it's pretty surprising to me that it would store the names by default.
* We should use [`create_constraint=True`](https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Enum.params.create_constraint) because I'm pretty sure SQLite will not do that natively, and having a constraint seems like a good idea.

2024-07-16 16:49 UTC, SyntaxColoring commented on robot-server/robot_server/persistence/_migrations/v4_to_v5.py
> +            schema_4.metadata.create_all(source_engine)
Nitpick: This `create_all()` call should no-op, because the source should be provided to us already complete and conformant to schema v4. Can we remove it for clarity?

This might have been copied from `up_to_3.py`? It was needed there basically because it was *up to 3* as opposed to *2 to 3.* It's confusing and I should have fixed it, sorry.

2024-07-16 16:49 UTC, SyntaxColoring commented on robot-server/robot_server/persistence/_migrations/v4_to_v5.py
> +        order_by_rowid=True,
Nitpick: I think this is harmless, but `order_by_rowid` can be `False` for `run_command_table` because it has explicitly-declared `row_id` and `index_in_run` columns.

I wonder if `order_by_rowid=True` is actually any slower or more memory-hungry than `=False`. Maybe it should just always be `True` to simplify things.

2024-07-16 16:49 UTC, SyntaxColoring commented on robot-server/robot_server/persistence/_migrations/v4_to_v5.py
> +            # run_time_parameter_values_and_defaults column is omitted
It looks like we're dropping the old column here and not copying its data into the new table. Is that correct?

If so, is that safe? e.g. from a caching perspective, won't it look like a protocol has been successfully analyzed without any parameter values, whereas in fact it *did* need parameter values, and they were just lost in the migration?

If it's a pain to migrate the actual RTP values, we could consider outright dropping *all* of the analysis data. It's supposed to be repeatable, anyway, so the worst case is that the robot just does it anew the next time they try to run the protocol, right?

2024-07-16 16:49 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/rtp_resources.py
> +            "bool": bool,
I don't think this serialization/deserialization strategy for `bool` will work.

`to_sql_values()` returns `str(self.parameter_value)`, e.g. `str(False)`, which is `"False"`.

But then, going the other way, `from_sql_row()` will do `bool(parameter_value)`, e.g. `bool("False")`, which is `True`.

2024-07-16 16:49 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/rtp_resources.py
> +            return converted_num
Could you clarify what this is doing? I can't see why `int(value)` would fail.

2024-07-16 16:49 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/rtp_resources.py
> +            "bool": bool,
If we still want every primitive RTP type to share one table, I would consider using `json.dumps()`/`json.loads()` just for the sake of not having to roll our own serialization/deserialization. We would use JSON for *just `parameter_value`*, basically replacing this callable dict, not for `parameter_variable_name` or `parameter_type`. As long as we stick to JSON scalars, it won't introduce formatting or field ordering nondeterminism concerns.

2024-07-16 19:28 UTC, SyntaxColoring reviewed
Final set of comments.

2024-07-16 19:28 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/protocol_analyzer.py
> +    async def load_orchestrator(
Thanks for this rename.

2024-07-16 19:28 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/protocol_store.py
> +        analyses_using_protocol = self._get_referencing_analysis_ids(protocol_id)
This is opening a transaction to get some data, then computing things to delete, then opening a separate transaction to do the deletion. For atomicity and isolation, can we bring this under one transaction?

There are a few ways to do this. Here's one.

Right now, in this:

```python
        delete_analysis_rtps_statement = sqlalchemy.delete(
            analysis_primitive_type_rtp_table
        ).where(
            analysis_primitive_type_rtp_table.c.analysis_id.in_(analyses_using_protocol)
        )
```

You're passing the separately-computed Python list, `analyses_using_protocol`, as the argument. You can actually pass a `sqlalchemy.select()` construct instead and keep all of the logic inside SQL. Something like:

```python
        delete_analysis_rtps_statement = sqlalchemy.delete(
            analysis_primitive_type_rtp_table
        ).where(
            analysis_primitive_type_rtp_table.c.analysis_id.in_(
                sqlalchemy.select(analysis_table.c.id).where(analysis_table.c.protocol_id == protocol_id)
            )
        )
```

You could also do this with some kind of join. Whatever you think is clearer.

2024-07-16 19:28 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/protocol_analyzer.py
> +        """Get the extracted RTPs."""
Could you elaborate a little here on why we're calling these "verified" run time parameters?

2024-07-16 19:28 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/analysis_store.py
> +            primitive_rtp_resources=[],
Is `primitive_rtp_resources=[]` right? If an analysis has one of these errors, shouldn't we store that the analysis was attempted with the RTP values that it was actually attempted with? If we don't, I'm a little worried about the implications of this for caching.

Maybe I'm getting confused about whether this column represents the *actual fully-resolved* RTP values or merely the *client-supplied* RTP values.

2024-07-16 19:28 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/analysis_store.py
>              for analysis_id in completed_analysis_ids
Just making sure, are you intentionally removing this `# todo` comment without populating `AnalysisSummary`'s `runTimeParameters` field here?

2024-07-16 19:28 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +            # The most recent analysis was done using different RTP values
Hypothetically, is it correct that the data is accessible enough now that we could efficiently check *all* analyses, not just the most recent one?

2024-07-17 16:46 UTC, sanni-t commented on robot-server/robot_server/persistence/_migrations/v4_to_v5.py
> +  as part of the completed analysis blob.
I think that's a good idea

2024-07-17 16:57 UTC, sanni-t commented on robot-server/robot_server/protocols/router.py
> +            # The most recent analysis was done using different RTP values
Yep!

2024-07-17 17:11 UTC, sanni-t commented on robot-server/robot_server/protocols/rtp_resources.py
> +            "bool": bool,
Darn! Good catch!! 
Hmm, alright, going to see if using json would be better than special-casing booleans

2024-07-17 17:12 UTC, sanni-t commented on robot-server/robot_server/protocols/rtp_resources.py
> +            return converted_num
`int("5.0")` fails. We allow having `5.0` as a valid integer param value.

2024-07-17 17:17 UTC, sanni-t commented on robot-server/robot_server/protocols/analysis_store.py
> +            primitive_rtp_resources=[],
> Maybe I'm getting confused about whether this column represents the actual fully-resolved RTP values or merely the client-supplied RTP values.

It represents the fully-resolved RTP values.

> Is primitive_rtp_resources=[] right? If an analysis has one of these errors, shouldn't we store that the analysis was attempted with the RTP values that it was actually attempted with? If we don't, I'm a little worried about the implications of this for caching.

I have been thinking about this, although more from a troubleshooting perspective. Let me write down the different data that gets saved when analysis fails at different stages and we can discuss if/ how to improve the rtp error handling.

2024-07-17 17:19 UTC, sanni-t commented on robot-server/robot_server/protocols/analysis_store.py
>              for analysis_id in completed_analysis_ids
er.. I am confused at my own comment

2024-07-17 17:23 UTC, sanni-t commented on robot-server/robot_server/persistence/_migrations/v4_to_v5.py
> +            # run_time_parameter_values_and_defaults column is omitted
> won't it look like a protocol has been successfully analyzed without any parameter values, whereas in fact it did need parameter values, and they were just lost in the migration?

The parameters also get saved as part of the full analysis and that's what the app uses for getting parameters' info. The `run_time_parameter_values_and_defaults` column was only used internally to check if the last analysis' parameters match the ones in the new request. So what will happen here is that the migration will still keep info of the RTPs in each of the persisted analyses but when the internal code tries to check for previous RTP values, it will just not find any matching values and will initiate a new analysis (*see note below). And it sounds like that's the behavior you were proposing too.

Removing analyses for uploaded protocols will be tougher to handle, especially because the ODD relies on analysis info to show the protocols on the screen. Without any analyses, it will just show all protocols with errors.

(*as I was typing this, I realized I have added a check that verifies that parameters defined in last analysis are same as in current analysis. As in, if the last analysis has three RTPs, then the new analysis should also contain the same three parameters, which could have different values obviously. In order for my above described behavior, I will need to make an exception for when there were no RTPs found corresponding to the last analysis, and I think that's acceptable)

2024-07-23 18:15 UTC, sanni-t commented on robot-server/robot_server/protocols/protocol_analyzer.py
> +        """Get the extracted RTPs."""
Because they are the full, validated params, as opposed to the RTP key-value pairs received from a client.

2024-07-23 18:20 UTC, sanni-t commented on robot-server/robot_server/persistence/_migrations/v4_to_v5.py
> +  as part of the completed analysis blob.
Talked with the team and we've decided to put these changes inside a new version so that the internal, v5 changes aren't lost. That means for someone on v4, there will be a transient v5 folder introduced and the migration will take slightly longer because of having to do 2 migrations, but v4 to v5 only involves addition of a new column ('protocol kind') while rest of the DB is copied as is, so it shouldn't be too time consuming. What do you think?

2024-07-24 14:41 UTC, sanni-t reviewed
Notes from meeting:
- Update the persistence snapshot tests to include RTP checks.

2024-07-24 16:06 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/rtp_resources.py
> +    parameter_type: str
Does `parameter_type` need to change, or can it change, to an `Enum`, now that the underlying column is a SQLAlchemy enum?

I would expect SQLAlchemy to give us the enum, not the str, when we do `results = transaction.execute(statement).all()`. But maybe I'm misunderstanding something.

2024-07-24 16:06 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/rtp_resources.py
> +            return converted_num
I think I'm confused, sorry.

I understand why you'd want to treat `5.0` as a valid integer param for the HTTP API and any other JSON documents, because JavaScript and JSON don't distinguish between ints and floats.

But are you saying that we're also constructing instances of this class where `parameter_type` is `"int"` and `parameter_value` is `5.0`, and then storing `("int", "5.0")` in SQL? If so, can we not do that? I'd find it pretty surprising.

2024-07-24 16:47 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/protocol_store.py
> +            .order_by(sqlite_rowid)
Nitpick: no need for this `.order_by` since we're just testing that things exist in this set, not returning it as an ordered list.

```suggestion
```

2024-07-24 16:47 UTC, SyntaxColoring commented on robot-server/robot_server/persistence/_migrations/v4_to_v5.py
> +            # run_time_parameter_values_and_defaults column is omitted
OK. So it sounds like that leaves us with the same data stored in two different places, and they won't always match? I think that's going to be error-prone, and your "as I was typing this..." note is an example of why.

I think ideally, we should migrate the old representation to the new representation. I'm not sure whether we can do that performantly, i.e. without the migration taking 25 minutes. I suspect the answer is "yes, with some care."

If we end up *not* doing that migration, I guess it's not a dealbreaker because we can do it later. But can we leave a comment here with your explanation of why it's okay to skip?

2024-07-25 16:00 UTC, sanni-t commented on robot-server/robot_server/persistence/_migrations/v4_to_v5.py
> +            # run_time_parameter_values_and_defaults column is omitted
> So it sounds like that leaves us with the same data stored in two different places, and they won't always match?

Not really. The only two possibilities are- 
- the analysis blob contains the full RTP params list and there's no corresponding RTP values in the RTP table (will happen for analyses migrated from v4)
- the analysis blob contains the full RTP params list and the same RTP values are in the RTP table for that analysis (will happen for any analyses generated since v6)

2024-07-25 16:02 UTC, sanni-t commented on robot-server/robot_server/protocols/protocol_store.py
> +            .order_by(sqlite_rowid)
I thought I removed this. Good catch

2024-07-25 16:12 UTC, sanni-t commented on robot-server/robot_server/protocols/rtp_resources.py
> +    parameter_type: str
Yep, it returns the enum, and we use the string value of it when creating the ParameterResource object from the db row. This is more favourable because the parameter types declared in the engine are string literals. Also the enum is more of a database concern and I don't want to leak that into rest of the server code.

2024-07-25 16:32 UTC, SyntaxColoring commented on robot-server/robot_server/persistence/_migrations/v4_to_v5.py
> +            # run_time_parameter_values_and_defaults column is omitted
> * the analysis blob contains the full RTP params list and there's no corresponding RTP values in the RTP table (will happen for analyses migrated from v4)

Right, to clarify, that's exactly what I mean by "the same data stored in two different places, and they won't always match."

2024-07-26 18:11 UTC, sanni-t commented on robot-server/robot_server/persistence/_migrations/v4_to_v5.py
> +            # run_time_parameter_values_and_defaults column is omitted
Talked about this in person. The RTP table is the record of all run time parameters that were successfully validated with the new analyzer version. The RTPs in the table will differ from those in the completed analysis if either the RTPs in the analysis had failed validation OR if they were not analyzed with the updated version. 
We agree that this is an acceptable scenario.

2024-07-26 18:14 UTC, sanni-t commented on robot-server/robot_server/protocols/analysis_store.py
> +            primitive_rtp_resources=[],
Talked about this in person. As mentioned above, we will not be saving any entries in RTP table for validation-failed parameters. The partially-validated RTPs will still live in the completed analysis blob for inspecting analyses retrospectively.

2024-07-26 18:21 UTC, sanni-t commented on robot-server/robot_server/protocols/analysis_store.py
>              for analysis_id in completed_analysis_ids
Alright, I remembered what this was about. And yes, it's an intentional removal. We decided to not save the full RTPs (with definitions) to their own table(s) so the only way to fetch the full list of RTPs with definitions is by de-serializing the completed analysis resource, and we don't want to do that for `AnalysisSummary` since its intention was to provide a glimpse of the analysis without having to make the expensive de-serializing step.
So I don't see a good way of adding RTPs to completed summaries and nor is it needed by anything.

2024-07-26 20:49 UTC, sanni-t commented on robot-server/robot_server/protocols/rtp_resources.py
> +            return converted_num
Yea, it can do that. I believe it's because we accept integers defined with a `.0` and don't truncate the trailing zero. We'll take a look at it again if it's causing confusion or any problems but I don't think it has to be in this PR.

2024-07-26 21:14 UTC, SyntaxColoring approved these changes
Great, thanks!

2024-07-26 21:14 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/rtp_resources.py
> +    parameter_type: str
OK, I see now that you're doing the `str`<->`Enum` conversion here instead of in `CompletedAnalysisStore`. That works for me.

I wouldn't have considered `PrimitiveParamSQLEnum` to be too low-level to appear in `CompletedAnalysisStore`, for what it's worth.

2024-07-29 17:56 UTC, sfoster1 approved these changes
Nice, I'm always for breaking stuff into more steps to better mirror semantics. I have a couple things I'd love to see changed but if stuff depends on this getting merged it's ok:
- Remove some null checks by slightly reorganizing
- Make remaining checks not just `assert`s but actual errors
- Just saying, `Scalar` feels like a better name than `Primitive`

2024-07-29 17:56 UTC, sfoster1 commented on robot-server/robot_server/protocols/analyses_manager.py
> +class FailedToInitializeAnalyzer(Exception):
Should this be an enumerated error so it can carry more context?

2024-07-29 17:56 UTC, sfoster1 commented on robot-server/robot_server/protocols/analysis_store.py
> +        assert set(param.variableName for param in new_parameters) == set(
Are we sure about this one? I really don't like using `assert` in this way in production code. If we're going to be paranoid, why not have this function (1) log something big and then (2) just return `False`, since if these parameter names don't match then they're definitionally different?

2024-07-29 17:56 UTC, sfoster1 commented on robot-server/robot_server/protocols/analysis_store.py
> +    ) -> None:
why change this? feels like a nice convenience thing to return the newly created object, and it's a smaller diff

2024-07-29 17:56 UTC, sfoster1 commented on robot-server/robot_server/protocols/completed_analysis_store.py
> +        rtps: Dict[str, PrimitiveAllowedTypes] = {}
nit:
```
resources = [PrimitiveParameterResource.from_sql_row(row) for row in results]
rtps = {param. parameter_variable_name: param.parameter_value for param in resources}
```
? Means you don't have to explicitly type `rtps`

2024-07-29 17:56 UTC, sfoster1 commented on robot-server/robot_server/protocols/protocol_analyzer.py
> +        self._orchestrator: Optional[RunOrchestrator] = None
Looking around the code, it seems like the first thing you always do with a protocol analyzer is call `load_runner` (now `load_orchestrator`) with the RTPs, including [in this pr](https://github.com/Opentrons/opentrons/pull/15650/files#diff-f1a7ff907d0ad851ce0c41eed2fed7cf46d31aa7e4f8df7669fd59cb6e4cd641R58). Given that, instead of having `load_orchestrator` can we
- Require an orchestrator instance as an initializer param, meaning it's not-null by construction
- make `create_protocol_analyzer` take the optional `run_time_param` values and build this there

That way we don't need all these asserts and we make it impossible to call `get_verified_run_time_parameters` in an illegal way.

2024-07-29 18:27 UTC, sanni-t commented
Thanks for the feedback @sfoster1. I'll address them in a follow-up PR since this one's quite overdue for merging.

2024-07-29 19:00 UTC, merged

2024-08-06 23:22 UTC, sanni-t commented on robot-server/robot_server/protocols/analysis_store.py
> +        assert set(param.variableName for param in new_parameters) == set(
@sfoster1 can you explain why you don't like using `assert` in this way? 
I prefer assert rather than silently logging because it makes sure that the error is actually brought to attention. It's a practice we've followed in most of robot server and engine code. If we only log the error and continue running (by returning `False` in this case), then the server might run into some other error down the line because failing this assertion means that there's a bug in our code somewhere else. So it's better to fail right away and know why it failed rather than failing a little later with a possibly unclear reason.