refactor(app): are you sure you want to cancel modal on desktop app
OpenTrons/opentrons-api pull request #15662
Opened 2024-07-15 19:29 UTC by TamarZanzouri

# Overview

closes https://opentrons.atlassian.net/browse/EXEC-553. 
wire up "are you sure you want to cancel?" desktop ER modal.

# Test Plan

- Test on ODD cancel run flow and make sure the styles didnt change.
- Tested on my local app + components. 

# Changelog

Mainly change style to support ODD and Desktop apps.

# Risk assessment

low.

2024-07-15 19:30 UTC, TamarZanzouri commented on app/src/atoms/buttons/SmallButton.tsx
> +  const TEXT_SIZE = isOnDevice ? '1.375rem' : '0.875rem'
Ill remove this

2024-07-15 19:30 UTC, TamarZanzouri commented on app/src/atoms/buttons/SmallButton.tsx
> +          fontSize={TEXT_SIZE}
and this :-)

2024-07-15 19:31 UTC, TamarZanzouri commented on app/src/organisms/ErrorRecoveryFlows/ErrorRecoveryWizard.tsx
> +    // change this to default typography
```suggestion
```

2024-07-15 19:31 UTC, TamarZanzouri commented on app/src/organisms/ErrorRecoveryFlows/shared/RecoveryContentWrapper.tsx
> +export function RecoverySingleColumnContentDesktop({
remove this

2024-07-15 19:32 UTC, TamarZanzouri commented on app/src/organisms/ErrorRecoveryFlows/shared/ErrorDetailsModal.tsx
> +export function ErrorDetailsModalDesktop(
can merge this with the ODD one

2024-07-15 20:20 UTC, sfoster1 requested changes
- some code-style stuff
- Instead of making these changes to `LegacyStyledText`, we should switch uses to `StyledText`. See the inline review for more details.

2024-07-15 20:20 UTC, sfoster1 commented on app/src/atoms/buttons/RadioButton.tsx
> +          oddStyle={isLarge ? 'level4HeaderRegular' : 'bodyTextRegular'}
`LegacyStyledText` doesn't work like this - you need to change it to `StyledText` to use these new params

2024-07-15 20:20 UTC, sfoster1 commented on app/src/atoms/buttons/SmallButton.tsx
> +  const TEXT_SIZE = isOnDevice ? '1.375rem' : '0.875rem'
we usually specify fonts in px as in typography. also do these match style tokens anywhere? we at the very least have a whole lot of `TYPOGRAPHY.fontSizeNN` type tokens

2024-07-15 20:20 UTC, sfoster1 commented on app/src/molecules/InterventionModal/index.tsx
> +                    width={16}
let's use `SPACING.spacing16` here (as long as this is actually 16px)

2024-07-15 20:20 UTC, sfoster1 commented on app/src/molecules/InterventionModal/index.tsx
> +                    height={16}
same

2024-07-15 20:20 UTC, sfoster1 commented on app/src/molecules/InterventionModal/index.tsx
> +                    size={SPACING.spacing32}
conflicts with `width` and `height`?

2024-07-15 20:20 UTC, sfoster1 commented on app/src/organisms/ErrorRecoveryFlows/ErrorRecoveryWizard.tsx
> +    return <LegacyStyledText as={'h4Bold'}>{titleText}</LegacyStyledText>
since we're touching it anyway, can we make this a `StyledText` with appropriate styles

2024-07-15 20:20 UTC, sfoster1 commented on app/src/organisms/ErrorRecoveryFlows/shared/ErrorDetailsModal.tsx
> +export function ErrorDetailsModalDesktop(
do you want to in this pr, or wait?

2024-07-15 20:20 UTC, sfoster1 commented on app/src/organisms/ErrorRecoveryFlows/shared/ErrorDetailsModal.tsx
> +      // gridGap={SPACING.spacing32}
```suggestion
```

2024-07-15 20:20 UTC, sfoster1 commented on components/src/atoms/StyledText/LegacyStyledText.tsx
> +    ${TYPOGRAPHY.level4DesktopHeaderRegular}
We should not be making changes of this type. We don't have the confidence that going forward we'll be able to stay disciplined about using the same semantic types in the desktop and ODD designs.

This is why `StyledText` exists as a separate thing: instead of changes like this, we can specify desktop and ODD styles independently.

So we should change the uses of `LegacyStyledText` that now require these to instead use `StyledText` with correct style names for desktop and ODD.

2024-07-15 20:20 UTC, sfoster1 commented on components/src/ui-style-constants/typography.ts
> +export const fontSize18 = '1.125rem' // 18px
same here - at this point, this file should really only contain ODD stuff. Changes that affect desktop would be made to the helix product typography.

2024-07-16 12:48 UTC, mjhuff reviewed
It's shaping up well! I'll give this a test and a more thorough review after Seth's comments clear and this becomes more finalized. Let me know if you have any Qs or need any help with lint.

As Seth mentioned, the big thing is we want to be very hesitant to make changes to anything in `components`, as (almost) everything there is effectively design-mandated.

2024-07-16 12:48 UTC, mjhuff commented on app/src/organisms/ErrorRecoveryFlows/RecoveryOptions/CancelRun.tsx
> +  width: 666px;
We prefer rem generally.

2024-07-16 12:48 UTC, mjhuff commented on app/src/organisms/ErrorRecoveryFlows/RecoveryOptions/CancelRun.tsx
> +    width: 848px;
rem

2024-07-16 17:36 UTC, sfoster1 commented on app/src/atoms/buttons/RadioButton.tsx
>          <LegacyStyledText
this has to be a `StyledText`, not a `LegacyStyledText`. `StyledText` is the one that supports `oddStyle` and `desktopStyle`, while `LegacyStyledText` - which we don't want to use anymore - supports `as`

2024-07-16 17:36 UTC, sfoster1 commented on app/src/atoms/buttons/SmallButton.tsx
> +  const TEXT_STYLE = css`
I believe this is font-size 14px, line-height 20px, font-weight semibold is `bodyDefaultSemiBold` in helix, and font-size 22px, line-height 28px, and semibold is `bodyTextSemiBold` in odd styles. So instead of this, we could just use `<StyledText oddStyle='bodyTextSemiBold' desktopStyle='bodyDefaultSemiBold'>{...}</StyledText>`

2024-07-16 17:36 UTC, sfoster1 commented on app/src/molecules/InterventionModal/index.tsx
> +                isOnDevice ? (
I suppose we could, but I feel like this can be responsiveized pretty easily by if nothing else setting `height=100% width=100%` and putting it in a `Box` with responsive css sizing

2024-07-16 17:36 UTC, sfoster1 commented on app/src/organisms/ErrorRecoveryFlows/RecoveryOptions/CancelRun.tsx
> +          css={ICON_SIZE}
if this works here it could work in the `InterventionModal` header too right?

2024-07-18 16:17 UTC, TamarZanzouri commented on app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx
> +    // isCalibrationComplete &&
```suggestion
    isCalibrationComplete &&
```

2024-07-18 17:39 UTC, TamarZanzouri commented on app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx
> +    // isCalibrationComplete &&
accidentally pushed this change this is just for testing purposes

2024-07-18 18:55 UTC, mjhuff commented on app/src/molecules/InterventionModal/index.tsx
> +              {iconHeading ?? null}
I prefer this personally, but we try to keep the same format across the codebase:
```suggestion
              {iconHeading != null ? iconHeading : null}
```

2024-07-18 18:57 UTC, mjhuff commented on app/src/molecules/InterventionModal/index.tsx
> +`
It's not intuitive, but we do use `SPACING` constants for width/height as well.

2024-07-18 18:58 UTC, mjhuff commented on app/src/organisms/ErrorRecoveryFlows/ErrorRecoveryWizard.tsx
> +    const titleText = props.hasLaunchedRecovery
```suggestion
    const titleText =hasLaunchedRecovery
```
and destructure `hasLaunchedRecovery` above.

2024-07-18 19:26 UTC, mjhuff commented on components/src/atoms/StyledText/LegacyStyledText.tsx
> +    @media ${RESPONSIVENESS.touchscreenMediaQuerySpecs} {
The tests are failing because we need to include something like this 
```suggestion
    ${TYPOGRAPHY.level4HeaderSemiBold}
    @media ${RESPONSIVENESS.touchscreenMediaQuerySpecs} {
```

2024-07-18 19:27 UTC, mjhuff commented on components/src/atoms/StyledText/LegacyStyledText.tsx
> +    @media ${RESPONSIVENESS.touchscreenMediaQuerySpecs} {
```suggestion
    ${TYPOGRAPHY.level3HeaderBold}
    @media ${RESPONSIVENESS.touchscreenMediaQuerySpecs} {
```

2024-07-18 19:27 UTC, mjhuff commented on components/src/atoms/StyledText/LegacyStyledText.tsx
> +    @media ${RESPONSIVENESS.touchscreenMediaQuerySpecs} {
```suggestion
    ${TYPOGRAPHY.level3HeaderBold}
    @media ${RESPONSIVENESS.touchscreenMediaQuerySpecs} {
```

2024-07-18 19:28 UTC, mjhuff commented on components/src/atoms/StyledText/__tests__/StyledText.test.tsx
> +    expect(screen.queryAllByText('h3Bold')[0]).toHaveStyle(
We generally prefer when rendering only one element for the sake of clarity.
```suggestion
    expect(screen.getByText('h3Bold')).toHaveStyle(
```

2024-07-18 19:28 UTC, mjhuff commented on components/src/atoms/StyledText/__tests__/StyledText.test.tsx
> +    expect(screen.queryAllByText('h4Bold')[0]).toHaveStyle(
```suggestion
    expect(screen.getByText('h4Bold')).toHaveStyle(
```

2024-07-18 19:29 UTC, mjhuff commented on components/src/helix-design-system/product/typography.ts
> +export const fontStyleHeadingMediumBold = `${fontWeightBold} ${fontSizeHeadingMedium}/${lineHeightHeadingMediumSemiBold} ${fontFamilyHeadingMediumSemiBold}`
Are we sure we want to be changing the typography file? We really shouldn't be touching this unless design tells us to, but I could be missing something.

2024-07-18 19:29 UTC, mjhuff commented on components/src/helix-design-system/product/typography.ts
Are we sure we want to be changing the typography file? We really shouldn't be touching this unless design tells us to, but I could be missing something.

2024-07-18 19:34 UTC, mjhuff commented on app/src/atoms/buttons/SmallButton.tsx
> +
```suggestion
```

2024-07-18 19:34 UTC, mjhuff commented on app/src/organisms/ErrorRecoveryFlows/RecoveryOptions/CancelRun.tsx
> +`
Let's use SPACING constants here. (If we have them for 3.75rem).

2024-07-18 19:37 UTC, mjhuff commented on app/src/organisms/ErrorRecoveryFlows/RecoveryOptions/ManageTips.tsx
> +
Let's nix these and use the constants in the `ErrorRecoveryFlows/constants.ts` file.

2024-07-18 19:37 UTC, mjhuff commented on app/src/organisms/ErrorRecoveryFlows/RecoveryOptions/ManageTips.tsx
> +        ></RecoveryRadioGroup>
```suggestion
        />
```

2024-07-18 19:38 UTC, mjhuff reviewed
It's close! Seems like the overflow menu might be a bit off on the desktop:

<img width="1019" alt="Screenshot 2024-07-18 at 2 52 43 PM" src="https://github.com/user-attachments/assets/9b92de25-d5b0-4c33-a135-c9a83c7e703d">

2024-07-18 19:42 UTC, mjhuff commented on components/src/atoms/StyledText/LegacyStyledText.tsx
> +    @media ${RESPONSIVENESS.touchscreenMediaQuerySpecs} {
In person convo, we need to not add these changes to `LegacyStyledText` and delete the `StyledText.test.tsx` file.

2024-07-18 20:31 UTC, sfoster1 requested changes
Will test further, but definitely need to remove all changes to `LegacyStyledText.tsx`

2024-07-18 20:31 UTC, sfoster1 commented on app/src/organisms/ErrorRecoveryFlows/RecoveryOptions/ManageTips.tsx
> +            setSelected(e.currentTarget.value as RemovalOptions)
this `as` should not be necessary - `RecoveryRadioGroup` should generate this for you

2024-07-18 20:31 UTC, sfoster1 commented on components/src/atoms/StyledText/LegacyStyledText.tsx
> +  h4SemiBold: css`
as we mentioned f2f, we should not have changes to this file. Changes should only be made to StyledText.

2024-07-19 14:25 UTC, sfoster1 approved these changes
Great! LGTM once it passes checks!

2024-07-19 14:32 UTC, mjhuff approved these changes
There's still a couple CSS issues:

- The font color on the cancel run subtext is not `black90`.
- The text isn't centered on the modal.

That being said, I don't think this is blocking. We can circle up and do touch-ups later. Thank you!

2024-07-19 16:40 UTC, merged