Checks that most recent run is completed in abr_scale script
OpenTrons/opentrons-api pull request #15661
Opened 2024-07-15 19:27 UTC by rclarke0

# Overview

Checks that run being pulled is completed. Adds error handling if no new runs need to be added.

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-07-15 19:57 UTC, sfoster1 requested changes
Spidey-sense tingles at that UnboundLocalError, I think that should be optionally `None` instead

2024-07-15 19:57 UTC, sfoster1 commented on abr-testing/abr_testing/data_collection/abr_google_drive.py
> +    except UnboundLocalError:
this is usually not an exception you want to be catching. Maybe make `runs_and_robots` optionally `None` instead and always exist?

2024-07-15 20:20 UTC, rclarke0 commented on abr-testing/abr_testing/data_collection/abr_google_drive.py
> +    except UnboundLocalError:
runs_and_robots is defined at the beginning so i think i can get rid of the error handling

2024-07-18 14:08 UTC, sfoster1 approved these changes
Looks good!

2024-07-19 11:53 UTC, merged