chore(api): Liquid-probe pre-loads the plunger downard when moving to top
OpenTrons/opentrons-api pull request #15674
Opened 2024-07-16 16:28 UTC by andySigler

# Overview

This PR modifies the `OT3API._move_to_plunger_top()` method to use the pipette's configured `backlashDistance` to make sure the plunger is preloaded in the downward direction. This is important to make sure the beginning movements are truly moving the plunger and compressing the air.

This PR also adds comments and calculations to explain the important details inside `OT3API.liquid_probe()`. These include:

- Fixing a bug in how `p_travel` was calculated per each pass
- Defining the "non-responsive" Z distance separately from the "overlap" Z distance
- Using the (unused) `plunger_impulse_time` from the liquid-probe config, instead relying on variable down in tool-sensors

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-07-16 17:03 UTC, sfoster1 requested changes
Looks good overall but let's push the magic down a layer

2024-07-16 17:03 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        the plunger's configured "top" position, but "top" plust the "backlashDistance".
```suggestion
        the plunger's configured "top" position, but "top" plus the "backlashDistance".
```

2024-07-16 17:03 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        baseline_during_z_sample_num = 20  # FIXME: (sigler) shouldn't be defined here?
yeah i would push this logic down to `tool_sensors` as a free function that is like `def non_responsive_distance_for_speed(speed: float): float`. then at least the magic numbers will live near some other magic numbers

2024-07-17 18:19 UTC, sfoster1 approved these changes
Code changes look good to me but would love @ryanthecoder 's eyes before merge

2024-07-22 15:49 UTC, ryanthecoder commented
lets replace with https://github.com/Opentrons/opentrons/pull/15732 that is rebased and has a few minor edits

2024-07-22 16:07 UTC, closed without merging