feat(api): build out well state for liquid height tracking
OpenTrons/opentrons-api pull request #15681
Opened 2024-07-16 19:09 UTC by aaron-kulkarni

# Overview
re EXEC-603

This PR adds a new `WellState` class. This class currently has only one attribute, `measured_liquid_heights`, which is used in liquid height tracking. We created this new class(rather than just adding this attribute to labware state or something related), to allow for more detailed well state tracking in the future.

## Details
`measured_liquid_heights` contains a Dict[labware_id, Dict[well_name, LiquidHeightInfo]]. This dictionary structure is meant to give time-efficient access to all wells of a particular labware, since the dictionary is primarily indexed by labware_id.

The presence/non-presence of a well in the `WellState` class indicates the following:
* If a well is not present: that well has never been probed.
* If a well is present but has a `height` value of 0: the most recent probe into that well found no liquid.
* If a well is present and has a height value of > 0: the most recent probe into that well found liquid. 

A quick word on the implementation of the new `LiquidHeightInfo` type. It has two attributes, `height` and `last_measured`. The `last_measured` attribute currently stores as a datetime, but it could be useful in the future to consider other alternatives. Maybe protocol steps?(or something similar). The reason we have a time-related attribute at all is because right now we don't track things like aspirates and dispenses, or even user inputted liquid loading(if that's the correct term). All liquid height state is determined only by doing a `liquid_probe`, so it's useful to know what the last time was we did a `liquid_probe` on this well.

For the purposes of the StateSummary, a new type was defined called `LiquidHeightSummary`. It has identifying information about the labware/well and the contents of the `LiquidHeightInfo` type.  

# Test Plan

Unit tests written and passed for well_view and well_store.
# Changelog

* Created `WellState` class, along with complementary `WellView` and `WellStore`
* Created `LiquidHeightInfo` type, which is used to store info about recent liquid height measurements.
* Created `LiquidHeightSummary` type, which is used in StateSummary. 

# Review requests

# Risk assessment

Low.

2024-07-17 18:01 UTC, sfoster1 requested changes
I think the structure of this is nice and we'll definitely want a `WellStore`, but I think we should put some thought in - and write that thought down - about the structure of the information within. I think we can write that down in the description, but honestly the description should be the longest part of this PR in that case. We should cover
- How do we track the relationship of these Well objects to the labware that contains them?
- What does the presence or absence of a Well in the wells data structure mean? What's it based on?
- How do we indicate that a well has never been probed for the presence of liquid? Probed, and no liquid found? Probed, and liquid found? Probed, and liquid found, but known to have been refilled?
- In general, what information should a human looking at a serialization of the Wells data structure be able to come to?

2024-07-17 18:01 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/wells.py
> +    def _handle_succeded_command(self, command: Command) -> None:
```suggestion
    def _handle_succeeded_command(self, command: Command) -> None:
```

2024-07-17 18:01 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/wells.py
> +            if command.result is None:
does that make sense? Under what conditions would the command result be `None`?

2024-07-17 19:59 UTC, aaron-kulkarni commented on api/src/opentrons/protocol_engine/state/wells.py
> +            if command.result is None:
Agreed it doesn't make sense. I initially did that to pass lint checks but I found a cleaner way around it.

2024-07-19 18:06 UTC, sfoster1 requested changes
Looking good, but let's remove that commented out code and make sure the well identification information is in the summary too. Also maybe a format pass on the description?

2024-07-19 18:06 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/wells.py
> +    #                       Dict[Labware: Dict[Wellname: [Height,TimeRecorded]]]
Remove commented out code

2024-07-19 18:06 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/state_summary.py
> +    wells: List[LiquidHeightInfo] = Field(default_factory=list)
This needs to have more of the data from the state - from just the summary, you wouldn't be able to tell what well is being talked about.

2024-07-22 14:04 UTC, sfoster1 submitted a review, later dismissed
Some more small style things.

2024-07-22 14:04 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/wells.py
> +        # for key,  in self._state.measured_liquid_heights.items():
remove commented out code

2024-07-22 14:04 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/wells.py
> +            self._state.measured_liquid_heights[labware_id]
This is not really a great pattern. In Python it's usually better to catch exceptions than try up front (some people disagree, but let's accept it for the sake of argument), but that means "write the code you were going to write and then catch possible exceptions", not "do a special thing to try and cause an exception". There's two options to try:
- Make `self._state.measured_liquid_heights` actually be a [defaultdict](https://docs.python.org/3/library/collections.html#collections.defaultdict) that builds dictionaries as its defaults; however, this might not work great with serialization
- Just have this code look more like `if labware_id not in self._state.measured_liquid_heights: ...`

2024-07-22 14:04 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/wells.py
> +        for labware in self._state.measured_liquid_heights.keys():
nit: could be `for labware, wells in self._state.measured_liquid_heights.items()` and then `for well, lhi in wells.items()`. I htink it would be neater because it would be only accessing temporaries.

2024-07-22 14:04 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/wells.py
> +        allHeights = []  # type: List[LiquidHeightSummary]
Prefer type annotations (i.e. `all_heights: List[LiquidHeightSummary]`) to type comments (i.e. what you have here)

2024-07-22 14:04 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/wells.py
> +        allHeights = []  # type: List[LiquidHeightSummary]
prefer `snake_case` for variables

2024-07-22 14:04 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/wells.py
> +        allHeights = []  # type: List[LiquidHeightSummary]
prefer type annotations to type comments

2024-07-22 14:04 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/wells.py
> +            self._state.measured_liquid_heights[labware_id][well_name].height
here is a good example of handling exceptions as something that happens from normal code. This will work, but a better way to do it would be something like 
```
try:
     return bool(self._state.measured_liquid_heights[labware_id][well_name])
except KeyError:
     return False
```

As with the inserting defaults example above, you really want the exception to be thrown while doing something you intend, not just doing something to see if it throws.

2024-07-23 18:43 UTC, aaron-kulkarni commented
Nevermind I did need the snapshot changes. The snapshot stuff on this branch is unrelated to the issues we were having earlier.

2024-07-26 18:33 UTC, sfoster1 requested changes
I think this is a really solid first implementation, and I also think we shouldn't merge it to edge until we branch it to 8.0. So this request-changes is to mark that we shouldn't merge it until then, but I do think it's great!

2024-09-06 20:28 UTC, sfoster1 approved these changes
Great! Thanks for finishing up the merge.

2024-09-06 20:29 UTC, merged