docs(api):liquid presence verification
OpenTrons/opentrons-api pull request #15695
Opened 2024-07-17 19:33 UTC by jwwojak

# Overview

Adding new documentation to describe new Liquid Presence Verification methods, includes updating docstrings.  Sandbox links below.

The JIRA ticket is [RTC-148](https://opentrons.atlassian.net/browse/RTC-148).

# Test Plan

Review the new docs.

# Changelog

**New**
Adds a new H2 section, [Liquid Presence Verification](http://sandbox.docs.opentrons.com/docs-liquid-presence-detection/v2/pipettes/loading.html#liquid-presence-verification) to the page, Loading Pipettes (`loading.rst`). Includes two H3 subsections:

- [Enable LPV Globally](http://sandbox.docs.opentrons.com/docs-liquid-presence-detection/v2/pipettes/loading.html#enable-lpv-globally)
- [Turning LPV Off and On](http://sandbox.docs.opentrons.com/docs-liquid-presence-detection/v2/pipettes/loading.html#turing-lpv-off-and-on)

**New**
Adds two new H2 sections to the page, Liquid Control (`liquids.rst`):

- [Detect Liquids](http://sandbox.docs.opentrons.com/docs-liquid-presence-detection/v2/basic_commands/liquids.html#detect-liquids)
- [Require Liquids](http://sandbox.docs.opentrons.com/docs-liquid-presence-detection/v2/basic_commands/liquids.html#require-liquids)

**Revisions/Additions**
Small changes to docstrings for:

- `liquid_presence_detection`, an argument of [load_instrument](http://sandbox.docs.opentrons.com/docs-liquid-presence-detection/v2/new_protocol_api.html?highlight=load_instrument#opentrons.protocol_api.ProtocolContext.load_instrument)
- [detect_liquid_presence](http://sandbox.docs.opentrons.com/docs-liquid-presence-detection/v2/new_protocol_api.html?highlight=detect_liquid_presence) in v2 Reference.
- [require_liquid_presence](http://sandbox.docs.opentrons.com/docs-liquid-presence-detection/v2/new_protocol_api.html?highlight=require_liquid_presence)

# Review requests

Take a look and or before adding others.

# Risk assessment

Low. Docs changes only.

2024-07-17 19:55 UTC, jwwojak commented
Didn't check w/ Black before opening PR.

2024-07-17 20:14 UTC, aaron-kulkarni commented on api/docs/v2/pipettes/loading.rst
> +Liquid Presence Verification (LPV) is a pressure-based feature that gives all Opentrons pipettes the ability to detect the presence or absence of a liquid in a well or reservoir. You can use LPV to i
LPV will only work for the Flex. The OT-2 pipettes don't have the necessary pressure sensors.

2024-07-17 20:42 UTC, jwwojak commented on api/docs/v2/pipettes/loading.rst
> +Liquid Presence Verification (LPV) is a pressure-based feature that gives all Opentrons pipettes the ability to detect the presence or absence of a liquid in a well or reservoir. You can use LPV to i
Oh, drat. That's right. My mistake. That paragraph was a last minute change. Needs to specify Flex-only.

2024-07-26 15:20 UTC, aaron-kulkarni commented on api/docs/v2/basic_commands/liquids.rst
> +The :py:meth:`.InstrumentContext.detect_liquid_presence` method tells a Flex pipette to check for the presence of a liquid in a wellplate or reservoir. This method returns ``True`` if the pressure se
_"Detection takes place during aspiration. As the Flex pipette detects a liquid, it stops, raises itself above the liquid's surface, and then resumes aspiration."_

Detections do take place during an aspiration, but the function that is called during an aspiration is `require_liquid_presence`, not `detect_liquid_presence`. 

Also, both require/detect can be called entirely separately from aspirations/dispenses. You can call `detect_liquid_presence` on 100 wells without ever doing an aspiration. I'm not sure how docs are generally written but it might be a good idea to keep explanations of automatic detection during aspirations separate from these two functions.

2024-07-26 17:31 UTC, jwwojak commented on api/docs/v2/basic_commands/liquids.rst
> +The :py:meth:`.InstrumentContext.detect_liquid_presence` method tells a Flex pipette to check for the presence of a liquid in a wellplate or reservoir. This method returns ``True`` if the pressure se
@aaron-kulkarni Thanks for the clarifications. These are some important distinctions.

- `detect_liquid_presence` and `require_liquid_presence` can be called separately from aspiration.
- function that does the automatic detection during an aspiration is `require_liquid_presence`, not `detect_liquid_presence`.

2024-07-26 20:01 UTC, y3rsh commented
Sorry for all the broken comments on here.  You can delete them.  If you pull edge into this branch everything is fixed and you wont be hassled by the comments.

2024-08-01 21:25 UTC, ecormany requested changes
Some changes to make. Semantic changes are around being clear about exactly when LLD happens, the difference between detecting and requiring, and the strong link between the require standalone method and global detection (naming things is hard, so it goes). Syntactic changes are to get the big code block working — get engineer support as needed. And stylistic changes are all to be blamed on the Pythonistas 🐍 🧐

2024-08-01 21:25 UTC, ecormany commented on api/docs/v2/pipettes/loading.rst
> +Liquid Presence Detection is a pressure-based feature that allows Opentrons Flex pipettes to detect the presence or absence of liquids in a well, reservoir, or other container. Liquid Presence Detect
This feature name should be lowercase: "liquid presence detection".

2024-08-01 21:25 UTC, ecormany commented on api/docs/v2/pipettes/loading.rst
> +    If your protocol uses :ref:`partial tip pickup <partial-tip-pickup>`, the pressure sensors for the Flex 8-Channel pipette are on channels 1 and 8. For the Flex 96-Channel Pipette, the pressure se
```suggestion
    If your protocol uses :ref:`partial tip pickup <partial-tip-pickup>`, the pressure sensors for the Flex 8-Channel pipette are on channels A1 and H1. For the Flex 96-Channel Pipette, the pressure sensors are on channels A1 and H12.
```
Matches how we refer to these channels/nozzles for partial tip pickup.

2024-08-01 21:25 UTC, ecormany commented on api/docs/v2/pipettes/loading.rst
> +--------------------------------
Yes, I would go with the gerund form to match other headers. It would also be good to shorten these headers. They're at the fourth level of the side nav, so they can rely on the context provided by their parent section.

2024-08-01 21:25 UTC, ecormany commented on api/docs/v2/pipettes/loading.rst
> +The easiest, and recommended, way to use Liquid Presence Detection is by adding the optional Boolean argument, ``liquid_presence_detection=True`` to :py:meth:`.ProtocolContext.load_instrument` in you
- Not recommended, because of how time-consuming it is.
- Remove comma after "argument" since the monospace formatting does the work (and this isn't an appositive).
- Last sentence, probably better to say "enables…for" instead of "adds…to"

2024-08-01 21:25 UTC, ecormany commented on api/docs/v2/pipettes/loading.rst
> +.. versionadded:: 2.20
Can remove this `versionadded` notice since no code shown yet in this section.

2024-08-01 21:25 UTC, ecormany commented on api/docs/v2/pipettes/loading.rst
> +    pipette.dispense(100, plate["A1"])
I don't think we gain anything from splitting up these code blocks. It makes it seem like the pickup action does something differently. It would be best to combine them and annotate where LPD happens with a comment.

Also, these don't match the pipette from before, which was loaded as `right`.

2024-08-01 21:25 UTC, ecormany commented on api/docs/v2/pipettes/loading.rst
> +    pipette.aspirate(100, reservoir["A2"])
```suggestion
    pipette.pick_up_tip()
    pipette.liquid_presence_detection=False  # liquid presence detection off
    pipette.aspirate(100, reservoir["A2"])  # aspirates immediately
```

no need to complicate with pickup location.

2024-08-01 21:25 UTC, ecormany commented on api/docs/v2/pipettes/loading.rst
> +To reactivate, add ``pipette.liquid_presence_detection=True`` at the point later in a protocol where it needs to be enabled, usually between picking up a new tip and aspirating a liquid.
```suggestion
To reactivate, set ``liquid_presence_detection=True`` at the point later in the protocol where it needs to be enabled, usually between picking up a new tip and aspirating a liquid.
```

2024-08-01 21:25 UTC, ecormany commented on api/docs/v2/pipettes/loading.rst
> +    pipette.aspirate(100, reservoir["A3"])
```suggestion
    pipette.pick_up_tip()
    pipette.liquid_presence_detection=True  # liquid presence detection on again
    pipette.aspirate(100, reservoir["A3"])  # detects liquid before aspirating
```

2024-08-01 21:25 UTC, ecormany commented on api/docs/v2/pipettes/loading.rst
> +See also :ref:`detect-liquid-presence` and :ref:`require-liquid-presence`.
It would be good to add context to these cross-references by moving them up to line 236 and adding an explanation that you should click through to these other sections if you want to do one-off detection.

2024-08-01 21:25 UTC, ecormany commented on api/docs/v2/basic_commands/liquids.rst
> +The :py:meth:`.InstrumentContext.detect_liquid_presence` method tells a Flex pipette to check for the presence of a liquid in a wellplate or reservoir. This method returns ``True`` if the pressure se
```suggestion
The :py:meth:`.InstrumentContext.detect_liquid_presence` method tells a Flex pipette to check for the presence of a liquid in a well plate or reservoir. This method returns ``True`` if the pressure sensors in the pipette detect a liquid and ``False`` if the sensors do not. It will not raise an error or stop your protocol when the robot detects an empty well. 

You should generally detect liquid immediately after picking up a tip and before aspirating, but you don't need to aspirate to use ``detect_liquid_presence()``. It's a standalone method that can be called when you only want to detect liquid. 

.. note::
    Accurate liquid detection requires fresh, dry pipette tips.

```

Couple typos and more specific guidance on when is ok/good to use this method.

2024-08-01 21:25 UTC, ecormany commented on api/docs/v2/basic_commands/liquids.rst
> +.. code-block:: python
This code block needs an overhaul. From most to least important:

- The `for` loop is broken because labware don't have an iterable `items()` method, much less one that has names and wells. 
  - It needs to be `for well in reservoir.wells()` or this will not analyze.
  - The reference to `name` in the comment should be `well.name`.
- Variable case and names don't match, which will lead to Python syntax errors. Variable names should be snake_case when assigned and referenced.
- The tip index is superfluous because it's never referenced in the messages at the end and you could use automatic tip tracking instead.
- General `black`ening
  - Two spaces before comment delimiters
  - `+=` is an assignment operator and should have spaces on either side

2024-08-01 21:25 UTC, ecormany commented on api/docs/v2/basic_commands/liquids.rst
> +Detection takes place during aspiration, but you don't need to aspirate to use ``require_liquid_presence``. It's a standalone method that can be called when you want to detect liquids only. See also
As above, you should call this with a fresh tip and before aspiration.

And the cross-reference can be strengthened to indicate that it links to instructions on how to perform this automatically for all aspirations on a given pipette.

2024-08-01 21:25 UTC, ecormany commented on api/docs/v2/basic_commands/liquids.rst
> +    pipette.require_liquid_presence()
Needs a well argument.

2024-08-01 21:25 UTC, ecormany commented on api/docs/v2/basic_commands/liquids.rst
> +    pipette.detect_liquid_presence()
Needs a well argument.

2024-08-01 21:25 UTC, ecormany commented on api/src/opentrons/protocol_api/instrument_context.py
> +        """Checks if there is liquid in a well. Will not raise an error if it does not detect liquid. Flex pipettes only. See :ref:`lpd` and :ref:`detect-liquid-presence`.
```suggestion
        """Checks if there is liquid in a well. 
        
        Returns ``True`` if liquid is present and ``False`` if liquid is not present. Will not raise an error if it does not detect liquid. Flex pipettes only. See :ref:`detect-liquid-presence`.
```
First sentence of a docstring should stand alone.

Removed xref to global detection, which is more like `require_liquid_presence()`.

2024-08-01 21:25 UTC, ecormany commented on api/src/opentrons/protocol_api/instrument_context.py
> +        """Checks for liquid in a well. Raises an error if no liquid is detected. Flex pipettes only. See :ref:`lpd` and :ref:`require-liquid-presence`.
```suggestion
        """Checks for liquid in a well and raises an error if none is detected. 
        
        When this method raises an error, Flex will offer the opportunity to enter recovery mode. In recovery mode, you can manually add liquid to resolve the error. 
        
        Works with Flex pipettes only. See :ref:`lpd` and :ref:`require-liquid-presence`.
```

Suggesting to differentiate the first lines and explain a bit more about what you can do when an error happens. (For power users, this also implies that you don't need to catch this error in a `try...except` block.)

2024-08-01 21:25 UTC, ecormany commented on api/src/opentrons/protocol_api/instrument_context.py
>          :returns: A boolean.
We could remove this, or move the prose description of the values of true and false here.

2024-08-01 21:25 UTC, ecormany commented on api/src/opentrons/protocol_api/instrument_context.py
>          :returns: None.
Remove or style as `None`

2024-08-01 21:25 UTC, ecormany commented on api/src/opentrons/protocol_api/protocol_context.py
> +        :param bool liquid_presence_detection: If ``True``, enables liquid presence detection for Flex 1-, 8-, or 96-channel pipettes. See :ref:`lpd`.
```suggestion
        :param bool liquid_presence_detection: If ``True``, enable liquid presence detection for Flex 1-, 8-, or 96-channel pipettes. See :ref:`lpd`.
```
Should be imperative like other param descriptions.

2024-08-08 15:46 UTC, jwwojak commented on api/docs/v2/pipettes/loading.rst
> +.. versionadded:: 2.20
@ecormany I was talking to Anthony, going back to that conversation about about LLD and partial tip pickup. He seems concerned that docs should include text reminding/warning users that the other channels can't sense liquid. Even though it is obvious, I was going to add another sentence along the lines of "these are the only pipette channels that can do LLD" or "When using partial tip pickup, other pipette channels cannot detect the presence/absence of a liquid." 

Need some help w/ guidance that points in 2 different directions–remove or keep and enhance.

2024-08-08 15:59 UTC, jwwojak commented on api/docs/v2/basic_commands/liquids.rst
> +.. code-block:: python
We're often not following our own rules re: [comments](https://peps.python.org/pep-0008/#comments).

> Comments should be complete sentences. The first word should be capitalized, unless it is an identifier that begins with a lower case letter (never alter the case of identifiers!).

2024-08-08 18:02 UTC, jwwojak commented on api/src/opentrons/protocol_api/instrument_context.py
>          :returns: A boolean.
Will move the longer, prose description to `:returns:` (line 2125).

2024-08-08 18:06 UTC, jwwojak commented on api/src/opentrons/protocol_api/instrument_context.py
>          :returns: None.
Not following here. I think you mean do the same thing as in `detect_liquid_presence` above.

2024-08-08 18:50 UTC, jwwojak commented on api/docs/v2/pipettes/loading.rst
> +    pipette.dispense(100, plate["A1"])
Oops. I see it now. Rewriting, fixing.

2024-08-08 19:20 UTC, ecormany commented on api/docs/v2/pipettes/loading.rst
> +.. versionadded:: 2.20
Let's include a brief description of this behavior in the API Reference entries for `detect_liquid_presence()` and `require_liquid_presence()`

2024-08-08 20:22 UTC, jwwojak commented on api/docs/v2/pipettes/loading.rst
> +.. versionadded:: 2.20
Making a note to self as a reminder:

- Remove the note text
- Put it in the reference
- Add the info about there's no sensors on all the channels, partial tip_won't_ detect on those non-sensor channels.

2024-08-12 15:20 UTC, jwwojak commented on api/docs/v2/pipettes/loading.rst
> +See also :ref:`detect-liquid-presence` and :ref:`require-liquid-presence`.
Line numbers are slightly different now. Moving content up to recommended location and adding more text about `detect_liquid_presence` and `require_liquid_presence`. Will write about them as standalone methods you can use without aspirating and give a summary of what they do. Methods will be linked to reference.

2024-08-16 14:47 UTC, ecormany approved these changes
Went through final changes with Joe. :shipit:

2024-08-16 15:02 UTC, merged