feat(robot-server): start logic for dynamic error recovery policy
OpenTrons/opentrons-api pull request #15707
Opened 2024-07-18 18:16 UTC by aaron-kulkarni

# Overview

Create robot-server function that turns a List of ErrorRecoveryRules into a full ErrorRecoveryPolicy. A future PR will implement the HTTP calls that actually create the list of rules.

EXEC-589

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-07-18 19:01 UTC, SyntaxColoring requested changes
This all looks great.

I think we should add some unit tests for `create_error_recovery_policy_from_rules()` before we move on, so we don't forget, but other than that I only have minor suggestions.

2024-07-18 19:01 UTC, SyntaxColoring commented on robot-server/robot_server/service/error_recovery.py
Let's move this to `robot_server/runs/`, so it'll live next to the models that it's using, and the routers that will call it. We could also maybe rename it to `error_recovery_mapping.py` for consistency with `validation_mapping.py`, which exists elsewhere.

robot-server's module hierarchy is confusing, sorry. TBH I don't really get the whole `/service/` thing, but [here's some helpful context from Seth](https://opentrons.slack.com/archives/CSPMY9048/p1704484574227449).

2024-07-18 19:01 UTC, SyntaxColoring commented on robot-server/robot_server/service/error_recovery.py
> +from typing import Optional
Very very minor nitpick, but let's try to group imports in this order:

1. Python standard library
2. External library or project (including `opentrons`, when we're in `robot_server`)
3. Modules local to this project (`robot_server` in this case)

To follow [PEP8](https://peps.python.org/pep-0008/#:~:text=Imports%20should%20be%20grouped%20in%20the%20following%20order%3A).

2024-07-18 19:01 UTC, SyntaxColoring commented on robot-server/robot_server/runs/error_recovery_models.py
> +    WAIT_FOR_RECOVERY = "wait-for-recovery"
A few minor stylistic things:

1. Enums should have `CamelCase` names, like `ValueMatchType` in this case. Same convention as regular classes.
2. Let's avoid subclassing this enum from `str` unless we really need to, for the reasons described [here](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/3479896162/Why+not+to+subclass+Python+enums+from+str). Just `Enum`.
3. The strings `"ignore"`, `"fail-run"`, and `"wait-for-recovery"` are going to be part of the HTTP interface, so let's make them `camelCase`, like `waitForRecovery`, to follow [our HTTP API conventions](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/575078506/HTTP+API+style).
4. The name `ValueMatchType` isn't really clicking for me?

    I would normally call this something like `ActionIfMatched`. But maybe we should avoid the word "action" because it already has two important meanings—the `/runs/{id}/actions` endpoints, and actions in `opentrons.protocol_engine`.

    Maybe just `IfMatch`? `ReactionIfMatch`?

    Totally up to you.

2024-07-18 19:01 UTC, SyntaxColoring commented on robot-server/robot_server/runs/error_recovery_models.py
> +    )
This models JSON objects of the form:

```json
{
    "commandType": "foo",
    "errorType": "bar",
    "ifMatch": "baz",
}
```

But I think we want it to be:

```json
{
    "matchCriteria": {
        "command": {
            "commandType": "foo",
            "error": {
                "errorType": "bar"
            }
        }
    },
    "ifMatch": "baz"
}
```

My rationale is:

* We want `matchCriteria` to be its own self-contained thing so, in the future, we can do things like add an `id` field to the *rule itself,* without worrying about it being confused as a match criteron, since commands also have `id` fields. [Here's some context on why the rule itself might need an `id`.](https://opentrons.slack.com/archives/C06M9F26YGH/p1721245985818779?thread_ts=1721241891.175299&cid=C06M9F26YGH)
* Within `matchCriteria`, we want `command` to be its own self-contained thing to leave room for totally different kinds of error-matching criteria in the future, that extend beyond the context of just one command. I don't know what those would be, but it's cheap to leave room for them now, so it seems like we might as well.
* Within `command`, we want the structure of `commandType`+`error`+`errorType` to mirror the structure of a command as you'd see it on the `GET /runs/{id}/commands/{id}` HTTP endpoint. This, again, leaves room for potential future improvements such as filtering based on the command `params` or `notes`.

What do you think?

2024-07-18 19:01 UTC, SyntaxColoring commented on robot-server/robot_server/runs/error_recovery_models.py
> +    """Request model for new error recovery rule creation."""
FYI this will also show up in HTTP responses, not just requests.

2024-07-18 19:01 UTC, SyntaxColoring commented on robot-server/robot_server/service/error_recovery.py
> +def create_error_recovery_policy_from_rules(
Looks good, but can we add a unit test for this?

Fortunately it's the fun (to me) kind of unit test. No mocks, just lots of black-box input and output, living in the moment, aah.

2024-07-23 14:13 UTC, aaron-kulkarni commented on robot-server/robot_server/service/error_recovery.py
> +def create_error_recovery_policy_from_rules(
Unfortunately I had to resort to mocks to create fake errors/commands/etc. If you think there's a cleaner or better way to do it just let me know

2024-07-24 01:58 UTC, SyntaxColoring approved these changes
Looks good, thanks.

We can update the `NotImplementedError` comment and I think there's a missing `==` on one if the `assert` statements, but other than that, this looks good to me to merge. Feel free to merge after fixing those and checking that all the CI is still passing.

2024-07-24 01:58 UTC, SyntaxColoring commented on robot-server/tests/runs/test_error_recovery_mapping.py
> +    assert policy(exampleConfig, mock_command, mock_error_data)
Looks like this is missing an `== ErrorRecoveryType.IGNORE_AND_CONTINUE`?

2024-07-24 01:58 UTC, SyntaxColoring commented on robot-server/robot_server/service/error_recovery.py
> +def create_error_recovery_policy_from_rules(
I would just construct actual full errors/command/etc. objects. Possibly with helper functions to make it more convenient.

This is a good guideline, in general:

| **Object type**                            | **Usage in tests**                                           |
|--------------------------------------------|--------------------------------------------------------------|
| "Behavioral" (it exists for its methods)   | Replace the object and its methods with test doubles (mocks) |
| "Data" (it exists to group stuff together) | Actually construct actual objects, in full                   |

But, you know, this only holds up to a certain point. There's a threshold where a data object gets so big and annoying to construct, that it clutters up the tests, and you would rather just create the parts that you *really* need, using something like a mock. I feel like our JSON protocol and labware definition models are like that, for example. Personally, the objects in this PR don't meet my threshold for that, but I can certainly see how they would.

But I think this works, no need to change it.

2024-07-24 01:58 UTC, SyntaxColoring commented on robot-server/robot_server/runs/error_recovery_models.py
> +    )
OK so it looks like this is modeling a structure that's, like this (in loose sketchy form):

```
rules
    matchCriteria
        criteria 1 (with one commandType and one errorType)
        criteria 2 (with one commandType and one errorType)
        criteria 3 (with one commandType and one errorType)
    ifMatch
        reaction 1
        reaction 2
        reaction 3
```

Where criteria 1 gets paired with reaction 1, criteria 2 gets paired with reaction 2, etc.

I think instead, we want:

```
rules
    rule 1
        matchCriteria (with one commandType and one errorType)
        ifMatch reaction
    rule 2
        matchCriteria (with one commandType and one errorType)
        ifMatch reaction
```

But I think we can merge this as-is and address it separately. On its own terms, this looks correctly-implemented,  and this PR nicely unblocks both the HTTP API work and the internal `opentrons.protocol_engine` work.

2024-07-24 01:58 UTC, SyntaxColoring commented on robot-server/robot_server/runs/error_recovery_mapping.py
> +                        raise NotImplementedError  # No protocol engine support for this yet. It's in another ticket.
```suggestion
                        raise NotImplementedError  # No protocol engine support for this yet. EXEC-302
```

2024-07-24 16:58 UTC, TamarZanzouri commented on robot-server/robot_server/runs/error_recovery_mapping.py
> +                    and defined_error_data.public.errorType
can we not use isInstance here instead of string comparison?

2024-07-24 17:12 UTC, merged

2024-07-24 17:17 UTC, SyntaxColoring commented on robot-server/robot_server/runs/error_recovery_mapping.py
> +                    and defined_error_data.public.errorType
We can't, not easily anyway.

We're taking JSON that's been parsed from the HTTP client, and turning it into a function that `ProtocolEngine` can call to determine how to handle an error.

For an `isinstance` check to work, we would need everything that the HTTP client might specify to parse into a distinct Python type. That's possible to do, and it might bring benefits for OpenAPI generation. But we would have to keep it in sync every time we added a new `errorType` to `opentrons.protocol_engine`, and I don't think we want to do that.

2024-07-24 19:04 UTC, TamarZanzouri commented on robot-server/robot_server/runs/error_recovery_mapping.py
> +                    and defined_error_data.public.errorType
spoke on the phone to further understand. I understand why we chose this approach. Thank you Max!

2024-07-24 19:33 UTC, aaron-kulkarni commented on robot-server/robot_server/runs/error_recovery_models.py
> +    )
#15785