feat(protocol-designer, app, api): step grouping proof of concept
OpenTrons/opentrons-api pull request #15737
Opened 2024-07-22 17:08 UTC by jerader

addresses AUTH-573

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

2024-10-24 13:05 UTC, sanni-t commented on api/src/opentrons/protocol_runner/json_translator.py
> +                raise ValueError("Uh oh")
Probably needs real error :P

2024-12-03 18:51 UTC, jerader commented
This PR was initially created before the PD redesign work started. the PD UI components that were previously used are soon to be deprecated and deleted since the PD redesign wrote completely new UI components. 

This is the followup ticket to utilize the new redux actions and selectors that were created in this PR: https://opentrons.atlassian.net/browse/AUTH-1112

2024-12-05 21:53 UTC, koji commented on app/src/organisms/Desktop/ProtocolDetails/AnnotatedSteps.tsx
> +              key={i}
```suggestion
              key={`group-${i}`}
```

2024-12-05 21:53 UTC, koji commented on app/src/organisms/Desktop/ProtocolDetails/AnnotatedSteps.tsx
> +              key={i}
```suggestion
              key={`individual-${i}`}
```

2024-12-05 21:56 UTC, koji commented on app/src/organisms/Desktop/ProtocolDetails/AnnotatedSteps.tsx
> +      cursor="pointer"
```suggestion
      cursor={CURSOR_POINTER}
```

2024-12-05 22:00 UTC, koji commented on app/src/organisms/Desktop/ProtocolDetails/AnnotatedSteps.tsx
> +              >
```suggestion
            <Flex
              alignItems={ALIGN_CENTER}
              backgroundColor={backgroundColor}
              color={COLORS.black90}
              borderRadius={BORDERS.borderRadius4}
              padding={`${SPACING.spacing8} ${SPACING.spacing8} ${SPACING.spacing8} ${SPACING.spacing16}`}
              
            >
              <LegacyStyledText
                as="h3"
                fontWeight={TYPOGRAPHY.fontWeightSemiBold}
              >
```

2024-12-05 22:04 UTC, koji commented on app/src/organisms/Desktop/ProtocolDetails/AnnotatedSteps.tsx
> +            minWidth={SPACING.spacing16}
do you think it is possible to avoid using width in p tag?

2024-12-05 22:06 UTC, koji commented on app/src/organisms/Desktop/ProtocolDetails/AnnotatedSteps.tsx
> +            color={COLORS.black90}
if this is for icon, recommend you set color in Icon.

2024-12-06 18:36 UTC, sfoster1 requested changes
Couple things I think we need to look at it in the app and api

2024-12-06 18:36 UTC, sfoster1 commented on api/src/opentrons/cli/analyze.py
> +    commandAnnotations: List[Any]
I think this will make the old analyses stored in the robot persistence database fail to rehydrate, we may need to either make this optional or add a migration

2024-12-06 18:36 UTC, sfoster1 commented on app/src/organisms/Desktop/ProtocolDetails/AnnotatedSteps.tsx
> +  const groupedCommands = analysis.commands.reduce<
this is running once per render of this component, can we bounce it to a hook or something (or ideally store it in redux when we rehydrate an analysis from somewhere) since it's a full commands list walk

2024-12-09 18:27 UTC, jerader commented on app/src/organisms/Desktop/ProtocolDetails/AnnotatedSteps.tsx
> +  const groupedCommands = analysis.commands.reduce<
thanks Seth, I'll add it to redux.

2024-12-09 19:32 UTC, jbleon95 commented on api/src/opentrons/cli/analyze.py
> +    commandAnnotations: List[Any]
This is pointing at the CLI analysis model (which probably should have this type as `CommandAnnotation` but thats a separate thing), but for the robot-server analysis model, this should be a safe change to make without adding a migration. The robot-server `CompletedAnalysis` model has a default factory for command annotations and we store the analysis just as JSON. Tested this by throwing this branch on a robot with existing runs and didn't see any issues.

2024-12-09 21:33 UTC, sfoster1 approved these changes
Looks awesome to me!

2024-12-09 21:52 UTC, sanni-t approved these changes
🙌 Annotations backend work looks great!

2024-12-11 17:23 UTC, merged