feat(api): Add robot context API skeleton
OpenTrons/opentrons-api pull request #15745
Opened 2024-07-22 19:55 UTC by Laura-Danielle

# Overview

Initial PR to create a skeleton API which exposes certain methods of a versioned HW api for finer robot control.

# Test Plan

- Verify that a protocol which uses `ctx._hw_manager` still works as expected

# Changelog

- Add a skeleton robot context

# Review requests

Check that you're OK with how we access this API using python.

# Risk assessment

Should be low-medium as we just changed how the underlying hardware is working as expected.

2024-07-22 20:09 UTC, DerekMaggio commented
There is a class called RobotContextTracker that is part of performance-metrics. 

If this feature makes more sense to call RobotContext than performance-metrics than it should get changed. I was instantly confused that you were using the performance-metrics class. Until I realized you weren't.

2024-07-23 13:37 UTC, sfoster1 requested changes
I think the signature of `move_to` is wrong and also we might want to pull out the reiteration of the function name in the `NotImplementedError`s since we'll just have to keep them up to date until merge.

2024-07-23 13:37 UTC, sfoster1 commented on api/src/opentrons/protocol_api/robot_context.py
> +        abs_axis_map: Dict[hw_types.Axis, hw_types.AxisMapValue],
this doesn't seem like it should take `abs_axis_map`, right? per the design doc, this is basically the normal `move_to` but it lets you specify `EXTENSION` as the mount so you can move the gripper. Otherwise, it still takes a `Point()`.

2024-07-23 13:37 UTC, sfoster1 commented on api/src/opentrons/protocol_api/robot_context.py
> +        raise NotImplementedError("`convert_axes_map` not yet implemented.")
```suggestion
        raise NotImplementedError("`axis_coordinates_for` not yet implemented.")
```

2024-07-23 14:39 UTC, Laura-Danielle commented
> There is a class called RobotContextTracker that is part of performance-metrics.
> 
> If this feature makes more sense to call RobotContext than performance-metrics, the class in performance-metrics should get changed. I was instantly confused that you were using the performance-metrics class. Until I realized you werent.
> 
> If performance-metrics should be changed just let me know and I can handle it

Hey @DerekMaggio yes I think we definitely want to call this the `RobotContext`.

2024-07-23 14:43 UTC, DerekMaggio commented
@Laura-Danielle, [ticketed here](https://opentrons.atlassian.net/browse/EXEC-623)

2024-07-24 14:05 UTC, ecormany requested changes, later dismissed
Thanks for giving me a preview of this! We do need to make sure that docs builds succeed before merging to `edge` — see inline comment. All my other comments are wordsmithing that can be addressed now or later.

2024-07-24 14:05 UTC, ecormany commented on api/src/opentrons/protocol_api/robot_context.py
> +    This interface will not be present in PAPIv3.
3️⃣ 👀

2024-07-24 14:05 UTC, ecormany commented on api/src/opentrons/protocol_api/protocol_context.py
> +    def robot(self) -> RobotContext:
The presence of this without publishing the RobotContext docs raises a Sphinx warning. We treat those as failures in API docs build. To successfully build, either:

- Add a (temporary) `nitpick_ignore_regex` at the bottom of `/api/docs/v2/conf.py`
- Add `.. autoclass:: opentrons.protocol_api.RobotContext` to `/api/docs/v2/new_protocol_api.rst` <-- you may or may not want to do this one right now because it also requires importing `RobotContext` in `__init__.py`, and it effectively "publishes" docs for this class in the sandbox.

We need to pick one before merging, or else subsequent docs builds on `edge` will fail.

2024-07-24 14:05 UTC, ecormany commented on api/src/opentrons/protocol_api/robot_context.py
> +    A context for exposing finer robot control movement.
For parallelism with other docstrings, maybe something like:
> A context for the movement system of the robot.

2024-07-24 14:05 UTC, ecormany commented on api/src/opentrons/protocol_api/robot_context.py
> +    controlling the gripper claw or pipette motors.
```suggestion
    Its methods can command the robot to perform an action, like moving to an absolute position,
    controlling the gripper jaw, or moving individual pipette motors.
```
the claaaaaw (our standard terminology is "jaw").

2024-07-24 14:05 UTC, ecormany commented on api/src/opentrons/protocol_api/robot_context.py
> +    def grasp_gripper(self, force: float) -> None:
I would suggest `open_gripper` and `close_gripper`, since that's the terminology I've seen elsewhere. `open_gripper_jaw` and `close_gripper_jaw` would be even more specific.

2024-07-24 17:09 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/robot_context.py
> +        abs_axis_map: Dict[hw_types.Axis, hw_types.AxisMapValue],
What stability guarantees are we making about this robot context stuff? Is it the same as the "normal" Python Protocol API, where we preserve backwards compatibility and it's governed by `apiLevel`?

If so, I think we should not use anything from `hw_types`, or anything defined outside `opentrons.protocol_api`, in our public signatures. I can elaborate on this if needed, but going forward, I think we need to draw a really bright line between what is publicly importable and usable, and what is not.

But that doesn't apply if you're intentionally leaving these new APIs loose, raw, and non-guaranteed.

What do you think?

2024-07-24 17:09 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/robot_context.py
> +    def release_gripper(self) -> None:
What's the line between "low-level, belongs in `RobotContext`" and "high-level, belongs in `ProtocolContext`"?

Like, is grasping the gripper really more low-level than moving to coordinates and aspirating in-place? Or retracting the pipettes?

I guess what I'm getting at is: exposing a lot of this stuff seems like a good idea, but should we just add it to `ProtocolContext`?

2024-07-24 17:09 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/robot_context.py
> +    def release_gripper(self) -> None:
What's the line between "low-level, belongs in `RobotContext`" and "high-level, belongs in `ProtocolContext`"?

Like, moving to coordinates and aspirating in-place can be done with `ProtocolContext`. So can retracting the pipettes. Is grasping the gripper really more low-level than those?

I guess what I'm getting at is: exposing a lot of this stuff seems like a good idea, but should we just add it to `ProtocolContext`?

2024-07-24 17:09 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/robot_context.py
I know this is still a draft, just a question for my context:

How are we planning to implement all of this? Add a bunch of lower-level commands to `opentrons.protocol_engine`? Or is the point to *bypass* `opentrons.protocol_engine` and go to straight to the hardware API the way we used to before PAPIv2.14?

2024-07-26 13:33 UTC, sfoster1 commented on api/src/opentrons/protocol_api/robot_context.py
The former, lower-level commands added to the engine (probably under a namespace)

2024-07-26 13:35 UTC, sfoster1 commented on api/src/opentrons/protocol_api/robot_context.py
> +    def release_gripper(self) -> None:
Grasping the gripper is more low-level than those because of historical choices we made about the context. Remember, there is no way to command the gripper in protocol api other than `move_labware` with a gripper strategy.

In general, the dividing line is: would we recommend this function to the average biologist? Or would we recommend it to an integrator of some new equipment?

2024-07-26 13:35 UTC, sfoster1 commented on api/src/opentrons/protocol_api/robot_context.py
> +        abs_axis_map: Dict[hw_types.Axis, hw_types.AxisMapValue],
This has the same stability guarantees as the rest of the API, so you are correct, and we should not use anything defined outside `opentrons.protocol_api`.

2024-07-29 15:54 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/protocol_context.py
> +    def robot(self) -> RobotContext:
Will definitely do the first option as we don't want to publish this right now :)

2024-07-31 19:11 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/robot_context.py
> +        abs_axis_map: Dict[hw_types.Axis, hw_types.AxisMapValue],
Agree with you both. Will address the better types in the implementation PRs.

2024-07-31 19:34 UTC, sfoster1 approved these changes
This looks good to me at this point!

2024-08-01 14:07 UTC, merged