chore(robot-server, api): add router for creating run error recovery policies
OpenTrons/opentrons-api pull request #15812
Opened 2024-07-26 18:00 UTC by TamarZanzouri

# Overview

part of https://opentrons.atlassian.net/browse/EXEC-302.

Closes EXEC-589.

add router for creating a error recovery policy for a run. 

# Test Plan

- POST via postman to `/runs/{runId}/policies` with payload:
`{
    "data": "policyRules":
        [
            {
                "matchCriteria": {
                    "command": {
                        "commandType": "aspirate",
                        "error": {
                            "errorType": "TipNotAttachedError"
                        }
                    }
                },
                "ifMatch": "ignoreAndContinue"
            }
        ]
}`
should get a `NotImplementedError` until @SyntaxColoring finishes PE logic. 
 
# Changelog

- added `create_run_policies` to `runs` router. 
- wire up `run_data_manager`, `run_orchestrator` and PE signature.

# Risk assessment

low.

2024-07-26 18:25 UTC, SyntaxColoring requested changes
Looks great, thanks. A handful of small changes.

2024-07-26 18:25 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/base_router.py
> +    base_router.post,
We want this to be `PUT` instead of `POST` because the client is idempotently replacing the list of rules, not appending new rules to the list.

2024-07-26 18:25 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/base_router.py
> +    request_body: Optional[RequestModel[List[ErrorRecoveryRule]]] = None,
I think the request body should be non-`Optional`, right? If the client wants to use an empty list of rules, they should send a request with `{"data": []}`?

2024-07-26 18:25 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/base_router.py
> +    },
It looks like the `status_code` and `responses` args don't match the implementation. We return 200, not 201, and an empty body, not a body with a `Run`.

I think the implementation is correct and this `responses` arg just needs to be updated to match.

2024-07-26 18:25 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +
Can we make this, and the call chain going all the way up, just `def` instead of `async def`?

2024-07-26 18:25 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/run_orchestrator.py
> +
Naming nitpick: Can we call this `set_error_recovery_policy()` instead of `create_error_recovery_policy()`? There is only ever one, and we're overwriting it. "Create", to me, implies that there can be any number of them, and that they can accumulate.

2024-07-26 18:25 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/base_router.py
> +        """
Can we document how these rules work? Either:

* Document the semantics here in the endpoint `description`.
* Or, put the list of rules in a `data.policyRules` field in the request body, instead of just `data` like you do now (see my other comment); and then document the semantics on the `policyRules` field.

EXEC-589 talks a little about the semantics in the way that I have in mind for this documentation.

2024-07-26 18:25 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/base_router.py
> +    request_body: Optional[RequestModel[List[ErrorRecoveryRule]]] = None,
For future extensibility, we might want to make this `{"data": {"policyRules": [...]}}` instead of just `{"data": [...]}`. Otherwise we won't have a clean way to add new fields in the future, if we need to.

I would, but it's your call.

2024-07-26 18:25 UTC, SyntaxColoring commented on robot-server/tests/runs/router/test_base_router.py
> +#     )
Reminder to either uncomment or delete this commented-out test.

2024-07-26 20:03 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/base_router.py
> +    summary="Create run policies",
Oh sorry, one more thing—let's put this under `errorRecoveryPolicies` instead of just `policies`, for specificity.

2024-07-29 15:22 UTC, sfoster1 approved these changes
Makes sense to me overall, thanks!

2024-07-29 18:19 UTC, SyntaxColoring approved these changes
This looks good to merge, and here's some feedback on the description for the future.

2024-07-29 18:19 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/base_router.py
> +        The following rules will persist during the run.
Answering your question in Slack:

* I would not say "When in error recovery," because this endpoint can work at *any* time, even when the run isn't in recovery mode. For example, it's perfectly valid to create a run, and then use this endpoint, and then play the run. You could leave something in to clarify that it's valid to do this at any point during a run, though, if you think that's helpful.
* Instead of saying "add the ability to ignore errors for commands," I would say something like, "decide how to handle different kinds of command failures." Because this endpoint lets you do more than just ignore errors—it lets you do other things too, according to the `ifMatch` field.
* Separately, in the *field description* for `policyRules`, I would probably explain that the rules are evaluated first-to-last and that the first exact match wins. Otherwise it's not clear what happens if you supply conflicting rules.

2024-07-29 18:59 UTC, merged