chore(api): apply mypy consistently across api
OpenTrons/opentrons-api pull request #15821
Opened 2024-07-29 14:59 UTC by aaron-kulkarni

# Overview

At present, typechecking is not applied fully and consistently across the API directory. This PR removes exceptions to mypy checking rules and makes sure that all mypy typechecking tests pass.

EXEC-201 EXEC-202

## Test Plan and Hands on Testing

## Changelog

## Review requests

## Risk assessment

Very low.

2024-08-02 13:41 UTC, sfoster1 reviewed
Going from `Well` to `Location` is done by doing `well.top()` or `well.bottom()` or something. In general though, I wouldn't worry too much about it; just getting the warnings removed is good enough, and making the typing elegant can happen in a followup pass.

The things to worry about are actual non-typechecking code changes to production software. That's what needs a second look, as in the API transfers code, for instance.

2024-08-02 13:41 UTC, sfoster1 commented on api/src/opentrons/protocols/labware.py
> +    from _typeshed import GenericPath
this does seem weird. Can it be `pathlib.Path`?

2024-08-02 15:55 UTC, aaron-kulkarni commented on api/src/opentrons/protocols/labware.py
> +    from _typeshed import GenericPath
I tried a few other ways: using path, using string, etc. but couldn't seem to get everything to fit together properly.

2024-08-02 17:59 UTC, ryanthecoder commented on api/tests/opentrons/hardware_control/test_instruments.py
> +        firmware=_find_smoothie_file(),
Should Be NONE since this isn't running on an actual robot

2024-08-02 18:16 UTC, aaron-kulkarni commented on api/tests/opentrons/hardware_control/test_instruments.py
> +        firmware=_find_smoothie_file(),
Talked about in person - made a different change

2024-08-07 14:19 UTC, sfoster1 approved these changes
Reviewed this, fixed up some little changes and some noise, very happy with it

2024-08-07 16:27 UTC, SyntaxColoring requested changes
This mostly looks good to me, but here's a few things that look questionable.

2024-08-07 16:27 UTC, SyntaxColoring commented on api/tests/opentrons/system/test_wifi.py
> +async def test_list_keys(wifi_keys_tempdir: str) -> None:
```suggestion
async def test_list_keys(wifi_keys_tempdir: Path) -> None:
```

2024-08-07 16:27 UTC, SyntaxColoring commented on api/tests/opentrons/system/test_wifi.py
> +async def test_key_lifecycle(wifi_keys_tempdir: str) -> None:
```suggestion
async def test_key_lifecycle(wifi_keys_tempdir: Path) -> None:
```

2024-08-07 16:27 UTC, SyntaxColoring commented on api/src/opentrons/protocols/advanced_control/transfers.py
> +        dests: List[Union[Well, types.Location]]
Nitpick, optional: if `sources` and `dests` are distinct from `srcs` and `dsts`, could we have more distinct names for them? `normalized_srcs` and `normalized_dsts` maybe?

2024-08-07 16:27 UTC, SyntaxColoring commented on api/src/opentrons/protocols/api_support/util.py
> +        assert isinstance(item, str)
Nitpick, optional:

I think this mypy error that we're "working around" is actually a legitimate typing bug. Calling code can do the expression `123 in ModifiedList(["a", "b", "c"])`, and one would normally expect that to just return `False`, but this code raises an `AttributeError` before this PR or an `AssertionError` with this PR.

I guess we should have it return `False`?

2024-08-07 16:27 UTC, SyntaxColoring commented on api/src/opentrons/protocols/execution/execute_python.py
> +        raise Exception
Is this meant to be `raise exception` (lowercase `e`), so it's handled like the `except KeyError` case a few lines below?

2024-08-07 16:27 UTC, SyntaxColoring commented on api/src/opentrons/protocols/labware.py
> +    assert "loadName" in labware_def["namespace"]
Is this `assert` correct? This looks like it will assert that `"loadName"` is a substring of whatever is the string value for `namespace` (typically `"opentrons"` or `"custom_beta"`)?

2024-08-07 17:14 UTC, sfoster1 commented on api/src/opentrons/protocols/execution/execute_python.py
> +        raise Exception
yes, I think so

2024-08-07 17:14 UTC, sfoster1 commented on api/src/opentrons/protocols/execution/execute_python.py
> +        raise Exception
i think a better way to handle it is for `_find_protocol_error` to allow `None`

2024-08-07 17:15 UTC, sfoster1 commented on api/src/opentrons/protocols/api_support/util.py
> +        assert isinstance(item, str)
Yeah, agreed. We should. It's a problem with how the magic dunders are specified in the language.

2024-08-07 17:16 UTC, sfoster1 commented on api/src/opentrons/protocols/labware.py
> +    assert "loadName" in labware_def["namespace"]
yeah wait what how did I miss this. This should just get deleted

2024-08-07 17:22 UTC, SyntaxColoring approved these changes
Hallelujah.

2024-08-07 18:11 UTC, sfoster1 commented
The failing tests are because fe6252c268f51658e5de6e017cf6985e1f1f0e85 needs to be merged into edge as well as release

2024-08-07 19:36 UTC, merged