refactor(components): move LegacyModal to components directory
OpenTrons/opentrons-api pull request #15870
Opened 2024-08-01 21:12 UTC by jerader

closes AUTH-619

# Overview

The `LegacyModal` , shell and header are going to be used for the PD liquid modal and the PD step list modal so we needed to move the folder from the app directory into the components directory

## Changelog

moved components and fixed imports

## Review requests

do a smoke test in the app and make sure it works as expected.

## Risk assessment

low

2024-08-02 13:34 UTC, sfoster1 requested changes
Okay, but if we're going to use it for new stuff can we please call it something other than `LegacyModal`? I know we have a `Modal` in the app molecules already, so maybe we can figure out some other way to differentiate? What is the difference, anyway? If `app/src/molecules/Modal` is ODD-only, can we rename it to `ODDModal` perhaps?

2024-08-02 14:15 UTC, jerader commented
> Okay, but if we're going to use it for new stuff can we please call it something other than `LegacyModal`? I know we have a `Modal` in the app molecules already, so maybe we can figure out some other way to differentiate? What is the difference, anyway? If `app/src/molecules/Modal` is ODD-only, can we rename it to `ODDModal` perhaps?

@sfoster1 both are good questions. Was blindly moving `LegacyModal` over so PD can use it in the future and did not think about renaming or other components. I'll post in the helix channel!

2024-08-05 14:08 UTC, mjhuff commented on app/src/molecules/OddModal/__tests__/Modal.test.tsx
Does this test file need to be `OddModal.test.tsx`?

2024-08-05 14:10 UTC, mjhuff reviewed
Just a few comments! Will look more as I have time.

Any chance we can leave a docstring on the Modal that we are using for the desktop that it is meant only for the desktop?

2024-08-05 14:10 UTC, mjhuff commented on app/src/molecules/OddModal/__tests__/ModalHeader.test.tsx
Should this be `OddModalHeader.test.tsx`?

2024-08-05 14:10 UTC, mjhuff commented on app/src/molecules/OddModal/__tests__/Modal.test.tsx
Should this file be `OddModal.test.tsx`?

2024-08-05 14:14 UTC, jerader commented on app/src/molecules/OddModal/__tests__/ModalHeader.test.tsx
oops yes you are right, thanks!

2024-08-05 14:16 UTC, jerader commented
> Any chance we can leave a docstring on the Modal that we are using for the desktop that it is meant only for the desktop?

@mjhuff yes, i left a comment on the `Modal` component that says 

```
/**
 * For Desktop app and Hwlix (which includes Protocol Designer) use only.
 */
```

2024-08-05 17:21 UTC, koji commented on components/src/modals/index.tsx
> +export * from './ModalHeader'
maybe creating `index.ts` for export statements?

2024-08-05 17:34 UTC, koji commented on app/src/organisms/DeviceDetailsDeckConfiguration/AddFixtureModal.tsx
> +import type { ModalProps } from '@opentrons/components'
```suggestion
import type { ModalProps } from '@opentrons/components'
import type { OddModalHeaderBaseProps } from '../../molecules/OddModal/types'
```

2024-08-05 17:35 UTC, koji commented on app/src/organisms/DeviceDetailsDeckConfiguration/DeckFixtureSetupInstructionsModal.tsx
> +import type { ModalProps } from '@opentrons/components'
```suggestion
import type { ModalProps } from '@opentrons/components'
import type { OddModalHeaderBaseProps } from '../../molecules/OddModal/types'
```

2024-08-05 17:39 UTC, koji commented on app/src/organisms/EmergencyStop/EstopMissingModal.tsx
> +import type { ModalProps } from '@opentrons/components'
```suggestion
import type { ModalProps } from '@opentrons/components'
import type { OddModalHeaderBaseProps } from '../../molecules/OddModal/types'
```

2024-08-05 17:40 UTC, koji commented on app/src/organisms/EmergencyStop/EstopPressedModal.tsx
> +import type { ModalProps } from '@opentrons/components'
```ts
import type { ModalProps } from '@opentrons/components'
import type {
  OddModalHeaderBaseProps,
  ModalSize,
} from '../../molecules/OddModal/types'
```

2024-08-05 17:46 UTC, koji commented on app/src/organisms/OnDeviceDisplay/RunningProtocol/RunFailedModal.tsx
>  import type { RunError } from '@opentrons/api-client'
```suggestion
import type { OddModalHeaderBaseProps } from '../../../molecules/OddModal/types'
import type { RunError } from '@opentrons/api-client'
```
```suggestion
import type { RunError } from '@opentrons/api-client'
import type { OddModalHeaderBaseProps } from '../../../molecules/OddModal/types'
```

2024-08-06 14:04 UTC, koji approved these changes
Left some comments.
Overall, the changes look good to me. Thank you for doing this!

2024-08-06 14:07 UTC, jerader commented on components/src/modals/index.tsx
> +export * from './ModalHeader'
good call, i'll move the modal component in there out into its own file and change this to index.ts

2024-08-06 14:51 UTC, sfoster1 approved these changes
Awesome! I am unreasonably happy about this. Thank you so much!

2024-08-06 15:06 UTC, mjhuff approved these changes
Thank you for doing this! Looks great!

2024-08-06 15:39 UTC, merged