Exec 504 get error list route
OpenTrons/opentrons-api pull request #15883
Opened 2024-08-02 20:30 UTC by TamarZanzouri

# Overview

closes https://opentrons.atlassian.net/browse/EXEC-504.
add an end point in commands router to fetch commands error list. 

## Test Plan and Hands on Testing

- Post a protocol that will cause a recovery workflow.
- Start the run and let the command fail.
- Resume from recovery.
- Let the run end.
- GET `/runs/{runId}/commands/errors` and make sure you are getting the full command error list. 

## Changelog

- added an end point to commands router` /runs/{runId}/commands/errors`.
- added logic in `CommandsState` to `get_error_slice`.

## Review requests

naming makes sense? changes make sense? location for the new route makes sense? (under commands router)

## Risk assessment

low. adding new logic

2024-08-02 21:00 UTC, SyntaxColoring requested changes
I think we should change the route from `/commands/errors` to `/commandErrors`, but other than that, this looks good to me. Thank you!

2024-08-02 21:00 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/commands.py
> +        based most recent error.
This works for this PR, but this "select automatically based on ___" pattern has given us trouble in the past. There's a lot of ambiguity in that definition, and it's very easy for in-memory stores, SQL-backed stores, and the public HTTP API docs to fall out of sync with each other, especially when we have lots of wrapping layers in the way like `RunOrchestrator` and `RunDataManager`.

I think it would greatly simplify things if, at the level of `opentrons.protocol_engine`, the `cursor` argument were always mandatory. If we want some kind of clever default at the level of the HTTP API, `robot-server` can implement that logic.

2024-08-02 21:00 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/commands_router.py
> +    path="/runs/{runId}/commands/errors",
I think we should probably put this under `/commandErrors` instead of `/commands/errors`. The `/commands/*` namespace is occupied by command UUIDs, and while we *could* probably get away with putting `errors` there too, that seems icky.

2024-08-02 21:00 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/commands_router.py
> +        status.HTTP_404_NOT_FOUND: {"model": ErrorBody[RunStopped]},
Is this `404` out of sync with the implementation? I don't see anything that would raise this.

2024-08-02 21:00 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/commands_router.py
> +    )
I'm not sure why `ResponseList` exists, but it seems weird and I don't think we need it? Take a look at how `GET /commands` returns a list.

2024-08-02 21:00 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/commands_router.py
> +) -> PydanticResponse[SimpleMultiBody[ResponseList[pe_errors.ErrorOccurrence]]]:
~~For the `meta` object to correctly show up in OpenAPI, this and the matching key in `responses` need to be a `MultiBody`, not a `SimpleMultiBody`. Take a look at how `GET /commands` does it.~~

Edit: I was wrong about `SimpleMultiBody` not having `meta`, but something else is going wrong with these declarations:

<img width="454" alt="Screenshot 2024-08-05 at 11 30 45 AM" src="https://github.com/user-attachments/assets/4eca8cfc-d831-490b-b9f9-2acc78a31e86">

(We want `data` to not be `null`, and we want `meta` to show the pagination fields.)

2024-08-02 21:00 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_data_manager.py
> +        raise RunNotCurrentError()
Might be worth a comment somewhere in here that we're raising an error because we haven't implemented the SQL layer yet, not because of any fundamental reason.

2024-08-05 13:31 UTC, sfoster1 requested changes
Some implementation notes, but mostly request-changes because of the route - I agree with @SyntaxColoring, I think this should be a child of `/runs/:runid` directly. I support `/runs/:runid/errors` rather than `/runs/:runid/commandErrors` just because it's shorter and I hate camelcase but obviously that's a matter of taste more than anything else.

2024-08-05 13:31 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/commands.py
> +                cursor = total_length - length
this is a bit confusing. why not set it to `0` directly?

2024-08-05 13:31 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/commands.py
> +        based most recent error.
agree with this

2024-08-05 13:31 UTC, sfoster1 commented on robot-server/robot_server/runs/router/commands_router.py
> +            " based on the currently running or most recently executed command."
this part isn't true, right? it's the most recent error

2024-08-05 13:31 UTC, sfoster1 commented on robot-server/robot_server/runs/router/commands_router.py
> +        status.HTTP_404_NOT_FOUND: {"model": ErrorBody[RunStopped]},
yeah it looks like you're raising a 409 for the run being stopped

2024-08-05 13:31 UTC, sfoster1 commented on robot-server/robot_server/runs/router/commands_router.py
> +        raise RunStopped(detail=str(e)).as_error(status.HTTP_409_CONFLICT) from e
should be 404 to match the docs right (or the docs should say it's a 409)

2024-08-05 18:15 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/commands.py
> +        based most recent error.
moved the logic to run orchestrator (made more sense?) let me know what you think about this.

2024-08-05 18:23 UTC, sfoster1 approved these changes
Much nicer, love the new API presentation. I think we probably still want to hoist the cursor defaulting to the robot server but other than that I'm happy with it.

2024-08-05 18:35 UTC, SyntaxColoring requested changes
I think the return type needs adjusting, but other than that this looks great, thanks.

2024-08-05 18:35 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/base_router.py
> +        )
Agreed with @sfoster1 about hoisting the default cursor logic all the way up here in the future. That'd be nice because then it can live right next to the HTTP-client–facing docstring that describes it.

2024-08-05 18:35 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/base_router.py
> +        status.HTTP_200_OK: {"model": SimpleMultiBody[list[pe_errors.ErrorOccurrence]]},
Both here and in the return type, I think we want `SimpleMultiBody[pe_errors.ErrorOccurrence]`, not `SimpleMultiBody[list[pe_errors.ErrorOccurrence]]`. (No `list` nested in the middle.) Right now, this is declared to return a response where `data` is a list of lists.

I think removing the `list` also lets you get rid of the `# type: ignore[arg-type]` you have on the `return` statement, at least for mypy. For pyright, it still complains, and I'm not sure why.

2024-08-05 19:57 UTC, SyntaxColoring approved these changes
Looks good, thanks!

2024-08-05 20:09 UTC, merged