fix(app, odd): run summery error list bug fixes
OpenTrons/opentrons-api pull request #15953
Opened 2024-08-09 17:02 UTC by TamarZanzouri

# Overview

closes https://opentrons.atlassian.net/browse/RQA-2923.
show warnings/errors depending on the run status.
modal header.
show error details on ODD if run completed with errors.

## Test Plan and Hands on Testing

- run a protocol with ER errors on ODD and desktop app.
- make sure that when the run is complete you are able to see the list of errors.
- warnings shown when run is successfully completed, errors if canceled or failed.

## Changelog

- inject run status to `RunFailedModal`.
- changed modal title
- changed text to show warnings/errors depending on the run status. 
- ODD - show view error details if there is an error list.

## Risk assessment

low. bug fixes.

2024-08-09 17:09 UTC, sfoster1 requested changes
Missed this before, but these texts should be in an i18next lookup with its built-in pluralization logic

2024-08-09 17:09 UTC, sfoster1 commented on app/src/molecules/Modal/ModalHeader.tsx
> -            marginRight={SPACING.spacing16}
really? this will affect all the rest of the modals on the ODD

2024-08-09 17:09 UTC, sfoster1 commented on app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx
> +              : `Run completed with ${
should be in a localization also

2024-08-09 17:09 UTC, sfoster1 commented on app/src/organisms/Devices/ProtocolRun/RunFailedModal.tsx
> +            : `${errors.length} ${
should be in a localization

2024-08-09 17:09 UTC, sfoster1 commented on app/src/organisms/OnDeviceDisplay/RunningProtocol/RunFailedModal.tsx
> +                runStatus === RUN_STATUS_SUCCEEDED ? 'warning' : 'error'
should be in a localization

2024-08-09 17:11 UTC, TamarZanzouri commented on app/src/molecules/Modal/ModalHeader.tsx
> -            marginRight={SPACING.spacing16}
we have a gap in the div above it. I think we can remove this. can test more if needed!

2024-08-09 18:45 UTC, sfoster1 requested changes
Internationalization still not quite right I'm afraid

2024-08-09 18:45 UTC, sfoster1 commented on app/src/organisms/Devices/ProtocolRun/RunFailedModal.tsx
> +                runStatus === RUN_STATUS_SUCCEEDED ? t('warning') : t('error')
this won't translate properly, right? if you translated it into say chinese, if there was more than one error it would have an "s" at the end of the chinese characters, and because the translation isn't number-aware it wouldn't have the right counting word. we should be using [the i18n pluralization tools](https://www.i18next.com/translation-function/plurals) here

2024-08-09 18:45 UTC, sfoster1 commented on app/src/organisms/OnDeviceDisplay/RunningProtocol/RunFailedModal.tsx
> +        : runStatus === RUN_STATUS_SUCCEEDED
same thing re: plural details

2024-08-09 20:57 UTC, sfoster1 approved these changes
approving to unblock, but we should do the pluralization thing

2024-08-12 13:40 UTC, TamarZanzouri commented
> approving to unblock, but we should do the pluralization thing

we probably need to update the packages. will do this in another pr/release. for now reverted the plural changs.

2024-08-12 16:29 UTC, mjhuff approved these changes
Nice! I haven't had the time to test it myself yet, but the code looks good. 

Feel free to merge after CI passes. Thank you for the changes!

2024-08-12 18:02 UTC, merged