feat(api): add innner well geometry to labware definitions
OpenTrons/opentrons-api pull request #15975
Opened 2024-08-12 21:00 UTC by caila-marashaj

2024-08-13 16:14 UTC, SyntaxColoring requested changes
This looks good, thanks, just some minor change requests and a question about the top-level `innerWellGeometry` field.

2024-08-13 16:14 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
> +    )
Question about how this field is supposed to work.

This is a top-level field, applying to the labware as a whole. Is each element in the list a vertical slice of the stack of frustums? And we're assuming that all the wells of a labware have the same stack of frustums?

2024-08-13 16:14 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
> +    )
Could you document whether this height is relative to the labware origin or to the bottom of the well?

2024-08-13 16:14 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
FYI at some point you'll have to hand-edit the JSON schema file in `shared-data`, too. I'm happy to leave that until later until after things have settled a bit more, as long as we have a ticket or `# todo` comments to remind us.

2024-08-13 16:14 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
> +    )
Since only some of these fields make sense depending on the `shape`, we should probably model this as a union of three separate `RectangularCrossSection | CircularCrossSection | HemisphericalCrossSection` classes, using `shape` as the [union discriminator](https://docs.pydantic.dev/latest/concepts/unions/#discriminated-unions).

2024-08-13 16:14 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/labware/types.py
>      gripHeightFromLabwareBottom: float
Do we need to add the new `innerWellGeometry` field here too?

2024-08-13 16:14 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
> +    shape: Literal["rectangular", "circular", "hemisphere"] = Field(
Nit: Let's use `hemispherical` instead of `hemisphere` so they're all adjectives.

2024-08-13 16:14 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
> +    shape: Literal["rectangular", "circular", "hemisphere"] = Field(
I would also consider pulling `hemisphere` into its own thing, outside of the list of cross-sections. Like `bottomTermination: "hemispherical" | "flat"` or something. Like, it doesn't make sense to have a stack of `circular, circular, hemisphere, circular`—`hemisphere` only makes sense at the bottom, right?

2024-08-13 16:48 UTC, caila-marashaj commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
> +    )
yep. We're basically making a list of the cross-sections at the top of every frustum/hemisphere, and then we'll be able to calculate volume from there.

And to start we are assuming that all of the wells are the same in a given labware

2024-08-13 16:50 UTC, caila-marashaj commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
yep, it's ticketed here: https://opentrons.atlassian.net/browse/EXEC-647

2024-08-13 16:53 UTC, caila-marashaj commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
> +    shape: Literal["rectangular", "circular", "hemisphere"] = Field(
yeah I wasn't too sure about this myself- I like this suggestion. And for `bottomTermination` it can be `hemisphere` or just `None`

2024-08-13 17:45 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
> +    )
Great, makes sense. FYI we do have standard labware that have heterogeneous wells, like: https://labware.opentrons.com/opentrons_10_tuberack_nest_4x50ml_6x15ml_conical

2024-08-14 16:04 UTC, caila-marashaj commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
> +    )
hmm ok. I'll add a todo to add a lookup table or something like that for well shape, and we'll only assume homogeneity to start.

2024-08-14 16:08 UTC, caila-marashaj commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
> +    )
https://opentrons.atlassian.net/browse/EXEC-675

2024-08-14 17:03 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
> +    bottom_shape: Optional[Hemisphere] = Field(
```suggestion
    bottomShape: Optional[Hemisphere] = Field(
```

`camelCase` for JSON models, plz

(and of course update the `TypedDict` version the same way)

2024-08-14 17:03 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
> +    top_height: _NonNegativeNumber = Field(
Ditto.

```suggestion
    topHeight: _NonNegativeNumber = Field(
```

2024-08-14 17:03 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
> +    )
Does `Hemisphere` actually need a `depth` field? I think it might be redundant:

* The bottom of the hemisphere is the bottom of the whole well, because the hemisphere is always at the bottom of the geometry stack.
* The top of the hemisphere is the bottom of whatever frustum lies directly above it, because there are no gaps in the geometry stack.
* The hemisphere depth is therefore just `bottomFrustumBottomZ - wellBottomZ`, right? Both of which are already available.

2024-08-14 17:03 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
> +    shape: Literal["rectangular", "circular"] = Field(
The [prior point](https://github.com/Opentrons/opentrons/pull/15975#discussion_r1715557094) about using a discriminated union still applies, but you can do that in another PR if you want.

2024-08-14 18:07 UTC, caila-marashaj commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
> +    )
The height of the bottom cross-section isn't available as the code is right now. I think for that to be the case we would have to either:

- have the geometric layouts of both the top and bottom faces of each frustum, which I think might be redundant
- have the geometric layout of just the top face, and still have the heights of both faces ?

I think what I want to do is:

- have the geometric layout of the top face of each frustum, including its height
- make the `bottomShape` no longer optional, and it will have to be either a hemisphere or a flat face
We'll need to know what the bottom of the well is no matter what, because if it isn't a hemisphere, we'll still need to calculate the surface area at the bottom

2024-08-14 18:31 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
> +    )
Ah, got it, yes, that all makes sense, TY.

2024-08-14 19:32 UTC, ryanthecoder reviewed
Just a nit on hemisphere

2024-08-14 19:32 UTC, ryanthecoder commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
> +class Hemisphere(BaseModel):
Can we rename `Hemisphere` to `SphericalSegment` cause I feel we will inevitably find one that doesn't have a perfect hemisphere

2024-08-14 19:32 UTC, ryanthecoder commented on shared-data/python/opentrons_shared_data/labware/types.py
> +    diameter: float
I think we should replace diameter with radius_of_curvature, because if we don't have a perfect hemisphere we'll need a way of figuring out what the diameter _would_ be

2024-08-14 19:41 UTC, SyntaxColoring approved these changes
Agreed with Ryan, but changes look good, TY!

2024-08-14 20:22 UTC, merged