feat(shared-data): labware schema v3
OpenTrons/opentrons-api pull request #16027
Opened 2024-08-15 20:45 UTC by caila-marashaj

## Review Requests
jesus christ this is nested

2024-08-19 21:10 UTC, SyntaxColoring requested changes
Thank you!

As discussed in-person, we'll focus on the JSON Schema side of this first, and then update the Python and TS bindings when the dust has settled.

I think the JSON Schema needs some restructuring to work as intended. One way to test it is to feed it into a tool like [this](https://json-schema.app/) and click around.

2024-08-19 21:10 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +        "default": {
This property named `default` means we're specifying a shape like:

```javascript
{
  "innerLabwareGeometry": {
    "default": {
      "frusta": [ /*...*/ ]
      "bottomShape": { /*...*/ }
    }
  }
}
```

I don't think that's intentional, is it? We want `innerLabwareGeometry` to be a mapping of arbitrary keys, like:

```javascript
{
  "innerLabwareGeometry": {
    "foo": {
      "frusta": [ /*...*/ ]
      "bottomShape": { /*...*/ }
    },
    "bar": {
      "frusta": [ /*...*/ ]
      "bottomShape": { /*...*/ }
    }
  }
}
```

2024-08-19 21:10 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +                },
This combination of `oneOf` and `anyOf` is interesting, and I see we're doing something similar in `wells`.

I think there is probably a way to get this approach to work, given JSON Schema's flexibility. But I think we should take a different approach. Instead of trying to specify what fine-grained combinations of properties are allowed and disallowed, let's have one subschema for circular frustums and one subschema for rectangular frustums, and do a `oneOf` between the two.

That way, it will map more directly to how we want the Python and TypeScript types to be. That's useful in the short term for humans reviewing them for parity, and it's also possibly useful in the long term for tools that autogenerate Python/TS bindings.

As a rough check, it can be helpful to feed this file into a JSON schema viewer to see how it gets parsed.  [Here](https://json-schema.app/view/%23/%23%2Fproperties%2FinnerLabwareGeometry/%23%2Fproperties%2FinnerLabwareGeometry%2Fproperties%2Fdefault/%23%2Fproperties%2FinnerLabwareGeometry%2Fproperties%2Fdefault%2Fproperties%2Ffrusta%2Fitems?url=https%3A%2F%2Fraw.githubusercontent.com%2FOpentrons%2Fopentrons%2F89befcf867c03bdb14e462d6a107c599f0d0884c%2Fshared-data%2Flabware%2Fschemas%2F3.json), you can see how the tool has to resort to displaying the raw boolean logic, which isn't super helpful.

Here's how we can define the subschemas: https://json-schema.org/understanding-json-schema/structuring#defs

You can also look at `shared-data/command/schemas/9.json`. That whole file is basically one big `oneOf` between a bunch of different command types.

2024-08-19 21:10 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +                }
`topHeight` needs to be nested inside a [`properties`](https://json-schema.org/understanding-json-schema/reference/object#properties) key.

Inside the `properties` key, we should also further specify the `xDimension`/`yDimension`/`diameter` properties as nonnegative numbers, and the `shape` property as the appropriate string literal. Right now, those properties are "required," but nothing if specifying what they are.

2024-08-19 21:10 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +              "type": "string"
This adds a `geometryDefinitionId` field that can be missing, but if it's not missing, it must be a `string`.
That's good and correct, but to work around Pydantic misbehavior, could we also allow it to be `null`? i.e. use `"type": ["string", "null"]` here.

Specifically, what I'm worried about is:

1. We start with a file that doesn't have `geometryDefinitionId`.
2. We parse it in Python, and Pydantic, in its infinite wisdom, converts the missing `geometryDefinitionId` to Python `None`.
3. We reserialize it back to JSON, and Pydantic, again in its infinite wisdom, converts the `None` to JSON `null`.
4. Now, after the round trip through Python, the file no longer conforms to the schema, because `null` is not a `string`.

2024-08-19 21:10 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +            "bottomShape": {
Most of the same feedback applies here, and I think you can probably reuse a lot of the same subschemas with `$ref`.

2024-08-19 21:14 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +        "default": {
One way to do this is with [`additionalProperties`](https://json-schema.org/understanding-json-schema/reference/object#additionalproperties).

[`patternProperties`](https://json-schema.org/understanding-json-schema/reference/object#patternProperties) would also work if we wanted to constrain the keys to certain regexes (like, say they *have* to be alphanumeric), but I don't think we have any reason to do that.

2024-08-20 20:09 UTC, SyntaxColoring requested changes
Yep, the JSON schema looks mostly right now, thanks! Just a few touchups:

2024-08-20 20:09 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +      "properties": {
We need to list out all of these properties in a `required` list. e.g. you can see [here](https://json-schema.app/view/%23/%23%2Fproperties%2FinnerLabwareGeometry/%23%2Fdefinitions%2FInnerWellGeometry/%23%2Fdefinitions%2FInnerWellGeometry%2Fproperties%2Ffrusta%2Fitems/%23%2Fdefinitions%2FBoundedSection?url=https%3A%2F%2Fraw.githubusercontent.com%2FOpentrons%2Fopentrons%2Fa6c63a816bbb4e87ace14cb6ea52029b4b0062ad%2Fshared-data%2Flabware%2Fschemas%2F3.json) that none of these properties are understood as required.

2024-08-20 20:09 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +            }
I think this `"type": "object"`+`"additionalProperties"` level is extraneous? This is saying that every element of the array is an object that can have arbitrarily-named properties whose values conform to the `BoundedSection` subschema. We want to say, instead, that every element of the array is an object confirming to the `BoundedSection` subschema.

I think you just want to put the `$ref` directly inside `"items"`.

2024-08-20 20:09 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +      "properties": {
Separately, I would specify [`additionalProperties: false`](https://json-schema.org/understanding-json-schema/reference/object#additionalproperties) on all the new objects we're adding to this schema. Otherwise, when writing labware definitions, it's easy to make mistakes like misspelling property names. `additionalProperties: false` is consistent with what this schema has done so far. 

I can imagine us lifting that restriction, for extensibility, but that would be a separate PR.

2024-08-20 20:09 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +    }
Right now, the schema is saying that `innerLabwareGeometry` either must not be present, or, if it is present, it must be this big object.

To avoid Pydantic derangement, we should either:

1. Also allow it to be `null`.
2. Require it to be present, even if it's just an empty object.

I suggest going with 1, because then every schema-2 labware definition also counts as a schema-3 labware definition, and we don't have to maintain two sets of bindings.

2024-08-20 20:45 UTC, SyntaxColoring requested changes
And comments for the TypeScript part, when you get there.

Same deal. Looks basically right, just needing a few small touchups.

2024-08-20 20:45 UTC, SyntaxColoring commented on shared-data/js/types.ts
> +}
This definition of `BoundedSection` does not quite match what you have in the JSON Schema or Python bindings. It's missing the nesting under the `geometry` field.

2024-08-20 20:45 UTC, SyntaxColoring commented on shared-data/js/types.ts
> +  innerLabwareGeometry: Record<string, InnerWellGeometry>
Currently, the JSON schema has `innerLabwareGeometry` as not-required, but this binding has it as required.

2024-08-20 20:45 UTC, SyntaxColoring commented on shared-data/js/types.ts
> +  | SphericalSegmentProperties
Naming nitpick: I would remove the word "Properties" from all of these names. Kind of for the same reason you would just name a class `class Foo`, as opposed to `class FooClass`.

I know some of the other types in this file, like `LabwareWellProperties`, are named like that. I'm not quite sure why.

2024-08-20 20:45 UTC, SyntaxColoring commented on shared-data/js/types.ts
> +export interface LabwareDefinition3 {
If we make the `innerLabwareGeometry` property omittable, we can just extend the existing `LabwareDefinition2` type (and rename it, I guess) instead of having to maintain two types at once, which I think would be nice.

2024-08-26 16:20 UTC, SyntaxColoring reviewed
LGTM but I think linting is failing.

2024-08-26 16:20 UTC, SyntaxColoring commented on shared-data/js/types.ts
> +  geometryDefinitionId?: string
I think this should be `geometryDefinitionId?: string | null`, for the same reasons we did that on `innerWellGeometry`.

2024-08-26 16:20 UTC, SyntaxColoring commented on shared-data/js/__tests__/labwareDefSchemaV3.test.ts
> +        labwareDef.innerLabwareGeometry[wellGeometryId].frusta[0].geometry.shape
Heads up that this is assuming that `frusta` is non-empty. That assumption logically makes sense. I think ideally, we would just also specify in the schema that `frusta` has a minimum length of 1. There is [a JSON Schema way to do that](https://json-schema.org/understanding-json-schema/reference/array#length).

Totally fine to leave as-is in this PR if you want to keep things rolling.

2024-08-26 16:22 UTC, sfoster1 approved these changes
Looking good to me pending the inline comments

2024-08-26 16:22 UTC, sfoster1 commented on shared-data/python/tests/labware/__init__.py
> +# TODO(cm): add python validation once labware definitions are added
we can leave the todo, but we shouldn't check in commented-out code

2024-08-26 20:48 UTC, SyntaxColoring approved these changes
Yay!

2024-08-26 20:48 UTC, merged