Exec 686 filter fixit commands out of the commands list
OpenTrons/opentrons-api pull request #16075
Opened 2024-08-20 20:03 UTC by TamarZanzouri

# Overview

## Test Plan and Hands on Testing

## Changelog

## Review requests

## Risk assessment

2024-08-20 20:07 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/run_orchestrator.py
> +            all_commands: Get all command intents.
include_fixit_commands

2024-08-20 20:08 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/run_orchestrator.py
> +            all_commands: Get all command intents.
```suggestion
            include_fixit_commands: Get all command intents.
```

2024-08-23 20:39 UTC, TamarZanzouri commented on robot-server/robot_server/runs/run_data_manager.py
>          # TODO(tz, 8-5-2024): Change this to return to error list from the DB when we implement https://opentrons.atlassian.net/browse/EXEC-655.
```suggestion
        # TODO(tz, 8-5-2024): Change this to return the error list from the DB when we implement https://opentrons.atlassian.net/browse/EXEC-655.
```

2024-08-28 18:09 UTC, SyntaxColoring submitted a review, later dismissed
I know this is a work in progress, just some preliminary comments:

2024-08-28 18:09 UTC, SyntaxColoring commented on robot-server/robot_server/persistence/tables/schema_7.py
> +    sqlalchemy.Column("command_intent", sqlalchemy.String, nullable=True),
1. I know our Pydantic model for `intent` is nullable and omittable, but I would consider making the SQL column non-nullable, since it would be semantically identical to `"protocol"`.
2. We will proooobably need some kind of index on this to efficiently support the slicing and filtering that we want to do? We could do a compound unique index on `(run_id, command_intent, index_in_run)`. I'm not sure how well that pattern would scale to more complicated kinds of filtering, or what the standard SQL practice is for this kind of thing. You can use SQLite's [`EXPLAIN QUERY PLAN`](https://sqlite.org/eqp.html) to experiment.

2024-08-28 18:09 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/command_history.py
> +
Yeah, this approach makes sense to me.

At this point, I think we should also think about a generalized container type that handles these details for us, so we don't have to carefully maintain all these single-purpose attributes. I'm imagining something like:

```python
l = FilterableList[Command](
    filters = {
        "intent": lambda c: c.intent,
        "status": lambda c: s.status,
        # ...
    }
)

l.append(command_1)
l.append(command_2)
# ...

filtered_results = l.slice(filter=("intent", "setup"), begin=10, end=20)
```

2024-09-10 17:49 UTC, sfoster1 requested changes
Looks good, need to remove all that commented out test code though.

Do we need both those `command_intent != 'fixit' OR command_intent == None`  things there? shouldn't fixit != none? isn't that column non-nullable anyway?

2024-09-10 17:49 UTC, sfoster1 commented on robot-server/robot_server/persistence/_migrations/v6_to_v7.py
> +        # Append the new column to existing protocols in v4 database
```suggestion
        # Append the new column to existing protocols in v6 database
```
?

2024-09-10 17:49 UTC, sfoster1 commented on robot-server/robot_server/runs/run_store.py
> +                            run_command_table.c.command_intent != "fixit",
do you really need both of these? doesn't `None != "fixit"`?

2024-09-10 17:49 UTC, sfoster1 commented on robot-server/tests/integration/http_api/persistence/test_compatibility.py
> +    # pytest.param(
fixup or delete

2024-09-10 17:54 UTC, TamarZanzouri commented on robot-server/robot_server/runs/run_store.py
> +                            run_command_table.c.command_intent != "fixit",
true! also removed the NULLABLE option. ill fix it.

2024-09-10 19:37 UTC, sfoster1 approved these changes
Sweet!

2024-09-10 20:25 UTC, vegano1 commented on robot-server/robot_server/persistence/_migrations/v6_to_v7.py
> +        )
We spoke a bit about this yesterday, can you go over why we need to do this?

The change that added [ProtocolKindSQLEnum](https://github.com/Opentrons/opentrons/pull/15822) converts the stored values for protocol_kind from plain strings to SQLEnums like so "<ProtocolKindSQLEnum.STANDARD: 'standard'>". While this is stored on the database in the above format, when you use sqlalchemy to query it returns an actual enum object.

So we don't want to store the plain string values "quick-transfer" and "standard" but `<ProtocolKindSQLEnum.QUICK_TRANSFER: 'quick-transfer'>`  and `<ProtocolKindSQLEnum.STANDARD: 'standard'>` as we have now.

Furthermore, we added this migration step to account for NULL protocol_kind values, which are semantically equal to the "standard" protocol kind in DB schema V5. This change would revert that.

2024-09-11 00:14 UTC, vegano1 reviewed
Left a comment regarding quick transfers protol_kind key in the database.

2024-09-11 17:00 UTC, TamarZanzouri commented on robot-server/robot_server/persistence/_migrations/v6_to_v7.py
> +        )
if we store the string values we are still able to parse as [ProtocolKindSQLEnum](https://github.com/Opentrons/opentrons/pull/15822). [if you will take a look at the code](https://github.com/Opentrons/opentrons/pull/15822/files#diff-4d388f1863f5cb7f953d817e6699638d651f354193793c9df04baaec402588f5R44) `lambda obj: [e.value for e in obj]` should insert the value of the enum in the DB but instead its storing the member. The problem I encountered is that bc we store <ProtocolKindSQLEnum.QUICK_TRANSFER: 'quick-transfer'> when migrating and copying over the row's `ProtocolKindSQLEnum` does not know how to parse this value. its expecting `quick-transfer`.

2024-09-11 17:38 UTC, sanni-t requested changes
Should definitely change the protocol table migration to copy it unmodified.

Other than that I think there has to be an easier way to migrate when only adding a column to the table (like what we do in v4 to v5 migration) but it's a soft suggestion. If this is blocking something then we don't have to make that optimization in this PR.

2024-09-11 17:38 UTC, sanni-t commented on robot-server/robot_server/persistence/_migrations/v6_to_v7.py
> +        )
What @vegano1 said. The protocol table should be copied unmodified. There is nothing wrong with the protocol kind column's contents in v6 database.

2024-09-11 17:38 UTC, sanni-t commented on robot-server/robot_server/persistence/_migrations/v6_to_v7.py
> +            _migrate_db_with_changes(source_transaction, dest_transaction)
Copying over unmodified tables individually work, but I wonder if there's an easier way of doing what you want. You are just adding a column to a table and inserting its contents. There should be a way to just copy over the entire .db file, then open it up with the new schema, add a column and insert contents for the new column.

The method in this PR is not wrong, but feels like we are doing too much work for just adding a column. Also, it's easy to forget to copy over tables and files when doing such individual copying.

2024-09-11 17:38 UTC, sanni-t commented on robot-server/robot_server/persistence/tables/schema_7.py
> +    sqlalchemy.Column("command_intent", sqlalchemy.String, nullable=False, index=True),
I can see the usefulness of creating an index on this, but it doesn't look like we are using it when selecting commands, are we? Not saying that this column shouldn't be indexed, just want to check if we are planning on using the index.

2024-09-11 17:49 UTC, TamarZanzouri commented on robot-server/robot_server/persistence/tables/schema_7.py
> +    sqlalchemy.Column("command_intent", sqlalchemy.String, nullable=False, index=True),
we are using `command_intent` in the where clause when slicing  historical run commands

2024-09-11 17:57 UTC, TamarZanzouri commented on robot-server/robot_server/persistence/_migrations/v6_to_v7.py
> +            _migrate_db_with_changes(source_transaction, dest_transaction)
I agree but its not just adding a column. Its selecting the command as a json and extracting data from it. I agree, if it was just a simple SQL server I would have probably just ALTER and UPDATE, but its a bit more complicated when using json objects.

2024-09-11 18:05 UTC, TamarZanzouri commented on robot-server/robot_server/persistence/_migrations/v6_to_v7.py
> +        )
> values_callable –
> A callable which will be passed the PEP-435 compliant enumerated type, which should then return a list of string 
> values to be persisted. This allows for alternate usages such as using the string value of an enum to be persisted to the database instead of its name. from documentation. https://docs.sqlalchemy.org/en/14/core/type_basics.html#sqlalchemy.types.Enum

2024-09-12 18:29 UTC, TamarZanzouri commented
tested migrations! works perfectly! tested changes in route - works as expected

2024-09-12 20:47 UTC, sanni-t approved these changes
Yay! I'm glad we were able to figure out the enum weirdness and reduce the steps needed to do the migration. 

Have a nitpick and a question. Otherwise the db changes lgtm!

2024-09-12 20:47 UTC, sanni-t commented on robot-server/robot_server/persistence/_migrations/v6_to_v7.py
> +        )
Nitpick- you don't *need* to read from the old table. The new table will contain the intent data you need. Will help reduce code lines.

2024-09-12 20:47 UTC, sanni-t commented on robot-server/robot_server/persistence/_migrations/v6_to_v7.py
> +                )
Does this get committed in the same transaction as the table update? I get confused with the different ways `execute` can be called and what it implies. Just want to be sure that it's one transaction.

2024-09-13 15:42 UTC, TamarZanzouri commented on robot-server/robot_server/persistence/_migrations/v6_to_v7.py
> +                )
Should be the same transaction

2024-09-13 17:27 UTC, merged