feat(api): add liquid_surface WellOrigin enum
OpenTrons/opentrons-api pull request #16139
Opened 2024-08-27 16:09 UTC by pmoegenburg

# Overview

## Test Plan and Hands on Testing

## Changelog

## Review requests

## Risk assessment

2024-08-30 20:13 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/types.py
> +    LIQUID_SURFACE = "liquid_surface"
`camelCase` for new public-facing strings in Protocol Engine, please. We think of them as part of the HTTP API, so they inherit [the HTTP API's conventions](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/575078506/HTTP+API+style).

Many of the older fields in Protocol Engine don't obey this convention, unfortunately.

2024-09-17 13:12 UTC, sfoster1 requested changes
This is awesome. It's almost there, but let's get some tests added for the protocol API first.

2024-09-17 13:12 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +    @requires_version(2, 21)  # confirm
confirmed!

2024-09-17 13:12 UTC, sfoster1 commented on shared-data/command/schemas/9.json
> +      "enum": ["top", "bottom", "center", "meniscus"],
This is definitely going to need command schema 10, actually. Let's merge this for now but that's the next thing we should do.

2024-09-17 14:48 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/core/legacy/legacy_well_core.py
> +        assert False, "get_meniscus only supported in API 2.21 & later"  # confirm
Re the `# confirm` comments: yes, this looks right.

2024-09-17 14:48 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/geometry.py
> +                if height:
```suggestion
                if height is not None:
```

Nitpick: Let's avoid a height of `0.0` counting as "liquid height unknown," since `get_last_measured_liquid_height()` defines `None` as the official sentinel for "liquid height unknown".

This probably will not matter in practice because the probe will probably never return a height of exactly 0.0. Just a semantic thing.

2024-09-17 14:48 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/geometry.py
> +                        z=height + offset.z,
It looks like we're currently storing these heights as raw absolute deck coordinates. I think we instead need to store them as relative heights from the bottom of the well or the bottom of the labware.

Imagine a protocol that:

1. Puts a labware in a deck slot
2. Measures the liquid height
3. Moves the labware to a Heater-Shaker module (whose surface is above that of deck slots)
4. Tries to aspirate at the meniscus

If I'm correctly reading the behavior as implemented in this PR, the pipette will try to drill through the labware to go to the z-coordinate where the meniscus *was* when the labware was sitting directly on the deck. We'll want it to instead go to where the meniscus is *now,* adding the height of the module.

This can change in another PR if you prefer.

2024-09-17 14:48 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/geometry.py
> +                        z=height + offset.z,
Separately, the `liquidProbe` Protocol Engine command and the `InstrumentContext.measure_liquid_height()` method currently *return* the height in absolute deck coordinates, and IMO they should also return it as a relative height from the bottom of the well, because that's the primary way that pipette positioning works when you're writing a protocol.

This doesn't have to happen in this PR, but I do think we should do it before too many internal scripts start relying on the deck-coordinates way.

2024-09-17 15:04 UTC, caila-marashaj reviewed
Agree with Seth and Max's comments, otherwise looking good!

2024-09-17 15:53 UTC, pmoegenburg commented on api/src/opentrons/protocol_engine/state/geometry.py
> +                if height:
Good call. Changed this population to None so this works: https://github.com/Opentrons/opentrons/blob/5e8fbedcb0213677c377c50c70ab7075def62f83/api/src/opentrons/protocol_engine/state/wells.py#L55

2024-09-17 18:09 UTC, sfoster1 requested changes
I think you haven't quite drawn the change to relative positioning all the way through yet. Also, please add a test for the actual protocol api well change, not just the core.

2024-09-17 18:09 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +                )  # in deck coordinates
if the change to `execution.pipetting` is what gives us this data, then this comment is no longer true

2024-09-17 20:08 UTC, sfoster1 approved these changes
Great! Please add a more descriptive PR message before merging and make sure it gets used as the commit message.

2024-09-17 20:23 UTC, merged