feat(protocol-designer): zoomed in deck and off-deck setup
OpenTrons/opentrons-api pull request #16176
Opened 2024-09-03 11:23 UTC by jerader

closes AUTH-757 AUTH-758 AUTH-748 AUTH-687

# Overview

## Test Plan and Hands on Testing

## Changelog

## Risk assessment

low, behind ff, but is a big PR

2024-09-03 18:32 UTC, shlokamin reviewed
first round of comments, still making my way through

2024-09-03 18:32 UTC, shlokamin commented on protocol-designer/src/labware-ingred/actions/actions.ts
> +export interface SelectLabwareDefUriAction {
nit: maybe rename these to `SELECT_LABWARE` and `selectLabware` so they read nicer? i don't think the def uri part is super relevant to redux and i dont think theres any namespace collision risk. and it would be like `SELECT_MODULE` and  `SELECT_FIXTURE`

2024-09-03 18:32 UTC, shlokamin commented on protocol-designer/src/labware-ingred/actions/actions.ts
> +export interface ZoomedInAction {
nit: redux actions are meant to denote a state change, which is why they are verbs. maybe call this `SELECT_SLOT` or `ZOOM_INTO_SLOT`

2024-09-03 18:32 UTC, shlokamin commented on protocol-designer/src/labware-ingred/actions/thunks.ts
> +export const selectPreselectedSlotInfo: (
nit: `selectPreselectedSlotInfo` is a little confusing to me (is it selected or preselected?). it looks like this action creator is going to select labware, modules, and fixtures. whether they are "preselected" or not doesn't sound relevant to redux so maybe name this `addSlotInfo` or something?

2024-09-03 18:32 UTC, shlokamin commented on protocol-designer/src/labware-ingred/actions/thunks.ts
> +  dispatch(selectFixture({ fixture: preSelectedFixture ?? null }))
if there are no labware/modules/fixtures we probably should not be dispatching actions right? even if the payload is null it seems a little weird because setting it to `null` seems like we're intentionally clearing the state

2024-09-03 18:32 UTC, shlokamin commented on protocol-designer/src/labware-ingred/reducers/index.ts
> +const initialState: ZoomedInSlotInfoState = {
maybe call this `selectedSlotInfo` instead to decouple the concept of zooming from state management

2024-09-03 18:32 UTC, shlokamin commented on protocol-designer/src/labware-ingred/reducers/index.ts
> +    //  @ts-expect-error
we should remove these `@ts-expect-error` statements

2024-09-03 18:39 UTC, ncdiehl11 requested changes

2024-09-03 18:39 UTC, ncdiehl11 commented on protocol-designer/src/pages/Designer/DeckSetup/SlotOverflowMenu.tsx
>  const MenuButton = styled.button`
Let's add border radius so hover doesn't remove radius:
`border-radius: inherit;`

2024-09-03 18:39 UTC, ncdiehl11 commented on protocol-designer/src/pages/Designer/DeckSetup/HoveredItems.tsx
> +  const hoveredSlotPosition = React.useMemo(
I think we need an affordance for rendering the Thermocycler in A1. Like this maybe
```
  const isThermocycler =
    hoveredModule != null &&
    getModuleType(hoveredModule) === THERMOCYCLER_MODULE_TYPE
  const thermocyclerSlot = robotType === OT2_ROBOT_TYPE ? '7' : 'B1'
  const slotToRenderIn = isThermocycler ? thermocyclerSlot : zoomedInSlot.slot
  const hoveredSlotPosition = React.useMemo(
    () => getPositionFromSlotId(slotToRenderIn ?? '', deckDef),
    [slotToRenderIn, deckDef]
  )
```
Also we likely need a similar special case in `SelectedHoveredItems`?

2024-09-03 18:39 UTC, ncdiehl11 commented on protocol-designer/src/pages/Designer/DeckSetup/utils.ts
>    cutoutFixtures: CutoutFixture[]
Line 65 may need to change to
```
      if (!['A1', 'B1'].includes(slot) && !FLEX_MIDDLE_SLOTS.includes(slot)) {
```

2024-09-03 18:39 UTC, ncdiehl11 commented on protocol-designer/src/pages/Designer/DeckSetup/utils.ts
> +  const newMinX = x - newWidth / 2 + 125
Where are these constants 125 and 50 coming from? I wonder if we can find these coordinates through calculation...

2024-09-03 18:51 UTC, jerader commented on protocol-designer/src/labware-ingred/actions/thunks.ts
> +  dispatch(selectFixture({ fixture: preSelectedFixture ?? null }))
oh ya lol good call!

2024-09-03 19:02 UTC, jerader commented on protocol-designer/src/labware-ingred/actions/actions.ts
> +export interface ZoomedInAction {
oh ya that makes a lot of sense! I never really thought about that but seeing as they are literally actions, they should be action names 😄

2024-09-03 19:33 UTC, jerader commented on protocol-designer/src/labware-ingred/actions/thunks.ts
> +  dispatch(selectFixture({ fixture: preSelectedFixture ?? null }))
oh ya actually this is used for adding and removing, so i'll change it to "editSlotInfo"

2024-09-03 19:36 UTC, jerader commented on protocol-designer/src/pages/Designer/DeckSetup/utils.ts
> +  const newMinX = x - newWidth / 2 + 125
oh these are to make sure the svg viewport it centered to the screen viewport, otherwise it is slightly down and right.

2024-09-03 19:37 UTC, jerader commented on protocol-designer/src/pages/Designer/DeckSetup/HoveredItems.tsx
> +  const hoveredSlotPosition = React.useMemo(
thank you!

2024-09-03 19:50 UTC, jerader commented on protocol-designer/src/pages/Designer/DeckSetup/utils.ts
>    cutoutFixtures: CutoutFixture[]
oooh, so you can add the thermocycler from slot A1 as well, i didn't think of that! thanks!

2024-09-03 20:04 UTC, jerader commented on protocol-designer/src/pages/Designer/DeckSetup/HoveredItems.tsx
> +  const hoveredSlotPosition = React.useMemo(
hmm i think i'm confused about this actually. is this so that we can see the thermocycler better when its zoomed in?

2024-09-03 20:07 UTC, jerader commented on protocol-designer/src/pages/Designer/DeckSetup/utils.ts
>    cutoutFixtures: CutoutFixture[]
hmm actually i take it back adding it as an option, because if its selected, we'd need to change the slot its selected in. since this redesign is on a "slot" basis and the slot the TC is rendered from is slot B1, i don't think we should allow this

2024-09-03 20:27 UTC, shlokamin reviewed
still making my way!

2024-09-03 20:27 UTC, shlokamin commented on protocol-designer/src/pages/Designer/DeckSetup/DeckItemHover.tsx
> +  isZoomed?: boolean
similar nit: i like `isSelected` to decouple selection from zooming

2024-09-03 20:27 UTC, shlokamin commented on protocol-designer/src/pages/Designer/DeckSetup/DeckSetupTools.tsx
> +    slot ?? ''
rather than passing in an empty string we should probably either return null or have this me an empty list

2024-09-03 20:27 UTC, shlokamin commented on protocol-designer/src/pages/Designer/DeckSetup/DeckSetupTools.tsx
> +  React.useEffect(() => {
is this useeffect necessary? if we're just trying to initialize data we can do that directly in the `useState` can't we?

2024-09-03 20:27 UTC, shlokamin commented on protocol-designer/src/pages/Designer/DeckSetup/DeckSetupTools.tsx
> +      width="374px"
is this 374px one-off intentional from design?

2024-09-03 20:27 UTC, shlokamin commented on protocol-designer/src/pages/Designer/DeckSetup/LabwareTools.tsx
>    }, [moduleType, isNextToHeaterShaker, robotType])
can we remove this useeffect and initialize state inside of the useState?

2024-09-03 20:37 UTC, shlokamin commented on protocol-designer/src/pages/Designer/DeckSetup/SelectedHoveredItems.tsx
> +  const zoomedInSlotInfo = useSelector(selectors.getZoomedInSlotInfo)
nit: i think this should be renamed to `selectedSlotInfo` and `setSlotInfo `

2024-09-03 20:37 UTC, shlokamin commented on protocol-designer/src/pages/Designer/DeckSetup/SlotOverflowMenu.tsx
> +  }
can we put these magic numbers into semantically named variable constants and rename `position` to something more clear?

2024-09-03 20:37 UTC, shlokamin commented on protocol-designer/src/pages/Designer/DeckSetup/SlotOverflowMenu.tsx
> +          zIndex: 5,
do we need this z index?

2024-09-03 20:37 UTC, shlokamin commented on protocol-designer/src/pages/Designer/DeckSetup/SlotOverflowMenu.tsx
> +      height="180px"
are these widths and heights meant to be these specific pixel dimensions?

2024-09-03 21:00 UTC, shlokamin commented on protocol-designer/src/pages/Designer/DeckSetup/utils.ts
> +      getModuleType(selectedModel) !== HEATERSHAKER_MODULE_TYPE &&
er sorry i dont fully understand this. why are we checking if the module is NOT a heater shaker?

2024-09-04 11:33 UTC, jerader commented on protocol-designer/src/pages/Designer/DeckSetup/DeckSetupTools.tsx
> +      width="374px"
yup!

2024-09-04 11:35 UTC, jerader commented on protocol-designer/src/pages/Designer/DeckSetup/LabwareTools.tsx
>    }, [moduleType, isNextToHeaterShaker, robotType])
oh ya this was copied over from the old component, i'll refactor

2024-09-04 11:48 UTC, jerader commented on protocol-designer/src/pages/Designer/DeckSetup/utils.ts
> +      getModuleType(selectedModel) !== HEATERSHAKER_MODULE_TYPE &&
this was copied over from the old util haha

2024-09-04 14:06 UTC, shlokamin commented on protocol-designer/src/pages/Designer/DeckSetup/utils.ts
> +  const newMinX = x - newWidth / 2 + 125
oo yeah @ncdiehl11 not a bad idea to see if we can calculate these instead of hard coding. probably not a right now task but i like this idea

2024-09-04 14:18 UTC, shlokamin commented on protocol-designer/src/pages/Designer/DeckSetup/utils.ts
> +  const { targetViewBox, viewBox, setViewBox } = props
this is very cool (yay JS!), and also IMO we should do this is CSS for performance/bug vector reasons. not worth doing right now unless @ncdiehl11 or @koji have bandwidth but a good refactor to ticket for later.

2024-09-04 14:18 UTC, shlokamin commented on protocol-designer/src/pages/Designer/Offdeck/OffDeckDetails.tsx
> +            {i18n.format(t('off_deck_labware'), 'upperCase')}
lol good catch

2024-09-04 14:18 UTC, shlokamin commented on protocol-designer/src/pages/Designer/index.tsx
> +  //  navigate to landing if suddenly you have no created protocol
how come this is necessary?

2024-09-04 14:18 UTC, shlokamin commented on protocol-designer/src/pages/Designer/index.tsx
> +    }
if we do need this, lets add a console log for debugging purposes. im scarred by all of these hard to find routing bugs 😨

2024-09-04 14:21 UTC, jerader commented on protocol-designer/src/pages/Designer/index.tsx
> +  //  navigate to landing if suddenly you have no created protocol
i keep running into issues where i'm developing and then i lose the redux tree and then i'm randomly on the designer page with no data. maybe this is only development issues so in prod, they shouldn't happen??

2024-09-04 14:22 UTC, jerader commented on protocol-designer/src/pages/Designer/DeckSetup/utils.ts
> +  const { targetViewBox, viewBox, setViewBox } = props
cool i can make a follow up ticket! ya i feel like this current way is not very optimized 😭

2024-09-04 19:36 UTC, jerader commented on protocol-designer/src/pages/Designer/DeckSetup/utils.ts
> +  const { targetViewBox, viewBox, setViewBox } = props
https://opentrons.atlassian.net/browse/AUTH-769

2024-09-04 19:37 UTC, jerader commented on protocol-designer/src/pages/Designer/index.tsx
> +  //  navigate to landing if suddenly you have no created protocol
ok i'm deleting this 😬

2024-09-05 15:32 UTC, ncdiehl11 approved these changes
Looks good! Couple of follow ons we will address

2024-09-05 16:02 UTC, merged