add volume and height math helpers
OpenTrons/opentrons-api pull request #16189
Opened 2024-09-04 18:13 UTC by caila-marashaj

2024-09-05 14:25 UTC, sfoster1 requested changes
I think we can improve the type definitions, organization, and error handling but the math part and approach to testing looks good.

2024-09-05 14:25 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +    def _volume_from_height(
If this is the entrypoint and tested, then IMO it should be public. It doesn't really make sense for this to be a public method of the geometry view, but it's also static, so let's just put these in their own `frustum_helpers.py` file where they're public free functions

2024-09-05 14:25 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +        shape: str,
This function takes a different set of arguments for every kind of shape that you can call it with. The best way to type it is with an overload set:
```
@overload
def volume_from_height(shape: Literal['spherical'], target_height: float, total_frustum_height: float, radius_of_curvature: float) -> float:
    ...

@overload
def volume_from_height(shape: Literal['rectangular'], target_height: float, total_frustum_height: float, bottom_length: float, bottom_width: float, top_length: float, top_width: float) -> float:
    ...

```
and so on.

The overloads form the externally-visible function definition; when you actually write the function body, you may still need the "everything is optional" approach, but you probably won't have to do the asserts because mypy will yell at you if you call it wrong

2024-09-05 14:25 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +    def _height_from_volume(
see my comments on `volume_from_height`

2024-09-05 14:25 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +        shape: str,
it may also be a better idea to have, separately, `volume_from_height_spherical()` and `volume_from_height_rectangular()` and have the top level `volume_from_height()` just dispatch appropriately, but that's up to you.

2024-09-05 14:25 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +        assert len(potential_heights) == 1
this needs more than an assert - this would happen if something either got bad sensor data, or got bad data from a labware definition. these are possible, especially with custom definitions, so we should have this be an enumerated error.

2024-09-05 14:34 UTC, jbleon95 requested changes
The actual body of the added functions look good besides for a couple nitpicks on that and some of the testing.

The bigger change I'm going to request here is moving the `@staticmethod` functions added to the `GeometryView` to be instead in its own helper function file. The reason for this has more to do with future unit testing than any dislike of static methods. If these methods remain where they are, future testing will have to make sure that any tested value will have to be mathematically accurate, even for unrelated tests or tests for code structure and not functional value testing.

If these are moved to their own file, then we can follow the pattern of monkeypatching out these functions, allowing geometry tests to focus on the higher level organization and let the frustra calculations be tested purely in isolation.

2024-09-05 14:34 UTC, jbleon95 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +    ) -> List[float]:
I would make this return a tuple, rather than a list, since the values inside are unchanging.

2024-09-05 14:34 UTC, jbleon95 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +    ) -> List[float]:
Same here

2024-09-05 14:34 UTC, jbleon95 commented on api/tests/opentrons/protocol_engine/state/test_geometry_view.py
> +@pytest.mark.parametrize("frustum", [f for f in RECTANGULAR_TEST_EXAMPLES])
```suggestion
@pytest.mark.parametrize("frustum", RECTANGULAR_TEST_EXAMPLES)
```
don't need the list comprehension here

2024-09-05 14:34 UTC, jbleon95 commented on api/tests/opentrons/protocol_engine/state/test_geometry_view.py
> +@pytest.mark.parametrize("frustum", [f for f in CIRCULAR_TEST_EXAMPLES])
```suggestion
@pytest.mark.parametrize("frustum", CIRCULAR_TEST_EXAMPLES)
```

2024-09-05 14:34 UTC, jbleon95 commented on api/tests/opentrons/protocol_engine/state/test_geometry_view.py
> +    random_indices = [randint(0, len(frustum["height"])) for i in range(5)]
I've never been a fan of randomness in unit tests, just because of my general dislike of non-determinism in these kind of tests. Even though this is choosing values within a bound, I'd rather have us just test every single index in the given examples, instead of a random selection.

2024-09-05 21:33 UTC, sfoster1 approved these changes
Excellent, looks great!

2024-09-06 14:04 UTC, jbleon95 approved these changes
Looking good, thanks for the changes.

2024-09-06 14:32 UTC, merged