fix(app): display correct pipette configuration names in run preview
OpenTrons/opentrons-api pull request #16191
Opened 2024-09-04 21:52 UTC by CaseyBatten

# Overview
Covers RQA-3128

Previously we only accepted Column, All, and 8ch configs. This opens the door to cover our newest configurations in the run preview.

## Test Plan and Hands on Testing
Uploa partial tip protocols to a flex utilizing Single, Row, and partial column. Ensure the run preview displays the expected configuration name at each.

## Changelog

## Review requests
Is this the proper way to expand this coverage? We will probably need to do some coverage checking in the future for other areas on the app end that reference the COLUMN type.

## Risk assessment
Low - updates text information on the UI in pattern with existing behavior.

2024-09-05 18:11 UTC, sfoster1 requested changes

2024-09-05 18:11 UTC, sfoster1 commented on app/src/molecules/Command/hooks/useCommandTextString/utils/getConfigureNozzleLayoutCommandText.ts
> +    amount: configurationParams.style === 'SINGLE' || 'ROW' || 'COLUMN' || 'PARTIAL_COLUMN' ? '8' : 'all',
This isn't the logic you probably mean (that would be something like `['SINGLE', 'ROW', 'COLUMN', 'PARTIAL_COLUMN'].includes(configurationParams.style)` which is the js equivalent of `configurationParams.style in ['SINGLE', 'ROW', 'COLUMN', 'PARTIAL_COLUMN']` but also even if you do that won't that make everything say `8`, when single should say 1 and row should say 12 and partial column should say, well, something else?

2024-09-09 15:40 UTC, smb2268 commented on app/src/molecules/Command/hooks/useCommandTextString/utils/getConfigureNozzleLayoutCommandText.ts
> +    amount: configurationParams.style === 'SINGLE' || 'ROW' || 'COLUMN' || 'PARTIAL_COLUMN' ? '8' : 'all',
@CaseyBatten The copy this translates into is "Configure pipette to use X nozzles". Do `QUADRANT` and `PARTIAL_COLUMN` always map to the same number of nozzles? If not, maybe we should change this to say something like "Configure pipette to use X layout"

2024-09-09 16:10 UTC, smb2268 commented on app/src/molecules/Command/hooks/useCommandTextString/utils/getConfigureNozzleLayoutCommandText.ts
> +    amount: configurationParams.style === 'SINGLE' || 'ROW' || 'COLUMN' || 'PARTIAL_COLUMN' ? '8' : 'all',
I can work on the implementation for this once we decide what the strings should be for each configuration.

2024-09-09 21:07 UTC, smb2268 commented on app/src/molecules/Command/hooks/useCommandTextString/utils/getConfigureNozzleLayoutCommandText.ts
> +    amount: configurationParams.style === 'SINGLE' || 'ROW' || 'COLUMN' || 'PARTIAL_COLUMN' ? '8' : 'all',
@ecormany Do you have an opinion on how we should word these in the run preview? Currently we say "Configure {{pipette}} to use {{amount}} nozzles", but this breaks down for quadrant and partial row configurations. Maybe we could say "Configure {{pipette}} to use {{configuration}} layout" with configuration mapping to "single", "row", "partial column", or "all" - or some combination of nozzle vs layout for different configurations

2024-09-10 20:40 UTC, smb2268 commented on app/src/molecules/Command/hooks/useCommandTextString/utils/getConfigureNozzleLayoutCommandText.ts
> +  const ConfigAmount = {
```suggestion
    // TODO(9/10/24): confirm these strings for copy consistency and add them to i18n 
    const ConfigAmount = {
```

2024-09-10 20:41 UTC, smb2268 approved these changes
I think this is good to merge in for alpha.6! Once we have support docs built around these different configurations, let's make sure these strings match the copy they're using. We should also add them to i18n for November since we'll actually be translating everything.

2024-09-10 21:18 UTC, sfoster1 approved these changes
Nice, I think this will work.

2024-09-10 21:20 UTC, merged