feat(protocol engine): calculate well volumetric capacities from labware defs
OpenTrons/opentrons-api pull request #16222
Opened 2024-09-09 22:13 UTC by caila-marashaj

## Overview
This adds a function in `GeometryView` that allows us to calculate the total volumetric capacity inside a given well. We'll traverse all of the listed segments of the well in shared-data, calculate the volume of each one, and map the height at the top of each segment, to the volume contained within the segment. So, the return value will be a dictionary that's something like `{height_0: volume_0, height_1: volume_1}`, where the volume between the bottom of the well and `height_0` will be `volume_0`, the volume contained between `height_0` and `height_1` will be `volume_1`, and the total volume of the well will be the sum of `volume_0` and `volume_1`.

The idea in mapping out heights to volumes rather than just returning the total volume or even a list of volumes, is that we'll likely call this when trying to figure out an unknown volume at some arbitrary height. In this case, we can:

- determine which two cross-sections our target height lies between
- find the volume within whatever frustum the target height is in
- add this volume to the complete volumes of every frustum beneath our target height  

## Changelog

- `bottomShape` is now only an `Optional[SphericalSegment]`
- the first cross-section in `frusta` is now considered to be either a flat bottom of a well (if there is one), or alternatively the cross-section at the top of the `SphericalSegment` on the bottom
- `BoundedSection` is now broken up into either `CircularBoundedSection` or `RectangularBoundedSection`
- `frusta` is expected to contain either only `RectangularBoundedSection`s or only `CircularBoundedSection`s, since this makes the math easier and also reflects how the wells we'll be dealing with are
- some more math in `frustum_helpers.py`

## TODO
- Write some tests

2024-09-10 13:35 UTC, sfoster1 requested changes
Some style and refactor suggestions

2024-09-10 13:35 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +    def get_well_volumetric_capacity(
somewhere between a nit and a bigger criticism: I'd really like us to get the actual math into a helper function of the form `def get_well_volumetric_capacity(labware_def: LabwareDefinition, well_name: str) -> ...` and have the geometry.py side just look like 
```python
def get_well_volumetric_capacity(self, labware_id: str, well_id: str) -> ...:
    labware_def = self._labware.get_definition(labware_id)
    try:
        return this_new_helper_function(labware_def, well_id)
    catch: 
        ...
        # massage exceptions here
```

just because there's so very much code in this file, and ultimately doing the math is something better suited elsewhere.

2024-09-10 13:35 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +    ) -> Dict[Tuple[float, float], float]:
I have some problems with this return shape.

First, I don't quite get what you'd use it for. Is the idea that you would look up the two elements that surround your target volume and linearly interpolate between them? Why wouldn't we just have `def height_from_volume(labware_id, well_id, height) -> float`?

Second, I'm really uncomfortable with having `Tuple[float, float]` as keys in a dictionary. You effectively can only ever use like the result of iterating keys to get the values out, and never a calculation, because any float weirdness will result in a key error. For instance, you'd always have to structure access like:
```
for key, item in this_kind_of_value:
    if key[0] > my_value:
        return item
```

and at that point, why do we have it in a dictionary, where ordering is only tangentially defined, instead of a sequence where ordering is part of the core function of the data structure?

Third, `Dict[Tuple[float, float], float]` doesn't match the comment on line 1207

2024-09-10 13:35 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +        if well_geometry.bottomShape.shape == "spherical":
aren't we missing handling for other kinds of bottom shapes here? we should raise a not implemented error or something if so.

2024-09-10 13:35 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +            # circular and rectangular or vise versa
```suggestion
            # circular and rectangular or vice versa
```

2024-09-10 13:35 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +            for i in range(len(sorted_frusta) - 1):
this is my bias towards avoiding index loops in higher level languages, but we could also do
```python
def leading_pair(seq: Sequence[float]) -> Iterator[Tuple[float, float]]:
    el = next(seq)
    nextEl = next(seq)
    while True:
        yield (el, nextEl)
        el = nextEl
        nextEl = next(seq)
```

and then this loop becomes
```python
for this_frustum, next_frustum in leading_pair(sorted_frusta):
     ...
```

2024-09-10 13:35 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +                top_cross_section_radius = top_circular_cs["diameter"] / 2
let's be consistent with either `/ 2.0` or `/ 2`

2024-09-10 13:35 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/labware/types.py
> +# todo(cm): make bottomShape just an option spherical segment
let's do this now, if that's what the code is being written to handle

2024-09-12 21:01 UTC, ryanthecoder commented on api/src/opentrons/protocol_engine/state/frustum_helpers.py
> +def get_well_volumetric_capacity(
I think we'll need to rethink this method a little bit so it doesn't depend on every well being a Optiona[bottom] + all_one_type_of_frusta. 
I think it should be able to iterate over a list of all potential shapes and stack them up accordingly

2024-09-12 21:13 UTC, sfoster1 approved these changes
approving to unblock but imo that function should return a list of tuples rather than a dict and we can slightly improve the pairwise iterator

2024-09-13 15:14 UTC, caila-marashaj commented on api/src/opentrons/protocol_engine/state/frustum_helpers.py
> +def get_well_volumetric_capacity(
ok, I think we can do a refactor in a follow-up. We can probably check if the cross-sections are different shapes, use the volume of a frustum formula if yes, and use the math we already have if no

2024-09-13 15:58 UTC, merged