chore(shared-data): create liquid class schema v1 and fixture
OpenTrons/opentrons-api pull request #16267
Opened 2024-09-17 16:28 UTC by ncdiehl11

# Overview

This PR introduces the first version of an Opentrons liquid class schema. Single liquid class definitions will adhere to this schema and be keyed by pipette and tip type.

## Test Plan and Hands on Testing

- Look through schema and ensure it adheres to our finalized liquid class testing matrix. Any feedback on schema structure/style is appreciated.
- Try out some test data in a JSON validator. I created a base fixture that passes schema validation. We can modify that for testing.

## Changelog

- create liquid class schema v1
- add fixture

## Review requests

See test plan. Should we leave keys for `patternProperties` pipette and tip type less restrictive strings? Perhaps safeString rather than following more stringent regex?

## Risk assessment

low

2024-09-17 18:19 UTC, sfoster1 requested changes
I'm a little concerned with the regexes that you specify for tips and for pipettes. Because these are keys, they're tough to document; and because we want to keep this open for more pipettes and tips, it's tough to make a properly restrictive and self-documenting regex (insofar as regexes can ever be self-documenting).

What about instead having these levels be arrays, something like
```
"properties: {
    "liquidName": ...,
    ...,
    "byPipette": {
        "type": "array",
        "description": "The settings for each kind of pipette for this liquid",
       "items": {
             "type": "object",
             "description": "The settings for a specific kind of pipette when handling this liquid",
             "properties": {
                   "pipetteModel": {
                         "type": "string",
                          "description": "The pipette model this applies to",
                          // free to have an enum or a pattern or just a string here
                    },
                    "byTipClass": {
                           "description": "Settings for each kind of tip this pipette can use",
                           "type": "array",
                           "items": {
                                "type": "object",
                                "properties": {
                                     "tipClass": {
                                          // again, free to have different enums or patterns or whatever
                                     },
                                     ...
                                }
                           }
                    }
             }
        }
    }

2024-09-17 18:19 UTC, sfoster1 commented on shared-data/liquid-class/schemas/1.json
> +    "^p[0-9]{2,4}": {
I see where you're going with the patternProperties here but I think it's going to be tough to come up with an appropriate regex and I'm not sure this is usefully it.

2024-09-17 18:19 UTC, sfoster1 commented on shared-data/liquid-class/schemas/1.json
> +        "^t[0-9]{2,4}$": {
same comment as with the pipette type

2024-09-17 21:23 UTC, ncdiehl11 commented on shared-data/liquid-class/schemas/1.json
> +    "^p[0-9]{2,4}": {
Yeah, that's a good callout. I like the idea of nesting the properties in arrays of objects containing the specific pipette/tip properties. Just pushed a commit to that effect and made some other refactors for only requiring certain properties if `enable` is `true`.

2024-10-02 16:50 UTC, sfoster1 approved these changes
Looks great to me! Sorry it took me a while to re-review.

2024-10-02 20:38 UTC, sanni-t approved these changes
This is awesome @ncdiehl! Just a couple of nitpicks.

We also need to add volume corrections but we can add those fields later

2024-10-02 20:38 UTC, sanni-t commented on shared-data/liquid-class/schemas/1.json
> +    },
This works, but I _think_ a more concise way of writing the required fields would be something like this-
```
"touchTip": {
      "type": "object",
      "description": "Shared properties for the touch-tip function.",
      "properties": {
        "enable": {
          "type": "boolean",
          "description": "Whether touch-tip is enabled."
        },
        "zOffset": {
          "type": "number",
          "description": "Offset from the top of the well for touch-tip, in millimeters."
        },
        "mmToEdge": {
          "type": "number",
          "description": "Offset away from the the well edge, in millimeters."
        },
        "speed": {
          "$ref": "#/definitions/positiveNumber",
          "description": "Touch-tip speed, in millimeters per second."
        }
      },
      "required": ["enable"],
      "if": {
        "properties": {
          "enable": { "const": true }
        }
      },
      "then": {
        "required": ["zOffset", "mmToEdge", "speed"]
      }
    },
```

i.e., `enable` is required always. And if enable is true, require the additional properties

Same for all the other properties that have gating behind the `enable` key.

2024-10-02 20:38 UTC, sanni-t commented on shared-data/liquid-class/schemas/1.json
> +      "description": "Mixing properties.",
Can we add a more elaborate description like you've used for `submerge`?

2024-10-02 20:38 UTC, sanni-t commented on shared-data/liquid-class/schemas/1.json
> +      "description": "Blowout properties.",
Same comment as `mix` description

2024-10-03 13:51 UTC, jbleon95 commented on shared-data/liquid-class/schemas/1.json
> +    },
I'm going to go further than this and ask if there's a reason why we don't just get rid of `enable` and make the the availability of a particular liquid class property depend on it being defined for a particular tip type, i.e. if it's there it's enabled and if it's not defined it's not enabled. This would simplify the Python models and we could always use known defaults if a user wishes to enable a default disabled property.

2024-10-03 14:49 UTC, sanni-t commented on shared-data/liquid-class/schemas/1.json
> +    },
> This would simplify the Python models and we could always use known defaults if a user wishes to enable a default disabled property.

@jbleon95 while I agree that not having enable/disable makes the python models as well as this schema much more compact, using some known defaults if a user enables a property whose sub-properties aren't defined isn't a great solution. It would lead to confusion and uncertainty about what the defaults are for each of the enable-gated properties.

That said, maybe there's a middle ground. The schema doesn't include whether to enable or disable those properties but you specify it when using the transfer function. So essentially it'll behave the same way you described, except, the liquid class definition will contain definitions of all properties & sub-properties so that when a transfer function wants to use it, it uses the values from liquid class's definition instead of some defaults.

2024-10-08 17:18 UTC, sanni-t reviewed
Some nitpicks but mainly want to make sure that the 'by volume' properties are as discussed. We want them to be objects where keys are volumes. So something like-
```
xyzByVolume: {
    "default": 123.
    "100": 1.2,
    .
    .
}
```
`"default"` will be required for all.

The schema for it would be something like-
```
"airGapByVolume": {
      "type": "object",
      "description": "Settings for air gap keyed by target aspiration volume.",
      "items": {
        "$comment": "Other keys in here should be volume in uL",
        "properties": {
           "default": { 
              "$ref": "#/definitions/positiveNumber"}
        },
        "required": ["default"],
        "additionalProperties": { "$ref": "#/definitions/positiveNumber", }
      }
    },
```
You can even assign pattern properties to the additional keys I think. So they'll always be strings of numbers

2024-10-08 17:18 UTC, sanni-t commented on shared-data/liquid-class/schemas/1.json
> +      "description": "a string safe to use for namespace. Lowercase-only.",
```suggestion
      "description": "A string safe to use for namespace. Lowercase-only.",
```

2024-10-08 17:18 UTC, sanni-t commented on shared-data/liquid-class/schemas/1.json
> +      "enum": ["bottom", "top", "center", "meniscus"]
What do you think about calling these `well-bottom`, `well-top`, `well-center` and `liquid-meniscus`? Much clearer what positions we are talking about. 
(and update the examples in the description or remove them since they're just repetition of the enums)

2024-10-08 17:18 UTC, sanni-t commented on shared-data/liquid-class/fixtures/fixture_glycerol50.json
> +              ],
This should be an object with items keyed by volume.

```
"airGapByVolume": {
    "default": "abc",
    "100": 10,
    "200": 20
}
```

2024-10-08 20:31 UTC, sanni-t approved these changes
Changes look good!! Thanks!!

2024-10-09 20:01 UTC, merged