refactor(api): Port `touchTip`, `liquidProbe`, and `tryLiquidProbe` location updates to `StateUpdate`
OpenTrons/opentrons-api pull request #16261
Opened 2024-09-16 20:04 UTC by SyntaxColoring

## Overview

More incremental work towards EXEC-652.

## Test Plan and Hands on Testing

* [ ] Run some protocols that do liquid probes and touch-tips. Make sure the path planning still looks right.

## Changelog

This continues the pattern started in #16160. The following commands now use the new `StateUpdate` mechanism to update the pipette's logical state for the purposes of path planning:

* `touchTip`
* `liquidProbe`
* `tryLiquidProbe`

## Review requests

Double-check that the behavior of the code that I'm removing from `PipetteStore` is exactly preserved by the code I'm adding to `TouchTipImplementation`, `LiquidProbeImplementation`, and `TryLiquidProbeImplementation`.

## Risk assessment

Medium.

2024-09-16 20:14 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/liquid_probe.py
> +        return e, state_update, deck_point
if its ok can we return a data model instead of a tuple? I find it confusing that the first arg can be an error/z pos

2024-09-16 20:16 UTC, TamarZanzouri requested changes
looks great! a small nip we spoke about in person :-)

2024-09-16 20:59 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/liquid_probe.py
> +        return e, state_update, deck_point
I'm using a `NamedTuple` now, which is a little better, but I'm still cramming a `float` and `Exception` into a single attribute, which sounds like the real point of confusion.

I think I'd like to keep that as-is for type safety reasons. There will always either be a "no liquid found" condition with exception details, or there will be a `z_pos`, so I'd rather represent that in the type system than use `assert`s or whatever. I do see your point about it being confusing when two totally different things are in a single attribute.

2024-09-17 20:48 UTC, TamarZanzouri approved these changes
Thank you for taking the time to try and fix my nip! Lgtm!

2024-09-18 13:43 UTC, merged