Exec 709 put command implementations in charge of labware store updates
OpenTrons/opentrons-api pull request #16276
Opened 2024-09-17 20:11 UTC by TamarZanzouri

# Overview

## Test Plan and Hands on Testing

## Changelog

## Review requests

## Risk assessment

2024-09-23 19:54 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/update_types.py
> +    """Update labware defention from command result."""
```suggestion
    """Update loaded labware."""
```

2024-09-23 22:02 UTC, SyntaxColoring requested changes
Looks great, thank you!

I think we can remove some of the possible values in `StateUpdate`, which will have cascading effects and simplify some of the logic in `state/labware.py`.

2024-09-23 22:02 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/absorbance_reader/close_lid.py
>              private=None,
As far as I can tell, these absorbance reader commands only returned `lidId`, `newLocation` and `offsetId` for implementation ease, so they could act like `moveLabware` commands. We do not actually have a reason to return this data to protocol authors. The fact that this acts like a `moveLabware` command is an implementation detail.

Since the absorbance reader is not released in v8.0 (I think?), I think your `set_labware_location()` work in this PR gives us an opportunity to remove these things from the public command interface and tighten things up. Might be worth a ticket or `# todo` comments.

@CaseyBatten what do you think?

2024-09-23 22:02 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/update_types.py
> +    """
I don't think we want `None` to be a possible value for `new_location`. When you're moving a labware, you need a valid location to move it to. And the `LabwareLocation` union already contains `OFF_DECK`.

2024-09-23 22:02 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/update_types.py
> +    offset_id: typing.Optional[str] | None | NoChangeType
I don't think we want `NO_CHANGE` (`NoChangeType`) to be a possible value of `offset_id`.

If you're moving a labware from one place to another, I think you always need to figure out what its offset will be in its new location. It's never safe to move the labware without updating the offset ID.

2024-09-23 22:02 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/labware.py
> +            return
Nit: This `return` is a no-op, right?

2024-09-23 22:02 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_engine/state/test_labware_store.py
> +            command=command,
You might want to make the `command`s in these tests `Comment` commands or something else other than `LoadLabware` to make it clear that the behavior of the subject only depends on the `StateUpdate`, not on the command or its result.

2024-09-23 22:02 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/labware.py
> +                get_args(LabwareLocation),
Although I see why you'd want to do this, I'd stay away from `isinstance` checking based on `get_args()` because if you have something like this:

```python
U = Union[ClassA, ClassB, Literal["L"]]

isinstance(x, get_args(U))
```

The `isinstance` call will try to check if its argument is an instance of `Literal["L"]`, which will not work. (I think it will raise some kind of error.)

Also, because `get_args()` returns `Any`, mypy will not be able to perform type narrowing.

2024-09-23 22:02 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/labware.py
> -)
🎉

2024-09-24 13:45 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/absorbance_reader/close_lid.py
>              private=None,
I agree. its very similar to move labware but I was not sure if it exactly the same.

2024-09-24 13:54 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/absorbance_reader/close_lid.py
>              private=None,
where do we put the lid? and why don't we appear to let you pick where to put it?

2024-09-24 13:54 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/labware.py
> +                get_args(LabwareLocation),
agree. I think this is probably a good place for a `match` to accomplish a similar thing structurally

2024-09-24 16:09 UTC, CaseyBatten commented on api/src/opentrons/protocol_engine/commands/absorbance_reader/close_lid.py
>              private=None,
> where do we put the lid? and why don't we appear to let you pick where to put it?

The lid is always put on either the Lid Dock that is physically attached to the absorbance reader, or the Reader Slot itself. Both of these are addressable areas provided by the absorbance reader module fixture. Closing the lid will always put it on the Reader Slot (assuming it isn't already closed), and Opening the lid will always put it on the Lid Dock (assuming it isn't already open). 

Regarding Tamar's changes, I believe these should be safe for the reasons Max pointed out above. We did indeed lift the move labware behavior for ease of implementation, hence the similarities. The absorbance reader module's substate is the owner of it's lid's labware ID, so we just use that to identify the lid in later references, no need for this success data that I can tell.

2024-09-25 17:06 UTC, sfoster1 approved these changes
Looks great! Nice!

2024-09-25 17:58 UTC, SyntaxColoring approved these changes
Still that no-op `return` thing, but looks great otherwise. Thank you!

2024-09-25 18:44 UTC, merged