feat(protocol engine): add frustum helpers compatibility with irregular well shapes
OpenTrons/opentrons-api pull request #16299
Opened 2024-09-19 15:30 UTC by caila-marashaj

# Overview

## Test Plan and Hands on Testing

## Changelog

## Review requests

## Risk assessment

2024-09-19 16:28 UTC, sfoster1 requested changes
Excellent. Let's add some tests though. Remember, the code's obvious now, but somebody might accidentally change it later and if tests fail they'll know they messed up.

2024-09-24 13:43 UTC, sfoster1 requested changes
Would love to see an explicit `isclose()` compare instead of set identity for floats.

Also, since this is a math thing, it might be worth investigating using hypothesis, but that doesn't have to be in this pr.

2024-09-24 13:43 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/frustum_helpers.py
>              rounded_root = round(real(root), 4)
since this is inside `if not iscomplex()`, do we need `real()`? or is it still a complex data type but with a 0 `Im`

2024-09-24 13:43 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/frustum_helpers.py
> +    valid_heights_set = set()
I'm a little nervous about using set identity checks for numerics, even if we're rounding them. These are going to be degree 3ish polynomials, right? Can we do an explicit `isclose()` comparison to whatever stored values we already have?

2024-09-24 15:01 UTC, caila-marashaj commented on api/src/opentrons/protocol_engine/state/frustum_helpers.py
>              rounded_root = round(real(root), 4)
complex data type w `+0j`

2024-09-24 15:52 UTC, caila-marashaj commented
> Would love to see an explicit `isclose()` compare instead of set identity for floats.
> 
> Also, since this is a math thing, it might be worth investigating using hypothesis, but that doesn't have to be in this pr.

https://opentrons.atlassian.net/jira/software/c/projects/EXEC/list?selectedIssue=EXEC-726

2024-09-24 17:06 UTC, sfoster1 approved these changes
lgtm!

2024-09-24 18:01 UTC, merged