fix(api): Fix liquidProbe error message after blowout
OpenTrons/opentrons-api pull request #16294
Opened 2024-09-18 21:16 UTC by SyntaxColoring

# Overview

This is the error message fix part of RQA-3213.

## Test Plan and Hands on Testing

```python
from opentrons import protocol_api

requirements = {"robotType": "Flex", "apiLevel": "2.20"}

def run(protocol: protocol_api.ProtocolContext):
    reservoir = protocol.load_labware("agilent_1_reservoir_290ml", "A1")
    tip_rack = protocol.load_labware("opentrons_flex_96_filtertiprack_1000ul", "A2")

    pipette = protocol.load_instrument(
        "flex_1channel_1000", mount="left", tip_racks=[tip_rack]
    )

    trashbin = protocol.load_trash_bin("A3")

    # disable liquid presence detection on the pipette
    pipette.liquid_presence_detection = False

    # dry aspirate to prove it is off
    protocol.comment(f"Reservoir in {reservoir.parent} is to have NO liquid")
    pipette.pick_up_tip()
    pipette.aspirate(1000, reservoir["A1"])

    pipette.blow_out(trashbin)

    protocol.comment(f"Current volume in pipette: {pipette.current_volume}")  # prints 0

    is_liquid_in_reservoir = pipette.detect_liquid_presence(reservoir["A1"])
    protocol.comment(f"Is there liquid in the reservoir? {is_liquid_in_reservoir}")
```

```shell
pipenv run opentrons_simulate rqa_3171.py
```

Before:

> ProtocolCommandFailedError [line 37]: Error 4000 GENERAL_ERROR (ProtocolCommandFailedError): TipNotEmptyError: This operation requires a tip with no liquid in it.

After:

> ProtocolCommandFailedError [line 37]: Error 4000 GENERAL_ERROR (ProtocolCommandFailedError): PipetteNotReadyToAspirateError: The pipette cannot probe liquid because of a previous blow out. Run a `prepareToAspirate` command in a safe place to reset the plunger.

## Changelog

## Review requests

## Risk assessment

2024-09-18 21:19 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/liquid_probe.py
> +            # with a tip that's previously held liquid, which they should avoid anyway.
Does this comment seem correct?

2024-09-18 21:21 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/pipettes.py
> +            None, after blow-out and the plunger is in an unsafe position.
Documentation correction, no behavioral change.

2024-09-19 13:01 UTC, sfoster1 requested changes
nit re: error message wording

2024-09-19 13:01 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/liquid_probe.py
> +            # with a tip that's previously held liquid, which they should avoid anyway.
aside from "here" really meaning "after we move to above the well", yeah

2024-09-19 13:01 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/liquid_probe.py
> +                " Run a `prepareToAspirate` command in a safe place to reset the plunger."
Let's not be so specific with the error here, or if we are this specific let's catch it and rethrow with a different message in the protocol API. The python protocol API has no `prepareToAspirate command`, so this would be pretty confusing for a user to see.

2024-09-19 16:25 UTC, sfoster1 approved these changes
Excellent, thank you!

2024-09-19 16:47 UTC, merged