feat(api): add WellVolumeOffset to WellLocation
OpenTrons/opentrons-api pull request #16302
Opened 2024-09-19 17:36 UTC by pmoegenburg

# Overview

## Test Plan and Hands on Testing

## Changelog

## Review requests

## Risk assessment

2024-09-19 19:29 UTC, sfoster1 requested changes
I think the logic isn't quite right and we're missing a function

2024-09-19 19:29 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/aspirate.py
> +        well_location = params.wellLocation
looks like we're not getting much out of these as intermediates - we just use them once lower down. maybe remove the intermediates to make the pr smaller?

2024-09-19 19:29 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +                    height_after_operation = self.get_ending_height(starting_liquid_height, operation_volume)
`get_ending_height` doesn't seem to exist?

2024-09-19 19:29 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +                if starting_liquid_height is not None:
so this logic isn't quite right with the new logic, right? We want it to be something like, in the `starting_liquid_height is not None` case,
```python
if well_location.volume_offset != 'operationVolume':
    target_height = get_height_after_volume(labware_id, well_name, volume_offset)
else:
    target_height = get_height_after_volume(labware_id, well_name, operation_volume or 0.0)
offset = offset.copy(update={"z": offset.z + target_height + well_location.offset.z)
```

2024-09-19 20:31 UTC, pmoegenburg commented on api/src/opentrons/protocol_engine/state/geometry.py
> +                if starting_liquid_height is not None:
Beat me to my push

2024-09-20 13:54 UTC, sfoster1 reviewed
Can get rid of another intermediate and remove a couple lines from the diff. looks good for now but holding off approving until that `get_ending_height` function exists

2024-09-20 13:54 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/aspirate.py
> +        volume = params.volume
let's remove this intermediate since it's not really needed

2024-09-20 14:50 UTC, SyntaxColoring reviewed
Thank you! Some questions about the outward-facing Protocol Engine API.

2024-09-20 14:50 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/types.py
> +    volumeOffset: WellVolumeOffset = Field(default_factory=WellVolumeOffset)
Since this `WellLocation` class is shared and reused in a bunch of places, adding the volume offset here will add it to the `pickUpTip` command, where I don't think it makes sense, does it? Can we split it up so only the liquid-handling commands are affected?

2024-09-20 14:50 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/types.py
> +    volumeOffset: WellVolumeOffset = Field(default_factory=WellVolumeOffset)
Do you have any future expansions in mind for this top-level `volumeOffset` field? Otherwise, it looks like there's a level of nesting that's not really accomplishing anything?

```javascript
{
    "origin": "top",
    "offset": {"x": 0, "y": 1, "z": 2}
    "volumeOffset": {"volumeOffset": 123}  // <-- here
}

2024-09-20 14:50 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/types.py
> +    volumeOffset: Union[float, Literal["operationVolume"]] = 0.0
If I'm reading this correctly, `operationVolume` is, for example, 15 µL if you're aspirating 15 µL from a 100 µL well. Is that correct? If so:

1. Is `operationVolume` necessary to add to Protocol Engine's API? The Protocol Engine caller already knows the operation volume, since they emitted the `aspirate` command with a volume of 15 µL in the first place. Can't they just specify `"volumeOffset": 15` here, if that's what they want?
2. If we keep `operationVolume,` can we have a docstring here explaining it?

2024-09-20 18:03 UTC, pmoegenburg commented on api/src/opentrons/protocol_engine/types.py
> +    volumeOffset: Union[float, Literal["operationVolume"]] = 0.0
See updated docstring

2024-09-20 18:03 UTC, pmoegenburg commented on api/src/opentrons/protocol_engine/types.py
> +    volumeOffset: WellVolumeOffset = Field(default_factory=WellVolumeOffset)
@sfoster1

2024-09-20 18:03 UTC, pmoegenburg commented on api/src/opentrons/protocol_engine/types.py
> +    volumeOffset: WellVolumeOffset = Field(default_factory=WellVolumeOffset)
@sfoster1

2024-09-20 18:12 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/types.py
> +    volumeOffset: Union[float, Literal["operationVolume"]] = 0.0
Sorry, I'm not seeing anything in the docstring update that deals with `operationVolume`?

2024-09-20 20:49 UTC, pmoegenburg commented on api/src/opentrons/protocol_engine/types.py
> +    volumeOffset: Union[float, Literal["operationVolume"]] = 0.0
Gotcha, updated, thanks for catching that.

2024-09-20 20:58 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/types.py
> +    volumeOffset: Union[float, Literal["operationVolume"]] = 0.0
Thanks for the update.

I'm afraid I still don't understand. You give the example of a `moveToWell` with `volumeOffset: "operationVolume"` that runs prior to an `aspirateInPlace`. When the robot executes that `moveToWell`, where are you saying it's supposed to go? Are you saying it will take the volume from the future `aspirateInPlace` command?

2024-09-23 14:17 UTC, pmoegenburg commented on api/src/opentrons/protocol_engine/types.py
> +    volumeOffset: Union[float, Literal["operationVolume"]] = 0.0
No worries! My running example is Protocol Designer, where the volume fed into `AspirateInPlace` will now be fed into `MoveToWell` via `WellVolumeOffset`. This will have the tip of the pipette move to the level of the meniscus at the end of the aspiration process (with some `WellOffset` so the tip is submerged below the meniscus). If starting height (a priori meniscus level) has not been found (via a LiquidProbe), user will receive a `LiquidHeightUnknownError`.

2024-09-23 21:08 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/types.py
> +    volumeOffset: WellVolumeOffset = Field(default_factory=WellVolumeOffset)
that's probably not necessary yeah, I think we should fix the nesting

2024-09-24 14:07 UTC, sfoster1 requested changes
Couple small things, and also let's remove the last of the temporary comments and commented out code

2024-09-24 14:07 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/types.py
> +class LiquidProbeWellLocation(BaseModel):
I think `LiquidProbeWellLocation` should allow `volumeOffset: float` (i.e., no `operationVolume`) so that you can specify something like `.bottom() + 200ul` for hinting "i'm pretty sure there's this much volume"

2024-09-24 14:07 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/types.py
>  class WellLocation(BaseModel):
I think we should call this `LiquidHandlingWellLocation`, and then have `WellLocation = LiquidHandlingWellLocation` if we don't want to change all the papi code

2024-09-24 14:07 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/types.py
> +                                executing commands with an origin of WellOrigin.MENISCUS. Specifying
honestly, it doesn't even have to be based on the meniscus, right? this could be a volume based offset from anywhere

2024-09-24 14:07 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +        return starting_height # delete, use line above once sub-methods implemented
if we merge this, we should merge the `return ending_height`, and not this comment

2024-09-24 18:27 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +            starting_liquid_height: Union[float, None] = 0.0
recommend pulling these if blocks into separate subfunctions for better testability

2024-09-27 13:58 UTC, sfoster1 requested changes
Looking really solid and definitely moving in the right direction. A couple inline notes to check out. More broadly,
- this is more of a nit, but typically you want your docstrings to have a short first line that quickly summarizes the function, then a linebreak, then the more full documentation. a lot of these functions have a single really long line as a docstring, which will look weird in editor autocorrect previews.
- looks like we don't have any tests for the new functionality in `protocol_engine.state.geometry`, just the fixups to keep the stuff in the geometry view tests passing. definitely want that before we merge
- let's make sure we get this tested on real hardware

2024-09-27 13:58 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/dispense.py
> +    PipetteIdMixin, DispenseVolumeMixin, FlowRateMixin, LiquidHandlingWellLocationMixin
should pass an operation volume here right

2024-09-27 13:58 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +            # raise InvalidWellDefinitionError(message=f"No geometryDefinitionId found for well: {well_name} in labware_id: {labware_id}")
No, we should implement this now. It is correct to say that you can't do this stuff on a well that doesn't have geometry information. If that makes it difficult to test, so be it - let's work up some test labware definitions that at least have a well-defined set of output positions that we can verify.

2024-09-30 16:20 UTC, sfoster1 requested changes

2024-09-30 16:20 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/aspirate.py
> +                well_location.offset.z = -2.0 # disallow offset.z > -1.0 ?
What's this for? Not sure it's a great idea - what if you want to use exactly `operationVolume` without a further offset?

2024-09-30 16:20 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/dispense.py
> +                well_location.offset.z = -2.0 # disallow offset.z > -1.0 ?
similar thing here. also if we do keep it, we shouldn't keep it in multiple places like this.

2024-10-11 13:16 UTC, sfoster1 requested changes
Looking great and almost there! Inline comments for change requests.

Generally, I do not think we should be validating scientific reasonableness in the engine - that should happen in the input layers like PD and PAPI. Specifically that's things like forcing dispense `volumeOffset` to 0, and requiring aspirate z offsets to be <0. Let the engine execute what it's given as long as it won't cause an outright error, like a collision.

2024-10-11 13:16 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/dispense.py
> +            well_location.volumeOffset = 0.0
why? isn't this one of the exact cases we want volume offsets for? if we want to say "hey you should always dispense at the meniscus exactly", that's a thing we should do in the PAPI and in PD; the engine should faithfully execute anything that physically makes sense, even if it isn't scientifically optimal.

2024-10-11 13:16 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/errors/exceptions.py
> +    This would result in aspiration above the meniscus (in air), which should not be allowed.
but it might certainly be something that someone wants to do! for instance, they might be rolling their own air gap function where they're as close to the liquid as possible without being in it so that they can go aspirate more quickly. Like with the volume offsets in dispense, if we want to mandate or even advise this, we should do it in the input layer like PAPI or PD and let the engine faithfully execute whatever it gets.

2024-10-11 13:16 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/aspirate.py
> +                raise InvalidAspirateLocationError(
see comment on the error definition - shouldn't do this

2024-10-11 13:16 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +                    f"Specifying {well_location.origin} with an offset of {well_location.offset} results in an operation location below the bottom of the well"
not always true that this is below the well, right? it could also be below the minimum height. Might be worth raising these exceptions from inside the logic above so we can take that into account.

2024-10-11 13:16 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/labware.py
> +                message=f"No innerLabwareGeometry found for labware_id: {labware_id}."
let's drop a TODO comment in this function for wordsmithing the error (in a followup pr)

2024-10-11 13:16 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/types.py
> +    volumeOffset: float = Field(
are we keeping `WellLocation` around for backwards compatibility? If so, maybe we can avoid adding `volumeOffset` to it.

2024-10-11 13:16 UTC, sfoster1 commented on shared-data/command/schemas/9.json
> +    "LiquidHandlingWellLocation": {
let's revert these changes with `git checkout edge -- shared-data/command/schemas/9.json` and change only command schema 10.

2024-10-11 14:58 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/protocol/models/shared_models.py
> +    offset: Optional[OffsetVector]
Are these used now that https://github.com/Opentrons/opentrons/pull/16420 is merged? You might be able to revert these additions.

2024-10-11 17:52 UTC, pmoegenburg commented on api/src/opentrons/protocol_engine/types.py
> +    volumeOffset: float = Field(
volumeOffset was added to WellLocation at your suggestion to enable more flexibility. Specifically for MoveToWell and TouchTip commands

2024-10-11 18:00 UTC, pmoegenburg commented on api/src/opentrons/protocol_engine/state/geometry.py
> +                    f"Specifying {well_location.origin} with an offset of {well_location.offset} results in an operation location below the bottom of the well"
Updated docstring

2024-10-11 18:45 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/types.py
> +    volumeOffset: float = Field(
okay, cool! sorry for forgetting :)

2024-10-11 18:46 UTC, sfoster1 approved these changes
Looks good to me pending on robot testing!

2024-10-11 20:36 UTC, SyntaxColoring approved these changes
Types mostly look good, just a couple places that I think need to be fixed.

Feel free to merge without fixing these, if you need to unblock something. But I do think we should fix these before release.

I found these by running a dev server (`make -C robot-server dev`), opening the HTTP API documentation (http://localhost:31950/redoc), and clicking through the `params` fields of the many commands in the `GET /runs/{runId}/commands/{commandId}` documentation. Another way of doing this would have been to feed the command schema into a viewer like https://json-schema.app/start.

I haven't looked closely at the `opentrons.protocol_engine` logic part of this since it seems like @sfoster1 already has, but I'm happy to if anyone thinks it's worthwhile.

2024-10-11 20:36 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/blow_out.py
> +class BlowOutParams(PipetteIdMixin, FlowRateMixin, LiquidHandlingWellLocationMixin):
Because `blowout` does not have a `volume` param, it should probably not be allowed to take the `"operationVolume"` sentinel.

In this sense, `LiquidHandlingWellLocationMixin` might be a misnomer. Its fields don't all make sense on `blowout`, even though `blowout` *is* definitely a liquid-handling command. It doesn't have to happen in this PR, but let's keep looking for a more precise name.

2024-10-11 20:36 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/types.py
I'm not sure if this happened in this PR, but the types as written allow `pickUpTip` to take `origin: "meniscus"`. We probably want a separate `WellOrigin` enum that excludes `"meniscus"`.

2024-10-15 21:22 UTC, SyntaxColoring commented on api/src/opentrons/types.py
> +
Recap from in-person discussion:

Yeah, I think this is totally fine as an initial solution. I don't think it makes `Location` any fundamentally worse than it was before.

Because this *is* a public-facing type, we should:

* Add a docstring to `is_meniscus` saying that it's only for Opentrons internal use.
* Make sure `is_meniscus` won't show up in the generated docs.opentrons.com site
    * I don't remember off the top of my head how we usually do this. I used to put `:meta private:` in the docstring, but I think we found once that that didn't *totally* remove it.
    * You can play around with `make docs-clean && make docs` in the `api` subdirectory. I haven't tried this yet. `is_meniscus` might already be excluded.

2024-10-15 21:22 UTC, SyntaxColoring commented on api/src/opentrons/types.py
> +        is_meniscus: Optional[bool] = None,
Because users do occasionally manually construct `Location`s, let's go to some pain here to prevent them from using this internal `is_meniscus` thing.

I would:

* Rename it something like `_ot_internal_is_meniscus`
* Make it [keyword-only](https://docs.python.org/3/glossary.html#term-parameter) so you can't write `Location(point, labware, True)`—you *have* to write `Location(point, labware, _ot_internal_is_meniscus=True)`
* If necessary, [override the Sphinx method signature](https://stackoverflow.com/questions/12082570/override-function-declaration-in-autodoc-for-sphinx) to hide this arg on docs.opentrons.com

2024-10-17 23:32 UTC, merged