feat(robot-server): Add `disableErrorRecovery` to `/settings` endpoints
OpenTrons/opentrons-api pull request #16355
Opened 2024-09-25 19:19 UTC by SyntaxColoring

## Overview

Another step towards EXEC-719.

## Test Plan and Hands on Testing

* [x] Play around with the endpoints with a dev server and make sure they work as expected, including that the value persists across boots.

## Changelog

This adds a `disableErrorRecovery` entry to the `/settings` endpoints. The value persists across boots via prior work in #16333. It does not actually affect robot behavior yet; follow-up work will have to connect it to `RunOrchestrator` etc.

Historically, the `/settings` endpoints have been a dumb window to `opentrons.config.advanced_settings`. We're skeptical of continuing that pattern, because: (1) sometimes these settings actually have nothing to do with the `opentrons` package; and (2) the `opentrons` package is a library that's installed on users' computers, and we don't want it storing global config that only makes sense when running on an actual OT-2 or Flex.

So, this PR goes to a little bit of pain to define the the new setting in `robot_server`, not in `opentrons`. It's kind of half-assed, sorry.

## Review requests

I'm unsure about my overall API design. Are the `/settings` endpoints the right place to add this?

Right now, the `/settings` endpoints are "dynamic": you can only know what options are available to change by running the server and asking it via `GET /settings`. Or by inspecting the Python source. The list of settings isn't statically available in the OpenAPI spec or anything.

This works well when we expect the client to dumbly render whatever the server returns. It's good for stuff like a feature flags page. But it makes less sense for settings that are actual *settings*—actual *product features*—where we want UX designs to dictate specific placement and copy.

So I guess I'm unsure of whether we want to keep extending `/settings` with stuff like this.

## Risk assessment

Low.

2024-09-25 19:38 UTC, sfoster1 requested changes
I agree with your cover comment - I do not think this should be in `/settings`, which regardless of how it started is really now just for feature flags. i would support either having a new route or just having like `/settings/fixed` ("fixed" as opposed to "dynamic", not "fixed" as opposed to "broken") or something

2024-09-25 19:57 UTC, vegano1 commented on robot-server/robot_server/service/legacy/routers/settings.py
> +        if update.id == "enableOEMMode" and robot_type == RobotTypeEnum.FLEX:
Unfortunately this is not accurate, the client uses the `enableOEMMode` advanced setting for the following

- The desktop app uses `enableOEMMode` to determine if the OEM mode toggle should be set or not.
- The ODD uses `enableOEMMode` to render in `branded` or `unbranded` mode

Right now without the `enableOEMMode` advanced setting the OEM Mode feature would not work

2024-09-25 19:59 UTC, vegano1 reviewed
Left a comment for oem mode

2024-09-30 14:16 UTC, SyntaxColoring reviewed
Moved from the existing `/settings` (feature flags) endpoint to a new `PATCH /errorRecovery/settings` endpoint.

I didn't feel good about trying to name and design an API for a more general replacement for `/settings` ("`/settings/fixed`") right now.

2024-09-30 14:16 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/error_recovery/test_settings.tavern.yaml
I'm once again omitting router-level tests with Decoy mocks, because this is a trivial CRUD endpoint and they would be wholly redundant with this Tavern test.

2024-09-30 15:42 UTC, sfoster1 approved these changes
Yeah, this looks good to me. Agree with the choice of route, too

2024-09-30 16:13 UTC, TamarZanzouri approved these changes
Nice job!!!

2024-09-30 17:12 UTC, merged