refactor(api): redefine well geometry structure
OpenTrons/opentrons-api pull request #16392
Opened 2024-09-30 21:12 UTC by caila-marashaj

2024-10-01 13:44 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/frustum_helpers.py
> +def get_cross_section_area(bounded_section: Any) -> float:
definitely don't want `Any` here, want the actual type

2024-10-01 13:44 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/frustum_helpers.py
> +    section: Any,
don't want this as `Any`

2024-10-01 13:44 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/frustum_helpers.py
> +    elif section["shape"] == "circular":
we probably want to have these things be 3d shape names instead of 2d, i.e. `cylinder` rather than circular

2024-10-01 13:44 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/frustum_helpers.py
> +    sorted_well: List[Any],
probably want to avoid `Any`

2024-10-01 16:10 UTC, SyntaxColoring reviewed
Agreed with Seth on avoiding `Any`.

Other than that, looks correct. Thank you! Here are some questions and comments on the underlying data shapes.

2024-10-01 16:10 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> After discovering some new shapes and generally interacting with the new well geometry data structures, I think it would be better to reshape the geometry data a little bit. Rather than having each section of a well be represented by its top cross-section and top height, let's just represent a section in its entirety, with bottom and top cross-sections and bottom and top heights being present in every shape that is not a SphericalSegment.

It's your choice, but I'll propose an alternative. Have a list of 2D cross sections like we did before, but give each cross-section a way to specify a `blend` or `transition` from the element below it. That would give you the same expressive power to represent shapes like these (which I guess is EXEC-712 and EXEC-744). But it would reduce duplication in the definitions and make them less error-prone. I think it also makes the naming a bit easier.

<img src="https://github.com/user-attachments/assets/e2975366-16c1-4f24-8f8c-16d7eb7787bc" width="175">
<img src="https://github.com/user-attachments/assets/158bfc59-e256-4dbf-af2d-64b3b3c97a68" width="175">

I can certainly see the reasoning behind this new way of doing it, though, so no preference from me either way.

2024-10-01 16:10 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +    "TruncatedCircularSegment": {
Just to make sure I understand, is `TruncatedCircularSegment` meant to represent a segment like this?

<img src="https://github.com/user-attachments/assets/158bfc59-e256-4dbf-af2d-64b3b3c97a68" width="175">

2024-10-01 16:10 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +    "RoundedRectangularSegment": {
Just to make sure I understand, is `RoundedRectangularSegment` meant to represent a segment like this?

<img src="https://github.com/user-attachments/assets/e2975366-16c1-4f24-8f8c-16d7eb7787bc" width="175">

2024-10-01 16:10 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +          "type": "number"
FYI, with `topHeight` and `bottomHeight` alone, `TruncatedCircularSegment` and `RoundedRectangularSegment` will not have the expressive power to say whether they're transitioning from bottom-circle to top-rectangle, or bottom-rectangle to top-circle. You could fix that by changing `topHeight` and `bottomHeight` to `circleHeight` and `rectangleHeight`, or by adding a separate `direction` field, or by deciding that it's okay to assume that the circle is always going to be on the bottom.

2024-10-01 16:10 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +    "RoundedRectangularSegment": {
If so, we might want to work on these new names to emphasize the fact that they're always blending between a pure rectangle and pure circle. As-is, if you don't look at the fields, it sounds like `RoundedRectangularSegment` represents something like this:

<img src="https://github.com/user-attachments/assets/764f3148-8a3b-4a72-be46-ce57cfc739d9" width="175">

2024-10-01 16:10 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +          "enum": ["truncatedcircular"]
Nitpick: Let's use `camelCase` for these literals (`truncatedCircular` and `roundedRectangular` instead of `truncatedcircular` and `roundedrectangular`).

2024-10-01 16:10 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
>          }
For spherical well bottoms, what's the current way to represent a spherical bottom that connects smoothly to a conical frustum above it? Is there such a way?

<img width="175" src="https://github.com/user-attachments/assets/057903e4-cb8d-47b6-99a5-462607a16351">

It seems like you'd have to do math based on the observation that the top diameter of the `SphericalSegment` is equal to the bottom diameter of the section above it. That works, but it breaks the self-containedness that you're going for in the rest of this PR.

2024-10-01 16:10 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/labware/types.py
> +#   that is concentric with the square.
I suggest centralizing documentation like this inside the JSON schema, and thinking of the Python bindings as dumb references to it. Basically just for single-source-of-truth reasons.

I would even go as far as to delete the `pydantic.Field` `description`s in `labware_definition.py`, though others have disagreed with me on that.

2024-10-03 13:22 UTC, sfoster1 requested changes
Inline changes.

I also don't quite get the point of taking this data from a labware definition, to a pydantic model, and then out to a typed dict. What does the typed dict give us that the pydantic model doesn't? It kind of seems like it just makes us define everything twice.

2024-10-03 13:22 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/labware/types.py
> +def ToInnerWellGeometryDict(
should probably be `def to_inner_well_geometry_dict` if it's a function rather than a class

2024-10-03 13:22 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/labware/types.py
> +def ToWellSegmentDict(segment: Union[WellSegment, WellSegmentDef]) -> WellSegment:
should probably be `def to_well_segment_dict` if it's a function rather than a class

2024-10-03 13:22 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/labware/types.py
> +            WellSegment, segment.model_dump(exclude_none=True, exclude_unset=True)  # type: ignore[union-attr]
you can probably get rid of the type ignore if you make it `if isinstance(segment, WellSegmentDef)`

2024-10-03 13:22 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/labware/types.py
> +# A rounded pyramid is a pyramid that is filleted on each corner with the following:
wonder if it might be helpful to have openscad code segments in these comments

2024-10-03 13:22 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/frustum_helpers.py
> +    well_geometry: Union[InnerWellGeometry, InnerWellGeometryDef],
why does this need to take both? this should basically only ever be called by the engine, and presumably the engine will always have this data in a fixed format post-parsing

2024-10-03 13:22 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/frustum_helpers.py
> +        section_volume: Optional[float] = None
nit: if you factor this into `def volume_of_section(segment: Union[...shapes...]) -> float`, then in that `volume_of_section` you can just return from each branch of the if instead of having an optional variable - like factoring for maximal `const`ness in c++.

2024-10-03 13:22 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/frustum_helpers.py
> +        if segment["shape"] == "spherical":
[nit] [pounding fork and knife on the table] `match`! `match`! `match`!

2024-10-03 13:22 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/frustum_helpers.py
> +        partial_height = _height_from_volume_spherical(
i think the same comment here as in `get_well_volumetric_capacity`, though here you haven't predefined `partial_height`

2024-10-03 13:22 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/frustum_helpers.py
> +    if checked_section["shape"] == "spherical":
same comment here as in `get_well_volumetric_capacity`

2024-10-03 13:22 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/frustum_helpers.py
> +    for segment in sorted_well:
same comment here as in `get_well_volumetric_capacity` (though without the match part)

2024-10-03 13:22 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/frustum_helpers.py
> +    height_within_well: Optional[float] = None
same comment here as in `get_well_volumetric_capacity`

2024-10-03 13:22 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/frustum_helpers.py
> +        if target_volume == section_volume:
this feels a little iffy since these are floats - maybe instead make sure `_find_height_in_partial_frustum` works well for `section_volume` ~= `target_volume` and remove the precheck

2024-10-04 18:07 UTC, SyntaxColoring requested changes

2024-10-04 18:07 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +      "required": ["shape", "radiusOfCurvature", "topHeight"],
`bottomHeight` was intended to be required, right?

```suggestion
      "required": ["shape", "radiusOfCurvature", "bottomHeight", "topHeight"],
```

2024-10-04 18:07 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +      "description": "A list of all of the sections of the well that have a contiguous shape",
This looks like a misplaced `description`?

```suggestion
```

2024-10-04 18:07 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +      "description": "A list of all of the sections of the well that have a contiguous shape",
Same, misplaced description?

```suggestion
```

2024-10-04 18:07 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +    "PyramidalFrustum": {
I'm sorry to be such a pain about this, but I think we want a word other than "pyramidal" here. It looks like you're using it to mean "rectangularish/squarish," but according to [[1](https://mathworld.wolfram.com/PyramidalFrustum.html), [2](https://mathworld.wolfram.com/Pyramid.html)], it has a different specific technical meaning. A frustum is pyramidal if the original shape, out of which the frustum was cut, had triangles for all of its side faces, and those triangles converge to a single point.

In numerical terms, given our `bottomXDimension`, `bottomYDimension`, `topXDimension`, and `topYDimension`, the frustum is only pyramidal if this happens to be true:

$\frac{topXDimension}{bottomXDimension} = \frac{topYDimension}{bottomYDimension}$

2024-10-04 18:07 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +    "RoundedPyramidSegment": {
Same re "pyramid".

2024-10-09 17:50 UTC, SyntaxColoring approved these changes
Shapes look great to me, thanks!

I haven't reviewed the processing part of this because it seems like @sfoster1 has already looked at it, but I'm happy to if you want more eyes.

2024-10-09 17:50 UTC, SyntaxColoring commented on shared-data/labware/schemas/3.json
> +          "enum": ["squaredcone"]
Nit, doesn't block merging: `camelCase` `squaredCone` and `roundedCuboid`, if possible.

2024-10-09 17:50 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/labware/labware_definition.py
> +module filitedCuboidSquare(bottom_shape, diameter, width, length, height, steps) {
Nit for these OpenSCAD snippets, doesn't block merging: `filleted` instead of `filited`.

2024-10-09 18:03 UTC, sfoster1 approved these changes
Excellent! Looks great to me.

2024-10-09 18:22 UTC, merged