Exec 734 allow the gripper to be opened while the door is open
OpenTrons/opentrons-api pull request #16394
Opened 2024-10-01 15:19 UTC by TamarZanzouri

# Overview

## Test Plan and Hands on Testing

## Changelog

## Review requests

## Risk assessment

2024-10-02 16:55 UTC, sfoster1 requested changes
i know it's a draft, i'm just marking changes so we don't forget to put this in schema 10 once https://github.com/Opentrons/opentrons/pull/16401 is merged

2024-10-02 16:55 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/commands.py
> +        if next_fixit_cmd and (
it seems like this logic allows the command outside of error recovery when we're `BLOCKED_BY_OPEN_DOOR`, shouldn't this only apply to `AWAITING_RECOVERY_BLOCKED_BY_OPEN_DOOR`?

2024-10-02 16:55 UTC, sfoster1 commented on api/tests/opentrons/protocol_engine/commands/unsafe/test_ungrip_labware.py
> +async def test_engage_axes_implementation(
copy/pasta?

2024-10-02 16:55 UTC, sfoster1 commented on shared-data/command/schemas/9.json
> +      "unsafe/ungripLabware": "#/definitions/UnsafeUngripLabwareCreate"
holding note, and the reason i'm marking this request changes instead of comment: we should rebase this and put it in schema 10 once https://github.com/Opentrons/opentrons/pull/16401 is merged

2024-10-02 19:24 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/commands.py
> +        if next_fixit_cmd and (
yep I only added this for testing purposes. I will remove it

2024-10-02 19:25 UTC, TamarZanzouri commented on shared-data/command/schemas/9.json
> +      "unsafe/ungripLabware": "#/definitions/UnsafeUngripLabwareCreate"
Ill do it! Thank you!

2024-10-03 13:33 UTC, sfoster1 requested changes
inline changes.

also is it really the case that we need to care about specifically the queue status for awaiting recovery, and specifically the engine status for `AWAITING_RECOVERY_OPEN_DOOR`? Can these both query the same thing?

2024-10-03 13:33 UTC, sfoster1 commented on shared-data/command/schemas/9.json
> +      "unsafe/engageAxes": "#/definitions/UnsafeEngageAxesCreate",
need to revert the changes here with `git checkout edge -- shared-data/command/schemas/9.json`

2024-10-03 13:33 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/commands.py
> +                allowed_while_door_open = (
[nit] i don't love this variable name. it seems like from the context `allowed_while_door_open` is a property of the _action_, and if so then it shouldn't take the _engine status_ into account. what if we remove the variable name and make it a second `if` or something?

2024-10-03 13:33 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/commands.py
> +            or self.get_status()
i wonder if this would be clearer if it was just a second if statement, like
```
if next_fixit_command and self._state.queue_status == QueueStatus.AWAITING_RECOVERY:
    return next_fixit_cmd

if next_fixit_command and (self.get_status() == EngineStatus.AWAITING_RECOVERY_BLOCKED_BY_OPEN_DOOR) and self.get(next_fixit_cmd).commandType == "unsafe/ungripLabware":
    return next_fixit_cmd
```

2024-10-05 01:04 UTC, SyntaxColoring commented
Latest commits should address the feedback above.

I did make one change to the logic, to make sure these special ungrip commands can also be queued and run when the engine status is `awaiting-recovery-paused`, not only when it's `awaiting-recovery-blocked-by-open-door`. If we're saying they're safe to run while the door is actually open, presumably they're also safe to run if the door has been closed and the closure just hasn't been "logically acknowledged" yet.

2024-10-07 14:32 UTC, TamarZanzouri commented
tested with the app and postman. works as expected!

2024-10-07 15:43 UTC, sfoster1 approved these changes
Nice, thanks for changing the name structure!

2024-10-07 15:44 UTC, merged