feat(robot-server): Add `GET` `runs/:runId/activeNozzleLayout/:pipetteId`
OpenTrons/opentrons-api pull request #16402
Opened 2024-10-02 18:26 UTC by mjhuff

Works towards [RSQ-161](https://opentrons.atlassian.net/browse/RSQ-161)

# Overview

To support partial tip during error recovery during certain flows, the server must expose details about pipetting tip layout for the current run. `NozzleMap` contains details the client is interested, but we really shouldn't return the entirety of `NozzleMap`, since it is A) quite large and B) contains a lot of info irrelevant from a client perspective. To that end, we return an `ActiveNozzleLayout` derived from the `NozzleMap` for the pipette of interest. 

After deliberating a bit, I decided to throw this on its own endpoint, since we only use it one spot, we'll probably refactor a bunch of stuff to some sort of stateful runs endpoint soon, and we have to specify a `pipetteId` to get the `NozzleMap` for a pipette, anyway. 

## Test Plan and Hands on Testing
- Verified the endpoint works as expected during a protocol.
- Verified the endpoint returns correct 409/404 errors when expected.

## Changelog
- Added `GET` `runs/:runId/activeNozzleLayout/:pipetteId`

## Review requests
- Does this approach make sense? Are we ok with the new `NozzleMapNotFound` error? 
- Note that I'll do the shared-data and api-client work in a separate PR.

## Risk assessment
- low I think

2024-10-02 18:47 UTC, sfoster1 requested changes
I think I'm a little uncomfortable with having this endpoint 
- (a) presenting current status
- (b) while the run is going
- (c) without linking it to the command that was active at the time

I'd love to see us change at least one of the above

2024-10-02 18:47 UTC, sfoster1 commented on robot-server/robot_server/runs/router/base_router.py
> +        # status.HTTP_404_NOT_FOUND: {
?

2024-10-02 18:47 UTC, sfoster1 commented on robot-server/robot_server/runs/run_models.py
> +class ActiveNozzleLayout(BaseModel):
I think we probably want the active nozzle here. otherwise the app would have to roll its own code to figure out which well to specify for the pick up tip command.

2024-10-02 18:50 UTC, mjhuff commented on robot-server/robot_server/runs/run_models.py
> +class ActiveNozzleLayout(BaseModel):
Ahhh yep, thank you.

2024-10-02 18:56 UTC, SyntaxColoring requested changes
Thanks, this all seems functionally right.

It smells like we should be coupling less tightly to `opentrons.hardware_control`, though:

2024-10-02 18:56 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/base_router.py
> +    pipetteId: str,
Since there's a bounded number of pipettes, I wouldn't mind having one endpoint return all of the pipettes at once, if that simplifies anything.

2024-10-02 18:56 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/base_router.py
> +    path="/runs/{runId}/activeNozzleLayout/{pipetteId}",
If we're adding a new endpoint for this, should we just go ahead and jump to putting it under `currentState` or something, like `/runs/{runId}/currentState/activeNozzleLayout`.

Also curious about your thoughts behind *not* putting this directly on `/runs/{runId}`. I don't have an informed opinion, but from prior discussions, it seemed like we'll have worse UI flickering and torn-state problems when things are split up more.

2024-10-02 18:56 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/base_router.py
> +    """An error if one tries to modify a stopped run."""
Docstring copypasta?

2024-10-02 18:56 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_models.py
> +
Agreed with exposing some `robot-server`-specific subset of the underlying hardware data, but some additional thoughts:

-  I think we should generally avoid exposing types from `opentrons.hardware_control`, like `NozzleConfigurationType`, directly in the HTTP API. They're far apart and different people tend to work on them, so it seems like a recipe for accidental changes and tight-coupling surprises.

   If we really need to expose these values 1:1, we can have some trivial mapping function based on a `match` statement or `if`/`elif` ladder. But we might not actually want to expose it 1:1—see the next point.
- I'm not up to speed on nozzle layouts, but is this really the best way of expressing this information? Like, in `NozzleConfigurationType`, isn't every case just a special case of `SUBRECT`? And I don't fully understand `columns` and `rows` yet, but they seem funky. How much of this is just `opentrons.hardware_control` having a weird internal structure for `opentrons.hardware_control` reasons?

- The `configureNozzleLayout` Protocol Engine command (`configure_nozzle_layout.py`) already defines some shapes for this. Would it be helpful to use them?

2024-10-02 18:59 UTC, mjhuff commented on robot-server/robot_server/runs/router/base_router.py
> +    pipetteId: str,
Alright, I'm down to do that. It doesn't simplify things immediately, but I think it does simplify things down the road.

2024-10-02 19:08 UTC, mjhuff commented on robot-server/robot_server/runs/router/base_router.py
> +    path="/runs/{runId}/activeNozzleLayout/{pipetteId}",
The main reason I didn't put this behind `runs/:runId` was so this could take a `pipetteId` and return only relevant nozzle data. I _think_ that approach also requires updating `StateSummary`, too, returning only `nozzle_map_by_pipette_id` from the tips store, which seems non-ideal to me? I could be wrong here.

I'm fine throwing this in `currentState` if that makes sense to you.

2024-10-02 19:22 UTC, mjhuff commented on robot-server/robot_server/runs/run_models.py
> +
Thanks for the feedback.From what I can tell, the `NozzleConfigurationType` is somewhat useful because the client can avoid fully iterating over rows/columns given certain `NozzleConfigurationType`, but for example, if the client has an 8-channel with a `SUBRECT`, this is essentially any consecutive nozzles that is not 1 nozzle or all 8 nozzles, at which point, we have to iterate to find the exact number of nozzles used. 

That being said, if `starting_nozzle` is actually what it sounds like, perhaps returning a count of nozzles is sufficient. I'll sync with @CaseyBatten briefly and clarify a few things. 

And fair enough on the type coupling!

2024-10-02 19:31 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/base_router.py
> +    path="/runs/{runId}/activeNozzleLayout/{pipetteId}",
Okay yeah the `stateSummary` is a good point. This gets meaningfully easier to evolve if we keep it out of `stateSummary` and out of the persistence layer.

Yeah, let’s do `currentState`.

2024-10-02 20:39 UTC, mjhuff commented on robot-server/robot_server/runs/run_models.py
> +
@SyntaxColoring After discussion with @CaseyBatten, it sounds like the best approach for what the client actually cares about is to return:

1. The starting nozzle. We need this for the tip pickup commands. It's always either A1/H1. 
2. The active nozzles. We can derive this from `map_store` and just send this as a flat array of nozzle names, ex ["A1", "B1", "C1"...].

2024-10-03 13:23 UTC, mjhuff commented
Ok, the following commits change the following:

- More nozzlin'. We now return `ActiveNozzleLayout`s for all pipettes used in the protocol run. No more specifying `pipetteId`.
- The endpoint is now `/runs/:runId/currentState`.
- We return a link to the "active" command to ground this state in space and time. Definitely open to suggestions concerning naming here, since it sounds like calling it "current command" is a big no no.
- `ActiveNozzleLayout` is different. From my understanding of partial tip, there are a few directions we can take this resource while being useful:

1. Return the `configuration`, the `startingNozzle`, and the `activeNozzleCount`. The client can figure out which nozzles are active based on this alone, but it requires anyone working with this API to possess knowledge of partial tip nuances. Ex, if you have an 8ch with `activeNozzleCount: 4` and the `startingNozzle: H1`, the four active nozzles are `H1, G1, F1, E1`. I personally don't love this, because it requires anyone using the API to be familiar with how partial tip layouts work per pipette (the 96ch has its own nuances). The pro here is that the resource is just a few scalars.
2. Return the `startingNozzle` and `activeNozzles`. The client can derive the `configuration` on its own. The pro here is we never worry about configuration and probably safeguard against any lower level partial-tip refactors. The con is this is pretty annoying to work with as the client, as we probably almost always want to know the config whenever we deal with partial tip layouts. The app doesn't do a great job of utilizing utilities for deriving relevant info from resources as it is (see deck config), and this feels like it contributes to the problem somewhat unnecessarily (imo).
3. Return `startingNozzle`, `activeNozzles`, and `config`. This approach is easiest on the client and (unsurprisingly) the one I defaulted to using. The tradeoff here is we potentially return an `activeNozzle` list of 96 nozzle strings, which seems fine to me, and there's the argument that `config` is _somewhat_ redundant with `activeNozzles`, see 2.

2024-10-03 15:22 UTC, SyntaxColoring reviewed
Changes make sense, thanks.

I've half-reviewed this so far. Dumping some thoughts before we start our block of meetings.

2024-10-03 15:22 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/base_router.py
> +    )
Some thoughts on grounding this data at a point in time

As implemented, this looks like it reports the "current" command with `GET /runs/{id}/commands`'s definition of "current," which is:

> the [command] that's running right now, or, if there is none, the one that was running most recently.

The "or" clause there unfortunately means that this link, on its own, is not sufficient to identify a point in time. The link will be the same between: (1) the run executing a command right now, and (2) the run having just executed a command and not yet having moved on to the next one. This will make it look to the client like time has not moved on and robot state has not changed, but in fact it has.

To solve this, we could either:

* Report not only the href of the "current" command, but also its `status`.
* Or, instead of reporting the "current" command, report the `lastCompletedCommand`. I don't think any other endpoints do this yet; it would be new.

I'm leaning towards `lastCompletedCommand` if that info happens to already be easy to access. It seems harder for a client to use wrongly.

-----

Some thoughts on whether to call this "active", "current", or something else else:

Pending all the stuff above, assuming we continue to use the same "current command" semantics that `GET /runs/{id}/commands` does right now, we should either:

* Call this `current` to match `GET /runs/{id}/commands`
* Call this something like `currentlyRunningOrMostRecentlyRun` to spell out what it actually does, and, separately, phase out `current` in `GET /runs/{id}/commands` and replace it with `currentlyRunningOrMostRecentlyRun` there too.

2024-10-03 15:22 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/base_router.py
> +    active_command: Optional[ResourceLink] = Field(
As an API nitpick, I would consider adding the plain command `id` here, not just its href, so clients don't have to parse the URL if they want the ID.

To do that, you could either subclass `ResourceLink` or use a completely standalone `BaseModel` class. `CommandLink` and `RunLink` use standalone classes.

Sorry for the misleading `ResourceLink` legacy cruft!

This doesn't have to happen in this PR.

2024-10-03 20:17 UTC, sfoster1 commented on robot-server/robot_server/runs/router/base_router.py
> +    )
i think `current` to match `GET /runs/{id}/commands` is the right way. The only thing worse than something being subtlely wrong is something being inconsistent and only _sometimes_ subtlely wrong

2024-10-03 20:29 UTC, sfoster1 approved these changes
Agree with Max but also agree with your other choices - I think it's fine to expose what you've exposed for the nozzle maps and having this be (some interpretation of) "current" status and linked to a command is great.

2024-10-03 20:50 UTC, SyntaxColoring approved these changes
New `ActiveNozzleLayout` shape looks good, thanks!

Looks good to merge. We can address the other items in follow-ups if you want.

2024-10-03 20:50 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_models.py
> +    config: str = Field(..., description="The nozzle configuration type.")
Doesn't have to happen in this PR, but we probably want an `Enum` or `Literal` here.

2024-10-03 20:50 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/base_router.py
> +    )
Discussed in-person with Jamey: We'll probably go with `lastCompletedCommand` to avoid concurrency gotchas.

2024-10-04 12:57 UTC, mjhuff commented
The below commits square up most of the feedback from above. I left a TODO `lastCompletedCommand`, which is the outstanding work left.

I'll merge after testing this one last time.

2024-10-04 13:11 UTC, merged