feat(api): Add RobotContext movement commands
OpenTrons/opentrons-api pull request #16403
Opened 2024-10-02 19:44 UTC by Laura-Danielle

# Overview

In this PR, you'll find a couple of major changes including hooking up the `RobotContext` with the protocol engine, adding the three movement commands (PLAT-351, PLAT-352, PLAT-449, PLAT-452, PLAT-455) in the context as well as http commands.

## Remaining work

- [x] Gate behind 2.21
- [x] Disable for OT-2
- [x] Add tests for: robot_core, movement, gantry_mover, motion_utils functions and protocol engine commands
- [x] Update absolute motion_utils function to properly handle critical point

## Test Plan and Hands on Testing

Robot has been tested with pipette mounts and will need to be tested with the gripper mount.

## Changelog

- Add robot_context movement commands
- Add `robot/moveTo`, `robot/moveAxesRelative` and `robot/moveAxesTo` protocol engine commands
- Add a robot core to share between the robot context and `moveTo` command
- Update the ot3controller to handle sending moves to the Q motor if it is requested
- Bump the command schema
- Add relevant tests

## Note
The `axis_coordinates_for` function can only properly handle `Location` types at this moment. There will be a follow-up PR to address `modules` and `slots`.

## Review requests

Double check that routing makes sense and that I'm not missing any movement conversions before passing off to the hardware controller.

## Risk assessment

Low. This is a use at your own risk API.

2024-10-03 13:48 UTC, sfoster1 requested changes
inline comments. also i think something got lost in `moveAxes` vs `moveAxesRelative`, it seems like the `gantry_mover` function is missing an argument or a separate implementation for relative moves

2024-10-03 13:48 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/execution/gantry_mover.py
> +            relative_move: Specifying whether a relative move needs to be handled or not.
?

2024-10-03 13:48 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/robot/move_axes_relative.py
> +        current_position = await self._gantry_mover.move_axes(
this should be some relative-move function, right?

2024-10-03 13:48 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/types.py
> +    CLAMP_JAW_96_CHANNEL = "clampJaw96Channel"
elsewhere we call this a "cam", i think calling this a "jaw" invites confusion with the gripper

2024-10-03 13:48 UTC, sfoster1 commented on api/src/opentrons/types.py
> +    def ot3_gantry_axes(cls) -> List["AxisType"]:
this is now public api, so this probably needs to be `def flex_gantry_axes`

2024-10-03 13:48 UTC, sfoster1 commented on api/src/opentrons/protocol_api/core/engine/robot.py
> +    AxisType.X: MotorAxis.X,
this kind of seems like it should be in the engine

2024-10-03 13:48 UTC, sfoster1 commented on api/src/opentrons/protocol_api/core/legacy/legacy_protocol_core.py
> +        # None,
commented code

2024-10-03 13:48 UTC, sfoster1 commented on api/src/opentrons/protocol_api/robot_context.py
> +        axis_map: Union[AxisMapType, StringAxisMap],
should these be hardware axes or engine axes? I think we should probably use engine axes, since this goes to the engine and that's what it uses, and also that will keep it the same as json protos

2024-10-06 13:40 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/core/engine/robot.py
> +    AxisType.X: MotorAxis.X,
It is in the engine, or did you mean a specific file?

2024-10-17 13:40 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/types.py
> +    CLAMP_JAW_96_CHANNEL = "clampJaw96Channel"
@sfoster1 how about `96_CHANNEL_CAM`?

2024-10-24 14:12 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/types.py
> +    CLAMP_JAW_96_CHANNEL = "clampJaw96Channel"
sounds good to me!

2024-10-24 14:14 UTC, sfoster1 commented on api/src/opentrons/protocol_api/core/engine/robot.py
> +    AxisType.X: MotorAxis.X,
This isn't the engine - this is the protocol api engine bindings. My point is really that in my opinion, we shouldn't need to move `AxisType` to `opentrons.types`; instead, we should push `MotorAxis` upwards. Types that are used for the hardware controller shouldn't be part of user API.

2024-11-01 17:22 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/robot_context.py
>      def axis_coordinates_for(
random question, is this intended to be called from a protocol before using `move_axes_relative` or `move_axes_to`?

2024-11-01 17:56 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/execution/gantry_mover.py
> +
```suggestion
```

2024-11-01 18:04 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/execution/gantry_mover.py
> +                else VIRTUAL_MAX_OT3_HEIGHT
can we use an OT2 one or change the name?

2024-11-01 18:12 UTC, ecormany commented on api/src/opentrons/protocol_api/protocol_context.py
> +            raise RobotTypeError("The RobotContext is only available on Flex robot.")
```suggestion
            raise RobotTypeError("The RobotContext is only available on Flex robots.")
```

2024-11-01 18:12 UTC, ecormany commented on api/src/opentrons/protocol_api/robot_context.py
> +    @requires_version(2, 21)
2.22 now, yes?

2024-11-01 18:16 UTC, TamarZanzouri approved these changes
a few nips but overall looks super intuitive and makes total sense. I just want to make sure we dont need to update the state right? (sorry I was not part of the convo's of this feature)

2024-11-03 12:33 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/robot_context.py
>      def axis_coordinates_for(
`move_axes_relative` can be called directly with a user dict, but `axis_coordinates_for` is intended to help users build a proper absolute position axis map from `location`. In a follow-up PR I will also build out the `slot` and `module` locations but I felt like there was already a lot here and decided not to address it as we only need "location" at the moment for the evo protocol.

2024-11-03 15:24 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/execution/gantry_mover.py
> +                else VIRTUAL_MAX_OT3_HEIGHT
good catch

2024-11-03 16:11 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/core/engine/robot.py
> +    AxisType.X: MotorAxis.X,
OK I guess that makes sense as well. I'll make the change, but as a PR based off this one since there is already a lot going on and there will be a decent amount of import changes.

2024-11-03 16:13 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/robot_context.py
> +        axis_map: Union[AxisMapType, StringAxisMap],
See comment from [here](https://github.com/Opentrons/opentrons/pull/16403#discussion_r1827014853)

2024-11-03 16:47 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/execution/gantry_mover.py
> +            relative_move: Specifying whether a relative move needs to be handled or not.
Updated the description, let me know if it makes more sense now.

2024-11-05 22:30 UTC, sfoster1 requested changes
There's a couple last little things we need to do. Some of them can be todos, but we definitely should update the command schema since it'll be quick.

2024-11-05 22:30 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        log.info(f"The move groups are {maybe_runners}.")
probably wants to be `debug`

2024-11-05 22:30 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        self._log.info(f"Move from: origin is {origin}")
note which coordinates this is in in the log message please

2024-11-05 22:30 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        self._log.info(f"Attempting to move {position} with speed {speed}.")
note which coordinates this is in in the log please

2024-11-05 22:30 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/robot/move_axes_relative.py
> +
another thing we need to add here, and in the other commands, is that we changed the way the engine keeps track of positions to be based on `StateUpdate` objects that command implementations return. specifically, these will need to return `state_updates` with `set_pipette_location()` as [aspirate now does](https://github.com/Opentrons/opentrons/blob/d0af9a1181141cf28d0869394c9cce9ed9c61b30/api/src/opentrons/protocol_engine/commands/aspirate.py#L131-L136) for protocol engine commands after this one to properly know where the pipette currently is. we can have a todo for this, but it will be outright broken until then.

2024-11-05 22:30 UTC, sfoster1 commented on shared-data/command/schemas/11.json
> +{
will need to merge `edge` and then rerun the schema generation, it's missing some stuff that got added since this was branched

2024-11-07 19:31 UTC, Laura-Danielle commented on api/src/opentrons/protocol_engine/commands/robot/move_axes_relative.py
> +
I mean it would still execute the movements no? We have tickets for updating state for the robot context and I'd rather not add more to the PR than necessary.

2024-11-07 22:59 UTC, sfoster1 approved these changes
Okay, I feel great about this now. Thanks for bearing with me, and thanks for splitting that stuff out. Great work!

2024-11-07 22:59 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/robot/move_axes_relative.py
> +
Yeah, they will. It'll just move weird after.

2024-11-08 22:11 UTC, merged