fix(app, shared-data): app crashes when using python apiLevel<2.16 with fixed trash
OpenTrons/opentrons-api pull request #16451
Opened 2024-10-09 21:07 UTC by TamarZanzouri

# Overview

closes [EXEC-759](https://opentrons.atlassian.net/browse/EXEC-759) - fix render deck map when trash is fixed (python api version < 2.16).

## Test Plan and Hands on Testing

upload the following protocol without labware on the deck:

```
from opentrons import protocol_api, types

metadata = {
    "apiLevel": "2.15",
}

requirements = {
    "robotType": "OT-3"
}

def run(ctx: protocol_api.ProtocolContext) -> None:
    tip_rack_50 = ctx.load_labware("opentrons_flex_96_filtertiprack_50ul", 4)
    ctx.move_labware(labware=tip_rack_50, new_location=5, use_gripper=True)
```

1. enter ER
2. select manually remove labware
3. make sure that after the count down the app is not crashing.
4. make sure deck map is rendering.

tested deck map locally - works as expected.

## Changelog

fixed but when using deck map with fixed trash with python protocols bellow 2.16.
added shared-data method to get fixed trash definition

## Review requests

changes make sense? did I forget anyhing?

## Risk assessment

low

[EXEC-759]: https://opentrons.atlassian.net/browse/EXEC-759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-10-09 21:24 UTC, sfoster1 requested changes
some code style comments that rise into sort of alarm levels when I note that the code that was there before your PR is doing a full command list scan every time through the `reduce`...

2024-10-09 21:24 UTC, sfoster1 commented on app/src/organisms/ErrorRecoveryFlows/hooks/useDeckMapUtils.ts
> +      let labwareDefinitionsByUri: LabwareDefinitionsByUri
Wait does this mean we're doing a full command array scan for every reduce callback here? Can we instead do something like
- hoist `const protocolLabwareDefinitionsByUri = getLoadedLabwareDefinitionsByUri(...)` to like line 261, _outside_ of this `reduce`
- factor this logic into a function like
```
const getLabwareDefinition = (uri: string) => { 
   if (lw.id === 'fixedTrash) {
      return getFixedTrashLabwareDefinitionsByUri(lw.definitionUri)[lw.definitionUri]
   } else {
      return protocolLabwareDefinitionsByUri[lw.definitionUri]
   }
``` 
which preserves `const`ness, and then call that function in the `reduce`?

2024-10-09 21:24 UTC, sfoster1 commented on shared-data/js/helpers/getFixedTrashLabwareDefinitionsByUri.ts
> +export function getFixedTrashLabwareDefinitionsByUri(
if we do my comment above, this doesn't have to work the same way as `getLoadedLabwareDefinitionsByUri()` and can just return the definition directly instead of a one-element computed-key object

2024-10-09 23:54 UTC, mjhuff reviewed
Yeah, the major thing is definitely my fault here. I think Seth covered everything, we need to hoist out the command scanning util. My one comment shouldn't apply if you use his recommendation for how to refactor `getFixedTrashLabwareDefinitionsByUri`. Thanks for doing all this!

2024-10-09 23:54 UTC, mjhuff commented on app/src/organisms/ErrorRecoveryFlows/hooks/useDeckMapUtils.ts
> +        )
Seth's approach should solve this, but if we do need some sort association of the `lw` to the actual `definitionUri`, we should validate that the `lw` is a `fixedTrash` within the `shared-data` util itself.

2024-10-10 00:08 UTC, mjhuff reviewed
Actually, we do this same nested iterative check on `L208`, so if you could move that outside of the `reduce` using the same aforementioned logic, that would be great!

2024-10-10 16:43 UTC, mjhuff requested changes
See comment above. 

- We need to move `getLoadedLabwareDefinitionsByUri` out of `getRunCurrentModulesInfo`, too. 
- We should memoize the value.

We can do this by hoisting your new function to the top level of `useDeckMapUtils` and doing something like:

```
const labwareDefinitionsByUri = useMemo(() => getLoadedLabwareDefinitionsByUri(
      protocolAnalysis.commands
    ), [])
```
and then pass that to `getRunCurrentModulesInfo` and `getRunCurrentLabwareInfo`.

Because the new `getLabwareDefinition` function is utilized in both places, we can just write this as a new function top-level fn, not within  `getRunCurrentModulesInfo` or `getRunCurrentLabwareInfo`

2024-10-10 16:49 UTC, mjhuff commented on shared-data/js/helpers/getFixedTrashLabwareDefinitionsByUri.ts
> +export function getFixedTrashLabwareDefinitionsByUri(
I think we should refactor this fn name, too?

2024-10-10 16:49 UTC, mjhuff commented on shared-data/js/helpers/getFixedTrashLabwareDefinitionsByUri.ts
> +export function getFixedTrashLabwareDefinitionsByUri(
It also doesn't need a parameter now.

2024-10-10 16:55 UTC, sfoster1 approved these changes
Looks awesome but also what Jamey said. No need for a rereview after that tbh

2024-10-10 18:40 UTC, mjhuff approved these changes
Awesome! Now you can make a resume bullet point along the lines of "exponentially improved the performance of Error Recovery"

2024-10-10 22:10 UTC, merged