feat(hardware): refactor tool_sensors to simplify and remove csvs
OpenTrons/opentrons-api pull request #16462
Opened 2024-10-10 20:45 UTC by ryanthecoder

# Overview

## Test Plan and Hands on Testing

## Changelog

## Review requests

## Risk assessment

2024-10-11 13:29 UTC, sfoster1 reviewed
Let's make these more special loggers I think

2024-10-11 13:29 UTC, sfoster1 commented on api/src/opentrons/config/__init__.py
> +        "SENSOR Log File",
```suggestion
        "Sensor Log File",
```

2024-10-11 13:29 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/flex_protocol.py
> +            asyncio.Queue[dict[SensorId, list[SensorDataType]]]
if we're going to use the lower case versions here we should change the rest of the file imo

2024-10-11 13:29 UTC, sfoster1 commented on api/src/opentrons/util/logging_config.py
> +            "opentrons_hardware.sensors.sensor_driver": {
we should give these sources a special name I think. this makes _all_ logging from that file (given that we typically build loggers with `logging.getLogger(__name__)`) go to this file. if we make the logger mapping keyed by something like `"pipette-pressure-sensor-log"` (obv a constant stored somewhere) then in the sensor driver file we can make one logger with `logging.getLogger(__name__)` for normal kinds of logging and a logger with `logging.getLogger("pipette-pressure-sensor-log")` for logging data. Could even have a separate one for capacitive and pressure sensors, etc

2024-10-11 13:29 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/backends/test_ot3_controller.py
> +    print(move_groups)
debug print

2024-10-16 16:30 UTC, sfoster1 requested changes
Looks good but let's consider whether the data should go in journald or not and add some tests for at least "how many messages am I trying to receive" mechanics and ideally more.

2024-10-16 16:30 UTC, sfoster1 commented on api/src/opentrons/util/logging_config.py
> +                "class": "systemd.journal.JournalHandler",
IMO we shouldn't send this to the journal - it will be a bunch of data

2024-10-16 17:53 UTC, ryanthecoder commented on api/src/opentrons/hardware_control/backends/flex_protocol.py
> +            asyncio.Queue[dict[SensorId, list[SensorDataType]]]
I'm not sure what that means

2024-10-21 19:17 UTC, sfoster1 approved these changes
Looks good to me!

2024-10-21 19:17 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/flex_protocol.py
> +            asyncio.Queue[dict[SensorId, list[SensorDataType]]]
for the types - `dict` instead of `typing.Dict`

2024-10-21 20:12 UTC, merged