fix(protocol-designer): enable color picker's alpha value
OpenTrons/opentrons-api pull request #16505
Opened 2024-10-17 14:08 UTC by koji

# Overview
enable color picker's alpha value

https://github.com/user-attachments/assets/f008c088-1414-409a-805c-525befcef329

close RQA-3347

## Test Plan and Hands on Testing

## Changelog

## Review requests

## Risk assessment
low

2024-10-17 20:27 UTC, ncdiehl11 requested changes

2024-10-17 20:27 UTC, ncdiehl11 commented on protocol-designer/src/organisms/DefineLiquidsModal/index.tsx
> +  const rgbaToHex = (r: number, g: number, b: number, a?: number): string => {
This doesn't seem to quite work for the toHex(alpha value). Maybe something like:

```
  const rgbaToHex = (r: number, g: number, b: number, a?: number): string => {
    const toHex = (value: number, isAlpha: boolean = false): string => {
      const hex = Math.round(isAlpha ? value * 255 : value).toString(16)
      return hex.length === 1 ? '0' + hex : hex
    }
    return a != null && a < 1
      ? `#${toHex(r)}${toHex(g)}${toHex(b)}${toHex(a, true)}`
      : `#${toHex(r)}${toHex(g)}${toHex(b)}`
  }
```

seems to work better because RGB values are [0, 255] while A value is [0, 1]

2024-10-17 20:27 UTC, ncdiehl11 commented on protocol-designer/src/organisms/DefineLiquidsModal/index.tsx
> +                      const { r, g, b, a } = color.rgb
to be cleaner maybe pass whole rgb object to `rgbaToHex`?

2024-10-17 20:41 UTC, koji commented on protocol-designer/src/organisms/DefineLiquidsModal/index.tsx
> +  const rgbaToHex = (r: number, g: number, b: number, a?: number): string => {
oh, good catch

2024-10-17 22:38 UTC, koji commented
tested the code [here](https://www.typescriptlang.org/play/?#code/PTAEDMFcDsGMBcCWB7aoBOBzARgQwCrIASApgB4AUWeAXKLtAJ4CUdAzvOotJqAN4AoEKBGxUHfugA0oTDOxTcoAL6gAvBhy4hYEaPHxQ8YuXWgK0OtEgBbbCXTN1APlDQAdMYDKnbpgoAjABszO4ADrgAJj646PAUAEwyAOQADMnMANw6evrQErgANmEAFkoaALK48CXu6MgwkRRKAFSgCQCsHVk5uegk8JDoaAAGAMQAJHzGpJSOylMz5BSYzAvTJpTYa4ubzcVlayPZwsoCAnkS1ASbZlRadAws7L48LvwXemL5hnwYMnJQAp6CozNdPpdDEsyHdLG5bPZHC8uG81K4PN5Xv5gqEItF4LF4klQGkMhDQN8CgdyiCAIQaayFQqgAD8oCqNTqDWgTVa7S6TjonQ65P6g2GoHGu1mVB2Gxlq3W0Io2yVeyKpVwR0+ZxyAFEyLgbGFCiRQJA2LhMCQaAJKYYSuQAMLIQrIdBgrSEGV8dA0YUAmgATiD8hoAHYAjJcDRUu4OsosqBhAB5SDwMLpuhjcDgIIAZgALOGABypO3iV0kdxu-yOsgut2OTJAA)

2024-10-18 14:17 UTC, ncdiehl11 approved these changes
code looks good and works well 💯

2024-10-18 14:17 UTC, ncdiehl11 commented on protocol-designer/src/organisms/DefineLiquidsModal/index.tsx
> +    const alpha = a != null ? Math.round(a * 255) : 255
👍

2024-10-18 14:23 UTC, merged