refactor(app): migrate useHomePipettes to local-resources
OpenTrons/opentrons-api pull request #16544
Opened 2024-10-21 13:44 UTC by mjhuff

# Overview

The new `local-resources` directory is a logical place to house on-the-fly maintenance runs that execute a set command list before closing the maintenance run, such as `useHomePipettes`. This PR just closes a TODO comment.

## Risk assessment
low - no functional changes

2024-10-21 15:17 UTC, sfoster1 requested changes
yesss more stuff to resources. however I regret to inform you that you have a typo in the filename `useGripperDispalyName.ts`

2024-10-21 15:17 UTC, sfoster1 commented on app/src/local-resources/instruments/hooks/useGripperDispalyName.ts
Typo in this filename!

2024-10-21 15:18 UTC, mjhuff commented on app/src/local-resources/instruments/hooks/useGripperDispalyName.ts
tank u

2024-10-22 12:50 UTC, sfoster1 approved these changes

2024-10-22 12:53 UTC, merged