feat(api, robot-server, app): Handle the Plate Reader lid while held by the gripper when the Estop is pressed.
OpenTrons/opentrons-api pull request #16574
Opened 2024-10-22 23:17 UTC by vegano1

# Overview

We don't want customers manually handling the Plate Reader lid as this can cause damage to the device when you press the estop while the gripper is holding the plate reader lid it will eventually home the gantry and hold onto the lid. When a new protocol is started the gripper jaws will open, causing the plate reader lid to fall and potentially get damaged. This pull request makes it so we automatically place the plate reader lid in its dock (staging area) when the robot resumes operating after physically and logically disengaging the estop.

Closes: [PLAT-451](https://opentrons.atlassian.net/browse/PLAT-451)

## Test Plan and Hands on Testing

- [ ] Make sure we can run a plate reader protocol without issues
- [ ] Make sure that the plate reader `open/close_lid` commands still work
- [ ] Make sure the plate reader lid is returned to its dock (staging area) after the stop is physically and logically disengaged.
- [ ] Make sure the run is cancelled when the estop is pressed
- [ ] Make sure the estop modal is shown while placing the plate reader lid back in its dock
- [ ] Make sure that we only call `placeLabware` when the estop is pressed

## Changelog

- Add a new `unsafe/placeLabware` command to PE to place labware the gripper is already holding on to.
- Add a new `placeLabwareState` to the `runs/{run_id}/currentState` endpoint to inform the client of the plate reader lid.
- Add a new `usePlacePlateReaderLid` hook on the client to conditionally call the `unsafe/placeLabware` command when the `placeLabwareState` returns the appropriate values.

## Review requests

- My react is rusty, please ensure I'm not doing something dumb.
- Is there anything else we should be checking in the unsafe/placeLabware command?

## Risk assessment

med, this changes post-estop behavior.

2024-10-22 23:59 UTC, mjhuff requested changes
Nice first go and one of the more complicated parts of React/JS!

See comments. I think the serious things are:

1. We're always creating a maintenance run when the estop modal is popped. We can get around this with some conditional logic.
2. We can use existing utils to do most of the heavy lifting in `usePlacePlateReaderLid`.
3. We're always closing the estop modal while plate reader commands may be running.

2024-10-22 23:59 UTC, mjhuff commented on app/src/App/OnDeviceDisplayApp.tsx
> +    <ApiHostProvider hostname="10.14.19.57">
Changed for testing?

2024-10-22 23:59 UTC, mjhuff commented on app/src/organisms/EmergencyStop/EstopPressedModal.tsx
```suggestion

import { usePlacePlateReaderLid } from '/app/resources/modules'
```
Nit, we generally place local imports in a grouping separate from the monorepo imports.

2024-10-22 23:59 UTC, mjhuff commented on app/src/resources/modules/hooks/usePlacePlateReaderLid.ts
> +    params: { labwareId: labwaerId, location: location },
```suggestion
    params: { labwareId, location },
```

2024-10-22 23:59 UTC, mjhuff commented on app/src/resources/modules/hooks/usePlacePlateReaderLid.ts
> +  labwaerId: string,
```suggestion
  labwareId: string,
```

2024-10-22 23:59 UTC, mjhuff commented on app/src/resources/modules/hooks/usePlacePlateReaderLid.ts
> +export function usePlacePlateReaderLid(
See `useHomePipettes`.

Ideally, we use `useRobotControlCommands` here, as this takes care of the implementation details concerning spinning up the maintenance run, managing it, providing loading state, executing callbacks after the commands complete, and then terminating the maintenance. This code dupes that utility.

Some pseudocode as an idea:

```
usePlacePlateReaderLid(...) {
  const { executeCommands, isExecuting } = useRobotControlCommands({
    ...props,
    commands: [YOUR_COMMANDS_HERE],
    continuePastCommandFailure: true,
onSettled: {modal close goes here}
  })

const placePlateReaderLid = () => {
executeCommands()
}

return {
placePlateReaderLid, 
isPlacing: isExecuting,
isPlateReaderGripped: conditional logic to determine whether the estop can close or we need to close it within here).
}

your build commands here

2024-10-22 23:59 UTC, mjhuff commented on app/src/organisms/EmergencyStop/EstopPressedModal.tsx
> +          placeReaderLid()
If I'm reading this correctly, currently there's no logical check to whether we should run this command, so we're always going to run it every e-stop press. 

I think ideally we encapsulate placeReaderLid() with some sort of check here to decide whether we should placeReaderLid(). Maybe within `usePlacePlateReaderLid`, see pseudocode below.

2024-10-22 23:59 UTC, mjhuff commented on app/src/organisms/EmergencyStop/EstopPressedModal.tsx
>            closeModal()
I'm like 90% sure this always closes the estop modal while the plate reader commands are running, which we probably don't want to do. This is kind of tricky to get around, but we'll need some sort of conditional logic to determine whether the plate reader hook is closing the modal or whether we should close it here. See pseudo code command in the hook.

2024-10-22 23:59 UTC, mjhuff commented on app/src/organisms/EmergencyStop/EstopTakeover.tsx
I don't think we need to touch this file. All the logic can be contained in `EstopPressedModal`.

2024-10-22 23:59 UTC, mjhuff commented on app/src/organisms/EmergencyStop/EstopPressedModal.tsx
> +  isWaitingForPlateReaderLidPlacement: boolean
To reduce code duplication and ensure desired behavior, I believe we want the hook to live in `EstopPressedModal` and we pass all these props to `TouchscreenModal` and `DesktopModal`.

2024-10-22 23:59 UTC, mjhuff commented on app/src/organisms/EmergencyStop/EstopTakeover.tsx
> +    setisWaitingForPlateReaderLidPlacement,
From what I can tell, this never does anything? See other comments, I don't think we need loading state here.

2024-10-23 11:37 UTC, vegano1 commented on app/src/organisms/EmergencyStop/EstopPressedModal.tsx
> +          placeReaderLid()
Correct this command always runs when the estop is pressed, however, the execution of commands is conditional in the `loadModuleIfSupplied` function. This makes it so all the logic for this placeReaderLid is self-contained and can be moved around when needed. Lets chat today.

2024-10-23 11:38 UTC, vegano1 commented on app/src/organisms/EmergencyStop/EstopPressedModal.tsx
>            closeModal()
yeah the `isPlacing` flag should prevent this from happening, lets chat.

2024-10-23 11:39 UTC, vegano1 commented on app/src/organisms/EmergencyStop/EstopTakeover.tsx
maybe, but, if we dont want the estop modal to get dismissed until all the placePlateReader logic is finished I figured we need to check that here.

2024-10-23 14:09 UTC, smb2268 commented on app/src/resources/modules/hooks/usePlacePlateReaderLid.ts
> +export function usePlacePlateReaderLid(
@mjhuff I looked at this briefly with Brayan yesterday and recommended replicating some of the logic in `useRobotControlCommands` to use it here since that hook requires commands to run when you call it as opposed to in the callback. That's difficult for this use case because the `location` and `labwareId` passed as params to the commands are variable and possibly null when we call the hook. We could refactor `useRobotControlCommands` to take in the commands in the callback to get around this replication

2024-10-23 15:04 UTC, mjhuff commented on app/src/resources/modules/hooks/usePlacePlateReaderLid.ts
> +export function usePlacePlateReaderLid(
Chatted w/ Brian, there is a way to do it using the existing hook, which we should use given the complexity of managing the lifecycle of a MR, but agreed that the longer term solution would be to refactor `useRobotControlCommands` commands to support loading a module.

2024-10-24 17:30 UTC, mjhuff approved these changes
Nice job! I do like the e-stop control flow much more now.

2024-10-24 17:30 UTC, mjhuff commented on app/src/organisms/EmergencyStop/EstopPressedModal.tsx
> +          setIsWaitingForResumeOperation={setIsWaitingForResumeOperation}
Two separate setters responsible for the same state seems strange to me, but I get that this code was here already, and  I don't think it's worth addressing now.

2024-10-28 14:36 UTC, CaseyBatten approved these changes
Engine side logic looks good, nice work on this. A non-blocking question down below regarding the fallback case for how some of our geometry is calculated/resolved in this implementation that may effect future labware recovery behavior, but otherwise this looks great!

2024-10-28 14:36 UTC, CaseyBatten commented on api/src/opentrons/protocol_api/core/engine/protocol.py
> +            if substate.lid_id is None:
This looks good, should provide coverage for the current run setup bug.

2024-10-28 14:36 UTC, CaseyBatten commented on api/src/opentrons/protocol_engine/commands/unsafe/unsafe_place_labware.py
> +        drop_offset = cast(Point, final_offsets.dropOffset) if final_offsets else None
Everything in the UnsafePlaceLabware command logic looks good, but just want to make sure I understand. When we're doing this None case here we are basically just lowering and releasing the labware in place + its movement center? So if we were between two slots, would we end up releasing the labware in a awkward deck space? Not really too much of an issue for this PR since the primary use case for now is plate reader lids which will always have resolved locations with final offsets.

2024-10-28 18:49 UTC, ahiuchingau approved these changes
Nice!! Just got a small question

2024-10-28 18:49 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/modules/absorbance_reader.py
> +        pass
What does it mean when we `deactivate` the module now?

2024-10-28 19:24 UTC, vegano1 commented on api/src/opentrons/hardware_control/modules/absorbance_reader.py
> +        pass
In the context of modules, the `deactivate` function means we stop whatever target action we are doing, such as heating, shaking, etc. We don't have any actions other than reading for the plate reader, but these happen relatively quickly, so we don't have to worry about them. The problem here was that I thought deactivate meant stop and disconnect the module, which is not correct as `deactivate` gets called when the estop is pressed. In the case of the plate reader it would disconnect and reconnect when the estop was pressed. This change fixes that behavior

2024-10-28 19:34 UTC, vegano1 commented on api/src/opentrons/protocol_engine/commands/unsafe/unsafe_place_labware.py
> +        drop_offset = cast(Point, final_offsets.dropOffset) if final_offsets else None
No, since these are just the dropoff offsets, in that case, we would navigate to the slot and drop off the labware +- some hardware stack-up margin. We should never be dropping labware in between 2 slots for example, unless the definition for that is way off.

2024-10-29 16:19 UTC, SyntaxColoring reviewed
Some drive-by comments. No objections to any of this merging as-is if you need to get it in for the v8.2.0 feature freeze.

2024-10-29 16:19 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/unsafe/unsafe_place_labware.py
> +            public=UnsafePlaceLabwareResult(), private=None, state_update=state_update
I think my recent changes are going to cause a minor conflict here: it'll complain that the `private` param doesn't exist anymore. You can just delete `private=None`.

2024-10-29 16:19 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/unsafe/unsafe_place_labware.py
> +        SuccessData[UnsafePlaceLabwareResult, None],
My recent changes are going to cause a minor conflict here: `SuccessData[UnsafePlaceLabwareResult, None]` should be replaced with just `SuccessData[UnsafePlaceLabwareResult]`.

2024-10-29 16:19 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/unsafe/unsafe_place_labware.py
> +        """Place Labware."""
Having not really been involved in this, I would find it helpful if one of these docstrings described when it's appropriate and legal for a client to use this `unsafe` command, and when it's not.

i.e., why is this called `unsafe/placeLabware`, and not just `placeLabware`.

I would also consider that the unfamiliar audience is probably comparing this with `moveLabware` and `loadLabware`, so we should describe how it's distinct from those.

2024-10-29 16:19 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_models.py
> +    estopEngaged: bool = Field(..., description="")
Nit: If we don't have a description to offer, let's just leave `description` unset instead of doing `description=""`.

i.e. `estopEngaged: bool` instead of `estopEngaged: bool = Field(..., description="")`.

2024-10-29 16:19 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_models.py
> +        ..., description="The location the Plate Reade lid should be in."
```suggestion
        ..., description="The location the Plate Reader lid should be in."
```

2024-10-29 16:19 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_models.py
> +
`placeLabwareState.location` is defined here in terms of the plate reader lid, specifically, as opposed to labware locations in general. So, should we either:

* Rename `placeLabwareState` to something that reflects that it's Plate-Reader–specific, and is not meant to be used for labware in general
* Or, redefine `placeLabwareState.location` to not be specifically about the plate reader lid

2024-10-29 16:19 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/unsafe/unsafe_place_labware.py
> +    labwareId: str = Field(..., description="The id of the labware to place.")
Theoretically, we shouldn't need the client to supply a `labwareId` parameter, should we? Isn't the point of this command that it drops whatever is currently being held, which we should already know?

2024-10-29 17:18 UTC, vegano1 commented on api/src/opentrons/protocol_engine/commands/unsafe/unsafe_place_labware.py
> +    labwareId: str = Field(..., description="The id of the labware to place.")
At this point we are not in a run context, we need to spin up a maintenance run, load the labware, then issue the unsafe/placeLabware command with the `labwareId` we just loaded in.

2024-10-29 19:51 UTC, merged