feat(api,app,shared-data): Track air gaps
OpenTrons/opentrons-api pull request #16662
Opened 2024-10-31 20:44 UTC by sfoster1

We now are trying to track the amount of liquid in the wells of the labware on the deck. To do this, we're tracking how much liquid we aspirate from wells and dispense into wells.

Unfortunately, sometimes users want to aspirate air and then dispense it into wells (well, they usually don't want to dispense it _into_ the well, but they want to dispense it). Until now, we'd treat any volume of air that got dispensed as a volume of liquid, and add it to the liquid tracked in the well. This is wrong.

There's a couple things we need to do to fix this, and this PR does them. It also does a couple other things to support that effort. It's big, but well-separated into commits, and that's a decent way to do it.

- a6a0856823a0dfa49182a1e28f1df3fcc2fae02c adds a utility class that can track the pipette contents and the relative ordering of air and liquid slugs within the pipette. It does this so that you can say "Hey I'm going to dispense x ul, how much of that is liquid?" and get a solid answer.
- c19b205d29f6c8c9434bd1e3e0496b5aed68654a integrates that with existing commands and state stores, in the process switching volume state tracking to `StateUpdate`
- 7d81a3c0ae5be131826c62144df5a257b9fd86cc adds `airGapInPlace`, a new command that works exactly like aspirate except that it doesn't take volume out of a well, and it adds air to the pipette internal volume tracking so that a subsequent dispense won't add liquid to the target well
- 3f4d07197c17c79528c50998c11a693031fcd710 makes the python protocol API use that for `air_gap` calls above a certain API version

There's also some supporting commits to add the new API version (since this is going into edge) and a command text for the new command.

This is a pretty in depth thing and will need at least some testing, but it is covered by pretty in-depth automated testing and I eagerly await some failing analysis snapshots. 

## reviewing
- can i get away with not changing the pipette state store tests to just be about state updates? please?
- does the fluid stack thing seem overwrought, underwrought, wroughten to the core?
- am I missing something?

## testing
- [ ] run a protocol that uses air gaps on api version 2.21. it should still work
- [ ] run a protocol that uses air gaps on api version 2.22. it should work in terms of physical actions
  - [ ] Inspect the volume trakcing and make sure the air isn't counted as liquid

Closes EXEC-792

2024-11-04 14:27 UTC, mjhuff reviewed
The FE changes look good to me! Thanks for explaining some of the `FluidStack` logic, too.

2024-11-04 14:51 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/legacy/legacy_instrument_core.py
> +        assert False, "Air gap tracking only available in API version 2.22 and later"
we usually raise an api error here instead

2024-11-04 14:52 UTC, TamarZanzouri commented on api/src/opentrons/protocol_api/core/legacy_simulator/legacy_instrument_core.py
> +    def air_gap_in_place(self, volume: float, flow_rate: float) -> None:
same comment as above

2024-11-04 15:07 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/commands/air_gap_in_place.py
> +    """Payload required to aspirate in place."""
```suggestion
    """Payload required to air gap in place."""
```

2024-11-04 15:11 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/update_types.py
> +        """Update record fo fluid held inside a pipette. See `PipetteUnknownFluidUpdate`."""
```suggestion
        """Update record of fluid held inside a pipette. See `PipetteUnknownFluidUpdate`."""
```

2024-11-04 15:17 UTC, ryanthecoder commented on api/src/opentrons/protocol_engine/types.py
> +    AIR = "AIR"
Probably outside of this PR but we should think about beads in the future.

2024-11-04 15:18 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/update_types.py
> +    type: typing.Literal["aspirated"] = "aspirated"
do we need the type? isnt the instance sufficient?

2024-11-04 15:37 UTC, TamarZanzouri commented on api/src/opentrons/protocol_engine/state/fluid_stack.py
> +            removed[-1] = new_last
should we override this item? shouldnt we just append?

2024-11-04 15:49 UTC, TamarZanzouri requested changes
some nips but no biggy!

2024-11-04 17:01 UTC, SyntaxColoring requested changes
Looks good overall, thank you!

Changes requested for a specific thing where we're initializing something as an empty `FluidStack()` instead of `None`.

My other big question is that we're making new commands for this instead of adding params to existing commands.

Other than that, just various small nitpicks.

2024-11-04 17:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/fluid_stack.py
> +        kind, add a new record to the end.
Meant this?

```suggestion
        If the new fluid is of a different kind than what's on the bottom of the stack, append a new record; if the same
        kind, add the volume to the existing record.
```

2024-11-04 17:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/fluid_stack.py
> +    """
Nitpick:

We might want to avoid "top" and "bottom" terminology. The most recently aspirated fluid is at the physical bottom of the physical liquid stack, but is at the "top" of the computer science FILO stack data structure.

Maybe "low-z/high-z"? "Tip/root"? "Newest/oldest"?

2024-11-04 17:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/instrument_context.py
> +           when dispensing into a well.
Is this meaningful if liquid tracking *also* did not exist before API version 2.22?

2024-11-04 17:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/update_types.py
> +
No change needed, just something to consider here.

Even though `pipette_aspirated_fluid` is a different dataclass field from `liquid_operated`, we can feel free to combine the *methods* if we feel like it'll make the command implementations less bug-prone. e.g. have one `set_fluid_operated()` method that affects the well volume and the tip volume at the same time, since that's going to be the overwhelmingly common case.

We can also go deeper and combine it at the field level. We did that with the pipette's "location" (logical location, e.g. "well A1") and "deck point" (physical location in deck coordinates).

2024-11-04 17:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/air_gap_in_place.py
I get nervous about the `aspirate[InPlace]`+`airGap[inPlace]` duplication because the control flow is pretty sensitive, now that we have error recovery. For example: It seems likely that someone in the future will change something in `aspirate`, like the exact places and ways in which we mutate the `StateUpdate`, but forget to make the same changes in `airGap`. Instead of a new command, what about adding an `isAir: bool = False` param to the existing `aspirate` and `aspirateInPlace` commands?

Also, liquid classes are coming. Do we think that project will add new params to `aspirate`+`aspirateInPlace` anyway?

2024-11-04 17:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/drop_tip.py
> +            state_update_if_false_positive.set_fluid_unknown(pipette_id=pipette_id)
I don't think you actually need this `state_update_if_false_positive.set_fluid_unknown(...)` line. `state_update_if_false_positive` is applied *additionally* to `state_update`, not *instead* of `state_update`, so you should already be covered by line 153.

I'm open to changing or renaming any of that if it's confusing.

2024-11-04 17:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/drop_tip_in_place.py
> +            )
Ditto.

2024-11-04 17:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/prepare_to_aspirate.py
> +            state_update.set_fluid_unknown(pipette_id=params.pipetteId)
Is this correct for a `prepareToAspirate`? Isn't a precondition of `prepareToAspirate` that it should be done away from liquid? So if it was empty before the overpressure, it should still be empty after the overpressure, not unknown, right?

2024-11-04 17:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/load_pipette.py
> +        state_update.set_fluid_unknown(pipette_id=loaded_pipette.pipette_id)
Why unknown instead of empty?

2024-11-04 17:01 UTC, SyntaxColoring commented on app/src/local-resources/commands/hooks/useCommandTextString/index.ts
> +    case 'airGapInPlace':
Do we also need a `case 'airGap'`?

2024-11-04 17:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/pipettes.py
> -            self._update_volumes(action)
🚮 👌

2024-11-04 17:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/pipettes.py
> +                ] = fluid_stack.FluidStack()
It looks like this chunk of `PipetteStore._update_tip_state()` is now competing with, e.g., the `state_update.set_fluid_empty(...)` call in `PickUpTipImplementation`.

I think this works for now, but in the medium term, we should probably aim to settle firmly on one side or the other. Maybe initialize everything as unknown/empty inside `_set_load_pipette()` and then remove this chunk from `_update_tip_state()`.

2024-11-04 17:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/pipettes.py
> +            )
We can turn this runtime problem into a static one:

```suggestion
            assert_never(state_update.pipette_aspirated_fluid)
```

With `assert_never` from `typing_extensions`.

2024-11-04 17:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/pipettes.py
> +            self._state.pipette_contents_by_id[pipette_id] = fluid_stack.FluidStack()
I haven't traced this all the way out, but it looks like some code that was consuming `aspirated_volume_by_id` treated `None` as semantically distinct from `0`. So do we still need to initialize it to `None` here and treat `None` as semantically distinct from an empty `FluidStack`?

2024-11-04 17:40 UTC, sfoster1 commented on api/src/opentrons/protocol_api/core/legacy/legacy_instrument_core.py
> +        assert False, "Air gap tracking only available in API version 2.22 and later"
We do in the more modern code, but in the legacy cores this is the pattern (see `get_active_channels`, etc). Those functions should never be called, because the API level should have already been checked and rejected if the legacy cores were going to be used.

2024-11-04 17:41 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/types.py
> +    AIR = "AIR"
I don't think beads matter on this level (other than wording, I guess) - they do actually count as displaced volume when you dispense them somewhere, so under this framing they'd just be "LIQUID"

2024-11-04 17:42 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/update_types.py
> +    type: typing.Literal["aspirated"] = "aspirated"
good question, I have no idea actually. I'll try it without the annotation.

2024-11-04 17:43 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/fluid_stack.py
> +    """
I guess `physically-lowest`?

2024-11-04 17:43 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +           when dispensing into a well.
No because it exists in API version 2.21 (though it's not used for anything really)

2024-11-04 17:45 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/drop_tip.py
> +            state_update_if_false_positive.set_fluid_unknown(pipette_id=pipette_id)
Oh, that make sense when I think through it

2024-11-04 17:46 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/prepare_to_aspirate.py
> +            state_update.set_fluid_unknown(pipette_id=params.pipetteId)
a precondition of prepare to aspirate is that it _should be_ done away from liquid. if we get an overpressure, there's a very good chance that it was in fact done inside liquid, or hard pressed against a well. we moved the plunger and pressure spiked; something's in the way. I think unknown is the right call here.

2024-11-04 17:47 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/load_pipette.py
> +        state_update.set_fluid_unknown(pipette_id=loaded_pipette.pipette_id)
we generally set "unknown" when there's no tip.

2024-11-04 17:47 UTC, sfoster1 commented on app/src/local-resources/commands/hooks/useCommandTextString/index.ts
> +    case 'airGapInPlace':
nope! i very purposefully did not add an `airGap` command, there is only `airGapInPlace`

2024-11-04 18:05 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/air_gap_in_place.py
to be clear, there is no `airGap` - there is only `airGapInPlace`, for this exact reason.

As to exactly why it's a separate command: I think this is a fundamentally different kind of operation, at an engine level, from aspirate. It's the same operation on a hardware level, but the hardware level is not the engine level - the engine level lives at this sort of "minimum viable domain-relevant operation" level, and air gaps are a different and purposefully selected thing than an operation there. In further PRs we should maybe unify some more code in the same way that we have `pipetting.aspirate_in_place`, but I think these _should be_ two different commands. For a solid example as to why, well, we get to see `air gap` in the run logs now.

2024-11-04 18:07 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/update_types.py
> +
We could, but I think that while "we want to update the well fluid and the pipette contents at the same time" is overwhelmingly common, the exact ways in which we update it is pretty specific to the commands in which it's used. I think that keeping that logic inlined into the command implementations is a bonus for readability.

2024-11-04 18:15 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/fluid_stack.py
> +    """
let me know if this is clearer

2024-11-04 18:27 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/fluid_stack.py
> +    """
Yep, that works, thanks.

2024-11-04 20:02 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/update_types.py
> +    type: typing.Literal["aspirated"] = "aspirated"
@TamarZanzouri i get a bunch of errors without it, I think it's worth keeping it

2024-11-04 20:04 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/pipettes.py
> +                ] = fluid_stack.FluidStack()
Agree, I think I'm going to settle on "let state update do its job" and delete this line (and the similarly commented ones) from the other update handlers

2024-11-04 20:08 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/pipettes.py
> +            self._state.pipette_contents_by_id[pipette_id] = fluid_stack.FluidStack()
Yes we do, and actually we do that - that's the unknown kind of update - and should have been doing it here. Which is why I deleted this line, in favor of the set_fluid_unknown call in LoadPipetteImpl.

2024-11-04 20:44 UTC, TamarZanzouri approved these changes
Thank you for your comments :-) nice job!

2024-11-04 20:51 UTC, SyntaxColoring approved these changes
Sweet, thank you!

2024-11-04 20:51 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/fluid_stack.py
> +you want air gaps in different places - physicall-ybelow liquid to prevent dripping, physically-above liquid to provide
```suggestion
you want air gaps in different places - physically-below liquid to prevent dripping, physically-above liquid to provide
```

2024-11-04 20:51 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/air_gap_in_place.py
> to be clear, there is no `airGap` - there is only `airGapInPlace`, for this exact reason.

Thanks, definitely missed that.

> As to exactly why it's a separate command: I think this is a fundamentally different kind of operation,

Yeah, eh. I don't think different domain operations necessarily *ought* to have different `commandTypes`, if they're close enough. And even if they ought to, I think the tradeoff against maintenance practicalities is often not worth doing that.

But not a huge deal. Happy to go with what's written.

> For a solid example as to why, well, we get to see air gap in the run logs now.

We'd be able to see that with an `isAir: true` param, too.

2024-11-05 14:11 UTC, ryanthecoder approved these changes
Looks good to me, and solves our volume tracking as intended

2024-11-05 14:48 UTC, merged