feat(shared-data, api): Add evo tips definition and restrictions on loading
OpenTrons/opentrons-api pull request #16710
Opened 2024-11-06 20:28 UTC by Laura-Danielle

# Overview

Add evo tips definition but as a labware so that liquid handling actions can happen in the 'labware'.

## Test Plan and Hands on Testing

Need to check that the stackup works as expected

## Changelog

- Add evo tips definition
- Add stacking component to nest deepwell plate
- Add error check for the evo tips definition so that it is not accidentally loaded onto the deck

## Review requests

Check that the labware role makes sense and the stacking part.

## Risk assessment

Low. Adding a new labware.

2024-12-10 14:21 UTC, sfoster1 requested changes
The verification logic wants to be in the engine but other than that looks good.

2024-12-10 14:21 UTC, sfoster1 commented on api/src/opentrons/protocol_api/validation.py
> +def ensure_labware_is_loadable(
This wants to be in the engine I reckon

2025-01-07 18:01 UTC, sfoster1 approved these changes
Excellent, looks good to me once checks pass!

2025-01-10 00:01 UTC, closed without merging

2025-01-10 00:02 UTC, Laura-Danielle commented
Rebase issues. Creating fresh branch to base off of chore release.