fix(api): add supported wavelengths to runtime error when initializing the plate reader.
OpenTrons/opentrons-api pull request #16797
Opened 2024-11-13 20:25 UTC by vegano1

# Overview

Add the supported wavelengths to the runtime error raised when an invalid wavelength is provided.

## Test Plan and Hands on Testing

- [ ] Make sure the supported wavelengths are reported in the runtime error

## Changelog

- add `supported_wavelengths` to runtime error

## Review requests

- I'm open to word smith's suggestions

## Risk assessment

low, log only change

2024-11-13 21:07 UTC, ecormany approved these changes
Nice, so simple! Would love to be able to surface this in analysis, but that's for another day…

2024-11-13 21:07 UTC, ecormany commented on api/src/opentrons/protocol_engine/commands/absorbance_reader/initialize.py
> +                    f" use {supported_wavelengths} instead."
Small change to make this a bit more like the error we have for loading an invalid module, which I like the format of:

```suggestion
                    f"Unsupported wavelengths: {unsupported_wavelengths}. "
                    f" Use one of {supported_wavelengths} instead."
```

2024-11-13 21:14 UTC, SyntaxColoring approved these changes
All my homies love actionability.

2024-11-13 21:15 UTC, sfoster1 requested changes
Comments inline, but should use a protocol engine error and maybe massage the formatting of the wavelengths.

2024-11-13 21:15 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/commands/absorbance_reader/initialize.py
> +                raise ValueError(
This should be an error from `protocol_engine.errors` that gets associated with an error code - maybe invalid protocol data, but ok to fall back to 4000 general error instead. If it's just a raw exception it will get a scarier UI.

Also this seems like it's just dumping a set to string which will look like this: "Unsupported wavelengths: {1000, 1400, 1200}. Use one of {500, 800, 1000} instead." Feels a little terse, maybe make it `{', '.join([str(wavelength) + 'nm' for wavelength in unsupported_wavelengths])` instead?

2024-11-14 14:28 UTC, vegano1 commented
@sfoster1 @ecormany 

Added `InvalidWavelengthError` and fixed up the formatting, here's what that looks like.

<img width="760" alt="Screen Shot 2024-11-14 at 9 13 13 AM" src="https://github.com/user-attachments/assets/b3cb8c61-4536-4195-b591-5ea878022853">

2024-11-14 17:13 UTC, sfoster1 approved these changes
Excellent, thank you!

2024-11-14 17:15 UTC, merged