feat(shared-data): add peak shared data definition
OpenTrons/opentrons-api pull request #16876
Opened 2024-11-18 21:33 UTC by ryanthecoder

# Overview

## Test Plan and Hands on Testing

## Changelog

## Review requests

## Risk assessment

2024-11-18 22:17 UTC, sfoster1 requested changes
it is unfortunately `PEEK`, for the material

2024-11-19 21:41 UTC, sfoster1 approved these changes
I'd love to figure out a way for this to be `p1000_multi_emulsify` (with an underscore) but if it makes it lots harder it's okay to not have it

2024-11-19 21:41 UTC, sfoster1 commented on shared-data/command/schemas/11.json
> +        "p1000_multiemulsify",
```suggestion
        "p1000_multi_emulsify",
```

2024-11-19 21:41 UTC, sfoster1 commented on shared-data/command/schemas/11.json
> +        "p1000_multiemulsify",
I kind of hate this but if it makes everything a million times harder to have the underscore we're fine without it

2024-11-19 22:16 UTC, ryanthecoder commented on shared-data/command/schemas/11.json
> +        "p1000_multiemulsify",
See the commit after this, I think this is actually the only place we need to have it specially processed.

2024-11-20 15:40 UTC, sfoster1 approved these changes
Okay, looks good to me!

2024-11-20 16:01 UTC, merged