test(api): install opentrons and simulate
OpenTrons/opentrons-api pull request #17048
Opened 2024-12-05 21:32 UTC by y3rsh

# Overview

Draft

## Test Plan and Hands on Testing

## Changelog

## Review requests

## Risk assessment

2024-12-06 16:38 UTC, SyntaxColoring approved these changes
Nice! Thank you!

2024-12-06 16:38 UTC, SyntaxColoring commented on .github/workflows/api-test-lint-deploy.yaml
> +      - name: Install opentrons and shared-data
```suggestion
      - name: Set up package-testing
```

2024-12-06 16:38 UTC, SyntaxColoring commented on .github/workflows/api-test-lint-deploy.yaml
> +        continue-on-error: true
Will this `continue-on-error: true` unintentionally remove the red X in the GitHub web UI if this test fails?

https://stackoverflow.com/questions/62045967/is-there-a-way-to-continue-on-error-while-still-getting-correct-feedback

2024-12-06 16:43 UTC, sfoster1 requested changes
We really need to test this on windows, perhaps most of all, unfortunately. Might need to have a powershell equivalent. Sorry to say it!

2024-12-06 16:43 UTC, sfoster1 commented on .github/workflows/api-test-lint-deploy.yaml
> +        os: ['ubuntu-22.04', 'macos-latest']
this does unfortunately really need to include windows

2024-12-06 16:43 UTC, sfoster1 commented on package-testing/Makefile
> +test:
would expect clean to be a recipe dependency up here as it is for `teardown`

2024-12-06 16:43 UTC, sfoster1 commented on package-testing/Makefile
> +test1:
probably wants `clean` as a dep

2024-12-06 16:43 UTC, sfoster1 commented on package-testing/Makefile
> +	./OT2_v6PD_expect_error.sh $(VENV_DIR) $(RESULTS_DIR)
if you make this a variable (`./$(TEST).sh $(VENV_DIR) $(RESULTS_DIR)`) then you could run it like `make test1 TEST=OT2_v6PD_expect_error` without having to edit the file

2024-12-06 17:16 UTC, y3rsh commented on .github/workflows/api-test-lint-deploy.yaml
> +        os: ['ubuntu-22.04', 'macos-latest']
Agreed, adding.

2024-12-06 17:16 UTC, y3rsh commented on .github/workflows/api-test-lint-deploy.yaml
> +        continue-on-error: true
I always forget this. Thank You.

2024-12-09 15:54 UTC, sfoster1 approved these changes
Looks awesome, thank yoU!

2024-12-16 18:39 UTC, merged