feat(protocol-designer): make timeline responsive
OpenTrons/opentrons-api pull request #17109
Opened 2024-12-13 21:30 UTC by koji

# Overview
make timeline responsive

close AUTH-877

## Test Plan and Hands on Testing

## Changelog

## Review requests

## Risk assessment
low

2024-12-13 21:37 UTC, koji commented on protocol-designer/src/pages/Designer/ProtocolSteps/DraggableSidebar.tsx
> +const INITIAL_SIDEBAR_WIDTH = 350
i'll get the right value from Mel next week

2024-12-13 21:38 UTC, koji commented on protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
> +  const [targetWidth, setTargetWidth] = useState<number>(350)
the initial value will be updated.

2024-12-13 21:44 UTC, koji commented
- [ ] fix check-js and lint-js errors

2024-12-17 15:19 UTC, ncdiehl11 commented
Whoa, looks really slick. I do see some highlighting when dragging the timeline toolbox (see "Ending deck"). Not sure if this is blocking, though.

https://github.com/user-attachments/assets/fd3ce6ce-7b32-48b7-9ceb-5a4832281194

2024-12-17 15:21 UTC, jerader commented on protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/StepContainer.tsx
> +      {showDeleteConfirmation === true && (
is this change needed?

2024-12-17 15:21 UTC, jerader commented on protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/StepContainer.tsx
> +      {showMultiDeleteConfirmation === true && (
same

2024-12-17 15:21 UTC, ncdiehl11 commented
I think the add step menu is being contained by the timeline toolbox container
<img width="352" alt="Screenshot 2024-12-17 at 10 21 02 AM" src="https://github.com/user-attachments/assets/3baad09a-0f81-4c38-be43-c58a1f363861" />

2024-12-17 15:24 UTC, jerader commented on protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
> +  console.log('targetWidth', targetWidth)
```suggestion
```

2024-12-17 15:33 UTC, ncdiehl11 requested changes
Left some comments but generally looking good

2024-12-17 15:33 UTC, ncdiehl11 commented on protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/AddStepButton.tsx
> +  const items = getSupportedSteps(enableComment)
maybe
```suggestion
  getSupportedSteps(enableComment).
    reduce<JSX.Element[]>((acc, stepType) => {
      return getIsStepTypeEnabled(enableComment, modules)[stepType]
        ? [...acc, <AddOverflowButton ... />]
        : acc
    }, [])
```

2024-12-17 15:33 UTC, ncdiehl11 commented on protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/AddStepButton.tsx
> +        display="flex"
```suggestion
        display={DISPLAY_FLEX}
```

2024-12-17 15:33 UTC, ncdiehl11 commented on protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/AddStepButton.tsx
> +  box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.2);
Do we have a constant for this?

2024-12-17 15:33 UTC, ncdiehl11 commented on protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/StepContainer.tsx
> +const SIDEBAR_MIN_WIDTH_FOR_ICON = 179
```suggestion
const PX_SIDEBAR_MIN_WIDTH_FOR_ICON = 179
```

2024-12-17 15:33 UTC, ncdiehl11 commented on protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/TerminalItemStep.tsx
> +import { START_TERMINAL_ITEM_ID } from '../../../../steplist'
can move up a few imports

2024-12-17 15:33 UTC, ncdiehl11 commented on protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/TerminalItemStep.tsx
> +  title: string
is this used anywhere?

2024-12-17 15:33 UTC, ncdiehl11 commented on protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
> +  console.log('targetWidth', targetWidth)
can remove

2024-12-18 15:27 UTC, koji commented on protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/StepContainer.tsx
> +      {showDeleteConfirmation === true && (
this is to solve eslint warning.

2024-12-18 15:27 UTC, koji commented on protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/StepContainer.tsx
> +      {showMultiDeleteConfirmation === true && (
this is to solve eslint warning.

2024-12-18 15:42 UTC, koji commented on protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/AddStepButton.tsx
> +  box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.2);
you mean box-shadow or the entire style? 
i think we don't have the constant for this part.

2024-12-18 15:46 UTC, koji commented on protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/TerminalItemStep.tsx
> +  title: string
good catch. we don't need that anymore.

2024-12-18 21:42 UTC, koji commented
> I think the add step menu is being contained by the timeline toolbox container <img alt="Screenshot 2024-12-17 at 10 21 02 AM" width="352" src="https://private-user-images.githubusercontent.com/47604184/396555562-3baad09a-0f81-4c38-be43-c58a1f363861.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NTMzODQsIm5iZiI6MTczNDU1MzA4NCwicGF0aCI6Ii80NzYwNDE4NC8zOTY1NTU1NjItM2JhYWQwOWEtMGY4MS00YzM4LWJlNDMtYzU4YTFmMzYzODYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDIwMTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMzVkMjE5OTI3ZmMyMTNkNWMzMzQyY2FjOWVkMTQ0Mzc0YTUyMTEwODI2ZGU5NWRjZmQzMzg0MDk3OWZjYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9VSNOh4hKWPWh2X8RLd6Ke748RO4EZCD3itSjKzKz6s">

@ncdiehl11 thank you for catching this.
finally, I could figure out what the issue is.

2024-12-20 19:57 UTC, ncdiehl11 commented
<img width="112" alt="Screenshot 2024-12-20 at 2 56 49 PM" src="https://github.com/user-attachments/assets/423811ff-4aef-4b50-b444-1732393416e2" />
Do we want to break "Timeline"?

2024-12-20 19:57 UTC, ncdiehl11 reviewed
left one comment but looks good 💪

2024-12-20 19:57 UTC, ncdiehl11 approved these changes

2024-12-20 19:59 UTC, koji commented
> <img alt="Screenshot 2024-12-20 at 2 56 49 PM" width="112" src="https://private-user-images.githubusercontent.com/47604184/397850610-423811ff-4aef-4b50-b444-1732393416e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MjQ5NjEsIm5iZiI6MTczNDcyNDY2MSwicGF0aCI6Ii80NzYwNDE4NC8zOTc4NTA2MTAtNDIzODExZmYtNGFlZi00YjUwLWI0NDQtMTczMjM5MzQxNmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDE5NTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NDM0ZGUzMWZmYzBjY2NiZmZlNjBiMWZiMTVmYjI1ZDUxZTQzNjk1NzQwYjg3YjFiYzk0MGJlNmJmZTI2ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aS3-TPZk58mWMaBXpzwM3sR-jAEtD9WA2yjzegYCrwM"> Do we want to break "Timeline"?

yeah, that is Mel's current design.
https://www.figma.com/design/WbkiUyU8VhtKz0JSuIFA45/Feature%3A-Protocol-Designer-Phase-1?node-id=10928-294030&m=dev

2024-12-20 20:01 UTC, merged

2025-11-10 23:45 UTC, ddcc4 commented on protocol-designer/src/pages/Designer/ProtocolSteps/DraggableSidebar.tsx
> +      <SidebarContainer ref={sidebarRef} resizedWidth={sidebarWidth}>
@koji Where is the `resizedWidth` property defined?

I can't seem to find any documentation about it, and it's causing the console to fill up with `Warning: React does not recognize the resizedWidth prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase resizedwidth instead. If you accidentally passed it from a parent component, remove it from the DOM element.`