8.3.0 alpha release notes draft
OpenTrons/opentrons-api pull request #17141
Opened 2024-12-18 18:48 UTC by emilyburghardt

# Overview

pushing our first draft of 8.3.0 alpha release notes; would appreciate feedback!

## Test Plan and Hands on Testing

asking for reviews on the alpha notes; will test the build before stable release. 

## Changelog

-edited Josh's release notes on PEEK pipettes
-modified both app and software release notes according to 2025 Release 1 8.3.0 (https://opentrons.atlassian.net/wiki/spaces/RBARM/pages/4570382346/2025+Release+1+8.3.0)

## Review requests

## Risk assessment

feedback on text. what are we missing? does anything need more description?

low

2024-12-18 19:01 UTC, emilyburghardt commented on api/release-notes.md
> +- Adds support for improved tip tracking in Python API version 2.22 protocols.
Should we document tip tracking for the release notes? Anything else to add?

2024-12-18 19:01 UTC, emilyburghardt commented on api/release-notes.md
> +- Recover from a stall or collision error during a protocol.
more description/information needed for Joe and I on this one to better describe it.

2024-12-18 19:01 UTC, emilyburghardt commented on api/release-notes.md
> +- Control robot movements outside of a protocol using the RobotContext API. For more, please read *link PAPI docs section*.
Adding robot context for now to release notes. Can remove as needed.

2024-12-18 19:56 UTC, y3rsh requested changes
Thank you, a few things to adjust and as discussed I will help you get that test.json change out shortly.

2024-12-18 19:56 UTC, y3rsh commented on api/release-notes.md
> +Welcome to 8.3.0-alpha.0! This release adds support for Evosep Evotips on the Flex, as well as other features.
```suggestion
Welcome to 8.3.0! This release adds support for Evosep Evotips on the Flex, as well as other features.
```

2024-12-18 19:56 UTC, y3rsh commented on api/release-notes.md
>  ## Opentrons Robot Software Changes in 8.3.0-alpha.0
It was a special case to provide a specific note for alpha.0.  That note is now enshrined forever in that build and you have folded it into the 8.3.0 notes so we can set the section header as the stable.
Same is true for the other file.
```suggestion
## Opentrons Robot Software Changes in 8.3.0
```

2024-12-18 19:56 UTC, y3rsh commented on api/release-notes.md
> +- Load a newly modified “FLEX 8-Channel EM 1000 µL” pipette equipped with a PEEK motor component to automate emulsion applications.
Want to be consistent with the `"` character and not use `“` or `”` I don't think.
```suggestion
- Load a newly modified "FLEX 8-Channel EM 1000 µL" pipette equipped with a PEEK motor component to automate emulsion applications. 
```

2024-12-18 19:56 UTC, y3rsh commented on api/release-notes.md
> +- Adds support for improved tip tracking in Python API version 2.22 protocols.
Without a specific improvement mentioned this feels hand wavy.

2024-12-18 21:54 UTC, y3rsh commented
As discussed keep running `make format` before commiting but do not worry about the failures that look like this.  I will fix those on 1/2, they are not your fault.
![image](https://github.com/user-attachments/assets/a6ff08f5-0606-47a8-9aae-851e00014e7c)

2024-12-19 20:06 UTC, jwwojak reviewed
A few small recommendations based on a Slack conversation with @emilyburghardt

2024-12-19 20:06 UTC, jwwojak commented on api/release-notes.md
> +- Load a newly modified “FLEX 8-Channel EM 1000 µL” pipette equipped with a PEEK motor component to automate emulsion applications.
For this pipette, we should remove the quote marks. Also, "FLEX" should be "Flex."

> Load a newly modified Flex 8-Channel EM 1000 µL pipette equipped with a PEEK motor component to automate emulsion applications.

2024-12-19 20:06 UTC, jwwojak commented on api/release-notes.md
> +- Recover from a stall or collision error during a protocol.
From our earlier Slack conversation, and other investigations, we have this version to use or modify:

> Improvements to the Flex error recovery feature help protocols recover from detected stalls and collisions, saving you valuable time and resources.

2024-12-19 20:06 UTC, jwwojak commented on app-shell/build/release-notes.md
> +- Load a newly modified “FLEX 8-Channel EM 1000 µL” pipette equipped with a PEEK motor component to automate emulsion applications.
re: previous comments:

- Use proper noun/name Flex instead of FLEX
- No quotes around pipette name

2024-12-19 20:06 UTC, jwwojak commented on app-shell/build/release-notes.md
> +- Recover from a stall or collision error during a protocol.
See suggested revision above.

2024-12-20 13:51 UTC, y3rsh commented
@y3rsh will need to do final fixup on this on 1/2 due to some [git shenanigans](https://opentrons.atlassian.net/browse/RDEVOPS-179) per 8.3.0-alpha.0 being special.

## So even if these are in shape before 1/2 do not merge.  Added that label.

2025-01-06 15:00 UTC, closed without merging