refactor(api): Add move splitting capability to driver move
OpenTrons/opentrons-api pull request #4848
Opened 2020-01-24 20:43 UTC by sfoster1

This is in service of unsticking frozen plunger axes.

When multi pipettes of certain models sit idle for too long, their plunger o
rings create more friction the next time they try to move. To move the o rings,
we have to move a short distance slowly with a higher current before continuing
the rest of the motion.

While this could happen at a higher level, implementing this as splitting up a
move commanded for other reasons lets us more easily share the logic between the
v1 and v2 hardware handling code. Now, the hardware handling code has to check
how long since the plunger last moved and command the split if necessary (or, if
the parameters for the split end up meaning that not that much time elapses
during the slow move, just do it every time in some contexts).

Closes #4674

## Testing
Check out the implementation and the tests and perhaps run it on a robot; at this point however the code isn't used anywhere

2020-01-27 18:57 UTC, sfoster1 commented
Adding do not merge because i realized i forgot to do the speed part of this!

2020-01-28 14:52 UTC, sfoster1 commented
OK added the speed control stuff.

2020-01-28 15:41 UTC, Laura-Danielle requested changes

2020-01-28 15:41 UTC, Laura-Danielle commented on api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
> +                isclose(coord, self.position[axis],
The resolution of our XY axis is approximately .4mm, should we maybe bump up the tolerances here? Right now this would only allow for about a ~0.034 margin.

2020-01-28 15:41 UTC, Laura-Danielle commented on api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
> +        - the actual move, plus a bit extra to give room to preload backlash
Should we not just subtract out the known backlash instead of preloading?

2020-01-28 16:43 UTC, sfoster1 commented on api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
> +        - the actual move, plus a bit extra to give room to preload backlash
We really should be doing both - to preload, move a little farther and then move back but don't change the position. This method, however, is just the way we've always been doing it, just with some more comments

2020-01-28 16:43 UTC, sfoster1 commented on api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
> +                isclose(coord, self.position[axis],
That is probably a good idea! As far as I know these parameters were chosen arbitrarily.

2020-01-28 20:28 UTC, Laura-Danielle approved these changes
Looks good to me 👍

2020-01-28 21:25 UTC, merged