Api mod fw update from local file
OpenTrons/opentrons-api pull request #4856
Opened 2020-01-24 21:57 UTC by b-cooper

## overview

## changelog

## review requests

2020-01-27 15:45 UTC, sfoster1 requested changes
Early thoughts on the draft. Structurally it looks ok but there's some inline comments

2020-01-27 15:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/__init__.py
> +    # TODO: BC 2020-01-24 use loop.add_signal_handler for proper cleanup
i give this a big maybe - signal handlers have to be added from the main thread every time, and some signals can't be handled anyway.

2020-01-27 15:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/__init__.py
> +    msg = context.get("exception", context["message"])
Bit of a nitpick but we should really log both the exception and the message. Per the docs, neither is optional so we shouldn't have to use get here.

2020-01-27 15:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/__init__.py
> +def handle_loop_exception(loop: asyncio.AbstractEventLoop, context):
`context` could probably be typed as `Dict[str, Any]`

2020-01-27 15:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/__init__.py
> +def use_or_initialize_loop(loop: Optional[asyncio.AbstractEventLoop]):
Annotate return type as `asyncio.AbstractEventLoop`

2020-01-27 15:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/mod_abc.py
> +        if None is loop:
can use that helper function here

2020-01-27 15:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/mod_abc.py
> +        return None
kinda bad form, can omit

2020-01-27 15:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/mod_abc.py
> +        MODULE_FW_RE = re.compile(f'{file_prefix}@v(.*).(hex|bin)')
```suggestion
        MODULE_FW_RE = re.compile(f'{file_prefix}@v(.*)\.(hex|bin)')
```

Also do we really handle either hex or bin? IMO we should pick one

2020-01-27 15:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/mod_abc.py
> +        fw_resources = [fw_dir / item for item in os.listdir(fw_dir)]
```suggestion
        fw_resources = fw_dir.iterdir()
```

Path objects have this handy operation that returns an iterator, which we then iterate through in line 60 (could even combine the two now)

2020-01-27 15:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/mod_abc.py
> +            matches = MODULE_FW_RE.search(str(fw_resource))
We could and probably should do a `match` on  `fw_resource.name`

2020-01-27 15:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/mod_abc.py
> +            raw_device_version = self._device_info.get('version', None)
In what conditions do we expect device_info to be valid but not have a version? Also we can just do `.get('version')`, returning None on key miss is implicit

2020-01-27 15:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/mod_abc.py
> +        self._available_update_version: Optional[str] = None
IMO we should bundle these two into a named tuple or something and have a function that returns `Optional[ModuleFirmware]` so we can't possibly be in a one-but-not-the-other situation

2020-01-27 15:45 UTC, sfoster1 commented on api/src/opentrons/main.py
> +        resources.extend([fw_dir / item for item in os.listdir(fw_dir)])
can be `resources.extend(fw_dir.iterdir())` (or `resources.extend(list(fw_dir.iterdir()))` if extend doesn't iterate)

2020-01-27 15:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/thermocycler.py
> +    def available_update_path(self):
needs a return value annotation

2020-01-27 15:45 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/mod_abc.py
> +        MODULE_FW_RE = re.compile(f'{file_prefix}@v(.*).(hex|bin)')
And as mentioned below we should make this a full string match and search the filename

2020-01-27 16:53 UTC, b-cooper commented on api/src/opentrons/hardware_control/modules/mod_abc.py
> +        fw_resources = [fw_dir / item for item in os.listdir(fw_dir)]
so handy ✋

2020-01-28 19:50 UTC, sfoster1 approved these changes
Looking really good!

2020-01-28 21:28 UTC, merged