feat(api): add perform module fw update endpoint
OpenTrons/opentrons-api pull request #4889
Opened 2020-01-29 23:15 UTC by b-cooper

## overview

Add ability to initiate a module fw update for a given attached module, referenced by its serial
number via http. Remove old unused module os level configuration. Update the module update machinery
and comments to be more accurate and generic.

Closes #4576

## changelog

  - add support for POST `/modules/[SERIAL]/update`, with no body
  - cleanup access to avrdude configuration, should be all through buildroot now
  - reorganize some of the module update logic to be more generic and accurate

## review requests

- Make sure your robot has a new buildroot build that includes module firmware files in `/usr/lib/firmware/` 
- Attached modules of each type [tc, md, td] to the robot that have lower firmware versions than those listed in the file names of `/usr/lib/firmware`
- POST to `[ROBOT_IP]:31950/modules/[MODULE_SERIAL]/update` and confirm that the fw update succeeds

2020-01-30 15:55 UTC, sfoster1 requested changes
Couple nitpicks but it looks good overall

2020-01-30 15:55 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/update.py
> +    for module in request.app['com.opentrons.hardware'].attached_modules:
let's make this return early if it doesn't find the module, we can cut a level of indentation that way

2020-01-30 15:55 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/update.py
> +                    status = 404
this doesn't quite seem like the appropriate status code? but i'm not sure what would be better

2020-01-30 15:55 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/update.py
> +                status = 400
this probably should be a 500 also, considering the request doesn't provide any info other than which module to update it's hard to see how it should be a 4xx

2020-01-30 16:09 UTC, b-cooper commented on api/src/opentrons/server/endpoints/update.py
> +                    status = 404
I'll change it to 500

2020-01-31 14:47 UTC, sfoster1 approved these changes
LGTM

2020-01-31 15:58 UTC, mcous submitted a review, later dismissed
Can you also add this endpoint to HAPIv1's OpenAPI spec? `api/src/opentrons/server/openapi.json`

2020-02-03 15:51 UTC, sfoster1 approved these changes
Rereviewed the module object refresh. Looks good.

2020-02-05 15:43 UTC, merged