feat(app): enable module firmware update button when update available
OpenTrons/opentrons-api pull request #4923
Opened 2020-02-05 18:58 UTC by b-cooper

## overview

Building on previous work to get the newest module fw on the robot per each release, this adds
functionality to the app allowing the user to update an attached module of their connected robot, if
that module has an available firmware update.

re #4576, Closes #4575

## changelog

  - Conditionally enable Module update Button if update available and connected to robot
  - Add guiding ("connect to robot") tooltip when button is "Update" and disabled
  - Added epic to handle the request and response of the POST to `/modules/{serial}/update`

## review requests

  - [ ] Confirm button is disabled and text reads "Updated" (same as before) for attached modules on a connected robot with up to date firmware (see current version map below)
```
  {
    temperature_module: 'v2.0.0',
    magnetic_module: 'v1.0.1',
    thermocycler: 'v1.1.0',
  }
```
- [ ] Confirm button reads "Update" for attached modules with out of date firmware
- [ ] "Update" button should be disabled with tooltip when not connected to robot
- [ ] "Update" button should result in spinning loader when clicked while connected to robot
- [ ] Module should reboot and return to list after update

2020-02-06 14:40 UTC, sfoster1 approved these changes
Tested on litter-hood and OT2CEP20191129B16, works as specified in PR message and also when presented with a robot without the corresponding backend patch

2020-02-06 20:45 UTC, mcous requested changes
A few little requests:

- Import cleanup
- `$FlowFixMe` without additional comment
- A few copy strings that weren't moved up with the other copy consts
- Leftover `console.log`

And one larger question:

- Should this PR include component unit tests? Given that client-side is the only protection we have here, and manual testing this is a real pain, I think we probably should

2020-02-06 20:45 UTC, mcous commented on app/src/components/ModuleItem/ModuleUpdate.js
> +import { dismissRequest } from '../../robot-api/actions'
Can we import this from `robot-api` instead of `robot-api/actions`?

2020-02-06 20:45 UTC, mcous commented on app/src/components/ModuleItem/ModuleUpdate.js
> +import { updateModule } from '../../modules/actions'
Can we import from `modules` instead of `modules/actions`?

2020-02-06 20:45 UTC, mcous commented on app/src/components/ModuleItem/ModuleUpdate.js
> +  // $FlowFixMe
What is this `$FlowFixMe` doing?

2020-02-06 20:45 UTC, mcous commented on app/src/components/ModuleItem/ModuleUpdate.js
> +  const buttonText = hasAvailableUpdate ? 'update' : 'up to date'
Can we move these magic strings up to the copy constants already above?

2020-02-06 20:45 UTC, mcous commented on app/src/components/ModuleItem/ModuleUpdate.js
>  export function ModuleUpdate(props: Props) {
Should we add component tests for this new functionality? Having watched the difficulty of manual testing and the variety of conditions involved + actions taken for this functionality, I'd hate to leave it all to manual QA

2020-02-06 20:45 UTC, mcous commented on app/src/modules/actions.js
> +  payload: { robotName, moduleId, message },
Are we doing anything with this payload? If not, it might make sense to leave it out until we need it

2020-02-06 20:45 UTC, mcous commented on app/src/robot-api/actions.js
> +  console.log(DISMISS_REQUEST)
Missed a console.log!

2020-02-06 21:34 UTC, b-cooper commented on app/src/components/ModuleItem/ModuleUpdate.js
> +  // $FlowFixMe
Flow doesn't like the fact that error the error key doesn't exist if `status !== FAILURE`.  Adding a comment that says the same.

2020-02-06 21:42 UTC, b-cooper commented on app/src/modules/actions.js
> +  payload: { robotName, moduleId, message },
I figured it is useful for debugging to tie the response back to the module and robot. Are you suggesting changing the success action to just have a `type` and `meta` key?

2020-02-06 22:17 UTC, mcous commented on app/src/components/ModuleItem/ModuleUpdate.js
> +  // $FlowFixMe
Would it make more sense to pull out latestRequest.error.message below, underneath the `latestRequest?.status === 'failure'` check? (might need to be `latestRequest && latestRequest.status === FAILURE` because our version of flow doesn't type all the way through `?.`

2020-02-06 22:17 UTC, mcous commented on app/src/components/ModuleItem/ModuleUpdate.js
> +      {latestRequest?.status === 'failure' && (
Missed in my review; can we use the FAILURE import instead of a magic string?

2020-02-06 22:32 UTC, b-cooper commented on app/src/components/ModuleItem/ModuleUpdate.js
> +  // $FlowFixMe
Sweet, I didn't know that about flow not pushing through `?.` yet, just patched it up

2020-02-07 15:54 UTC, mcous approved these changes
💯

2020-02-07 15:54 UTC, mcous commented on app/src/components/ModuleItem/__tests__/ModuleUpdate.test.js
> +  test('component renders', () => {
[More food for thought (and our testing discussion next week than a request] Rather than snapshot tests, I think to consider this fully tested we would need tests for:

- Triggering the `onClick` prop of the button (when not disabled) dispatches the correct action
- When request is in progress a spinner icon is displayed
- If request errors, alert modal is rendered
- Alert modal dismisses request state

It's good that we're testing button disabledness, but at the moment I still think this requires manual QA

As a pleasant side effect for maintainability, I think in the process of writing these tests (preferably TDD-style), we would have discovered that this really needs to be a couple components (at least)

2020-02-07 15:54 UTC, mcous commented on app/src/modules/actions.js
> +  payload: { robotName, moduleId, message },
As discussed in person, I agree with you that we should leave the payload alone. This "useless" payload is a function of our overreliance on RPC-style HTTP endpoints and we should keep an eye on this sort of stuff in HAPIv2

2020-02-07 17:05 UTC, merged