refactor(api): split module labware handling
OpenTrons/opentrons-api pull request #4931
Opened 2020-02-06 18:23 UTC by sfoster1

This puts all the module labware stuff (module geometries, loading, etc)
into its own file module_geometry.py. This is both a good idea in
general since it reduces the size of the fairly monstrous labware.py and
also paves the way for future work in loading modules.

2020-02-06 19:07 UTC, amitlissack commented on api/src/opentrons/protocol_api/module_geometry.py
> +        definition['ordering'] = definition['ordering'][3::]
Could there be a potential issue with this mutation of `labware`'s private member?

2020-02-06 19:20 UTC, sfoster1 commented on api/src/opentrons/protocol_api/module_geometry.py
> +        definition['ordering'] = definition['ordering'][3::]
it's definitely not the best style. It works in practice because this is the only way that labware is accessed when used (which it's not, currently - this is a hack for a feature we decided to not ship at least yet, putting the thermocycler module partially off the deck to save a deck slot at the expense of the leftmost three rows of wells in a 96-plate) but it's absolutely fragile.

The best way forward may be to delete it. That said I'd prefer to avoid modifying code in this pr any more than absolutely necessary to make the changed module structure work correctly.

2020-02-12 16:04 UTC, Laura-Danielle requested changes
Code looks good, just one name change to make it slightly less confusing.

2020-02-12 16:04 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/module_geometry.py
> +    def disambiguate_calibration(self) -> bool:
Can we instead name this property something like `is_module_parent` or something?

2020-02-12 16:39 UTC, sfoster1 commented on api/src/opentrons/protocol_api/module_geometry.py
> +    def disambiguate_calibration(self) -> bool:
No, this is a general method that might be added to other stuff in the future - it's also part of the DeckItem abstract base class

2020-02-12 17:09 UTC, Laura-Danielle approved these changes
LGTM

2020-02-12 17:16 UTC, merged