refactor(shared-data): split v2 module defs into own files
OpenTrons/opentrons-api pull request #4936
Opened 2020-02-06 20:09 UTC by sfoster1

This split makes the schema apply to only an individual module
definition, which will in turn allow definition consumers to schema
check definition inputs on an individual basis instead of as a document
defining all valid modules.

2020-02-07 18:36 UTC, IanLondon requested changes
Looks good, splitting the module defs into their own files similar to labware defs makes a lot of sense.

One thing I think is missing is that the module defs previously had a unique key for the module model eg `magdeck` and `magdeckGen2`, but the files are like `magnetic_module.json`, `magnetic_module_gen2.json`. How is a module meant to be uniquely identified?

Also we need to update the description of JSON protocol v4 `"description": "model of module. Eg 'magdeck' or 'magdeckGen2'. This should match a top-level key in shared-data/module/definitions/2.json"`

More context:

I think PD will need to use v2 modules b/c we need in PD to know the moduleType of a module (generation-agnostic) that v2 has and v1 doesn’t. PD when loading protocols that contain modules needs to translate from module model to moduleType (at some point).

Another thing: if this is still flexible, it would be clearer if models are always specific, eg `magdeckGen1` `magdeckGen2` instead of `magdeck` `magdeckGen2` b/c the less-specific `magdeck` seems like it’s a model type where it’s a model here. This ambiguity made a handful of FE module-related stuff tricky to understand, so I’m going to disambiguate model type vs module in https://github.com/Opentrons/opentrons/issues/4897

2020-02-07 18:36 UTC, IanLondon commented on shared-data/js/modules.js
> +import moduleSpecs from '../module/definitions/1.json'
this is OK as a temporary fix. The `ModuleDef2` type isn't v2, neither is `getModuleDef2`, and `getModuleTypeFromModuleModel` won't work (it's being used in PD now). However it looks like this isn't breaking anything that isn't already broken (loading a previously saved protocol with modules into PD), I can add the cleanup stuff I mentioned above to #4897.

2020-02-07 18:49 UTC, sfoster1 commented on shared-data/js/modules.js
> +import moduleSpecs from '../module/definitions/1.json'
I can definitely add things here

2020-02-07 18:52 UTC, sfoster1 commented
It sounds like
- We should add a "model" key to the individual defs that always matches the def filename, and is a short name like "magnetV1" or "temperatureV2" or "thermocyclerV1" (this breaks away from the public consumption name with generations, which is definitely good).
- We have the `moduleType` key already
- I think we get rid of the `loadNames` array because it's a python api only concern and hoist them into code

2020-02-07 19:11 UTC, IanLondon commented on shared-data/js/modules.js
> +import moduleSpecs from '../module/definitions/1.json'
we could follow the pattern we did in `getAllDefinitions` at `protocol-designer/src/labware-defs/utils.js`, modules instead of labware. The way we did it for labware is by-project, so eg app and protocol-designer get the labware defs their own way. The shared-data utils always take a labware def and derive info from it. So if we keep this approach, the 3 fns in `shared-data/js/modules.js` probably need to move to PD, I think... 

The idea was that we didn't want to make all consumers of shared-data JS imports forced to also download all the labware definition data. But since there's not a lot of module definition data, maybe we don't have to make this optimization. If that's true, we could do something like that `getAllDefinitions` fn using webpack `require.context` in `shared-data` instead of both in app and PD.

Or we can punt this to 4897 🙃

2020-02-10 22:11 UTC, IanLondon requested changes
moduleAccessors test only passing b/c no files are loaded (and moduleSpecsSchema too I think)

2020-02-10 22:13 UTC, IanLondon commented on shared-data/js/__tests__/moduleSpecsSchema.test.js
> +const v2DefinitionsGlobPath = path.join('../../module/definitions/2/*.json')
this is broken too like above, needs `__dirname`

2020-02-10 22:13 UTC, IanLondon commented on shared-data/js/__tests__/moduleAccessors.test.js
> +const v2DefinitionsGlobPath = path.join('../../module/definitions/2/*.json')
this isn't working, I Slacked you a fix

2020-02-10 22:16 UTC, IanLondon commented on shared-data/js/__tests__/moduleSpecsSchema.test.js
> +    const modulePaths = glob.sync(v2DefinitionsGlobPath)
like the patch I sent for moduleAccessors, let's add a false positive test, ensuring `expect(modulePaths.length).toBeGreaterThan(0)`

I like these b/c if we ever change the paths to defs in shared-data, the glob-based tests can silently just get empty array of files and nothing will fail to warn us otherwise

2020-02-13 16:50 UTC, b-cooper approved these changes
Looks Good 🌾

2020-02-18 14:56 UTC, IanLondon approved these changes
looks good!

2020-02-18 14:56 UTC, IanLondon commented on shared-data/js/__tests__/moduleSpecsSchema.test.js
> +      console.log(`full path is ${modulePath}`)
stray log

2020-02-18 18:27 UTC, mcous requested changes
Some change requests to ensure cross-OS compatibility and that we pull in definition files the same way for different definitions

2020-02-18 18:27 UTC, mcous commented on shared-data/js/__tests__/moduleAccessors.test.js
> +  test('got at least 1 module def (avoid false positive for tests)', () => {
IMO this belongs in a `beforeAll` block, not a `test`

2020-02-18 18:27 UTC, mcous commented on shared-data/js/__tests__/moduleAccessors.test.js
> +  __dirname,
This patterns exists in various places in our codebase, but would cause problems with cross-OS tests. Per [glob's documentation](https://github.com/isaacs/node-glob#windows), we shouldn't use Windows style paths (which will be present in `__dirname` on Windows) in glob patterns.

We should use the `cwd` and `abdolute` options of `glob` to accomplish the same output with the pattern limited to forward-slashes:

```js
const V2_DEFS_GLOB_PATTERN = '../../module/definitions/2/*.json'
const GLOB_OPTIONS = { cwd: __dirname, absolute: true }

// ...

  const validDefPaths = glob.sync(V2_DEFS_GLOB_PATTERN, GLOB_OPTIONS) 
```

2020-02-18 18:27 UTC, mcous commented on shared-data/js/__tests__/moduleAccessors.test.js
> +      expect(getModuleTypeFromModuleModel(model)).toMatch(/.*/)
What exactly is this testing? Shouldn't we make sure the result is one of `MAGNETIC_MODULE_TYPE`, `TEMPERATURE_MODULE_TYPE`, `THERMOCYCLER_MODULE_TYPE`?

2020-02-18 18:27 UTC, mcous commented on shared-data/js/__tests__/moduleAccessors.test.js
> +      expect(getModuleDisplayName(model)).toMatch(/.*/)
This expectation also doesn't look like its really testing anything, especially given the test name

2020-02-18 18:27 UTC, mcous commented on shared-data/js/__tests__/moduleSpecsSchema.test.js
> +const v2DefinitionsGlobPath = path.join(
Same glob comment

2020-02-18 18:27 UTC, mcous commented on shared-data/js/__tests__/moduleSpecsSchema.test.js
> +  test('got at least 1 v2 module def (avoid false positive for tests)', () => {
Same beforeAll comment

2020-02-18 18:27 UTC, mcous commented on shared-data/js/modules.js
> +  } catch (ex) {
This try-catch is setting off warning bells in my head. This looks like a job for a webpack import context like we do with labware definitions.

Also, this needs to log if it catches

2020-02-19 16:00 UTC, sfoster1 commented on shared-data/js/__tests__/moduleSpecsSchema.test.js
> +  test('got at least 1 v2 module def (avoid false positive for tests)', () => {
👍

2020-02-19 16:00 UTC, sfoster1 commented on shared-data/js/__tests__/moduleSpecsSchema.test.js
> +const v2DefinitionsGlobPath = path.join(
👍

2020-02-19 16:00 UTC, sfoster1 commented on shared-data/js/__tests__/moduleAccessors.test.js
> +      expect(getModuleDisplayName(model)).toMatch(/.*/)
Yup we went back and forth on the implementation here and this didn't get updated

2020-02-19 16:01 UTC, sfoster1 commented on shared-data/js/__tests__/moduleAccessors.test.js
> +      expect(getModuleTypeFromModuleModel(model)).toMatch(/.*/)
wanted to make it context agnostic and mostly not be falsy (e.g. this would be an "is a string and not an error" check but we can make it exact

2020-02-19 16:01 UTC, sfoster1 commented on shared-data/js/__tests__/moduleAccessors.test.js
> +  __dirname,
👍

2020-02-19 16:01 UTC, sfoster1 commented on shared-data/js/__tests__/moduleAccessors.test.js
> +  test('got at least 1 module def (avoid false positive for tests)', () => {
👍

2020-02-19 16:27 UTC, mcous commented on shared-data/js/__tests__/moduleAccessors.test.js
> +      expect(getModuleTypeFromModuleModel(model)).toMatch(/.*/)
I think "valid models have a string model type" is a fine test, but in that case I might write that assertion as

```js
expect(getModuleTypeFromModuleModel(model)).toEqual(expect.any(String))
```

to be just a little more explicit than a catchall regexp

2020-02-19 22:17 UTC, mcous commented on shared-data/js/__tests__/moduleAccessors.test.js
> +      // $FlowFixMe: this is not null because of above expect
`$FlowFixMe`s should be added only as a last resort. In this case, does optional access work?

```js
 expect(loadedDef?.model).toEqual(model)
```

2020-02-20 14:44 UTC, sfoster1 commented on shared-data/js/__tests__/moduleAccessors.test.js
> +      // $FlowFixMe: this is not null because of above expect
it does!

2020-02-20 17:18 UTC, IanLondon commented on shared-data/js/__tests__/moduleSpecsSchema.test.js
> +beforeAll(() => {
Nitpick/question: I'm not sure why this assert is wrapped in `beforeAll`? There's no async stuff going on.

2020-02-20 17:32 UTC, sfoster1 commented on shared-data/js/__tests__/moduleSpecsSchema.test.js
> +beforeAll(() => {
Mike's previous PR review asked to do the false positives in a beforeAll

2020-02-20 18:58 UTC, mcous approved these changes
A couple testing nitpicks but looks good overall

2020-02-20 18:58 UTC, mcous commented on shared-data/js/__tests__/moduleSpecsSchema.test.js
> +  assert(MODULE_PATHS.length > 0)
Nitpick, but you should continue to use jest's expect here rather than pulling in assert

2020-02-20 18:58 UTC, mcous commented on shared-data/js/__tests__/moduleSpecsSchema.test.js
> +beforeAll(() => {
My reasoning there is that it's a condition for the suite to be valid rather than a specific unit test

2020-02-20 18:58 UTC, mcous commented on shared-data/js/__tests__/moduleSpecsSchema.test.js
> +        console.log(JSON.stringify(validationErrors, null, 4))
Conditionals in tests ring alarm bells in my head. This log is unnecessary because the expectation failure below will print the contents of it's not null

2020-02-20 19:05 UTC, sfoster1 commented on shared-data/js/__tests__/moduleSpecsSchema.test.js
> +  assert(MODULE_PATHS.length > 0)
oh, didn't know you could

2020-02-20 19:06 UTC, sfoster1 commented on shared-data/js/__tests__/moduleSpecsSchema.test.js
> +        console.log(JSON.stringify(validationErrors, null, 4))
Sure

2020-02-20 20:27 UTC, merged