Api gen2 modules wip
OpenTrons/opentrons-api pull request #5039
Opened 2020-02-20 15:11 UTC by sfoster1

This is the beginnings of the work to handle gen2 modules in the protocol API. It has (most of the commits from) the split module schemas pr worked in, which I'll rebase out later.

2020-02-24 21:28 UTC, IanLondon commented on api/src/opentrons/hardware_control/modules/magdeck.py
> +                revision_num = float(revision.split('v')[-1])  # type: ignore
What's a revision vs a model? This string parsing seems potentially funky but maybe I'm just lacking context.

2020-02-24 21:29 UTC, IanLondon commented on api/src/opentrons/hardware_control/modules/magdeck.py
> +            if revision_num < 20:
could this `20` live as data somewhere in some `constants.py` or in JSON?

2020-02-24 21:38 UTC, IanLondon commented on api/src/opentrons/hardware_control/modules/magdeck.py
> +                revision_num = float(revision.split('v')[-1])  # type: ignore
Is a revision string like `'V20'` or like `'mag_deck_v20'`? I see it both ways below but I'm assuming it's the latter looking at this with only lowercase `v`. I guess it's very boilerplatey to make a dict `revision_num_map = {"mag_deck_v19": 19, "mag_deck_v20": 20}` but splitting on `v` also isn't ideal... IDK

2020-02-25 14:49 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/magdeck.py
> +            if revision_num < 20:
that's probably a good idea (i'd put it in a constants.py)

2020-02-25 14:49 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/magdeck.py
> +                revision_num = float(revision.split('v')[-1])  # type: ignore
1. it's objectively funky
2. see pr description

2020-03-03 20:16 UTC, IanLondon commented on api/src/opentrons/hardware_control/modules/magdeck.py
> +    if revision_num < 20:
same comment about moving the 20 to a variable in something like `constants.py`

2020-03-03 21:03 UTC, nusrat813 approved these changes

2020-03-04 16:38 UTC, Laura-Danielle requested changes
Small change requests. Will test this on my robot as a sanity check.

2020-03-04 16:38 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/definitions.py
> +V2_MODULE_DEF_VERSION = types.APIVersion(2, 3)
If this is the first version that people can use GEN2 modules we should put it somewhere in the docs. Since we haven't released the new modules, it might be good to just make a ticket so we don't forget.

2020-03-04 17:25 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/tempdeck.py
> +        return 'temperatureModuleV2'
I think no because it's a bit awful - if we had more consistent revision numbers, I would say yes. for now, having a constant as the divider i think is the best way to do it.

2020-03-04 17:31 UTC, sfoster1 commented on api/src/opentrons/drivers/temp_deck/driver.py
> -            device_info = self._send_command(GCODES['DEVICE_INFO'])
👍

2020-03-04 17:31 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/magdeck.py
> +    if revision_num < 20:
👍

2020-03-04 17:31 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/tempdeck.py
> +    if revision_num < 20:
👍

2020-03-04 18:36 UTC, Laura-Danielle commented
Code changes look good. When I tested this on my robot, I was unable to use `opentrons_execute` to 1. be able to control modules and 2. check for backwards compatibility. For example, I was able to load a GEN1 module with `magnetic module gen2` without receiving any errors.

The modules themselves to do not work (i.e. not actually performing specified commands) when I use `opentrons_execute`.

2020-03-06 20:16 UTC, Laura-Danielle approved these changes
Re-tested on robit. Code looks good to me.

2020-03-06 21:12 UTC, nusrat813 approved these changes
9 bullets tested, working as intended 👍

2020-03-06 21:19 UTC, merged