fix(api): remove unnecessary pipette movement during mix
OpenTrons/opentrons-api pull request #5128
Opened 2020-02-28 22:35 UTC by ahiuchingau

## overview
In APIv2, the pipette would move above the well between each aspirate-dispense repetitions during mix. The original logic for this movement is to reset the plunger position above liquid level after a blow-out command, to avoid over-aspiration in the subsequent `aspirate`. 

However, we currently evaluate the necessity of this action by checking the current volume of the pipette: if the volume is equal to 0, the pipette is always moved above the top of the well. Instead, we should check the plunger position and only move the pipette when the position is below the `bottom` position.

closes #4640 

## changelog
- add a check for the plunger position in `aspirate` to avoid unnecessary pipette movement
- include the pipette bottom position in the pipette config dictionary for easy access in the protocol API
- add function in hardware control API to return the current plunger position
- bump max API version to 2.3

## review requests
Run the following protocol in API version 2.2 and 2.3 and see that:
- in v2.2, the pipette moves out of the well before each aspirate
- in v2.3, the pipette only moves out of the well after blowout
```
pip.pick_up_tip()
pip.mix(repetitions=3)
pip.blow_out()
pip.mix(repetitions=3)
pip.return_tip()
```

2020-03-02 14:29 UTC, sfoster1 requested changes
Definitely the right way to solve it in general, but some of this functionality is actually in `hardware_control.pipette.Pipette` already, let's use that

2020-03-02 14:29 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +    @requires_version(2, 3)
underscore methods, which are private by convention, don't need requires_version annotations

2020-03-02 14:29 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +    async def plunger_position(
This doesn't feel like quite the right interface - the hardware controller's abstraction of a pipette is based around volumes, not positions. 

`hardware_control.pipette.Pipette` actually already has a `ready_to_aspirate` flag that is managed by `hardware_control.API.prepare_for_aspirate`. If we expose that through the `hardware_pipette` interface, we can gate both the move to top and, if we want, the call to `prepare_for_aspirate` behind it.

2020-03-02 14:29 UTC, sfoster1 commented on api/tests/opentrons/protocol_api/test_context.py
> -    assert len(fake_move.call_args_list) == 2
we should add a test for the case where we do in fact want to prepare for aspirate here

2020-03-04 16:46 UTC, sfoster1 approved these changes
Code LGTM once we delete the now-unused `plunger_position` function, feel free to merge once @nusrat813 approves

2020-03-04 16:46 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +    async def plunger_position(
delete

2020-03-04 20:29 UTC, nusrat813 commented
Issues with aspirate and dispense - not using max volume if volume not specified

2020-03-04 21:11 UTC, sfoster1 approved these changes
LGTM after publish changes

2020-03-04 21:23 UTC, nusrat813 commented
Retested after publish changes, working as intended 👍

2020-03-04 21:23 UTC, nusrat813 approved these changes

2020-03-04 21:40 UTC, merged

2020-03-05 02:37 UTC, SyntaxColoring commented
I believe we need documentation and API changelog updates as well, right?