Api execution manager for pipette actions
OpenTrons/opentrons-api pull request #5180
Opened 2020-03-06 23:07 UTC by b-cooper

## overview

In order to prevent pause/cancel edge case failures, make hardware control move and home commands observe the execution manager. Also, augment the execution manager to provide conditional locked access to a state variable, that now has a canceled state in addition to running and paused.

## changelog

- hardware controller `API` functions for `_move`, `home`, and `retract` all wait for the execution manager to be running
- replace `ExecutionManager`'s `_is_running` (an instance of `asyncio.Event`) with `_state` (an enum of [RUNNING, PAUSED, CANCELED]) and `_condition` (an instance of `asyncio.Condition`) to protect access to `_state`.
  

## review requests

2020-03-09 14:24 UTC, sfoster1 requested changes
Couple nitpicky style changes but the code looks fine. Should be fun to test

2020-03-09 14:24 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +    async def pause(self):
shouldn't be async, just calls `run_coroutine_threadsafe`

2020-03-09 14:24 UTC, sfoster1 commented on api/src/opentrons/hardware_control/execution_manager.py
> +                if self._state is ExecutionState.CANCELED:
let's make the spelling consistent, don't really care which way

2020-03-10 14:15 UTC, sfoster1 requested changes
A couple small change requests

2020-03-10 14:15 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        async def _chained_calls():
I don't think we necessarily need this to be a chained call run in threadsafe mode. Synchronous functions like `halt` need it because calls to them won't be automatically transformed by `ThreadManager`, but here they will - as long as you're accessing the API through a threadmanager, the `reset` coroutine will execute in the managed thread. so we can execute these inline

2020-03-10 14:15 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/test_execution_manager.py
> +    assert await exec_mgr.get_state() == ExecutionState.RUNNING
This should also test the behavior of `wait_for_is_running` in specific states. You can use [asyncio.wait_for](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait_for) to wrap the cases where it should block.

2020-03-10 21:25 UTC, nusrat813 approved these changes
Tested, cancel working properly

2020-03-11 15:46 UTC, sfoster1 approved these changes
code lgtm!

2020-03-11 17:40 UTC, merged