feat(api): use instrument max achievable height in plan_moves
OpenTrons/opentrons-api pull request #5193
Opened 2020-03-10 15:15 UTC by ahiuchingau

## overview
Currently, the safety height for a pipette to move between labware is strictly determined by adding the default labware z margin (10 mm) to the `deck.highest_z`. Since the P300 Gen2 multis are very tall compared to other models, some widely used module + labware setups (i.e. magnetic module + deep well plate / temperature module + aluminum screw-cap tube block) with a total safe height of ~143 mm can sometimes triggers the P300 Gen2 multis to hit the limit switch.

To solve this problem, we are changing the safety height when dealing with these tall labware configs:
1. add default labware z margin to the deck highest z to get the safety height
2. compare the safety height to the pipette max achievable height
3. if the safety height is greater than the max achievable height but the deck highest Z is at least 1 mm shorter than the max achievable height, use the max achievable height as the safety height instead
4. if the deck highest z is actually taller than the max achievable height, raise a LabwareHeightError

NOTE: We only expect the correct max height to be calculated on the robot because of specific robot calibrations.

closes #5156

## changelog
- added a method to hardware control API to get the instrument max achievable height
- modified safety height to pipette homed height when labware is too tall but still has enough labware z clearance (min: 1 mm) from the max achievable height
- updated and added some appropriate tests

## review requests
Make sure Magnetic Module + Deep Well Plate / Temperature Module + Aluminum Tube Rack would not trigger the Gen2 multis to hit the limit switch

2020-03-10 20:34 UTC, sfoster1 requested changes
Couple little changes but on the whole it looks good

2020-03-10 20:34 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +            critical_point: CriticalPoint = None):
```suggestion
            critical_point: CriticalPoint = None) -> float:
```

2020-03-10 20:34 UTC, sfoster1 commented on api/src/opentrons/protocol_api/geometry.py
>          # TODO: Remove these awful Well.top() calls when we eliminate the back
glad we can do this! but also remove the comment

2020-03-10 20:34 UTC, sfoster1 commented on api/src/opentrons/protocol_api/geometry.py
> +        # if we are already at the labware, we know the instr max height would
`would would`

2020-03-10 20:34 UTC, sfoster1 commented on api/src/opentrons/protocol_api/geometry.py
> +                    f"max pipette achievable height: {instr_max_height}")
Maybe `"The tallest piece of labware added to your deck, which is {deck.highest_z}mm tall, is too tall for the longest pipette on your deck, which can only raise to {instr_max_height}mm above the deck. This may be because a piece of labware is incorrectly defined, incorrectly calibrated, or physically too tall. Please check your labware definitions and calibrations."`

Even better would be if we could access the labware that has the highest z so we could tell people which one it was.

2020-03-11 14:49 UTC, b-cooper approved these changes
Code looks good! 🌵

2020-03-11 14:49 UTC, b-cooper commented on api/src/opentrons/protocol_api/geometry.py
> +                    " This may be because the labware is correctly defined, "
*incorrectly* defined?

2020-03-11 14:54 UTC, ahiuchingau commented on api/src/opentrons/protocol_api/geometry.py
> +                    " This may be because the labware is correctly defined, "
Oops

2020-03-11 15:02 UTC, sfoster1 commented on api/src/opentrons/protocol_api/geometry.py
> +                tallest_lw = list(filter(
What happens if there's an empty deck?

2020-03-11 17:32 UTC, sfoster1 approved these changes
LGTM

2020-03-12 17:20 UTC, merged