fix(api): call module functions across threads
OpenTrons/opentrons-api pull request #5194
Opened 2020-03-10 17:10 UTC by sfoster1

Moving to the threadmanager broke the case of calling module functions
through the threadmanager, since the module objects would be returned
directly.

They are now wrapped in CallBridger objects that have the
__getattribute__ override the same as thread managers but don't do the
actual thread managing. This is LRU cached so we don't build a bunch of
them.

## Testing
- Make sure that the module cards both in the pipettes and modules page and in protocol work

2020-03-10 18:18 UTC, b-cooper approved these changes
functionality looks good, just a couple of questions.

2020-03-10 18:18 UTC, b-cooper commented on api/src/opentrons/hardware_control/thread_manager.py
> +            wrapped = asyncio.wrap_future(fut)
Before, this was failing in some contexts because the main thread didn't have an event loop. Do you have reason to believe this isn't an issue anymore?

2020-03-10 18:18 UTC, b-cooper commented on api/src/opentrons/hardware_control/thread_manager.py
> +    def __getattribute__(self, attr_name: str) -> Any:
As this is really identical to the `__getattribute__` defined in the `ThreadManager`, and we don't want them to diverge individually, is there some way that they can both call a shared abstracted function to enforce this similarity?

2020-03-10 18:27 UTC, amitlissack commented on api/src/opentrons/hardware_control/thread_manager.py
> +        if attr_name == 'attached_modules':
Why?

2020-03-10 18:27 UTC, amitlissack commented on api/src/opentrons/hardware_control/thread_manager.py
> +class CallBridger(Generic[WrappedObj]):
Is this another interface like `ThreadManager` that wraps an API object?  What is a`CallBridger`?

2020-03-10 19:05 UTC, sfoster1 commented on api/src/opentrons/hardware_control/thread_manager.py
> +class CallBridger(Generic[WrappedObj]):
It is a threadmanager lite, I suppose. The `ThreadManager` is-a `CallBridger`, but it also is the actual owner of the thread. It could probably be changed to use the `CallBridger`

2020-03-10 19:37 UTC, amitlissack requested changes

2020-03-10 19:37 UTC, amitlissack commented on api/src/opentrons/hardware_control/thread_manager.py
> +class CallBridger(Generic[WrappedObj]):
Is there a future state where calling methods on a HardwareController or API or whatever it is does not happen through a `ThreadManager` or `CallBridger` any other wrapper that hides the interface? 

It's probably beyond the scope of this PR, but It's worth stating that the developer experience of using these wrappers is not pleasant.

2020-03-10 20:11 UTC, sfoster1 commented on api/src/opentrons/hardware_control/thread_manager.py
> +        if attr_name == 'attached_modules':
I will put a comment there. The reason is that this is the only thing that supplies more object that have complex methods that get called on them. All the other members and methods of the hardware control API actually only take or return data bundles.

2020-03-10 20:12 UTC, sfoster1 commented on api/src/opentrons/hardware_control/thread_manager.py
> +class CallBridger(Generic[WrappedObj]):
There is; it would be when the Smoothie serial driver and the module serial drivers are async. Right now, the serial transactions block and therefore block the event loop.

2020-03-11 20:19 UTC, sfoster1 commented on api/src/opentrons/hardware_control/thread_manager.py
> +            wrapped = asyncio.wrap_future(fut)
Do you remember what those contexts were?

2020-03-11 20:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/thread_manager.py
> +        return CallBridger(module, self._loop)
👍

2020-03-11 20:35 UTC, nusrat813 approved these changes
Tested, working as intended

2020-03-11 20:38 UTC, amitlissack approved these changes
Thanks

2020-03-12 13:39 UTC, merged