feat(api): Add API calibration check session
OpenTrons/opentrons-api pull request #5197
Opened 2020-03-10 19:53 UTC by Laura-Danielle

## overview

Closes #5094. You can now create a "calibration" session and receive the current status of that session.

## changelog

- Add in a session manager for any calibration sessions created
- Add in a calibration session class which holds information such as pipettes attached and upcoming steps
- Add in pydantic models associated with response shapes
- Add in util file that holds all steps available for a given session type (might have different steps for saving calibration transform and/or mount offset for example)

## review requests

@amitlissack do the pydantic models look sufficient?
@b-cooper are response shapes OK?

Let me know if I need any more documentation and/or any implementations seems incorrect.

2020-03-10 20:17 UTC, amitlissack requested changes

2020-03-10 20:17 UTC, amitlissack commented on api/src/opentrons/server/__init__.py
> +        # import pdb
Can you lose these comments please

2020-03-10 20:17 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/session.py
> +    mount_axis: str = \
Is this really a string? Can it be an enum instead?

2020-03-10 20:17 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/session.py
> +    plunger_axis: str = \
Same here. Can it be an enum?

2020-03-10 20:17 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        self.pipettes = self._key_by_uuid(hardware.get_attached_instruments())
Why is this public? Can it be private? You already have properties that get the current pipette.

2020-03-10 20:17 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/session.py
> +def _format_status(session_type: str):
Ideally, you would construct a `CalibrationSessionStatus` object rather than a dict.

2020-03-10 20:17 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        return web.json_response(response, status=200)
response should be a `CalibrationSessionStatus`. 

```web.json_response(response.dict(), status=200)```

2020-03-10 20:17 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        return web.json_response(response, status=201)
Same as above regarding `CalibrationSessionStatus`

2020-03-10 20:17 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        return web.json_response(status=200)
Is this meant to be an empty response?

2020-03-10 20:17 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/util.py
> +    'check': [
You've defined an enumeration called `CalibrationCheckActions` with some of these values. Any chance that can be used to avoid string constant duplications?

2020-03-10 20:17 UTC, amitlissack commented on api/tests/opentrons/conftest.py
> +    # await app.shutdown()
Why is this commented out?

2020-03-10 21:15 UTC, Laura-Danielle commented on api/src/opentrons/server/endpoints/calibration/session.py
> +    plunger_axis: str = \
Yes can be an enum. Will change.

2020-03-10 21:16 UTC, Laura-Danielle commented on api/tests/opentrons/conftest.py
> +    # await app.shutdown()
Should be deleted. Will remove.

2020-03-10 21:16 UTC, Laura-Danielle commented on api/src/opentrons/server/endpoints/calibration/util.py
> +    'check': [
Yep I will look into it.

2020-03-11 14:38 UTC, sfoster1 requested changes
Some inline comments around typing, but also some higher level things:

- We should keep the route handlers separate from the internal logic. This is generally good practice but especially needed when we know we'll have to port this to fastapi eventually. By keeping handlers in a separate place and restricting their code to serialization/deserialization and request validation, we make them a lot easier to delete and replace later
- In general, consider module structure: what should be in the same file? We have a problem on the python side of things with 5000 line files. While we want to avoid having 5000 1-line files, we can split this up a bit more.
- All the internal logic should operate on enums, dataclasses, and occasionally state objects. We shouldn't be using dictionaries of strings internally to change our behavior - it makes it tough to typecheck, tough to validate, and less clear.
- This is going to be a lot easier if we start with a state machine rather than starting with handlers. Explicit state machines are easy to test and easy to understand. The handlers then map nicely to state transitions.

2020-03-11 14:38 UTC, sfoster1 commented on api/pipettes/fake10pip.json
> +{"dropTipShake": true, "model": "p10_single_v1"}
Should this file (and the others like it, won't spam all of them) be checked in?

2020-03-11 14:38 UTC, sfoster1 commented on api/src/opentrons/server/__init__.py
> +def init(hardware: Union[ThreadManager, HardwareAPILike] = None,
This should probably take just a `ThreadManager` rather than the union, right? There's behavior in e.g. the shutdown handlers that will only work if this is a thread manager.

2020-03-11 14:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +            "fakeUUID1": {
these are response examples, right? I think they need to be wrapped in an `examples` field per https://pydantic-docs.helpmanual.io/usage/schema/#schema-customization

2020-03-11 14:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +from uuid import UUID, uuid1
it's probably better to use `uuid4` rather than `uuid1`. 4 is random; 1 is about host ids and current times and stands a better (if still small) chance of colliding.

2020-03-11 14:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        self._current_uuid: typing.Optional[str] = None
i think we probably want to avoid this being internal state; all of our action handlers should take a target pipette uuid as a parameter, and the hardware controller can handle the retract requirements

2020-03-11 14:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        self.token = str(uuid1())
While we'll have to serialize the uuids to strings to send via json, internally we should maintain them as UUID objects. We can turn them into strings when building responses, and load them from strings when parsing requests via the `hex` argument to the UUID constructor.

2020-03-11 14:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +            if mount.name.lower() == 'right':
If this is a constant we can compare the mount enum entry directly, right? like `mount == Mount.RIGHT`?

2020-03-11 14:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +class CalibrationSession:
The methods of this class should be typed

2020-03-11 14:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +class SessionManager:
Methods should be typed

2020-03-11 14:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +session_storage = SessionManager()
This should probably be in the app storage

2020-03-11 14:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +def _format_status(session_type: str):
and we should type it

2020-03-17 16:04 UTC, sfoster1 requested changes
Couple more comments

2020-03-17 16:04 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +    def _build_state_machine(
this should be the source of truth for the state machine structure and should probably be a file-scope free function

2020-03-17 16:04 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/models.py
> +import typing
let's only have what's absolutely necessary as pydantic models

2020-03-18 11:41 UTC, amitlissack requested changes

2020-03-18 11:41 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/check.py
> +        return web.json_response(json.loads(serialize), status=200)
I notice that this conversion to json and then back to a dict is happening a number or times. What problem is this solving? Is there perhaps another way to solve it?

2020-03-18 11:41 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/check.py
> +    # pydantic restricts dictionary keys that can be evaluated. Since
Thanks for the comment!

2020-03-18 11:41 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/check.py
> +    pips = session._pipettes
In my opinion if we need to access the private `_pipettes` outside of the `CalibrationSession` scope we should add a `pipettes` property.

2020-03-18 11:41 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/util.py
> +        self.add_state("sessionStart", 0)
What do the numbers signify?

2020-03-18 11:41 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/util.py
> +        self._modify_state("sessionStart", "sessionStart", "specifyLabware")
Do these states map to functions somewhere?

2020-03-18 11:41 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/util.py
> +        self.add_state("checkPointTwo", 4)
I think it would be great to define these state names in one place only. Either as enums or as members of some class or something.

2020-03-19 15:09 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/check.py
> +        links = {'links': {next.name: url}}
oo thats really nice

2020-03-19 15:18 UTC, sfoster1 requested changes
Couple little nitpicks but the structure is looking really good

2020-03-19 15:18 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/check.py
> +    session_type = request.match_info['type']
unless i'm missing something, it looks like the type here isn't actually checked - you could do `POST /calibration/ajnfklsjdlajs/session` and look for the `ajnfklsjdlajs` session. We should probably limit this to `check`. Presumably this would be handled by request models on the fastapi side but here there's nothing.

2020-03-19 15:18 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/check.py
> +        # Ugly work-around for serializing UUIDs and Axis types. See
is this comment referring to `_format_status`? or out of date?

2020-03-19 15:18 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/models.py
> +        json_encoders = {Axis: str}
could we put the uuid encoder in here too?

2020-03-19 15:18 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        self._pipettes.update(new_dict)
this won't remove the old keys since every new call to `_key_by_uuid` will generate a new uuid - we may want to clear the dict first

2020-03-19 15:18 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/util.py
> +class StateEnum(enum.Enum):
this all looks really nice

2020-03-19 15:18 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/util.py
> +stateInput = TypeVar('stateInput', bound=str)
let's keep types CamelCased

2020-03-19 15:18 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/util.py
> +            self, states, rel: relationship,
can we type `states`?

2020-03-19 15:18 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/util.py
> +    def next_state(self, input: stateInput = None) -> 'State':
should this maybe take a relationship kind (like normal, exit, error) and the upper code can specify which one it wants? this fallthrough stuff looks like it could cause some surprising behaviors

2020-03-19 15:18 UTC, sfoster1 commented on api/tests/opentrons/server/test_calibration_session.py
> +    class Relationship(enum.Enum):
Lol

2020-03-19 15:22 UTC, Laura-Danielle commented on api/tests/opentrons/server/test_calibration_session.py
> +    class Relationship(enum.Enum):
I had it as 'relations' before lmao

2020-03-19 15:24 UTC, Laura-Danielle commented on api/src/opentrons/server/endpoints/calibration/check.py
> +        # Ugly work-around for serializing UUIDs and Axis types. See
Out of date now. @amitlissack helped come up with a nice way of utilizing serialization behavior from models.

2020-03-19 15:37 UTC, amitlissack reviewed
Looking good. Just some minor questions.

2020-03-19 15:37 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/util.py
> +            self, states, rel: relationship,
`states` is not typed.  Is it a `List[State]`?

2020-03-19 15:37 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/util.py
> +        if curr and hasattr(self._relationship, curr):
Sorry, but I find this logic pretty confusing. Would it perhaps make more sense for `_relationship`, `_exit_relationship`, and `_exit_relationship` to each be a set of State objects (or State object names) rather than Enums?

2020-03-19 15:37 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/util.py
> +    sessionStart = State("sessionStart", enum.auto())
I'm really happy with the change to using a enums for the state names.

2020-03-19 17:26 UTC, b-cooper approved these changes
Looks good to me. I agree with the most recent comments too. 🏭

2020-03-19 20:04 UTC, Laura-Danielle commented on api/src/opentrons/server/endpoints/calibration/session.py
> +"""
Yep. I am planning on making a calibration check session, but figured I'd hold off on that change until this one gets merged in.

2020-03-19 20:22 UTC, sfoster1 approved these changes
This looks really good! Love a state machine.

2020-03-24 13:34 UTC, amitlissack requested changes

2020-03-24 13:34 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/models.py
> +    Dict[str, AttachedPipette]
What does this do? I think that you should change `CalibrationSessionStatus` to have a field `instruments: Dict[str, AttachedPipette]`

2020-03-24 13:34 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/util.py
> +        if hasattr(relationship_enum, input):
My 2 cents is that if one finds themselves wanting to use `hasattr` and `getattr` they should think long and hard about whether they've picked the right data structures. 

That's my opinion. I'm demanding a change here. I just would have used a `Set` for `relationship`.

2020-03-24 20:30 UTC, sfoster1 requested changes
Bit of a nitpick but structurally looks good

2020-03-24 20:30 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/util.py
> +CheckExitRelationshipDict = {
bit of a nitpick but this is a variable not a type, let's keep it snake_case

2020-03-24 20:38 UTC, Laura-Danielle commented on api/src/opentrons/server/endpoints/calibration/util.py
> +        if hasattr(relationship_enum, input):
Just saw this comment, but relationships are now in the form of `Dict[Enum, Enum]` and does not require `hasattr` to check whether something exists or not.

2020-03-24 20:52 UTC, amitlissack approved these changes
Thanks for being open and patient with all the comments.

2020-03-24 21:02 UTC, sfoster1 approved these changes
looks good to me structurally, and tested on a robot OK

2020-03-24 21:25 UTC, mcous reviewed
I have a few questions after reading through this in conjunction with #5260 

- Why aren't there separate `GET` and `POST` endpoints for deck calibration sessions?
- Why are we parameterizing the session type in the URL? This seems premature to me

2020-03-24 21:25 UTC, mcous commented on api/src/opentrons/server/endpoints/calibration/check.py
> +    If a session exists, this endpoint will return the current status.
This makes me nervous. I think that there should be separate endpoints for create and fetch. As implemented, this looks pretty easy to get a stale session even if the client wanted to create a new one. Clients failing to clean up their sessions will be relatively common

2020-03-24 21:25 UTC, mcous commented on api/src/opentrons/server/http.py
> +            '/calibration/{type}/session', check.create_session)
Why are we bothering with a {type} parameter here? It seems a little premature

2020-03-24 21:46 UTC, Laura-Danielle commented on api/src/opentrons/server/endpoints/calibration/check.py
> +    If a session exists, this endpoint will return the current status.
To your first point, there was originally a `GET` and `POST` request. @b-cooper and I discussed/decided to remove the GET endpoint because the `POST` request already returns a status as [per the ticket requirements](https://github.com/Opentrons/opentrons/issues/5094).

The parameterization is to prepare for deck cal/pipette mount calibration work which will all be using the code from `session.py` and `util.py`.  I am fine with changing it to specifically be `/calibration/check/session` if you are concerned about it.

2020-03-24 21:54 UTC, merged