feat(api): add v4 JSON executor
OpenTrons/opentrons-api pull request #5221
Opened 2020-03-12 18:47 UTC by shlokamin

## overview

WIP - This PR closes #4868 by adding the v4 JSON executor to the api

## changelog

## review requests

2020-03-13 16:13 UTC, sfoster1 requested changes
Preliminary change requests to make this a bit more idiomatic python and support cancel

2020-03-13 16:13 UTC, sfoster1 commented on api/src/opentrons/protocol_api/execute_v4.py
> +    if status == 'heating':
We should push this logic down all the way to the `hardware_control.modules.TemperatureModule`, so cancelling works here.

The way cancel is currently implemented is in the [execution manager in hardware control](https://github.com/Opentrons/opentrons/blob/edge/api/src/opentrons/hardware_control/execution_manager.py) with an [asyncio condition](https://docs.python.org/3/library/asyncio-sync.html#asyncio.Condition) wrapping a state that can be running, paused, or cancelling. When you call a hardware control function that checks the condition (or one of the whitelisted ones for cancellation), you can be cancelled.

As this code stands, the cancellation won't actually happen here - you could be awaiting for a very long time, especially if there's an error in the tempdeck communications.

Making a `tempdeck.await_temperature(target: float)` function will fix this. We can register it as cancellable with the execution manager, which means it will get cancelled when a cancel happens; or we can implement some more complex logic that pairs monitoring the condition with awaiting the temperature.

The other open question is, what's supposed to happen to the protocol state when this is running? How does it interact with pause? This is as much a UX question as a technical question (@howisthisnamenottakenyet ).

2020-03-13 16:13 UTC, sfoster1 commented on api/src/opentrons/protocol_api/execute_v4.py
> +dispatcher_map: Dict[Any, Any] = {
This map and the code in `dispatch_json` looks like it will work, but I'd prefer to avoid magic strings in favor of enums - it's a bit easier to type systematically, since we don't have literal types (yet) in mypy. In addition, python enums can have arbitrary objects as values, so you could have something like

```
class JsonCommandHandler(NamedTuple):  # could also be a typed generic passed down to the handler element (see above re: C++ brain)
   name: str
   handler: Callable[] # appropriately type

class JsonCommand:
   "delay": JsonCommandHandler(...)
```

2020-03-13 16:13 UTC, sfoster1 commented on api/src/opentrons/protocol_api/execute_v4.py
> +                  protocol_data: Dict[Any, Any],
Similar to the comment above about typing, it would be nice for a lot of these arguments to be more tightly-defined objects rather than string-keyed dicts; it would also be nice for the protocol parse stage to yield data structures that actually have object references rather than string ids referring to keys in other string-keyed dicts.

2020-03-13 16:13 UTC, sfoster1 commented on api/src/opentrons/protocol_api/module_geometry.py
> +                         .join(model_map.keys()) + '", "' + '", "'
This is intended to be a literate error for python protocols; it may be better to avoid mentioning the `model_map` at all, or to explicitly mention it as a lesser alternative, something like:

"Valid names (ignoring case): {alias_map.keys()}

You can also refer to modules by their exact model: {model_map.keys()}"

2020-03-13 16:13 UTC, sfoster1 commented on api/src/opentrons/protocol_api/module_contexts.py
> +    @requires_version(2, 0)
This should require version 2.3, since it will be new in 2.3. Also, changes or additions to api-exposed methods should be accompanied with a change note in the [version docs](https://github.com/Opentrons/opentrons/blob/edge/api/docs/v2/versioning.rst)

2020-03-13 16:28 UTC, shlokamin commented on api/src/opentrons/protocol_api/execute_v4.py
> +    if status == 'heating':
Eek, forgot about cancel. I'm fine with moving this down to the module level, that means we're exposing another "hidden" thing to the module context though. But I guess there isn't really another option.

2020-03-13 17:08 UTC, sfoster1 commented on api/src/opentrons/protocol_api/execute_v4.py
> +    if status == 'heating':
it's really of equal status to the other one though - they come as a pair.

Honestly it's reasonable at this point to unhide it - we wanted to keep it hidden because you could set the temperature, but waiting for it wasn't exposed. If properly waiting for it is exposed, we might as well have it be part of the python api. What do you think @pantslakz and @howisthisnamenottakenyet

2020-03-16 18:21 UTC, shlokamin commented on api/src/opentrons/hardware_control/modules/tempdeck.py
> +
made `_await_temperature` a closure function to make it private

2020-03-16 19:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/tempdeck.py
> +
yeah that's fine with me. we're in general not concerned about enforcing visibility - we use the standard python practice of making private members start with underscores and trust people not to abuse it - but it's not worth changing this implementation

2020-03-16 19:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/tempdeck.py
> +        return await t
what does this return? if it's nothing, we don't need to `return`; if it's something, we should annotate the return type in both the inner closure and the wrapper

2020-03-16 19:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/tempdeck.py
> +                while (self.temperature < awaiting_temperature):
unnecessary parens

2020-03-16 19:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/tempdeck.py
> +                while (self.temperature > awaiting_temperature):
unnecessary parens

2020-03-20 18:17 UTC, shlokamin commented on api/tests/opentrons/test_execute.py
looks like a test using a v4 fixture needs to be added

2020-03-20 18:17 UTC, shlokamin commented on api/tests/opentrons/protocols/test_parse.py
> +
same thing here, looks like a test using a v4 fixture needs to be added

2020-03-20 18:22 UTC, IanLondon commented on api/tests/opentrons/protocols/test_parse.py
> +    # TODO IMMEDIATELY: v4 fixture here
we should add a v4 fixture and make sure it executes without crashing. Ideally it would do a gcode snapshot or something like that to make sure it's translated into PAPI calls exactly as we expect, but for now an integration smoke test would be nice.

2020-03-20 18:22 UTC, IanLondon commented on api/tests/opentrons/test_execute.py
> +# TODO IMMEDIATELY: test v4 fixture
same comment here as I made before

2020-03-20 18:27 UTC, IanLondon approved these changes
looks good, have comments about additional tests using the v4 fixture. Approved pending QA on robot :smile:

2020-03-20 19:26 UTC, sfoster1 requested changes
Couple little change requests but the structure looks good

2020-03-20 19:26 UTC, sfoster1 commented on api/src/opentrons/protocol_api/execute_v3.py
> +def _delay(context, params) -> None:
type annotations for arguments?

2020-03-20 19:26 UTC, sfoster1 commented on api/src/opentrons/protocol_api/execute_v3.py
> +    if slot not in [str(s + 1) for s in range(12)]:
would probably rather this check on a deck definition, or the keys in the associated protocol context's `deck` object

2020-03-20 19:26 UTC, sfoster1 commented on api/src/opentrons/protocol_api/execute_v3.py
> +dispatcher_map: Dict[Any, Any] = {
this could probably use the nice command enums as keys, though from talking previously it might want to stay `Any` for values since all the functions are different

2020-03-20 19:26 UTC, sfoster1 commented on api/src/opentrons/protocol_api/execute_v3.py
> +    pipette_command_list = [
This could involve enums a bit more

2020-03-20 19:26 UTC, sfoster1 commented on api/src/opentrons/protocol_api/module_geometry.py
> +    model_map: Mapping[str, ModuleModel] = {
[nitpitck] i think this should be a computed constant in this file, that could be something like
```
MODELS_BY_NAME = { e.value: e for e in itertools.chain(list(MagneticModuleModel), list(TemperatureModuleModel), list(ThermocyclerModuleModel)}
```

2020-03-23 13:39 UTC, shlokamin commented on api/src/opentrons/protocol_api/execute_v3.py
> +def _delay(context, params) -> None:
Yeah so this branch was actually based off of Ian's v3 executor refactor branch. I completely forgot that there were changes made to the v3 executor at all. I was trying to avoid touching the v3 executor for that reason, but since this PR already does, may as well address these changes too. Is that okay @IanLondon ?

2020-03-24 14:47 UTC, shlokamin commented on api/src/opentrons/protocol_api/module_geometry.py
> +    model_map: Mapping[str, ModuleModel] = {
I agree. I just tried this, and unfortunately it seems like mypy isn't smart enough to realize that `MODELS_BY_NAME ` is of type `Mapping[str, ModuleModel]`, but rather thinks it's of type `Mapping[str, _ProvideLookup]`.

Not sure how to get around this so I'll leave it for now. If you have any ideas lmk tho

2020-03-24 22:40 UTC, sfoster1 approved these changes
LGTM once qa approves. In the future we probably shouldn't merge edge back into longstanding branches though, it really makes a mess of the diff.

2020-03-24 22:42 UTC, shlokamin commented
Yeah that's my bad. I saw there was a conflict in the versioning notes so I thought I would merge and fix, but it really just made the tree unintelligible

2020-03-25 17:49 UTC, nusrat813 approved these changes

2020-03-25 18:15 UTC, merged