refactor(api): limit gen2 mag module max engage height
OpenTrons/opentrons-api pull request #5244
Opened 2020-03-17 18:00 UTC by ahiuchingau

## overview
This PR limits the Gen2 Magnetic Module engage height to 25 mm at 100 steps/mm.

In order to enforce this limit even during simulation, the simulating driver would need to know which model was loaded in the protocol. Therefore, the hardware module will now take an closes #5212
 argument `sim_model` during simulation from protocol context, which will then be evaluated to determine the correct max engage height. 

Note: Gen1 magnetic module behavior remains unchanged.
closes #5212

## changelog
- passed module model 
- added and updated appropriate tests

## review requests
- check that during both run and simulation, engage height > 25 mm should raise an error for Gen2 Magdeck
- check that max engage height for Gen1 is still 45 mm

## risk assessment
Low risk because gen1's behavior should be the same

2020-03-17 20:02 UTC, sfoster1 requested changes
Couple small changes.

I'm also not really sure about merging this until we make the change in the module firmware - if we merge this now, gen2 magdecks will become unusable until that is merged.

2020-03-17 20:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/tempdeck.py
> +                 sim_model: str = None) -> None:
same here re: push down to the driver

2020-03-17 20:02 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/thermocycler.py
> +                 sim_model: str = None) -> None:
if we're going to add this to all three we should put it in the abstract base class

2020-03-18 15:53 UTC, sfoster1 requested changes
Let's also move the simulating drivers to `opentrons.drivers.{module_name}`, ahve the modules connect to the simulators, get an appropriate hw revision based on the sim model, and have a single builder function in `opentrons.hardware_control.modules` to build the simulated modules.

2020-03-24 15:22 UTC, sfoster1 requested changes
Let's change some stuff to get rid of the `type: ignore` in driver assignments so typechecking continues to work, but the structure looks good

2020-03-24 15:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/tempdeck.py
> +                simulating, sim_model or self.model())
`self.model` is based on device info and therefore won't be present yet, so this is a correct type check failure. `build_driver` should allow `None` for its model and we shouldn't do `sim_model or self.model()`, just `sim_model` (same for the other modules)

2020-03-24 15:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/tempdeck.py
>              self._driver = temp_locks[port][1]
if we annotate `self._driver` as `Union[ThermocyclerDriver, SimulatingDriver` we can get rid of the `type: ignore` (same for the other modules)

2020-03-24 15:22 UTC, sfoster1 commented on api/src/opentrons/protocol_api/protocol_context.py
> +            hc_mod_instance._connect()
this is nice!

2020-03-24 15:22 UTC, sfoster1 commented on api/tests/opentrons/api/test_session.py
> +    print(type(mod2))
diagnostic print, remove

2020-03-25 15:29 UTC, sfoster1 approved these changes
LGTM if qa pass

2020-03-25 19:38 UTC, nusrat813 approved these changes
Tested - working as intended

2020-03-25 21:38 UTC, merged