App cal check init and complete
OpenTrons/opentrons-api pull request #5260
Opened 2020-03-20 20:02 UTC by b-cooper

# overview

Build out the domain and view layer scaffolding for the incoming deck calibration check flow.
Functionality is behind a new feature flag.

Closes #5030

## changelog
 - Add app-side feature flag "Enable Deck Cal Check"
 - Add ‘Check deck calibration’ section in the ‘Robot Controls’ card with a 'Check Calibration' button.
- Clicking ‘Check Calibration’ button launches the calibration check flow and creates a new deck calibration check session on the robot
- On launching the check calibration flow, user views the 'Deck Calibration Check Complete' modal which includes button to exit 'Drop Tip and Exit' flow and return to Robot page also ending deck calibration check session (homing the robot).
- Added analytics events for starting deck calibration check and successfully passing the deck calibration check

## review requests

- [ ] ensure "Check Calibration" button is not visible if feature flag isn't toggled on
- [ ] toggle on feature flag and ensure "Check Calibration" button launches Check Calibration flow when clicked
- [ ] confirm exiting from the titlebar and "drop tip and exit" buttons close session and home robot
- [ ] analytics event fires for 'startCalibrationCheck' when session starts
- [ ] analytics event fires for 'startCalibrationPass' when check completes successfully

## risk assessment

Low risk, as all functionality is behind an app side __dev__ feature flag.

2020-03-24 16:08 UTC, b-cooper commented on app/src/components/RobotSettings/ControlsCard.js
> +            // onClick: checkCalibration,
Nuke this

2020-03-24 21:27 UTC, mcous requested changes
Haven't tested, but I have a variety of comments related to consistency with existing app code. Also, the added epics are not covered by unit tests. Also also, the combo create/fetch endpoint makes me nervous and I've commented as such in #5197

If possible, it would also be good to use `refactor` in this PR title instead of `feat`. Usually for FF'd stuff in the app we try to reserve `feat` (and thus, the changelog entry) for the PR that removes the feature flag and promotes the behavior to release

2020-03-24 21:27 UTC, mcous commented on app/src/calibration/epic/index.js
> +export const calibrationEpic: Epic = combineEpics(
These epics are not covered by unit tests

2020-03-24 21:27 UTC, mcous commented on app/src/calibration/actions.js
> +export const fetchDeckCheckSession = (
`fetch...` actions in the app always correspond to `GET` requests. This appears to be a `POST` request. Could it be `postCreateDeckCheckSession` to line up with existing stuff?

2020-03-24 21:27 UTC, mcous commented on app/src/calibration/actions.js
> +export const endDeckCheckSession = (
This would line up a little better with existing actions if it was `deleteDeckCheckSession`

2020-03-24 21:27 UTC, mcous commented on app/src/calibration/actions.js
> +  error: {},
Should be `RobotApiErrorResponse`

2020-03-24 21:27 UTC, mcous commented on app/src/calibration/actions.js
> +  error: {},
Should be `RobotApiErrorResponse`

2020-03-24 21:27 UTC, mcous commented on app/src/calibration/types.js
> +import {
`import typeof {` makes these easier to work with

2020-03-24 21:27 UTC, mcous commented on app/src/components/CheckDeck/index.js
> +  log.info('deck check session data: ', deckCheckSessionData || {})
Info seems too high a priority log for this, could it be `debug`?

2020-03-24 21:27 UTC, mcous commented on app/src/components/CheckDeck/index.js
> +const log = createLogger(__filename)
Pretty sure we have a `useLogger` in the app for logging from components

2020-03-24 21:27 UTC, mcous commented on app/src/components/CheckDeck/index.js
> +    dispatch(push(parentUrl))
I would avoid using a `push` action to change routes since it tends to leak routing concerns way down components instead pass a `exit` (or whatever) function in via props that uses `routeProps.history.push`.

This comment doesn't matter if we can avoid using routes for this wizard

2020-03-24 21:55 UTC, b-cooper commented on app/src/components/CheckDeck/index.js
> +  log.info('deck check session data: ', deckCheckSessionData || {})
This is log call is temporary and only acting as a placeholder for the work that will immediately follow to parse `deckCheckSessionData` in this component and conditionally render steps of the wizard.

2020-03-30 23:09 UTC, mcous requested changes
A collection of thoughts and actual change requests. The functionality looks mostly good! My one change request for functionality is:

- We need to put `key={robotName}` at a top level place to ensure we unmount components when the robot changes (see GIF below)

And then for code but not behavior change requests:

- `app/src/calibration/index.js` shouldn't export the reducer
- `RobotApiResponseMeta` is incorrectly spread into calibration action metas when it's already in `RobotApiRequestMeta.response`
- `RobotApiResponseMeta` shouldn't be wrapped in `$Shape`

Some thoughts on the epics that aren't change requests. Was just looking at the code and thought this might be worth exploring.

- I wonder if putting the 409 (for create) and recreate (for delete) logic in `mapResponseToAction` is doable / would simplify things?
    - i.e. don't trigger on multiple actions, but instead:
        - If create 409s, issue a delete trigger on response rather than a create failure
        - If delete for recreate succeeds (which was kind of an internal delete anyway), issue a create trigger instead of a delete success
    - It would certainly make the tests more simple

Everything else is just cleanup thoughts + stuff we'd already talked about for future PRs

2020-03-30 23:09 UTC, mcous commented on app/src/calibration/epic/createRobotCalibrationCheckSessionEpic.js
> +const mapActionToRequest: ActionToRequestMapper<CreateRobotCalibrationCheckSessionAction> = action => ({
For future reference: the `mapActionToRequest` function is passed `state`, so it could be used to issue a GET request if the session already exists in state. That way we wouldn't have to create a whole new epic once fetch is a thing

2020-03-31 16:48 UTC, b-cooper commented on app/src/calibration/__tests__/epic.test.js
> +    mockGetRobotByName.mockReturnValue(mockRobot)
I'll opt to use these helpers in the next PR. Thanks for the tip

2020-03-31 17:42 UTC, mcous approved these changes
Code changes look great and behavior is as expected. Any of these comments that seem good to follow up on can go in a future PR

2020-03-31 17:42 UTC, mcous commented on app/src/calibration/__fixtures__/index.js
> +  successStatus: 200,
Nitpick, but should this be a 201?

2020-03-31 17:42 UTC, mcous commented on app/src/calibration/api-types.js
> +  | 'sessionStart'
These strings should live in `constants` at some point

2020-03-31 17:42 UTC, mcous commented on app/src/calibration/types.js
> +  payload: $Shape<{| robotName: string, recreate: boolean |}>,
Does this need to be a `$Shape`? This addition to the [Flow docs](https://flow.org/en/docs/types/utilities/#toc-shape) has been freaking me out about $Shape:

> Note: $Shape<T> is not equivalent to T with all its fields marked as optional. In particular, Flow unsoundly allows $Shape<T> to be used as a T in several contexts. For example in
>
>     const personShape: PersonDetails = {age: 28};
>     (personShape: Person);
>
> Flow will unsoundly allow this last cast to succeed. If this behavior is not wanted, then this utility type should be avoided.

2020-03-31 17:42 UTC, mcous commented on app/src/components/RobotSettings/index.js
> +    <CardContainer key={robot.name}>
👍

2020-03-31 17:42 UTC, mcous commented on app/src/components/CheckCalibration/CompleteConfirmation.js
> +    dispatch(completeRobotCalibrationCheck(robotName))
Can be addressed in a future PR: given the instructions in the button are "Drop tip and exit", I think it makes sense to delay dismissing the calibration state until the drop tip is actually initiated.

In that case, it might make sense to move this dispatch into the `exit` passed down by the parent

2020-03-31 17:42 UTC, mcous commented on app/src/components/RobotSettings/ControlsCard.js
> +  const [isCheckingRobotCal, setIsCheckingRobotCal] = React.useState(false)
Can be addressed in a future PR: I think the initial value of this state should be driven by the presence of an existing check session for this robot in state

2020-03-31 17:54 UTC, b-cooper commented on app/src/components/CheckCalibration/CompleteConfirmation.js
> +    dispatch(completeRobotCalibrationCheck(robotName))
I will address it in an upcoming PR as the flow starts to lay out. The 'complete' action should actually only be triggered when you have "successfully passed the robot calibration check", so tying it in with exit isn't the desired behavior, but it may well make sense to throw it in the button's onclick before the exit occurs.  All this to say, there should probably be a loading state of some sort while the robot is dropping tip, before the modal is closed, so I'll check with design about adding that in as we go forward.

2020-03-31 18:29 UTC, merged