feat(api): Add labware required to session status
OpenTrons/opentrons-api pull request #5298
Opened 2020-03-26 19:50 UTC by Laura-Danielle

## overview

Closes #5095. This PR adds a labware sub-status to the overall session status.

## changelog

- Add a LabwareStatus model which includes the load name, tiprack uuid and other identifying factors.
- Add in tools to build the labware dict based on a pipette's max volume.
- Add in a method to build labware objects (note this method will not be used until the next PR dealing with implementations of `move_to/pick_up_tip`) 

## review requests
- Does code make sense?
- Should anything else be added to the status?

## risk assessment

- Ensuring that the session program still works as expected.

2020-03-26 20:00 UTC, sfoster1 requested changes
It makes sense to me and I see the goal of keeping the model separate from the internal data structures, but here we should probably make the internal datastructures dataclasses or something - IMO dicts with specific keys isn't a good choice.

2020-03-26 20:00 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/models.py
> +    tiprackID: UUID4
this probably should be just a general id, not necessarily tiprackId right? or the model should be called TiprackStatus

2020-03-26 20:11 UTC, Laura-Danielle commented on api/src/opentrons/server/endpoints/calibration/models.py
> +    tiprackID: UUID4
Was the ticket referring the the hash of the particular tiprack loaded in? I guess I got confused by [ticket](https://app.zenhub.com/workspaces/opentrons-hmg-5e1cdf98e04060788ad94e32/issues/opentrons/opentrons/5095) wording.

Do we want to have a tiprack uuid in the pipette dict, and then key the labware dict by the tiprack uuid for easier look-up?

2020-03-27 15:57 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/models.py
> +    tiprackID: UUID4
So the idea is to have a link in both directions. `forPipettes` in the labware model lets you know which pipettes the labware is associated with. and then, like you said, the `tiprackId` is actually in the _pipette_ model, and lets you know the id of the tiprack that is associated with that pipette. the `tiprackId` should contain the uuid of the particular labware.

the labware dict is keyed by the uuid of the labware, and the labware object itself should contain that uuid as well.

2020-03-30 17:18 UTC, sfoster1 approved these changes
lgtm!

2020-03-30 17:45 UTC, b-cooper approved these changes
Looks good ✌️,  just a couple of comments/questions about organization and naming.

2020-03-30 17:45 UTC, b-cooper commented on api/src/opentrons/server/endpoints/calibration/session.py
> +class LabwareDefinition:
Nit: The name of this data class is a little confusing to me. It feels weird to me to have a class called `LabwareDefinition` which includes a member which is also of `LabwareDefinition` in a different namespace.  Is there a way that the difference between them could be captured in the name?  e.g. `LabwareInSlot`?

2020-03-30 17:45 UTC, b-cooper commented on api/src/opentrons/server/endpoints/calibration/session.py
> +            return self._slot_options.pop(0)
nit: because we're mutating this private member as we fill the deck, I think it would be clearer to name it something like `_open_slot_options` or `_available_slot_options` to hammer home that it's something that is changing through iterations.

2020-03-30 17:45 UTC, b-cooper commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        self._lw_definitions: typing.Dict[UUID, LabwareDefinition] = {}
I see some redundancy here with the `_lw_definitions` and the `_labware_info` members. They both act as a sort of data store for labwares by id. If I understand the intention correctly, it looks like maybe `_lw_definitions` could be absorbed by `_deck`.  That way, when the only time we need to access def information is for loading a labware onto the deck, which we can use to access that Labware def or object after the fact.  Thoughts?

2020-03-30 17:56 UTC, Laura-Danielle commented on api/src/opentrons/server/endpoints/calibration/session.py
> +class LabwareDefinition:
Yep can do. (I'm bad at naming things)

2020-03-30 19:29 UTC, merged