docs(api): add gen2 modules
OpenTrons/opentrons-api pull request #5302
Opened 2020-03-27 14:10 UTC by ahiuchingau

## overview
This PR adds GEN2 modules to the docs and some minor fixes.
closes #4225

2020-03-27 15:15 UTC, Laura-Danielle requested changes
Just a few questions/suggestions before I approve

2020-03-27 15:15 UTC, Laura-Danielle commented on api/docs/v2/new_modules.rst
> +    GEN2 Temperature Module and GEN2 Magnetic Module are introduced in Robot Software version 3.17.0. If you are using these modules, make sure the API level of your protocol is at least 2.3 or highe
```suggestion
    GEN2 Temperature Module and GEN2 Magnetic Module are introduced in Robot Software version 3.17.0. You can determine if your module is a GEN2 model by inspecting the sides of the device for a label that specifies `GEN2`. If you are using these modules, make sure the API level of your protocol is at least 2.3 or higher.
```

2020-03-27 15:16 UTC, ahiuchingau commented on api/docs/v2/new_modules.rst
> +    - <= 50 uL: 5 minutes
Pretty sure it's total liquid, I should probably specify that

2020-03-30 16:01 UTC, sfoster1 requested changes
Couple inline changes. Also double check that the versioning page mentions gen2 modules

2020-03-30 16:01 UTC, sfoster1 commented on api/docs/v2/new_modules.rst
> +Tempearture Module
```suggestion
Temperature Module GEN2
```

2020-03-30 16:01 UTC, sfoster1 commented on api/docs/v2/new_modules.rst
> +    GEN2 Temperature Module and GEN2 Magnetic Module are introduced in Robot Software version 3.17.0. You can determine if your module is a GEN2 model by inspecting the sides of the device for a labe
Let's also stay consistent with "Temperature Module GEN2" and "Magnetic Module GEN2" rather than "GEN2 xxxxxx Module"

2020-03-30 16:01 UTC, sfoster1 commented on api/docs/v2/new_modules.rst
> +Temperature Module Gen1 would not be able to sufficiently cool itself when a Thermocycler
```suggestion
Temperature Module GEN1 would not be able to sufficiently cool itself when a Thermocycler
```

2020-03-30 16:01 UTC, sfoster1 commented on api/docs/v2/new_modules.rst
> +Recommended GEN2 Magnetic Module bead attraction time:
Magnetic Module GEN2

2020-03-30 16:01 UTC, sfoster1 commented on api/docs/v2/new_modules.rst
> +Magnetic Module
Magnetic Module GEN2

2020-03-30 16:01 UTC, sfoster1 commented on api/docs/v2/new_modules.rst
> +Compared to the older version, the GEN2 Magnetic Module uses smaller magnets. This mitigates an
Magnetic Module GEN2

2020-04-01 18:06 UTC, Laura-Danielle approved these changes
👍

2020-04-01 19:04 UTC, sfoster1 approved these changes
LGTM!

2020-04-01 19:04 UTC, merged