feat(app): guide the user through leveling gen2 multis
OpenTrons/opentrons-api pull request #5348
Opened 2020-04-01 17:08 UTC by sfoster1

This new flow added in to change pipette guides the user through making
sure their gen2 multi pipettes are level, using the extension block and
manually pulling the pipettes against it.

Closes #5344

Design reference:
new text on pre-attach screen: https://app.zeplin.io/project/5aa97729db58a2192f10d0d6/screen/5e839ed0f792546d4c858d30
leveling screen: https://app.zeplin.io/project/5aa97729db58a2192f10d0d6/screen/5e839ed07319a9140ea11305

## Status

Not done yet (doesn't have all the videos for the different pipette/mount combos - there will be one for each, so four total), but still as of now interested in feedback on
- frontend fundamentals like how the spacing is done
- doublecheck that the new webpack handler for videos is the right thing
- interesting in thoughts about how to better structure the new entry in the wizard

## Risk Assessment

Really low, this is just adding a screen to the change pipette flow and slightly modifying the text in another

2020-04-02 15:57 UTC, b-cooper commented on app/src/components/ChangePipette/LevelPipette.js
> +function ExitButton(props: Props) {
Nit: because this component is so shallow, I'd placing the instance of `PrimaryButton` directly in the `LevelPipette` component for clarity in this file. This kind of abstraction feels unnecessary. You could probably make the same argument for the `Status` component.  It's not really adding branching logic, just a haven for some variable declarations.

2020-04-14 14:50 UTC, b-cooper approved these changes
Code looks good to merge, don't have a GEN2 multi to test with unfortunately.

2020-04-16 14:50 UTC, mcous requested changes
One change request for video sizing. Otherwise this code looks pretty clean. Unable to test because I don't have a robot and left some nits because I was already commenting

2020-04-16 14:50 UTC, mcous commented on app/src/components/ChangePipette/LevelPipette.js
> +      <video width="100%" autoPlay={true} loop={true} controls={true}>
The height and width props of `<video>` only accepts [pixel values, not percentages](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-width). I definitely see various tutorials calling out `width="100%"` but I'm pretty sure it's invalid

If you want full width, I would use CSS. I would also might consider using `max-width` rather than `width`

2020-04-16 14:50 UTC, mcous commented on app/src/components/ChangePipette/styles.css
> +  margin-bottom: 50px;
Where's this pixel value coming from? If possible, I like to stick to whole or half value `rem`s (unless you're down below 1 rem, in which case a logarithmic scale is nice for consistency).

Anyway, does this have to be exactly 50 pixels, or will 3 rems work?

2020-04-16 14:50 UTC, mcous commented on app/src/components/ChangePipette/LevelPipette.js
> +      <LevelingVideo pipetteName={pipetteModelName} mount={mount} />
I think it might make sense to rename this `pipetteName` prop to avoid and sort of false implication of consistency with the other components that are using `displayName` as the value

2020-04-16 14:50 UTC, mcous commented on app/src/components/ChangePipette/styles.css
> +  max-height: 480px;
While I'm picking nits, could this be `30rem`?

2020-04-16 14:50 UTC, mcous commented on app/src/components/ChangePipette/LevelPipette.js
> +      Next, level the {props.pipetteName}
Since this is a new file, could copy all go at the top with an i18n TODO? It looks like you got one of the messages up there already

2020-04-16 14:59 UTC, sfoster1 commented on app/src/components/ChangePipette/styles.css
> +  margin-bottom: 50px;
mostly just tuning until it looked like the design. 3 rems is probably fine

2020-04-16 15:00 UTC, sfoster1 commented on app/src/components/ChangePipette/styles.css
> +  max-height: 480px;
👍

2020-04-16 15:00 UTC, sfoster1 commented on app/src/components/ChangePipette/LevelPipette.js
> +      Next, level the {props.pipetteName}
👍

2020-04-16 15:00 UTC, sfoster1 commented on app/src/components/ChangePipette/LevelPipette.js
> +      <LevelingVideo pipetteName={pipetteModelName} mount={mount} />
👍

2020-04-16 15:00 UTC, sfoster1 commented on app/src/components/ChangePipette/LevelPipette.js
> +      <video width="100%" autoPlay={true} loop={true} controls={true}>
Betrayed by google again...

2020-04-16 18:22 UTC, pantslakz approved these changes
:fire:

2020-04-16 19:31 UTC, mcous approved these changes

2020-04-20 14:38 UTC, merged