feat(api): Allow move, jog and tip handling for a cal session
OpenTrons/opentrons-api pull request #5376
Opened 2020-04-07 15:31 UTC by Laura-Danielle

## overview

Closes #5096. This PR lays the final ground work for the follow-up tickets in deck cal check. It adds functionality for pick up tip, drop tip, move.

## changelog

- Added in two more fields in an attached pipette status
- Add a parameter value for any move action which requires a saved offset
- Add in state updates to all endpoint facing methods from `CalibrationCheckSession`
- Ported the pipette info over to a dataclass
- Adds more tests in, including an incomplete integration test -- will finish once the other location PRs are done.

## review requests

Please play around with the endpoints in postman. I just need to fix-up jogging on the tiny client I made, then I will post it here.

Does state handling seem OK? Should I add in more states, or are the current states sufficient.

## risk assessment

Ensure no behavior for previously existing behavior is different.

2020-04-07 16:38 UTC, sfoster1 requested changes
Some little things, but the high points are
- there's a lot of duplication of state held by the hardware controller - maybe we should just keep around a uuid to mount mapping and query the hardware controller more
- i think we can tighten up the separation between the endpoint handlers and the actual internal logic, moving more internal logic functions to take datatypes like `Point` and having the handlers translate arguments

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/check.py
>          await hardware.cache_instruments()
these sort of hardware control things should probably move into a `session.build` or similar so they can be reused in fastapi

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/check.py
> +    session_type, session = _fetch_type_and_session(request)
this sort of boilerplate getting the session and type can be moved into a middleware so the session is presented to the handler if present and an error automatically returned otherwise

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/check.py
> +    response = _format_status(session, request.app.router)
we might also be able to put the status return in a middleware, but if we can we can probably make a `status_response(session, router) -> aiohttp.Response` helper function

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/check.py
> +        invalidate_path = f"/calibration/{session_type}/session/invalidateTip"
this could be a named route too right

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/check.py
> +                "dropTip": f"/calibration/{session_type}/session/dropTip",
same here

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/check.py
> +    if session.get_pipette(pipette).has_tip:
the handling for the session already having a tip could be pushed down to the session, with it raising a custom exception if the tip is already present and the handler catching that exception

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/check.py
> +        await session.return_tip(pipette)
same here re: checking if the session has a tip

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/models.py
> +    has_tip: Optional[bool]=\
this duplicates tracking in the hardware controller - could we just use that?

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +# from .models import AttachedPipette
commented

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +_KT = typing.TypeVar('_KT')
love it, but maybe make the typevar names a bit more descriptive here, like `MoveKey` and `MoveValue`

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +    model: typing.Optional[str]
a lot of this stuff duplicates information in `hardware_control.api.attached_pipettes`, can we just rely on that info?

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +    model: str
duplicate data from hardware control - let's rely on that if possible

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        self._pipettes = self._key_by_uuid(hardware.get_attached_instruments())
here it may make sense to map a uuid and a mount and rely on requesting information from the hardware every time rather than caching

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +            max_vol = data.max_volume
may make sense to build a more explicit alternate labware dict rather than this

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        if mount == Axis.Z:
`hardware_control.types.Axis.to_mount`

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +    async def _jog(self, pipette: UUID, vector: Point):
if we switch to storing a mapping of uuid to mount, this could take the mount and be a little simpler

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +            tip_length = self._deck[lw_info.slot].tip_length  # type: ignore
i think this is an acceptable way to handle it, doesn't need a todo

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +    def get_tiprack(self, uuid: UUID):
return type annotation

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        update_dict = getattr(self._moves, 'moveToTipRack')
why use getattr here? we assume it succeeded and returned a dict below on line 305

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        assert curr_state == 'invalidateTip',\
these assertion errors should probably be explicitly handled in the http handlers - they actually represent bad requests, or possible `Precondition Failed`, since it's the client breaking the sequence enforced by the server. They shouldn't be 500s.

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        get_position = getattr(self._moves, 'moveToTipRack')
why use getattr here when we assume it worked on the next line?

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        get_position = getattr(self._moves, next_state)
same thing with getattr. also we probably want a more-fully-defined return type - could save it somewhere so we don't have to type it out every time

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +                new_dict[id.hex] = {"offset": offset, "locationId": loc.hex}
this probably wants to map the uuids to the values directly; it's for the presentation layer to stringify it - consider that we'll do this with a custom encoder in fastapi

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +    async def jog(self, pipette: UUID, vector: typing.List):
could probably be more specific with the vector type. also this could take a `Point`, and the endpoitn could be responsible for creating that type (again, this would be a custom deserializer in fastapi)

2020-04-07 16:38 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/util.py
> +        move_state = self._move_relationship.get(state)
[nitpick] `return bool(self._move_relationship.get(state))`?

2020-04-07 20:22 UTC, Laura-Danielle commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        assert curr_state == 'invalidateTip',\
@sfoster1 Does it make sense to handle that in [this ticket](https://app.zenhub.com/workspaces/opentrons-hmg-5e1cdf98e04060788ad94e32/issues/opentrons/opentrons/5255)?

2020-04-09 20:31 UTC, Laura-Danielle commented
Closing in favor of creating a new PR to make it easier for code review.

2020-04-09 20:31 UTC, closed without merging