feat(api): Allow moves to crosses and slot 5
OpenTrons/opentrons-api pull request #5415
Opened 2020-04-13 04:15 UTC by Laura-Danielle

## overview

Closes #5099 and closes #5098. This PR enables the calibration session to move to all three crosses on the deck (1,3,7) and the left of slot 5 to check the height.

## changelog

- Add a method in `geometry.py` to grab the cross information from the ot deck json definition. 
-  Move the `_moves` attribute to the top level session -- since deck calibration session will also be using these points
-  Add in a different move input that is in the shape of `{'location': {'locationId', 'position'}, 'pipetteId'}`. Now, move takes in two different input shapes depending on the state.
- Expand on the integration test to check an entire deck check flow with two pipettes (*note* this test will be changed once the session has control over the active pipette again.)

## review requests

The state machine needs a little more work I think -- it's gross having to check whether the `moveToTiprack` state is active or not to prevent the state from moving forward when returning tip to the tiprack.

## risk assessment

This only adds onto the deck calibration check project. Some things were moved around to acc

2020-04-13 16:44 UTC, b-cooper approved these changes

2020-04-13 16:44 UTC, b-cooper commented on api/src/opentrons/protocol_api/geometry.py
> +        positions = list(filter(lambda pos: 'C' in pos['id'],
Just because this filtering is a little cryptic, can we name the variable `cross_positions` and/or throw a comment on here to explain that 'C' is for 'cross'?

2020-04-13 16:44 UTC, b-cooper commented on api/src/opentrons/protocol_api/geometry.py
> +                             f'valid deck slots are: {pos_ids}')
this will print "position 2 could not be found, valid deck slots are: ['1BLC', '3BRC',...]". If you change the list comprehension above to only grab the first character (`pos['id'][0]`) of each id, it will actually correspond to deck slots.

2020-04-13 16:44 UTC, b-cooper commented on api/src/opentrons/server/endpoints/calibration/session.py
> +    def _build_cross_dict(self, slot: str) -> typing.Dict:
Just a thought, this function could take a deck location id (e.g. '1BLC') instead of a slot. That way we could avoid having to parse the id string in `get_calibration_position` at all.

2020-04-13 16:44 UTC, b-cooper commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        if not if_return:
I think if the logic for `moveToTiprack` needs to be reused for another step in the state machine that has different before and after links, it's asking for a separate state string that gets handled almost the same, but differently.  For example having a `moveToTiprack` state that represents the initial pipette nozzle movement to the full tiprack, and a `returnToTiprack` state that represents the pipette with tip returning to the tiprack location it removed it's tip from. Under the hood, the should call the same functions to get the gantry to that spot, but from the state machine's perspective, they are different steps with different implications.

2020-04-13 18:47 UTC, sfoster1 requested changes

2020-04-13 18:47 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +    def _build_cross_dict(self, slot: str) -> typing.Dict:
that's a good idea.

2020-04-13 18:47 UTC, sfoster1 commented on api/src/opentrons/protocol_api/geometry.py
> +            (pos for pos in positions if pos['id'].startswith(pos_name)),
this is pretty fragile, both because it relies on proper ordering within slots and because it relies on lexical sorting of numerical strings, e.g. checking a string that could be "10" for the prefix "1". I think we should take the full IDs as inputs.

2020-04-13 18:51 UTC, b-cooper commented on api/src/opentrons/protocol_api/geometry.py
> +            (pos for pos in positions if pos['id'].startswith(pos_name)),
I'll go ahead and make these changes to the PR and update it.

2020-04-14 14:41 UTC, sfoster1 approved these changes
LGtM!

2020-04-14 14:41 UTC, merged