Pd refactor edit modules
OpenTrons/opentrons-api pull request #5445
Opened 2020-04-17 20:49 UTC by shlokamin

## overview

Draft. Closes #5366
## changelog

## review requests

## risk assessment

2020-04-20 02:42 UTC, shlokamin commented on protocol-designer/src/components/modals/EditModulesModal/__tests__/form-state.test.js
> +// TODO(mc, 2020-03-13): DANGER: mocking Formik hooks here is code smell,
copied this over from `app/src/components/RobotSettings/SelectNetwork/ConnectModal/__tests__/form-state.test.js`. When formik v3 comes out we should stop mocking the Formik hooks.

2020-04-20 16:04 UTC, Kadee80 reviewed
So far, edit module modal seems to perform as expected, however regardless of Disable Module Restrictions FF and GEN1 mag/temp on deck - I'm not seeing the No 8-Channel Access warnings on the deckmap.

2020-04-20 16:11 UTC, shlokamin commented
@Kadee80 hmm that is weird I am not able to reproduce... you're using gen 1 multi channel pipettes with gen 1 modules right?

2020-04-20 16:12 UTC, Kadee80 commented
@shlokamin I am an idiot, i had Gen2 pipettes selected. Please disregard my previous comment.

2020-04-20 16:19 UTC, shlokamin commented
lol don't sweat it, so many different configurations to parse through

2020-04-20 18:47 UTC, Kadee80 approved these changes
🥠 
- [x] Edit module modal functionality looks gtg!

2020-04-20 21:01 UTC, shlokamin commented on protocol-designer/fixtures/state/deck.js
> +import fixture_96_plate from '@opentrons/shared-data/labware/fixtures/2/fixture_96_plate'
ya I'm using this as a deck setup fixture in `protocol-designer/src/components/modals/EditModulesModal/__tests__/EditModulesModal.test.js`

2020-04-20 22:32 UTC, IanLondon approved these changes
looks good, phew

2020-04-20 22:32 UTC, IanLondon commented on protocol-designer/src/components/modals/EditModulesModal/index.js
> +      .required('This field is required'),
i18n here?

2020-04-20 22:34 UTC, IanLondon commented on protocol-designer/fixtures/state/deck.js
> +import fixture_96_plate from '@opentrons/shared-data/labware/fixtures/2/fixture_96_plate'
cool thanks I missed that. We should make a note to reuse these elsewhere. Do you think we could convert these `export const Foo = {...stuff here...}` to `export const createFoo = () => ({...stuff here...})` to protect against accidental mutation?

2020-04-23 20:57 UTC, mcous requested changes
Sorry for the very long delay on this review; this week has not been my week. But this looks great! These are relatively minor change requests, but I think they're important enough to request

- There's a bunch of object type definitions that need to be exact objects or explicitely set to inexact with a `...`, e.g. `{| exact: true |}` vs `{ explicitelyInexact: true, ... } `
    - We have a flow lint currently set to warning about this, so if you enable flow warnings you should see these in your editor
- I think we might be missing some FilePage tests? It's possible I just missed them
- I think we should avoid mocking action creators, see comments below

2020-04-23 20:57 UTC, mcous commented on protocol-designer/src/components/__tests__/EditModules.test.js
> +jest.mock('../portals/MainPageModalPortal.js')
In the app we moved our Portal mocking to be automatic via `scripts/setup-global-mocks.js` and `app/src/components/portal/__mocks__/index.js`. Def might be nice for PD, too

2020-04-23 20:57 UTC, mcous commented on protocol-designer/src/components/__tests__/EditModules.test.js
> +    mockPortal.mockReturnValue(<div>mock portal</div>)
This strikes me as a little unsafe (in the general case, not necessarily here specifically). In the app our mock portal is a fragment that blindly renders children whereas this would prevent any portal children from rendereing

2020-04-23 20:57 UTC, mcous commented on protocol-designer/src/components/__tests__/EditModules.test.js
> +      <Provider store={mockStore}>
`mount` takes `wrappingComponent` and `wrappingComponentProps` options. This mount certainly isn't wrong, but I've been tending to prefer...

```js
const render = () => {
  return mount(<MyComponent />, {
    wrappingComponent: Provider,
    wrappingComponentProps: { store: mockStore },
  })
}
```

...to communicate intent about what the component under test truly is. Also, if enzyme is ever able to fix its problems with shallow rendering and `useContext`, I think this is the format we'll have to use if we want to shallow render our connected components

2020-04-23 20:57 UTC, mcous commented on protocol-designer/src/components/__tests__/FilePage.test.js
> +  })
Are we missing test cases here? Should there be tests to make sure EditModules renders when it's supposed to? Forgive me if this is present in another test file and I've just missed it

2020-04-23 20:57 UTC, mcous commented on protocol-designer/src/components/EditModules.js
> +type EditModulesProps = {
Should be exact object

2020-04-23 20:57 UTC, mcous commented on protocol-designer/src/components/EditModules.js
> +  moduleToEdit: {
Should be exact object

2020-04-23 20:57 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/ConnectedSlotMap.js
> +type ConnectedSlotMapProps = {
Should be exact object

2020-04-23 20:57 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/ModelDropdown.js
> +type ModelDropdownProps = {
Should be exact object

2020-04-23 20:57 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/SlotDropdown.js
> +type ModelDropdownProps = {
Should be exact object

2020-04-23 20:57 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/__tests__/EditModulesModal.test.js
> +      expect(createModuleMock).toHaveBeenCalledWith(expectedParams)
Mocking pure action creators feels a little like code smell to me, and this test as written doesn't actually test that the action has been dispatched. I think something like this would be a better test:

```js
// with stepFormActions.createModule unmocked
expect(mockStore.dispatch).toHaveBeenCalledWith(
  createModuleMock(expectedParams)
)
```

2020-04-23 20:57 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/index.js
> +type EditModulesModalProps = {
Should be exact object

2020-04-23 20:57 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/index.js
> +type DeckInfo = {
Exact object

2020-04-23 20:57 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/index.js
> +type ModuleInfo = {
Exact object

2020-04-23 20:57 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/__tests__/EditModulesModal.test.js
> +jest.mock('../../../../step-forms/actions')
Related to other comment about mocking action creators. This mock looks like it wasn't added by this PR, but mocking action creators is a bad idea IMO so it would be great if this PR could remove this mock

2020-04-27 20:19 UTC, shlokamin commented on protocol-designer/src/components/__tests__/EditModules.test.js
> +jest.mock('../portals/MainPageModalPortal.js')
this is a great idea, i'm gonna make a ticket to address this as part of other global mocking things too.

2020-04-27 20:24 UTC, shlokamin commented on protocol-designer/src/components/__tests__/EditModules.test.js
> +      <Provider store={mockStore}>
i had no idea about this... this is very cool

2020-04-27 21:15 UTC, shlokamin commented on protocol-designer/src/components/__tests__/FilePage.test.js
> +  })
Yes there should be, thank you! forgot to come back to this

2020-04-28 14:21 UTC, shlokamin commented on protocol-designer/src/components/modals/EditModulesModal/__tests__/EditModulesModal.test.js
> +      expect(createModuleMock).toHaveBeenCalledWith(expectedParams)
Fair! My thought was "what that action creator does is not my concern so I'll just make sure it's called with the right stuff. However, you're right, it's pure, so there isn't any need to do that.

2020-04-28 14:58 UTC, shlokamin commented on protocol-designer/src/components/__tests__/EditModules.test.js
> +jest.mock('../portals/MainPageModalPortal.js')
I went ahead and added main page portal mocking to `scripts/setup-global-mocks.js`

2020-04-28 17:41 UTC, mcous reviewed
Currently discussing these items with you in Slack, but posting here so we don't lose track

2020-04-28 17:41 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/ModelDropdown.js
> +      error={meta.error}
Not sure if this is important, but IIRC this could cause an error to be displayed for this field before the field has been marked touched by an onBlur

2020-04-28 17:41 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/index.js
> +                          error={slotError}
Why is `slotError` done outside of form validation? It seems like if there's a slot error then the form should not be allowed to be submitted

2020-04-28 17:41 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/index.js
> +              disabled={slotIssue}
Same comment. If there's an issue that prevents submit, that feels like it should go in form validation. Formik exposes an `isValid` boolean on the form context for disabling the submit button

2020-04-28 17:41 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/index.js
> +                <HoverTooltip
[No change requested because not introduced by this PR] Could use the `useHoverTooltip` hook to remove a layer of render-prop-as-children nesting

2020-04-28 17:41 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/index.js
> +      validationSchema={validationSchema}
It doesn't look like a validation schema on its own is enough to validate this form. It looks like we should be passing in our own custom validation function that does the schema check _and_ checks the various value conditions we have that are currently a little deep in the component structure

2020-04-29 22:45 UTC, shlokamin commented on protocol-designer/src/components/modals/EditModulesModal/index.js
> +                          error={slotError}
As per our slack discussion I created a custom validator fn which all of this is done under. Thanks for the suggestion, this really cleans things up a bit!

2020-04-29 22:45 UTC, shlokamin commented on protocol-designer/src/components/modals/EditModulesModal/index.js
> +                <HoverTooltip
@Kadee80 is gonna do this in a follow up PR

2020-04-30 03:37 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/__tests__/ModelDropdown.test.js
> +    jest.clearAllMocks()
Can this be `resetAllMocks`?

2020-04-30 03:37 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/__tests__/SlotDropdown.test.js
> +  it('should render a DropdownField with the appropriate props', () => {
Not a problem right now because there's only one test in this suite, but we're missing an `afterEach` with `resetAllMocks`

2020-04-30 03:37 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/__tests__/form-state.test.js
> +    jest.clearAllMocks()
Redundant call to `clearAllMocks`; [reset also clears](https://jestjs.io/docs/en/mock-function-api#mockfnmockreset)

2020-04-30 03:37 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/__tests__/form-state.test.js
> +      wrapper.setProps({})
According to the [enzyme README](https://github.com/enzymejs/enzyme#reacttestutilsact-wrap), `setProps` may not have to be wrapped in `act`. That being said, the README also says `invoke` doesn't need to be wrapped but I've always found I need to wrap it...

2020-04-30 03:37 UTC, mcous commented on protocol-designer/src/components/__tests__/FilePage.test.js
> +      .prop('openEditModuleModal')()
Should this (and below) be an `invoke`?

2020-04-30 03:37 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/index.js
> +        selectedSlot: `Slot ${initialValues.selectedSlot} is occupied by another module or by labware incompatible with this module. Remove module or labware from the slot in order to continue.`,
Instead of duplicating this, why not run `initialValues` through the validator? (I think you can also set Formik's `validateOnMount` prop to true to do the same thing)

It looks like you're trying to make sure that an error doesn't show up off the bat on `selectedModel`, and if that's the case, I don't think we want to do that, because:

- We need the "field required" error in the `errors.selectedModel` if it's missing at the beginning to disable submit
- Even if `errors.selectedModel` is present, the `touched` logic in `ModelDropdown` will prevent the error from being shown to the user until they blur the dropdown

2020-04-30 03:37 UTC, mcous commented on protocol-designer/src/components/modals/EditModulesModal/ConnectedSlotMap.js
> +  const [field] = useField(fieldName)
Why are we passing in an `isError` prop instead of checking for the presence of a field error from `useField`?

If I'm reading things right it looks like there are two errors available for this field:

- Value missing
- Slot occupied

`isError` is set if the field error is "slot occupied", but if the value is missing, `SlotMap` will never render leaving `isError=false` unused, making the check for a specific type of error redundant

2020-04-30 14:43 UTC, shlokamin commented on protocol-designer/src/components/modals/EditModulesModal/__tests__/SlotDropdown.test.js
> +  it('should render a DropdownField with the appropriate props', () => {
good call

2020-04-30 14:44 UTC, shlokamin commented on protocol-designer/src/components/__tests__/FilePage.test.js
> +      .prop('openEditModuleModal')()
huh i guess i need to read enzyme docs more thoroughly, did not know about `invoke`, this is good knowledge to have lol

2020-04-30 14:51 UTC, shlokamin commented on protocol-designer/src/components/__tests__/FilePage.test.js
> +      .prop('openEditModuleModal')()
this is cool: 

> React 16.8+, .invoke will wrap your handler with ReactTestUtils.act and call .update() automatically.

2020-04-30 15:17 UTC, shlokamin commented on protocol-designer/src/components/modals/EditModulesModal/ConnectedSlotMap.js
> +  const [field] = useField(fieldName)
Good point, if `SlotMap` never renders if the value is missing, checking for a specific error is not needed. The only reason I could think to keep the error check is if the conditional rendering logic changes. In that way we are clearly still only showing the error if there is a slot issue. However, even if that happens, it is all isolated inside of this component anyways.

2020-04-30 16:20 UTC, mcous approved these changes
Noted a couple little things in Slack, but I'm really happy with this. Thanks for dealing with all the review requests!

2020-04-30 18:22 UTC, IanLondon approved these changes
Awesome! Thank you @shlokamin for taking the time to carefully refine this and thanks @mcous for the feedback!

2020-04-30 18:34 UTC, merged