refactor(api): Remove diagonal movement from touch tip
OpenTrons/opentrons-api pull request #5470
Opened 2020-04-22 20:43 UTC by Laura-Danielle

## overview

Closes #5451. This PR adds in an extra move to touch tip which first moves to the center before switching directions the pipette is moving in.

## changelog

- Change the edge list for touch tip to have an extra move to the center
- Add an extra test to verify this change only exists in API v2.4

## review requests

Check that the diagonal behavior when moving from left/right -> top/bottom is removed in api version 2.4.

## risk assessment

Low, just ensure that the behavior changes between version 2.3 and 2.4.

2020-04-22 20:50 UTC, sfoster1 requested changes

2020-04-22 20:50 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +    def _build_edges(
can we pop this over to a utils module and make it a pure function both for testability and to get it out of this exceedingly large file

2020-04-22 20:50 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +                where.center().point + offset_pt,
i think this needs to be `where._from_center_cartesian(z=1)`?

2020-04-23 13:57 UTC, sfoster1 approved these changes
Code LGTM, tested on my robot

2020-04-23 18:17 UTC, nusrat813 approved these changes
Tested - working as intended

2020-04-24 02:51 UTC, merged