refactor(api): Avoid collisions with modules during touch tip
OpenTrons/opentrons-api pull request #5485
Opened 2020-04-24 17:57 UTC by Laura-Danielle

## overview

Closes #5448. This PR adds in touch tip collision avoidance with modules/physical end of the robot. This feature is only available in api version 2.4 and above. Touch tip behavior should remain the same for API versions below 2.3.

## changelog
- add in a function in the `Deck` class that looks up whether a module exists in a given slot based on the pipette mount you are using
- Add in a second function in `protocol_api.util.py` which modifies the edge list depending on parameters listed in 
- Make the edge list a dataclass to clean-up the code #5448

## review requests
Pls test on a robot.

## risk assessment
Risk is, again, low to medium. Check that old touch tip behavior remains the same in 2.3 and below. Then, check that the following is true:

- [ ] Touching tip with a left pipette in the last column of slots 3, 6, 9 results in top/left/bottom pattern
- [ ] Touching tip with a left pipette in the last column of a plate with a temp/mag mod in the slot next to it (i.e. labware in slot 2, module in slot 3) results in top/left/bottom
- [ ] Touching tip with a right pipette in the first column of a plate with a temp/mag mod in the slot next to it (i.e. labware in slot 2, module in slot 1) results in top/right/bottom pattern
- [ ] Touching tip anywhere else with either pipette results in normal left/right/top/bottom pattern

2020-04-24 18:17 UTC, sfoster1 requested changes
Inline touch up comments

2020-04-24 18:17 UTC, sfoster1 commented on api/src/opentrons/protocol_api/geometry.py
> +    def check_labware_next_to_module(
kind of a nitpick, but this name doesn't quite fit - it's more like `is_edge_move_unsafe` or something. It checks more than just if a labware is next to a module.

2020-04-24 18:17 UTC, sfoster1 commented on api/src/opentrons/protocol_api/geometry.py
> +        Check if slot next to target labware contains a slot. Only relevant
```suggestion
        Check if slot next to target labware contains a module. Only relevant
```

2020-04-24 18:17 UTC, sfoster1 commented on api/src/opentrons/protocol_api/geometry.py
> +            if target.parent in deck_set:
we can probably invert some of this logic and make it more procedural and cut down on the levels of indentation here. For instance, 
1. find the applicable deck set and save it to an intermediate (and bail if there isn't one, e.g. the parent is a module)
2. find the neighboring slot from the deck set (and bail if it's off the edge)
3. check if that slot has a module

Don't need as much structure and a bit easier to read

2020-04-24 18:17 UTC, sfoster1 commented on api/src/opentrons/protocol_api/geometry.py
> +            ['1', '2', '3'], ['4', '5', '6'],
this sort of thing might be a bit cleaner using accessor methods on the deck, something like

```
def right_of(self, slot: str) -> Optional[str]:
   "Find the slot to the immediate right of the passed-in slot (None if on the left edge)
```

that's also a bit friendlier to refactors, independent testing, and derivation from the deck defs eventually

2020-04-24 18:17 UTC, sfoster1 commented on api/src/opentrons/protocol_api/geometry.py
> +                if other_labware:
fyi 320-324 can just be `return isinstance(other_labware, ModuleGeometry)` since `isinstance(None, ModuleGeometry)` should be `False`

2020-04-24 18:17 UTC, sfoster1 commented on api/src/opentrons/protocol_api/util.py
> +class EdgeList:
love it

2020-04-24 18:17 UTC, sfoster1 commented on api/src/opentrons/protocol_api/util.py
> +        return list(filter(None, astuple(edge_list)))
I do like the use of `filter` but the `None` as predicate is a bit weird - it might be clearer to use the construct `[edge for edge in astuple(edge_list) if edge]` here

2020-04-24 18:17 UTC, sfoster1 commented on api/src/opentrons/protocol_api/util.py
> +    if where.parent.parent in ['3', '6', '9'] and left_pip_criteria:
could use `geometry.first_parent` here

2020-04-24 19:26 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/util.py
> +    if where.parent.parent in ['3', '6', '9'] and left_pip_criteria:
I get a circular import error when I try to import stuff from geometry. I modified this to be `labware.parent` instead.

2020-04-24 19:57 UTC, sfoster1 requested changes
Couple more fixups in geometry

2020-04-24 19:57 UTC, sfoster1 commented on api/src/opentrons/protocol_api/geometry.py
> +            other_labware = self.left_of(target.parent)
what happens if this is called on a labware? might want to use `first_parent` _here_

2020-04-24 19:57 UTC, sfoster1 commented on api/src/opentrons/protocol_api/geometry.py
> +            idx = int(slot) + 1
this is where we need that treatment of deck rows. This would return slot 4 if called on slot 3, which we don't want.

2020-04-27 13:48 UTC, sfoster1 commented on api/tests/opentrons/protocol_api/test_geometry.py
> +def test_labware_in_next_slow():
slow? slot? row? both?

2020-04-27 13:49 UTC, sfoster1 commented on api/src/opentrons/protocol_api/geometry.py
> +ROW_LENGTH = 3
Let's put it on the wish list for deck definition future changes i suppose

2020-04-27 13:49 UTC, sfoster1 approved these changes
Code looks good pending QA approval

2020-04-28 14:06 UTC, nusrat813 approved these changes
Tested - working as intended

2020-04-28 14:08 UTC, merged