feat(protocol-designer): add custom tiprack on protocol creation
OpenTrons/opentrons-api pull request #5489
Opened 2020-04-27 15:34 UTC by shlokamin

## overview

This PR closes #4736 by enabling the custom tiprack upload button in the protocol creation modal.

## changelog

  - Curried createCustomLabwareDef action to handle both full labware def upload as well as only tiprack upload 
  - Enabled custom tiprack upload button in file creation modal
  - Pulled in custom labware info in labware selection modal in deck map

## review requests
When Enable Custom Tipracks FF is off:
   - You should not be able to see the `Upload Custom Tip Rack` button in the protocol creation modal

When Enable Custom Tipracks FF is on: 
  - `Upload Custom Tip Rack` button should be visible in protocol creation modal
  - If uploading a file that is NOT JSON, should see `Incompatible file type` warning modal
  - If uploading a file that is JSON but NOT valid tiprack, should see `Must be tiprack` warning modal @howisthisnamenottakenyet need your exact copy text here
  - If uploading a valid tiprack file that has already been uploaded, should see `Duplicate labware definition` warning modal
  - If uploading a file that is valid tiprack JSON file that has not already been uploaded, after the upload you should see the tiprack in both the left and right pipette tiprack dropdown fields. 
  - You should be able to select the tiprack and carry on like normal 
  - In the deck map, you should be able to select the custom tiprack in the labware selection modal under `custom labware`

Note - right now after you select the tiprack and hit save, the browser modal will prompt `Are you sure you want to create a new file? Any unsaved changes will be discarded.` As this is default behavior whenever a user uploads something. @howisthisnamenottakenyet is this desired?

## risk assessment

Low? This should probably be tested on the robot though since we have no way of knowing that this really works.

2020-04-27 15:44 UTC, shlokamin commented on protocol-designer/src/components/modals/FilePipettesModal/PipetteFields.js
> +
@IanLondon I'm pulling all labware defs here rather than pulling in only latest defs. I don't see this as an issue but want to double check. It just seemed simpler this way since `getLabwareDefsByURI` grabs both custom and standard labware.

2020-04-27 16:14 UTC, shlokamin commented on protocol-designer/src/components/modals/FilePipettesModal/PipetteFields.js
> +            <input
Oop need to do `i18n` here

2020-04-27 17:19 UTC, shlokamin commented on protocol-designer/src/components/modals/FilePipettesModal/PipetteFields.js
> +
thought — if we want to separate it out and have custom tipracks show up first we could grab latest standard defs from `getOnlyLatestDefs` and custom defs from `getCustomLabwareDefsByURI` and merge them separately

2020-04-27 17:23 UTC, Kadee80 approved these changes
🥒 
- [x] FF off shows old UI
- [x] Upload custom tiprack works in PD 
- [x] Upload custom labware still works in PD
- [x] Tested exported protocol with custom tiprack on robot with full runs and calibration etc.

2020-04-27 17:50 UTC, IanLondon requested changes
* I think it's not intended behavior that custom labware shows up under the category? Or maybe the design changed, but on last release custom labware only shows up under the "CUSTOM LABWARE" section
* In EditPipettesModal, the error modals you get when uploading non-labware/non-json/non-tipracks are hidden under the EditPipettesModal

2020-04-27 17:50 UTC, IanLondon commented on protocol-designer/src/components/modals/FilePipettesModal/PipetteFields.js
> +
I think it's good here, only reason it was formerly using `getOnlyLatestDefs` was bc custom labware wasn't relevant back then

2020-04-27 17:50 UTC, IanLondon commented on protocol-designer/src/components/modals/LabwareUploadMessageModal/LabwareUploadMessageModal.js
> +        <p>This labware definition is not a Tip Rack.</p>
i18n?

2020-05-01 17:13 UTC, shlokamin commented on protocol-designer/src/components/modals/LabwareUploadMessageModal/LabwareUploadMessageModal.js
> +        <p>This labware definition is not a Tip Rack.</p>
Ah good point. None of the messages in this file are using i18n, maybe it makes sense to make a ticket to change all of them so there's no inconsistency in the file. I'll do that now

2020-05-04 20:38 UTC, IanLondon approved these changes
:pick:

2020-05-05 15:00 UTC, merged