feat(protocol-designer): add groundwork for 5421
OpenTrons/opentrons-api pull request #5494
Opened 2020-04-27 16:32 UTC by IanLondon

## overview

This is part 1/2 for #5421, kind of a grab-bag of picks from the too-many-changes branch, `pd_cleanup-legacy-steps`

Note: I'm introducing the term "presaved step form" into PD. This means a form that has never been saved. It's temporary, closing it will delete it. It will exist visually in the step item timeline, but isn't really part of the timeline until it after is saved and becomes a real step. (But this PR only makes a not-yet-used helper fn, real hook-up in next PR).

## changelog

- turn off i18n debug-mode noise (annoying in tests, when you run Jest it spams the log)
- fix issue with labware and pipette fields being seen as non-pristine in new step forms
- make `newProtocolWithModules.spec.js` case-insensitive when selecting buttons (eg it always looks like "SAVE" b/c of CSS uppercasing, but might be "Save" or "save" in the DOM text)
- convert WellSelectionModal to functional component with hooks
- rename `generateNewForm` to `createBlankForm` (b/c once we get to the next PR, "generate" would be confusing)
- add `createPresavedStepForm` fn with tests. This should cover all functionality now in the `selectStep` thunk. In this PR it's not yet used, in the next PR it will replace the `addStep` / `selectStep` thunk flow.
- move `protocol-designer/src/step-forms/utils.js → protocol-designer/src/step-forms/utils/index.js` (this is to make other utils not in index.js possible to mock in isolation, later)

## review requests

- [ ] Nothing touched should break (sanity check) esp WellSelectionModal
- [ ] Comprehensive & correct test expectations for `createPresavedStepForm`.
- [ ] Creating a brand new form should no longer show you "this field is required" errors eg for pipette/labware fields (new fix from this PR)
- [ ] Deleting a labware that was used in a form should show you "this field is required" error for that labware field when you open up the form again (existing behavior, just check against regression)

## risk assessment

PD only, medium

2020-04-27 16:35 UTC, IanLondon commented on protocol-designer/src/steplist/fieldLevel/index.js
> +): LabwareEntity | null => {
this was causing labware + pipette fields to always appear as "dirty" even in new forms bc the fn `getDirtyFields` compares a default blank form (where these fields are null) to the current form to determine if they're dirty. These "hydrator" fns `getLabwareEntity`/`getPipetteEntity` were returning undefined, so `getDirtyFields` did `isDirty = null === undefined`, so they always appeared dirty

2020-04-27 17:35 UTC, Kadee80 approved these changes
💅 
- [x] Nothing touched should break (sanity check) esp WellSelectionModal
- [x] Comprehensive & correct test expectations for `createPresavedStepForm`.
- [x] Creating a brand new form should no longer show you "this field is required" errors eg for pipette/labware fields (new fix from this PR)
- [x] Deleting a labware that was used in a form should show you "this field is required" error for that labware field when you open up the form again (existing behavior, just check against regression)

2020-04-29 17:47 UTC, shlokamin requested changes
Good stuff @IanLondon! Left some small questions/comments. Also a few general thoughts regarding `createPresavedStepForm.js` :

(1) I think it's relatively clear what `createPresavedStepForm.js` is doing, though it is a bit imperative. This isn't necessarily a bad thing, but I do wonder if we can break this up into even more pieces of logic that clearly describe what changes are happening to `formData`, and maybe even find a way to chain them together.

(2) Sort of related to the last point, but it worries me a bit that in each `if` statement we mutate the same `formData` variable (even though it's being spread). It just feels a bit weird to keep reassigning a variable through different logic paths and return the same variable at the end. It would be nice to be able to construct an object through various pieces of logic that build upon each other. I'm loosely imagining something like: 

```
{
   ...createBlankForm(args),
   ...getLabwareEntities(args),
   ...getPipetteEntities(args),
   ...getModuleId(args)
   ...getModuleStepParams(args)
}
```

What do you think? May not even be possible given how it's set up but thought it was worth sharing the idea!

2020-04-30 22:02 UTC, IanLondon commented on protocol-designer/src/step-forms/test/createPresavedStepForm.test.js
> +      magnetAction: 'engage',
done. The `'18'` is coming from the `labwareOnMagModule.def.parameters` set up in beforeEach, but I factored it out to make it more searchable

2020-04-30 22:22 UTC, IanLondon commented on protocol-designer/src/step-forms/test/createPresavedStepForm.test.js
> +    })
The benefit of having it explicit/verbose like this is that we don't care where the values are from, rather we have this expectation that after the form is created, this is exactly what a new presaved step form should look like. Eg the weirdness with the missing fields for mix steps has been around in PD for probably a year, but I only noticed it because the fields are missing in this explicit test.

It's slightly less unit-y and more integration-y than if we made `getDefaultsForStepType`'s data totally transparent to these test expectations, but since`getDefaultsForStepType` is a somewhat internal dependency and a very simple dependency with no logic just data (it is a nested dictionary implemented as a switch-case fn) I think it's still within the "unit"?

2020-04-30 22:27 UTC, IanLondon commented on protocol-designer/src/step-forms/test/createPresavedStepForm.test.js
> +    const args = {
oof yeah this is not clear here and I'm missing a case. There should be 3 cases:
1. no previous magnet step, so make it engage
2. previous magnet step is engage, so make it disengage
3. previous magnet step is disengage, so make it engage

will update shortly

2020-04-30 22:31 UTC, IanLondon commented on protocol-designer/src/ui/modules/utils.js
> +
I'm just paranoid that because unsealed object (dictionary) access is unsafe, some consumer may forget to cast undefined to null eg the fn `f` with `f( allTheModules[id] )` might get `undefined`. So maybe the answer is to use `magnetModuleId: ?string` instead of `magnetModuleId: string | null` :( I'm not sure

2020-05-01 15:28 UTC, shlokamin commented on protocol-designer/src/ui/modules/utils.js
> +
hmm yeah this is something that I think I've seen come up a few times, and should probably be decided on as a system wide thing. I guess to me the real question is "how do we want to represent an `empty` value in our system?" 

From there we can know what to expect and have our function signatures match accordingly. And that'll make things like chaining/creating new data structures easier too.

2020-05-01 15:34 UTC, shlokamin commented on protocol-designer/src/step-forms/test/createPresavedStepForm.test.js
> +    })
Hmm, I see the case to be made for both sides. Doing it this way makes the test more verbose but I see your point about having a rigid clear expectation. And this is a step form test, so explicit inputs/outputs make sense here.

2020-05-01 17:02 UTC, shlokamin approved these changes
Looks good! I like dig the `FormUpdater` pattern 😎 Seems like `formData ` isn't being used in `_patchTemperatureModuleId` but other than that looks good to go!

2020-05-04 18:14 UTC, merged