feat(api): Allow Non-Full plate Thermocycler Configuration
OpenTrons/opentrons-api pull request #5498
Opened 2020-04-27 20:25 UTC by Laura-Danielle

## overview

Closes #5464. This PR adds in support for a "semi" thermocycler configuration which can support up to 80 samples.

## changelog

- Add in more 'bad locations' in geometry to avoid when a thermocycler is loaded onto the deck
- Add in a parameter to the `load_module` method called `configuration` that allows you to specify the non-full plate configuration (called `semi`)
- Modify the thermocycler offset when the semi configuration is specified
- Modify the wells you can access on the plate (this will get a little confusing when you access stuff by index; should we do a weird hack to fix that?)

## review requests

Please test the following listed in risk assessment using this protocol:
```
def run(ctx):
	tc = ctx.load_module('thermocycler', configuration='semi')
	tc_lw = tc.load_labware('nest_96_wellplate_100ul_pcr_full_skirt')
	tiprack = ctx.load_labware('opentrons_96_tiprack_1000ul', 1)
         pip = ctx.load_instrument('p1000_single_gen2', 'right', tip_racks=[tiprack])

	slot_11_lw = ctx.load_labware('corning_96_wellplate_360ul_flat', 11)

	pip.transfer(200, slot_11_lw['A1'], tc_lw['A4'])
```

## risk assessment

Low/Medium. We should test a few different things:
- [ ] Add in a labware to slot 8 or 11 and perform an action that will cause the robot to move either to this location or from this location to slots 1 or 4.
- [ ] Check that you cannot access columns 1 or 2 by name
- [ ] Check that you can move through columns/rows as normal on the thermocycler without collision

2020-04-27 21:28 UTC, sfoster1 requested changes
Put some inline comments in - summary is, we shouldn't use unrestricted strings, we should change where we catch errors, and we don't have to implement this for loading from v1 defs because it only is available on api levels where we load from v2.

2020-04-27 21:28 UTC, sfoster1 commented on api/src/opentrons/protocol_api/module_geometry.py
> +                'are trying to utilize thermocycler parameters only in 2.4')
doubled up text here, "are trying to" is in both lines. Also we should catch this in the `protocol_context.load_module` method and raise an exception there.

2020-04-27 21:28 UTC, sfoster1 commented on api/src/opentrons/protocol_api/module_geometry.py
> +                  configuration) -> ModuleGeometry:
Since the semithermocycler configuration is only valid in api level 2.4 and subsequent, when we use v2 defs, we don't have to implement it for v1 defs

2020-04-27 21:28 UTC, sfoster1 commented on api/src/opentrons/protocol_api/geometry.py
> +            if isinstance(i, ThermocyclerGeometry) and i.is_semi_configuration:
could we turn this into a method on ModuleGeometry called `covered_slots()` or something that could return the parent internally

2020-04-27 21:28 UTC, sfoster1 commented on api/src/opentrons/protocol_api/module_geometry.py
> +        if configuration == 'semi':
I'm pretty uncomfortable with the use of strings for the configuration here. If we want to do this, we should limit them in some way that's parameterized by the module type and enforced there. Right now, you can pass anything you want and it will behave the same unless it's "semi" (and capitalization matters!).

What I'd recommend is making the ModuleGeometry classes have enums of allowable configurations and having the loaders check if the passed configuration is in them (or none, with some default), caps-independent. 

We should also take a look at having a type stub for these functions that includes overloads.

2020-04-27 21:28 UTC, sfoster1 commented on api/src/opentrons/protocol_api/module_geometry.py
> +            offset = offset + Point(-23.28, 0, 0)
We should handle this in the class initializer or something, it's a bit gross (though I understand it's a hack - let's also drop a todo)

2020-04-28 16:40 UTC, sfoster1 requested changes
Couple more comments - sorry, these are getting a bit nitpicky, but we are adding a new public interface to the protocol API and it deserves the fine-tuning.

2020-04-28 16:40 UTC, sfoster1 commented on api/src/opentrons/protocol_api/module_geometry.py
> +        configuration: ThermocyclerConfiguration,
[nitpick] we could default this - it's only relevant if we're loading a thermocycler.

2020-04-28 16:40 UTC, sfoster1 commented on api/src/opentrons/protocol_api/module_geometry.py
> +        tc_configuration: bool = False) -> ModuleGeometry:
ok this part is a bit weird. This interface should absolutely be either
- `configuration: str = None` with an appropriate comment about how it should be the name of a configuration, and then turned into that configuration asap
- `configuration: ThermocyclerConfiguration = None`

It shouldn't be a bool because there's kind of three separate possibilities here, and it should be commented.

2020-04-28 16:40 UTC, sfoster1 commented on api/src/opentrons/protocol_api/protocol_context.py
> +            self._log.warning(
This should just straight up be a VersionError

2020-04-28 16:40 UTC, sfoster1 commented on api/src/opentrons/protocol_api/protocol_context.py
> +            semi_configuration: bool = False) -> ModuleTypes:
Kind of the same argument as `module_geometry.load_module` here. The problem with the plain string argument that was checked by value wasn't necessarily that it was ever a string, but that it really is an enum, and it should at some point be turned into one.

Keeping this argument generic at the user api level is ok - it provides forward compatibility for eventual reuse. But we do want to, as we currently do, allow it to not be specified at all and then make sure that if it _is_ specified, it's specified as one of a subset of acceptable values.

2020-04-28 19:40 UTC, sfoster1 approved these changes
Looks good to me! Really happy with it.

2020-04-28 20:24 UTC, b-cooper approved these changes
This looks great. Just a small comment about doc strings.

Also, I wanted to add a thought regarding some extra functionality we might enable in our next pass of this feature as we increase FE support.  It looks like, in addition to only missing 2 columns vs. 3 columns, the actual semi configuration is completely accessible by the pipette on the left mount.  We might be able to leverage this in the future to give users access to the whole block  while also giving them access to use slots 8 and 11.

2020-04-28 20:24 UTC, b-cooper commented on api/src/opentrons/protocol_api/module_geometry.py
>      """
There should probably be an entry in this doc string for the new configuration param, just like the one at the context level

2020-04-28 21:03 UTC, nusrat813 approved these changes
Tested - working as intended

2020-04-28 21:43 UTC, merged