refactor(app): add load labware, deck setup, tip pick up, point checks to cal check
OpenTrons/opentrons-api pull request #5499
Opened 2020-04-27 20:37 UTC by b-cooper

## overview

Add views and supporting business logic to back the robot calibration flow. Additions include:
guiding user through loading the correct tipracks on the deck, jogging and picking up a tip for the
active pipette, checking the three xy calibration points, and checking the z calibration.

This PR grew to encapsulate a fair amount of new code because of some extenuating circumstances. Apologies for the large scope, I'll do my best to summarize the changes below.

Closes #5033, Closes #5034, Closes #5036, Closes #5037

## changelog
- add robot calibration check components: `DeckSetup`, `TipPickUp`, `CheckXYPoint`, and `CheckHeight`
- add GET existing session behavior instead instead of creating a new robot cal check session by default every time. Flow is now if no existing session, try and create one. 409 conflicting for the POST should rarely if ever be hit.
- add POST update session behavior to handle all actions a user can dispatch from the newly implemented views that would update the robot cal check session. This includes: jogging, picking up tip, confirming tip is attached, claiming no tip is attached, checking all X/Y points in the flow, and checking the height at slot 5. 
- allow `mapActionToRequest` to return null which will be filtered out by the `mapToRobotApiRequest` implementation. This allows epics that use this operator to receive many action types and branch logic accordingly (some branches passing through unhandled to be filtered out)
- add some props to the `JogControls` component so that it can be reused in this flow and elsewhere. Both the step options and the mutable axes are parameterized now.

## review requests

- [ ] With feature flag on, start a robot calibration check session for a robot running edge
- [ ] it prompts you to load the correct tip racks onto your deck, given your attached pipettes
- [ ] the gantry then moves to the above A1 of the tiprack for your left pipette 
- [ ] you can then jog in all directions and step sizes to get the nozzle above the tip
- [ ] pick up the tip and confirm tip was attached
- [ ] proceed through checks at crosses on slots 1, 3 and, 7
- [ ] proceed to check deck height  at slot 5 

## risk assessment

Large footprint, but nearly all is behind a feature flag.  

There are two exceptions that do touch code that was already in place.

- the ability of the robot-api `mapActionToRequest` function to return null and get immediately filtered out. This is useful in allowing the `updateRobotCalibrationCheckSessionEpic` to handle many types input actions. This shouldn't have any effect at all to existing code, but technically touches any requests through the new robot-api rxjs operators machinery.

- the `JogControls` component that was being used in a couple places in the app, is now capable of supporting some axis and step size customization.

2020-04-29 13:46 UTC, sfoster1 requested changes
Some changes from testing:

- In the deck view, the long labware names mean that you almost can’t see the relevant part (the tip rack volume); in addition, resizing the window resizes the text rather than displaying more of it. Could we have a double row of text there?
- You can still queue up jogs by pressing really fast
- If you fail to pick up tip and press try again the pipette doesn’t move back to the tip rack
- All-capsed tip rack names display “10 ML” which I assume is the capital mu again

2020-04-29 15:54 UTC, mcous requested changes
Haven't gotten to testing on my robot yet, but the code looks pretty good! A few nitpicks here and there, but I'm liking the test coverage.

I also like the bail out behavior addition to the API request mapper, but I don't think it'll work as written, so that's my change request for now. Will test on my robot and update with my results

2020-04-29 15:54 UTC, mcous commented on app/src/components/CheckCalibration/DeckSetup.js
> +type TiprackRenderProps = { labwareDef: LabwareDefinition2, slotDef: DeckSlot }
Can this be an exact object?

2020-04-29 15:54 UTC, mcous commented on app/src/components/CheckCalibration/TipPickUp.js
> +  function jog(axis: JogAxis, direction: JogDirection, step: JogStep) {
[No change requested] A lot of these action dispatchers look common. At some point a `useCalibrationActions` (or whatever name) hook that does the `robotName` + `pipetteId` + `dispatch` binding could be cool and reduce the testing burden a little

2020-04-29 15:54 UTC, mcous commented on app/src/components/CheckCalibration/__tests__/DeckSetup.test.js
> +    MockRobotWorkSpace.mockReturnValue(null)
I've realized I can shortcut these kinds of component mocks at the mock call itself to reduce test setup boilerplate. If it works here, it would look like:

```js
jest.mock('@opentrons/components/src/deck/RobotWorkSpace', () => ({
  RobotWorkSpace: () => <></>
}))
```

Enzyme will still be able to match on RobotWorkSpace and get props passed in and such

2020-04-29 15:54 UTC, mcous commented on app/src/components/CheckCalibration/utils.js
> +const ORDERED_AXES: Array<JogAxis> = ['x', 'y', 'z']
Would this make sense as a tuple type instead of an array?

2020-04-29 15:54 UTC, mcous commented on app/src/components/JogControls/index.js
> +      .flatMap(handler => handler)
Unless I'm missing something obvious (it's before noon and I'm only one coffee in, so forgive me if I am), could we just use a `flatMap`?

```js
    const handlersForAxes: Array<KeypressHandler> = axes
      .flatMap(a => handlersByAxis[a])
```

2020-04-29 15:54 UTC, mcous commented on app/src/components/JogControls/index.js
> +          .flatMap(name => name)
Same question here: this looks like it should be one flatMap call rather than a map and an identity flatMap

2020-04-29 15:54 UTC, mcous commented on app/src/robot-api/operators.js
> +) => ?Types.RobotApiRequestOptions
Nitpick, but could we prefer explicit `null` to the Flow `?` type? Makes checks easier down the line (can use `=== null` instead of `== null` and `?Type` doesn't exist in TypeScript

2020-04-29 15:54 UTC, mcous commented on app/src/robot-api/operators.js
> +    filter(request => request != null),
I like the idea, but I don't think this is correct. Could you add a test to cover this behavior?

The `map` places the result of `mapActionToRequest` into a tuple, so `request` will never be `null`, it will be `[host, null, triggerAction]`

2020-04-29 19:16 UTC, mcous commented on app/src/calibration/epic/__tests__/fetchRobotCalibrationCheckSessionEpic.test.js
> +      testScheduler.run(({ hot, cold, expectObservable, flush }) => {
You should use the API mock helpers for these tests. It'll bring the size of this PR down.

https://github.com/Opentrons/opentrons/blob/820eb6b76b676aceaa344107f972cf2538217984/app/src/robot-api/__utils__/epic-test-mocks.js#L45

2020-04-29 19:19 UTC, mcous commented on app/src/components/CheckCalibration/DeckSetup.js
> +  'Place full tiprack(s) on the deck, in their designated slots, as illustrated below.'
Screens are wrong on this one. Should be "tip rack" (two words) rather than one word for consistency across out stack in `DECK_SETUP_PROMPT` and `DECK_SETUP_BUTTON_TEXT`

2020-04-29 22:03 UTC, b-cooper commented on app/src/components/CheckCalibration/TipPickUp.js
> +  function jog(axis: JogAxis, direction: JogDirection, step: JogStep) {
That's a good idea, and it plugs into some of the simplifications of the http interface that might consolidate the update epic logic as well.

2020-04-29 22:15 UTC, b-cooper commented on app/src/components/JogControls/index.js
> +      .flatMap(handler => handler)
Good point!

2020-04-29 22:44 UTC, b-cooper commented on app/src/calibration/epic/__tests__/fetchRobotCalibrationCheckSessionEpic.test.js
> +      testScheduler.run(({ hot, cold, expectObservable, flush }) => {
I'll do it for the 'GET' epic now, and the update after the api changes.

2020-04-29 22:59 UTC, b-cooper commented
@sfoster1 regarding your change requests:

 - "tip rack names are truncated on the deck" This has been a problem across our stack and because of the svg/html divide it's not quite simple to add another line. I totally agree this needs to be addressed, though it's a large bag of chips for this PR. I'm adding a comment and noting with design
- "You can still queue up jogs by pressing really fast". I did a quick spelunk and added a debounce, which works great, but breaks some of the epic tests. Instead of banging my head against the wall more, @mcous  and I have discussed a better way to address this UX concern that will require a couple of tweaks to the shared operators we're using across the app to communicate with the robot http api. Instead of debouncing for an arbitrary delay, this should either be handled by the domain layer not dispatching another HTTP request if one of the same type is already in flight, or this could alternatively be addressed on the robot side, by swallowing requests to jog while a jog is ongoing etc.  
- "If you fail to pick up tip and press try again the pipette doesn’t move back to the tip rack", That is a great point and I'm noting it, though that is managed by the python in this flow, so it will have to be addressed there.
- I fixed up the new instance of our old friend "capital Mu" in the tiprack names. A long term, less hacky solution, might be in the not too distant future.

2020-04-30 15:50 UTC, sfoster1 approved these changes
LGTM then!

2020-05-01 16:30 UTC, mcous approved these changes
🥮

2020-05-01 20:27 UTC, merged