feat(api, app): add state change information to rpc
OpenTrons/opentrons-api pull request #5512
Opened 2020-04-29 20:55 UTC by sfoster1

This adds an extra structure of StateInfo to the RPC session that
transmits information like the reason behind a state change to the app.

As a first pass at using it, it also displays the message from a
protocol pause in the pause alert box.

## Testing
- On a robot with this commit, make sure that if you put a `protocol_context.pause()` (or `robot.pause()` in your protocol the message shows up in the alert box
- On a robot without this commit, make sure pausing still works and shows the old reason-less result box

This is a precursor and set of new functionality for adding the rest of the window switch pausing; displaying the user pause message is just a good example of what it can do.

2020-04-30 00:07 UTC, mcous requested changes
Got some naming and type definition nits, but mostly I'd like to make sure there are unit tests in place for:

- RPC full session comes into api-client with `stateInfo` undefined (old robot)
- RPC full session comes into api-client with `stateInfo === {}` (initial state)
- RPC full session comes into api-client with `stateInfo` set with properties
- Same tests for RPC state update notification

The RPC API client is not typechecked because it's old and janky, so these unit tests are (even more) important to have in place when we make changes

2020-04-30 00:07 UTC, mcous commented on app/src/components/RunLog/styles.css
> +.pauseUserMessage {
CSS class name convention for our codebase is, (weirdly enough) snake case. Weird that the linter didn't catch this, but we may have disabled the rule or something

2020-04-30 13:04 UTC, amitlissack requested changes

2020-04-30 13:04 UTC, amitlissack commented on api/src/opentrons/api/dev_types.py
> +from typing_extensions import Literal, TypedDict
Didn't we have an issue with `typing_extensions`? I don't recall the details. But Ian had to make a code change to remove dependence on it.

2020-04-30 13:04 UTC, amitlissack commented on api/src/opentrons/api/session.py
> +            self.stateInfo.pop('estimatedDuration', None)
This line looks like it's incorrect. Is there a unit test for this function?

2020-04-30 13:27 UTC, sfoster1 commented on app/src/robot/api-client/client.js
> +      update.stateInfo = pick(apiSession.stateInfo, [
So many question marks... will do

2020-04-30 13:27 UTC, sfoster1 commented on app/src/robot/reducer/session.js
> +  stateInfo: SessionStatusInfo,
Sure

2020-04-30 13:27 UTC, sfoster1 commented on app/src/robot/types.js
> +  message: ?string,
Absolutely

2020-04-30 13:28 UTC, sfoster1 commented on api/src/opentrons/api/session.py
> +        self.stateInfo: 'StateInfo' = {}
It can be used for any state; many of the functions will only be used in pause for now, but e.g. `changedAt` and `estimatedDuration` could be used for more.

2020-04-30 13:29 UTC, sfoster1 commented on app/src/components/RunLog/styles.css
> +.pauseUserMessage {
👍

2020-04-30 13:29 UTC, sfoster1 commented on api/src/opentrons/api/dev_types.py
> +from typing_extensions import Literal, TypedDict
The issue was that it's not on the robot, so modules that include it have to not be imported on the running system - that's why we do the `dev_types` module, which is only imported when `TYPE_CHECKING`.

2020-04-30 13:30 UTC, sfoster1 commented on api/src/opentrons/api/session.py
> +            self.stateInfo.pop('estimatedDuration', None)
Not yet, wanted to get this up for comments on the js side quickly - should have been more straightforward about that

2020-04-30 18:39 UTC, sfoster1 commented on api/src/opentrons/api/session.py
> +        if user_message:
It would definitely be cleaner if I wanted to have all the keys there all the time but I kind of like the idea of removing keys and making sure they always have values if present

2020-04-30 20:06 UTC, amitlissack approved these changes

2020-04-30 20:06 UTC, amitlissack commented on api/src/opentrons/api/session.py
> +        if user_message:
Have it your way, but I'll make one last statement. Up to you. It's not that big a deal. 

So... I am not a fan of having several if / else clauses that do almost exactly the same thing. You can filter out the `None` values when creating payload below.

2020-05-04 22:57 UTC, mcous approved these changes
JS tests look good 👍

2020-05-04 22:57 UTC, mcous commented on app/src/components/RunLog/SessionAlert.js
> +  message && <div className={styles.pause_user_message}>{message}</div>
`<p>` is more appropriate for copy than a `<div>`

2020-05-05 12:45 UTC, merged