feat(protocol-designer): make steps transient until saved
OpenTrons/opentrons-api pull request #5560
Opened 2020-05-04 19:59 UTC by IanLondon

## overview

Closes #5421 

Also adds confirmation modal when navigating away from an edited step which has already been saved

## changelog

## review requests

- [ ] Creating a step and cancelling it, or deselecting it (by going to a different step, or to start/end deck state), should show a confirmation modal
- [ ] Try to break the new form / save / edit flow, including clicking away from steps and jumping from one step to another. Values should not carry across forms. Having a modal open (eg well selection modal, tip position modal, ...) and going to another form should work OK.
- [ ] The "Wait until temperature reached?" modal flow should work as before
- [ ] Auto-filled values for new forms should fill out correctly (via `createPresavedStepForm`, see `createPresavedStepForm.test.js` for expectations, this was added in the previous PR)

## risk assessment

Limited to PD, but relatively high. This changes how PD works with step forms in a significant way. However, our test coverage is pretty decent so the happy paths should be safe. But there might be weird edge cases?

2020-05-04 20:02 UTC, IanLondon commented on protocol-designer/src/components/StepEditForm/ButtonRow/index.js
> +type ButtonRowProps = {|
ButtonRow is just buttons, it was weird to have it be connected and do its own dispatches

2020-05-04 20:11 UTC, IanLondon commented on protocol-designer/src/components/StepEditForm/index.js
> +const StepEditFormManager = (props: StepEditFormManagerProps) => {
I like this separation where a wrapper does all the "hooking up" via hooks and then the component it wraps is just concerned with presentation. It's the old container-component paradigm but having hooks lets you blur those boundaries easily when in some cases you shouldn't.

Note that `StepFormManager` is then `connect`-ed to Redux with a mapStateToProps. This is needed because if we use `useState` hook instead, all the connected fields that are children on the form will pull state before the parent can unmount them, and they'll index into that state with ids that aren't valid for the state anymore because those fields aren't meant to be rendered anymore (aka zombie children problem in Redux hooks docs)

2020-05-04 20:14 UTC, IanLondon commented on protocol-designer/src/components/steplist/PresavedStepItem.js
> +export const PresavedStepItem = () => {
The presaved step isn't really in the timeline. It's more like a terminal step item than a real step item. It just indicates what step you're in the process of making.

2020-05-05 20:26 UTC, Kadee80 approved these changes
🥨 🩺 
Couldn't break it!

2020-05-06 17:08 UTC, shlokamin requested changes
Lookin solid! Left some small comments/questions

2020-05-06 17:08 UTC, shlokamin commented on protocol-designer/src/ui/steps/actions/types.js
> +export type AddStepAction = {| type: 'ADD_STEP', payload: AddStepPayload |}
exact type

2020-05-06 17:08 UTC, shlokamin commented on protocol-designer/src/ui/steps/reducers.js
>  const selectedItem: Reducer<SelectedItemState, *> = handleActions(
looks like you have coverage for `SAVE_STEP_FORM ` just need `ADD_STEP `?

2020-05-06 17:08 UTC, shlokamin commented on protocol-designer/src/ui/steps/selectors.js
> +export const getSelectedStepTitleInfo: Selector<StepTitleInfo | null> = createSelector(
per the comment did you intend to add tests in this PR

2020-05-06 17:08 UTC, shlokamin commented on protocol-designer/src/ui/steps/test/reducers.test.js
> +    const action = {
is the naming here wrong? looks like the action is of type `SELECT_TERMINAL_ITEM`, did you mean to test `ADD_STEP`? Looks like there isn't one for it

2020-05-06 17:57 UTC, IanLondon commented on protocol-designer/src/components/StepDescription.js
good catch

2020-05-06 18:02 UTC, IanLondon commented on protocol-designer/src/components/StepEditForm/index.js
> +      </div>
any new StepType without a form should be under a prerelease setting / FF, so it shouldn't be exposed to the user unless we accidentally forgot to put an "Add Step" option under that FF, which would be something we'd wanna quickly fix either way.

This todo div isn't new in the PR btw, it's just moved around in the refactor

2020-05-06 18:04 UTC, IanLondon commented on protocol-designer/src/ui/steps/actions/__tests__/addStep.test.js
> -import { addStep } from '../thunks/addStep'
before it was b/c it was a thunk and I think it needed mocking of imports so it had its own file, now it's just b/c I didn't feel like adding it to the big actions.test.js since I imagine that will eventually get broken up if it gets big. Do you think it should be part of `actions.test.js` now?

2020-05-06 18:09 UTC, IanLondon commented on protocol-designer/src/ui/steps/test/reducers.test.js
> +    const action = {
thanks for the catch!

2020-05-06 19:03 UTC, IanLondon commented on protocol-designer/src/components/useConditionalConfirm.js
> +export const useConditionalConfirm = (
I'll make a ticket

2020-05-06 19:05 UTC, IanLondon commented on protocol-designer/src/ui/modules/selectors.js
>  import { getLabwareNicknamesById } from '../labware/selectors'
I think a few months ago at a JS guild talk we proposed avoiding imports from `/moduleDir/index.js` because it tends to be the cause of circular dependency issues, but I'm not sure if we've been consistent about that in new code (IDK if I have but I try to)

2020-05-06 19:11 UTC, IanLondon commented on protocol-designer/src/components/useConditionalConfirm.js
> +export const useConditionalConfirm = (
#5589

2020-05-06 20:52 UTC, shlokamin approved these changes
🚢

2020-05-06 21:01 UTC, merged