Api cal check comparison states
OpenTrons/opentrons-api pull request #5583
Opened 2020-05-05 23:40 UTC by b-cooper

## overview

## changelog

## review requests

## risk assessment

2020-05-06 15:24 UTC, sfoster1 requested changes
Couple small comments but also I think we should make the validity comparisons based on magnitude rather than per-element comparisons.

2020-05-06 15:24 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/middlewares.py
> +            MODULE_LOG.exception("Calibration Check Exception: {}".format(e))
`log.exception()` puts the current exception in the message on its own, don't need to explicitly add it

2020-05-06 15:24 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/models.py
> +    differenceVector: Point = PointField()
should we put the threshold in here too?

2020-05-06 15:24 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +calibration tasks such as joggingTo your calibration data, performing mount
find/replace gone awry?

2020-05-06 15:24 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +    :note: The UUID class is utilized here instead of UUID4 for type joggingTo
find/replace

2020-05-06 15:24 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        "before": "_load_tip_rack_objects"
these are getting pretty massive, should we move them to a constants file or something?

2020-05-06 15:24 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        return absolute_diff_vector > threshold_vector
we should probably store a threshold magnitude and compare the absolute diff magnitude to it. this per-component check is effectively enforcing a valid polygon; I think we'd want a valid sphere.

2020-05-06 15:24 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +                exceeds = absolute_diff_vector > comp.threshold_vector
same thing about per-element box comparison vs magnitude comparison

2020-05-06 16:42 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/session.py
> +                pipette_dict[pipette_id] = {'mount': mount, 'tiprack_id': None,'critical_point': cp}
nit: would be nice if this wasn't a dict, but a `dataclass` .

2020-05-06 16:42 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/session.py
> +                x=fixed_trash.point.x + 20,
magic number

2020-05-06 16:42 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        self._first_mount: typing.Optional[Mount] = None
Just a question: Do you think it would be easier to have mounts be a collection that we pop from rather than two named first and second?

2020-05-06 16:42 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        if self.current_state_name == \
Could be useful to have a function `in_preparing_state`, as we have the same if/else clause below.

2020-05-06 17:31 UTC, b-cooper commented on api/src/opentrons/server/endpoints/calibration/session.py
> +                pipette_dict[pipette_id] = {'mount': mount, 'tiprack_id': None,'critical_point': cp}
I agree, though I also think that the concept of `pipette_id` here no longer has much meaning. In that case the next set of changes to this flow could/should instead have the pipettes' info keyed by mount (as they are in the hardware controller). Then the tip rack objects would have a `forMounts` key rather than `forPipettes`. I'll throw a comment in there to capture both thoughts.

2020-05-06 17:32 UTC, mcous reviewed
Oops thought I posted this already. Nothing jumped out at me from the code, so I'll give this a try on my robot and see how behavior looks

2020-05-06 17:36 UTC, b-cooper commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        self._first_mount: typing.Optional[Mount] = None
I thought about keeping them in a Collection of some sort, but as the rest of the state machine has a concept of `firstFoo` and `secondFoo` it seemed more consistent to hold onto the mounts accordingly.  I'm up for a refactor in the next stages though.

2020-05-06 17:43 UTC, b-cooper commented on app/src/calibration/epic/updateRobotCalibrationCheckSessionEpic.js
> +    case ROBOT_CALIBRATION_CHECK_COMPARE_POINT: {
That's a good point.  With @amitlissack's forthcoming changes to this api the logic in this epic will change anyway, as we won't be hitting different paths for all of these updates, we'll just be switching out the contents of the body. Given that change, I think it could absolutely make sense to also shift the calling actions to a similar single "updateSession" abstraction. It would certainly make things easier to grok and terser.

2020-05-06 17:43 UTC, b-cooper commented on app/src/components/CheckCalibration/index.js
> +  CHECK_STEP_PREPARING_FIRST_PIPETTE,
good point

2020-05-07 11:07 UTC, amitlissack approved these changes

2020-05-07 11:07 UTC, amitlissack commented on api/src/opentrons/types.py
> +        xIs = isclose(self.x, other.x, rel_tol=1e-05, abs_tol=1e-08)
nit: since `is_close` to be true for all you can make a tuple of x, y, z and use `all` function. save some comparisons.

2020-05-07 11:07 UTC, amitlissack commented on api/tests/opentrons/server/calibration/test_check_calibration_session.py
> +async def in_inspecting_first_tip(check_calibration_session):
For the future: Since we will rely on these kinds of tests for calibration overhaul, we should come up with a less verbose way to set up fixtures.

2020-05-07 14:06 UTC, Laura-Danielle approved these changes
Code makes sense to me. Looks good!

2020-05-07 14:15 UTC, sfoster1 approved these changes
LGTM!

2020-05-07 15:47 UTC, merged