feat(api,robot-server): Api hardware sim from file
OpenTrons/opentrons-api pull request #5680
Opened 2020-05-14 17:54 UTC by amitlissack

## overview

This adds the ability to create a hardware simulator from a json file. Essentially, we store the arguments passed to `API.build_hardware_simulator`. There's an additional feature to enable configuring the modules. Devs can define a series of function calls + args for each module. 

Additionally, this PR has the robot-server use this feature for its tavern tests. This enables the new /sessions and /module tests as they require pipettes and modules respectively.

I made the decision to isolate the simulator_setup in its own file to limit the intrusiveness of this PR.

## changelog

- Add simulator_setup module with utilities to load and save files. Also to create a simulator from a file.
- robot-server defines a setting identifying the path of a simulator configuration file.
- the default dotenv file points to the new simulator configuration file
- tavern tests for /sessions and /modules

## review requests

Whatcha think?

## risk assessment

Nothing. It's just tests and simulators.

2020-05-14 18:11 UTC, amitlissack commented on api/src/opentrons/hardware_control/api.py
> +        await backend.watch_modules(
Not sure I understand why registering the modules in the simulator was asynchronous.

2020-05-14 18:12 UTC, sfoster1 requested changes
I think this will break module watching on robots. Also could we separate the pr and have one with the api changes and one with the server integration?

We should also have a way to load this file in `opentrons_simulate`.

2020-05-14 18:12 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        await backend.watch_modules(
This actually needs to be a task because it has the same lifetime as the api object as a whole - it sits on the loop and watches inotify for changes

2020-05-14 18:12 UTC, sfoster1 commented on robot-server/robot_server/service/routers/session.py
> +             status_code=http_status_codes.HTTP_201_CREATED,
is this an accidental inclusion?

2020-05-14 18:17 UTC, amitlissack commented on robot-server/robot_server/service/routers/session.py
> +             status_code=http_status_codes.HTTP_201_CREATED,
No. I included the robot server tests because they depend on this JSON file feature.

2020-05-14 18:18 UTC, amitlissack commented on api/src/opentrons/hardware_control/api.py
> +        await backend.watch_modules(
Can you double check that? In looking at Simulator.watch_modules all it does is take the attached_modules and register them.

2020-05-14 18:24 UTC, amitlissack commented
> I think this will break module watching on robots. Also could we separate the pr and have one with the api changes and one with the server integration?
> 
> We should also have a way to load this file in `opentrons_simulate`.

I can certainly split it up. I put them together to illustrate how I'd use the feature. Especially that it's a pre-req to cal check integration testing.

2020-05-14 18:37 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        await backend.watch_modules(
Oh you know I think you're right - I wasn't registering the context correctly here.

2020-05-14 18:37 UTC, sfoster1 commented
> > I think this will break module watching on robots. Also could we separate the pr and have one with the api changes and one with the server integration?
> > We should also have a way to load this file in `opentrons_simulate`.
> 
> I can certainly split it up. I put them together to illustrate how I'd use the feature. Especially that it's a pre-req to cal check integration testing.

That makes sense! However, I think the `opentrons_simulate` integration also shows that. If you want to keep them un-split that's fine though.

2020-05-14 18:38 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        await backend.watch_modules(
to be like the controller version, no other reason really

2020-05-18 14:52 UTC, sfoster1 approved these changes
Looks good! Will we add the support to `opentrons_simulate` in a followup?

2020-05-18 15:07 UTC, amitlissack commented
> Looks good! Will we add the support to `opentrons_simulate` in a followup?

Was working on adding it to this one.

2020-05-18 16:15 UTC, mcous approved these changes
This looks like a fantastic feature. I've added some repository housekeeping requests if you have a minute in this PR or a followup

2020-05-18 16:15 UTC, mcous commented on robot-server/simulators/dev.json
> +{
Including this file in revision control might end up a little messy. Could you rename it to `example.json` or something similar (if it's a necessary test fixture, maybe `test.json`?) and:

- Add a `README` to this directory describing the simulator file format
- Add a .gitignore rule (either to this directory or the top-level, no preference from me) to ensure simulator files other than the template/test-fixture are not accidentally added to the repo?

2020-05-18 16:15 UTC, mcous commented on robot-server/simulators/dev.json
> +    "RIGHT": {
Are these keys supposed to be all-caps? IIRC mounts everywhere else in the codebase are lowercase

2020-05-18 16:53 UTC, sanni-t commented on api/src/opentrons/simulate.py
> +    print("AMIT")
a leftover debug print?

2020-05-18 16:54 UTC, amitlissack commented on api/src/opentrons/simulate.py
> +    print("AMIT")
No. That's essential.  :(

2020-05-18 17:06 UTC, amitlissack commented on robot-server/simulators/dev.json
> +    "RIGHT": {
It's actually case insensitive.

2020-05-18 17:11 UTC, sanni-t approved these changes
Haven't tested yet, but code looks good! Super cool feature 
🆒

2020-05-18 20:47 UTC, merged