refactor(app): incorporate fast api session into cal check
OpenTrons/opentrons-api pull request #5690
Opened 2020-05-15 22:37 UTC by b-cooper

## overview

Deprecate the old calibration check domain layer that relied on the aiohttp api. Connect calibration
check components to the new sessions domain layer.

## changelog

## review requests

## risk assessment

2020-05-18 14:07 UTC, amitlissack approved these changes
Looks good to me.

2020-05-18 14:07 UTC, amitlissack commented on app/src/sessions/types.js
> -  data: { ... },
Nice!

2020-05-19 16:19 UTC, mcous requested changes

2020-05-19 16:19 UTC, mcous commented on app/src/analytics/__tests__/robot-calibration-events.test.js
> +          id: Calibration.CALIBRATION_CHECK_SESSION_ID,
Per Slack discussion with @amitlissack and @b-cooper, this should be treated as an opaque string ID. The API currently returns `calibrationCheck` for `id`, but only for internal convenience before calibration overhaul, so the client and its tests should not rely on this temporary behavior

2020-05-19 16:19 UTC, mcous commented on app/src/calibration/constants.js
> +export const CALIBRATION_CHECK_SESSION_ID = 'calibrationCheck'
This constant name is a little confusing, could we rename it? It (should) be used to match on the HAPI's `sessionType`, not `id`. Maye `SESSION_TYPE_CALIBRATION_CHECK` or `CALIBRATION_CHECK_SESSION_TYPE`?

2020-05-19 16:19 UTC, mcous commented on app/src/calibration/constants.js
>  export const ROBOT_CALIBRATION_CHECK_PATH: '/calibration/check/session' =
Is this constant still needed?

2020-05-19 16:19 UTC, mcous commented on app/src/calibration/epic/__tests__/fetchRobotCalibrationCheckSessionEpic.test.js
> -import { setupEpicTestMocks, runEpicTest } from '../../../robot-api/__utils__'
Why were these helpers removed?

2020-05-19 16:19 UTC, mcous commented on app/src/calibration/epic/fetchRobotCalibrationCheckSessionEpic.js
> +    tap(console.log),
Accidental `console.log`

2020-05-19 16:19 UTC, mcous commented on app/src/calibration/epic/fetchRobotCalibrationCheckSessionEpic.js
> +      // && action.payload.error.id === CALIBRATION_CHECK_SESSION_ID
I think this will be `sessionType`, not `id`

2020-05-19 16:19 UTC, mcous commented on app/src/analytics/__tests__/robot-calibration-events.test.js
> +    getRobotSessionById.mockReturnValue({
This may be more appropriate as a stub rather than a blind mock. As written, the event maker function could pass the completely wrong arguments into `getRobotSessionById` and the test will still pass.

I've started to write these with `mockImplementation` instead of `mockReturnValue` for that reason:

```js
getRobotSessionById.mockImplementation((state, robotName, sessionId => {
  expect(state).toBe(MOCK_STATE)
  expect(robotName).toBe(MOCK_ROBOT.name)  // or whatever it is in this test
  expect(sessionId).toBe(MOCK_SESSION_ID)
  // mock return here
})
```

2020-05-19 16:19 UTC, mcous commented on app/src/analytics/__tests__/robot-calibration-events.test.js
> +const getRobotSessionById: JestMockFn<
This selector is used throughout this PR as "get session by session type", not by opaque ID. This should be a new selector that returns the session by `sessionType`, not by the ID (which, as mentioned in another comment, is not stable)

2020-05-19 16:19 UTC, mcous commented on app/src/components/CheckCalibration/index.js
> +      Sessions.createSessionCommand(
Not part of this PR, so not a change request right now, but we should probably rename this action creator to reflect that this action is for creating and immediately executing a command object

2020-05-19 16:33 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/models.py
> +OffsetVector = List[float]
You can feel free to change it to: `OffsetVector = Tuple[float, float, float]`
And remove the `min_items=3, max_items=3` from `OffsetVectorField`

2020-05-19 18:09 UTC, b-cooper commented on app/src/calibration/epic/__tests__/fetchRobotCalibrationCheckSessionEpic.test.js
> -import { setupEpicTestMocks, runEpicTest } from '../../../robot-api/__utils__'
They are not appropriate for this epic. They assume an action is dispatched from the view layer which maps to an fetch request, which will differentially map to a failure or response.

This epic is just listening for the `FETCH_SESSION_FAILURE` action, and with a couple of conditions mapping to a `CREATE_SESSION` action.

2020-05-20 15:38 UTC, mcous commented on app/src/calibration/epic/__tests__/fetchRobotCalibrationCheckSessionEpic.test.js
> -import { setupEpicTestMocks, runEpicTest } from '../../../robot-api/__utils__'
They don't assume that. You can omit the mock API response argument and continue to use the helpers as boilerplate reducers. For example, the wifi epic maps a POST_WIFI_DISCONNECT_SUCCESS action internally to a FETCH_WIFI_LIST action. No view layer trigger and no request / response mapping:

https://github.com/Opentrons/opentrons/blob/87131613ed1282056931f34b89f985022e20405c/app/src/networking/epic/__tests__/disconnectEpic.test.js#L81-L95

2020-05-20 16:10 UTC, mcous requested changes
Changes from last time look good! I've got some follow-up requests, included an untested reducer that has what looks to me like a potential bug if the API responds unexpectedly

2020-05-20 16:10 UTC, mcous commented on app/src/components/CheckCalibration/index.js
>    React.useEffect(() => {
Not a change request for this PR, but this `useEffect` had been freaking me out. I think there's too much surface area for the effect dependencies to change and have an unintentional `createSession` dispatch.

Could we consider moving this logic to the (or a) parent? At this point it shouldn't be in this PR, but longer term I would feel a lot better if this dispatch was more directly connected to a single user action, e.g.:

1. User clicks button triggering `GET` or `POST`
2. Button shows spinner or something while request is in flight
3. Request completes and:
    - If success, CheckCalibration is rendered (maybe even with session passed in as a prop)
    - If failure, some failure is displayed somehow

2020-05-20 16:19 UTC, b-cooper commented on app/src/sessions/selectors.js
> +export const findRobotSessionIdByType: (
I called it `findRobotSessionIdByType`, because it is using find, there is no guarantee that there are not multiple sessions of a given type (not true for cal check) and given that I wanted to be clear that this is finding the first existing session of that `type`. In that way I think it diverges from the other selectors, and integrates more helper logic. Would `getFirstSessionOfType` be better?

2020-05-20 16:22 UTC, b-cooper commented on app/src/sessions/types.js
>  export type SessionCommand = {|
Looks like `SessionCommandRequest` is unused. ...deleting it

2020-05-20 17:19 UTC, sfoster1 approved these changes
LGTM after walkthrough!

2020-05-20 17:29 UTC, b-cooper commented on app/src/sessions/selectors.js
> +export const findRobotSessionIdByType: (
fwiw ... Ended up calling it `getRobotSessionOfType`

2020-05-20 20:07 UTC, mcous approved these changes
🔴 😍

2020-05-20 21:01 UTC, merged