feat(api, app): implement automatic door safety stop feature
OpenTrons/opentrons-api pull request #5706
Opened 2020-05-20 14:30 UTC by ahiuchingau

## overview
This PR adds the automatic door safety stop feature, and enables it if the user has toggled on the `enableDoorSafetySwitch` feature flag. 

closes #2820, closes #2752 

## changelog
- new `enableDoorSafetySwitch` feature flag

- added `doorState` (door open/closed) and `blocked` (if door safety switch is enabled and door is open) to session info

- automatically pauses the protocol when the robot door is opened

- used the two added info to enable and disable the `Start Run` and `Resume` button in the app

## review requests

## risk assessment

2020-05-20 14:56 UTC, sfoster1 requested changes
Some inline comments.

Also, I think that the object passed to the hardware controller callback is better off being a [tagged union](https://mypy.readthedocs.io/en/stable/literal_types.html#tagged-unions), like

```
class HardwareEventType(Enum):
    DOOR_STATE_CHANGE = auto() # new event types get new entries

class DoorStateNotification(TypedDict):
   event: Literal[HardwareEventType.DOOR_STATE_CHANGE]
   new_state: DoorState

# new event types get new TypedDict classes (or dataclasses if we want)

HardwareEvent = Union[DoorStateNotification] # when we add more event types we add them here
```

That means that the type of the callback can always stay as `Callable[[HardwareEvent], None]` and if they're written correctly, to check the kinds of events they get, they don't ever need to change. If we do it as in this pr, where the different data is passed in as an argument, then we have to change the form of all the callbacks whenever we add a new event type.

2020-05-20 14:56 UTC, sfoster1 commented on api/src/opentrons/api/session.py
> +        self._event_watcher = self._hardware.register_callback(
should probably have a just-in-case check to see if `_event_watcher` exists already

2020-05-20 14:56 UTC, sfoster1 commented on api/src/opentrons/config/advanced_settings.py
> +                    "pause your robot only after it has completed it's "
```suggestion
                    "pause your robot only after it has completed its "
```

2020-05-20 14:56 UTC, sfoster1 commented on api/src/opentrons/config/advanced_settings.py
> +                    "Note that opening the robot door during a run will "
```suggestion
                    "Opening the robot door during a run will "
```

2020-05-20 14:56 UTC, sfoster1 commented on app/src/robot/api-client/client.js
> +    update.blocked = apiSession.blocked ?? null
I'll defer to js folks, but to me there's not really a need for this to be nullable - it can just be `false` in that case, since `null` means "not blocked"

2020-05-20 14:56 UTC, sfoster1 commented on app/src/robot/api-client/client.js
> +    update.doorState = apiSession.doorState ?? null
this could end up being "unknown" instead of null

2020-05-20 14:56 UTC, sfoster1 commented on app/src/robot/reducer/session.js
> +  doorState: string | null,
we should probably have some enumerated literals for this, since that's what it is on the robot side

2020-05-20 14:56 UTC, sfoster1 commented on app/src/robot/test/api-client.test.js
> +          doorState: null,
[begins typing in @mcous ] We should probably have tests for this that check 
- incremental session updates with `null` `doorState` and `blocked` (which is what's here, so nice work)
- incremental session updates with non-`null` `doorState` and `blocked`

2020-05-20 14:56 UTC, sfoster1 commented on app/src/components/RunPanel/RunControls.js
> +    const pauseDisabled = disabled || isBlocked
What situations would we be in. where `isBlocked` is true while we're running?

2020-05-20 15:02 UTC, ahiuchingau commented on app/src/components/RunPanel/RunControls.js
> +    const pauseDisabled = disabled || isBlocked
`isRunning` is True when the state is either `running` or `paused`

When the protocol is paused due to the door opening, and before the door is closed again, we'd get both `isRunning` and `isBlocked`

2020-05-20 16:38 UTC, amitlissack commented on api/src/opentrons/api/session.py
> +        self.doorState: Optional[str] = None
convention is to use snake case please.

2020-05-20 16:38 UTC, amitlissack commented on api/src/opentrons/api/session.py
> +        self.doorState = str(state)
Why did you choose to have door state be a str type rather than a DoorState?

2020-05-20 20:40 UTC, sfoster1 commented on api/src/opentrons/api/session.py
> +        self.doorState = str(state)
needs to go through rpc, which doesn't have custom serdes (at least right now)

2020-05-21 18:47 UTC, sfoster1 commented on app/src/components/RunPanel/RunControls.js
> +    const pauseDisabled = disabled || isBlocked
ah, good catch!

2020-05-26 20:41 UTC, sfoster1 requested changes
couple (very small, promise) change requests

2020-05-26 20:41 UTC, sfoster1 commented on api/src/opentrons/api/session.py
> +        self.clear()
why do we need these extra `clear` calls?

2020-05-26 20:41 UTC, sfoster1 commented on api/src/opentrons/hardware_control/dev_types.py
> +if TypedDict is not None:
this is really nice!

2020-05-26 20:41 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +            cb(hw_event)
let's wrap this in a `try... except Exception`  that logs or something so we know if a callback has an error.

2020-05-26 20:41 UTC, sfoster1 commented on app/src/robot/test/api-client.test.js
> +        blocked: 'fasle',
s/`fasle`/`false`/

should this be a string or should it be a bool? bit odd that it passes even with the typo

2020-05-26 20:41 UTC, sfoster1 commented on app/src/robot/test/api-client.test.js
> +        blocked: 'false',
should this be a string?

2020-05-26 21:07 UTC, ahiuchingau commented on api/src/opentrons/api/session.py
> +        self.clear()
I added the `clear` calls because the `hardware_event_watcher` in the existing session wasn't properly exiting when a new session is created, and ended up registering multiple callbacks in hardware controller.  By calling `clear()` first, I was able to make sure the callback has been unregistered before creating the new session.

2020-05-26 21:08 UTC, ahiuchingau commented on app/src/robot/test/api-client.test.js
> +        blocked: 'fasle',
Definitely should be a bool! This is outdated and the typos have been fixed

2020-05-26 21:09 UTC, ahiuchingau commented on app/src/robot/test/api-client.test.js
> +        blocked: 'false',
same as above

2020-05-26 21:11 UTC, sfoster1 commented
We should get a tooltip on the start/resume button when it's disabled, @pantslakz do you have an idea for the text

2020-05-26 21:13 UTC, sfoster1 requested changes
Oh the designs actually have a tooltip when the button is disabled - we should add that. I think we have a component for it now?

2020-05-26 23:26 UTC, mcous commented
Will give this a thorough review tomorrow. Out of curiosity, why aren't we using the new `stateInfo`/`statusInfo` field? Adding new fields to the RPC state is inherently risky and I don't necessarily see why it's necessary in this case

2020-05-27 15:44 UTC, ahiuchingau commented
@mcous There's no particular reason why we're not putting the info in `statusInfo` instead, we certainly can! I wasn't aware of how risky adding new fields would be so I didn't think of that

2020-05-28 13:10 UTC, amitlissack commented on api/src/opentrons/hardware_control/dev_types.py
> +        event: Literal[HardwareEventType.DOOR_SWITCH_CHANGE]
Why are we using `TypedDict` if it's potentially not available ?

2020-05-28 13:10 UTC, amitlissack commented on app/src/components/RunPanel/RunControls.js
> +      <HoverTooltip tooltipComponent={runTooltip}>
It's ok for `runToolTip` to be null here?

2020-05-28 14:17 UTC, ahiuchingau commented on app/src/components/RunPanel/RunControls.js
> +      <HoverTooltip tooltipComponent={runTooltip}>
I believe the `runTooltip` here only describes the text showed by the tooltip, when it's null (in this case, when the protocol is not blocked), the tooltip would just not appear.

I could be wrong but I used the `tooltipText` in /app/src/components/ModuleItem/ModuleUpdate.js as a reference

2020-05-28 14:20 UTC, amitlissack commented on app/src/components/RunPanel/RunControls.js
> +      <HoverTooltip tooltipComponent={runTooltip}>
Sounds good to me. Just asking.

2020-05-28 14:54 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/dev_types.py
> +        event: Literal[HardwareEventType.DOOR_SWITCH_CHANGE]
I thought if it's only used for type-checking, it wouldn't matter as much. But now that you mentioned it, I think switching to `dataclass` should work too

2020-05-28 15:27 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/dev_types.py
> +        event: Literal[HardwareEventType.DOOR_SWITCH_CHANGE]
Actually, we might still need to import `Literal` from `type_extensions` if we want to add 
more types of hardware event down the line. @amitlissack any ideas on how I can achieve something similar to the example here without using `Literal`?

```:python
class HardwareEventType(enum.Enum):
    DOOR_SWITCH_CHANGE = enum.auto()
    SOMETHING_ELSE = enum.auto()

@dataclass
class SomethingElseNotification:
    event: Literal[HardwareEventType.SOMETHING_ELSE]
    new_state: int

@dataclass
class DoorStateNotification:
    event: Literal[HardwareEventType.DOOR_SWITCH_CHANGE]
    new_state: DoorState

HardwareEvent = Union[DoorStateNotification, SomethingElseNotification]
```

2020-05-28 15:47 UTC, amitlissack commented on api/src/opentrons/hardware_control/dev_types.py
> +        event: Literal[HardwareEventType.DOOR_SWITCH_CHANGE]
So `event` can only be one thing? Perhaps it should just be set by default? 
```
class HardwareEventType(enum.Enum):
    DOOR_SWITCH_CHANGE = enum.auto()
    SOMETHING_ELSE = enum.auto()

@dataclass
class SomethingElseNotification:
    event: HardwareEventType = HardwareEventType.SOMETHING_ELSE
    new_state: int

@dataclass
class DoorStateNotification:
    event: HardwareEventType = HardwareEventType.DOOR_SWITCH_CHANGE
    new_state: DoorState
```

2020-05-28 15:49 UTC, mcous commented on app/src/robot/api-client/client.js
> +    update.doorState = apiSession.door_state ?? ''
I know this is following the pattern of what already exists in this part of the codebase, but unfortunately this code is very old and was written before we had typechecking in JS. I highly recommend using `null` over an empty string for "unknown"

2020-05-28 15:49 UTC, mcous commented on app/src/robot/test/__fixtures__/session.js
> +    blocked: false,
If we're going to add fields to the RPC session (which, again, I'm really hoping we don't have to do), like when we added stateInfo, we'll want another fixture that omits these fields entirely

2020-05-28 15:49 UTC, mcous commented on app/src/robot/test/api-client.test.js
> +      session.door_state = null
`null` is not the same as `undefined` or a missing field in JavaScript, so this test doesn't replicate reality as written. See my comment about test fixtures and how the `handles sessionResponses without status info` test above works

2020-05-28 15:49 UTC, mcous commented on api/src/opentrons/api/dev_types.py
> +    doorState: str
Ah I'm sorry that I didn't post a for full explanation of what I was referring to before you pushed this change. Changing the shape of `stateInfo` is exactly the same problem as changing the shape of the session itself. I think we can get this minimal door switch functionality in without adding any (public) fields anywhere

2020-06-01 12:02 UTC, theosanderson commented on api/src/opentrons/api/session.py
> +                "robot door is cloed before resuming.")
(happened to be reading to understand code changes) s/cloed/closed/

2020-06-01 12:53 UTC, SyntaxColoring commented on api/src/opentrons/api/session.py
> +                "robot door is cloed before resuming.")
Also `s/blocked is cannot/blocked and cannot`. :)

2020-06-01 13:34 UTC, sfoster1 requested changes
I'll check out the functionality (the structure does look good!) but there's some typos, and I also think I disagree with the change to dataclasses from TypedDicts for the hardware event payloads. We were using TypedDicts for the payloads because we can do tagged unions with them; that way, when we implement more kinds of events, we can pass just the data from a given event. I don't think you can do that with dataclasses. While dataclasses are usually better than typed dicts, I think this is one of the cases where that's not true, and we should stick with typed dicts

2020-06-01 13:34 UTC, sfoster1 commented on api/src/opentrons/hardware_control/types.py
> +@dataclass
Does mypy support tagged unions based on dataclasses? I don't think it does, and the existence of [this pypi module](https://pypi.org/project/tagged-dataclasses/) seems to support that thought.

2020-06-01 13:34 UTC, sfoster1 commented on api/src/opentrons/hardware_control/types.py
> +    event: HardwareEventType = HardwareEventType.DOOR_SWITCH_CHANGE
I'm pretty sure that if mypy _does_ support tagged dataclasses, this would need to be of type `Literal[HardwareEventType.DOOR_SWITCH_CHANGE]`

2020-06-01 13:51 UTC, amitlissack commented
> I'll check out the functionality (the structure does look good!) but there's some typos, and I also think I disagree with the change to dataclasses from TypedDicts for the hardware event payloads. We were using TypedDicts for the payloads because we can do tagged unions with them; that way, when we implement more kinds of events, we can pass just the data from a given event. I don't think you can do that with dataclasses. While dataclasses are usually better than typed dicts, I think this is one of the cases where that's not true, and we should stick with typed dicts

It is unfortunate that this wasn't shared before the change was implemented. A real waste of time it was. 

How can we avoid this in the future?

2020-06-01 14:47 UTC, ahiuchingau commented
@amitlissack It was really just my own fault. I thought I thoroughly tested our tagged union use cases with `dataclasses` before making the changes. 

But in my conversation with Seth, we realized that tagged unions actually do work with dataclasses! Though I'd still need to import `Literal` to make it fully functioning

2020-06-01 14:52 UTC, amitlissack commented
> @amitlissack It was really just my own fault. I thought I thoroughly tested our tagged union use cases with `dataclasses` before making the changes.
> 
> But in my conversation with Seth, we realized that tagged unions actually do work with dataclasses! Though I'd still need to import `Literal` to make it fully functioning

So pleased to hear that.

2020-06-01 14:56 UTC, ahiuchingau commented on api/src/opentrons/api/session.py
> +                "robot door is cloed before resuming.")
oh boy

2020-06-01 19:31 UTC, mcous approved these changes
JS side LGTM. As noted in slack, the client-side isn't using the door state at all, so we should add whatever TODO comments we need to make sure they don't get inadvertently removed if we are planning on using that property in the future

2020-06-01 20:45 UTC, sfoster1 approved these changes
Looks good to me! Can't wait to merge it!

2020-06-02 19:59 UTC, nusrat813 approved these changes
Tested - working as intended

2020-06-02 20:46 UTC, merged