refactor(api): Check tiprack thresholds after tip pickup
OpenTrons/opentrons-api pull request #5708
Opened 2020-05-20 15:31 UTC by Laura-Danielle

## overview

This PR will need to be rebased after #5676 is merged in. According to designs, pick up tip should occur before checking whether the jog to the tiprack was outside of the specified threshold.

## changelog
- Add in a new trigger state called `move_to_tiprack`
- Separate out pick up tip into two separate functions instead of trying to determine which pipette to used based on the state name.
- Add in two new cal check states to specify that you are jogging to the tiprack
- Ensure you are saving the reference point and post-jog point for jogging to the tiprack so you can appropriately compare points.

## review requests

Check over the state machine states, see that the logic still makes sense. Test on a robot

## risk assessment

Should be very low. Only re-arranging the order of execution for steps in the state machine.

2020-05-20 16:35 UTC, amitlissack reviewed
Is the new trigger `joggingFirstPipetteToTiprack` expected to be called from the run app client?

2020-05-20 16:35 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/util.py
> +        # print(events)
Can you remove this comment?

2020-05-20 16:35 UTC, amitlissack commented on api/src/opentrons/server/endpoints/calibration/util.py
> +            # print(WILDCARD)
This one too?

2020-05-20 18:57 UTC, sfoster1 requested changes
Couple inline changes but the structure looks fine

2020-05-20 18:57 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +                   CalibrationCheckState.joggingSecondPipetteToTiprack
we should either return a default in an `else` or explicitly raise an exception like a `RuntimeError`, in the `else` case, otherwise callers that put the wrong state in will blow up trying to unpack `None` which isn't that useful an error

2020-05-20 18:57 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +        states when looking up the reference point.
Could we get a more explicit description of the return tuple and types for the function

2020-05-22 14:56 UTC, sfoster1 requested changes
This looks like it will work but we have to update the types here to make it all pass, we shouldn't have that `type: ignore` in here.

2020-05-22 14:56 UTC, sfoster1 commented on api/src/opentrons/server/endpoints/calibration/session.py
> +                              transitions=CHECK_TRANSITIONS,  # type: ignore
why does this now need a `# type: ignore`? do we have to update the type of the transitions dict?

2020-05-26 13:17 UTC, sfoster1 approved these changes
👍

2020-05-26 13:55 UTC, merged