refactor(app): add analytics event to cal check session exit
OpenTrons/opentrons-api pull request #5780
Opened 2020-05-29 23:32 UTC by b-cooper

## overview

Add analytics event that fires on exit of a calibration check session and includes diagnostic data from check in the properties.

## risk assessment

Relatively minimal: behind a feature flag and only adding analytics side effect to existing code.

2020-06-01 14:34 UTC, mcous requested changes
Just went through a refactor with the U2E adapter analytics in #5764. Previously, there was a selector to get the U2E adapter device and a "helper" function to turn a device into analytics props. Tried to add a few more fields to the analytics object in that PR and the whole structure fell apart.

It ended up being way more testable / simple to have a full-on selector to get analytics props that handled pulling the device from state so the event mapper didn't have to. I recommend the same change here.

Also, do any of these properties need to be added to the Intercom user profile?

2020-06-01 14:34 UTC, mcous commented on app/src/sessions/helpers.js
> +export const getAnalyticsPropsForSession = (
Having just gone through this for the U2E adapter analytics, I think this is easier to deal with as a full on selector so that the event mapper doesn't have to deal with the logic of pulling out a calibration check session and then passing it back in

2020-06-01 14:34 UTC, mcous commented on app/src/sessions/helpers.js
> +    //  session.details.comparisonsByStep,
Errant comment?

2020-06-01 14:34 UTC, mcous commented on app/src/sessions/helpers.js
> +  session: ?Types.Session
Can this be `Types.Session | null`?

2020-06-01 14:34 UTC, mcous commented on app/src/sessions/types.js
> +export type CalibrationCheckSessionAnalyticsProps = {
- Why can't this be an exact object? We have full control over it
- This object doesn't have any field that explicitly identifies it as a calibration check session

2020-06-01 14:34 UTC, mcous commented on app/src/analytics/make-event.js
> +        session.sessionType === Sessions.SESSION_TYPE_CALIBRATION_CHECK
This logic isn't tested and (aside from the event name) is duplicated with logic in `getAnalyticsPropsForSession`

2020-06-01 14:34 UTC, mcous commented on app/src/analytics/make-event.js
> +          name: 'calibrationCheckExit',
I think this logic might be simplified if name is a more generic "session exit" and the analytics props identify the session type. Still just as filterable in MixPanel and then that logic can be moved to a selector

2020-06-01 14:34 UTC, mcous commented on app/src/sessions/helpers.js
> +  if (!session) return null
This logic isn't covered by tests

2020-06-01 14:34 UTC, mcous commented on app/src/sessions/helpers.js
> +  return null
I don't think this return is covered by the tests either

2020-06-01 15:13 UTC, b-cooper commented on app/src/sessions/types.js
> +export type CalibrationCheckSessionAnalyticsProps = {
- I agree it should be an exact object, making that change now
- There are 24 keys in this object that wouldn't exist in other sessions (e.g.`comparingFirstPipetteHeightDifferenceVector`). My thought was to keep these objects separate for different sessions and then have analytics handle a union type for session exits in general.

2020-06-02 03:08 UTC, mcous approved these changes
Looking good! Still missing one test case I think but source looks solid.

Do we need TODO(s) for handling early exits and/or automatic deletes due to conflicts?

2020-06-02 03:08 UTC, mcous commented on app/src/analytics/make-event.js
> +        return Promise.resolve(null)
Should also test this branch

2020-06-02 03:08 UTC, mcous commented on app/src/sessions/types.js
> +  | {||}
What are these for? Asking out of curiosity

2020-06-02 13:50 UTC, b-cooper commented on app/src/sessions/types.js
> +  | {||}
They are for appeasing flow for the meantime. There is a bug tracked here https://github.com/facebook/flow/issues/2977 that keeps exact object types with all optional fields from accepting a possibly empty object.

2020-06-02 15:36 UTC, mcous commented on app/src/sessions/types.js
> +  | {||}
If that's the case I'm not sure this will work. Flow doesn't allow you to assign an empty object to something that's typed as `{||}`. As written in that issue thread, I would use `$Shape` instead, which can be unsafe but should be fine if every property is already marked as optional

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGKmAD5gDetcOGAlnAHYCGMA-AFxgAzhgBOLdgHMaAXyq0G1WagDGHYWCgkBxUhTpLs+MACFOI8mAAkAZQAWnfAB4GYJqw7d+Q0eKmKAfOiq7OoARmYCpuZ60kA

2020-06-02 20:52 UTC, merged