feat(api): Add endpoints to access labware calibration
OpenTrons/opentrons-api pull request #5811
Opened 2020-06-04 00:20 UTC by Laura-Danielle

## overview

Closes #5553. This PR adds in endpoints that allow you to access the current labware calibrations stored on the robot.

## changelog
- Modified the `index.json` file such that the key is now the labware hash. This is to prevent duplicate keys in the even that we start storing labware calibration per slot.
- Added in three endpoints as per the ticket specifications. 

## Notes

## review requests

You should clear labware calibration before testing on a robot.

Also check if there is any documentation things that might be missing.

## risk assessment

Low. New feature that is not being used anywhere at the moment.

2020-06-04 13:55 UTC, mcous commented on api/src/opentrons/protocol_api/labware.py
> +def get_all_calibrations() -> List[Dict[str, Any]]:
Does this method need to be a part of the protocol API? It doesn't feel to me like it's got anything to do with protocols

2020-06-04 13:55 UTC, mcous commented on api/src/opentrons/protocol_api/labware.py
>  def _add_to_index_offset_file(labware: Labware, lw_hash: str):
I know this PR doesn't touch this, but for the sake of clarity: this also looks to me like it doesn't belong in the Protocol API

2020-06-04 13:55 UTC, mcous commented on robot-server/robot_server/service/labware/router.py
> +def _format_calibrations(calibrations: List[Dict[str, Any]]):
Similar to my question above about the Protocol API: should this logic be in the router? Both of these feel like part of a standalone labware calibration library, like the files in `api/src/opentrons/system`

2020-06-04 14:04 UTC, amitlissack requested changes
I hope my comments make sense to you. Please reach out if you want further explanation and/or assistance.

2020-06-04 14:04 UTC, amitlissack commented on robot-server/robot_server/service/labware/router.py
> +    ns, ln, ver = lw_funcs.details_from_uri(calibration['uri'])
Return annotation and doc string please.

2020-06-04 14:38 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +def get_all_calibrations() -> List[Dict[str, Any]]:
it would probably be pretty nice to get calibration handling out of the protocol api tree. i think that tree needs a bit of a refactor to split out
- json protocol handling
- parts of the python code not explicitly to do with user apis

2020-06-04 14:48 UTC, sfoster1 requested changes
Some inline change requests

2020-06-04 14:48 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +def _remove_offset_from_index(calibration_id: str):
We have a lot of string types that mean various things - could we do a `CalibrationID = NewType('CalibrationID', str)`?

2020-06-04 14:48 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +    else:
[nit] if we're just going to raise a `FileNotFoundError` if the file doesn't exist, we can just access it without the existence check

2020-06-04 14:48 UTC, sfoster1 commented on robot-server/robot_server/service/labware/router.py
> +    return time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(specified_time))
Please use [ISO-8601](https://www.w3.org/TR/NOTE-datetime) datetime formatting and express this time in UTC rather than localtime. Keep in mind this may drop us into a hellscape of time formatting problems since the robot may not actually know the time

2020-06-04 20:14 UTC, Laura-Danielle commented on robot-server/robot_server/service/labware/router.py
> +    return time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(specified_time))
sounds exciting

2020-06-08 16:48 UTC, sfoster1 commented
Talked offline - a lot of the comments about moving responsibility for calibration out of here also apply to #5820, let's add todos here and there and then follow up these prs with that refactor

2020-06-09 23:46 UTC, Laura-Danielle commented on api/tests/opentrons/protocol_api/test_labware.py
> +    all_cals = labware.get_all_calibrations()
it's using pytest's temporary directory to create the index file/read from it.

The main point of the test was to check that an index file was created and the list all calibrations function correctly returned the expected data. I felt like it would be overkill to format all of the 'expected' data and then check that it matches. That's why I chose to check only the key values.

However, writing out the above, it doesn't necessarily seem to be testing much. I'll add a helper to format the expected data.

2020-06-12 13:22 UTC, sfoster1 requested changes
More details in the individual comments. Also I think the merge has messed some stuff up?

2020-06-12 13:22 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +LabwareDefinition = Dict[str, Any]
Use the `LabwareDefinition` typedef available from `opentrons_shared_data`

2020-06-12 13:22 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +ModuleData = Dict[str, Any]
We should get a more involved typedef here, maybe using `TypedDict`

2020-06-12 13:22 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +class WellShape(Enum):
These things seem to be merge casualties? They're not present in edge. rebasing on edge may be a better idea than merge edge in here

2020-06-12 13:22 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +    print("OFFSETS PATH")
debug prints

2020-06-12 13:22 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +def _format_calibration_type(data: Dict) -> CalibrationTypes:
i think we can do a better typedef for the argument here

2020-06-12 13:22 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +    lastModified: str
Let's keep this as a `datetime` when loaded, and store as an iso-formatted string when on disk

2020-06-12 13:22 UTC, sfoster1 commented on robot-server/robot_server/service/labware/router.py
> +def _convert_time(specified_time: Optional[int]) -> Optional[datetime]:
Not sure where this becomes an int? It seems to be a string in `CalibrationData`?

2020-06-12 13:22 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +    tipLength: CalibrationData
I know this is annoying but since this is internal we should stick with `snake_case` for members here, as in `CalibrationInformation` right below this

2020-06-12 13:22 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +    lastModified: str
and we should keep this `snake_case`

2020-06-12 13:33 UTC, Laura-Danielle commented
> More details in the individual comments. Also I think the merge has messed some stuff up?

yeah, I'm still fixing stuff up. It's not fully ready for review yet. Looks like the merge did mess some stuff up.

2020-06-15 14:54 UTC, amitlissack reviewed
Looking real good. Just a few minor questions and thoughts.

2020-06-15 14:54 UTC, amitlissack commented on api/src/opentrons/protocol_api/labware.py
> +    value: Union[Optional[float], List]
A `List` of what?

2020-06-15 14:54 UTC, amitlissack commented on api/src/opentrons/protocol_api/labware.py
> +    string_to_return = ''
Is there a reason to not use `join` here?

2020-06-15 14:54 UTC, amitlissack commented on api/src/opentrons/protocol_api/labware.py
> +    if data.get('tipLength'):
If `data.get('tipLength')` were assigned to a variable you could save some typing and dict lookups on lines 1295 and 1296.

2020-06-15 14:57 UTC, sfoster1 requested changes
Some things in the details that could use clarification or change

2020-06-15 14:57 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +    offset: List
`List[float]`?

2020-06-15 14:57 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +    value: Union[Optional[float], List]
What's the difference here? Is one the tip length and one the offset?

2020-06-15 14:57 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +        data: CalibrationDict) -> CalibrationTypes:  # type: ignore
Why does this need a type ignore?

2020-06-15 14:57 UTC, sfoster1 commented on robot-server/robot_server/service/labware/router.py
> +    token = secrets.token_urlsafe(nbytes=8)
if i'm understanding the semantics of the [json response resource id](https://jsonapi.org/format/#document-resource-object-identification), this is supposed to be a resource identifier that, well, identifies a resource. that means it should nominally be able to be used to look up the resource in some other api. so I think in this case it should probably be the calibration identifier?

2020-06-15 14:57 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +    :Note: The return type of this function is actually
can you expand on this a bit more? could this be a use case for tagged unions?

2020-06-15 14:57 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +def _combine_strings(*args, delimiter=''):
couldn't this be done using `join`? a really generic function name like this is a bit odd, it strikes me as something that either
- is only really used in specific circumstances and therefore could do with a more specific name and perhaps a more specific type
- is used in many circumstances and either could be replaced with a builtin like `join` or put in a `utils` file

2020-06-15 15:01 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/labware.py
> +    string_to_return = ''
No reason not to

2020-06-15 15:11 UTC, Laura-Danielle commented on robot-server/robot_server/service/labware/router.py
> +    token = secrets.token_urlsafe(nbytes=8)
@sfoster1 I think that makes sense when accessing an individual calibration, but what about the list of calibrations?

@amitlissack do you have any thoughts on this?

2020-06-15 17:48 UTC, ahiuchingau requested changes

2020-06-15 17:48 UTC, ahiuchingau commented on api/src/opentrons/protocol_api/labware.py
> +from typing_extensions import TypedDict
The `typing_extensions` module has not been added to the robot. For type-checking purposes, we can move the TypedDicts to protocol_api/dev_types.py for now until the refactor

2020-06-15 20:06 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/labware.py
> +    value: Union[Optional[float], List]
Yes. It's a generic way to store the data.

2020-06-16 16:37 UTC, amitlissack requested changes

2020-06-16 16:37 UTC, amitlissack commented on robot-server/tests/integration/test_labware_calibration_access.yaml
> +          <<: *calibration_data
This file needs to be renamed to end with `.tavern.yaml`. It's not being executed at the moment.

2020-06-16 17:59 UTC, sfoster1 commented on api/src/opentrons/protocol_api/constants.py
> -class JsonCommand(enum.Enum):
is this another merge casualty or is this deletion intentional

2020-06-24 14:45 UTC, sfoster1 requested changes
Couple debug prints that need to be changed, and I really think we shouldn't have a union across two different structures.

2020-06-24 14:45 UTC, sfoster1 commented on api/src/opentrons/config/__init__.py
> +    print("inferring base")
prints

2020-06-24 14:45 UTC, sfoster1 commented on api/src/opentrons/config/__init__.py
> +        print("Conferring base here")
prints

2020-06-24 14:45 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +    value: Union[Optional[float], List[float]]
I think this is probably a bad idea. To me, types that have unions differing in structure really need to be either a tagged union or two separate types - having a `Union[float, List[float]]` is different from just a `Union[float, int]` or `Optional[float]`. And this type is in fact looking at different kinds of data.

What if we instead had a tagged union populated by the loader? Remember, this doesn't necessarily have to exactly match the json structure - or, rather, if we have a type that _does_ exactly match the json structure, we should _also_ have a type that represents the data in memory, which could be a tagged union.

2020-06-24 14:45 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +    index_file = TIP_LENGTH_CALIBRATION_PATH/'index.json'
Honestly, I think having this as a function call is a better idea, so its value can change while the system is still up without monkeypatching

2020-06-24 14:52 UTC, amitlissack commented on api/src/opentrons/config/__init__.py
> +    print("inferring base")
we can remove prints?

2020-06-24 14:52 UTC, amitlissack commented on api/src/opentrons/protocol_api/dev_types.py
> +    lastModified: str
There's a mixture of camel and snake case. Is there a reason for that?

2020-06-24 14:52 UTC, amitlissack commented on robot-server/robot_server/service/labware/models.py
> +    value: OffsetVector = OffsetVectorField()
Do you think that it's valuable to add `Field` definitions to provide descriptions of all these model attributes?

2020-06-24 14:52 UTC, amitlissack commented on robot-server/robot_server/service/labware/models.py
> +class TipData(BaseModel):
Would you want to add a doc string to the class? It would appear in the API docs.

2020-06-24 14:59 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/labware.py
> +    value: Union[Optional[float], List[float]]
To me, tagged unions would defeat the main goal of having this accept two very different types. I was hoping to use this as a generalized type since the keys would be the same, just different types for the value. I will just make two separate dataclasses.

2020-06-24 15:02 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/dev_types.py
> +    lastModified: str
nope.

2020-06-24 15:02 UTC, Laura-Danielle commented on robot-server/robot_server/service/labware/models.py
> +    value: OffsetVector = OffsetVectorField()
Can do

2020-06-24 16:13 UTC, ahiuchingau commented on api/src/opentrons/protocol_api/labware.py
> +    tip_length = CalibrationData(
Maybe you could set default values for your dataclass variables to make stuff like this simpler?
```python
@dataclass
class CalibrationData:
    value: Optional[float] = None
    lastModified: Optional[str] = None
```

2020-06-24 16:14 UTC, ahiuchingau commented on api/src/opentrons/protocol_api/labware.py
> +        mod = ''
Same thing here, see comment above

2020-06-24 16:54 UTC, amitlissack approved these changes

2020-06-24 16:54 UTC, amitlissack commented on robot-server/tests/integration/test_labware_calibration_access.tavern.yaml
> +          - attributes:
Not important for now, but if you get into writing a lot of these test and YAML in general it's worth learning about anchors and other neat features : https://learnxinyminutes.com/docs/yaml/

2020-06-24 16:56 UTC, ahiuchingau approved these changes
LGTM

2020-06-24 17:03 UTC, sfoster1 requested changes
Code looks good, but in testing it I get a 500 when trying to GET /labware/calibrations. Shortened traceback:

```
File "/usr/lib/python3.7/site-packages/robot_server/service/labware/router.py", line 108, in get_all_labware_calibrations
                                                    all_calibrations = lw_funcs.get_all_calibrations()
                                                  File "/usr/lib/python3.7/site-packages/opentrons/protocol_api/labware.py", line 1440, in get_all_calibrations
                                                    cal_blob = _read_file(str(cal_path))
                                                  File "/usr/lib/python3.7/site-packages/opentrons/protocol_api/labware.py", line 1160, in _read_file
                                                    with open(filepath, 'r') as f:
                                                FileNotFoundError: [Errno 2] No such file or directory: '/data/labware/v2/offsets/opentrons/opentrons_1_trash_1100ml_fixed/1.json'
```

2020-06-24 18:16 UTC, sfoster1 approved these changes
LGTM!

2020-06-24 18:42 UTC, merged