feat(api): define data architecture for tip length calibration in v2
OpenTrons/opentrons-api pull request #5820
Opened 2020-06-04 19:48 UTC by ahiuchingau

## overview
This PR defines new data architecture for tip length calibration data.

closes #5606

## changelog
- added a robot feature flag `enableTipLengthCalibration`
- added new dir `/data/tip_lengths` to store tip length calibration files
- new `save_tip_length_calibration` method in the protocol api labware module
   - it takes in the labware, tip length and the ID of the pipette that performed the calibration
   - saves the data in a json file with labware hash as the name, looks something like this
```
/data/tip_lengths/LABWAERE_HASH.json:

{
    PIPETTE_ID_1: {
        tipLength: 22.0,
        lastModified: 1591297770.961788},
    PIPETTE_ID_2: {
        tipLength: 25.0,
        lastModified: 1591297725.123456},
    }
}
```
- added load and clear calibration methods
- tests to make sure all of the above work

## review requests
Code sanity
How do we like the structure?

## risk assessment
low - methods are currently not hooked up anywhere yet and are all behind a feature flag

2020-06-04 20:40 UTC, sfoster1 requested changes
Inline comments. Also I think labware calibration stuff should really move to another subpackage. Anybody have good ideas on location?

2020-06-04 20:40 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +def _get_labware_tip_length_path(labware: Labware):
similar to the comments on https://github.com/Opentrons/opentrons/pull/5811, I think it's time to split some of this calibration management stuff out of the `protocol_api` subtree. We could keep it here for this PR, but if so we should do a refactor right afterwards to move it.

2020-06-04 20:40 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +def load_tip_length_calibration(labware: Labware, pip_id: str):
needs a return type annotation

2020-06-04 20:40 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +    if ff.enable_tip_length_calibration():
not sure i like having this feature flag here - it means we can't test this function without setting the flag. i think it's better to check the feature flag in whatever _calls_ this function.

2020-06-04 20:40 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +    if ff.enable_tip_length_calibration():
same re: feature flag location

2020-06-04 20:41 UTC, Laura-Danielle commented
Posting for visibility. @ahiuchingau and I had a conversation about the file structure in slack. Please put a thumbs up if you agree or comment if you think we should do something different and/or additional

We decided to implement the following:
1. Inside the tip lengths folder, all files with calibrations would be stored under the pipette serial number. Each file would have multiple entries mapping labware hash -> tip length value
2. There should be an index file which maps labware hashes -> valid pipette serial numbers for that particular labware so that we can easily map tip length calibrations to tiprack + pipette combos (to eventually be used on whether you can skip calibration or not).

2020-06-04 20:41 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/labware.py
> +def _get_labware_tip_length_path(labware: Labware):
Would it be weird to put them in the top level calibration folder under labware?

2020-06-04 21:02 UTC, amitlissack requested changes

2020-06-04 21:02 UTC, amitlissack commented on api/tests/opentrons/protocol_api/test_offsets.py
> +        labware.save_tip_length_calibration(test_labware, tip_length_1,
As I mentioned above about breaking `save_tip_length_calibration`, you don't need to test that `json.dump` works. You really just care that `test_labware` and `tip_length_1` are stored correctly in some data structure, right?

Your unit test could be much smaller.

2020-06-04 21:02 UTC, amitlissack commented on api/tests/opentrons/protocol_api/test_offsets.py
> +        # update tip length data for same labware: same pipette
Also, I recommend breaking this into several unit tests. Each with its own descriptive name.

2020-06-04 21:04 UTC, amitlissack commented on api/src/opentrons/protocol_api/labware.py
> +def _get_labware_tip_length_path(labware: Labware):
i put calcheck stuff in `opentrons.calibration.check`. The idea being that we could have other packages as `opentrons.calibration.tip_length` etc.

2020-06-05 13:54 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +def _get_labware_tip_length_path(labware: Labware):
So the thing that makes this weird to me is that the protocol api labware structure is on some level a consumer of calibration data. _Executing_ calibration is certainly not the job of the protocol api, and should be a job of the server, but we want the protocol api or its structure anyway to be able to _consume_ calibration data still. To do this would I think requires injecting some calibration provider entity - which I guess is completely reasonable, but maybe outside the scope of this PR.

2020-06-08 16:48 UTC, sfoster1 commented
A lot of the comments about refactors around where calibration lives also apply to #5811, let's do those refactors after we merge these two prs

2020-06-10 18:54 UTC, sfoster1 requested changes
Some small changes around path and date handling, but  given that we're going to do the refactor to pull calibration out of protocol api in a followup this lgtm otherwise.

2020-06-10 23:59 UTC, ahiuchingau commented on api/src/opentrons/protocol_api/labware.py
> +TipLengthCalibration = Dict[str, float]
I had to make the last modified key to be a string as the datetime value needed to be stringified

2020-06-11 15:13 UTC, sfoster1 requested changes
Sorry for being a stickler about time formatting but we really need it to be consistent or we'll get ourselves into a nasty place pretty quickly. Let's make a standard time format, put it in a common utils file or something, and then never think about it again.

2020-06-11 15:13 UTC, sfoster1 commented on api/src/opentrons/protocol_api/dev_types.py
> +    lastModified: str
The idea here is that when this is loaded into memory, it's always a `datetime`. It's only a string when written to desk. We can load it with `strptime`.

2020-06-11 15:13 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +        'lastModified': datetime.utcnow().strftime("%B %d %Y, %H:%M:%S")
This needs to be formatted to iso-8601, which is YYYY-MM-DDTHH:MM:SS (number months). We should also take the format string specifier and put it in a common file.

2020-06-11 15:59 UTC, b-cooper commented on api/src/opentrons/protocol_api/labware.py
> +        'lastModified': datetime.utcnow().strftime("%B %d %Y, %H:%M:%S")
There's a function for that! https://docs.python.org/2/library/datetime.html#datetime.datetime.isoformat

2020-06-11 17:54 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +        'lastModified': datetime.utcnow().strftime("%B %d %Y, %H:%M:%S")
Yay! let's use that

2020-06-12 13:53 UTC, sfoster1 requested changes
One more tiny change

2020-06-12 13:53 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +            return obj
I think we should probably let these raise, otherwise we'll get some _very_ strange type confusions out of misformatted dicts. We should handle the possible errors in the decode, and just remove the calibration.

2020-06-12 14:28 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +            return obj
Oh, I didn't understand that swallowing these errors is required because they get called on all values. Let's keep swallowing the errors, but assert that the value decoded properly afterward.

2020-06-15 13:45 UTC, sfoster1 approved these changes
LGTM! Nice

2020-06-15 13:54 UTC, amitlissack approved these changes
awesome possum!

2020-06-15 14:38 UTC, Laura-Danielle approved these changes
Nice

2020-06-15 14:50 UTC, merged