feat(api, docs): add GPIO rail lights and door control to ProtocolContext
OpenTrons/opentrons-api pull request #5862
Opened 2020-06-09 20:59 UTC by ahiuchingau

## overview
This PR adds robot rail lights control and allows monitoring of the robot light and door state to ProtocolContext, and bumps the max protocol API version to 2.5.

closes #5775 and closes #5703 

Note: GPIO control does not work on Jupyter Notebook

## changelog
- added the method `set_rail_lights()` and two properties `rail_lights_on` and `door_closed`
- updated docs to reflect the new changes

## risk assessment
Low

2020-06-09 21:03 UTC, sfoster1 approved these changes
LGTM! I think we should keep richer gpio interfaces on the table for future ux work though - allowing access to more pins, having interesting primitives like waiting for a pin to change, something like that.

2020-06-09 21:06 UTC, ahiuchingau commented
@sfoster1 Totally agreed! Definitely something we should do in the near future

2020-06-09 21:21 UTC, b-cooper approved these changes
This is a great addition.  The documentation look thorough too 🍨 

I had a thought, I don't know if we document this elsewhere, but perhaps this would be a good place to have a `NOTE:` that explains that the top window and door must both be closed in order for the robot to report the door is closed? Just looking forward to the gotcha's the first time some one tries to use the door switch boolean without a top panel on their OT-2.

2020-06-09 21:24 UTC, SyntaxColoring commented
> I had a thought, I don't know if we document this elsewhere, but perhaps this would be a good place to have a NOTE: that explains that the top window and door must both be closed in order for the robot to report the door is closed? Just looking forward to the gotcha's the first time some one tries to use the door switch boolean without a top panel on their OT-2.

Is that true? I didn't even realize the OT-2 had a way of detecting the presence of the top panel.

2020-06-09 21:33 UTC, Laura-Danielle requested changes

2020-06-09 21:33 UTC, Laura-Danielle commented on api/docs/v2/new_atomic_commands.rst
> +The door safety switch feature flag has been added to the OT-2 software since the 3.19.0 release. Enabling the feature flag allows your robot to pause a running protocol and prohibit the protocol fro
Maybe we can put a screenshot of where the feature flag is located? There are a few places that we have "feature flags" that might be confusing for the user.

2020-06-09 21:33 UTC, Laura-Danielle commented on api/docs/v2/versioning.rst
> +    - :py:attr:`.ProtocolContext.door_closed`: describes whether the robot door is closed
I'm a little worried about users trying to use the `door_closed` method + have the feature flag switched on.

Should we maybe put a note stating you should use one or the other to control robot behavior and/or only use this method to do a status check?

2020-06-09 21:35 UTC, ahiuchingau commented
@b-cooper good call! I'll add it in!

@SyntaxColoring Yes - the top panel and the front panel switches are connected in series to the same GPIO pin. After OT-2 refresh, we will be able to identify which panel is open in new robots because they will be connected to separate pins.

2020-06-09 22:22 UTC, Laura-Danielle approved these changes
**N I C E**

2020-06-10 13:32 UTC, sfoster1 requested changes
Some interlinks in the docs don't quite work, they display in the interlink font-face but aren't actually links. According to [this random stackexchange answer](https://stackoverflow.com/questions/27170958/sphinx-documentation-how-to-reference-a-python-property) we may need to use `:py:obj:` to link to props across pages

2020-06-10 15:11 UTC, sfoster1 approved these changes
Nice! Thanks for fixing it.

2020-06-10 15:12 UTC, merged