refactor(protocol-designer): Update confirm unsaved step deletion modals
OpenTrons/opentrons-api pull request #5877
Opened 2020-06-10 20:41 UTC by Kadee80

## overview

closes #5762 by updating the Pristine Step Deletion Modal. It also adds an optional buttons override prop to the cancel continue modal (to update button text)

## changelog

- refactor(protocol-designer): Update confirm unsaved step deletion modals

## review requests

- [ ] Clicking off an unsaved step (creating another new step) -> modal has updated text, header, and button text
- [ ] Clicking close on an unsaved step -> modal has updated text and header

## risk assessment
Low, but please confirm i didn't break any other cancel/continue modals

2020-06-11 14:41 UTC, shlokamin requested changes
Looks solid! A few things:

(1) One small flow nitpick with `$Diff`
(2) The lines seem a bit close together right? Is this intended?

<img width="601" alt="Screen Shot 2020-06-11 at 10 22 28 AM" src="https://user-images.githubusercontent.com/5788529/84400274-d5193380-abcf-11ea-8aac-b99e9c8c8956.png">

2020-06-11 14:42 UTC, Kadee80 commented on components/src/modals/ContinueModal.js
> +  ...$Diff<AlertModalProps, { buttons?: mixed }>,
will look into this

2020-06-11 14:43 UTC, Kadee80 commented
> Looks solid! A few things:
> 
> (1) One small flow nitpick with `$Diff`
> (2) The lines seem a bit close together right? Is this intended?
> 
> <img alt="Screen Shot 2020-06-11 at 10 22 28 AM" width="601" src="https://user-images.githubusercontent.com/5788529/84400274-d5193380-abcf-11ea-8aac-b99e9c8c8956.png">

Will update css

2020-06-11 14:47 UTC, IanLondon commented on components/src/modals/ContinueModal.js
> +  const buttonOverride = props.buttons && props.buttons.length > 0
I thought of ContinueModal as "AlertModal with cancel and continue buttons", so it seems a little weird to make ContinueModal allow you to override its buttons bc then you're really just using AlertModal right? Or is ContinueModal doing something more than the buttons?

2020-06-12 14:38 UTC, IanLondon approved these changes
LGTM! 

Note: copy doesn't match ticket (it's `If you continue without saving` here and in ticket it's `If you navigate away without saving`) but I'm assuming that's a Morgan-approved copy change?

2020-06-12 14:38 UTC, IanLondon commented on protocol-designer/src/components/StepCreationButton.js
> +            <p style={{ lineHeight: 1.5 }}>
inline style?! :scream_cat: lol

2020-06-12 14:39 UTC, Kadee80 commented on protocol-designer/src/components/StepCreationButton.js
> +            <p style={{ lineHeight: 1.5 }}>
yeah F it lol

2020-06-12 14:44 UTC, shlokamin approved these changes
✅

2020-06-12 14:49 UTC, merged