Fix simulate with real config
OpenTrons/opentrons-api pull request #5908
Opened 2020-06-15 15:20 UTC by Laura-Danielle

## overview

Closes #5774 and closes #5829. Support noticed that the labware height error would often get thrown during simulation for certain combinations of pipettes + labware. This is because simulation does not actually use a valid deck transform for any operation checks.

If the labware height error is going to be useful outside of the robot, we should simulate using a valid transform.

Making this a draft PR because I wanted to get feedback.

## changelog

- Modify tests to get them passing
- Add in a valid deck transform to simulation

## review requests

Wasn't sure what the best way to categorize the deck transform change was for tests. I feel like it's a little confusing for the home position to be 243, for example, instead of 218.

You can test that simulation works with any of the protocols referenced in the tickets.

## risk assessment

Low, just changes for simulation.

2020-06-15 19:32 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/api.py
> +            [0.0, 0.0, 0.0, 1.0]]
Should we check to see if it's simulating on an actual robot? We should only use this simulator calibration if it's not.

2020-06-15 19:35 UTC, sfoster1 requested changes

2020-06-15 19:35 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        await api_instance.update_config(
This is not the right way to go about this, I think.

In the normal case, where all of this is running on a robot, we load the config from disk. That way, the simulator shares the deck calibration (among other things) that the real  hardware controller is using, so the simulator behaves the same as the real hardware controller. Overwriting the simulator calibration here actually removes that, and all simulators - including those on the robot - would use this identity-but-with-correct-z-offset setup.

The corner case of running simulation outside of a robot, where no correct deck calibration (or for that matter instrument calibration) can exist, is where the problem arises. So the solution is probably actually in the config module, to correctly detect
a) i'm loading a config on something that isn't a robot
b) the config i'm loading is identity (adding this check lets people copy over their robot config, or alter it manually for whatever purpose)

and, _only in that case_, apply the identity-with-z-offset.

Really, the longer term fix is that if identity is a completely invalid calibration - rather than right in the general case but probably needs tuning through the normal calibration process to be suitable for the robot - then it shouldn't be the default, the identity-with-z-offset should be. But for the quick fix, patching it in in the above cases is probably the right move.

2020-06-15 19:46 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +        await api_instance.update_config(
yep that makes sense.

2020-06-15 22:46 UTC, SyntaxColoring commented
Just FYI in case this affects your solution exploration at all:

It looks like customers are also seeing `LabwareHeightError` problems on *robots* simulating protocols—not just when using `opentrons_simulate`. We'll post more information as we learn more.

2020-06-18 13:10 UTC, sfoster1 requested changes

2020-06-18 13:10 UTC, sfoster1 commented on api/src/opentrons/config/robot_configs.py
> +    if not IS_ROBOT and not api_v1 and not deck_cal_to_check:
we should also check if the deck calibration is the identity and not override it if not - we want to allow people to copy their robot's deck calibration over if they want to.

2020-06-18 13:10 UTC, sfoster1 commented on api/src/opentrons/config/robot_configs.py
> +    if not IS_ROBOT and not api_v1 and not deck_cal_to_check:
Also why not load the offset for v1?

2020-06-18 13:10 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +
intentional?

2020-06-18 13:10 UTC, sfoster1 commented on api/tests/opentrons/cli/test_cli.py
> +    # This test would only be valid on a robot now.
then we should mock setting  IS_ROBOT=true and test it here

2020-06-18 13:10 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/test_moves.py
> +    c._config = c._config._replace(
these kind of per-test changes are a little gross especially uncommented - we should m ake it a fixture, and also consider just using the fixture that sets IS_ROBOT

2020-06-18 13:26 UTC, Laura-Danielle commented on api/src/opentrons/config/robot_configs.py
> +    if not IS_ROBOT and not api_v1 and not deck_cal_to_check:
The labware height error is only in v2, so we don't need to make this change for v1.

2020-06-18 13:27 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +
nope

2020-06-18 19:21 UTC, sfoster1 approved these changes
lgtm!

2020-06-18 20:00 UTC, merged