feat(labware-library): avoid adding info to 'group' field in LC
OpenTrons/opentrons-api pull request #5975
Opened 2020-06-22 20:52 UTC by IanLondon

## overview

Closes #5801

## changelog

* ensures Labware Creator doesn't save extra fields to `group` field (ideally, aluminum block + tuberack would allow user to give display name + display category + brand that differs from)
* also ensures via unit tests that these rules are followed for fixtures and Opentrons standard labware definitions.
* updates fixtures that did not follow 'group' rules

## review requests

- [ ] Check labware library labware pages. LL pages for **aluminum blocks and tube racks** should look the same as LL prod (just compare a few random ones)
- [ ] Check labware library labware pages. LL pages for **well plates and reservoirs** should look the same as LL prod (just compare a few random ones)
- [ ] For any labware you make in LC (tube rack, well plate, reservoir, aluminum block), it should not include `group.brand`, `group.metadata.displayName`, or `group.metadata.displayCategory` (see jest integration test diff)
- [ ] Code review, esp of new unit tests for labware standard defs + fixtures. Does this capture what the 'group' rules are supposed to be?

- Note that there is one standard labware that violates the `groups` rule, it's exempted in the new unit tests

## risk assessment

2020-06-23 15:28 UTC, mcous requested changes

2020-06-23 15:28 UTC, mcous commented on labware-library/src/labware-creator/fieldsToLabware.js
> +      // Since LC doesn't allow the user to specify any of these 3 fields for wells themselves, we'll omit them
The user does, in fact, specify the display category for the tube rack and aluminum block. Following our existing definitions and the prompts shown to the user in labware creator, I think `group[].displayCategory` should be:

- Left unspecified for well plates and reservoirs
- Set to `tubeRack` for tube racks
- Set to `tubeRack` or `wellPlate` for aluminum block depending on how the user answers this prompt:
    <img width="390" alt="Screen Shot 2020-06-23 at 11 25 51 AM" src="https://user-images.githubusercontent.com/2963448/85423155-5f548680-b544-11ea-9240-bbb9f51706e7.png">

2020-06-23 15:28 UTC, mcous commented on shared-data/js/__tests__/labwareDefSchemaV2.test.js
> +  test(`${filename} should not contain "groups.brand.brand" that matches the top-level "brand.brand"`, () => {
Should these two tests be `it` instead of `test`?

2020-06-23 15:48 UTC, IanLondon commented on shared-data/js/__tests__/labwareDefSchemaV2.test.js
> +  test(`${filename} should not contain "groups.brand.brand" that matches the top-level "brand.brand"`, () => {
linter doesn't like `it`, prefers `test` (???) inside this fn

2020-06-23 19:03 UTC, mcous commented on shared-data/js/__tests__/labwareDefSchemaV2.test.js
> +  test(`${filename} should not contain "groups.brand.brand" that matches the top-level "brand.brand"`, () => {
Maybe because, according to the syntax tree, they are outside of a `describe`?

2020-06-23 19:09 UTC, mcous approved these changes

2020-06-23 19:09 UTC, mcous commented on labware-library/src/labware-creator/__tests__/_getGroupMetadataDisplayCategory.test.js
> +  it('should return null for wellPlate', () => {
Do we need a test for reservoir?

2020-06-23 20:00 UTC, Kadee80 approved these changes
🦝

2020-06-23 20:58 UTC, Laura-Danielle reviewed
Just a comment, but otherwise looks good.

2020-06-23 20:58 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/execute_v4.py
> +    sorted_modules = sorted(
why does the sorting order need to be stable?

2020-06-24 14:36 UTC, IanLondon commented on api/src/opentrons/protocol_api/execute_v4.py
> +    sorted_modules = sorted(
d'oh, that change was not supposed to get in this PR. It's for eventual multiple modules support, but should be part of another PR. Thanks for noticing! Yikes

2020-06-24 15:38 UTC, merged