refactor(app): tip length calibration: introduction screens
OpenTrons/opentrons-api pull request #6034
Opened 2020-06-30 16:39 UTC by ahiuchingau

# Overview
This PR builds the introduction screens for tip length calibration. 

NOTE: this does not adds or utilizes the real session yet

# Changelog
- introduce `haveBlock` to CalibrateTipLengthParentProps
- fill out Introduction.js
- add rendered calibration block image as a placeholder
- add ConfirmExitModal.js, to be implemented to the exit button

# Review requests
Make sure you have enabled the tip length calibration in the Advanced Settings in the app
1. Upload any protocol, go to the calibrate page
    It should says `[mount] Pipette Tip Length Calibration`, see [design](https://www.figma.com/file/SHavJVuFOvV6Cq1kPgY47W/Calibration-Overhaul-Tip-Length-Calibration?node-id=2%3A0)
2. Update the `currentStep` from an empty string to `sessionStarted` in the `mockTipLengthCalibrationSessionDetails`
    You should see an alert modal, see [design](https://www.figma.com/file/SHavJVuFOvV6Cq1kPgY47W/Calibration-Overhaul-Tip-Length-Calibration?node-id=4%3A3)
3. Update `haveBlock` in CalibrateTipLength/index.js from `null` to `true
    You should see a modal page showing the required p300 tip rack (required for the mock session) and the calibration block,
see [design](https://www.figma.com/file/SHavJVuFOvV6Cq1kPgY47W/Calibration-Overhaul-Tip-Length-Calibration?node-id=2%3A619) 

# Risk assessment
low - behind a feature flag

2020-07-01 17:18 UTC, b-cooper requested changes
Overall looks great 🛸 

I've got a couple of suggestions about copy and style, but other than that the only thing that needs fixing is the margin of the intro modal at the default viewport. The modal window isn't taking up as much space as it does in the design and it's causing the text to wrap prematurely.

<img width="1026" alt="Screen Shot 2020-07-01 at 12 15 27 PM" src="https://user-images.githubusercontent.com/4731953/86272745-13858b00-bb9d-11ea-99aa-ae4f441f0c88.png">

2020-07-01 17:18 UTC, b-cooper commented on app/src/components/CalibrateTipLength/Introduction.js
> +          <a
Is there a reason you swapped out the `<Link external />` component usage for a raw `<a></a>` tag here?  I think that 
```
<Link external href={`${LABWARE_LIBRARY_PAGE_PATH}/${tiprack.loadName}`}>. 
   {VIEW_TIPRACK_MEASUREMENTS}
</Link>
```

provides the exact same functionality.

2020-07-01 17:18 UTC, b-cooper commented on app/src/components/CalibrateTipLength/styles.css
> +  font-size: var('--fs-body-2');
Here an below, instead of just setting the font-size to the variable from typography.css we probably want the whole mixin for font-body-2-dark. 

e.g.
```
.intro_content {
  @apply --font-body-2-dark;

  margin-bottom: 1rem;
}
```

that way we are explicit about what font weight and color the text should be as well.

2020-07-01 17:18 UTC, b-cooper commented on app/src/components/CalibrateTipLength/styles.css
> +.tipracks_note_emphasized_body {
I think this style is unused?

2020-07-01 17:18 UTC, b-cooper commented on app/src/components/CalibrateTipLength/styles.css
> +.tipracks_note_div {
Nit: If `.tipracks_note` or `.tipracks_note_wrapper` works just as well, it keeps the css from being logically bound to a certain html/react element like 'div'.

2020-07-01 17:18 UTC, b-cooper commented on app/src/components/calibration-info.css
> +  max-width: 55%;
Out of curiosity, why did this style need tweaking?

2020-07-01 17:18 UTC, b-cooper commented on app/src/components/CalibrateTipLength/Introduction.js
Mostly a design question, but I think this main modal is meant to have a Header "Tip Length Calibration". I noticed it's missing on one of the versions in figma.  It's probably worth checking with design

2020-07-01 18:09 UTC, mcous commented on app/src/components/CalibrateTipLength/Introduction.js
> +      <div className={styles.tipracks_note_div}>
This can be a primitive <Flex>

```js
<Flex
  marginTop={SPACING_3}
  marginBottom={SPACING_4}
  flexDirection={DIRECTION_COLUMN}
  alignItems={ALIGN_FLEX_START}
  position={POSITION_RELATIVE}
>
```

(See other comment about `POSITION_RELATIVE` maybe not being necessary)

2020-07-01 18:09 UTC, mcous commented on app/src/components/CalibrateTipLength/styles.css
> +  position: relative;
Why is `position: relative` applied here? I don't see any `position: absolute` children

2020-07-01 18:09 UTC, mcous commented on app/src/components/CalibrateTipLength/styles.css
> +  position: relative;
Why is `position: relative` applied here? I don't see any `absolute` children

2020-07-01 18:09 UTC, mcous commented on app/src/components/CalibrateTipLength/Introduction.js
> +  const tiprackID =
Why is `hasBlock` passed in as a prop but the tip rack has to be pulled from the session? This component is fairly presentational, so I think the `hasBlock` approach is better than forcing this component to understand anything about the sessions API

2020-07-01 18:37 UTC, b-cooper commented on app/src/components/CalibrateTipLength/Introduction.js
> +            <div className={styles.button_spacer} />
✋ I suggested the use of a spacer component here over a margin.  Firstly, I think there are many ways to skin this cat and "avoid spacer elements in general" could just as well be "avoid margin in general" (see article posted in #js a while back: https://mxstbr.com/thoughts/margin).

In conclusion, I think until we standardize some type of `gutter` prop or mechanism as a _wrapping_ component concern (maybe in `Flex` or `Box`), this solution to spacing is just as good as any.

2020-07-01 21:34 UTC, ahiuchingau commented on app/src/components/calibration-info.css
> +  max-width: 55%;
Whoops I was testing something and forgot to revert this back

2020-07-01 22:09 UTC, ahiuchingau commented on app/src/components/CalibrateTipLength/index.js
> +const buildTitleBarProps = (): TitleBarProps => {
Yes it was - I will remove it

2020-07-02 14:02 UTC, mcous commented on app/src/components/CalibrateTipLength/Introduction.js
> +            <div className={styles.button_spacer} />
@b-cooper yup, I read that article this first time around! The spacing style props in our primitives were put in place exactly to address this spacing concern. I posted this link in some of the early primitives reviews; did you get a chance to read it? It touches on spacer elements, wrapping components, and spacing props: https://styled-system.com/guides/spacing

With spacing props, this looks like:

```js
<SecondaryBtn marginRight={SPACING_3} onClick={/* ... */}>
  {HAVE_BLOCK}
<SecondaryBtn>
<SecondaryBtn onClick={/* ... */}>
  {USE_TRASH}
<SecondaryBtn>
```

2020-07-06 18:26 UTC, ahiuchingau commented on app/src/components/CalibrateTipLength/Introduction.js
> +const ALERT_TIP_LENGTH_CAL_HEADER = 'Pipette calibration has been updated!'
After looking at the [design](https://www.figma.com/file/SHavJVuFOvV6Cq1kPgY47W/Calibration-Overhaul-Tip-Length-Calibration?node-id=4%3A3) again, I think it actually makes sense that it is "Pipette calibration has been updated" as this alert is introducing tip length calibration in the user flow for the first time

2020-07-06 19:30 UTC, b-cooper commented on app/src/components/CalibrateTipLength/Introduction.js
> +const ALERT_TIP_LENGTH_CAL_HEADER = 'Pipette calibration has been updated!'
Oh wow, yeah I didn't think of it that way. I guess at some point down the road we'll want to change this header once everyone is familiar with the new tip length calibration. Thanks for clarifying!

2020-07-09 15:50 UTC, b-cooper approved these changes
Code looks good 🎲

2020-07-09 15:50 UTC, b-cooper commented on app/src/components/CalibrateTipLength/DeckSetup.js
> +  const { hasBlock } = props
🥇 I think my brain was stuck in 🐍 mode. Good catch

2020-07-09 15:50 UTC, b-cooper commented on app/src/components/CalibrateTipLength/labwareImages.js
> +  require('../../img/labware/opentrons_calibrationblock.png'),
very tiny nit: `opentrons_calibration_block.png` with the last two words separated by an underscore fits our file naming patterns more consistently.

2020-07-13 22:26 UTC, ahiuchingau commented on app/src/components/calibration-info.css
> +  max-width: 55%;
@b-cooper After the design review with Pantea, I remembered why i changed this:
When max-width is 48%, the tip length calibration title is cut short 
<img width="1092" alt="Screen Shot 2020-07-13 at 6 20 19 PM" src="https://user-images.githubusercontent.com/20424172/87359328-8dbaf580-c535-11ea-9109-6be905557047.png">

I think I can fix this by just removing the `max-width` property:
<img width="1092" alt="Screen Shot 2020-07-13 at 6 26 33 PM" src="https://user-images.githubusercontent.com/20424172/87359726-66185d00-c536-11ea-9992-0092e4b8d97d.png">

2020-07-13 22:27 UTC, ahiuchingau commented on app/src/components/CalibrateTipLength/Introduction.js
> +const ALERT_TIP_LENGTH_CAL_HEADER = 'Pipette calibration has been updated!'
Pantea is going to try to modify this header so it makes sense for both new and older users.

2020-07-14 15:30 UTC, b-cooper approved these changes
Looking great. 🦓

2020-07-14 15:30 UTC, b-cooper commented on app/src/components/CalibrateTipLength/calibrationBlockRender.js
> +export function CalibrationLabwareRender(
Because this is the main exported component in this file, I would rename the file `CalibrationLabwareRender.js`.
Note that for files that export a react component, our convention is to name the file the same as the component which is also CapitalCase.

2020-07-14 15:30 UTC, b-cooper commented on app/src/components/CalibrateTipLength/calibrationBlockRender.js
> +  return isTiprack ? (
For now, this works because we're only rendering a tiprack and a block, but if we flip this boolean logic this component will actually be prepared to render any labware. e.g.

instead of 
```
isTiprack ? <LabwareRender /> : <CalibrationBlockRender />
```
```
isCalibrationBlock ?  <CalibrationBlockRender /> : <LabwareRender />
```

This might just be worth throwing into a TODO comment that we should address in the next steps building out this flow. 

Also, I think that the Calibration Block definition is the perfect place to adopt the `layers` key of the labware schema that defines the svg paths to render (see deck definitions).  That way this component can be even more generic, and it won't have to have knowledge of a few special labware `loadNames`

2020-07-14 19:57 UTC, merged