feat(protocol-designer): only show one labware name in sidebar tooltip for TC + temp + mix steps
OpenTrons/opentrons-api pull request #6088
Opened 2020-07-08 17:52 UTC by shlokamin

# Overview

This PR closes #6061 by only showing one labware name for mix, temperature, and TC steps.

# Changelog
- Only show one labware name in sidebar tooltip for TC + temp + mix steps

# Review requests

Code review, I did some funny stuff

- [ ] Make a mix step, in the sidebar when you hover over labware there should only be one labware name
- [ ] Make a temperature step, in the sidebar when you hover over labware there should only be one labware name
- [ ] Make a TC step, in the sidebar when you hover over labware there should only be one labware name

For TC steps, validate this behavior for ending hold too

# Risk assessment
Low, just modifying tooltip text

2020-07-08 18:00 UTC, shlokamin commented on protocol-designer/src/components/steplist/StepItem.js
> +const getSingleLabwareNameProps = (
blah don't love this name

2020-07-10 15:01 UTC, IanLondon requested changes
If what we want is always just one name, `nickname || displayName`, then we can use `labwareNickname` bc it's already falling back to the displayName throughout PD

Then, we can just get rid of labwareDisplayName props across these substeps components, LabwareTooltipContents, etc

Might as well also remove all the `labwareDisplayName` props from `protocol-designer/src/steplist/types.js` various substep type defs

And  `labwareNamesByModuleId` (eg in `generateSubsteps`) can also become just `{[moduleId: string]: string` instead of `{[moduleId: string]: ?{ nickname: ?string, displayName: string }}`

Unless we feel like we might want to differentiate nickname vs labware type in substeps in the future? If we don't think we will, we can strip out a lot of complexity in passing these names thru (and can delete some test complexity too)

2020-07-12 23:55 UTC, shlokamin commented
Good point @IanLondon! I deleted a bunch of code where `labwareDisplayName` was being used. Tests seem happy and it doesn't look like I broke anything, but if you could also give this a thorough look/test that would be awesome!

2020-07-13 14:52 UTC, Kadee80 approved these changes
🔧 🦖

2020-07-13 16:53 UTC, IanLondon approved these changes
:alembic:

2020-07-13 16:58 UTC, merged