refactor(robot-server): add deck and labware to tip length calibration
OpenTrons/opentrons-api pull request #6105
Opened 2020-07-10 19:41 UTC by b-cooper

# Overview

Add relevant labware and deck management for the tip length calibration flow. Begin wiring up
hardware control commands. Build out unit tests.

# Changelog

- Add labware and deck management to the tip length calibration user flow
- Implement first hardware calls from command handlers in `pick_up_tip` and `return_tip`
- Put `preparePipette` command into the calibrationCheck commands instead of shared calibrationCommands as it isn't quite generic enough.
- Add moveToTipRack command

# Review requests

- Things are unit tested, so nothing hugely testable at the moment, can always create a session with sessionType tipLengthCalibration, but you won't get very much detail back atm.

# Risk assessment

Low, mostly unused code changed

2020-07-13 14:34 UTC, sfoster1 requested changes
Couple inline changes that could make it a bit cleaner, but overall looks good!

2020-07-13 14:34 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +        # mod geometry contexts. Ignore type checking error here.
Could get rid of some type ignores by annotating the intermediate
`tiprack: Labware = self._deck[TIP_RACK_SLOT]  # type: ignore (the only one you need)`

2020-07-13 14:34 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +    def _get_trash_lw(self) -> labware.Labware:
Specifically the initialization of the deck with the correct trash labware feels like something that could be a builder classmethod on `Deck` that is used both here, in the other calibration flows, and in the `ProtocolContext`.

2020-07-13 14:34 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +        cal_block_slot = (RIGHT_MOUNT_CAL_BLOCK_SLOT
Just a personal preference but this might be cleaner if you collapse it into some dicts:
```
# in constants
CAL_BLOCK_SETUP = {
   Mount.RIGHT: {
         'load_name': 'opentrons_calibrationblock_shortsideright`, # or whatever
         'slot': 1 # or whatever
   },
   Mount.LEFT: ....
}

# here
setup = CAL_BLOCK_SETUP[self._mount]
self._deck[setup['slot']] = labware.load(
    setup['load_name'], 
    self._deck.position_for(setup['slot']))
```

2020-07-13 22:12 UTC, ahiuchingau approved these changes
Nice - looks good to me!

2020-07-14 13:56 UTC, sfoster1 approved these changes
Nice!

2020-07-14 16:19 UTC, merged