refactor(api): Move calibration related functions out of the protocol_api
OpenTrons/opentrons-api pull request #6107
Opened 2020-07-13 11:07 UTC by Laura-Danielle

# Overview

As per comments made in both #5811 and #5820, requests were made to move file operators/calibration functions out of `labware.py` in the `protocol_api` folder.

# Changelog

- Move above functions to a `calibration_storage` folder

# Review requests

Do you like the naming conventions/new structure?

# Risk assessment

very low, just moving code around

2020-07-13 14:22 UTC, sfoster1 requested changes
Really good refactor that I'm glad we didn't let slip by!

Some general notes in addition to the inline comments:

- The new subpackage `opentrons.calibration_storage` should really have a package docstring that talks about what it's for, why it should be used, and a general pointer as to how it should be used (e.g. "To read calibrations, use the `get` module. To write them, use the `modify` module").
- We should decide now if we want to use this subpackage for just labware calibration data, or if we want to load robot calibration data in this subpackage as well. If it's just for labware calibration data, the name of the subpackage and its package docstring should reflect that. If it's for all calibration data, the functions that are relevant only to labware calibration (for instance `calibration_storage.delete.clear_calibrations`) should be named and docstring'd to match that expectation. We may change whatever decision we make about this later - and that's fine! - but this package should be opinionated from the beginning.

2020-07-13 14:22 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/file_operators.py
> +def _read_file(filepath: str):
We should also be consistent in our use of `pathlib.Path` vs `string`. the `os` modules accept `Union[str, bytes, os.PathLike[str], os.pathLike[bytes]`  (see [typeshed definition](https://github.com/python/typeshed/blob/1e0e40f61c8a4c7f905c26fcf471763c2b33257f/stdlib/2and3/_typeshed/__init__.pyi#L47) ) and we can do something similar.

2020-07-13 14:22 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/delete.py
> +from . import types as local_types, file_operators as io
Should have a nice module docstring

2020-07-13 14:22 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/get.py
> +def load_calibration(labware: 'Labware'):
This doesn't feel like an appropriate separation of concerns for this module, which is otherwise pretty much only about reading data from the filesystem. I don't think anything in `calibration_storage` should have to know about the `Labware` type beyond maybe how to hash it. For instance, I think this function should return an offset (or maybe an optional offset if we don't want to create defaults), and the function's caller in `protocol_api.labware` should be the thing that modifies the `Labware` object. In other words, make its interface much more like the tip length calibration functions elsewhere in this module.

2020-07-13 14:22 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/get.py
> +def get_tip_length_data(
Is this function called/does it need to be called outside this module? If not, it could be `_get_tip_length_data` to make it more apparent.

2020-07-13 14:22 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/helpers.py
> +import typing
Quick module docstring

2020-07-13 14:22 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/helpers.py
> +def _get_parent_identifier(
These functions are all called externally to `calibration_storage.helpers` and therefore shouldn't be named with leading underscores

2020-07-13 14:22 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/helpers.py
> +def _get_parent_identifier(
They should also have docstrings

2020-07-13 14:22 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/modify.py
> +import typing
Should have a module docstring

2020-07-14 14:48 UTC, ahiuchingau commented on api/src/opentrons/calibration_storage/types.py
> +    lastModified: str
I think this refactor would be a good time to standardize the calibration data we read from files. For example, `lastModified` here is a str but for tip length calibration is a datetime. I do feel that using the encoder-decoder to write the datatime as a str to the file and then read the str as a datatime is the better approach.

2020-07-14 17:36 UTC, Laura-Danielle commented on api/src/opentrons/calibration_storage/file_operators.py
> +def _read_cal_file(filepath: str, decoder=None) -> dict:
I was thinking we might want to potentially use another encoder/decoder at some point in time

2020-07-14 21:47 UTC, Laura-Danielle commented on api/src/opentrons/calibration_storage/get.py
> +def get_tip_length_data(
It will be called outside of the module once the new tip length calibration method is implemented.

2020-07-14 21:51 UTC, Laura-Danielle commented on api/src/opentrons/calibration_storage/file_operators.py
> +def _read_cal_file(filepath: str, decoder=None) -> dict:
I was trying to generalize these function so that they could be used with other encoders/decoders if we so chose.

2020-07-14 21:51 UTC, Laura-Danielle commented on api/src/opentrons/calibration_storage/get.py
> +def get_tip_length_data(
This function will be called once the new tip length calibration project is complete.

2020-07-15 16:24 UTC, Laura-Danielle commented
Closing as changes to this branch did not propagate here. Will open another PR.

2020-07-15 16:24 UTC, closed without merging