Tip calibration add session details and commands
OpenTrons/opentrons-api pull request #6132
Opened 2020-07-15 16:47 UTC by b-cooper

# Overview

# Changelog

# Review requests

# Risk assessment

2020-07-15 16:58 UTC, amitlissack commented on robot-server/robot_server/robot/calibration/tip_length/models.py
> +# TODO: BC: the mount field here is typed as a string
What are the serialization problems? Are they string enums?

2020-07-15 16:58 UTC, amitlissack commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +    def pipette(self) -> AttachedPipette:
Minor point really, but I would make this a function and not a property. Same as `required_labware` below. 

I might be in the minority on this, but I feel like a property should barely do more than return a member variable. These are methods that create and return new. They're not really properties.

2020-07-15 17:06 UTC, b-cooper commented on robot-server/robot_server/robot/calibration/tip_length/models.py
> +# TODO: BC: the mount field here is typed as a string
This comment is copied over from the cal check models where the `mount` enum was being serialized as the enum index as opposed to the value.  As this draft PR is still a work in progress, if you know of a way to fix it in place, I'll add it in.

2020-07-15 17:08 UTC, b-cooper commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +    def pipette(self) -> AttachedPipette:
That makes sense to me. Will make the change now.
In addition, expect some more changes on this PR as it's a WIP.

2020-07-20 16:53 UTC, amitlissack commented on robot-server/robot_server/robot/calibration/tip_length/models.py
> +    tip_length: Optional[float] =\
`tipLength`. We are doing camel case in http bodies..

2020-07-20 17:47 UTC, sfoster1 requested changes
I think we should make the `AttachedPipette` values non-optional (if tip length cal is running, there should always be a pipette).

2020-07-20 17:47 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/tip_length/models.py
> +    model: Optional[str] =\
Do these need to be optional? Tip length calibration can only be invoked on a pipette if it is present. We should never have a non-attached pipette,  and that should be enforced in the model.

2020-07-21 14:15 UTC, b-cooper commented on robot-server/robot_server/robot/calibration/tip_length/models.py
> +    tip_length: Optional[float] =\
Good catch, don't know how that slipped back in there.

2020-07-21 17:47 UTC, sfoster1 approved these changes
Python side LGTM

2020-07-21 18:26 UTC, ahiuchingau commented on app/src/pages/Calibrate/CalibrateTipLengthControl.js
> +        title={`${mount} pipette calibration`}
but this can also totally be in a separate PR!

2020-07-21 18:35 UTC, b-cooper commented on app/src/pages/Calibrate/CalibrateTipLengthControl.js
> +        title={`${mount} pipette calibration`}
Good call.  Let's add this into #6155 before when we rebase it with these changes.

2020-07-21 18:36 UTC, merged