docs(api): explain multichannel pipettes
OpenTrons/opentrons-api pull request #6175
Opened 2020-07-20 19:26 UTC by sfoster1

Adds a block of explanation about the way users should specify locations when using multichannel pipettes 

Closes #4946

2020-07-20 19:44 UTC, ethanfjones commented on api/docs/v2/new_pipette.rst
> +        # Aspirate from wells A1, A3, A5, A7, A9, A11, A13, and A15
Should this be A1, C1, D1, F1, H1, J1, L1, N1?

2020-07-20 20:19 UTC, sfoster1 commented on api/docs/v2/new_pipette.rst
> +        # Aspirate from wells A1, A3, A5, A7, A9, A11, A13, and A15
Yes. Good catch. I will never get columns vs wells and numbers vs letters. right the first time as long as I live

2020-07-20 22:49 UTC, nickcrider requested changes
I think this will be super helpful to users! Thanks so much for pulling this together!

Just one correction in the example code for the 384-well and then the rest are style comments.

2020-07-20 22:49 UTC, nickcrider commented on api/docs/v2/new_pipette.rst
> +multi-channel pipettes, commands treat the *backmost channel* of a
I would say this as `...the *backmost channel* (closest to the back of the robot) of a...`
for avoidance of doubt

2020-07-20 22:49 UTC, nickcrider commented on api/docs/v2/new_pipette.rst
> +:py:meth:`Well.bottom`) can be applied to the single specified well.
Delete `to the single specified well`
while technically correct, it could confuse readers as they're thinking about all 8 nozzles working on the entire column.

2020-07-20 22:49 UTC, nickcrider commented on api/docs/v2/new_pipette.rst
> +between the nozzles of a multi-channel pipette means that a multi-channel
Use `spacing` instead of `space`

2020-07-20 22:49 UTC, nickcrider commented on api/docs/v2/new_pipette.rst
> +        right.dispense(300, plate['A2'])
Shouldn't this be ` right.dispense(300, plate['B1'])`

2020-07-20 22:50 UTC, nickcrider commented on api/docs/v2/new_pipette.rst
> +multi-channel pipettes, commands treat the *backmost channel* of a
or `(furthest from the door)` ??

2020-07-21 13:05 UTC, sfoster1 commented on api/docs/v2/new_pipette.rst
> +multi-channel pipettes, commands treat the *backmost channel* of a
I like `(furthest from the door)` personally, `(closest to the back of the robot)` feels redundant

2020-07-21 13:07 UTC, sfoster1 commented on api/docs/v2/new_pipette.rst
> +:py:meth:`Well.bottom`) can be applied to the single specified well.
Well, that's the distinction I'm trying to make. How about

```
This also means that offset changes (such as .top or .bottom) can be applied to the specified well, and each channel of the multichannel pipette will be located at the specified position relative to the well it is over.
```

2020-07-21 13:07 UTC, sfoster1 commented on api/docs/v2/new_pipette.rst
> +        right.dispense(300, plate['A2'])
[internal screaming]

2020-07-21 13:53 UTC, nickcrider commented on api/docs/v2/new_pipette.rst
> +:py:meth:`Well.bottom`) can be applied to the single specified well.
I like this way of explaining it!

2020-07-21 13:53 UTC, nickcrider approved these changes

2020-07-21 14:14 UTC, Laura-Danielle approved these changes
Looks good to me. If you want, it might also be helpful to leave a blurb about how aspiration/dispense is controlled by one motor -- have seen some customers be a little confused about that.

2020-07-21 17:45 UTC, merged