feat(protocol-designer): add air gap command creator
OpenTrons/opentrons-api pull request #6179
Opened 2020-07-20 22:25 UTC by shlokamin

# Overview

This PR closes #6053 by adding an air gap command creator.
# Changelog

Example changelog:
- Add air gap command creator

# Review requests
It's not hooked up yet so really just a thorough code review.

- try to think through any errors that might occur, I took all from `aspirate` and I can't think of any others
- make sure unit tests cover all error cases

# Risk assessment

Low

2020-07-21 16:04 UTC, IanLondon requested changes
Looks good! Only thing missing that I can see is handling `pipetteDoesNotExist` and `labwareDoesNotExist`?

2020-07-21 16:05 UTC, IanLondon commented on protocol-designer/src/step-generation/commandCreators/atomic/airGap.js
> +  const actionName = 'aspirate'
should be `airGap`

2020-07-21 16:29 UTC, shlokamin commented on protocol-designer/src/step-generation/commandCreators/atomic/airGap.js
> +  const actionName = 'aspirate'
AHHH thank you 🤦🏽‍♂️

2020-07-21 17:21 UTC, IanLondon approved these changes
:small_airplane: :space_invader:

2020-07-23 14:19 UTC, Kadee80 approved these changes
🐤

2020-07-23 14:23 UTC, merged