refactor(robot-server): tip length calibration: move pip to ref location and save offsets
OpenTrons/opentrons-api pull request #6180
Opened 2020-07-21 01:56 UTC by ahiuchingau

# Overview
Fill out the `move_to_reference_point` and `save_offset` commands for tip length calibration user flow.

# Changelog
- added safety buffer for reference points (z=5 mm)
- determined the reference points:
    - trash bin location: slot 12 offset + (x=25mm, y=25mm, z=trash's highest Z)
    - calibration block location: 
- updated `CAL_BLOCK_SETUP_BY_MOUNT` by adding well name based on the pipette mount
- save_offset() now saves the `TipCalibrationUserFlow._nozzle_z_offset` during measuringNozzleOffset state,
   which is then used to calculate the tip length during measuingTipOffset
- added more tests

# Review requests
I struggled with mypy and had to ignore the type to pass the check:

user_flow.py: line 115
```
calblock: labware.Labware = self._deck[slot]  # type: ignore
```
I understand that `self._deck[slot]` returns a DeckItem instead of a labware. I just couldn't figure out mypy didn't raise for this:

same file: line 154
```
tiprack: labware.Labware = self._deck[TIP_RACK_SLOT]
```

What am I missing?

# Risk assessment
low - new changes are behind a feature flag

2020-07-21 14:44 UTC, sfoster1 requested changes
Some comments on the code (I haven't tested yet) but It's nice to see all our previous calibration work pay off in the simplicity of the actual calibration part!

2020-07-21 14:44 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
>      async def move_to_reference_point(self, *args):
looks like we don't need `*args` heree, might as well remove it

2020-07-21 14:44 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +            calblock: labware.Labware = self._deck[slot]  # type: ignore
this is the right thing to do. mypy doesn't complain about the lower location I think because the function is untyped... which seems like an oversight.

One way to get rid of the type: ignores would be a refactor to deck that add some methods like
```
def labware_in(self, slot: DeckLocation) -> Labware:
    assert isinstance(self[slot], Labware), f'The item in {slot} is not a labware')
    return self[slot]  # type: ignore
```
and similar for other deck item union members

2020-07-21 14:44 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +            point = trash._offset._replace(z=trash_height) + \
Drilling down into `_offset` is a bit weird to me. Couldn't we use `.top()` here and then modify the location returned there?

2020-07-21 14:44 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +        return Location(point, None)
Why set the associated labware to `None`? shouldn't it be the trash?

2020-07-21 14:44 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +            calblock: labware.Labware = self._deck[slot]  # type: ignore
(doesn't have to be this pr, and arguably probably shouldn't be)

2020-07-21 14:44 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +            cur_pt = await self._hardware.gantry_position(self._mount)
I think this needs to track the critical point, because if this is a multichannel we should be using `FRONTMOST_NOZZLE`

2020-07-21 14:44 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +        self._nozzle_z_offset = None
Could we call this something like `nozzle_height_at_reference` or something? `nozzle_z_offset` doesn't feel quite right, it's a position rather than an offset

2020-07-21 14:44 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +    async def _calculate_tip_length(self):
return type annotation please

2020-07-21 15:34 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +                self._deck[TIP_RACK_SLOT]._definition, TIP_RACK_SLOT,
Not sure what we want to do about this, but since we don't currently save calibrations in relation to the slot the parent should actually be an empty string.

I also don't know that we'll ever reference tipracks per slot for tip length definitions. Maybe we should just remove the need for a parent entirely? @sfoster1 do you have any thoughts on this?

2020-07-22 00:42 UTC, ahiuchingau commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +            point = trash._offset._replace(z=trash_height) + \
How about using `deck.position_for(trash.parent)` instead, to return the location of slot 12's bottom left corner?

2020-07-22 02:20 UTC, ahiuchingau commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +                self._deck[TIP_RACK_SLOT]._definition, TIP_RACK_SLOT,
I 100% agree with you Laura.

When `create_tip_length_data()` was first created, it didn't care about the slot (see #5820).

The `parent_id` was generated using `get_parent_identifier()` in labware.py which returns an empty string when the tip rack is the only labware in the slot. That should almost always be the case anyway. I only kept the parent ID there in case someone wants to create a custom labware to hold the tiprack for whatever reason.

I can put up a separate PR that nukes the entire idea of saving the parent id in the labware hash, or updates `create_tip_length_data` to reflect the old behavior. Though I'm in favor of the latter

2020-07-22 13:31 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +            point = trash._offset._replace(z=trash_height) + \
Given that we're moving to a position on the trash labware I would prefer to base it on the labware rather than the slot

2020-07-22 13:34 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +                self._deck[TIP_RACK_SLOT]._definition, TIP_RACK_SLOT,
I don't think we need anything other than the labware hash for tip length calibration, no. We definitely need to not set the parent slot. I think in this PR we should just not set it, and maybe in a future refactor we can remove it.

2020-07-22 13:35 UTC, sfoster1 approved these changes

2020-07-22 13:35 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/tip_length/constants.py
> +TRASH_REF_POINT_OFFSET = Point(26, 33, 0)  # offset from corner of slot 12
It's a bit gross to me to do this because this really is relative to the labware

2020-07-22 13:39 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +                self._deck[TIP_RACK_SLOT]._definition, TIP_RACK_SLOT,
Sounds good to me

2020-07-22 14:38 UTC, ahiuchingau commented on robot-server/robot_server/robot/calibration/tip_length/constants.py
> +TRASH_REF_POINT_OFFSET = Point(26, 33, 0)  # offset from corner of slot 12
Ok will make the offset relative to the top of the trash instead

2020-07-22 20:31 UTC, merged