fix(api, app): Clear instrument offset before performing deck calibration
OpenTrons/opentrons-api pull request #6208
Opened 2020-07-23 21:17 UTC by Laura-Danielle

# Overview

Closes #5022 by resetting instrument offset for all pipettes any time a new deck calibration begins. Some design changes were also added in the app by following instructions from [this design](https://app.zeplin.io/project/5aa97729db58a2192f10d0d6/screen/5f174015bc047a778385eb90).

# Changelog

- Add messaging in deck cal CLI about re-doing pipette calibration (instrument offset does not get taken into account here because robot settings/deck cal are reset before beginning the program)
- Modify the app according to the design above
- The robot _no longer_ restarts after a deck calibration
- Reset instrument offset in `endpoints.py` and reload the current pip instrument offset to be (0, 0, 0)
- Remove feature flags for v1 in `endpoints.py` as it's no longer relevant

# Review requests

Please check that the code place for resetting instrument offset etc are OK.

# Test Plan

1. Before putting this PR on a robot, perform a robot app deck calibration with crazy large instrument offset (10 in z for example)
    - check that you get a weird-ish deck calibration (i.e. larger/smaller than normal Z component)
2. Put this PR on a robot, perform robot app calibration with same crazy large instrument offset above
    - check that robot does not restart
    - check that instrument offset is cleared out after completing deck calibration
    - check that deck calibration transform looks more normal
    - run the calibrate to crosses protocol (WITHOUT RESTARTING ROBOT) and calibrate your pipettes. Check that the robot looks pretty accurate.

Let me know if you have any other questions!

# Risk assessment

Medium. There was concern that customers would be confused by the new messaging at the end of the deck calibration program in the app. Please make sure we are OK with this language before merging.

2020-07-23 21:52 UTC, sfoster1 requested changes
Python side looks good (haven't tested though) but we should change the FE copy a bit

2020-07-23 21:52 UTC, sfoster1 commented on app/src/components/CalibrateDeck/AttachTip.js
> +          Please note that as a result of the new deck calibration data, your
Maybe cut this para as discussed yesterday? I think just the final para ("In order to effectively use..." is enough of a warning.

2020-07-23 21:53 UTC, Laura-Danielle commented on app/src/components/CalibrateDeck/AttachTip.js
> +          Please note that as a result of the new deck calibration data, your
Ah ok, I misunderstood. Will remove it.

2020-07-24 12:49 UTC, sfoster1 approved these changes
LGTM pending QA and UX review

2020-07-27 21:02 UTC, nusrat813 approved these changes
Tested - working as intended

2020-07-28 13:16 UTC, pantslakz approved these changes

2020-07-28 13:19 UTC, merged

2020-07-28 15:06 UTC, SyntaxColoring commented
@Laura-Danielle 

> by resetting instrument offset for all pipettes any time a new deck calibration begins

If you start and then abort a deck calibration, is the pipette calibration still cleared? (If so, I don't think it would be a big problem—just looking out for surprises.)