fix(robot-server): correct return tip height, only load block when present
OpenTrons/opentrons-api pull request #6224
Opened 2020-07-27 23:16 UTC by b-cooper

# Overview

Correct the return tip height being used by the pipette when returning the tip used for calibration
back to its well. 

Also, only load calibration block onto the deck if creator of the tip length
calibration session has access to a calibration block.

# Changelog

- actually factor in pipette's `return_tip_height` when returning tip in tip length cal flow
- if you create a tip length cal session with `hasCalibrationBlock == False` the user flow should now not load the block onto the deck anyway

# Review requests

- [ ] try running through tip length cal without a calibration block, you shouldn't be prompted to place a block on your deck
- [ ] pipette should properly return tip such that part of the tip is inside the tip rack well, but not so much that the ejection sheath will push against the tip rack well.

# Risk assessment

low, patches to unreleased code

2020-07-28 12:05 UTC, amitlissack reviewed
There are no unit test changes in this PR.

2020-07-28 12:05 UTC, amitlissack commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +        tiprack: labware.Labware = self._deck[TIP_RACK_SLOT]  # type: ignore
Why is type ignore needed?

2020-07-28 12:05 UTC, amitlissack commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +            tip_length = self._get_default_tip_length()
If I am an example, new eyes will have a hard time figuring out all this computation. A few comments would be helpful.

2020-07-28 13:09 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +        tiprack: labware.Labware = self._deck[TIP_RACK_SLOT]  # type: ignore
we need some better typing around deck items. A deck slot can contain a labware but it can also contain a modulegeometry (really, it can contain a [DeckItem ABC](https://github.com/Opentrons/opentrons/blob/463d56de478da44023e851423c40fb8787aa6918/api/src/opentrons/protocol_api/definitions.py#L12)).

2020-07-28 13:48 UTC, sfoster1 requested changes
The height thing is correct but there's actually another bug there that's not captured in this PR (yet): `_tip_origin_loc` is captured from `gantry_position` but without specifying the appropriate critical point, which means it captures the location of the backmost channel of a multi at pickup - halfway into slot 11. Then we move to that location using the appropriate critical point, which means the frontmost channel moves  halfway into slot 11. We need to use the appropriate CP when storing the original tip location.

2020-07-28 13:48 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +            tip_return_ratio = self._hw_pipette.config.return_tip_height
the ship has kind of sailed on this, I'm noticing, but we probably shouldn't be accessing the hardware `Pipette` object directly outside of the hardware controller since we don't have adapters in place; modification should happen through the hardware controller API instance. We'll need to change this when we split out the hardware controller to its own process.

2020-07-28 14:18 UTC, amitlissack commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +        tiprack: labware.Labware = self._deck[TIP_RACK_SLOT]  # type: ignore
I see. Is that why there's so much `isinstance` business in the contexts and protocol session?

2020-07-28 17:22 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/tip_length/user_flow.py
> +        tiprack: labware.Labware = self._deck[TIP_RACK_SLOT]  # type: ignore
I think most `isinstance` business in the session is to correctly support both api versions (that's certainly why it's there in the command callbacks, serialization, calibration stuff etc). A lot of the `isinstance` stuff in the protocol contexts is there to support the (perhaps overly-) flexible arguments for things like motion targets, where you can specify `plate['A1']` or `plate['A1'].top()`. There's probably some places that do `isinstance` checks for internal things on the deck but not too terribly many.

2020-07-29 21:29 UTC, sfoster1 approved these changes
LGTM! Nice!

2020-07-29 21:40 UTC, merged