refactor(shared-data): allow api level dependent flow rates
OpenTrons/opentrons-api pull request #6279
Opened 2020-08-04 18:12 UTC by sfoster1

Recent hardware changes allow us to update the default flow rate for
Gen2 Single pipettes to 10mm/s plunger speed (resulting flow rate varies
per pipette class), including retroactively. To avoid changing user
protocols under them, this adds new data for the changed values:
- flow rate values now can be organized in an object keyed with api
levels
- this will eventually supercede the single-value structure
- the api level 2.0 key is the "default", and should be used unless
operating at a higher api level for which there is a superceding value.

## Review requests

- Does this structure look good?  Nothing  uses this data yet (that'll be a follow up pr)
- Do the values for api level 2.0 match the "value" defaults?
- Are the 2.6 values properly twice the 2.0 levels, where they exist?

2020-08-04 18:43 UTC, sfoster1 commented on shared-data/pipette/definitions/pipetteNameSpecs.json
> +      "valuesByApiLevel": {"2.0": 5}
wrong place

2020-08-04 19:01 UTC, IanLondon requested changes
JSON schema def not correct

2020-08-04 19:01 UTC, IanLondon commented on shared-data/pipette/schemas/pipetteNameSpecsSchema.json
> +    "perApiLevelValues": {
`perApiLevelValues` should be `valuesByApiLevel`

this schema is permissive and doesn't have `"additionalProperties": false`, so it's not caught!

2020-08-04 19:27 UTC, sfoster1 commented on shared-data/pipette/schemas/pipetteNameSpecsSchema.json
> +    "perApiLevelValues": {
aha!

2020-08-04 19:28 UTC, sfoster1 commented on shared-data/pipette/schemas/pipetteNameSpecsSchema.json
> +    "perApiLevelValues": {
Wait this is the looked-up definition. `valuesByApiLevel` is the name of the objects.

2020-08-04 22:12 UTC, Laura-Danielle requested changes
We either need to remove the ability to modify default flow rates in pipette settings (only available under DEV but customers still need to use it), or we need to find another way to categorize default speeds. If we are able to assert that pipette functions in GEN2 `2.0` hold up no matter what default speed they have, then maybe we should have _another_ schema definition that separates out default values by api level (for any parameter that may have a default which is not affected by pipette functions).

This may reduce the need for bumping model versions as well.

2020-08-05 11:29 UTC, shlokamin commented on shared-data/pipette/schemas/pipetteNameSpecsSchema.json
> +      "required": ["value", "min", "max", "valuesByApiLevel"],
`valuesByApiLevel ` isn't required is it?

2020-08-05 11:29 UTC, shlokamin commented on shared-data/python/opentrons_shared_data/pipette/dev_types.py
> +    valuesByApiLevel: Dict[str, float]
Idk how optional params work here but does it need to be specified that `valuesByApiLevel` is optional? If I recall correctly you can't explicitly say that one field is optional with a `TypedDict`, you have to make everything optional :/

2020-08-05 13:31 UTC, sfoster1 commented on shared-data/pipette/schemas/pipetteNameSpecsSchema.json
> +      "required": ["value", "min", "max", "valuesByApiLevel"],
It is in this schema; the "2.0" entry contains the old default "value" level, so we can eventually remove the "value" key.

2020-08-05 13:32 UTC, sfoster1 commented on shared-data/python/opentrons_shared_data/pipette/dev_types.py
> +    valuesByApiLevel: Dict[str, float]
It's not optional (see above)

2020-08-05 13:40 UTC, shlokamin approved these changes

2020-08-05 14:55 UTC, sfoster1 commented
> We either need to remove the ability to modify default flow rates in pipette settings 

I think this is the path forward. Flow rate modification is a first-class feature in the protocol API.

2020-08-05 15:16 UTC, IanLondon commented on shared-data/pipette/schemas/pipetteNameSpecsSchema.json
> +      "type": "object",
would you want to put `"additionalProperties": false,` inside `configValue`? Right now this is allowed:

```json
"defaultAspirateFlowRate": {
      "value": 5,
      "min": 0.001,
      "max": 50,
      "YOLOOOOO": 123,
      "valuesByApiLevel": { "2.0": 5 }
    },
```

2020-08-05 15:19 UTC, sfoster1 commented on shared-data/pipette/schemas/pipetteNameSpecsSchema.json
> +      "type": "object",
I think we'd decided to avoid `additionalProperties: false` consistently to allow for future-compatible schema changes or something?

2020-08-05 15:37 UTC, IanLondon approved these changes
looking good! I don't want to block on the additionalProperties thing but I'm not sure why we'd want to avoid it, since for this particular schema we can make "breaking changes" to the schema itself without version-desyncing trouble as long as they're backwards compatible (as this PR demonstrates)

2020-08-05 15:50 UTC, Laura-Danielle approved these changes
lgtm

2020-08-05 17:49 UTC, merged