feat(api): Save new robot calibration in a separate location
OpenTrons/opentrons-api pull request #6281
Opened 2020-08-04 21:20 UTC by Laura-Danielle

# Overview

Closes #6247. Here a new directory under `data` called `robot` is created. Anything to do with robot settings/calibrations (i.e, deck transform or instrument offsets) should be saved in this folder. 

# Changelog

- Create new directory for robot related calibrations
- Add more methods for saving this data in the `calibration_storage` folder
- Add in helpers in `hardware_control` to handle loading and saving the data gantry data -- could be expanded to instrument offset data later.
- Add a test to check loading/saving methods
- Check the overhaul feature flag to decide which transform matrix to use in checks/position calculations

# Review requests

Any other tests to add? Code organization look OK?

# Risk assessment

Low. Not being used unless calibration overhaul feature flag is switched.

2020-08-04 21:48 UTC, ahiuchingau commented on api/src/opentrons/calibration_storage/dev_types.py
> +    last_modified: datetime
Use camelCase for the keys in this TypedDict pls

2020-08-04 21:48 UTC, ahiuchingau commented on api/src/opentrons/calibration_storage/modify.py
> +    gantry_path = robot_dir/'transform.json'
I think it's okay to keep the name as `deck_calibration.json` since it's in the `/data/robot/` directory. Or maybe we could call this `deck_transform.json` so the name itself is more clear

2020-08-04 21:48 UTC, ahiuchingau commented on api/src/opentrons/calibration_storage/modify.py
> +    gantry_path = robot_dir/'transform.json'
^ actually `deck_calibration` is better especially if the class `DeckCalibration` is being used in `hardware_control/robot_calibration.py`

2020-08-05 18:03 UTC, sfoster1 requested changes
Inline comments, but I think the big one is - rather than modifying the new data to make it a 3d affine transform, I think we should duplicate the transform application codepaths so that we can really cleanly delete the old ones. when we remove the feature flag.

2020-08-05 18:03 UTC, sfoster1 commented on api/src/opentrons/hardware_control/robot_calibration.py
> +        deck_cal_obj.attitude =\
Oh I see why this works with the above matrix shape handling now.  IMO let's not. do. this. Instead, let's split the  places that deal with that data such that we can delete the paths that deal with the old data easily when the time comes.

2020-08-05 18:03 UTC, sfoster1 commented on api/src/opentrons/hardware_control/robot_calibration.py
> +    attitude: Optional[types.AttitudeMatrix] = None
Does this need to be optional? It seems like the loader is  building an identity default

2020-08-05 21:18 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/robot_calibration.py
> +    attitude: Optional[types.AttitudeMatrix] = None
Does not need to be optional

2020-08-11 19:15 UTC, sfoster1 requested changes
The data format store looks good, but I think there's some problems with the actual calculations in `move_to` - we should apply offsets on the deck side of the transform, not the motor controller side. Also, we need some tests for `move_to` and friends when the calibration overhaul is on.

2020-08-11 19:15 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/file_operators.py
> +        data: typing.Mapping,
Nice

2020-08-11 19:15 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/file_operators.py
> +        data: typing.Mapping,
We could parametrize it a bit farther but for what this actually does I don't know that it's necessary

2020-08-11 19:15 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        if ff.enable_calibration_overhaul():
This isn't quite right, and in a way that may simplify things a bit. We want all of our calibration offsets to live in deck space, on the deck side of the attitude transform. That means that going from deck -> smoothie means adding the offsets before applying the attitude transform, and going from smoothie -> deck means applying the attitude transform inverse and then subtracting the offsets. This is the same sense as pre-overhaul. So we can pull the `offset_vector` part out of this function and apply it in `move_to` in the same way as we do pre-overhaul.

2020-08-11 19:15 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +            if len(to_transform) != 2:
Even though we're probably going to set the attitude matrix to have 0 z-bound components (e.g. [e11, e12, 0; e21, e22, 0; 0, 0, 1]) let's treat it as if it's a full 3d attitude, so the constraint here should be the same - xyz or none of them, e.g. plunger only - as pre-overhaul

2020-08-13 17:40 UTC, sfoster1 requested changes
Structure looks great; some inline changes though.

One larger thing I'm kinda thinking about: there is a _lot_ of marshaling into/out of numpy arrays scattered around here. I wonder if it might be better to read data from json and turn it into a numpy array as early as possible and have it be a proper array as it hangs out in memory. 

That might also be good for a follow-up pr, since we should probably get this one merged.

Either way, a couple little things we can tighten up and then this will be ready.

2020-08-13 17:40 UTC, sfoster1 commented on api/src/opentrons/util/linal.py
> +def identity_deck_transform(size: int = 4):
this is kind of minor, but for this to be a reasonable function it should really either load the feature flag and return the appropriate thing automatically or take like new vs old; otherwise, it's literally the exact same thing as calling `np.identity`

2020-08-13 17:40 UTC, sfoster1 commented on api/src/opentrons/util/linal.py
> +def solve_attitude(
a note on types - we do in fact require precisely 3 of these points, not just a list of them. Might be better to express that here.

2020-08-13 17:40 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        # Tell apply_transform to just do the change of base part of the
comment might be in the wrong place now

2020-08-13 17:40 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        self._log.info("Final smoothie position")
this probably doesn't want to be info level, and it definitely doesn't want to be two separate messages

2020-08-13 17:40 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        to_transform = tuple((tp
moving this down desyncs it from its comment on line 958 and adds some noise to the diff since it's not actually changed

2020-08-13 17:40 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +            m_offset = top_types.Point(*self._config.mount_offset)
don't need the different name now I believe

2020-08-13 17:40 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        rank = np.linalg.matrix_rank(curr_cal)
since this is a cached function, rather than doing row/rank we might want to just give inverting it a shot and catch the exception if it's non-invertable for the singularity check

2020-08-13 17:40 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        elif np.array_equal(curr_cal, id_matrix):
i think it may be better to actually do a metadata check here for `last_modified != None`. Technically, a robot _could_ properly have an identity calibration (especially now that the offset isn't baked in); we were testing for identity to serve as a proxy for "never run deck calibration", but now we have the metadata to determine that directly.

2020-08-13 18:38 UTC, sfoster1 approved these changes
LGTM! Nice!

2020-08-13 19:06 UTC, merged