refactor(robot-server): create deck calibration user flow
OpenTrons/opentrons-api pull request #6282
Opened 2020-08-04 21:32 UTC by ahiuchingau

# Overview
This PR creates a user flow and state machine for deck calibration in robot server.

![Screen Shot 2020-08-04 at 4 35 53 PM](https://user-images.githubusercontent.com/20424172/89342294-956f4500-d670-11ea-993d-1f17201d8d91.png)

closes #6249 

# Changelog
- move SimpleStateMachine and StateTransitionError out of `robot-server/robot/calibration/tip_length/` to the top level `robot-server/robot/calibration` to be used in deck calibration as well
- test state machine transitions
- add fixtures for user flow test

# Review requests
Most of the commands in the user flow have not been implemented yet, and will be done in different ticket #6254.

# Risk assessment
Low, however, it does touches tip length calibration by moving some utils to the top level directory.

2020-08-05 14:20 UTC, amitlissack approved these changes
Nice job!

2020-08-05 14:20 UTC, amitlissack commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +class DeckCalibrationUserFlow():
Nit. `()` not needed if not deriving from some class.

2020-08-05 17:13 UTC, sfoster1 requested changes
Couple inline comments but the structure looks great!

2020-08-05 17:13 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/constants.py
> +WILDCARD = '*'
since we moved this up a level can we call this `STATE_WILDCARD` or something

2020-08-05 17:13 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +    def _select_target_pipette(self):
this doesn't need to be implemented yet but it should probably return _some_ dummy value. It also should have its return type annotated.

2020-08-05 17:13 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +    def _get_tip_rack_lw(self):
return type annotated, can load some random tiprack that doesn't even have to match the pipette

2020-08-05 17:13 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +    def _get_critical_point(self):
return type annotation

2020-08-05 17:13 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +    async def _get_current_point(self):
return type annotation

2020-08-05 18:05 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/deck/constants.py
> +    sessionStarted = "sessionStarted"
We need a joggingToDeck state that happens after the tip is picked up and before jogging to the first calibration point

2020-08-06 13:05 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +        return self._hardware._attached_instruments[Mount.RIGHT], Mount.RIGHT
Can ignore => since implementation will be different here, maybe it's better to just have this as pass

2020-08-07 14:44 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +        return self._hardware._attached_instruments[Mount.RIGHT], Mount.RIGHT
No, if it's a pass the function implicitly returns `None` so we couldn't annotate the return type in this PR, which I absolutely think we should do

2020-08-07 14:44 UTC, sfoster1 approved these changes
Looks good to me!

2020-08-07 14:45 UTC, merged