refactor(robot-server): deck calibraton - tip pick up and invalidate tip
OpenTrons/opentrons-api pull request #6376
Opened 2020-08-18 14:53 UTC by ahiuchingau

closes #6256

# Overview
This PR fills in the preparing pipette flow for deck calibration.

# Changelog
- updated `pick_up_tip`, `return_tip`
- implemented `_get_tip_length` by trying to get the new tip length calibration data; use the default tip length if not found
- added tests

# Review requests

# Risk assessment
low, behind a feature flag

2020-08-18 15:24 UTC, Laura-Danielle reviewed
Just some small comments, let me know if you have questions

2020-08-18 15:24 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +                self._hw_pipette.pipette_id,  # type: ignore
What error are you getting from this type ignore?

2020-08-18 15:24 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +        self._tip_origin_pt = await self._hardware.gantry_position(
Shouldn't this be called `nozzle_origin_pt`?

2020-08-18 15:24 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +            return get.load_tip_length_calibration(
Also might be good to have a more user facing method (maybe in protocol api or hw controller) that loads the tip length data into a dataclass so that you don't need to index into the dictionary

2020-08-18 15:24 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +        self._tip_origin_pt = await self._hardware.gantry_position(
Also do we not have the pipette's critical point info at this time?

2020-08-18 15:24 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +    async def _move(self, to_loc: Location):
same with a move function that's already implemented in the session? [maybe I'm too out of the game at this point :P ]

2020-08-18 15:25 UTC, sfoster1 requested changes
Looks good but it would be awesome if we could refactor some common code

2020-08-18 15:25 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +        saved_default = None
these methods are pretty much the same as in tip length calibration, right? can we pull them into some shared utility? or is the behavior too different

2020-08-18 15:25 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +        if saved_default:
this wants to be in a `try... finally`

2020-08-18 21:14 UTC, ahiuchingau commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +                self._hw_pipette.pipette_id,  # type: ignore
`hw_pipette` currently can be None (which is fixed by #6382), once that is merged, this type ignore can be removed

2020-08-18 21:17 UTC, ahiuchingau commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +        self._tip_origin_pt = await self._hardware.gantry_position(
I copied the name from TipLengthCalibrationUserFlow to keep things consistent. 

In tip length cal, there's a `nozzle_height_at_reference` so I feel that using `nozzle_origin_pt` could potentially make it confusing

2020-08-19 12:37 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +        self._tip_origin_pt = await self._hardware.gantry_position(
yeah that should be tip origin pt i think, it's the origin point of the current tip

2020-08-19 14:34 UTC, ahiuchingau commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +        saved_default = None
Some are the same and can be shared

2020-08-19 20:28 UTC, ahiuchingau commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +            return get.load_tip_length_calibration(
It might be worth doing this in a separate refactor since it'll be touching the api

2020-08-20 16:50 UTC, sfoster1 approved these changes
Code looks good!

2020-08-20 17:32 UTC, Laura-Danielle approved these changes
lgtm

2020-08-20 17:33 UTC, merged