refactor(robot-server): deck cal - jog to deck and calibration points
OpenTrons/opentrons-api pull request #6389
Opened 2020-08-20 15:03 UTC by ahiuchingau

closes #6349, closes #6351

# Overview
This PR implements the (1) jogging to deck, and (2) jogging to calibration-points in the deck calibration flow. 

# Changelog
- filled in `save_offset()`
  - during `joggingToDeck`, saves only the z as the deck z reference height to be used in determining the move to height for the 3 calibration points
  - during `savingPoint[One,Two,Three]`, adds the current position to `saved_points`
- adding `get_cal_point_location` to get the location for each calibration point, using the deck z reference height as the z

# Review requests
Note: This PR doesn't take care of the actual saving the attitude matrix yet! It will be done in a separate PR.

# Risk assessment
Low, behind a feature flag, all new code

2020-08-20 18:48 UTC, sfoster1 requested changes
I think we should change the way we save points to make the typing work a bit better

2020-08-20 18:48 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +        self._saved_points: tuple = ()
this isn't the right way to type this. `Tuple`s in are fixed-length containers for heterogeneous data (or, to support some pythonisms, unlimited length "immutable" containers for homogenous data, but gross) and therefore need a different approach to typing and to consideration for reusing them in class members like this. We could and possibly should type this as `self._saved_points = Tuple[Optional[float], Optional[float], Optional[float]] = (None, None, None)`. We could also, and I think this is a better idea, make a typed dict like
```
class SavedPoints(TypedDict):
   '1BRC': float  # or whatever the idea is
   '3BRC': float
   '7BRC': float
   'z': float  # or some other id
```

and then have `self._saved_points: SavedPoints = {}` or something like this. we can later pass the xy points to solve with `[v for v in value if k != 'z' for k, v in self._saved_points.items()]`

2020-08-20 19:01 UTC, b-cooper approved these changes
Code looks good to me 🏯

2020-08-24 20:38 UTC, sfoster1 approved these changes
LGTM! Nice!

2020-08-24 21:50 UTC, merged