feat(api): Support pipette pairing for pickup and drop tip
OpenTrons/opentrons-api pull request #6390
Opened 2020-08-20 17:14 UTC by Laura-Danielle

# Overview

Closes #6275. This PR adds pipette pairing support to the pick up and drop tip methods of the hardware controller.

# Changelog

- Add tests for pick up and drop tip + checking current is set correctly
- Modify set active current to take in multiple axes
- Modify retract to allow for different types of axes and to support pipette pairing
- Modify `_move_plunger` to support pipette pairing 

# Review requests

Code look OK? Are the tests sufficient?

# Risk assessment

Low, new feature that is not being utilized currently.

2020-08-20 18:15 UTC, amitlissack commented on api/src/opentrons/hardware_control/api.py
> +    async def _move_plunger(self, mount: Union[top_types.Mount, PipettePair],
I realize there's been investment in this pattern already, but wanted to express this anyway as food for thought for the future:

Is there a possibility of not using a `Union` here? Can we use object oriented techniques to simplify this code? Isn't a PipettePair just two Mounts?

2020-08-20 18:20 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +    async def _move_plunger(self, mount: Union[top_types.Mount, PipettePair],
That's an interesting idea. It's sort of two mounts, but with the added caveat of a 'primary' or 'secondary' pipette. The use-case in a protocol context would be: 
1. I have `pipette1` and `pipette2` and I say they are "paired" together
2. If I call an action (say aspirate or pick up tip) with pipette 1 on the right mount, then it should use the XY values of that pipette to move to a given location. If however, I call pick up tip with pipette2 on the left mount, then it should use the XY values of the left pipette to move to a given location.

I'm not sure how we would be able to encapsulate that while inheriting from mount, for example, but if you have ideas I'd be open.

2020-08-20 18:21 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +    async def _move_plunger(self, mount: Union[top_types.Mount, PipettePair],
I tried to think of a way of avoiding `isinstance` because I know we're trying to move away from using that, but I didn't have any great ideas.

2020-08-20 18:41 UTC, sfoster1 requested changes
I think we can make this a lot simpler by changing the way some precondition checks work, and also I think some of the postcondition setting in `pick_up_tip` is wrong

2020-08-20 18:41 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +            z_axis: bool = True):
This is a bit gross to me. Having a boolean switch that completely changes the behavior of a function is not a good sign.

The term `retract` also doesn't have a lot of meaning when applied to a plunger, and if we ever do something smarter with pipette retraction other than a fast home we'll have to split this out again. 

Doing a fast home of the plunger is also not something that needs to be exposed to users of this api - it's a purely internal thing. 

What I would suggest is:
- remove the `z_axis` arg from here. This should only do pipette retraction, by mount.
- make a `_fast_home` binding that takes a `Sequence[Axis]` and coalesces calls to `self._backend.fast_home` 
- call `_fast_home` from this function and from the callsites that use `retract(..., z_axis=False)`. those callsites should figure out twinning on their own.

2020-08-20 18:41 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +            assert instr1 and instr2, \
Let's either make this a `NoPipetteAttachedException` or make a new exception that inherits from NPAE called like `InvalidTwinSetupException` or something

2020-08-20 18:41 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +            action: str) -> Tuple[
I think this function does a little too much and maybe could be refactored a bit. You can tell because it doesn't really remove that much complexity from its call sites - they still have to handle checking whether the secondary return values exist or not. I think we'd be a bit better off with something like:

```
PipetteHandlingData = TypeVar('PipetteHandlingData', Tuple[Pipette, top_types.Mount])

@typing.overload
def _instruments_for(self, top_types.Mount) -> Tuple[PipetteHandlingData] = ...

@typing.overload
def _instruments_for(self, PipettePair) -> Tuple[PipetteHandlingData, PipetteHandlingData]:
    # most of the current body of _prepare_for_tip_action, but without the 
    # tip checking that requires an action string. you're now returning a tuple
    # that may be 1-ary or 2-ary, which means the callsites can iterate through
    # them and handle the twinning and non-twinning case the same.
    # this also may be useful in more cases than just pickup/drop tip -
    # for instance, it could be pretty useful in move_to and address Amit's
    # comment a bit
    ...

def _ready_for_tip_attach(self, targets: Sequence[PipetteHandlingData[):
    # here is an example of the sequence handling. call this on the return value
    # of _instruments_for, and it doesn't care whether there's one or two
    for target in targets: assert not target[0].has_tip

# and a similar thing for ready_for_tip_remove
```

2020-08-20 18:41 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +            self._prepare_for_tip_action(mount, 'pickup')
once this is replaced with `_instruments_for`, rather than destructuring the return value immediately you can store it as a sequence type (aka `instrs = self._instruments_for(mount)) and do sequence operations on it (e.g. `self._ready_for_tip_attach(instrs)` and `plunger_currents = {Axis.of_plunger(instr[1]): instr[0].config.plunger_current for instr in instrs}`)

2020-08-20 18:41 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        p_instr.add_tip(tip_length=tip_length)
these postconditions need to be set on both instruments (much easier if you can loop through `instrs` as above)

2020-08-20 18:41 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        retract_target = p_instr.config.pick_up_distance\
there should be one of these for each instrument

2020-08-20 18:41 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        if 'pickupTipShake' in p_instr.config.quirks:
the shake actions should really be `if any(['pickupTipShake' in instr.config.quirks for instr in instrs])`, same with the one in drop tip

2020-08-20 18:41 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        p_instr, p_mount, s_instr, s_mount =\
see comments for pick up tip

2020-08-20 18:41 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        if 'doubleDropTip' in p_instr.config.quirks:
see comments for the quirks in pickuptip

2020-08-20 18:41 UTC, sfoster1 commented on api/src/opentrons/hardware_control/simulator.py
> +        for ax in axis:
let's very much not let the smoothie driver's approach to axes ('oh just jam them together in a string!') affect us at this level. if we want to allow specifying multiple axes, this signature should be `Sequence[str]`

2020-08-20 19:31 UTC, amitlissack commented on api/src/opentrons/hardware_control/api.py
> +    async def _move_plunger(self, mount: Union[top_types.Mount, PipettePair],
In this function, `move_rel`, and `move_to` there are snippets that create an `OrderedDict`. 

There could be an abstract class that is a *MovableWithPlunger* thing which has functions that determine the target for move_plunger, move_rel, and move_to,  and so on. There could be *MountWithPlunger* and a *PipettePairWithPlunger* that each implement the move_X functions. They return an object with the OrderedDict and SecondaryZ (if necessary).

Then move_rel, move_to, and move_plunger can be called with a *MovableWithPlunger*. 

You don't have to take that route, you can also just create `move_rel_target`, `move_to_target`, and `move_plunger_target` global functions that accept the `Union[Mount, PipettePair]`. These functions would create the OrderedDict, secondary_z and probably have quite a bit of shared code.

2020-08-26 13:05 UTC, sfoster1 requested changes
Definitely some cleanup to do - deleting some unused functions and renaming some used only once - but also I think there's one more refactor you can do that will help tremendously.

2020-08-26 13:05 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        if isinstance(mount, PipettePair):
This might get cleaner with a further refactor in line with @amitlissack 's idea. If you have a util function
```
@overload
def mounts(motion_target: PipettePair) -> Tuple[Mount, Mount] = ...

@overload
def mounts(motion_target: Mount) -> Tuple[Mount] = ...

def mounts(motion_target):
    if isinstance(motion_target, Mount): return (motion_target,)
    return (motion_target.primary, motion_target.secondary)
```

In here, you can then do
```
mounts = mounts(mount)
all_axes_pos = OrderredDict(((Axis.X, ...), (Axis.Y, ...))
for m in mounts:
    all_axes_pos[Axis.by_mount(m)]: self._current_position[Axis.by_mount(m)]
    all_axes_pos[Axis.of_plunger(m)]: self._current_position[Axis.of_plunger(m)]

if len(mounts) == 2:
   secondary_z = Axis.of_mount(mounts[1])
```

Cuts down on the complexity a fair bit, and that `mounts` function (or whatever you call it) might help in `instruments_for`.

2020-08-26 13:23 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +    def _prepare_for_tip_action(
This is for drop tip and the subsequent aspirate/dispense PRs

2020-08-26 13:23 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +            self._log.info(f'Picking up tip on {pipettes[0].name}')
It was in the code-base previously, but I'm happy to change it to debug. I think we should still have it for both cases though.

2020-08-26 13:24 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +    def _ready_for_tip_action(
This is for drop tip and the subsequent aspirate/dispense functions because they have to do the same prechecks

2020-08-26 13:26 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +    def _fast_home(
Got it.

2020-08-26 13:28 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +    async def _move_relative_to_target(
How about `_move_relative_n_axes`?

2020-08-26 15:04 UTC, sfoster1 approved these changes
Looks really good!

2020-08-26 16:06 UTC, merged