feat(api): Allow pipette pairing for aspirate and dispense functions
OpenTrons/opentrons-api pull request #6450
Opened 2020-08-27 15:31 UTC by Laura-Danielle

# Overview

closes #6273 and closes #6274. This PR adds in functionality for pipette pairing in the aspirate/dispense functions for hardware control.

# Changelog
- Modify aspirate/dispense/blow out/prepare for aspirate functions to accommodate for pipette pairing
- Add tests to ensure the plungers move to the correct positions for these functions

# Review requests
I am currently taking the minimum speed for aspirate/dispense, but the maximum speed in blow out. Do we think this assumption is correct/good?

Any other tests we might need?

# Risk assessment

Low/Medium. There shouldn't be any changes for single pipette moves, but we should run a protocol now that all hardware control stuff is done to make sure nothing is broken.

2020-08-27 16:22 UTC, sfoster1 requested changes
Some changes and simplifications we should make.

We should also consider and explicitly document this default-volume behavior, when you specify `None` for aspirate or dispense volume. I think the two reasonable options are each pipette aspirates its max, even if they're different; or, each pipette aspirates the minimum of the two maxes. I don't really mind either way. But, the behavior should be documented.

On the speed question, keep in mind that if you're specifying a multi-axis move, then smoothie will interpret this as a combined speed, so in fact neither axis will move at the specified speed. The only way to reasonably do this is actually to set the axis max speeds for each axis and command a reasonably high speed to cap them as appropriate. Failing that, the minimum speed is probably fine.

2020-08-27 16:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        if len(instruments) > 1 and\
This is a bit weird to me. `prepare_for_aspirate` is called unconditionally by the protocol api and the current contract of this function to its callers is that it will do whatever is necessary to prep - including possibly doing nothing. The check here violates that contract.

I think this function should do its prepare actions for any pipette that has volume 0 currently. It should be OK for one pipette to not have zero volume.

2020-08-27 16:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        if 0 in asp_vol:
I don't think this is quite right, we should only bail if _all_ of `asp_vol` is 0

2020-08-27 16:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +    def _check_aspirate_volume(
This is a bit weird to me - I think it should probably either
1. always return one volume
or
2. return the same number of volumes as there are instruments (and I think it should be this one)

The case implemented here, where the length of the returned sequence can vary but not based on the number of instruments, is hard to keep in your head along with all the rest of the stuff that can vary.

2020-08-27 16:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        def vol_check(idx: int) -> float:
if `_check_aspirate_volume` always returns the same number of volumes as instruments, we can get rid of this

2020-08-27 16:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        for idx, instr in enumerate(instruments):
once we know `instruments` and `asp_vol` are the same length, we can do `for instr, vol in zip(instruments, asp_vol)` and abandon the indexing

2020-08-27 16:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        dist = tuple(self._plunger_position(
we can zip here too once these are the same length

2020-08-27 16:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        self._backend.set_active_current(plunger_currents)
can we move this inside the `try`? the currents only get reset after a move, so an exception here might mean that they stay high

2020-08-27 16:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +            for idx, instr in enumerate(instruments):
can be `zip` once the asp vol is changed

2020-08-27 16:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +            disp_vol = (volume, )
similar to `asp_vol`, i think this should always be the same length as the instruments

2020-08-27 16:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        if 0 in disp_vol:
definitely not equivalent logic - should be `all([dv == 0 for dv in disp_vol])`

2020-08-27 16:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        self._backend.set_active_current(plunger_currents)
move inside the `try`

2020-08-27 16:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +                     instr[0].current_volume - vol_check(idx), 'dispense')
could be `zip` based

2020-08-27 16:22 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +            for idx, instr in enumerate(instruments):
could be `zip` based

2020-08-27 17:02 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +        if 0 in disp_vol:
Should we not return if either pipette as a 0 disposal volume? It might get weird only dispensing from one pipette during twinning. Would you be more satisfied with an error being raised (though that might break some people's protocols)?

2020-08-28 12:57 UTC, sfoster1 approved these changes
Looks good to me!

2020-08-28 13:07 UTC, merged