feat(robot-server,app): add download deck calibration button
OpenTrons/opentrons-api pull request #6453
Opened 2020-08-27 20:48 UTC by ahiuchingau

closes #6055

# Overview
This PR adds a download deck calibration button per this [design](https://www.figma.com/file/sbjDtrRzqd46SEx1NG5QHD/Calibration-Overhaul---Deck-Calibration?node-id=31%3A638).

# Changelog
Robot server:
- add `DeckCalibrationData` model with fields: `type, matrix, lastModified, pipetteCalibratedWith, tiprack`
- update get calibration status endpoint based on the deck calibration type
    - old deck calibration data found in `/data/` will only contain the type `MatrixType.affine` and the matrix data
    - new deck calibration data in `/data/robot/` will have the type `MatrixType.attitude`, matrix data, information on the pipette and tiprack used in calibration 

App:
- new `DeckCalibrationDownload` component that renders whenever the deck calibration status is not null 
    - renders last modified date time only if the deck calibration type is `attitude` (affine deck cal doesn't contain info on when it was last modified)

# Review requests
Put this on your robot, you should be able to download your deck calibration file in robot settings on the app:
1. enable the calibration overhaul feature flag on your robot
2. _complete new deck calibration if you haven't already_
3. you should be able to see when the deck calibration was last calibrated as follows
![Screen Shot 2020-08-27 at 4 37 34 PM](https://user-images.githubusercontent.com/20424172/91492431-a54f0300-e883-11ea-82b8-54f988cacf50.png)
4. download calibration file, the default file name should be `{your-robot-name}-deck-calibration.json`
5. the downloaded file's format should look like:
```.js
{
  type: 'attitude',
  matrix: [[]],
  lastModified: 'somedatetime',
  pipetteLastCalibratedWith: 'pipetteID',
  tiprack: 'tiprack hash'
}
```
6. make sure the info is the same as the `data/robot/deck_calibration.json`
7. switch off the calibration overhaul feature flag
8. see that the last modified field disappears
9. download calibration
10. the downloaded format contain the same info as the old deck calibration data in `data/deck_calibration.json`
```.js
{
  type: 'affine',
  matrix: [[]]
}
```

# Risk assessment
Medium since this PR modifies an existing endpoint and alters the look of the robot settings tab on the app.

2020-08-27 21:01 UTC, sfoster1 requested changes
Looks good in general but there's some little stuff to change.

2020-08-27 21:01 UTC, sfoster1 commented on robot-server/robot_server/service/legacy/routers/deck_calibration.py
> +        deck_cal = robot_cal.load().deck_calibration
We should get the loaded version from the hardware controller if possible. I'd like to start avoiding reloading stuff from disk every time.

2020-08-27 21:01 UTC, sfoster1 commented on robot-server/tests/integration/test_deck_calibration.tavern.yaml
> +                - !anyfloat
probably needs one fewer `!anyfloat`

2020-09-02 02:07 UTC, ahiuchingau commented on robot-server/tests/integration/test_deck_calibration.tavern.yaml
> +                - !anyfloat
I thought it should be 4 in this case because an affine matrix would still have 4 columns

2020-09-02 13:14 UTC, sfoster1 commented on robot-server/tests/integration/test_deck_calibration.tavern.yaml
> +                - !anyfloat
Yeah I think you're right

2020-09-02 13:16 UTC, sfoster1 approved these changes
Code LGTM once you fix the type checks

2020-09-03 16:40 UTC, merged