refactor(api): migrate legacy deck calibration to new format
OpenTrons/opentrons-api pull request #6459
Opened 2020-09-01 14:01 UTC by ahiuchingau

closes #6446

# Overview
When the enable calibration overhaul feature flag is switched on for the first time, valid legacy deck calibration data will be migrated to the new format if there is no current deck calibration. 

# Changelog
- during `load_attitude_matrix`, it will now try to load the affine deck calibration into the new format before loading the default calibration data

- the old calibration data do not contain info on the pipette or tiprack that were used in calibration, so they will be saved as `UNKNOWN`

- pull deck cal matrix validation methods out of hardware controller to be used in `load_attitude_matrix`

- add a new function `migrate_affine_xy_to_attitude`

- update some tests

# Review requests
Should `pipette_calibrated_with` and `tiprack` be `UNKNOWN` or an empty string? Does the code look sane?

# Risk assessment
Medium, as it migrates some data. However, it all happens behind a feature flag and the old data will not actually be removed; so it would not break anything when the feature flag is switched off again.

2020-09-01 15:45 UTC, Laura-Danielle reviewed
Some questions/food for thought. Let me know if you want to talk through anything.

2020-09-01 15:45 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/robot_calibration.py
> +                                            pip_id='UNKNOWN',
I think this should be whatever a default pip id or lw hash would be from the deck cal program, otherwise we should put some indication that this is specifically from a legacy deck calibration.

If we go the legacy route, I would be OK with adding an additional key to `DeckCalibration` to specify that.

2020-09-01 15:45 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/robot_calibration.py
> +    return RobotCalibration(
Was this necessary?

2020-09-01 15:45 UTC, Laura-Danielle commented on api/tests/opentrons/hardware_control/test_api_helpers.py
> +    inrange_matrix = [[1, 0, 1], [0, 1, 2], [0, 0, 1]]
Why did you change the order of this test?

2020-09-01 15:45 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/robot_calibration.py
> +                                            pip_id='UNKNOWN',
Also if you're changing what the default string is in `modify.py` you don't need to specify UNKNOWN here.

2020-09-01 16:15 UTC, ahiuchingau commented on api/tests/opentrons/hardware_control/test_api_helpers.py
> +    inrange_matrix = [[1, 0, 1], [0, 1, 2], [0, 0, 1]]
I changed it just because i didn't want to modify the deck cal `last_modified` twice

2020-09-01 16:16 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/robot_calibration.py
> +    return RobotCalibration(
No, i previously added something that made that line longer but removed it and forgot to change this back

2020-09-02 13:12 UTC, sfoster1 requested changes

2020-09-02 13:12 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/modify.py
> +        pip_id: str = 'UNKNOWN',
It's unfortunately usually a bad idea to provide objects in argument defaults in python, since if you subsequently modify them the defaults are modified forever. This doesn't appear to be a problem in this particular case, but it's good to avoid it generally.

I also think that `None` is perfectly appropriate for the migration case, down to saving nulls in the json. 

That said, argument defaults should be used when the case of not providing the argument is common. If we almost always provide the argument, but occasionally we don't, we shouldn't use a default but should type it as `pip_id: Optional[str], lw_hash: Optional[str]` so that callers must explicitly pass `None`.

2020-09-02 13:12 UTC, sfoster1 commented on api/src/opentrons/hardware_control/robot_calibration.py
> +                "Attitude deck calibration matrix not found. Mirgating "
```suggestion
                "Attitude deck calibration matrix not found. Migrating "
```

2020-09-08 17:25 UTC, sfoster1 approved these changes
Looks good to me!

2020-09-08 17:37 UTC, merged