feat(api): Add skeleton Pipette pairing context
OpenTrons/opentrons-api pull request #6472
Opened 2020-09-02 13:28 UTC by Laura-Danielle

# Overview
closes #6438.  I've coordinated with the CPX team to try and make the Pipette Pairing context a little more future proof for the work they are doing with protocols/the protocol contexts. In practice, this means that rather than implementing an abstract base class for the contexts we should expect that there will be an interface for both the instrument "object"/pipette pairing "object". A consequence of that being that I will be implementing all of the actual functions (which will eventually extend the interface) as a separate class and use the context purely as a documentation/validation location.

I have the instrument context objects as placeholders for now being passed into the pipette pairing context, but likely that would change to the instrument "object" instead.

# Changelog

- Add in a pipette pairing context
- Add in a function on instrument context called `pair_with` that actually creates the pipette pairing object
- Add docs where relevant so far

# Review requests

Signature of the pipette pairing context look OK? Error for non-same pipettes look OK?

# Risk assessment

Low, code does not do anything except set up a skeleton at the moment.

2020-09-02 13:34 UTC, sfoster1 requested changes
Couple little changes particularly in the documentation

2020-09-02 13:34 UTC, sfoster1 commented on api/docs/v2/versioning.rst
> +- You can now move both pipettes simultaneously on the robot! See :py:meth:`.InstrumentContext.pair_with` for
May want to add a note that this feature is still under development

2020-09-02 13:34 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +            self, instrument: 'InstrumentContext') -> PairedInstrumentContext:
If we're going full `__future__.annotations` don't need the quotes here

2020-09-02 13:34 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +        The building block commands are the same (pick_up_tip, aspirate etc),
Probably shouldn't `etc` here, and the methods should be crosslinked or at the very least double-backticked

2020-09-02 13:34 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +        pipette pairing. This means that you cannot utilize a p1000 single
Should capitalize "P1000 Single" and "P300 Single"

2020-09-02 13:34 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +            right_pipette = ctx.load_instrument('p300_single_gen2', 'right')
Let's make this example actually a functional protocol, with a `def run(ctx)` and `metadata`. If possible, it would be good to use the text-replacement for the api level (but it may not be)

2020-09-02 13:34 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument_context.py
> +from typing import TYPE_CHECKING, Union
might as well use future annotations here too

2020-09-02 13:34 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument_context.py
> +                 **config_kwargs) -> None:
what's the kwargs for? I'd love to avoid this pattern in favor of explicitly defining args, unless the kwargs are passed through to some other function unchanged

2020-09-02 13:36 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/paired_instrument_context.py
> +                 **config_kwargs) -> None:
not being used for anything so I can remove it

2020-09-03 13:45 UTC, sfoster1 approved these changes
LGTM!

2020-09-03 13:49 UTC, merged