refactor(api): save and load pipette offset data
OpenTrons/opentrons-api pull request #6502
Opened 2020-09-08 20:53 UTC by ahiuchingau

closes #6416

# Overview
This PR adds functions on the api side to load and save pipette calibration data.

# Changelog
- add functions in `/calibration_storage` to save and load pipette offset data
- add a load function in `hardware_controller/robot_calibration` to allow more straightforward access to offset data

# Review requests
Data format looks ok?
Two follow-up PRs will take care of (1) adding these functions in the pipette calibration flow and (2) using the new pipette offset data in hardware control motion, once this PR is merged.

# Risk assessment
Low, new code is not hooked up yet

2020-09-08 20:58 UTC, sfoster1 requested changes
Need to remove a debug print but looks good other than that

2020-09-08 20:58 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/modify.py
> +    print(robot_dir)
debug print, should remove

2020-09-08 23:05 UTC, ahiuchingau commented on api/src/opentrons/calibration_storage/modify.py
> +    print(robot_dir)
oops

2020-09-09 13:06 UTC, sfoster1 approved these changes
Looks good to me!

2020-09-09 13:27 UTC, merged