Twinning protocol pickup drop tip
OpenTrons/opentrons-api pull request #6528
Opened 2020-09-11 12:27 UTC by Laura-Danielle

# Overview

Closes #6439. To help future proof a little, the twinning context is split out into two separate files. The context file and the actual execution file. The context file contains all the info on docstrings and validates locations passed in whereas the execution file talks to the hardware controller to actually move the robot.

# Changelog

- Split out the twinning context into a "context/docstrings/validation" and a function execution
- Add tests for the twinning context
- Add in a helper function to shift well locations for tip tracking purposes
- Add in a property to grab a PipettePair enum type based on the mount passed in
- Added miscellaneous helper functions to ensure functionality is correct.

# Review requests

How do you feel about the split out? If you have two pipettes of the same type to test this, please do.

# Risk assessment

Low, this is an incomplete/undocumented feature. Things to look out for when testing are crashes during either pickup/drop/return tip (mostly on the left pipette).

2020-09-11 14:30 UTC, amitlissack commented on api/src/opentrons/hardware_control/api.py
> +            assert instr[0]
Is an assert the right choice here? What does this exception mean?

2020-09-11 14:30 UTC, amitlissack commented on api/src/opentrons/protocol_api/paired_instrument.py
> +    def __init__(self,
type annotations please

2020-09-11 14:31 UTC, sfoster1 requested changes
Inline comments but the structure looks good

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
>      def set_current_tiprack_diameter(self, mount, tiprack_diameter):
Let's take the time to annotate these functions

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
>      def set_working_volume(self, mount, tip_volume):
let's add annotations

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +def select_tiprack_from_list_paired_pipettes(
This needs some what and why documentation

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +        assert starting_point.parent is first
If this is something that can happen because of a problem in the user's protocol, it needs a better exception

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +    try:
So if you called pick_up_tip on a twinned context of multis repeatedly, it would pick up columns 1/4, 2/5, 3/6, 4/8 and then move to the next tiprack 1/4, 2/5, 3/6? Cool!

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/protocols/api_support/util.py
> +    shifted_column = str(int(unshifted_well[1::]) + well_spacing)
Really don't like the string manipulation here. Would much prefer to do something with `columns()` and numerical indexing.

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument.py
> +from typing import Union, Optional
I think this shouldn't be in `protocol_api`, it should be where the other interfaces/implementations are?

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument.py
> +                 primary_instrument,
Need annotations

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument.py
> +        self._mount = mount
Let's call this something else if possible, like `self._twin_policy` or something, to make it clear it isn't a literal mount

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument_context.py
> +                 mount: hc_types.PipettePair,
As with the implementation, let's call this arg and the private member something other than `mount`

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument_context.py
> +                 hardware_manager,
Needs a type probably

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument_context.py
> +        tip in its :py:attr:`InstrumentContext.tip_racks` list. Pick up tip
Copypasta

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument_context.py
> +        Since the XY position is determined by the primary pipette, you
location arg is optional, should either make it mandatory or change the language here to "if you choose to specify a tip,"

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument_context.py
> +        pipette to. Based on pipette spacing, the robot will determine
Kind of not true, right? We have a default spacing based on nominally-separated pipettes and a standard 96-tip-layout rack, but this phrasing makes it seem like we're doing math that we're not (and shouldn't be) doing

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument_context.py
> +        The tip to pick up can be manually specified with the `location`
need double-backticks

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument_context.py
> +        The current spacing of the two pipettes is approximately 34 milimeters,
```suggestion
        The current spacing of the two pipettes is approximately 34 millimeters,
```

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument_context.py
> +        The current spacing of the two pipettes is approximately 34 milimeters,
I think this has to be indented more than the `.. note::` directive? might want to check how it renders

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument_context.py
> +        full 12 columns of a 96 SBS footprint.
I think we should add a note about how this is only true while specifically using `paired.pick_up_tips`, and you can go back to picking up tips one at a time for the last two columns, maybe with an example snippet

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument_context.py
> +                f'The location you specified {primary_loc} is'
```suggestion
                f'The location you specified ({primary_loc}) is '
```

2020-09-11 14:31 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument_context.py
> +        Since the XY position is determined by the primary pipette, you
Same thing as `pick_up_tip` about `location` being optional

2020-09-14 21:03 UTC, sfoster1 approved these changes
Looks good to me!

2020-09-15 16:35 UTC, merged