feat(api): Add pipette pairing to the command log and support in rpc
OpenTrons/opentrons-api pull request #6577
Opened 2020-09-18 21:58 UTC by Laura-Danielle

# Overview

Closes #6442. This PR adds support for pipette pairing in the app by adding all of the pipette pairing commands to the command log and rpc.

# Changelog

- Make a small change in `sessions.py` to support multiple instruments in a single command
- Add new command functions for all pipette pairing functions in `commands.py`
- Add a new publisher function that does not bind `commands.py` signatures to the `PairedInstrumentContext` signatures (especially since we don't need the defaults anyways)
- Add in a check in the tests to assert that context commands are getting populated
- Make shift labware more robust for the command logs so that it can show shifts for 96 well plates, 24 well tuberacks, 384 well plates & reservoirs.

# Review requests

Test on a robot if you can. Look over the code. Let me know if you want more tests somewhere.

# Risk assessment

Low, this is adding logs so that you can 1. calibrate in the app and 2. see these commands in the run log. After this PR is merged, we can start fully testing pipette pairing.

2020-09-18 22:48 UTC, nusrat813 approved these changes
Tested - working as intended

2020-09-21 13:16 UTC, sfoster1 requested changes
We can clarify the typing on the new commands since they're only implemented for APIv2; also, some of these `before` commands need to actually be issued before the action happens since the `before` is (nominally) used to highlight the action that is currently happening.

Also, should the runlog strings contain the information that it's a twinned action?

2020-09-21 13:16 UTC, sfoster1 commented on api/src/opentrons/commands/commands.py
> +    except AttributeError:
Is this expected to catch the apiv1 case? because if so we can remove it given that pairing isn't implemented for apiv1

2020-09-21 13:16 UTC, sfoster1 commented on api/src/opentrons/commands/commands.py
> +        instruments: Sequence, volume: float,
let's specify what these are sequences of since this is only implemented for apiv2

2020-09-21 13:16 UTC, sfoster1 commented on api/src/opentrons/commands/commands.py
> +    except AttributeError:
same as paired_aspirate

2020-09-21 13:16 UTC, sfoster1 commented on api/src/opentrons/commands/commands.py
> +        instruments: Sequence, volume: float,
same as paired_aspirate

2020-09-21 13:16 UTC, sfoster1 commented on api/src/opentrons/commands/commands.py
> +        instruments: Sequence, locations: Sequence,
same as paired_aspirate

2020-09-21 13:16 UTC, sfoster1 commented on api/src/opentrons/commands/commands.py
> +def paired_blow_out(instruments: Sequence, locations: Optional[Sequence]):
same as paired aspirate

2020-09-21 13:16 UTC, sfoster1 commented on api/src/opentrons/commands/commands.py
> +def paired_touch_tip(instruments: Sequence, locations: Optional[Sequence]):
same as paired aspirate

2020-09-21 13:16 UTC, sfoster1 commented on api/src/opentrons/commands/commands.py
> +    """ Implement a second publisher outside of the decorator that
:raised_hands:

2020-09-21 13:16 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument_context.py
> +        cmds.publish_paired(self.broker, cmds.paired_aspirate, 'before',
this looks like the wrong place for the before, should be before the call to `self.paired_instrument_obj.aspirate`

2020-09-21 13:16 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument_context.py
> +        cmds.publish_paired(self.broker, cmds.paired_dispense, 'before',
the `before` call should be before the call to `paired_instrument_obj.dispense`

2020-09-21 13:16 UTC, sfoster1 commented on api/src/opentrons/protocol_api/paired_instrument_context.py
> +    def _get_secondary_target(labware: Labware, primary_loc: Well) -> Well:
This is starting to feel like it should be a method on the labware object since it has to know so much about the spacing.

2020-09-21 13:16 UTC, sfoster1 commented on api/src/opentrons/protocols/api_support/util.py
> +    unshifted_column = math.floor(unshifted_index/modulo_value)
[nit] i think you can make this just `unshifted_column = unshifted_index // modulo_value` ([integer division](https://docs.python.org/3.1/tutorial/introduction.html#numbers))

2020-09-21 16:21 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/paired_instrument_context.py
> +    def _get_secondary_target(labware: Labware, primary_loc: Well) -> Well:
Since this is really specific to twinning/getting a well target from another well I decided to keep it in the paired instrument context -- especially because the error is so specific. I don't think it would really be applicable in other places at the moment.

2020-09-21 16:58 UTC, sfoster1 approved these changes
Changes lgtm

2020-09-21 18:12 UTC, merged