refactor(api, shared-data): use pipette offset in hardware control
OpenTrons/opentrons-api pull request #6587
Opened 2020-09-22 12:58 UTC by ahiuchingau

# Overview
This PR incorporates pipette offset calibration data in hardware motion by updating the pipette's critical point.

closes #6427, closes #6534

# Changelog
- add new property `nozzleOffset` to pipetteModelSpecs to represent the true distance from the mount to the pipette nozzle
- load `nozzle_offset` to pipette config
- load pipette offset calibration during `cache_instruments` and pass to `Pipette`
   - default offset is `[0, 0, 0]` if data do not exist
- use pipette offset and nozzle offset to determine critical point, instead of using the instrument and model offset
- update to tests to reflect the above changes

# Review requests
To test this PR, make sure your robot has the changes in #6586 and to remove all old pipette offset data.

# Risk assessment
Medium, new features are behind a feature flag but they affect robot motion. Any old deck/pipette offset calibration should be cleared and recalibrated before testing these changes.

2020-09-22 13:26 UTC, sfoster1 requested changes
Couple tiny changes, need to make sure the effects of pipette offset calibration get loaded

2020-09-22 13:26 UTC, sfoster1 commented on api/src/opentrons/hardware_control/pipette.py
> +    def nozzle_offset(self):
Needs a type annotation

2020-09-22 13:26 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
>              new_p = Pipette(
We should make sure that the robot server reloads the pipette offsets after it completes nozzle offset by calling `reset_instrument`

2020-09-22 13:28 UTC, sfoster1 requested changes
We should also switch uses of `mount_offset` to some other value that cannot be modified and sticks with the default (0, -34, 0) if the calibration overhaul switch is flipped, otherwise changes to the mount offset from pre-overhaul calibration will persist (and we'll have no way to change them). This probably should be a new robot config setting called like `left_mount_offset` or something.

2020-09-23 16:48 UTC, sfoster1 approved these changes
Code lgtm, haven't tested yet tho

2020-09-23 16:57 UTC, b-cooper approved these changes
code looks good 🍨

2020-09-23 18:32 UTC, nusrat813 requested changes
Return tip is not working correctly after the pipette offset - shouldn’t load the pipette offset calibration until it’s finished dropping the tip

2020-09-24 17:32 UTC, sfoster1 requested changes
Let's make the new mount offset loaded from the config and then we're good

2020-09-24 17:32 UTC, sfoster1 commented on api/src/opentrons/config/robot_configs.py
> +        left_mount_offset=DEFAULT_MOUNT_OFFSET,
we should in fact load this from the config so that people can modify it if they want for some reason, or in testing - that's what this configuration file is for now that it doesn't contain calibration data. but there's nothing in the code that will modify it.

2020-09-24 18:32 UTC, Laura-Danielle approved these changes
Tested on my robot and code looks good aside from Seth's comment!

2020-09-24 18:45 UTC, sfoster1 commented
I test it on my robot and it looked good there as well, so I'm good to merge once we get that value loaded from config

2020-09-24 20:11 UTC, sfoster1 approved these changes
Looks good to me!

2020-09-24 20:24 UTC, nusrat813 approved these changes
LGTM

2020-09-24 23:28 UTC, merged