fix(api): Do not perform a transfer if a zero volume is passed in
OpenTrons/opentrons-api pull request #6620
Opened 2020-09-23 22:32 UTC by Laura-Danielle

# Overview

Closes #6452. Support found a bug/differing behavior between transfer + distribute/consolidate where a transfer would skip over an action if a zero volume is given whereas distribute/consolidate would at least 1. move to the location and/or 2. aspirate a disposal volume if given.

# Changelog

- Check whether the API version is below 2.7
      - if it is, append every volume passed for distribute/consolidate
      - If it's not, check that the volume is larger than zero to append
- Add tests to check both new behavior and old (broken) behavior so we make sure not to "break" users current protocols
- Add a note about the updated behavior in `version.rst`

# Review requests

Can we possibly get this into 3.21.0? Otherwise I'll change the API version to be 2.8. Should I add more details in the advanced commands page of the docs?

# Risk assessment

Low, gating a bug fix behind an API version

2020-09-24 13:07 UTC, sfoster1 requested changes
Aadding the ability to pass a list of volumes to `distribute` is new functionality (at least compared to what's documented in v2-complex-commands) and really needs to have documentation and examples if we want to add it.

I'm agnostic-leaning-toward-no on whether this gets into 3.21.

2020-09-24 13:07 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +                   volume: Union[float, Sequence[float]],
This is actually a pretty big change that needs to be documented as well

2020-09-24 13:07 UTC, sfoster1 commented on api/src/opentrons/protocols/advanced_control/transfers.py
> +    def _check_volume_not_zero(self, volume: float) -> bool:
Kind of a nitpick but this could be a static method that takes the api level as an argument and therefore be easier to test

2020-09-24 13:40 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/instrument_context.py
> +                   volume: Union[float, Sequence[float]],
Technically you could always pass in a list or a float, but I will make sure it's well documented.

2020-09-24 17:27 UTC, sfoster1 requested changes
Couple more little changes in docs but looking good

2020-09-24 17:27 UTC, sfoster1 commented on api/docs/v2/new_complex_commands.rst
> +Skipping Wells
Probably should mention that this only works in apiv2.8 otherwise bad things happen

2020-09-24 17:27 UTC, sfoster1 commented on api/docs/v2/new_complex_commands.rst
> +can use a list of volumes to skip over certain wells by setting the volume to zero.
mention that this only works right in 2.8

2020-09-24 17:27 UTC, sfoster1 commented on api/docs/v2/versioning.rst
> +|     2.8     |          4.0.0              |
:eyes:

2020-09-24 17:27 UTC, sfoster1 commented on api/docs/v2/versioning.rst
> +- You can now pass in a list of volumes to distribute and consolidate. See
I think there's a link missing after "see"

2020-09-24 17:27 UTC, sfoster1 commented on api/docs/v2/versioning.rst
> +    - Passing in a zero volume to any :ref:`v2-complex-commands` will result in no actions taken for aspirate or dispense
is this meant to be nested

2020-09-24 17:31 UTC, Laura-Danielle commented on api/docs/v2/versioning.rst
> +- You can now pass in a list of volumes to distribute and consolidate. See
oops yep

2020-09-24 17:31 UTC, Laura-Danielle commented on api/docs/v2/versioning.rst
> +    - Passing in a zero volume to any :ref:`v2-complex-commands` will result in no actions taken for aspirate or dispense
Yes

2020-09-24 17:33 UTC, Laura-Danielle commented on api/docs/v2/new_complex_commands.rst
> +Skipping Wells
So it's a bit confusing...the transfer behavior is the same/has been the same since 2.0

2020-09-24 17:33 UTC, Laura-Danielle commented on api/docs/v2/new_complex_commands.rst
> +can use a list of volumes to skip over certain wells by setting the volume to zero.
Yeah I will put a warning here for that

2020-09-25 17:02 UTC, sfoster1 approved these changes
LGTM, nice!

2020-09-25 17:05 UTC, merged