feat(robot-server,app): extend pipette offset cal to include tip length cal if needed
OpenTrons/opentrons-api pull request #6641
Opened 2020-09-28 16:18 UTC by b-cooper

# Overview

Add functionality to the pipette offset calibration user flow to allow a user to set the tip length
for the pipette-tip combination that they intend to use for the pipette offset calibration. Add
branching and assertion logic to guide the state transitions in the user flow accordingly. Also add
the last of the tip length cal child components to the shared calibration panels and map to them
from the new pipette offset calibration states when appropriate.

Closes #6420

# Changelog

# Review requests

- [ ] Try running Pipette Offset calibration without a tip length cal value for the tip rack. Should perform TLC then Pip offset
- [ ] Try running Pipette Offset calibration with existing tip length cal value for the tip rack. Should behave as it did before
- [ ] Ensure Tip Length cal standalone flow still functions as expected. 

# Risk assessment

low risk, code still behind feature flag, though pipette offset and tip length cal flows were both effected

2020-09-28 16:38 UTC, sfoster1 requested changes

2020-09-28 16:38 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/pipette_offset/user_flow.py
> +            if self._saved_offset_this_session:
only save the data if it's a legal transition

2020-09-28 16:55 UTC, sfoster1 requested changes

2020-09-28 16:55 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/pipette_offset/user_flow.py
>          self._state_machine = PipetteOffsetCalibrationStateMachine()
Let's try implementing loading one of two different state machines instead of doing checks in the handlers

2020-09-28 16:55 UTC, sfoster1 commented on app/src/components/CalibrationPanels/CompleteConfirmation.js
>  export function CompleteConfirmation(props: CalibrationPanelProps): React.Node {
If we add an intermediate complete state we can get rid of the bool

2020-10-06 12:55 UTC, sfoster1 requested changes

2020-10-06 12:55 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/constants.py
> +CAL_BLOCK_SETUP_BY_MOUNT: Dict[Mount, Dict[str, str]] = {
Bit of a nit but the actual lef elements here (the dicts that contain `load_name` `slot` and `wells` should probably be a dataclass IMO

2020-10-06 12:55 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/pipette_offset/user_flow.py
> +        self._has_calibrated_tip_length: bool =\
So this only happens if there is no stored tip length calibration for this pipette/tiprack combo, right? 

I don't think that works with the labware-cal-initiated tip length _re_calibration. If you have a valid TLC that you want to redo, the only way for the system to accomplish that would be to DELETE it using the HTTP endpoint and then start this flow. But if you then decide to skip it, there's no more calibration.

2020-10-06 12:55 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/pipette_offset/user_flow.py
> +        self._has_calibrated_tip_length: bool =\
Basically we may want a flag as a create param that is like "force tip length recalibration"

2020-10-06 13:35 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/pipette_offset/user_flow.py
> +        self._has_calibrated_tip_length: bool =\
right that makes sense

2020-10-06 20:35 UTC, sfoster1 approved these changes
Happy with the code!

2020-10-07 15:30 UTC, b-cooper commented on robot-server/robot_server/robot/calibration/pipette_offset/models.py
> +    tipLengthLoad: bool = Field(
The name of this variable is a little confusing to me. Is it a boolean of "should Perform TLC prior to pipette offset cal"?  If so, maybe something like `shouldCalibrateTipLength` would be clearer?

2020-10-07 19:33 UTC, merged