chore(build): add github workflow for PD e2e tests
OpenTrons/opentrons-api pull request #6642
Opened 2020-09-28 16:26 UTC by shlokamin

# Overview

This PR adds a github workflow for running PD end to end tests

# Changelog

- Add github workflow for PD e2e tests

# Risk assessment

Low

2020-09-28 16:29 UTC, shlokamin commented on .github/workflows/pd-e2e-test.yaml
> +        run: make setup-js
I don't we think everything that `setup-js` grabs.

Looking at the PD makefile, `test-e2e` only needs:
- concurrently
- wait-on

However, these are not dev dependencies in PD's package.json (btw, this also seems to be the case for the app and LL). We should probably add them so that when PD's `make-setup` runs, those dependencies will get installed.  Then, instead of doing `run: make setup-js`, we can do `run: make -C protocol-designer setup`, which should significantly decease setup time.

2020-09-28 17:26 UTC, sfoster1 commented on .github/workflows/pd-e2e-test.yaml
> +        run: make setup-js
You should also consider using the github cache action to save the yarn cache as in [the robot stack workflow pr](https://github.com/Opentrons/opentrons/pull/6632/files#diff-7f06a9e35f7408d1633bda1dfa4d3902R58-R72).

2020-09-28 20:27 UTC, shlokamin commented on .github/workflows/pd-e2e-test.yaml
> +        run: make setup-js
@mcous @IanLondon are y'all opposed to me adding these as dev dependencies to PD's `package.json`? or would I be breaking a known (or unknown) pattern of sorts?

2020-09-29 15:21 UTC, IanLondon approved these changes
LGTM. I don't think dependencies/devDependencies is the right place to declare task-specific dependencies because "devDependencies" is supposed to be for development + testing, and git actions is something finer-grained. IDK what our caching options are and how they're shared across different actions, seems worth investigating!

2020-10-01 14:55 UTC, mcous commented on .github/workflows/pd-e2e-test.yaml
> +        run: make setup-js
We have been following the [lerna convention](https://github.com/lerna/lerna#common-devdependencies) of pulling all common devDependencies (or in our case, simply all) up to the workspace root. I believe this to be a more convenient setup for most development tasks, and I would prefer to keep it if at all possible.

Keep in mind that `test-e2e` also runs `make dev`, which then requires our entire JS build toolchain, which is the bulk of our `devDependencies`, so I'm not sure you'd be able to save much time here. I think Seth's advice to enable the yarn cache is the best path forward here

2020-10-01 22:35 UTC, shlokamin commented on .github/workflows/pd-e2e-test.yaml
> +        run: make setup-js
Ah I missed that `test-e2e` runs `make dev`, which now that I'm reading this is quite obvious...

I don't follow how `make dev` requires our entire JS build toolchain though... is that what calling `webpack-dev-server` does here?

```js
.PHONY: dev
dev: export NODE_ENV := development
dev:
	webpack-dev-server --hot
```

2020-10-07 13:54 UTC, mcous requested changes
Didn't mean to let this one slip by, here's my actual feedback to keep things moving along.

Also, with regards to your dev dependency question:

> I don't follow how `make dev` requires our entire JS build toolchain though... is that what calling `webpack-dev-server` does here?

Yup!

- webpack-dev-server
    - webpack.config.js
        - webpack loaders
            - babel + babel presets / plugins
            - PostCSS + PostCSS preset / plugins
            - Various other webpack loaders
        - webpack plugins
            - Image (favicon) processing plugins

2020-10-07 13:54 UTC, mcous commented on .github/workflows/pd-e2e-test.yaml
> +    runs-on: 'ubuntu-latest'
Is there value in doing a cross-OS build matrix on this one?

2020-10-07 13:54 UTC, mcous commented on .github/workflows/pd-e2e-test.yaml
> +      - name: 'setup-js'
I think we should copy in the cache and setup steps from the app build job here:

https://github.com/Opentrons/opentrons/blob/58c32d3041058b69b6a94e03ace31cafdf86c720/.github/workflows/app-test-build-deploy.yaml#L62-L75

Reasoning:

- Caching yarn is important, because yarn is much faster populating `node_modules` if its pulling from a primed cache
- Caching the `npm` folder is important, because that's where [prebuild-install]() caches prebuilt native modules

Copying is annoying, but in the future [composite run steps](https://github.blog/changelog/2020-08-07-github-actions-composite-run-steps/) in GH actions [will support "uses"](https://github.com/actions/runner/issues/646), so we can move it to a common location then.
    - The PD build depends on native modules, including `sharp` via [favicons-webpack-plugin](https://github.com/jantimon/favicons-webpack-plugin)

2020-10-07 13:54 UTC, mcous commented on .github/workflows/pd-e2e-test.yaml
> +    paths:
I think the shared `webpack-config` folder needs to be in this paths list, as well as the top-level `package.json` for development dependencies

2020-10-08 15:06 UTC, shlokamin commented on .github/workflows/pd-e2e-test.yaml
> +    runs-on: 'ubuntu-latest'
This is a great point — I think so! I'll do `['windows-latest', 'ubuntu-latest', 'macos-latest']` for now.
 @IanLondon what are your thoughts?

2020-10-08 15:19 UTC, shlokamin commented on .github/workflows/pd-e2e-test.yaml
> +      - name: 'setup-js'
Makes sense to me! Just to confirm, I won't be needing the ['set complex environment variables](https://github.com/Opentrons/opentrons/blob/58c32d3041058b69b6a94e03ace31cafdf86c720/.github/workflows/app-test-build-deploy.yaml#L55)' step since this action doesn't doesn't trigger anything that needs those environment variables, right?

2020-10-08 17:36 UTC, shlokamin commented on .github/workflows/pd-e2e-test.yaml
> +    runs-on: 'ubuntu-latest'
[The chrome image is currently broken for the windows image.](https://github.com/actions/virtual-environments/issues/1546). Imo it seems like more trouble than its worth to keep around their suggested fix, or to install chrome as a dev dependency just for this use case. 

I can be convinced though, so if anyone disagrees please chime in!

2020-10-27 15:41 UTC, mcous reviewed
Did not mean to let this sit around like this. Other than a tiny path change, I think this looks good to go.

- Is there anything else we need to get this across the finish line?
- Do we need Windows in the build matrix, or did we remove it for a reason that I missed?

2020-10-27 15:41 UTC, mcous commented on .github/workflows/pd-e2e-test.yaml
> +      - '.package.json'
```suggestion
      - 'package.json'
```

2020-10-27 15:41 UTC, mcous commented on .github/workflows/pd-e2e-test.yaml
> +      - './package.json'
If you're feeling pedantic, for consistency above:

```suggestion
      - 'package.json'
```

2020-10-28 03:08 UTC, shlokamin commented on .github/workflows/pd-e2e-test.yaml
> +      - '.package.json'
🤦🏽 thank you

2020-10-28 03:15 UTC, shlokamin commented on .github/workflows/pd-e2e-test.yaml
> +      - '.package.json'
> Do we need Windows in the build matrix, or did we remove it for a reason that I missed?

See [this comment](https://github.com/Opentrons/opentrons/pull/6642#discussion_r501895324). 

The thread is old but chome seems to be broken on the windows image :/

2020-11-05 18:30 UTC, sfoster1 approved these changes
LGTM!

2020-11-05 18:39 UTC, mcous approved these changes

2020-11-05 18:59 UTC, merged