refactor(app): gate protocol calibrate and run on pipette offset cal
OpenTrons/opentrons-api pull request #6644
Opened 2020-09-28 20:06 UTC by sfoster1

If the calibration overhaul is enabled, the user should not be able to start calibrating their labware or running their protocol until all pipettes used in the protocol have pipette offset calibrations. If they don't, disable those tabs and display the same kind of warning you get if a pipette isn't attached.

## Testing
- Make sure that if you don't have the cal overhaul enabled you never see this (a good way to test this is to enable cal overhaul, make sure you do see it, and then disable cal overhaul and make sure it goes away)
- Test that having a pipette that _isn't_ used in the protocol and doesn't have a calibration doesn't block you

Closes #6627

2020-09-28 20:36 UTC, emilywools commented
looks good when I reviewed IRL (via hangout) with Seth

2020-09-28 20:37 UTC, emilywools approved these changes

2020-09-29 13:22 UTC, mcous reviewed
Just driving by

2020-09-29 13:22 UTC, mcous commented on app/src/components/FileInfo/MissingItemWarning.js
> +  OutlineButton,
I think you meant to import [SecondaryBtn](https://s3-us-west-2.amazonaws.com/opentrons-components/edge/index.html#btn) here. OutlineButton is a much older component that doesn't use style props

2020-09-29 13:22 UTC, mcous commented on app/src/components/FileInfo/MissingItemWarning.js
> +        texttransform={TEXT_TRANSFORM_UPPERCASE}
This is the default of both `SecondaryBtn` (and `OutlineButton`). It's not doing anything here (and also needs to be `textTransform` if it was going to do anything)

2020-09-29 13:22 UTC, mcous commented on app/src/components/FileInfo/MissingItemWarning.js
>          Component={Link}
When this is switched to a `SecondaryBtn`, the prop to do this is called `as`

2020-09-29 13:22 UTC, mcous commented on app/src/components/FileInfo/MissingItemWarning.js
> +        className={styles.width_auto}
`width: auto` is the default width style on `SecondaryBtn`

2020-09-29 13:23 UTC, sfoster1 commented on app/src/components/FileInfo/MissingItemWarning.js
> +        texttransform={TEXT_TRANSFORM_UPPERCASE}
oh I had it as `textTransform` and the console complained about it, which all makes sense if this is the wrong component and isn't styled properly

2020-09-29 14:43 UTC, Laura-Danielle requested changes
I am blocked from proceeding when I have two pipettes attached with only one calibrated, and I am only using the calibrated pipette in the protocol.

I don't _think_ this should matter, but both the pipettes attached are P1000 GEN2s.

2020-09-29 15:17 UTC, Laura-Danielle approved these changes
lgtm

2020-09-29 15:39 UTC, merged