refactor(api): Extract geometry from Well into WellGeometry
OpenTrons/opentrons-api pull request #6666
Opened 2020-10-01 20:17 UTC by amitlissack

# Overview

An attempt to separate `Well` class from its deck geometry. Tried to follow pattern that I saw in the modules. 

# Changelog

- The well definition and parent only go to construct a `WellGeometry` object which is passed in to `Well` constructor.
- WellGeometry returns `Point` objects. 

# Review requests

Is this correct approach? 
`max_value` was a sneaky little public member of `Well`. I made into a property.

# Risk assessment

Tests pass.  Which took some effort.

2020-10-02 12:42 UTC, sfoster1 approved these changes
Code LGTM, nice!

2020-10-02 12:51 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/labware.py
> -    def _from_center_cartesian(
This will break some people's protocols, especially if we don't gate it behind an api version.

This is behavior that we had to port over from api v1.

2020-10-02 12:51 UTC, Laura-Danielle requested changes
Geometry looks good, I just have some concern around some of the private methods in the `Well` class.

2020-10-02 12:53 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/labware.py
> -    def _from_center_cartesian(
We can also just keep the method on `Well` and call the underlying implementation from `WellGeometry`. It sucks that it's a "private" method, but we had intended for users not to use this when we first build out these methods. Turns out a lot more people customize where they move around in the well than we thought.

2020-10-02 12:56 UTC, amitlissack commented on api/src/opentrons/protocol_api/labware.py
> -    def _from_center_cartesian(
That's a good idea. 

Does this also apply to `_top`, `_bottom`, etc? I removed a bunch of private methods from `Well`.

2020-10-02 13:23 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/labware.py
> -    def _from_center_cartesian(
No, those private methods aren't used. Their public counterparts are.

We might also take the opportunity to have a public + private method here for `_from_center_cartersian` and start encouraging users to use that instead (plus throw it in the docs). We can tell the user facing teams to recommend the public facing method from now on as well.

2020-10-02 15:13 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/labware.py
> -    def _from_center_cartesian(
I guess ideally, we'd also throw a warning, but I don't think we have a great mechanism for that, today.

2020-10-02 19:17 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/labware.py
> +    def _from_center_cartesian(self, x: float, y: float, z: float) -> Point:
What I have in mind, basically, is someone's going to read an old protocol 1.5 years from now, see `_from_center_cartesian()`, and go "WTF is this? Is this the same as `from_center_cartesian()`? Why is this used?"

2020-10-02 19:27 UTC, amitlissack commented on api/src/opentrons/protocol_api/labware.py
> +    def _from_center_cartesian(self, x: float, y: float, z: float) -> Point:
I am confused by what you mean by making it public? Surrounding with `@requires_version`?

We should delete it at v4, right?

2020-10-02 19:43 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/labware.py
> +    def _from_center_cartesian(self, x: float, y: float, z: float) -> Point:
Sorry, yeah—you can read "make it public" as synonymous to "document it."

-----

> We should delete it at v4, right?

I'm not sure. I don't think we've ever removed a single function from the API, before.

I don't think so. The way we currently do versioning—where the latest version of the API knows how to emulate all previous versions of the API, down to 2.0—means that there's not actually much of a benefit to removing a function. It's not like you can actually delete the code, or stop worrying about its maintenance. You still have to keep it around, because there's a chance someone could upload a protocol with `metadata={"apiLevel":"2.0"}` that uses the old function.

2020-10-02 20:04 UTC, sanni-t approved these changes
Looks good!

2020-10-02 20:30 UTC, amitlissack commented on api/src/opentrons/protocol_api/labware.py
> +    def _from_center_cartesian(self, x: float, y: float, z: float) -> Point:
@Laura-Danielle can I get your feedback on this?

2020-10-05 13:47 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> -    def _from_center_cartesian(
We don't have a great (or any mechanism) for sending warnings from the robot for display in the runapp, true. But we can put a `log.warning` call in there and it'll pop up if someone is using jupyter or simulating with `opentrons_simulate`. That's about as good as we can get, I think. I definitely support adding a warning.

2020-10-05 13:50 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +    def _from_center_cartesian(self, x: float, y: float, z: float) -> Point:
Well, there's two things about deleting it at v4.

1. V4.0 is a robot software major version change, not a python protocol api major version change. We could also do a python protocol api major version change, but as of now we just plan to do a minor version bump to 2.8 because of a kind of standard level of minor feature addition or change. That said, I could see an argument for removing this in a minor version, because a) users _must_ exactly specify a maximum target version and therefore it won't break anything and b) undocumented `_` prefixed methods aren't part of our versioning contract.
2. While deleting a method doesn't help in the short term, it does help over time. 4.0 is certainly too soon, but one of the things a robot software major version change might reasonably do is remove support for older protocol API versions. We'd base that decision on user feedback and available analytics. So removing the method does create a path forward - on a 12-24 month timeframe, I would think - to truly deleting it.

2020-10-05 14:44 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/labware.py
> +    def _from_center_cartesian(self, x: float, y: float, z: float) -> Point:
Here, I agree with Seth and Max. I think we should not plan to delete the method, but rather the API versions it was compatible with.

2020-10-05 14:44 UTC, Laura-Danielle commented on api/src/opentrons/protocol_api/labware.py
> +        return self._geometry.from_center_cartesian(x, y, z)
In these instances, we typically called the new public method on the class rather than the underlying implementation. (i.e. `self.from_center_cartesian(x, y, z)`) but I will leave it up to you as to whether you want to do this.

2020-10-05 14:45 UTC, Laura-Danielle approved these changes
lgtm. Added two cents to the delete conversation and a small comment at the call site of `_from_center_cartisean`, but neither is blocking to merging this thing.

2020-10-05 15:20 UTC, merged