chore(scripts): add script to write version from git to package.json
OpenTrons/opentrons-api pull request #6669
Opened 2020-10-02 18:52 UTC by mcous

## overview

This is a bit of an RFC for the [Release Automation Initiative](https://coda.io/d/Release-Automation-Initiative_dJclFpoTy5u), sepcifically focused on the "Move Versions to Git" step.

This PR adds a script to the repo (without using it) that reads `git describe` and uses it to construct the version string for every project in the repo.

- A project may specific a `tagPrefix`, e.g. `protocol-designer@` to filter `git describe`
- The version logic is:
    - If commit is exactly a tag, use the version from the tag
    - If last tag was a regular version, construct a pre-minor version with git describe metadata
        - e.g. `2.2.4 ->  2.3.0-dev.31+55daec2c6`
        - Went with minor rather than patch because that's our regular releases from `edge`
    - If last tag was a pre-release version, increment the pre-release with git describe metadata
        -e.g. `3.0.0-beta.3 -> 3.0.0-beta.4-dev.1+bc625168e`
- Version format was selected to be:
    - Compatible with semver
    - Normalizable according to [PEP 440 - Version Identification and Dependency Specification](https://www.python.org/dev/peps/pep-0440/)
- `pyproject.toml` support is not included, but could be if we thought it would help switch to poetry or anything like that
    - Went with RegExp over JSON parsing to be a little more flexible in this regard without having to pull in an external TOML parsing lib

## changelog

chore(scripts): add script to write version from git to package.json

## review requests

So the sort of hypothetical workflow that this slots into looks like this:

0. Set all local versions to `0.0.0-dev` (using this script's `--reset` flag) and commit it
    - We do this once to declare "we now use git for versions"
1. In CI, we run this script before building any assets
    - The script will write definitive versions to the `package.json` files
    - The built assets will have those versions using the existing mechanisms of their build systems
        - This may mean we can remove custom version code in PD, but that would not be required
2. On a release tag, the logic of this script means that the assets being released will have a release version written to the assets
    - This script **doesn't care about the release itself**, it's just here to write versions

### play around with it

The usage instructions are in the script! If you clone this branch, run:

```shell
# print usage text
node scripts/write-versions-from-git.js --help

# see what would happen if you ran the --reset helper
node scripts/write-versions-from-git.js --dryrun --reset

# see what would happen if you ran the regular logic
node scripts/write-versions-from-git.js --dryrun
```

Try it out without `--dryrun` to watch it actually write files. Also, try jumping around your git history to see if you get the versions you expect.

## risk assessment

N/A; script is not used. Script will be a source of future risk if we decide to merge this PR and use it, thought.

2020-10-02 18:56 UTC, mcous commented on scripts/write-versions-from-git.js
> +"{next_version}-snapshot.{commits_since_tag}-{commit_sha}"
```suggestion
"{next_version}-dev.{commits_since_tag}+{commit_sha}"
```

2020-10-02 19:14 UTC, SyntaxColoring commented
I don't know if we care, but one thing that surprised me about `git describe` is that, on its own, it will *not* point out if there were any untracked changes involved in the build.

So, you could:

1. Check out tag `3.21.0`.
2. Change some files.
3. Leave those files uncommitted.
4. Build the software.

And the version string will still be `3.21.0`, instead of `3.21.0-dirty` or `3.21.0-dev` or something.

-----

You can do `git describe --dirty`, which will append `-dirty` if there are any uncommitted changes to tracked files.

But `git describe --dirty` ignores entirely *new* files. To detect those, you need [some more scripting](https://stackoverflow.com/questions/2657935/checking-for-a-dirty-index-or-untracked-files-with-git).

2020-10-02 19:34 UTC, sfoster1 requested changes
Definitely looks like it will work but I honestly think it could be a lot better if we build in more integration to the package.json tree and read and handle json files with native js machinery. We're not supporting toml so we don't have to worry about that for now; and I think that loading a toml file is entirely a reasonable thing to add a dev dependency for.

2020-10-02 19:34 UTC, sfoster1 commented on scripts/write-versions-from-git.js
> +// TODO(mc, 2020-10-02): pull from filesystem somehow? this information
Yeah isn't this the `workspaces` key of the top-level `package.json`

2020-10-02 19:34 UTC, sfoster1 commented on scripts/write-versions-from-git.js
> +const RE_CURRENT_VERSION = /"version": "([a-z0-9.-]+)"/
I see the reasons for it in the commit message but I will say I'm a little uncomfortable parsing json like this. Especially since we're not supporting toml at first anyway, I really think we should load and re-emit the json files and handle them in memory as json.

2020-10-05 13:29 UTC, sfoster1 commented
> I don't know if we care, but one thing that surprised me about `git describe` is that, on its own, it will _not_ point out if there were any untracked changes involved in the build.

I don't think we  really care about this. For our use cases, only CI builds are distributable artifacts, and those won't have these kinds of modifications. We can make builds outside of ci have -dev tags unconditionally.

2020-10-05 19:19 UTC, sfoster1 approved these changes
Really like this!

2020-10-27 17:38 UTC, mcous commented
Closing this RFC PR as "accepted". **Please do not delete this branch!**

This will come back as a part of an actual release process overhaul

2020-10-27 17:38 UTC, closed without merging