refactor(api):  more well and labware refactors
OpenTrons/opentrons-api pull request #6671
Opened 2020-10-02 20:47 UTC by amitlissack

# Overview

Another step in Labware refactor. Goals are to reduce the amount of work done by Well and Labware.

# Changelog

- Created a `WellImplementation` class which `Well` will delegate all work to. `WellImplementation` can become our internal replacement for `Well`. A class that knows nothing of protocols. 
- Moved `Labware._create_indexed_dictionary` logic out of Labware and into its own class `WellGrid`. 
- **Next Step**: move tip tracking from Labware into a separate class. It's only dependency would be the `WellGrid`

# Review requests

**WIP. Just looking for comments on direction.**

**Notice that this builds on the unmerged https://github.com/Opentrons/opentrons/pull/6666**

Is this a good step forward?

# Risk assessment

Medium. This doesn't touch public interface of Labware or Well, but modifies the guts a lot.

2020-10-05 13:40 UTC, sfoster1 requested changes
A couple nits, but the thing I'd really like to see is the addition of a warning in the private method `_from_center_cartesian`

2020-10-05 13:40 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +    def _from_center_cartesian(self, x: float, y: float, z: float) -> Point:
Since this only exists as a patch for people inappropriately using it in protocols, could we maybe
1. refactor `from_center_cartesian` to call `self._geometry.from_center_cartesian` so this method is never called internally
2. issue a `log.warning()` to stop using this

That warning won't be seen on a normal upload but if somebody's using `opentrons_simulate` they'll know

2020-10-05 13:40 UTC, sfoster1 commented on api/src/opentrons/protocols/geometry/well_geometry.py
> +class WellGeometry:
Wonder if we could get a bit fancier with either inheritance and a metaclass to provide `CircularWell` and `RectangularWell` specializations or using a union-discriminated props typed dict to avoid the `type: ignore`s in `center`

2020-10-05 13:40 UTC, sfoster1 commented on api/src/opentrons/protocols/implementations/well_grid.py
> +    pattern = re.compile(r'^([A-Z]+)([1-9][0-9]*)$', re.X)
This really feels like something that should be in the shared-data python bindings. It's so specific to key names in the labware definition.

2020-10-05 13:40 UTC, sfoster1 commented on api/src/opentrons/protocols/implementations/well_grid.py
> +class Grid(NamedTuple):
not dataclass?

2020-10-05 13:40 UTC, sfoster1 commented on api/src/opentrons/protocols/implementations/well_grid.py
> +            assert match, 'could not match well name pattern'
include the well name pattern and the well name in the error message

2020-10-05 13:42 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +        return self._impl.has_tip()
This has always bugged me about the way we express whether a labware is a tiprack. I really wish we could have some type-level distinction between things that are tipracks and things that aren't. I don't know if this is the right time to do that, but I wish it was.

2020-10-05 13:53 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +    @requires_version(2, 8)
Oh this should probably be explicitly documented in the part of [new_labware.rst](https://github.com/Opentrons/opentrons/blob/edge/api/docs/v2/new_labware.rst) that talks about positioning within wells

2020-10-05 13:54 UTC, sfoster1 commented on api/src/opentrons/protocol_api/labware.py
> +    @requires_version(2, 8)
And in the version table in [versioning.rst](https://github.com/Opentrons/opentrons/blob/edge/api/docs/v2/versioning.rst)

2020-10-05 15:44 UTC, amitlissack commented on api/src/opentrons/protocol_api/labware.py
> +        return self._impl.has_tip()
I don't see that happening in this PR.

2020-10-05 17:10 UTC, amitlissack commented on api/src/opentrons/protocol_api/labware.py
> +    def _from_center_cartesian(self, x: float, y: float, z: float) -> Point:
Chose a simpler approach.

2020-10-05 17:11 UTC, amitlissack commented on api/src/opentrons/protocols/geometry/well_geometry.py
> +class WellGeometry:
Chose a simpler approach.

2020-10-06 15:45 UTC, mcous approved these changes
IMO this makes some really good readability progress and looks like it will slot in nicely with neutral engine work

🎺

2020-10-06 17:29 UTC, Laura-Danielle approved these changes
I like this a lot!

2020-10-06 18:05 UTC, b-cooper commented on api/src/opentrons/protocols/implementations/well_grid.py
> +    """A helper class to access extract row and column information from
```suggestion
    """A helper class to extract row and column information from
```

2020-10-06 18:12 UTC, b-cooper commented
🔢 !

2020-10-06 18:12 UTC, sanni-t approved these changes
🙌

2020-10-06 20:39 UTC, sfoster1 approved these changes
Nice! Big step forward

2020-10-07 12:39 UTC, merged