refactor(app): Support tlc + poc flow in the app
OpenTrons/opentrons-api pull request #6709
Opened 2020-10-09 01:19 UTC by Laura-Danielle

# Overview

This PR finishes out functionality for the app to support a tip length calibration + pipette offset flow when a user is trying to recalibrated a tiprack that was used in the pipette offset flow.

# Changelog

- Made the labware type in the app generic for all session types
- Added in missing logic for calibration block support in the pipette offset calibration
- Check the tiprack being calibrated against the tiprack saved for pipette offset
- Changed some names for session params
- Launch a TLC + Pip Offset from the `TipLengthControl` page

# Review requests

Please test out both flows fully on a robot. See the test plan below.

# Risk assessment

Low. Behind a feature flag.

## Test Plan
1. Perform a tip length calibration (without any pip offset, or using a different tiprack)
   a. It should function as normal with no changes to the designs.
2. Perform a pipette offset calibration from the `Pipettes & Modules` page.
    a. It should function as normal with no changes to the designs.
3. Perform a tip length calibration using a tiprack that was used in a pipette offset calibration
    a. The flow should first calibrate the tip length and then use that tip length to calculate the pipette offset. The flows should be separate but connected (i.e. the tip length flow has all of the normal screens, a modal pops up asking you to continue to the pip offset and then the pip offset flow has all of the normal screens).

2020-10-09 12:46 UTC, sfoster1 requested changes
Couple nits but the structure looks good

2020-10-09 12:46 UTC, sfoster1 commented on app/src/pages/Calibrate/Pipettes.js
> +    ? tipRackURI === pipetteOffsetCalibration.tiprackUri
While we need the URI for identifying a tiprack to a user, a comparison of what was calibrated like this should probably use the definition hashes

2020-10-09 12:46 UTC, sfoster1 commented on app/src/pages/Calibrate/CalibrateTipLengthControl.js
> +    if (isExtendedPipOffset && useTrashSurface.current !== null) {
We should probably test that `dispatchRequests` is called with the right kind of session based on the input here

2020-10-09 12:46 UTC, sfoster1 commented on app/src/pages/Calibrate/CalibrateTipLengthControl.js
> +          {isExtendedPipOffset ? (
and if we're doing component tests we can check whether `CalibratePipetteOffset` or `CalibrateTipLength` gets rendered

2020-10-09 15:16 UTC, b-cooper requested changes
Looks good overall, will test on my robot.  There are a couple of confusing leftovers in the pip offset user flow that are mixed in with the new code that I commented on.

2020-10-09 15:16 UTC, b-cooper commented on robot-server/robot_server/robot/calibration/pipette_offset/user_flow.py
> +                unmet_condition="tip length calibration data does not exist")
The helper here is a little cofusing, but the `unmet_condition` param is a string that describes what should be true in order to proceed, but in this case is not true.  Now that we've `should_perform_tip_length` is the check, the `unmet_condition` would be something more crunchy like "not performing tip length calibration". Because you're not supposed to `move_to_tip_rack` from the `labwareLoaded` state if you are performing tip length calibration.

The same goes for the other `flag_unmet_transition_req` below

2020-10-09 15:16 UTC, b-cooper commented on robot-server/robot_server/robot/calibration/pipette_offset/user_flow.py
> +                unmet_condition="incorrect state machine loaded")
this string will be returned to the client in the event that they try to go down the correct path. Maybe the semantics of the `flag_unmet_transition_req` should be updated, but right now this would print something like 

"""
The command handler move_to_reference_point may not occur in the state labwareLoaded when incorrect state machine loaded is not true
"""

Because of the included negative, this is an inaccurate statement.

`unmet_condition="performing additional tip length calibration"`

would be more accurate here.

2020-10-09 15:16 UTC, b-cooper commented on robot-server/robot_server/robot/calibration/pipette_offset/user_flow.py
> +    def _initialize_deck(self):
this method was removed in favor of the separated `_load_tip_rack` and `_load_calibration_block` functions.  Either they should be re-updated to cover adding the lw to the deck (and this function removed). 

Alternatively, if we know now that we won't need to add or remove a calibration block after starting a session, then we can move the guts of both back into this method. And we can also delete all of the stuff surrounding `set_has_calibration_block`.

2020-10-09 15:22 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/pipette_offset/user_flow.py
> +                not self.has_calibrated_tip_length and\
It is updated once the tip length is saved in `save_offset()`. It will throw an error if you try to calibrate pip offset with non-default tipracks (which you can't even do at the moment).

I think we should still keep it in because it is a valid check.

2020-10-09 18:09 UTC, sfoster1 requested changes
Works as intended but
- We display "remove the calibration block" right after the tip length portion when the tip is still touching the block, so you can't actually move it. We should retract or something
- We _also_ display "remove the calibration block" when the flow as a whole terminates, so if you're doing the fused tlc + pipette offset then you see it twice

2020-10-09 21:18 UTC, sfoster1 approved these changes
Tested, works for me!

We probably need to do the same logic when we start a tip length calibration from the pipettes & modules page but in reverse (e.g. if there's no tip length calibrated for the pipette, do a tip length calibration first) but we can do that in a follow up pr

2020-10-12 16:37 UTC, nusrat813 approved these changes
Flows are working as intended, however need to verify that the calculation is being saved correctly. Currently looks like it is using old tip length logic

2020-10-12 18:09 UTC, b-cooper approved these changes
Looks good. Just a few small things to address

2020-10-12 18:09 UTC, b-cooper commented on app/src/components/InstrumentSettings/PipetteOffsetCalibrationControl.js
> +            hasBlock={false}
This feels a little weird, as hasBlock is set everywhere else by whether or not the user has access to a calibration block.  This would be a good place for an optional prop that defaults to `null`.  That way we can tell the difference between not having a cal block and not needing one.

In that case, this instance wouldn't need to specify the `hasBlock` prop at all.

2020-10-12 18:09 UTC, b-cooper commented on app/src/sessions/pipette-offset-calibration/constants.js
> +export const PIP_OFFSET_STEP_COMPLETE_TIP_LENGTH: 'tipLengthComplete' =
for clarity, this const name should probably match the string value `PIP_OFFSET_STEP_TIP_LENGTH_COMPLETE`.

2020-10-12 18:09 UTC, b-cooper commented on robot-server/robot_server/robot/calibration/pipette_offset/user_flow.py
> +                unmet_condition="tip length calibration data does not exist")
These `unmet_condition` values still need to be updated

2020-10-12 18:29 UTC, sfoster1 approved these changes
Just reiterating approval after @nusrat813 blew away my nice checkmark >:(

2020-10-12 18:38 UTC, Laura-Danielle commented on app/src/components/InstrumentSettings/PipetteOffsetCalibrationControl.js
> +            hasBlock={false}
I had this before because of some wonky ordering in the create params b/c of unions + pydantic -- it wouldn't recognize this was pip offset unless I had specified it. It should be resolved now that there is only one create param model for both tip length cal & pip offset cal. I will remove it.

2020-10-12 23:15 UTC, merged