chore: include notify-server in buildroot build
OpenTrons/opentrons-api pull request #6775
Opened 2020-10-14 21:50 UTC by amitlissack

# Overview

closes #6746 

# Changelog

# Review requests

TBD

# Risk assessment

None

2020-10-15 12:31 UTC, sfoster1 requested changes

2020-10-15 12:31 UTC, sfoster1 commented on notify-server/setup.py
> +"""A setuptools based setup module.
If we're going to check this in, IMO we should mark it binary in git; and we should also either
- Figure out a way to autogenerate it in a github workflow or something (don't know if we can do this)
- Autogenerate it in a github workflow, and have a lint check that autogenerates it, compares it to what was checked in, and fails the pr if the two differ to make sure we can't forget to run `make setup-py` if we change poetry

2020-10-15 12:37 UTC, amitlissack commented on notify-server/setup.py
> +"""A setuptools based setup module.
Thanks, I forgot about this issue. There is no reason to have it in source control.

My preference would be to not check it in. How would you suggest I generate it for the buildroot build?

2020-10-15 12:48 UTC, sfoster1 commented on notify-server/setup.py
> +"""A setuptools based setup module.
Well, there's a couple ways
- You could add `poetry_setup` to buildroot as a _host_ python package. I am not sure how well this will work, but if the answer is "very well, thank you" then you can run it in `buildroot.mk`.
- You could add it to the buildroot dockerfile and run it in the dockerfile outside of buildroot (gross)
- You could change our devops workflow so that the buildroot workflow pulls artifacts from github, and build wheels with `setup.py` in them in github workflows (this is probably what we should do longterm)
- You could try and set up a github workflow that runs on prs and amends them dynamically, which would be gross and I don't know if it would be possible but I bet it would be

2020-10-15 12:56 UTC, amitlissack commented on notify-server/setup.py
> +"""A setuptools based setup module.
I vote 3. Where is our devops workflow for buildroot? How do i get started?

2020-10-19 16:30 UTC, mcous commented on notify-server/pyproject.toml
> +poetry-setup = "^0.3.6"
We talked about this during an in-person review, but it looks like the author of poetry-setup has [deprecated it](https://github.com/orsinium-archive/poetry-setup/commit/79159373aef389216e3018a94a584728fe02699d) in favor of a tool called [dephell](https://github.com/dephell/dephell) which looks to be able to do the same thing

2020-10-21 14:15 UTC, amitlissack commented on notify-server/setup.py
> +"""A setuptools based setup module.
I've abandoned poetry.

2020-10-21 14:15 UTC, amitlissack commented on notify-server/pyproject.toml
> +poetry-setup = "^0.3.6"
This is abandoned.

2020-10-27 15:46 UTC, mcous approved these changes
I think this looks good, but there's a couple things that look like potentail naming inconsistencies that I thought I should point out

2020-10-27 15:46 UTC, mcous commented on notify-server/Makefile
> +wheel_file = dist/$(call python_get_wheelname,notify-server,notifyserver,$(BUILD_NUMBER))
I'm not really up to date with what `python_get_wheelname` expects, but is the Python package name `notify_server` (with the underscore), and if that's true, does that mean the call should be this?

```suggestion
wheel_file = dist/$(call python_get_wheelname,notify-server,notify_server,$(BUILD_NUMBER))
```

2020-10-27 15:46 UTC, mcous commented on notify-server/setup.py
> +DISTNAME = 'notifyserver'
This is probably 100% related to my question above, but is there a reason the underscore went away?

2020-10-28 22:06 UTC, sanni-t approved these changes

2020-10-29 11:17 UTC, amitlissack commented on notify-server/Makefile
> +wheel_file = dist/$(call python_get_wheelname,notify-server,notifyserver,$(BUILD_NUMBER))
Just following the pattern of `robotserver`.

2020-10-29 12:38 UTC, sfoster1 requested changes
Looks good overall, but two key things
- Let's typecheck the tests too
- I hate makefiles

2020-10-29 12:38 UTC, sfoster1 commented on notify-server/Makefile
> +	$(python) -m mypy $(SRC_PATH)
Let's get ahead of the game compared to our other systems and typecheck tests from the beginning

2020-10-29 12:38 UTC, sfoster1 commented on notify-server/buildroot.mk
> +define get_pkg_json_key
We should name this macro PYTHON_OPENTRONS_NOTIFY_SERVER_get_pkg_json_key or PONS_get_pkg_json_key or something because every single makefile gets processed during the build and make doesn't have any namespacing or anything, so if other makefiles have (or later gain) a definition like this they'll stomp on each other, and since the path to package json is interned here it'll have different weird behaviors

2020-10-29 12:38 UTC, sfoster1 commented on notify-server/setup.py
> +if os.name == 'posix':
I think this isn't necessary anymore; it had been necessary in the specific case of a) using travis and b) having the build process emit the names of all the json files, like labware defs or whatever, that were getting packed

2020-10-29 12:38 UTC, sfoster1 commented on notify-server/setup.py
> +DISTNAME = 'notifyserver'
Yeah while it will all technically work if the wheel and package name is not the same as the actual installed python package (see pyserial, for instance) it would be nice if the name of the distribution was the same as the thing you give `import`.

2020-10-29 18:13 UTC, amitlissack commented on notify-server/tests/integration/test_pub_sub.py
> +    await sleep(.1)
I'm not proud of myself for this.

2020-11-02 13:31 UTC, sfoster1 approved these changes
lgtm! can't wait to publish and subscribe

2020-11-02 16:29 UTC, merged