refactor(app, api): calibration check middleware
OpenTrons/opentrons-api pull request #6781
Opened 2020-10-15 13:36 UTC by Laura-Danielle

# Overview

This PR ports calibration check over to the new architecture style/design of the other calibration flows. It also changes the name from `Robot Calibration Check` -> `Robot Calibration Health Check`. Closes #6725 and closes #6710.

# Changelog
Will record the change log once this PR is complete.

# Review requests

This is a WIP. Server is pretty much ready for review, but the app still needs some screen flow changes. Tests also need to be fixed up still.

# Risk assessment

High. This is completely changing how the calibration check session worked previously, although we are not releasing immediately, we should be weary of any new bugs that might get introduced.

2020-10-16 16:18 UTC, b-cooper approved these changes
awesome!  🔑

2020-10-16 16:18 UTC, b-cooper commented on app/src/components/CalibrationPanels/TipConfirmation.js
> +  const isBadTipPickUp =
We should move this cal check specific step/panel combination into it's own file in the CheckCalibration component directory. That way these generic panels don't have to serve every special case. This example is branching only on currentStep (within a check cal session), which is exactly what the parent component step/panel mapping does, it should just slot in there.

2020-10-16 16:18 UTC, b-cooper commented on app/src/components/CheckCalibration/index.js
> +const ROBOT_CALIBRATION_CHECK_SUBTITLE = 'Calibration heatlh check'
```suggestion
const ROBOT_CALIBRATION_CHECK_SUBTITLE = 'Calibration health check'
```

2020-10-20 13:55 UTC, sfoster1 requested changes
Lots of little change requests to keep in mind

2020-10-20 13:55 UTC, sfoster1 commented on app/src/components/CalibrationPanels/SaveXYPoint.js
> +    let commands = null
does the stuff in 190:196 only apply to `isHealthCheck === true`? if so consider moving it into the if block on 185:187. Also consider making this a `const`-binding using an anonymous function or a logical expression like a ternary, eg
```
const commands = isHealthCheck  
    ?( (finalCommand && activePipette?.rank
          ? ... 
           : ...)
    : ...)
```

2020-10-20 13:55 UTC, sfoster1 commented on app/src/components/CalibrationPanels/DeckSetup.js
> +  'Place full tip rack(s) and Calibration Block on the deck within their designated slots as illustrated below.'
it's a little thing, but in all flows except cal check this will never have multiple tip racks. consider either making separate values or making this a function that accepts the number of tipracks or something.

2020-10-20 13:55 UTC, sfoster1 commented on app/src/components/CalibrationPanels/SaveZPoint.js
> +  if (sessionType === Sessions.SESSION_TYPE_CALIBRATION_HEALTH_CHECK) {
Consider using `const`-binding here with a ternary or something.

2020-10-20 13:55 UTC, sfoster1 commented on app/src/components/CalibrationPanels/types.js
> +  checkBothPipettes?: boolean | null,
This is growing a whole lot of optional attributes. While we don't have to do it now, we should at the very least drop a todo to refactor this into a union type discriminated on the session type.

2020-10-20 13:55 UTC, sfoster1 commented on app/src/components/CheckCalibration/ResultsSummary.js
> +  ].reduce((acc, step): CalibrationHealthCheckComparison | null => {
We needed this last-failed logic in the old system because of the overlapping of the calibration components; I don't think we need it anymore. Honestly since we're already going to have the marked-bad logic on the server side, it might be worth having the server just tell us which calibrations are a problem, and generating the troubleshooting screen based on that. In the interim, I think we definitely don't need this logic here.

2020-10-20 13:55 UTC, sfoster1 commented on app/src/components/CheckCalibration/ReturnTip.js
> +  let commandsList
consider using `const`-binding and a ternary here

2020-10-20 13:55 UTC, sfoster1 commented on app/src/components/CheckCalibration/ReturnTip.js
> +        ${!onFinalPipette ? CONTINUE_TO_NEXT : EXIT_PROGRAM}`}
minor but if it's a binary comparison can we use positive logic e.g. `${onFinalPipette ? EXIT_PROGRAM : CONTINUE_TO_NEXT}`

2020-10-20 13:55 UTC, sfoster1 commented on app/src/components/CheckCalibration/ReturnTip.js
> +        {!onFinalPipette ? CONTINUE : EXIT}
same thing about positive logic

2020-10-20 13:55 UTC, sfoster1 commented on app/src/sessions/selectors.js
> +  const modelsByMount: Types.AnalyticsModelsByMount = instruments.reduce(
Since we removed the analytics above, do we actually need this selector? And if we do, should it be here?

2020-10-20 13:55 UTC, sfoster1 commented on app/src/sessions/selectors.js
> +  const { comparisonsByPipette, activePipette } = session.details
Do we need this selector?

2020-10-20 13:55 UTC, sfoster1 commented on app/src/sessions/selectors.js
> +      [`${instrument.mount.toLowerCase()}PipetteModel`]: instrument.model,
[comment is not actually about this line] We should probably move calibration check selectors, actions, epics, etc into a `calibration-check` subdirectory like we have for `pipette-offset-calibration`, `tip-length-calibration`, etc

2020-10-20 13:55 UTC, sfoster1 commented on app/src/support/intercom-event.js
> +      const eventProps = null
If we're gonna do this we should probably just delete 14:25 and unconditionally return null, but also we probably shouldn't do this, we should remove the function

2020-10-20 13:55 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +    def can_distinguish_instr_offset(self):
i think this is copy/pasted but marking it for change anyway - the answer to this is now always "yes"

2020-10-20 13:55 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +    def _load_active_tiprack(self) -> labware.Labware:
this also might have been copy/pasted, but rather than looking up the tipracks like this we should use the tipracks specified in the pipette offset calibration

2020-10-20 13:55 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +        MODULE_LOG.info(f"HW PIPS: {hw_pips}")
remember to remove or lower level

2020-10-20 13:55 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +        MODULE_LOG.info(f"INFO PIPS: {info_pips}")
remember to remove or lower level

2020-10-20 13:55 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +            tip_length=self._hw_pipette.config.tip_length,
now's probably a good time to fix mike's comment about making this camelCase

2020-10-20 13:55 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +    def _get_error_source(
main refactor target to get the right behavior (is that something we want to do in this pr?)

2020-10-20 13:55 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +        point = self.active_tiprack.wells()[0].top().point + \
probably want similar logic as what's now in the other calibration flows around using the saved point for the tiprack

2020-10-20 13:55 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +        if self._hw_pipette.has_tip:
this is a good change but does it belong here?

2020-10-20 13:55 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/models.py
> +        description='The full tiprack definition(s)'
this is definitely set up to be a single tip rack definition, if we want it to be possibly-multiple we should probably make the type `List[dict]` and change the session creators

2020-10-20 13:55 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/pipette_offset/user_flow.py
> +    @property
good change but does it belong in this pr?

2020-10-20 13:55 UTC, sfoster1 commented on robot-server/robot_server/service/session/router.py
> +    log.info("delete was called! ")
remember to remove/lower level

2020-10-20 13:55 UTC, sfoster1 commented on robot-server/robot_server/service/session/router.py
> +    log.info(f"session object {session_obj}")
remember to remove/lower level

2020-10-20 13:55 UTC, sfoster1 commented on robot-server/robot_server/service/session/session_types/check_session.py
> +        # create params right now because of the pydantic union problem.
rather than having it be optional, having it be a list that therefore may be empty is probably a good choice

2020-10-20 14:25 UTC, Laura-Danielle commented on app/src/sessions/selectors.js
> +  const modelsByMount: Types.AnalyticsModelsByMount = instruments.reduce(
Brian wanted us to keep the selectors, but disconnect them.

2020-10-20 14:26 UTC, Laura-Danielle commented on app/src/sessions/selectors.js
> +      [`${instrument.mount.toLowerCase()}PipetteModel`]: instrument.model,
Should I do that in this PR or put a TODO about it?

2020-10-20 14:26 UTC, Laura-Danielle commented on app/src/sessions/selectors.js
> +  const { comparisonsByPipette, activePipette } = session.details
Re- other selector comment, brian wanted us to keep the selector implementations around

2020-10-20 14:28 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/deck/user_flow.py
> +        if self._hw_pipette.has_tip:
I can remove it and put a TODO. It was just annoying when my robot went to return a tip that wasn't necessary

2020-10-20 14:29 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/models.py
> +        description='The full tiprack definition(s)'
I'll change the description back. Basically was having a lot of issues w/ pydantic models -- I wanted to have an optional create param for check calibration but it was mixing up deck cal w/ check cal when I didn't specify the tipracks I wanted to use. Then I thought about adding it to this model, but realized it just wasn't worth it at this point.

2020-10-20 14:34 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/pipette_offset/user_flow.py
> +    @property
I made the change before your other PR that was put up. I'm going to be rebasing anyways so I'll probably just remove this to make it easier.

2020-10-20 14:46 UTC, b-cooper commented on app/src/sessions/selectors.js
> +  const modelsByMount: Types.AnalyticsModelsByMount = instruments.reduce(
I was thinking if we're not wiring up the new analytics in this PR, then we should keep the old selectors around until it's time to add them back in. In case some of them are used wholesale, or slightly just tweaked.

2020-10-20 23:03 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +    def _get_error_source(
Nope, mostly just wanted to port everything over to the new system and get it working. I'll throw in TODOs on behavior that needs to change

2020-10-21 19:17 UTC, sfoster1 reviewed
Code all looks good to me, will test some

2020-10-21 19:17 UTC, sfoster1 commented on robot-server/robot_server/service/session/session_types/check_session.py
> +        # await configuration.hardware.cache_instruments()
:raised_eyebrow:

2020-10-22 02:00 UTC, Laura-Danielle commented on robot-server/robot_server/service/session/session_types/check_session.py
> +        # await configuration.hardware.cache_instruments()
oops!

2020-10-22 13:15 UTC, sfoster1 approved these changes
lgtm!

2020-10-22 13:41 UTC, merged