refactor(app): checks pip offset cal data before showing clear deck cal warning
OpenTrons/opentrons-api pull request #6826
Opened 2020-10-20 19:54 UTC by ahiuchingau

Currently, even if you don't have any pipette offset data stored on the robot, a warning would show up telling you that starting deck cal will wipe all pipette offset and tip length data. 

This PR updates this so that the warning modal only shows up if pip offset data are detected.

2020-10-20 20:47 UTC, sfoster1 requested changes

2020-10-20 20:47 UTC, sfoster1 commented on app/src/components/RobotSettings/__tests__/DeckCalibrationControl.test.js
> +          pipOffsetDataPresent={true}
This should test the actual behavior of the modal, and make sure that
- if it's true you don't get a confirmation modal, the flow just starts
- if it's false you do get a confirmation modal

2020-10-21 16:07 UTC, sfoster1 approved these changes
LGTM!

2020-10-21 16:28 UTC, Laura-Danielle commented on app/src/components/RobotSettings/DeckCalibrationControl.js
> +      {showConfirmStart && pipOffsetDataPresent && (
This might get very confusing for users if we block deck cal from opening just because there is no pip offset data.

Doesn't need to be addressed in this PR, but maybe we need to add a modal or something to that effect instructing user that they need to go perform pip offset.

2020-10-21 17:21 UTC, b-cooper approved these changes
📃

2020-10-21 17:22 UTC, merged