feat(api): Prevent Python API v1 protocol upload in server version 4.0.0
OpenTrons/opentrons-api pull request #6841
Opened 2020-10-22 04:16 UTC by Laura-Danielle

# Overview
This PR prevents python protocol api v1 upload in server version 4.0.0. 

# Changelog

- prevent api v1 upload during simulation
- remove a lot of irrelevant tests
- convert other tests to expect an error
- remove a lot of un-used sample protocols

# Review requests

Please review the message and let me know if it sounds OK!

# Risk assessment

Med-High, we're deprecating api v1 -- we want to make sure the message is clear/to the point and readable.

2020-10-22 13:06 UTC, sfoster1 requested changes
This is looking good but we should also disallow importing `robot`, `pipette`, etc from the top level using this: https://www.python.org/dev/peps/pep-0562/ to raise the same error if you try.

2020-10-22 13:06 UTC, sfoster1 commented on api/src/opentrons/protocols/types.py
> +The python protocol you uploaded has the Python API Version {0}.  Robot server version 4.0.0 is
I think it's probably safe to hardcode version 1 here but if you're going to make dynamic you should probably add a minimum-supported constant and format it in on lines 79 and 81.

2020-10-22 13:06 UTC, sfoster1 commented on api/tests/opentrons/api/test_session.py
> -async def test_load_from_text(session_manager, protocol):
:smile:

2020-10-22 14:38 UTC, ahiuchingau reviewed
👏   awesome

2020-10-22 14:40 UTC, amitlissack reviewed
This may be my favorite PR ever!

2020-10-23 12:43 UTC, sfoster1 requested changes
Couple little details to fix up here

2020-10-23 12:43 UTC, sfoster1 commented on api/src/opentrons/__init__.py
> +    # if attrname in LEGACY_MODULES:
let's remove the comments

2020-10-23 12:43 UTC, sfoster1 commented on api/src/opentrons/api/session.py
> -        if self._use_v2:
God yes

2020-10-23 12:43 UTC, sfoster1 commented on api/src/opentrons/legacy_api/instruments/pipette.py
> -    @commands.publish.both(command=commands.delay)
I think we want to still publish this

2020-10-23 12:43 UTC, sfoster1 commented on api/src/opentrons/protocols/api_support/definitions.py
> +MINIMUM_SUPPORTED_VERSION = types.APIVersion(2, 0)
:raised_hands:

2020-10-23 12:43 UTC, sfoster1 commented on api/src/opentrons/protocols/types.py
> +            self.version, APIVersion(2, 0))
`MINIMUM_SUPPORTED_VERSION`?

2020-10-23 13:41 UTC, Laura-Danielle commented on api/src/opentrons/legacy_api/instruments/pipette.py
> -    @commands.publish.both(command=commands.delay)
I left this code for other people to delete, but didn't feel like making the dependencies here work since the code is going to be deleted.

2020-10-23 13:53 UTC, sfoster1 commented on api/src/opentrons/legacy_api/instruments/pipette.py
> -    @commands.publish.both(command=commands.delay)
Oh I totally didn't notice this was in apiv1 never mind

2020-10-23 13:54 UTC, sfoster1 approved these changes
:1st_place_medal:

2020-10-23 14:10 UTC, merged