refactor(api): Modify cal check backend to match the new design flows
OpenTrons/opentrons-api pull request #6866
Opened 2020-10-27 18:36 UTC by Laura-Danielle

# Overview

Closes #6727. This adds support for tip length check in the check calibration health flow.

# Changelog
- Add in states to support tip length calibration checks
- Refactor the data models to store info based on calibration type (i.e. tip length calibration vs pip offset vs deck cal)
- Load tip rack based on pip offset if applicable
- Add the tip rack load name to each pipette attached for the intro screen
- Refactor tests to match new flow

# Items of work remaining

- Compare the tip length thresholds correctly
- Add in collision support to cal check
- Add in create params for cal check (running into pydantic union errors again, may be time to bite the bullet and finish the literal refactor)

# Review requests

Take a look at the data models and make sure it makes sense to you. @ahiuchingau let me know if there are other things you need for the front end that I might have missed here.

# Risk assessment

Medium. We should ensure this matches up with work done in #6839 so that the screens function correctly.

2020-10-27 19:14 UTC, sfoster1 requested changes
Aside from the thing about create params, we should really get some testing around the labware initialization.

Also, calibration health check is really only a reasonable thing to do if we actually have a full set of calibrations to check. We should bail with a 409 or something.

2020-10-27 19:14 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/models.py
> +    tipRacks: Optional[List[dict]] = Field(
Rather than making this an `Optional[List]` it could just be a `List` (which may be empty)

2020-10-27 19:14 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +        if tip_rack_def:
I think there's some things we can fix up here. First, there should always be an existing calibration (see the top-level change request). So this logic is actually just "do we have a definition for the tiprack in the def". So we should
- Pull the uri from the def
- See if a labware with that uri was specified in the create params
  - if it was, use it
- if no matching tiprack was specified, see if we know it internally
   - if we do, use that
- if we don't know a matching tiprack and we didn't get one in the create params, we probably should just fail to initialize the session, but another option would be to fall back to loading a standard tiprack for the volume (not checking the passed-in tip rack list: this is a failure state that we're trying to account for here)

2020-10-29 19:25 UTC, ahiuchingau commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +                tipRack=info_pip.tip_rack.load_name,
Could you switch this to `display_name` instead? It would work a lot better in the results screen

2020-10-29 20:44 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +                tipRack=info_pip.tip_rack.load_name,
Let's _add_ display name but also have the full URI available.

2020-10-29 21:01 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +                tipRack=info_pip.tip_rack.load_name,
🆗

2020-10-30 14:24 UTC, sfoster1 requested changes
Couple little things but the structure looks good, and if we fix this stuff up we should get it merged - it's going to be hard to comprehensively test until the frontend is in

2020-10-30 14:24 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/models.py
> +        Field('acceptable',
why does this have a default while the others dont? also could the type be a literal union?

2020-10-30 14:24 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/models.py
> +    status: str =\
could this type be a literal union?

2020-10-30 14:24 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/models.py
> +    status: str =\
could this be a literal union?

2020-10-30 14:24 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/models.py
>      rank: str
literal union?

2020-10-30 14:24 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/models.py
> +        None,
`[]`?

2020-10-30 14:24 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +        deck = get.get_robot_deck_attitude()
probably should check whether it's statically bad or identity etc

2020-10-30 14:24 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/user_flow.py
>          if len(pips) == 1:
can we drop a todo here to make this a little more general and have less repeated logic? that said, i think this is completely fine for this pr per [my personal bible](https://programmingisterrible.com/post/139222674273/write-code-that-is-easy-to-delete-not-easy-to)

2020-10-30 14:29 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/check/models.py
> +        Field('acceptable',
oops I should have removed that one

2020-10-30 18:36 UTC, sfoster1 approved these changes
:checkered_flag:

2020-10-30 18:56 UTC, merged