refactor(api): add waypoint planning without the use of Location
OpenTrons/opentrons-api pull request #6882
Opened 2020-10-29 04:15 UTC by mcous

## overview

In the protocol engine, we need access to motion planning to be able to accomplish pipette movements. However, the existing functions in `opentrons.protocols.geometry.planning` (specifically, `plan_moves`) is tightly coupled to the Python Protocol API via its use of the `Location` class (and its reliance in that usage on the `Labware` and `Well` classes) as well as (to a lesser extent) the `Deck` class. See #6690 for more details on the difficulty of working with `Location`.

This PR adds a new function to `planning` called `get_waypoints`. Using existing clearance values and arc logic, it spits out a set of waypoints (the same output as `plan_moves`), but its inputs are simple `Points` along with various movement parameters that are based on geometry but to be calculated elsewhere.

I added a default `False` parameter to `plan_moves` called `use_experimental_waypoint_planning` to demonstrate how it would be used in "real life." Note that, when being used, it takes over for both:

- `opentrons.protocols.geometry.planning._build_safe_height`
- `opentrons.harware_control.util.plan_arc`

## Changelog

- refactor(api): add waypoint planning without the use of Location

## Review requests

While this PR is still up in draft state, I'll try to open up a PR using this function as part of #6763 for additional demonstation of its usage.

Otherwise:

- How does this look?
- How do the tests look?
- This produces different waypoints than the `plan_moves` tests expect, what does that mean?
    - Looks like it may be related to how `get_waypoints` will not emit some waypoints if the origin and/or desitination point is higher than the minimum required Z arc clearance 

## Risk assessment

Short term: N/A; it's not wired to anything
Longer term:
- Movement planning is a big deal, validating this extra hard would be important for actual usage
- If we were to ever use this in the Protocol API (pre-protocol engine), we'd need an PAPI version bump

2020-10-29 13:25 UTC, sfoster1 requested changes
Inline change requests.

Also, if I look at the interface to this function, I see no symbolic geometry at all (which is the point). IMO that means that rather than duplicating `hardware_control.util.plan_moves` here, we should make `hardware_control.planning.plan_moves`, move `hardware_control.util.plan_moves` there, and expand its functionality. Just looking at the input and output types, once you've boiled away all the symbolic geometry, what's left should be in the hardware controller.

Keep in mind this doesn't affect simulation vs run or anything - it's just a free function either way.

2020-10-29 13:25 UTC, sfoster1 commented on api/src/opentrons/protocols/geometry/planning.py
> +    Get waypoints between an origin point and a desitination point.
```suggestion
    Get waypoints between an origin point and a destination point.
```

2020-10-29 13:25 UTC, sfoster1 commented on api/src/opentrons/protocols/geometry/planning.py
> +    if move_type != MoveType.DIRECT:
nit: can we flip this and have
```
if move_type == MoveType.DIRECT:
   return (dest, dest_cp)
```

Saves an indent level and you don't have to keep it in mind while reading the rest of the function

2020-10-29 13:25 UTC, sfoster1 commented on api/src/opentrons/protocols/geometry/planning.py
> +        if dest.z + MINIMUM_Z_MARGIN > max_travel_z:
These errors are something that we have added a lot of detail to in `build_safe_height`, and that we often get requests to add more detail to. The failures that it catches stem from other problems (bad labware calibration and bad deck calibration), but this is the last place that we are able to catch them and need to have a very detailed error when they happen. If this error could arise in any other way than basically a bugcheck, we need to include detail about which labware is the problem, and explain the issue more (as in `_build_safe_height`)

2020-10-29 13:25 UTC, sfoster1 commented on api/src/opentrons/protocols/geometry/planning.py
> +    if move_type != MoveType.DIRECT:
These precondition checks need some comments about what they're accomplishing, or maybe the function as a whole needs some explanation of why it's doing what it's doing - e.g., using the combination of precondition checks and a minimax call to establish a z arc move inside some band

2020-10-29 13:25 UTC, sfoster1 commented on api/src/opentrons/protocols/geometry/planning.py
> +            max(min_travel_z + travel_z_margin, origin.z, dest.z)
We should probably make this check `max(min_travel_z, origin.z, dest.z) + travel_z_margin`. IMO we should always be adding at least a small margin to these points if we're doing an arc move.

2020-10-29 13:25 UTC, sfoster1 commented on api/src/opentrons/protocols/geometry/planning.py
> +        if travel_z > dest.z:
There's some trickiness with critical point transitions in here.

A guiding directive of all our motion planning is that emitted moves should be only in the plane of the deck or only in z/a. That gets pretty complicated when we're switching between critical points. 

The most common critical point swapping scenario is when going from default (`TIP`) to `XY_CENTER` - that's the `centerMultiChannelOnWells` quirk case. In this case, we need to change our target critical point from the origin cp to the dest cp in an xy move, which pretty much has to be this one, so we probably should have it unconditionally.

It's also worth considering cases, although they're rarer, of critical point transitions that involve z changes. Probably a larger question - we may need to have something like an in-plane cp and a z cp considered separately to get good motion in all cases.

2020-10-29 13:25 UTC, sfoster1 commented on api/src/opentrons/protocols/geometry/planning.py
> +        if travel_z > dest.z:
Honestly, conditionally adding the points like this feels like a premature optimization to me, and if we really really want to stick with it we should probably have it do a post-processing pass to coalesce identical waypoints.

2020-10-29 15:16 UTC, mcous commented on api/src/opentrons/protocols/geometry/planning.py
> +    if move_type != MoveType.DIRECT:
Hah I love an early return but was told at some point it wasn't very "Pythonic" so I've been avoiding it even though I want to do it. Happy to flip this

2020-10-29 15:46 UTC, mcous commented on api/src/opentrons/protocols/geometry/planning.py
> +        if dest.z + MINIMUM_Z_MARGIN > max_travel_z:
Something that I didn't put in this PR but that I think makes sense is to have these be separate motion-planning-specific errors that then the caller would catch and wrap with a more detailed explanaition. I think that huge explanaition chunk in `_build_safe_height` is a little gnarly and also doesn't look to me like it accurately capture.

Should I put that into this PR?

2020-10-29 15:47 UTC, mcous commented on api/src/opentrons/protocols/geometry/planning.py
> +            max(min_travel_z + travel_z_margin, origin.z, dest.z)
I had the same thought, but from reading our existing code, it seems like we're not currently doing that. I'm down, but it seems like it might make sense to try to get this behavior matching, first

2020-10-29 16:00 UTC, mcous commented on api/src/opentrons/protocols/geometry/planning.py
> +        if travel_z > dest.z:
I see, this misses a critical point transition. That can be tested for and added.

I disagree that it's premature optimization: each additional waypoint will result in an additional call to the hardware controller, which doesn't look to have any short-circuit available to it

2020-10-29 16:03 UTC, mcous commented
> Also, if I look at the interface to this function, I see no symbolic geometry at all (which is the point). IMO that means that rather than duplicating hardware_control.util.plan_moves here, we should make hardware_control.planning.plan_moves, move hardware_control.util.plan_moves there, and expand its functionality. Just looking at the input and output types, once you've boiled away all the symbolic geometry, what's left should be in the hardware controller.

For me, especially as a newcomer to this area of the codebase, it was pretty confusing to find motion/waypoint planning in the hardware control module. I think there deserves to be a geometry system that lives outside the harware_controller and outside the protocol system, hence the decision to put it in `planning.py` rather than `util.py`. I'd rather keep it here for now, or maybe make a new `geometry` / `motion_planning` module

2020-10-29 17:34 UTC, sfoster1 commented on api/src/opentrons/protocols/geometry/planning.py
> +        if dest.z + MINIMUM_Z_MARGIN > max_travel_z:
Yeah, please do

2020-10-29 17:35 UTC, sfoster1 commented
> For me, especially as a newcomer to this area of the codebase, it was pretty confusing to find motion/waypoint planning in the hardware control module. I think there deserves to be a geometry system that lives outside the harware_controller and outside the protocol system, hence the decision to put it in `planning.py` rather than `util.py`. I'd rather keep it here for now, or maybe make a new `geometry` / `motion_planning` module

Based on my heuristic of "does it involve symbolic geometry" I really think it doesn't belong in the protocols tree, at the very least.

2020-10-29 20:40 UTC, amitlissack reviewed
If we could divorce `Location.labware` from `Labware` and `Well`, would you still follow this path?

2020-10-29 20:40 UTC, amitlissack commented on api/src/opentrons/protocols/geometry/planning.py
> +
Minor nit: 

can we have temp vars for readability here? `same_labware` and `same_well`

2020-10-29 20:40 UTC, amitlissack commented on api/src/opentrons/protocols/geometry/planning.py
> +) -> List[Waypoint]:
10 arguments to this function!

Several are not in doc string and not obvious (to me at least).

2020-11-05 18:28 UTC, mcous commented on api/src/opentrons/protocols/geometry/planning.py
> +        if travel_z > dest.z:
Upon further inspection (via writing unit test cases), I actually can't figure out if/how this would miss a critical point transition, given that all our critical points transitions are in the XY and existing planning logic relies on this fact

I definitely acknowledge that this could change in the future, but that would require changes to our _existing_ arc planning code and probably the `CriticalPoint` interface, too

2020-11-05 18:36 UTC, mcous commented on api/src/opentrons/protocols/geometry/planning.py
> +            max(min_travel_z + travel_z_margin, origin.z, dest.z)
Following up: I would prefer to leave this as-is for now. Existing planning code _appears_ to ignore the height of the origin / destination entirely, which could cause a move _downwards_ in Z before moving over in XY, depending on the inputs.

Because saying "we always move up a little" introduces some clearance concerns we've never thought about or dealt with yet, it feels a little easier to me to say "we're already at/going to this z-height, so we know it is safe" _for now_ until we can examine the problem a little more closely.

2020-11-05 21:56 UTC, sfoster1 approved these changes
I like the new package! I think we should merge it and have it available to test in edge.

2020-11-06 16:40 UTC, amitlissack approved these changes
Looks good.

2020-11-06 16:40 UTC, amitlissack commented on api/src/opentrons/motion_planning/types.py
> +class Waypoint():
Minor point, but unless you're inheriting you don't need the `()`

2020-11-06 17:01 UTC, mcous commented on api/src/opentrons/motion_planning/types.py
> +class Waypoint():
I... honestly did not know that 😬 . It looks like sans-`()` is way more common in our codebase so I'll fix these up where I see them for consistency

2020-11-06 18:15 UTC, merged