refactor(app): remove attributes, types & meta from http models
OpenTrons/opentrons-api pull request #6887
Opened 2020-10-29 19:50 UTC by sanni-t

# Overview

This PR is part of the HTTP model flattening initiative to remove unused properties. See #6847 for more details.
Closes #

# Changelog

Removed attributes, types & meta from client-side http request/response models from
- All calibration models
- All Sessions models
- robot-server/system models

# Review requests

Check that the changes work well with server-side

# Risk assessment

High. Changes the structure of all http payloads

2020-10-29 19:56 UTC, amitlissack commented
We should probably review this for sanity then merge into the backend branch. The real testing can happen in that PR.

2020-10-30 15:21 UTC, mcous requested changes
Just need one change based on our mini pairing when we ran into that test that wasn't actually working. Rather than putting a confusing (and incorrect) assertion in, we should fix the mock data to better match what's in actual application state.

Once that's fixed I'm good to merge this into the other branch for official testing + review

2020-10-30 15:21 UTC, mcous commented on app/src/calibration/labware/__tests__/selectors.test.js
>              type: 'some_v1_labware',
We need to add `definitionHash: null` to this fake to match what is actually going to be in application state

2020-10-30 15:21 UTC, mcous commented on app/src/calibration/labware/__tests__/selectors.test.js
> +          calibrationData: { x: 1.2, y: 4.6, z: 7.9 },
See comment above about correcting the mock state data. This change should be reverted in favor of using a (more) accurate mock

2020-10-30 15:24 UTC, mcous commented on app/src/calibration/labware/__tests__/selectors.test.js
>          ...omit(lwCalibration, 'definitionHash'),
Note for posterity: this omit was in the wrong place (pre-flattening), which meant this test wasn't actually doing anything / working. Looks like maybe a copy paste error or an assertion pasted in from the failure log to get the test to pass.

To get on a soap box: this is the sort of problem that TDD is good at preventing in a lot of cases

2020-10-30 21:11 UTC, sanni-t commented on app/src/calibration/labware/__tests__/selectors.test.js
>              type: 'some_v1_labware',
I talked with @b-cooper offline to understand the test cases. The second mock here is for a V1 type labware which would not contain a definitionHash. The unintentional calibrationData received in the test in question would actually not be used because of the presence of a `calDataAvailable` property in `LabwareSummary`. I have updated the test comment to include this information.

2020-11-01 20:54 UTC, mcous commented on app/src/calibration/labware/__tests__/selectors.test.js
>              type: 'some_v1_labware',
A `v1` type labware will not have a definition hash, but the RPC labware object in state (which these tests mock our) _will_ have a `definitionHash` key explicitly set to to null by the RPC API client:

https://github.com/Opentrons/opentrons/blob/c48a60081b1e2c3eb6a54d4aba6d23dac131224b/app/src/robot/api-client/client.js#L615-L635

We definitely are feeding bad data into the code under test. If that wasn't the case here, our best move would be to wipe out the test with a todo rather than keeping an assertion that confirms unintended behavior. But, since we _are_ feeding bad data in, we need to fix the bad data

2020-11-02 22:08 UTC, mcous approved these changes
🥙

2020-11-02 22:40 UTC, merged