refactor(app): update cal check screens to match backend changes
OpenTrons/opentrons-api pull request #6895
Opened 2020-11-02 15:42 UTC by ahiuchingau

# Overview
Closes #6731. This updates the screens for the calibration check flow based on the [design](https://www.figma.com/file/nbDHskbW5zaXwtrLvEIKVj/calibration-overhaul?node-id=141%3A524) and the backend changes made in #6866.

# Changelog
- new result summary screen + tests
- update the move command for each screen based on the new cal check state machine
- update the cal check fixture to reflect the new changes

# Review requests
Make sure you can run through calibration check and see that the screens match the design

There are some TODOs following this PR:
- fix analytics selectors and move them to a different file (related to tickets #6626 & #6623)
- add ask-for-cal-block to cal check flow

2020-11-02 16:40 UTC, sfoster1 requested changes
Couple small change requests

2020-11-02 16:40 UTC, sfoster1 commented on app/src/sessions/calibration-check/constants.js
> +// export const CHECK_STEP_NO_PIPETTES_ATTACHED: 'noPipettesAttached' =
delete

2020-11-02 16:40 UTC, sfoster1 commented on app/src/sessions/selectors.js
> +// import { some } from 'lodash'
Honestly I think a lot of this stuff is going to change significantly since the kind of results data is changing so we should just delete this stuff instead of commenting it out

2020-11-02 20:17 UTC, Laura-Danielle requested changes
The ordering of the screens is incorrect. The screens appear to be following the old order (i.e. check all of first pip including deck cal, then check second pip only pip offset)

1. If there are two pipettes, the first pipette should only check tip length + pipette offset and the second pipette should check tip length + pipette offset + deck calibration
2. If there is only 1 pipette, it should check tip length + pipette offset + deck calibration

2020-11-02 21:41 UTC, sfoster1 reviewed
LGTM once other comments are addressed

2020-11-02 22:22 UTC, nusrat813 approved these changes
Tested - feature working as intended 

to look into in another PR - return tip height when exiting modal at a given point is too high

2020-11-04 13:32 UTC, sfoster1 approved these changes
There's a couple places that are still using `Button` elements and separate css files we should  add TODOs to switch to `Btn` primitives and style props but overall looks good

2020-11-04 13:32 UTC, sfoster1 commented on app/src/components/CheckCalibration/ResultsSummary.js
> +          className={styles.summary_exit_button}
let's TODO this and other uses of `PrimaryButton` and `className` specifiers to change to the `Btn` primitives and style props

2020-11-04 13:32 UTC, sfoster1 commented on app/src/components/CheckCalibration/ResultsSummary.js
> +          className={cx(styles.summary_icon, {
Let's `TODO` this or switch to specifyign `color`, etc as style props

2020-11-04 16:25 UTC, Laura-Danielle approved these changes
LGTM! Nice!

2020-11-04 18:37 UTC, merged