fix(api): Specify correct channels for a paired pipette during pick up tip
OpenTrons/opentrons-api pull request #6903
Opened 2020-11-03 14:39 UTC by Laura-Danielle

# Overview

There is no 'channels' attribute in a pipette pairing context, hence the use case in pick up tip would have failed. 

# Changelog

- Change `self.channels` to the primary_instrument channels

# Risk assessment

Low. Not a widely advertised feature and this is fixing a bug.

2020-11-03 14:43 UTC, amitlissack requested changes
The fix looks fine, but I think a unit test should be added for this case.

2020-11-04 13:36 UTC, sfoster1 commented
So what's the problem and the behavior affect here? That if you did 
```
def run(ctx):
    left = ctx.load_instrument('p300_multi_gen2', 'left')
    right = ctx.load_instrument('p300_single_gen2', 'right')
    tiprack = ctx.load_labware('opentrons_96_tiprack_300ul', '1')
    paired = left.pair_with(right)
    paired.pick_up_tip(tiprack)
```
specifically passing the tiprack rather than a target well, you'll pick up from A1 then B1 then C1 etc rather than A1 then A2?

I think we should add a test case for this, yes. I _think_ that this is not a behavior people would rely upon so we don't need a new api level.

2020-11-05 14:55 UTC, Laura-Danielle commented
> So what's the problem and the behavior affect here? That if you did
> 
> ```
> def run(ctx):
>     left = ctx.load_instrument('p300_multi_gen2', 'left')
>     right = ctx.load_instrument('p300_single_gen2', 'right')
>     tiprack = ctx.load_labware('opentrons_96_tiprack_300ul', '1')
>     paired = left.pair_with(right)
>     paired.pick_up_tip(tiprack)
> ```
> 
> specifically passing the tiprack rather than a target well, you'll pick up from A1 then B1 then C1 etc rather than A1 then A2?
> 
> I think we should add a test case for this, yes. I _think_ that this is not a behavior people would rely upon so we don't need a new api level.

This is a pretty rare use case in my opinion, but the actual behavior is this:

```
def run(ctx):
    left = ctx.load_instrument('p300_multi_gen2', 'left')
    right = ctx.load_instrument('p300_single_gen2', 'right')
    tiprack = ctx.load_labware('opentrons_96_tiprack_300ul', '1')
    paired = left.pair_with(right)
    pick_up_location = Location(Point(10, 10, 10), tiprack)
    paired.pick_up_tip(pick_up_location)
```

2020-11-16 16:03 UTC, amitlissack requested changes
Code looks fine. Just asking for a small test organization change.

2020-11-16 16:03 UTC, amitlissack commented on api/tests/opentrons/protocol_api/test_paired_context.py
> +
Can we have two different tests whose names make it clear what the test is for?

2020-11-16 16:15 UTC, Laura-Danielle commented on api/tests/opentrons/protocol_api/test_paired_context.py
> +
sure

2020-11-16 16:41 UTC, amitlissack approved these changes
Thank you!

2020-11-16 17:04 UTC, merged