feat(navbar): navbar redesign
OpenTrons/opentrons-api pull request #6904
Opened 2020-11-03 18:39 UTC by MichalCzerwonka

Navbar redesign

# Overview

# Changelog

# Review requests

# Risk assessment

2020-11-17 18:37 UTC, mcous requested changes
Code comments:

- This is a really massive PR. It would have been better as a series of smaller PRs
- This adds a lot of CSS to the monorepo
    - The monorepo does not use the `.module.css` convention used in the website
    - We've been moving away from CSS modules to styled-components in the monorepo
    - Variables attached to `:root` appear to shadow other variable that the component library attaches to `:root`, which has led to bugs in the past
        - Any `:root` variables (if CSS cannot be avoided) should be named/scoped so as to not conflict with already established variable names from the components library
- I don't see any unit tests added, which I would want for the components that include state

Behavior notes from reviewing <http://sandbox.labware.opentrons.com/navbar-redesign/>. This is just what I noticed, and shouldn't be considered an exhaustive list

- The nav should match the content width, but it does not
- The dropdown carets don't appear to be present
- The mobile nav CTA buttons look like their spacing is wrong
    - Also, I'm getting weird scroll bar behaviors for elements _underneath_ the mobile nav

2020-11-17 18:37 UTC, mcous commented on labware-library/src/components/MainNav/Logo.js
> +        src="https://s3.amazonaws.com/opentrons-images/website/ot_logo_full.png"
Images should be added to the repo so they can be CDN'd. Using an S3 bucket for images like this has led to unnecessary failures due to AWS failures

2020-11-17 18:37 UTC, mcous commented on labware-library/src/components/MainNav/Logo.js
> +    <a href="https://opentrons.com/">
I believe our canonical link should include the `www`

2020-11-17 18:37 UTC, mcous commented on labware-library/src/components/MainNav/MenuButton.js
> +          src={`data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iMzFweCIgaGVpZ2h0PSIyM3B4IiB2aWV3Qm94PSIwIDAgMzEgMjMiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6L
This SVG source should be included via an `import` so it can go through the webpack file loader for inlining automatically

2020-11-17 18:37 UTC, mcous commented on labware-library/src/components/MainNav/MainNav.module.css
> +  --bd-radius-default: 3px;
Because it's attached to `:root`, I'm pretty sure this runs the risk of clobbering our `--bd-radius-default: 2px;` defined in the component library, which has happened in the past

2020-11-17 18:37 UTC, mcous commented on labware-library/src/components/MainNav/Logo.js
> +import styles from './MainNav.module.css'
New code in the monorepo should prefer using `styled-components` and our UI primitives defined in our [primitives library](https://s3-us-west-2.amazonaws.com/opentrons-components/edge/index.html#section-primitives) over CSS modules

2020-11-17 18:37 UTC, mcous commented on labware-library/src/components/MainNav/NavLink.js
> +        className={cx('link_title', className)}
What is the bare `link_title` class for?

2020-11-17 18:37 UTC, mcous commented on labware-library/src/components/MainNav/NavLink.js
> +      <a
This could (should?) be a [`<Link>` primitive](https://s3-us-west-2.amazonaws.com/opentrons-components/edge/index.html#link) with its `external` prop set

2020-11-17 18:37 UTC, mcous commented on labware-library/src/components/Nav/index.js
> +      .fetch('https://opentrons.com/api/navigationData.json')
This request fails dues to cors from <http://sandbox.opentrons.com/navbar-redesign>. I feel like this should be injected at build time, not executed at run time.

Also, what is this file and how does it compare to `labware-library/src/components/Nav/nav.json` below?

2020-11-17 18:37 UTC, mcous commented on labware-library/src/components/Nav/nav.json
> +  "homeUrl": "https://opentrons.com",
@mmonsees should this be `www`?

2020-11-17 18:37 UTC, mcous commented on labware-library/src/styles/colors.css
> +:root {
Are these not already present in the components library?

2020-11-17 18:37 UTC, mcous commented on labware-library/src/styles/typography.css
> +:root {
These should be in the components library (some of them already are)

2020-11-17 18:37 UTC, mcous commented on labware-library/src/components/Nav/__tests__/__snapshots__/Nav.test.js.snap
> +        <SubdomainNav
This snapshot test should probably be removed in its entirety. Organizationally, we don't really believe in snapshot tests anymore and this is just unnecessary churn

2020-11-17 18:55 UTC, mmonsees commented on labware-library/src/components/Nav/nav.json
> +  "homeUrl": "https://opentrons.com",
that's correct, we decided to go with www. I didn't know to spec that out, so thank you for adding it here.

2020-11-19 18:49 UTC, MichalCzerwonka commented on labware-library/src/components/MainNav/Logo.js
> +    <a href="https://opentrons.com/">
You used this URL on old version of Nav and `www` redirect me to non `www` page, are you sure that url should contain `www`?

2020-11-19 18:50 UTC, MichalCzerwonka commented on labware-library/src/components/Nav/nav.json
> +  "homeUrl": "https://opentrons.com",
You used this URL on old version of Nav and www redirect me to non www page, are you sure that url should contain www?

2020-11-19 18:51 UTC, MichalCzerwonka commented on labware-library/src/styles/typography.css
> +:root {
What is component library? This nav was created for main page and nobody told me about any components library. :(

2020-11-19 18:51 UTC, MichalCzerwonka commented on labware-library/src/styles/colors.css
> +:root {
What is component library? This nav was created for main page and nobody told me about any components library. :(

2020-11-19 19:06 UTC, MichalCzerwonka commented on labware-library/src/components/Nav/index.js
> +      .fetch('https://opentrons.com/api/navigationData.json')
This is the same file local version is used as fallback. This is our approach proposed in the estimation another pages doesn't have any builds.

2020-11-19 19:06 UTC, MichalCzerwonka commented on labware-library/src/components/Nav/__tests__/__snapshots__/Nav.test.js.snap
> +        <SubdomainNav
Sorry, I don''t know about that.

2020-11-19 19:11 UTC, MichalCzerwonka commented on labware-library/src/components/MainNav/Logo.js
> +        src="https://s3.amazonaws.com/opentrons-images/website/ot_logo_full.png"
Done.

2020-11-19 19:11 UTC, MichalCzerwonka commented on labware-library/src/components/MainNav/MenuButton.js
> +          src={`data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iMzFweCIgaGVpZ2h0PSIyM3B4IiB2aWV3Qm94PSIwIDAgMzEgMjMiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6L
Done

2020-11-19 19:11 UTC, MichalCzerwonka commented on labware-library/src/components/MainNav/MainNav.module.css
> +  --bd-radius-default: 3px;
Ok, I removed all root variables.

2020-11-19 19:11 UTC, MichalCzerwonka commented on labware-library/src/components/MainNav/Logo.js
> +import styles from './MainNav.module.css'
Sorry, This is the first time I hear about it

2020-11-19 19:13 UTC, MichalCzerwonka commented
> Code comments:
> 
> * This is a really massive PR. It would have been better as a series of smaller PRs
> * This adds a lot of CSS to the monorepo
>   
>   * The monorepo does not use the `.module.css` convention used in the website
>   * We've been moving away from CSS modules to styled-components in the monorepo
>   * Variables attached to `:root` appear to shadow other variable that the component library attaches to `:root`, which has led to bugs in the past
>     
>     * Any `:root` variables (if CSS cannot be avoided) should be named/scoped so as to not conflict with already established variable names from the components library
> * I don't see any unit tests added, which I would want for the components that include state
> 
> Behavior notes from reviewing http://sandbox.labware.opentrons.com/navbar-redesign/. This is just what I noticed, and shouldn't be considered an exhaustive list
> 
> * The nav should match the content width, but it does not
> * The dropdown carets don't appear to be present
> * The mobile nav CTA buttons look like their spacing is wrong
>   
>   * Also, I'm getting weird scroll bar behaviors for elements _underneath_ the mobile nav

I addresed comments, but I don't know why sandbox version is different than the local version. I guess thats why you see this visual issues.

2020-11-24 18:49 UTC, mcous commented
Still looks like there are navbar width + spacing issues at a variety of screen sizes:

<img width="1539" alt="Screen Shot 2020-11-24 at 1 44 08 PM" src="https://user-images.githubusercontent.com/2963448/100138268-c9f35080-2e5b-11eb-88ec-477f6295b66b.png">

<img width="1345" alt="Screen Shot 2020-11-24 at 1 43 57 PM" src="https://user-images.githubusercontent.com/2963448/100138058-74b73f00-2e5b-11eb-9da7-72a88f2c251b.png">

<img width="1144" alt="Screen Shot 2020-11-24 at 1 39 39 PM" src="https://user-images.githubusercontent.com/2963448/100138065-75e86c00-2e5b-11eb-8b86-f854a5b1ce38.png">

<img width="475" alt="Screen Shot 2020-11-24 at 1 41 03 PM" src="https://user-images.githubusercontent.com/2963448/100138062-754fd580-2e5b-11eb-8038-8534d6cb8afe.png">

2020-12-02 02:26 UTC, mmonsees commented on labware-library/src/components/MainNav/Logo.js
> +    <a href="https://opentrons.com/">
@MichalCzerwonka we do want to use “www.opentrons.com” as our canonical host name (not opentrons.com). We want this to be the version of the host name to be indexed consistently by search engines.

@mcous do you know about the redirect he's referencing? I'm not sure what that is.

2022-03-16 13:00 UTC, amitlissack commented
Closed due to inactivity

2022-03-16 13:00 UTC, closed without merging