feat(robot-server): increment HTTP API version
OpenTrons/opentrons-api pull request #6917
Opened 2020-11-04 20:26 UTC by mcous

## Overview

This PR increments the robot-server's HTTP API version to account for the breaking response format changes included in v4.0.0 of the robot stack.

BREAKING CHANGE: Requests without Opentrons-Version or with a value lower than 2 will be rejected

Closes #6851

## Changelog

- Increment HTTP API version
- Require clients to specify an `Opentrons-Version` header that is at least `2`
- Add `*` as accepted value for `Opentrons-Version` that means "use latest available version"

## Review requests

We should carefully consider the implications of this change:

- Once a robot has been upgraded to v4, all requests, including health checks, to the robot-server from prior versions of the app will reject
    - In the app, this will manifest as a robot that "is not responding correctly to requests."
- The **update-server** is unaffected by these changes, and older versions of the app _should_ remain able to downgrade a 4.0 robot

Again, this is a **BREAKING CHANGE**.

# Risk assessment

In terms of pure functionality: low. Unit and integration tests have been updated to test for our desired behavior.

In terms of user experience: high. Old apps connecting to new robots is going to be a hopefully rare occurrence, but will be relatively confusing due to lack of messaging around this on the (old) app-side. That being said, I think this is probably less confusing than whatever random errors might bubble up to the user due to breaking changes in the response formats. themselves

2020-11-04 21:34 UTC, sfoster1 commented on robot-server/tests/service/test_app.py
> +    resp = api_client.get('/openapi.json', headers={API_VERSION_HEADER: "1"})
If this is the self-documentation, shoudln't this and other docs urls get a carveout?

2020-11-05 17:40 UTC, sfoster1 requested changes
TEsted on robot and LGTM; however, we should also opt out the health endpoint, and add min (at least) and max (maybe) supported HTTP versions, relying on (yet-to-be-added) handshake negotiations to get to whatever the server actually wants.

2020-11-05 18:56 UTC, sfoster1 approved these changes
LGTM!

2020-11-05 19:10 UTC, amitlissack commented on robot-server/robot_server/constants.py
> +NON_VERSIONED_ROUTES = [
I suggest you make this a Set instead of a list.

2020-11-05 20:01 UTC, amitlissack approved these changes
Looks good!

2020-11-05 20:21 UTC, mcous commented on robot-server/robot_server/constants.py
> +# value is different and separaate from the application version.
```suggestion
# value is different and separate from the application version.
```

2020-11-05 20:47 UTC, merged