feat(api): Mark calibrations as bad when determined they exceed threshold
OpenTrons/opentrons-api pull request #6918
Opened 2020-11-04 20:32 UTC by Laura-Danielle

# Overview

Closes #6730. Now, when a user completes calibration check, the app will be able to detect calibrations that were marked bad.

# Changelog

- Add a method in calibration storage to mark a file with a bad status
- Add a method in the user flow to mark a calibration as bad if it exceeds threshold.
- Refactor the valid calibration check
- Add a test on the user flow to check the new behavior
- Fix up an enum check

# Review requests

Any other tests you would like? Test on a robot, force your calibrations to be above the threshold and you should see
that the app picks up bad calibrations afterwards.

It will only get resolved once you re-do whichever calibration was marked bad.

# Risk assessment

Low.

2020-11-04 22:17 UTC, sfoster1 requested changes
I think we can make this a little bit better by not going too overboard with using the same function for marking everything bad, since the caller calls different things regardless. Either something like a data transformation only function; or a separate set of functions for each kind of calibration data or something I think would make the `mark_bad` function itself (or whatever replaces it) a bit nicer to read.

2020-11-04 22:17 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/modify.py
> +            typing.Tuple[float, str, 'Labware']],
It's a bit odd that this is a tuple and the other stuff isn't - can we get a nice type for tip length calibration in line with the other kinds?

2020-11-04 22:17 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/modify.py
> +            typing.Tuple[float, str, 'Labware']],
Also, rather than having a union, I think we should probably type this as a series of overload defs, but that's a personal preference

2020-11-04 22:17 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/modify.py
> +        cal_status: typing.Optional[local_types.CalibrationStatus] = None):
don't need both `Optional` and `= None`, mypy will figure it out

2020-11-04 22:17 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/modify.py
> +        cal_status: typing.Optional[local_types.CalibrationStatus] = None):
Don't need both `Optional` and `=None`, mypy will figure it out

2020-11-04 22:17 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/modify.py
> +        cal_status: typing.Optional[local_types.CalibrationStatus] = None
don't need both `Optional` and `=None`, mypy will figure it out

2020-11-04 22:17 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/modify.py
> +            typing.Tuple[float, str, 'Labware']],
In fact, since whatever calls this is going to know what kind of calibration it has, it may make a lot more sense to have `mark_bad` be a function that transforms a calibration type rather than a function that transforms _and saves_ it. Since the calibration types are all dataclasses, that means that we can stararg expand them. Something like:

```
@typing.override
def mark_bad(calibration: local_types.DeckCalibration) -> local_types.DeckCalibration: ...

@typing.override
def mark_bad(calibration: local_types.PipetteOffsetCalibration) -> local_types.PipetteOffsetCalibration: ...

@typing.override
def mark_bad(calibration: local_types.TipLengthCalibration) -> local_types.TipLengthCalibration: ...

def mark_bad(calibration):
    caldict = calibration.as_dict()
    caldict['status'] = local_types.CalibrationStatus(markedBad=True, ...)
   return type(calibration)(**caldict)
```

 and then the callers do
```
bad_cal  = mark_bad(calibration)
save_deck_calibration(bad_cal)
```

2020-11-04 22:17 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/check/user_flow.py
> +            modify.mark_bad(
Yeah see here we're already calling things differently depending on what we know the types to be so I don't think we need a fully generic function, or at least a fully generic mark-and-save function.

2020-11-09 18:06 UTC, sfoster1 approved these changes
Let's remove that commented assert but the code looks good to me

2020-11-09 18:06 UTC, sfoster1 commented on api/src/opentrons/calibration_storage/modify.py
>      # assert labware._is_tiprack, \
remove

2020-11-09 18:59 UTC, Laura-Danielle commented on api/src/opentrons/calibration_storage/modify.py
>      # assert labware._is_tiprack, \
This commented out assert is part of the comment block above. I want to keep it in as a reminder for what we had previously utilized in that method.

2020-11-09 21:43 UTC, nusrat813 approved these changes

2020-11-09 21:44 UTC, merged