feat(app, robot-server): Report both the minimum and maximum supported protocol api versions
OpenTrons/opentrons-api pull request #6921
Opened 2020-11-05 14:31 UTC by Laura-Danielle

# Overview

closes #6894. This PR surfaces both the minimum and maximum supported API version in the app in preparation for 4.0.0 since API V1 will be deprecated.

# Changelog

- Add in two new keys to the health request that represent the minimum/maximum protocol api version
- Modify the protocol api selector, add in a check for the old health request vs new health request and generate the label accordingly

# Review requests

Test two use-cases:
1. A robot with this branch pushed to it
2. A separate robot that has the older method 

# Risk assessment

Low, it's a small change in the app. However, since the keys are changing in the health response, we should thoroughly test on different server versions to make sure the app can still support both.

2020-11-05 14:39 UTC, sfoster1 requested changes
Couple little changes but I'm excited to move forward with it.

2020-11-05 14:39 UTC, sfoster1 commented on app/src/components/RobotSettings/InformationCard.js
> +const DEFAULT_MINIMUM_API_VERSION = '2.0'
Since this is the value when the data isn't presented; and since the data started being presented in the case where this value was 2.0; I think the default should actually be '1.0', to support the older robots that won't be reporting the version.

2020-11-05 14:39 UTC, sfoster1 commented on app/src/components/RobotSettings/InformationCard.js
> +const DEFAULT_MINIMUM_API_VERSION = '2.0'
I also think this should be in the middleware layer, and the redux state should always have a value here.

2020-11-05 14:39 UTC, sfoster1 commented on app/src/components/RobotSettings/InformationCard.js
> +          {oldHealthCheck ? (
I don't think we need the different layouts if the version is always correct (which it will be if we change the default to 1.0)

2020-11-05 14:39 UTC, sfoster1 commented on robot-server/tests/integration/test_health_check.tavern.yaml
> +        minimum_protocol_api_version:
These values probably want to be fixtured or pulled from some other source of truth so we don't have to keep changing them

2020-11-05 16:33 UTC, mcous requested changes

2020-11-05 16:33 UTC, mcous commented on app/src/components/RobotSettings/InformationCard.js
> +const DEFAULT_MINIMUM_API_VERSION = '2.0'
I would suggest this logic lives in a selector rather than state. It would be good for the state to differentiate between value present and value missing for debugging purposes

2020-11-05 16:33 UTC, mcous commented on app/src/components/RobotSettings/InformationCard.js
> +              value={protocolApiVersions[0] || DEFAULT_MAX_API_VERSION}
Prefer `??` to `||`

2020-11-05 16:33 UTC, mcous commented on app/src/components/RobotSettings/InformationCard.js
> +                DEFAULT_MINIMUM_API_VERSION} Maximum: ${protocolApiVersions[1] ||
Is there a missing comma or other separator here?

2020-11-05 16:33 UTC, mcous commented on app/src/discovery/selectors.js
> +    healthField?.protocol_api_version ||
Prefer `??`

2020-11-05 16:33 UTC, mcous commented on discovery-client/src/types.js
> +export type NewHealthResponse = {
Do not add a new type here. Add `minimum_protocol_api_version` and `maximum_protocol_api_version` as optional fields to the existing definition of the health response

2020-11-05 16:33 UTC, mcous commented on app/src/components/RobotSettings/InformationCard.js
> +    version => version
This logic should be in the selector. The `protocolApiVersions.length === 1` in the component below seems hard to maintain + understand by future developers compared to an interfaces that has an explicit `min` and `max` (see comment in selector)

2020-11-05 16:33 UTC, mcous commented on app/src/discovery/selectors.js
> +): Array<string | null> => {
I think this selector will be much easier to deal with if it returns a `{| min: string | null, max: string |}` object

2020-11-05 16:41 UTC, Laura-Danielle commented on app/src/discovery/selectors.js
> +): Array<string | null> => {
good idea!

2020-11-06 16:25 UTC, sfoster1 requested changes
Looks good, but some deleted code to get rid of.

Also the visuals here are a little weird, since the text is all formatted the same it kind of blends together. @emilywools what do you think?
![Screenshot from 2020-11-06 11-12-12](https://user-images.githubusercontent.com/3091648/98389932-b73ae800-2022-11eb-847f-f7ae482b1923.png)

2020-11-06 16:25 UTC, sfoster1 commented on robot-server/tests/integration/test_health_check.tavern.yaml
> +      # json:
Probably want to delete this or uncomment it

2020-11-06 17:29 UTC, emilywools commented on robot-server/tests/integration/test_health_check.tavern.yaml
> +      # json:
how about abbreviate the min and max and add an extra space between them, a la

![Screen Shot 2020-11-06 at 12 27 34 PM](https://user-images.githubusercontent.com/4339860/98396423-b195d000-202b-11eb-8e21-6bc9c4654367.png)

2020-11-06 17:30 UTC, emilywools commented on robot-server/tests/integration/test_health_check.tavern.yaml
> +      # json:
(you should match the other font weights / styles, i just did a quick n dirty mockup based on a screenshot

2020-11-06 18:54 UTC, mcous reviewed
I think this is an improvement with `getRobotProtocolApiVersion` but still isn't quite correct yet

2020-11-06 18:54 UTC, mcous commented on app/src/discovery/__tests__/selectors.test.js
> +      expected: { min: '1.0', max: '2.0' },
This feels wrong. If we're missing this information, it means:

- We're dealing with a very old, pre-PAPI2 robot, or:
- The health request is not coming back successfully (e.g. update server is healthy, robot server is not)

In both of those cases, reporting a maximum API version of 2.0 is incorrect. I think it would be more appropriate for this whole selector to return `null` in that case so the UI in question can say "Unknown" or something similar.

We're also missing a test case for an old health response that does not include any protocol API version

2020-11-06 18:54 UTC, mcous commented on app/src/components/RobotSettings/InformationCard.js
> +            value={`Minimum: ${protocolApiVersions.min} Maximum: ${protocolApiVersions.max}`}
- This still looks like it needs a comma or other visual separator between min and max
- I feel like this should say "unknown" if we don't know, not `Min: 1.0, Max: 2.0` which, as far as I can tell, isn't actually correct for the situation in which it would occur (see other comment)

2020-11-06 18:57 UTC, Laura-Danielle commented on robot-server/tests/integration/test_health_check.tavern.yaml
> +      # json:
@emilywools, @mcous is suggesting a [visual separator](https://github.com/Opentrons/opentrons/pull/6921#discussion_r518941454) like a comma. Thoughts?

2020-11-06 19:19 UTC, emilywools commented on robot-server/tests/integration/test_health_check.tavern.yaml
> +      # json:
i think its fine without it, but we can add a comma

2020-11-06 19:20 UTC, emilywools commented on robot-server/tests/integration/test_health_check.tavern.yaml
> +      # json:
do you think someone would confuse it for coordinates if we add the comma?

2020-11-06 20:06 UTC, sfoster1 commented on app/src/components/RobotSettings/InformationCard.js
> +            value={`Minimum: ${protocolApiVersions.min} Maximum: ${protocolApiVersions.max}`}
`Min 1.0` is appropriate for "good health response without minimum protocol api" because it is correct for 3.x robots.
`Max 1.0` is appropriate for "good health response without maximum protocol api" because the max-supported field was added in 3.15.0 with the release of API version 2, and therefore robots without this field do not support api version 2.
I agree that "unknown" is the right response for bad-health-response, though.

2020-11-09 19:48 UTC, mcous approved these changes

2020-11-09 19:48 UTC, mcous commented on api/src/opentrons/protocol_api/__init__.py
> +from opentrons.protocols.api_support.definitions import MAX_SUPPORTED_VERSION, MINIMUM_SUPPORTED_VERSION  # noqa(F401)
Nit: should these const names be consistent? `MAX_` vs `MINIMUM`?

2020-11-09 19:58 UTC, sfoster1 approved these changes
Nice!

2020-11-09 21:21 UTC, merged