feat(api): add move-to-well to protocol engine
OpenTrons/opentrons-api pull request #6943
Opened 2020-11-06 21:15 UTC by mcous

## Overview

This PR adds a `MoveToWell` command to the protocol engine to support moving a given pipette to the **top** of a specified well.

Takes over for #6889, closes #6763, closes #6646 

## Changelog

### command model changes

- Move to well command added
- Load labware command;s `location` param changed to a  new union type `LabawareLocation`
    - For now this union only includes a `DeckSlotLocation`
    - Will be expanded in the future for modules

### state store changes

- Selector added to `labware.py` substore
    - Does a labware have a given quirk?
- Selectors added to `geometry.py` substore
    - Get the absolute position of a well
    - Get the highest Z of a labware
    - Get the highest Z of all labware
- `motion.py` substore added with:
    - Current location state (which labware and well are we at and which pipette did we use to get there?)
    - Get the current location state
    - Get the a pipette's location data (mount and critical point) based on the current location data
    - Get a set of waypoints given the current location and a desired labware / well location

### executor changes

- New pipetting handler class with a handler for MoveToWellRequest
    - Gets pipette mount and origin critical point information from state
    - Gets current gantry position and instrument max height from hardware controller
    - Calls motion planning selector
    - Passes waypoints to hardware controller's `move_to` method

## Review requests

First off, how does this look? Are the tests (and there are a lot of them) grokable?

I'm currently working on a way to actually smoke test this on a real life robot while we're still waiting on 4.0.0 to get back into `edge` for the http flattening, but between SSH and loading Python protocol files, I think we'll be able to figure something out.

# Risk assessment

Low and high, simultaneously

- Low, because this isn't hooked to anything
- High, because pipette movement is such a fundamental part of running protocols, so this needs to be right (eventually) for the protocol engine to ever be the thing we use to run protocols

2020-11-06 21:29 UTC, mcous commented on api/src/opentrons/protocol_engine/state/motion.py
> +        location = self.get_current_location_data()
Missing docstring and general comments about what this selector is doing

2020-11-06 21:29 UTC, mcous commented on api/src/opentrons/protocol_engine/state/motion.py
> +        pipette_data = self._pipette_store.state.get_pipette_data_by_id(
Missing docstring

2020-11-06 21:29 UTC, mcous commented on api/src/opentrons/protocol_engine/state/motion.py
> +            mount=pipette_data.mount,
This mount return feels a little unnecessary. Maybe this selector should just return the critical point

2020-11-06 21:29 UTC, mcous commented on api/src/opentrons/protocol_engine/state/motion.py
> +    def __init__(
More missing docstrings. Should see about incrementally adding docstring linting to `api`

2020-11-06 21:41 UTC, amitlissack reviewed
Two small comments for now. I'll look more on monday. 

Mr JS has become Mr Py overnight. Rock'em sock'em!!

2020-11-06 21:41 UTC, amitlissack commented on api/src/opentrons/protocol_engine/state/geometry.py
> +            _labware_store=labware_store,
Your extensive use of dataclasses is interesting. To me, dataclasses are to classes what like structs are to classes in C++.  The use of leading `_` for constructor args is weird looking to me. 

Not saying it's bad. I might just have to get used to it.

2020-11-06 21:41 UTC, amitlissack commented on api/src/opentrons/protocol_engine/state/motion.py
> +    _current_location: Optional[LocationData] = None
To continue the theme of Mike's interesting use of dataclasses.  I think what I find weird is that leading `_` indicates a protected member, by convention. 

Not asking for a change. Just something to think about.

2020-11-06 22:10 UTC, sfoster1 requested changes
The functionality looks good but I'm continuing to worry about the way we store data in these state classes. I think a big point of the protocol context and labware refactor was to make internal classes that would be useful in an HTTP api context as well, and I'd really like to see those classes be the things in the state stores.

I also think we should take advantage of the, well, uniqueness of the uuid paradigm. No reason to look up well and labware if the well uid is unique across all loaded wells, which it already is.

2020-11-06 22:10 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +        labware_data = self._labware_store.state.get_labware_data_by_id(
This is kind of a reimplementation of the logic in the labware implementations, and thus risks diverging in a pretty important place. Is there a way we could reuse some of that?

In general it would be nice to square the circle between the labware implementation stuff and implementations like this PR. If the point of the labware implementations is to make them more usable in areas other than a protocol context, shouldn't we use them here?

2020-11-06 22:10 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +        labware_data = self._labware_store.state.get_labware_data_by_id(
Also, if we're using UUIDs everywhere, why do we need the labware id? Why do we need to go through defs? Wouldn't it be better for these state stores to be maps of UUIDs (for serialization on the HTTP api) to references to labware implementations, so we could just do `labware_store.get_well(well_id).top()`?

2020-11-06 22:10 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/motion.py
> +    _current_location: Optional[LocationData] = None
I think I am asking for a change. We use that convention extensively elsewhere in the python side, and I think we should stick to it.

2020-11-06 22:10 UTC, sfoster1 commented on api/src/opentrons/types.py
> +class DeckSlot(int, enum.Enum):
seems like it should be in `opentrons_shared_data` somewhere

2020-11-06 23:15 UTC, mcous commented on api/src/opentrons/protocol_engine/state/geometry.py
> +        labware_data = self._labware_store.state.get_labware_data_by_id(
I think the reason I went this way is mostly a question of ergonomics. As written, a load labware result returns you three things:

- A generated labware ID
- Calibration data
- The labware definition

So, using that information, you can use the labware ID and the well name from the definition to access the well. If we wanted to _also_ generate uuids for each well in every labware, we could definitely do that, but it would involve returning that mapping in the load labware response.

With well UUIDs, though, I also start feeling like that might make the state a little too uninspectable. There's going to be, at most, 11 labware in any given protocol, so the UUID to physical thing map there isn't that onerous. Even a simple protocol probably has hundreds of wells, though, so that starts to feels a little a pain.

Regardless, if we chose _not_ to generate UUIDs for wells, then `well_id` is definitely the wrong parameter name here, given that it's _not_ a unique identifier like everything else named `*_id`

2020-11-06 23:16 UTC, mcous commented on api/src/opentrons/protocol_engine/state/motion.py
> +    _current_location: Optional[LocationData] = None
100% me being lazy and trying to get away with not writing an `__init__` method

2020-11-06 23:34 UTC, mcous commented
Damn, thanks for the quick reviews!

From @sfoster1:

> The functionality looks good but I'm continuing to worry about the way we store data in these state classes. I think a big point of the protocol context and labware refactor was to make internal classes that would be useful in an HTTP api context as well, and I'd really like to see those classes be the things in the state stores.

This is a really good point, and @amitlissack and I were talking a little about (or maybe around) this earlier today. I think the TL;DR is that I'd like a little bit of greenfield re-implementation in the engine's various first passes. I've got the following things on my mind:

- Build this thing with near-complete test coverage
    - A lot of our code isn't adequately tested, or is old enough that we can't really trust the tests
    - Some greenfield re-implementations give us the opportunity to write tests we're confident in
    - Starting from that point is a better place to then start re-working and bringing in existing implementations
- Existing code, even stuff that's had a refactoring pass, can be pretty coupled
    - It's hard to decouple completely speculatively
    - An actual tested implementation to compare to helps get the refactor right
- The engine doesn't need a lot of the stuff that exists in the protocol API and its implementations
    - I think it makes sense to keep the engine state as dirt-simple as it can possibly be
    - Where I think the various implementation classes are really going to start to shine is when we build a Python protocol runner on top of this
        - We can have selectors that return the implementation class (or implementation classes that wrap the state)
        - With proper use of caching, we can swap out the state backing of the ProtocolContext while keeping the API intact

I think early on there's going to be a cadence of:

1. Push to a feature (e.g. basic pipetting)
2. Take stock
3. Refactor engine and tests to line up / use with existing behavior and implementations where needed
4. Repeat

2020-11-06 23:36 UTC, mcous commented
Oh yeah, also, really hacky test protocol! `make push` this branch to your robot and upload this through the app:

```py
import asyncio
from uuid import uuid4
from typing import Optional

from opentrons.types import DeckSlot, MountType
from opentrons.protocol_api import ProtocolContext
from opentrons.protocol_engine import ProtocolEngine, command_models as cmd
from opentrons.protocol_engine.types import DeckSlotLocation

# metadata
metadata = {
    'protocolName': 'ProtocolEngine smoke test',
    'author': 'Mike Cousins <mike@opentrons.com>',
    'description': 'Protocol to smoke-test the ProtocolEngine by HACKING',
    'apiLevel': '2.7'
}


def run(ctx: ProtocolContext) -> None:
    asyncio.run(run_protocol(ctx))


async def run_protocol(ctx: ProtocolContext) -> None:
    # HACK(mc, 2020-11-06): don't ever do this in a real protocol
    hw_api = ctx._hw_manager.hardware._obj_to_adapt
    engine = ProtocolEngine.create(hardware=hw_api)

    async def execute_command(
        request: cmd.CommandRequestType
    ) -> Optional[cmd.CommandResultType]:
        command_id = str(uuid4())
        command = await engine.execute_command(request, command_id=command_id)
        ctx.comment(f"{type(command.request).__name__} - {command_id}")
        ctx.comment(f"{command.request}")

        if isinstance(command, cmd.FailedCommand):
            ctx.comment(f"{command.error}")
            return None

        return command.result

    result = await execute_command(
        cmd.LoadLabwareRequest(
            location=DeckSlotLocation(DeckSlot.SLOT_5),
            loadName="opentrons_96_tiprack_300ul",
            namespace="opentrons",
            version=1
        ),
    )

    rack_5 = result.labwareId  # type: ignore[union-attr]

    result = await execute_command(
        cmd.LoadLabwareRequest(
            location=DeckSlotLocation(DeckSlot.SLOT_8),
            loadName="opentrons_96_tiprack_300ul",
            namespace="opentrons",
            version=1
        ),
    )

    rack_8 = result.labwareId  # type: ignore[union-attr]

    result = await execute_command(
        cmd.LoadPipetteRequest(
            pipetteName="p300_single_gen2",
            mount=MountType.RIGHT,
        ),
    )

    p300 = result.pipetteId  # type: ignore[union-attr]

    await execute_command(
        cmd.MoveToWellRequest(pipetteId=p300, labwareId=rack_5, wellId="A1")
    )

    await execute_command(
        cmd.MoveToWellRequest(pipetteId=p300, labwareId=rack_5, wellId="H12")
    )

    await execute_command(
        cmd.MoveToWellRequest(pipetteId=p300, labwareId=rack_8, wellId="H12")
    )

    await execute_command(
        cmd.MoveToWellRequest(pipetteId=p300, labwareId=rack_8, wellId="A1")
    )
```

2020-11-07 03:18 UTC, mcous commented on api/src/opentrons/protocol_engine/state/motion.py
> +            mount=pipette_data.mount,
Never mind, this selector gets both because they're the two inputs into `hw.gantry_position`

2020-11-09 14:15 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +        labware_data = self._labware_store.state.get_labware_data_by_id(
Ah yeah I definitely missed that those weren't actually UUIDs

2020-11-09 14:28 UTC, sfoster1 requested changes
The dataclass removal left some holes unfortunately, gotta remove the now-class-member-definitions once these aren't dataclasses

2020-11-09 14:28 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/commands.py
> +    _commands_by_id: Dict[str, cmd.CommandType]
If this isn't a dataclass, you don't want to have this both here and set in `__init__` it creates some really confusing semantics about where and when this is addressed:

```
>>> class test:
...   a = {}
...   def __init__(self, k, v):
...     self.a = {k, v}
... 
>>> t = test('hi', True)
>>> t.a
{True, 'hi'}
>>> t2 = test('lo', False)
>>> t2.a
{False, 'lo'}
>>> t.a
{True, 'hi'}
>>> t.a['what'] = 'yo'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'set' object does not support item assignment
>>> 
```
The way it's currently implemented creates a class attribute `_commands_by_id` that is shadowed by an instance attribute `_commands_by_id` at instantiation time, which means that accesses _inside_ the class through `self` get the shadowed instance attributes but access from _outside_ the class don't.

2020-11-09 14:28 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/commands.py
> +    _state: CommandState
don't want this here if it's not a dataclass

2020-11-09 14:28 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +    _labware_store: LabwareStore
don't want these here if it's not a dataclass

2020-11-09 14:28 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/geometry.py
> +    _state: GeometryState
don't want these here if this isn't a dataclass

2020-11-09 14:28 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/labware.py
> +    _labware_by_id: Dict[str, LabwareData]
don't want this here if it's not a dataclass

2020-11-09 14:28 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/labware.py
> +    _state: LabwareState
don't want this here if it's not a dataclass

2020-11-09 14:28 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/motion.py
> +    _labware_store: LabwareStore
don't want these if this isn't a dataclass

2020-11-09 14:28 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/motion.py
> +    _state: MotionState
don't want this here if it isn't a dataclass

2020-11-09 14:28 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/pipettes.py
> +    _pipettes_by_id: Dict[str, PipetteData]
remove

2020-11-09 14:28 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/pipettes.py
> +    _state: PipetteState
remove

2020-11-09 14:34 UTC, sfoster1 commented
from @mcous :

> This is a really good point, and @amitlissack and I were talking a little about (or maybe around) this earlier today. I think the TL;DR is that I'd like a little bit of greenfield re-implementation in the engine's various first passes. I've got the following things on my mind:
*snip*
> I think early on there's going to be a cadence of:
> 
>     1. Push to a feature (e.g. basic pipetting)
> 
>     2. Take stock
> 
>     3. Refactor engine and tests to line up / use with existing behavior and implementations where needed
>
>     4. Repeat

The desire to greenfield stuff for better testing makes sense but building a full parallel implementation doesn't make sense to me, and I think it could put us in a place where we get to actually implementing uploaded-protocol-execution and realize there's some huge refactors in the engine stuff that need to happen. While I think there's no way to avoid that in routing calls to the hardware, this state stuff and the parallel geometry implementation are the things that scare me the most and I think there we can and should be reimplementing uploaded-protocol evaluation in terms of the new stuff as we add it. That seems like it's tough and adds a lot of friction to implementing the http protocol stuff, and that's true, but putting it all off until the end means that just when we think "ahh, we're done" we realize we have these fully parallel implementations that we have to test separately and reimplement rather than implementing true vertical slices that we can test independently.

Implementing through uploaded-protocol execution also forces us to think about uploaded-protocol execution all the time, which is good because it prevents the "oh god this is going to be so hard to implement" all-at-once realization when the thing is done.

2020-11-09 16:14 UTC, b-cooper approved these changes
Great additions 🍔 . A couple of small comments

2020-11-09 16:14 UTC, b-cooper commented on api/src/opentrons/protocol_engine/state/geometry.py
> +        position = deck_def["locations"]["orderedSlots"][slot - 1]["position"]
This logic feels wobbly to me. The `orderedSlots` array in the deck definition defines  each slot object in the default order that the are to be traversed. The `slot` param here actually maps to the slot `"id"` key.  So it would be more accurate to do a find on the `orderedSlots` until the `id == slot`. That way we're not assuming that all deck definitions have to have slot id's that start at `1` etc.

2020-11-09 16:14 UTC, b-cooper commented on api/src/opentrons/types.py
> +class DeckSlot(int, enum.Enum):
Also, it would be great for consistency if this type mirrored the js flow type, which makes the important distinction between `DeckSlot` (the object of all properties pertaining to that location) and `DeckSlotId` (the string/number representation that is used to access and refer to the former).

2020-11-09 16:14 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/commands.py
> +    _commands_by_id: Dict[str, cmd.CommandType]
OH never mind all this I didn't see that it doesn't actually have a value, we're good

2020-11-09 16:15 UTC, sfoster1 commented on api/src/opentrons/protocol_engine/state/commands.py
> +    _commands_by_id: Dict[str, cmd.CommandType]
This is wrong because you're not assigning a value, as I am in this example.

2020-11-09 18:30 UTC, amitlissack approved these changes
This is good stuff. 

It gets us very close to our initial objective of basic pipetting over HTTP.

2020-11-09 18:46 UTC, sfoster1 approved these changes
Makes sense with offline discussion; let's just rename that `well_id` and I like it a lot!

2020-11-09 20:02 UTC, mcous commented on api/src/opentrons/types.py
> +class DeckSlot(int, enum.Enum):
How does something like `DeckSlotName` sound for now? I think we def need to align this further, but I also kind of want to avoid the confusion we had with `well_id`, because these aren't UUIDs

2020-11-10 16:45 UTC, merged