feat (protocol-designer): Add mount designation for matching pipettes
OpenTrons/opentrons-api pull request #6959
Opened 2020-11-10 19:27 UTC by Kadee80

# Overview

closes #6783 by adding `[L]` or `[R]` to the end of pipette names in pipette selection dropdowns when both pipettes are the same.

# Changelog

- feat (protocol-designer): Add L|R mount designation for same pipettes

# Review requests

- [ ] Left /Right designation appends to pipette name when both pipettes are the same
- [ ] Left /Right designation is appended to pipette name when pipettes are different
- [ ] Pipette selection and step saving unaffected

# Risk assessment

Low, Isolated selector for pipette dropdown

2020-11-10 19:49 UTC, Kadee80 commented on protocol-designer/src/step-forms/selectors/index.js
> +  const pipettes = Object.keys(pipettesOnDeck).map(id => {
Had to do it like this instead of values so that flow didn't flip 🙃

2020-11-11 19:52 UTC, shlokamin approved these changes
Looks good! Though I think you meant to say this 😄 

` Left /Right designation is NOT appended to pipette name when pipettes are different`

2020-11-12 16:08 UTC, IanLondon requested changes
could we have some unit test coverage of this? We have some selector tests in `protocol-designer/src/step-forms/test/selectors.test.js` but `getEquippedPipetteOptions` is uncovered

2020-11-12 16:08 UTC, IanLondon commented on protocol-designer/src/step-forms/selectors/index.js
> +  left: '(L)',
i18n?

2020-11-16 19:15 UTC, IanLondon approved these changes
looking good, thanks for the tests!

2020-11-16 21:09 UTC, merged