feat(protocol-designer): add pipette min to warnings
OpenTrons/opentrons-api pull request #6974
Opened 2020-11-11 18:15 UTC by shlokamin

# Overview

This PR adds the pipette minimum to "below recommended minimum" warnings. I also moved all form warning text into `i18n`.

closes #6493

# Changelog

- add pipette minimum to "below recommended minimum" warnings
- move all form warning text into i18n

# Review requests

- Code review
- Go through each of the warnings outlined in the [ticket](https://github.com/Opentrons/opentrons/issues/6493) and make sure the warning text matches, and that they include the correct pipette min.

I also moved the well overflow morning into `i18n` so make sure that guy still works too.

# Risk assessment

Low

2020-11-11 19:16 UTC, Kadee80 approved these changes
🦈

2020-11-12 15:14 UTC, IanLondon requested changes

2020-11-12 15:14 UTC, IanLondon commented on protocol-designer/src/steplist/formLevel/warnings.js
> +const FORM_WARNINGS: { [FormWarningType]: (?number) => FormWarning } = {
not sure if `?number` will be flexible enough to accommodate future warning metadata, but I'm OK with it as a start, I guess I might prefer `?string` b/c it's more versatile but that's a nitpick

2020-11-12 15:14 UTC, IanLondon commented on protocol-designer/src/steplist/formLevel/warnings.js
> +const FORM_WARNINGS: { [FormWarningType]: (?number) => FormWarning } = {
actually I wonder if since we always access `FORM_WARNINGS.NAME_OF_WARNING` and never `FORM_WARNINGS[dynamicWarningKey]`, should we get rid of FORM_WARNINGS and instead make each into a warning creator fn eg `belowMinAirGapVolume = (min: number): FormWarning => ...` , `overMaxWellVolume = (): FormWarnings => ...`

same pattern as in `protocol-designer/src/step-generation/warningCreators.js` and `step-generation/errorCreators.js`

then we'll have arbitrary args that are type-safe

2020-11-12 15:52 UTC, shlokamin commented on protocol-designer/src/steplist/formLevel/warnings.js
> +const FORM_WARNINGS: { [FormWarningType]: (?number) => FormWarning } = {
Nice, I like that better!

2020-11-13 18:19 UTC, shlokamin commented on protocol-designer/src/steplist/formLevel/warnings.js
> -// TODO: Ian 2018-12-06 use i18n for title/body text
😄

2020-11-16 19:27 UTC, IanLondon approved these changes
digging the changes :+1:

2020-11-16 19:36 UTC, merged