refactor(api): move some private methods out of InstrumentContext class.
OpenTrons/opentrons-api pull request #6984
Opened 2020-11-12 15:46 UTC by amitlissack

# Overview

This is a modest effort to chip away at InstrumentContext's size. (-130 lines)

# Changelog

Move private utility functions out of the InstrumentContext class. Put them in `protocols` package. 

# Review requests

Not much. This is a cut and paste job.

# Risk assessment

None

2020-11-12 15:48 UTC, amitlissack commented on api/src/opentrons/protocol_api/instrument_context.py
> +                                         self.hw_pipette.get(
Cannot use `self.return_height` due to version restrictions. This kind of thing will disappear with next refactor.

2020-11-12 20:46 UTC, mcous reviewed
On it's own, I think this is a good PR. We're kinda in a bad spot, though, because this PR refactors code that has diverged in #6793. I'm not sure how to reconcile while the 4.0.0 release is still ongoing

2020-11-12 20:46 UTC, mcous commented on api/src/opentrons/protocols/api_support/instrument.py
> +def tip_length_for(pipette: PipetteDict, tiprack: Labware) -> float:
The logic of this function at least has changed in the 4.0.0 release branch

2020-11-12 20:50 UTC, amitlissack commented on api/src/opentrons/protocols/api_support/instrument.py
> +def tip_length_for(pipette: PipetteDict, tiprack: Labware) -> float:
Hmmm. Good call. Perhaps I should branch of 4.0.0 release branch for this PR and only merge it to edge after 4.0.0 release branch is merged into edge. 

Makes sense?

2020-11-30 13:46 UTC, sfoster1 commented on api/src/opentrons/protocols/api_support/instrument.py
> +def tip_length_for(pipette: PipetteDict, tiprack: Labware) -> float:
@amitlissack This is the current implementation in edge:

```python
@lru_cache(maxsize=12)
    def _tip_length_for(self, tiprack: Labware) -> float:
        """ Get the tip length, including overlap, for a tip from this rack """

        def _build_length_from_overlap() -> float:
            tip_overlap = self.hw_pipette['tip_overlap'].get(
                tiprack.uri,
                self.hw_pipette['tip_overlap']['default'])
            tip_length = tiprack.tip_length
            return tip_length - tip_overlap

        try:
            parent = LabwareLike(tiprack).first_parent() or ''
            return get.load_tip_length_calibration(
                self.hw_pipette['pipette_id'],
                tiprack._implementation.get_definition(),
                parent).tip_length
        except TipLengthCalNotFound:
            return _build_length_from_overlap()
```

2020-11-30 13:48 UTC, sfoster1 requested changes
Just the `tip_length_for` to change for the 4.0 changes I think

2020-11-30 16:50 UTC, SyntaxColoring approved these changes
* The refactoring rationale makes sense to me.
* I skimmed the diff to see that what was removed was also added back in elsewhere.
* I haven't looked at the 4.0.0 merge conflict stuff, but I trust that it will be straightforward to resolve in this PR, given this PR just moves function blocks around.

2020-12-01 13:20 UTC, sfoster1 approved these changes
lgtm!

2020-12-01 18:39 UTC, merged