feat(robot-server): add door state event publisher
OpenTrons/opentrons-api pull request #7042
Opened 2020-11-20 14:40 UTC by sanni-t

# Overview

Closes #6924 

# Changelog

# Review requests

# Risk assessment

2020-11-20 18:54 UTC, amitlissack requested changes

2020-11-20 18:54 UTC, amitlissack commented on notify-server/Pipfile
> +opentrons = {editable = true, path = "./../api"}
One of these is redundant.

2020-11-20 18:54 UTC, amitlissack commented on robot-server/robot_server/hardware_wrapper.py
> +        settings = NotifyServerSettings()
I recommend you move the creation of a publisher to `dependencies.py`. We only need a single instance of a publisher in the robot-server.

For context: https://fastapi.tiangolo.com/tutorial/dependencies/

2020-11-20 18:54 UTC, amitlissack commented on robot-server/robot_server/hardware_wrapper.py
> +    def _publish_door_event(self, hw_event: HardwareEvent):
There may be a time when `HardwareEvent`'s aren't just door switch events.

2020-11-20 18:54 UTC, amitlissack commented on robot-server/robot_server/service/app.py
> +    # await api_wrapper.init_door_event_publisher()
Don't need this comment

2020-11-20 18:54 UTC, amitlissack commented on robot-server/tests/test_hardware_wrapper.py
> +async def test_door_event():
This test can simply call `_publish_door_event`

2020-11-20 19:42 UTC, sanni-t commented on notify-server/Pipfile
> +opentrons = {editable = true, path = "./../api"}
😑

2020-11-23 18:17 UTC, sfoster1 commented on robot-server/robot_server/hardware_wrapper.py
> +    def _publish_door_event(self, hw_event: HardwareEvent):
In fact there are already more! If there's a `pause_with_message`, this callback gets called with the message (I dunno if we want to keep it though)

2020-11-23 18:17 UTC, sfoster1 commented on robot-server/robot_server/hardware_wrapper.py
> +            self._event_publisher.send_nowait("hardware.door_event", Event(
Do we have/want to have a constants file or a types file where we define constants like this topic and the structures they correspond to?

2020-12-02 14:45 UTC, sfoster1 reviewed
Working on #7074 I think has given me some more in depth opinions on this and I wonder if we can take some lessons from that. I think the biggest thing that we could do is some more typing work on the typing of the publishers and subscribers. For instance, doing the `overload` for `publish` and `subscribe` could be really useful, but I don't know that mypy has the capability to do it for multiple topics automatically.

The thing that would make it possible I think is if we could create a type-level association between a topic and its associated event. Maybe this is just me whistling into the wind and it's not really possible with mypy; the example in C++ would be something like

```
struct HardwareEvent {
  int door_state;
};
struct HardwareTopic {
   const static str Topic = "hardware";
   typedef HardwareEvent Event;
};

template <typename T>
struct Notifier {
   void publish<T::Topic>(T::Event event);
};
```
(this isn't quite valid I think but you can do something like this). The goal is to have more specific type bindings for the publish and the subscribe sides so that you always have to send the correct event for the topic, rather than specifying any topic from a list of topics and any event from a list of events.

2020-12-02 17:16 UTC, sanni-t commented
> Working on #7074 I think has given me some more in depth opinions on this and I wonder if we can take some lessons from that. I think the biggest thing that we could do is some more typing work on the typing of the publishers and subscribers. For instance, doing the `overload` for `publish` and `subscribe` could be really useful, but I don't know that mypy has the capability to do it for multiple topics automatically.
> 
> The thing that would make it possible I think is if we could create a type-level association between a topic and its associated event. Maybe this is just me whistling into the wind and it's not really possible with mypy; the example in C++ would be something like
> 
> ```
> struct HardwareEvent {
>   int door_state;
> };
> struct HardwareTopic {
>    const static str Topic = "hardware";
>    typedef HardwareEvent Event;
> };
> 
> template <typename T>
> struct Notifier {
>    void publish<T::Topic>(T::Event event);
> };
> ```
> 
> (this isn't quite valid I think but you can do something like this). The goal is to have more specific type bindings for the publish and the subscribe sides so that you always have to send the correct event for the topic, rather than specifying any topic from a list of topics and any event from a list of events.

That's a good point. CPX talked about this and we concluded that it's too early to decide on this structure. There are also going to be events that share a topic. So we'll need to update the structure when we have a better idea of what events & topics will have to be tied together. I will add a TODO with this note in the payload type.

2020-12-02 17:53 UTC, sanni-t commented
Added ^TODO

2020-12-03 14:25 UTC, amitlissack requested changes
Please look at comments.

Specifically about topics. I am suggesting we start with a few broad topics.

2020-12-03 14:25 UTC, amitlissack commented on robot-server/robot_server/hardware_wrapper.py
> +    DOOR_EVENT = "hardware.door_event"
This should be in the notification server project

2020-12-03 14:25 UTC, amitlissack commented on robot-server/robot_server/hardware_wrapper.py
> +    def _publish_door_event(self, hw_event: HardwareEvent):
What we're saying is that this method is misnamed. It is a listener for hardware events.

2020-12-03 14:25 UTC, amitlissack commented on robot-server/robot_server/hardware_wrapper.py
> +    DOOR_EVENT = "hardware.door_event"
Additionally, I am starting to think that door events should come via a `hardware` topic.

2020-12-03 14:25 UTC, amitlissack commented on notify-server/notify_server/models/payload_type.py
> +    # TODO (SPP,2020-12-02): Add more specific type bindings for pub/subs
As mentioned below, door switch event may not warrant a topic. I suggest a disambiguating string in this object.

2020-12-03 15:14 UTC, sfoster1 commented on robot-server/robot_server/hardware_wrapper.py
> +    DOOR_EVENT = "hardware.door_event"
> This should be in the notification server project

I dunno, the more I think about it the more I like the concept of generic code only in the notify server, or at least a clear separation between the part of the notify server that defines the message routing and pub/sub stuff, and the part that provides type and model definitions for messages.

I do like the idea of not requiring subscribers to depend directly on the publishing project, which is the real benefit of keeping message types in the notify server. So reading the rest of this comment, where I talk about the "publisher project" and the "notify server", you could also think of it as the "notify server data definitions" and "notify server core".

 While you could make the notify server core code properly typed if mypy had better HKT support, separately-generic functions, or both, I think we can get to a similarly good place by doing the following:

- The notify server core publisher and subscriber class defs are ABCs
- Notification publisher projects/notify server data definitions make custom overrides for the publisher class using overloads linking `topic`s (by literal) and `Message` types (as unions of models). 

The topic and model definitions are public to consumer projects:
```
robot_server.types

TOPIC_A: Final = 'TopicA'

class MessageA1(notify_server.BaseMessage):
    pass

class MessageA2(notify_server.BaseMessage):
    pass

MessagesA = Union[MessageA1, MessageA2]

TOPIC_B: Final = 'TopicB'

class MessageB1(notify_server.BaseMessage):
   pass

class MessagesB = Union[MessageB1]
```

The publisher definition provides type-safe calls to `publish` internally in the project/is only imported from the notify server data definitions by the publisher, and does not need to be otherwise public:
```
robot_server.publisher

class RobotServerPublisher(Publisher):
    @overload
    def publish(topic: Literal['TopicA'], messages: MessagesA): ...
  
    @overload
    def publish(topic: Literal['TopicB'], messages: MessagesB): ...

   def publish(topic, messages): return super().publish(topic, messages)

RobotServerPublisher().publish(TOPIC_B, MessageA1())  # type error
```

And, the subscriber definition is intended to provide any subscriber project depending on the publisher/notify server data definitions with type-safe subscription:

```
robot_server.notifications

class RobotServerSubscriber(Subscriber):
    @overload
    def subscribe(topic: Literal['TopicA'], callback: Callable[[MessagesA], None]) -> None: ...

    @overload
    def subscribe(topic: Literal['TopicB'], callback: Callable[[MessagesB], None]) -> None: ...

    def subscribe(topic, callback): super().subscribe(topic, callback)
```

Now, you're in some other project, and you want to add a subscriber to what the robot server provides. By depending on either the robot server or the notify server data definitions, you get this `RobotServerSubscriber` class for free and can use it directly and immediately.

2020-12-03 16:28 UTC, amitlissack commented on robot-server/robot_server/hardware_wrapper.py
> +    DOOR_EVENT = "hardware.door_event"
I think this is some good thinking. I also believe that it isn't a heavy lift to make these changes.

My hope is that we find publishing and subscribing very useful. Refactors will happen as we learn more about how we use the notify server clients.

2020-12-04 17:46 UTC, amitlissack approved these changes
Thanks for your patience with all the comments.

2020-12-04 17:46 UTC, amitlissack commented on robot-server/Pipfile
> +mypy = "*"
This is incorrect. `mypy` is only a dev dependency

2020-12-04 17:49 UTC, sfoster1 approved these changes
Looks good to me!

2020-12-04 18:00 UTC, mcous approved these changes

2020-12-04 18:00 UTC, mcous commented on notify-server/Pipfile
> +opentrons = {editable = true, path = "./../api"}
Nit, but could this just be `../api`?

2020-12-04 18:00 UTC, mcous commented on notify-server/notify_server/clients/publisher.py
> +            log.exception(f"Exception while sending publish event: {e}")
Is the `{e}` is redundant here? I thought that calling `log.exception` in an exception handler automatically adds exception info to the log

2020-12-04 18:00 UTC, mcous commented on notify-server/notify_server/models/payload_type.py
>      SampleTwo,
[Not urgent] Might be worth removing the SampleEvents now that we have a real event!

2020-12-04 18:45 UTC, sanni-t commented on notify-server/notify_server/models/payload_type.py
>      SampleTwo,
I think we can leave it until we add one more real event. Helps see the pattern easily.

2020-12-04 19:57 UTC, merged