feat(shared-data): add default tipracks to each pipette name spec
OpenTrons/opentrons-api pull request #7108
Opened 2020-12-07 20:48 UTC by Laura-Danielle

# Overview

Closes #7085. Add a key called `defaultTipracks` which holds a list of tiprack URIs that are compatible with that pipette type, and part of the opentrons labware library.

# Changelog

- Modify pipetteNameSpecs to accommodate the new key
- Load that key into pipette configs
- Update snapshots

# Review requests

Cool with the key name? Anything else you would like to change?

# Risk assessment

Low, adding another key to `pipetteNameSpecs`.

2020-12-07 21:27 UTC, sfoster1 requested changes
This will work great but it might be a good idea to make the python typing a list of labware URI rather than literals, because this list of literals is both too specific (since we now have to update it every time we change/add tipracks) and not specific enough (it allows 300ul tipracks in the 10ul pipettes, for instance).

2020-12-07 21:54 UTC, shlokamin requested changes
Seems reasonable to me!

Just one thing — we should add `defaultTipracks` to the Flow def `PipetteNameSpecs` in `shared-data/js/types.js` so we can interact with the type appropriately in JS world.

@IanLondon jotting down a few things to note:

(1) `defaultTipracks` is a required field now for pipettes, which is good for us to know
(2) We should modify this description in the our protocol schema defs: 
```js
"pipetteName": {
      "description": "Name of a pipette. Does not contain info about specific model/version. Should match keys in pipetteNameSpecs.json file",
      "type": "string"
    }
```
I did a quick `Ctrl + F` to find this.  I don't see why we're referencing `pipetteNameSpecs.json` in the description. Is there a reason for that?

2020-12-08 19:12 UTC, shlokamin approved these changes

2020-12-09 19:43 UTC, IanLondon commented on shared-data/js/types.js
> +  defaultTipracks: Array<string>,
:+1:

2020-12-09 19:59 UTC, IanLondon approved these changes

2020-12-09 20:04 UTC, sfoster1 approved these changes
Awesome!

2020-12-09 20:17 UTC, merged