Show errors when labware definition invalid
OpenTrons/opentrons-api pull request #7113
Opened 2020-12-09 05:20 UTC by MarcelRobitaille

# Overview

The purpose of this pull request is to show Ajv validation errors. I spent a good while today troubleshooting my labware definition, which I think is needless since Ajv points out exactly what went wrong.

# Changelog

- Make [`validatelabwareDefinition`](https://github.com/MarcelRobitaille/opentrons/blob/4e889d470660c0ab20f0328bfaa140cac8aaad5f/app-shell/src/labware/validation.js#L28) return a list of validation errors
- Make [`validateLabwareFiles`](https://github.com/MarcelRobitaille/opentrons/blob/4e889d470660c0ab20f0328bfaa140cac8aaad5f/app-shell/src/labware/validation.js#L34) add `errors` key to each returned file object
- Make [`AddLabwareFailureModal`](https://github.com/MarcelRobitaille/opentrons/blob/4e889d470660c0ab20f0328bfaa140cac8aaad5f/app/src/components/AddLabwareCard/AddLabwareFailureModal.js#L111) and [`LabwareItem`](https://github.com/MarcelRobitaille/opentrons/blob/4e889d470660c0ab20f0328bfaa140cac8aaad5f/app/src/components/ListLabwareCard/LabwareItem.js#L73) show a list of validation errors

# Review requests

# Risk assessment

Ack shows that `validateLabwareDefinition` is not used anywhere else, so there is no risk to change its signature.
Adding the `errors` key to the file object should not pose any risk either.

Adding elements to the UI could have an adverse affect on layout.

I admit that I have not run / added tests, but when I `make test-js`, I get `SyntaxError: Cannot use import statement outside a module` for each file, although I followed installation diligently.

I checked for open issues, and didn't find any.

2020-12-09 16:34 UTC, sfoster1 requested changes
Thanks for the PR! The added functionality looks really good, but there's a couple things to fix up before it can be accepted.

Small things first:
- Please change the title of the PR to something that follows [conventional-commits](https://www.conventionalcommits.org/en/v1.0.0/), such as `feat(app,app-shell): Display validation errors that make an added labware invalid` (I can also do this, if you're ok with it)
- If you run `make format`, the warnings about newlines and so on should go away. 
- Similarly, you can run the rest of our checks locally:
  - `make check-js` runs `flow` to check types
  - `make lint-js` runs a suite of style and static analysis checkers for javascript (there are other ones for css changes and so on, but you haven't made any changes there so they shouldn't be necessary)
  - `make test-js` runs our automated test suite
If all those pass locally, they should pass on Github Actions as well.

The bigger changes flow from these as well; when you run `make check-js`, you'll notice that `flow` will have a lot of errors. We really rely on the [flow javascript type system](https://flow.org/) to make our js development better. In this case, you'll need to change types starting from the lowest level (I've made some inline comments to explain a bit further), and bring those changes up through the Redux actions that the `app-shell`, which is the electron node process, uses to communicate with the electron ui process (the `app`).

We also rely really heavily on automated testing, in our case done with [jest](https://jestjs.io/); tests for a given file can usually be found in a subdirectory called `__tests__` in the same directory as the file. While we don't require 100% coverage, a change to the basic format of interprocess communication in the app should have some tests with it.

Again, this is an awesome PR! Thanks for submitting it!

2020-12-09 16:34 UTC, sfoster1 commented on app-shell/src/labware/validation.js
> +const validateLabwareDefinition = (data: any): DefinedError[] | null => {
The type here should probably be `Array<DefinedError> || LabwareDefinition2` I think, if we're going to pass the error upward; or possibly however `ajv` types the result of `compile`. Or possibly, to make it a little clearer at runtime which is which, an object like `{| errors: Array<DefinedError> |} | {|definition: LabwareDefinition2 |}`

2020-12-09 16:34 UTC, sfoster1 commented on app-shell/src/labware/validation.js
> +    if (errors) {
If you take the approach above of using a union of objects, this could be a bit simpler

2020-12-09 16:34 UTC, sfoster1 commented on app-shell/src/labware/validation.js
>      // check file against the schema
As with `validateLabwareDefinition`, `validateLabwareFiles` I think needs types that correspond with its new behavior; maybe create a new type `InvalidLabwareFile` which stores the ajv errors, and have `validateLabwareFiles` return `Array<CheckedLabwareFile | InvalidLabwareFile>`? This will then need to also be done to `validateNewLabwareFile` below, and we'll also need to change the typing for the redux action used to dispatch the result of the validation back to the UI thread. Those actions are in `app/src/custom-labware/actions`. The dispatch point is also where we would finally break apart the union gathering the either-error-or-validated-labware union.

2020-12-09 20:39 UTC, IanLondon commented
Hey thank you @MarcelRobitaille this is an exciting contribution! I'm down to fix Flow-typing stuff if you'd like me to help.

2020-12-10 02:05 UTC, MarcelRobitaille commented on app-shell/src/labware/validation.js
> +const validateLabwareDefinition = (data: any): DefinedError[] | null => {
Sorry, I'm new to flow. My suggestion was to make this function return an array of `DefinedError` or `null`. Before, it either returned its argument unchanged or `null`, so I thought making it no longer return the argument would be fine. I also considered returning an array or an object of errors and the definition, but I decided to go with the simpler solution since the argument isn't modified. What do you think?

2020-12-10 02:13 UTC, MarcelRobitaille commented
Thanks for the kind feedback. @IanLondon actually yeah I'm new to flow and would really appreciate the help!

2020-12-11 13:34 UTC, sfoster1 commented on app-shell/src/labware/validation.js
> +const validateLabwareDefinition = (data: any): DefinedError[] | null => {
Well, what that unchanged return did is use types to establish a function whose inputs are an unverified definition, and whose outputs are either a verified definition or a well-defined error. That's a really handy thing to have, and it presents a good point for any future work around fusing extra information or something like that (nothing involved with that now, as you can see). I would prefer we keep that style and have this function return the definition or error.

2020-12-11 15:02 UTC, MarcelRobitaille commented on app-shell/src/labware/validation.js
> +const validateLabwareDefinition = (data: any): DefinedError[] | null => {
Ok, that's what I suspected. I tried to do it as you suggested. Have I done it correctly now?

2022-03-16 13:36 UTC, amitlissack commented
Closed due to inactivity

2022-03-16 13:36 UTC, closed without merging