refactor(robot-server): implement the load labware function to accept tipracks from the client
OpenTrons/opentrons-api pull request #7131
Opened 2020-12-15 15:16 UTC by Laura-Danielle

# Overview
This PR supports #7901 on the backend. 

# Changelog

- Add ability to pass a tiprack definition during a load labware command
- Implement load labware for deck calibration and pipette offset
- Add tests for that + modify older tests

# Review requests

Due to pydantic union issues (again) I had to make the tiprack definition required in load labware. Should we try to do a refactor of request models to avoid using unions again here, or is this fine for now?

# Risk assessment

Medium. We are changing how load labware works on the backend, and forcing the front end to pass in a tiprack definition for all of the user flows to this command.

We should test all of the user flows once #7901 is up.

2020-12-15 15:36 UTC, sfoster1 requested changes
We cannot require all `loadLabware` commands to contain a labware. The app in 4.0 sends this command for all the user flows, and this would therefore be a breaking API change.

We have to accept `loadLabware` commands without a definition element in all cases. In cases where it previously did nothing, it should continue to do nothing; in the cases we're adding, not sending a labware def should make it continue to do nothing, and stick with the labware def sent at session establish. I'm not sure what the best way to do that is - @amitlissack any ideas about the particulars of how to get this to work with pydantic?

2020-12-15 15:36 UTC, sfoster1 commented on robot-server/robot_server/service/session/models/command.py
> +    tiprackDefinition: dict = Field(
This may want a richer type like at least `Dict[str, Any]`

2020-12-15 15:36 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/pipette_offset/user_flow.py
> +        self._load_tip_rack(
let's validate this def against the schema and make sure it's a tiprack before passing it to `_load_tiprack`. `_load_tiprack` taking a `LabwareDefinition` means that the def should be checked for validity.

2020-12-15 15:36 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/pipette_offset/user_flow.py
> +        state_machine: PipetteOffsetStateMachine =\
Any way we can get rid of these type ignores?

2020-12-15 15:41 UTC, Laura-Danielle commented on robot-server/robot_server/robot/calibration/pipette_offset/user_flow.py
> +        self._load_tip_rack(
We don't validate that anywhere else. Should I add that in to the create params as well for all of the flows?

2020-12-15 15:44 UTC, sfoster1 commented on robot-server/robot_server/robot/calibration/pipette_offset/user_flow.py
> +        self._load_tip_rack(
Yeah probably should! Should return a 4xx if it fails

2021-01-04 14:08 UTC, sfoster1 approved these changes
I'm ok moving forward with this but it is a little weird that it will _always_ emit "loadLabware" as a supported command no matter the current state.

2021-01-04 19:23 UTC, mcous commented
Just a heads up: The `ProtocolEngine` will almost certainly have separate `loadLabware` and `loadLabwareFromDefinition` commands defined. I think we should do the same here, especially if we're looking for the presence of some supported command to answer on the client side "can this thing load a custom labware"?

2021-01-05 16:26 UTC, ahiuchingau approved these changes
Tested on robot, LGTM!

2021-01-05 19:14 UTC, merged