feature(robot-server): protocol http api uses fast sim
OpenTrons/opentrons-api pull request #7146
Opened 2020-12-19 02:00 UTC by amitlissack

# Overview

Upload performs analysis to extract metadata and equipment requirements for a protocol.

# Changelog

- divide up UploadedProtocol class into multiple files.

# Review requests

This is a first stab at this. I'm not sure that the models are complete.

# Risk assessment

None. This is not publicized

2020-12-21 15:32 UTC, sfoster1 requested changes
I think we should keep the names of attributes consistent with their names in rpc where those names aren't explicitly backcompat hacks (aka everything but pipette name), especially around `requestedAs` (which is `name` here) and `name`, which here is `pipetteName`. We also need a bit more information in the labware model, as I understand it.

Structurally, what's here looks good but it leaves two really big holes that I'd like to see todo comments or planned work for:
- We need to be able to upload custom labware. I think I see where it will fit in, but it's a really important need. We also need to be able to subsequently download the custom labware associated with the protocol to handle one client uploading a protocol and another client querying that protocol.
- We need to get rich error information out of failed protocol simulations. This can be internal errors from the simulation failing, but could also be things like syntax errors from the uploaded protocol. I think we should not handle this through letting the exception bubble up to the standard fastapi handlers, since errors in the protocol are actually one of the expected outcomes of the simulation, and we want to bundle in a lot of information about for instance which line of the protocol the error happened on. We get that information for free from the machinery in `execute.run_protocol`, but I really think it should be a different kind of 200 response since fundamentally the _simulate call itself_ didn't have an error - the protocol did. I could also see a 4xx being acceptable, but we really need richer error information than we want to provide from other endpoints.

2020-12-21 15:32 UTC, sfoster1 commented on robot-server/robot_server/service/protocol/models.py
> +    name: str = \
The (one of the) annoying things about the protocol execution model is the whole actual name vs requested name thing. I think it's best to keep that element, which I think is `name` here, as `requestedAs`.

2020-12-21 15:32 UTC, sfoster1 commented on robot-server/robot_server/service/protocol/models.py
> +class LoadedPipette(BaseModel):
Should we use the `opentrons_shared_data.pipettes.types.PipetteName` set of literals here?

2020-12-21 15:32 UTC, sfoster1 commented on robot-server/robot_server/service/protocol/models.py
> +    type: str = \
`name` and `type` don't really correspond to descriptors we use in other places. I think `name` should be `label` (if that's the argument to `load_labware` it's meant to capture) and `type` should probably be `uri`, unless it's the type as in "96standard" or "reservoir", in which case we should add the contents of the URI somewhere in this model as well.

It's also important to have labware definitions available from this API somewhere to support uploading a protocol with custom labware from one runapp and then interacting with the protocol from another.

2020-12-21 15:32 UTC, sfoster1 commented on robot-server/robot_server/service/protocol/models.py
> +    type: str = \
Oh it also might be better to encode here if the labware is on a module; the client currently decides that and certainly can continue to, but it seems like it should be the server's responsibility.

2020-12-21 15:32 UTC, sfoster1 commented on robot-server/robot_server/service/protocol/models.py
> +    name: str = \
is the `name` here supposed to be a label or the module type? Probably we should have both

2020-12-21 15:32 UTC, sfoster1 commented on robot-server/robot_server/service/protocol/models.py
> +    name: str = \
A lot of data definitions for modules are available in `opentrons_shared_data.module.dev_types`, for things like module types and in fact module models; might be useful here.

2020-12-21 15:32 UTC, sfoster1 commented on robot-server/robot_server/service/protocol/analyze.py
> +    metadata = protocol.metadata \
it might be worth adding a todo in `protocols.parse` and `protocols.types` to have type definitions and extractors for similar data from json protocols. that data is there, we just don't have builtins to extract it.

2020-12-21 15:32 UTC, sfoster1 commented on robot-server/robot_server/service/protocol/analyze.py
> +    run_protocol(protocol, context=ctx)
more about it in the overall review comment, but `run_protocol` will raise any exceptions incurred by the simulation, which could include things like syntax errors; we really want rich error information available here.

2020-12-21 16:52 UTC, amitlissack commented on robot-server/robot_server/service/protocol/models.py
> +    name: str = \
> I think we should keep the names of attributes consistent with their names in rpc where those names aren't explicitly backcompat hacks (aka everything but pipette name), especially around `requestedAs` (which is `name` here) and `name`, which here is `pipetteName`. We also need a bit more information in the labware model, as I understand it.
> 
> Structurally, what's here looks good but it leaves two really big holes that I'd like to see todo comments or planned work for:
> 
> * We need to be able to upload custom labware. I think I see where it will fit in, but it's a really important need. We also need to be able to subsequently download the custom labware associated with the protocol to handle one client uploading a protocol and another client querying that protocol.
> * We need to get rich error information out of failed protocol simulations. This can be internal errors from the simulation failing, but could also be things like syntax errors from the uploaded protocol. I think we should not handle this through letting the exception bubble up to the standard fastapi handlers, since errors in the protocol are actually one of the expected outcomes of the simulation, and we want to bundle in a lot of information about for instance which line of the protocol the error happened on. We get that information for free from the machinery in `execute.run_protocol`, but I really think it should be a different kind of 200 response since fundamentally the _simulate call itself_ didn't have an error - the protocol did. I could also see a 4xx being acceptable, but we really need richer error information than we want to provide from other endpoints.

Very deliberately not dealing with those in this PR. The way we catch and represent errors and the way we handle custom labware are worthy of thought and investigation. 

TODOs are pretty meaningless. They're littered around our code base and represent no commitment to doing any sort of work.  I'll create a tickets to add custom labware support and improve/catch errors.

2020-12-21 16:52 UTC, amitlissack commented on robot-server/robot_server/service/protocol/models.py
> +class LoadedPipette(BaseModel):
Good idea. I'll look at it.

2021-01-05 13:00 UTC, amitlissack commented on robot-server/robot_server/service/protocol/analyze.py
> +    run_protocol(protocol, context=ctx)
Pushing to a future PR

2021-01-05 13:12 UTC, amitlissack commented on robot-server/robot_server/service/protocol/models.py
> +    type: str = \
I'm not sure about the labware/module relationship. If a labware and module are in the same slot then the labware is loaded on the module (right?). That can be easily deduced from this model. `ProtocolContext.loaded_labwares` exposes labware by slot regardless of module parent. 

Another approach I was considering is a deck model mapping slot number to items in that slot. I'm not thrilled about that. 

Perhaps I will rename `slot` to `location` or `parent`.

2021-01-05 13:18 UTC, amitlissack commented on robot-server/robot_server/service/protocol/analyze.py
> +    metadata = protocol.metadata \
Gonna create a ticket.

2021-01-07 14:16 UTC, sfoster1 approved these changes
Looks good to me, looking forward to seeing how it evolves!

2021-01-19 18:55 UTC, mcous approved these changes
This one LGTM! Little note in Slack about test data, but otherwise I'm moving on to reviewing #7225

2021-01-22 22:06 UTC, merged