fix(robot-server,notify-server): async
OpenTrons/opentrons-api pull request #7152
Opened 2020-12-21 21:29 UTC by amitlissack

# Overview

Client create methods need to be `async`. 

# Changelog

Fix a documentation error
Make create methods `async`
Redo dependency creating the singleton publisher

# Review requests

asyncio makes me feel stupid.
does door state still work?

# Risk assessment

Very low.

2020-12-21 21:33 UTC, sfoster1 reviewed
what's up with the `Pipfile.lock` changes?

2020-12-21 23:30 UTC, amitlissack commented
> what's up with the `Pipfile.lock` changes?

I modified the Pipfile in notify-server to use editable `shared-data`. Not sure why robot-server got updated. I undid it.

2020-12-23 16:03 UTC, SyntaxColoring reviewed
Left some comments and questions.

In our call this morning, you said you wanted to go over it again yourself and refresh your memory on why some of these changes were necessary.

I haven't had the chance to test that the door state still works, and I won't have access to my OT-2 over the holidays—sorry!

2020-12-23 16:03 UTC, SyntaxColoring commented on notify-server/Pipfile
> +opentrons-shared-data = {editable = true, path = "./../shared-data/python"}
`pipenv` frightens and perplexes me, so I'm assuming this and `Pipfile.lock` are correct.

2020-12-23 16:03 UTC, SyntaxColoring commented on notify-server/README.rst
> +   python -m notify_server.app_sub -s tcp://localhost:5555 topic1 topic2
If you're already in the neighborhood fixing readme mistakes, the "Development environment" section incorrectly says that notify-server uses Poetry.

(No need for this to get fixed in this PR, of course.)

2020-12-23 16:03 UTC, SyntaxColoring commented on notify-server/notify_server/clients/publisher.py
> -            await connection.send_multipart(entry.to_frames())
This isn't directly related to this PR and you don't have to fix it here, but the name `_send_task()` was confusing to me. I think it means "this is a task whose job it is to send," but it reads as "take a task and send it somewhere." The noun phrase is mistakable as a verb phrase.

2020-12-23 16:03 UTC, SyntaxColoring commented on notify-server/notify_server/clients/publisher.py
> +                log.exception(f"Failed to send {entry}")
Should we really be swallowing all exceptions here? What exceptions do we anticipate from `send_multipart()` and `to_frames()`? Can we be more narrow?

If we have to fail, can we fail somewhere more transparent than this background task? For example, if a user of this API can cause an exception by trying to send a badly-formatted payload, is there a way to raise that error *when they first give us the payload,* instead of here, when we happen to be getting around to sending it?

2020-12-23 16:03 UTC, SyntaxColoring commented on notify-server/notify_server/clients/subscriber.py
> +async def create(
I wasn't initially sure why this needed to be async. But from our video call, I understand:

* Creating the "background" task [needs](https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task:~:text=RuntimeError%20is%20raised%20if%20there%20is%20no%20running%20loop%20in%20current%20thread.) a running event loop.
* Even if it didn't, making this async is a good idea to strongly indicate to the caller that they should be in an async context.

So in principle, changing this to `async` LGTM.

-----

Inside `create_subscriber()`, there's a `sock.connect()` call. If that were a normal network socket, I would be concerned that we're running a potentially long-running blocking operation in this main event loop thread.

I don't know enough about ZMQ sockets to know if that call is actually problematic in our case. What do you think?

2020-12-23 16:03 UTC, SyntaxColoring commented on notify-server/tests/integration/test_pub_sub.py
> +        settings.publisher_address.connection_string())
I really hate our line length limits. :( &lt;/rant&gt;

2020-12-23 16:03 UTC, SyntaxColoring commented on robot-server/robot_server/hardware_wrapper.py
> +        from robot_server.service.dependencies import get_event_publisher
Is this `import` statement here deliberately, or should it be at the top of the file?

2020-12-23 16:03 UTC, SyntaxColoring commented on robot-server/robot_server/hardware_wrapper.py
> +        self._event_publisher: typing.Optional[Publisher] = None
I'm a bit unclear on what this whole class is doing, so maybe this is a dumb question, but why are these `Optional`/`None`, instead of being concretely initialized here in `__init__()`?

2020-12-23 16:03 UTC, SyntaxColoring commented on robot-server/robot_server/hardware_wrapper.py
> +        if self._event_publisher:
See comment above about `self._event_publisher` being optional.

2020-12-23 16:03 UTC, SyntaxColoring commented on robot-server/robot_server/service/dependencies.py
> +_event_publisher_inst = None
This wouldn't necessarily be better unless you think it is, but you can avoid a global variable by putting the `_event_publisher_inst` attribute on the `get_event_publisher()` function.

https://stackoverflow.com/a/279597/497934

2020-12-23 16:03 UTC, SyntaxColoring commented on robot-server/robot_server/service/session/session_types/protocol/execution/command_executor.py
> +            hardware=configuration.hardware,
What does this do?

2020-12-23 16:12 UTC, SyntaxColoring requested changes
test comment, ignore me

2020-12-23 16:47 UTC, sanni-t commented on robot-server/robot_server/hardware_wrapper.py
> +        from robot_server.service.dependencies import get_event_publisher
It creates a circular dependency since the dependencies file imports from hardware wrapper. Hence it's inside here.

2020-12-23 16:47 UTC, sanni-t commented on robot-server/robot_server/hardware_wrapper.py
> +        self._event_publisher: typing.Optional[Publisher] = None
Initialization of the hardware wrapper happens through an async call to `initialize()` during robot-server startup. This initialization fetches the actual hardware control api (or the hw threadmanager) which is required to initialize the hardware event publisher. In case if the hardware api isn't available, no publisher will be created. Hence it's only defining the property here and creating the actual publisher later.

2020-12-23 20:03 UTC, SyntaxColoring commented on notify-server/notify_server/clients/publisher.py
> +                log.exception(f"Failed to send {entry}")
Thinking about this some more: I think exception handling being tough here is a symptom of some funky internal implementation details, which also happen to leak through and cause some funky semantics on `send()`.

This might sound a bit handwavey because I'm rushing out the door. And I'm only like 20% sure how ZMQ works because I haven't read the guide yet. But bear with me.

-----

Our `publisher.Publisher` has an internal `Queue`. This internal queue happens to be of unbounded length (I'm not sure if the unbounded length is intentional, but that's how we make it in `publisher.create()`).

`publisher.Publisher.send()` returns after it places a message on that internal queue. To me, this...seems like an unnecessarily weak primitive? Wouldn't we want it to return when it successfully *gives ZMQ the message*? In a sense, ZMQ is itself a big queue, right? Why, then, are we only using it indirectly, through a feeder queue?

Using an internal feeder queue:

* Hides certain failures until it's too late to handle them properly, as discussed above in my comment about exception handling.
* Circumvents natural backpressure. [Backpressure is a good thing (and hidden buffers can be a bad thing)](https://vorpus.org/blog/some-thoughts-on-asynchronous-api-design-in-a-post-asyncawait-world/#bug-1-backpressure). If, for some reason, ZMQ can't accept messages as quickly as we're submitting them, we should slow down until ZMQ is ready.
* Smells like the kind of thing that will hide deadlocking bugs. I'm vaguely reminded of some Go bugs that I've seen. Handwavey, I know, sorry—but from a high level, you can imagine how a hidden buffer adds nondeterminism to whether a `put()` or `get()` operation will block, and that nondeterminism causes bugs because you have to remember to consider it *every time you `put()` or `get()`*, and that's hard.
* Weakens our message ordering guarantees by a lot. We can no longer say anything about the relative ordering of events submitted by two publishers to a common topic. If we're fine with this, then, okay—but then we should formally document what delivery semantics we *can* rely on, and we'll have to be very careful to build users of our notification system around those guarantees. Because that's the kind of breach of intuition that makes distributed systems hard.

Separately, `publisher.Publisher.send_nowait()` returns immediately, and either submits the message or fails silently depending on whether there's room in the internal queue. Again, I don't think this is a usefully strong primitive. But also, since the queue is unbounded, I think this will never actually fail, and so it's equivalent to `publisher.Publisher.send()`?

-----

tl;dr I think this is the code telling us that the internal feeder queue is questionable, and we should listen to the code. But let me know if this are unclear and I'll try to be a bit more concrete when I have some more time.

2020-12-23 22:40 UTC, sanni-t reviewed
Door state still works 👍

2020-12-28 13:13 UTC, amitlissack commented on notify-server/README.rst
> +   python -m notify_server.app_sub -s tcp://localhost:5555 topic1 topic2
Good catch

2020-12-28 13:17 UTC, amitlissack commented on notify-server/notify_server/clients/publisher.py
> +                log.exception(f"Failed to send {entry}")
I made it way more complicated than necessary due to ignorance. The goal was to make sending an event be as non-obtrusive as possible. But I didn't realize that zmq already does that. 

Thanks for thinking about this.

I will remove the queuing.

2020-12-28 13:18 UTC, amitlissack commented on robot-server/robot_server/service/session/session_types/protocol/execution/command_executor.py
> +            hardware=configuration.hardware,
`configuration.hardware` is a `ThreadManager`. Its `sync` property returns a `SynchronousAdaptor`. The protocol context requires a synchronous interface to the `API` class.

2020-12-28 21:01 UTC, amitlissack commented on robot-server/robot_server/service/dependencies.py
> +_event_publisher_inst = None
I like it! Thanks

2020-12-30 15:34 UTC, SyntaxColoring commented on notify-server/notify_server/clients/serdes.py
> +"""Implementation of the QueueEntry class."""
This docstring looks outdated.

I'd personally just delete this module-level docstring unless you think it has something to add over the method- and class-level docstrings.

2020-12-30 15:34 UTC, SyntaxColoring commented on notify-server/notify_server/clients/publisher.py
>      def send_nowait(self, topic: str, event: Event) -> Future[Any]:
Do we need both `send_nowait()` and `send()` still?

2020-12-30 15:34 UTC, SyntaxColoring commented on notify-server/notify_server/network/connection.py
> +        return self._socket.send_multipart(frames)  # type: ignore
Why `def ... -> Future[Any]` and `return`, instead of `async def ... -> None` and `await`?

Not necessarily a negative thing, just wondering.

2020-12-30 15:34 UTC, SyntaxColoring commented on notify-server/notify_server/network/connection.py
> +    def send_multipart(self, frames: List[bytes]) -> Future[Any]:
Why return a `Future[Any]` instead of `await`ing inside the function and returning `None`?

Not necessarily a negative thing, just wondering.

2020-12-30 15:36 UTC, amitlissack commented on notify-server/notify_server/clients/publisher.py
>      def send_nowait(self, topic: str, event: Event) -> Future[Any]:
We do need both. There is non-async code in our code base that should be able to send notifications.

2020-12-30 15:36 UTC, amitlissack commented on notify-server/notify_server/network/connection.py
> +    def send_multipart(self, frames: List[bytes]) -> Future[Any]:
For the reason mentioned above.

2020-12-30 15:37 UTC, amitlissack commented on notify-server/notify_server/clients/serdes.py
> +"""Implementation of the QueueEntry class."""
Arghhh

2020-12-30 15:55 UTC, SyntaxColoring commented on notify-server/notify_server/clients/publisher.py
>      def send_nowait(self, topic: str, event: Event) -> Future[Any]:
Makes sense.

Note that this makes the semantics slightly different between async code and non-async code, though. Async code can optionally wait until ["sending is complete"](https://pyzmq.readthedocs.io/en/latest/api/zmq.asyncio.html#socket:~:text=message.-,Returns%20a%20Future%20that%20resolves%20when%20sending%20is%20complete.), while non-async code can't.

This isn't necessarily a problem—just making sure it's intentional.

2020-12-30 15:59 UTC, SyntaxColoring commented on notify-server/notify_server/network/connection.py
> +    def send_multipart(self, frames: List[bytes]) -> Future[Any]:
Oh interesting. So `send_multipart()` will begin sending the message even before it's `await`ed.

Hmmm. So, `send_multipart()` returns a `Future`, but it seems like `Future`s are [always bound](https://docs.python.org/3/library/asyncio-future.html#asyncio.Future.get_loop) to `asyncio`event loops. Which might mean that it needs to be called with an event loop running, anyway?

2020-12-30 17:38 UTC, amitlissack commented on notify-server/notify_server/clients/publisher.py
>      def send_nowait(self, topic: str, event: Event) -> Future[Any]:
Yes, of course. You are right. And I believe that it is clear. In the previous iteration the result you waited for was the queueing. It was not possible to wait for the message to be sent.

2020-12-30 17:43 UTC, amitlissack commented on notify-server/notify_server/network/connection.py
> +    def send_multipart(self, frames: List[bytes]) -> Future[Any]:
`send` and `send_nowait` must be called from a thread with a running loop. In fact, the `Producer` creation must happen in a thread with a running loop. 

That is actually the root issue that led to this PR and its aborted changes. (This is truly a misguided holiday-time PR). The `get_event_publisher` dependency is not marked `async`. FastApi calls non `async` dependencies in a `ThreadPoolExecutor` (in a thread without an event loop).  That is why I made the `create` method `async` back then (remember when I didn't know why when we were chatting?).

The point is that this PR took a different turn and became about simplification of consumers.

2020-12-31 21:36 UTC, SyntaxColoring commented on notify-server/notify_server/network/connection.py
> +    def send_multipart(self, frames: List[bytes]) -> Future[Any]:
Hm, I think I'm lost.

In the above thread, [you said](https://github.com/Opentrons/opentrons/pull/7152#discussion_r550235187) that `send()` and `send_nowait()` were *both* needed because we need to support async callers as well as sync callers.

But here, you're saying "`send` and `send_nowait` must [both] be called from a thread with a running loop"? Doesn't that imply they both only support async callers?

2021-01-04 14:10 UTC, amitlissack commented on notify-server/notify_server/network/connection.py
> +    def send_multipart(self, frames: List[bytes]) -> Future[Any]:
We can talk about this later. I think there's some semantics confusion going on. 

In the mean time. I am closing this PR. It's misguided and dumb.

2021-01-04 14:10 UTC, amitlissack commented
Closing this PR. There's nothing good about it.

2021-01-04 14:10 UTC, closed without merging