refactor(robot-server): Version checking is changed from opt-out to opt-in
OpenTrons/opentrons-api pull request #7178
Opened 2021-01-05 19:41 UTC by amitlissack

# Overview

`Opentrons-Version` required header is not documented in the OpenAPI spec.  This causes the version checking middleware to make the /api interactive GUI unusable. 

closes #7171

# Changelog

The middleware will no longer check the version but only populate response header. Header validation will happen in a dependency (fastapi Depends) check_version_header which is added to the routers that require version checking.

# Review requests

This is the cleanest way I could think of solving this issue.  Is it too cumbersome? While the `Depends(check_version_header)` is sprinkled throughout the legacy API, it's a single entry for all of our newer API.

# Risk assessment

Medium. While this affects every API, the tests are thorough.

2021-01-06 22:45 UTC, SyntaxColoring requested changes
Left some code feedback, but I'm also not sure I fully understand #7171.

If the interactive UI broke because our required headers were missing from our OpenAPI spec, shouldn't we fix that by making headers part of our OpenAPI spec?

2021-01-06 22:45 UTC, SyntaxColoring commented on robot-server/robot_server/service/dependencies.py
> +        constants.API_VERSION
I think we use `header_value` and `opentrons_version` interchangeably here? For readability, we should just have one or the other.

```suggestion
    requested_version = (
        int(opentrons_version)
        if opentrons_version != constants.API_VERSION_LATEST else
        constants.API_VERSION
```

or

```suggestion
    header_value = opentrons_version
    requested_version = (
        int(header_value)
        if header_value != constants.API_VERSION_LATEST else
        constants.API_VERSION
```

2021-01-06 22:45 UTC, SyntaxColoring commented on robot-server/robot_server/service/legacy/routers/__init__.py
> +                                           Depends(check_version_header)])
Duplicate `Depends(check_version_header)`?

2021-01-06 22:45 UTC, SyntaxColoring commented on robot-server/robot_server/service/legacy/routers/__init__.py
> +                                           Depends(check_version_header)])
Another duplicate `Depends(check_version_header)`.

2021-01-07 02:27 UTC, amitlissack commented
> Left some code feedback, but I'm also not sure I fully understand #7171.
> 
> If the interactive UI broke because our required headers were missing from our OpenAPI spec, shouldn't we fix that by making headers part of our OpenAPI spec?

That's exactly what this PR does.

2021-01-07 15:27 UTC, SyntaxColoring commented
> > Left some code feedback, but I'm also not sure I fully understand #7171.
> > If the interactive UI broke because our required headers were missing from our OpenAPI spec, shouldn't we fix that by making headers part of our OpenAPI spec?
> 
> That's exactly what this PR does.
> 
> FastApi generates the OpenAPI spec from inspecting the HTTP request handler functions supplied to the routers. Using middleware to check the version works just fine, but it bypasses FastAPI's tools for documenting and validating headers.

*Oh,* that makes more sense. I forgot FastApi generates the OpenAPI spec; I thought it was somehow the other way around. Thanks for explaining

So then is it correct to say that this PR does two things?

1. Correct the OpenAPI spec so that it mentions our `Opentrons-Version` headers.
2. Change the OpenAPI spec so that the `Opentrons-Version` headers are optional, instead of mandatory.

Where only (1) would strictly be required to get the interactive UI working again?

2021-01-07 15:38 UTC, amitlissack commented
> > > Left some code feedback, but I'm also not sure I fully understand #7171.
> > > If the interactive UI broke because our required headers were missing from our OpenAPI spec, shouldn't we fix that by making headers part of our OpenAPI spec?
> > 
> > 
> > That's exactly what this PR does.
> > FastApi generates the OpenAPI spec from inspecting the HTTP request handler functions supplied to the routers. Using middleware to check the version works just fine, but it bypasses FastAPI's tools for documenting and validating headers.
> 
> _Oh,_ that makes more sense. I forgot FastApi generates the OpenAPI spec; I thought it was somehow the other way around. Thanks for explaining.
> 
> So then is it correct to say that this PR does two things?
> 
> 1. Correct the OpenAPI spec so that it mentions our `Opentrons-Version` headers.
> 2. Change the OpenAPI spec so that the `Opentrons-Version` headers are optional, instead of mandatory.
> 
> Where only (1) would strictly be required to get the interactive UI working again?

1. Correct. This is all that is required to make UI work again. 
2. Not quite. `Opentrons-Version` was optional for a select set of paths that we analysing in the middleware. 

Another thing is that we let FastAPI validate the opentrons-version header for us. It can only be "*" or an integer.

2021-01-07 16:54 UTC, sanni-t approved these changes
Neat!

2021-01-07 17:49 UTC, amitlissack commented on robot-server/robot_server/service/dependencies.py
> +        constants.API_VERSION
Done

2021-01-07 18:27 UTC, mcous approved these changes
Much nicer, thanks for taking care of this

2021-01-07 20:01 UTC, SyntaxColoring approved these changes
Code changes from my prior feedback LGTM, thanks. 👍

2021-01-07 20:05 UTC, merged

2021-01-26 17:32 UTC, JamesRH commented
Could you please update the documentation about the camera to reflect this change: https://support.opentrons.com/en/articles/2831465-using-the-ot-2-s-camera

This worked for me using `curl 7.71.1 (x86_64-pc-win32)` 

    curl "http://X.X.X.X:31950/camera/picture" -X POST -H "Opentrons-Version:2" -o tmp.jpg

2021-01-26 23:06 UTC, SyntaxColoring commented
@JamesRH Thanks for reporting that. It should be updated now. 🙂

2021-01-28 00:48 UTC, JamesRH commented
Great. I'd suggest putting in the curl command in the documentation:

    curl "http://X.X.X.X:31950/camera/picture" -X POST -H "Opentrons-Version:2" -o tmp.jpg

and maybe even a code example that will display the image in a Jupyter notebook:

```python
!curl "http://X.X.X.X:31950/camera/picture" -X POST -H "Opentrons-Version:2" -o tmp.jpg
from IPython.display import Image
Image(jpg.name)
```

Or in pure python with only libraries on the OT-2:

```python
def deckcam(ip):
    from IPython.display import Image
    from urllib.request import Request, urlopen

    req = Request(url='http://'+ip+':31950/camera/picture', 
                  headers={'Opentrons-Version':'2'}, 
                  method='POST')
    img = urlopen(req).read()
    return Image(img)
 
#for running on Jupyter notebook on computer you connect to the OT-2 from, use IP of the OT-2 (replace X.X.X.X)
deckcam('X.X.X.X.X')

#for running on OT-2 hosted Jupyter notebook
deckcam('localhost')
```

If the PIL library was running on the OT-2, I have code that rotates the image and optionally saves the file. Let me know if there is interest in incorporating that in to the codebase.