refactor(api): add back private members used in protocol development
OpenTrons/opentrons-api pull request #7185
Opened 2021-01-06 22:37 UTC by Laura-Danielle

# Overview

This PR adds back in private members, and adds public counterparts, used in protocol development by our customer facing teams. If I missed anything, please let me know.

Moving forward @ncdiehl11 and @chazmanc, the software team has created [this coda doc](https://coda.io/d/Workaround-Request-from-Apps-eng_deCLqWp5mMx/Known-Recommended-Workarounds_suQaU#_luDDj) for us to reference either 1. workarounds we've given you and/or 2. feature requests from the apps eng team to make protocol development easier. We want to make sure we are not breaking future protocols!

# Changelog

- Added well parameters back in on the `Well` class. The private members are explicitly not versioned.
- Added docs around the above
- Added in a private member for hardware manager access in the protocol context.

# Review requests

Check if I should add other things. If you have arguments _against_ back in certain things, please leave a comment below. 

# Risk assessment

Low. Adding back in previously existing behavior.

2021-01-06 23:08 UTC, amitlissack requested changes
I am quite opposed to adding the private member properties. Our contract is the public methods of the protocol API. Everything else is private implementation details.

2021-01-06 23:09 UTC, amitlissack requested changes

2021-01-06 23:09 UTC, amitlissack commented on api/src/opentrons/protocol_api/protocol_context.py
> +    def _hw_manager(self):
If you want access to hardware manager, add a public accessor called `hardware_manager`.

2021-01-06 23:15 UTC, Laura-Danielle commented
I agree with you when a _customer_ finds a random private member that they want to use. However, because we never had public members for some of these things (i.e. the hardware manager etc) then we started sending off protocols to customers that accessed private members.

We could argue that 4.0.0 is a major version bump, and therefore it's no longer our responsibility to maintain them, but I do feel a bit icky doing that. The breaking change was meant to be that API v1 was no longer available, not that customer's protocols would break in API V2 and there was no version control in that sense.

@ncdiehl11 or @chazmanc would you mind weighing in on how often the well parameters/hardware manager is used and sent to customers?

2021-01-06 23:16 UTC, SyntaxColoring commented on api/docs/v2/new_labware.rst
> +The diameter of a given well, which is only relevant for labware with circular wells.
Can we specify what happens when the well *isn't* circular? Is this `0`? `None`? Some other random value? Does the function raise an exception? Invoke undefined behavior?

Ditto for `length` and `width`.

2021-01-06 23:16 UTC, SyntaxColoring commented on api/docs/v2/new_labware.rst
> +The depth of a given well
I think we should:

* Specify that units are in mm.
* Use the opportunity to elaborate a little on what "depth" means.

> The distance, in mm, between the very top of the well and the very bottom.
  
Or something. This would clarify what `depth` means for non-flat well bottoms, for example.

2021-01-06 23:16 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/labware.py
> +        return self.depth
Would it be worth adding comments like this?

```suggestion
    # Preserved for compatibility with workarounds used by Applications Engineering.
    @property
    def _depth(self) -> float:
        MODULE_LOG.warning("This attribute is deprecated."
                           "Please use 'depth' instead.")
        return self.depth
```

Otherwise, I worry we won't know why it's deprecated and what needs to happen before we can safely remove it.

2021-01-06 23:20 UTC, amitlissack commented
> @amitlissack I agree with you when a _customer_ finds a random private member that they want to use. However, because we never had public members for some of these things (i.e. the hardware manager etc) then we started sending off protocols to customers that accessed private members.
> 
> We could argue that 4.0.0 is a major version bump, and therefore it's no longer our responsibility to maintain them, but I do feel a bit icky doing that. The breaking change was meant to be that API v1 was no longer available, not that customer's protocols would break in API V2 and there was no version control in that sense.
> 
> @ncdiehl11 or @chazmanc would you mind weighing in on how often the well parameters/hardware manager is used and sent to customers?

A reasonable compromise to me, if I'm alone in thinking that supporting all private members from the past is a bad idea, seems to mark these `_` prefixed properties as targeted for deprecation in an immediate version of the API. And creating a ticket to remove them. 

So the warning isn't just "deprecated", but "will be removed in version 4.2".

2021-01-06 23:41 UTC, SyntaxColoring commented
So, I think there's a few questions here.

1. Can we preserve these private methods perpetually?
   1. Certainly, we *must* let them break *at some point.*
   2. Is it appropriate for us to let them break *today?* @amitlissack seems to think yes; @Laura-Danielle seems to think no; I don't have an informed opinion.
2. If we decide that we're preserving these private methods today, how do we do that robustly?
   1. In my opinion:
       1. We specify, document, and test them as if they were public methods. We leave source comments so that it's glaringly obvious to anyone working on that code that they need to be preserved.
       2. In general, we *commit* to our decision to support them for however long we've decided. No "best effort" support, or supporting them only until a refactor is inconvenienced by them. That's too wishy-washy.

-----

@amitlissack:
> A reasonable compromise to me, if I'm alone in thinking that supporting all private members from the past is a bad idea, seems to mark these `_` prefixed properties as targeted for deprecation in an immediate version of the API. And creating a ticket to remove them.
> 
> So the warning isn't just "deprecated", but "will be removed in version 4.2".

With any kind of scheduled deprecation, we should keep in mind that the Opentrons App's can't surface Python warnings to the user. Unless we fix that, we'll always risk customers who are happily running their Opentrons-written protocols someday running into surprise breakage, no matter how long we give them to get their protocols fixed.

2021-01-07 14:39 UTC, sfoster1 requested changes
I think we're overthinking this a bit (but I would like to see a couple small changes). We have a robust mechanism for enforcing changes in the protocol API and surfacing problems: the API version. The [versioning documentation](https://docs.opentrons.com/v2/versioning.html) explicitly _does not_ call out removal of things from the protocol api as requiring a major version bump; only large structural changes, which this is not.

Here is what I think we should do:
- Add the new public accessors under a new API version, 2.9
- Add the private accessors back and retroactively tag them as available from API version 2.0. Implement them _in parallel_ as top level accessors, rather than having the public accessors depend on the private ones.
- Add a way to remove things in API versions that raises an error that says "this was removed in api version xx" and mark the private methods as removed in API version 2.9
- We commit to supporting the private method accessors in the same terms as anything else: they are supported in API levels 2.8 and under. As long as API level 2.8 and under is supported by the robot software, the private method accessors will be supported. 

This is definitely an unfortunate place to find ourselves in! But we can't retroactively break protocols (more than we already have). The way forward to avoid this in the future is to keep records of workarounds that we have given to customers and aggressively prioritize making public methods for those customers.

So, the specific changes I'd like to see here are the addition of a "removed-in" marker with appropriate errors, and the addition of added-in and the new removed-in marker to the private properties.

2021-01-07 15:29 UTC, amitlissack commented
> I think we're overthinking this a bit (but I would like to see a couple small changes). We have a robust mechanism for enforcing changes in the protocol API and surfacing problems: the API version. The [versioning documentation](https://docs.opentrons.com/v2/versioning.html) explicitly _does not_ call out removal of things from the protocol api as requiring a major version bump; only large structural changes, which this is not.
> 
> Here is what I think we should do:
> 
> * Add the new public accessors under a new API version, 2.9
> * Add the private accessors back and retroactively tag them as available from API version 2.0. Implement them _in parallel_ as top level accessors, rather than having the public accessors depend on the private ones.
> * Add a way to remove things in API versions that raises an error that says "this was removed in api version xx" and mark the private methods as removed in API version 2.9
> * We commit to supporting the private method accessors in the same terms as anything else: they are supported in API levels 2.8 and under. As long as API level 2.8 and under is supported by the robot software, the private method accessors will be supported.
> 
> This is definitely an unfortunate place to find ourselves in! But we can't retroactively break protocols (more than we already have). The way forward to avoid this in the future is to keep records of workarounds that we have given to customers and aggressively prioritize making public methods for those customers.
> 
> So, the specific changes I'd like to see here are the addition of a "removed-in" marker with appropriate errors, and the addition of added-in and the new removed-in marker to the private properties.

I would like to understand where the line stops. If we declare that removing `_hw_manager` from `ProtocolContext` is a breaking change, what does that mean for the members of `API` class? Is changing any of those now a breaking change too?

Would also like to understand how we communicate these workarounds to customers. What promises are made? What are expectations?

My expectation is that I'm on my own if I use some class in some library that has a member called `_hw_manager`.

I'll be sad, but will accept @sfoster1 's solution if this is the last time this kind of thing happens.

2021-01-07 16:00 UTC, SyntaxColoring commented
> I would like to understand where the line stops....
> [...]
> My expectation is that I'm on my own if I use some class in some library that has a member called _hw_manager.

Possibly, the criteria should be:

* Were protocols with the unsupported method written by *Opentrons Applications Engineering*?
* And, are those protocols used by *customers who don't know Python?*

If you're an Opentrons customer who knows Python and writes your own Python Protocol API protocols, yes, you should be on your own. You should understand the implications of using underscore-prefixed names.

On the other hand, if you're a customer who doesn't know Python—who's blindly using files written for you by Opentrons Applications Engineering—we can't expect you to know, understand, or care about this stuff.

2021-01-07 17:50 UTC, ncdiehl11 approved these changes

2021-01-07 18:03 UTC, Laura-Danielle commented
From a F2F meeting, the following was decided:

1. Keep `_hw_manager` as a private member in protocol context
2. Remove remaining private members, but add public versions for API version 2.9.
3. Create a separate PR to throw an error when a member is removed in a certain version.

2021-01-07 18:48 UTC, chazmanc approved these changes
lgtm

2021-01-08 01:33 UTC, amitlissack approved these changes
Thanks!

2021-01-08 14:08 UTC, sfoster1 requested changes
Need to add an entry for 2.9 and the additional props in versioning.rst

2021-01-08 16:13 UTC, sfoster1 approved these changes
Nice!

2021-01-08 16:34 UTC, merged