feat(protocol-designer): Add multiselect mode UI
OpenTrons/opentrons-api pull request #7211
Opened 2021-01-11 19:47 UTC by Kadee80

# Overview

This PR closes #7104 and addresses the tool-tip section of #7105

# Changelog

- Break out TitlesStepItem (remove dependency on complib TitledList)
- Add multislect toolbar
- Add multiselect toolbox(s)
- Add new icons to component library

# Review requests

Still a WIP but please take a look at the code and sanity check it.

# Risk assessment

Low, PD only under FF. Please make sure single select step items are unaffected

2021-01-11 21:21 UTC, IanLondon reviewed
not sure what's WIP vs non-WIP but looks good so far

2021-01-11 21:21 UTC, IanLondon commented on protocol-designer/src/components/lists/TitledStepList.js
> +export type TitledListProps = {|
`TitledStepListProps or just Props?

2021-01-11 21:21 UTC, IanLondon commented on protocol-designer/src/components/steplist/MultiSelectToolbar/index.js
> +export const MultiSelectToolbar = (): React.Node => {
weird Q: is JS doing some kind of hoisting? The const `MultiSelectToolbar` is getting defined in the file before eg `SelectAllIcon` is defined

2021-01-11 21:26 UTC, Kadee80 commented on protocol-designer/src/components/lists/TitledStepList.js
> +export type TitledListProps = {|
oh copy pasta. will change

2021-01-11 21:26 UTC, Kadee80 commented on protocol-designer/src/components/steplist/MultiSelectToolbar/index.js
> +export const MultiSelectToolbar = (): React.Node => {
yup hoisting! doesd that feel yucky? also i feel like these icons can be consolidated with props etc, maybe in their own file?

2021-01-12 04:35 UTC, shlokamin commented on protocol-designer/src/components/lists/TitledStepList.js
> +import { type IconName, Icon } from '@opentrons/components'
types after styles 🤪

2021-01-12 04:35 UTC, shlokamin commented on protocol-designer/src/components/lists/TitledStepList.js
> +  )
What does this do? 🤔

2021-01-12 04:35 UTC, shlokamin commented on protocol-designer/src/components/lists/styles.css
> +  min-height: 3.5rem;
idk what our current practices are re: style constants, but should we be using constants for this sort of stuff? i.e. `min-height: HEIGHT_MEDIUM` or somethin?

2021-01-12 04:35 UTC, shlokamin commented on protocol-designer/src/components/steplist/MultiSelectToolbar/index.js
> +export const MultiSelectToolbar = (): React.Node => {
I am confused by this... I thought [function expressions do not get hoisted](https://developer.mozilla.org/en-US/docs/web/JavaScript/Reference/Operators/function#function_expression_hoisting)...

2021-01-12 04:35 UTC, shlokamin commented on protocol-designer/src/components/steplist/MultiSelectToolbar/styles.css
> +  padding: 0 0.75rem;
same q: re: stying constants in this file

2021-01-12 14:38 UTC, shlokamin commented
Oh, can we throw in some unit tests too? might also help sus out what's necessary and what isn't

2021-01-12 15:43 UTC, Kadee80 commented on protocol-designer/src/components/steplist/MultiSelectToolbar/index.js
> +export const MultiSelectToolbar = (): React.Node => {
gonna refactor the toolbar to use the new primitives and fix this

2021-01-12 15:44 UTC, Kadee80 commented on protocol-designer/src/components/lists/TitledStepList.js
> +  )
this was ported from `TitledList` i think we were having issues with invalid children (not LIs) Mike had a todo note about enforcing <li> only for children

2021-01-12 15:45 UTC, Kadee80 commented on protocol-designer/src/components/lists/styles.css
> +  min-height: 3.5rem;
`HEIGHT_MEDIUM` are the js constants when we use primitives, not in style sheets. Leaving the `TitledStepItem` styles as css modules since there are oh so many conditional styles.

2021-01-12 15:45 UTC, Kadee80 commented on protocol-designer/src/components/steplist/MultiSelectToolbar/styles.css
> +  padding: 0 0.75rem;
Going to refactor these guys and use the new primitives, so yes i'll use the new styling constants

2021-01-19 14:55 UTC, shlokamin requested changes
Looks good! can we add some tests around `MultiSelectToolbar`? I know the component is really just a small facilitator but I think it would at the very least provide some nice documentation to developers + some safety in the event icon names or whatever get changed. 

Same deal with `StepList`, would be nice to just add a small test saying that when in multi select mode the `MultiSelectToolbar` gets rendered. I'd rather not rely on e2e tests for that since there isn't really a need to do it so high up, and cuz I'm worried that would be flakey and cause us more headaches.

I also left a small flow nitpick 🙃

2021-01-19 14:55 UTC, shlokamin commented on protocol-designer/src/components/lists/TitledStepList.js
> +  children?: React.Node,
if we're going to say that all children must be `li` elements, can we enforce that with flow? could really save us debugging time down the line if it's more explicit. maybe something like 

```js
React.Element<'li'> //or
React.ChildrenArray<React.Element<'li'>>
```

https://flow.org/en/docs/react/children/#toc-only-allowing-a-specific-element-type-as-children

2021-01-19 16:27 UTC, shlokamin commented
Just so stuff doesn't get blocked, im gonna address my comments and merge this so we can continue on with https://github.com/Opentrons/opentrons/issues/7105

2021-01-20 02:08 UTC, shlokamin commented on protocol-designer/src/components/lists/TitledStepList.js
> +  children?: React.Node,
So I spent quite a bit of time trying to type this more strictly, but unfortunately given the way we compose each of the dependent components that consist of `li` elements, enforcing type checking with flow will not work. Ex, if an `li` is wrapped inside a `React.Fragment` (which we do in a few different places) flow will raise errors.

2021-01-20 02:09 UTC, shlokamin approved these changes

2021-01-20 02:22 UTC, merged