feat(protocol-designer): add selector to get batch edit disabled fields
OpenTrons/opentrons-api pull request #7223
Opened 2021-01-14 20:19 UTC by shlokamin

# Overview

This PR adds a selector to get batch edit disabled fields, along with the reason why they are disabled.

Note: I included dependent fields to checkboxes in this selector (ex. if `aspirate_mix_checkbox` is disabled, it will also return that `aspirate_mix_volume` and `aspirate_mix_times` are also disabled). If this is unnecessary it's an easy fix to remove that. I guess it all depends on how we wanna consume this selector in the UI.

closes #7193

# Changelog

- Add selector to get batch edit disabled fields

# Review requests
Code review (including tests)

# Risk assessment
Low, well tested and not being used yet

2021-01-14 20:47 UTC, shlokamin commented on protocol-designer/src/ui/steps/selectors.js
> +    )
might be having a bit too much fun here with `reduce`... but figured it's better than doing a bunch of redundant `array.some` loops, thereby unnecessarily increasing time complexity. could also do a single `forEach` and reassign scoped variables but this just seemed like a cleaner way to do this.

2021-01-14 20:48 UTC, shlokamin commented on protocol-designer/src/ui/steps/selectors.js
> +      // $FlowIssue(sa, 2021-01-13): https://github.com/facebook/flow/issues/8186
Flow doesn't like this bcuz it can't type narrow this object effectively. Imo not worth the extra code appeasing Flow would require.

2021-01-20 15:14 UTC, IanLondon requested changes
I think we're missing the combo errors for the mix fields, where you can get disabled due to either different pipettes AND/OR path (multi-aspirate path for aspirate mix or multi-dispense path for dispense mix) so it's 3(?) disabled tooltips: "different pipettes", "bad path", "different pipettes and bad path".

(From the spreadsheet I'm not sure what the intended tooltips are in the case where both pipettes and path are problems)

Also this part's just a nitpick but I wonder if the i18n could be pared down since the copy we ended up on doesn't require distinct tooltips for each of the >20 fields, but only pipette/source labware/dest labware/multi-aspirate/multi-dispense = 5 and maybe 2 more for "pipette AND multi-asp path" + "pipette AND multi-disp path" if those cases get unique copy.

2021-01-20 15:14 UTC, IanLondon commented on protocol-designer/src/localization/en/tooltip.json
> +        "disabled": {
also `aspirate-pipette-different` here? And then the combo pipette+path case needs to be handled (?)

2021-01-20 15:14 UTC, IanLondon commented on protocol-designer/src/localization/en/tooltip.json
> +          "multi-aspirate": "Cannot edit while one or more selected steps uses the multi-aspirate path. Selected steps must also share the same pipette."
same comment as `aspirate_mix_checkbox`

2021-01-20 15:14 UTC, IanLondon commented on protocol-designer/src/localization/en/tooltip.json
> +          "multi-aspirate": "Cannot edit while one or more selected steps uses the multi-aspirate path. Selected steps must also share the same pipette."
same comment as `aspirate_mix_checkbox`

2021-01-20 15:14 UTC, IanLondon commented on protocol-designer/src/localization/en/tooltip.json
> +          "multi-dispense": "Cannot edit while one or more selected steps uses the multi-dispense path. Selected steps must also share the same pipette."
similar deal, `multi-pipette` (and combo multi-dispense + multi-pipette?) for all the `dispense_mix_*` fields

2021-01-20 16:42 UTC, shlokamin commented
In the mixed case (lets say for example in a `aspirate => mix` advanced setting both the pipettes are different AND the path is `multi aspirate`) only the tooltip for `path cannot be multi aspirate` will show up. This is cuz that specific error also takes into account pipettes being different: 

`"Cannot edit while one or more selected steps uses the multi-aspirate path. Selected steps must also share the same pipette."`

In the event that ONLY the pipette is different, just the `pipettes cannot be different` tooltip will show up.

I'm not sure if that is desired behavior though... I just sort of decided it to be that way since the ticket/sheet are sorta vague about that case. Let's discuss after standup!

2021-01-20 17:01 UTC, shlokamin commented
As per discussion after standup there was a misunderstanding around tooltip text and we need to compose them when multiple errors are present.  Good catch, @IanLondon!

2021-01-22 15:18 UTC, IanLondon approved these changes
:toolbox:

2021-01-27 15:43 UTC, Kadee80 approved these changes
🧫

2021-01-27 16:27 UTC, merged