Pd multi select controls functionality
OpenTrons/opentrons-api pull request #7264
Opened 2021-01-27 15:03 UTC by shlokamin

# Overview

This PR adds functionality to the multi select toolbar. Closes #7105 

# Changelog

- Add functionality to the multi select toolbar

# Review requests

Code review, including tests. There's a lot here plz make sure its simple enough to follow/makes sense.

Enter batch edit mode, and follow the test cases in [the ticket](#7105 ). It only includes select/deslect all, and expand/collapse

# Risk assessment
Low/med, not being used yet and pretty well tested.

2021-01-29 17:12 UTC, Kadee80 commented on protocol-designer/src/ui/steps/test/reducers.test.js
> +  it('should toggle multiple steps upon TOGGLE_MULTIPLE_STEPS_COLLAPSED', () => {
Isn't the desired behavior an expand all / collapse all selected, not toggle the expanded vs collapsed ones?

2021-02-01 15:35 UTC, shlokamin commented on protocol-designer/src/ui/steps/test/reducers.test.js
> +  it('should toggle multiple steps upon TOGGLE_MULTIPLE_STEPS_COLLAPSED', () => {
It is indeed! I made an action that takes in the steps to toggle as input to:
(1) be more functional and explicit
(2) not tie concerns up too much with the UI. Ex, if in the future we need to be able to toggle some but not all steps, we should be able to. 

It's kinda like right now the `selectAllSteps` action creator calls `SELECT_MULTIPLE_STEPS` under the hood. 
if it makes more sense to make a `toggleAllStepsCollapsed` action creator that calls `TOGGLE_MULTIPLE_STEPS_COLLAPSED` under the hood, instead of a `toggleMultipleStepsCollapsed` action creator that takes in a list of ids I'm also down for that.

2021-02-02 15:55 UTC, shlokamin commented on protocol-designer/src/step-forms/selectors/index.js
> +
this selector is captured here https://github.com/Opentrons/opentrons/issues/7245

2021-02-02 15:57 UTC, Kadee80 commented on protocol-designer/src/ui/steps/test/reducers.test.js
> +  it('should toggle multiple steps upon TOGGLE_MULTIPLE_STEPS_COLLAPSED', () => {
Its seems like the behavior in the UI right now toggles the open ones to closed, and the closed to open, which might not necessarily jive with the icon/tooltip in the toolbars expected behavior?

2021-02-02 15:58 UTC, shlokamin commented on protocol-designer/src/steplist/actions/actions.js
> +      nextStepId = potentialNextStepId
this whole block is rather unfortunate and hard to follow. i would love to refactor this to be more readable

2021-02-02 16:00 UTC, shlokamin commented on protocol-designer/src/ui/steps/test/reducers.test.js
> +  it('should toggle multiple steps upon TOGGLE_MULTIPLE_STEPS_COLLAPSED', () => {
Ohhhh i see what you are saying, good catch you are absolutely correct! Will fix this now, thanks for catching this

2021-02-02 16:27 UTC, IanLondon requested changes
**Select/de-select all**
- [x] There is an icon with two states that represents whether steps in the timeline are selected
- [x] This icon has the tooltip "Select All". If all are selected, tooltip should read "Deselect All"
- [x] When there are some checked steps in the timeline and some unchecked steps, the icon is in the _mixed_ state 
- [x] When icon is in _mixed_ state and it is clicked, two things happen: (1) the icon switches to _all selected_ state (2) all non-terminal steps in the timeline are selected
- [x] When all non-terminal steps in the timeline are selected the icon is in the _all selected_ state
- [ ] **(??? I'm not sure what this means. What is the lastSelected supposed to become when you do "Select All" ???** When icon is in _all selected_ state and is clicked PD attempts to exit multi select mode. When exiting multi select mode, make sure that single edit mode is entered with the `lastSelected` step being selected. Please see [figma chart ](https://www.figma.com/file/6p1uxeeioDikcfSwLCfxi4/Batch-Editing?node-id=827%3A67)for conditions as to what happens next. 

**Expand/collapse**
- [x] There is an icon/button for expand/collapse
- [x] When multi-select mode is first entered the icon is in the _expand_ state
- [x] When icon is in the _expand_ state it has a tooltip that reads "Expand"
- [x] When icon is in the _expand_ state and is clicked two things happen: (1) the icon switches to the _collapse_ state (2) all selected steps are expanded
- [x] When icon is in the _collapse_ state it has a tooltip that reads "Collapse"
- [x] Seems they just toggle, so some may collapse and others may expand** When icon is in the _collapse_ state and is clicked two things happen: (1) the icon switches to the _expand_ state (2) all selected steps are collapsed

**Delete**
- [x] There is an icon for deleting steps
- [ ] This icon has the tooltip "Delete"
- [ ] After step deletion, PD will remain in batch edit mode and have only 1 step selected
- [ ] After the deletion of steps, the next step selected is one of two cases: (1) If the step following the last deleted step is a **non terminal** item, that step is the next step selected. (2) If the step following the last deleted step is a **terminal item**, select the last non-terminal step in the protocol instead.

If all steps get deleted, exit batch edit mode with starting deck state selected

**Duplicate**
- [ ] There is an icon for duplicating steps
- [ ] This icon has the tooltip "Duplicate"
- [ ] Steps created by the duplication are contiguous, even if the initial selection wasn't
- [ ] Duplicated steps appear below the last step of the original selection.
- [ ] Only the duplicates are now selected. The original selection is not selected.

2021-02-02 17:44 UTC, Kadee80 approved these changes
💪 Thanks for fixing the toggle behavior and the tooltips!

2021-02-03 17:57 UTC, IanLondon requested changes
everything looks good other than the changes we talked about this afternoon, LMK when to re-review

2021-02-03 17:57 UTC, IanLondon commented on protocol-designer/src/steplist/actions/actions.js
> +): ThunkAction<*> => (dispatch: ThunkDispatch<*>, getState: GetState) => {
nitpick: I think type inference by `*` is deprecated/discouraged(???), uhh cannot confirm, I can't find it in the docs. But you should be able to type this fully (eg `renameLabware` thunk has `ThunkAction<CreateContainerAction | RenameLabwareAction>`). Your call though, we do a bunch of `FunkyReduxType<*>` in PD and when we go to TS the landscape might be different

2021-02-04 21:54 UTC, IanLondon approved these changes
new commits look good!

2021-02-04 23:53 UTC, merged