feat(components): Add isIndeterminate options prop to InputField
OpenTrons/opentrons-api pull request #7280
Opened 2021-02-02 17:47 UTC by Kadee80

# Overview

closes #7255

# Changelog

- Add isIndeterminate options prop to InputField
- Add tests for placeholder/value overrides

# Review requests

- [ ] Markdown example behaves as expected
- [ ] Test cases make sense

# Risk assessment

Low, optional tested prop in component library

2021-02-03 19:11 UTC, IanLondon requested changes
has key typo that weirdly happens not to break functionality in component markdown

2021-02-03 19:11 UTC, IanLondon commented on components/src/forms/InputField.md
> +  setState({ inputValue: e.target.value, isIndetermiante: false })
`isIndetermiante` typo. I got really confused why it still behaves correctly with this typo here but it's because it's just like `setState({inputValue: e.target.value, misspelledKey: 'whatever'})` will leave `state.isIndeterminate` on L75 as `undefined` because that key no longer exists in `state` :stuck_out_tongue: wow

2021-02-03 19:16 UTC, IanLondon approved these changes
swag

2021-02-04 15:23 UTC, shlokamin approved these changes

2021-02-04 17:18 UTC, merged