refactor(protocol-designer): use FieldProps interface instead of FieldcConnector wrapper
OpenTrons/opentrons-api pull request #7297
Opened 2021-02-08 17:10 UTC by IanLondon

# Overview

Closes #7217 -- instead of the hook (which caused weird zombie children stuff and overall ended up being more complicated with the StepFormManager and the step form component itself both using the same selectors)

Should NOT affect behavior of PD, should be a pure refactor.

# Changelog

- Remove all uses of deprecated `<FieldConnector>` wrapper from fields that we'll want to use in  (TODO make new ticket for removing the remainder)
- Remove unused tooltip prop functionality from the field UI components
- Refactor StepEditForm/StepEditFormManager/StepEditFormComponent to make it a little cleaner
- Update documentation .md

# Review requests

This is a big one, hopefully E2E will cover a decent amount, but since pretty much every field in every form is touched by this, it needs to be a comprehensive review of... all fields in all step form types :sob: 

- All field-level errors and warnings across all steps
- All form-level errors and warnings across all steps
- All pristinity error/warning masking behavior
- Code review, especially of `makeSingleEditField` and `StepEditFormManager / StepEditFormComponent` and of the changed UI fields and form components
- Confirm delete modals when you delete/cancel a step form that has unsaved changes

# Risk assessment

PD-only, but high. This touches a lot of stuff!

ALSO - migrations were touched because getDefaultsForStepType was missing a field in the Mix form, which was then missing from migrations (if you didn't ever check that one box, it was undefined instead of `false` in the saved form). I can't think of a way that including this field would be harmful, and I think it's safe to not count it as a "migration", but please confirm that this is indeed safe.

2021-02-08 17:12 UTC, IanLondon commented on components/src/forms/CheckboxField.js
> +  /** props passed into label div. TODO IMMEDIATELY what is the Flow type? */
I can't figure out how to tell Flow "you can put any props in here that are allowed in an HTMLDivElement". I tried a few combos (@shlokamin had some suggestions in #js) but none worked for this

2021-02-08 17:14 UTC, IanLondon commented on protocol-designer/fixtures/protocol/5/mix_5_2_0.json
> +          "mix_touchTip_checkbox": false,
this field was missing in `getDefaultsForStepType` and therefore also missing from saved files where the user never toggled this checkbox. Now that this field is included in the defaults, the result of migrations is different. I don't think there will be any negative effect from this, so I think this is a safe change, but please think through any problems that might occur

2021-02-08 17:15 UTC, IanLondon commented on protocol-designer/src/components/FileSidebar/utils/__tests__/getUnusedEntities.test.js
> +        stepType: 'moveLiquid',
`type StepType` was formerly `string` because of a bad behavior of Flow's `$Values` . Now that it's a proper enum, several Flow-typed tests needed to be updated because eg `'transfer'` is NOT a valid `StepType`

2021-02-08 17:16 UTC, IanLondon commented on protocol-designer/src/components/StepEditForm/StepEditFormComponent.js
> +export const StepEditFormComponent = (props: Props): React.Node => {
Factored out from `StepEditForm/index.js`

2021-02-08 17:18 UTC, IanLondon commented on protocol-designer/src/components/StepEditForm/fields/PathField/index.js
> +>(mapSTP, () => ({}))(Path)
without this `() => ({})` dealie-doo, Flow correctly errors because the default mapDispatchToProps that `connect` would otherwise put in will include a `dispatch` prop, and `dispatch` is not a prop that `PathField` should take. I don't remember if there's a more elegant way to disable the default DTP fn than this?

2021-02-08 17:19 UTC, IanLondon commented on protocol-designer/src/components/StepEditForm/fields/ProfileItemRows.js
> +    focusHandlers.blur(fieldId)
uniquely, the TC profile fields (because they are the only **dynamic** fields we have) use the focusHandlers directly. This is explained a little in the updated documentation .md

2021-02-08 17:21 UTC, IanLondon commented on protocol-designer/src/components/StepEditForm/fields/__tests__/DelayFields.test.js
> +        propsForFields: {
I considered making some util fn that creates mock `FieldProps` so I could do `propsForFields: { ...makeFieldPropsTestUtilThing({name: 'aspirate_delay_checkbox', value: true}), ...etc},` instead of this pretty verbose setup. But I hesitated bc it might just make these shorter, but harder to read and understand. Thoughts?

2021-02-08 17:25 UTC, IanLondon commented on protocol-designer/src/components/StepEditForm/index.js
> +const mapDispatchToProps = (dispatch: ThunkDispatch<*>): DP => {
it was weird to have StepEditFormManager use `connect` and also use `useDispatch`. It needs to use `connect` to avoid zombie children problems, so I switched it to normal STP + DTP with no hooks (instead of STP + useDispatch weird combo)

2021-02-08 17:26 UTC, IanLondon commented on protocol-designer/src/components/StepEditForm/types.js
> +  isIndeterminate?: boolean,
for `makeSingleEditFieldProps`, `isIndeterminate` will always be undefined. But for `makeBatchEditFieldProps/useBatchEditFieldProps/etc`, this will be populated and passed down into the UI components.

2021-02-08 17:26 UTC, IanLondon commented on protocol-designer/src/components/StepEditForm/types.js
> +export type StepFormProps = {|
previously, this was not typed and was very implicit! I explain this type a bit in the updated documentation .md

2021-02-08 17:27 UTC, IanLondon commented on protocol-designer/src/components/StepEditForm/utils.js
> +export const getDirtyFields = (
factored out of `StepEditForm/index.js` to make that file shorter and allow mocking

2021-02-08 17:28 UTC, IanLondon commented on protocol-designer/src/components/steplist/__tests__/StepItemContents.test.js
> +    const stepType: any = 'awaitTemperature'
IDK what's going on in this test with the stepType set to "awaitTemperature" which is definitely not a real stepType, punted it to a ticket for later #7285. Needed to any-type it in the meantime now that `StepType` is a proper enum instead of just `string` type

2021-02-08 17:30 UTC, IanLondon commented on protocol-designer/src/form-types.js
> +export type StepType =
The ` $Keys<typeof stepIconsByType>` before actually did not work and resolved to `string`!?! I had some problems with the StepEditFormComponent/StepEditFormManager due to `StepType` not actually being an enum, so I needed StepType to be the enum it was supposed to be. This caused some problems and exposed a few odd test cases that I commented on above

2021-02-08 17:32 UTC, IanLondon commented on protocol-designer/src/steplist/formLevel/getDefaultsForStepType.js
> +        times: null,
**Important** to note that I added these missing fields for `mix` forms. Otherwise, the `makeSingleEditFieldProps` would be missing entries for these fields. Adding these missing fields may be risky but should be a good thing?

2021-02-08 21:17 UTC, Kadee80 commented on protocol-designer/src/components/StepEditForm/fields/__tests__/DelayFields.test.js
> +        propsForFields: {
I'm a fan of leaving as is. It's a little longer but it's all in one place and easier to reference.

2021-02-09 19:36 UTC, shlokamin reviewed
Left a few comments but looks good! Will play around with the forms now

2021-02-09 19:36 UTC, shlokamin commented on components/src/forms/CheckboxField.js
> +  /** classes to apply to inner label text div. Deprecated. use labelProps.className */
does this mean that `className` doesn't work anymore?

2021-02-09 19:36 UTC, shlokamin commented on components/src/forms/CheckboxField.js
> +        )}
looks like `hoverTooltipHandlers` never gets used here

2021-02-09 19:36 UTC, shlokamin commented on protocol-designer/fixtures/protocol/5/mix_5_2_0.json
> +          "mix_touchTip_checkbox": false,
Oh shoot, did we just forget to include this? I can't think of any weird ramifications but i think it's worth talking through real quick, it's been a while since I've thought about this.

2021-02-09 19:36 UTC, shlokamin commented on protocol-designer/src/components/StepEditForm/fields/PathField/index.js
> +>(mapSTP, () => ({}))(Path)
wtf, i've been playing with this and can't seem to figure it out... how is there no way to disable DTP???

2021-02-09 19:36 UTC, shlokamin commented on protocol-designer/src/components/StepEditForm/fields/RadioGroupField.js
> +    disabled, // NOTE: not used
if not used why pull it out of props?

2021-02-09 19:55 UTC, shlokamin requested changes
transfer => disposal volume and transfer => blowout tooltips aren't showing up. 

everything else seems to be working in the transfer + mix + pause forms

2021-02-09 21:11 UTC, shlokamin approved these changes
heck ya, great stuff @IanLondon. Really appreciate your heavy lifting on this, this was a monster task

2021-02-09 21:11 UTC, Kadee80 approved these changes
🎣

2021-02-09 21:11 UTC, IanLondon commented on protocol-designer/src/components/StepEditForm/fields/RadioGroupField.js
> +    disabled, // NOTE: not used
so that it's excluded from `...radioGroupProps`

2021-02-09 21:18 UTC, IanLondon commented on components/src/forms/CheckboxField.js
> +        )}
good point. Punting to #7307 (should be trivial though)

2021-02-09 21:20 UTC, IanLondon commented on components/src/forms/CheckboxField.js
> +  /** classes to apply to inner label text div. Deprecated. use labelProps.className */
it's just weird. The `className` prop is applied to the `label` element that wraps the content of CheckboxField, but usually we want to style the div inside that holds the text you actually see as the label

2021-02-09 21:27 UTC, merged