feat(api): Add physical USB Port information to the hardware controller
OpenTrons/opentrons-api pull request #7359
Opened 2021-02-18 23:53 UTC by Laura-Danielle

# Overview

Closes #7196. This PR reads/interprets the physical USB port information found in sys/bus. There are typically two formats for the usb port id:
1. No Hub: `<bus id>.<port>`
2. USB Hub: `<bus id>.<hub>.<port>`

# Changelog

- Created a driver to read from the sys bus path
- Created a module for common algorithms and added a generic depth first search
- Add a USBPort dataclass to the build method of each module
- Add tests for the above, fix any other tests

# Review requests

Please test on your robot. You can do so by:
1. Plugging/unplugging multiple modules into the robot. Check that regular functionality remains the same such as running protocols/controlling protocols.

# Risk assessment

Medium, adding new functionality to the hardware controller

2021-02-19 13:56 UTC, amitlissack reviewed
Really nicely written pull request! 

Not sure I'm requesting any changes. Just have a lot of questions.

2021-02-19 13:56 UTC, amitlissack commented on api/src/opentrons/algorithms/dfs.py
> +    def dfs(self) -> Set[VertexName]:
I'm curious. Why did you choose to make this functionality in a class rather than a function `dfs` that takes a `Graph` as input and returns a set?

Why would someone construct this and call `dfs` more than once?

2021-02-19 13:56 UTC, amitlissack commented on api/src/opentrons/drivers/rpi_drivers/types.py
> +    def find_hub(
Could this function return a `USBPort` object? Or am I misunderstanding.

2021-02-19 13:56 UTC, amitlissack commented on api/src/opentrons/drivers/rpi_drivers/types.py
> +            if node not in port_nodes:
I don't how long the split `full_name` can realistically be but this is a linear search and could be slow.

2021-02-19 13:56 UTC, amitlissack commented on api/src/opentrons/drivers/rpi_drivers/usb.py
> +        :returns: The matching port, or an empty port dataclass
What is the reason to return an empty `USBPort` rather than `None`?

2021-02-19 13:56 UTC, amitlissack commented on api/src/opentrons/drivers/rpi_drivers/usb_simulator.py
> +class USBBusSimulator:
Yay for simulator! 

I would be pretty happy if this and `USBBus` derived from some common interface. Or `USBBusSimulator` could be renamed and become the base class of `USBBus`. 

My rationale is that it will help keep the simulator and real class consistent.

2021-02-19 13:56 UTC, amitlissack commented on api/src/opentrons/drivers/rpi_drivers/usb_simulator.py
> +        pass
Should this return some dummy value?

2021-02-19 13:56 UTC, amitlissack commented on api/src/opentrons/drivers/rpi_drivers/usb_simulator.py
> +        pass
Should this return an empty list?

2021-02-19 13:56 UTC, amitlissack commented on api/src/opentrons/drivers/rpi_drivers/usb_simulator.py
> +        pass
Return an empty list?

2021-02-19 13:56 UTC, amitlissack commented on api/tests/opentrons/algorithms/test_dfs.py
> +@pytest.fixture(params=load_graph())
could the `scope` be `session`? I believe that otherwise `load_graph` will needlessly be called many times.

2021-02-19 13:56 UTC, amitlissack commented on api/src/opentrons/hardware_control/modules/utils.py
> +# NOTE: Must import all modules so6hey actually create the subclasses
spelling?

2021-02-19 15:31 UTC, sfoster1 commented on api/src/opentrons/drivers/rpi_drivers/types.py
> +            if node not in port_nodes:
A single bus can support up to 127 devices (including hubs) so that's the max length.

2021-02-19 15:39 UTC, sfoster1 requested changes
Definitely agree with Amit's points; in particular, the simulator concrete methods all need to return the type they say they return, can't just `pass` if that method is supposed to actually return a value.

I also think that the DFS stuff probably does want to be stateless.

This all looks really good though, very impressive.

2021-02-23 15:45 UTC, sfoster1 requested changes
Couple things about the structure of the depth-first sort. Also it's really a depth-first sort of a tree, not a depth-first search, right? There's nothing you're searching for.

2021-02-23 15:45 UTC, sfoster1 commented on api/src/opentrons/protocols/implementations/protocol_context.py
> +                    usb_port=self._hw_manager.hardware._backend._usb.find_port(''),
This is a layering violation - the protocol layer should never have to dive down to the `_backend`.

What if instead we added a method to the hardware controller like this:

```
def find_modules(self, by_model: str -> List[SynchronousAdapter]: ...
```
or ideally have a hardware-control level enum for models. 
That can then be passed down to the backend if necessary, and ideally do a filter on `attached_modules` if we're not simulating. If we are simulating, it can build the appropriate dummy module, in the same way that `cache_instruments` does.

This might be a lot for this pr, but if we want to do it in a follow up a) let's comment it here b) let's do that follow up.

2021-02-23 15:45 UTC, sfoster1 commented on api/src/opentrons/algorithms/dfs.py
> +    def dfs(self) -> Set[VertexName]:
Yeah the way the search state is cached in an instance variable is worrying, to me. Having to remember to call `.reset()` every time is a source of bugs; invariants like "i have been reset" should really be enforced by language mechanisms if at all possible, which it is here, by removing them. The DFS class could stay a class since it'll be handy to bundle up the graph; but I think `_current_vertex` and `_visited_vertices` should not be instance or class variables. Python has lexical scoping; let's use it by moving the definition of `_dfs` into the definition of `dfs`, and making `current_vertex` and `visited_vertices` local variables in `dfs` which are closed over by the definition of `_dfs`.

If you do that, the job of the `DFS` class changes to "have a handle on the `Graph` object so you don't have to store it separately", and it is no longer stateful other than that, which is a lot easier to handle.

If you don't want to use lexical scoping and closures, you can also keep the `_dfs` definition separate and have `current_vertex` and `visited_vertex` be parameters that it passes along in the recursion case.

Finally, remember that python has a recursion limit (of 1000, by default, and customizable with `sys.setrecursionlimit`), and it has it for a reason: the interpreter doesn't do TCO. This is not a problem that's likely to arise in practice, because the only way to get recursion that deep would be to physically chain 124 hubs or so in between the raspberry pi and the module, but it may be worth considering reframing this as an iteration.

2021-02-23 15:45 UTC, sfoster1 commented on api/src/opentrons/algorithms/graph.py
> +            sort_by: Callable) -> None:
Can we get further parametrization on `Callable`? it should be `Callable[[VertexLike], VertexName]` right?

2021-02-23 15:45 UTC, sfoster1 commented on api/src/opentrons/algorithms/graph.py
> +            sorted_graph.sort(key=sort_by)
sorting on every append makes this function's time complexity `O(N*O(sort))`. We should add all the vertices and then do one sort at the end.

2021-02-23 15:45 UTC, sfoster1 commented on api/src/opentrons/algorithms/graph.py
> +        del self._lookup_table[vertex.name]
this will cause a `KeyError` if you delete a non-existent vertex. That may be fine, but it doesn't match the behavior of `add_vertex`, which silently does nothing if you add a vertex that already exists.

2021-03-11 16:30 UTC, Laura-Danielle commented on api/src/opentrons/protocols/implementations/protocol_context.py
> +                    usb_port=self._hw_manager.hardware._backend._usb.find_port(''),
I will be addressing this in the protocol context PR (I felt like it fit better). I left the code here the same since that branch is based off this other branch. I will be posting that PR shortly.

2021-03-11 21:17 UTC, sfoster1 approved these changes
LGTM modulo the changes in the second PR.

2021-03-11 21:20 UTC, merged