feat(protocol-designer): Add test coverage to StepCreationButton
OpenTrons/opentrons-api pull request #7400
Opened 2021-03-01 18:04 UTC by Kadee80

# Overview

This PR closes #7355 by adding missing tests to the `StepCreationButton`

# Changelog

- feat(protocol-designer): Add test coverage to StepCreationButton

# Review requests

code review

# Risk assessment

Low. PD single component test coverage only

2021-03-01 19:01 UTC, shlokamin requested changes
Looks good! I don't think we should be mocking internals like `useState` though bcuz that's really getting into implementation details of React, and doing so doesn't gain us much confidence in the component's behavior. But based on the looks of it if you delete the lines where you mock `useState` your tests should pass as is!

2021-03-01 19:01 UTC, shlokamin commented on protocol-designer/src/components/__tests__/StepCreationButton.test.js
> +
how come you have to mock `useState` here? we should probs leave internals like these as is

2021-03-01 19:04 UTC, Kadee80 commented on protocol-designer/src/components/__tests__/StepCreationButton.test.js
> +
Good catch. Removing

2021-03-01 21:40 UTC, shlokamin approved these changes

2021-03-02 16:54 UTC, IanLondon approved these changes

2021-03-02 16:54 UTC, IanLondon commented on protocol-designer/src/components/__tests__/StepCreationButton.test.js
> +        button.simulate('click')
`simulate` is apparently bad? And we should do `button.invoke('onClick')()` instead?? But who knows. See discussion in #js slack channel :sob:

2021-03-02 17:23 UTC, merged