feat(update-server): Add bootId field to GET /server/update/health
OpenTrons/opentrons-api pull request #7404
Opened 2021-03-01 21:17 UTC by SyntaxColoring

# Overview

As part of fixing #6585, we want the OT-2 to expose a *boot ID* over HTTP. When the boot ID changes, you know the OT-2 has restarted. This PR implements the back-end half of that.

# Changelog

* Added `bootId` to `GET /server/update/health`, one of update-server's endpoints.

# Review requests

* How does versioning work in update-server? How can I communicate to future consumers of this HTTP API that, if they rely on `bootId`, their code won't work for earlier robot software versions?
* The test, as implemented, feels pretty trivial and unsatisfying to me. Am I overthinking it, or should I try harder to find a way to exercise more of the new code?
* This code will crash `make dev` if you run it on an OS other than Linux. Other file accesses in update-server already crash `make dev` if you run it on an OS other than Linux. Still, are we okay with this?
* See also my concerns in "risk assessment," below, regarding update-server fault tolerance.

## Smoke testing

I've already done this:

1. `make push`.
2. `GET /server/update/health`.
3. Confirm there's a `bootId` field with a string like `265bc611...`.
4. Confirm the field remains constant across requests.
5. Confirm the field remains constant across `systemctl restart opentrons-update-server`.
6. Confirm the field does *not* remain constant across power cycles and reboots.

# Risk assessment

Low-ish since the above smoke test passes, I guess?

It's simple code, but, as implemented, the above smoke test is the only way to make sure it doesn't crash `opentrons-update-server`.

I suppose we could make it more fault-tolerant by catching `Exception`s raised by `get_boot_id()`. But that comes with complexity, and we don't do that for a similar access to `/etc/VERSION.json`, so...

2021-03-02 18:47 UTC, mcous requested changes
- I think that this it's ok that this makes the update server only runnable on Linux. That's pretty much the state of the current world
- We can handle lack of boot ID with the client-side type definition, the same way as we do with the `capabilities` field, which only exists on newer versions of the software
- I think obfuscating the boot UUID is more trouble than it's worth

2021-03-02 18:47 UTC, mcous commented on update-server/otupdate/buildroot/control.py
> +    # Hash to obfuscate so no one accidentally relies on this specifically
Is this really necessary? I'm not sure I see why we should obfuscate this UUID

2021-03-02 18:47 UTC, mcous commented on update-server/otupdate/buildroot/control.py
> +    with open('/proc/sys/kernel/random/boot_id', 'rb') as file:
Should this path string go in a constant variable?

Also, this gets a little nitpicky, but I generally find `pathlib` a little easier to read in terms of intent:

```py
# this assumes we do not obfuscate, see other comment
def _get_os_boot_id() -> str: 
    return Path('/proc/sys/kernel/random/boot_id').read_text().strip()
```

2021-03-02 20:33 UTC, SyntaxColoring commented on update-server/otupdate/buildroot/control.py
> +    with open('/proc/sys/kernel/random/boot_id', 'rb') as file:
> Should this path string go in a constant variable?

I thought about that, but I decided against it because it felt like indirection without substance.

* It will never make sense to change the path without changing the function that uses the path.
* Another thing that maybe influences my gut feeling: I read `open('/proc/sys/kernel/random/boot_id)` not as a filesystem access, but as a platform API call. (Because this *is* how Linux does platform API calls, basically.) 

> Also, this gets a little nitpicky, but I generally find `pathlib` a little easier to read in terms of intent

Agreed. Changed.

2021-03-02 20:57 UTC, SyntaxColoring commented on update-server/otupdate/buildroot/control.py
> +    # Hash to obfuscate so no one accidentally relies on this specifically
Good question. It's certainly not necessary. I do think it's nice to have, though.

We don't want to commit to defining this field as the *Linux kernel* boot ID, because that's a real low-level implementation detail. But we're calling it "a boot ID," and everyone knows we run Linux, so it's conceivable that *someone, eventually* will assume they're the same, maybe without realizing it. We could *document* that they're not the same, but it seems more foolproof to just code it so that this mistake is impossible. Like how [Go randomizes iteration order over maps](https://stackoverflow.com/q/55925822/497934).

I guess the question is whether it's worth the complexity. IMO yes; it's "only" a `sha256()` call. But I wouldn't mind if this were vetoed.

2021-03-02 22:34 UTC, mcous commented on update-server/otupdate/buildroot/control.py
> +    # Hash to obfuscate so no one accidentally relies on this specifically
My thinking is sort of:

- It's already a UUID (or at least, I think it is based on _very_ light googling) and we use UUIDs for identifiers in other resources
- I can't think of any failure modes that could be caused by someone assuming the string to be a Linux boot ID
    - Conversely, I _can_ think of future features that may be more difficult to build if we obfuscate this ID

This is coming not from a performance complexity standpoint, but rather a maintenance complexity standpoint. It feels a lot to me like a YAGNI

2021-03-02 23:41 UTC, SyntaxColoring commented on update-server/otupdate/buildroot/control.py
> +    # Hash to obfuscate so no one accidentally relies on this specifically
To clarify your point, I think there's potentially two questions:

1. Whether this ID is in UUID format (32 hex digits in 5 groups separated by hyphens, like `123e4567-e89b-12d3-a456-426614174000`).
2. Whether this ID is the exact one provided by the Linux kernel. That is, if I compare it to the result of something else that's documented to return `/proc/sys/kernel/random/boot_id`, it *must* be the same.

You're saying that we should specifically design and document this interface so that the answer to both questions is "yes," right?

2021-03-03 17:35 UTC, mcous commented on update-server/otupdate/buildroot/control.py
> +    # Hash to obfuscate so no one accidentally relies on this specifically
Oops, my last response sort of obscured what I was trying to say rather than clarifying it. Also I know this is a pretty little thing! That being said, I think it's an important philisophical discussion as we continue development on the robot software.

My position is:

1. Our spec (and API contract) should be **"There is a field which is a string which changes every boot. The format of the string is not specified."**
2. Putting the contents of `/proc/sys/kernel/random/boot_id` in a health endpoint field satisfies this requirement
    - The string will change every boot
    - Returning a UUID formatted string, _while purposefully not a part of our spec_, is a reasonable thing for a developer to read as "some random identifier" 
3. Hashing the contents of the file:
    1. Does not get us closer to satisfying the spec, because we have already met the spec
    2. Does not prevent any identifiable failure mode (**My opinion!** Eager to hear a counterpoint here)
    3. Adds another thing for some future developer to have to worry about

(3ii) and (3iii) say to me that we shouldn't hash the boot ID.

-- 

(There's a less compelling point I tried to make that "in the future, we may have a good reason to specify in our API contract that it _is_ the Linux boot ID." Given that this suffers the same problem as (3ii) - it's difficult to identify a concrete reason to do so - I think this point can be safely ignored)

2021-03-03 22:15 UTC, SyntaxColoring commented on update-server/otupdate/buildroot/control.py
> +    # Hash to obfuscate so no one accidentally relies on this specifically
> I know this is a [petty?] little thing! That being said, I think it's an important philisophical discussion as we continue development on the robot software.

Totally with you.

I think we're both paying close attention because we're treating this not as a mere bugfix implementation detail, but as a meaningful extension of our platform API. Our platform API doesn't support detecting when a robot restarts, and we want it to. And we want to do that right, and establish good patterns so that future work also does it right.

The philosophical discussion is productive.

-----

From an earlier message:

> This is coming not from a performance complexity standpoint, but rather a maintenance complexity standpoint. It feels a lot to me like a YAGNI

Yep, I can see that.

I applied YAGNI more to the *spec* and less to the implementation. "Do we *need* to provide the *Linux kernel boot ID,* or is that unnecessarily specific?" It seems we both agree it's unnecessarily specific, at least for today.

So then, as a totally separate second step: "Within the envelope of this intentionally vague spec, how do we make it as hard as possible to use our interface incorrectly? (With reasonable effort on our part.)" I came up with obfuscation. But my sense of "reasonable effort" might be miscalibrated.

I think there's two potential maintenance burdens to be scared of:

1. Maintaining the internal implementation code. Keeping it readable, approachable, simple, well-tested, and so on.
2. Maintaining the public interface. If, someday, something sufficiently important relies on its *accidental* behavior instead of its *specified* behavior, we have to live with that and find a way to preserve the accidental behavior.

I was less paranoid about (1) and more paranoid about (2).

-----

> 3. Hashing the contents of the file:
>    i. Does not get us closer to satisfying the spec, because we have already met the spec
>    [...]
>    iii. Adds another thing for some future developer to have to worry about

Agreed.

> 3. Hashing the contents of the file:
>    ii. Does not prevent any identifiable failure mode (**My opinion!** Eager to hear a counterpoint here)

This is the vague, contrived scenario in the back of my mind.

1. Suppose we someday want to change the ID's source from the Linux kernel to something else.
  
   Maybe we readopt containerization, or do something else that makes `/proc/sys/kernel/random/boot_id` less appropriate.

   Maybe we get update-server's `make dev` to work, and, for its `bootId` dummy values, we want to include something distinctly un-UUID-like to make it obvious that those values should never appear in production.

2. Despite our documentation, we're unpleasantly surprised to find that someone accidentally relied on it being the kernel boot ID. And we don't want to just break it.

    Maybe, to tie into some kind of logging or auditing thing, they tried correlating it with `journalctl --list-boots`. Or maybe they tried correlating it with a Python protocol's view of `/proc/sys/kernel/random/boot_id`.
   
    This someone could be one of us, or an external API consumer.

-----

> (There's a less compelling point I tried to make that "in the future, we may have a good reason to specify in our API contract that it _is_ the Linux boot ID." Given that this suffers the same problem as (3ii) - it's difficult to identify a concrete reason to do so - I think this point can be safely ignored)

I think that's a good point, though, and not something that my solution accounts for.

2021-03-03 23:11 UTC, SyntaxColoring commented on update-server/otupdate/buildroot/control.py
> +    # Hash to obfuscate so no one accidentally relies on this specifically
With all this in mind, I'm happy to remove the obfuscation if you still are, because:

* The flexibility to someday change the API contract so that it *is* the Linux kernel boot ID is appealing, even without a specific use case in mind.
* Ultimately, as the author of this code, It's probably not my right to say that it's simple and maintainable. If someone else thinks that it's more complex than is worthwhile, that's hard to argue against. 🙂

2021-03-04 15:57 UTC, mcous commented on update-server/otupdate/buildroot/control.py
> +    # Hash to obfuscate so no one accidentally relies on this specifically
I think I'm still in favor of removing it. I think the code itself and the comments are great and explain what it's doing really well. That being said, the "maintenance burden" I worry about is more along the lines of a future developer coming in and thinking "oh, we must have had a bug here and it's really important that we do this hashing here and elsewhere," when in reality it was pretty speculative on our part

Also down to go ahead and spec that it _is_ the Linux boot ID, if that makes anyone feel better. (Also also down to continue not spec'ing that)

2021-03-05 16:05 UTC, mcous approved these changes
🪂

2021-03-05 16:05 UTC, mcous commented on update-server/otupdate/buildroot/control.py
> +    return Path('/proc/sys/kernel/random/boot_id').read_text()
Might be worth adding a `strip()` on the end for any trailing newlines

2021-03-05 16:51 UTC, merged