feat(protocol-designer): implement save button disabling in batch edit form
OpenTrons/opentrons-api pull request #7405
Opened 2021-03-01 23:05 UTC by IanLondon

# Overview

Closes #7130

# Changelog

# Review requests

- [ ] See ticket for disabling behavior and tooltips
- [ ] Code & test review

# Risk assessment

Low, PD only

2021-03-01 23:05 UTC, IanLondon commented on protocol-designer/src/components/BatchEditForm/__tests__/BatchEditMoveLiquid.test.js
> +    // expect(handleSave).not.toHaveBeenCalled()
why does this fail!?!

2021-03-02 15:25 UTC, shlokamin requested changes
Missing cancel tooltips but looks good other than that!

**Cancel**
- [ ] Cancel button has the tooltip "Reset unsaved changes to the form"
**cancel tooltip not hooked up yet**
- [x] When cancel button is clicked, any unsaved changes to the form revert. No changes to the step selection and the form is still open. 

**Enabled Save**
- [x] When there have been changes to the form, the save button is enabled
- [x] Enabled save button has the tooltip "Apply changes to all selected steps"
- [x] When enabled save button is clicked, (1) changes to the form are applied and (2) the save button becomes disabled because there are no new changes to the form. 

**Disabled Save**
- [x] When there are no changes to the form since its last save state, the save button is disabled
- [x] Disabled button has the tooltip "No new changes to save"
- [x] When changes are made to the form, the save button is enabled

2021-03-02 15:25 UTC, shlokamin commented on protocol-designer/src/components/BatchEditForm/__tests__/BatchEditMoveLiquid.test.js
> +  it('save should be enabled when form has changes', () => {
this is small a nit pick, but sometimes we write our `it` blocks like sentences: `it should be enabled when the form has changes`, and sometimes we structure the names like you have here. my personal preference is the former, but tbh it doesn't matter much to me as long as we're all doing the same thing.

2021-03-02 15:25 UTC, shlokamin commented on protocol-designer/src/components/BatchEditForm/index.js
> +  const handleCancel = () => dispatch(resetBatchEditFieldChanges())
i think this is the right move, it makes sense for the batch edit form component to do this stuff on its own

2021-03-02 17:22 UTC, Kadee80 approved these changes
💾 🚫 
Works as described. Was oddly satisfied resetting form changes with the cancel button.

2021-03-02 17:53 UTC, shlokamin approved these changes

2021-03-02 18:42 UTC, merged