test(protocol-designer): e2e batch edit automation cases
OpenTrons/opentrons-api pull request #7414
Opened 2021-03-03 19:08 UTC by reachojhaneha

# Overview

Writing the e2e tests for batch

# Changelog

- Automation cases for batch edit

# Risk assessment
low

2021-03-17 21:12 UTC, shlokamin requested changes
Prior to release we should make sure we assert that each of the actions we're doing were successful. I'm down to pitch in here!

2021-03-17 21:12 UTC, shlokamin commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +    })
after this can we guarantee that the banner shows up or something? just to show we are in batch edit mode

2021-03-17 21:12 UTC, shlokamin commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +    })
can we validate that the steps actually get selected? maybe via styles or something, we can look into this

2021-03-17 21:12 UTC, shlokamin commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +
can we validate that he flow rate gets saved? maybe by reopening the form and making sure the value has changed

2021-03-17 21:12 UTC, shlokamin commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +    cy.get('button').contains('exit batch edit').click()
Same thing with all of these, we should validate that the steps have been deleted/duplicated/expanded. And that we've successfully exited batch edit mode

2021-03-17 21:17 UTC, reachojhaneha commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +    })
Good Point. I am doing set of actions in this script but not verifying them. Will verify these steps.

2021-03-17 21:17 UTC, reachojhaneha commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +    })
will do

2021-03-17 21:18 UTC, reachojhaneha commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +
will do

2021-03-17 21:18 UTC, reachojhaneha commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +    cy.get('button').contains('exit batch edit').click()
will do

2021-03-17 21:29 UTC, shlokamin commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +    })
cool, lmk if you'd like any support. and thanks for this, we really appreciate it!

2021-03-29 18:37 UTC, shlokamin commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +    })
how come this range selection is needed? it looks like just after there is another range selection on `StepItem_4`

2021-03-29 18:37 UTC, shlokamin commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +    cy.get('button').contains('delete steps').click()
this doesn't quite validate that a duplicate and delete went through. could we also verify that when you click `duplicate` there will be a total of 18 steps? could just be: 

```js
cy.get('[data-test="StepItem_18"]').should('exist') //there are now 18 step items
```

and then after the `delete`:

```js
cy.get('[data-test="StepItem_10"]').should.not.('exist') // there are now only 9 stepitems
```

or something like that... 

does that make sense?

2021-03-29 18:49 UTC, reachojhaneha commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +    cy.get('button').contains('delete steps').click()
this is addressed, not after duplicating i verify that 18 steps are there and deleting steps verify the remaining steps too.

2021-03-29 18:49 UTC, reachojhaneha commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +    })
removed this step

2021-03-29 19:57 UTC, shlokamin reviewed
Some small typos, but it also looks like CI is failing. Looks this test cannot find the `exit batch edit mode` button

2021-03-29 19:57 UTC, shlokamin commented on protocol-designer/cypress/integration/batchEdit.spec.js
>      // Delete the dublicated steps
`dublicated  => duplicated` 😄

2021-03-29 19:57 UTC, shlokamin commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +  it('Verify Flowrate, dublicate, delete functionality in Batch Edit Mode', () => {
`dublicate  => duplicate` 😄

2021-03-29 19:57 UTC, shlokamin commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +    // Dublicate the selected steps
`dublicate => duplicate 😄`

2021-03-29 20:01 UTC, reachojhaneha commented on protocol-designer/cypress/integration/batchEdit.spec.js
>      // Delete the dublicated steps
Test is not finding exit batch edit mode button, as its not able to enter the batch edit form. Does the E2E run on production environment? As this case passes on sandbox

2021-03-29 20:01 UTC, reachojhaneha commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +    // Dublicate the selected steps
Thanks, will correct this

2021-03-29 21:19 UTC, shlokamin commented on protocol-designer/cypress/integration/batchEdit.spec.js
>      // Delete the dublicated steps
no they only run on sandbox

2021-03-31 16:07 UTC, shlokamin commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +      .should('exist')
This part I do not follow...

1. We duplicated our 9 steps, so now we have 18 steps selected
2. We shift + click on step number 9 (at this point which steps are selected?)
3. Delete all of the selected steps
4. Then only 1 item is selected

How is it that only 1 item is left selected?

2021-03-31 16:33 UTC, shlokamin commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +      .should('exist')
i think i answered my own q above...

would it be worth checking that we only have 9 steps left after clicking `delete`?

2021-03-31 20:24 UTC, IanLondon commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +    // Expand ALL steps
I think this comment is inaccurate, it's really expanding just the selected steps (1 and 4 at this point)

2021-03-31 20:30 UTC, IanLondon requested changes
Looks great! Just have a few comments.

Also, could you merge the latest edge on to this? It has some changes that have already been merged into edge (eg StepSelectionBanner + SubstepRow) and also since this branch may be getting a little older, it'd be good to update it so that we're not surprised by something unexpected happening when it is merged

2021-03-31 20:30 UTC, IanLondon commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +    cy.get('[data-test="SubstepRow_aspirateWell"]')
This is testing that the step is expanded, right? Maybe we should make sure specifically that steps 1 & 4 are expanded and that eg step 2 isn't? Right now, this would pass if any one step was expanded, I think.

2021-03-31 20:30 UTC, IanLondon commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +      .should('exist')
Might be nice to have a comment just pointing out that after the shift-click, Steps 1 to 9 should be selected (bc it's hard to follow in my head as a read it)

Also agree I think we might want to delete, then select all, and confirm that 9 steps are remaining (instead of, or in addition to, checking that 1 step is currently selected immediately after clicking delete)

2021-04-07 13:42 UTC, reachojhaneha commented on protocol-designer/cypress/integration/batchEdit.spec.js
> +      .should('exist')
this is what i tried: selected all the steps and shift + step 9 to deselect steps 9 to 18. Delete steps 1-8 steps as they are selected. Once all the selected steps are deleted, next step becomes selected as for batch edit one step is always selected(imo this is a verification too).
Now, about selecting steps 9-18 steps, select-all(id - #ClickableIcon_select)  is hidden by another element <div class="lists__title_bar__3n-Et lists__clickable__2o_y_">...</div>, and cypress is not able to access it. Hence i took the other route mentioned above.

2021-04-16 13:56 UTC, shlokamin commented
Looks like e2e cases are failing: 

```
AssertionError: Timed out retrying after 4000ms: Expected to find content: 'Batch editing of settings is only available for Transfers' within the element: <p#Text_noSharedSettings.Text-sc-1wb1h0f-0.nVDCX> but never did.
```

2021-04-16 14:03 UTC, Kadee80 commented
> Looks like e2e cases are failing:
> 
> ```
> AssertionError: Timed out retrying after 4000ms: Expected to find content: 'Batch editing of settings is only available for Transfers' within the element: <p#Text_noSharedSettings.Text-sc-1wb1h0f-0.nVDCX> but never did.
> ```

Might this be because we changed the text to Transfers or Mix?

2021-04-16 14:12 UTC, shlokamin commented
Ahhh yep, we have to change the cypress query to `"Batch editing of settings is only available for Transfer or Mix steps"`

2021-04-19 14:54 UTC, IanLondon approved these changes
🎉

2021-04-20 14:11 UTC, shlokamin approved these changes

2021-04-20 14:14 UTC, merged