feat(api): implement get_tip_tracker and comments
OpenTrons/opentrons-api pull request #7436
Opened 2021-03-04 14:39 UTC by amitlissack

# Overview

Tip tracker and explanation of un implemented methods in `engine.LabwareContext`.

# Changelog

- add comments about not unimplemented methods.
- implement get_tip_tracker

# Review requests

# Risk assessment

None

2021-03-04 18:37 UTC, SyntaxColoring approved these changes

2021-03-04 18:37 UTC, SyntaxColoring commented on api/src/opentrons/protocols/implementations/engine/labware_context.py
> +        # TODO AL 2020304 - Is Labware.name setter necessary?
No, IMO.

* docs.opentrons.com describes nothing to set, or even access, a labware's name after creating it. (Though `load_labware` does have a `label` parameter).
* If we want this to be part of the public API, we should think about what it means, bubbling up all the way to how it's presented in the UI. (e.g. Is it intended to describe the *labware,* or the reagents *in* the labware?)
* If we need it for internal reasons, I guess I question why it's part of `LabwareContext`'s top-level public API at all, as opposed to something like `LabwareContext.opentrons_internals.set_name`. But that's really a PAPI-wide pattern, not specific to `LabwareContext` or `set_name`.

2021-03-04 18:37 UTC, SyntaxColoring commented on api/src/opentrons/protocols/implementations/engine/labware_context.py
> +        #  calibration over RPC
Hm. Interesting question.

Assuming the platform provides a separate API for consumers to edit labware calibrations...is there ever a legitimate reason to want to edit labware calibration *in the middle of a Python protocol*? I don't know.

Given calibration's historical subtleties, I'm leaning towards: yes, this is only here to support labware calibration over RPC, and when we're free of RPC, we should simplify the API by removing this.

I was typing up a hypothetical scenario where someone could want to implement their own labware calibration with with *✨  computer vision ✨*, or whatever. But then I realized they could be controlling that through *Protocol Engine* commands, rather than Python function calls.

¯\\\_(ツ)\_/¯

2021-03-04 18:37 UTC, SyntaxColoring commented on api/src/opentrons/protocols/implementations/engine/labware_context.py
> +        # TODO AL 2020304 - Is Labware.tip_length setter necessary?
Ditto `set_calibration` comments.

2021-03-04 18:37 UTC, SyntaxColoring commented on api/tests/opentrons/protocols/implementation/engine/test_labware_context.py
> +    assert isinstance(labware_context.get_tip_tracker(), TipTracker)
Can we instead rely on static type checking for this?

2021-03-04 18:52 UTC, amitlissack commented on api/src/opentrons/protocols/implementations/engine/labware_context.py
> +        # TODO AL 2020304 - Is Labware.name setter necessary?
I'm with you. I am going to take your comment and put it in the ticket that deals with this issue.

2021-03-04 18:59 UTC, mcous reviewed
Could we use this PR more to inform what additions we'll need to make to Protocol Engine state to implement tip tracking successfully?

2021-03-04 18:59 UTC, mcous commented on api/tests/opentrons/protocols/implementation/engine/test_labware_context.py
> +    assert isinstance(labware_context.get_tip_tracker(), TipTracker)
Sort of a similar comment from me. Since this is a collaborator test, the value here needs to be that the test verifies things are wired up properly based on the stubbed out data.

I would expect to see something in here that made sure the returned TipTracker was wired up to the protocol engine data

2021-03-04 18:59 UTC, mcous commented on api/src/opentrons/protocols/implementations/engine/labware_context.py
> +        return TipTracker(columns=self.get_well_grid().get_columns())
Are we constructing a `TipTracker` this way because that's how it works with vanilla Protocol Context? If so, I think this PR could bring some extra value if we did (1) and (2) below:

1. Considered what a TipTracker would look like if it was fed by Protocol Engine state
2. Used (1) to construct a TipTracker like we would want it to be constructed
3. Used (2) to add tip tracking and necessary selectors to feed TipTracker to the engine
    - Own PR probably

2021-03-04 19:05 UTC, amitlissack commented on api/tests/opentrons/protocols/implementation/engine/test_labware_context.py
> +    assert isinstance(labware_context.get_tip_tracker(), TipTracker)
I'll delete it.

2021-03-04 19:41 UTC, sanni-t approved these changes

2021-03-04 19:41 UTC, sanni-t commented on api/src/opentrons/protocols/implementations/engine/labware_context.py
> +        # TODO AL 2020304 - Is Labware.name setter necessary?
Does PD require it? Looking at a json protocol, I'm guessing no?

2021-03-04 19:54 UTC, amitlissack commented on api/src/opentrons/protocols/implementations/engine/labware_context.py
> +        return TipTracker(columns=self.get_well_grid().get_columns())
Ideally, we would not use TipTracker at all. I think that I missed a couple details. 

I'll look at it.

2021-03-04 21:28 UTC, mcous requested changes
I've got a batch of comments that are sort of variations on the theme of "provide access to engine state rather than copying it into a new object"

2021-03-04 21:28 UTC, mcous commented on api/src/opentrons/protocols/implementations/engine/labware_context.py
> +        return Point(x=x, y=y, z=z) + self.get_geometry().offset
I think this can / should be a call to the protocol engine directly. IIRC this `get_calibrated_offset` should return the location of the labware's origin in deck coordinates. The engine already does this, and it could be split out into it's own `geometry` selector

2021-03-04 21:28 UTC, mcous commented on api/src/opentrons/protocols/implementations/engine/labware_context.py
>      def is_tiprack(self) -> bool:
I think this should go to the engine, too. The `labware` state should have an `is_tiprack` selector

2021-03-04 21:28 UTC, mcous commented on api/src/opentrons/protocols/implementations/engine/labware_context.py
>          return self.get_parameters()['loadName']
Can this come from the engine, too? We have a `get_definition_uri` selector, I think a `get_load_name` selector would make sense, too

2021-03-04 21:28 UTC, mcous commented on api/src/opentrons/protocols/implementations/engine/labware_context.py
> +        return self.get_geometry().z_dimension + self.get_calibrated_offset().z
I think this should be a call to `self._state_view.geometry.get_labware_highest_z(self._id)` instead

2021-03-04 21:28 UTC, mcous commented on api/src/opentrons/protocols/implementations/engine/labware_context.py
> +        return LabwareGeometry(
Looking at `LabwareGeometry` with the presence of the engine state, it seems like LabwareGeometry at this point only serves as a cached value. There looks to be value in keeping the `LabwareGeometry` interface, so I wonder if we can construct `LabwareGeometry` as a passthrough to the StateView, instead?

As for the caching stuff, coming from a heavily Redux-based perspective, caching is a thing that makes a lot of sense at the state selector level rather than trying to manage value objects constructed with the underlying data floating around outside the state

2021-03-04 21:28 UTC, mcous commented on api/src/opentrons/protocols/implementations/engine/labware_context.py
> +            WellImplementation(
Similar comment to the `LabwareGeometry` stuff. I think we should construct `WellImplementation` with a reference to the state view, the labware ID, and the well name. I think it'll be easier to manage as a convenience interface for the underlying data in state rather than a copy of the state floating around

2021-03-08 13:57 UTC, amitlissack commented on api/src/opentrons/protocols/implementations/engine/labware_context.py
> +        return LabwareGeometry(
I think that's a fine idea. I feel like it should be pushed to future work. My rationale is that it has implications for the vanilla protocol context work.

2021-03-08 13:58 UTC, amitlissack commented on api/src/opentrons/protocols/implementations/engine/labware_context.py
> +            WellImplementation(
Similar to `LabwareGeometry`. I suggest we push this to a future PR. `WellImplementation` could be refactored as an interface with PE and vanilla implementation.

2021-03-08 17:40 UTC, amitlissack commented on api/src/opentrons/protocols/implementations/engine/labware_context.py
> +        return TipTracker(columns=self.get_well_grid().get_columns())
Kinda covered by #7424

2021-03-08 17:41 UTC, amitlissack commented on api/src/opentrons/protocols/implementations/engine/labware_context.py
> +        return LabwareGeometry(
See #7448

2021-03-08 17:42 UTC, amitlissack commented on api/src/opentrons/protocols/implementations/engine/labware_context.py
> +            WellImplementation(
See #7449

2021-03-08 20:49 UTC, merged