refactor(app): modules page revamp
OpenTrons/opentrons-api pull request #7497
Opened 2021-03-16 00:55 UTC by ahiuchingau

# Overview
This PR updates the Modules page on the app following this [design](https://www.figma.com/file/GWe9EvcpyehHSAb4bfEKrK/Multiples-of-a-Module-(MoaM)?node-id=77%3A1289).

# Changelog
- added colored dots to module status
- added engage/disengage button for Magnetic Module
- separated thermocycler lid and block temperature controls into two different buttons
- updated temperature control modal
- fixed tests

# Review requests
Module USB ports will not be showing at this point yet, but will be incorporated into another PR.
- Make sure the colored dots are reflecting the status correctly (see [here](https://www.figma.com/file/GWe9EvcpyehHSAb4bfEKrK/Multiples-of-a-Module-(MoaM)?node-id=77%3A1289))
- Test on the robot with modules ensure the module control buttons work as intended

# Risk assessment
Medium, this adds a new module control ability to this page (engage/disengage the magnetic module) and could potentially break the behavior of the set temp button for the temperature module and thermocycler.

2021-03-16 16:42 UTC, emilywools commented
i checked the temp module and it looks good. It doesn't look like we have any error handling when a user enters an invalid value, though. I tried in the current state and we don't have error handling there either, but it would be nice to add it at some point. 

I dont have a TC or mag module to test, could someone get me some screenshots to take a look?

2021-03-17 14:04 UTC, Laura-Danielle requested changes
Some small changes. I was unable to test on my physical robot (issues with homing still), but we should make sure QA thoroughly tests the control buttons especially for the thermocycler.

2021-03-17 14:04 UTC, Laura-Danielle commented on app/src/molecules/ModuleControls/MagnetControl.js
> +      units: null,
I think we should either have mm for both or not. We can convert the old unit to mms right? I don't remember the conversion but maybe you or @sfoster1 do?

2021-03-17 14:04 UTC, Laura-Danielle commented on app/src/molecules/ModuleControls/index.js
> +  console.log(mod)
left a console log in here

2021-03-17 14:34 UTC, ahiuchingau commented on app/src/molecules/ModuleControls/MagnetControl.js
> +      units: null,
Does that mean the user would have to convert the engage height they normally use in the protocol to mms in order to use this feature? I think that could be confusing. 

Could @emilywools weigh in on this as well?

2021-03-17 14:35 UTC, ahiuchingau commented on app/src/molecules/ModuleControls/index.js
> +  console.log(mod)
oops

2021-03-18 15:03 UTC, b-cooper approved these changes
Code looks good, just a question about hardcoded values that probably already exist in `shared-data`.  And the predictable `i18next` comment, but it's no big deal for this PR
🧑‍🚀

2021-03-18 15:03 UTC, b-cooper commented on app/src/molecules/ModuleControls/MagnetControl.js
> +  if (model === MAGNETIC_MODULE_V1) {
Do these values already exist on the module definitions? If so, it'd be ideal to reference those values here instead of hardcoding them.

2021-03-18 15:03 UTC, b-cooper commented on app/src/molecules/ModuleControls/MagnetControl.js
> +  const alertHeading = `Set Engage Height for ${displayName}`
Definitely not a deal breaker for this PR, but especially for new components like this, we should be aiming to put all new copy directly into `i81next`

2021-03-18 15:03 UTC, b-cooper commented on app/src/pages/Robots/ModuleSettings/ModuleItem/ModuleImage.js
> -import styles from './styles.css'
💣

2021-03-18 16:56 UTC, ahiuchingau commented on app/src/molecules/ModuleControls/MagnetControl.js
> +  if (model === MAGNETIC_MODULE_V1) {
Yeah I totally agree but they are not on the definitions unfortunately :/

2021-03-23 17:49 UTC, Laura-Danielle approved these changes
looks good to me

2021-03-23 18:38 UTC, b-cooper approved these changes
Looks good 🥼  

Just one gratuitous `css` prop

2021-03-23 18:38 UTC, b-cooper commented on app/src/molecules/ModuleControls/TemperatureControl.js
> +        css={css`
This should be able to be replaced with `paddingX={SPACING_2}`

2021-03-23 23:21 UTC, merged

2021-03-24 16:33 UTC, emilywools commented
Nus sent me some screenshots and I have a couple nits:

can the "update" button be the normal button height?
<img width="1025" alt="Screen Shot 2021-03-24 at 12 28 33 PM" src="https://user-images.githubusercontent.com/4339860/112347120-ff3e6c80-8c9c-11eb-9b52-1de706b20ff4.png">

can the grey box behind the engage heights be the lighter gray? (#FAFAFA) 
<img width="1014" alt="Screen Shot 2021-03-24 at 12 29 00 PM" src="https://user-images.githubusercontent.com/4339860/112347166-0bc2c500-8c9d-11eb-90ae-d60b37148663.png">