fix(api): check the symlink of the virtual port to map to the physical port
OpenTrons/opentrons-api pull request #7524
Opened 2021-03-22 18:00 UTC by Laura-Danielle

# Overview
When developing #7359 , I made the assumption that the port referred to the _serial_ or _device path_ name, something to the effect of tty*. However, the port we have information of on the hardware control side is the _virtual port_, which looks more like `dev/ot_module_[NAME OF MODULE]`. Unfortunately, the raspberry pi only does mapping from the serial port to the physical usb port information.
Since there is not a multi-way symlink (i.e. we cannot look up the virtual port via the device path), we need to do the reverse look up from the virtual port to get the device path and then match up the physical port to each individual module.

When looking into this, I also realized we weren't properly using the physical ports in a sorted order, so that is taken care of while we do the reverse look-up.

# Changelog
- Add in a function to read the symlink on the virtual port
- Actually sort attached modules by physical port order via the new function `match_virtual_port`
- Add a test to check the new behavior

# Review requests
Put on a robot, especially @ahiuchingau to double check this fixes the original problem. Look over the code and let me know if you would like any changes to be made and/or whether it's better to just add a symlink that maps the serial port to the virtual port on buildroot.

# Risk assessment

Medium. Please test on a robot and please think about the comment in the Review Requests section.

2021-03-22 18:29 UTC, sfoster1 requested changes
I think we can use `os.readlink` rather than shelling out but it looks good and makes sense.

2021-03-22 18:29 UTC, sfoster1 commented on api/src/opentrons/drivers/rpi_drivers/usb.py
> +                ['readlink', virtual_port]).strip().decode()
https://docs.python.org/3/library/os.html#os.readlink ?

2021-03-22 21:40 UTC, ahiuchingau approved these changes
Tested on robot ✅

2021-03-23 13:35 UTC, sfoster1 approved these changes
Nice!

2021-03-23 13:58 UTC, merged