feat(api): add physical USB Port information to the hardware controller
OpenTrons/opentrons-api pull request #7532
Opened 2021-03-23 17:15 UTC by Laura-Danielle

# Overview
Closes #7196. This PR forces the protocol context to use modules in order of loading in the protocol.

# Changelog

- Move around some types in module geometry to utilize inside `api.py` (I feel like this isn't the best place, but I wasn't sure where these types should live)
- Modify `api.py` to return a list of modules which match the type and model passed in
- Keep track of the modules loaded into the protocol context 

# Review requests

Please look over the code and tests. Let me know if it makes sense or not.

# Risk assessment
Medium. We are slightly modifying how load module works in the protocol context so we should try loading some modules and running a protocol to make sure that nothing has changed in the behavior.

2021-03-23 18:58 UTC, amitlissack commented on api/src/opentrons/hardware_control/api.py
> +    def find_modules(
We're in the 1800s in this file. Do you think there's a way to consolidate the various module related methods into their own class? This new method and `register_modules` and `unregister_modules`. And wrap `_attached_modules`.

2021-03-23 19:01 UTC, sfoster1 requested changes
Let's just move around some of the by-model vs by-type checks in `find_module` but I like the structure.

2021-03-23 19:01 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +    def find_modules(
Since we're already doing narrowing by specific model in the protocol context (which is in fact where I think this should happen), maybe we should have this not take the `by_model` attribute and instead just a `by_type` attribute; then the back-compat stuff is entirely limited to the protocol context, and we don't have this dichotomy where the `resolved_type` is ignored unless we're simulating?

2021-03-23 19:01 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/types.py
> +class _ProvideLookup(Enum):
wonder if we can put this in some more generic place? i guess we'd have to make the error more generic

2021-03-23 19:01 UTC, sfoster1 commented on api/src/opentrons/protocols/context/protocol_api/protocol_context.py
> +        available_modules = self._hw_manager.hardware.find_modules(
so if we changed `find_modules` to only take the type, I think it would be a little nicer because most of the backcompat is _already_ here.

2021-03-23 19:25 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +    def find_modules(
sure!

2021-03-25 21:40 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +    def find_modules(
@amitlissack this will be done in a follow-up PR so as not to make this PR confusing.

2021-03-25 21:54 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/modules/types.py
> +class _ProvideLookup(Enum):
Will address this in the follow up PR to create a module control wrapper

2021-03-26 13:54 UTC, sfoster1 approved these changes
Nice, I like it!

2021-03-26 15:09 UTC, merged