refactor(app): migrate App source to TypeScript
OpenTrons/opentrons-api pull request #7550
Opened 2021-03-26 20:16 UTC by b-cooper

# Overview

WIP

This migrates the source code of the Opentrons App from using flow as a typing system to using TypeScript.

# Changelog

# Review requests

# Risk assessment

2021-04-28 12:46 UTC, mcous reviewed
Only made it through 115 files, but gonna try to work through this piece by piece. Might be worth landing #7731 first to be able to ditch another copy of `opentrons__shared-data.d.ts`

2021-04-28 12:46 UTC, mcous commented on app/src/App/__mocks__/portal.ts
> +type Props = { children: React.ReactNode }
```suggestion
interface Props {
  children: React.ReactNode
}
```

2021-04-28 12:46 UTC, mcous commented on app/src/App/__mocks__/portal.ts
> +// mock portal for enzyme tests
This file should be named `portal.tsx`

2021-04-28 12:46 UTC, mcous commented on app/src/__mocks__/logger.ts
> +): (message: string, meta: unknown) => void {
This return type looks wrong. This should be returning a `Logger` interface from `app/src/logger`, not a log function

2021-04-28 12:46 UTC, mcous commented on app/src/assets/labware/__mocks__/getLabware.ts
> +export function getLegacyLabwareDef(loadName: ?string): null {
```suggestion
export function getLegacyLabwareDef(loadName: string | null | undefined): null {
```

2021-04-28 12:46 UTC, mcous commented on app/src/assets/labware/__mocks__/getLabware.ts
> +export function getLatestLabwareDef(loadName: ?string): null {
```suggestion
export function getLatestLabwareDef(loadName: string | null | undefined): null {
```

2021-04-28 12:46 UTC, mcous commented on app/src/assets/labware/getLabware.ts
> +  loadName: ?string
```suggestion
  loadName: string | null | undefined
```

2021-04-28 12:46 UTC, mcous commented on app/src/assets/labware/getLabware.ts
> +  loadName: ?string
```suggestion
  loadName: string | null | undefined
```

2021-04-28 12:46 UTC, mcous commented on app/src/molecules/DeckMap/index.tsx
> +  $Diff<OP, ContextRouter>
This looks like leftover flow stuff

2021-04-28 12:46 UTC, mcous commented on app/src/molecules/DeckMap/index.tsx
> +import type { ContextRouter } from 'react-router-dom'
`ContextRouter` is a flow typedef

2021-04-28 15:20 UTC, b-cooper commented on app/src/molecules/DeckMap/index.tsx
> +  $Diff<OP, ContextRouter>
Yup, it's not the only leftover flow stuff either, I'm still actively working through the migration.  Definitely let me know if you want to hop in and grab some.

2021-05-19 22:57 UTC, mcous reviewed
Little  end-of-day batch of comments after about 100/800 files reviewed

2021-05-19 22:57 UTC, mcous commented on app/src/assets/labware/findLabware.ts
> +// TODO(mc, 2021-05-19): this function does not filter by loadName
```suggestion
// TODO(mc, 2021-05-19): this function does not filter by namespace
```

2021-05-19 22:57 UTC, mcous commented on app/src/assets/labware/getLabware.ts
> +const labwareSchemaV1DefsContext = (require as any).context(
Unnecessary cast thanks to webpack-env defs

```suggestion
const labwareSchemaV1DefsContext = require.context(
```

2021-05-19 22:57 UTC, mcous commented on app/src/assets/labware/getLabware.ts
> +function getLegacyLabwareDefs(): Readonly<LabwareDefinition1[]> | null {
I don't think `null` should be tacked on here; it can't return `null`

```suggestion
function getLegacyLabwareDefs(): Readonly<LabwareDefinition1[]> {
```

2021-05-19 22:57 UTC, mcous commented on app/src/assets/labware/getLabware.ts
> +  const def = getLegacyLabwareDefs()?.find(d => d.metadata.name === loadName)
Related to comment above, `getLegacyLabwareDefs()` will never be null

```suggestion
  const def = getLegacyLabwareDefs().find(d => d.metadata.name === loadName)
```

2021-05-19 22:57 UTC, mcous commented on app/src/assets/labware/getLabware.ts
> +const labwareSchemaV2DefsContext = (require as any).context(
Unnecessary cast

```suggestion
const labwareSchemaV2DefsContext = require.context(
```

2021-05-19 22:57 UTC, mcous commented on app/src/atoms/ToggleBtn/index.tsx
> +      disabled={Boolean(disabled)}
While I think this is correct, this is a source code change. We may want to consider reverting until we can make this change while also adding a test case for `disabled === null`, which does not currently exist

2021-05-19 22:57 UTC, mcous commented on app/src/molecules/DeckMap/index.tsx
> +type Props = OP & SP
We could use `interface` here if we wanted

```suggestion
interface Props extends OP, SP {}
```

2021-05-19 22:57 UTC, mcous commented on app/src/molecules/JogControls/DirectionControl.tsx
> +const CONTROLS_CONTENTS_BY_PLANE: { [plane in Plane]: ControlsContents } = {
Do we think `Record` is more readable here?

```suggestion
const CONTROLS_CONTENTS_BY_PLANE: Record<Plane, ControlsContents> = {
```

2021-05-19 22:57 UTC, mcous commented on app/src/organisms/AnalyticsSettingsModal/index.tsx
> +  return !seen ? (
Highlighting this as a source code change without test coverage that we may want to revert

2021-05-19 22:57 UTC, mcous commented on app/src/organisms/CalibrateDeck/__tests__/CalibrateDeck.test.tsx
> +  component: React.ReactNode
I don't think `React.ReactNode` is correct . Maybe something like this will work?

```ts
import type { CalibrationPanelProps } from '../../CalibrationPanels/types'

// ...
interface CalibrateDeckSpec {
  component: (props: CalibrationPanelProps) => JSX.Element
// ...
```

2021-05-19 22:57 UTC, mcous commented on app/src/organisms/CalibrateDeck/__tests__/CalibrateDeck.test.tsx
> +  childProps?: {}
Doesn't look like this is used

2021-05-19 22:57 UTC, mcous commented on app/src/organisms/CalibrateDeck/__tests__/CalibrateDeck.test.tsx
> +  [key: string]: unknown
Doesn't look like this is used

2021-05-19 22:57 UTC, mcous commented on app/src/organisms/CalibrateDeck/index.tsx
> +  [step in CalibrationSessionStep]?: React.ComponentType<CalibrationPanelProps>
This might be a little more readable as a partial record

```ts
const PANEL_BY_STEP: Partial<
  Record<CalibrationSessionStep, React.ComponentType<CalibrationPanelProps>>
>  = {
```

2021-05-19 22:57 UTC, mcous commented on app/src/organisms/CalibrateDeck/index.tsx
> +  [step in CalibrationSessionStep]?: StyleProps
Same comment about avoiding bare `x in Y` in favor of `Record` type alias

2021-05-19 22:57 UTC, mcous commented on app/src/organisms/CalibrateDeck/index.tsx
> +  const Panel = currentStep != null ? PANEL_BY_STEP[currentStep] : null
Source code changes. I may be missing it, but I don't see a test case for not rendering anything if a panel can't be found. I've seen this exact sort of change cause problems in the previous TS PRs; I think we should revert it

2021-05-19 22:57 UTC, mcous commented on app/src/organisms/CalibratePipetteOffset/__tests__/CalibratePipetteOffset.test.tsx
> +  childProps?: {}
Doesn't look like this is used

2021-05-19 22:57 UTC, mcous commented on app/src/organisms/CalibratePipetteOffset/__tests__/CalibratePipetteOffset.test.tsx
> +type CalibratePipetteOffsetSpec = Partial<{
Why is this `Partial`?

2021-05-19 22:57 UTC, mcous commented on app/src/organisms/CalibratePipetteOffset/index.tsx
> +  [step in CalibrationSessionStep]?: React.ComponentType<CalibrationPanelProps>
Partial Record maybe?

2021-05-19 22:57 UTC, mcous commented on app/src/organisms/CalibratePipetteOffset/index.tsx
> +  [step in CalibrationSessionStep]?: StyleProps
Partial Record?

2021-05-19 22:57 UTC, mcous commented on app/src/organisms/CalibratePipetteOffset/index.tsx
> +  const Panel = currentStep != null ? PANEL_BY_STEP[currentStep] : null
Source code change that I think we should revert

2021-05-19 22:57 UTC, mcous commented on components/__utils__/mountWithStore.ts
> +  subscribe: jest.MockedFunction<(args: []) => void>
```suggestion
  subscribe: jest.MockedFunction<() => void>
```

2021-05-19 22:57 UTC, mcous commented on components/__utils__/mountWithStore.ts
> +  dispatch: jest.MockedFunction<(...actions: Action[]) => Action>
The original flow type is a tuple representing a single action param, not an array of actions

```suggestion
  dispatch: jest.MockedFunction<(action: Action) => Action>
```

2021-05-19 22:57 UTC, mcous commented on app/typings/global.d.ts
> +      Intercom?: (...args: any[]) => unknown
Should this go in its own `intercom.d.ts` file?

2021-05-19 22:57 UTC, mcous commented on app/typings/global.d.ts
> +        [key: string]: unknown
Why is this here? We know this object only has the one `ipcRenderer` key:

```ts
// preload script for renderer process
// defines subset of Electron API that renderer process is allowed to access
// for security reasons
import { ipcRenderer } from 'electron'

global.APP_SHELL_REMOTE = { ipcRenderer }
```

2021-05-19 22:57 UTC, mcous commented on app/typings/form-data.d.ts
> +declare module 'form-data' {
The version of `form-data` that we use (v2.5.0) ships its own types. The reason that we don't pick it up is because it's in app-shell purgatory and not hoisted.

We should declare `"form-data": "2.5.0"` in the monorepo's dev dependencies (which is correct, because the app's tests depend on it) and delete this `any` shim. This exposes a little type error in the test that will need some casting to fix up

2021-05-20 16:48 UTC, mcous reviewed
Another batch of comments

2021-05-20 16:48 UTC, mcous commented on app/src/redux/support/intercom-binding.ts
> +    global.Intercom?.(Constants.INTERCOM_BOOT, iprops)
Source code change. We've had bugs in the past with intercom silently not being loaded, so this no-op here could hide an actual bug that we'd want to fail loudly

2021-05-20 16:48 UTC, mcous commented on app/src/redux/shell/robot-logs/reducer.ts
> +  state = state ?? INITIAL_STATE
I'm not sure we should make this change just yet. Can we put it back and downgrade an eslint rule to a warning temporarily (don't remember if this is a TS complaint or an eslint complaint)

2021-05-20 16:48 UTC, mcous commented on app/src/redux/shell/remote.ts
> +// @ts-expect-error
What error is getting thrown here? Can this comment be expanded?

2021-05-20 16:48 UTC, mcous commented on app/src/redux/shell/reducer.ts
> +  state = state ?? INITIAL_STATE
Source code change

2021-05-20 16:48 UTC, mcous commented on app/src/redux/shell/index.ts
> +export const CURRENT_VERSION: string = process.env.OT_APP_VERSION as string
Rather than doing `process.env.XYZ` and pretending like this is Node, should we go a more simple route and define bare constants? `process.env` makes me feel weird because we are not injecting this from the build environment variables

See the path I took in the discovery client: https://github.com/Opentrons/opentrons/blob/6209f7124b8a19a260e11d15a218fb284e97bed7/discovery-client/webpack.config.js#L19

2021-05-20 16:48 UTC, mcous commented on app/src/redux/shell/epic.ts
> +        'meta' in a &&
Source code change in a particularly important piece of code. I'd like to revert this

2021-05-20 16:48 UTC, mcous commented on app-shell/typings/global.d.ts
> +        [key: string]: unknown
I don't think this should be added, there are no other keys in this object

2021-05-20 16:48 UTC, mcous commented on app/src/redux/shell/epic.ts
> +    // @ts-expect-error TODO: don't use fromEvent and ipcRenderer type should work properly
This is an odd comment. `IpcRenderer` is from electron and should be typed as an EventEmitter, so `fromEvent` should be just fine here. What's it complaining about?

2021-05-20 16:48 UTC, mcous commented on app/src/redux/sessions/reducer.ts
> +  state = state ?? INITIAL_STATE
Source code change

2021-05-20 16:48 UTC, mcous commented on app/src/redux/system-info/reducer.ts
> +  state = state ?? INITIAL_STATE
Source code change

2021-05-20 16:48 UTC, mcous commented on app/src/redux/support/profile.ts
> +    [Constants.PROFILE_APP_VERSION]: process.env.OT_APP_VERSION,
Same comment about `process.env`

2021-05-20 18:52 UTC, b-cooper commented on app/src/atoms/ToggleBtn/index.tsx
> +      disabled={Boolean(disabled)}
I'm flexible in the "no source code changes" edict with these kinds of things. In my mind we will ultimately spend more time than is necessary to dance around something that is plain in terms of intention. If reverting these types of basic code changes is really helpful for considering this PR in a vacuum, then I'm fine with us taking the pedantic approach and revert them with a ts-expect-error and a follow-up PR that addresses as many ts-expect-errors as possible.

2021-05-20 19:22 UTC, b-cooper commented on app/src/pages/Calibrate/CalibratePanel/PipetteList.tsx
> +        const pipTipracks = uniqBy(
this is a linting related source code change, variable name was just switched to camelCase

2021-05-20 19:41 UTC, b-cooper commented on app/src/pages/Calibrate/CalibrateTipLengthControl.tsx
> +        createRequestId.current =
these null protections are also small source changes. originally the code relied on downstream falsey checks of these id refs. TS needs us to protect accessing the newly more specific `RobotApiMetaRequest` meta values.

2021-05-20 19:44 UTC, b-cooper commented on app/src/pages/Calibrate/Pipettes/PipettesContents.tsx
> +    Partial<{
This `Partial` is redundant because all props are already optional. We should consider changing this type to { [mount in Mount]?: InstrumentInfoProps }

2021-05-20 20:21 UTC, IanLondon requested changes
Submitting early in the interest of early feedback. I just finished `app/src/redux/analytics/` and am continuing to move down the list

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/alerts/epic.ts
> +      (a: Action): a is AlertDismissedAction =>
I didn't know about the `is` operator, then got excited, then got disappointed bc it doesn't seem to guard against incorrect filters correctly. Eg I can do `(a: Action): a is AlertDismissedAction => a.type === 'robot:RUN'` or any other action type and it doesn't care that it's not `ALERT_DISMISSED` :(

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/alerts/reducer.ts
> +export const alertsReducer: Reducer<AlertsState, Action> = (state, action) => {
this `default-param-last` lint rule is a bummer bc there's a decently strong convention to use `(state = initialState, action)` as the signature for a Redux reducer, that is tied to the difference in Redux state btw `null` and `undefined`.

Always in Redux reducers (specifically, for any app that uses `combineReducers` or its conventions), `undefined` is an invalid state that signifies a reducer isn't initialized and should return its initial state. For many reducers, `null` is a valid state so the nullish coalescing operator `??` won't work in a straightforward way. If not using default args, we should generally do something like `state = state === undefined ? INITIAL_STATE : state` to get the same effect in cases where the state is `null` at any point in the reducer's lifetime.

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/alerts/selectors.ts
> +) => null | AlertId[] = createSelector(
just checking bc I don't know the background: is it a conscious choice to switch from read-only array to plain array? I know sometimes read-only arrays require the read-only type to propagate everywhere so it could very likely be a pragmatic move. Just checking if this is on purpose or by accident

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/analytics/__tests__/hooks.test.tsx
> +    const render = (): ReturnType<typeof mount> => {
this should be inferred fine, can just be `const render = () => {` right? Tested that, seems fine

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/analytics/__tests__/make-event.test.ts
> +    const success = robotActions.connectResponse(null)
code change, just calling it out (and it's in a test anyhow)

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/analytics/constants.ts
>  export const ANALYTICS_PIPETTE_OFFSET_STARTED: 'analytics:PIPETTE_OFFSET_STARTED' =
I am pretty sure that the explicit typing of a string const is no longer required in TS, it was only a Flow thing. `export const ANALYTICS_PIPETTE_OFFSET_STARTED = 'analytics:PIPETTE_OFFSET_STARTED'` should be fine. At least that's what I've seen in TS with VSCode type annotation hints. The explicit `: 'a'` in `const A: 'a' = 'a'` seems redundant in TS.

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/analytics/make-event.ts
> +                      tipRackDisplayName:
code change, seems fine

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/analytics/make-event.ts
> +          // @ts-expect-error even if we used the in operator, TS cant narrow error to anything more specific than 'unknown' https://github.com/microsoft/TypeScript/issues/25720
The action here is either `'robot:SESSION_RESPONSE' | 'robot:SESSION_ERROR'` at this point in the switch-case. So we can check the action type `action.type` to figure out what the payload is. It might have given you problems earlier just because `const { type: actionType, payload: actionPayload, meta } = action` might make TS lose the connection between `action.type` and `action.payload`?

This works for me:
```js
error:
            (action.type === 'robot:SESSION_ERROR' &&
              action.payload.error &&
              action.payload.error.message) ||
            '',
```

but it's a code change, could do in a separate PR!

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/analytics/mixpanel.ts
> +    if ('name' in event) mixpanel.track(event.name, event.properties)
code change, seems safe tho

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/analytics/selectors.ts
> +type ProtocolDataSelectorResultFunc = (
why not use the `Selector` type from `reselect` then do `const _getUnhashedProtocolAnalyticsData: Selector<State, ProtocolAnalyticsData> = createSelector(`? You can eliminate `ProtocolDataSelectorResultFunc` and `ProtocolDataSelector` with that substitution.

I think the one advantage of `OutputSelector` is that it exposes fns like `resultFunc` for use in tests. But `_getUnhashedProtocolAnalyticsData` isn't exported or used in tests. I could see wanting to stick to `OutputSelector` though.

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/analytics/selectors.ts
> +    const robotAnalyticsData = settings.reduce<RobotAnalyticsData>(
code change, hard to imagine it having any negative effect though!

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/analytics/selectors.ts
> +      pipetteModel: pip?.model ?? '',
Code change. I'm assuming that `''` is a valid value for `PipetteOffsetCalibrationAnalyticsData`. But before, it was maybe possible for it to be `undefined` here.

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/analytics/selectors.ts
> +      pipetteModel: pip?.model ?? '',
Code change, similar to above. I'm assuming that `''` is a valid value for `TipLengthCalibrationAnalyticsData['pipetteModel']`. But before, it was maybe possible for it to be `undefined` here.

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/analytics/selectors.ts
> +      if (pipData != null) {
Code change here and the next couple lines. Is this a fix? This fn doesn't seem to be directly tested. In the indirect tests (`getAnalyticsDeckCalibrationData` I think tests its output indirectly), these cases aren't hit. Just FYI, not a blocker for me!!

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/analytics/selectors.ts
> +  return instruments.reduce<CalibrationCheckByMount>(
some code changes not covered by tests inside this `reduce`

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/analytics/types.ts
> +  [ffName: string]: boolean | string
type change. Is it more correct?

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/analytics/types.ts
> +export type DeckCalibrationAnalyticsData = {
With `export interface DeckCalibrationAnalyticsData {` here, this causes an error in `make-event.ts`. I played around with it and if you're OK with a code change, you can fix it like (L290):

```ts
case Sessions.SESSION_TYPE_DECK_CALIBRATION: {
          const dcAnalyticsProps = getAnalyticsDeckCalibrationData(state)
            
          return Promise.resolve(dcAnalyticsProps != null
            ? {
                name: 'deckCalibrationStarted',
                properties: {...dcAnalyticsProps},
              }
            : null)
        }
```

apparently TS is happy if you spread `{...dcAnalyticsProps}`, but confused if you don't.

This comment is just a nitpick, not blocking, might be better off not making any changes to what you have already.

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/analytics/types.ts
> +  [mount in Mount]: { model: string } | null
that's cool!

2021-05-20 20:21 UTC, IanLondon commented on app/src/redux/analytics/types.ts
> +// eslint-disable-next-line @typescript-eslint/consistent-type-definitions
same deal as comment above, I think. Fixed with `properties: {...hcAnalyticsProps},` :/

2021-05-20 21:21 UTC, shlokamin reviewed
Preliminary comments, ill keep moving on

2021-05-20 21:21 UTC, shlokamin commented on app/src/molecules/JogControls/DirectionControl.tsx
> +const CONTROLS_CONTENTS_BY_PLANE: { [plane in Plane]: ControlsContents } = {
i think `Record` is a bit more readable

2021-05-20 21:21 UTC, shlokamin commented on app/src/molecules/ModuleControls/TemperatureControl.tsx
> +    return TEMPERATURE_RANGES[model]?.secondary as TemperatureRanges
code change

2021-05-20 21:21 UTC, shlokamin commented on app/src/molecules/ModuleControls/TemperatureControl.tsx
> +    return TEMPERATURE_RANGES[model]?.primary as TemperatureRanges
code change

2021-05-20 21:21 UTC, shlokamin commented on app/src/molecules/ModuleControls/TemperatureControl.tsx
> +  [model in ModuleModel]?: {
code change, this param is now optional

2021-05-20 21:21 UTC, shlokamin commented on app/src/molecules/ReleaseNotes/index.tsx
> +  source: string | null | undefined
i think we can make this optional and then have `string | null` right?

2021-05-20 21:21 UTC, shlokamin commented on app/src/molecules/modals/BottomButtonBar.tsx
> +            className={cx(styles.bottom_button, button?.className)}
code change

2021-05-20 21:21 UTC, shlokamin commented on app/src/organisms/Alerts/LostConnectionAlert/index.tsx
> +  return showAlert ? (
code change

2021-05-20 21:21 UTC, shlokamin commented on app/src/organisms/Alerts/__tests__/Alerts.test.tsx
> +    wrapper.find(U2EDriverOutdatedAlert).invoke('dismissAlert')?.(true)
are these optional chains necessary?

2021-05-20 21:21 UTC, shlokamin commented on app/src/organisms/Alerts/__tests__/U2EDriverOutdatedAlert.test.tsx
> +    link.invoke('onClick')?.({} as React.MouseEvent)
this is being called with `{}` now rather than with nothing

2021-05-20 21:21 UTC, shlokamin commented on app/src/organisms/Alerts/__tests__/U2EDriverOutdatedAlert.test.tsx
> +    link.invoke('onClick')?.({} as React.MouseEvent)
same deal here

2021-05-20 21:21 UTC, shlokamin commented on app/src/organisms/Alerts/__tests__/U2EDriverOutdatedAlert.test.tsx
> +    wrapper.find('Link[to="/more/network-and-system"]').invoke('onClick')?.(
and here

2021-05-20 21:23 UTC, shlokamin commented on app/src/redux/analytics/types.ts
> +export type DeckCalibrationAnalyticsData = {
ya this was me i think, its really weird. @b-cooper pointed me to this: https://github.com/microsoft/TypeScript/issues/15300#issuecomment-332366024

2021-05-20 21:31 UTC, b-cooper commented on app/src/pages/More/AddLabwareCard/__tests__/AddLabwareCard.test.tsx
>      render = () =>
instead of typing use of provider, updated this test to use the new `mountWithStore` util

2021-05-20 21:39 UTC, b-cooper commented on app/src/pages/More/ListLabwareCard/LabwareItem.tsx
> +    <li className={cx(styles.item, { [styles.invalid]: Boolean(warning) })}>
this is a small source code change in order to allow `classnames` types to be satisfied, was truthiness-check, and now is truth-check

2021-05-20 21:41 UTC, b-cooper commented on app/src/pages/More/ListLabwareCard/__tests__/LabwareItem.test.tsx
> +    definition: undefined,
adding and explicit undefined here helps TS with a type that unions all of the different file possibilities, and `InvalidLabwareFile` is the only one without a definition key/value

2021-05-20 21:50 UTC, b-cooper commented on app/src/pages/Robots/ConnectPanel/index.tsx
> +  onScanClick: () => startDiscovery(),
slight code change here moving from the functional to object version of `mapDispatchToProps` satisfies the connect functions types without having to import other types from `react-redux`. Mostly a convenience change as all new connected components use the hooks api

2021-05-20 21:51 UTC, b-cooper commented on app/src/pages/Robots/InstrumentSettings/PipetteInfo.tsx
> +          wordSpacing={SIZE_6} // always one word to a lin
looks like the comment was accidentally trimmed here

2021-05-20 21:56 UTC, b-cooper commented on app/src/pages/Robots/ModuleSettings/ModuleItem/ModuleUpdate.tsx
> +    latestRequestId ? getRequestById(state, latestRequestId) : null
code changes here to be extra cautious that we don't pass a non-existent `latestRequestId` to anything that is expecting a real id.

2021-05-20 21:59 UTC, b-cooper commented on app/src/pages/Robots/RobotSettings/CheckCalibrationControl.tsx
> +        createRequestId.current =
code change here to protect against null accession on dispatched actions that don't have `.meta.requestId`

2021-05-20 22:05 UTC, b-cooper commented on app/src/pages/Robots/RobotSettings/DeckCalibrationControl.tsx
> +          'requestId' in dispatchedAction.meta
code change here to protect against null accession (in a typesafe way) on actions that don't have `.meta.requestId`

2021-05-20 22:08 UTC, b-cooper commented on app/src/pages/Robots/RobotSettings/ResetRobotModal.tsx
> +  const resetRequest = useSelector((state: State) => {
code change here to protect against getting the status off of a request that doesn't exist

2021-05-20 22:08 UTC, b-cooper commented on app/src/pages/Robots/RobotSettings/ResetRobotModal.tsx
> +            value={Boolean(resetOptions[o.id])}
code change here to explicitly give LabeledCheckbox the boolean that it's expecting

2021-05-20 22:12 UTC, b-cooper commented on app/src/pages/Robots/RobotSettings/SelectNetwork/ConnectModal/__tests__/ConnectModal.test.tsx
> +      formik.invoke('onSubmit')?.(mockValues, {} as any) // eslint-disable-line @typescript-eslint/no-floating-promises
Note this eslint disable  silencing a pretty useless (in this instance) warning for our usage of `formik.invoke()`

2021-05-20 22:15 UTC, b-cooper commented on app/src/pages/Robots/RobotSettings/SelectNetwork/ConnectModal/form-fields.ts
>      // NOTE(mc, 2020-03-13): Flow v0.119 unable to refine via consts
this comment no longer applies

2021-05-20 22:20 UTC, b-cooper commented on app/src/pages/Robots/RobotSettings/SelectNetwork/index.tsx
> +    const lastId = last(requestIds)
code change to protect against retrieving a request when the id doesn't exist

2021-05-20 22:22 UTC, b-cooper commented on app/src/pages/Robots/RobotSettings/UpdateBuildroot/InstallModal.tsx
> +  let heading: string = ''
slight code change here

2021-05-20 22:28 UTC, b-cooper commented on app/src/pages/Robots/RobotSettings/inputs.tsx
> -// @flow
fyi, this  file was entirely unused

2021-05-20 22:30 UTC, b-cooper commented on app/src/pages/Run/RunLog/CommandList.tsx
> +          [styles.executed]: Boolean(handledAt),
code change here to give classnames the boolean values that it's expecting, instead of just truthiness checking

2021-05-20 22:31 UTC, b-cooper commented on app/src/pages/Run/RunLog/SessionAlert.tsx
> +): string | JSX.Element | null | undefined =>
does this actually need `string` in its return type?

2021-05-20 22:33 UTC, b-cooper commented on app/src/pages/Upload/FileInfo/Continue.tsx
> +        className={cx({ disabled: Boolean(disabledReason) })}
code change to give `classnames` the boolean that it's expecting instead of relying on truthiness

2021-05-20 22:35 UTC, b-cooper commented on app/src/pages/Upload/FileInfo/ProtocolPipettesCard.tsx
> +            itemProps && (
code change to protect against accessing `itemProps` internals when it is `null`

2021-05-20 22:37 UTC, b-cooper commented on app/src/pages/Upload/UploadPanel/Upload.tsx
> +    if ('dataTransfer' in event && event.dataTransfer.files) {
slight code change in these conditionals to allow TS to tap into implicit type narrow

2021-05-20 22:38 UTC, b-cooper commented on app/src/pages/Upload/UploadPanel/Upload.tsx
> +    if ('value' in event.currentTarget) event.currentTarget.value = ''
this change addresses the existing FlowFixMe

2021-05-20 22:40 UTC, b-cooper commented on app/src/pages/Upload/UploadPanel/index.tsx
> +  // @ts-expect-error TODO: thunk action messes up react-redux mapDispatchToProps type, should use hooks api here anyway
this is a particularly unfortunate `@ts-expect-error` though I feel less bad as this will be removed soon during the Labware Calibration Overhaul

2021-05-21 13:52 UTC, IanLondon commented on app/src/redux/buildroot/__tests__/selectors.test.ts
> +import * as discoSelectors from '../../discovery/selectors'
🕺

2021-05-21 16:33 UTC, mcous reviewed
Sitting at 350 out of 835 files reviewed, got a nice batch of source code changes that I'd like to revert for safety given out conversion best practices

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CalibratePipetteOffset/useCalibratePipetteOffset.tsx
> +          'requestId' in dispatchedAction.meta
Source code changes

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CalibrateTipLength/__tests__/CalibrateTipLength.test.tsx
> +  [key: string]: unknown
Unused I think

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CalibrateTipLength/__tests__/CalibrateTipLength.test.tsx
> +  childProps?: {}
Unused from the looks of it

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CalibrateTipLength/index.tsx
> +  [step in CalibrationSessionStep]?: React.ComponentType<CalibrationPanelProps>
Looks like this could be a Partial Record

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CalibrateTipLength/index.tsx
> +  const Panel = currentStep != null ? PANEL_BY_STEP[currentStep] : null
Source code change

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CalibrationPanels/ChooseTipRack.tsx
> +      robotName && getAttachedPipettes(state, robotName)[mount]?.id
Source code change

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CalibrationPanels/ChooseTipRack.tsx
> +      handleChosenTipRack(selectedTipRack?.definition ?? null)
Source code change

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CalibrationPanels/CompleteConfirmation.tsx
> +    lookupType in contentsBySessionType
Source code change

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CalibrationPanels/SaveXYPoint.tsx
> +  const contents =
Source code change

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CalibrationPanels/SaveXYPoint.tsx
> +          <source src={String(demoAsset)} />
Source code change

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CalibrationPanels/SaveZPoint.tsx
> +  const contents =
Source code change

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CalibrationPanels/SaveZPoint.tsx
> +  [sessionType in SessionType]?: {
Partial record?

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CalibrationPanels/__tests__/CompleteConfirmation.test.tsx
> +        pipMount = 'left' as Mount,
`as const` _might_ work here, too

2021-05-21 16:33 UTC, mcous commented on app/src/redux/shell/remote.ts
> +        `Expected APP_SHELL_REMOTE.${String(
What's with this `String`? `propName` is already typed `string`, isn't it?

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CalibrationPanels/useConfirmCrashRecovery.tsx
> +): [React.ReactNode, React.ReactNode] {
Nice opportunity for a TypeScript [labeled tuple](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#labeled-tuple-elements) here

```suggestion
): [message: React.ReactNode, modal: React.ReactNode] {
```

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/ChangePipette/CheckPipettesButton.tsx
> +      'requestId' in dispatchedAction.meta
Source code changes

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/ChangePipette/index.tsx
> +        'requestId' in dispatchedAction.meta
Source code changes

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CheckCalibration/ResultsSummary.tsx
> +              {calibrationsByMount[m].pipette != null &&
Source code changes

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CheckCalibration/ResultsSummary.tsx
> +  ].reduce((sum, item) => sum + (item ? 1 : 0), 0)
Minor source code change

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CheckCalibration/ThresholdValue.tsx
> +  const formattedValue = parseFloat(String(value)).toFixed(1)
Source code change

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CheckCalibration/__tests__/CheckCalibration.test.tsx
> +type CheckCalibrationSpec = Partial<{
Why is this Partial?

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CheckCalibration/__tests__/CheckCalibration.test.tsx
> +  childProps?: {}
Is this used?

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/CheckCalibration/index.tsx
> +  const Panel = currentStep != null ? PANEL_BY_STEP[currentStep] : null
Source code change

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/ConfigurePipette/ConfigForm.tsx
> +        [name]: value,
Source code change

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/ConfigurePipette/ConfigForm.tsx
> +      return f.value !== f.default ? f.value?.toString() ?? '' : ''
Source code change

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/ConfigurePipette/index.tsx
> +    return lastId ? getRequestById(state, lastId) : null
Source code change

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/ConfigurePipette/index.tsx
> +      ? 'message' in updateRequest.error && updateRequest.error.message != null
Source code change

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/ProtocolModuleList/index.tsx
> +        justifyContent={!hasDuplicateModule ? JUSTIFY_SPACE_BETWEEN : undefined}
Source code change

2021-05-21 16:33 UTC, mcous commented on app/src/organisms/ProtocolModuleList/index.tsx
> +                !hasDuplicateModule ? JUSTIFY_SPACE_BETWEEN : undefined
Source code change

2021-05-21 16:33 UTC, mcous commented on app/src/pages/Calibrate/CalibrateTipLengthControl.tsx
> +        createRequestId.current =
Regardless, I think we should revert these changes. There don't appear to be any tests covering this logic, unless I'm missing something

2021-05-21 16:33 UTC, mcous commented on app/src/pages/Calibrate/UncalibratedInfo.tsx
> +  [key: string]: unknown
Is this needed?

2021-05-21 16:33 UTC, mcous commented on app/src/redux/custom-labware/types.ts
> +  definition: undefined
This feels like a weird thing to do. I'd rather throw a `@ts-expect-error` TODO in `app/src/pages/More/ListLabwareCard/LabwareItem.tsx` to get at the definition differently than add a weird explicitly undefined property here

2021-05-21 16:33 UTC, mcous commented on app/src/pages/More/ListLabwareCard/__tests__/LabwareItem.test.tsx
> +    definition: undefined,
Not a huge fan of this. See comment on `InvalidLabwareFile` interface

2021-05-21 16:33 UTC, mcous commented on app/src/pages/More/SystemInfoCard/__tests__/U2EDriverWarning.test.tsx
> +  const trackEvent: ReturnType<
```suggestion
  const trackEvent: jest.MockedFunction<
```

2021-05-21 17:03 UTC, celsasser commented on app/src/assets/labware/findLabware.ts
> +  customLabware: LabwareDefinition2[]
How do you guys feel about the use of Readonly? For example (this guy could get kind of deep), `customLabware: ReadonlyArray<Readonly<LabwareDefinition2>>`. I love the information it gives both the developer and the compiler.

2021-05-21 20:29 UTC, mcous reviewed
515 of out 835 files reviewed

2021-05-21 20:29 UTC, mcous commented on app/src/pages/Robots/ConnectPanel/index.tsx
> +  onScanClick: () => startDiscovery(),
Why make this code change? We don't have test coverage of this component, I think we should revert

2021-05-21 20:29 UTC, mcous commented on app/src/pages/Robots/ModuleSettings/ModuleItem/ModuleUpdate.tsx
> +    latestRequestId ? getRequestById(state, latestRequestId) : null
I think we should revert; don't have any test coverage

2021-05-21 20:29 UTC, mcous commented on app/src/pages/Robots/ModuleSettings/ModuleItem/ModuleUpdate.tsx
> +    if (latestRequestId != null) {
Code change

2021-05-21 20:29 UTC, mcous commented on app/src/pages/Robots/ModuleSettings/ModuleItem/ModuleUpdate.tsx
> +              {latestRequest.error != null
Code change

2021-05-21 20:29 UTC, mcous commented on app/src/pages/Robots/RobotSettings/CheckCalibrationControl.tsx
> +        createRequestId.current =
Would like to revert

2021-05-21 20:29 UTC, mcous commented on app/src/pages/Robots/RobotSettings/DeckCalibrationControl.tsx
> +        jogRequestId.current =
Source code change

2021-05-21 20:29 UTC, mcous commented on app/src/pages/Robots/RobotSettings/DeckCalibrationControl.tsx
> +        trackedRequestId.current =
Source change

2021-05-21 20:29 UTC, mcous commented on app/src/pages/Robots/RobotSettings/DeckCalibrationControl.tsx
> +      'source' in data && typeof data?.source === 'string'
Source change

2021-05-21 20:29 UTC, mcous commented on app/src/pages/Robots/RobotSettings/DeckCalibrationControl.tsx
> +              {createRequest != null &&
Source change

2021-05-21 20:29 UTC, mcous commented on app/src/pages/Robots/RobotSettings/SelectNetwork/ConnectModal/KeyFileField.tsx
> +      uploadKeyRef.current && uploadKeyRef?.current?.click()
Source code change

2021-05-21 20:29 UTC, mcous commented on app/src/pages/Robots/RobotSettings/SelectNetwork/index.tsx
> +                'error' in requestState &&
Source code change

2021-05-21 20:29 UTC, mcous commented on app/src/pages/Robots/RobotSettings/SelectNetwork/index.tsx
> +    const lastId = last(requestIds)
Minor source code change

2021-05-21 20:29 UTC, mcous commented on app/src/pages/Robots/RobotSettings/UpdateFromFileControl.tsx
>        // NOTE: File.path is Electron-specific
At some point could augment the File interface to get rid of the `any` below

2021-05-21 20:29 UTC, mcous commented on app/src/pages/Run/RunLog/CommandList.tsx
> +    if (this.refs.ensureVisible)
Should add some braces here I think

2021-05-21 20:29 UTC, mcous commented on app/src/pages/Run/RunPanel/RunControls.tsx
> +      {isConfirmCancelOpen ? (
Source code change

2021-05-21 20:29 UTC, mcous commented on app/src/pages/Upload/FileInfo/InstrumentItem.tsx
> +  const match = compatibility
Source code change

2021-05-21 20:29 UTC, mcous commented on app/src/pages/Upload/UploadPanel/UploadInput.tsx
> +        iconName: 'ot-file' as React.ComponentProps<
This feels like it should be the type `IconName`

2021-05-21 20:29 UTC, mcous commented on app/src/pages/Upload/UploadPanel/UploadInput.tsx
> +        Component: 'label' as React.ComponentProps<
Is this needed? Isn't the type of the `Component` set to `any`?

2021-05-21 20:29 UTC, mcous commented on app/src/redux/alerts/reducer.ts
> +export const alertsReducer: Reducer<AlertsState, Action> = (state, action) => {
Agree, I think we should revert the `state = state ?? INITIAL_STATE` changes in favor of downgrading the lint rule until we can take a consistent crack at this outside a TS conversion PR

2021-05-21 20:29 UTC, mcous commented on app/src/redux/analytics/constants.ts
>  export const ANALYTICS_PIPETTE_OFFSET_STARTED: 'analytics:PIPETTE_OFFSET_STARTED' =
They are not required, but it might be nice to leave them alone in this PR for the sake of the diff because they're not hurting anything.

In the library PRs, they were important to preserve this way for the Flow conversion, but that's not in play here

2021-05-21 20:29 UTC, mcous commented on app/src/redux/analytics/hash.ts
> +  // TODO (sa 2021-05-19): probably should not be using the crypto module from global, use node module instead
Not sure about this comment, is there a problem using [built-in window.crypto](https://developer.mozilla.org/en-US/docs/Web/API/Window/crypto)?

2021-05-21 20:29 UTC, mcous commented on app/src/redux/analytics/make-event.ts
> +                      tipRackDisplayName:
Not sure I see a test case for missing tiprackDefinition in `commandData`, if that's true I'd ask to revert

2021-05-21 20:29 UTC, mcous commented on app/src/redux/analytics/mixpanel.ts
> +    if ('name' in event) mixpanel.track(event.name, event.properties)
No test coverage here, may want to revert

2021-05-24 14:23 UTC, b-cooper commented on app/src/pages/Upload/UploadPanel/UploadInput.tsx
> +        iconName: 'ot-file' as React.ComponentProps<
I believe that's exactly what `React.ComponentProps<typeof PrimaryButton>['iconName']` resolves to

2021-05-24 14:31 UTC, celsasser commented
Is it possible to break up this PR? It's hard to review. Physically and mentally. Sometimes it times out for me. Sometimes the browser gives up his ghost and won't let me comment. Kind of thinking that javascript is a subset of typescript...could we maybe break it apart into multiple PRs with conceptual groupings? And with those little PRs make sure we are adopting the TS practices that we all agree on (please correct me if we already have a formal best practices document).

2021-05-24 14:35 UTC, celsasser commented on app/src/assets/labware/getLabware.ts
> +let labwareSchemaV2Defs: LabwareDefinition2[] | null = null
Why don't we like `ReadonlyArray`?

2021-05-24 14:43 UTC, b-cooper commented on app/src/redux/alerts/selectors.ts
> +) => null | AlertId[] = createSelector(
Yes this was a conscious decision for the reason you outlined.  Elsewhere in the TS migration push, we've opted for removing Readonly for now in places where the TS readonly types would have cascading effects across the project, in a way that the flow readonly types didn't.

2021-05-24 14:56 UTC, celsasser commented on app/src/atoms/structure/LabeledValue.tsx
> +  label: string | React.ReactNode
I am sure there are, but just checking that there are use cases in which a label and value can be either?

2021-05-24 15:29 UTC, celsasser commented on app/src/i18n.ts
> +    missingKeyHandler: (lng, ns, key, _fallbackValue) => {
Wondering whether these params should be strongly typed and wondering why `fallback` is underscored (and not used).

2021-05-24 15:30 UTC, celsasser commented on app/src/i18n.ts
> +  (err, _t) => {
Same question as above. Is underscore used for unused properties?  Can we get rid of them?

2021-05-24 15:32 UTC, celsasser commented on app/src/logger.ts
>  export type Log = (message: string, meta?: {}) => void
Very nitpicky but it's a little confusing to me when `log` is both used as a noun (as in the log to which stuff is going) and a verb as it is here (please log the following to the log)

2021-05-24 15:35 UTC, celsasser commented on app/src/molecules/DeckMap/LabwareItem.tsx
> +  let title: string
Should his pals below be typed?

2021-05-24 15:37 UTC, celsasser commented on app/src/molecules/DeckMap/index.tsx
> +  labwareBySlot?: { [slot: string]: Labware[] | undefined }
Is there value in having undefined properties? I mean, could se just not add them (or remove them) if they have no value?

2021-05-24 15:41 UTC, celsasser commented on app/src/molecules/DeckMap/index.tsx
> +  labwareBySlot?: { [slot: string]: Labware[] | undefined }
I may be wrong but looking here it looks like a slot will always have a value - https://github.com/Opentrons/opentrons/pull/7550/files#diff-f35253ef3be66aa09e55725af44f8c776045b989a2487d86caa4ab98e509f856R158?

2021-05-24 15:44 UTC, celsasser commented on app/src/molecules/DeckMap/index.tsx
> +  modulesBySlot?: { [slot: string]: DisplayModule | undefined }
Same comment as above for `modulesBySlot` - https://github.com/Opentrons/opentrons/pull/7550/files#diff-f35253ef3be66aa09e55725af44f8c776045b989a2487d86caa4ab98e509f856R132

2021-05-24 15:53 UTC, celsasser commented on app/src/molecules/JogControls/DirectionControl.tsx
> +  axis: 'x' | 'y' | 'z'
Do we want to be consistent and use predefined types - `Axis`?

2021-05-24 16:30 UTC, celsasser commented on app/src/assets/labware/findLabware.ts
> +  customLabware: LabwareDefinition2[]
See this was answered elsewhere. Nonetheless wondering whether it is an ambition?

2021-05-24 16:31 UTC, celsasser commented on app/src/assets/labware/getLabware.ts
> +let labwareSchemaV2Defs: LabwareDefinition2[] | null = null
Answered elsewhere.

2021-05-24 18:31 UTC, IanLondon reviewed
Can't comment on the diff about this but: `app/src/redux/protocol/__tests__/*.test.js` has 3 un-typescript-ified `.js` files 🤔

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/buildroot/actions.ts
> +): BuildrootStatusAction {
type change, but it looks like this is more precise

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/buildroot/epic.ts
> +        // @ts-expect-error TODO: host is actually of type Robot|ReachableRobot but this action expects a RobotHost
this file has a lot of `ts-expect-error`s, do these TODOs (here and below) deserve a follow-up ticket so that they don't get lost? Up to you all!

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/buildroot/reducer.ts
> +  state = state ?? INITIAL_STATE
Same comment as other reducers, if the state is ever allowed to be null (now or in the future) this won't work as expected

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/calibration/labware/actions.ts
> +  meta: {} as RobotApiRequestMeta,
`{}` is not a valid `RobotApiRequestMeta`, should there be a todo/ticket?

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/calibration/pipette-offset/actions.ts
> +  meta: {} as RobotApiRequestMeta,
same deal as above, not a valid `RobotApiRequestMeta`, might merit a ticket

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/calibration/pipette-offset/epic/fetchPipetteOffsetCalibrationsOnConnect.ts
> +      // @ts-expect-error TODO: something is wrong here robotName will be a tuple
ticket?

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/calibration/reducer.ts
> +  state = state ?? INITIAL_STATE
same real with `??` and `null`

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/calibration/tip-length/actions.ts
> +  meta: {} as RobotApiRequestMeta,
same deal, `{}` not a valid `RobotApiRequestMeta`

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/config/reducer.ts
> +  // eslint-disable-next-line @typescript-eslint/default-param-last
same comment, here the initial state is `null` and the `state = state ?? initialState` pattern doesn't work

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/config/schema-types.ts
> +export interface ConfigV0 {
dunno if losing the `$ReadOnly`s in this file is an undesirable thing here?

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/custom-labware/__fixtures__/index.ts
> +  definition: undefined,
code change, but seems correct?

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/custom-labware/__tests__/actions.test.ts
> +            definition: undefined,
code change, seems OK?

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/custom-labware/reducer.ts
> +  state = state ?? INITIAL_STATE
some comment, same pattern

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/custom-labware/selectors.ts
> +// @ts-expect-error(sa, 2021-05-11): TS unable to do type refinements via filter
could follow the pattern of `is` operator for filters?

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/custom-labware/selectors.ts
> +//  @ts-expect-error(sa, 2021-05-11): filesByName[name] might be undefined because filesByName is typed as a partial type
follow up / ticket?

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/discovery/constants.ts
>  export const CONNECTABLE: 'connectable' = 'connectable'
same comment about explicit annotation of string consts not being unnecessary

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/discovery/epic.ts
> +        'payload' in startAction && startAction.payload != null
code change, looks OK

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/discovery/epic.ts
> +// TODO(bc, 2021-05-17): nuke this epic, it is now dead code, functionality is covered by resartEpic in robot-admin
ticket?

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/modules/__fixtures__/index.ts
> +  method: 'GET' as Method,
tested, it seems like it's fine to remove these `as Method` annotations, here and L292, not sure what they're doing?

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/modules/epic/fetchModulesEpic.ts
> +  if ('moduleModel' in response) {
code change, looks safe

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/modules/selectors.ts
> +  ): { [moduleId: string]: Types.AttachedModule } =>
it might be more readable to factor this inner fn out, though factoring that out would be a code change

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/networking/reducer.ts
> +  state = state ?? INITIAL_STATE
same comment, `??` operator vs default arg

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/networking/reducer.ts
> +      const requestId =
code change, looks OK

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/networking/types.ts
> +  meta: RobotApiRequestMeta | {}
what's going on here with `meta`? There was some `meta` weirdness, maybe some `ts-expect-error`s above I think

at the least, just to be DRY we probably shouldn't do `RobotApiRequestMeta | {}` multiple times but instead define that as a type and reuse that new type, if we have to

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/pipettes/selectors.ts
> +            ? getPipetteModelSpecs(attached.model as PipetteModel)
hmm this is bc `PipetteModelSpecs` isn't typed with `model: PipetteModel`, rather it's (incorrectly?) string. But could be outside the scope of this PR, it's in `shared-data`

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/pipettes/selectors.ts
> +  return Boolean(
code change, but looks like the one place this fn is called is just doing truthy check so should be fine

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/pipettes/selectors.ts
> +    return Constants.PIPETTE_MOUNTS.reduce<Types.ProtocolPipetteInfoByMount>(
trivial nitpick: it's weird to read the return right after `pipetteHasOffset` is defined without `{}`, at first I thought some strange syntax was going on with `=> Boolean(...) return`

2021-05-24 18:31 UTC, IanLondon commented on app/src/redux/pipettes/selectors.ts
> +          ? getPipetteNameSpecs(requestedAs as PipetteName)?.displayName
should `StatePipette.requestedAs` be `PipetteName` type? Or (eventually) should we check that `requestedAs` string is a valid `PipetteName` somewhere?

2021-05-24 18:59 UTC, shlokamin commented on app/src/organisms/AnalyticsSettingsModal/AnalyticsToggle.tsx
> +  toggleOptedIn: () => toggleAnalyticsOptedIn(),
code change — we still need to dispatch this action right?

2021-05-24 18:59 UTC, shlokamin commented on app/src/organisms/CalibratePipetteOffset/__tests__/useCalibratePipetteOffset.test.tsx
> +      .invoke('onClick')?.({} as React.MouseEvent)
invoking with {} instead of nothing, this to me is a different test

2021-05-24 18:59 UTC, shlokamin commented on app/src/organisms/CalibratePipetteOffset/useCalibratePipetteOffset.tsx
> +export type Invoker = (props: InvokerProps | undefined) => void
can this just be an optional prop? i know TS treats `undefined` as an actual value, (i.e. not the same as "nothing")

2021-05-24 18:59 UTC, shlokamin commented on app/src/organisms/CalibratePipetteOffset/useCalibratePipetteOffset.tsx
> +    Partial<Omit<PipetteOffsetCalibrationSessionParams, 'mount'>>,
this is a bit different than what was there before right? wouldn't it just be 
```js
sessionParams: Partial<PipetteOffsetCalibrationSessionParams>?
```
unless what's here is intentionally more specific (and safe!)

2021-05-24 18:59 UTC, shlokamin commented on app/src/organisms/CalibratePipetteOffset/useCalibratePipetteOffset.tsx
> +            : null
code changes, but they look fine

2021-05-24 18:59 UTC, shlokamin commented on app/src/organisms/CalibrateTipLength/index.tsx
> +  return currentStep != null && Panel ? (
code change

2021-05-24 18:59 UTC, shlokamin commented on app/src/organisms/CalibrateTipLength/index.tsx
> +        // @ts-expect-error TODO: ConfirmExitModal expects sessionType
we should probably make `sessionType` in `ConfirmExitModalProps` optional

2021-05-24 18:59 UTC, shlokamin commented on app/src/organisms/CalibrationPanels/ChooseTipRack.tsx
> +      robotName && getAttachedPipettes(state, robotName)[mount]?.id
code change

2021-05-24 18:59 UTC, shlokamin commented on app/src/organisms/CalibrationPanels/ChooseTipRack.tsx
> +      handleChosenTipRack(selectedTipRack?.definition ?? null)
code change

2021-05-24 18:59 UTC, shlokamin commented on app/src/organisms/CalibrationPanels/ChosenTipRackRender.tsx
> +  )[1] as any
woa, this is interesting.i didnt know you could force typescript into thinking an object is a specific type this way

2021-05-24 18:59 UTC, shlokamin commented on app/src/organisms/CalibrationPanels/CompleteConfirmation.tsx
> +      : null
code change

2021-05-24 18:59 UTC, shlokamin commented on app/src/organisms/CalibrationPanels/DeckSetup.tsx
> +  [st in SessionType]: {
could change to `Record` depending on readability preferences

2021-05-24 18:59 UTC, shlokamin commented on app/src/organisms/CalibrationPanels/Introduction.tsx
> +        .reduce<React.ReactNode[]>((prev, current) => [prev, ' ', current], [])}
code change?

2021-05-24 18:59 UTC, shlokamin commented on app/src/organisms/CalibrationPanels/SaveXYPoint.tsx
> +    [mount in Mount]: { [channels in 'multi' | 'single']: string }
nit pick: could use `Record`

2021-05-24 18:59 UTC, shlokamin commented on app/src/organisms/CalibrationPanels/__tests__/ConfirmCrashRecoveryModal.test.tsx
> +    getExitButton(wrapper).invoke('onClick')?.({} as React.MouseEvent)
calling this with `{}` instead of nothing

2021-05-24 18:59 UTC, shlokamin commented on app/src/organisms/CalibrationPanels/__tests__/ConfirmCrashRecoveryModal.test.tsx
> +    getNoTipRestartButton(wrapper).invoke('onClick')?.({} as React.MouseEvent)
calling this with {} instead of nothing

2021-05-24 19:06 UTC, b-cooper commented on app/src/redux/analytics/selectors.ts
> +  return instruments.reduce<CalibrationCheckByMount>(
The only change, aside from formatting, that I see is the casting of key `k as keyof ...`. Am I missing an actual code change?

2021-05-24 19:28 UTC, b-cooper commented on app/src/redux/analytics/types.ts
> +  [ffName: string]: boolean | string
I believe it is actually more correct after referencing the `getRobotAnalyticsData` selector which returns a reduced object with an initial value of 
```
{
        robotApiServerVersion: getRobotApiVersion(robot) || '',
        robotSmoothieVersion: getRobotFirmwareVersion(robot) || '',
        robotLeftPipette: pipettes.left?.model || '',
        robotRightPipette: pipettes.right?.model || '',
}
``` 

All of these are string values. If anyone is worried about this as a source change, I'm happy to revert it and replace it with ts-expect-errors

2021-05-24 20:35 UTC, IanLondon requested changes
`app/src/redux/robot/api-client/__tests__/create-sessions.test.js` and `app/src/redux/robot/api-client/client.js` are `.js` not `.ts` ??

2021-05-24 20:35 UTC, IanLondon commented on app/src/redux/protocol/selectors.ts
> +          // @ts-expect-error(sa, 2021-05-12): data has been type narrowed to be Readonly<ProtocolFileV3<{}>>, which does not have modules
ticket to fix it?

2021-05-24 20:35 UTC, IanLondon commented on app/src/redux/protocol/selectors.ts
> +  if (data !== null && 'metadata' in data && 'source' in data.metadata) {
code changes in this selector

2021-05-24 20:35 UTC, IanLondon commented on app/src/redux/robot-admin/__tests__/reducer.test.ts
> +      meta: {} as RobotApiRequestMeta,
more weird `meta`

2021-05-24 20:35 UTC, IanLondon commented on app/src/redux/robot-admin/actions.ts
> +  meta: RobotApiRequestMeta | {}
more `MetaType | {}`, see earlier comment

2021-05-24 20:35 UTC, IanLondon commented on app/src/redux/robot-admin/reducer.ts
> +  state = state ?? INITIAL_STATE
same comment about reducer initial state

2021-05-24 20:35 UTC, IanLondon commented on app/src/redux/robot-admin/reducer.ts
> +      // @ts-expect-error TODO: guard type better here, don't do default destructing
:+1:

2021-05-24 20:35 UTC, IanLondon commented on app/src/redux/robot-api/__tests__/hooks.test.tsx
> +    wrapper.find('button').invoke('onClick')?.({} as React.MouseEvent)
weird, are the enzyme types wrong / too strict?

also just noting that this file has code changes;`()` to `?.()`

2021-05-24 20:35 UTC, IanLondon commented on app/src/redux/robot-api/helpers.ts
> +  if ('message' in response) {
code change here and below, seems OK as long as `message` wasn't ever `''`

2021-05-24 20:35 UTC, IanLondon commented on app/src/redux/robot-api/http.ts
> +  const options: RequestInit = {
type change?

2021-05-24 20:35 UTC, IanLondon commented on app/src/redux/robot-api/reducer.ts
> +  // eslint-disable-next-line @typescript-eslint/default-param-last
same old reducer default arg comment

2021-05-24 20:35 UTC, IanLondon commented on app/src/redux/robot-api/reducer.ts
> +  // @ts-expect-error(sa, 2021-05-17): type guard action.meta
more `meta` issues possibly related to comments above

2021-05-24 20:35 UTC, IanLondon commented on app/src/redux/robot-api/types.ts
> +export type RobotApiV2ResponseData = Partial<{ id: string }>
when to use `Partial<{ someKey: SomeType }>` versus `{ someKey: SomeType; [otherKeys: string]: unknown }`? So far I've seen the latter pattern when migrating from Flow explicit inexact obj (Flow example: `{someKey: SomeType, ...}`)

2021-05-24 20:35 UTC, IanLondon commented on app/src/redux/robot-controls/actions.ts
> +  meta: {} as RobotApiRequestMeta,
more weird `meta`

2021-05-24 20:35 UTC, IanLondon commented on app/src/redux/robot-controls/reducer.ts
> +  state = state ?? INITIAL_STATE
same old comment, reducer initial state

2021-05-24 20:35 UTC, IanLondon commented on app/src/redux/robot-controls/types.ts
> +  meta: RobotApiRequestMeta | {}
more weird `meta` with `| {}`, though many types below are OK without the `| {}`

2021-05-24 20:35 UTC, IanLondon commented on app/src/redux/robot-settings/reducer.ts
> +  state = state ?? INITIAL_STATE
another reducer initial state code change

2021-05-24 20:35 UTC, IanLondon commented on app/src/redux/robot/actions.ts
> +export const actionTypes: Record<string, any> = {
could this whole object be `as const`?

2021-05-24 20:35 UTC, IanLondon commented on app/src/redux/robot/api-client/index.ts
> +  // @ts-expect-error: make this `meta` access happier for TS
more `meta` probs

2021-05-24 21:17 UTC, IanLondon requested changes
another `.js`: `app/src/redux/robot/api-client/worker.js`

aand, finished first pass reviewing all the files in `app/src/redux`

2021-05-24 21:17 UTC, IanLondon commented on app/src/redux/robot/reducer/calibration.ts
>      // TODO(mc, 20187-01-26): caution - not covered by flow yet
now not covered by TS?

2021-05-24 21:17 UTC, IanLondon commented on app/src/redux/robot/reducer/calibration.ts
> +  state = state ?? INITIAL_STATE
same comment about initial state

2021-05-24 21:17 UTC, IanLondon commented on app/src/redux/robot/reducer/index.ts
> +// TODO: (sa 2021-15-18: remove any typed state in combineReducers)
ticket?

2021-05-24 21:17 UTC, IanLondon commented on app/src/redux/robot/selectors.ts
> +  return Constants.PIPETTE_MOUNTS.includes(target as Mount)
code change 🤔

2021-05-24 21:17 UTC, IanLondon commented on app/src/redux/robot/selectors.ts
> +  return Constants.DECK_SLOTS.includes(target as Slot)
code change 🤔 similar to above

2021-05-24 21:17 UTC, IanLondon commented on app/src/redux/robot/selectors.ts
> +    status === ('running' as SessionStatus) ||
are these strings not valid `SessionStatus`?

2021-05-24 21:17 UTC, IanLondon commented on app/src/redux/robot/selectors.ts
> +        modelSpecs: getPipetteModelSpecs(pipette?.name as PipetteModel) || null,
code changes

2021-05-24 21:17 UTC, IanLondon commented on app/src/redux/robot/selectors.ts
> +            ? instByMount[a.calibratorMount as Mount]?.channels ?? 0
code changes

2021-05-24 21:17 UTC, IanLondon commented on app/src/redux/robot/test/actions.test.ts
> +    // eslint-disable-next-line @typescript-eslint/consistent-type-assertions
lint-friendly equivalent to `const update: SessionUpdate = { state: 'running', startTime: 1 } as any` ?

2021-05-24 21:17 UTC, IanLondon commented on app/src/redux/sessions/actions.ts
> +  meta: {} as RobotApiRequestMeta,
`meta` strikes again

2021-05-24 21:17 UTC, IanLondon commented on app/src/redux/sessions/calibration-check/types.ts
> +  model: PipetteModel
type change, but seems OK

2021-05-24 21:17 UTC, IanLondon commented on app/src/redux/sessions/epic/clearAllSessionsOnDisconnectEpic.ts
> -      console.log(robotName)
code change but seems good to do

2021-05-24 21:17 UTC, IanLondon commented on app/src/redux/sessions/epic/fetchAllSessionsOnConnectEpic.ts
> +      const [, robotName] = args
code change

2021-05-24 21:17 UTC, IanLondon commented on app/src/redux/sessions/types.ts
> +  | {}
does `| {}` have the same meaning as `| {||}`?

2021-05-24 21:17 UTC, IanLondon commented on app/src/redux/sessions/types.ts
> +  meta: RobotApiRequestMeta | {}
more meta biz

2021-05-24 21:17 UTC, IanLondon commented on app/src/redux/shell/reducer.ts
> +// TODO: (sa 2021-15-18: remove any typed state in combineReducers)
I might have said this but, should there be a ticket to deal with `combineReducers<any, ....`?

2021-05-24 21:17 UTC, IanLondon commented on app/src/redux/support/__tests__/profile.test.ts
> +      'App Version': process.env.OT_APP_VERSION,
source code change, also seems to be related to Mike's comment about about OT_APP_VERSION

2021-05-25 14:28 UTC, shlokamin reviewed
after this review i'll have checked all of the molecules and organisms

2021-05-25 14:28 UTC, shlokamin commented on app/src/organisms/ConfigurePipette/ConfigErrorBanner.tsx
> +}
i think these are slightly different right?

2021-05-25 16:25 UTC, b-cooper commented on app/src/redux/alerts/epic.ts
> +      (a: Action): a is AlertDismissedAction =>
Looping back from offline conversation. There is a place for these kinds of user specified type predicates. This article does a good job of laying it out https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates

2021-05-25 16:52 UTC, b-cooper commented on app/src/redux/shell/epic.ts
> +    // @ts-expect-error TODO: don't use fromEvent and ipcRenderer type should work properly
```
Argument of type '{ send: (s: string, ...args: unknown[]) => void; }' is not assignable to parameter of type 'FromEventTarget<Action>'.
      Type '{ send: (s: string, ...args: unknown[]) => void; }' is not assignable to type 'ArrayLike<EventTargetLike<Action>>'.ts(2769)
```

2021-05-26 15:00 UTC, b-cooper commented on app/src/redux/buildroot/epic.ts
> +        // @ts-expect-error TODO: host is actually of type Robot|ReachableRobot but this action expects a RobotHost
made a ticket [here](https://github.com/Opentrons/opentrons/issues/7839) !

2021-05-26 15:15 UTC, b-cooper commented on app/src/redux/calibration/pipette-offset/epic/fetchPipetteOffsetCalibrationsOnConnect.ts
> +      // @ts-expect-error TODO: something is wrong here robotName will be a tuple
#7840

2021-05-26 15:23 UTC, shlokamin commented on app/src/organisms/Alerts/__tests__/Alerts.test.tsx
> +    wrapper.find(U2EDriverOutdatedAlert).invoke('dismissAlert')?.(true)
gonna keep em because we're asserting that the invoke went through. if we dont get through the optional chain the test would fail

2021-05-26 15:26 UTC, b-cooper commented on app/src/redux/discovery/epic.ts
> +        'payload' in startAction && startAction.payload != null
Reverted this one to be safe

2021-05-26 16:44 UTC, shlokamin commented on app/src/organisms/AnalyticsSettingsModal/index.tsx
> +  return !seen ? (
as per discussion in slack going to keep this
https://opentrons.slack.com/archives/C0239CHEHU0/p1622042385004900

2021-05-26 19:56 UTC, b-cooper commented on app/src/organisms/ConfigurePipette/ConfigErrorBanner.tsx
> +}
I believe these are actually functionally identical. Unless I'm mistaken, `message: ?string` in flow equates directly to `message: string | null | undefined` in TS.  and further that last `... | undefined` can be replaced by `message?: ...` on the index.

2021-05-26 19:59 UTC, b-cooper commented on app/src/redux/robot/reducer/calibration.ts
>      // TODO(mc, 20187-01-26): caution - not covered by flow yet
updated the comment

2021-05-27 16:07 UTC, b-cooper commented on app/src/redux/sessions/types.ts
> +  | {}
I believe it does, as TS object types are exact by default.

2021-05-27 16:20 UTC, b-cooper commented on app/src/redux/pipettes/selectors.ts
> +            ? getPipetteModelSpecs(attached.model as PipetteModel)
I'll add a todo in shared-data within this PR.

2021-05-27 16:31 UTC, b-cooper commented on app/src/redux/pipettes/selectors.ts
> +          ? getPipetteNameSpecs(requestedAs as PipetteName)?.displayName
I think at some point that's probably a good idea, luckily we'll be touching some of this code soon with the pre-run flow updates.

2021-05-27 17:25 UTC, IanLondon commented on app/src/atoms/structure/LabeledValue.tsx
> +  label: string | React.ReactNode
`React.ReactNode` includes `string` in its union, so this is redundant anyway

2021-05-27 18:04 UTC, IanLondon commented on app/src/pages/Run/RunLog/SessionAlert.tsx
> +): string | JSX.Element | null | undefined =>
It does, `Unexpected nullable string value in conditional. Please handle the nullish/empty cases explicitly.eslint@typescript-eslint/strict-boolean-expressions` unless we do a code change for a ternary

2021-05-27 20:15 UTC, shlokamin commented on app/src/organisms/CalibrationPanels/Introduction.tsx
> +        .reduce<React.ReactNode[]>((prev, current) => [prev, ' ', current], [])}
well this one kinda sucks...

Without passing an initial value into reduce and using generic typing, there is no way to tell TS that the reduced value is of a different type than the acc and val. gonna leave a comment and revert :/

2021-05-27 20:31 UTC, b-cooper commented on app/src/organisms/CalibratePipetteOffset/useCalibratePipetteOffset.tsx
> +    Partial<Omit<PipetteOffsetCalibrationSessionParams, 'mount'>>,
I think the point here is to specify that `mount` is a required params, and that all of the others are optional.

2021-05-28 15:27 UTC, b-cooper commented on app/src/organisms/CalibrationPanels/ChosenTipRackRender.tsx
> +  )[1] as any
Yeah we use the `const foo: MyObjectType = {someKey: someValue} as any` pattern a lot in tests where we only need to stub out part of the `MyObjectType` for a particular unit. It's quick and dirty, though it's just sugar on top of an any cast, so probably best to be avoided in most code.

2021-05-28 16:02 UTC, b-cooper commented on app/src/redux/robot-api/__tests__/hooks.test.tsx
> +    wrapper.find('button').invoke('onClick')?.({} as React.MouseEvent)
Yeah they're pretty strict. They're expecting a click event passed to the onClick function.  Also as the test will fail if there is no onClick handler, so the code change here is moot.

2021-05-28 16:50 UTC, b-cooper commented on app/src/assets/labware/findLabware.ts
> +  customLabware: LabwareDefinition2[]
Yes, I do think it is an ambition for the long term. In the short term our usage of readonly in flow was relatively iffy. At least until the JS guild can get together and talk about the virtues and best practices of adopting more Readonly TS types in the App, we're dialing them back for this initial migration.

2021-05-28 16:57 UTC, b-cooper commented on app/src/molecules/DeckMap/index.tsx
> +  labwareBySlot?: { [slot: string]: Labware[] | undefined }
I believe that there is actually a possibility that the value will be undefined here.  The type in the reduce is `{ [slot in Labware['slot']]?: Labware[] }` and the `?` before the `:` specifies that there may be keys from the Slot union type that correspond to undefined values. This component is also pretty old, so we'll likely update some of this code soon and be more explicit about what keys/values are present for Labware and Modules by Slot.

2021-05-28 16:58 UTC, b-cooper commented on app/src/molecules/DeckMap/index.tsx
> +  modulesBySlot?: { [slot: string]: DisplayModule | undefined }
see response regarding LabwareBySlot above https://github.com/Opentrons/opentrons/pull/7550/files#r641690225

2021-05-28 17:03 UTC, b-cooper commented on app/src/organisms/CalibrateTipLength/index.tsx
> +        // @ts-expect-error TODO: ConfirmExitModal expects sessionType
Actually I, looking at the component, I think it actually shouldn't be optional and as there is important messaging about where the pipette goes after exit depending on the Session Type. This looks like a mistaken omission that was permitted by the previous loose Flow types.

2021-05-28 17:06 UTC, b-cooper commented on app/src/redux/analytics/hash.ts
> +  // TODO (sa 2021-05-19): probably should not be using the crypto module from global, use node module instead
I'm removing this TODO for now.

2021-05-28 17:09 UTC, b-cooper commented on app/src/redux/analytics/selectors.ts
> +type ProtocolDataSelectorResultFunc = (
Good call 👍

2021-05-28 17:15 UTC, b-cooper commented on app/src/redux/custom-labware/selectors.ts
> +//  @ts-expect-error(sa, 2021-05-11): filesByName[name] might be undefined because filesByName is typed as a partial type
#7849

2021-05-28 17:18 UTC, b-cooper commented on app/src/redux/discovery/epic.ts
> +// TODO(bc, 2021-05-17): nuke this epic, it is now dead code, functionality is covered by resartEpic in robot-admin
#7850

2021-05-28 17:26 UTC, b-cooper commented on app/src/redux/protocol/selectors.ts
> +          // @ts-expect-error(sa, 2021-05-12): data has been type narrowed to be Readonly<ProtocolFileV3<{}>>, which does not have modules
#7851

2021-05-28 17:33 UTC, b-cooper commented on app/src/redux/robot-api/http.ts
> +  const options: RequestInit = {
I this is a built in TS type and appears to be equivalent to the built-in Flow type `RequestOptions`

2021-05-28 17:35 UTC, b-cooper commented on app/src/redux/robot-api/types.ts
> +export type RobotApiV2ResponseData = Partial<{ id: string }>
As discussed offline. This difference between them is mostly a matter of style and there are merits of both in some cases over others for readability.  If we ever want to take a harder stance in the future this is that kind of style decision that would be best aided by a lint rule.

2021-05-28 17:43 UTC, b-cooper commented on app/src/redux/robot/reducer/index.ts
> +// TODO: (sa 2021-15-18: remove any typed state in combineReducers)
#7852

2021-05-28 18:00 UTC, b-cooper commented on app/src/redux/support/intercom-binding.ts
> +    global.Intercom?.(Constants.INTERCOM_BOOT, iprops)
👍 I'll update the `global.d.ts` so that `{Intercom?: ... }` isn't defined as optional  -> `{Intercom: ...}`. There is test coverage for Intercom not loading.

2021-05-28 20:34 UTC, b-cooper commented on app/src/pages/Upload/UploadPanel/UploadInput.tsx
> +        Component: 'label' as React.ComponentProps<
It is required because the `Component` isn't `any` it is `React.ComponentType<any> | keyof JSX.IntrinsicElements`.

This code will be updated soon with the new atomic button anyway.

2021-05-28 20:36 UTC, b-cooper commented on app/src/i18n.ts
> +    missingKeyHandler: (lng, ns, key, _fallbackValue) => {
good point, we generally use underscore for unused parameters, though unless they come before other used params, it's not super useful. I'll remove them.

2021-05-28 20:37 UTC, b-cooper commented on app/src/i18n.ts
> +  (err, _t) => {
https://github.com/Opentrons/opentrons/pull/7550#discussion_r641803697

2021-06-01 14:11 UTC, IanLondon approved these changes

2021-06-01 14:35 UTC, shlokamin approved these changes
🚢

2021-06-01 16:23 UTC, mcous approved these changes
🤞

2021-06-01 16:25 UTC, merged