refactor(protocol-designer): rename webworker stuff & add comments
OpenTrons/opentrons-api pull request #7585
Opened 2021-04-02 19:46 UTC by IanLondon

# Overview

@shlokamin and I were pairing and I got very confused by `new Worker()` when `Worker` is not the global object but instead imported from a `worker.js` file, and I forgot about `worker-loader` being a crucial part of why `worker.js` works at all! This PR is meant to make this more readable.

# Changelog

# Review requests

- Should not change any behavior, just refactor
- Clearer than before?

# Risk assessment

Low

2021-04-07 03:07 UTC, shlokamin approved these changes

2021-04-07 03:16 UTC, shlokamin requested changes
Oop hit the button too early, looks like we're getting a webpack error, could be the naming not sure whats going on:

```js
_timelineWorker__WEBPACK_IMPORTED_MODULE_7__.default is not a constructor
```

2021-04-07 15:26 UTC, IanLondon commented on webpack-config/lib/rules.js
> +    test: /[\\/]+worker\.js$/,
I'm hoping this is correct for cross-OS matching eg Windows paths can be `\` and potentially paths can be `\\` or `//` AFAIK.

I want to rule to only allow `path/to/worker.js` and not `path/to/somethingworker.js`. Right now we're relying on this being case-sensitive because we have eg `makeWorker.js` which should not be picked up by `worker-loader`.

It might be more explicit to have the rule be `[\\/]+__workers__[\\/]+*\.(js|ts)` so that workers are in a `__workers__/` directory, maybe more intuitive that something is looking at that special name than having to intuit that `worker.js` is a special name?

2021-04-07 16:42 UTC, mcous reviewed
Should we explore switching to [worker-plugin](https://github.com/GoogleChromeLabs/worker-plugin) for less magic - or at least, a different form of magic that is a lot closer to vanilla `new Worker` syntax?

(Full disclosure, I've been using `worker-loader` for [a _long_ time](https://github.com/tracespace/viewer/blob/a98f075f3207c6806eff955f61a257426ab9a3e6/config/index.js#L62-L66) and I've hated every single minute of it)

2021-04-07 16:42 UTC, mcous commented on webpack-config/lib/rules.js
> +    test: /[\\/]+worker\.js$/,
It would be weird to me if webpack wasn't normalizing these paths to POSIX beforehand. Expected a passed in regex here to account for cross-system path separator differences would be... unreasonable, IMO.

I'm not super down for `__workers__`, because this breaks our existing convention of stuff in a directory `__something__` is not production code (see: `__tests__`, `__fixtures__`, (test) `__utils__`).

If we wanted to keep using `worker-loader` and we wanted to make this more strict, I thik we should use a [function test](https://webpack.js.org/configuration/module/#condition) rather than a regex test:

```js
test: filename => path.basename(filename).match(/^worker\.(js|ts)$/)
```

2021-04-08 16:01 UTC, mcous requested changes
This is just lovely. I think we're missing the `plugins` config option to WorkerPlugin, but otherwise I'm pretty [stoked](https://www.youtube.com/watch?v=QgXObaM9i2Q)

2021-04-08 16:01 UTC, mcous commented on app/webpack.config.js
> +    // see https://github.com/GoogleChromeLabs/worker-plugin#globalobject-string--false
From reading these docs, do we still need this line here or can we rely on `WorkerPlugin` to set it properly in its own child compiler?

2021-04-08 16:01 UTC, mcous commented on protocol-designer/src/timelineMiddleware/makeTimelineMiddleware.js
> +  const worker: TimelineWorker = (new Worker('./worker', {
Should we add a TODO comment to remove this `any` in the TS conversion? Assuming that our `TimelineWorker` interface extends from TS's `Worker` interface, a TS `as` cast should be fine here

2021-04-08 16:01 UTC, mcous commented on protocol-designer/webpack.config.js
> +    }),
I think we might be missing a `plugins` option here to make sure the WorkerPlugin picks up our `EnvironmentPlugin` insertions. See https://github.com/GoogleChromeLabs/worker-plugin#plugins-array

```js
new WorkerPlugin({
  // disable warnings about HMR when we're in prod
  globalObject: DEV_MODE ? 'self' : false,
  // add required JS plugins to child compiler
  plugins: ['EnvironmentPlugin'],
}),
```

2021-04-08 16:01 UTC, mcous commented on app/webpack.config.js
> +    }),
Same comment about missing `plugins`

2021-04-08 16:32 UTC, IanLondon commented on app/webpack.config.js
> +    // see https://github.com/GoogleChromeLabs/worker-plugin#globalobject-string--false
ah right, should be handled by

```js
    new WorkerPlugin({
      // disable warnings about HMR when we're in prod
      globalObject: DEV_MODE ? 'self' : false,
    }),
```

2021-04-08 19:14 UTC, mcous approved these changes
Code looks good, smoke tested the development and production versions of the app and everything looked good.

Generated worker file itself also looked good; file name was appropriately hashed for cache busting

⛑️

2021-04-16 16:45 UTC, Kadee80 approved these changes
PD appears unaffected, tested:
- single and batch edit mode 
-  modules in a protocol
- import/export

2021-04-16 17:36 UTC, shlokamin approved these changes
LGTM

2021-04-19 14:52 UTC, merged