feat(api): protocol engine InstrumentContext implementes pick_up_tip
OpenTrons/opentrons-api pull request #7621
Opened 2021-04-12 17:36 UTC by amitlissack

# Overview

closes #7326 

# Changelog

# Review requests

# Risk assessment

None

2021-04-12 22:18 UTC, SyntaxColoring requested changes

2021-04-12 22:18 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api_experimental/instrument_context.py
> +    def __init__(self, client: ProtocolEngineClient, pipette_id: str) -> None:
Question for anyone: How do we name IDs from Protocol Engine to disambiguate them from other kinds of IDs? For example, here, `pipette_id` could be confused for a pipette load name, like `"p300_single_gen2"`.

Curious if other people have had similar discomfort. Or maybe it's a non-problem.

2021-04-12 22:18 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api_experimental/instrument_context.py
> +        #  either.
I'm doing something like this for `aspirate()`'s `rate`:

```suggestion
        if (presses is not None) or (increment is not None):
            raise NotImplementedError()
```

Seems less likely to get forgotten.

2021-04-12 22:18 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api_experimental/instrument_context.py
> +        # TODO(al, 2021-04-12): What about home_after?
```suggestion
        if not home_after:
            raise NotImplementedError()
```

Same as comment above.

2021-04-12 22:18 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api_experimental/labware.py
> +        return self._id
Can we somehow mark this as not belonging to the public API?

My vision is that this should be `Labware.internals.id`. But as a lightweight solution for now, we could move it to the bottom of the class, under a comment like `# Internal stuff, not part of the public Protocol API interface`?

2021-04-12 22:18 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api_experimental/protocol_context.py
> +    def pause(self, msg: str = None) -> None:
It's weird that this isn't a mypy error, isn't it?

2021-04-12 22:18 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api_experimental/protocol_context.py
> +    def comment(self, msg: str = None) -> None:
Ditto.

2021-04-12 22:47 UTC, sanni-t commented on api/src/opentrons/protocol_api_experimental/protocol_context.py
> +    def pause(self, msg: str = None) -> None:
mypy doesn't check things that don't have type annotations ＼| ￣ヘ￣|／

2021-04-12 22:55 UTC, amitlissack commented on api/src/opentrons/protocol_api_experimental/labware.py
> +        return self._id
I'll leave this for another time. There's no guarantee that this is a public interface yet.

2021-04-12 22:55 UTC, amitlissack commented on api/src/opentrons/protocol_api_experimental/protocol_context.py
> +    def pause(self, msg: str = None) -> None:
It was an error before I added the type annotation.

2021-04-13 12:38 UTC, mcous approved these changes
LGTM 🏇

2021-04-13 14:30 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api_experimental/labware.py
> +        return self._id
Sorry—no guarantee that what is a public interface yet? The whole `Labware` class?

2021-04-13 14:46 UTC, amitlissack commented on api/src/opentrons/protocol_api_experimental/labware.py
> +        return self._id
Yes. The whole `Labware` class.

2021-04-13 14:58 UTC, sanni-t approved these changes
🙌

2021-04-13 17:29 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api_experimental/protocol_context.py
> +    def pause(self, msg: str = None) -> None:
Right, but isn't it weird that `None` counts as a `str`, as opposed to `Optional[str]`? I thought that was part of the weird mypy configuration that we were escaping by moving to a separate top-level `protocol_api_experimental` module.

2021-04-13 17:54 UTC, amitlissack commented on api/src/opentrons/protocol_api_experimental/protocol_context.py
> +    def pause(self, msg: str = None) -> None:
Isn't it just an implied `Optional[str]`. Does it matter?

2021-04-13 19:04 UTC, SyntaxColoring approved these changes
`resource_id` move looks good. Thanks!

2021-04-13 19:13 UTC, merged