feat(protocol-designer): RFC add form level volume error to mix form
OpenTrons/opentrons-api pull request #7625
Opened 2021-04-12 23:21 UTC by shlokamin

# Overview

This RFC PR adds a form level error to the mix form when the volume is greater than the pipette/tip max volume.

Not intended to be merged (yet), I made assumptions about copy text and we haven't even decided whether we want to actually do this yet.

Closes #7603

# Changelog

- Add form level volume error to mix form

# Review requests
Make sure form level error shows up in mix form when the volume is greater than the pipette/tip max volume
Does stuff look good?

# Risk assessment
Low

2021-04-12 23:25 UTC, shlokamin commented on protocol-designer/src/steplist/formLevel/errors.js
> +const FORM_ERRORS: { [FormErrorKey]: (mixed) => FormError } = {
I changed the type here bcuz I wanted to be able to pass in a value to render. Having this be a function makes it more flexible in that way, and it is still typed to return a `FormError`

2021-04-12 23:25 UTC, shlokamin commented on protocol-designer/src/steplist/formLevel/errors.js
> +const FORM_ERRORS: { [FormErrorKey]: (mixed) => FormError } = {
I don't love the input being `mixed`, but wasn't sure of a better way to do this

2021-04-12 23:25 UTC, shlokamin commented on protocol-designer/src/steplist/formLevel/errors.js
> +    title: `Volume is greater than maximum pipette/tip volume (${String(
sorta winged this @howisthisnamenottakenyet

2021-04-12 23:37 UTC, shlokamin commented on protocol-designer/src/steplist/formLevel/errors.js
> +const FORM_ERRORS: { [FormErrorKey]: (mixed) => FormError } = {
(bcuz it has to be generic enough for other inputs for all of the warnings)

2021-04-15 16:41 UTC, Kadee80 approved these changes
🏈 LGTM! I defer to others for copy but its clear and dynamic!

2021-04-16 14:59 UTC, IanLondon requested changes

2021-04-16 14:59 UTC, IanLondon commented on protocol-designer/src/steplist/formLevel/errors.js
> +const FORM_ERRORS: { [FormErrorKey]: (mixed) => FormError } = {
It seems like the whole `FORM_ERRORS` structure being a "Record<FormErrorKey, FormError>" is just for namespacing convenience and readability within only this file. We never do `FORM_ERRORS[dynamicVariable]` it's always hard-coded `FORM_ERRORS.SPECIFIC_ERROR`. Now that they will have different signatures, that old pattern isn't working nicely.

We could maybe move them to the top-level instead of nested in FORM_ERRORS. Ie, we could get rid of FORM_ERRORS and directly do `const INCOMPATIBLE_ASPIRATE_LABWARE: FormError = { /* title: ..., dependentFields: ... */ }` and so on for all the keys in FORM_ERRORS. Including `const VOLUME_TOO_HIGH = (pipetteCapacity: number): FormError => { /* ... */ }`. Then they're all independently typed, so they can take whatever args and those args can be easily + explicitly typed

Also, while we're in this file I wonder if we can make `type FormError` exact-typed, it's probably only missing the `|`s by mistake. I just attempted it on edge and it seems like there's no errors

2021-04-16 15:29 UTC, shlokamin commented on protocol-designer/src/steplist/formLevel/errors.js
> +const FORM_ERRORS: { [FormErrorKey]: (mixed) => FormError } = {
nice, i like that idea

2021-04-16 18:14 UTC, IanLondon commented on protocol-designer/src/steplist/formLevel/errors.js
> +export const volumeTooHigh = (fields: HydratedFormData): ?FormError => {
nitpick: I think it returns type `FormError | null`

2021-04-16 18:14 UTC, IanLondon approved these changes
changes look good!

2021-04-20 20:10 UTC, merged