feat(api): fast simulation catches tip and volume errors
OpenTrons/opentrons-api pull request #7631
Opened 2021-04-13 18:53 UTC by amitlissack

# Overview

closes #7627

# Changelog

# Review requests

# Risk assessment

2021-04-13 20:26 UTC, mcous approved these changes

2021-04-14 12:35 UTC, sfoster1 commented on api/src/opentrons/protocols/context/simulator/instrument_context.py
> +                f'Cannot {action} with a tip attached'
[nitpick] wording different between the two errors?

2021-04-14 12:37 UTC, sfoster1 requested changes
The exceptions raised here are presented to users, right? We should make the language a little less terse and programmer-y. Maybe give the hardware actions some `human_name` attrs and recommend ameliorating actions?

2021-04-14 12:38 UTC, sfoster1 commented on api/src/opentrons/protocols/context/simulator/instrument_context.py
> +        assert new_volume <= self._pipette_dict['working_volume'],\
Maybe make this its own nice semantic error rather than an assertion like `NoTipAttachedError`/`TipAttachedError`?

2021-04-14 12:41 UTC, amitlissack commented on api/src/opentrons/protocols/context/simulator/instrument_context.py
> +                f'Cannot {action} with a tip attached'
> The exceptions raised here are presented to users, right? We should make the language a little less terse and programmer-y. Maybe give the hardware actions some `human_name` attrs and recommend ameliorating actions?

I chose to stick with the same exact wording users would have seen from existing simulation errors.

2021-04-14 12:42 UTC, amitlissack commented
> The exceptions raised here are presented to users, right? We should make the language a little less terse and programmer-y. Maybe give the hardware actions some `human_name` attrs and recommend ameliorating actions?

I chose to stick with the same wording as users would have seen with full simulation.

2021-04-14 12:44 UTC, amitlissack commented on api/src/opentrons/protocols/context/simulator/instrument_context.py
> +        assert new_volume <= self._pipette_dict['working_volume'],\
This PR is really about achieving parity with slow simulation. It's not about making nicer errors.

2021-04-14 15:39 UTC, sfoster1 approved these changes
OK, looks all good to me w/r/t the wording then

2021-04-14 15:40 UTC, merged