feat(protocol-engine): InstrumentContext implements dispense
OpenTrons/opentrons-api pull request #7640
Opened 2021-04-14 18:26 UTC by sanni-t

Closes #7329 

# Overview

Implement dispense command in experimental Protocol Engine InstrumentContext. 
As a first pass, the command has been simplified to perform the most basic dispense action with specific args; cases not covered are documented & guarded with error raises.

# Changelog

- Added `dispense` method to experimental InstrumentContext
- Added `SyncClient.dispense`

# Review requests

- Code & tests look ok
- Have all 'not implemented' cases been covered?

# Risk assessment

None.

2021-04-14 19:12 UTC, SyntaxColoring requested changes
Other than these two things, looks great to me!

2021-04-14 19:12 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api_experimental/instrument_context.py
> +        """Dispense a volume of liquid (in microliters)."""
I think we should leave out the docstrings so we don't compete with the ones in `opentrons.protocol_api`.

I think for now, docstrings in `protocol_api_experimental` should be reserved for cases where our behavior intentionally differs from APIv2. (Or maybe even in those cases, we leave out the docstrings and maintain a changelog elsewhere. I dunno.)

2021-04-14 19:12 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api_experimental/instrument_context.py
> +            raise NotImplementedError("Volume tracking not yet supported in PE.")
```suggestion
        if not volume:
            raise NotImplementedError("Volume tracking not yet supported in PE.")
```

Unfortunately, current APIv2 behavior is to dispense the current volume if `volume` is `None` *or 0.* For now, we should preserve that behavior here.

https://github.com/Opentrons/opentrons/blob/df68ea2da42b99334eee17077ed9dc3d3f3bf7f8/api/src/opentrons/protocol_api/instrument_context.py#L291

#6741 documented this for other `InstrumentContext` methods, but it looks like I missed `dispense()`. Sorry!

2021-04-14 19:35 UTC, mcous commented on api/src/opentrons/protocol_api_experimental/instrument_context.py
> +        """Dispense a volume of liquid (in microliters)."""
Personally I would rather see docstrings in this PR than not

2021-04-14 19:38 UTC, mcous commented on api/src/opentrons/protocol_api_experimental/instrument_context.py
> +            raise NotImplementedError("Volume tracking not yet supported in PE.")
I see what you're saying, but I kind of prefer the explicitness of `volume is None`. Perhaps we could do `volume is None or volume == 0`?

On the JS-side, we have linters that yell at you if you try to infer a falsey value from a number that may be `null`, and I think the same rule should apply here with `None`

2021-04-14 19:40 UTC, mcous reviewed
This LGTM except for the weird `0` volume means "all volume" behavior preservation that Max noted

2021-04-14 19:56 UTC, sanni-t commented on api/src/opentrons/protocol_api_experimental/instrument_context.py
> +            raise NotImplementedError("Volume tracking not yet supported in PE.")
Oh! I did not realize it does that for volume == 0. Thanks @SyntaxColoring.
I like @mcous's suggestion of `volume is None or volume == 0`. I think `not volume` makes it easy to overlook the 0 volume case as I just did.

2021-04-14 22:44 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api_experimental/instrument_context.py
> +        """Dispense a volume of liquid (in microliters)."""
My thinking is:

1. We shouldn't write docstrings just to have docstrings. I would rather have `# noqa: D102` than a tautological docstring (like "`createFoo()`: create a Foo").

   [I tried making this point in another PR](https://github.com/Opentrons/opentrons/pull/7413#discussion_r587783750), but I never followed up. The context of that PR was a little different, so parts of those arguments might not make sense, but I think those arguments could be generalized to apply to this PR.
2. Alternatively, we could make our docstrings not tautological, and write them to be fleshed-out, meaningful, and complete. But I think doing that well would be a surprising amount of work. And it would duplicate what already exists in `protocol_api`, for no benefit that I can see.

I envision, late in the Protocol Engine development cycle, copy-pasting the docstrings from `protocol_api` to `protocol_api_experimental`. We do it late to minimize drift, and to possibly take advantage of whatever refactors have emerged by then to bring parts of both implementations under common interfaces.

2021-04-14 22:49 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api_experimental/instrument_context.py
> +        """Dispense a volume of liquid (in microliters)."""
Unrelated: If we do keep this docstring, we should remove the sneaky `# noqa: D102` a few lines above.

2021-04-16 00:10 UTC, SyntaxColoring approved these changes
Changes since my prior review look good. Thanks!

2021-04-16 17:33 UTC, mcous approved these changes

2021-04-19 15:17 UTC, merged