chore(makefile): fix pipenv invocation in update-server
OpenTrons/opentrons-api pull request #7729
Opened 2021-04-26 19:16 UTC by X-sam

Pipenv was being invoked using an implicit local install, changed it to use the environment variable
$PIPENV instead.

# Overview

# Changelog

# Review requests

# Risk assessment

2021-04-26 20:37 UTC, sanni-t approved these changes
🎉

2021-04-26 21:57 UTC, SyntaxColoring requested changes

2021-04-26 21:57 UTC, SyntaxColoring commented on update-server/Makefile
> +	$(pipenv_envvars) $(pipenv) sync $(pipenv_opts)
Nice catch!

I think this can be reduced to:

```suggestion
	$(pipenv) sync $(pipenv_opts)
```

Because `$(pipenv)` is defined like:

https://github.com/Opentrons/opentrons/blob/5da32381c0cc94d622d4e3e064d10d80aaf0187d/scripts/python.mk#L8

2021-04-26 22:55 UTC, SyntaxColoring approved these changes
Looks good to me!

2021-04-28 12:54 UTC, mcous approved these changes
🎯 nice fix! `make teardown-py` followed by `make setup-py` works on my machine an CI seems to be happy.

If you wanted to fix the missing update-server teardown target in this or a future PR, note that the `teardown-py` target in the top-level Makefile will also need to be adjusted

2021-04-28 12:55 UTC, mcous commented on update-server/Makefile
Doh, forgot to include this in my review:

PR is approved either way, but it looks like we're missing a `teardown` target in this Makefile:

```make
.PHONY: teardown
teardown:
	$(pipenv) --rm
```

Good candidate for continuing Makefile fixes in this or another PR

2021-04-28 13:09 UTC, X-sam commented on update-server/Makefile
Oh, I'll add that! Is our expected Makefile nomenclature documented somewhere? `teardown` is not a target I've seen before...

2021-04-28 16:53 UTC, mcous commented on update-server/Makefile
Unfortunately no, not documented anywhere outside of the Makefiles themselves and the contributing guide. For us, they mean, roughly "install / uninstall development dependencies"

The targets `setup` and `teardown` have a fun history in our Makefiles, in that they are newer names for targets that used to be called `install` and `uninstall`.  That was particularly bad (and my fault!), because they were in there to mirror `npm install`, but `make install` means something _wildly_ different in conventional Makefile usage

2021-05-20 16:11 UTC, mcous approved these changes

2021-06-04 16:55 UTC, merged