chore: update release notes for 4.3.0
OpenTrons/opentrons-api pull request #7760
Opened 2021-05-03 19:32 UTC by sfoster1

Updates the app and api release notes for 4.3.0.

2021-05-03 19:34 UTC, sfoster1 commented on app-shell/build/release-notes.md
> +We've improved module funcitonality with Opentrons App 4.3.0. The app now supports protocols with 2 Temperature Modules or 2 Magnetic Modules. All connected modules display their USB port connection
```suggestion
We've improved module functionality with Opentrons App 4.3.0. The app now supports protocols with 2 Temperature Modules or 2 Magnetic Modules. All connected modules display their USB port connection (including limited USB port information for hubs). We've also updated how modules are displayed on the Run tab.
```

2021-05-03 19:35 UTC, sfoster1 commented on app-shell/build/release-notes.md
> +We've improved module functionality with Opentrons App 4.3.0. The app now supports protocols with 2 Temperature Modules or 2 Magnetic Modules. All connected modules display their USB port connection
```suggestion
We've improved module functionality with Opentrons App 4.3.0. The app now supports protocols with two Temperature Modules or two Magnetic Modules. All connected modules display their USB port connection (including limited USB port information for hubs). We've also updated how modules are displayed on the Run tab.
```

2021-05-03 19:35 UTC, sfoster1 commented on api/release-notes.md
> +- The OT-2 now supports protocols with 2 Magnetic Modules or 2 Temperature Modules. Protocols may now load more than one of the same module type by calling `protocol.load_module()` multiple times wit
```suggestion
- The OT-2 now supports protocols with two Magnetic Modules or two Temperature Modules. Protocols may now load more than one of the same module type by calling `protocol.load_module()` multiple times with the same type of module and different deck slots.
```

2021-05-03 19:41 UTC, Laura-Danielle requested changes
Just a few comments.

2021-05-03 19:41 UTC, Laura-Danielle commented on api/release-notes.md
> +- The OT-2 now supports protocols with two Magnetic Modules or two Temperature Modules. Protocols may now load more than one of the same module type by calling `protocol.load_module()` multiple times
Can we just link to the support article on multiple modules rather than having the second sentence? Technically users could always load multiple modules into their protocols (aside from the thermocycler). We should also emphasize that this is for python api protocols only.

2021-05-03 19:41 UTC, Laura-Danielle commented on app-shell/build/release-notes.md
> +We've improved module functionality with Opentrons App 4.3.0. The app now supports protocols with two Temperature Modules or two Magnetic Modules. All connected modules display their USB port connect
```suggestion
We've improved module functionality with Opentrons App 4.3.0. The app now supports protocols with two Temperature Modules or two Magnetic Modules for Python API Protocols. All connected modules display their USB port connection (including limited USB port information for hubs). We've also updated how modules are displayed on the Run tab.
```

2021-05-03 19:41 UTC, Laura-Danielle commented on api/release-notes.md
> +- The OT-2 now supports protocols with two Magnetic Modules or two Temperature Modules. Protocols may now load more than one of the same module type by calling `protocol.load_module()` multiple times
Here is the link for the support article: https://support.opentrons.com/en/articles/5167312-using-modules-of-the-same-type-on-the-ot-2

2021-05-03 19:46 UTC, emilywools commented on app-shell/build/release-notes.md
> +We've improved module functionality with Opentrons App 4.3.0. The app now supports protocols with two Temperature Modules or two Magnetic Modules. All connected modules display their USB port connect
good call!!

2021-05-04 15:26 UTC, sfoster1 commented on api/release-notes.md
> +- The OT-2 now supports protocols with two Magnetic Modules or two Temperature Modules. Protocols may now load more than one of the same module type by calling `protocol.load_module()` multiple times
@marisafenn what do you think?

2021-05-06 00:10 UTC, marisafenn commented on api/release-notes.md
> +- The OT-2 now supports protocols with two Magnetic Modules or two Temperature Modules. Protocols may now load more than one of the same module type by calling `protocol.load_module()` multiple times
Overall I agree with @Laura-Danielle:
> Can we just link to the support article on multiple modules rather than having the second sentence? Technically users could always load multiple modules into their protocols (aside from the thermocycler). We should also emphasize that this is for python api protocols only.

Perhaps something along the lines of:
```suggestion
- The OT-2 now supports the use of two Magnetic Modules or two Temperature Modules in the same Python API protocol. See our Help Center article on <Using modules of the same type (as a hyperlink)> for an overview of how this feature should be configured.
```
Up to y'all if you think it'd be good to include referencing the need to call `protocol.load_module()` explicitly. I do not think it is necessary but I am making the assumption that a user would know to repeatedly call whatever module(s) they have multiples of but I don't know if this a big assumption or not. I am also still getting up to speed on the tone and style of Opentrons' previous release notes as far as consistency goes.

I would avoid the original phrasing of,
> "...multiple times with the same type of module and different deck slots"

because I think it is unnecessary, but I am making another assumption about a user being able to intuit this sort of information about the feature. Regardless, I think linking to the Help Center article is a good idea (as Laura mentioned) because it may also address other questions the user has. Plus it offers troubleshooting steps/advice. By doing this, we are essentially presenting the user with additional self-service tools while also educating them (despite channel switching, which I would rather avoid but I'm learning is hard to do in software/hardware) and offering clear visual aids vs. saying "call this multiple times for your modules." Anyhow, feel free to disregard if you feel I am rambling about semantics at this point.

2021-05-06 00:25 UTC, marisafenn approved these changes

2021-05-06 00:26 UTC, marisafenn approved these changes

2021-05-06 12:56 UTC, Laura-Danielle approved these changes
lgtm

2021-05-06 12:57 UTC, merged