feat(api): JSON protocol labware loading support in Protocol Engine
OpenTrons/opentrons-api pull request #7762
Opened 2021-05-03 20:20 UTC by amitlissack

# Overview

closes #7429 

# Changelog

# Review requests

# Risk assessment

None

2021-05-04 12:39 UTC, amitlissack commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +        labware_id: Optional[str]
Should this default to `None`?

2021-05-04 14:45 UTC, mcous commented
Was thinking through this, and I think I see a potential snag with this model: if a JSON protocol must be collapsed into a (1) load definition command and then (2) a load labware command that depends on the output of the load definition execution (because it breaks apart the URI). Because the input of (2) depends on the execution output of (1), we can no longer load all protocol commands without executing anything (in a pedantic sense).

Not sure what the resolution is here, but a few ideas in order of least annoying to most annoying

1. Accept that it's ok for the command translator to know how to break apart a labware URI into load labware request params, move on with our lives
2. Create some sort of "load labware by URI" command
3. Fallback to load labware by definition command

Sitting with it for a few hours, I'm pretty ok with (1), which I think means this PR is all good, but figured I should check in

2021-05-04 15:32 UTC, mcous requested changes
I think we need to avoid putting the definitions in multiple places in the labware store, otherwise we're going to run into debugging / source of truth issues.

Also, I just pushed up a PR that adds a pretty similar method to the labware store, so let's figure out how to name both of them to avoid confusion

2021-05-04 15:32 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/add_labware_definition.py
> +    labware_definition: LabwareDefinition = Field(
Should this be camel case? Also might be nice to just shorten to `definition` to match the `LoadLabwareResult`

2021-05-04 15:32 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/load_labware.py
> +        ...,
Should this default to `None`?

2021-05-04 15:32 UTC, mcous commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +            definition = self._state.labware.get_labware_definition(
Shoot, this name sort of conflicts with `state.labware.get_definition(labware_id=labware_id)` added in #7769. Should we shift the names of one or both of these to be a little more clear?

2021-05-04 15:32 UTC, mcous commented on api/src/opentrons/protocol_engine/state/labware.py
> +            self._state._labware_definitions_by_uri[uri] = \
This is storing the same definition in multiple places in the same state tree. We should strive to avoid (ideally) any sort of state duplication, because it makes debugging and source of truth much harder to follow.

Why are we storing the definition upon completion of `LoadLabwareResult`?

2021-05-04 16:48 UTC, amitlissack commented on api/src/opentrons/protocol_engine/commands/load_labware.py
> +        ...,
Yes

2021-05-04 16:49 UTC, amitlissack commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +            definition = self._state.labware.get_labware_definition(
Yes. I'll fix after we merge yours.

2021-05-04 16:51 UTC, amitlissack commented on api/src/opentrons/protocol_engine/state/labware.py
> +            self._state._labware_definitions_by_uri[uri] = \
Good point on the first.

The second, just to cache the definition so we don't need to reload definitions.

2021-05-04 16:54 UTC, amitlissack commented
> Was thinking through this, and I think I see a potential snag with this model: if a JSON protocol must be collapsed into a (1) load definition command and then (2) a load labware command that depends on the output of the load definition execution (because it breaks apart the URI). Because the input of (2) depends on the execution output of (1), we can no longer load all protocol commands without executing anything (in a pedantic sense).
> 
> Not sure what the resolution is here, but a few ideas in order of least annoying to most annoying
> 
> 1. Accept that it's ok for the command translator to know how to break apart a labware URI into load labware request params, move on with our lives
> 2. Create some sort of "load labware by URI" command
> 3. Fallback to load labware by definition command
> 
> Sitting with it for a few hours, I'm pretty ok with (1), which I think means this PR is all good, but figured I should check in

Since we call `LoadLabwareRequest` knowing the components of the URI, it's not really necessary to use the values in `AddLabwareDefinitionResult`. 

So I am ok with `1` too.

2021-05-05 13:14 UTC, mcous approved these changes

2021-05-05 13:14 UTC, mcous commented on api/src/opentrons/protocol_api_experimental/labware.py
> +        return cast(LabwareParameters, definition.parameters.dict())
Oh boy, this whole thing with the type dicts. I wonder how much of a "breaking" change it is to switch to the models. I also wonder if this `parameters` method is really even used

2021-05-05 13:14 UTC, mcous commented on api/src/opentrons/protocol_engine/state/labware.py
> +        elif isinstance(command.request, AddLabwareDefinitionRequest) and \
I believe this check on `command.request` is redundant. The system will only ever pair a `AddLabwareDefinitionRequest` with a  `AddLabwareDefinitionResult`, and the typing should know that

2021-05-05 13:14 UTC, mcous commented on api/tests/opentrons/conftest.py
> +            "quirks": ["a quirk"],
I wonder if we can remove `quirks` without breaking any tests. It's not required, according to the JSON schema

2021-05-05 13:14 UTC, mcous commented on robot-server/tests/conftest.py
> +def minimal_labware_def():
Maybe in the future we can create a fixtures library in `shared-data` (or wherever) and import them into `conftest.py`'s instead

2021-05-05 13:20 UTC, amitlissack commented on api/src/opentrons/protocol_engine/state/labware.py
> +        elif isinstance(command.request, AddLabwareDefinitionRequest) and \
It is. It's just there for mypy.

2021-05-05 13:22 UTC, amitlissack commented on api/src/opentrons/protocol_api_experimental/labware.py
> +        return cast(LabwareParameters, definition.parameters.dict())
This will be version 3. We can break away. Can't we?

2021-05-05 13:22 UTC, amitlissack commented on api/src/opentrons/protocol_engine/state/labware.py
> +        elif isinstance(command.request, AddLabwareDefinitionRequest) and \
I'll double check but I added the check for mypy.

2021-05-05 13:23 UTC, amitlissack commented on api/tests/opentrons/conftest.py
> +            "quirks": ["a quirk"],
I am guessing it's in use by some test. I'll check.

2021-05-05 13:24 UTC, amitlissack commented on robot-server/tests/conftest.py
> +def minimal_labware_def():
That's a nice idea. It's not really clear to me what does and does not belong in shared-data.

2021-05-05 13:31 UTC, amitlissack commented on api/src/opentrons/protocol_engine/state/labware.py
> +        elif isinstance(command.request, AddLabwareDefinitionRequest) and \
Ha! You were right. Weirdly pycharm marked it as a type error but not mypy. I don't get it. But I removed the check

2021-05-05 14:00 UTC, merged