refactor(labware-creator): Break out Grid and Volume sections
OpenTrons/opentrons-api pull request #7768
Opened 2021-05-04 14:21 UTC by Kadee80

# Overview

Addresses #7707

# Changelog

- refactor(labware-creator): Break out Grid and Volume sections

# Review requests

- [ ] code review
- [ ] LC still generates working definitions

# Open Questions
- Other sections conditionally render the text `wells` or `tubes` do we want to add this here?

# Risk assessment

Low, but we should check definition generation yet again

2021-05-04 21:10 UTC, IanLondon requested changes
some typing changes

2021-05-04 21:10 UTC, IanLondon commented on labware-library/src/labware-creator/components/sections/Grid.tsx
> +  // @ts-expect-error `includes` doesn't want to take null/undefined
Could be `return values.labwareType == null || ['aluminumBlock', 'tubeRack'].includes(values.labwareType) ? null : ( ... )`. Otherwise it's kind of unintuitive to trace out the case for labwareType being `null | undefined` -- is it supposed to return `null` or return the div?

Also L36 needs to be `export const Grid = (): JSX.Element | null => {`

2021-05-04 21:10 UTC, IanLondon commented on labware-library/src/labware-creator/components/sections/Volume.tsx
> +  // @ts-expect-error `includes` doesn't want to take null/undefined
same comment as above

2021-05-05 03:38 UTC, shlokamin commented on labware-library/src/labware-creator/components/__tests__/FormAlerts.test.tsx
> +    const warning = container.querySelector('[class="alert warning"]')
so testing library docs [explicitly call out using class selectors as a bad thing](https://testing-library.com/docs/queries/about/#manual-queries), but i do think it's important to test that we're seeing a warning vs error here. idk if folks have a better alternative to this @Opentrons/js

2021-05-05 03:58 UTC, shlokamin commented on labware-library/src/labware-creator/components/__tests__/sections/Footprint.test.tsx
> +      return <div></div>
as per the testing discussion in [this thread](https://github.com/Opentrons/opentrons/pull/7737#discussion_r623354742) (it's long I'm sorry we should really document these opinions somewhere... perhaps in coda? @mcous) I'm removing throwing an error here because it exerts unnecessary design pressure. If someone interacts with this mock in some other way that would result in the test still passing, we should not stop it from doing so.

2021-05-05 04:02 UTC, shlokamin commented on labware-library/src/labware-creator/components/FormAlerts.tsx
> -  }
this logic is moved to the beginning of each section, where it should be. I mistakenly left it inside of `FormAlerts` on the first pass.

2021-05-05 17:06 UTC, Kadee80 commented on labware-library/src/labware-creator/components/sections/Volume.tsx
> +  // @ts-expect-error `includes` doesn't want to take null/undefined
both of these comments can be applied to the height section as well! happy to do it lemme know

2021-05-05 18:03 UTC, Kadee80 commented
smoke tested. LGTM

2021-05-05 18:38 UTC, shlokamin approved these changes

2021-05-06 14:45 UTC, IanLondon approved these changes
sweeet 🥐

2021-05-06 14:58 UTC, merged