fix(api): add pause manager to separate pause and delay
OpenTrons/opentrons-api pull request #7773
Opened 2021-05-05 23:01 UTC by ahiuchingau

# Overview
Separate the pause and delay logic in hardware controller so they don't interfere with each other. 

Closes #6898, closes #7272

# Changelog

# Review requests

# Risk assessment

2021-05-06 20:18 UTC, sfoster1 requested changes
The overall concept (having a pause stack that saves one or more typed reasons for a pause, and only resumes when the stack is entirely resolved) makes sense to me. I think there's some functionality that needs to be fixed (the thing about `delay()` probably causing a protocol cancel if the door is open when the `delay()` ends); some internal interfaces that can be cleaned up (callers shouldn't need to know about the pause manager); and I think a missing bit of functionality, which is having a way for callers to either reset the pause stack as a whole or clear out all entries of a given type. For instance, at the end of a protocol or when a protocol is cancelled, any `PauseType.PAUSE`s that are in the stack should go away somehow, as well as probably `DELAY`s.

2021-05-06 20:18 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +    def should_pause(self):
`should_pause` feels like it is the same as checking `self.queue.empty()`, right? or is there something I'm missing?

2021-05-06 20:18 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +            raise PauseResumeError
I think we either want this to not be an exception (we just don't unpause) or we want to catch it at the end of `delay`

2021-05-06 20:18 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        if not self._pause_manager.should_pause:
if the door opened during the `delay` there would be an exception here, and I'm pretty sure it would cancel the protocol that called `delay`, so we should either catch the exception or just not unpause here

2021-05-06 20:18 UTC, sfoster1 commented on api/src/opentrons/api/session.py
> +        self._hardware.pause_manager_pause(PauseType.PAUSE)
This is weird to me. I don't think this should be two calls.

2021-05-06 20:18 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +    def pause_manager_pause(self, pause_type: PauseType) -> None:
I think the interface that hardware control presents upwards can be improved. We shouldn't require callers to know to call both `pause_manager_pause` and  `pause` or `pause_manager_resume` and `resume`, each should just be one call.

2021-05-06 20:21 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/api.py
> +    def should_pause(self):
Yea it's the same thing

2021-05-06 20:30 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +    def should_pause(self):
Let's collapse them together then and implement `should_pause` as checking `queue.empty()`. one fewer place to check!

2021-05-10 14:36 UTC, sfoster1 requested changes
Looking really good, couple little things

2021-05-10 14:36 UTC, sfoster1 commented on api/src/opentrons/hardware_control/types.py
> +class PauseType(enum.Enum):
since this is in `types` anyway, why not simplify things and have callers use it rather than a `from_delay` bool? So have the sessions api call `hardware.pause(PauseType.PAUSE)`, `delay` calls `hardware.pause(PauseType.DELAY)`, that sort of thing?

2021-05-10 14:36 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +        self.queue: List[PauseType] = []
This might want to be a `queue.Queue` so it's easily cross-thread

2021-05-10 14:36 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +    def set_door(self, door_state):
type annotations?

2021-05-10 14:36 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +    def _evaluate_door_state(self, door_state) -> bool:
type annotations for `door_state`?

2021-05-10 14:36 UTC, sfoster1 commented on api/src/opentrons/hardware_control/api.py
> +    def blocked_by_door(self):
return type annotation?

2021-05-10 17:38 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/types.py
> +class PauseType(enum.Enum):
My logic was that since there's only one instance where `hardware.pause(PauseType.DELAY)` would occur, and it's called by api session delay; I thought this would make the code looks neater. 

Looking back, it's a probably a lazy fix. Will add the `PauseType` in!

2021-05-11 12:32 UTC, sfoster1 approved these changes
Nice! Looks good to me once tested

2021-05-11 15:01 UTC, amitlissack commented on api/src/opentrons/hardware_control/api.py
> +        if self._pause_manager.queue:
Is this a check to see whether we should resume? If so, can we have a method in the `PauseManager` that makes that clear?

2021-05-11 15:22 UTC, amitlissack commented on api/src/opentrons/hardware_control/api.py
> +        self.resume(PauseType.DELAY)
If this line is somehow not reached, will we ever be able to unpause?

2021-05-11 15:34 UTC, ahiuchingau commented on api/src/opentrons/hardware_control/api.py
> +        self.resume(PauseType.DELAY)
If somehow a delay is not resumed, the protocol will get stuck there. Do you have an opinion on how this can be handled?

2021-05-11 15:40 UTC, amitlissack commented on api/src/opentrons/hardware_control/api.py
> +        self.resume(PauseType.DELAY)
Either a try - finally block or `PauseManager` can support some sort of context manager so you can do something like:

```
with pm.pauser(type):
      delay()
```

2021-05-12 14:01 UTC, Laura-Danielle requested changes
Looks good to me, just a stylistic request :)

2021-05-12 14:01 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +class PauseManager:
This should be pulled out into its own separate file, especially since we're trying to reduce the amount of code in this file.

2021-05-12 14:01 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/api.py
> +        self._pause_manager = PauseManager(self._door_state)
(Not for this PR). From the refactors I'm doing, it seems like we will probably want to move all the callback logic fully into the backend controller to further reduce duplications between the api/controller.

I also think we should consolidate what event watcher we're using for door state/modules -- which can be done after my refactor PR gets merged.

2021-05-12 15:55 UTC, Laura-Danielle approved these changes
ty

2021-05-12 16:29 UTC, amitlissack approved these changes

2021-05-12 17:01 UTC, merged

2021-05-26 14:40 UTC, nusrat813 commented
Tested. LGTM