fix(api): simulation allows aspirating and dispensing on a tip rack
OpenTrons/opentrons-api pull request #7788
Opened 2021-05-11 14:56 UTC by celsasser

# Overview
_The robot does not raise an error or warning when trying to aspirate and dispense on a tip rack. This occurs during the simulation and the tip rack is from the Opentrons labware library, not customized._

I am doing the most basic fix and testing whether the destination is a tip-rack. I don't like it. It seems like there is a nicer and more general solution to validation problems. Though it looks like validation is often combined with type constraining. Will either put up a draft PR or pursue alternative:

# Changelog
- refactor `aspirate` to see if the destination is a tiprack and raise runtime error if it is.
- create a test protocol to unit test
- adding change to .gitignore to include package-lock.json as it does not seem to be in the project but is generated if one does `npm install` on the root.

# Review requests
- Is there a convention we use for error messages. @mcous, I think you mentioned centralizing errors and error templates? 
- Do we want to try to centralize validation. I understand that it happens at different levels, but think there could be value in attempting to group the functionality, the messaging, possible re-use.

# Risk assessment
- None, provided nobody aspirates tips.

2021-05-11 23:37 UTC, amitlissack reviewed
Less than 7 days in and you are venturing into some of our trickiest code. You are a brave soul.

2021-05-11 23:37 UTC, amitlissack commented on api/src/opentrons/protocol_api/instrument_context.py
> +        validate_can_dispense(loc)
I might be nuts, but I think that `loc` is definitely a `Location` when we get to this spot, no?

If that is the case, then the `validate_can_...` methods can take a `Location`. Then you'd be able to use the `location.labware.is_well` or `location.labware.is_labware` etc rather than isinstance.

2021-05-12 14:11 UTC, celsasser commented on api/src/opentrons/protocol_api/instrument_context.py
> +        validate_can_dispense(loc)
Yes, it looks like you are right. Sort of missed the dispense part of the ticket when solving it and mimicked what I had done for aspirate. I will update. Thanks!

2021-05-12 14:14 UTC, celsasser commented on api/src/opentrons/protocol_api/instrument_context.py
> +        validate_can_dispense(loc)
Wait, except for `self._ctx.location_cache`? Do we know 🐬  that `loc` is a `Location`?

2021-05-12 14:15 UTC, celsasser commented on api/src/opentrons/protocol_api/instrument_context.py
> +        validate_can_dispense(loc)
Yes, he is of type `Location`. Well, nice having a conversation with you in github :)

2021-05-12 15:32 UTC, celsasser commented
> Less than 7 days in and you are venturing into some of our trickiest code. You are a brave soul.

Haha, thanks! It was really educational and also touched a number of things and made me know how little I know...which I should have known...

2021-05-12 16:50 UTC, sanni-t reviewed
Definitely some of our trickiest code

2021-05-12 16:50 UTC, sanni-t commented on api/tests/opentrons/test_simulate.py
> +    monkeypatch.setenv('OT_API_FF_allowBundleCreation', '1')
I don't think this is required. Bundling is a post-simulation step. (It bundles labware and other data from the protocol to pass it to the session in order to use for calibration and protocol running).

2021-05-12 16:50 UTC, sanni-t commented on api/src/opentrons/protocols/api_support/instrument.py
> +def validate_can_aspirate(
(Ignore if you are already working on this) I think we should make a single validation for both aspirate and dispense. In fact, I feel like your `_is_tiprack` function might be just the thing we need.

2021-05-12 17:00 UTC, celsasser commented on api/src/opentrons/protocols/api_support/instrument.py
> +def validate_can_aspirate(
That makes sense, but I guess I was/am thinking two (or three) things: 
1. Does this conflict with this feedback - https://github.com/Opentrons/opentrons/pull/7788/files#r630606222?
2. I was thinking about the possibilities of validation. Right now it is very simple, but conceptually (in a future where we know more about the state of the deck) it seems like it could be capable of more. Such as validating that there is stuff in the location. Or that there is a tube in the location. 
3. Isolating validation. It seems like it has the potential to be a whole layer of responsibility of its own? But also, I ran into lint complexity issues when I attempted to make the change inline (https://github.com/Opentrons/opentrons/pull/7788/files#diff-6811e2f4d45b8d159abed031a1b00c50e69ecc5aa7d8e19a674527fb4be3298cR186).

Please let me know what you think. My mission certainly isn't to unnecessarily change the way you guys do things.

2021-05-12 17:02 UTC, celsasser commented on api/tests/opentrons/test_simulate.py
> +    monkeypatch.setenv('OT_API_FF_allowBundleCreation', '1')
Thanks! I didn't understand it and attempted to remove it but ran into some error. It may have been unrelated. And I may have been imagining things. Let me give it a shot.

2021-05-12 17:03 UTC, sanni-t commented on api/src/opentrons/protocols/api_support/instrument.py
> +def validate_can_aspirate(
(^might be my uninformed suggestion, so let me know if there's a specific reason for having separate logic for aspirate vs dispense)

2021-05-12 17:03 UTC, mcous requested changes
This changeset looks pretty good to me! Only putting this as a "change request" to make sure we don't accidentally merge before sorting out the API version

2021-05-12 17:03 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +        validate_can_aspirate(dest)
In an annoying twist (which you have no real way of knowing about until now), we're going to need to create a new Protocol API version for this behavior and gate this check inside a version check.

#7609 (and #7754, because we forgot to include docs in the first PR) is a recent change we did where we also fixed a bug, gated behind an API Version bump. They can serve as a good reference for what changes an API version bump entails

2021-05-12 18:13 UTC, celsasser commented on api/src/opentrons/protocols/api_support/instrument.py
> +def validate_can_aspirate(
At the moment, none. But in a future where we knew what was in them then I can see (provided I am right and aspirate means to suck stuff out of a location) different concerns for the two. Sort of like I was saying in #2 above. For example, what if nothing is in the location from which you are trying to aspirate. Or if a location is beyond capacity once a dispense is performed. And then the messaging that we send back. But here I think you are suggesting that I move the test and exception throwing into instrument_context? There I ran into complexity issues with the linter, but That was a three line conditional vs. a two line conditional.

2021-05-12 18:16 UTC, celsasser commented on api/src/opentrons/protocols/api_support/instrument.py
> +def validate_can_aspirate(
Was just thinking about dispense and the possibilities that we were smart and that we knew what was in the pipette and was was in location and warn them in they were about to cause an 💥 .  That made me laugh. Don't think we are anywhere close to that. And maybe the user wants to blow themselves up. Who are we to judge!?

2021-05-12 18:32 UTC, celsasser commented on api/src/opentrons/protocol_api/instrument_context.py
> +        validate_can_aspirate(dest)
Okay, thanks! A lot I actually don't understand up there ☝️  but will. Let me start by taking a look at the referenced PRs.

2021-05-12 19:16 UTC, mcous reviewed
API version bump changes look good. Added additional context for what I meant by "adding a gate"

2021-05-12 19:16 UTC, mcous commented on api/docs/v2/versioning.rst
> +|     2.11    |          4.3.1              |
This would go out in the next scheduled release rather than the currently (already released) version

```suggestion
|     2.11    |          4.4.0              |
```

2021-05-12 19:16 UTC, mcous commented on api/docs/v2/versioning.rst
> +- In Python protocols requesting API version 2.11, validation to prevent aspiration and dispensation to tip-racks.
```suggestion
- In Python protocols requesting API version 2.11, attempting to aspirate from or dispense to tip racks will raise an error.
```

2021-05-12 19:16 UTC, mcous commented on api/src/opentrons/protocol_api/instrument_context.py
> +        validate_can_aspirate(dest)
The "gate" I was referring to was nothing fancy, just a little `if` statement!

```py
if self.api_version >= APIVersion(2, 11):
    validate_can_aspirate(dest)
```

2021-05-13 14:36 UTC, sanni-t commented on api/src/opentrons/protocols/api_support/instrument.py
> +def validate_can_aspirate(
Got it! Thanks for that explanation! So now I understand the thought process behind making two separate validations for aspirate & dispense but I still don't get why their logic is different. Can't both take a `types.Location` and just check for `if labware.parent and labware.parent.is_tiprack:`?

2021-05-13 15:13 UTC, celsasser commented on api/src/opentrons/protocols/api_support/instrument.py
> +def validate_can_aspirate(
@sanni-t - I changed it as a reaction to this feedback - https://github.com/Opentrons/opentrons/pull/7788#discussion_r630606222. It seems that we always know that the location is a `Location` and that being the case agreed with @amitlissack in that we don't need to add variability if we don't need it thinking that it might lead to confusing conclusions (in the brains of other developers).

2021-05-13 15:21 UTC, celsasser commented on api/src/opentrons/protocols/api_support/instrument.py
> +def validate_can_aspirate(
@sanni-t - yes, you are totally right. I think I was too literal about @amitlissack 's suggestion.  I see now that they both are constrained to `Location`. Thanks and fixing.

2021-05-14 14:57 UTC, celsasser commented on api/docs/v2/versioning.rst
> +- In Python protocols requesting API version 2.11, validation to prevent aspiration and dispensation to tip-racks.
Haha, just realized that this was not a change you made but rather a very cleverly disguised suggestion. Updating now.

2021-05-20 14:17 UTC, mcous approved these changes
🎥

2021-05-20 14:33 UTC, merged