feat(api): implement JsonFileRunner
OpenTrons/opentrons-api pull request #7797
Opened 2021-05-11 21:14 UTC by sanni-t

Closes #7645 

# Overview

Implements the `JsonFileRunner` class. .

# Changelog

- implemented `load`, `play`, `pause`, `stop` for `JsonFileRunner`
- created a `CommandQueueWorker` skeleton to delegate flow control to
- added `ProtocolEngine` `add_command` stub
- tests

# Review requests

- tests make sense?
- thoughts about `add_command` being sync/ async?
- anything missing in the implementation?

# Risk assessment

None

2021-05-11 23:44 UTC, amitlissack commented
What isn't clear to me is whether this ticket includes generating the LoadPipette and AddLabware requests from the JsonProto.

2021-05-12 18:40 UTC, mcous requested changes
Overall looks really good! My thoughts on your review requests:

> tests make sense?

Yup, `test_json_runner_load_commands_to_engine` is perfect! I've got a big essay below on why the other test (`test_json_runner_load_translation`), is redundant and should be removed.

> Thoughts about add_command being sync/ async?

Sync as you've implemented it is my vote.

> anything missing in the implementation?

Command ID! ~This is fun, because it surfaces a problem with the command translator and stuff we've discussed:~

- ~Decision in discussion: use PD step IDs as the PE command IDs~
- ~Implementation of command translator: map one PD step to many PE commands~
- ~Confusion: what do we do with the command ID without a 1-to-1 PD step to PE command mapping?~

~I have a proposal in a comment below, but open to other suggestions. Also, given this confusion,~ for @amitlissack's question...

> What isn't clear to me is whether this ticket includes generating the LoadPipette and AddLabware requests from the JsonProto.

...maybe we punt on that until we sort out step loading

---
Edit: struckthrough some stuff because I totally misunderstood the data that is present in a JSON protocol file

2021-05-12 18:40 UTC, mcous commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +    def add_command(self, request: CommandRequestType) -> None:
I think we probably want this to mirror the `execute_command` method a little bit:

- Takes an additional `command_id` argument
- Returns the `PendingCommand`

2021-05-12 18:40 UTC, mcous commented on api/tests/opentrons/file_runner/test_json_file_runner.py
> +    mock_cmd1 = cast(CommandRequestType,
Oh hm, why is this `cast` needed? I'm curious because I think we need to simplify the engine's command types, so this sort of "test pain" is a good signal that we might need to change something in those types

2021-05-12 18:40 UTC, mcous commented on api/tests/opentrons/file_runner/test_json_file_runner.py
> +def test_json_runner_load_translation(
Of these two tests, I think `test_json_runner_load_commands_to_engine` is the truly valuable one. I'm not sure this one (`test_json_runner_load_translation`) is providing any value that the second test doesn't cover. See additional comment below about combining `when` and `verify`

2021-05-12 18:40 UTC, mcous commented on api/tests/opentrons/file_runner/test_json_file_runner.py
> +    decoy.verify(command_translator.translate(protocol.commands[0]),
So this is my fault for not implementing this warning in `decoy` yet, but **you shouldn't use `when` and `verify` together in the same test for the same dependency**. This is not a technical requirement, but rather, [a conceptual testing concept](https://github.com/testdouble/testdouble.js/blob/main/docs/B-frequently-asked-questions.md#why-shouldnt-i-call-both-tdwhen-and-tdverify-for-a-single-interaction-with-a-test-double).

In general, this is the rule of thumb (not hard and fast, but will get you good results most of the time):

- If the dependency returns data, use `when`
- If the dependency is called for side-effects (or the subject doesn't care about the return value), use `verify`

If we're talking about the JSON file runner, we have two dependencies:

- `command_translator` - Called to get its data, and the subject uses the data
- `protocol_engine` - Called as a "side effect" (we don't care about its data)

In this first test, we spit out some empty data (presumably to avoid crashing the subject) and then verify the call arguments to the translator. This should feel odd to use because **we know that it's our test subject's job to do _something_ with the translator's data**, but this test doesn't interact with the output data at all.

In our second test, we spit out non-empty data, and that data can only come out correctly **if the translator is properly called** thanks to the stub configuration. Then we check that data is fed into the engine properly. So the second test is doing everything the first test is doing (making that first test redundant), but doing it better because we're actually making assertions on the data that is flowing through our dependencies.

The whole "don't use verify and when at the same time" thing was _really_ confusing to me when I first started using `testdouble.js`, where I learned this rule. It felt overly restrictive and arbitrary. As I came around to it, though, I realized the places where I felt like I needed to use `when` and `verify` were happening for more-or-less two reasons:

1. I just wasn't used to stubbing, and instead my brain was still in the world of call-and-then-verify-spy-was-called
    - This is what I think is happening here!
    - This is a very `MagicMock` way writing this test, and thankfully, with Decoy we just don't need this test
    - This gets better the more you practice it; I ended up learning to let go of the instinct to write this kind of test, which is nice, because it means I write fewer tests with no loss in value
2. It's a signal that your code is not well structured
    - This is not happening here, but you can also get into a place where you can't fully test the functionality of your code without stubbing and then verifying
    - If this happens, it's really easy to think "this stupid test library doesn't have the right features to test my code"
    - The harder question that one _should_ (IMO) be asking is "what does it mean that code is hard to test in this way?"

2021-05-12 18:40 UTC, mcous commented on api/src/opentrons/file_runner/json_file_runner.py
> +                self._protocol_engine.add_command(cmd)
We need to make sure that we add the command ID from the JSON protocol to the command we add to the engine. I'm also now realizing that this is a serious wrinkle in the translator API potentially returning multiple commands...

For now, could we:
- Add a `command_id` argument to `add_command`
- Pass the step ID from the PD command directly in as the `command_id`
- Add a big TODO comment to address what should happen if a PD command is translated into multiple PE commands
    - Potential solution: always translate one-to-one  

Aside: This is the sort of little problem that would've been more obvious if we'd started at the runner and then implemented the translator. C'est la vie; there are other problems that bottom-up development catches better than top-down

2021-05-13 01:04 UTC, sanni-t commented on api/tests/opentrons/file_runner/test_json_file_runner.py
> +    mock_cmd1 = cast(CommandRequestType,
It is not needed. That was just me complicating things.

2021-05-13 01:05 UTC, sanni-t commented on api/tests/opentrons/file_runner/test_json_file_runner.py
> +    decoy.verify(command_translator.translate(protocol.commands[0]),
Thanks for the detailed explanation! It is indeed still confusing to figure out which tests fit into that category but good to know it'll get better with practice. I'll remove the first test.

2021-05-14 19:22 UTC, celsasser commented on api/tests/opentrons/file_runner/test_json_file_runner.py
> +    """Create a stubbed command translator fixture."""
Fixtures are REALLY neat! This is a total nit but think comment need to be updated.

2021-05-14 20:05 UTC, sanni-t commented on api/tests/opentrons/file_runner/test_json_file_runner.py
> +    """Create a stubbed command translator fixture."""
Good catch!

2021-05-14 20:13 UTC, sanni-t commented on api/src/opentrons/file_runner/json_file_runner.py
> +                self._protocol_engine.add_command(cmd)
Discussed this offline and decided to have `add_command` generate the UUID since there is no immediate use case for a command ID in the file runner. As `add_command` implementation is part of a different ticket, leaving a TODO note for it.

2021-05-20 14:19 UTC, mcous approved these changes
👟

2021-05-20 15:15 UTC, merged