Pd transfer advance settings e2e
OpenTrons/opentrons-api pull request #7805
Opened 2021-05-12 18:39 UTC by reachojhaneha

Overview
Writing the e2e tests for batch edit advance settings for transfer steps

Changelog
Automation cases for batch edit transfer steps
Risk assessment
low

2021-05-17 20:31 UTC, IanLondon approved these changes
looks good to me! Just left some nitpicks

2021-05-17 20:31 UTC, IanLondon commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +function importProtocol() {
nitpick: for more readability, we might want to move these helper fns to the top of the file?

2021-05-17 20:31 UTC, IanLondon commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +      [isMacOSX ? 'metaKey' : 'ctrlKey']: true,
To make this code less repetitive, we could have define a constant at the top, eg `const batchEditClickOptions = { [isMacOSX ? 'metaKey' : 'ctrlKey']: true }` then `cy.get('something_blah_blah').click(batchEditClickOptions)`

2021-05-17 20:31 UTC, IanLondon commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +  const isMacOSX = Cypress.platform === 'darwin'
we should be able to use the `isMacOSX` constant already defined at the top of the file?

2021-05-17 20:31 UTC, IanLondon commented on protocol-designer/cypress/support/commands.js
> +Cypress.Commands.add('prewettip', () => {
Is there something more explicit for these command names, eg "togglePreWetTip" or "clickPreWetTip" instead of "prewettip"?

Same question for "mixaspirate" below.

2021-05-17 20:31 UTC, IanLondon commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    cy.get('div[class*=FlowRateInput__description]').contains(
I can push up a `data-test` for this so we don't have to use a classname if you'd like?

2021-05-18 14:06 UTC, shlokamin requested changes
Looks solid! left some questions/comments. 

Also, side question — do we have any e2e coverage where we actually export a protocol and compare it to a fixture? i.e. make a bunch of changes using batch edit, and then verify the JSON commands are correct?

2021-05-18 14:06 UTC, shlokamin commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +  it('Verify functionality of advance settings with different pipette and labware', () => {
i think `advance` should be `advanced` here

2021-05-18 14:06 UTC, shlokamin commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    // Different Pipette diabales aspirate and dispense Flowrate and Mix settings
`diabales` => `disables`

2021-05-18 14:06 UTC, shlokamin commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +      [isMacOSX ? 'metaKey' : 'ctrlKey']: true,
nice, i second this!

2021-05-18 14:06 UTC, shlokamin commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    cy.get('[id=WellOrderField_button_aspirate]').should('be.visible')
can we also check whether the well order button should display as `mixed` or not? i.e. when the well orders are the same, an image should show up (`<img src={ZIG_ZAG_IMAGE}` />) otherwise it should say `mixed`. If we are already checking this functionality in another e2e test don't worry about it though

2021-05-18 14:06 UTC, shlokamin commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    cy.get('button').contains('save').should('not.be.enabled')
what is the difference between `.should('be.disabled')` and `.should('not.be.enabled')`? are they the same?

2021-05-18 14:06 UTC, shlokamin commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    cy.get('input[name="dispense_mix_checkbox"]').click({ force: true })
i think we should be careful about using `{ force: true }` unless we really need to be, bcuz it can lead to bugs where we are clicking on things that are not actually visible to users. @reachojhaneha @IanLondon what do y'all think?

2021-05-18 14:06 UTC, shlokamin commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    cy.get('input[name="aspirate_flowRate"]').should('have.value', '')
your comment says it should be displayed with `"-"` but it looks like we are asserting the value should be an empty string. This is technically correct, but can we also check for the dash in the `placeholder` property on the `input`?

i.e. it should look like this:

`<input value={''} placeholder={'-'}`

2021-05-18 14:06 UTC, shlokamin commented on protocol-designer/cypress/support/commands.js
> +  cy.get('input[name="preWetTip"]').click({ force: true })
how come we have to `force: true` here?

2021-05-18 14:06 UTC, shlokamin commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    // Verify that volume is set to 2 and repitions to 2
this comment says `volume` and `repetitions` but the assertion only checks for delay seconds

2021-05-18 14:06 UTC, shlokamin commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    cy.get('input[name="aspirate_delay_seconds"]').should('have.value', 2)
this comment says `volume` and `repetitions` but the assertion only checks for delay seconds

2021-05-18 14:06 UTC, shlokamin commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    // Verify that volume is set to 2 and repitions to 2
this comment says `volume` and `repetitions` but the assertion only checks for touch tip offset

2021-05-18 14:06 UTC, shlokamin commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    // Verify that volume is set to 2 and repitions to 2
this comment says `volume` and `repetitions` but the assertion only checks for blowout options

2021-05-18 14:06 UTC, shlokamin commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    // Verify that volume is set to 2 and repitions to 2
this comment says volume and repetitions but the assertion only checks for blowout options

2021-05-18 16:06 UTC, reachojhaneha commented on protocol-designer/cypress/support/commands.js
> +  cy.get('input[name="preWetTip"]').click({ force: true })
All these input fields are hidden by the parent div, and until i do {force: true,} Cypress is not able to click on the element.
Also i feel force:true is necessary to click the checkboxes. 
https://docs.cypress.io/api/commands/check#No-Args - check for reference

2021-05-18 16:07 UTC, reachojhaneha commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    // Verify that volume is set to 2 and repitions to 2
Comments have been copied across testcases. I thought i fixed these errors, will fix them now

2021-05-18 16:08 UTC, reachojhaneha commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    cy.get('input[name="aspirate_delay_seconds"]').should('have.value', 2)
Will fix the comments

2021-05-18 16:08 UTC, reachojhaneha commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    // Verify that volume is set to 2 and repitions to 2
fixing the comments

2021-05-18 16:08 UTC, reachojhaneha commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    // Verify that volume is set to 2 and repitions to 2
fixing the comments

2021-05-18 16:08 UTC, reachojhaneha commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    // Verify that volume is set to 2 and repitions to 2
fixing the comments

2021-05-18 16:11 UTC, reachojhaneha commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    cy.get('input[name="dispense_mix_checkbox"]').click({ force: true })
All these input fields are hidden by the parent div, and until i do {force: true,} Cypress is not able to click on the element.
Also i feel force:true is necessary to click the checkboxes.
https://docs.cypress.io/api/commands/check#No-Args - check for reference

2021-05-18 16:15 UTC, reachojhaneha commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    cy.get('[id=WellOrderField_button_aspirate]').should('be.visible')
This is a good point. I will be adding the well-order mixed case in mix-e2e cases.

2021-05-18 16:15 UTC, reachojhaneha commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    // Different Pipette diabales aspirate and dispense Flowrate and Mix settings
oops, will fix the typo

2021-05-18 16:16 UTC, reachojhaneha commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +  it('Verify functionality of advance settings with different pipette and labware', () => {
fixing this

2021-05-18 16:20 UTC, reachojhaneha commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    cy.get('div[class*=FlowRateInput__description]').contains(
I would say for this particular case, i felt classname will work with regex , but for next time we can definitely avoid using classname as they can break.

2021-05-18 16:20 UTC, reachojhaneha commented on protocol-designer/cypress/support/commands.js
> +Cypress.Commands.add('prewettip', () => {
Good Point i can use togglePreWetTip here.

2021-05-18 16:21 UTC, reachojhaneha commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +  const isMacOSX = Cypress.platform === 'darwin'
Yes, this part of the cleanup was missed. Thanks for bringing this up

2021-05-18 16:22 UTC, reachojhaneha commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +function importProtocol() {
sure, I can place them at the top of the file.

2021-05-21 14:00 UTC, reachojhaneha commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    cy.get('input[name="aspirate_flowRate"]').should('have.value', '')
I tried this 
// indeterminate state in flowrate is empty
    cy.get('input[name="aspirate_flowRate"]').should('have.value', '-') <but the case failed.> Cypress is not able to pick the placeholder value.

2021-05-21 15:05 UTC, reachojhaneha commented
> Looks solid! left some questions/comments.
> 
> Also, side question — do we have any e2e coverage where we actually export a protocol and compare it to a fixture? i.e. make a bunch of changes using batch edit, and then verify the JSON commands are correct?

> Is that something an end user will do? I accept that they will export the protocol, but will they match it with the json?

2021-05-21 15:07 UTC, reachojhaneha commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    cy.get('button').contains('save').should('not.be.enabled')
not sure about this. Will find out

2021-05-22 13:08 UTC, reachojhaneha commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    cy.get('button').contains('save').should('not.be.enabled')
They are both the same and can be used interchangeably. Tried this and it works.

2021-05-24 14:21 UTC, shlokamin commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    cy.get('button').contains('save').should('not.be.enabled')
cool, for readability i think we should be consistent. `.should('be.disabled')` is more clear IMO

2021-05-24 14:37 UTC, shlokamin commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    cy.get('input[name="dispense_mix_checkbox"]').click({ force: true })
I am not seeing `{ force: true }` as necessary for checkboxes in the documentation. If the checkbox is hidden by the parent div, that is not good, as this means it is not accessible. 

I just looked into why this is happening, and it is indeed because we are hiding the checkbox so we can render an SVG of the icon on top of the actual input element, which is pretty bad because this means people cannot tab over the checkbox if they need to. 

We probably should not be doing this @IanLondon @Kadee80 but it looks like this functionality in the checkbox field is part of CL :/

2021-05-24 14:38 UTC, Kadee80 commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    cy.get('input[name="dispense_mix_checkbox"]').click({ force: true })
> I am not seeing `{ force: true }` as necessary for checkboxes in the documentation. If the checkbox is hidden by the parent div, that is not good, as this means it is not accessible.
> 
> I just looked into why this is happening, and it is indeed because we are hiding the checkbox so we can render an SVG of the icon on top of the actual input element, which is pretty bad because this means people cannot tab over the checkbox if they need to.
> 
> We probably should not be doing this @IanLondon @Kadee80 but it looks like this functionality in the checkbox field is part of CL :/

Need to re-remember this but there should be a tab-index prop that would help with this? I know it exists for other form components.

2021-05-24 18:44 UTC, shlokamin commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    cy.get('input[name="aspirate_flowRate"]').should('have.value', '')
looks like you can do this: 

```js
  cy.get('input[name="aspirate_flowRate"]').should('have.attr', 'placeholder', '-')
```

https://example.cypress.io/commands/querying

2021-05-24 18:44 UTC, shlokamin commented on protocol-designer/cypress/integration/transferSettings.spec.js
> +    cy.get('input[name="aspirate_flowRate"]').should('have.value', '')
the value is an empty string (which you have), but we also wanna make sure we are displaying the correct placeholder

2021-05-24 18:46 UTC, shlokamin approved these changes
LGTM! Also left a comment in the thread about testing for the dash in the placeholder for indeterminate values

2021-05-25 20:40 UTC, Kadee80 approved these changes
🐬 looks great!

2021-05-27 15:26 UTC, nusrat813 approved these changes
LGTM

2021-06-01 13:21 UTC, merged