feat(api): protocol engine command queue worker
OpenTrons/opentrons-api pull request #7817
Opened 2021-05-18 00:24 UTC by amitlissack

# Overview

closes #7646

# Changelog

# Review requests

# Risk assessment

2021-05-18 18:44 UTC, SyntaxColoring commented
With the current interface, this class might have error propagation pitfalls.

`.play()` and `.pause()` return instantly; they merely schedule the play or pause to happen soon. Which means there's no way for the `CommandQueueWorker` to propagate a command error.

I'm pushing to this branch:

* A fix so that the error will at least propagate to the holder of the `CommandQueueWorker` when they call `.wait_terminated()`.
* Some fleshed-out docstrings to call out the existing behavior and hopefully make it easier to code-review code that uses this class.

The Trio approach to making this more foolproof—which I agree with—[would be to use a "nursery" context manager](https://trio.readthedocs.io/en/stable/reference-core.html#tasks-let-you-do-multiple-things-at-once). We shouldn't spawn a child task unless we can prove that we—or, at least, *someone*—is going to be a responsible parent for it.

But it's hard to guess what the interface of this class needs to provide before seeing it in action. So I'm holding off on making those changes until we see this class used in context.

2021-05-18 19:38 UTC, celsasser commented on api/src/opentrons/file_runner/json_file_runner.py
> +    def __init__(
Is this picked up from @sanni-t 's recent PR - https://github.com/Opentrons/opentrons/pull/7797/files#diff-6b95c553d2325826d1e5df2572635789e511e6cf82c9a9985d6e6b1e311aeab4R10?  (maybe should read the PR...)

2021-05-18 19:44 UTC, amitlissack commented on api/src/opentrons/file_runner/json_file_runner.py
> +    def __init__(
Oops. I should re-target. I always make the same mistake.

2021-05-18 20:29 UTC, SyntaxColoring commented on api/src/opentrons/file_runner/command_queue_worker.py
> +        """Wait until this `CommandQueueWorker` has stopped executing new commands.
Would a name like `wait_to_be_idle()` be more representative of what this method does?

2021-05-18 20:30 UTC, SyntaxColoring commented on api/src/opentrons/file_runner/command_queue_worker.py
> +            self._task = None
Not entirely sure what to do about this, yet.

It might turn out to be moot when we see what we need out of this class when it's used in context, so I'm avoiding thinking about it too hard for now.

2021-05-18 20:34 UTC, SyntaxColoring commented on api/src/opentrons/file_runner/command_queue_worker.py
> +            )
Unclear to me: What happens (or should happen) if a command raises an error? Is that command returned to the front of the queue, or is it consumed?

2021-05-20 15:42 UTC, mcous requested changes
I've got a fair number of thoughts on this one! Let me know if you'd like to discuss

2021-05-20 15:42 UTC, mcous commented on api/src/opentrons/file_runner/command_queue_worker.py
> +            )
Let's model existing behavior: if a command raises an error, the run is aborted. This doesn't need to be handled here; the queue can be configured to return no pending commands if there is a `FailedCommand` in the queue

2021-05-20 15:42 UTC, mcous commented on api/src/opentrons/file_runner/command_queue_worker.py
> +        self.stop()
Should `pause` and `stop` have different behaviors? For example:

- `pause`: pause queue processing
- `stop`: marked current command (if any) as `Cancelled`, pause queue processing
    - Perhaps this indicates that the engine needs a `cancel_command` by ID method

2021-05-20 15:42 UTC, mcous commented on api/src/opentrons/file_runner/command_queue_worker.py
> +            self._task = asyncio.create_task(self._loop())
I'm fairly partial to a different sort of algorithm for these sorts of loops, where the worker has two methods: one to do the work, and one to schedule the next unit of work, if needed.

- `_execute_command`
    2. `await` the command's execution 
    3. Call `self.schedule_next_command` when the execution is done
- `_schedule_next_command`
    1. Check if the worker should be running
    2. Get next pending command ID
    3. Call `self._task = create_task(self._execute_command(command_id))` if there's a command in the queue
        - Else do `self._task = None` or something 

The reason I like this is that we can separate out execution from scheduling, and also we don't have to write `break` anywhere because there's no while loop. Instead of one big `self._task` the represents the loop, you end up with a self-perpetuating series of `self._task` values, where the current task is always **the execution of the current command**

2021-05-20 15:42 UTC, mcous commented on api/src/opentrons/file_runner/command_queue_worker.py
> +            ProtocolEngineError: If there was a problem executing one of the commands
This isn't true as written (not that it has to remain the way it currently is!). `engine.execute_command` does not raise right now; it captures errors and puts them in state

2021-05-20 15:42 UTC, mcous commented on api/src/opentrons/file_runner/command_queue_worker.py
> +        When you're finished with a `CommandQueueWorker`, you must call this method on
I don't love this requirement; I think the worker should be able to clean up after itself. See my comment about the task chain for an idea about how that can be accomplished

2021-05-20 15:42 UTC, mcous commented on api/tests/opentrons/file_runner/test_command_queue_worker.py
> +async def test_pause(
This is a pretty funky test (especially `mock_execute_command`), and it says to me that maybe this code could be structured in a way to make this more testable. I think using `decoy` over `MagicMock` could be helpful here, given that it's API is intentionally limited to provide test pain to guide subject structure.

If we ask ourselves "what does pause mean?", I think we only have one real requirement:

- While paused, any attempt to "get the next pending command" should return `None`

I think this test becomes more simple if we spin that functionality off into its own unit, a `CommandQueue` wrapper of the protocol engine. Maybe that `CommandQueue` has three methods:

- `pause`
- `unpause` (or whatever)
- `get_next_command`

Tests for the `CommandQueue` look like:

- Test that it returns the proper command given engine state
- Test that it returns `None` if `pause` was called
- Test that it can be `unpause`'d

Tests for `pause` of the `CommandQueueWorker` then become:

- Test that `worker.pause` and `worker.stop` tell the queue to pause
- Test that `worker.play` tells the queue to unpause
- Ensure that `CommandQueue.get_next_command` is used to feed the next command ID in

That lets you side-step all this lifecycle weirdness and takes `CommandQueueWorker` to a place where it is more strictly a collaborator and not both a thing that delegates _and_ a thing that has logic.

This entire video is great if you haven't already watched it, but it's got [a section specifically about do vs. delegate](https://youtu.be/aTqC5CIy7mg?t=1127).

2021-05-20 15:42 UTC, mcous commented on api/src/opentrons/file_runner/command_queue_worker.py
> +            pending = self._engine.state_store.commands.get_next_request()
I think it would be better if the command queue worker could deal only in command IDs, i.e. get the ID of the next pending command and tell the engine to execute the pre-existing command with that ID. I think this means re-working or replacing `execute_command`

Because the existing implementation of `execute_command` does too much (it creates _and_ executes the command), this will overwrite the `createdAt` time of the command, which would have been set when it was loaded into the engine.

I think where we currently use `execute_command`, we should replace it with `create_command` from #7797 followed by a new "execute command by ID" method added by this PR

2021-06-01 13:46 UTC, mcous commented on api/src/opentrons/file_runner/command_queue_worker.py
> +            pending = self._engine.state_store.commands.get_next_request()
**Update on this change request: let's punt it.**

In my experimentation this is gnarlier than expected. The PE's design needs to adjust more than expected to account for what had previously only been speculative

2021-06-07 18:31 UTC, SyntaxColoring commented on api/src/opentrons/file_runner/command_queue_worker.py
> +        """Wait until this `CommandQueueWorker` has stopped executing new commands.
Doing this.

2021-06-08 17:51 UTC, SyntaxColoring commented on api/src/opentrons/file_runner/command_queue_worker.py
> +        self.stop()
As discussed in a call (I think): we'll delete `pause()` for now, since it's anticipating a difference that doesn't actually exist today.

Your thoughts about the engine growing a `cancel_command(id)` method sound good to me.

2021-06-08 18:18 UTC, SyntaxColoring commented on api/src/opentrons/file_runner/command_queue_worker.py
> +            self._task = asyncio.create_task(self._loop())
As we sort of talked about in a call and DMs, I'm not doing this in this PR, because its interaction with how the rest of the class is implemented would cause a bug.

`wait_to_be_idle()` is currently implemented roughly like:

```python
async def wait_to_be_idle(self) -> None:
    if self._task is not None:
        await self._task
        self._task = None
```

The bug is that this would only wait for the *first* task (or some nondeterministic task) to complete, not the *final* task. So, if you `.play()` and then immediately `.wait_to_be_idle()`, `.wait_to_be_idle()` could return after only the *first command* completes, while the rest of the commands are still running.

We could rewrite `wait_to_be_idle()` to fix this. I only got halfway-ish into this before abandoning it, but I think it would require adding an `asyncio.Event` class attribute, and `await`ing that instead of a task to wait for idleness. My hesitations about this are:

* It adds another piece of confusingly quasi-orthogonal state to the class. Although we could mitigate this by having a more structured, dedicated `WorkerState` type instead of a bunch of loose attributes.
* It's difficult (impossible?) to ensure that every task in that self-perpetuating chain is `await`ed. A consequence of not `await`ing a task is that exceptions won't be propagated properly, potentially making errors turn into hangs, or otherwise leaving things in an inconsistent state. (A lot of my fear of un-`await`ed tasks comes from the essay [Notes on structured concurrency, or: Go statement considered harmful](https://vorpus.org/blog/notes-on-structured-concurrency-or-go-statement-considered-harmful).)

So I'm going back to the original approach of having a single task with a loop.

----

I did find a way to rewrite the `while` loop as a `for` loop, though. Maybe that partially addresses your original concern that `while` loops with `break`s don't feel fail-safe?

2021-06-08 18:19 UTC, SyntaxColoring commented on api/src/opentrons/file_runner/command_queue_worker.py
> +            self._task = None
I lost track of this through subsequent rewrites, but I *think* no problem like this exists in the current code.

2021-06-08 18:20 UTC, SyntaxColoring commented on api/src/opentrons/file_runner/command_queue_worker.py
> +            )
Edit: I forgot `get_next_request()` is currently totally unimplemented. I left a note in its docstring for this requirement. We'll do this in another PR.

2021-06-08 18:50 UTC, SyntaxColoring commented on api/src/opentrons/file_runner/command_queue_worker.py
> +        When you're finished with a `CommandQueueWorker`, you must call this method on
Discussion of the task chain idea: https://github.com/Opentrons/opentrons/pull/7817#discussion_r636174409

Notes from call:

* The cleanup requirement turns out to be approximately the same whether we have a single task or a self-perpetuating chain of tasks.
* Arguably, there is no cleanup requirement in *either* case; it's not like we need to free a file descriptor, or something.
* However, I eel fairly strongly that if you spawn an asyncio task, you need to make sure it's `await`ed at some point. This makes sure the language's normal mechanisms of exception propagation and resource cleanup work properly. I stole this opinion from [Notes on structured concurrency, or: Go statement considered harmful](https://vorpus.org/blog/notes-on-structured-concurrency-or-go-statement-considered-harmful/).

Further thoughts:

Taking for granted that an `await` needs to happen, there's an open interface design question of *where* it should happen, from the `CommandQueueWorker` caller's perspective. Do you call `await wait_to_be_idle()` just once when you're done with the class? Do you call it between each adjacent `pause()` and `play()`? Do we make `pause()` async and bake the `await` into that?

Meanwhile, I softened the documentation from "must" to "should" and left a todo to look into this further.

2021-06-08 18:53 UTC, SyntaxColoring commented on api/src/opentrons/file_runner/command_queue_worker.py
> +            return None
Given that `CommandRequestType` is part of the public interface of `get_next_request()`, should it be importable as `protocol_engine.CommandRequestType` or something?

2021-06-08 20:12 UTC, SyntaxColoring commented on api/src/opentrons/file_runner/command_queue_worker.py
> +            ProtocolEngineError: If there was a problem executing one of the commands
Thanks. Removed this note.

Other error-handling discussion in this thread: https://github.com/Opentrons/opentrons/pull/7817#discussion_r634727526

2021-06-09 14:07 UTC, SyntaxColoring commented on api/src/opentrons/file_runner/command_queue_worker.py
> +        if self._task is not None:
Do we still need this if we have a single big loop task?

2021-06-09 14:15 UTC, SyntaxColoring commented on api/tests/opentrons/file_runner/test_command_queue_worker.py
> +async def test_stop(
Should be `test_pause()`.

2021-06-09 14:19 UTC, mcous approved these changes
LGTM 📦 (discussed a lot in person)

2021-06-09 14:36 UTC, SyntaxColoring commented on api/tests/opentrons/file_runner/test_command_queue_worker.py
> +async def test_pause(
Notes from call:

* We'll revisit these tests in a future pairing session. Leaving them mostly alone for now.

2021-06-09 14:47 UTC, SyntaxColoring commented on api/src/opentrons/file_runner/command_queue_worker.py
> +        if self._task is not None:
Removed.

2021-06-09 16:40 UTC, sanni-t approved these changes
👷‍♂️
Thanks for updating all the comments with details from your discussion!

2021-06-09 16:40 UTC, sanni-t commented on api/tests/opentrons/file_runner/test_command_queue_worker.py
> +    """It not execute any commands."""
```suggestion
    """It should not execute any commands."""
```

2021-06-09 19:48 UTC, merged