Change instances of wells to well
OpenTrons/opentrons-api pull request #7828
Opened 2021-05-24 17:08 UTC by ethanfjones

plate.wells() was used when plate.well() should be used. I replaced all instances of plate.wells() with plate.well()

# Overview

# Changelog

# Review requests

# Risk assessment

2021-05-24 17:34 UTC, Laura-Danielle requested changes

2021-05-24 17:34 UTC, Laura-Danielle commented on api/docs/v2/new_examples.rst
> +            p300.distribute(200, reservoir.well()[i], plate.rows()[i])
This should still be `.wells()`.

2021-05-24 17:34 UTC, Laura-Danielle commented on api/docs/v2/new_examples.rst
> +        for well in reservoir.well()[:4]:
Same here.

2021-05-24 17:34 UTC, Laura-Danielle commented on api/docs/v2/new_examples.rst
> +        p300.distribute(50, reservoir['A12'], plate.well())  # dilutent
Same for this example as well.

2021-05-24 17:34 UTC, Laura-Danielle commented on api/docs/v2/new_examples.rst
> +            source = reservoir.well()[i]
Also here

2021-05-24 17:34 UTC, Laura-Danielle commented on api/docs/v2/new_examples.rst
> +        p300.aspirate(100, plate.well('A1'))
Technically, this is deprecated behavior. I'm wondering if we should just remove this completely from the docs to discourage users from using this.

2021-05-24 19:01 UTC, ethanfjones commented on api/docs/v2/new_examples.rst
> +        p300.aspirate(100, plate.well('A1'))
Gotcha so wells can only be used with distribute/transfer? 


I only tested this with the aspirate and assumed the others were just a typo.

2021-05-24 19:42 UTC, SyntaxColoring commented on api/docs/v2/new_examples.rst
> +        p300.aspirate(100, plate.well('A1'))
The deprecated behavior is that the well name is passed as an argument to the `.wells()` function, instead of as an index into the list that it returns.

In other words, instead of this:

```python
plate.wells('B1')
```

It should be one of these:

```python
plate.wells()[1]
# or
plate.wells_by_name()['B1']
```

> Note that this method takes args for backward-compatibility, but use of args is deprecated and will be removed in future versions. Args can be either strings or integers, but must all be the same type (e.g.: self.wells(1, 4, 8) or self.wells(‘A1’, ‘B2’), but self.wells(‘A1’, 4) is invalid.

(from https://docs.opentrons.com/v2/new_protocol_api.html?highlight=wells#opentrons.protocol_api.labware.Labware.wells)

2021-05-24 19:43 UTC, SyntaxColoring commented on api/docs/v2/new_examples.rst
> +        p300.aspirate(100, plate.well('A1'))
I agree with Laura that our example code shouldn't be using the deprecated `plate.wells(well_name)` form.

2021-05-25 19:09 UTC, Laura-Danielle commented on api/docs/v2/new_examples.rst
> +        p300.aspirate(100, plate.well('A1'))
Sorry I'm not getting notifications on my github comments for some reason.

The equivalent of `plate.well('B1')` is now -> `plate['B1']`. If a user wants to have a _list_ of wells, they should simply use python indexing; i.e. `plate.wells()[0:7]` which would give the first column of a 96 well labware.

@ethanfjones, I'm not sure I follow ``Gotcha so wells can only be used with distribute/transfer?``. You can only use a single well when using the "atomic" commands such as aspirate or dispense. You can use a single well _or_ a list of wells for advanced commands such as distribute or transfer.

2021-05-25 20:06 UTC, ethanfjones commented on api/docs/v2/new_examples.rst
> +        p300.aspirate(100, plate.well('A1'))
@Laura-Danielle and Mr. Syntax, thanks for the response. 

Your explanation makes sense to me!

2021-05-27 22:11 UTC, Laura-Danielle approved these changes

2021-05-27 22:25 UTC, SyntaxColoring requested changes

2021-05-27 22:25 UTC, SyntaxColoring commented on api/docs/v2/new_examples.rst
>          p300.drop_tip()
There's both a `p300.return_tip()` and `p300.drop_tip()` here. Merge mistake?

2021-05-27 22:27 UTC, SyntaxColoring commented on api/docs/v2/new_examples.rst
>          p300.drop_tip()
Looks like it should be `drop_tip()` (see #7834).

2021-05-27 22:29 UTC, Laura-Danielle commented on api/docs/v2/new_examples.rst
>          p300.drop_tip()
yep it's a merge mistake. Thought I deleted that pesky `return_tip`

2021-05-27 22:31 UTC, SyntaxColoring approved these changes

2021-05-27 22:32 UTC, merged