feat(labware-creator): Add hand placed tip fit section and alerts
OpenTrons/opentrons-api pull request #7832
Opened 2021-05-24 21:40 UTC by Kadee80

# Overview

closes #7713

# Changelog

- feat(labware-creator): Add hand placed tip fit section and alerts
- add tests

# Review requests

- [ ] Hand-Fit section only renders when tipRack is selected
- [ ] Hand fit dropdown is required when visible (orange) (dont select an option and blur the field)
- [ ] Selecting `loose` renders error (red)
- [ ] Selecting `snug` renders info to proceed (blue)
- [ ] Code/tests are sane?

# Risk assessment

Low. This field is new but it does not affect labware definition generation.

2021-05-25 14:32 UTC, IanLondon commented on labware-library/src/labware-creator/labwareFormSchema.ts
> +    handPlacedTipFit: Yup.mixed().when('labwareType', {
can it be `string()` instead of `mixed()`?

2021-05-25 14:33 UTC, Kadee80 commented on labware-library/src/labware-creator/labwareFormSchema.ts
> +    handPlacedTipFit: Yup.mixed().when('labwareType', {
i'll give that a try.

2021-05-25 14:34 UTC, IanLondon commented on labware-library/src/labware-creator/components/utils/getTipFitAlerts.tsx
> +export const getTipFitAlerts = (
could this be a normal component `TipFitAlerts` that takes props?

2021-05-25 14:36 UTC, IanLondon commented on labware-library/src/labware-creator/components/FormAlerts.tsx
> +    key={LOOSE_TIP_FIT_ERROR}
IDK if `key` is doing anything in this component scope

2021-05-25 14:38 UTC, IanLondon requested changes
left some comments

2021-05-25 16:25 UTC, Kadee80 commented on labware-library/src/labware-creator/components/utils/getTipFitAlerts.tsx
> +export const getTipFitAlerts = (
sure!

2021-05-25 16:29 UTC, Kadee80 commented on labware-library/src/labware-creator/components/utils/getTipFitAlerts.tsx
> +export const getTipFitAlerts = (
actually, lets leave this as a follow up PR since we also have getHeightAlerts and getXYDimensionAlerts in utils that should be changed but i don't want to muddy this PR with refactoring all of them

2021-05-25 16:30 UTC, Kadee80 commented on labware-library/src/labware-creator/components/FormAlerts.tsx
> +    key={LOOSE_TIP_FIT_ERROR}
i think it is since we can have multiple errors in the map below

2021-05-25 17:04 UTC, IanLondon commented on labware-library/src/labware-creator/components/__tests__/sections/HandPlacedTipFit.test.tsx
> +    expect(screen.getByText('Hand-Placed Tip Fit'))
does wrapping these in `expect` do anything? If I remember right, it doesn't, the `getBy___` fns will raise an error and `expect` won't do anything special with it (I thiiink...)

2021-05-25 17:06 UTC, IanLondon commented on labware-library/src/labware-creator/components/__tests__/sections/HandPlacedTipFit.test.tsx
> +    when(getTipFitAlertsMock)
should we use the real thing instead of mocking this? Not a rhetorical question, I don't know what the answer is! But I thought mocking children was contrary to react-testing-library

2021-05-26 14:52 UTC, IanLondon approved these changes

2021-05-26 16:34 UTC, merged