refactor(robot-server): start sessions router for HTTP-based runs
OpenTrons/opentrons-api pull request #7833
Opened 2021-05-24 22:46 UTC by mcous

## Overview

This PR builds of the #7804 research spike to add a new `/sessions` router that will execute protocols runs using a `ProtocolEngine`, `AbstractFileRunner`, and other associated interfaces.

Specifically, this starts building out stubs for the following robot-server interfaces and value objects:

- `SessionStore`, where session resource data can be kept in memory
- `SessionRunner`, where `ProtocolEngine` and `FileRunner` instances can be managed
- `Session` models, to be replaced / merged with pre-existing session models
- `SessionInput` models, to provide an interface for controlling the lifecycle of a session (aka play/pause)

This takes out a chunk of #7808 by providing the beginnings of HTTP routes to:

- Create a session from a protocol resource
- Tell the session to start executing

## Changelog

- refactor(robot-server): start sessions router for HTTP-based runs

## Review requests

Two main requests on this one:

- I'm interested in feedback from a standpoint of data encapsulation and interface / responsibility design
    - e.g. "SessionInput is a weird name, what about XYZ" is helpful, because the name of the value object affects perceived responsibilities
    - e.g. "We need other session types" is not helpful, because having more subclasses of Session in this PR wouldn't change how data flows through the routes and dependencies
- Tests in this PR are for interface design of the router, so please approach them from that standpoint
    - Do they communicate the intent of the test subject's dependency orchestration well?
    - Is the test subject doing a good job of not mixing logic with delegation?

This new sessions router is placed behind the `enableProtocolEngine` feature flag, but all routes will raise a `NotImplementedError` right now. If you'd like to see for yourself, go ahead and run the dev server with the feature flag enabled:

```shell
make dev OT_API_FF_enableProtocolEngine=true
```

## Risk assessment

No risk for production code. The risk here is mostly in strategy and approach. Eventually, this sessions router and models will need to account for existing flows, like deck calibration and tip length check. The trick will be to pay down tech debt while keeping that stuff operational.

2021-05-25 16:30 UTC, celsasser requested changes
I like it. Most of my feedback is questions, curiosity and some suggestions. Only two typo change requests.

2021-05-25 16:30 UTC, celsasser commented on robot-server/robot_server/router.py
> +from .sessions import sessions_router as experimental_sessions_router
Pretty insignificant, but being that this is our future (and am very optimistic about it) in the interest of minimizing changes when we tear the old stuff out does it make sense to let this guy be named `sessions_router` and rename the older one to something like `deprecated_session_router`?

2021-05-25 16:30 UTC, celsasser commented on robot-server/robot_server/sessions/dependencies.py
> +    """Get the current system time."""
I remember seeing an argument (think it was in the pragmatic programmer) that I agree with which had to do with redundant comments. They said it much more eloquently, but essentially is there value in a comment that restates a well named function. And, well done in choosing a well named function :).  

But can see reasons for including it so that we don't neglect it as the function develops?

2021-05-25 16:30 UTC, celsasser commented on robot-server/robot_server/sessions/dependencies.py
> +    """Generate a unique identifier string."""
I don't know why this guy draws my attention. I think it's because of the localization of unique id creation. Unique id generation seem to be a common problem (with lots of different variations) and wondering whether the functionality to create them should be more central and standardized. Like for example, reserve the possibility of using URNs (which I like but that's just a personal preference motivated by the information they contain).

2021-05-25 16:30 UTC, celsasser commented on robot-server/robot_server/sessions/dependencies.py
> +"""Session router dependency wire-up."""
I wondered why this guy is called `dependencies.py` and then learned a little about fastAPI and see that he supports dependency injection. I also see that these methods are being used via dependency injection. But still have a hard time thinking of them as dependencies in a way that other functions are not dependencies. So then found myself wondering about the name again. If this is a convention and you guys embrace it then unread all that you just read :)

2021-05-25 16:30 UTC, celsasser commented on robot-server/robot_server/sessions/router.py
> +@sessions_router.post(
FastAPI seems really neat. Well done, Mike!

2021-05-25 16:30 UTC, celsasser commented on robot-server/robot_server/sessions/router.py
> +@sessions_router.get(
Just wondering whether we want query-param filtering control? Such as the ability to exclude inactive sessions?

2021-05-25 16:30 UTC, celsasser commented on robot-server/robot_server/sessions/router.py
> +        "Provide input data to the session in order to control the"
Does it need a space or is this python magic?

2021-05-25 16:30 UTC, celsasser commented on robot-server/robot_server/sessions/router.py
> +        session = session_store.remove_session_by_id(session_id=sessionId)
Okay, I know this is dumb but being that the function is called `remove_session_by_id` is it sort of redundant to name the parameter vs. by position?  If the function were called `remove_session` it would make total sense to me. And would match his `session_store.get_session` buddy up above.

2021-05-25 16:30 UTC, celsasser commented on robot-server/robot_server/sessions/router.py
> +@sessions_router.post(
I don't know what session inputs are but am an advocate of having GET support where one has PUT/POST functionality. Integration tests come to mind if there are no other reasons.

2021-05-25 16:30 UTC, celsasser commented on robot-server/robot_server/sessions/session_models.py
> +class Session(ResponseDataModel):
Wondering about naming convention. I see right up above we are explicit in naming input models but here are not referring to it as a response object. Is it because we use him in contexts outside of the API? Same goes for his friends such as `SessionInput`.

2021-05-25 16:30 UTC, celsasser commented on robot-server/robot_server/sessions/session_runner.py
> +    def handle_input(
Haha, this confused me. "handle input - wow, this is going to be a very busy method". But see that it is designed to handle what we call "session input". Probably not confusing to people more familiar with sessions. Though wondering whether it may help to call it something other than `handle`? Maybe `create_input`? Looking at other handler names they seems to match their HTTP method, for example: `create_session`, `get_session`, `remove_session_by_id`.

2021-05-25 16:30 UTC, celsasser commented on robot-server/tests/helpers.py
> +# TODO(mc, 2021-05-24): add links checking
I've seen some TODOs that date back to times when we were writing programs on cave walls. I'm wondering whether there is any policy about creating tickets vs. TODOs or a TODO pointing to a ticket...

2021-05-25 16:30 UTC, celsasser commented on robot-server/tests/sessions/test_sessions_router.py
> +def test_create_session_explicitely(
```suggestion
def test_create_session_explicitly(
```

2021-05-25 16:30 UTC, celsasser commented on robot-server/tests/sessions/test_sessions_router.py
> +def test_create_basic_session_implicitely(
```suggestion
def test_create_basic_session_implicitly(
```

2021-05-25 16:30 UTC, celsasser commented on robot-server/tests/sessions/test_sessions_router.py
> +    expected_session = Session(id=unique_id, createdAt=current_time)
Fixtures are new to me and think they are really cool, but wondering what the dividing line is? Like here, would a `session` fixture valuable being that sessions with the same params are being created in other places in here?

2021-05-25 16:30 UTC, celsasser commented on robot-server/tests/sessions/test_sessions_router.py
> +def test_delete_session_by_id_with_missing_id(
We are like willy wonka and make the impossible possible.

2021-05-25 16:37 UTC, celsasser commented on robot-server/tests/sessions/test_sessions_router.py
> +def test_delete_session_by_id_with_missing_id(
https://www.youtube.com/watch?v=3pwvB4_Te8A. Covid destroyed lickable wallpaper's market potential.

2021-05-25 17:05 UTC, mcous commented on robot-server/robot_server/sessions/dependencies.py
> +    """Get the current system time."""
Ping @SyntaxColoring

2021-05-25 17:06 UTC, mcous commented on robot-server/robot_server/sessions/dependencies.py
> +    """Generate a unique identifier string."""
Probably! For now, is it cool if we consider this a design-exploration stub and replace when we have (integration) tests in place to do so?

2021-05-25 17:07 UTC, mcous commented on robot-server/robot_server/sessions/dependencies.py
> +"""Session router dependency wire-up."""
"Embrace" is a strong word, because I'm definitely open to suggestions, but yeah was just following some other file names I've seen in the robot_server. I'd be looking for a filename that communicates: *"look here to see what this router's dependency graph looks like"*

2021-05-25 17:08 UTC, mcous commented on robot-server/robot_server/sessions/router.py
> +@sessions_router.get(
Yes for sure, but I'd like to keep out of scope for this PR

2021-05-25 17:09 UTC, mcous commented on robot-server/robot_server/sessions/router.py
> +@sessions_router.post(
Yup, my plan would be to make the `SessionInput` list part of the `Session` response itself when we get to fleshing out of those models. I think that would include a `GET /sessions/:sid/inputs` etc. endpoints as well

2021-05-25 17:11 UTC, mcous commented on robot-server/robot_server/sessions/session_models.py
> +class Session(ResponseDataModel):
I'm of the personal opinion that it's nice not to call things `SomeResourceResponse` if the model is supposed to be a projection of "some resource"; just call it `SomeResource`, save some typing, and make the schema a little easier to read / use as generated types on the client-side.

This isn't a super strongly help belief, so happy to do whatever for consistency and get it written down in the style guide

2021-05-25 17:14 UTC, mcous commented on robot-server/robot_server/sessions/session_runner.py
> +    def handle_input(
`SessionInput` is something I invented for this PR, so we're all confused. Very open to suggestions for naming "thing that represents a client's lifecycle control command but not a scientific command".

I agree, though, I think this needs some sort of split between resource creation / storage and handling whatever side-effects are necessary for a given control command.

2021-05-25 17:46 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/dependencies.py
> +"""Session router dependency wire-up."""
Yeah, this confused me when I first learned FastAPI, too.

`fastapi_dependencies.py`? `injectable_dependencies.py`?

Alternatively, I mean, FastAPI dependencies are *mostly* normal functions. (Mostly, not entirely. FastAPI has its own not-quite-vanilla-context-managers way to code dependencies that do cleanup, to my chagrin.) What would we call this module if FastAPI *didn't* have dependency injection, and we used them as normal functions? `support.py`? `binding.py`?

2021-05-25 17:56 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/session_runner.py
> +    def handle_input(
IMO this is a symptom of overgenerality. We're trying to handle all these different session types and operations in the same ways, so we have to take the endpoints so high up in abstraction that we drain them of concrete meaning. We can't get much more specific than "provide input data for...whatever this input data is used for."

I'm writing up more detailed thoughts now.

2021-05-25 18:46 UTC, mcous commented on robot-server/robot_server/sessions/router.py
> +@sessions_router.post(
Added `inputs` field to the `Session` resource model. Would like to punt on more endpoints to keep this already large PR from growing

2021-05-25 18:48 UTC, mcous commented on robot-server/tests/helpers.py
> +# TODO(mc, 2021-05-24): add links checking
Not at the moment, but very open to suggestions!

2021-05-25 18:52 UTC, celsasser commented on robot-server/robot_server/sessions/dependencies.py
> +    """Generate a unique identifier string."""
Sure. Do you want to add a todo? Either way, I'll resolve it.

2021-05-25 18:54 UTC, celsasser commented on robot-server/robot_server/sessions/dependencies.py
> +"""Session router dependency wire-up."""
A lot of stuff in this directory that has to do with sessions (which I imagine it all does) adopts the prefix `session_`. And they all seem to encapsulate roles (input, models, runner). What do you guys think about `session_operations`?

2021-05-25 18:55 UTC, celsasser commented on robot-server/robot_server/sessions/router.py
> +@sessions_router.get(
Got it.

2021-05-25 18:58 UTC, celsasser commented on robot-server/tests/helpers.py
> +# TODO(mc, 2021-05-24): add links checking
I guess it depends on whether this is a not to yourself for the near future or if this is something you would like to see happen but runs the risk of not happening anytime soon.

2021-05-25 18:59 UTC, mcous commented on robot-server/tests/sessions/test_sessions_router.py
> +    expected_session = Session(id=unique_id, createdAt=current_time)
I think here specifically there's a little bit of danger with test fixtures obscuring the intent of the test. Here, we need to make sure that the `unique_id` and `current_time` dependencies are fed properly into the created `Session` resource, so it's nice to have it all right here in test itself, at the expense of verbosity.

I figure we'll definitely end up with some model fixtures for this router's tests before all's said and done, though

2021-05-25 19:05 UTC, celsasser commented on robot-server/robot_server/sessions/dependencies.py
> +"""Session router dependency wire-up."""
Sorry, totally missed @SyntaxColoring 's suggestions. Think this point is great, `Alternatively, I mean, FastAPI dependencies are mostly normal functions. (Mostly, not entirely. FastAPI has its own not-quite-vanilla-context-managers way to code dependencies that do cleanup, to my chagrin.) What would we call this module if FastAPI didn't have dependency injection, and we used them as normal functions?`

2021-05-25 19:39 UTC, mcous commented on robot-server/tests/helpers.py
> +# TODO(mc, 2021-05-24): add links checking
More of the former than the latter. The current sessions router includes response links, so if we didn't add `links` then the integration tests would fail with the new router once we switched. Mostly skipped them right now because `links` are under active discussion as part of the styleguide

2021-05-25 19:41 UTC, mcous commented on robot-server/robot_server/sessions/session_runner.py
> +    def handle_input(
Split this into:
1. `session_store.create_input` to create (and store) the input resource model
2. `session_runner.trigger_input_effects` to... trigger effects, like pausing a `Runner` class

2021-05-26 03:00 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/dependencies.py
> +    """Get the current system time."""
Haha yeah, this is a big pet peeve of mine. 😁 

I had an essay written up, but I don't think this PR is the place for it. Good callout for the style guide. Are you thinking this is an HTTP API style guide thing, or a Python-in-general style guide thing?

In this specific case, I agree with @celsasser:

* We should consider renaming `get_current_time()` to `get_current_system_time()`.
* We should remove the docstring. If the linter complains about that, the linter is wrong, and we should either disable that overzealous check, or work around it with a `#noqa`.

2021-05-26 03:09 UTC, mcous commented on robot-server/robot_server/sessions/dependencies.py
> +"""Session router dependency wire-up."""
I think for now I'm going to stick with `dependencies.py` for a few reasons:

- It's what we're already doing (see `robot_server/service/dependencies.py`)
- It's what FastAPI suggests for project structure](https://fastapi.tiangolo.com/tutorial/bigger-applications/#dependencies) (Not that these sorts of things should be followed blindly)
- There's symmetry between `dependencies.py` and the `Depends` utility they all require

> What would we call this module if FastAPI didn't have dependency injection, and we used them as normal functions?

It's hard to see in this PR with a series of `NotImplementedError`s, but these functions are all intended to be factory functions to initialize our utility classes with the correct dependence graph so they can be injected. Without dependency injection, these functions don't exist, and utility class initialization / wire-up happens in a more ad-hoc manner

2021-05-26 14:07 UTC, mcous commented on robot-server/robot_server/sessions/dependencies.py
> +    """Get the current system time."""
Would fleshing out the docstring also be an option?

```py
def get_current_time() -> datetime:
    """Get the current system time.
    
    This dependency can be used to generate timestamps for resource
    creation and updates.

    Returns:
        The current time in UTC
    """"

2021-05-26 14:49 UTC, celsasser approved these changes
There are a couple of comments that are optional. Looks good.

2021-05-26 15:56 UTC, SyntaxColoring reviewed
GitHub threw away some of my work, ugh, so this is a partial review while I find the rest of my comments.

2021-05-26 15:56 UTC, SyntaxColoring commented on robot-server/robot_server/router.py
> +from .sessions import sessions_router as experimental_sessions_router
Could the other router also be considered experimental? (It's involved in a beta, right?)

How about `protocol_engine_backed_router`?

Edit: I see in a later commit you've changed the other one to `deprecated_session_router`. I think that's fine, too.

2021-05-26 15:56 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/dependencies.py
> +    raise NotImplementedError()
To supplement the docstring discussion in the other thread:

The fact that a `SessionStore` is "an interface to retrieve session data" is potentially a good, meaningful tidbit to have in a docstring. But, I think it belongs only in the `SessionStore` class docstring, not this function docstring.

These function docstrings would be the place to explain facts about the functions themselves, like how they'll return a single shared `SessionRunner` across all requests. (And even that might be unnecessary to document, since it's such a common pattern in our dependencies.) But if there's nothing like that, I think we should omit them.

I'm pretty aggressively DRY about docstrings. Giving a cold audience a good intuition for something can be difficult—so we should attempt it in as few places as possible, and focus on doing it well in those places. And, if the docstring is duplicated, there's a risk that someone could come along later, thoughtfully try to improve the docstring, but improve the "wrong copy" of the docstring.

Ditto for `SessionRunner`.

2021-05-26 15:56 UTC, SyntaxColoring commented on robot-server/robot_server/router.py
> +from .service.session.router import router as deprecated_session_router
For my edification: what goes in `.service` and what doesn't?

That module's docstring says

> Service libraries and utilities.

But I don't understand what "service" means in this context, or why old sessions are `.service.session` and these new sessions are just `.session`.

2021-05-26 15:59 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/dependencies.py
> +    """Get the current system time."""
Yep, that works too.

I see redundant comments as sitting in an "uncanny valley." The code can be improved, more-or-less equally, by taking the comment in either of two opposite directions: either deleting it or making it really pull its weight.

We shouldn't feel pressured to choose the "making it really pull its weight" direction. Undocumented internal functions are legitimate. Sometimes we deliberately want to leave something vaguer and open to interpretation, or lean on intuition.

2021-05-26 16:37 UTC, mcous commented on robot-server/robot_server/sessions/dependencies.py
> +    raise NotImplementedError()
Is something like this, in an in-progress branch, better?

https://github.com/Opentrons/opentrons/blob/595d5c2c446564db529b4deb781f4f5ae532a617/robot-server/robot_server/sessions/dependencies.py#L19-L24

2021-05-26 16:41 UTC, mcous commented on robot-server/robot_server/router.py
> +from .service.session.router import router as deprecated_session_router
I had the same question, and the conclusion that I can to was: "shared service libraries and utilities should be in `robot_server.service`. My opinions:

Good:
- Base/abstract HTTP request and response models
- Common dependencies, like version header extraction
- Errors (i.e. maybe I should move `robot_server.errors` back to `robot_server.service.errors`?

Bad:
- Business logic, like routes and specific resource models

This should be encoded in the styleguide in some way, if we all agree

2021-05-26 17:16 UTC, SyntaxColoring requested changes

2021-05-26 17:16 UTC, SyntaxColoring commented on robot-server/tests/sessions/test_sessions_router.py
> +    )
Notwithstanding my questioning of whether a "start input" is something that we should have:

```suggestion
    """It should handle a start input."""
    expected_input = SessionInput(
        inputType=SessionInputType.START,
        createdAt=current_time,
        id=unique_id,
    )
```

Typo?

2021-05-26 17:16 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/router.py
> +    description="Get a list of all active and inactive sessions.",
1. How can there be more than one active session at once? Aren't sessions mutually exclusive?
2. What is an inactive session?

2021-05-26 17:16 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/session_inputs.py
> +    START = "start"
Notwithstanding my questioning of whether generalized session input should exist:

Is "start" not the default state of a protocol? Is the act of POSTing a new session not, itself, the thing that should make the robot start to move?

I keep getting confused about what actions are associated with the protocol resource and what actions are associated with the protocol run session resource.

2021-05-26 17:16 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/session_inputs.py
> +    """
I don't think we should try to generalize an input mechanism across all session types. Instead, I think each session type should have its own specific resources and actions.

Examples:

```
# Exact endpoint hierarchies and spellings TBD.

# See if the protocol is paused because the user hit the pause button.
GET /sessions/protocol_run/current/user_pause_state
200 { "userPaused": true }

# User clicks resume button.
PUT /sessions/protocol_run/current/user_pause_state { "userPaused": false }
200  { "userPaused": false }

# Or maybe:
POST /sessions/protocol_run/current/user_pause_state/actions/resume
200  { "userPaused": false }

# See if the current step needs user input.
GET /sessions/protocol_run/current/user_pause_state/steps/current
{
    "id": "abc123"
    "status": "awaitingUserInput",
    "userInput": {
        "spec": {
            "sample_count", { "type": "int", "minimum": 1, "maximum": 96 }
        }
        "currentValue": null
    }
}

# User provides input to the step.
PATCH /steps/abc123/user_input { "sample_count": 48 }
```

**Ideologically:**

A generalized input mechanism feels to me like RPC-over-JSON-over-HTTP. I'm not saying this would be *wrong*—it would be a perfectly functional way to control the robot—but I do think it would be contrary to our prior-stated ambitions of making a RESTful interface.

Instead of trying to anticipate commonalities between sessions, I think we should start with the most dumb, direct, literal, concrete interfaces possible. And then move things under generalized umbrellas only as patterns and needs emerge.


**Practically:**

Indirection and generality make documentation difficult. OpenAPI doesn't model them well.

If you have a protocol run session, for example, as a 3rd-party developer, you'd want to see all the things that you can do on it. But our documentation wouldn't naturally provide you with that list. It would only provide you with the list of things that anyone can do on *any* session type. We'd have to take pains to explain that only some of them are valid for different session types. And it would be up to you to manually adhere to those requirements. (OpenAPI and static typing couldn't help you.)

And even if the docs weren't a problem, I think the indirection and generality are undue conceptual weight. A 3rd-party dev won't want to "issue a start command to a protocol run session"; they'll want to "start a protocol run."

2021-05-26 17:16 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/__init__.py
> +"""
I like this description of what sessions are.

It would also help me if we scoped out what making something a session "does," and why we do it. (More specifically than "to manage them.")

In my mind, it's:

1. Mutual exclusion. I shouldn't be able to calibrate while I'm running a protocol.
2. A machine-readable entry point into inspecting the robot's current state. If I connect my Opentrons App out of the blue to your robot, my app needs a way of finding what the robot is "currently doing" and presenting that to me. That's the "current session."

Is that it, or am I missing something?

2021-05-26 17:21 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/dependencies.py
> +    raise NotImplementedError()
👍 

If you wanted, I think you could even make it something like:

```python
"""Return a singleton `SessionStore`, shared across all requests."""
```

Since "an interface to retrieve session data" and "...holds an in-memory database of created sessions" are both automatically documented by  this function being typed as returning a `SessionStore`.

2021-05-26 17:29 UTC, SyntaxColoring commented on robot-server/robot_server/router.py
> +from .service.session.router import router as deprecated_session_router
Okay, so that implies that `.service.{legacy,session,pipette_offset,protocol,tip_length,notifications}.router` should all be lifted out?

I'm down with that.

Should we also rename it?

* `robot_server.shared_interface_helpers`
* `robot_server.common_util`
* Uhhh ¯\\\_(ツ)\_/¯

2021-05-26 17:38 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/session_inputs.py
> +    """
> And then move things under generalized umbrellas only as patterns and needs emerge.

To clarify what I mean here by an "emerged need..."

Client code like this would be a red flag that we need to generalize something.

```python
def delete_current_session():
    if current_session_type() == "calibration":
        delete_current_calibration_session()
    elif current_session_type() == "liveProtocol":
        delete_current_live_protocol_session()
    # ...ad nauseam.
```

On the other hand, if two resources merely look like they have similar data, or similar actions, I wouldn't consider that alone to be a good reason to bring them under a generalized umbrella. Generalizations ought not form taxonomies for taxonomies' sake. ["Duplication is far cheaper than the wrong abstraction."](https://sandimetz.com/blog/2016/1/20/the-wrong-abstraction) (Again, though, not that I'm calling the existing API "wrong.")

2021-05-26 18:01 UTC, mcous commented on robot-server/robot_server/router.py
> +from .service.session.router import router as deprecated_session_router
Yes to all that. Not in this PR, though!

2021-05-26 18:04 UTC, mcous commented on robot-server/robot_server/sessions/router.py
> +    description="Get a list of all active and inactive sessions.",
> 1. How can there be more than one active session at once? Aren't sessions mutually exclusive?

I don't think there could be, but I also does this description imply that there could be?

> 2. What is an inactive session?

A session whose state has been preserved for re-activation at a later time, but is not currently in use. In my imagination, I think of a user pausing a protocol to re-do a calibration before returning to the protocol run where they left off

2021-05-26 18:05 UTC, mcous commented on robot-server/robot_server/sessions/session_inputs.py
> +    START = "start"
> Is "start" not the default state of a protocol? Is the act of POSTing a new session not, itself, the thing that should make the robot start to move?

I don't think creating a session resource should start the run. Using our UI as an example, you would create the session resource when you get to the run page, inspect and verify, and then start the run using the run controls when you are satisfied

2021-05-26 18:07 UTC, mcous commented on robot-server/robot_server/sessions/session_inputs.py
> +    START = "start"
> I keep getting confused about what actions are associated with the protocol resource and what actions are associated with the protocol run session resource.

I'm treating them like the following:

- Protocol resource
    - Files
    - Protocol type
    - Simulation / analysis
- Session resource
    - State of an individual protocol run, as its happening

2021-05-26 18:11 UTC, mcous commented on robot-server/robot_server/sessions/__init__.py
> +"""
I would add "a historical record of events that occurred during a given calibration / protocol run / etc." I also might take issue with:

> Mutual exclusion. I shouldn't be able to calibrate while I'm running a protocol.

Counterpoint: why not? I can image this flow: you're running a protocol, something is off, you issue a manual series of commands / resource updates to correct the issue (and those events are recorded in session state), and you proceed with the run

2021-05-26 18:42 UTC, mcous commented on robot-server/robot_server/sessions/session_inputs.py
> +    """
## On RPC and REST (ideology)

> A generalized input mechanism feels to me like RPC-over-JSON-over-HTTP. I'm not saying this would be wrong—it would be a perfectly functional way to control the robot—but I do think it would be contrary to our prior-stated ambitions of making a RESTful interface.

I disagree. This solution models user-provided control inputs as a specific, timestamped, identifiable resources on the server, which can be queried and referenced. The creation of that resource triggers some side-effects, which is not my favorite, but useful in this case. IMO the resource creation makes it REST'y.

From your examples:

> PUT /sessions/protocol_run/current/user_pause_state { "userPaused": false }
> 200  { "userPaused": false }

This is also pretty REST'y, going with resource mutation rather than resource creation. It's similar to how we do things over in the factory tools. I'm having some trouble figuring out what the resource(s) look(s) like here, though. Is it the session? Is it some child of the session?

```js
type ProtocolSession = {
  id: string,
  user_pause_state: {
    userPaused: boolean,
  },
  // ...
}
```

I prefer `POST /session/:sid/inputs` for a few reasons:

- I think it's important that there be a record of pauses, resumes, etc. This necessitates the creation of some resource to represent those events, so why not just deal with those resources directly?
- Where possible, I prefer immutable resource creation to resource mutation, _especially_ with the end goal of triggering a side effect 

>  POST /sessions/protocol_run/current/user_pause_state/actions/resume
200  { "userPaused": false }

This is 100% just a remote procedure call ("do a resume") in a URL, so I think we can both agree that this is not the way to go.

> Instead of trying to anticipate commonalities between sessions, I think we should start with the most dumb, direct, literal, concrete interfaces possible. And then move things under generalized umbrellas only as patterns and needs emerge.

I don't think saying "sessions require user input, and therefore we need a way to model user input events" is an unreasonable commonality to conclude.

## On the OpenAPI spec (practicality)

We're in total agreement that good OpenAPI Spec modeling of behaviors is table stakes for this project.

> Indirection and generality make documentation difficult. OpenAPI doesn't model them well.

I think there's some subtlety here. I think OpenAPI is perfectly capable or modelling them well (enough), but we need to do a good job of structuring our models to make that happen, which we haven't done well in the previous /sessions iteration.

> If you have a protocol run session, for example, as a 3rd-party developer, you'd want to see all the things that you can do on it. But our documentation wouldn't naturally provide you with that list. It would only provide you with the list of things that anyone can do on any session type.

This is 100% possible, we just have to model our different session types properly:

```py
from .input_models import AbstractInput, StartInput, PauseInput, StopInput

class AbstractSession:
    inputs: Optional[List[AbstractInput]]

class ProtocolSession:
    inputs: List[Union[StartInput, PauseInput, StopInput]]

class UnstoppableSession:
    inputs: Literal[None]
```

2021-05-26 18:44 UTC, sanni-t reviewed
My comments are mainly naming related.
I am not too sure of `SessionInput` either but I can warm up to it. It just doesn't reflect what it's talking about. Maybe something like `SessionControlInput` if that's not too wordy for everyone..

2021-05-26 18:44 UTC, sanni-t commented on robot-server/robot_server/sessions/router.py
> +    data = session_builder.build(
So, if I'm understanding this correctly, adding an entry to the sessions store using `create()` actually creates the session, while session builder creates a representation of the session in terms of tangible session properties? If so, I think the name `session_builder` and the `build` method are confusing. It reads as the thing that actually builds/creates a session. 
I don't have great alternatives but thinking of something like a `SessionRepr`..

2021-05-26 18:52 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/session_inputs.py
> +    START = "start"
> you would create the session resource when you get to the run page, inspect and verify, and then start the run using the run controls when you are satisfied

Wouldn't I be inspecting the "simulation/analysis," which is under your "Protocol resource" bullet point? (Also, I agree with your bullet points.

2021-05-26 18:55 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/session_inputs.py
> +    START = "start"
Actually, this might be better to work out visually. Meantime, I don't mind the default state being waiting.

2021-05-26 20:29 UTC, mcous commented on robot-server/robot_server/sessions/session_inputs.py
> +    """
> This is 100% possible, we just have to model our different session types properly:

Hm upon second thought, this is easy at the `Session` schema level. I think you're right that it becomes less fun at the URL schema level

2021-05-26 20:55 UTC, SyntaxColoring approved these changes
We have a few threads here where I'm not really convinced, but I don't think merging this PR should wait for me to form a coherent argument.

I'll gather my thoughts and we can continue discussing later (here on in Slack), if you want to merge now.

2021-05-26 20:58 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/session_inputs.py
> +    """
> Hm upon second thought, this is easy at the Session schema level. I think you're right that it becomes less fun at the URL schema level

Yup, exactly.

I think there's two questions here that I kind of conflated:

1. Is there a single input endpoint, overloaded to support all session types? Or does each session type have its own dedicated input endpoint?
2. Regardless of we decide for (1), is an input endpoint then further split up based on the "kind" of input? If so, where do we stop splitting it up?

I care more about (1) than (2).

2021-05-28 13:57 UTC, mcous commented
Merging this one because I'm already too far into the next PR to really wrangle things, so here are unresolved items that require followup (that I know about):

- `SessionInput` is too broad a name, let's switch to `SessionControl` or `SessionControlInput` to reflect that we're collecting requests to control the run
- `SessionBuilder` doesn't accurately reflect what that utility is doing, switch it to `ResponseBuilder` to reflect that it's purely mapping existing session data to a `Session` model for HTTP response purposes
- Need to add various TODO comments

2021-05-28 13:57 UTC, merged