fix(app): Run timer stays at 00:00:00 if you reconnect in the middle of a delay
OpenTrons/opentrons-api pull request #7841
Opened 2021-05-26 16:57 UTC by celsasser

### DRAFT: keeping track of changes that I've made that I don't necessarily want in the formal PR.

# Overview
If the Opentrons App disconnects from an OT-2 in the middle of a protocol, and reconnects while the OT-2 is in the middle of a delay step, the Opentrons App's run timer will be stuck at 00:00:00, as if the protocol had never started.

This may contribute to users thinking a protocol has "canceled itself."

# Changelog

# Review requests

# Risk assessment

2021-05-26 16:57 UTC, celsasser commented on api/src/opentrons/hardware_control/api.py
> +            if self.is_simulator:
Revert once done testing

2021-05-26 17:00 UTC, celsasser commented on app/src/redux/robot/reducer/session.js
> +  console.log(`sessionReducer ${action.type}, action=`, action);
Remove

2021-05-26 17:00 UTC, celsasser commented on app/src/redux/robot/reducer/session.js
> +    // todo: ce - think we want to pick up where we left off?
Wrong

2021-05-26 17:00 UTC, celsasser commented on app/src/redux/robot/reducer/session.js
> +  return { ...state, runTime: Date.now(), runRequest: { inProgress: true, error: null } }
Wrong

2021-05-26 17:01 UTC, celsasser commented on app/src/redux/robot/reducer/session.js
> +    runTime: Date.now()
Why did I do this?

2021-05-26 17:02 UTC, celsasser commented on app/src/redux/robot/selectors.js
> +  console.log('getRunSeconds: ', {startTime, runTime, pausedDuration});
Remove logging

2021-05-26 17:03 UTC, celsasser commented on app/src/rpc/client.js
> +        console.log('_handleMessage', this._resultTypes, this._typeObjectCache);
Remove

2021-05-26 17:03 UTC, celsasser commented on app/src/rpc/websocket-client.js
> +    console.log(`rpc.parseMessage: ${data}`);
Remove

2021-05-27 22:40 UTC, SyntaxColoring commented on app/src/redux/robot/reducer/session.js
> +  pausedDuration: number,
Am I correct in interpreting this as:

* `pausedDuration` is the total number of seconds that this protocol has spent paused, across all steps executed so far?
* `pausedTime` is, when the protocol is currently paused, the timestamp when this pause started?

2021-05-28 14:29 UTC, celsasser commented on app/src/redux/robot/reducer/session.js
> +  pausedDuration: number,
Yes, that's exactly right. Will update comments with those words. [updated comments with small revision to make `pausedTime` more consistent with `startTime`]

2021-05-28 15:25 UTC, SyntaxColoring commented on app/src/redux/robot/reducer/session.js
> +  }
> In the process of looking for and testing the bug found that pause does not pause the timer. The solution is hacky in that refresh wipes the slate clear. But I think for the most common use case it is better than the way it currently works or doesn't work depending on how you look at it.

So if you:

1. Start running a protocol.
2. Get through a bunch of pauses and delays in the protocol, amounting to 15 minutes.
3. Disconnect from the robot or quit the app.
4. Reconnect to the robot or reopen the app.

Then the run timer will jump up by 15 minutes between steps 3 and 4, since the app will no longer have any knowledge of `pausedDuration`?

If this is right, I don't think we should attempt to pause the timer during pauses at all. The timer being predictable and consistent is more important than it excluding pause time.

2021-05-28 15:29 UTC, SyntaxColoring commented on app/src/redux/robot/reducer/session.js
> +  }
Also:

When you're authoring a protocol, there's a distinction between a "delay" ("this scientific process requires our science juice to marinate for exactly 15 minutes before we move on to the next step") and a "pause" ("I want to wait here until the user clicks 'Resume'").

By the time these events reach the Opentrons App, I *think* (but I'm definitely not sure) that they get conflated into a single "pause" event.

It wouldn't be right for the timer to stop running during one of those deliberate 15-minute delays. But if we fix the timer running during pauses, we might accidentally do that?

2021-05-28 15:29 UTC, celsasser commented on app/src/redux/robot/reducer/session.js
> +  }
Yes, that's exactly right. Okay, then if we do want support for it then we would have to go deeper and make the robot-server or lower track track pauses. But sounds like we should the hacky fix out.

2021-05-28 15:31 UTC, celsasser commented on app/src/redux/robot/reducer/session.js
> +  }
Oh dear, I've lost the ability to type proper sentences. Okay, I'll pull it out.

2021-05-28 15:53 UTC, celsasser commented on app/src/redux/robot/reducer/session.js
> +  }
> Also:
> 
> When you're authoring a protocol, there's a distinction between a "delay" ("this scientific process requires our science juice to marinate for exactly 15 minutes before we move on to the next step") and a "pause" ("I want to wait here until the user clicks 'Resume'").
> 
> By the time these events reach the Opentrons App, I _think_ (but I'm definitely not sure) that they get conflated into a single "pause" event.
> 
> It wouldn't be right for the timer to stop running during one of those deliberate 15-minute delays. But if we fix the timer running during pauses, we might accidentally do that?

I may have been mistaken about what you were saying. It's a little confusing. The pause I am addressing is not the delay in the protocol. It's 100% the `Pause` button in the app. When they press pause I am essentially stopping the timer from ticking and measuring the time between when the initiated pause and resumed it. And upon resume the timer ticks again.

I am not doing anything with delays scripted into protocols.

Does that change anything?  The motivation for doing it was that we are conditioned to see things pause when we pause them. Maybe I spent too much time in the media industry.

2021-06-01 15:09 UTC, SyntaxColoring commented on app/src/redux/robot/reducer/session.js
> +  }
Sorry, I think you can disregard that—I think I'm just confusing myself. :\

2021-06-01 18:28 UTC, mcous requested changes
Ok so the TL;DR on this review is that most of the existing timer state is completely useless. At one point in the robot server's history, `session.startTime` could not be trusted, so we did a lot of work to try to bandaid around that. Since #6501, we **can** trust the server time, more or less, so all this brittle stuff isn't really doing anything.

There's also the knotty UX question of "what does the run timer do when the protocol is paused?" We've been attempting to pause the timer when the run is paused or delayed, but that's really difficult to do reliably given server constraints.

I think the pause time tracking idea this PR adds is solid and helpful, _and_ I think we actually have enough information from the server to track it. The gist of everything that follows is **what if we surfaced current pause time to the user** instead of trying to get clever about when the timer runs or not.

The key is that the server sends a `session.statusInfo` object that gets placed in `state.robot.session.statusInfo`. Whenever the protocol status changes (e.g. to `paused`), this `statusInfo` object will hold on to a relative timestamp of when that change occurred. 

That means we have the following reliable information from the server:

- Protocol run start time
- Relative timestamp of the last status change

Given that, rather than trying to **add** stuff to client state until things work, I think this PR should, instead, try to **remove** stuff until it works 😄

- Remove the `runTime` state entry because it represents "total run time", and we can calculate that from `startTime` in a selector / in the UI component
- Remove `remoteTimeCompensation` state entry and associated machinery, because with time syncing, this has been made unnecessary
- Remove the `TICK_RUN_TIME` action and associated machinery, because why would we need to do this in state?

If we go back to our original story for this bug, it's something along the lines of:

> As a user, I want to know that a robot I've connected to is still running its protocol, even if it's paused.

So, I propose that **we ditch trying to stop the run timer when the protocol is paused**. IMO it's too technically difficult to implement reliably given the current constraints:

- Server does not differentiate between a delay and a pause
- Server does not track a historical record of pauses

Instead we can have a run timer that is running from the moment the user hits start until the moment the protocol ends or is stopped. But, we still want to make sure the user knows the protocol is paused (or delaying). So, using the information we already have...

- Relative start of the current pause in relation to overall start time (`session.statusInfo.changedAt` if `session.status === PAUSED`)
- Current time from `Date.now()`

...we should update the run timer UI **when the protocol is paused**, doing something like:

- Make the currently big "Run Time: 01:02:03" smaller, calling it "Total Run Time" and putting it just above "Start Time"
- Where the big runner timer used to be, put "Paused For: 01:02:03"

I think this hits all our requirements:

- Total run time is now driven by:
    - Hasn't run yet: nothing, it's 0
    - When running / paused: `Date.now()` less `session.startTime`  
    - When stopped / errored / finished: `session.statusInfo.changedAt` (because that's when the status changed to `stopped`, etc.)
- Current paused time is driven by:
    - If not paused: nothing, it's 0
    - If paused: `Date.now()` less `session.startTime + session.statusInfo.changedAt`
- If robot is paused, user knows clearly that it's paused and for how long it's been paused, because UI clearly communicates a ticking time labeled "Paused For"
- If robot is not paused, everything keeps going smoothly

2021-06-01 18:28 UTC, mcous commented on app/src/redux/robot/reducer/session.js
> +    runTime: Date.now(),
I think calls to anything non-idempotent should be strictly avoided in Redux reducers. Which makes it _very_ embarrassing to realize that `handleTickRunTime` below has been sitting there for 4 years with a call to `Date.now()` that I definitely wrote...

2021-06-01 21:25 UTC, celsasser commented
> Ok so the TL;DR on this review is that most of the existing timer state is completely useless. At one point in the robot server's history, `session.startTime` could not be trusted, so we did a lot of work to try to bandaid around that. Since #6501, we **can** trust the server time, more or less, so all this brittle stuff isn't really doing anything.
> 
> There's also the knotty UX question of "what does the run timer do when the protocol is paused?" We've been attempting to pause the timer when the run is paused or delayed, but that's really difficult to do reliably given server constraints.
> 
> I think the pause time tracking idea this PR adds is solid and helpful, _and_ I think we actually have enough information from the server to track it. The gist of everything that follows is **what if we surfaced current pause time to the user** instead of trying to get clever about when the timer runs or not.
> 
> The key is that the server sends a `session.statusInfo` object that gets placed in `state.robot.session.statusInfo`. Whenever the protocol status changes (e.g. to `paused`), this `statusInfo` object will hold on to a relative timestamp of when that change occurred.
> 
> That means we have the following reliable information from the server:
> 
> * Protocol run start time
> * Relative timestamp of the last status change
> 
> Given that, rather than trying to **add** stuff to client state until things work, I think this PR should, instead, try to **remove** stuff until it works 😄
> 
> * Remove the `runTime` state entry because it represents "now, if running", and we can calculate that from `startTime` in a selector / in the UI component
> * Remove `remoteTimeCompensation` state entry and associated machinery, because with time syncing, this has been made unnecessary
> * Remove the `TICK_RUN_TIME` action and associated machinery, because why would we need to do this in state?
> 
> If we go back to our original story for this bug, it's something along the lines of:
> 
> > As a user, I want to know that a robot I've connected to is still running its protocol, even if it's paused.
> 
> So, I propose that **we ditch trying to stop the run timer when the protocol is paused**. IMO it's too technically difficult to implement reliably given the current constraints:
> 
> * Server does not differentiate between a delay and a pause
> * Server does not track a historical record of pauses
> 
> Instead we can have a run timer that is running from the moment the user hits start until the moment the protocol ends or is stopped. But, we still want to make sure the user knows the protocol is paused (or delaying). So, using the information we already have...
> 
> * Relative start of the current pause in relation to overall start time (`session.statusInfo.changedAt` if `session.status === PAUSED`)
> * Current time from `Date.now()`
> 
> ...we should update the run timer UI **when the protocol is paused**, doing something like:
> 
> * Make the currently big "Run Time: 01:02:03" smaller, calling it "Total Run Time" and putting it just above "Start Time"
> * Where the big runner timer used to be, put "Paused For: 01:02:03"
> 
> I think this hits all our requirements:
> 
> * Total run time is now driven by:
>   
>   * Hasn't run yet: nothing, it's 0
>   * When running / paused: `Date.now()` less `session.startTime`
>   * When stopped / errored / finished: `session.statusInfo.changedAt` (because that's when the status changed to `stopped`, etc.)
> * Current paused time is driven by:
>   
>   * If not paused: nothing, it's 0
>   * If paused: `Date.now()` less `session.startTime + session.statusInfo.changedAt`
> * If robot is paused, user knows clearly that it's paused and for how long it's been paused, because UI clearly communicates a ticking time labeled "Paused For"
> * If robot is not paused, everything keeps going smoothly

Okay, not sure I am clear on where to go from here, but totally accept that it was a mistake to deviate from the bug. And regarding the deviation I wasn't attempting to sync to anything going on in the protocol. It only was meant to pause the timer when a user initiated pause via the interface - the `PAUSE` button. It was hacky. 

Regarding next steps (taking for granted that I will remove everything having to with pause that I introduced) I think by removing `remoteTimeCompensation` will fix it. Do we want to be more aggressive?

2021-06-01 22:10 UTC, celsasser commented on app/src/redux/robot/reducer/session.js
> +    runTime: Date.now(),
Oh, don't be too hard on yourself. It's probably one of my edits :)

2021-06-01 22:48 UTC, mcous commented
> Okay, not sure I am clear on where to go from here, but totally accept that it was a mistake to deviate from the bug.

My apologies, I didn't mean to imply that you made any sort of mistake here! This is some of the very oldest code in the app, it has a lot of baggage. 

> Regarding next steps (taking for granted that I will remove everything having to with pause that I introduced) I think by removing remoteTimeCompensation will fix it. Do we want to be more aggressive?

The source of the bug, as best I can tell from reading the code, is:

- The run timer relies on `state.robot.session.runTime` to exist as a value that represents "now"
    - The _only_ thing that can set `runTime` is a `TICK_RUN_TIME` action
- The code in `app/src/redux/robot/api-client/client.js` has an interval that runs, triggering a `TICK_RUN_TIME` action every second to set `state.robot.session.runTime` to `Date.now()`
    - The client stops this interval whenever `session.status` is not `running`
- If the app connects to a robot with `session.status === 'paused'`, the `TICK_RUN_TIME` interval will never spin up, and `runTime` will never get set to `Date.now()`

So, as food for thought, here are two potential solutions:

### option 1: do the least

- Modify `handleSessionUpdate` in `app/src/redux/robot/reducer/session.ts` to set `runTime`
    - Probably set it to something weird like:
        - If session status is `running`, set `runTime` to `now`
        - If session status is `paused`, set `runTime` to `startTime + statusInfo.changedAt - remoteTimeCompensation`

### option 2: do the most

See review comment above, but the gist of it is "ditch all client-side run time tracking and calculate everything from server state, updating the UI to account for the differences"

I like option (2) because it's more "correct" and doesn't feel like a huge lift, but option (1) would probably still fix the bug.

2021-06-01 22:52 UTC, celsasser commented
> > Okay, not sure I am clear on where to go from here, but totally accept that it was a mistake to deviate from the bug.
> 
> My apologies, I didn't mean to imply that you made any sort of mistake here! This is some of the very oldest code in the app, it has a lot of baggage.
> 
> > Regarding next steps (taking for granted that I will remove everything having to with pause that I introduced) I think by removing remoteTimeCompensation will fix it. Do we want to be more aggressive?
> 
> The source of the bug, as best I can tell from reading the code, doesn't (necessarily) have anything to do with `remoteTimeCompensation`. I think:
> 
> * The run timer relies on `state.robot.session.runTime` to exist as a value that represents "now"
>   
>   * The _only_ thing that can set `runTime` is a `TICK_RUN_TIME` action
> * The code in `app/src/redux/robot/api-client/client.js` has an interval that runs, triggering a `TICK_RUN_TIME` action every second to set `state.robot.session.runTime` to `Date.now()`
>   
>   * The client stops this interval whenever `session.status` is not `running`
> * If the app connects to a robot with `session.status === 'paused'`, the `TICK_RUN_TIME` interval will never spin up, and `runTime` will never get set to `Date.now()`
> 
> So, as food for thought, here are two potential solutions:
> 
> ### option 1: do the least
> * Modify `handleSessionUpdate` in `app/src/redux/robot/reducer/session.ts` to set `runTime`
>   
>   * Probably set it to something weird like:
>     
>     * If session status is `running`, set `runTime` to `now`
>     * If session status is `paused`, set `runTime` to `startTime + statusInfo.changedAt - remoteTimeCompensation`
> 
> ### option 2: do the most
> See review comment above, but the gist of it is "ditch all client-side run time tracking and calculate everything from server state, updating the UI to account for the differences"
> 
> I like option (2) because it's more "correct" and doesn't feel like a huge lift, but option (1) would probably still fix the bug.

Actually, the fix is in here. Not to say there is not merit in whatever you are suggestion. But this change does fix the bug:
https://github.com/Opentrons/opentrons/pull/7841/files#diff-70c3a3773407c64d3c2d47db4193d50bafe264edd3e70da1cc7d16c97a320c5eR209

2021-06-01 23:15 UTC, celsasser commented
> > Okay, not sure I am clear on where to go from here, but totally accept that it was a mistake to deviate from the bug.
> 
> My apologies, I didn't mean to imply that you made any sort of mistake here! This is some of the very oldest code in the app, it has a lot of baggage.
> 
> > Regarding next steps (taking for granted that I will remove everything having to with pause that I introduced) I think by removing remoteTimeCompensation will fix it. Do we want to be more aggressive?
> 
> The source of the bug, as best I can tell from reading the code, doesn't (necessarily) have anything to do with `remoteTimeCompensation`. I think:
> 
> * The run timer relies on `state.robot.session.runTime` to exist as a value that represents "now"
>   
>   * The _only_ thing that can set `runTime` is a `TICK_RUN_TIME` action
> * The code in `app/src/redux/robot/api-client/client.js` has an interval that runs, triggering a `TICK_RUN_TIME` action every second to set `state.robot.session.runTime` to `Date.now()`
>   
>   * The client stops this interval whenever `session.status` is not `running`
> * If the app connects to a robot with `session.status === 'paused'`, the `TICK_RUN_TIME` interval will never spin up, and `runTime` will never get set to `Date.now()`
> 
> So, as food for thought, here are two potential solutions:
> 
> ### option 1: do the least
> * Modify `handleSessionUpdate` in `app/src/redux/robot/reducer/session.ts` to set `runTime
>   
>   * This part of the reducer gets triggered whenever the app connects to a robot and whenever the session state gets updated
>   * Probably set it to something weird like:
>     
>     * If session status is `running`, set `runTime` to `now`
>     * If session status is `paused`, set `runTime` to `startTime + statusInfo.changedAt - remoteTimeCompensation`
> 
> ### option 2: do the most
> See review comment above, but the gist of it is "ditch all client-side run time tracking and calculate everything from server state, updating the UI to account for the differences"
> 
> I like option (2) because it's more "correct" and doesn't feel like a huge lift, but option (1) would probably still fix the bug.

I'm sure you are right. For whatever the reason, I was either reading or observing that the bug had to do with the start-time. Which I'll take a look at, but it was _that_ problem that a null `remoteTimeCompensation` fixed...which was not the bug. option #2 sounds good. Thanks.

2021-06-02 14:23 UTC, celsasser commented
Going to take the excellent feedback in this PR but pursue it with a new branch since the commit history in this one is of no value and the massive TS effort has been merged into `edge`. Will port the feedback to the new PR.

2021-06-02 14:23 UTC, closed without merging