refactor(robot-server): add experimental protocol router
OpenTrons/opentrons-api pull request #7856
Opened 2021-06-01 14:27 UTC by mcous

## Overview

This PR adds an experimental `/protocols` router when the `enableProtocolEngine` feature flag is on. It's goal is to tackle the following checkbox from #7816:

- [ ] a /protocol_upload http POST endpoint that is able to fetch the protocol file as form data

Blocked by #7855, will require sync after merge

## Changelog

This PR re-adds functionality already covered by the HTTP Protocol Upload Beta program. I went with a feature flagged separate router for two reasons:

- To avoid breaking the working HTTP protocol upload, which is in use by various people
- To give us space to complete ignore large chunks of functionality until we have concrete uses for them
    - (At which point we would pull them in from the previous protocols router or write new stuff, as needed)

## Review requests

You should be able to run these endpoints yourself:

```shell
make -C robot-server dev OT_API_FF_enableProtocolEngine=1
```

- [ ] `GET /protocols`
    - Retrieve all uploaded protocols
- [ ] `POST /protocols files=<file_list>`
    - Upload files under the `files` key via a `form-data` body
- [ ] `GET /protocols/:protocol_id`
- [ ] `DELETE /protocols/:protocol_id`  

I've also made [a Postman collection](https://gist.github.com/mcous/7dde93b6ea83753b86b0d84b40ba07f6) to make testing this endpoints easier:

- `{{hostname}}` is set to `localhost` by default
- `{{protocol_id}}` is set to the ID of the latest `POST`'d protocol

### Known deviations / not implemented for this PR

- Has a single `files` list for protocol creation, per discussions in Slack, for simplicity at this point, if nothing else
    - Will not work if you pass more that one file, though
    - It will also fail if you pass 0 files!
- Only understands JSON files
    - However, does not yet attempt any validation of those files
- Does not attempt to limit how many protocols get uploaded
- Does not run any simulation or analysis on the files, just assigns an ID and stores them

## Risk assessment

Very low! Completely isolated from production via feature flag

2021-06-01 18:10 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/protocol_store.py
> +        protocol_dir.mkdir(parents=True, exist_ok=True)
I understand `parents=True` to automatically create the root directory (`self._directory`), but why `exist_ok=True`? I'd expect it to be an error if I tried to do something that would accidentally partially overwrite an existing protocol.

(If it turns out that we want `create()` to be idempotent, we should document that. But I don't think that's something we want, at least at the store level.)

```suggestion
        # TODO(mc, 2021-06-02): check for protocol collision
        protocol_dir.mkdir(parents=True)
```

2021-06-01 18:10 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/protocol_store.py
> +                    file_path.write_bytes(contents)
Are we intentionally deferring using `aiofiles` or something for this? If so, should we leave a todo?

2021-06-01 18:10 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +    """Get an uploaded protocol by ID."""
These are more examples of the kind of docstring that I would omit. It's a restatement of both the function name and the FastAPI `summary`.

2021-06-01 18:10 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/__init__.py
> +]
How do you decide what gets exported from `robot_server.protocols`?

`protocols_router` I can understand, because it's used by the top-level router. But why `get_protocol_store()` and the rest?

2021-06-01 18:10 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/dependencies.py
> +PROTOCOL_STORE_DIRECTORY = Path(gettempdir()) / "protocols"
```suggestion
PROTOCOL_STORE_DIRECTORY = Path(gettempdir()) / "opentrons-protocols"
```

IMO we should keep most of our filesystem stuff prefixed with `ot-` or `opentrons-` to distinguish it from system or vendor stuff.

2021-06-01 18:10 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/dependencies.py
> +        setattr(request.app.state, PROTOCOL_STORE_KEY, protocol_store)
What's the benefit of using `request.app.state` here, instead of only *returning* `protocol_store` and leaving it up to our code to explicitly pass it down the call stack (which it does, when needed)?

2021-06-01 18:10 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/protocol_models.py
> +    createdAt: datetime = Field(..., description="When this protocol was uploaded.")
Can we rename `createdAt` to `uploadedAt`, to avoid conflation with when the protocol was *authored* (according to its Opentrons metadata or its filesystem timestamp)?

2021-06-01 18:10 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/protocol_store.py
> +    created_at: datetime
Ditto the other `created_at` -> `uploaded_at` comment.

2021-06-01 18:10 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/protocol_store.py
> +            if upload_file.filename != "":
What does a filename of `""` mean?

2021-06-01 18:10 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/protocol_store.py
> +        """Get all protocols currently saved in the system."""
```suggestion
        """Get all protocols currently saved in this store."""
```

(To not imply that it gets all protocols across all stores, somehow.)

2021-06-01 18:10 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/protocol_store.py
> +class ProtocolNotFoundError(ValueError):
I don't think it really matters, but:

```suggestion
class ProtocolNotFoundError(KeyError):
```

or

```suggestion
class ProtocolNotFoundError(LookupError):
```

?

2021-06-01 18:10 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/response_builder.py
> +        )
Can we make this a simple free function?

2021-06-01 18:10 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/response_builder.py
> +        )
I gather that there's a TDD tradition of turning every function (verb) into a class (noun) so you can dependency-inject it. Is that what's going on here?

2021-06-01 18:10 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +    summary="Uploaded protocol",
```suggestion
    summary="Upload a protocol",
```

2021-06-01 18:10 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/protocol_store.py
> +class ProtocolStoreEntry:
I don't have an easy answer for this right now, but this asymmetry is bugging me:

* An HTTP protocol response can be named "just `Protocol"`
* But a protocol store entry is `ProtocolStoreEntry`

Maybe when things stabilize a little, we'll revisit the import hierarchy and lean on package names more, or something.

2021-06-01 18:10 UTC, SyntaxColoring commented on robot-server/tests/protocols/test_protocol_store.py
> +    expected_file_path = tmp_path / "protocol-id" / "protocol.json"
For my edification:

I'm never sure about things like this. This ties this test to internal implementation details of both the `subject()` fixture and the `ProtocolStore` class. Is that, uh, "allowed"?

2021-06-01 18:10 UTC, SyntaxColoring commented on robot-server/tests/protocols/test_protocol_store.py
> +    assert expected_file_path.exists() is False
Should this capture the return value of `subject.remove("protocol-id")` and assert that it matches what we passed to `subject.create()`?

2021-06-01 18:40 UTC, mcous commented on robot-server/robot_server/protocols/protocol_store.py
> +        protocol_dir.mkdir(parents=True, exist_ok=True)
`mkdir(exist_ok=True)` will no-op if the directory exists. That feels safer to me, and makes this logic easier to re-use when we get around to adding files to existing protocols

2021-06-01 18:41 UTC, mcous commented on robot-server/robot_server/protocols/protocol_store.py
> +                    file_path.write_bytes(contents)
I'm feeling a lot less militant these days about doing file IO in a threadpool, which is all `aiofiles` does. I don't think it's worth the effort at this point to try to get that particular dependency set up

2021-06-01 18:42 UTC, mcous commented on robot-server/robot_server/protocols/__init__.py
> +]
They're all used by `robot_server.sessions` in #7858

2021-06-01 18:45 UTC, mcous commented on robot-server/robot_server/protocols/protocol_models.py
> +    createdAt: datetime = Field(..., description="When this protocol was uploaded.")
I'd rather keep `createdAt` as a consistent timestamp across our resource models for "when the resource was created on the server". I think any potential confusion is easily addressable via protocol file / metadata information / documentation (to be added to this response model later), and the style consistency is worth the tradeoff

2021-06-01 18:49 UTC, mcous commented on robot-server/robot_server/protocols/dependencies.py
> +        setattr(request.app.state, PROTOCOL_STORE_KEY, protocol_store)
The `ProtocolStore` is wired as a singleton because it contains an in-memory database, so we only want the one instance. Attaching it to [`app.state`](https://www.starlette.io/applications/#storing-state-on-the-app-instance) is an alternative to storing it in a module-level global variable.

It functions the same way, but attaching global stuff to `app.state` is more how I'm used to working with HTTP frameworks (e.g. [express' app.locals](http://expressjs.com/en/4x/api.html#app.locals))

2021-06-01 18:50 UTC, mcous commented on robot-server/robot_server/protocols/protocol_store.py
> +            if upload_file.filename != "":
As I found out today, it's what can happen if you don't click on a file in Postman before you send the request with a `files` field. Going to address this TODO in this PR with a 400 response

2021-06-01 18:52 UTC, mcous commented on robot-server/robot_server/protocols/protocol_store.py
> +class ProtocolStoreEntry:
I think I want to rename this `ProtocolResource` to mirror what I've done in #7858 with sessions:

- `SessionResource` - Canonical, internal representation of the session state resource
- `Session` - Response model, simply named for the benefit of the OAS / client

2021-06-01 18:57 UTC, mcous commented on robot-server/robot_server/protocols/response_builder.py
> +        )
Yup. If I had a good way to mock out a whole imported module rather than partially `patch`'ing it in Python, I would do that. But, since I don't, I think a namespace class with `@staticmethod`s is safer

2021-06-01 18:59 UTC, mcous commented on robot-server/tests/protocols/test_protocol_store.py
> +    expected_file_path = tmp_path / "protocol-id" / "protocol.json"
This is a good point, I should take the value from `files` instead and read that

2021-06-01 20:55 UTC, celsasser approved these changes
Some small comments but looks good.

2021-06-01 20:55 UTC, celsasser commented on robot-server/robot_server/protocols/protocol_store.py
> +        file_path = files[0]
Think this has to do with your comment, but seems a little precarious to be at the mercy of the order of the files when created.

2021-06-01 20:55 UTC, celsasser commented on robot-server/robot_server/protocols/router.py
> +) -> MultiResponseModel[Protocol]:
So we just return metadata about the protocols. Not the protocol file contents. I guess there is no use case for the contents (sort of a question, maybe just talking out loud)...

2021-06-01 20:55 UTC, celsasser commented on robot-server/tests/protocols/test_protocol_store.py
> +def subject(tmp_path: Path) -> ProtocolStore:
`subject` makes sense to you guys?

2021-06-01 20:56 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/dependencies.py
> +        setattr(request.app.state, PROTOCOL_STORE_KEY, protocol_store)
Aaaah, I totally misread this. It attaches the `ProtocolStore` to the *whole app,* but I thought it was attaching it to just the *request.*

I'd softly prefer a module-level global variable, [or even a property on the function object](https://stackoverflow.com/a/279586/497934), because it seems like it would be less obscure. (No need to reimplement plain Python features through Starlette.)

But if we want to make a package-wide idiom out of `app.state`, I'm willing to try it.

2021-06-01 21:15 UTC, SyntaxColoring commented on robot-server/tests/protocols/test_protocol_store.py
> +def subject(tmp_path: Path) -> ProtocolStore:
Yeah, I like it. I think it keeps the test suite focused. Given that we type it as `subject: ProtocolStore`, it should still be clear what it's referring to.

2021-06-01 22:16 UTC, mcous commented on robot-server/tests/protocols/test_protocol_store.py
> +def subject(tmp_path: Path) -> ProtocolStore:
This particular convention is something I picked up from [testsdouble](https://github.com/testdouble/contributing-tests/wiki/Subject)

2021-06-01 22:16 UTC, mcous commented on robot-server/robot_server/protocols/router.py
> +) -> MultiResponseModel[Protocol]:
File contents is probably a thing we will need. But also feels like a reasonable thing to punt on right now

2021-06-01 22:45 UTC, celsasser commented on robot-server/tests/protocols/test_protocol_store.py
> +def subject(tmp_path: Path) -> ProtocolStore:
Okay, I guess just wondering whether we are trying to create a standard and whether we will be consistent and use it in the future for subjects being tested. For a moment, I wondered whether it was a scientific term.

2021-06-01 22:46 UTC, celsasser commented on robot-server/tests/protocols/test_protocol_store.py
> +def subject(tmp_path: Path) -> ProtocolStore:
Got it

2021-06-01 22:52 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/response_builder.py
> +        )
Adding this to tomorrow's agenda because it seems like a convention that we should all understand and commit to, if we're going to do it.

2021-06-01 22:59 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/protocol_models.py
> +    createdAt: datetime = Field(..., description="When this protocol was uploaded.")
I don't think I agree with that tradeoff, but taking it for granted for the moment: could we do `resourceCreatedAt` instead of `createdAt`, then?

2021-06-02 00:40 UTC, mcous commented on robot-server/robot_server/protocols/dependencies.py
> +        setattr(request.app.state, PROTOCOL_STORE_KEY, protocol_store)
There's definitely a testing benefit. By attaching singletons to `app` and by using a fixture to spin up a new `app` for every test, we get test isolation without any manual cleanup

2021-06-02 00:50 UTC, mcous commented on robot-server/robot_server/protocols/protocol_models.py
> +    createdAt: datetime = Field(..., description="When this protocol was uploaded.")
That's a little bit more typing than I want to do everywhere, and feels redundant. For now, in the absence of other spec'd properties in the response body, consistency wins out as the default for me

2021-06-02 13:29 UTC, sanni-t commented on robot-server/tests/protocols/test_protocol_store.py
> +def subject(tmp_path: Path) -> ProtocolStore:
Yea, we've been using `subject` to define the test subject in a test file in almost all of our recent ProtocolEngine tickets

2021-06-02 13:58 UTC, sanni-t requested changes
Docstring mismatches.
Else looks good.

2021-06-02 13:58 UTC, sanni-t commented on robot-server/tests/protocols/test_protocol_store.py
> +    """It should get a single protocol from the store."""
```suggestion
    """It should raise an error when protocol not found."""
```

2021-06-02 13:58 UTC, sanni-t commented on robot-server/tests/protocols/test_protocol_store.py
> +    """It should get a single protocol from the store."""
```suggestion
    """It should get all protocols existing in the store."""
```

2021-06-02 13:58 UTC, sanni-t commented on robot-server/tests/protocols/test_protocol_store.py
> +    """It should save a single protocol to disk."""
```suggestion
    """It should remove specified protocol's files from store."""
```

2021-06-02 13:58 UTC, sanni-t commented on robot-server/tests/protocols/test_protocol_store.py
> +    """It should get a single protocol from the store."""
```suggestion
    """It should raise an error when trying to remove non-existent protocol."""
```

2021-06-02 13:58 UTC, sanni-t commented on robot-server/tests/protocols/test_protocols_router.py
> +    """Get an TestClient for /protocols routes with dependencies mocked out."""
```suggestion
    """Get an app instance for /protocols routes with dependencies mocked out."""
```

2021-06-02 13:58 UTC, sanni-t commented on robot-server/tests/protocols/test_protocols_router.py
> +    """It should return a single protocol file."""
```suggestion
    """It should return a 404 error when requesting a non-existent protocol."""
```

2021-06-02 16:24 UTC, sanni-t approved these changes
👍

2021-06-02 16:42 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/protocol_store.py
> +class ProtocolStoreEntry:
The OAS point is interesting. I wonder if there's a way to override that, like how we can override function names with `operationId`.

Internal `FooResource` and public `Foo` seems fine for now.

2021-06-02 18:39 UTC, mcous commented on robot-server/robot_server/protocols/protocol_models.py
> +    createdAt: datetime = Field(..., description="When this protocol was uploaded.")
Keeping an eye on this, especially once file metadata is in the mix, but leaving alone for now

2021-06-02 18:55 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/response_builder.py
> +        )
Discussed this in a hangout. Summary:

* Dependency injection makes the switch between the subject code running in production and the subject code running under test is more explicit, which feels safer and clearer.
* A class instead of a module makes bad mocking practices harder: it prevents partial mocking.
  * I personally still don't quite get why it would be bad in this case, but this video recommended by @mcous looks good and I will watch it later:
  * https://blog.testdouble.com/talks/2018-03-06-please-dont-mock-me/
* All are on board with leaving this as-written

2021-06-02 19:09 UTC, SyntaxColoring approved these changes
LGTM with `mkdir` change, as discussed in a call.

2021-06-02 20:08 UTC, merged