feat(labware-creator): Update grid spacing when tiprack is selected
OpenTrons/opentrons-api pull request #7932
Opened 2021-06-10 21:30 UTC by Kadee80

# Overview

closes #7725 by updating title and instructions to grid spacing sectionwhen tiprack is selected 

# Changelog

- feat(labware-creator): Update grid spacing when tiprack is selected

# Review requests

- [ ] title reads tip spacing when tiprack selected
- [ ] description references tips when triprack selected

# Risk assessment

Low copy changes in LC only

2021-06-11 16:27 UTC, smb2268 approved these changes
Looks good other than the one comment!

2021-06-11 16:27 UTC, smb2268 commented on labware-library/src/labware-creator/components/sections/WellSpacing.tsx
> +        {getLabwareName(values, false)}.
For this copy it looks like we want the plural text -- `getLabwareName(values, true)`

2021-06-11 16:29 UTC, smb2268 commented on labware-library/src/labware-creator/components/sections/WellSpacing.tsx
> +        {getLabwareName(values, false)}.
I also noticed that in the screenshot in the ticket, `center` is no longer bold. Not sure if that is an intentional or necessary change 🤷🏼‍♀️

2021-06-14 18:58 UTC, IanLondon requested changes

2021-06-14 18:58 UTC, IanLondon commented on labware-library/src/labware-creator/components/__tests__/sections/WellSpacing.test.tsx
> +const getLabwareNameMock = getLabwareName as jest.MockedFunction<
why mock `getLabwareName`? And if we're mocking it, it seems weird to mock "well" vs "tip" -- in testing both these cases, we're really just testing the mock setup -- `mockReturnValue("well")` vs `mockReturnValue("tip")`. One `mockReturnValue('foo')` with `nestedTextMatcher('foo spacing measurements...` would maybe make it clearer what is the testing and what is the mock

2021-06-14 18:58 UTC, IanLondon commented on labware-library/src/labware-creator/components/sections/WellSpacing.tsx
> +        {getLabwareName(values, false)}.
Yup, should be "center of wells" but right now it's "center of well" -- regression. Also should be plural for tips: "center of tips"

2021-06-16 16:05 UTC, Kadee80 commented on labware-library/src/labware-creator/components/__tests__/sections/WellSpacing.test.tsx
> +const getLabwareNameMock = getLabwareName as jest.MockedFunction<
not sure how to address this. the `getLabwareName` test tests for the actual proper words to be returned, we need to mock it here so that we get well/tip but maybe this is just a dumb redundant test for tips?

2021-06-17 15:47 UTC, IanLondon approved these changes

2021-06-17 18:12 UTC, merged