refactor(robot-server): add PE commands to /sessions responses
OpenTrons/opentrons-api pull request #8006
Opened 2021-06-24 19:50 UTC by mcous

## Overview

This PR builds on the models added to the ProtocolEngine by #7993 and adds ProtocolEngine commands to the (currently feature-flagged) `/sessions` endpoints. It also adds two new endpoints:

- `GET /sessions/:session_id/commands`
- `GET /sessions/:session_id/commands/:command_id`

Closes #7871.

## Changelog

- Add `SessionCommandSummary` models to `GET /sessions` and `GET /sessions/:session_id`
- Add new `GET /sessions/:session_id/commands` endpoint that returns `SessionCommandSummary` models
- Add new `GET /sessions/:session_id/commands/:command_id` endpoint that returns full `protocol_engine.Command` models

In real world testing, serializing all the commands of even a simple JSON protocol in full took _a long_ time (1.5s response time on an OT-2). So, after disucssions in Slack, I decided to create a minimal `SessionCommandSummary` model for the collection endpoints. We should expect to revisit this decision as development progresses, but for now I think it's a reasonable compromise.

## Review requests

TODO(mc): update Postman testing collections and post test procedure.

- [ ] Everything works as advertised (pending test plan)
- [ ] Code looks good
- [ ] Tests look good
- [ ] Generated OpenAPI Spec makes sense

## Risk assessment

N/A; work is entirely feature flagged

2021-06-24 20:12 UTC, mcous reviewed
Highlights from this PR

2021-06-24 20:12 UTC, mcous commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +        queued_command = self.state_view.commands.get(command_id)
In usage, `state_view.commands.get_command_by_id` felt quite excessive. In line with similar feedback in the past, I renamed the methods of the `CommandView` to remove `command`, given that they're all accessed via `state_view.commands`:

before | after
--- | ---
`commands.get_command_by_id` | `commands.get`
`commands.get_all_commands` | `commands.get_all`
`commands.get_next_command` | `commands.get_next_queued`

2021-06-24 20:12 UTC, mcous commented on robot-server/robot_server/service/json_api/response.py
> +ResponseDataT = TypeVar("ResponseDataT", bound=BaseModel)
Went down a bit of a rabbit hole on this one!

- This TypeVar is used by the generic `ResponseModel` to say that its `data` field must be a `ResponseDataModel`
- `ResponseDataModel` is a class in the `robot_server` package that is a `BaseModel` with an `id` field defined
- We want to put `protocol_engine.Command` models in HTTP `ResponseModel`s
    - protocol_engine.Command` is a `BaseModel` with an ID field defined
    - However, it cannot inherit from `robot_server.ResponseDataModel`

So, I saw two options available:

1. Move the responsibility of `ResponseDataModel` into the `opentrons` package as some basic resource base class
2. Downgrade this to a `BaseModel` and rely styleguide conventions to ensure all responses have IDs

I went with (2) because it was just way easier. I also explored a third option:

3. Create a resource [`Protocol`](https://mypy.readthedocs.io/en/stable/protocols.html) and set this TypeVar to say that `data` must be both `ResourceLike` (an object with an `id` property) and a `BaseModel`

Option 3 doesn't work because of fundamental limitations in the Python typing system:

- There's no `Intersection` type to say `TypeA & TypeB`
- You can't create a `Protocol` from an actual class

Longer term (assuming Option 3 never pans out), I can see us doing a version of option 1, especially if discussions continue on some sort of `OpentronsBaseModel`

2021-06-24 20:12 UTC, mcous commented on robot-server/robot_server/sessions/router.py
> +    session: ResponseModel[Session] = Depends(get_session),
I can't decide if this is great or awful, but turns out, you can throw an entire route handler into `Depends` to compose routes. Here (and in the route below) it allows us to avoid repeating ourselves with `SessionNotFound` responses.

If this bothers you, I'm happy to revert and make this more verbose / repeat ourselves a little

2021-06-24 20:12 UTC, mcous commented on robot-server/robot_server/sessions/schema_models.py
> +SessionCommandResponse = Union[
This is tedious, but it's also really important if we want our OpenAPI Spec to be reasonable. The difference between...

1. `ResponseModel[Union[CommandA, CommandB, ...]]`
2. `Union[ResponseModel[CommandA], ResponseModel[CommandB], ...]]`
 
...is **huge** in terms of the generated spec, even though they're mathematically identical. The OAS from option (1) is unusable, wheras (2) generates a nice set of reasonable types in the schema.

If we had known about this when we were evaluating response shapes, I think this would've been a huge 👎 against going with `JSON:API`-style responses (i.e. `{ data: ... }`. Unfortunately, that ship's kind of sailed, so I think we're stuck with this for the time being

2021-06-24 20:12 UTC, mcous commented on robot-server/tests/sessions/test_sessions_router.py
> +    session = SessionResource(
Could probably `DRY` these command route tests up a little. These stubs are common between all or most of the `200` tests

2021-06-29 02:01 UTC, SyntaxColoring approved these changes
🕺

2021-06-29 02:01 UTC, SyntaxColoring commented on api/src/opentrons/file_runner/command_queue_worker.py
> +            return self._engine.state_view.commands.get_next_queued()
Very nice.

2021-06-29 02:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/command_unions.py
> +from .load_labware import (
```suggestion
from .drop_tip import DropTip, DropTipRequest, DropTipResult, DropTipCommandType

from .load_labware import (
```

Whitespace nitpick for consistency with the rest of this file.

2021-06-29 02:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +        queued_command = self.state_view.commands.get(command_id)
This feels much better to me.

If we wanted to go even further, how would we feel about replacing `commands.get(id)` with `commands[id]`?

2021-06-29 02:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/commands.py
>          """Get a list of all commands in state, paired with their respective IDs.
```suggestion
        """Get a list of all commands in state.
```
Docstring update to match change in type signature.

2021-06-29 02:01 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/router.py
> +    response_model=SessionResponse,  # type: ignore[arg-type]
Not for this PR, but maybe we should in general just not use `response_model`, and instead do:

```python
    responses={
        status.HTTP_200_SUCCESS: {"model": Union[Success1, Success2]}, # I'm assuming this works.
        status.HTTP_404_NOT_FOUND: {"model": ErrorResponse[ProtocolNotFound]},
        status.HTTP_409_CONFLICT: {"model": ErrorResponse[SessionAlreadyActive]},
    },
```

`response_model` always weirded me out anyway: why is there one special success response? Especially given our error handling strategy of not `raise`ing HTTP errors from anything but the top level.

`response_model`'s use [seems to be](https://fastapi.tiangolo.com/tutorial/response-model/#add-an-output-model) automatically converting the function's return value to the given class. But we don't do that—we always return the exact, explicit model class that we want. e.g. we return `Foo(bar="baz")` instead of `{"bar": "baz"}`.

2021-06-29 02:01 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/router.py
> +    commands = engine_store.engine.state_view.commands.get_all()
Food for thought on the summarization thing.

Maybe what we really need isn't summarization, but pagination. If *n* full commands is too many to have in a response, we can't really solve that problem by summarizing those commands. If we summarize, then, at best, we've just multiplied the threshold of "too many" by some constant. In the general case, a protocol can probably have an unbounded number of commands.

2021-06-29 02:01 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/router.py
> +    session: ResponseModel[Session] = Depends(get_session),
Off the top of my head, I do not understand this, but I'll look at it again tomorrow morning when I'm smarter.

2021-06-29 02:01 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/schema_models.py
> +SessionCommandResponse = Union[
Yeah. I don't know if this is the same problem you're talking about, but this is basically how I imagined we'd fix our possible `links` values not being specified in the OpenAPI spec.

2021-06-29 02:01 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/session_view.py
> +        ]
If we basically stick with this summarization scheme, we might want something like `[c.to_summary() for c in commands]`.

2021-06-29 02:01 UTC, SyntaxColoring commented on robot-server/tests/sessions/test_sessions_router.py
> +    """It should a collection response when a session exists."""
Accidental docstring change?

2021-06-29 02:01 UTC, SyntaxColoring commented on robot-server/tests/sessions/test_sessions_router.py
> +    # TODO(mc, 2021-06-23): add actual multi-session support
This `TODO` seems bigger than this particular test function. Should we make it a ticket instead?

2021-06-29 02:05 UTC, SyntaxColoring requested changes
Changing my review to "Request changes"...

* [x] To remind us to look at this thing: https://github.com/Opentrons/opentrons/pull/8006#discussion_r660180280
* [x] ~~To remind me to look at the OpenAPI spec~~ Done, see below.
* [x] ~~To remind me to test this with Postman~~ Done, see below.

Other than that, and the nitpicks listed in my review above, this seems good to me to merge.

2021-06-29 13:52 UTC, sanni-t approved these changes
👾

2021-06-29 13:52 UTC, sanni-t commented on robot-server/robot_server/sessions/router.py
> +    commands = engine_store.engine.state_view.commands.get_all()
That's interesting.. How about summarization + pagination? The summarization makes it readable while pagination would help with the 'unbounded commands' problem.

2021-06-29 14:18 UTC, mcous commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +        queued_command = self.state_view.commands.get(command_id)
I'm anit-bracket-notation for this interface. Supporting bracket notation would bring in magic (methods) that just aren't needed and don't (IMO) meaningfully improve the DX of this class.

- It would make testing harder (or at least inconsistent, where we can no longer do a simple function mock)
- It makes it less obvious that `commands.get(id)` may be a computed value
    - If, for example, different parts of a given `Command` were stored in different places, and `get` pulled them all together
    - This isn't outside the realm of possibility
- You can already do `command_state.commands_by_id[id]`

2021-06-29 14:20 UTC, mcous commented on robot-server/robot_server/sessions/router.py
> +    response_model=SessionResponse,  # type: ignore[arg-type]
I've played around with this, and I walked away having experienced a bad time. It messes with response validation and possibly also the OpenAPI Spec. Better to work on pulling in [InferringRouter](https://fastapi-utils.davidmontague.xyz/user-guide/inferring-router/) instead I think

2021-06-29 14:23 UTC, mcous commented on robot-server/robot_server/sessions/router.py
> +    commands = engine_store.engine.state_view.commands.get_all()
I agree, I think pagination on this endpoint is going to end up being necessary.

> That's interesting.. How about summarization + pagination? The summarization makes it readable while pagination would help with the 'unbounded commans' problem.

I like this. If we're paginating, we've got query params. To I wonder if a "summary vs full" query param we could implement. I don't think this is (or will be) the only place in the HTTP API where this will come up, so some sort of universal "give me the full thing" query param might end up fairly widely used

2021-06-29 14:25 UTC, mcous commented on robot-server/tests/sessions/test_sessions_router.py
> +    # TODO(mc, 2021-06-23): add actual multi-session support
We don't have any user stories for this yet, so I think a TODO is appropriate

2021-06-29 16:56 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/router.py
> +    commands = engine_store.engine.state_view.commands.get_all()
For inspiration, we might look at Twitter's new API, which I *think* has some systematic way of letting you choose whether you want the full thing.

2021-06-29 20:35 UTC, SyntaxColoring commented
> Generated OpenAPI Spec makes sense?

There's some weirdness happening to our enums. Here's a snippet from our generated OpenAPI spec:

```json
"SessionCommandSummary": {
    "title": "SessionCommandSummary",
    "required": [
        "id",
        "commandType",
        "status"
    ],
    "type": "object",
    "properties": {
        "id": {
            "title": "Id",
            "type": "string",
            "description": "Unique command identifier."
        },
        "commandType": {
            "title": "Commandtype",
            "anyOf": [
                {
                    "const": "addLabwareDefinition",
                    "type": "string"
                },
                {
                    "const": "aspirate",
                    "type": "string"
                },
...
```

The `anyOf` `const`s *looks* good, but, in the docs...

<img width="630" alt="Screen Shot 2021-06-29 at 4 17 46 PM" src="https://user-images.githubusercontent.com/3236864/123863544-b62f3180-d8f7-11eb-9b15-4b9d0959636b.png">

I don't know if this is a `/redoc` problem or a Pydantic problem or what.

2021-06-29 20:43 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/router.py
> +    session: ResponseModel[Session] = Depends(get_session),
Aha okay I get it now.

Yeah, uh, I also can't tell if this is great or awful, lol.

Would it feel better if, instead of this:

```
get_session_commands()
    |
    V
get_session()
```

It were this?

```
get_session_commands()    get_session()
                      \   /
                       V V
          _internal_get_session()

I don't mind it staying as-is for this PR, if you want to merge today.

2021-06-29 20:44 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/router.py
> +        "available for a given command."
```suggestion
        "`GET /sessions/{sessionId}/commands/{commandId}` to get all "
        "information available for a given command."
```

2021-06-29 21:01 UTC, SyntaxColoring commented
Postman testing worked.

`POST`ing the `start` action yielded a successful response, but the robot didn't do anything. Through `GET sessions/{{session_id}}/commands` and `GET {{session_id}}/commands/{{command_id}}`, I could see that it failed on the first `loadPipette` command because I didn't have the correct pipettes physically attached. Cool!

2021-06-29 21:02 UTC, SyntaxColoring approved these changes
Looks good to me to merge, but see open comments/threads above.

2021-06-29 21:42 UTC, mcous commented
> The anyOf consts looks good, but, in the docs...

Oof. Fingers crossed this is a redoc thing. Maybe time to experiment with a FastAPI + Pydantic upgrade. Merging for now, but lets keep an close eye on this.

2021-06-29 21:42 UTC, merged