style(api,robot-server): start using black to format some modules
OpenTrons/opentrons-api pull request #8158
Opened 2021-07-23 17:35 UTC by mcous

## Overview

As part of #7629, this PR introduces [black](https://github.com/psf/black) to the monorepo. It takes a low-churn approach to this addition by limiting formatting / associated `make` tasks to files that were already broadly adhering to `black` style.

## Changelog

- Bring in black
- Introduce `format` targets in Makefiles
- Format some code that was already close

## Review requests

- [ ] Low churn approach seems good?
- [ ] Ok with using a beta version of black?
    - Anecdotally, I have yet to encounter a single issue after having black set in my editor for various projects for several months now
- [ ] Any other files we want to pull into formatting right now? 

## Risk assessment

Low, but not zero, as source code is technically being changed

2021-07-23 19:06 UTC, SyntaxColoring requested changes
Nice!

The changes I'm requesting are marked ⚠️ . Other than those, suggestions are optional, and this looks great to merge, and 

-----

> Low churn approach seems good?

Yep!

> Ok with using a beta version of black?
>
> Anecdotally, I have yet to encounter a single issue after having black set in my editor for various projects for several months now

Yep, I agree.

> Any other files we want to pull into formatting right now?

None off the top of my head.

2021-07-23 19:06 UTC, SyntaxColoring commented on api/Makefile
> -PATH := $(shell cd .. && yarn bin):$(PATH)
⚠️ I like this change, but can it potentially effect the how `npx` is found in the line immediately below? If so, can we leave it out of this PR for separate review?

2021-07-23 19:06 UTC, SyntaxColoring commented on api/Makefile
> -lint: $(ot_py_sources)
The removal of the dependency on `$(ot_py_sources)` makes sense to me because `lint` is `.PHONY` and would be rerun regardless of dependencies, anyway. Is that your thinking too?

It looks like, now, `ot_py_sources`, `ot_shared_data_sources`, `ot_resources`, and `ot_sources` are unused. Do you want to remove them in this PR?

2021-07-23 19:06 UTC, SyntaxColoring commented on api/Pipfile
> +decoy = "~=1.6.4"
⚠️  Looks like an accidental `decoy` version change?

2021-07-23 19:06 UTC, SyntaxColoring commented on Makefile
> +
Are JS folks okay with dropping `onchange` support?

2021-07-23 19:06 UTC, SyntaxColoring commented on robot-server/Makefile
> -PATH := $(shell cd .. && yarn bin):$(PATH)
⚠️ See my earlier comment on the analogous section in the `api` makefile.

2021-07-23 19:06 UTC, SyntaxColoring commented on robot-server/Pipfile
> +decoy = "~=1.6.4"
⚠️ Ditto accidental `decoy` change?

2021-07-23 19:14 UTC, mcous commented on api/Makefile
> -lint: $(ot_py_sources)
> The removal of the dependency on $(ot_py_sources) makes sense to me because lint is .PHONY and would be rerun regardless of dependencies, anyway. Is that your thinking too?

Yup!

> It looks like, now, ot_py_sources, ot_shared_data_sources, ot_resources, and ot_sources are unused.

`ot_sources` (and by extension, all these other ones) are still used in the wheel build target, which is why I didn't remove them

2021-07-23 19:16 UTC, mcous commented on api/Makefile
> -PATH := $(shell cd .. && yarn bin):$(PATH)
`npx` is not development dependency installed via `yarn`, but instead a built-in binary of the Node.js installation, so the path modifications had no bearing on how `npx` was found. I would have prefered to change this to `SHX = yarn shx` instead, but `yarn` messes with the CWD in a way that we can't really work around here.

Given that we exclusively use `npx` to access `shx`, that means our `PATH` modifications were entirely unused

2021-07-23 19:16 UTC, mcous commented on api/Pipfile
> +decoy = "~=1.6.4"
Intentional! Just me being sneaky. Since on my machine I have to wipe out the lockfiles anytime I want to update a dependency, this update is happening no matter what in this PR via the lockfile. Figured it was better to be explicit so as to not confuse myself later.

(Plus the [two bugfixes this pulls in are helpful](https://github.com/mcous/decoy/releases))

2021-07-23 19:19 UTC, mcous commented on Makefile
> +
I swear I asked people in #js months ago if anyone was using this, and the only responses were "no". Can't find any evidence of that thread, but afaik every single JS developer is running prettier in their editor

2021-07-23 19:21 UTC, SyntaxColoring commented on Makefile
> +
Good enough for me!

2021-07-23 19:22 UTC, SyntaxColoring commented on api/Makefile
> -lint: $(ot_py_sources)
Oh oops, not sure how I missed that. 👍

2021-07-23 19:24 UTC, SyntaxColoring approved these changes
🖤

2021-07-26 13:22 UTC, sfoster1 approved these changes
yay!

if we can get it to install properly i guess it's fine to use beta software i just wish they'd publish a real release so tooling wouldn't complain.

Also in cases like this I kinda think it's better to just rip the bandaid off.

2021-07-26 15:20 UTC, mcous commented
> if we can get it to install properly i guess it's fine to use beta software

Yeah, sort of feel the same way at this point. As long as the version spec is exact (rather than a range) pipenv will install it without complain. Black seems to be speeding up their release cadence, but apparently they need to rewrite their parser because of Python 3.10, so I think we'll be waiting on a "stable" release for a while.

> Also in cases like this I kinda think it's better to just rip the bandaid off.

Noted! If it's cool with you, I'll fast follow with another PR or two. Maybe one PR to convert source (without tests), and once that's stable, follow up with tests

2021-07-26 15:20 UTC, merged