feat(app): add labware setup step to protocol setup flow
OpenTrons/opentrons-api pull request #8172
Opened 2021-07-27 22:24 UTC by shlokamin

# Overview
Closes #7665

# Changelog

- Add labware setup step to protocol setup flow

# Review requests

# Risk assessment

Low, behind FF

2021-07-28 22:03 UTC, b-cooper requested changes
Looks great. I've sprinkled some comments throughout. 🌸 

 I also noticed that there are a lot of new css modules additions. We've been mainly using `styleProps` et al for all new component styling in the App. Also when using old css modules based components, if they can be updated to use style props, we've been generally opting to migrate them over as a matter of housekeeping.

2021-07-28 22:03 UTC, b-cooper commented on app/src/assets/localization/en/module_display_names.json
> +{
This file strikes me as something that should not exist in i18n. These strings are proper nouns that describe specific products, which are not generally translated. The display names for the modules can be grabbed from their JSON definition.

2021-07-28 22:03 UTC, b-cooper commented on app/src/assets/localization/en/protocol_setup.json
> +  "example_text": "Alice is using a labware in Slot 6. During pre-run check, she adjust the pipette position while checking the A1 of the labware to 0.2mm in X, and 1.2mm in Z. Later, Bob is preparin
I know this copy is still in progress, but I believe "pre-run check" is being updated to "labware position check"

2021-07-28 22:03 UTC, b-cooper commented on app/src/assets/localization/en/protocol_setup.json
> +  "labware_help_modal_text_1": "You can make optional positioning adjustments before a protocol run using labware offsets. These adjustments are measured to the nearest 1/10th mm and can be made in X
For translation keys in the app, I've been trying to avoid cryptic identifiers to make the file more readable by itself. For example a key like "labware_help_modal_text_1" could be replaced with something that explains that translation's meaning  e.g. "labware_offset_explanation". 

One other thing to note here, it looks like these three translations `text_1 ... 3` are actually semantically one long explanation. If this is the case, they should be grouped under one translation key.  The new lines can be captured using `react-i18next`'s  `Trans` component [docs](https://react.i18next.com/latest/trans-component).  By default it supports usage of "<br/>" in translation strings and will safely convert them to react break elements.

This is also a useful pattern for interpolating variable strings into translations, or embedding links or other elements within a translatable chunk.

2021-07-28 22:03 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/LabwareSetup/LabwareInfoOverlay.tsx
> +    <svg>
is this `svg` tag necessary here?  it should be redundant as this overlay is already being rendered as deep child of the `RobotWorkspace`'s `svg` parent

2021-07-28 22:03 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/LabwareSetup/LabwareInfoOverlay.tsx
> +      <p className={styles.display_name}> {displayName} </p>
All of the contents of this `div` could be replaced with the `Trans` component. You can pass down and object of with keyed variables to interpolate into the translation string. This should clear up all of the weird whitespace workarounds.  Look [here](https://github.com/Opentrons/opentrons/blob/d00cbf95ceed3350566ebd2b54944d937b01ca69/app/src/pages/Robots/RobotSettings/connection.tsx#L60) for an existing usage of the component with sub components and variable options passed down via the `components` and `tOptions` props respectively

2021-07-28 22:03 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/LabwareSetup/ModuleTag.tsx
> +          : STD_SLOT_X_DIM + childXOffset)
It seems like this calculation shouldn't include the slot dimensions at all, shouldn't it be based off of the module's x and y dimensions?

2021-07-28 22:03 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/LabwareSetup/index.tsx
> +          viewBox={`-64 -10 ${530} ${456}`}
It's probably valuable to put some of these viewbox constants as importable from the components library, but in the mean time, perhaps we can move it to a const at the top of this file?

2021-07-29 13:27 UTC, jerader reviewed
I tested a few example protocols and noticed that the thermocycler doesn't show up in labware setup when implemented - I'm guessing this is not intentional since the other modules show up fine.

2021-07-29 14:11 UTC, shlokamin commented on app/src/assets/localization/en/module_display_names.json
> +{
Great point, I have a bad habit of throwing everything in i18n and not thinking too hard about why — this is a great example of something that does not belong there

2021-07-29 14:17 UTC, shlokamin commented on app/src/assets/localization/en/protocol_setup.json
> +  "labware_help_modal_text_1": "You can make optional positioning adjustments before a protocol run using labware offsets. These adjustments are measured to the nearest 1/10th mm and can be made in X
oh this is 💯 will def use this

2021-07-29 14:21 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/LabwareInfoOverlay.tsx
> +    <svg>
this is true, i actually threw it in cuz my unit test was complaining that no `svg` parent exists (because technically from just rendering `LabwareInfoOverlay` no `svg` exists at all). i guess this component would only really be used inside of an svg tag, so i think it's safe to get rid of it

2021-07-29 14:45 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/ModuleTag.tsx
> +          : STD_SLOT_X_DIM + childXOffset)
slacked you then realized i should just do this here for posterity lol. shouldn't the text with the module info start right next to the slot? if it started next to the module rectangle, it would be off screen right?

2021-08-04 18:17 UTC, emilywools commented
THANK YOU this is looking fab!!!!

things I noticed, let me know if I should be logging any of these on a different ticket:

1. header should have an X next to close (not a chevron)
<img width="1065" alt="Screen Shot 2021-08-04 at 2 08 17 PM" src="https://user-images.githubusercontent.com/4339860/128232280-6e150ffd-d67e-452e-96e1-14a972fe9d4f.png">

2. bottom of labware or just the overlay is not rounded to match the rest of the labware
<img width="346" alt="Screen Shot 2021-08-04 at 2 09 32 PM" src="https://user-images.githubusercontent.com/4339860/128232363-1b1002c3-66c9-4fbe-a079-75dcb128f9ed.png">

3. Can you add some more space between the x, y and z offset s (so after the number and before the next letter)
4. can you change the label for the offsets from "Offset Data" to "Offset"
5. Can you make the deck SVG a bit smaller (maybe 20%) so a user can see more of it in their viewport at once (we might have to play around with the right size together)
6. on the labware overlay, can you have 2 "paragraphs" 1 for the labware name, and 1 for the offset data label and the data, and make the offset data label closer to the data so it looks like 1 paragraph (does that make sense??)
7. Labware Help modal: it looks like there's a scroll bar without a scroll bar on the right side of the modal
<img width="932" alt="Screen Shot 2021-08-04 at 2 18 20 PM" src="https://user-images.githubusercontent.com/4339860/128233569-dce8aa17-2d1c-4a63-bedf-743fa9664782.png">

8. Labware help modal: can you make the close button OT blue
9. Labware help modal: can you make sure all the corners of the modal are rounded
10. Labware help modal: can you have the modal cover the entire app, including the main nav
11. "setup for run" title for the accordions should be bigger font size than the individual accordion headers

2021-08-04 19:06 UTC, b-cooper commented on app/src/assets/localization/en/protocol_setup.json
> +  "labware_help_example": "<p>Alice is using a labware in Slot 6. During labware position check, she adjust the pipette position while checking the A1 of the labware to 0.2mm in X, and 1.2mm in Z. La
In this translation and above, the usage of `<p>` in the translation string is a bit suspicious to me. I think in this case, it shouldn't be included at all. Above, if the only point is to embed a line break, then I'd probably opt for the <br /> tag first.  In my mind it keeps more separate the concerns of layout markup and translation traits more effectively.  e.g. "This block of english text should be broken up into these indented thoughts" as opposed to "this block of english text, which is also an HTML p tag etc."

2021-08-04 19:15 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/LabwareSetup/LabwareSetupModal.tsx
> +            <Box margin={`${SPACING_3} ${SPACING_5}`}>
This is totally fine, just throwing it out there in case you hadn't encountered the helper style props `marginX` and `marginY`.  You could use them here like `<Box marginY={SPACING_3} marginX={SPACING_5}` />

2021-08-04 19:26 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/LabwareSetup/index.tsx
> +                      <svg>
this `<svg>` tag is gratuitous

2021-08-04 19:30 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/LabwareSetup/LabwareInfoOverlay.tsx
> +        className: cx(styles.labware_info_overlay),
`innerDivProps` here should accept all style props too. I guess a more accurate prop name would be `innerBoxProps`. You should be able to avoid adding this css rule and potentially the whole css file.

2021-08-04 19:32 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/LabwareSetup/styles.css
> +@import '@opentrons/components';
I think, theoretically all of these rules can be replaced with style prop usage in their components?  Are there any necessary legacy hold outs?

2021-08-04 19:47 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/LabwareSetup/utils/getLabwareRenderCoords.ts
> +        if ('modules' in protocolData) {
isn't this whole block of logic duplicated by `getModuleRenderCoords`?

2021-08-04 19:51 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RunSetupCard.tsx
> +    matingSurfaceVector?: [number, number, number]
this interface doesn't seem to fit the object returned by `getLabwareRenderCoords` despite it's return type.  It looks like maybe `matingSurfaceVector` should be replaced with the `z` value?

2021-08-05 15:31 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/LabwareInfoOverlay.tsx
> +        className: cx(styles.labware_info_overlay),
oh this is great i did not realize this, good catch! was able to get rid of most of the css module styles. unfortunately i still need a few of them to pass into `RobotWorkSpace` and `Modal` ☹️

2021-08-05 15:48 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/utils/getLabwareRenderCoords.ts
> +        if ('modules' in protocolData) {
I think they're slightly different. this block in `getLabwareRenderCoords` is first looking to see if there are any modules in the slot that this labware (in the iteration) is on top of. If there is a module under the labware, we do some math and apply the module offset to the labware.

In `getModuleRenderCoords`, we don't care about labware, we're just returning the corrds of the module, so we don't have to do any lookup. In `getModuleRenderCoords` we also add the module's model (which `getLabwareRenderCoords` doesn't care about), but once we refactor our module render component to only care about coordinates we can get rid of the module model. 

But if I'm missing something and there's a way we can reuse some logic here and make this cleaner I'm all for it!

2021-08-05 16:37 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard.tsx
> +    matingSurfaceVector?: [number, number, number]
oy good catch

2021-08-05 16:47 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/styles.css
> +@import '@opentrons/components';
almost, `RobotWorkSpace` and `Modal` still only take `className` :/

2021-08-05 16:47 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/styles.css
> +@import '@opentrons/components';
but was able to git rid of most of em!

2021-08-05 19:38 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/LabwareSetup/utils/getLabwareRenderCoords.ts
> +            const slotHasMatingSurfaceVector = getSlotHasMatingSurfaceUnitVector(
I think technically since we're iterating over the `modules` and the `labware` now, as opposed to the `slots` from the deck def, we don't really have to do the mating surface check. That was a way for us to make sure we didn't place items in the trash's slot, which is sort of an upstream concern here.  No module or labware's slot parameter should ever be 12 anyway.

2021-08-05 19:40 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/LabwareSetup/LabwareInfoOverlay.tsx
> +        display: 'flex',
nit: there are constants for these values. `DISPLAY_FLEX` , 'DIRECTION_COLUMN', and `JUSTIFY_FLEX_END` I believe

2021-08-05 19:41 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/LabwareSetup/index.tsx
> +                      <g>
I think this `<g>` tag is also gratuitous

2021-08-05 19:58 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/utils/getLabwareRenderCoords.ts
> +            const slotHasMatingSurfaceVector = getSlotHasMatingSurfaceUnitVector(
if we don't check the mating surface we'll have to check for something else (could be if that id is the trash's id or something) bcuz the trash shows up in `state.protocol.data.labware`. so if we got rid of the check, trash would render in slot 12

2021-08-05 20:01 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/LabwareSetup/utils/getLabwareRenderCoords.ts
> +            const slotHasMatingSurfaceVector = getSlotHasMatingSurfaceUnitVector(
aha, good point, I forgot that the trash shows up in the labware object. Cool let's keep this as is then.

2021-08-05 20:24 UTC, shlokamin commented
@emilywools 
- [x] 1. header should have an X next to close (not a chevron)
- [x] 2. bottom of labware or just the overlay is not rounded to match the rest of the labware
- [x] 3. Can you add some more space between the x, y and z offset s (so after the number and before the next letter)
- [x] 4. can you change the label for the offsets from "Offset Data" to "Offset"
- [x] 5. Can you make the deck SVG a bit smaller (maybe 20%) so a user can see more of it in their viewport at once (we might have to play around with the right size together)
- [x] 6. on the labware overlay, can you have 2 "paragraphs" 1 for the labware name, and 1 for the offset data label and the data, and make the offset data label closer to the data so it looks like 1 paragraph (does that make sense??)
- [ ] 7. Labware Help modal: it looks like there's a scroll bar without a scroll bar on the right side of the modal

When the text can't fill the viewport a scrollbar will appear. When i make the window big enough the scroll bar goes away. What's the expected behavior?

- [x] 8. Labware help modal: can you make the close button OT blue
- [ ] 9. Labware help modal: can you make sure all the corners of the modal are rounded

they're showing up rounded for me... let's look together on your machine I may have just forgotten to include that on the version you checked
- [ ] 10. Labware help modal: can you have the modal cover the entire app, including the main nav

not done yet. i expected this to be the default behavior when rendering a modal inside the main `Portal` in the run app... @b-cooper is there any time we have a modal take up the whole screen in the run app?
- [x] 11. "setup for run" title for the accordions should be bigger font size than the individual accordion headers

2021-08-05 20:38 UTC, smb2268 approved these changes
looks great! 🤘🏻 nice work

2021-08-05 20:43 UTC, jerader approved these changes
Looking great - good job!

2021-08-05 20:49 UTC, b-cooper commented
Re: Whole view port modals.  Yes we do block the whole window for the captive calibration modals. In this case you just need to render the modal into the Top Portal as opposed to the Modal Portal (confusingly named) you can do this by passing the `level="top"` prop to the app's `Modal` component

2021-08-05 20:51 UTC, b-cooper approved these changes
Looking good! 🏭 some good improvements to the way we think about placing things on the rendered deck

2021-08-05 21:11 UTC, merged