feat(app): gather all protocol and calibration data
OpenTrons/opentrons-api pull request #8182
Opened 2021-07-29 15:54 UTC by smb2268

fix #8097

# Overview

This PR includes all of the selectors needed to gather data on required labware from a json protocol and check that against the labware that is currently on the robot. 

# Changelog
1. Create selector to synthesize needed pipette and tiprack info from protocol
2. Create selector to check if necessary labware is on the robot
3. Create selector to synthesize matching labware and calibration info
4. Create selector to determine whether robot calibration step is complete
5. Display this data in plain text in the robot calibration step in the app
6. TODO: Fix TS errors and add testing

# Review requests

Am I missing any possible reasons that the calibration step is not complete? Is this all of the data we need to consider to display all scenarios?

# Risk assessment

Mid - behind feature flag

2021-07-30 15:30 UTC, b-cooper requested changes
Everything is looking good. These are some gnarly bits of the client that you're untangling and you've tackled it well.  

I made a few house keeping suggestions.  I'll do another pass over the code, and test it out, once you've got some tests written too.

2021-07-30 15:30 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/DeckCalibration.tsx
> +      <Text marginTop={SPACING_3}>Deck Calibration</Text>
This string can get thrown in i18n too.

2021-07-30 15:30 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/DeckCalibration.tsx
> +      typeof deckCalData?.source === 'string'
It looks like you can get rid of this `@ts-expect-error` if you add  `('source' in deckCalData && ` to the beginning of this expression.

2021-07-30 15:30 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/DeckCalibration.tsx
> +  if (deckCalData == null) {
This makes sense that we'd want to return `null` if there is not deckCalData present.  Maybe just for good measure, we should throw an explanatory comment here that highlights that this component's parent shouldn't be rendered if there is no cal data.

2021-07-30 15:30 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/DeckCalibration.tsx
> +export const DeckCalibration: React.FunctionComponent<Props> = (
For functional components we've mostly been typing them like plain old functions that return `JSX.Element` or in components like this one `JSX.Element | null`.

So this would be 

```
export function DeckCalibration(props: Props): JSX.Element | null { ....
```

2021-07-30 15:30 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/DeckCalibration.tsx
> +import * as React from 'react'
One note on file organization for these new components. It looks like `RobotCalibrationStep` is only ever going to be rendered as a direct child of `RunSetupCard`. And furthermore, this `DeckCalibration` components is only ever rendered as a direct child of `RobotCalibrationStep`.  In order to make this relationship clearer when browsing these files we often opt for a directory here. Any parent component that is sufficiently complex to warrant another child component file (that will never appear outside of that parent) should be turned into a directory with an the main component export in `index.tsx` and any specialized child components files collocated with it."

The dir structure for the larger `ProtocolSetup` organism would then look like:
 
```
app/src/organisms/ProtocolSetup/
    index.tsx
    hooks.tsx
    MetadataCard.tsx
    RunSetupCard/
        index.tsx    <-- old contents of RunSetupCard.tsx
        RobotCalibrationStep/
             index.tsx <-- old contents of RobotCalibrationStep.tsx
             DeckCalibrationInfo.tsx <-- this component
             CollapsibleStep.tsx <-- only used in RunSetupCard

```


Now at a glance I can glean that `ProtocolSetup` is composed of two specialized children `RunSetupCard` and `MetadataCard`.  It's also now clearer that `RunSetupCard` is itself complex enough to be broken into a directory with its own specialized children.

2021-07-30 15:30 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RobotCalibrationStep.tsx
> +export const RobotCalibrationStep: React.FunctionComponent<Props> = (
```suggestion
export function RobotCalibrationStep(props: Props): JSX.Element {
```
to follow the existing typing convention for functional components in the app

2021-07-30 15:30 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RobotCalibrationStep.tsx
> +        {protocolPipetteData.map(protocolPipette => {
Maybe it would be clearer what this tuple `protocolPipette` is if the `Object.entries` call was inline here instead of above.  e.g.

```
{Object.entries(protocolPipetteData).map(([mount, pipetteData]) => {
   ...
}
``` 
also you can destructure the tuple in the parameters to save the first few lines of this anonymous function.

2021-07-30 15:30 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RobotCalibrationStep.tsx
> +                <span>
This text should live in i18n. This kind of interpolation is also a perfect use case for the `Trans` component from [react-i18next](https://react.i18next.com/latest/trans-component). The same goes for the tip length calibration map below too.

2021-07-30 15:30 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RunSetupCard.tsx
> +    [ROBOT_CALIBRATION_STEP_KEY]: <RobotCalibrationStep robot={robot} />,
because this parent component already grabs `ProtocolData` from redux, it might make sense to pass that down as a prop to `RobotCalibrationStep` in addition to robot in the interest of keeping child components as pure as possible.

2021-07-30 15:30 UTC, b-cooper commented on app/src/redux/calibration/selectors.ts
> +        reason: 'calibrate deck',
Doesn't have to happen in this PR, but it would be good to capture these reasons in a typed const, that way we can also use them later on as a sort of enum key to the actual tool tip message.

2021-07-30 15:30 UTC, b-cooper commented on app/src/redux/protocol/selectors.ts
> +  // where are the type definitions of these protocol data objects?
they should be importable from `@opentrons/shared-data`

2021-08-17 20:27 UTC, b-cooper approved these changes
Looks good to merge! 🧇

2021-08-17 20:27 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RunSetupCard/RobotCalibrationStep/DeckCalibration.tsx
> +  const buildDeckLastCalibrated: (
Because this formatting function actually does a fair bit of usefully logic for any time that we visualize deck calibration data, can we call out with a TODO comment that this function is a copy of `buildDeckLastCalibrated` from the `RobotSettings`  page and mention that ideally they both components could import this from a shared utils location?

2021-08-17 20:27 UTC, b-cooper commented on app/src/redux/calibration/types.ts
> +export interface ProtocolCalibration {
naming nit: This object is more of a `ProtocolCalibrationStatus` in my mind.  `ProtocolCalibration` mirrors our naming of actual calibration values (e.g. coordinate data in from  `DeckCalibration`, `PipetteOffsetCalibration`, and `TipLengthCalibration`).

2021-08-18 14:23 UTC, shlokamin reviewed
Great work Sarah!

Left a few comments. I don't want to hold up this PR, but I think we should come back and add some missing test coverage because some of these selectors you wrote are pretty important and we'll rely on them heavily. 

Also, I see you moved `RobotCalibrationStep` into `RunSetupCard`. When I did labware setup I kept `LabwareSetup` as it's own directory as a sibling to `RunSetupCard`, and I see @jerader did the same for `ModuleSetup`. 

It doesn't really matter to me which structure we choose, but we should be consistent in where we place each of these steps (since they're siblings), and be consistent in the naming (postfix with Step or not).

2021-08-18 14:23 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/RobotCalibrationStep/DeckCalibration.tsx
> +import { formatLastModified } from '../../../CalibrationPanels/utils'
nit: we unfortunately have a pattern of imports we follow that is not enforced by a linter **sigh** check out [this discussion](https://github.com/Opentrons/opentrons/pull/4680#discussion_r363102698) 

basically we usually do

1. Builtin Node.js modules (import fs from 'fs')
2. External npm modules (import * as React from 'react')
3. Opentrons modules (import { THERMOCYCLER } from '@opentrons/shared-data')
4. Parent relative modules (import { SomeParentComponent } from '../../parent')
5. Sibling relative modules (import { SomeSiblingComponent } from './sibling')
6. type imports (import type {Whatever} from './types')

2021-08-18 14:23 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/RobotCalibrationStep/DeckCalibration.tsx
> +        : t('last_calibrated')
nit: i like simple ternaries but nested ones like this make me feel sad. this is really a personal style choice though

2021-08-18 14:23 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/RobotCalibrationStep/DeckCalibration.tsx
> +        : t('last_calibrated')
curious what @b-cooper and @jerader think too

2021-08-18 14:23 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/RobotCalibrationStep/index.tsx
> +import { formatLastModified } from '../../../CalibrationPanels/utils'
same point as before re: import order

2021-08-18 14:23 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/index.tsx
> +    [ROBOT_CALIBRATION_STEP_KEY]: <RobotCalibrationStep robot={robot} />,
looks like we're missing a test to see whether `RobotCalibrationStep` gets called with the correct props. you can do something similar to what we did for [LabwareSetup](https://github.com/Opentrons/opentrons/blob/618161c74e582845d5907e9368c199396486ed6f/app/src/organisms/ProtocolSetup/__tests__/RunSetupCard.test.tsx#L60) but make sure that `RobotCalibrationStep` is called with the correct (mocked) robot instead

2021-08-18 14:23 UTC, shlokamin commented on app/src/redux/calibration/selectors.ts
> +        return {
Looks like codecov is complaining a lot here since this selector doesn't seem to be covered by any tests

2021-08-18 14:23 UTC, shlokamin commented on app/src/redux/calibration/types.ts
> +export interface ProtocolCalibration {
agreed!

2021-08-18 14:23 UTC, shlokamin commented on app/src/redux/pipettes/selectors.ts
> +) => Types.ProtocolPipetteTipRackCalDataByMount = createSelector(
same deal here, this doesn't seem to be covered by any tests

2021-08-18 15:50 UTC, smb2268 commented on app/src/organisms/ProtocolSetup/RunSetupCard/RobotCalibrationStep/DeckCalibration.tsx
> +        : t('last_calibrated')
I actually agree, this is super unreadable -- I pulled this from https://github.com/Opentrons/opentrons/blob/edge/app/src/pages/Robots/RobotSettings/DeckCalibrationControl.tsx#L174-L195 but I'm not even sure if we need all of these variations since `Last Calibrated` is the only variation displayed in the figma. I'll probably update this when I do the next ticket which has more of the visual stuff

2021-08-18 16:13 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RunSetupCard/RobotCalibrationStep/DeckCalibration.tsx
> +        : t('last_calibrated')
Yeah good point, I think we are probably far enough from the release of 4.0 that we can deprecate the "last migrated".  Feel free to do just make it "last calibrated" here or in the next ticket, whichever is easier. I am also not a fan of nested ternaries, I'm glad we all feel that way

2021-08-19 21:30 UTC, smb2268 commented
> Also, I see you moved `RobotCalibrationStep` into `RunSetupCard`. When I did labware setup I kept `LabwareSetup` as it's own directory as a sibling to `RunSetupCard`, and I see @jerader did the same for `ModuleSetup`.
> 
> It doesn't really matter to me which structure we choose, but we should be consistent in where we place each of these steps (since they're siblings), and be consistent in the naming (postfix with Step or not).

@shlokamin I don't have a strong opinion on how these should be organized. I'll drop the postfix Step since I'm last to merge. For file organization I was going off of @b-cooper's suggestion in this comment, which I do think makes sense since all three of these are technically children of `RunSetupCard`, but since that's more of a structural component without a lot of logic nI don't mind if the children are outside of the folder. https://github.com/Opentrons/opentrons/pull/8182#discussion_r679999105

2021-08-23 18:11 UTC, merged