feat(rootfs.py): ot3 RootFS class {WIP}
OpenTrons/opentrons-api pull request #8200
Opened 2021-08-04 13:11 UTC by sotaoverride

Class for controlling OT3 RootFS {WIP}

OT3 RootFS manipulation to manage updates, system restore etc. This would act as a helper class.

2021-08-11 16:16 UTC, sfoster1 requested changes
While this utility script looks like it would work, the immediate next step is to make it part of the actual update server anyway. I think we should skip straight to that step, and have this script be in a new subpackage of the update server; call it `openembedded` and stand it next to `buildroot`. it doesn't have to have a lot in it, just a `__main__.py` that contains the script itself. We can then add the dependencies to pipenv.

In the future we'll still have to refactor some things - it would be nice to share some of the logic here - but this would be a better start.

2021-08-13 15:23 UTC, Laura-Danielle reviewed
Just some suggestions

2021-08-13 15:23 UTC, Laura-Danielle commented on update-server/otupdate/openembedded/RootFS.py
> +    major: str
Can we make the major and minor versions integers?

2021-08-13 15:23 UTC, Laura-Danielle commented on update-server/otupdate/openembedded/RootFS.py
> +    ROOTFS_PART1 = ''
Can we also make these configs into a dataclass?

2021-08-13 15:23 UTC, Laura-Danielle commented on update-server/otupdate/openembedded/RootFS.py
> +    def setPartition(self, arg, PartitionName):
Nit: typically we don't use camel case in python for functions. Here we would call it `set_partition` rather than `setPartition`

2021-08-13 15:23 UTC, Laura-Danielle commented on update-server/otupdate/openembedded/RootFS.py
> +    def getPartition(self):
Same nit: no camel case.

2021-08-13 15:23 UTC, Laura-Danielle commented on update-server/otupdate/openembedded/RootFS.py
> +    def swapPartition(self, arg):
Same nit: no camel case.

2021-08-13 15:23 UTC, Laura-Danielle commented on update-server/otupdate/openembedded/RootFS.py
> +    def factoryRestore(self, arg):
Same nit: no camel case.

2021-08-13 15:23 UTC, Laura-Danielle commented on update-server/otupdate/openembedded/RootFS.py
> +    def printRootFSPartition(self, arg):
Same nit: no camel case.

2021-08-13 15:23 UTC, Laura-Danielle commented on update-server/otupdate/openembedded/RootFS.py
> +    ROOTFS_PART1 = ''
And then you can initialize the dataclass with these default values when you call it in the class.

2021-08-18 19:53 UTC, sotaoverride commented
> While this utility script looks like it would work, the immediate next step is to make it part of the actual update server anyway. I think we should skip straight to that step, and have this script be in a new subpackage of the update server; call it `openembedded` and stand it next to `buildroot`. it doesn't have to have a lot in it, just a `__main__.py` that contains the script itself. We can then add the dependencies to pipenv.
> 
> In the future we'll still have to refactor some things - it would be nice to share some of the logic here - but this would be a better start.

the __main__.py in otupdate still needs a refactor, got the other bits mentioned above in

2021-08-19 17:13 UTC, DerekMaggio requested changes

2021-08-19 17:13 UTC, DerekMaggio commented on update-server/otupdate/openembedded/RootFS.py
> +    def set_partition(self, arg, PartitionName):
Unless I am missing something it looks like `PartitionName` is a variable. 
If so, it should use snake case and be `partition_name`. 
Using the uppercase camel case denotes a class, so it looks like you are passing a class called `PartitionName` to the function

2021-08-19 17:13 UTC, DerekMaggio commented on update-server/otupdate/openembedded/RootFS.py
> +        if m:
This should be, `if match is not None`. If for some reason the search returned a `False` or `True` value or `1` or `0` this would get all messed up

2021-08-19 17:13 UTC, DerekMaggio commented on update-server/otupdate/openembedded/RootFS.py
> +        if currentPartition is not None:
Should this log some kind of error if `currentPartition` is None?

2021-08-19 17:13 UTC, DerekMaggio commented on update-server/otupdate/openembedded/RootFS.py
> +        currentPartition = self.get_partition()
Coding Convention: You are swapping between snake and camel case

2021-08-19 17:13 UTC, DerekMaggio commented on update-server/otupdate/openembedded/RootFSCLI.py
> +        parser_debug.set_defaults(func=rfs.debug)
To confirm I am understanding correctly. This line is where you are mapping the cli command to the actually functionality that it is going to run?

2021-08-19 17:13 UTC, DerekMaggio commented on update-server/otupdate/openembedded/RootFSCLI.py
> +        parser_debug.add_argument('--tt', '-t', type=str, nargs='?', help="test title",
With this one if you call `-t` without a value, `t` will equal `OT# RootFS Tests`? If you call it with a value, `t` will equal `OT3 RootFS Test`?

2021-08-20 13:13 UTC, sfoster1 requested changes

2021-08-20 13:13 UTC, sfoster1 commented on update-server/otupdate/openembedded/RootFS.py
> +    def set_partition(self, arg, PartitionName):
let's get some type hints in here also

2021-08-20 13:13 UTC, sfoster1 commented on update-server/otupdate/openembedded/RootFS.py
> +    def get_partition(self):
type hints for return

2021-08-20 13:13 UTC, sfoster1 commented on update-server/otupdate/openembedded/RootFS.py
> +            return None
consider `raise`ing here, this isn't really an acceptable failure case right

2021-08-20 13:13 UTC, sfoster1 commented on update-server/otupdate/openembedded/RootFS.py
> +    def print_rootFS_partition(self, arg):
I think it'll be a little more flexible if these are just returning strings and a caller prints it if they want; that way we can use this class going forward

2021-08-20 13:13 UTC, sfoster1 commented on update-server/otupdate/openembedded/RootFS.py
> +    def print_rootFS_config(self, arg):
same here - maybe return a string instead

2021-08-20 13:13 UTC, sfoster1 commented on update-server/otupdate/openembedded/RootFSCLI.py
> +                                           const='opentrons-ot3-image'
we have a surprisingly long line length (93 i think?) we should take advantage

2021-08-20 13:13 UTC, sfoster1 commented on update-server/otupdate/openembedded/requirments.txt
> +bmap-tools==3.6
let's get rid of this since we're not using it

2021-08-20 13:13 UTC, sfoster1 commented on update-server/setup.py
> +INSTALL_REQUIRES = [
transitive dependencies don't go in `INSTALL_REQUIRES`, just direct dependencies - when using `setup.py` it's up to `pip` to figure it out.

one thing we might want to think about is providing the openembedded part as an addon? i don't think it matters much though

2021-08-20 13:13 UTC, sfoster1 commented on update-server/otupdate/openembedded/RootFS.py
> +        out = subprocess.Popen(shlex.split("df /"),
i'm pretty sure this will work but it feels like a kind of weird workaround; could we parse `/etc/fstab` or the result of `mount` or i'm sure there's something in `/proc` somewhere?

2021-08-20 13:44 UTC, DerekMaggio requested changes

2021-08-20 13:44 UTC, DerekMaggio commented on update-server/otupdate/openembedded/RootFS.py
> +    class root_FS_config:
You are going to hate me. 
Classes should be capitalized camel case. For example, `AatirShouldHateDerek`
Variables, functions, and methods should be snake case. For example, `a_whole_lot`

2021-08-20 15:09 UTC, sotaoverride commented on update-server/otupdate/openembedded/RootFSCLI.py
> +        parser_debug.set_defaults(func=rfs.debug)
yep, thats the hope here.

2021-08-20 15:09 UTC, sotaoverride commented on update-server/otupdate/openembedded/RootFSCLI.py
> +        parser_debug.add_argument('--tt', '-t', type=str, nargs='?', help="test title",
yeah, this was just to give the tests a title.. title passed gets appended at the end a fixed string
print('ROOTFS_TEST_TITLE '+arg.tt+'\n')

2021-08-20 15:09 UTC, sotaoverride commented on update-server/otupdate/openembedded/RootFS.py
> +        currentPartition = self.get_partition()
opps, though snake was just for function names. ill go snake all over.

2021-08-23 14:56 UTC, sotaoverride commented on update-server/otupdate/openembedded/requirments.txt
> +bmap-tools==3.6
egg format for bmaptools is suppose to install it as a command line tool, and im hoping to use it some system restore functions. this pr use it in factory_restore function

2021-08-24 15:56 UTC, sfoster1 commented on update-server/otupdate/openembedded/requirments.txt
> +bmap-tools==3.6
sorry, i meant this entire file. it's not used anymore

2021-08-24 15:56 UTC, sfoster1 commented on update-server/Pipfile
> +bmap-tools = {editable = true, ref = "master", git = "https://github.com/intel/bmap-tools.git"}
given that we have this as a versioned requirement in `install_requires` in setup.py, can we make this a versioned requirement here as well?

2021-08-24 16:28 UTC, sotaoverride commented on update-server/Pipfile
> +bmap-tools = {editable = true, ref = "master", git = "https://github.com/intel/bmap-tools.git"}
think the issue with bmap-tools was that since it's not on pypi doing something like bmap-tools = xxxx wasn't working out. is that what you mean by a straight up version requirement here?

2021-08-24 16:56 UTC, sfoster1 commented on update-server/Pipfile
> +bmap-tools = {editable = true, ref = "master", git = "https://github.com/intel/bmap-tools.git"}
it was, but in that case how are we specifying it in the the `setup.py`?

2021-09-08 18:28 UTC, Laura-Danielle reviewed
Just one comment. Looks fine otherwise.

2021-09-08 18:28 UTC, Laura-Danielle commented on update-server/otupdate/openembedded/RootFS.py
> +        self.RootFSConfig_ = self.RootFSConfig('' , '', '' , '',
When you have defaults set, you can just do: `RootFSConfig()`. It will pre-populate the date class with the defaults you made above.

2021-09-08 18:28 UTC, Laura-Danielle commented on update-server/otupdate/openembedded/RootFS.py
> +        self.RootFSConfig_ = self.RootFSConfig('' , '', '' , '',
Also, unless you _really_ want to make sure you can't access this dataclass you can just pull it out of `RootFS` and put it near `RootFSInfo`

2021-09-08 18:41 UTC, sotaoverride commented on update-server/otupdate/openembedded/RootFS.py
> +        self.RootFSConfig_ = self.RootFSConfig('' , '', '' , '',
cool, thanks. Ill start using those dataclass features. Ive kinda moved onto this branch now [openembedded-update-server ](https://github.com/Opentrons/opentrons/pull/8303), will get these changes in on there.

2021-09-08 19:58 UTC, sotaoverride commented
moving this to openembedded-update-server

2021-09-08 19:58 UTC, closed without merging