feat(api): Add G-Code Parser Makefile Execution
OpenTrons/opentrons-api pull request #8203
Opened 2021-08-04 19:35 UTC by DerekMaggio

# Overview

Added support for running the G-Code Parser CLI through the `api` project Makefile. 

# Changelog

* Add device name to text mode output
* Add HTML formatting for GCodeDiffer HTML output
* Add strings_are_equal method to GCodeDiffer
* Utilize strings_are_equal method in cli.py
* Add Makefile targets to run G-Code Parser
* Add first protocol test to Makefile

# Review requests

Check if I am doing anything dumb in the Makefile

# Risk assessment

None

2021-08-05 15:39 UTC, amitlissack reviewed
Code looks good to me. I'll test it out before +1.

2021-08-05 15:39 UTC, amitlissack commented on api/Makefile
> +	google-chrome file://$(diff_file)
Does this have to bee `google-chrome`? Would `open` launch the default browser?

2021-08-05 15:56 UTC, amitlissack approved these changes
Tested `make g-code-smoothie-protocol-run` and worked fine. 

I recommend someone who is more Makefile knowledgable approves before merging.

2021-08-05 16:07 UTC, DerekMaggio commented on api/Makefile
> +	google-chrome file://$(diff_file)
I don't have open on my system :/

2021-08-06 15:05 UTC, sotaoverride reviewed
trying to figure if you need to add actions to this branch?

2021-08-06 15:05 UTC, sotaoverride commented on .github/workflows/g-code-confirm.yaml
> +      - uses: 'actions/checkout@v2'
im trying to find this action under actions for this repo? is that where its picked up from?

2021-08-06 15:05 UTC, sotaoverride commented on .github/workflows/g-code-confirm.yaml
> +  pull_request:
maybe set it to trigger for all branches for now too?

2021-08-06 15:07 UTC, sotaoverride commented on .github/workflows/g-code-confirm.yaml
> +      - uses: 'actions/checkout@v2'
or are these some gh actions you can add straight away ??

2021-08-06 15:14 UTC, sotaoverride reviewed
do new workflows just get picked up, or you have to add them the first time around?https://github.com/Opentrons/opentrons/actions/new

2021-08-06 18:51 UTC, sotaoverride commented on .github/workflows/g-code-confirm.yaml
> +      - uses: 'actions/checkout@v2'
figured these actions just come with github..

2021-08-06 19:13 UTC, sotaoverride commented on .github/workflows/g-code-confirm.yaml
> +name: G-Code-Confirm
missing quotes here, 'G-Code-Confirm'

2021-08-06 19:13 UTC, sotaoverride requested changes, later dismissed
think you just had the quotes missing for you workflow name..

2021-08-06 19:31 UTC, sotaoverride reviewed
there were a few annoying yaml syntax things - ran the gavi workflow validator. https://github.com/Opentrons/opentrons/blob/test-ghactions/.github/workflows/g-code-confirm.yaml

2021-08-06 19:54 UTC, sotaoverride commented on .github/workflows/g-code-confirm.yaml
> +name: G-Code-Confirm
take that back, apparently its valid to have to quote??

2021-08-06 20:20 UTC, sotaoverride commented on .github/workflows/g-code-confirm.yaml
> +  workflow_dispatch:
not sure how this works - did a quick read and makes me think it needs a webhook to start or something? maybe thats why this workflow isnt running when a push / pr happens ?https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event

2021-08-09 17:47 UTC, Laura-Danielle approved these changes
lgtm

2021-08-09 18:28 UTC, merged