refactor(robot-server): Refactor hardware wrapper
OpenTrons/opentrons-api pull request #8213
Opened 2021-08-09 19:30 UTC by SyntaxColoring

# Overview

# Changelog

# Review requests

# Risk assessment

2021-08-09 21:07 UTC, SyntaxColoring commented on robot-server/robot_server/app.py
> +from notify_server.settings import Settings as NotifyServerSettings
These imports feel clunky to me. Is there a better way to write this?

We need:

* `notify_server.clients.publisher.Publisher`
* `notify_server.clients.publisher.create()`
* `notify_server.settings.Settings`

2021-08-09 21:07 UTC, SyntaxColoring commented on robot-server/robot_server/app.py
>  )
In the next PR, these imports from `.service.dependencies` will all be removed. Request-level dependencies will depend on app startup and shutdown, rather than app startup and shutdown depending on request-level dependencies.

2021-08-09 21:07 UTC, SyntaxColoring commented on robot-server/robot_server/app.py
> +    app.state.hardware = slow_initializing.start_initializing(factory)
Creating an `app.state.hardware` attribute is a lazy stopgap until the next PR. It's bad because it's not typesafe (accesses to `app.state.hardware` will be typed as `Any`) and it doesn't really scale past more than one thing.

In the next PR, it's changing to be something like:


```python
@dataclass
class LifetimeDependencySet:
    hardware: ThreadManager
    motion_lock: ThreadedAsyncLock
    # ...

@app.on("startup")
def startup():
    # [Create hardware, motion_lock, etc.]
    # ...
    app.state.lifetime_dependencies = LifetimeDependencySet(
        hardware,
        motion_lock,
        # ...
    )
```

2021-08-09 21:07 UTC, SyntaxColoring commented on robot-server/robot_server/hardware_initialization.py
> +    _init_event_watchers(thread_manager, event_publisher)
This is technically a behavioral change!

Because of this line, this `initialize()` function will only return if initializing event watchers succeeds. So if initializing event watchers fails, you'll get a 500 error on any endpoint that `Depends` on hardware.

The old code did this in initialization:

https://github.com/Opentrons/opentrons/blob/8f297afbf2602312d488265b517755fbafacd333/robot-server/robot_server/hardware_wrapper.py#L42-L47

And implemented retrieval like this:

https://github.com/Opentrons/opentrons/blob/8f297afbf2602312d488265b517755fbafacd333/robot-server/robot_server/hardware_wrapper.py#L84-L86

Which meant the hardware could appear ready and successfully initialized even if `_init_event_watchers()` raised an exception.

2021-08-09 21:07 UTC, SyntaxColoring commented on robot-server/tests/test_slow_initializing.py
> +import unittest.mock
This uses `unittest.mock` for absolutely no good reason. I basically just wanted to see how it would turn out. I'm happy to port to Decoy if we think there's an advantage.

2021-08-09 21:07 UTC, SyntaxColoring commented on robot-server/tests/test_slow_initializing.py
> +    typing.cast(unittest.mock.Mock, exception_logger).assert_not_called()
Here's an attempt to use `typing.cast()` as a slightly more discerning alternative where we would otherwise use a big `# type: ignore` hammer.

2021-08-09 21:07 UTC, SyntaxColoring commented on robot-server/robot_server/slow_initializing.py
> +            # This affects what's printed in stack traces.
Is it weird for this comment to exist? `raise Foo() from None` feels obscure to me, but, what am I going to do, copy this comment every single place I do `raise Foo() from None`? (It's also used in this PR's rewrite of the `get_hardware()` dependency, and I don't comment on it there.)

2021-08-09 21:11 UTC, SyntaxColoring commented on robot-server/robot_server/service/dependencies.py
This diff got weird. I suggest viewing in split mode.

2021-08-09 21:38 UTC, SyntaxColoring commented on robot-server/robot_server/app.py
> +    factory = partial(hardware_initialization.initialize, _make_event_publisher())
This is what fixes the direct cause of #8023. It provides a real event publisher argument, whereas before, the hardware API initialization code was getting a default FastAPI `Depends` object.

2021-08-10 18:46 UTC, mcous reviewed
Haven't tested yet, but looks pretty good. Thoughts below in advance of pairing and review tomorrow

2021-08-10 18:46 UTC, mcous commented on robot-server/robot_server/slow_initializing.py
> +            # Deliberately not interfering with BaseExceptions because asyncio seems to
Still less than a year in on my Python adventure, but from what I have read, it's usually a bad idea to `except BaseException`, because [`BaseException` includes stuff](https://docs.python.org/3/library/exceptions.html#exception-hierarchy) like `GeneratorExit`, `KeyboardException`, etc.

If one should (practically) never catch `BaseException`, what does this comment mean?

2021-08-10 18:46 UTC, mcous commented on robot-server/tests/test_slow_initializing.py
> +    typing.cast(unittest.mock.Mock, exception_logger).assert_not_called()
I think typing might count as an advantage to using `decoy` here:

```py
from decoy import Decoy, matchers

# ...

async def test_progress_and_success(decoy: Decoy) -> None:  # noqa: D103
    # ...

    exception_logger = decoy.mock(func=slow_initializing.log)

    subject = slow_initializing.start_initializing(
        factory=factory, exception_logger=exception_logger
    )

    # ...

    decoy.verify(
        exception_logger(matchers.Anything()),
        times=0,
    )

async def test_exception_propagated(decoy: Decoy) -> None: # noqa: D103
    # ...

    decoy.verify(
        exception_logger(original_exception_1),
        times=1,
    )
```

2021-08-10 18:46 UTC, mcous commented on robot-server/robot_server/service/dependencies.py
> +from robot_server import app, constants, util, errors
Does this create a circular dependency somewhere? `app` depends on routers which depend on the dependency functions in this file

2021-08-10 18:46 UTC, mcous commented on robot-server/robot_server/slow_initializing.py
> +            # This affects what's printed in stack traces.
Is an exception raise the best move for us here? We're already calling the method `get_if_ready`, so if we take inspiration from `dict.get`, I think it would be appropriate for this method to return `Optional[_T]`. The interface is for getting an object that may take a while to initialize; I think `None` makes sense as a return value for "not ready yet".

(Exception still makes sense to me for "initialization failed")

2021-08-10 19:39 UTC, SyntaxColoring commented on robot-server/robot_server/slow_initializing.py
> +            # This affects what's printed in stack traces.
I had the same thought.

Points in favor of raising:

1. It matches the design of [`asyncio.Future.result()`](https://docs.python.org/3/library/asyncio-future.html#asyncio.Future.result).
2. In the edge case when `_T` is `None`, raising makes it easier for the API to distinguish between the "not ready yet" and "done" states. I think it *might sometimes* make sense for `_T` to be `None` when a dependency represents doing something, instead of providing something. Like how we have a dependency for checking version headers. Maybe initializing global logging objects should work like this? Maybe setting up notification subscriptions should work like this? I'm not sure yet.

Points in favor of returning `Optional[_T]`:

1. The typechecker will force callers to acknowledge, somehow, that the object might not be ready when they request it. They need to implement their own error handling instead of relying on propagating the exception from this method.

On balance, I end up softly preferring raising.

2021-08-10 19:45 UTC, SyntaxColoring commented on robot-server/robot_server/slow_initializing.py
> +            # Deliberately not interfering with BaseExceptions because asyncio seems to
I think you're right. This comment is overthinking it. A reasonably informed programmer wouldn't be tempted to change this from `Exception` to `BaseException` any more than they'd be tempted to change any other `try` / `except` block from `Exception` to `BaseException`. There's nothing special here.

I'll remove this comment and the matching one in the other method.

2021-08-10 19:48 UTC, SyntaxColoring commented on robot-server/robot_server/service/dependencies.py
> +from robot_server import app, constants, util, errors
Oh, that's interesting. It sure seems like it should. I wonder how I'm able to run unit tests and `make dev` without import errors, then?

2021-08-11 14:44 UTC, SyntaxColoring commented on robot-server/robot_server/app.py
> +    # we'll leak a socket.
~~This is getting fixed in the next PR.~~ This is fixed with subsequent commits in this PR.

2021-08-12 20:50 UTC, SyntaxColoring reviewed
Importing additional changes and unresolved comments from #8232.

2021-08-12 20:50 UTC, SyntaxColoring commented on robot-server/robot_server/__init__.py
> +from .app_setup import app
This rename avoids ambiguity in `from robot_server import app`. (Does that import the `app` FastAPI object, or the `app` module?)

2021-08-12 20:50 UTC, SyntaxColoring commented on robot-server/robot_server/app_setup.py
> +app.on_event("startup")(initialize_logging)
Comment from @mcous:

> This method is "discouraged" according to [the startlette docs](https://github.com/encode/starlette/blob/e45c5793611bfec606cd9c5d56887ddc67f77c38/starlette/applications.py#L114-L117):
> 
> > ```python
> > # The following usages are now discouraged in favour of configuration
> > #  during Starlette.__init__(...)
> > def on_event(self, event_type: str) -> typing.Callable:
> >     return self.router.on_event(event_type)
> > ```

2021-08-12 20:50 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +def _prepared_motion_lock() -> _CMFactory[ThreadedAsyncLock]:
Comment from @mcous:

> Could this also be typed as `typing.Iterator[_YieldT]`?

2021-08-12 20:50 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +    # symmetry with the other dependencies.
Comment from @mcous:

> This seems confusing to me. If it's not using the context manager, I think simply not using a context manager is easier than using one and adding a comment explaining why we're using a context manager that isn't needed

2021-08-12 20:50 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +def install_startup_shutdown_handlers(app: FastAPI) -> None:
Comments from @mcous:

> If avoidable, it would be nice to not have a function that mutates the value you pass in. Is there a way we can do this differently, maybe using the __init__ args of FastAPI and a get_app_state helper?


> I don't think this module should be responsible for installing these things on the `app`. I would try to model this after the `exception_handlers` module a little bit, where we export handlers (i.e. `handle_startup` and `handle_shutdown`).
> 
> This allows this module to be concerned with lifetime dependencies and the `setup_app` module to be concerned with setting up the app

2021-08-12 20:50 UTC, SyntaxColoring commented on robot-server/robot_server/service/dependencies.py
> +    return lifetime_dependency_set.motion_lock
Comment from @mcous:

> Little naming nitpick, but when scanning this almost reads like `set motion lock`. Can we drop `_set` from the name? e.g. `lifetime_deps` or `lifetime_dependencies`

2021-08-12 20:50 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +        await context_manager.__aexit__(None, None, None)
Comment from @mcous:

> This closure with decorators is making me feel a little icky

2021-08-12 20:50 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +    # whole `lifespan` context manager as one piece.
Comment from @mcous:

> If we have to split right now, should we be using a context manager? I'd rather have this be more explicit now (e.g. not using somewhat mysterious `__aenter__()` and `__aexit__(None, None, None)` methods) and refactor when we have actual CM support

2021-08-12 22:00 UTC, SyntaxColoring commented on robot-server/robot_server/app_setup.py
> +app.on_event("startup")(initialize_logging)
This is [FastAPI's `@on_event("startup")`](https://fastapi.tiangolo.com/advanced/events/), not Starlette's.

My understanding is:

* FastAPI's `on_event("startup")` has *historically* been basically a straight pass-through to Starlette's `on_event("startup")`.
* Starlette has been moving away from that API, and towards:
    * Accepting startup/shutdown handlers up-front, as arguments to `__init__()`.
    * Accepting a single `lifetime` context manager instead of split startup and shutdown functions.
* FastAPI, meanwhile, has not caught up to those Starlette changes. I think they're still trying to work out how FastAPI's automatic dependency resolution machinery would fit in. So, for now, this is what FastAPI gives us.

2021-08-12 22:11 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +def _prepared_motion_lock() -> _CMFactory[ThreadedAsyncLock]:
`typing.Iterator[_YieldT]` would pass our typechecking, but pedantically, I think `typing.Generator` is more correct.

`@contextlib.contextmanager` functions take the form:

```python
@contextlib.contextmanager
def foo():
    bar = make_bar()
    try:
        yield bar
    finally:
        release_bar(bar)
```

When the body  of a `with foo(): ...` block raises an exception, `foo()` will see the exception raised from its `yield bar` line.

The way this has to work is by `contextlib` [throwing the exception into `foo()`](https://github.com/python/cpython/blob/03648a2a91f9f1091cd21bd4cd6ca092ddb25640/Lib/contextlib.py#L153) via `foo.throw()`, which is [a magical method of generators](https://www.python.org/dev/peps/pep-0288/#specification-for-generator-exception-passing) (not iterators).

2021-08-12 22:17 UTC, SyntaxColoring commented on robot-server/robot_server/service/dependencies.py
> +    # todo: Handle exception
reminder to self

2021-08-12 22:17 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +# dependencies, and clean them up with their .remove_all() methods.
reminder to self

2021-08-12 22:17 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +        # todo(mm, 2021-08-04): Inherited from previous code. Why imported here?
reminder to self

2021-08-12 22:17 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +        # Need something like task groups.
reminder to self

2021-08-12 22:29 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +        event_publisher.close()
ℹ️ This `.close()` was omitted before this PR.

2021-08-12 22:29 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +            fully_initialized_result.clean_up()
ℹ️ This `.clean_up()` was omitted before this PR.

2021-08-12 22:29 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +        # For responsiveness on startup, this
⚠️ Complete sentence, much?

2021-08-13 14:25 UTC, SyntaxColoring commented on robot-server/robot_server/hardware_initialization.py
> +        publisher = "robot_server_event_publisher"
ℹ️ The `publisher` value changed because it was previously based on the name of the containing class, which no longer exists.

2021-08-13 14:26 UTC, SyntaxColoring commented on robot-server/robot_server/app.py
> +    app.state.hardware = slow_initializing.start_initializing(factory)
Moot point now that "the next PR" has been merged into this one.

2021-08-13 14:29 UTC, SyntaxColoring commented on robot-server/robot_server/app.py
>  )
Moot now that "the next PR" has been merged into this one.

2021-08-13 17:57 UTC, SyntaxColoring commented on robot-server/robot_server/service/dependencies.py
> +from robot_server import app, constants, util, errors
Still not sure why this ever worked for me, but the import loop is dealt with explicitly now.

2021-08-13 19:29 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +            await fully_initialized_result.on_shutdown()
ℹ️ This looks a little silly. On shutdown, if this background-initializing dependency is still outstanding, we patiently wait for it to finish initializing (or error out) so that we can...uh...immediately tear it back down.

This is a conservative choice. We could instead, for example, try to cancel the background task, to exit sooner. I opted not to do that because:

* I haven't looked into whether our lower-level code (like `opentrons.initialize()`) would gracefully handle cancellation.
* Cancellation is hard to get right, especially with raw `asyncio`, and it would take a bit of thought to make sure `SlowInitializing` interacts with it properly. I think `anyio` task groups could help, too, so I'd want to wait until we have them before attempting it.
* KISS.

2021-08-13 20:15 UTC, SyntaxColoring commented on robot-server/tests/conftest.py
>      return client
ℹ️ This is intended to retain current test behavior, but current test behavior turns out to be pretty confusing and I doubt it's really what we want.

In our non-integration tests:

* When a test hits an endpoint that depends on `get_hardware()`, it will get a **mock** hardware object.
* When a test hits an endpoint that depends on `get_motion_lock()`, it will get a **real** motion lock.
* When a test hits an endpoint that depends on `get_protocol_manager()`, it will get a **real** protocol manager.
* When a test hits an endpoint that depends on `get_protocol_manager()`, it will get a **real** protocol manager.
* When a test hits an endpoint that depends on `get_session_manager()`, it will get a **real** session manager.
    * Minor change: the real session manager will now reference the same motion lock and protocol manager returned by `get_motion_lock()` and `get_protocol_manager()`. Before, it used different instances.
* All other dependencies not specifically overridden will be **real.**

2021-08-13 20:57 UTC, SyntaxColoring commented on robot-server/robot_server/service/dependencies.py
> +        ) from None
ℹ️ This preserves existing behavior.

If you tried to open a WebSocket connection while the hardware was still coming up:

1. The RPC endpoint would depend on `get_rpc_server()`
2. `get_rpc_server()` would depend on `get_hardware()`
3. `get_hardware()` would raise `HTTP_503_SERVICE_UNAVAILABLE`, which wouldn't make sense in the context of a WebSocket connection, so I guess the connection would get closed with a generic error? I don't know. I haven't looked at it in WireShark or anything.

2021-08-13 21:02 UTC, SyntaxColoring commented on robot-server/tests/test_hardware_initialization.py
> +async def test_initialize_smoke(
I did my best to adapt the tests from the now-obsolete `test_hardware_wrapper.py`, but I'm not really sure what I'm doing. These tests feel okay to me, but it also doesn't feel like they cover a whole lot. I think I'm craving some kind of deeper integration test where we do something like inject a door event into the `ThreadManager` and see that it comes out the other end of the notify-server.

2021-08-13 22:50 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +  automatically getting cleaned up when the process ends.
ℹ️ This second guideline says, in other words: if a dependency needs to be *cleaned up when the server shuts down,* that dependency should be *created when the server starts up.* Lifetime dependencies are symmetrical.

This prompts a change for our `get_protocol_manager()`, `get_session_manager()`, and `get_rpc_server()` dependencies.

Formerly, we would lazy-initialize each one of those whenever the first request that needed it happened to come in.

https://github.com/Opentrons/opentrons/blob/4be5bc00b7db5958238e53ad7738af31a046fca0/robot-server/robot_server/service/dependencies.py#L79-L88

And then we would attempt to clean each one up during server shutdown.

https://github.com/Opentrons/opentrons/blob/4be5bc00b7db5958238e53ad7738af31a046fca0/robot-server/robot_server/app.py#L66-L74

(That shutdown code was buggy—see #8051.)

The motivation of changing this is simplicity, basically.

To fix the buggy shutdown code *and* keep lazy-initializing those dependencies, we'd have to do something like:

* Make a "slot" for each dependency.
* If/when a dependency is lazy-initialized, store it in its slot.
* During shutdown, inspect which slots are filled in, and call their cleanup handlers.
    * Being careful to do this in the correct order: higher-level dependencies cleaned up first, lower-level dependencies cleaned up last.

And this machinery didn't seem worthwhile. I think our former lazy initialization of `get_protocol_manager()`, `get_session_manager()`, and `get_rpc_server()` was just because FastAPI happened to make lazy initialization more convenient—it wasn't because we strongly felt that lazy-initialization was the better behavior—and that convenience disappears when we have to clean things up.

(For example, this has nothing to do with this PR, but I think we should consider eager-initializing `get_session_store()` and `get_engine_store()`.)

2021-08-14 00:20 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +    # whole `lifespan` context manager as one piece.
Yeah, the `__aenter__()` and `__aexit__()` calls look arcane. I think they look more intimidating than they actually are, but I appreciate the want to be rid of them.

I guess it depends on which part you're thinking of not being a context manager. Could you clarify?

I'm enthusiastic about using context managers as the working medium within this module.

For one thing, they're the natural mechanism for both ends of this module's contract. At one end, our individual dependencies are certainly best expressed as context managers. At the other end, FastAPI and Starlette are moving towards adopting context managers. So it seems good to stick with that ideal for as much as possible, and adapt our way out of it only at the exact point where we have to deal with a known library limitation.

But also, context managers are nice here because they *compose* really well when we nest them. (The `contextlib.AsyncExitStack` is just syntactic sugar for this, as if we had a deep nest of `with` statements.) A nest of context managers automatically gives us:

1. Correct FILO ordering
2. Correct cleanup of the partial stack if something fails before we get to the innermost level of nesting
3. Correct cleanup of everything even if an inner level raises an exception during its cleanup handler

Implementing all of this without context managers—for example, if we had a simple `on_startup()`/`on_shutdown()` function pair—would be error-prone. For example, [the `on_shutdown()` implementation before this PR](https://github.com/Opentrons/opentrons/blob/3fa59b1d00ff90bf16a1d6badb959780c9e76d2e/robot-server/robot_server/app.py#L66-L74) misses point (3).

But! If we specifically want to avoid the arcane-looking `__aenter__()` and `__aexit__()` calls, we could do something like this:

```python
def install_startup_shutdown_handlers(app: FastAPI) -> None:
    context_manager = _prepared_everything()
    exit_stack = contextlib.AsyncExitStack()

    @app.on_event("startup")
    async def on_startup() -> None:
        app.state.app_dependencies = await exit_stack.enter_async_context(context_manager)

    @app.on_event("shutdown")
    async def on_shutdown() -> None:
        await exit_stack.aclose()
```

I don't know about you, but this doesn't strike me as much better?

2021-08-14 00:24 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +        await context_manager.__aexit__(None, None, None)
This should go away when I address https://github.com/Opentrons/opentrons/pull/8213/files#r688071186. It'll be like `return on_startup, on_shutdown` instead.

2021-08-14 02:27 UTC, SyntaxColoring commented on api/src/opentrons/hardware_control/api.py
> +    def register_callback(self, cb):
If we want to keep this PR's changes confined to `robot-server`, I'm happy to revert this.

2021-08-14 07:35 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +"""Dependencies (in the FastAPI sense) that last for the lifetime of the server.
Maybe this should be a submodule of `util`?

2021-08-16 17:41 UTC, sanni-t commented on robot-server/robot_server/lifetime_dependencies.py
> +        await thread_manager.get_when_ready(),
This needs to return a slow initializing session manager

2021-08-16 17:58 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +        try:
This nested `try` might be hard to understand, and its duplication across all these context managers is a red flag. Centralize this logic under `SlowInitializing`, maybe.

2021-08-16 17:59 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +async def _prepared_everything() -> _ACMFactory["LifetimeDependencySet"]:
Even though this is an internal function, a docstring would probably help here.

2021-08-16 18:05 UTC, SyntaxColoring commented on robot-server/robot_server/lifetime_dependencies.py
> +        try:
Or:

```python
finally:
    with contextlib.suppress(InitializationFailedError):
        fully_initialized_result = slow_initializing.get_when_ready()
        await fully_initialized_result.on_shutdown()
```

Or:

Just not suppress the `InitializationFailedError`. Let it propagate?

2021-08-18 06:37 UTC, SyntaxColoring commented on api/src/opentrons/hardware_control/api.py
> +    def register_callback(self, cb):
Reverting this.

2021-08-19 16:29 UTC, mcous requested changes
Sorry this has taken so long with travels, but I've been thinking about this a lot so wanted to get this review in. We definitely need to chat about this in person to resolve I think or this will take forever 🙃 

On the whole, I worry this PR does too much and adds a lot of hard to read / follow code to solve problems that aren't quite the problems we're actually experiencing.

Acceptance criteria that I see:

- [ ] Make sure hardware (and probably the RPC server, which also spins up threads) are initialized properly
- [ ] Make sure child threads are shut down at app shutdown, mostly for to make sure our test suite keeps working until we can address our mocking / lack of mocking problems in tests

I think `ProtocolManager` and `SessionManager` cleanups are red-herrings and are mostly - if not entirely - unnecessary. They are not production facing, and arguable not necessary at all (even the file cleanup done by ProtocolManager, because the files are placed in a temporary directory) 

Focusing on our acceptance criteria of "make sure hardware stuff can spin up in the background", I think we should take the following simplification steps:

- An individual dependency can declare its own cleanup handlers or register them with a cleanup system rather than centralizing all lifetime dependencies into one place
- We lean into process termination as cleanup, as it's the strategy we use in both dev and production
    - For further reading, I've been very influenced in this regard by the philosohpy of [let it crash](https://verraes.net/2014/12/erlang-let-it-crash/) and [crash-only software](https://en.wikipedia.org/wiki/Crash-only_software)

2021-08-19 16:29 UTC, mcous commented on robot-server/robot_server/app_setup.py
> +app.on_event("startup")(initialize_logging)
> This is FastAPI's @on_event("startup"), not Starlette's.

From [reading the source](https://github.com/tiangolo/fastapi/blob/master/fastapi/applications.py), **FastAPI does not define `on_event`**; it's definitely a straight pass-through because the `FastAPI` class inherits from `Starlette`.

I think using the `__init__` methods (which FastAPI also accepts) is the best available move. If we must use `@app.on_event` (which may turn out to be the case depending on how badly we want the `app.state` dictionary in there), I think all of them should be defined in the top-level `app.py`

2021-08-19 16:29 UTC, mcous commented on robot-server/robot_server/app_setup.py
> +lifetime_dependencies.install_startup_shutdown_handlers(app)
Passing `app` as an argument to a function that's going to mutate `app` is a warning sign to me. From what I can tell, `lifetime_dependencies` requires two things in the current PR:

1. `app`, to mutate the startup and shutdown handlers
2. `app.state`, to attach persistent data

I think (1) should be removed in favor of the app setup being in charge of attached handlers exposed by the `lifetime_dependencies` module, and any other methods should operate on a `State` object rather than a `FastAPI` app

2021-08-19 16:29 UTC, mcous commented on robot-server/robot_server/lifetime_dependencies.py
> +"""Dependencies (in the FastAPI sense) that last for the lifetime of the server.
I personally dislike `util` as a module name / concept. I prefer where this sits right now

2021-08-19 16:29 UTC, mcous commented on robot-server/robot_server/lifetime_dependencies.py
> +  automatically getting cleaned up when the process ends.
Pulling from the "Details" section:

> Note that because we support hot reloading, we do need to explicitly clean up most resources; we can't rely on things automatically getting cleaned up when the process ends.

I pulled this quote out because it feels to me like a lot of this PR comes out of this assumption, but I don't see how it can be true. Uvicorn runs the server in a subprocess and [terminates the process on reload](https://github.com/encode/uvicorn/blob/19edcb3defead5d5d45eec748c48349b04832293/uvicorn/supervisors/basereload.py). This makes sense, because there's no other way to reliably reload Python files.

This, to me says **we can absolutely rely on process termination for cleanup**. If we can rely on process termination, how much of this PR is necessary? I think cleanup may be important for our tests, but that's a test problem, not an application problem

2021-08-19 16:29 UTC, mcous commented on robot-server/robot_server/app_setup.py
> +__all__ = ["app"]
These `__all__` variables in internal, non-init files feel a little redundant to me

2021-08-19 16:29 UTC, mcous commented on robot-server/robot_server/app_setup.py
> -    (await get_hardware_wrapper()).async_initialize()
Ignoring the fact that it was broken, I dislike this removal. If I'm trying to establish context while reading this server code, the question "how is the hardware connection created?" is really important, and when we put it here, in the app-level startup handler, the pathway to find that answer is really obvious

2021-08-19 16:29 UTC, mcous commented on robot-server/robot_server/hardware_initialization.py
> +"""Utilities for initializing the hardware interface."""
"Utilities" is always a bit of a warning sign for me. Something you need utilities, but if we have a hardware connection we need to initialize and hand out as a dependency, shouldn't those all be in the same place?

Is there a way we can restructure this PR to have `robot_server/hardware.py` be the thing that actually exports a startup / shutdown handler for the hardware along with the `get_hardware` dependency function? I'm imagining a system where any given dependency is able to use classes / functions in `lifetime_dependencies` to declare themselves a lifetime dependency.

For example, if this module was to export 2 or 3 methods, I think everything would be a lot easier to follow:

1. `def initialize_hardware(app_state: State) -> None`
    - Creates a backround task to initialize a ThreadManager
    - Uses `slow_initializing` and/or `lifetime_dependencies` to attach it to app state
    - (Maybe) registers cleanup with `lifetime_dependencies`
2. `def get_hardware(app_state: State) -> ThreadManager`
    - Retrieve the slow initializing hardware
    - Raise if not initialized
3. (Maybe) `def shutdown_hardware(app_state: State) -> None`
    - Shut down the hardware
    - The necessity of this would depend on if `lifetime_dependencies` centralized cleanup or not

2021-09-20 19:54 UTC, SyntaxColoring commented
We're deeming this not worth the complexity given that  #8278 solves #8023. #8051 is still a problem, but we think we'll just live with it and wait for FastAPI to give us a first-party solution instead of trying to DIY it ourselves.

I need to go through this diff and see if there are any other little fixes worth pulling out, but then we can close this PR.

2021-10-21 22:13 UTC, closed without merging