feat(app): add module setup step to protocol setup
OpenTrons/opentrons-api pull request #8224
Opened 2021-08-10 17:34 UTC by jerader

# Overview

This adds module setup steps, closes #8221 

# Changelog

- add module setup steps to protocol setup

# Review requests

-See ticket #8221
-I added multiple_module_help_example.png to assets. Not sure if this is the correct place for it to be.
-I already completed a few things in the module setup epic #7664 including: 1) creating the MultipleModulesModal and 2) setting up the Proceed to Labware button
-Had to move getLabwareRenderCoords and getModuleRenderCoords to utils in Protocol Setup so it could be accessed by ModuleSetup

# Risk assessment

low, behind FF

2021-08-11 20:45 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/ModuleSetup/index.tsx
> +        <Link
This link should only be rendered if the loaded protocol contains two modules of the same type, otherwise it should not be present.

2021-08-11 21:16 UTC, b-cooper reviewed
The logic is looking really good in here 🌸 

I've dropped a smattering of conventions and code style comments. Once those are addressed this should be ready to merge.

2021-08-11 21:16 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/ModuleSetup/ModuleInfo.tsx
> +            &nbsp; Not Connected
This string and other copy in this component should be added as translations to the `protocol_setup.json` i18next translation file. The `&nbsp;` is also best replaced with a bit of `marginRight` on the `Icon` above. (e.g. 
```
<Icon
  name="alert-circle"
  marginRight={SPACING_1}
  ...
```
)

2021-08-11 21:16 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/ModuleSetup/ModuleInfo.tsx
> +            height="10px"
For custom size values that aren't importable the `layout.ts` `SIZE_n` constants, our convention is to use `rem` as units in place of `px`. So `height` and  `width` should be `0.625rem` here.

2021-08-11 21:16 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/ModuleSetup/ModuleInfo.tsx
> +          <Text font_family={'Open Sans'} fontSize={'0.45rem'}>
The font sizes we use across our UI's are stored in semantic constants in a file called `components/src/styles/typography.ts`. The three sizes of text in the figma design for this component are 14pt, 12pt, and 10pt  . These three sizes translate to our constants name `FONT_SIZE_BODY_2`, `FONT_SiZE_BODY_1` and `FONT_SIZE_CAPTION` respectively.

Commonly, our designs group a number of typography specific styles together, so we often use a few utility constants that combine `fontSize`, `fontWeight` and `color` for consistency and ease of use. These are `FONT_BODY_2_DARK`, `FONT_HEADER_DARK` etc.

Following these principles, the three `Text` tags have all of their style props replaced like so:

```
<Text {...FONT_BODY_1_DARK}>
...
<Text {...FONT_BODY_2_DARK} fontWeight={FONT_WEIGHT_SEMIBOLD}>
...
<Text fontSize={FONT_SIZE_CAPTION} fontStyle={FONT_STYLE_ITALIC} color={C_DARK_GRAY}>
...
```

2021-08-11 21:16 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/ModuleSetup/MultipleModulesModal.tsx
> +            <Trans
I believe that the `Trans` component does not need to be used here. The `Trans` component should be used when we need to interpolate mark up or variables within a single translation.  Because this translation makes up an entire block of text with no variables and no markup to interpolate, we can use the standard `t` function. Furthermore, we should remove `<block>` tags from the translation as they add no meaning.

 It can be replaced with ```
<Text 
    fontSize={FONT_SIZE_BODY_1}
    fontWeight={FONT_WEIGHT_REGULAR}>
  {t('multiple_modules_example')}
</Text>    
```

2021-08-11 21:16 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/ModuleSetup/MultipleModulesModal.tsx
> +          <Flex>
Does this `<img />` tag need to be wrapped in a `<Flex>` or is this extraneous?

2021-08-11 21:16 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/ModuleSetup/index.tsx
> +          viewBox={`-64 -10 ${530} ${456}`}
this `viewBox` value should be a simple string (no back-ticks for interpolation) stored in a constant at the top of this file e.g.
```
const DECK_VIEW_BOX = '-64 -10 530 456'
```

2021-08-12 13:07 UTC, jerader commented on app/src/organisms/ProtocolSetup/ModuleSetup/ModuleInfo.tsx
> +          <Text font_family={'Open Sans'} fontSize={'0.45rem'}>
when I use `FONT_SIZE_BODY_1`, `FONT_SIZE_BODY_2`, and `FONT_SIZE_CAPTION`, the fonts are super big 😬  (so big that the icon doesn't fit) 
 
<img width="781" alt="Screen Shot 2021-08-12 at 09 05 31" src="https://user-images.githubusercontent.com/66035149/129201786-fdbf35e0-c75b-4989-8252-2eda8351b868.png">

2021-08-12 13:08 UTC, jerader commented on app/src/organisms/ProtocolSetup/ModuleSetup/index.tsx
> +        <Link
That is something I was going to implement with the last ticket for module setup and didn't realize it was part of this ticket?

2021-08-12 13:39 UTC, jerader commented on app/src/organisms/ProtocolSetup/ModuleSetup/MultipleModulesModal.tsx
> +          <Flex>
oh ya, it's definitely extraneous. Thanks!

2021-08-12 14:16 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/ModuleSetup/index.tsx
> +        <Link
Ok that's totally fine. In cases like this, when I'm implementing part of a visual without all of it's functionality, I'll often add a `//TODO: IMMEDIATELY` comment to myself (and others) as a reminder that this functionality is incomplete.

2021-08-12 14:33 UTC, shlokamin requested changes
lookin good, great work jethary! left some comments. also, the text in the multiple modules help modal is a bit small, is that intentional?

2021-08-12 14:33 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/index.tsx
> +import { CoordinatesByLabwareId } from '../utils/getLabwareRenderCoords'
how come you removed the `type` prefix here? when possible it's nice to keep it mainly because it conveys intention but it also also only loads in types at build time (which means there are no remnants at runtime so it's a bit more performant ) which is cool. but yeah i mainly like it cuz it just clearly conveys what's going on (`CoordinatesByModuleModel ` is a type rather than a component)

2021-08-12 14:33 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/index.tsx
> -const DECK_MAP_VIEWBOX = '-64 -100 650 550'
how come you removed this const?

2021-08-12 14:33 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/index.tsx
> +                      </svg>
how come you added this svg tag? is it necessary?

2021-08-12 14:33 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/index.tsx
> -const DECK_MAP_VIEWBOX = '-64 -100 650 550'
also the actual viewbox is different, was this change in scope of this ticket?

2021-08-12 14:33 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/ModuleSetup/__tests__/ModuleSetup.test.tsx
> +    LabwareRender: jest.fn(() => <div>mock LabwareRender</div>),
since you're not using `LabwareRender` in `ModuleSetup` you don't need to mock it do you?

2021-08-12 14:33 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/ModuleSetup/__tests__/ModuleSetup.test.tsx
> +  )
this is really my fault for not putting these in a shared testing util, note to self (me) to do that

2021-08-12 14:33 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/index.tsx
> -const DECK_MAP_VIEWBOX = '-64 -100 650 550'
the deckmap in both module setup and labware setup is much larger, i know @emilywools had asked me to make it smaller in the labware setup ticket. if we want them to be bigger can we capture that somewhere just so the ACs are clear?

2021-08-12 14:33 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/ModuleSetup/styles.css
> +}
looks like this is exactly the same as `LabwareSetup/styles.css`, do we need both of these?

2021-08-12 15:59 UTC, jerader commented on app/src/organisms/ProtocolSetup/LabwareSetup/index.tsx
> -const DECK_MAP_VIEWBOX = '-64 -100 650 550'
I actually don't know why i removed it. I added it back. What is the bigger size we want? @emilywools

2021-08-12 16:10 UTC, jerader commented on app/src/organisms/ProtocolSetup/ModuleSetup/__tests__/ModuleSetup.test.tsx
> +    LabwareRender: jest.fn(() => <div>mock LabwareRender</div>),
ah good catch. I probably copied and pasted your test initially and forgot to delete that part.

2021-08-12 16:16 UTC, jerader commented on app/src/organisms/ProtocolSetup/ModuleSetup/styles.css
> +}
nope we don't need 2. I'll move one to the ProtocolSetup folder

2021-08-12 16:25 UTC, jerader commented on app/src/organisms/ProtocolSetup/LabwareSetup/index.tsx
> +                      </svg>
I get a warning without it when running the test file. 

This is the warning:
`Warning: The tag <g> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
        in g (created by mockConstructor)
        in div (created by mockConstructor)
        in mockConstructor (created by LabwareSetup)
        in div (created by styled.div)
        in styled.div (created by LabwareSetup)
        in LabwareSetup
        in Router (created by StaticRouter)
        in StaticRouter
        in Provider (created by ProviderWrapper)
        in I18nextProvider (created by ProviderWrapper)
        in ProviderWrapper`

2021-08-12 17:36 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/index.tsx
> +                      </svg>
yeah the test is complaining because it doesnt have a parent component that renders an svg, but in practice `RobotWorkSpace` will render the svg for us.

so to get around that, you can just wrap your the tested component in an svg like this https://github.com/Opentrons/opentrons/blob/618161c74e582845d5907e9368c199396486ed6f/app/src/organisms/ProtocolSetup/LabwareSetup/__tests__/LabwareInfoOverlay.test.tsx#L22

2021-08-13 14:21 UTC, shlokamin commented
looks like we've still got merge conflicts — did you push the changes from the rebase we did yesterday?

2021-08-16 15:23 UTC, shlokamin reviewed
looks good jethary! left a few comments, and I also noticed the `Proceed to Labware Setup` button is pretty close to the deckmap. in figma it looks like theres a little more space in between the two, ill defer to @emilywools for that though!

2021-08-16 15:23 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/index.tsx
> +                      </svg>
looks like the extra `svg` tag is still there

2021-08-16 15:23 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/ModuleSetup/MultipleModulesModal.tsx
> +const HOW_TO_MULTIPLE_MODULES_HREF = '#' // TODO IMMEDIATELY: get the actual link
@b-cooper @emilywools we should take note of the links we gotta come back and add once we're ready to ship

2021-08-16 15:23 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/ModuleSetup/__tests__/ModuleSetup.test.tsx
> +  )
note to self, after https://github.com/Opentrons/opentrons/pull/8238 gets merged come back and import these from shared utils

2021-08-16 15:23 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/ModuleSetup/styles.css
> +}
looks like this copy still exists. overflow-y should also be `auto`, not `scroll`. `scroll` will always show the scroll bar, while auto only shows it when the window is too small (i just learned this last week)

2021-08-16 15:23 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/__tests__/RunSetupCard.test.tsx
>    it('renders robot calibration, modules, and labware setup if some modules in protocol', () => {
not introduced by this PR, but this test never actually checked for anything related to robot calibration — we should probably remove `robot calibration` from the test name.

also, now that im reading this again, what this test is really doing is making sure module setup gets rendered correctly (with the right props), and then asserts that the callback we pass into `ModuleSetup` renders `Labware Setup`

Maybe we can change the test name to `it('renders module setup, and allows the user to proceed to labware setup`) or something. I think this would convey intention a little more clearly

2021-08-16 16:18 UTC, emilywools commented
hey there! The multiple modules help modal should only display if there there are multiple of the same module. its definitely in the right spot for when those conditions exist, though. the "learn more" link in the modal can go to this link: https://support.opentrons.com/en/articles/5167312-using-modules-of-the-same-type-on-the-ot-2

2021-08-16 21:02 UTC, shlokamin reviewed
looks like as @emilywools pointed out the multiples of module link is showing up even if there are no multiples of a module. looks like the ticket says `If multiple modules are called for, a "Multiple Modules Help" callout linking to a help modal will appear on the right side of the step, along with some additional copy in the description`

2021-08-16 21:02 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/index.tsx
> +                      </g>
i dont think we need this `g` tag, it's not doing anything. i dont think there should actually be any changes at all in `LabwareSetup` besides the import changes.

2021-08-16 21:02 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/index.tsx
> +        <Text color={C_DARK_GRAY} margin={`${SPACING_4} ${SPACING_6}`}>
are these margin changes in `LabwareSetup` intentional? i dont think they should have been changed right?

2021-08-16 21:02 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/index.tsx
> -            color={C_BLUE}
@emilywools wanted the color of this button to be blue, was removing this intentional?

2021-08-16 21:02 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/index.tsx
> -            backgroundColor={C_BLUE}
same thing here button re:color

2021-08-17 18:42 UTC, shlokamin approved these changes
left a few comments but code looks good to me! i'll defer to @b-cooper and @emilywools for design feedback. i know we're still waiting for the updated module renders and what not, but i assume we'll add that stuff in later

great work jethary!!

2021-08-17 18:42 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/__tests__/LabwareSetup.test.tsx
> +        </svg>
my bad for not making these `svg` tags, thank you for fixing this!

2021-08-17 18:42 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwareSetup/index.tsx
> +        <Text color={C_DARK_GRAY} margin={`${SPACING_6} ${SPACING_3}`}>
is there a reason we changed this from using `marginX` and `marginY`? these should be the same but i kinda like the `marginX` `marginY` syntax instead cuz it conveys intention clearly

2021-08-17 20:11 UTC, emilywools commented
hey @jerader 

1. can you make the cursor a finger instead of a vertical line/ibeam thing?

2. would we be able to have this copy be dynamic based on there being 1 vs more than 1 module? so if there's one module it says
> Plug in and power up the required module via the OT-2 USB Port. Place the module(s) as shown in the deck map.

if there are more than 1 module, it says
> Plug in and power up the required module(s) via the OT-2 USB Port(s). Place the module(s) as shown in the deck map.

2021-08-18 15:47 UTC, jerader commented
> 2. would we be able to have this copy be dynamic based on there being 1 vs more than 1 module? so if there's one module it says
> 
> > Plug in and power up the required module via the OT-2 USB Port. Place the module(s) as shown in the deck map.
> 
> if there are more than 1 module, it says
> 
> > Plug in and power up the required module(s) via the OT-2 USB Port(s). Place the module(s) as shown in the deck map.

This part of @emilywools comment will be addressed in the upcoming ticket.

2021-08-18 18:34 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/ModuleSetup/index.tsx
> +        <Btn //    TODO IMMEDIATELY: make button show up only when MoaM is attached
No update necessary, but just to be clear, it shouldn't be conditionally shown whether or not MoaM are attached to the robot, but rather when MoaM are specified in the protocol.

2021-08-18 18:35 UTC, b-cooper approved these changes
looks good 🪶 !

2021-08-18 19:10 UTC, merged