fix(api): drop tip after cancel
OpenTrons/opentrons-api pull request #8229
Opened 2021-08-11 01:04 UTC by sanni-t

Closes #7466
Closes #3738
Closes #5428

# Overview

This PR adds a functionality that if a protocol is cancelled mid-run and the pipette has a tip attached when the cancel is initiated, then the robot will empty the tip & drop the it in the pipette's trash container before homing the plungers.

This is achieved in the following way:

Right after a cancel is issued:
1. pipette state is stored to determine whether it has a tip (and to save the last known plunger location but I’m not using that right now)
2. Cancel is fully executed with `home_after=False`. Hardware controller state is reset.
3. A protocol context is created with the reset hardware controller.
4. Instruments saved during simulation are loaded.
5. Pipettes homed in XYZA.
6. Tip added to the pipettes using `hardware.add_tip()` (only the ones that previously had tips when cancelled).
7. `pipette.drop_tip()` drops the tip in pipette’s trash container.

# Changelog

- Added the above logic to `api/session.py`
- Modified the `protocol_context.home()` & its corresponding implementation functions to accept a `home_plunger` boolean parameter

# Review requests

1. This can perform a drop tip without homing the plungers because it seems like the smoothie actually retains the plunger position values even after the hard halt & reset. Does this look like a risky move? We can alternatively have the hw_controller read plunger position from the saved state instead of from the smoothie.
2. Do you see any consequences of creating a protocol context like this after a hardware reset? Am I putting the hardware controller in some weird state?
3. If you can, test this on a robot. Try to break the logic.

There is one case I know for sure where this doesn't work: if the protocol is cancelled exactly in the middle of a tip pick_up, i.e., when the pipette end has pushed against the tip but not retracted yet, the pipette states will reset before its `has_tip` value is updated. In this case, the tip will stay on the pipette and plungers will home without dropping the tip. But there won't be any risk of pipette contamination so I think it's okay.

# Risk assessment

High. Affects all cancellations.

2021-08-11 13:52 UTC, Laura-Danielle commented
The thing that is a bit yucky about this implementation (and the reason I was trying to find a solution in one of the lower levels -- like hardware controller) is that we are going to be ripping out RPC so we would need to reimplement drop tip after cancel again.

The other thing that should either be resolved in this PR or a follow up is that there is a copy change to the cancel text in #3738.

2021-08-11 21:03 UTC, SyntaxColoring requested changes
This makes sense to me, but:

* I'm unfamiliar with RPC and its potential traps.
* From prior team conversations, I'm not confident I understand the differences between `SynchronousAdapter.home()`, `SynchronousAdapter.halt()`, etc. (we said some of the docstrings are wrong, or something?)

So someone who's more familiar with those things should confirm.

Also: how will we make sure that this keeps operating as intended in releases going forward? It looks hard to integration-test. Can we add it to our manual release testing checklist?

2021-08-11 21:03 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api/protocol_context.py
> +    def home(self, home_plungers: bool = True):
Requesting changes for this: we'll need to be careful here since this is the public Python Protocol API.

Some options:

* Accept `home_plungers` as a new part of the public Python Protocol API. Publicly document it, and guard it behind an `apiLevel` check. A user on `apiLevel: "2.0"` should be able to call `.home()` but shouldn't be able to call `.home(home_plungers=False)`, for example. And we might consider making this a [keyword-only argument](https://www.python.org/dev/peps/pep-3102/).
    * I'm skeptical of this option because it seems like the public Python Protocol API already gives users a way to do this? See the next bullet point.
* ~~Use the existing `InstrumentContext.home_plunger()` method instead of adding a `home_plungers` parameter to `ProtocolContext.home()`.~~
* Rename this `home_plungers` parameter to `_home_plungers`, and publicly document it as being unstable and for internal use only.
* Find a way to exclude this `home_plungers` parameter from the public docs.
* Find a way to not call through the public Python Protocol API.

2021-08-11 21:03 UTC, SyntaxColoring commented on api/src/opentrons/protocols/context/protocol_api/protocol_context.py
> +            self._hw_manager.hardware.home()
This is a nitpick and I don't know if anyone else agrees, so feel free to ignore this suggestion, but I usually find double-negative `else` statements harder to read. Would this be clearer like this?

```suggestion
        if home_plungers:
            self._hw_manager.hardware.home()
        else:
            self._hw_manager.hardware.home([Axis.X, Axis.Y, Axis.Z, Axis.A])
```

2021-08-12 15:26 UTC, sanni-t commented on api/src/opentrons/protocol_api/protocol_context.py
> +    def home(self, home_plungers: bool = True):
Good point. I like the first (api_level guard) and last (maybe create a different, private method) options. 

> Use the existing InstrumentContext.home_plunger() method instead of adding a home_plungers parameter to ProtocolContext.home()

But we *don't* want to home plungers when performing a `ctx.home()` in this PR..

> Rename this home_plungers parameter to _home_plungers, and publicly document it as being unstable and for internal use only.

I think creating a different, private method might be a better option.

2021-08-12 15:38 UTC, sanni-t commented
> The thing that is a bit yucky about this implementation (and the reason I was trying to find a solution in one of the lower levels -- like hardware controller) is that we are going to be ripping out RPC so we would need to reimplement drop tip after cancel again.

I actually find implementing this in hardware controller to not be the right approach. I think we want the hardware controller to perform the most granular tasks. Dropping tip on cancel is a compound task and best implemented by the entity that controls the flow of a protocol. You are right that this will need to be mimicked for cancellation via http/protocol-engine but we should be able to do that easily since this logic uses mostly public methods that aren't going to change. That's a good point though, I'll see if I can implement this in the protocol engine or create a ticket to do that so we don't forget.

> The other thing that should either be resolved in this PR or a follow up is that there is a copy change to the cancel text in #3738.

I knew I was forgetting something! Thanks

2021-08-12 16:50 UTC, mcous reviewed
Haven't tested this on hardware yet, but I think there might be a way to simplify this / avoid constructing a new `ProtocolContext`. See comments below

2021-08-12 16:50 UTC, mcous commented on api/src/opentrons/api/session.py
> +        ctx.home(home_plungers=False)
Could this also be `self._hardware.home(axes=Axis.gantry_axes())`?

2021-08-12 16:50 UTC, mcous commented on api/src/opentrons/api/session.py
> +                self._hw_iface().add_tip(
`self._hw_iface()` just really confused me. If we replaced it everywhere with `self._hardware` in this PR (because that's all it does) I would not be mad...

2021-08-12 16:50 UTC, mcous commented on api/src/opentrons/api/session.py
> +            'plunger_state': {
I'd say remove this if we're not using it. It adds a fair amount to this method that makes it harder to read

2021-08-12 16:50 UTC, mcous commented on api/src/opentrons/api/session.py
> +            'has_tip': {mount: pip['has_tip'] for mount, pip in instruments.items()},
Should we save `tip_length` instead and use that when we call `add_tip` later rather than trying to grab it from the tiprack?

2021-08-12 16:50 UTC, mcous commented on api/src/opentrons/api/session.py
> +    def _drop_tip_after_cancel(self, saved_pipette_state: Dict) -> None:
We should create a dataclass or `typing.NamedTuple` rather than using a bare dict for readablity

2021-08-12 16:50 UTC, mcous commented on api/src/opentrons/api/session.py
> +        ctx = self._get_context_with_loaded_instruments()
This is a little icky, but we _may_ still have access to the pipette contexts without creating a new one via the `self._instruments` attribute. This is a `List[Instrument]` where `Instrument` has an `_instrument` property that should be an `InstrumentContext`.

If it's still valid when `_drop_tip_after_cancel` is called, I wonder if something like this would work (see earlier comment about a `SavedPipetteState` dataclass that we can put helper methods on):

```py
    def _drop_tip_after_cancel(prev_pipette_state: SavedPipetteState) -> None:
        self._hardware.home(axes=Axis.gantry_axes())

        for instrument_wrapper in self._instruments:
            mount = instrument.mount
            pipette_ctx = instrument_wrapper._instrument            
            tip_length = prev_pipette_state.get_tip_length(mount):
            
            if tip_length is not None:
                self._hardware.add_tip(mount=mount, tip_length=tip_length)
                pipette_ctx.drop_tip()
```

2021-08-12 16:50 UTC, mcous commented on api/src/opentrons/protocol_api/protocol_context.py
> +    def home(self, home_plungers: bool = True):
I don't think we need this. We can just go to `self._hardware` directly in `session.py`:

```py
self._hardware.home(axes=Axis.gantry_axes())
```

2021-08-12 17:55 UTC, mcous commented on api/src/opentrons/api/session.py
> +        ctx = self._get_context_with_loaded_instruments()
Thinking about this a little further, this may require use of `temp_connect`, depending on details of how `self._instrument` is populated that I just don't remember.

```py
for instrument_wrapper in self._instruments:
    mount = instrument.mount
    protocol_ctx = instrument_wrapper._context    
    tip_length = prev_pipette_state.get_tip_length(mount):
        
    if tip_length is not None:
        self._hardware.add_tip(mount=mount, tip_length=tip_length)
        with protocol_ctx.temp_connect(self._hardware):
            instrument_wrapper._instrument.drop_tip()
```

2021-08-12 18:10 UTC, sanni-t commented on api/src/opentrons/api/session.py
> +        ctx.home(home_plungers=False)
I have tried that but in order to use the protocol context, the context's `home()` need to be used as it updates/initializes some other things like last accessed location inside this `home()`.

2021-08-12 18:12 UTC, sanni-t commented on api/src/opentrons/api/session.py
> +            'has_tip': {mount: pip['has_tip'] for mount, pip in instruments.items()},
Good point!

2021-08-12 18:28 UTC, sanni-t commented on api/src/opentrons/api/session.py
> +        ctx = self._get_context_with_loaded_instruments()
I am pretty sure the contexts stored in `self._instruments` use an InstrumentContextSimulation so we won't be able to actually perform a drop tip. All the session properties cache simulated objects. The run method creates a separate, local context that uses real implementations. So they get trashed once the control leaves the run method.
But I know some of this makes my head hurt so maybe I'm misunderstanding something?

2021-08-12 18:59 UTC, mcous commented on api/src/opentrons/api/session.py
> +        ctx.home(home_plungers=False)
Does that matter to us? If so, could we use the already public `location_cache` setting for that?

```py
ctx.location_cache = None
```

2021-08-12 19:01 UTC, mcous commented on api/src/opentrons/api/session.py
> +        ctx = self._get_context_with_loaded_instruments()
> I am pretty sure the contexts stored in self._instruments use an InstrumentContextSimulation so we won't be able to actually perform a drop tip. All the session properties cache simulated objects

Ah if that's the case, does the `temp_connect` solution I posted above work? The whole job of `temp_connect` is to connect a simulated context to real hardware

2021-08-12 19:33 UTC, sanni-t commented on api/src/opentrons/api/session.py
> +        ctx = self._get_context_with_loaded_instruments()
Oh! Hmm.. that might work. I'll try that

2021-08-25 22:32 UTC, sanni-t commented
Updated PR description to reflect changed approach from feedback

2021-08-26 02:03 UTC, SyntaxColoring reviewed
Code mostly makes sense to me. About to smoke-test on a robot.

2021-08-26 02:03 UTC, SyntaxColoring commented on api/src/opentrons/api/session.py
> +              then we will have change this logic.
My understanding is that there's also a second potential problem. Calling `self._hardware.halt()` does not stop the motors gracefully at an electromagnetic/electromechanical level. If the plunger motor was moving at the time, it could skip. So, even if the motor controller board's memory of the plunger's current location isn't wiped out, it could be slightly wrong.

I don't really understand any of this, though. I'm mostly regurgitating from https://opentrons.slack.com/archives/C021013589M/p1626972320027200?thread_ts=1626972207.027100&cid=C021013589M. So I could be wrong.

And we don't think this matters, functionally. It's just something to mention in the note.

2021-08-26 02:03 UTC, SyntaxColoring commented on api/src/opentrons/api/session.py
> +        saved_tip_length = {mount: pip['tip_length']
I don't know if I'm looking at the right type, but should we use [`pip['has_tip']`](https://github.com/Opentrons/opentrons/blob/83a8d34c731bf376e977892cc7f22c5f3ae3ec00/api/src/opentrons/hardware_control/pipette.py#L56) instead?

2021-08-26 02:03 UTC, SyntaxColoring commented on api/src/opentrons/protocols/context/protocol_api/protocol_context.py
> +        self._hw_manager.hardware.home([Axis.X, Axis.Y, Axis.Z, Axis.A])
Is this change left over from a previous revision?

2021-08-26 02:03 UTC, SyntaxColoring commented on api/src/opentrons/hardware_control/api.py
> +            result['tip_length'] = instr.current_tip_length
I don't really understand what's going on this function, but what's the story with this addition? `tip_length` appears to be a required key in `PipetteDict`. Did typechecking just never catch this omission, and we got lucky that it never caused any problems?

2021-08-26 02:59 UTC, SyntaxColoring commented
From `journalctl --follow`:

```
Aug 26 02:47:05 red-dust opentrons-api[246]: Exception during RPC call:
                                             Traceback (most recent call last):
                                               File "/usr/lib/python3.7/site-packages/robot_server/service/legacy/rpc/rpc.py", line 262, in make_call
                                                 self.executor, self.call_and_serialize, func
                                               File "usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
                                               File "/usr/lib/python3.7/site-packages/robot_server/service/legacy/rpc/rpc.py", line 253, in call_and_serialize
                                                 call_result = func()
                                               File "/usr/lib/python3.7/site-packages/opentrons/api/session.py", line 466, in stop
                                                 for mount, pip in instruments.items()}
                                               File "/usr/lib/python3.7/site-packages/opentrons/api/session.py", line 466, in <dictcomp>
                                                 for mount, pip in instruments.items()}
                                             KeyError: 'tip_length'
```
Ugh! Nope. Not your fault. I didn't realize `hardware.attached_instruments` includes the unattached mount key as well. What happens you test with both pipettes attached. Fix coming up.

2021-08-26 15:12 UTC, sanni-t commented on api/src/opentrons/api/session.py
> +        saved_tip_length = {mount: pip['tip_length']
`tip_length` is non-zero only when there is a tip attached. We need the tip length to perform a drop tip anyway so this one param is enough to do both.

2021-08-26 15:50 UTC, sanni-t commented on api/src/opentrons/hardware_control/api.py
> +            result['tip_length'] = instr.current_tip_length
This is a bit funny function. It is building a new dict from the keys specified in configs and then assigning latest values of all keys. So the `tip_length` key existed in this new dict, it just wasn't holding the latest value. 
I hadn't looked too much into this before but I'm now realizing that some of this logic might exist to counter a bug in other part of this file where the pipetteDict doesn't get updated correctly. Going to look at that and fix it if it's not a can of worms..

2021-08-26 16:40 UTC, sanni-t commented on api/src/opentrons/api/session.py
> +              then we will have change this logic.
That is true. Although I haven't seen any problems with this while testing. I think that's proving this comment from @sfoster1 that "..the skipping during halt thing i doubt is a problem for the plunger during liquid handling operations because it doesn’t go that fast"

I will add that as a note.

2021-08-26 17:43 UTC, mcous reviewed
I've got a couple tiny things, but otherwise looks pretty good. Proceeding with testing.

Aside: the tip management in hardware controller scares me!

2021-08-26 17:43 UTC, mcous commented on api/src/opentrons/api/session.py
> +        assert self.instruments, "No instruments found for performing a drop tip."
Can we get rid of this assert? A protocol could conceivably be module-only or something weird, so I think we should no-op if we've got no instruments, not assert

2021-08-26 17:43 UTC, mcous commented on api/src/opentrons/api/session.py
> +    def _drop_tip_after_cancel(self, saved_tip_length: Dict) -> None:
```suggestion
    def _drop_tip_after_cancel(
        self,
        saved_tip_length: Dict[MountType, Optional[float]],
    ) -> None:
```

2021-08-26 17:43 UTC, mcous commented on api/src/opentrons/hardware_control/api.py
> +            result['tip_length'] = instr.current_tip_length
Oof, this tip length situation looks pretty jacked up™️. `hw_api.add_tip` and `hw_api.remove_tip` fiddle with an instrument dict that goes absolutely nowhere, because the instrument dictionary is built anew every time.

I think this here is our least bad option for now

2021-08-26 18:50 UTC, mcous approved these changes
Changes look good to me and this procedure works on my robot. As discussed, I think there's an unavoidable risk of bottoming out the plunger depending on when _exactly_ the cancel happens due to the OT-2's dead-reckoning positioning, but that risk is easily outweighed by liquid aspiration risk, and we're not worried about any damage to the pipette from over-driving during drop tip.

Very cool to finally get this in ⛵

2021-08-27 18:38 UTC, SyntaxColoring approved these changes
Changes after my prior review seem good. Tested on a robot and it seems to work. 🎉

2021-08-30 15:59 UTC, Corey-ONeal commented
Testing is complete with no issues. This is good to go and I am approving this for QA now.

2021-08-30 16:00 UTC, Corey-ONeal approved these changes
Testing complete, good to go!

2021-08-30 16:30 UTC, merged