test(protocol-designer): fixing thermocycler failing cypress tests
OpenTrons/opentrons-api pull request #8234
Opened 2021-08-11 20:45 UTC by reachojhaneha

fixing thermocycler failing cypress tests
Closes #7224 and #8189

2021-08-13 14:15 UTC, shlokamin requested changes
wow, so including an extra space fixes the issue? was the issue that the last character was getting cut off? 

if this is a cypress issue, can we reference the issue in the code? as someone trying to understand why we sometimes have some extra spaces it might be confusing. 

it's odd that we only sometimes have to add the extra space and sometimes not... weird

2021-08-13 14:15 UTC, shlokamin commented on protocol-designer/cypress/integration/newProtocolWithModules.spec.js
> +        'Mag Deck Well '
can we keep this string in a constant? and then next to the constant we can have a comment that explains why there is an empty space after `Well`

2021-08-13 14:15 UTC, shlokamin commented on protocol-designer/cypress/integration/newProtocolWithModules.spec.js
> +        'Temp Deck Block '
same thing here

2021-08-13 14:15 UTC, shlokamin commented on protocol-designer/cypress/integration/newProtocolWithTC.spec.js
> +      cy.get('input[class*="LabwareOverlays__name_input"]').type('TC Well ')
same thing here

2021-08-13 14:15 UTC, shlokamin commented on protocol-designer/cypress/integration/newProtocolWithTC.spec.js
> +      cy.get('input[class*="LabwareOverlays__name_input"]').type('TC Well ')
same thing here

2021-08-13 14:49 UTC, reachojhaneha commented on protocol-designer/cypress/integration/newProtocolWithModules.spec.js
> +        'Mag Deck Well '
https://stackoverflow.com/questions/66257661/how-to-resolve-missing-characters-bug-in-cypress-type-command
My issue is similar to the one in the link. Cypress is not typing the entire string due to race condition. I tried multiple things like timeout, delay, wait and matching the input typed in the field. Nothing seems to be working. 
A space at the end of the string passes the case.

2021-08-13 14:57 UTC, reachojhaneha commented on protocol-designer/cypress/integration/newProtocolWithModules.spec.js
> +        'Temp Deck Block '
I am trying not to change the code. The idea is only to make it pass. There are multiple things that can be improved starting with modular cases and making testcases independent. We got 2 failures, where as fixing 1 cases fixed the other tc. Dependency leads to multiple failures.

2021-08-13 15:14 UTC, reachojhaneha commented on protocol-designer/cypress/integration/newProtocolWithModules.spec.js
> +        'Temp Deck Block '
does it make sense?

2021-08-13 15:15 UTC, reachojhaneha commented on protocol-designer/cypress/integration/newProtocolWithTC.spec.js
> +      cy.get('input[class*="LabwareOverlays__name_input"]').type('TC Well ')
"TC Well" has a variable, but i wanted to include a space. while verifying the text i am using the variable.

2021-08-13 15:16 UTC, reachojhaneha commented on protocol-designer/cypress/integration/newProtocolWithTC.spec.js
> +      cy.get('input[class*="LabwareOverlays__name_input"]').type('TC Well ')
"TC Well" has a variable, but i wanted to include a space. while verifying the text i am using the variable.

2021-08-13 15:35 UTC, shlokamin commented on protocol-designer/cypress/integration/newProtocolWithModules.spec.js
> +        'Temp Deck Block '
I understand we don't want to change the code much, but we also have to make sure that folks coming in and reading this understand what's going on. If we include extra spaces that appear random to someone who is not aware of this issue in cypress (even though they aren't actually random), we should be explicit and explain why in a comment or variable or something. 

So even something like 
```js

const tempDeckBlockWithExtraSpace // Note: reason this is needed is because of a cypress race condition. see `https://stackoverflow.com/questions/66257661/how-to-resolve-missing-characters-bug-in-cypress-type-command`

// and then in the test
cy.get('input[class*="LabwareOverlays__name_input"]').type(tempDeckBlockWithExtraSpace)

```

We just want to have some sort of documentation/explanation for why we need this hack, and a comment should be sufficient for now

2021-08-24 19:14 UTC, shlokamin approved these changes
thanks for looking into this neha!

2021-08-24 20:24 UTC, merged