feat(app): usb connection and moam modal functionality in module setup
OpenTrons/opentrons-api pull request #8257
Opened 2021-08-25 20:54 UTC by jerader

# Overview

Closes ticket #8233 

# Changelog

- add usb connection and connection status to module setup
- add functionality to `Proceed to Labware Setup` CTA
- add correct functionality to Multiple of a module (MoaM) modal to only show up if MoaM are in the uploaded protocol
- address Emily's comment mentioned on PR #8224 

# Review requests

- Addresses everything in ticket #8233 including Emily’s comment and the remaining acceptance criteria in #7664 
- For `usbPort` info, if user has a robot where the server version is below 4.3, rather than displaying what port or hub number the module is connected by, it will say `USB Port Connected`. Note: the Opentrons-dev bot does not have usbPort info so you should see `USB Port Connected`.

# Risk assessment

low, below FF

2021-08-26 19:05 UTC, shlokamin submitted a review, later dismissed
coming along! 

i think your `ModuleInfo` tests need a bit of rework. i'd start by thinking about what exactly `ModuleInfo`'s job is, and then craft your test cases from there. i.e. `it('should display a warning icon when modules are not attached')`

2021-08-26 19:05 UTC, shlokamin commented on app/src/assets/localization/en/protocol_setup.json
> +  "modules_setup_step_description": "Plug in and power up the required modules via the OT-2 USB Ports. Place the modules as shown in the deck map.",
do we need both of these?

2021-08-26 19:05 UTC, shlokamin commented on app/src/assets/localization/en/protocol_setup.json
> +  "usb_port_connected_old": "USB Port Connected"
`usb_port_connected_old` makes this seem like we don't need it anymore. what is its purpose?

2021-08-26 19:05 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx
> +                      </g>
is there a reason you added a `g` tag?

2021-08-26 19:05 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx
> +            backgroundColor={C_BLUE}
how come you switched this ordering?

2021-08-26 19:05 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/ModuleInfo.tsx
> +  const { x, y, orientation, moduleModel, usbPort, hubPort, isAttached } = props
how come you changed this from a function expression to a function declaration? we normally stick to function expressions when we can

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/function
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function

2021-08-26 19:05 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/ModuleInfo.tsx
> +          <p>
rather than conditionally rendering `Icon` twice, you can do something like this:

```js
 <Icon
     name="alert-circle"
     color={isAttached  ? COLOR_SUCCESS  : COLOR_ERROR}
     key="icon"
     height="0.625rem"
     width="0.625rem"
     marginRight={SPACING_1}
     marginTop={SPACING_1}
  />
```

2021-08-26 19:05 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/ModuleInfo.tsx
> +              t('hub_connected')}
this is a pretty dense block of ternaries, can this be extracted so it's easier to read?

2021-08-26 19:05 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/__tests__/ModuleInfo.test.tsx
> +  when.allArgs((args, equals) => equals(args[0], matcher))
you should be able to import this from shared components now if you rebase on top of edge: 

```
import {
  componentPropsMatcher,
  renderWithProviders,
} from '@opentrons/components/__utils__'
```

2021-08-26 19:05 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/__tests__/ModuleInfo.test.tsx
> +jest.mock('../ModuleInfo')
this test should be testing `ModuleInfo` right? we don't actually want to mock it, we only want to mock the dependencies of `ModuleInfo` that we need to

2021-08-26 19:05 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/__tests__/ModuleInfo.test.tsx
> +  it('should render no modules connected', () => {
this test isn't actually making any assertion, so it will always pass. what should module info be actually be doing?

the test name says it should not render any modules, but i dont think the `ModuleInfo` component has any concept of "modules", it just takes in info about a particular module and then renders some text and an icon depending on that info it loooks like

2021-08-26 19:05 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/__tests__/ModuleInfo.test.tsx
> +  it('should render modules connected on a robot server 4.3 or higher', () => {
same deal here, this test isn't making any assertions

2021-08-26 19:05 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/index.tsx
> +                      </React.Fragment>
same comment earlier about conditionally rendering `Icon` twice, you can render these components once and change what props you pass in depending on whether `modulesByPort` is empty or not

2021-08-26 19:05 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/index.tsx
> +  let MODULE_SETUP_KEY = 'module_setup_step'
how come this isn't a const too?

2021-08-26 19:06 UTC, shlokamin commented on app/src/assets/localization/en/protocol_setup.json
> +  "modules_setup_step_description": "Plug in and power up the required modules via the OT-2 USB Ports. Place the modules as shown in the deck map.",
if the extra is needed to pluralize, i18n can handle that for us i think: https://www.i18next.com/translation-function/plurals

2021-08-26 19:34 UTC, jerader commented on app/src/assets/localization/en/protocol_setup.json
> +  "usb_port_connected_old": "USB Port Connected"
If your robot server version is below 4.3, the usb and hub ports don't have a string (I double checked with my robot when it was version 4.0). So `usb_port_connected_old` is to support that.

2021-08-26 19:35 UTC, jerader commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx
> +                      </g>
whoops. idk how this got added back. removing it now.

2021-08-26 19:36 UTC, jerader commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx
> +            backgroundColor={C_BLUE}
some weirdness probably occurred when i rebased this to my last PR. i'll change it back 😬

2021-08-26 19:46 UTC, jerader commented on app/src/assets/localization/en/protocol_setup.json
> +  "modules_setup_step_description": "Plug in and power up the required modules via the OT-2 USB Ports. Place the modules as shown in the deck map.",
This is something that Emily wanted to implement. She mentioned it in a comment on my last PR #8224

2021-08-30 17:30 UTC, emilywools commented
hey Jethary! looking good! Here are some things I noticed:

1. can you add a space between the end of the sentence and the link in the MoaM modal:?
<img width="118" alt="Screen Shot 2021-08-30 at 1 25 52 PM" src="https://user-images.githubusercontent.com/4339860/131379718-88500d9a-08eb-4213-9018-71f9d6be1ead.png">
2. the green successfully connected icon should have a check mark in it instead of a !
3. The two temp modules are overlapping each other a little bit. Will this be resolved when we have the SVGs? 
<img width="451" alt="Screen Shot 2021-08-30 at 1 29 00 PM" src="https://user-images.githubusercontent.com/4339860/131379992-5ebf35c1-2e1a-460c-89fe-1f63b70fb415.png">

2021-08-30 18:39 UTC, jerader commented
@emilywools - this will be fixed when we have the SVGs 😄 

> 3. The two temp modules are overlapping each other a little bit. Will this be resolved when we have the SVGs?
> <img alt="Screen Shot 2021-08-30 at 1 29 00 PM" width="451" src="https://user-images.githubusercontent.com/4339860/131379992-5ebf35c1-2e1a-460c-89fe-1f63b70fb415.png">

2021-08-30 18:57 UTC, emilywools approved these changes
sounds good! looks good to me

2021-09-01 17:15 UTC, smb2268 requested changes
Looking really good overall, Jethary! I l just left a few comments that can help DRY things up.

2021-09-01 17:15 UTC, smb2268 commented on app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/index.tsx
> +import type { AttachedModule } from '../../../../redux/modules/types'
Pasting a comment Shlok left on my PR since it's relevant here and he explained it well! https://github.com/Opentrons/opentrons/pull/8182#discussion_r691253358: 

nit: we unfortunately have a pattern of imports we follow that is not enforced by a linter
basically we usually do
1. Builtin Node.js modules (import fs from 'fs')
2. External npm modules (import * as React from 'react')
3. Opentrons modules (import { THERMOCYCLER } from '@opentrons/shared-data')
4. Parent relative modules (import { SomeParentComponent } from '../../parent')
5. Sibling relative modules (import { SomeSiblingComponent } from './sibling')
6. type imports (import type {Whatever} from './types')

2021-09-01 17:15 UTC, smb2268 commented on app/src/assets/localization/en/protocol_setup.json
> +  "usb_port_connected_old": "USB Port Connected"
Maybe making this title more descriptive, something like `usb_port_connected_old_server_version` could make this more clear

2021-09-01 17:15 UTC, smb2268 commented on app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/index.tsx
> +                    ) : (
There aren't any differences between what you're returning here if attached is true vs false. If the variation between them is handled with different prop inputs than you can remove this ternary!

2021-09-01 17:15 UTC, smb2268 commented on app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/index.tsx
> +                            usbPort={port}
For this ternary, it looks like the only difference between having `attached` be true or false is what you're passing for `usbPort`. To make this DRY you can remove the larger ternary and do this instead: 

```
<React.Fragment
  key={`LabwareSetup_Module_${moduleModel}_${x}${y}`}
>
  <ModuleViz
    x={x}
    y={y}
    orientation={orientation}
    moduleType={getModuleType(moduleModel)}
  />
  <ModuleInfo
    x={x}
    y={y}
    moduleModel={moduleModel}
    orientation={orientation}
    isAttached={attached}
    usbPort={attached === true ? port : null}
    hubPort={attached === true ? port : null}
  />
</React.Fragment>
```

2021-09-01 17:15 UTC, smb2268 commented on app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/index.tsx
> +                            hubPort={port}
I'm not familiar with `usbPort` vs `hubPort` - we're passing in the string `port` for both, are they always the same thing? Looks like

2021-09-01 17:35 UTC, jerader commented on app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/index.tsx
> +                            hubPort={port}
On the robot, there are 2 or 4 usb ports (depending on if you have the OT-2 or the OT-2-R) If your robot has 2 usb ports which is the more common robot of the 2 and if you need to connect all 3 modules, you'll need to connect a hub that has more usb ports attached to it. `port` is the same in my code because your module is either connected via usb or hub and `const port = module.usbPort.hub || module.usbPort.port`. Hope this clears things up!

2021-09-01 17:49 UTC, jerader commented on app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/index.tsx
> +                    ) : (
omg that ternary is for no reason, thank you for noticing this!

2021-09-01 18:11 UTC, smb2268 commented on app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/index.tsx
> +                            hubPort={port}
Gotcha yes that makes sense - thanks for explaining!!

2021-09-01 18:12 UTC, smb2268 approved these changes
lgtm! 🚀

2021-09-03 15:42 UTC, b-cooper approved these changes
🚢

2021-09-03 15:44 UTC, merged