refactor(robot-server): Expose protocol metadata to HTTP clients
OpenTrons/opentrons-api pull request #8274
Opened 2021-08-31 20:37 UTC by SyntaxColoring

# Overview

# Changelog

# Review requests

# Risk assessment

2021-09-09 19:16 UTC, mcous reviewed
I know this PR is still very in progress, but I have some thoughts about unit responsibilities that may help with the naming stuff request in the PR description, so here we go

2021-09-09 19:16 UTC, mcous commented on api/src/opentrons/protocol_runner/__init__.py
>      "ProtocolFile",
I think this PR is a good time to rename this to `ProtocolSource`

2021-09-09 19:16 UTC, mcous commented on robot-server/robot_server/protocols/protocol_models.py
> +        extra = "allow"
Should we just use a `Dict[str, Any]` rather than having a `BaseModel` with only arbitrary fields?

2021-09-09 19:16 UTC, mcous commented on robot-server/robot_server/protocols/dependencies.py
> +        protocol_store = ProtocolStore(_PROTOCOL_STORE_DIRECTORY, PreAnalyzer())
You might have already gotten here yourself, but I would not inject `PreAnalyzer` into the `ProtocolStore`. The store is currently not a collaborator, and if you inject `PreAnalyzer`, you'll turn it into one. From there, you'll either 

1. Have redundant tests if you continue to opaquely test `ProtocolStore`
2. Need to make another "pure" unit to handle the storage mechanisms of `ProtocolStore`, testing the "new" collaborator `ProtocolStore` using mocks

Neither of those sound fun to me. Instead, looking at our current / potential units in play:

- `get_protocol` route handler - collaborator
- `ProtocolStore` - "pure" unit
    - Takes vanilla files
    - Copies files to disk
    - Creates protocol resources
    - Stores protocol resources
- `PreAnalyzer` - "pure" unit
    - Takes vanilla files
    - ???

Looking at that, I think one collaborator (the route handler) is still good, so I might end up shifting these responsibilities around. Hopefully that helps with naming, too:

- `PreAnalyzer`
    - Takes vanilla files
        - Or technically, Starlette `UploadFiles`, which conveniently will have the file contents spooled up in memory
    - File reading stuff to parse metadata, determine protocol type, etc.
    - Returns a data structure that includes the file objects and parsed stuff
- `ProtocolStore`
    - Takes whatever the `PreAnalyzer` returns
    - Puts files on disk
    - Returns `ProtocolSource`
- Route handler
    - Passes files to `PreAnalyzer`
    - Passes `PreAnalyzer` return value to `ProtocolStore`
    - Passes `ProtocolStore` return value to response

2021-09-10 16:01 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/protocol_models.py
> +        extra = "allow"
Maybe, yeah. I'll investigate and see what produces a nicer OpenAPI spec.

2021-09-10 16:12 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/__init__.py
> +    "JsonPreAnalysis",
If we're re-exporting the `pre_analysis` interface here, this should probably include error types, too.

If that becomes noisy and cumbersome, maybe don't reexport anything, and expect callers to import the `protocol_runner.pre_analysis` module to be imported as its own thing.

2021-09-10 16:16 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/pre_analysis.py
> +    def analyze(  # noqa: D102
It's weird that Codecov is complaining about these lines not being covered by tests. Is something wrong with our PyTest coverage collection?

2021-09-10 16:24 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/pre_analysis.py
> +    def analyze(  # noqa: D102
Local coverage report looks sensible. Theory: we're looking at alerts from the last CI job that passed. Tests are currently failing, so CI is failing, so these alerts haven't been updated.

2021-09-10 17:16 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_runner/test_pre_analysis.py
> +    ).dict(exclude_unset=True)
Investigate if we can set this in the config of the model

2021-09-10 17:16 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_runner/test_pre_analysis.py
> +    # metadata.
Maybe give this nuance its own test, separating it from the simple case.

2021-09-14 16:07 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_runner/test_pre_analysis.py
> +# it should allow ints.
Ticketing further investigation into

* what we currently actually allow
* what we should allow

as part of #8334.

2021-09-15 20:05 UTC, SyntaxColoring commented on robot-server/tests/protocols/test_protocol_store.py
> +# async def test_get_all_protocols(
Reminder to self: uncomment/fix this.

2021-09-15 20:08 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/__init__.py
>      "ProtocolFile",
Will rename to `ProtocolRunSource` because `ProtocolSource` sounds to me like it could be the input to the pre-analyzer.

2021-09-16 13:41 UTC, mcous requested changes
Looking pretty good! I think we're doing a little too much in the create protocols route handler, and I've got assorted thoughts

2021-09-16 13:41 UTC, mcous commented on api/src/opentrons/protocol_runner/pre_analysis.py
> +        parsed_json = json_load(main_file.file_like)
Why not use `JsonProtocol.parse_file`? Also, shot in the dark, would the file seeking issues be resolved if we opened and closed the file-like?

```python
with open(main_file.file) as f:
    parsed_json = JsonProtocol.parse_file(f)
```

2021-09-16 13:41 UTC, mcous commented on api/src/opentrons/protocol_runner/pre_analysis.py
> +    # (Otherwise, Pydantic would silently discard them.)
Can we set the `Metadata` class's config to allow extra properties instead? This will line the Pydantic model up with the JSON schema more accurately

2021-09-16 13:41 UTC, mcous commented on api/src/opentrons/protocol_runner/pre_analysis.py
> +    # todo(mm, 2021-09-14): Specify whether this is allowed to contain path separators,
After thinking about it, I don't think this is necessary. Let's add a docstring that specs it as the filename with suffix, to match `Path.name`

2021-09-16 13:41 UTC, mcous commented on api/src/opentrons/protocol_runner/pre_analysis.py
> +class InputFile:  # noqa: D101
I'm not sure I see the value of this dataclass at the moment, given that it's an arbitrary (looking) renaming of the fields from `starlette.datastructure.UploadFile`. Can we use a `typing.Protocol` here instead and go with structural subtyping for now?

2021-09-16 13:41 UTC, mcous commented on api/src/opentrons/protocol_runner/pre_analysis.py
> +class JsonPreAnalysis:  # noqa: D101
This class will need `schema_version` to support #8339

2021-09-16 13:41 UTC, mcous commented on api/src/opentrons/protocols/models/json_protocol.py
> +def make_minimal(
This is only used by tests. I think it should be moved back to where it was

2021-09-16 13:41 UTC, mcous commented on robot-server/robot_server/protocols/dependencies.py
> +async def get_pre_analyzer(app_state: AppState = Depends(get_app_state)) -> PreAnalyzer:
Unless there's an actual need for a factory, I woudn't add one

2021-09-16 13:41 UTC, mcous commented on robot-server/robot_server/protocols/protocol_models.py
> +        extra = "allow"
Let's use the enum provided by Pydantic instead

```py
from pydantic import BaseModel, Field, Extra
# ...
extra = Extra.allow

2021-09-16 13:41 UTC, mcous commented on robot-server/robot_server/protocols/protocol_models.py
> +            " (`protocolMetadata` may have information about"
```suggestion
            " (`metadata` may have information about"
```

2021-09-16 13:41 UTC, mcous commented on robot-server/robot_server/protocols/protocol_models.py
> +    # todo(mm, 2021-09-07): Should this be exposed to clients? We don't expose Python
Yes it should, and we'll need to expose API level at some point. Generally, look at the current app's file upload page for answers to the question "what information do we need?"

2021-09-16 13:41 UTC, mcous commented on api/tests/opentrons/protocol_runner/test_pre_analysis.py
> +    ).dict(exclude_unset=True)
As discussed, I don't think `exclude_unset` is worth the trouble here

2021-09-16 13:41 UTC, mcous commented on robot-server/robot_server/protocols/router.py
> +        await file.seek(0)
I think it's the responsibility of `pre_analyzer.analyze` to ensure that it doesn't mutate its arguments in this way. Having this in the route handler is not collaborator work

2021-09-16 13:41 UTC, mcous commented on robot-server/robot_server/protocols/router.py
> +        # (Starlette v0.13.2), mypy infers Union[SpooledTemporaryFile[bytes], IO[Any]].
Might be the difference between `fastapi.UploadFile` and `starlette.datastructures.UploadFile`

2021-09-16 13:41 UTC, mcous commented on robot-server/robot_server/protocols/router.py
> +        pre_analysis = pre_analyzer.analyze(pre_analysis_input)
Would be nice to move this down into the `try` block below

2021-09-16 13:41 UTC, mcous commented on api/src/opentrons/protocol_runner/pre_analysis.py
> +    # it.
This requirement feels pretty unintuitive for someone who might come in to use this interface, especially given that this file is an input argument

2021-09-16 13:41 UTC, mcous commented on api/src/opentrons/protocol_runner/pre_analysis.py
> +class PreAnalyzer:  # noqa: D101
Across the board, can we replace these `noqa: D101` with docstrings?

2021-09-16 13:41 UTC, mcous commented on robot-server/robot_server/protocols/router.py
> +        return PreAnalysisInputFile(upload_file.filename, underlying_file)
In general, can we use named parameters for dataclasses?

2021-09-16 13:41 UTC, mcous commented on robot-server/robot_server/protocols/router.py
> +    def convert_upload_file_to_pre_analysis_input(
I'd be down to get rid of this function. I think it makes the whole thing harder to read and I don't see what value the `assert` is bringing to the table

2021-09-16 13:41 UTC, mcous commented on robot-server/tests/protocols/test_protocol_store.py
> +from decoy import Decoy, matchers
Unused `Decoy` should be removed

2021-09-16 15:34 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +        await file.seek(0)
Replying in https://github.com/Opentrons/opentrons/pull/8274/files#r710118492.

2021-09-16 15:46 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/pre_analysis.py
> +    # it.
Yeah.

I thought about this, but came to the conclusion that this is a losing battle in Python; this is just how iterables and files work. I think it would be unconventional and inconsistent for the `PreAnalyzer` to take this responsibility.

As a general rule in Python, whenever you're reusing an iterable, it's your responsibility as the caller to reset it between uses, if you need to. Contrived example:

```python
dummy_data = [1, 2, 3, 4, 5]
my_iterable = reversed(dummy_data)
print(list(my_iterable)) # Prints [5, 4, 3, 2, 1].
print(list(my_iterable))  # Doesn't print anything; iterable was already exhausted.
```

File-like objects work the same way.

A less contrived example:

```python
file = open("Hello World.txt")
print(requests.post("http://httpbin.org/post", files={"my_file": file}).json())  # OK.
print(requests.post("http://httpbin.org/post", files={"my_file": file}).json())  # Wrong: file needs to be reset.
```

2021-09-16 15:58 UTC, SyntaxColoring commented on api/src/opentrons/protocols/models/json_protocol.py
> +def make_minimal(
Right, but it's now used by tests in both `api` and `robot-server`.

2021-09-16 16:02 UTC, SyntaxColoring commented on robot-server/tests/protocols/test_protocol_store.py
> +from decoy import Decoy, matchers
Nice catch, thanks.

2021-09-16 16:30 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +        # (Starlette v0.13.2), mypy infers Union[SpooledTemporaryFile[bytes], IO[Any]].
I think this actually got magically resolved by one of the `edge` merges into this branch. A mypy update, I guess? Who knows. I hope to find peace with its dreadful mysteries.

2021-09-16 16:35 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +    def convert_upload_file_to_pre_analysis_input(
The important part was the `assert`. It showed mypy that the construction of `PreAnalysisInputFile(upload_file.filename, underlying_file)` could assume that `upload_file.filename` was a `SpooledTemporaryFile[bytes]` and not an `IO[Any]`.

Like a `typing.cast()`, except with runtime typechecking, because I wasn't 100% confident in this, and if I turned out to be wrong, I would rather have an `AssertionError` here than a `AttributeError`/`ValueError`/`TypeError` somewhere down the line.

But anyway, this is all moot now because this function got removed per another discussion: https://github.com/Opentrons/opentrons/pull/8274#discussion_r710115697

2021-09-16 16:36 UTC, mcous commented on api/src/opentrons/protocols/models/json_protocol.py
> +def make_minimal(
I would duplicate the helper in that case

2021-09-16 16:40 UTC, mcous commented on api/src/opentrons/protocol_runner/pre_analysis.py
> +    # it.
Blah. Ok, if this is just too hard™️ at the moment, can we add a TODO comment to move to the "put the file on disk as part of pre-analysis" architecture that you drew out this week? Maybe that also resolves our naming issue: `ProtocolSaver` or something

2021-09-16 17:11 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/pre_analysis.py
> +        parsed_json = json_load(main_file.file_like)
> Also, shot in the dark, would the file seeking issues be resolved if we opened and closed the file-like?

Good thought, but it turns out no, unfortunately.

A `SpooledTemporaryFile` can't be reopened after it's closed. This sort of makes sense: closing a temporary file is signaling that we no longer need it, so the library can then free the memory it was occupying or delete it from the filesystem. There might not be anything to reopen if we come back to it again.

2021-09-16 17:16 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/dependencies.py
> +async def get_pre_analyzer(app_state: AppState = Depends(get_app_state)) -> PreAnalyzer:
Could you clarify this comment?

The endpoint handler `create_protocol()` has a `pre_analyzer` argument so that the PyTest function `test_create_protocol` can replace it with a mock. For that argument to be a real `PreAnalyzer` in production, it needs to be a FastAPI dependency, right?

2021-09-16 17:28 UTC, mcous commented on robot-server/robot_server/protocols/dependencies.py
> +async def get_pre_analyzer(app_state: AppState = Depends(get_app_state)) -> PreAnalyzer:
To flesh out, I meant: "since `PreAnalyzer` is not a singleton nor does it have any dependencies it itself needs injected, then we're free to pass the `PreAnalyzer` constructor directly into `Depends` without the need to make a `get_pre_analyzer` function

```
async def create_protocol(
    # ...
    pre_analyzer: PreAnalyzer = Depends(PreAnalyzer),
    # ...
) -> ResponseModel[Protocol]:

2021-09-16 17:32 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/protocol_models.py
> +        extra = "allow"
Changed to use enum.

Deferring the `Dict[str, Any]` thing.

2021-09-16 17:33 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/dependencies.py
> +async def get_pre_analyzer(app_state: AppState = Depends(get_app_state)) -> PreAnalyzer:
Oh! Cool.

2021-09-16 17:59 UTC, mcous commented on api/src/opentrons/protocol_runner/pre_analysis.py
> +        parsed_json = json_load(main_file.file_like)
Cool cool cool

2021-09-16 20:17 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/pre_analysis.py
> +    # (Otherwise, Pydantic would silently discard them.)
Yes, done.

* `class Config: Extra.allow` was set on other parts of those Pydantic models, just not `Metadata`. Not sure why.
    * A problem with the JSON protocol schema?
    * A problem with autogenerating Pydantic models from the JSON protocol schema?
    * An oversight in manual fixups?
* Looking at this more closely made me realize some other gotchas: https://github.com/Opentrons/opentrons/issues/8334#issuecomment-921206045

2021-09-16 20:31 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/pre_analysis.py
> +        parsed_json = json_load(main_file.file_like)
> Why not use `JsonProtocol.parse_file`?

A combination of a couple of reasons.

First, it turns out `.parse_file()` takes a *path,* not a file-like object. 🙃 

Second, even if it could take a file-like object, that would make it look something like this:

```python
    try:
        parsed_protocol = JsonProtocol.parse_file(main_file.file_like)
    except (JSONDecodeError, PydanticValidationError) as exception:
        raise JsonSchemaValidationError() from exception
```

In other words we can't get rid of the `JSONDecodeError`. Pydantic doesn't appear to convert it to `PydanticValidationError`; it lets it propagate.

Catching it like this felt fragile to me because Pydantic's choice of default JSON deserializer is an undocumented implementation detail. How do we know we have to catch `json.JSONDecodeError` and not, like, some_fancy_json.JSONDecodeError`?

2021-09-16 20:45 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_runner/test_pre_analysis.py
> +    ).dict(exclude_unset=True)
> Investigate if we can set this in the config of the model

Turns out no, we can't. :(

> As discussed, I don't think `exclude_unset` is worth the trouble here

I'd like to keep it because:

* We just have to set this kwarg in a couple of places, so it's not out of our way.
* It matches the apparent intended behavior of our JSON protocol schema. (Acknowledging that we could just decree in #8334 that not-present is the same as `null. But I'd like to avoid making that decision right here and now.)
* It matches the intuitive meaning of "pass metadata straight-through without modification."
* It makes this test more readable and a bit less fragile. We don't have to fill `expected_metadata` with a bunch of `None`s, and add additional `None`s every time we add a new metadata field to the JSON protocol schema.

2021-09-16 20:46 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_runner/test_pre_analysis.py
> +    # metadata.
Deferring this.

2021-09-16 21:20 UTC, SyntaxColoring commented on api/src/opentrons/protocols/models/json_protocol.py
> +def make_minimal(
Done, but this is surprising to me and I'd like to hear your thoughts.

2021-09-16 21:40 UTC, mcous commented on robot-server/robot_server/protocols/protocol_models.py
> +    """
I might consider paring this down. Detail is good, but brevity is also really important to make sure people can (and will) read it. Also, given discussions today about #8334, I don't think it's a good idea to commit to `The exact set of fields is not defined by this API.` right now

```suggestion
    """Extra, nonessential information about the protocol.

    This can include data like:

    * A human-readable title and description.
    * A last-modified date.
    * A list of authors.

    Metadata may contain fields other than those explicitly
    listed in this schema. Any such fields should be treated
    as arbitrary.

    The metadata *should not* include information needed
    to run the protocol correctly. For historical reasons, Python
    protocols define their `apiLevel` inside their metadata, but
    this should be considered an exception to the rule.
    """
```

2021-09-16 21:40 UTC, mcous commented on api/src/opentrons/protocols/models/json_protocol.py
> +        extra = Extra.allow
👍

2021-09-16 21:40 UTC, mcous commented on api/src/opentrons/protocol_runner/pre_analysis.py
> +        parsed_json = json_load(main_file.file_like)
> First, it turns out .parse_file() takes a path, not a file-like object. 🙃

🤦 of course it does

> In other words we can't get rid of the JSONDecodeError. Pydantic doesn't appear to convert it to PydanticValidationError; it lets it propagate.
>
> Catching it like this felt fragile to me because Pydantic's choice of default JSON deserializer is an undocumented implementation detail (I think?)

I think Pydantic propogating the `JSONDecodeError` is probably a good thing (or at least, a not horrible thing). We _should_ differentiate between something that isn't JSON and something that is not the JSON document we expect.

Also, Pydantic's docs [mention that it uses json.dumps explicitely](https://pydantic-docs.helpmanual.io/usage/exporting_models/#modeljson). In the realm of "things we can rely on", I think Pydantic using Python's built-in `json` module as the default json implementation is pretty rock solid. Also, it's not like the version of Pydantic we're using is going to change under our feet.

I would probably write this something like this:

```python
def _analyze_json(main_file: InputFile) -> "JsonPreAnalysis":
    try:
        # at this point both _analyze_json and _analyze_python would be
        # calling file_like.read(), so maybe move that (and a seek(0))
        # external to this function
        contents = main_file.file_like.read()
        protocol = JsonProtocol.parse_raw(contents)
    except IOError:
        # ...handle read error
    except JSONDecodeError as exception:
        raise JsonParseError() from exception
    except PydanticValidationError as exception:
        raise JsonSchemaValidationError() from exception

    return JsonPreAnalysis(metadata=protocol.metadata.dict())
```

It's short, it catches reasonable errors with only one ugly try/raise, and it leans on something else (Pydantic) to do all the hard stuff

2021-09-17 14:03 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +        pre_analysis = pre_analyzer.analyze(pre_analysis_input)
[Discussed in call] leaving this alone to keep the `try` blocks small and specific.

2021-09-17 14:07 UTC, SyntaxColoring commented on api/src/opentrons/protocols/models/json_protocol.py
> +def make_minimal(
[Discussed in call] Duplicated test fixtures feel better than a dead code path in production source.

2021-09-17 14:12 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/__init__.py
>      "ProtocolFile",
[Discussed in call] Leaving this alone for now until after refactor to put stuff on the disk and deal with `pathlib.Path` objects earlier. (See `todo` comment in code.)

2021-09-17 15:47 UTC, mcous approved these changes
🤘

2021-09-17 16:42 UTC, merged