refactor(robot_server,api): do not use ThreadManager with ProtocolEngine
OpenTrons/opentrons-api pull request #8278
Opened 2021-09-01 14:04 UTC by mcous

## Overview

This PR updates the robot-server and api's initialization routines to bypass the `ThreadManager` if the "Enable ProtocolEngine" feature flag is enabled.

## Changelog

- Do not use ThreadManager with ProtocolEngine
    - This change breaks RPC if the feature flag is set
    - This wasn't intentional, but it's a natural result of bypassing the `ThreadManager` and its `SyncAdapter`
    - I don't think it's a problem and do not intend to fix it

## Review requests

Test plan TODO. TL;DR: run protocols with both the feature flag on and off, see if anything breaks

## Risk assessment

Medium due to touching hardware initialization code and nearly complete lack of test coverage

2021-09-01 16:17 UTC, mcous commented on robot-server/robot_server/service/dependencies.py
> +            f"version unconditionally, specify {constants.API_VERSION_LATEST}'"
```suggestion
            f"version unconditionally, specify '{constants.API_VERSION_LATEST}'"
```

2021-09-01 17:55 UTC, mcous commented on robot-server/robot_server/app.py
> -    (await get_protocol_manager()).remove_all()
These weren't doing anything, nor were they necessary for the intended behavior, based on my testing. Removed them accordingly

2021-09-01 18:00 UTC, mcous commented on robot-server/robot_server/app.py
> +    await cleanup_hardware(app.state)
`cleanup_rpc_server` may still raise due to #8155. I wonder if this makes more sense with a gather and some logs:

```suggestion
    shutdown_results = await asyncio.gather(
        cleanup_rpc_server(app.state),
        cleanup_hardware(app.state),
        return_exceptions=True,
    )
    
    shutdown_errors = [r for r in shutdown_results if isinstance(r, Exception)]
    
    for e in shutdown_errors:
        log.warning(f"Error encountered during shutdown", exc_info=e) 
```

2021-09-01 19:01 UTC, mcous commented on robot-server/robot_server/app.py
> -    (await get_protocol_manager()).remove_all()
Oof, looks like I might be wrong here. Tests are hanging on my machine in a way that reminds me of our previous experience with `ulimit`

2021-09-01 20:03 UTC, SyntaxColoring commented on api/src/opentrons/__init__.py
> -        # Let this raise an exception.
Could we leave this comment in? It helped me navigate this code at one point. IIRC this raises an `IndexError` when there's no motor controller board physically attached.

(Ideally, this would probably raise a custom `NoMotorControllerPortError` or whatever, but I don't think that's for this PR.)

2021-09-01 20:38 UTC, mcous commented on api/src/opentrons/__init__.py
> +    async def _blink():
I feel pretty suspicious that the "button blink while initializing" may not be working in this PR

2021-09-01 21:35 UTC, SyntaxColoring requested changes

2021-09-01 21:35 UTC, SyntaxColoring commented on robot-server/robot_server/app.py
> +    )
This `gather()` makes me nervous.

* The interface of the matched factory function, `get_rpc_server()`, takes a hardware parameter. As the caller, I would assume that that hardware would need to stay valid for the entire lifetime of the RPC server, including its cleanup code.
* `cleanup_rpc_server()` in fact *does not* touch the hardware, and it *does* appear safe to call it concurrently with `cleanup_hardware()`. But you have to read the implementation of `cleanup_rpc_server()` to know that. It feels like a breach of encapsulation.

I'd be more comfortable with a simple:

```python
await cleanup_rpc_server()
await cleanup_hardware()
```

Note that this would still be buggy because an exception in `cleanup_rpc_server()` will prevent `cleanup_hardware()` from running. However, I think that's okay for this PR, because:

* That interrupted shutdown bug existed before.
* That interrupted shutdown bug still exists with the `gather()` code, because of the `await get_protocol_manager()` and `protocol_manager.remove_all()` above the `gather()`.

I think solving the interrupted cleanup bug is in the domain of #8051. It probably requires either a horrible `try`/`except` mess or `contextlib.ExitStack`.

2021-09-01 21:35 UTC, SyntaxColoring commented on robot-server/robot_server/app_state.py
> +    websocket: WebSocket = None,
Wow. I'm amazed that this works...? Is this in the docs or discussed in a GitHub issue anywhere?

2021-09-01 21:35 UTC, SyntaxColoring commented on robot-server/robot_server/hardware.py
> +        await asyncio.gather(initialize_task, return_exceptions=True)
I think this can just be this?

```suggestion
        await initialize_task
```

2021-09-01 21:35 UTC, SyntaxColoring commented on robot-server/robot_server/hardware.py
> +    unsubscribe_from_events = getattr(app_state, _HARDWARE_EVENT_UNSUBSCRIBE_KEY, None)
I think this is good for this PR, but one of the things I was trying to work out in #8213 was how to avoid too much indirection through keys, because it subverts typechecking.

What ended up in that PR was you'd access one `DependencySet` dataclass through a key, and then access the actual things you cared about in a type-safe way through that dataclass. So the indirection was still there, but it was consolidated and mitigated.

That strategy was messy in other ways, so I don't think it's the final solution, but I do hope we can find some other way to avoid this.

2021-09-01 21:35 UTC, SyntaxColoring commented on robot-server/robot_server/hardware.py
> +            dependency injection system will attempt to provide it.
Requesting changes for this.

This wording might be misleading, since FastAPI's *won't* attempt to provide `app_state` if you call `get_hardware()` without providing it. (It will only provide it when `get_hardware` is used as a dependency, like `Depends(get_hardware)`.)

2021-09-01 21:35 UTC, SyntaxColoring commented on robot-server/robot_server/service/legacy/rpc/__init__.py
> +    "get_rpc_server",
Requesting changes (or at least discussion) for this.

This makes me nervous because you can now do, for example, `from service.legacy import get_rpc_server`. And then, unless you read the docstring, it looks like `get_rpc_server` is just a normal function that you can call like `get_rpc_server()`.

I'm hoping for a strong naming convention that sets our FastAPI dependency functions apart from other functions. Possibilities:

* Making sure `dependencies` is always in the import path somewhere, like what we had before, so it's `service.legacy.rpc.dependencies.get_rpc_server`. I think we discussed this before, but I don't remember your thoughts on it. I personally don't mind it.
* Making it something like `service.legacy.rpc.dep_rpc_server`.

Ditto for `robot_server.hardware.get_hardware`.

2021-09-01 21:54 UTC, mcous commented on robot-server/robot_server/hardware.py
> +        await asyncio.gather(initialize_task, return_exceptions=True)
This is to ensure shutdown happens cleanly if:

- Initialization raised for some reason
- Shutdown requested before the hardware initialization finishes

2021-09-01 23:06 UTC, mcous commented on robot-server/robot_server/app_state.py
> +    websocket: WebSocket = None,
I found it by reading the Starlette source, where it is present in the public API of the [`HTTPConnection` base class](https://github.com/encode/starlette/blob/84e2dc7bfe35aa82a0db958519810309e73de8f5/starlette/requests.py#L58-L62):

> ```python
> class HTTPConnection(Mapping):
>     """
>     A base class for incoming HTTP connections, that is used to provide
>     any functionality that is common to both `Request` and `WebSocket`.
>     """
>
>     # ...
>
>     @property
>     def app(self) -> typing.Any:
>         return self.scope["app"]
> ```

Probably worth a docs PR into both FastAPI and Starlette

2021-09-01 23:10 UTC, mcous commented on robot-server/robot_server/app.py
> +    )
I hear your and agree with your concerns, but I'd rather keep the `gather` for this PR because:

- We know `protocol_manager.remove_all()`, as written, won't raise
- We know RPC cleanup _will_ raise in a common condition (connection present during shutdown)
- We know that hardware cleanup and RPC cleanup, as written, can run concurrently
- If something changes in the future that means they can't run concurrently, there will be a log statement

Removing the `gather` make me more nervous than omitting it. Let's not let perfect be the enemy of good

2021-09-01 23:26 UTC, mcous commented on robot-server/robot_server/hardware.py
> +    unsubscribe_from_events = getattr(app_state, _HARDWARE_EVENT_UNSUBSCRIBE_KEY, None)
I think this would be better if I know how to get some sort of immutable, unique [Symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol)-like object in Python for use as the key rather than a string, where the remote but real possibility of key collisions exist, but to be honest that's the extent of my concern with this.

I don't share the concern about subverting typchecking for a few reasons:

- The keys and value storage on `AppState` are entirely private implementation details of this module
- The primary value I derive from typing in scripted languages is code documentation and maybe some refactor safety
    - I think the object keys satisfy the documentation value, and I think this module is too small for any serious refactor safety concerns
    - Some type annotations on the variable declarations probably couldn't hurt, though!

In order to strictly type `AppState`, you end up needing to:

- Create an object that has to know about the implementation details of every module in the system that may want to store arbitrary global data, breaking encapsulation
- Introduce circular (type) dependencies

Those, to me, are serious downsides that introduce brittleness and coupling into the entire application, and I don't see what value it gives us in exchange. As we work with `AppState`, all data attached to `AppState` is private to the module that creates it

2021-09-02 00:01 UTC, mcous commented on robot-server/robot_server/service/legacy/rpc/__init__.py
> +    "get_rpc_server",
If there's one thing I've learned working with FastAPI, its that nothing is ever just a normal function you can call 🙃. Mostly, though, I guess I don't feel nervous about this? If someone comes in thinking they can call `get_rpc_server` function outside of `Depends` or without passing in `AppState` explicitly, they'll be disabused of that notion when whatever it was they were trying to do doesn't work at all.

(I'm not counting the server setup and teardown bugs that we definitely did not notice for a while because a) teardown doesn't really matter because the process is stopped, and b) the part of setup that was broken wasn't a production codepath nor was it ever subject to actual tests. In anything even remotely production-facing, I think we'd notice pretty quickly.)

My TL;DR here is that I feel it's reasonable to expect a developer in this codebase to understand how and where the dependency injection system is used. That's my take, and I don't love the idea of forcing myself to do more typing for this, but:

- I dislike putting `dependencies` in public module name
    - This opinion _generally_ holds for any module name that describes the type of thing it is rather than the scope of its logic in the application, including `models`, `constants`, `types`, etc.
- I could live with `get_hardware_dependency`, etc.

2021-09-02 03:29 UTC, SyntaxColoring commented on robot-server/robot_server/hardware.py
> +    unsubscribe_from_events = getattr(app_state, _HARDWARE_EVENT_UNSUBSCRIBE_KEY, None)
> In order to strictly type `AppState`, you end up needing to:
> 
> * Create an object that has to know about the implementation details of every module in the system that may want to store arbitrary global data, breaking encapsulation
> * Introduce circular (type) dependencies

Here's another approach that avoids those downsides.

```python
class TypedStateValue(typing.Generic[T]):
    def __init__(unique_key: str) -> None:
        # Alternatively, we might be able to have this autogenerate unique keys.
        self._unique_key = unique_key
    
    def get_from(app_state: AppState) -> T:
        return getattr(app_state, self._unique_key)

    def set_on(app_state: AppState, value: T) -> None:
        setattr(app_state, self._unique_key, value)
```

```python
_initialize_task = TypedStateValue[asyncio.Task]("_initialize_task")
_hardware_api = TypedStateValue[API]("_hardware_api")
_unsubscribe_from_events = TypedStateValue[typing.Callable[[], None]]("_unsubscribe_from_events")

async def cleanup_hardware(app_state: AppState) -> None:
    initialize_task = _initialize_task.get_from(app_state)
    hardware_api = _hardware_api.get_from(app_state)
    unsubscribe_from_events = _unsubscribe_from_events.get_from(app_state)

    # ...
```

I agree that the severity of not having typechecking is lessened by this module being small and these attributes being internal. I do still think we should strive to have typechecking when it doesn't take "too much" machinery, and I hope the sketch above falls under the threshold for "too much"?

2021-09-02 13:10 UTC, mcous commented on robot-server/robot_server/hardware.py
> +    unsubscribe_from_events = getattr(app_state, _HARDWARE_EVENT_UNSUBSCRIBE_KEY, None)
That's a pretty neat little helper, will add it to rovot_server/app state.py

2021-09-02 14:48 UTC, SyntaxColoring commented on robot-server/robot_server/service/legacy/rpc/__init__.py
> +    "get_rpc_server",
> If there's one thing I've learned working with FastAPI, its that nothing is ever just a normal function you can call

Magic is good because Everything Always Just Works, right? 🙃 

> Mostly, though, I guess I don't feel nervous about this?...

* It's certainly possible I'm just traumatized by the server setup/teardown bugs, but I'm still a bit nervous about the same thing happening again.
* Also, even if FastAPI dependency functions weren't special and error-prone in this way, I think I can see a separation-of-layers argument for keeping them apart?

I think let's keep this as-is for this PR, and open a naming convention discussion in `#python` or something.

2021-09-02 14:49 UTC, SyntaxColoring commented on robot-server/robot_server/hardware.py
> +        await asyncio.gather(initialize_task, return_exceptions=True)
Aha. I think I'd find a `try`/`except` clearer, but this works for me if you want to keep it as-is.

2021-09-02 15:17 UTC, SyntaxColoring commented on robot-server/robot_server/app_state.py
> +    websocket: WebSocket = None,
I'm more surprised by the `= None` thing working.

2021-09-02 16:07 UTC, mcous commented on robot-server/robot_server/app_state.py
> +    websocket: WebSocket = None,
Oh shoot, yeah, that needs a comment. It needs to be `request: Request` and `websocket: WebSocket` in order for FastAPI to magically pick up the type annotations and inject the object. `request: Optional[Request]` will blow up DI.

From there, our mypy config is set to be a little more lenient than I'd like, where you're allowed to do `foo: SomeType = None` instead of `foo: Optional[SomeType] = None`. Will add comments to that effect because it's a gotcha

2021-09-02 16:21 UTC, SyntaxColoring approved these changes
Code changes since my last review look good, though there are still some open conversations.

Smoke tests (according to the plan in the description) passed. 🎉

2021-09-02 17:05 UTC, mcous commented on api/src/opentrons/__init__.py
> +    async def _blink():
Looks like it's ok! To quote @SyntaxColoring 

> IIRC there is some redundancy in our light-blinking implementation. I think there’s a systemd service that blinks the lights until robot-server starts up, and then robot-server blinks the lights until it reaches some internal checkpoint, or something.

2021-09-03 12:34 UTC, sanni-t approved these changes
Very cool!! 
Just the comment about making sure hardware api initializes correctly on a refresh robot.

2021-09-03 12:34 UTC, sanni-t commented on api/src/opentrons/__init__.py
> +    """Build the hardware controller wrapped in a TheadManager.
```suggestion
    """Build the hardware controller wrapped in a ThreadManager.
```

2021-09-03 12:34 UTC, sanni-t commented on api/src/opentrons/__init__.py
> +    systemdd_notify()
This _might_ have to go after the hardware api initialization. Putting it here might result in  GPIO access conflict on a refresh robot. Have we tested this on an OT2R?

2021-09-03 14:05 UTC, mcous commented on api/src/opentrons/__init__.py
> +    systemdd_notify()
I've only tested on non-refresh, I believe. I put it here because I thought I saw it come before hardware init in the existing code. Def worth double and triple checking

2021-09-03 15:53 UTC, sanni-t commented on api/src/opentrons/__init__.py
> +    systemdd_notify()
Cool. I can go over the service files and test on the refresh electronics.

2021-09-07 17:43 UTC, sanni-t commented on api/src/opentrons/__init__.py
> +    systemdd_notify()
Tested that refresh electronics start up correctly. PR is good to merge!

2021-09-07 17:53 UTC, merged