feat(app): add labware setup CTA functionality
OpenTrons/opentrons-api pull request #8301
Opened 2021-09-03 16:52 UTC by jerader

# Overview

Closes ticket #8175 

# Changelog

# Review requests

- add CTA functionality to Labware Setup including 3 different tooltips depending on what may need to be complete

# Risk assessment

low

2021-09-10 21:42 UTC, b-cooper requested changes
This is a great start, and with a bit of tweaking it'll be there.!

It looks like the logic that calculates the `disabledReason` is a little bit inaccurate right now.  It would be great to pull it into its own hook that we can unit test separately. (and can be shared between `LabwareSetup` and `ModuleSetup` too). 

We also have an established pattern that might be useful to deploy here for cases where we have a button that may be disabled for many reasons.  Basically instead of maintaining two variables `isDisabled: boolean` and `disabledReason: string`  you can just maintain `disabledReason: string | null`. This way, if it `disabledReason === null` we know that it's not disabled, and if `disabledReason === 'any string describing why it's disabled'` then we can pass that string to the tooltip to be rendered on the disabled button.  This should clean up some of the numerous `if else` blocks in this PR, and make the function more easily testable.

2021-09-10 21:42 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/__tests__/LabwareSetup.test.tsx
> +  it('should render a deck WITHOUT labware and WITHOUT modules and CTA disabled', () => {
Is this right?  I believe we still want to render the labware and the modules in the case that the CTA is disabled.

2021-09-10 21:42 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx
> +  const allModulesAttached =
I don't think the logic of this boolean holds up.  We want to iterate over every required module and make sure that there is a corresponding attached module for each.  I think `uniqueModules` will actually always be identical to `moduleModels` here based on the way this is currently written (unless there is an extra module plugged in, but we don't need to worry about that).  It looks like this was carried over from previous work in `ModuleSetup` so we should make sure it's fixed in both places, or better yet, abstract this logic to a hook that is used in both places and declutter both of these components a bit.

2021-09-13 11:59 UTC, jerader commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx
> +  const allModulesAttached =
Hi Brian, thanks for the feedback - what example are you thinking of where this logic won't work? `uniqueModules` can sometimes be the same length as `moduleModels` but not always. For example if you have 1 module plugged in but it isn't the 1 you need,  `moduleModels.length` = 1, `combinedModules.length` = 2, `uniqueModules.length` = 2, and `combinedModules.length - uniqueModules.length` = 0 which does not equal `moduleModels`. So CTA would be disabled. Additionally, in that example `moduleModels` doesn't equal `uniqueModules`. I know this logic is probably a bit messier than what it could be but I think it is correct.

That makes sense to make a hook and use it in both places - I will do that!

2021-09-13 15:02 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx
> +  const allModulesAttached =
If there are two instances of a requested module attached, this will give a false negative.  e.g.

```
requestedModules = ['temp', 'mag']
attachedModules = ['temp', 'temp', 'mag']

combinedModules = ['temp', 'temp', 'mag', 'temp', 'mag'] // [...attached, ...requested]
uniqueModules = [ 'temp', 'mag']

allModulesAttached = ((5 - 2) === 2) // false
```

2021-09-14 12:42 UTC, jerader commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/__tests__/LabwareSetup.test.tsx
> +  it('should render a deck WITHOUT labware and WITHOUT modules and CTA disabled', () => {
good catch, I'll remove this case!

2021-09-17 15:42 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx
> +          Labware Position Check
NOTE: This is not in i18n because it's just placeholder text, the newest designs don't even include this string

2021-09-17 15:45 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/__tests__/ModuleSetup.test.tsx
> +    expect(button).not.toHaveAttribute('disabled=""')
this seems weird, let's investigate how to test if the button is disabled directly

2021-09-17 16:27 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RunSetupCard/ProceedToRunCta.tsx
> +  const proceedToRunDisabledReason = calibrationIncomplete
refactor to not included nested ternary

2021-09-17 16:28 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RunSetupCard/ProceedToRunCta.tsx
> +    <React.Fragment>
remove this fragment, it is unnecessary

2021-09-17 16:29 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RunSetupCard/__tests__/ProceedToRunCta.test.tsx
> +  })
add test cases for 1. calibration incomplete and 2. both missing modules and cal incomplete

2021-09-17 16:31 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RunSetupCard/__tests__/hooks.test.tsx
> +  })
add test case for missing module id's if there are some

2021-09-17 16:34 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RunSetupCard/hooks.ts
> +  let robotName = ''
replace with 
```
if (robot == null) return [] // NOTE: this should only be called when there is a robot connected
```

2021-09-17 16:35 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RunSetupCard/index.tsx
> +      stepInternals: <LabwareSetup labwareRenderCoords={labwareRenderCoords} />,
the `labwareRenderCoords` prop should be removable now

2021-09-17 16:37 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/__tests__/RunSetupCard.test.tsx
>        .mockReturnValue(mockLabwareRenderCoords)
add test case to ensure that the "Mock Proceed to Run" gets rendered

2021-09-17 18:17 UTC, jerader commented on app/src/organisms/ProtocolSetup/RunSetupCard/index.tsx
> +      stepInternals: <LabwareSetup labwareRenderCoords={labwareRenderCoords} />,
wait, I don't think its removable yet because I didn't change it in my code? I only changed `moduleRenderCoords` to match your branch

2021-09-17 18:24 UTC, jerader commented on app/src/organisms/ProtocolSetup/RunSetupCard/hooks.ts
> +  let robotName = ''
I am not sure how to write it so the return comes after the `attachedModules` hook in order to fix the lint error. this is what I have:
`  if (robot == null) {
    return []
  }
  const attachedModules = useSelector((state: State) =>
    getAttachedModules(state, robot.name)
  )`

2021-09-18 19:56 UTC, merged