OE update server {WIP}
OpenTrons/opentrons-api pull request #8303
Opened 2021-09-07 13:57 UTC by sotaoverride

OE update server RET-109

API update server for updating OT3s (running  openembedded)

2021-09-07 18:00 UTC, sfoster1 requested changes
Some changes inline; also, I think we should separate the concepts of the cli and the server a little more

2021-09-07 18:00 UTC, sfoster1 commented on update-server/otupdate/RootFS.ini
> +[DEFAULTS]
doesn't quite feel right that this file lives in the source tree; it would get put into the installed package.

Also, for better or worse, we've more or less standardized on json as a format for config files, so we should use that.

2021-09-07 18:00 UTC, sfoster1 commented on update-server/otupdate/RootFS.ini
> +root_fs_partition = ROOT_AATIR
forgot to delete? is that an env var reference?

2021-09-07 18:00 UTC, sfoster1 commented on update-server/otupdate/__main__.py
> +from openembedded_server.__main__ import main
This will break all current OT-2s by using the wrong backend. We should either
- leave this untouched, and when we start the server on the ot3s do `python -m otupdate.openembedded` (i think this is the right thing to do)
- have this parse some config to decide which to run

2021-09-07 18:00 UTC, sfoster1 commented on update-server/otupdate/openembedded/RootFS.ini
> +[DEFAULTS]
I think I see what this is doing, providing default carveouts. It definitely should be json though

2021-09-07 18:00 UTC, sfoster1 commented on update-server/otupdate/openembedded/RootFS.py
> +import argparse
current style is to keep python filenames `snake_case` not `CamelCase` eg `rootfs`

2021-09-07 18:00 UTC, sfoster1 commented on update-server/otupdate/openembedded/RootFS.py
> +        print('check this \n')
definitely need to remove these before committing. this system should be set up with python logging. it's ok to have the logging go to stdout/err because systemd will grab it

2021-09-07 18:00 UTC, sfoster1 commented on update-server/otupdate/openembedded/RootFS.py
> +    def get_partition(self) -> RootFSInfo:
since this is intended for use in our systems, could we replace parsing `mount` with just reading the current value of the variable in the u-boot environment? default it to some default for when that hasn't been written yet, which would just be after the first flash.

2021-09-07 18:00 UTC, sfoster1 commented on update-server/otupdate/openembedded/RootFS.py
> +    def factory_restore(self, arg: argparse.Namespace) -> None:
i don't quite get the point of the factory restore here. is this supposed to be a multiple partition full disk image?

2021-09-07 18:00 UTC, sfoster1 commented on update-server/otupdate/openembedded/RootFS.py
> +        return ('Current RootFS Partition '+tmp.disk+'\n')
style nit: parens in return statements in python always bug me because they also create tuples, so i always have to look a couple times. would you mind avoiding them unless necessary?

2021-09-07 18:00 UTC, sfoster1 commented on update-server/otupdate/openembedded/RootFSCLI.py
> +"""
filename should be `snake_case`

2021-09-07 18:00 UTC, sfoster1 commented on update-server/otupdate/openembedded/__main__.py
> +Entrypoint for the openembedded update server
the server is in another subpackage, right?

2021-09-07 18:00 UTC, sfoster1 commented on update-server/otupdate/openembedded_server/__init__.py
> +        web.post('/server/oe//restore', rfs.factory_restore),
```suggestion
        web.post('/server/oe/restore', rfs.factory_restore),
```

2021-09-07 18:00 UTC, sfoster1 commented on update-server/otupdate/openembedded_server/__main__.py
> +# whats this _handler_for and _notify_up being defined here for, (function definition)
they're used lower down in the file, to provide direct-to-journald log output and `sd_notify` integration respectively. the comments on line 26-9 are about the sd_notify part;  it's then called on line 97. `_handler_for` is used on line 64.

2021-09-07 18:00 UTC, sfoster1 commented on update-server/otupdate/openembedded_server/__main__.py
> +    rfscli = RootFSCLI.RootFSCLI()
i think we either shouldn't be using this here or shouldn't be calling it a cli. If it's a common set of args for configuring things, let's make a common set of args for configuring things; but certainly this server should not be able to be started with options about functionality, that's just confusing.

2021-09-08 17:59 UTC, sotaoverride commented on update-server/otupdate/openembedded_server/__main__.py
> +    rfscli = RootFSCLI.RootFSCLI()
calling this class OEServerMode, will use to run the server in different modes.

2021-09-21 15:39 UTC, sotaoverride commented
chunking this into something manageable

2021-09-21 15:39 UTC, closed without merging