feat(g-code-testing): HTTP G-Code GitHub Action (RET-174)
OpenTrons/opentrons-api pull request #8338
Opened 2021-09-13 18:55 UTC by DerekMaggio

# Overview

# Changelog

# Review requests

# Risk assessment

2021-09-14 16:23 UTC, sfoster1 requested changes
This is a lot of tests, and they're all separate makefile targets and each makefile target is a separate line in the github action. That's a lot to keep up to date and maintain; in addition to whatever's necessary to make the test run, it guarantees touching two other files.

What if instead we used a test system with test autodiscovery - pytest, for instance, since this is in python - and used its output reporting? one command, and the only thing you need to touch to change or add a test is the test code itself.

2021-09-14 16:23 UTC, sfoster1 commented on .github/workflows/g-code-http-tests.yaml
> +      - 'api/**'
You probably want to trigger it on this workflow file too
```suggestion
      - 'api/**'
      - '.github/workflows/g-code-http-tests.yaml'
```

2021-09-14 16:23 UTC, sfoster1 commented on .github/workflows/g-code-http-tests.yaml
> +        if: always()
```suggestion
```

Do you need this?

2021-09-14 18:11 UTC, DerekMaggio commented
> This is a lot of tests, and they're all separate makefile targets and each makefile target is a separate line in the github action. That's a lot to keep up to date and maintain; in addition to whatever's necessary to make the test run, it guarantees touching two other files.
> 
> What if instead we used a test system with test autodiscovery - pytest, for instance, since this is in python - and used its output reporting? one command, and the only thing you need to touch to change or add a test is the test code itself.

@sfoster1, the hard part is comparing against S3.
Is it okay if I pull in the S3 python package use that?

2021-09-15 17:31 UTC, amitlissack commented on g-code-testing/tests/g_code_comparision/test_quick_protocol.py
> +def test_quick_protocols(master_file_name, path, settings):
Would be nice to see type annotations on all args and returns.

2021-09-15 19:09 UTC, DerekMaggio commented on g-code-testing/tests/g_code_comparision/test_quick_protocol.py
> +def test_quick_protocols(master_file_name, path, settings):
Updated

2021-09-16 17:52 UTC, sfoster1 approved these changes
This looks great! I think you can make the yaml a bit better using job matrices, but that's about it. Really like the use of pytest markers.

2021-09-16 17:52 UTC, sfoster1 commented on .github/workflows/g-code-confirm-tests.yaml
> +name: "G-Code-Confirm"
I think you can use https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix to make this a bit more concise. It's just text substitution, so you could make your matrix a list of tests to run and put it in the commands to make and the names of the jobs

2021-09-16 19:32 UTC, merged