feat(update-server): Initial Refactor
OpenTrons/opentrons-api pull request #8375
Opened 2021-09-21 16:11 UTC by sotaoverride

# Overview

Initial refactor and additions to update-server for making it usable across systems using different build systems (OE and buildroot)
# Changelog

# Review requests

# Risk assessment

2021-09-23 17:37 UTC, sfoster1 requested changes

2021-09-23 17:37 UTC, sfoster1 commented on update-server/otupdate/__main__.py
> +from .openembedded_server.__main__ import main
Must remove this before merging since it will break the OT2

2021-09-27 15:11 UTC, Laura-Danielle commented on update-server/otupdate/__main__.py
> +# oe_main()
Rogue comment here, I think.

2021-09-27 15:11 UTC, Laura-Danielle commented on update-server/otupdate/__main__.py
> +    if args.build_system == 'oe':
Can you explain the logic a little bit more? Why do we need to remove oe from the CLI args? Is there a way to just have flags for every required argument?

2021-09-27 15:11 UTC, Laura-Danielle commented on update-server/otupdate/openembedded_server/__init__.py
> +# , name_management
Is this meant to be here?

2021-09-27 15:11 UTC, Laura-Danielle commented on update-server/otupdate/openembedded_server/__init__.py
> +    LOG.info('TODO')
Does TODO stand for toradex? It's a bit confusing because we usually use that to symbolize that there is further work to do.

Generally it's also good to provide a little brief description of what is about to be executed (i.e. 'Building server')

2021-09-27 15:11 UTC, Laura-Danielle commented on update-server/otupdate/openembedded_server/__init__.py
> +        # web.post('/server/name', name_management.set_name_endpoint),
Do we want these endpoints or no?

2021-09-27 15:11 UTC, Laura-Danielle commented on update-server/otupdate/ot_utils/file_actions.py
> +    which = subprocess.check_output(['ot-unused-partition']).strip()
I think you can add `.decode()` to line 289 and have the key of the dict be a regular string.

2021-09-27 15:11 UTC, Laura-Danielle commented on update-server/tests/openembedded/test_bmap.py
> +import subprocess
Why are these commented out?

2021-09-27 15:29 UTC, sotaoverride commented on update-server/otupdate/__main__.py
> +    if args.build_system == 'oe':
this is just to make sure the current implementation for update-server doesn't break for ot2
The entry point for update server is the otupdate package. From there, we branch out to run the update server for either openembedded (oe), or buildroot. python -m otupdate defaults to buildroot (keeps the servers from breaking for ot2). python -m otupdate oe would run the server open embedded / ot3

2021-09-27 15:29 UTC, sotaoverride commented on update-server/otupdate/__main__.py
> +# oe_main()
yeah, I can git rid of that.

2021-09-27 15:29 UTC, sotaoverride commented on update-server/otupdate/openembedded_server/__init__.py
> +# , name_management
will take it out

2021-09-27 15:29 UTC, sotaoverride commented on update-server/otupdate/openembedded_server/__init__.py
> +    LOG.info('TODO')
more like just a to do, will go back and see what I was truing to log here.

2021-09-27 15:29 UTC, sotaoverride commented on update-server/otupdate/openembedded_server/__init__.py
> +        # web.post('/server/name', name_management.set_name_endpoint),
I have some name_management stuff made for ot3/openembedded, idea was to uncomment this in a follow up pr

2021-09-27 15:29 UTC, sotaoverride commented on update-server/tests/openembedded/test_bmap.py
> +import subprocess
took the bmap stuff out of this pr, will take this out too

2021-09-27 15:31 UTC, sotaoverride commented on update-server/otupdate/__main__.py
> +    if args.build_system == 'oe':
oh and I was trying to take oe out so the oe parser doesn't complain that it doesn't understand what oe is

2021-10-25 19:45 UTC, closed without merging