WIP: Partially implement #8070
OpenTrons/opentrons-api pull request #8396
Opened 2021-09-23 20:50 UTC by SyntaxColoring

# Overview

# Changelog

# Review requests

# Risk assessment

2021-09-23 20:52 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/router/commands_router.py
> +# todo(mm, 2021-09-23): Should this accept a list of commands, instead of just one?
I think yes, but I got stuck working out what that input model would look like. Just a raw `List[pe_commands.CommandRequest]`? Would we need a bespoke `PostSessionCommandsInput` model?

2021-09-23 20:55 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/router/commands_router.py
> +# todo(mm, 2021-09-23): Should this return a summary, instead of a full command?
I think no, for 2 reasons:

1. For this endpoint specifically, the output corresponds pretty directly to the input. If you don't want to receive a lot of data all at once, you can just...not send a lot of data all at once?
2. I'm growing skeptical of the benefits of summarization for our endpoints in general.

2021-09-23 22:32 UTC, mcous commented on robot-server/robot_server/sessions/router/commands_router.py
> +# todo(mm, 2021-09-23): Should this return a summary, instead of a full command?
Agree. The summarization of commands in the session endpoint should be considered a hack, at best. I'd like to avoid actually shipping that, if at all possible

2021-09-23 22:33 UTC, mcous commented on robot-server/robot_server/sessions/router/commands_router.py
> +# todo(mm, 2021-09-23): Should this accept a list of commands, instead of just one?
I think it's fine to leave alone for now. We'll come back to it depending what the app needs for LPC

2021-09-23 22:35 UTC, mcous approved these changes
Looks like one or two more docstrings fixes, but code looks right to me 🍸

2021-09-23 22:35 UTC, mcous commented on robot-server/robot_server/sessions/router/commands_router.py
> +        "A summary of the added command is returned. "
Per your comment, I think this docsrring might be wrong?

2021-09-23 22:35 UTC, mcous commented on robot-server/robot_server/sessions/router/commands_router.py
> +    """Fix before merge: Docstring."""
TODO

2021-09-23 23:06 UTC, SyntaxColoring commented on robot-server/robot_server/sessions/router/commands_router.py
> +    """Fix before merge: Docstring."""
🤦 ty

2021-09-24 06:54 UTC, sanni-t approved these changes
LGTM other than changes already pointed out

2021-09-24 14:53 UTC, mcous requested changes

2021-09-24 14:53 UTC, mcous commented on robot-server/robot_server/sessions/router/commands_router.py
> +    command_request: pe_commands.CommandRequest,
Oh, oops, this absolutely needs to be `RequestModel[pe_commands.Command]` like you called out in Slack

2021-09-24 16:21 UTC, mcous approved these changes

2021-09-24 16:29 UTC, merged