feat(app): labware position check generic screen dynamic text
OpenTrons/opentrons-api pull request #8451
Opened 2021-10-01 21:41 UTC by jerader

# Overview

closes ticket #8384 

# Changelog

- created `labwarePositionCheckStepDetail` and test
- created `labwarePositionCheckStepDetailModal` and test
- created a protocol fixture for a test
- created a `nestedTextMatcher` file (a copy of the file in labware-library that I was having trouble accessing) in order to fully test text with an html tag

# Review requests

- [ ] review `labwarePositionCheckStepDetailModal` and the test to make sure the styling matches the figma node
- [ ] review `labwarePositionCheckStepDetail` and the test
- [ ] the `labwarePositionCheckStepDetail` test should cover all the dynamic text cases, but running all [4 conditions](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0%3A-Protocol-Upload-Revamp?node-id=4684%3A118077) on the app might be good too
- [ ] review the `nestedTextMatcher` file to make sure it is in an appropriate location since for some reason, I was having a hard time importing the file on the following path: `labware-library/src/labware-creator/components/__testUtils__/nestedTextMatcher.ts`

# Risk assessment

low, behind ff

2021-10-05 13:35 UTC, shlokamin requested changes
Made my way through most of this, haven't gotten to look at some of the tests yet but I will!

Great stuff @jerader! Left some comments but this is great. Thanks for taking this head on, it's honestly wild to me how fast you've picked this all up.

One thing I noticed is that when you expand/contract the viewport when you're in the `See how to tell if the pipette is centered` modal, the images don't stick together, and the text disappears into the image if the viewport is too big. Maybe we just have everything always stick together? 

@emilywools what is your preference?

2021-10-05 13:35 UTC, shlokamin commented on app/src/assets/localization/en/labware_position_check.json
> +  "labware_step_detail_modal_nozzle_image_2_nozzletext": "Nozzle is not centered",
nit: can this be changed to `labware_step_detail_modal_nozzle_image_2_nozzle_text` to match the rest of the snake cased text in this file?

2021-10-05 13:35 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwarePositionCheckStepDetail.tsx
> +import { useProtocolDetails } from '../../RunDetails/hooks'
nit: import order is slightly off — see [this comment](https://github.com/Opentrons/opentrons/pull/8182#discussion_r691253358)

also, since `LabwarePositionCheckStep` is a type you can do:

`import type { LabwarePositionCheckStep } from './types'` so it can be erased at runtime

2021-10-05 13:35 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwarePositionCheckStepDetail.tsx
> +  if (introInfo == null) return null
nit: can this null check be moved up so that both null checks are together? it's a little easier to follow that way:

`if (protocolData == null || introInfo == null ) return null`

2021-10-05 13:35 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwarePositionCheckStepDetail.tsx
> +        marginRight={SPACING_1}
in the standard viewport the text I'm seeing isn't centered — can we use flexbox instead justify the content center?

also, since the text here will be rendered on top, and then we'll have to render the labware component, the svg of the tip/nozzle, and the jog controls, it's probably worth it to extract this detail text you have here into it's own component (within the same file should be fine) so we can do something along the lines of:

```js
 return (
    <React.Fragment>
      {showLabwarePositionCheckStepDetailModal && (
        <LabwarePositionCheckStepDetailModal
          onCloseClick={() => setLabwarePositionCheckStepDetailModal(false)}
        />
      )}
      <StepDetailText {...someProps} />
      <LabwareRender {...someProps} />
      <JogControls {...someProps} />
      
    </React.Fragment>
  )
```

does that make sense?

2021-10-05 13:35 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwarePositionCheckStepDetailModal.tsx
> +import labwarePositionCheckModalImage5 from '../../../assets/images/labware_position_check_modal_nozzle_or_tip_image3.svg'
nit: import order (see comment above). man i wish this could be enforced by a linter and we could just hit a button to auto format imports. its annoying this is something we even have to think about

2021-10-05 13:35 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/__testUtils__/nestedTextMatcher.ts
> +
very cool! can this be moved into the components library? if you rebase on top of edge you should see the other utils moved over there:

https://github.com/Opentrons/opentrons/blob/8c008c41ce4dc093770343f8edac18cc69ca4c51/components/src/testing/utils/matchers.ts

2021-10-05 13:35 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/__tests__/GenericStepScreen.test.tsx
> +} from '@opentrons/components/__utils__'
if you rebase on top of edge, these utils have moved into components library: https://github.com/Opentrons/opentrons/blob/8c008c41ce4dc093770343f8edac18cc69ca4c51/components/src/testing/utils/matchers.ts

2021-10-05 13:35 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/__tests__/GenericStepScreen.test.tsx
> +  )
since after yesterdays standup we decided we're gonna change the the interface of `renderWithProviders` to return a tuple, after you rebase on top of edge this will have to be changed to:

```js
return renderWithProviders(
    <StaticRouter>
      <GenericStepScreen {...props} />
    </StaticRouter>
  )[0]
```

if you grep for `renderWithProviders ` once you rebase you'll see!

2021-10-05 13:35 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/__tests__/LabwarePositionCheckStepDetail.test.tsx
> +import { nestedTextMatcher } from '../__testUtils__/nestedTextMatcher'
nit: import order

2021-10-05 14:14 UTC, jerader commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwarePositionCheckStepDetail.tsx
> +        marginRight={SPACING_1}
yup makes sense to me! Definitely a lot more organized this way

2021-10-07 19:47 UTC, shlokamin approved these changes
Heck yeah, great work @jerader! huge props for how well this is tested too 😄

2021-10-07 19:47 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/__tests__/LabwarePositionCheckStepDetail.test.tsx
> +import '@testing-library/jest-dom'
since this is included in `scripts/setup-global-imports.js` i dont think we need this here

2021-10-07 19:47 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/__tests__/StepDetailText.test.tsx
> +} from '@opentrons/components/src/testing/utils'
these should be able to be imported straight from `@opentrons/components` right?

2021-10-07 20:43 UTC, merged