test(app): Protocol Upload Revamp e2e test case
OpenTrons/opentrons-api pull request #8507
Opened 2021-10-11 21:52 UTC by reachojhaneha

**Overview**
Add the ability to drive the installed run app for end to end testing of the feature Protocol Upload revamp(PUR).

- Use python, selenium(4), and pytest to execute tests against the installed run app.
- Roughly use the[ Page Object Model](https://www.toolsqa.com/selenium-webdriver/page-object-model/)
- See [Notes in README](https://github.com/Opentrons/opentrons/compare/app-testing-installed-python-selenium?expand=1#diff-c8553976128c5a29097f45c16088ceddb354664d655950da556cd6b8b380a5acR7)

**TestCase Scenarios:** 

- Happy path scenario for PUR - connecting to robot->landing on protocol page->uploading a protocol -> verifying "setup for run page"
- Multiples of a module - verifying that Moam link is available when a protocol with MoaM is uploaded
- Gen 1 pipette - Links related to Gen 1 pipette and no modules are uploaded.
- No modules uploaded testcases
All new code with no dependencies outside of the new app-testing directory.

**Risk assessment**
There is no risk to any other module in the repository. The app-testing folder is self contained.

2021-10-11 23:51 UTC, y3rsh requested changes
# 🎉
### Awesome work @reachojhaneha only a little cleanup remaining.

2021-10-11 23:51 UTC, y3rsh commented on app-testing/conftest.py
> +    }
There is no need to create a whole new fixture.  Please add it to the above fixture like
```python
"python1": Path(
            Path(__file__).resolve().parent,
            "files/protocol/python1/test_drive.py",
        ),
"protocoluploadjson": Path(
            Path(__file__).resolve().parent,
            "files/protocol/json1/upload_protocol.json",
        ),
```

2021-10-11 23:51 UTC, y3rsh commented on app-testing/gen/electron/buildflags/buildflags.h
> +#endif  // ELECTRON_BUILDFLAGS_BUILDFLAGS_H_
Is this added by mistake?

2021-10-11 23:51 UTC, y3rsh commented on app-testing/src/menus/protocol_file.py
> +    file_drag_locator: tuple = (By.ID, "file_input")
All of the `tuple` type annotations will need to be changed.  Mypi corrected my original version of these from `tuple` to `Tuple[str, str]` 
Make sure to run `make check` it should be complaining about these.

2021-10-11 23:51 UTC, y3rsh commented on app-testing/src/pages/module_setup.py
> +"""Model for the screen of module setup"""
Need a `.` at the end, `make check` will catch 😊

2021-10-11 23:51 UTC, y3rsh commented on app-testing/tests/protocol_upload_test.py
> +        protocol_upload.click_enable_pur_feature()
Do you need to click this toggle as a part of the test?  If not you may skip this with a configuration change.  All you need are these 2 lines above line [43 ](https://github.com/Opentrons/opentrons/pull/8507/files#diff-d7380cd6709cc0c827d450c487226a16f61cfe9f6d20237ee49e73c1b6e1e77aR43)
```python
# use new protocol tab
ot_application.config["devInternal"] = {"preProtocolFlowWithoutRPC": True}
```

2021-10-11 23:51 UTC, y3rsh commented on app-testing/tests/protocol_upload_test.py
> +def test_protocol_upload(
Need a docstring describing the test.

2021-10-11 23:51 UTC, y3rsh commented on app-testing/tests/protocol_upload_test.py
> +) -> None:
This test requires a robot running or the dev emulator correct?   Including the below validates it is running so the test will fail fast if it is not.
````python
    robot = OtRobot()
    # expecting docker emulated robot
    assert robot.is_alive(), "is a robot available?"
````

2021-10-11 23:51 UTC, y3rsh commented on app-testing/src/pages/robot_calibration.py
> +from enum import Enum
Unused import, again `make check` will call these out 😊

2021-10-25 16:12 UTC, reachojhaneha commented on app-testing/tests/protocol_upload_test.py
> +        protocol_upload.click_enable_pur_feature()
Yes, i have to toggle the PUR feature , once it is out in production, i will remove these 3 lines.

2021-10-29 14:04 UTC, y3rsh requested changes
Looks great but for a few small changes to meet linting.  Try to use the docstrings to describe the purpose of the element from the user perspective.  The code documents clearly the how of the locating.  docstrings for functions that  already have descriptive name are awkward... I suggest be brief `"""Click module."""`.  Most of these wont be helpful but we want consistency.  If there is any unique behavior or state dependency for an element, definitely mention that.

2021-10-29 14:04 UTC, y3rsh commented on app-testing/src/pages/moam_pur.py
> +"""Class for Moam Setup flow."""
Please move these lines in your page objects directly under the class declaration so it becomes a docstring.

2021-10-29 14:04 UTC, y3rsh commented on app-testing/src/pages/module_setup.py
> +        scroll: WebElement = WebDriverWait(self.driver, 2).until(
`scroll` is a confusing name for the element to scroll to in this context.  I thought for a second we were grabbing the scroll bar or something.  I am cool with a generic short name here but I think `mag_module` `target` or `element` would be more optimal.

2021-10-29 14:04 UTC, y3rsh commented on app-testing/src/pages/module_setup.py
> +    def get_proceed_to_labware_setup(self) -> WebElement:
A lot of the functions are missing a docstring.  Hopefully `make check` is flagging this.

2021-11-01 18:37 UTC, b-cooper approved these changes
Looks good to me 🧪

2022-02-16 21:49 UTC, shlokamin commented on app-testing/files/protocol/python1/moam_pur.json
>      "author": "AA BB",
how come this json file is in a folder called `python1`?

2022-02-16 21:49 UTC, shlokamin commented on app-testing/tests/protocol_upload_test.py
> +        left_menu = LeftMenu(driver)
is `LeftMenu` supposed to be the nav bar? if so can we name it `NavBar` so it matches our react component naming? doesnt matter a ton cuz we'll have to change this after 5.1 but consistency is nice

2022-02-16 21:49 UTC, shlokamin commented on app-testing/tests/protocol_upload_test.py
> +        left_menu = LeftMenu(driver)
how come this line is repeated? 

```
left_menu = LeftMenu(driver)
```

2022-02-16 21:49 UTC, shlokamin commented on app-testing/tests/protocol_upload_test.py
> +        drag_and_drop_file(input, test_protocols["protocoluploadjson"])
it looks like the protocol file for `protocoluploadjson` has no commands. don't we want to test LPC on a real protocol?

2022-02-16 21:49 UTC, shlokamin commented on app-testing/tests/protocol_upload_test.py
> +        assert labware_position_check.get_labware_success_toast().is_displayed()
it doesn't look like we ever validate the contents of the summary screen (i.e. what offsets we're about to apply. ex, if we jog twice to the left by 1mm on a piece of labware, we'd expect to see this offset show up in the summary screen. that's probably an important thing to test right?

2022-02-16 21:49 UTC, shlokamin commented on app-testing/tests/protocol_upload_test.py
> +        assert labware_position_check.get_labware_success_toast().is_displayed()
also, should we be testing that after we apply offsets that they show up in the labware setup step?

2022-03-02 00:46 UTC, reachojhaneha commented on app-testing/src/pages/moam_pur.py
> +"""Class for Moam Setup flow."""
this is done

2022-03-02 00:55 UTC, reachojhaneha commented on app-testing/src/pages/module_setup.py
> +        scroll: WebElement = WebDriverWait(self.driver, 2).until(
this is changed to toggle

2022-03-02 01:11 UTC, reachojhaneha commented on app-testing/src/pages/module_setup.py
> +    def get_proceed_to_labware_setup(self) -> WebElement:
i have added the docstring

2022-03-02 01:11 UTC, reachojhaneha commented on app-testing/files/protocol/python1/moam_pur.json
>      "author": "AA BB",
moved the protocols to json folder

2022-03-02 01:20 UTC, reachojhaneha commented on app-testing/tests/protocol_upload_test.py
> +        left_menu = LeftMenu(driver)
a lot of this code will be rewritten with 5.1, as LeftMenu is being used by other tests out of PUR, i am not in favor of changing the LeftMenu class

2022-03-02 01:20 UTC, reachojhaneha commented on app-testing/tests/protocol_upload_test.py
> +        left_menu = LeftMenu(driver)
this is corrected

2022-03-02 01:20 UTC, reachojhaneha commented on app-testing/tests/protocol_upload_test.py
> +        drag_and_drop_file(input, test_protocols["protocoluploadjson"])
this protocol has commands

2022-03-02 01:21 UTC, reachojhaneha commented on app-testing/tests/protocol_upload_test.py
> +        assert labware_position_check.get_labware_success_toast().is_displayed()
So, we decided to test the deckmap offset settings which inturn tests the summary screen. the asserts have been added to the tests

2022-03-08 19:15 UTC, shlokamin approved these changes
Approved pending changing DOM ids to be unique and validating labware offsets for ALL labware (not just the first one)

2022-03-10 20:53 UTC, y3rsh approved these changes
Approved with the same caveat as @shlokamin

2022-03-14 16:22 UTC, reachojhaneha commented
Now, the test checks all the labware offsets in the PR

2022-03-14 17:08 UTC, merged