feat(app): reveal jog controls
OpenTrons/opentrons-api pull request #8528
Opened 2021-10-14 20:44 UTC by jerader

closes #8382

# Overview

closes #8382 

# Changelog

- adds jog controls to `LabwarePositionCheckStepDetail` component 
- converts all jog control buttons + the `radiobox-marked` icon to be blue

# Review requests

- make sure the styling matches [figma](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0%3A-Protocol-Upload-Revamp?node-id=4327%3A835599)
- review all AC

# Risk assessment

low, behind ff

2021-10-14 21:03 UTC, jerader commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwarePositionCheckStepDetail.tsx
> +            <Flex justifyContent={JUSTIFY_CENTER} marginTop={'-8rem'}>
i added negative margins in various locations because the Deckmap extended too far down and I was having trouble fixing it. However, it turns out if you add a `zIndex` to specify the element to go to the top, it fixes the issue of the buttons being un-clickable! 😃

2021-10-18 22:14 UTC, shlokamin requested changes
This is pretty close! just a few things: 

- In the standard viewport the buttons bleed into the jump size column (see screenshot attached)
<img width="866" alt="Screen Shot 2021-10-18 at 3 45 14 PM" src="https://user-images.githubusercontent.com/5788529/137812962-9eed24d2-ba81-4db2-aa35-8946614b2a11.png">

- It looks like you modified the `RadioGroup` component in components library which is widely used throughout the frontend ecosystem. That means that this also affects on PD + LL in addition to the run app, which I don't think we want right now

- Rather than using negative margin to crop the deckmap, you can use the [SVG `viewBox`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox) property which should be a bit cleaner

2021-10-18 22:14 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwarePositionCheckStepDetail.tsx
> +            <Flex justifyContent={JUSTIFY_CENTER} marginTop={'-8rem'}>
gocha, i think a better solution would be to modify the [`viewBox`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox) of the deckmap, that way we don't have to worry about applying margin to other components,

2021-10-18 22:14 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/__tests__/LabwarePositionCheckStepDetail.test.tsx
> +      expect(getByRole('link', { name: 'Reveal jog controls' })).toBeTruthy()
`getByRole('link', { name: 'Reveal jog controls' })` should be sufficient!

2021-10-18 22:14 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/__tests__/LabwarePositionCheckStepDetail.test.tsx
> +      expect(screen.queryByText('Mock Jog Controls')).not.toBeNull()
same deal here, this can just be `getByText('Mock Jog Controls'))`

2021-10-18 22:14 UTC, shlokamin commented on components/src/forms/RadioGroup.tsx
>            </div>
this component is also used in PD and LL, which means that radio buttons used by them will now show up blue (which we don't know that we want yet)

2021-10-19 17:18 UTC, jerader commented
Hi @emilywools , please review the following and let me know if they look ok! On Friday we discussed the different color combinations for the Jump Size icons and you initially wanted only the selected button to be Blue. However, turns out its a little tricky to write that since it is also used throughout PD and LL. Is what I have now okay? Additionally, I think what I have now makes the unselected buttons look clickable (as opposed to having them black with the selected one blue) Let me know 😄 

<img width="548" alt="Screen Shot 2021-10-19 at 12 48 15" src="https://user-images.githubusercontent.com/66035149/137955768-99285575-4143-4b8b-91f8-e15ce8611b33.png"
<img width="569" alt="Screen Shot 2021-10-19 at 13 14 55" src="https://user-images.githubusercontent.com/66035149/137959407-709071f1-b938-400c-8aa6-44604f188efa.png">
>

2021-10-19 17:56 UTC, shlokamin approved these changes
LGTM! Nice work @jerader!

2021-10-19 18:18 UTC, emilywools approved these changes
this looks great!! thank you

2021-10-19 20:31 UTC, merged