feat(app): LPC final summary screen scaffolding
OpenTrons/opentrons-api pull request #8575
Opened 2021-10-21 13:46 UTC by jerader

# Overview

addresses #8219, this creates the final summary screen scaffolding

# Changelog

- created `SummaryScreen` and `LabwareOffsetsSummary` components

# Review requests

- review styling to make sure it matches the [figma](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0%3A-Protocol-Upload-Revamp?node-id=4071%3A20429)

# Risk assessment

low, behind ff

2021-10-25 20:53 UTC, shlokamin requested changes
good stuff, really cool to see this screen come together! left a few comments, also:
- it looks like we're getting an error in our console bcuz some of the `Flex` elements dont have keys. you can just assign the key to the list index (i think you already do that elsewhere in this PR)
- in the standard viewport elements are scrunched together, i think that `flexBasis` + `flexShrink` can help you assign a min width for the flex items, and `minWidth` for the non flex items
![Screen Shot 2021-10-25 at 4 25 33 PM](https://user-images.githubusercontent.com/5788529/138769228-d972eace-472f-4c41-b872-904cf8027cee.png)

2021-10-25 20:53 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwareOffsetsSummary.tsx
> +import { useTranslation } from 'react-i18next'
this guy should go above `@opentrons/components` imports

2021-10-25 20:53 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwareOffsetsSummary.tsx
> +            flexDirection={DIRECTION_COLUMN}
boxes dont use flexbox, so this `flexDirection` property doesnt actually do anything. i think we can delete it

2021-10-25 20:53 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwareOffsetsSummary.tsx
> +            flexDirection={DIRECTION_COLUMN}
same deal here

2021-10-25 20:53 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwareOffsetsSummary.tsx
> +            flexDirection={DIRECTION_COLUMN}
same thing here

2021-10-25 20:53 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/__tests__/LabwarePositionCheck.test.tsx
> +  // })
rather than commenting you can to `it.todo` instead i think

2021-10-27 14:50 UTC, shlokamin requested changes

2021-10-27 14:50 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwareOffsetsSummary.tsx
> +        width="106%"
this `width="106%"` comes off as a magic number to me. is this intentional? ideally we'd just have this parent take up as much space is needed by its contents

2021-10-27 14:50 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwareOffsetsSummary.tsx
> +              color={C_DISABLED}
it looks like in figma this color should be `C_MED_GRAY` (`#9b9b9b`)

generally we only wanna use `C_DISABLED` when there is text that is disabled

2021-10-27 14:50 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwareOffsetsSummary.tsx
> +              color={C_DISABLED}
same thing here

2021-10-27 14:50 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwareOffsetsSummary.tsx
> +              color={C_DISABLED}
same thing here

2021-10-27 14:50 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwareOffsetsSummary.tsx
> +        width="106%"
to do that, we can just do `flex={'auto'}`, this will set the `flex-basis` property to auto, which means remaining space will be distributed depending on the content size of each element (rather than divided evenly)

2021-10-27 14:50 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwareOffsetsSummary.tsx
> +        <Flex flexDirection={DIRECTION_ROW} justifyContent={JUSTIFY_CENTER}>
i dont think this `justifyContent={JUSTIFY_CENTER}` is doing anything right?

2021-10-27 14:50 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwareOffsetsSummary.tsx
> +            flex={'1 1 30%'}
this can be changed to `flex={'auto'}` too, that way space will be assigned based on the size of the contents so we dont have to do that math

2021-10-27 14:50 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwareOffsetsSummary.tsx
> +            flex={'1 1 40%'}
same thing re: `flex={'auto'}`

2021-10-27 14:50 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwareOffsetsSummary.tsx
> +            flex={'1 1 30%'}
same thing re: `flex={'auto'}`

2021-10-27 14:50 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwareOffsetsSummary.tsx
> +                  </Text>
can we change the `marginRight={'0.15rem'}` to `marginRight={SPACING_1}` and can we change the `marginRight={'0.4rem'}` to `marginRight={SPACING_2}`?

i think they match figma close enough and that way we're using our standard spacing system

2021-10-27 14:50 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/SectionList.tsx
> -      marginLeft={SPACING_5}
ayo nice!

2021-10-27 14:50 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/SummaryScreen.tsx
> +        <Flex flex={'1 1 40%'} flexDirection={DIRECTION_COLUMN}>
same thing re: flex={'auto'} so we dont have to do the math

2021-10-27 14:50 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/SummaryScreen.tsx
> +        <Flex flex={'1 1 80%'} marginRight={SPACING_4}>
same thing re: flex={'auto'} so we dont have to do the math

2021-10-29 19:36 UTC, shlokamin requested changes

2021-10-29 19:36 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/LabwareOffsetsSummary.tsx
> +                <Flex marginBottom={SPACING_3} css={FONT_BODY_1_DARK}>
still getting this error in the console: `Warning: Each child in a list should have a unique "key" prop.`

if you add a key here on line 148 it should go away

2021-10-29 19:36 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/GenericStepScreen.tsx
> +        <LabwarePositionCheckStepDetail selectedStep={props.selectedStep} />
right now this `flex={'1 1 60%'}` isn't doing anything, i thought it was cuz `LabwarePositionCheckStepDetail` has a fixed width, but even if i remove that width,`flex={'1 1 60%'}` doesn't seem to do anything and honestly im not sure how the ratio gets preserved. 

i guess lets just get rid of the `flex={'1 1 60%'}` for now? I wonder if theres something else with a fixed with lower in the tree thats making the flex element grow...

2021-10-29 19:36 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/SummaryScreen.tsx
> +          <DeckMap completedLabwareIdSections={labwareIds} />
looks like the deckmap component is too big compared to whats on figma, i think it should be the same size as the deckmap in the generic step screen so its a consistent UX

2021-11-01 13:37 UTC, jerader commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/GenericStepScreen.tsx
> +        <LabwarePositionCheckStepDetail selectedStep={props.selectedStep} />
you're right, it doesn't seem to do anything, thanks for noticing that!

2021-11-01 13:47 UTC, jerader commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/SummaryScreen.tsx
> +          <DeckMap completedLabwareIdSections={labwareIds} />
Yeah, i took a closer look and you're right. Does this look better?

<img width="830" alt="Screen Shot 2021-11-01 at 09 46 24" src="https://user-images.githubusercontent.com/66035149/139681650-43d97257-5281-4f22-85be-71617c023537.png">

2021-11-04 18:14 UTC, shlokamin approved these changes
LGTM! sorry for the long delay @jerader!

2021-11-04 19:08 UTC, merged