feat(app): Run Details Command List
OpenTrons/opentrons-api pull request #8682
Opened 2021-11-09 17:38 UTC by jerader

# Overview

closes #8368 

# Changelog

- creates `CommandList` and `ProtocolSetupInfo` components 
- adds a commands fixture json file to stub in command text

# Review requests

- review AC from ticket
- make sure `ProtocolSetupInfo` matches the [figma](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0%3A-Protocol-Upload-Revamp?node-id=5629%3A145096)
- there was a lot of stubbing in v6 commands throughout writing this so call out any weird things you see. 

# Risk assessment

low, behind ff

2021-11-11 18:05 UTC, smb2268 requested changes
This is looking great so far @jerader! I added a few minor code comments but also noticed a few styling discrepancies from the figma:

1. Missing protocol run status banner at the top of the screen when a step failed (should be red - Protocol Run Failed banner)
2. The Protocol Steps title should be a larger font and bolded 
3. The Protocol Setup banner/dropdown should have a grey background to match the styling of an anticipated step

2021-11-11 18:05 UTC, smb2268 commented on app/src/organisms/RunDetails/ProtocolSetupInfo.tsx
> +    } else if (moduleName != null && moduleName.includes('Thermocycler')) {
this can be replaced by
```suggestion
    } else if (moduleName?.includes('Thermocycler')) {
```

2021-11-11 18:05 UTC, smb2268 commented on app/src/organisms/RunDetails/ProtocolSetupInfo.tsx
> +    SetupCommand.result?.definition.metadata.displayName.includes('Trash')
the linter prefers
```suggestion
    (SetupCommand.result?.definition.metadata.displayName.includes('Trash')) ?? false
```

2021-11-11 18:05 UTC, smb2268 commented on app/src/organisms/RunDetails/CommandList.tsx
> +              else if (command.id === props.anticipated)
I think this logic might be incorrect -- `props.anticpated` will be equal to the command id of the first anticipated step, but for styling we'll want each anticipated step to have to have a `queued` status. Maybe it would be easier to pass in the index of the first anticipated step for this prop and say 
`if (index >= props.anticipated) 
{ legacyCommandTypeStatus = 'queued' }`

2021-11-11 18:05 UTC, smb2268 commented on app/src/organisms/RunDetails/CommandList.tsx
> +              let legacyCommandTypeStatus = 'queued' as Status
Since the `legacyCommandTypeStatus` will be used even after we remove the stubbed out `legacyCommands`, can you change the name of this variable? Maybe something like `commandRunStatus`

2021-11-11 21:11 UTC, jerader commented on app/src/organisms/RunDetails/CommandList.tsx
> +              else if (command.id === props.anticipated)
Wow using index made this easy to fix! thanks for the suggestion 😄

2021-11-12 16:33 UTC, b-cooper reviewed
This is looking good overall, there are a few housekeeping things to clean up so we can efficiently un-stub things soon

2021-11-12 16:33 UTC, b-cooper commented on app/src/assets/localization/en/run_details.json
> +  "load_pipette_protocol_setup": "Load {{pipette_name}} in <span>{{mount_name}}</span> Mount",
is this <span></span> necessary?

2021-11-12 16:33 UTC, b-cooper commented on app/src/organisms/RunDetails/CommandItem.tsx
>      <Flex>
is this outer `Flex` redundant now?

2021-11-12 16:33 UTC, b-cooper commented on app/src/organisms/RunDetails/ProtocolSetupInfo.tsx
> +  let SetupCommandText
this should be `setupCommandText`. PascalCase should only be used for components. This is a `React.ReactNode`(could be an instance of a component), which can be captured by a normal camelCase variable name.

The same goes for the `SetupCommand` it should be `setupCommand`

2021-11-12 16:33 UTC, b-cooper commented on app/src/organisms/RunDetails/CommandItem.tsx
> +  commandText?: JSX.Element
This type should probably be React.ReactNode

2021-11-12 16:33 UTC, b-cooper commented on app/src/organisms/RunDetails/CommandItem.tsx
> +  queued: { border: 'no-border', backgroundColor: C_NEAR_WHITE },
I think these 'no-border''s should be 'none'

2021-11-12 16:33 UTC, b-cooper commented on app/src/organisms/RunDetails/CommandList.tsx
> +              ></Icon>
Components with no children should be self closing. e.g. `<Icon ... />`

2021-11-12 16:33 UTC, b-cooper commented on app/src/organisms/RunDetails/CommandList.tsx
> +            <strong>{t('protocol_steps')}</strong>
instead of using strong to bold text, we should use the `fontWeight`style prop and pass in one of our `FONT_WEIGHT_xxxx` constants

2021-11-12 16:33 UTC, b-cooper commented on app/src/organisms/RunDetails/index.tsx
> +      <Flex key={commandId[commandIdIndex]}>
this key should be unnecessary

2021-11-12 16:33 UTC, b-cooper commented on app/src/organisms/RunDetails/index.tsx
> +  const commandId = fixtureCommands.commands.map(command => command.id)
nit: if a variable holds an array of a noun, lets name it the plural of that noun for clarity and consistency.  e.g. `commandIds`

2021-11-12 16:33 UTC, b-cooper commented on app/src/organisms/RunDetails/CommandList.tsx
> +              if (command.id === props.inProgress) commandTypeStatus = 'running'
Each command has it's own `status` property. We should be able to avoid all of these props and `if/else` business  just by branching on the 4 statuses 'queued' | 'running' | 'succeeded' | 'failed'. This can follow the reconciling anticipated/live commands work that @smb2268 is working on now.

2021-11-12 16:33 UTC, b-cooper commented on app/src/organisms/RunDetails/CommandList.tsx
> +                command.id[index] >= props.anticipated[index]
This is comparing two characters by parsing a single character out of the id strings of two commands.  We should never be parsing command id strings, they should be treated as opaque identifiers and compared via `===`

2021-11-12 16:33 UTC, b-cooper commented on app/src/organisms/RunDetails/CommandList.tsx
> +                    {command.data.legacyCommandText}
now that we're using the adapter, you should be able to use `command.params.legacyCommandText`

2021-11-12 16:33 UTC, b-cooper commented on app/src/organisms/RunDetails/CommandList.tsx
> +                    paddingTop={SPACING_1}
these 4 padding values can be collapse to `padding={`${SPACING_1} ${SPACING_2}`}`

2021-11-12 16:33 UTC, b-cooper commented on app/src/organisms/RunDetails/CommandList.tsx
> +                    flex={'auto'}
I have a feeling this `flex={'auto'}` is extraneous

2021-11-12 16:33 UTC, b-cooper commented on app/src/organisms/RunDetails/CommandText.tsx
> +  commandText?: JSX.Element
This should be `React.ReactNode`

2021-11-12 16:33 UTC, b-cooper commented on app/src/organisms/RunDetails/ProtocolSetupInfo.tsx
> +        command =>
should be able to use a type predicate here to get rid of this ts-expect-error


```
(command): command id LoadModuleCommand => ... 
```

2021-11-12 16:33 UTC, b-cooper commented on app/src/organisms/RunDetails/ProtocolSetupInfo.tsx
> +    } else if (moduleName?.includes('Thermocycler')) {
instead of checking for a hard coded string here, can we check if `moduleModel` is a thermocycler type?

2021-11-12 16:33 UTC, b-cooper commented on app/src/organisms/RunDetails/ProtocolSetupInfo.tsx
> +      paddingTop={SPACING_1}
padding short hand works here too `padding={"<vertical> <horizontal>"}`

2021-11-12 16:40 UTC, smb2268 commented on app/src/organisms/RunDetails/CommandList.tsx
> +        {props.isFailed ? (
In the figma this banner can have three statuses: Cancelled, Failed, and Complete. Complete will have different styling than the other two

2021-11-12 16:45 UTC, smb2268 commented on app/src/organisms/RunDetails/CommandList.tsx
> +              if (command.id === props.inProgress) commandTypeStatus = 'running'
I've actually already made this change on my branch, so it's fine with me if you leave this as is!

2021-11-16 23:22 UTC, smb2268 approved these changes
Fixed all failing tests and did a test run on the robot - all looking good 🎉

2021-11-16 23:39 UTC, merged