refactor(protocol-engine): Support adding labware offsets to a ProtocolEngine.
OpenTrons/opentrons-api pull request #8730
Opened 2021-11-12 02:57 UTC by SyntaxColoring

# Overview

# Changelog

# Review requests

# Risk assessment

2021-11-12 14:55 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/load_labware.py
> +            offset=loaded_labware.offset,
As discussed, this should by an offset ID rather than the offset itself; otherwise we'll have this resoucre in state in multiple places, leaving the source of truth ambiguous (which is the same problem we currently have with labware definitions)

2021-11-12 14:55 UTC, mcous commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +    offset: Optional[LabwareOffset]
ID rather than full resource

2021-11-12 14:55 UTC, mcous commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +        return self.state_view.labware.get_labware_offsets()
I don't think either of these methods are necessary. `engine.state_view` is already a public interface

2021-11-12 14:55 UTC, mcous commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +        self._action_dispatcher.dispatch(AddLabwareOffsetAction(labware_offset))
I would make three changes here:

- Add a resource creation timestamp
- Don't add a `to_labware_offset` method to `LabwareOffsetCreate`
    - This allows `LabwareOffsetCreate` to focus on schema/data modeling without caring about how to handle that data
    - In my experience, creating separate data mappers is more maintainable in the long run
- Follow the pattern in `add_command`, and add the generated ID, generated timestamp, and create data to the action
    - When the action hits the store, the store can create, represent, and return the resource as it sees fit
    - The store, thanks to its testing strategy, will be a more maintainable place for request data > to resource mapping logic to live

2021-11-12 19:53 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_runner/smoke_tests/test_protocol_runner.py
> +        offsetId=None,
Calling this out for CPX review.

2021-11-12 20:25 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/types.py
> +    # it this whole record, which the 3D vector is part of?
Calling this out for CPX review.

I think I want to rename this `offset` field to `vector`.

2021-11-15 15:05 UTC, mcous requested changes
Looking good, but missing:

- Test coverage
- Creating the engine with offsets

2021-11-15 15:05 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/load_labware.py
> +    # string in the OpenAPI spec, instead of a required nullable string.
If adding a default value of `None` makes this behave, let's do it and call the TODO resolved

2021-11-15 15:05 UTC, mcous commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +        offset = self._state_store.labware.find_applicable_labware_offset(
Would this selector be sufficient if it just returned the offset ID, instead? Would allow us to get rid of the conditional below

2021-11-15 15:05 UTC, mcous commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +    def add_labware_offset(self, request: LabwareOffsetCreate) -> LabwareOffset:
Missing a test for this collaborator

2021-11-15 15:05 UTC, mcous commented on api/src/opentrons/protocol_engine/state/labware.py
> +    def get_labware_offset(self, labware_offset_id: str) -> LabwareOffset:
Looks like we've got an uncovered branch for this method

2021-11-15 15:05 UTC, mcous commented on api/src/opentrons/protocol_engine/state/labware.py
> +    def get_labware_offsets(self) -> List[LabwareOffset]:
Is there a test for this selector?

2021-11-15 15:05 UTC, mcous commented on api/src/opentrons/protocol_engine/state/labware.py
> +    def find_applicable_labware_offset(
Looks like we don't have a test for this method

2021-11-15 15:05 UTC, mcous commented on api/src/opentrons/protocol_engine/types.py
> +    # it this whole record, which the 3D vector is part of?
Please do

2021-11-15 15:10 UTC, mcous commented on api/tests/opentrons/protocol_runner/smoke_tests/test_protocol_runner.py
> +        offsetId=None,
I think this requires the ability to create the engine with offsets

2021-11-15 16:40 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/load_labware.py
> +    # string in the OpenAPI spec, instead of a required nullable string.
It looks like it sort of behaves.

```python
offsetId: Optional[str] = Field(
    None,
    description="...",
)
```

This appears to generate OpenAPI where `offsetId` is omittable, but if it's there, it's a string (and not `null`).

Which is not really what we want. Very frustrating and concerning that Pydantic makes us conflate:

* fields that are omittable in the JSON spec
* fields that are nullable in the JSON spec
* fields that are omittable when we're constructing models in our Python code
 
But I guess this is the best we can easily do for now.

2021-11-15 18:06 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/labware.py
> +    def get_labware_offsets(self) -> List[LabwareOffset]:
Previously no. Added now.

2021-11-15 18:11 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +        offset = self._state_store.labware.find_applicable_labware_offset(
Yeah, that would work too.

Any time I'm implementing some kind of "find a matching value in this dict" thing, I softly prefer doing it this way, where the matching ID and value are both returned together. Just to save the caller from having to do a redundant lookup.

2021-11-15 18:57 UTC, mcous commented on api/src/opentrons/protocol_engine/execution/equipment.py
> +        offset = self._state_store.labware.find_applicable_labware_offset(
Right, but the value (the full `LabwareOffset`) model is not used here or anywhere else

2021-11-15 19:11 UTC, mcous approved these changes

2021-11-15 19:11 UTC, mcous commented on api/src/opentrons/protocol_engine/state/labware.py
> +                assert command.result.offsetId in self._state.labware_offsets_by_id
I wouldn't put an assertion here; raises in the reducer are pretty difficult and should be avoided. Additionally, this assertion is kinda confusing, because it doesn't guard against any ill defined behavior in this function itself. I'm pretty sure our bases are already covered by the `LabwareOffsetDoesNotExistError` error raised in the labware selector

2021-11-15 19:11 UTC, mcous commented on api/src/opentrons/protocol_engine/state/labware.py
> +        assert labware_offset.id not in self._state.labware_offsets_by_id
Same story about raises in the reducer. This would be better moved to a selector, where duplicate IDs would actually be a logic error (ambiguity around which resource to return). The reducer will work just fine if there are duplicate IDs

2021-11-15 19:11 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +                offsetId=None,
Seems to me like we could use the same `find_applicable_labware_offset` selector here if we can somehow give the command mapper access to a PE state view. Should be doable, might require some restructuring of our testing strategy

2021-11-15 19:11 UTC, mcous commented on api/tests/opentrons/protocol_engine/execution/test_equipment_handler.py
> +            vector=LabwareOffsetVector(x=1, y=2, z=3),
Nothing except `id` is used in the test / by the subject. I'd call this a signal to change `find_applicable_labware_offset` to `find_applicable_labware_offset_id`

2021-11-15 19:51 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/load_labware.py
> +    # string in the OpenAPI spec, instead of a required nullable string.
I think this is more of an OpenAPISpec issue than a Pydantic issue. Full support for nullable fields (in a consistent, compatible with JSONSchema situation) only landed in OASv3.1, released less than a year ago. This will be a breaking change in Pydantic, [not likely to land until v2](https://github.com/samuelcolvin/pydantic/pull/1611#issuecomment-687825826).

For now (and honestly probably in the future), I think building an API where "missing" is treated differently than `null` is a really difficult client experience, so I'm very fine with (most of) the conflation

2021-11-15 22:19 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/labware.py
> +                assert command.result.offsetId in self._state.labware_offsets_by_id
Noted. Let's discuss this more outside of this PR.

2021-11-15 22:27 UTC, merged

2021-11-15 22:28 UTC, SyntaxColoring commented
Merging this to move on to some meatier stuff that this was blocking, but there are good thoughts above that we should come back to.