refactor(engine): add `home` command
OpenTrons/opentrons-api pull request #8745
Opened 2021-11-12 19:51 UTC by mcous

## Overview

See title. Necessary for LPC if the user experiences a collision

## Changelog

- Add home command
- Add state reaction to clear last accessed well upon home

## Review requests

- [ ] Code looks good
- [ ] Tests look good
- [ ] Works on robot

## Risk assessment

Low

2021-11-12 21:27 UTC, SyntaxColoring approved these changes
Mostly looks good to me. One API concern that might matter?

2021-11-12 21:27 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/execution/movement.py
> +            hardware_axes = [MOTOR_AXIS_TO_HARDWARE_AXIS[a] for a in axes]
If `axes` is `[]` (not `None`), it looks like this will home all motors, but the docstring makes it sound like it should no-op.

2021-11-12 21:27 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_engine/execution/test_movement_handler.py
> +    """It should propogate a must home error."""
```suggestion
    """It should propagate a must home error."""
```

⭕ 🅰️

2021-11-12 21:27 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/commands/home.py
> +    )
Are there any ordering guarantees here? Like, if you do `X, Y`, is that different from `Y, X`?

Actually, come to think of it, how homing `Y` without homing `X` work? The robot physically needs to home `X` first to put the pipette carriage in the correct place to hit the `Y` switch, right?

Maybe say that the safest thing for the client to do for now is leave this omitted so the hardware controller can decide how to home, and leave a todo to come back to this later?

2021-11-12 21:27 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_engine/state/test_pipette_store.py
> +    """It clear the last accessed well with a home command."""
Good call. 👍

2021-11-12 22:55 UTC, sanni-t requested changes

2021-11-12 22:55 UTC, sanni-t commented on api/src/opentrons/protocol_engine/execution/movement.py
> +            raise MustHomeError(str(e)) from e
This seems to be swallowing the error. The command succeeds with some gibberish (I think) X & Y values in the response.

2021-11-15 14:41 UTC, mcous commented on api/src/opentrons/protocol_engine/execution/movement.py
> +            raise MustHomeError(str(e)) from e
I think the problem was that `hardware_api.gantry_position` would actually never throw a `MustHomeError`, for the same reason as `hadware_api.move_rel`. Applied the same fix for `gantry_position` as #8724, can you check if this resolves the issue?

2021-11-15 14:42 UTC, mcous commented on api/src/opentrons/protocol_engine/commands/home.py
> +    )
Modified the docstring to note that the robot may home more axes than explicitly specified in order to properly home any axes that _were_ explicitly specified. This is Hardware API behavior but it's been established behavior for years, so I'm comfortable including it in the public API

2021-11-15 14:43 UTC, mcous commented on api/src/opentrons/protocol_engine/execution/movement.py
> +            hardware_axes = [MOTOR_AXIS_TO_HARDWARE_AXIS[a] for a in axes]
TIL that empty collections are falsey in Python (they are truthy in JavaScript)

2021-11-15 16:36 UTC, sanni-t approved these changes
LGTM! `savePosition` fails correctly after the change.

2021-11-15 16:36 UTC, sanni-t commented on api/src/opentrons/hardware_control/api.py
> +                "Current position of {str(mount)} pipette is unknown, please home."
```suggestion
                f"Current position of {str(mount)} pipette is unknown, please home."
```

2021-11-15 17:05 UTC, merged