refactor(api, engine, runner): analyze legacy load_labware on module
OpenTrons/opentrons-api pull request #8769
Opened 2021-11-15 16:16 UTC by sanni-t

Closes #8608 

# Overview

# Changelog

# Review requests

# Risk assessment

2021-11-15 20:50 UTC, mcous requested changes
Looks like this is on the right track. I think we should move the `moduleId` stuff out of the protocol context. We need to make sure all ID mapping logic is fully contained to the mapper interface; anything else will be too implicit to manage effectively

2021-11-15 20:50 UTC, mcous commented on api/src/opentrons/protocol_api/module_contexts.py
> +        return f"{self._geometry.model}-Slot{self._geometry.parent}"
Keeping this in sync with the `LegacyCommandMapper` looks really brittle. I wouldn't try to establish any concept of PE module ID in the module context

2021-11-15 20:50 UTC, mcous commented on api/src/opentrons/protocol_api/module_contexts.py
> +                moduleId=self.engine_id,
Would it be easier to send over the module location (i.e. slot) instead? I think assuming 1 module per slot will hold

2021-11-15 20:50 UTC, mcous commented on api/src/opentrons/protocol_api/protocol_context.py
> +                module_id=module_context.engine_id,
Same comment. Would replace this with `deck_slot` to mirror labware load

2021-11-15 20:50 UTC, mcous commented on api/src/opentrons/types.py
> +class LabwareLoadInfo:
These are not top-level types, and I would avoid moving them here. If we want to move them out of `protocol_context.py`, I would move them to something like `src/opentrons/protocol_context/load_info.py` or something that's still scoped within `opentrons.protocol_context`

2021-11-15 20:50 UTC, mcous commented on api/src/opentrons/types.py
> +class LabwareLoadOnModuleInfo:
Would it be easier to have `LabwareLoadInfo` handle both deck and module labware? Since they'll both map into `pe_commands.LoadLabware`, having two separate legacy info types feels a little redundant

2021-11-15 20:50 UTC, mcous commented on api/src/opentrons/types.py
> +    from opentrons_shared_data.labware.dev_types import LabwareDefinition
Setting aside that I don't think we should be adding to this file, for future reference: avoid putting type imports under a `TYPE_CHECKING` conditional unless we're avoiding a circular type import

2021-11-15 21:03 UTC, SyntaxColoring reviewed
> * Code looks good.

LGTM!

> * Upload a legacy protocol with labware on modules and see that the labware is populated in analysis with the correct moduleId

Confirmed. This made me realize that we don't have a top-level `modules` list in a `CompletedAnalysis`, though. I'll ticket that separately.

2021-11-15 21:03 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/state/geometry.py
> +            raise NotImplementedError("Not implemented for labware on modules")
Could we avoid the `isinstance` stuff here by doing something like:

```python
parent_pos = self.get_labware_parent_position(labware_id=labware_id)
origin_offset = self._labware.get_definition(labware_id).cornerOffsetFromSlot
return Point(
    x=slot_pos.x + origin_offset.x
    y=slot_pos.y + origin_offset.y
    z=slot_pos.z + origin_offset.z
)
```

2021-11-15 21:03 UTC, SyntaxColoring commented on api/src/opentrons/types.py
> +class LabwareLoadOnModuleInfo:
I had the same question. I don't have a preference either way, personally.

2021-11-15 21:06 UTC, SyntaxColoring commented on api/src/opentrons/types.py
> +    from opentrons_shared_data.labware.dev_types import LabwareDefinition
I'm not up to speed on the full history, but [it looks like the intent of `.dev_types` specifically was to only be imported under `TYPE_CHECKING`](https://github.com/Opentrons/opentrons/blob/662e09ef60db7525d3e12a5c24b4a47402139bfc/shared-data/python/opentrons_shared_data/pipette/dev_types.py#L1-L6). I suppose because we didn't always have `typing_extensions` on the robot, so this would otherwise break at runtime?

2021-11-15 21:19 UTC, sanni-t commented on api/src/opentrons/protocol_engine/state/geometry.py
> +            raise NotImplementedError("Not implemented for labware on modules")
That does look better

2021-11-15 21:24 UTC, sanni-t commented on api/src/opentrons/types.py
> +class LabwareLoadOnModuleInfo:
Yea, I can see how `LabwareLoadInfo` can handle both when not trying to pass a `moduleId` as noted in @mcous's above comments. Will make that change.

2021-11-16 16:25 UTC, mcous approved these changes
Some little stuff, but this LGTM

2021-11-16 16:25 UTC, mcous commented on api/src/opentrons/protocol_api/load_info.py
> +    on_module: Optional[bool] = False
We don't need the `Optional` here thanks to the default value

```suggestion
    on_module: bool = False
```

2021-11-16 16:25 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
> +        # TODO (spp, 2021-11-15): Will we need to store here labware on modules too?
Right now we're in the clear, but only because tipracks aren't ever loaded on top of modules (I hope...). We'll need to do _something_ if/when we get to mapping legacy commands other than `pickUpTip`

2021-11-16 16:25 UTC, mcous commented on api/tests/opentrons/protocol_runner/test_legacy_command_mapper.py
> +    decoy: Decoy, minimal_labware_def: LabwareDefinition
`decoy` fixture unused here

2021-11-16 16:25 UTC, mcous commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
>                  raise Exception(f"{module_load_info.module_name} requires a location.")
I know this isn't part of this PR, but since we're in this file, could we change this to an `assert` instead of a general `Exception`?

2021-11-16 16:28 UTC, sanni-t commented on api/src/opentrons/protocol_runner/legacy_command_mapper.py
>                  raise Exception(f"{module_load_info.module_name} requires a location.")
I am actually getting rid of this entirely and going to fetch the slot location from `protocol_context`. Going to push the change once all tests pass.

2021-11-16 17:33 UTC, sanni-t reviewed
Did some module-related cleanup.

2021-11-16 17:33 UTC, sanni-t commented on api/src/opentrons/protocol_api/load_info.py
> +    deck_slot: DeckSlotName
Changed this from `location: Optional[DeckLocation]` to match the signature of `LoadLabwareInfo`. Also, we really only need the slot name so this makes more sense.
Made it a required field to match PE `loadModule`'s expectations.

2021-11-16 17:33 UTC, sanni-t commented on api/src/opentrons/protocol_api/protocol_context.py
> +        module_loc = module.geometry.parent
Fetching the slot location from geometry so we won't have to interpret the location of thermocyclers in the command mapper.

2021-11-16 17:33 UTC, sanni-t commented on api/tests/opentrons/protocol_runner/test_legacy_command_mapper.py
> +def test_map_module_load() -> None:
Don't need the parametrized tests now that we aren't inferring a module location inside command mapper.

2021-11-16 19:42 UTC, mcous commented on api/src/opentrons/types.py
> +    from opentrons_shared_data.labware.dev_types import LabwareDefinition
I'd guess the same thing, given the age of that docstring block. No new developments in this area since the [last thread](https://github.com/Opentrons/opentrons/pull/8784) which we sort of captured in the [Python style guide](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/951648308/Python+style)

2021-11-16 19:48 UTC, mcous reviewed
Approval still holds, but same comment about `assert` vs bare `Exception`s

2021-11-16 19:48 UTC, mcous commented on api/src/opentrons/protocol_api/module_contexts.py
> +            raise Exception("Unexpected labware object parent")
Same comment about this being more appropriate using `assert`, I think

```suggestion
        assert isinstance(module_loc, (int, str)), "Unexpected labware object parent"
        deck_slot = types.DeckSlotName.from_primitive(module_loc)
```

(Double checked the line length on this suggestion, won't trigger the linter)

2021-11-16 19:48 UTC, mcous commented on api/src/opentrons/protocol_api/protocol_context.py
> +            raise Exception("Unexpected labware object parent")
```suggestion
        assert isinstance(module_loc, (int, str)), "Unexpected labware object parent"
        deck_slot = types.DeckSlotName.from_primitive(module_loc)
```

2021-11-16 19:52 UTC, sanni-t commented on api/src/opentrons/protocol_api/module_contexts.py
> +            raise Exception("Unexpected labware object parent")
Ah yes. Will do. 
Thanks for checking the line length!

2021-11-16 21:26 UTC, merged