feat(hardware): set and receive subsystem's motion constraints
OpenTrons/opentrons-api pull request #8772
Opened 2021-11-15 19:56 UTC by ahiuchingau

# Overview
This PR adds `SetMotionConstraints` and `GetMotionConstraintsRequest` to CAN messages and removes the deprecated `SetSpeed/GetSpeed` messages.

# Changelog

# Review requests

# Risk assessment

2021-11-15 21:01 UTC, amitlissack approved these changes

2021-11-15 21:06 UTC, amitlissack requested changes

2021-11-15 21:06 UTC, amitlissack commented on hardware/opentrons_hardware/drivers/can_bus/messages/message_definitions.py
> +    payload_type: Type[BinarySerializable] = payloads.MotionConstraintsPayload
The host may broadcast the request to all subsystems. The response needs to identify the source. 

So a NodeId will be needed in this response.

2021-11-15 21:09 UTC, sfoster1 commented on hardware/opentrons_hardware/drivers/can_bus/messages/message_definitions.py
> +    payload_type: Type[BinarySerializable] = payloads.MotionConstraintsPayload
Should we systematically add a `NodeId` to all responses, possibly through inheritance on the python side? That would solve this problem in the long term.

2021-11-15 21:14 UTC, amitlissack commented on hardware/opentrons_hardware/drivers/can_bus/messages/message_definitions.py
> +    payload_type: Type[BinarySerializable] = payloads.MotionConstraintsPayload
Yes.

2021-11-15 21:47 UTC, ahiuchingau commented on hardware/opentrons_hardware/drivers/can_bus/messages/message_definitions.py
> +    payload_type: Type[BinarySerializable] = payloads.MotionConstraintsPayload
@sfoster1 yep, Amit and I spoke about adding NodeId to all response messages earlier and will do this in a followup PR

2021-11-30 13:58 UTC, sfoster1 approved these changes
Nice! Might need to add more stuff eventually but good for now

2021-12-02 19:31 UTC, amitlissack approved these changes

2021-12-07 20:08 UTC, sfoster1 commented
Let's remove this in favor of https://github.com/Opentrons/ot3-firmware/pull/172

2021-12-07 20:08 UTC, closed without merging