refactor(app): pUR FF Removal: Nav
OpenTrons/opentrons-api pull request #8894
Opened 2021-11-23 16:29 UTC by smb2268

close #8873

# Overview
Remove FF from Navigation

# Changelog
All instances of `preProtocolFlowWithoutRPC` and their logic should be removed from the following locations within the nav.

- [ ] opentrons/app/src/App/hooks.ts
- [ ] opentrons/app/src/App/__tests__/hooks.test.tsx
- [ ] opentrons/app/src/redux/nav/__tests__/selectors.test.ts

# Review requests
Verify that the new nav loads whether FF is on or off

# Risk assessment
low

2021-11-23 21:06 UTC, b-cooper requested changes
Mostly good, just one bug that needs to be addressed

2021-11-23 21:06 UTC, b-cooper commented on app/src/App/hooks.ts
> +  const [robots, upload, more] = useSelector(getNavbarLocations)
This is not behaving as you intended.  Be careful when destructuring arrays, the indices will be maintained even if the names change locally. In the current implementation `more` is actually the contents of the calibration location (which is the 2 index returned from getNavbarLocations).  You will either need to edit the contents of the `getNavbarLocations` selector to only return `robots`, `upload`, and `more`, or change this line to 

```
const [robots, upload, _legacyCalibrate, _legacyRun, more] = useSelector(
  getNavbarLocations
)
```

2021-11-23 22:00 UTC, smb2268 commented on app/src/App/hooks.ts
> +  const [robots, upload, more] = useSelector(getNavbarLocations)
Ah my mistake - I'll push the former fix and make a TODO to clean up the `nav/__tests__/selectors.test.tsx` file for when we're ripping out more of the unnecessary code next week.

2021-11-24 16:49 UTC, jerader approved these changes
did a quick search and didn't find any instances of `preProtocolFlowWithoutRPC` 🚀

2021-11-24 19:39 UTC, b-cooper approved these changes
💣

2021-11-24 20:04 UTC, merged