refactor(app): add protocol record creation loading spinner
OpenTrons/opentrons-api pull request #8978
Opened 2021-12-03 18:23 UTC by sakibh

# Overview

Adds a loading state when a user uploads a protocol file based on the loading state of the crete
protocol mutation hook.

![Screen Shot 2021-12-03 at 1 15 23 PM](https://user-images.githubusercontent.com/14794021/144653438-85a83b82-70e0-4b7c-bb76-0ca162a93648.png)

closes #8951

# Changelog

- Exposes `isLoading` state from useCreateProtocolRun hook.
- Added `ProtocolLoader` component to render spinner 

# Review requests

- Check if protocol loading spinner renders when uploading a protocol.

Note: There seems to be a side issue where RQ thinks the loading of the protocol analyses data is complete but the data loads in a bit later causing the spinner to disappear prematurely.

# Risk assessment

low

2021-12-03 21:20 UTC, b-cooper requested changes
Looking good, just a couple of tweaks and this'll be ready to go

2021-12-03 21:20 UTC, b-cooper commented on app/src/organisms/ProtocolUpload/hooks/useCurrentProtocolRun.ts
> +    isLoading,
it might be helpful to alias this isLoading as `isCreatingProtocolRun` and return that in the final object. That way it's a little clearer what is loading, as this hook composes a couple of requests

2021-12-03 21:20 UTC, b-cooper commented on app/src/organisms/ProtocolUpload/index.tsx
> +    <>
this fragment is gratuitous

2021-12-03 21:20 UTC, b-cooper commented on app/src/organisms/ProtocolUpload/index.tsx
> +          fontSize={FONT_SIZE_HUGE}
This font size (`3rem`) is twice the size of the text in the designs.  There is no `1.5rem` constant in `typography.ts`, so in most cases I would say you should just inline `'1.5rem'` here, but I think the jump from `FONT_SIZE_HEADER='1.125rem'` to `FONT_SIZE_HUGE='3rem'` could probably use an intermediate.  Would you mind adding `1.5rem` as a constant and naming it something like `FONT_SIZE_BIG` or something else that is clearly bigger than a "header" and not as big as "huge"?

2021-12-03 21:20 UTC, b-cooper commented on app/src/organisms/ProtocolUpload/index.tsx
> +          {isLoading ? (
Can you refactor this nested ternary out of this branching?  Generally we avoid nesting ternary statements for readability's sake.  You could define an intermediate function before this component's return statement. Even something like this to split up this logic would clean it up a bit:

```
const renderContents = () => (
 runRecord != null && protocolRecord != null 
  ? <ProtocolSetup />
  : <UploadInput onUpload={handleUpload} />
)

```

2021-12-03 21:20 UTC, b-cooper commented on react-api-client/src/protocols/useCreateProtocolMutation.ts
> +    isLoading: mutation.isLoading,
the mutation is already being spread into the returned object above at line 54, so this addition and the above type are both unnecessary.

2021-12-07 18:22 UTC, brenthagen approved these changes

2021-12-07 18:23 UTC, b-cooper approved these changes

2021-12-07 18:23 UTC, merged