feat(hardware): add move manager
OpenTrons/opentrons-api pull request #9022
Opened 2021-12-08 17:05 UTC by ahiuchingau

# Overview

# Changelog

# Review requests

# Risk assessment

2021-12-08 17:15 UTC, sfoster1 reviewed
let's just remove some prints before we forget, pin the numpy version, and maybe shuffle some types around but looking solid

2021-12-08 17:15 UTC, sfoster1 commented on hardware/Pipfile
> +numpy = "*"
should probably lock this to the robot version which is 1.17.4

2021-12-08 17:15 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/types.py
> +class Axis(enum.Enum):
can we maybe promote these two (Axis and Coordinates) to a top-level type? they'll eventually be the primary external interface here

2021-12-08 17:15 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/types.py
> +class Coordinates(NamedTuple):
this probably wants an `as_vector` method or something that produces a numpy vector, or maybe a method like that inside motion planning

2021-12-08 17:15 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +        print(f'Axis {axis}')
probably remove the `print`

2021-12-08 17:15 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_manager.py
> +            print(f'Iter: {i}')
remove

2021-12-08 17:15 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_manager.py
> +                    print(f'Move: {middle}')
remove

2021-12-08 17:15 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_manager.py
> +                print(f'To blend: {to_blend}')
remove

2021-12-09 18:38 UTC, Laura-Danielle reviewed
Have some initial comments. Will try to finish reviewing tomorrow.

1. In general, we should try to use numpy functions only when we're working with actual array/matrix math imo.
2. Anything that is an array should be a numpy array. This makes it easier to do multiplication etc.

2021-12-09 18:38 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +        elif np.sign(next_move.unit_vector[axis.value]) == np.sign(axis_component):
rather than using `np.sign()` to check if a single component is negative or positive, wouldn't it make more sense to use multiplication? We can multiply the two components and check that the value is always positive since P*P = P and N*N = P and everything else would be a different direction.

See the quick timing test below.
```
def check_numbers(a, b):
    if (a*b) > 0:
       return 'same'
    else:
        return 'no'

def check_numbers_np(a, b):
    if np.sign(a) == np.sign(b):
       return 'same'
    else:
        return 'no'

timeit.timeit(lambda: "-".join(check_numbers(-2, -2)), number=100)
0.0002507069999637679
timeit.timeit(lambda: "-".join(check_numbers_np(-2, -2)), number=100)
0.0003715720000059264

timeit.timeit(lambda: "-".join(check_numbers_np(2, -2)), number=100)
0.0002165230000059637
timeit.timeit(lambda: "-".join(check_numbers(2, -2)), number=100)
5.8078999984445545e-05

```

2021-12-09 18:38 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +            assert False, "planning final speed failed"
When would the move ever fail here?

2021-12-09 18:38 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +        if axis_speed_limit / final_speed < 1:
Is the range that we're checking here between 0 and 1?

2021-12-09 18:38 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +    initial_speed_vectors = np.multiply(initial_speed, move.unit_vector)
if unit vector is a numpy array, you can just do initial_speed * unit_vector

2021-12-09 18:38 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +    acceleration = np.dot(max_acceleration_vector, move.unit_vector)
are you trying to scale the acceleration with the max accel vector (I.E. x1 * x2, y1*y2, z1*z2)? If so, you should use `np.multiply()`

2021-12-10 19:28 UTC, ahiuchingau commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +        if axis_speed_limit / final_speed < 1:
Saving the min value

2021-12-20 14:59 UTC, sfoster1 requested changes
Comments in the pr; definitely need some overall blending-succeeds tests; but really really looks great!

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_manager.py
> +        move_list: List[Move] = [],
do we need this as an `__init__` arg? isn't this in some sense the output?

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_manager.py
> +        target_list: List[MoveTarget] = [],
IMO if this is a one-shot object where you build one for a target set, run its computation, and then you're done with it, there's no reason to have this be optional

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_manager.py
> +class MoveManager:
This object straddles a line where
- Its fundamental parameters (constraints, origin, targets) are in init args, which makes it seem like a oneshot object where you build it, do its computation, get its results, and dispose of it; and it's a class to make factoring out common work easier, kind of an implementation detail
- But it doesn't do its work in the initializer, you still have to call another method
- And also it has a reset method, so it's technically multi-use

I think that it should really pick a side. Either,
- Keep the arguments in `__init__` and make it also do the work in `__init__` (or provide some classmethod that builds the object and then immediately runs computation so that callers only need to know one thing). Ditch `reset()`, make those init args non-optional, etc.
or
- Discard the idea of it being a one-shot and keep it as a manager. Remove the `origin` and `target_list` arguments from `__init__` and add them to `plan_motion`. In fact, remove the `origin` and `target_list` items from state as much as possible and make `plan_motion` more pure, keeping the origin, target list, and move list as normal variables rather than instance members.

I support the second one I think because if we later have to make it a streaming solution where its major interface is, rather than a `plan_moves` that executes on a batch, a streamer with an `add_move` and an iterative `plan`, that's an easier refactor.

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_manager.py
> +        origin: Optional[Coordinates] = None,
IMO this class and move processing in general should really all be numpy types. I think in the long term the boundary between numpy things and non-numpy things should be the hardware controller, but for now it can be here, at the public interface of this class. This entry point I think should have more python type arguments that are flexible w/r/t which axes are used and what order they're in, like a `Dict[str, float]` or something where it can be the dang string axis names that the controller knows about; and internally it should just all be numpy vectors and then one external Axis->vector index map.

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/types.py
> +    """Coordinates for all axes."""
In line with my comment on the planner's public interface, IMO all the types in this file that are internal should be numpy mappings that present ways to convert them into/out of numpy, but definitely actively store things as ndarrays. So `Coordinates` should have-a vector and present `from_iter`, `__iter__`/`__next__`, and `to_dict` methods.

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/types.py
> +    distance: float
these floats should probably be `np.float64`

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/types.py
> +        return math.sqrt(
and these should use numpy math

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/types.py
> +import math
let's keep this all numpy, it's a no `import math` zone

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/types.py
> +    unit_vector: Coordinates
maybe we should have a `UnitVector` type so mypy can tell us if we mess up

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/scripts/plan_motion.py
> +import logging
Can we make this a little more interactive rather than hardcoded? We'll need something that lets you just sort of move around from the command line. It can be pretty hacky, like it could have a `move_sequence` argument that's just a string that should be a `List[float]` literal that gets `eval`ed (lol) or some quick repl functionality or something

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +import math
let's try and keep this all numpy

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +import math
meaning, 
- use numpy sqrt if we can
- type things as numpy `float64` rather than `float`
- `ndarray` rather than list

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +            not prev_move or not prev_move.unit_vector[axis.value]
[nit] when we're getting multiple line conditionals imo we should factor them into functions even if they're one-use, like some `def ends_stopped(move: Optional[Move]) -> bool`

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +        elif prev_move.unit_vector[axis.value] * axis_component > 0:
elegant, love it

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +        if not axis_component:
maybe wants to be `if abs(axis_component) < SOME_FLOAT_THRESHOLD`

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +            axis_speed_limit = axis_constraints.max_speed_discont / axis_component
[nit] `axis_speed_limit`, and this may be my priors, gives me the idea that this is an axis speed component, not a speed limit based on axis constraints. maybe `constrained_speed` is a better name?

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +    constraints: SystemConstraints, move: Move, prev_move: Optional[Move]
i think this was carried over from the jupyter notebook, but I think we don't need both `prev_move` to be `Optional` and the list padding in the top level `plan_move`. By adding the dummy start and end moves in the top-level planning, we should be ensuring that `prev_move` is always present, just zeroed in the first-real-move case. That then simplifies that first conditional as well as the typing.

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +        elif (
IMO we should make line 80 (`elif not prev_move.unit_vector[axis.value]`) to line 115 (`assert False`) its own function. What this allows us to do is early-return the computed speed limits rather than have this each-branch-sets-a-variable thing, which I like a little better stylistically, and prevents people reading this function from getting a little lost in the soup about what exactly the loop is doing - the loop body will be pretty obviously going through axes, and that function can be something like `def initial_speed_limit_from_axis(axis_component: numpy.float64, axis_constraints: Constraints[axis], previous_component: numpy.float64) -> numpy.float64`

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +    next_move: Optional[Move],
same as with `initial_speed`, i think the window padding means this doesn't have to be optional

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +def find_final_speed(
basically same comments  on this as in `find_initial_speed` but I'll put some quick reminders down

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +        if not axis_component:
probably wants to be `if abs(axis_component) < SOME_SMALL_NUMBER`

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +        elif (
factor the loop body to some function

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +            assert False, "planning final speed failed"
probably never, which is why the `assert` is nice to have - it would only happen on bugs

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +                math.copysign(
no `math` zone

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_utils.py
> +                return initial_speed == final_speed
this may (will, almost certainly) need to be `initial_speed - final_speed < SOME_SMALL_FLOAT_CONSTANT`

2021-12-20 14:59 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/types.py
> +class Axis(enum.Enum):
I think I disagree with myself on this actually. We want everything under the `MovePlanner` interface to be pure numpy, and eventually want everything to be pure numpy, so I think for now it's ok for the planner's top level interface to be `Dict[str, float]` (or `Dict[Union[Literal['X'], Literal['Y'],...], float]`) and the internals to be numpy

2022-01-03 15:52 UTC, ahiuchingau commented on hardware/opentrons_hardware/hardware_control/motion_planning/move_manager.py
> +class MoveManager:
Yep I think the second one is better too.

2022-01-04 01:01 UTC, ahiuchingau commented on hardware/opentrons_hardware/hardware_control/motion_planning/types.py
> +    unit_vector: Coordinates
I'm using the `UnitVector` type in the `get_unit_vector()` function so mypy will typecheck the return value, but I don't think we need to change the unit_vector here because we want the values to all be 0 when it's a dummy move

2022-01-04 21:38 UTC, amitlissack commented on hardware/opentrons_hardware/hardware_control/motion_planning/types.py
> +    def initial_speed(self) -> float:
Maybe a pre-mature optimization.... but....

Looks like this property and the following two are called repeatedly. Since this dataclass is imutable, perhaps it would be wise to cache the initial speed, final speed, and non-zero block count in a post_init step?

2022-01-06 18:40 UTC, amitlissack commented on hardware/opentrons_hardware/hardware_control/motion_planning/types.py
> +    def initial_speed(self) -> float:
Thanks!

2022-01-06 21:22 UTC, ahiuchingau commented on hardware/opentrons_hardware/scripts/plan_motion.py
> +import logging
Agreed. Will do this in a followup PR!

2022-01-06 22:02 UTC, sfoster1 approved these changes
Looks great!

2022-01-06 22:02 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/types.py
> +    def __post_init__(self) -> None:
whoa

2022-01-06 22:02 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/motion_planning/types.py
> +    X = 0
Good with these for now but I can't help but think there's a more general way to do this; I feel like we use these explicitly as keys in a lot of different places and I think we can avoid it.

2022-01-06 22:20 UTC, merged