feat(app): create error toast when TLC or POC fails
OpenTrons/opentrons-api pull request #9032
Opened 2021-12-08 20:52 UTC by jerader

closes #9000

# Overview

This PR adds a failed toast if pipette offset calibration or tip length calibration fail:
<img width="1030" alt="Screen Shot 2021-12-08 at 15 47 40" src="https://user-images.githubusercontent.com/66035149/145282114-2e85629e-6d4b-48d1-b604-1ae1708c35c5.png">

# Changelog

- created a `CalibrationFailedToast` component and test
- added onto `ProtocolSetup`

# Review requests

- I grabbed the failed calibration reasoning from `useProtocolCalibrationStatus()` not sure if that is correct (the above image has a stubbed in `error_reason` since `ProtocolCalibrationStatus.reason` is 
` | 'calibrate_deck_failure_reason'
    | 'calibrate_tiprack_failure_reason'
    | 'calibrate_pipette_failure_reason'
    | 'attach_pipette_failure_reason'`)
- make sure it matches figma
- test on a robot

# Risk assessment

low, behind ff

2021-12-08 21:04 UTC, jerader commented
@emilywools, a few questions for you!

1. is it ok if the banner is above the metadata card? or do we want it to be over the metadata card like it shows on figma? 
2. do we want the user to be able to dismiss the banner?

2021-12-08 21:19 UTC, emilywools commented
1. can the banner sit at the top of the user's viewport, above the main content of the app? cc @shlokamin because i asked him this very question today
2. yes, i think it makes sense to add a close button. Sorry that I missed that! Figma is updated now

2021-12-08 21:53 UTC, b-cooper requested changes
The view layer looks good here, unfortunately `useProtocolCalibrationStatus` is meant to read existing calibration values from the robot and match them with required calibrations based on the protocol's equipment.  Therefore the `calibrationStatus` that it returns is actually a static representation of whether or not the required calibrations are complete.  

This toast actually needs to present an error in the actual PoC or TLC calibration process.

 This will likely require appending some functionality to `app/src/redux/sessions` to handle the `CREATE_SESSION_FAILURE` action type in some inspectable way.

2021-12-15 16:30 UTC, shlokamin commented
Looks like we need to add a case in `app/src/redux/sessions/reducer.ts` to handle a `CREATE_SESSION_FAILURE` action. 

The weird thing here is we need to map the action payload that comes from a `CREATE_SESSION_FAILURE` action to a session id, but we dont get one back as part of a `CREATE_SESSION_FAILURE` action payload. 

i'll look into this more after we resolve some of the more critical PUR issues

2022-01-03 22:30 UTC, shlokamin commented
Closing this for now. We do not have a global way to handle calibration failures, so they'll need to be tackled individually inside of `CalibrateTipLengthControl` (for TLC) and `useCalibratePipetteOffset` (for POC). Since so much of this is going to be changed as part of the next gen app work, let's table this and tackle it after the PUR release.

2022-01-03 22:30 UTC, closed without merging