feat(app): add Comment text above comment commands in run details
OpenTrons/opentrons-api pull request #9054
Opened 2021-12-09 18:34 UTC by jerader

closes #9040

# Overview

This PR adds the Comment text above command commands in the run details page.
<img width="664" alt="Screen Shot 2021-12-09 at 13 28 51" src="https://user-images.githubusercontent.com/66035149/145455044-600f1ac9-8760-4af6-b0aa-500948c6a3c8.png">

<img width="659" alt="Screen Shot 2021-12-09 at 13 22 15" src="https://user-images.githubusercontent.com/66035149/145455054-bb440ad9-f8ff-4b4a-97ef-6031cd48ef66.png">

# Changelog

- added onto `CommandItem` component

# Review requests

- I tested on my robot, test on your robot if you want as well. NOTE: only comments written in python protocols are supported!
- review figma

# Risk assessment

low, behind ff

2021-12-09 19:35 UTC, shlokamin requested changes, later dismissed

2021-12-09 19:35 UTC, shlokamin commented on app/src/organisms/RunDetails/CommandItem.tsx
> +      commandOrSummary.id.includes('COMMENT') ? (
we shouldn't be assuming that a command's `id` containing `COMMENT` will reliably mean that it's actually a comment. while this works, it's brittle, because this isn't a contract that's upheld by CPX, so this could break and we'd have no idea of knowing.

what I think would be better is if parsed the custom command's `legacyCommandType` and looked for `command.COMMENT`, because that is a reliable matcher to tell us the command type is a comment, and this is a contract that is upheld by CPX (and won't break unless they tell us and communicate the change).

2021-12-09 19:35 UTC, shlokamin commented on app/src/organisms/RunDetails/CommandItem.tsx
> +          {t('comment_step')}{' '}
is this space needed here? `{' '}`

2021-12-09 19:55 UTC, jerader commented on app/src/organisms/RunDetails/CommandItem.tsx
> +      commandOrSummary.id.includes('COMMENT') ? (
I see, i'll fix this, thanks! But, since `  commandOrSummary: Command | RunCommandSummary` is it ok to leave the `commandOrSummary.id.includes('COMMENT')` since `RunCommandSummary` doesn't have a param?

2021-12-09 20:07 UTC, jerader commented on app/src/organisms/RunDetails/CommandItem.tsx
> +          {t('comment_step')}{' '}
whoops nope. i appeared when i fixed the formatting at one point.

2021-12-09 21:36 UTC, b-cooper submitted a review, later dismissed
Looking good functionally, just a couple of implementation details that need to be cleaned up a bit.

2021-12-09 21:36 UTC, b-cooper commented on app/src/organisms/RunDetails/CommandItem.tsx
> +      Object.values(commandDetails.data.params).includes('command.COMMENT')) ||
Instead of matching on the string values of every param in the custom command, we should be more direct about what we're looking for here. We know that legacy commands will have `commandType === 'custom'` and we also know that they will have two param keys `legacyCommandType` and `legacyCommandText`.  This fuzzy check should be replaced with `commandDetails.data.params?.legacyCommandType === 'command.COMMENT'`

2021-12-09 21:36 UTC, b-cooper commented on app/src/organisms/RunDetails/CommandItem.tsx
> +    commandOrSummary?.id.includes('COMMENT')
We should never parse anything out of any kind of `id` string. Id's are meant to be opaque identifiers that are matched by strict equality only. 

What was this extra `||` check meant to catch that isn't already covered by the previous line?

2021-12-09 21:45 UTC, jerader commented on app/src/organisms/RunDetails/CommandItem.tsx
> +      Object.values(commandDetails.data.params).includes('command.COMMENT')) ||
I am confused, params doesn't have `legacyCommandType`?

2021-12-10 18:39 UTC, shlokamin commented on app/src/organisms/RunDetails/CommandItem.tsx
> +    commandDetails !== null &&
`commandDetails?.data` should already be checking that `commandDetails !== null` right?

2021-12-10 18:41 UTC, shlokamin commented on app/src/organisms/RunDetails/CommandItem.tsx
> +    Object.values(commandDetails.data.params).includes('command.COMMENT')
we should be explicitly checking that `commandDetails.data.params.legacyCommandType  ===  ""command.COMMENT""`

this will iterate over all params and check if any of their values include `command.Comment`, which is more brittle

2021-12-10 19:29 UTC, smb2268 approved these changes
The most recent `isComment ` updates look good and styling is as expected!

2021-12-14 17:45 UTC, shlokamin reviewed
looks like this is failing CI, we can merge after it gets fixed

2021-12-14 19:04 UTC, merged