refactor(app): Move LPC toast above metadata
OpenTrons/opentrons-api pull request #9057
Opened 2021-12-09 19:04 UTC by Kadee80

# Overview

closes #9010 by moving LPC success toast above main content,

# Changelog

- refactor(app): Move LPC toast above metadata

# Review requests

run through LPC
close it out
- [ ] success toast should be above metadata at top of the page

# Risk assessment
low, just some small DOM stuff in the app

2021-12-09 19:39 UTC, shlokamin requested changes

2021-12-09 19:39 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/index.tsx
> -        <MetadataCard />
this just rearranges the DOM, it doesn't actually fix the success toast to the top of the user's viewport

2021-12-09 19:43 UTC, Kadee80 commented on app/src/organisms/ProtocolSetup/index.tsx
> -        <MetadataCard />
i guess im not clear on what the ticket is asking?

2021-12-09 22:01 UTC, shlokamin requested changes

2021-12-09 22:01 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/index.tsx
> +          <MetadataCard />
we shouldn't need to change the DOM ordering, just the CSS!

2021-12-09 22:01 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/styles.css
> +  position: fixed;
i think this is a perfect place where `position: sticky` would be appropriate, right?

2021-12-09 22:01 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/styles.css
> +  width: 89.5%;
i dont think we need to change the width at all, figma has it a bit bigger than the full width but i think it's fine for it to just take up the entire width (so we shouldn't need to specify one at all)

2021-12-09 22:01 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/styles.css
> +  position: fixed;
```suggestion
  position: sticky;
```

2021-12-09 22:01 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/styles.css
> +  width: 89.5%;
```suggestion
```

2021-12-13 17:26 UTC, jerader reviewed
Making the toast sticky works! Overall looking good, just left 1 comment about the width.

2021-12-13 17:26 UTC, jerader commented on app/src/organisms/ProtocolSetup/styles.css
> +  width: 89.5%;
I agree that we don't need to change the width.

<img width="956" alt="Screen Shot 2021-12-13 at 12 23 55" src="https://user-images.githubusercontent.com/66035149/145859155-1fc6b03a-18a7-4c63-8ab3-2c539ec42216.png">

2021-12-14 17:40 UTC, Kadee80 commented on app/src/organisms/ProtocolSetup/styles.css
> +  position: fixed;
sticky didn't work. tried and failed

2021-12-14 17:41 UTC, Kadee80 commented on app/src/organisms/ProtocolSetup/styles.css
> +  width: 89.5%;
without changing the width it either gets too big or small. i can noodle with this

2021-12-14 17:49 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/styles.css
> +  width: 89.5%;
using the following CSS styles i think it looks fine: 
```css
.sticky_alert {
  position: sticky;
  top: 3rem;
  z-index: 100;
}

```
<img width="1026" alt="Screen Shot 2021-12-14 at 12 48 51 PM" src="https://user-images.githubusercontent.com/5788529/146052441-6bde401a-fb26-4eac-99ed-86229944df1a.png">

2021-12-14 17:50 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/styles.css
> +  position: fixed;
hmm, seems to work on my end... see https://github.com/Opentrons/opentrons/pull/9057/files#r768907397

2021-12-14 18:21 UTC, shlokamin approved these changes

2021-12-14 18:39 UTC, shlokamin requested changes
@Kadee80 just realized you left in the changes to DOM ordering, I don't think we need those

2021-12-14 19:00 UTC, jerader approved these changes
lgtm!

2021-12-20 23:27 UTC, shlokamin approved these changes
🚢

2021-12-21 16:51 UTC, merged