refactor(api): ot3 hardware control API
OpenTrons/opentrons-api pull request #9062
Opened 2021-12-09 21:31 UTC by sfoster1

Switches the OT3 hardware controller to a whole new hardware control API rather than just a controller.

Some changes required for the OT3 to work - the big one is that the plunger runs in the other direction - really can't be entirely handled in the controller layer alone, and need hardware API changes. With #9201 , it's much more reasonable to have two hardware control APIs with the same interface and working with typechecking, so this PR creates that second API and adds the changes required for the OT3 to run protocols. 

It also adds testing for the new API, by extending the `hardware` fixture in the API tests to provide both ot3 and ot2 hardware controllers. To me, this testing is sufficient to not have to do the same thing in the robot server, but I'm interested in other opinions.

The next steps after this API is to start pulling common implementation into shared code rather than leaving it duplicated between the two APIs, and either merge the controller code into the API or (since we may need the Simulation layer until we can finally get rid of api-level simulation) change the interface to better-reflect the internal data structures of the OT3 hardware controller.

This PR when merged should allow protocols to be run on the OT3 as long as you're ok with not homing, having hardcoded pipettes, and changing the default deck calibration to [[1, 0, 0], [0, -1, 0], [0, 0, -1]] and the pipette calibration to have different offsets. Those defaults will follow in other PRs.

Cannot be merged until
- [x] https://github.com/Opentrons/opentrons/pull/9201 is merged
- [x] https://github.com/Opentrons/opentrons/pull/9207 is merged
- [x] https://github.com/Opentrons/opentrons/pull/9209 is merged
- ~[ ] targeted on edge instead of https://github.com/Opentrons/opentrons/tree/ot3-protocol-base which is a synthetic merge-base of edge + the above three prs~ retargeted on ot3-5.0-work
- ~[ ] 5.0.0 will no longer be including changes in edge by default~ retargeted on ot3-5.0-work

2021-12-09 22:12 UTC, shlokamin requested changes
this is raaaad! we'll need to add these new pipettes to the block lists for pipette dropdowns in PD + the app so they don't show up. I can do that if you want!

See the `PipetteSelect` in shared components, it takes a `nameBlocklist` prop that consuming components in PD + the app should now be utilizing.

2021-12-10 14:33 UTC, mcous approved these changes
PE stuff looks good, just a couple comments about things this PR makes redundant

2021-12-10 14:33 UTC, mcous commented on api/src/opentrons/protocol_engine/resources/deck_data_provider.py
>      async def get_deck_definition(short_fixed_trash: bool = False) -> DeckDefinitionV2:
This `short_fixed_trash` arg is entirely unused by the ProtocolEngine code. Since we're consolidating FF checking into `deck_type`, which is nice, we can safely remove this arg (and the two tests in `tests/opentrons/protocol_engine/resources/test_deck_data_provider.py` that use it can be removed)

2021-12-10 14:33 UTC, mcous commented on api/src/opentrons/protocols/geometry/deck.py
> +    def __init__(self, load_name: str = "") -> None:
Can this be optional, instead of empty-string-as-falsey?

```suggestion
    def __init__(self, load_name: Optional[str] = None) -> None:
```

2021-12-10 14:33 UTC, mcous commented on api/tests/opentrons/protocol_engine/conftest.py
> +    SHORT_TRASH_DECK,
Following up on the comment above about FF logic consolidation; this import (and the `short_trash_deck_def` below) can be removed if that unused arg is removed

2022-01-06 16:39 UTC, amitlissack commented on api/src/opentrons/hardware_control/hardware_protocols.py
> +    def get_attached_instrument(self, mount: Mount) -> "PipetteDict":
Does `PipetteDict` need to be quoted?

2022-01-06 16:39 UTC, amitlissack commented on api/src/opentrons/hardware_control/hardware_protocols.py
> +        """Home the two z-axes"""
If this homes both z axes why does it take a `mount` argument?

2022-01-06 16:39 UTC, amitlissack commented on api/src/opentrons/hardware_control/hardware_protocols.py
> +        """Home the entire robot and initialize current position.
nit. this function homes a list of axes.

2022-01-06 16:39 UTC, amitlissack commented on api/src/opentrons/hardware_control/hardware_protocols.py
> +        ...
Doc string?

2022-01-06 16:43 UTC, sfoster1 commented on api/src/opentrons/hardware_control/hardware_protocols.py
> +    def get_attached_instrument(self, mount: Mount) -> "PipetteDict":
I think not since we put type extensions on the robot

2022-01-06 16:44 UTC, sfoster1 commented on api/src/opentrons/hardware_control/hardware_protocols.py
> +        """Home the two z-axes"""
docstring's out of date

2022-01-07 17:49 UTC, sfoster1 commented
> this is raaaad! we'll need to add these new pipettes to the block lists for pipette dropdowns in PD + the app so they don't show up. I can do that if you want!
> 
> See the `PipetteSelect` in shared components, it takes a `nameBlocklist` prop that consuming components in PD + the app should now be utilizing.

This code moved to https://github.com/Opentrons/opentrons/pull/9207

2022-01-07 17:49 UTC, sfoster1 commented on api/tests/opentrons/protocol_engine/conftest.py
> +    SHORT_TRASH_DECK,
This code moved to https://github.com/Opentrons/opentrons/pull/9207

2022-01-07 17:50 UTC, sfoster1 commented
> this is raaaad! we'll need to add these new pipettes to the block lists for pipette dropdowns in PD + the app so they don't show up. I can do that if you want!
> 
> See the `PipetteSelect` in shared components, it takes a `nameBlocklist` prop that consuming components in PD + the app should now be utilizing.

This code moved to https://github.com/Opentrons/opentrons/pull/9209

2022-01-07 17:51 UTC, sfoster1 commented on api/src/opentrons/hardware_control/hardware_protocols.py
> +    def get_attached_instrument(self, mount: Mount) -> "PipetteDict":
This code moved to https://github.com/Opentrons/opentrons/pull/9201

2022-01-18 16:57 UTC, shlokamin approved these changes
sounds like the pipette select work got pulled from this PR so we can worry about that elsewhere

2022-01-24 15:28 UTC, Laura-Danielle approved these changes
Had two comments, in general looks good.

2022-01-24 15:28 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +    async def identify(self, duration_s: int = 5):
Should we remove this since the LED stuff will be different?

2022-01-24 15:28 UTC, Laura-Danielle commented on hardware/tests/test_scripts/test_can_comm.py
> +        can_comm.prompt_payload(GetStatusResponsePayload, mock_get_input)
Why did we change this to `GetStatus`?

2022-01-24 15:37 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +    async def identify(self, duration_s: int = 5):
We should maybe remove the specific LED stuff (though I think we should wait on that) but `identify` in and of itself is actually a kind of generic semantic concept that can stay.

2022-01-24 15:38 UTC, sfoster1 commented on hardware/tests/test_scripts/test_can_comm.py
> +        can_comm.prompt_payload(GetStatusResponsePayload, mock_get_input)
The test changed because the device info prompt isn't the same as it used to be. There are probably other ways to change it though.

2022-01-25 21:38 UTC, merged