refactor(app): disable LPC CTA when empty protocol is uploaded
OpenTrons/opentrons-api pull request #9063
Opened 2021-12-09 21:37 UTC by sakibh

# Overview

This PR will disable the LPC CTA on the Labware Setup Step if the protocol doesn't include at least one labware AND one pipette. closes #9041

![Screen Shot 2021-12-09 at 3 33 05 PM](https://user-images.githubusercontent.com/14794021/145479086-7c5e2fe9-6fcb-477d-b7af-eb7c57ba213b.png)

# Changelog

- Added boolean to check if `protocolData` contains labware and pipettes, in order to disable the LPC CTA and display a tool tip.
- Added test to check if LPC CTA is disabled with protocolData for pipettes and labware is empty.

# Review requests

- Check that the LPC CTA is disabled with the correct tool tip message when a protocol that doesn't include at least one labware AND one pipette is uploaded.

# Risk assessment

low

2021-12-09 21:56 UTC, b-cooper requested changes
Looking good. Left a few comments

2021-12-09 21:56 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx
> +                      {t('labware_position_check_not_available_empty_protocol')}
Just curious, is this `Box` strictly required? What happens if you just pass the `{t('labware_position_check_not_available_empty_protocol')}` as the children of the `<Tooltip >`

2021-12-09 21:56 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx
> +    isEmpty(protocolData?.pipettes) && isEmpty(protocolData?.labware)
I think technically this needs to `isEmpty(protocolData?.pipettes) || isEmpty(protocolData?.labware)` . LPC is meaningless is either of them is empty

2021-12-09 21:56 UTC, b-cooper commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx
> +  const disableLabwarePositionCheckEmptyProtocols =
Now that we've got two possible reasons that the LPC CTA could be disabled, a cleaner pattern to use is `disabledReason: string | null` . We use this in `app/src/App/hooks` to establish the reason behind disabling certain navigation items.  Basically, here we'd declare a `let lpcDisabledReason: string | null = null` and then follow with if statement for the two cases 
```
if (runStatus != null && runStatus !== RUN_STATUS_IDLE){
  lpcDisabledReason = t(...)
} else if (isEmpty(protocolData?.pipettes) && isEmpty(protocolData?.labware)) {
  lpcDisabledReason = t(...)
}
```

Then later on we only need to have one tooltip and we render it as long as `lpcDisabledReason !== null`. Same for the button's `disabled` prop.

2021-12-09 22:22 UTC, sakibh commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx
> +  const disableLabwarePositionCheckEmptyProtocols =
Thanks for suggesting this. Great way to DRY this up!

2021-12-09 22:23 UTC, sakibh commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx
> +    isEmpty(protocolData?.pipettes) && isEmpty(protocolData?.labware)
Great catch on this! You are right that it definitely should be OR.

2021-12-09 22:24 UTC, sakibh commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx
> +                      {t('labware_position_check_not_available_empty_protocol')}
Yep, it works just fine without the `Box`.

2021-12-10 18:51 UTC, b-cooper approved these changes
Looks awesome 😎

2021-12-10 19:26 UTC, merged