refactor(app): add a status to the protocol run record for last run
OpenTrons/opentrons-api pull request #9073
Opened 2021-12-10 19:12 UTC by sakibh

# Overview

This PR adds a Run status for the most recent run protocol in the upload page's empty state. closes #9031 

Run status:
![Screen Shot 2021-12-10 at 1 59 31 PM](https://user-images.githubusercontent.com/14794021/145628669-ce481ed8-478c-4615-9b30-330885c3e668.png)

Modal copy:
![Screen Shot 2021-12-10 at 2 03 24 PM](https://user-images.githubusercontent.com/14794021/145628706-323f309b-80e9-464e-8e46-7f9e69f2cee1.png)

# Changelog

- Added Run status column to last run protocol in the `UploadInput` component
- Added `getMostRecentRunStatus` utility function to retrieve the most recent run status for the front-end
- Added tests
- Fixed the retrieval of the most recent protocol run id in the `useMostRecentRunId` hook
- Updated modal copy

# Review requests

- Check that when you upload a protocol and then close it immediately the status is `Not started`
- Check that when you upload a protocol and then cancel it in the middle of a run the status is `Canceled`
- Check that when you upload a protocol and then complete the entire run, the status is `Complete`

# Risk assessment

low

2021-12-10 19:27 UTC, jerader reviewed
Looking good and works as expected on my robot. The only thing is the bullet points are missing on the [modal](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0%3A-Protocol-Upload-Revamp?node-id=9788%3A180017) (before Not Started, Canceled, Complete)

2021-12-13 15:43 UTC, sakibh commented
> Looking good and works as expected on my robot. The only thing is the bullet points are missing on the [modal](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0%3A-Protocol-Upload-Revamp?node-id=9788%3A180017) (before Not Started, Canceled, Complete)

Thanks for testing! I added the bullet points in now.

![image](https://user-images.githubusercontent.com/14794021/145842636-643c01f6-4c87-438d-8bbb-d606a3ddb21a.png)

2021-12-13 17:01 UTC, jerader commented
> > Looking good and works as expected on my robot. The only thing is the bullet points are missing on the [modal](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0%3A-Protocol-Upload-Revamp?node-id=9788%3A180017) (before Not Started, Canceled, Complete)
> 
> Thanks for testing! I added the bullet points in now.
> 
> ![image](https://user-images.githubusercontent.com/14794021/145842636-643c01f6-4c87-438d-8bbb-d606a3ddb21a.png)

@sakibh I think the text after `canceled` and `complete` aren't supposed to be bold

2021-12-13 17:39 UTC, sakibh commented
> 
> @sakibh I think the text after `canceled` and `complete` aren't supposed to be bold

Completely overlooked this 🤦‍♂️.  Turns out the `<list>` tag needs to come before `<strong>`. It is good now: 
![image](https://user-images.githubusercontent.com/14794021/145861090-c5e9be54-f4f2-4fb8-95c8-eb682466e7a5.png)

2021-12-14 17:58 UTC, shlokamin requested changes

2021-12-14 17:58 UTC, shlokamin commented on app/src/organisms/ProtocolUpload/getMostRecentRunStatus.ts
> +}
a couple of things here:

1. It looks like this function accepts a run, and returns it's status. this util can be used to get the status of any run, regardless of whether it's the most recent run or not. I think we should rename this to `getRunDisplayStatus` so that the name conveys it's flexibility (and the fact that this is a display status, which is distinct from the status on the run record itself)
2. If the run's status is stopped, then for it to be in a `cancelled` state, we just need to make sure a `PLAY` was issued at some point right? not just that it was the first action to have been dispatched

2021-12-14 17:58 UTC, shlokamin commented on app/src/organisms/ProtocolUpload/hooks/useMostRecentRunId.ts
>  }
can you provide context on this? did we have it backwards before?

2021-12-14 17:59 UTC, shlokamin commented
Looking good! added a few comments but this is solid overall, and thanks for adding test coverage :)

2021-12-14 18:03 UTC, sakibh commented on app/src/organisms/ProtocolUpload/hooks/useMostRecentRunId.ts
>  }
The following: `allRuns.data[0].id` returns the first run id in the runs array returned by the API. But the most recent run is the last item on the array. If you upload a protocol and then cancel you will notice in the empty upload state that the run record never changes, this seems to be because it is always referencing the first run that was created and not the most recent run.

2021-12-14 18:06 UTC, sakibh commented on app/src/organisms/ProtocolUpload/getMostRecentRunStatus.ts
> +}
1. That definitely makes sense. I will rename this to `getRunDisplayStatus`
2. I'm not 100% sure on this. If a run is started, will the first action always be a `PLAY` action? I can alternatively just map through the actions and look for a `PLAY` instead of checking if the first action is a `PLAY`?

2021-12-14 18:40 UTC, shlokamin commented on app/src/organisms/ProtocolUpload/getMostRecentRunStatus.ts
> +}
for 2. you can just do a [find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

2021-12-14 18:40 UTC, shlokamin commented on app/src/organisms/ProtocolUpload/hooks/useMostRecentRunId.ts
>  }
sweet, thanks @sakibh !

2021-12-15 18:55 UTC, shlokamin approved these changes
code changes look good to me, thanks @sakibh !

2021-12-15 20:16 UTC, merged