feat(api): remove Calibrate to Bottom from Robot Settings
OpenTrons/opentrons-api pull request #9111
Opened 2021-12-15 15:19 UTC by jerader

closes #9093

# Overview

This PR removes the `Calibrate to Bottom` settings in the robot settings

# Changelog

-

# Review requests

- put the build from this Pr on your robot and factory reset and/or restart server - `Calibrate to Bottom` should no longer be an option

# Risk assessment

Low, behind ff

2022-01-13 15:26 UTC, SyntaxColoring requested changes
I don't really understand all the nuances of our JSON config migration and how it relates to robot server upgrades/downgrades, but according to this comment in `advanced_settings.py`, we should add a migration and tests for this?

```python
# If you add or remove any settings here BE SURE TO ADD A MIGRATION below.
# You will also need to update the migration tests in:
# api/tests/opentrons/config/test_advanced_settings_migration.py
```

2022-01-13 15:55 UTC, shlokamin commented
Oh good catch @SyntaxColoring, thanks!

2022-01-13 16:09 UTC, mcous requested changes
This change requires a config migration on the API side. See #8913 for an example of what's required in the `opentrons.config` module when removing a setting

2022-01-14 20:02 UTC, mcous approved these changes

2022-01-14 20:28 UTC, SyntaxColoring approved these changes

2022-01-14 21:19 UTC, merged