refactor(app): move apply labware offsets to hook and out of summary screen
OpenTrons/opentrons-api pull request #9116
Opened 2021-12-15 20:53 UTC by jerader

closes #8905 

# Overview

This PR moves apply labware offset logic from the summary screen and into the `useLabwarePostionCheck` hook

# Changelog

- refactored the logic and also extended a few props

# Review requests

- I ran this on my robot and it worked but best to run on another robot to make sure this didn't break anything
- I tried moving the `useLabwareOffset` hook from the `summaryScreen` and into the `useLabwarePositionCheck` hook but it kept completely freezing LPC, so I kept it in `summaryScreen` but not sure if I should move it

# Risk assessment

low, behind ff

2021-12-17 22:34 UTC, sakibh approved these changes
LGTM! Tested on my robot and LPC is working as expected.

2022-01-03 17:00 UTC, shlokamin requested changes

2022-01-03 17:00 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/__tests__/SummaryScreen.test.tsx
> +  LabwareOffsetLocation: { slotName: 'slot' },
i dont think this should be capitalized

2022-01-03 17:00 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/hooks/useLabwarePositionCheck.ts
> +      setLabwareOffsets: (active: LabwareOffsets) => void
This hook should not be exposing the `setLabwareOffsets` setter, this should be an implementation detail handled inside of this hook. This hook should call `useLabwareOffsets` directly and return `labwareOffsets`

2022-01-07 19:41 UTC, jerader commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/__tests__/SummaryScreen.test.tsx
> +  LabwareOffsetLocation: { slotName: 'slot' },
oh yup, you're right. Good catch!

2022-01-10 13:00 UTC, jerader commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/hooks/useLabwarePositionCheck.ts
> +      setLabwareOffsets: (active: LabwareOffsets) => void
Cool, I fixed that and it broke the LPC button on `labwareSetup/index`. No error pops up in console. 🤔

2022-01-10 18:19 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/LabwarePositionCheck/hooks/useLabwarePositionCheck.ts
> +      setLabwareOffsets: (active: LabwareOffsets) => void
what's happening is we're performing a bunch of state updates over and over again when we call `setLabwareOffsets`. the fix is to only apply state updates when `labwareOffsets.length === 0`, but then we run into another problem...

since before `useLabwareOffsets` was called from inside the summary screen, it was called only when we had enough data to calculate our labware offsets (meaning, when `savePositionCommandData` was actually filled out).

now that we've moved calls to `useLabwareOffsets` inside of `useLabwarePositionCheck`, we have to call `useLabwareOffsets` immediately in order to [not violate the rules of React hooks ](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level). this means we're calling the hook before we have all of our data, which will actually cause a white screen because inside of `useOffsetDataByLabwareId`, we throw an error when we don't have all of our `savePositionCommandData`.

there are ways to get around all of this (like passing is a `isCompleted` boolean into the hooks and having them return default data when the boolean is not true), but tbh i think that actually makes things more confusing and misleading.

the hooks to calculate offset data are really only relevant once we, well, have offset data. so in order to use them as is, they need to only be called from  the `SummaryScreen`.  we should honestly do a larger refactor and change the core logic for how offsets are calculated, but i don't think that is a good use of time at the moment given the crunch we're in.

let's table this ticket until after the 5.0 release and come back to it. sorry this turned out to open a bigger can of worms than I thought :/

2022-01-11 20:32 UTC, shlokamin commented
closing this, we;'ll address this later

2022-01-11 20:32 UTC, closed without merging