fix: Fix poetry errors
OpenTrons/opentrons-api pull request #9176
Opened 2022-01-03 16:06 UTC by DerekMaggio

# Overview

# Changelog

# Review requests

# Risk assessment

2022-01-03 17:29 UTC, sfoster1 requested changes
Looks like line 12 of this file has the wrong name for itself  which is why the test isn't triggering on this PR, we should fix that

2022-01-03 17:54 UTC, DerekMaggio commented
> Looks like line 12 of this file has the wrong name for itself which is why the test isn't triggering on this PR, we should fix that

https://github.com/Opentrons/opentrons/pull/9176/commits/554a85ac7e255800e3e5313de979bc75d36d6a20

2022-01-04 18:31 UTC, amitlissack approved these changes
Rockin

2022-01-04 18:33 UTC, sfoster1 approved these changes
lgtm!

2022-01-04 18:34 UTC, merged