feat(app): add jupyter advanced setting to download offset data
OpenTrons/opentrons-api pull request #9284
Opened 2022-01-20 21:59 UTC by sakibh

# Overview

This PR adds a toggle in the advanced settings for jupyter and ssh users to download offset data. This addresses the first task in #9059

![image](https://user-images.githubusercontent.com/14794021/150428442-7f757ec6-7c9f-4212-b2de-7156c432eb1a.png)

# Changelog

- Added toggle item in advanced settings
- Added selector for labware offset data toggle
- Added new schema type in redux config
- Added test coverage for selector and component

# Review requests

- Check that the toggle item matches the design and copy of the [Figma design](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0%3A-Protocol-Upload-Revamp?node-id=9846%3A186829)
- Check that the selector is implemented and working properly for use in downstream tasks

# Risk assessment

low

2022-01-20 23:41 UTC, sakibh commented on app/src/redux/config/schema-types.ts
> +  }
Not sure what the naming should be for the schema in redux and also the name of the selector. Open to suggestions.

2022-01-21 16:30 UTC, shlokamin requested changes
I think you're almost there! I'm getting a white screen when i navigate to the more tab where this FF toggle lives. I suspect this is because we need to add a config migration in `app-shell/src/config/migrate.ts` bcuz right now no `robotSettings` property exists on the config. 

lets talk about this after standup though and we can resolve this!

2022-01-24 20:02 UTC, shlokamin approved these changes
left some suggestions, but code changes look good to me and I tested that the config correctly toggles in redux1

2022-01-24 20:02 UTC, shlokamin commented on app-shell/src/config/migrate.ts
> +    // @ts-expect-error (sh: 01-24-2021): migrateVersion function input typed to never
Anyone know why this is happening? I couldn't figure it out :/

2022-01-24 20:02 UTC, shlokamin commented on app-shell/src/buildroot/index.ts
> +            type: 'buildroot:FILE_UPLOAD_DONE' as 'buildroot:FILE_UPLOAD_DONE',
my bad for not thinking of this earlier, but these `as` casts can all be changed to `as const` instead which is more accurate and safer

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions
```suggestion
            type: 'buildroot:FILE_UPLOAD_DONE' as const,
```

2022-01-24 20:02 UTC, shlokamin commented on app-shell/src/buildroot/index.ts
> +              type: 'buildroot:UNEXPECTED_ERROR' as 'buildroot:UNEXPECTED_ERROR',
```suggestion
              type: 'buildroot:UNEXPECTED_ERROR' as const,
```

2022-01-24 20:02 UTC, shlokamin commented on app-shell/src/buildroot/index.ts
> +            type: 'buildroot:USER_FILE_INFO' as 'buildroot:USER_FILE_INFO',
```suggestion
            type: 'buildroot:USER_FILE_INFO' as const,
```

2022-01-24 20:02 UTC, shlokamin commented on app-shell/src/buildroot/index.ts
> +            type: 'buildroot:UNEXPECTED_ERROR' as 'buildroot:UNEXPECTED_ERROR',
```suggestion
            type: 'buildroot:UNEXPECTED_ERROR' as const,
```

2022-01-24 20:03 UTC, shlokamin commented on app-shell/src/config/migrate.ts
> +    // @ts-expect-error (sh: 01-24-2021): migrateVersion function input typed to never
@b-cooper @mcous

2022-01-24 22:09 UTC, b-cooper commented on app-shell/src/config/migrate.ts
> +    // @ts-expect-error (sh: 01-24-2021): migrateVersion function input typed to never
"""
multiple candidates for the same type variable in contra-variant positions causes an intersection type to be inferred.
"""
It looks like we can avoid this with a slight refactor of `MIGRATIONS` const by making it an object (then we loose ordinality). Probably best to punt that refactor to another day though

2022-01-24 22:09 UTC, b-cooper approved these changes

2022-01-24 22:18 UTC, merged