refactor(engine): Simplify multi-threadedness of HW event intake
OpenTrons/opentrons-api pull request #9344
Opened 2022-01-31 18:52 UTC by SyntaxColoring

# Overview

This PR iterates on the work of #9335.

# Changelog

# Review requests

# Risk assessment

2022-01-31 20:54 UTC, mcous requested changes
Can we move this to a sub-dependency (a la HardwareStopper) to avoid polluting the top-level ProtocolEngine class with these concerns? Will likely make testing and resource cleanup easier to grok, too

2022-01-31 20:54 UTC, mcous commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +    # (e.g. with something like contextlib.AsyncExitStack).
We already have an async factory function: `src/opentrons/protocol_engine/create_protocol_engine.py`

2022-01-31 20:54 UTC, mcous commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +        future.result()
Defining an inner async function seems a bit strange here. Does [loop.call_soon_threadsafe](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.call_soon_threadsafe) work without the overhead of the weird nested async function?

2022-01-31 21:01 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +        future.result()
`call_soon_threadsafe()` unfortunately doesn't seem to provide any way of waiting for the call to complete. `run_coroutine_threadsafe` does because it returns a future.

2022-02-01 16:22 UTC, sanni-t commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +            self._remove_hardware_event_watcher()
Good call on moving it up

2022-02-01 16:39 UTC, sanni-t commented on api/src/opentrons/protocol_runner/protocol_runner.py
> +        #   3.
I am not sure if the background task calls `engine.finish()` after a cancel. The second call to finish comes from the robot server when it tries to delete a run, which calls `engine_store.clear()` which calls `engine.finish()`.

2022-02-01 16:44 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/protocol_runner.py
> +        #   3.
Interesting.

I was looking at this:

https://github.com/Opentrons/opentrons/blob/1b58b4e69fa70ce16eb5a5a2e2956341397b3033/api/src/opentrons/protocol_runner/protocol_runner.py#L97

Which reads to me as "call `.finish()` indiscriminately at the "end" of a "run," but it's not clear to me what "end" or "run" precisely mean, here. I *think* it includes cancellation, but I'm not sure.

2022-02-01 20:31 UTC, sanni-t commented on api/src/opentrons/protocol_runner/protocol_runner.py
> +        #   3.
(Noting down my reply from call) Sorry, you are right, `engine.finish()` gets called after a cancel but it won't get called twice by the runner/ the background task. The second call I saw was probably from when I tried to close out the protocol in the app and it sent a run delete request.

2022-02-01 20:48 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/protocol_runner.py
> +        #   3.
Removing this unfinished `# todo` because I don't really understand this.

I think it's a big red flag that we're having to account for `.finish()` being called more than once; the calling structures above Protocol Engine ought to do exactly-once resource cleanup. But we'll have to look into that separately.

2022-02-01 20:49 UTC, SyntaxColoring commented on api/src/opentrons/protocol_engine/protocol_engine.py
> +    # (e.g. with something like contextlib.AsyncExitStack).
[Discussed in call] Removing this `todo` because we're not aligned on it.

2022-02-01 21:03 UTC, mcous approved these changes

2022-02-01 21:31 UTC, sanni-t approved these changes
LGTM! Just a comment

2022-02-01 21:31 UTC, sanni-t commented on api/src/opentrons/protocol_engine/execution/hardware_event_forwarder.py
> +        # NOTE: We assume we're being called from a separate thread
I think this should go in the docstring since it dictates how the method should be used

2022-02-01 22:11 UTC, merged