refactor(api,robot-server): Remove Pydantic `.construct()`s in tests
OpenTrons/opentrons-api pull request #9428
Opened 2022-02-10 22:41 UTC by SyntaxColoring

This PR replaces, in test files, Pydantic `Model.construct(...)` with `Model(...)`. Before this PR, we had an inconsistent mixture of both.

This was decided previously on the CPX squad. Our rationale was roughly:

* The performance benefits of `.construct()` are not worthwhile in tests
* The runtime validation in tests is a nice final defense in case our production code does something that subverts static type-checking, like `.update({...})`, and it gets it wrong somehow.

# Review requests

I used a global search and replace here. Skim over the code and make sure there's nothing obviously wrong.

# Risk assessment

Very low. Changes are only to test files

2022-02-10 22:59 UTC, SyntaxColoring commented
Uh okay it looks like this broke a lot:

* `decoy.matchers`, which sort of makes sense.
* New errors about missing fields? Does the Pydantic plugin for Mypy not warn us if fields are missing in `.construct()`? If so, that's pretty horrifying.
* Other new errors? Why is `tests/runs/router/test_commands_router.py::test_get_run_commands` failing with what looks like an actual data mismatch?

2022-02-11 17:28 UTC, mcous requested changes
Only commented on a couple demonstration lines, but everything that either...

- Uses a `matchers` object, or
- Omits required parameters that aren't used by the code under test
    - These lines should have `type-ignore[call-args]` comments 
    - Aside: this for sure a questionable practice, be we can leave addressing that outside the scope of this PR

...should be using `construct`.

I think that means from this PR, the only changes we want to be making are in `robot-server`. That makes sense to me, I bet they were caught up in a find-and-replace-all or something

2022-02-11 17:28 UTC, mcous commented on api/tests/opentrons/protocol_engine/state/test_module_store.py
> +        command=commands.LoadModule(  # type: ignore[call-arg]
This was construct due to a bunch of missing required parameters, which is also what the `# type: ignore[call-arg]` is there for

2022-02-11 17:28 UTC, mcous commented on api/tests/opentrons/protocol_runner/smoke_tests/test_json_file_reader.py
> +    assert result == json_protocol.Model(
This uses a `matchers.IsA(dict)` down on line 43

2022-02-24 19:30 UTC, mcous approved these changes
Reverted the `construct` removals that should not have happened so we can close this PR out

2022-02-24 20:47 UTC, merged