feat(api): Integrate acceleration in OT3 hardware control api
OpenTrons/opentrons-api pull request #9432
Opened 2022-02-11 02:34 UTC by ahiuchingau

We're integrating motion blending in the OT3 HC api.

Couple todos after this PR:
* retrieve the correct pipette kind based on cached instruments
* update system constraints in MoveManager using the correct pipette kind
* `api._backend.move_block` is currently kind of hacky and should be refactored
* remove `api._backend.move` since it should be replaced by `move_block()`
* use real max speeds for each axis
* consolidate all of the Axis enums in the monorepo, and make it easier to look up node id using Axis

2022-02-11 15:01 UTC, sfoster1 requested changes
Think we should refactor how the moves get sent to the firmwares

2022-02-11 15:01 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +                for move in moves[0]:
This iteration is in the wrong place I think. We really want all the outputs of the move blending to live in the same move group. There needs to be 0 latency between blocks (and honestly between moves, whenever we have multiple moves blended together) so they all need to be provided to the firmwares by the time they get to executing them.

2022-02-11 15:01 UTC, sfoster1 commented on api/src/opentrons/config/robot_configs.py
> +            config.acceleration.none[axis.lookup],
This will get a little easier with #9433 but I think even for now we should avoid changing the `Axis` type in favor of having a like `_constraint_for_axis(axis: Axis) -> str` little method in this module since I think this is the only place `Axis.lookup` is used

2022-02-11 15:01 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3simulator.py
> +        block: Block,
this I think should probably take a `List[Move]` - we want every output of the blending to be in the same move group, that's why we have the move groups.

2022-02-14 15:27 UTC, sfoster1 approved these changes
Looks great to me!

2022-02-15 15:18 UTC, Laura-Danielle approved these changes
Looks great! Had some random comments/questions, but they could be addressed in follow-ups. I don't have a preference.

2022-02-15 15:18 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +        self._pipette_kind = PipetteKind.NONE
So `pipette_kind` here refers to the entire gantry configuration? I'm getting a little confused by the usage. I know that we have parameters for the different types of pipettes/how many/if there is a gripper, but I feel like it might make more sense to call this thing 'gantry configuration' or something of the sort.

Doesn't necessarily need to be addressed in this PR, but something to keep in mind.

2022-02-15 15:18 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +        except ZeroLengthMoveError as zero_length_error:
What type of move would cause this error? Is there a way we can detect it before the hardware controller?

2022-02-15 15:18 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/scripts/repl.py
> -from opentrons.types import Mount, Point  # noqa: E402
🙌

2022-02-15 15:18 UTC, Laura-Danielle commented on hardware/opentrons_hardware/hardware_control/motion_planning/types.py
> +@dataclasses.dataclass(frozen=False)
We should just take out the `frozen` parameter if we don't want to use it. Dataclasses default to frozen being false iirc.

2022-02-15 15:18 UTC, Laura-Danielle commented on hardware/tests/opentrons_hardware/hardware_control/test_motion_plan.py
> +        "B": b_constraint,
Are we calling the pipette motors `P` or sticking with `B` and `C`?

2022-02-15 16:08 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        except ZeroLengthMoveError as zero_length_error:
It happens when the move doesn't actually do anything. The place it most frequently arose was in tests for something like pick up tip. A lot of those tests are written to either not "move" the gantry, or "move" it over the tip once and then repeatedly do the pickup with different params, so the phase of the protocol context pickup where you move to the tiprack doesn't do anything. It could happen in a protocol if someone did a move to `tiprack["A1"]` and then `pick_up_tip(tiprack["A1"])`. 

The protocol context habitually doesn't ask for current position before issuing moves, and it shouldn't - it wants to be idempotent and not really care about the state before the command, just the state after the command. Even the hardware controller doesn't really care, and given the number of different ways that you can get to `_move` I think this kind of error handling path is reasonable. It's a bad idea to use exceptions for control flow, but _to the motion math section_ this is a legitimately exceptional case - the caller just doesn't care.

2022-02-15 16:08 UTC, sfoster1 commented on hardware/tests/opentrons_hardware/hardware_control/test_motion_plan.py
> +        "B": b_constraint,
P for sure, but that's gonna have to wait for #9433

2022-02-15 21:02 UTC, merged