refactor(api): Add more stub methods to APIv3 `MagneticModuleContext`
OpenTrons/opentrons-api pull request #9473
Opened 2022-02-15 17:50 UTC by SyntaxColoring

# Overview

This is a step towards #9393. It sets the method signatures for Python Protocol API v3's version of `MagneticModuleContext`.

# Changelog

Things are almost entirely unchanged from APIv2. The differences are:

* Added strict parameter validation to `.engage()` to disallow, for example, setting `height` and `offset` simultaneously. In APIv2, this appears permitted with the undocumented behavior that one is favored over the other.
* Removed the `.geometry` property, which seemed internal and not legitimately usable by protocol authors.
* Removed `.load_labware_by_name()`, which has long been deprecated in favor of `.load_labware()`. 

I've also noted these in Confluence.

# Review requests

Do all method signatures look good? Do we agree with the changes?

# Risk assessment

None. No one is using this code yet.

2022-02-15 18:03 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api_experimental/module_contexts/magnetic_module_context.py
> +    # every time the module is retrieved. If yes, we don't need this method.
I'm having trouble digging up a reference, but I *think* people are relying on this being true. Or maybe I'm thinking of labware objects or well objects?

2022-02-15 19:35 UTC, mcous requested changes
Looks on the right track to me

2022-02-15 19:35 UTC, mcous commented on api/src/opentrons/protocol_api_experimental/module_contexts/magnetic_module_context.py
> +        if len([a for a in [height, height_from_base, offset] if a is not None]) > 1:
Can we encode this as an `@overload`, too?

2022-02-15 19:35 UTC, mcous commented on api/src/opentrons/protocol_api_experimental/module_contexts/magnetic_module_context.py
> +        """See APIv2 docstring."""
I'd softly prefer a noqa and a TODO compared to a docstring that may be overlooked

2022-02-15 19:35 UTC, mcous commented on api/src/opentrons/protocol_api_experimental/module_contexts/magnetic_module_context.py
> +        raise NotImplementedError()
I agree, _and_ its not in the user-facing docs. Let's ditch it in this PR

2022-02-15 19:35 UTC, mcous commented on api/src/opentrons/protocol_api_experimental/module_contexts/magnetic_module_context.py
> +    def status(self) -> Literal["engaged", "disengaged"]:
Let's encode this as a `class MagneticModuleStatus(str, Enum)` instead. Still a string, so not a breaking change

2022-02-15 19:35 UTC, mcous commented on api/src/opentrons/protocol_api_experimental/module_contexts/magnetic_module_context.py
> +    # every time the module is retrieved. If yes, we don't need this method.
Our lives are much easier with this custom `__eq__` (and probably a `__hash__`, too) in place based on PE identity. I'd also like to preserve our ability to return new objects as an implementation detail. Can we remove this TODO?

2022-02-15 19:35 UTC, mcous commented on api/src/opentrons/protocol_api_experimental/module_contexts/magnetic_module_context.py
> +            raise ValueError(
Can this be defined as a custom `ValueError` in `opentrons.protocol_api_experimental.errors`?

2022-02-15 19:41 UTC, SyntaxColoring commented on api/src/opentrons/protocol_api_experimental/module_contexts/magnetic_module_context.py
> +        raise NotImplementedError()
[Discussed in call] This *is* in the docs it turns out, but we're ditching this anyway because it doesn't make sense in APIv3. Also, so far, we've heard no objections from internal folks in Slack.

2022-02-15 23:19 UTC, mcous approved these changes

2022-02-15 23:39 UTC, sanni-t approved these changes
LGTM! 
As discussed in the call, would like to get the ok from apps engg on removal of `load_labware_object()`

2022-02-16 14:35 UTC, sanni-t commented on api/src/opentrons/protocol_api_experimental/module_contexts/magnetic_module_context.py
> +    def calibrate(self) -> None:  # noqa: D102
Thought a bit more about this and I think it should be safe to remove. `Calibrate` will simply move the magnets upto a point where it'll bump up against the walls of the wells. Afaik, the magnets need to be brought up to a very specific height for the protocol and not just 'as high as they can be' in the labware. The calibration or 'plate probing' feature was added so that a user could move the mag bed to the highest point and then query the height of that point and then use +/- this value in `engage`. The API doesn't expose the current height property so the use of `calibrate` gets restricted to only those few cases where a user would really need the magnets to just move to the highest accessible point along the wells. Definitely worth confirming with science/ apps engg but I feel less anxious about removing this now.

2022-02-16 15:18 UTC, SyntaxColoring commented
No objections heard from Support or Applications Engineering.

2022-02-16 15:32 UTC, merged