refactor(api): use correct sys constraints for OT3
OpenTrons/opentrons-api pull request #9484
Opened 2022-02-16 15:24 UTC by ahiuchingau

This PR reconfigures the new OT3config by grouping the speed settings (accelerations, max speeds, max speed discontinuity) together. Once we can cache the correct pipette kind based on hardware, the system constraints will be able to load the correctly associated speed settings from the config.

2022-02-16 15:30 UTC, Laura-Danielle commented on api/src/opentrons/config/types.py
> +    def by_pipette_kind(
can we change to `gantry_configuration` in this PR?

2022-02-16 16:04 UTC, sfoster1 requested changes
Can we call it motion settings or something? otherwise looks good!

2022-02-16 16:04 UTC, sfoster1 commented on api/src/opentrons/config/defaults_ot3.py
> +        speed_settings=OT3SpeedSettings(
this is a nit but can we call this motion settings since it also has acceleration

2022-02-16 16:06 UTC, ahiuchingau commented on api/src/opentrons/config/types.py
> +    def by_pipette_kind(
How about `gantry_load` or something like that? Gantry_configuration.none doesn't quite make sense to me.

2022-02-16 16:30 UTC, Laura-Danielle commented on api/src/opentrons/config/types.py
> +    def by_pipette_kind(
sure that sounds fine to me

2022-02-17 14:33 UTC, sfoster1 approved these changes
Great!

2022-02-17 16:32 UTC, Laura-Danielle approved these changes
ty

2022-02-17 16:32 UTC, merged