fix(app): fix heater shaker intro pg and misc typography
OpenTrons/opentrons-api pull request #9493
Opened 2022-02-16 22:54 UTC by jerader

# Overview

addresses comments in https://github.com/Opentrons/opentrons/pull/9469#pullrequestreview-885099211

fixes missing key in `MenuList`

# Changelog

- remove improper usage of TYPOGRAPHY
- adds unique key to `MenuList`
- addresses a few PR comments in `Introduction`

# Review requests

- review usage of TYPOGRAPHY

# Risk assessment

low

2022-02-17 16:29 UTC, shlokamin requested changes
Looking good! left a few comments. Sorry to jostle you back and forth, but I think getting this stuff right early is important because everything in the unified app is going to be built on top of these building blocks you are making now, which is kinda cool 😎

2022-02-17 16:29 UTC, shlokamin commented on app/src/assets/localization/en/heater_shaker.json
> +  "intro_wizard_modal_page_title": "{{name}} - Attach Heater Shaker Module",
i think these name changes are the opposite of what Brian meant [in his PR comment](https://github.com/Opentrons/opentrons/pull/9469#discussion_r808421248), i think he was trying to say we should name thing according to meaning, not implementation (so avoid things like `btn` or `intro`

2022-02-17 16:29 UTC, shlokamin commented on app/src/atoms/Banner/Banner.tsx
> +          marginTop={'2.75rem'}
may as well throw this in `components/src/ui-style-constants/spacing.ts`

2022-02-17 16:29 UTC, shlokamin commented on app/src/atoms/MenuList/MenuItem.tsx
> +  width: 9.562rem;
i know this width is just a translation of what's in figma, but i think we should refrain from assigning fixed widths to buttons. the reason being is because they should grow and shrink depending on their text contents. If in i18n we added another language, we'd want the button to accommodate for the difference in text. If we specify a fixed width, the button wouldn't adjust to the change in space the text makes. 

ping @mmencarelli

2022-02-17 16:29 UTC, shlokamin commented on app/src/atoms/MenuList/MenuList.stories.tsx
> +  width: 9.562rem;
same thing here

2022-02-17 16:29 UTC, shlokamin commented on app/src/atoms/ModalPage/index.tsx
> +        padding={'1rem'}
can use `spacing4` here

2022-02-17 16:29 UTC, shlokamin commented on app/src/organisms/Devices/HeaterShakerWizard/Introduction.tsx
> +      <Flex flexDirection={DIRECTION_COLUMN} paddingRight={'1.25rem'}>
`spacingM` should work here

2022-02-17 16:29 UTC, shlokamin commented on app/src/organisms/Devices/HeaterShakerWizard/index.tsx
> +        buttonContent = t('btn_complete')
i think what you had before (`complete `) was correct! `btn_complete` ties the word to an implementation (a button) which we don't want.

2022-02-17 16:29 UTC, shlokamin commented on app/src/organisms/Devices/HeaterShakerWizard/index.tsx
> +          title: t('intro_wizard_modal_page_title', { name: robotName }),
this could probably be renamed to `intro_title` to remove references to implementation details

2022-02-17 16:29 UTC, shlokamin commented on app/src/organisms/Devices/HeaterShakerWizard/index.tsx
> +              {t('btn_back')}
same thing here, `back` was fine!

2022-02-17 16:29 UTC, shlokamin commented on components/src/modals/DeprecatedModalPage.tsx
> +export function DeprecatedModalPage(
we should mark this as deprecated using the `@deprecated` decorator: https://github.com/Opentrons/opentrons/blob/273be7a9b90eb2a488858efc3fe60992e24fd124/components/src/tooltips/HoverTooltip.tsx#L36

2022-02-17 16:29 UTC, shlokamin commented on components/src/modals/DeprecatedModalPage.tsx
> +export function DeprecatedModalPage(
Also, as long as we mark the old `ModalPage` component as `@deprecated`, we can keep the name the same. We should probably rename our new component that you've made to something new like `Interstitial`. We can talk about this after standup with Mel though and see what she thinks

2022-02-17 16:33 UTC, shlokamin commented on app/src/organisms/Devices/HeaterShakerWizard/index.tsx
> +          title: t('intro_wizard_modal_page_title', { name: robotName }),
actually i think i might be confused here too, lets talk about this after standup

2022-02-17 16:50 UTC, shlokamin commented on app/src/organisms/Devices/HeaterShakerWizard/index.tsx
> +          title: t('intro_wizard_modal_page_title', { name: robotName }),
as per the convo after standup, something like `heater_shaker_setup_description` or something

2022-02-18 21:24 UTC, shlokamin commented on app/src/assets/localization/en/heater_shaker.json
> +  "t10_torx_screwdriver": "T10 Torx Screwdriver",
nit: not sure if this should go in i18n since it seems like a proper noun

2022-02-18 21:24 UTC, shlokamin commented on components/src/structure/DeprecatedTitleBar.tsx
> +): JSX.Element {
Since our new title bar has a new name (`InterstitialTitleBar`) we don't need to change the name of the old `TitleBar` to `DeprecatedTitleBar`. My personal preference is to just let the `@deprecated ` decorator indicate that a component is deprecated (rather than prefixing with `Deprecated`. 

It looks like we prefix in `DeprecatedTooltip`, but i think that's because we couldn't come up with a new name for the new component that wasn't misleading. Ping @b-cooper

2022-02-18 21:24 UTC, shlokamin commented on components/src/modals/DeprecatedModalPage.tsx
> +export function DeprecatedModalPage(
same comment as before, i don't think we need to change the name of `ModalPage`, we just have to mark it as deprecated using the `@deprecated` decorator

2022-02-18 21:31 UTC, jerader commented on components/src/structure/DeprecatedTitleBar.tsx
> +): JSX.Element {
I see so i should revert back to just `Tooltip` and `ModalPage` since we renamed the new components 🙃

2022-02-18 21:41 UTC, b-cooper commented on app/src/assets/localization/en/heater_shaker.json
> +  "t10_torx_screwdriver": "T10 Torx Screwdriver",
It's probably fine for now, at least "screwdriver" need to be translated in some cases.  But yeah this is a good rule to add to our nascent i18n rules-of-thumb.

2022-02-18 21:44 UTC, b-cooper commented on app/src/atoms/MenuList/index.tsx
> +  id?: string
Do we need this `id` prop for anything in particular?

2022-02-18 21:47 UTC, b-cooper reviewed
These changes look good, I left a few small comments.

I agree that the deprecated components should only be marked deprecated by the docstring decorator to match our current pattern.  No need to rename the old components to `DeprecatedTitleBar` or `DeprecatedModalPage`.

2022-02-18 21:47 UTC, b-cooper commented on components/src/structure/DeprecatedTitleBar.tsx
> +): JSX.Element {
*`TitleBar` and `ModalPage` 👍

2022-02-22 15:18 UTC, shlokamin approved these changes
Thanks @jerader!

2022-02-22 15:18 UTC, shlokamin commented on app/src/organisms/Devices/HeaterShakerWizard/Introduction.tsx
> +            text={t('t10_torx_screwdriver', { name: 'T10 Torx' })}
nice!

2022-02-22 15:18 UTC, shlokamin commented on components/src/modals/ModalPage.tsx
> +
i don't think marking these props as deprecated hurts, but it's not necessary since we've already marked the component as deprecated

2022-02-22 15:18 UTC, shlokamin commented on components/src/structure/TitleBar.tsx
> +
same thing here: don't think we need to mark the type as deprecated, just the component is fine

2022-02-22 15:56 UTC, sakibh approved these changes

2022-02-22 17:28 UTC, merged