added HomeRequest, HomeResponse messages
OpenTrons/opentrons-api pull request #9531
Opened 2022-02-22 15:52 UTC by caila-marashaj

2022-02-22 16:08 UTC, sfoster1 requested changes
I think this makes sense, although we should make sure we know what the home response thing intends to be. 

A couple things though:

1. When you home, you want to stop _immediately_ when the switch triggers. That's sort of incompatible with acceleration - if you're accelerating, by definition you couldn't immediately stop because you couldn't immediately start
2. when does the response come? after it executes? How is it different from a normal move response?
3. Does this go in move groups? I think it looks like it does, and honestly that's a really good idea that I'm all for

2022-02-22 16:08 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_bindings/messages/payloads.py
> +    """Response to requets to home."""
```suggestion
    """Response to requests to home."""
```

2022-02-22 16:19 UTC, caila-marashaj commented on hardware/opentrons_hardware/firmware_bindings/messages/payloads.py
> +    """Response to requets to home."""
1- sounds good, I'll take out the acceleration
2- the response is a boolean that comes back after the home move finishes, and just contains a boolean abt whether or not the homing was successful
3- Yes it's going in move groups

2022-02-22 18:22 UTC, Laura-Danielle commented on hardware/opentrons_hardware/firmware_bindings/messages/message_definitions.py
> +class HomeResponse:  # noqa: D101
Remove.

2022-02-22 18:22 UTC, Laura-Danielle commented on hardware/opentrons_hardware/firmware_bindings/messages/messages.py
> +    defs.HomeResponse,
Also here.

2022-02-22 18:22 UTC, Laura-Danielle commented on hardware/opentrons_hardware/firmware_bindings/messages/payloads.py
> +class HomeResponse(MoveGroupResponsePayload):
Same here.

2022-02-22 18:30 UTC, Laura-Danielle approved these changes
Looks good to me.

2022-02-22 18:34 UTC, sfoster1 approved these changes
Looks good to me!

2022-02-24 15:01 UTC, Laura-Danielle approved these changes

2022-02-24 15:02 UTC, merged