feat(app): heater shaker wizard power on page
OpenTrons/opentrons-api pull request #9536
Opened 2022-02-22 18:49 UTC by jerader

re #9283 

# Overview

This creates the `PowerOn` component in the heater shaker wizard setup flow. Currently, the heater shaker is stubbed in for a `magneticModuleGen2`

Module powered on and button enabled:
<img width="855" alt="Screen Shot 2022-02-22 at 1 39 08 PM" src="https://user-images.githubusercontent.com/66035149/155197750-661cb549-7682-417f-94af-7d4a17f30592.png">

Module powered off and button disabled:
<img width="854" alt="Screen Shot 2022-02-22 at 1 38 39 PM" src="https://user-images.githubusercontent.com/66035149/155197883-bd42508f-02ce-455b-93bd-9f2dfb21f325.png">

# Changelog

- added on to `PowerOn` component and increased button functionality and tooltip in `HeaterShakerWizard` component

# Review requests

- locally, go to `ModuleSetup` and change the model to equal a module that you have so you can see the setup wizard
- start the wizard and press the continue button until you reach the Power On page
- you should see a title, description, a MagneticModuleGEN2 image with the module info
- the proceed button should be disabled if the module is not activated and should have a tooltip
- the proceed button should not be disabled if the module is plugged in

Note: there are a few things stubbed out and are reminded in comments. A ticket #9519 has been created as a follow up to plug everything in

# Risk assessment

low

2022-02-22 21:59 UTC, shlokamin commented on app/src/organisms/Devices/HeaterShakerWizard/PowerOn.tsx
> +  )
i dont think this is necessary since we'll already be connected to a robot, and we already poll the modules endpoint

2022-02-22 21:59 UTC, shlokamin commented on app/src/organisms/Devices/HeaterShakerWizard/index.tsx
> +  let isDisabled: boolean = false
i think this can be simplified to use just one variable: 
```js
const isHeaterShakerAttached =
    attachedModules != null &&
    attachedModules.some(
      //  TODO(jr, 2022-02-18): get heaterShaker module when model exists
      module => module.model === 'magneticModuleV2'
    )

// later...

{currentPage <= 5 ? (
            <PrimaryBtn
              alignItems={ALIGN_CENTER}
              disabled={!isHeaterShakerAttached}
              {...targetProps}
}

// later...

{!isHeaterShakerAttached? (
                <Tooltip {...tooltipProps}>
                  {t('module_is_not_connected')}
                </Tooltip>
              ) : null}


```

2022-02-22 21:59 UTC, shlokamin commented on app/src/organisms/Devices/HeaterShakerWizard/PowerOn.tsx
> +import { useDispatch } from 'react-redux'
we shouldnt need to dispatch any redux actions inside this component

2022-02-23 14:34 UTC, jerader commented on app/src/organisms/Devices/HeaterShakerWizard/index.tsx
> +  let isDisabled: boolean = false
Oh yup, you're right! Simplifying now 😄

2022-02-23 14:46 UTC, jerader commented on app/src/organisms/Devices/HeaterShakerWizard/index.tsx
> +  let isDisabled: boolean = false
oh actually, this way doesn't work because we want the button to only be disabled for the `PowerOn` component in the setup wizard. If we simplify it this much, the buttons will be disabled for all the pages in the wizard if the heater shaker is not turned on.

I also just realized that I'm looking for if the heater shaker is attached but i want the button to be disabled if the heater shaker is not turned on. Whoops, will fix that now.

2022-02-23 15:44 UTC, shlokamin commented on app/src/organisms/Devices/HeaterShakerWizard/PowerOn.tsx
> +            {map(moduleRenderInfoById, ({ moduleDef, attachedModuleMatch }) => {
sorry i missed this before, but why are we mapping over all of the modules and rendering a fragment for each one? we just want to pull out the H/S right? we should probably have logic higher up that pulls out the H/S (for now we can just pull out the mag mod like you have below) and just renders that one element so that we dont unnecessarily render empty fragments into the DOM

2022-02-23 16:06 UTC, shlokamin commented on app/src/organisms/Devices/HeaterShakerWizard/index.tsx
> +  let isDisabled: boolean = false
ah i see why i'm confused now! it's cuz the side effect of changing `isDisabled` is happening inside of `getWizardDisplayPage`.  `getWizardDisplayPage` is a function that returns a DOM node (which makes sense, cuz by the name i'd think its just a function that gets the display page), so it's sorta misleading to be performing other side effects inside of it. could we update `isDisabled` somewhere else? also can we rename this to `isPrimaryCTADisabled` since there are two buttons in the wizard?

2022-02-23 18:01 UTC, jerader commented on app/src/organisms/Devices/HeaterShakerWizard/PowerOn.tsx
> +            {map(moduleRenderInfoById, ({ moduleDef, attachedModuleMatch }) => {
Yeah, i did some refactoring - not sure if the refactor is the best way to go about it either. LMK what you think when you get a chance 😄

2022-02-23 18:32 UTC, jerader commented on app/src/organisms/Devices/HeaterShakerWizard/index.tsx
> +  let isDisabled: boolean = false
I'm a bit confused how to update `isDisabled` somewhere else, do you mean like render the button inside the `PowerOn` component? I can definitely rename it to `isPrimaryCTADisabled`

2022-02-24 15:40 UTC, shlokamin commented on app/src/organisms/Devices/HeaterShakerWizard/index.tsx
> +
while this works, i think this logic can be simplified using `find`

```js
const heaterShaker = attachedModules.find(module => module.model === 'heaterShakerModuleV1').

// later

<PowerOn
            attachedModule={heaterShaker ?? null  }
            // i don't even think you need `isAttached` cuz you know that if `attachedModule` is falsey 
/>

```

2022-02-24 15:42 UTC, shlokamin commented on app/src/organisms/Devices/HeaterShakerWizard/index.tsx
> +  let isDisabled: boolean = false
ah, i just mean moving that logic into an if statement somewhere higher, so the side effect doesn't get conflated with `getWizardDisplayPage `: 

```js
if(currentPage === 4){isPrimaryCTADisabled = Boolean(heaterShaker)} //or whatever
```

2022-02-24 16:02 UTC, jerader commented on app/src/organisms/Devices/HeaterShakerWizard/index.tsx
> +
ah yes thank you! I tend to forget all these things we can use like `find` `some` `indexOf` etc.

2022-03-01 22:01 UTC, shlokamin requested changes

2022-03-01 22:01 UTC, shlokamin commented on app/src/organisms/Devices/HeaterShakerWizard/__tests__/HeaterShakerWizard.test.tsx
> +      //  TODO(jr, 2022-02-18): fit get attached modules to have an attached heater shaker and can click through whole flow
fit?

2022-03-01 22:01 UTC, shlokamin commented on app/src/organisms/Devices/HeaterShakerWizard/PowerOn.tsx
> +            block: <Text fontSize="1rem" />,
these can't both be `Text` elements, because `p` tags cannot be children of other `p` tags. 

if you look in your console you'll see this warning: `Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.`

you can do something like this though: `block: <span />`

2022-03-01 22:04 UTC, jerader commented on app/src/organisms/Devices/HeaterShakerWizard/__tests__/HeaterShakerWizard.test.tsx
> +      //  TODO(jr, 2022-02-18): fit get attached modules to have an attached heater shaker and can click through whole flow
whoops idk why thats there lol.

2022-03-02 15:27 UTC, shlokamin approved these changes
🚢

2022-03-02 17:21 UTC, merged