feat(app): about Module Slideouts
OpenTrons/opentrons-api pull request #9543
Opened 2022-02-23 13:57 UTC by jerader

closes #9305

# Overview

This PR creates the About Module slideout to get the module's serial and version number and to update the module if an update is available.

(note: the new AlertItem is not created yet so using the old one for now)
<img width="314" alt="Screen Shot 2022-02-22 at 4 50 03 PM" src="https://user-images.githubusercontent.com/66035149/155330438-fb631992-cb1e-40f1-9920-d97586fa1df4.png">

<img width="316" alt="Screen Shot 2022-02-23 at 8 34 54 AM" src="https://user-images.githubusercontent.com/66035149/155330418-89a50942-d0d8-46a8-beaf-58849b02917d.png">

# Changelog

- Created the `AboutModuleSlideout` component and test

# Review requests

- when you open the overflow menu on the module cards, click on `About Module` and you should get the module's information. It should work for all module cards regardless of the module. When heater shaker has an emulator, it should work for that as well.
- you should see the title, the version number and serial number. And if an update is available, you should see the AlertItem banner and a button.
- the button should update the module (using `updateModule`)
- the link on the banner should just `console.log` - I am not sure where it should link to, the ticket didn't specify.

There are several TODO comments left to remind us to go back and do them, a follow up ticket has been created.

# Risk assessment

low

2022-02-23 21:39 UTC, sakibh requested changes
The slideout looks great! However, slideout state just needs to be reorganized so the click away and closing the menu on click works properly.

2022-02-23 21:39 UTC, sakibh commented on app/src/organisms/Devices/ModuleCard/ModuleOverflowMenu.tsx
> +  const [showAboutModule, setShowAboutModule] = React.useState(false)
You don't want to handle the state of this slideout here; instead it is better to do it in the parent component. Notice how when you open the "About module" slideout and then click elsewhere on the page, it closes the entire slideout. Also when you click "About module" it leaves the overflow menu open. You want to move this state value to the parent component (`ModuleCard`) and then either create a function like `handleMenuItemClick` or pass down the state setter to the child component and on click you render the slideout, but you will also need to handle the state of the overflow menu as well to hide it on click.

2022-02-23 21:39 UTC, sakibh commented on app/src/organisms/Devices/ModuleCard/AboutModuleSlideout.tsx
> +          data-testid={`alert_item_firmware_update_${module.model}`}
Nicely placed test ids!

2022-02-24 14:04 UTC, jerader commented on app/src/organisms/Devices/ModuleCard/ModuleOverflowMenu.tsx
> +  const [showAboutModule, setShowAboutModule] = React.useState(false)
Cool, will fix this! Thank you for calling it out.

2022-02-24 16:18 UTC, shlokamin reviewed
are you seeing the slideout flicker when it's first opened too? also I noticed that multiple slideouts (and even different types of slideouts) can stack on top of each other. i think the behavior we want is that only one slideout can ever be open at one time... is that right @mmencarelli @emilywools ?

https://user-images.githubusercontent.com/5788529/155562268-5718c799-55e0-4201-9b21-708f1f4384df.mov

2022-02-24 16:18 UTC, shlokamin commented on app/src/assets/localization/en/device_details.json
> +  "set_tc_temp_slideout_btn": "Set {{part}} Temperature",
not introduced by this PR, but can we remove the `btn` postfix in this i18n key?

2022-02-24 16:18 UTC, shlokamin commented on app/src/organisms/Devices/ModuleCard/AboutModuleSlideout.tsx
> +    robotName && updateModule(robotName, module.serial)
`updateModule` returns a redux action, which means you have to dispatch it in order for it to do anything!  not sure if you've gotten a chance to go through a redux tutorial yet, but if not i've been told this one is solid: https://www.taniarascia.com/redux-react-guide/

2022-02-24 16:51 UTC, emilywools commented
hey @shlokamin thanks for the video, its super helpful. each slideout should gray out all of the content behind it. if a user clicks anywhere on that gray area, it closes the modal. so in the scenario in the video, once you've opened a slideout, clicking to the left of the slideout should close it, and then a user would have to hover and click another item in the menu to see a different slideout.

does that make sense?

2022-02-24 17:07 UTC, shlokamin commented
cool yeah makes sense thanks @emilywools! ill make a new ticket that describes that so we can merge what we have

2022-02-28 17:14 UTC, sakibh approved these changes
LGTM!

2022-02-28 17:14 UTC, sakibh commented on app/src/organisms/Devices/ModuleCard/ModuleOverflowMenu.tsx
> +  aboutModuleClick: () => void
nit: should we name this the same as the function in the parent component for consistency? So instead of `aboutModuleClick` it should be `handleAboutClick`. And the same thing for `handleClick` as well (this was done in a different PR).

2022-02-28 17:14 UTC, sakibh commented on components/src/modals/Overlay.tsx
> +    backgroundColor = 'rgba(115, 115, 115, 0.9)'
nit: Learned this recently, but if you prefer using the constants for the colors you can actually do this string concatenation with opacity in the hexadecimal: `backgroundColor: OVERLAY_GRAY_90 + '59'` 59 here corresponds to 35%.

2022-03-01 14:51 UTC, jerader commented on components/src/modals/Overlay.tsx
> +    backgroundColor = 'rgba(115, 115, 115, 0.9)'
oh cool! i'll change that.

2022-03-02 15:50 UTC, shlokamin approved these changes
this looks great! thanks @jerader!

2022-03-02 15:50 UTC, shlokamin commented on components/src/modals/BaseModal.tsx
> +    overlayColor = 'rgba(22, 33, 45, 0.35)',
remind me again because things have changed so many times — is this `overlayColor` supposed to be different than the one in the `Overlay` component? 

here in `BaseModal`: `overlayColor = 'rgba(22, 33, 45, 0.35)'`
over in `Overlay`: `backgroundColor = 'rgba(115, 115, 115, 0.9)'`

2022-03-02 17:23 UTC, jerader commented on components/src/modals/BaseModal.tsx
> +    overlayColor = 'rgba(22, 33, 45, 0.35)',
hey `baseModal` and `overlay` are the same backrgound colors now. i think you were looking at the overlay color when `alertOverlay === true`

2022-03-02 17:34 UTC, merged