app - Selectors for the Labware Offset
OpenTrons/opentrons-api pull request #9546
Opened 2022-02-23 14:41 UTC by reachojhaneha

I am adding ID selectors to LabwareInfoOverlay.tsx for the offset box, displayName and X,Y,Z offset values itself

- 'LabwareInfoOverlay_offset_box'
- 'LabwareInfoOverlay_displayName'
- 'LabwareInfoOverlay_X'
- 'LabwareInfoOverlay_Y'
- 'LabwareInfoOverlay_Z'
- 'LabwareInfoOverlay_X_value'
- 'LabwareInfoOverlay_Y_value'
- 'LabwareInfoOverlay_Z_value'

2022-02-23 18:58 UTC, shlokamin requested changes
i think we should just pick one formatting style and stick to it. it looks like elsewhere we do `id="ComponentName_descriptionInCamelCase"` which works for me

2022-02-23 18:58 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/LabwareInfoOverlay.tsx
> +      id="LabwareInfoOverlay_offset_box"
this id is formatted differently than the one below — the second work here is kebab case and in the id below it is camel case. let's just stick to the style you have below?

`id="LabwareInfoOverlay_displayName"`

2022-02-23 18:58 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/LabwareInfoOverlay.tsx
> +              id="LabwareInfoOverlay_X_value"
same this here, this is different. let's go with `ComponentName_descriptionInCamelCase`

2022-02-23 18:58 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/LabwareInfoOverlay.tsx
> +              id="LabwareInfoOverlay_X"
same thing here

2022-02-23 18:58 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/LabwareInfoOverlay.tsx
> +              id="LabwareInfoOverlay_Y"
same thing here

2022-02-23 18:58 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/LabwareInfoOverlay.tsx
> +              id="LabwareInfoOverlay_Y_value"
same thing here

2022-02-23 18:58 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/LabwareInfoOverlay.tsx
> +              id="LabwareInfoOverlay_Z"
same thing here

2022-02-23 18:58 UTC, shlokamin commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/LabwareInfoOverlay.tsx
> +              id="LabwareInfoOverlay_Z_value"
same thing here

2022-02-23 20:09 UTC, reachojhaneha commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/LabwareInfoOverlay.tsx
> +      id="LabwareInfoOverlay_offset_box"
addressed this

2022-02-23 20:09 UTC, reachojhaneha commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/LabwareInfoOverlay.tsx
> +              id="LabwareInfoOverlay_X_value"
done

2022-02-23 20:09 UTC, reachojhaneha commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/LabwareInfoOverlay.tsx
> +              id="LabwareInfoOverlay_X"
done

2022-02-23 20:09 UTC, reachojhaneha commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/LabwareInfoOverlay.tsx
> +              id="LabwareInfoOverlay_Y"
done

2022-02-23 20:09 UTC, reachojhaneha commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/LabwareInfoOverlay.tsx
> +              id="LabwareInfoOverlay_Y_value"
done

2022-02-23 20:09 UTC, reachojhaneha commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/LabwareInfoOverlay.tsx
> +              id="LabwareInfoOverlay_Z"
done

2022-02-23 20:09 UTC, reachojhaneha commented on app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/LabwareInfoOverlay.tsx
> +              id="LabwareInfoOverlay_Z_value"
done

2022-02-25 19:44 UTC, shlokamin approved these changes
LGTM! The CI failure is an issue with the windows OS on the gh runner. Tests are passing on other operating systems so feel free to merge!

2022-02-28 16:24 UTC, merged