fix(api): working volume is not set in fast simulation
OpenTrons/opentrons-api pull request #9550
Opened 2022-02-23 20:51 UTC by amitlissack

# Overview

closes #9503 

# Changelog

# Review requests

# Risk assessment

2022-02-23 21:12 UTC, mcous commented
This fixes transfers, which is good, but I don't think it resolves the issue completely. Check out this protocol:

```python
from opentrons import types

metadata = {
    "protocolName": "Tip Volume Testing",
    "apiLevel": "2.12",
}


def run(ctx):
    tr = ctx.load_labware("opentrons_96_filtertiprack_200ul", 1)
    p300 = ctx.load_instrument("p300_single", types.Mount.RIGHT, [tr])
    reservoir = ctx.load_labware("nest_1_reservoir_195ml", 3)

    p300.pick_up_tip()
    p300.aspirate(location=reservoir.wells()[0].bottom(1))
    p300.drop_tip()
```

- Fast analysis results: tries to aspirate 300 uL, errors out because it exceeds tip max volume
- Actual run: aspirates 200 uL

2022-02-23 21:34 UTC, mcous requested changes
Marking this as a change request because in fixing one issue, this can cause a valid protocol to fail analysis rather than produce an invalid analysis. See comment and repro above

2022-02-23 21:45 UTC, amitlissack commented
> Marking this as a change request because in fixing one issue, this can cause a valid protocol to fail analysis rather than produce an invalid analysis. See comment and repro above

Thanks.  I am pretty out of touch with how to test these changes well. I am concerned that you're going to keep finding failing protocols for me.

2022-03-25 16:52 UTC, mcous commented
I believe all pipette state lives in the `PipetteDict` model, so, running down the list of "does the instrument simulator deal with `PipetteDict` properly?", this is what I get:

- [x] `name: PipetteName` - static, from pipette definition
- [x] `model: PipetteModel` - static, from pipette definition
- [x] `back_compat_names: List[PipetteName]` - static, from pipette definition
- [x] `pipette_id: str` - static, from pipette definition
- [x] `display_name: str` - static, from pipette definition
- [x] `min_volume: float` - static, from pipette definition
- [x] `max_volume: float` - static, from pipette definition
- [x] `channels: ChannelCount` - static, from pipette definition
- [ ] `aspirate_flow_rate: float` - **mutable**, not properly handled by simulator
- [ ] `dispense_flow_rate: float` - **mutable**, not properly handled by simulator
- [ ] `blow_out_flow_rate: float` - **mutable**, not properly handled by simulator
- [ ] `aspirate_speed: float` - **mutable**, not properly handled by simulator
- [ ] `dispense_speed: float` - **mutable**, not properly handled by simulator
- [ ] `blow_out_speed: float` - **mutable**, not properly handled by simulator
- [x] `current_volume: float` - **mutable**, handled by simulator
- [x] `tip_length: float` - **mutable**, handled by simulator
- [ ] `working_volume: float` - **mutable**, not properly handled by simulator
- [x] `tip_overlap: Dict[str, float]` - static, from pipette definition
- [ ] `available_volume: float` - **mutable**, not properly handled by simulator
- [x] `return_tip_height: float` - statis, from pipette definition
- [x] `default_aspirate_flow_rates: Dict[str, float]` - static, from pipette definition
- [x] `default_dispense_flow_rates: Dict[str, float]` - static, from pipette definition
- [x] `default_blow_out_flow_rates: Dict[str, float]` - static, from pipette definition
- [x] `default_aspirate_speeds: Dict[str, float]` - static, from pipette definition
- [x] `default_dispense_speeds: Dict[str, float]` - static, from pipette definition
- [x] `default_blow_out_speeds: Dict[str, float]` - static, from pipette definition
- [ ] `ready_to_aspirate: bool` - **mutable**, not properly handled by simulator
- [x] `has_tip: bool` **mutable**, handled by simulator

## Differences

### `(aspirate|dispense|blow_out)_(flow_rate|speed)`

The `_speed` properties are computed properties of the `_flow_rate` properties. Whenever `_flow_rate` is set, `_speed` must be set, too.

### `working_volume`

Hardware controller clamps `working_volume` at the instrument's max volume, while the simulator does not.

### `available_volume`

`available_volume` is a computed property, and needs to be updated any time `working_volume` or `current_volume` changes.

This PR updates the `get_available_volume` method of `InstrumentContextSimulation`, but does not set `PipetteDict.available_volume`. This gets things into a weird state where the `PipetteDict` (which is public to the context class) has an `available_volume` entry that differs from `InstrumentContextSimulation.get_available_volume`.

### `ready_to_aspirate`

The `ready_to_aspirate` field should be set to `True` by `InstrumentContextSimulation.aspirate` to simulate what happens in the hardware controller.

2022-03-29 18:10 UTC, mcous approved these changes
Code changes look good. Another dep on the hardware simulator is a bummer but I don't see any better way to do it at the moment.

Tested with the original repro protocols and analysis seems to be correct, now

2022-03-29 18:21 UTC, amitlissack commented
> Code changes look good. Another dep on the hardware simulator is a bummer but I don't see any better way to do it at the moment.
> 
> Tested with the original repro protocols and analysis seems to be correct, now

Agreed.

2022-03-29 18:22 UTC, merged