feat(ot3): add home request, test to move group runner
OpenTrons/opentrons-api pull request #9563
Opened 2022-02-24 16:18 UTC by caila-marashaj

2022-02-24 18:03 UTC, sfoster1 approved these changes
Looks good! Let's just factor out that velocity conversion and maybe acceleration

2022-02-24 18:03 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +                    int((step.velocity_mm_sec / interrupts_per_sec) * (2**31))
let's factor this out into a helper I think

2022-03-15 15:10 UTC, sfoster1 requested changes
Some inline things but looking good!

2022-03-15 15:10 UTC, sfoster1 commented on api/src/opentrons/config/defaults_ot3.py
> +        OT3AxisKind.X: 100,
the right answer to these values is probably less than 10k but more than 100, but we can do that in a future pr

2022-03-15 15:10 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        group = create_move_group(origin, moves, self._present_nodes, stop_condition)
i kinda like the implicit destructuring more (e.g., don't make this change) but iot's a matter of taste

2022-03-15 15:10 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +    async def home(self, axes: List[OT3Axis]) -> Dict[OT3Axis, float]:
I think the map is better

2022-03-15 15:10 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        """Move to a position.
should keep the old docstring

2022-03-15 15:10 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +                # TODO(cm, 2/28/22): confirm that we don't need to move plunger
we definitely do need to do this, let's bring it back (but only if you homed a plunger)

2022-03-15 15:10 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +                # TODO(cm, 2/28/22): confirm that we don't need to move plunger
That said, this function had an extremely important point with complex ot-2 homing behavior; the better strategy may be to alter `home_plunger` to do
```
await self.home([OT3Axis.of_mount(checked_mount)])
target_pos = target_position_from_plunger(checked_moiunt, instr.config.bottom, self._current_position)
await self._move(target_pos, acquire_lock=False, home_flagged_axes=False)
```
and get rid of `_do_plunger_home` entirely.

2022-03-15 15:10 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
>          await self.current_position(mount=checked_mount, refresh=True)
as currently implemented i think we can't do this - `current_position` will fail if youii're not homed yet

2022-03-15 15:10 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +            # TODO raise error
done, right?

2022-03-15 15:10 UTC, sfoster1 commented on api/src/opentrons/hardware_control/types.py
> +        """The axes which are used for moving plunger motors."""
the idea with this accessor is actually "z/a axes that are not for the gripper", not "plunger motors" - we don't have a list of those, and perhaps should, but that functionality in general is handled by `of_main_tool_actuator`

2022-03-15 15:10 UTC, sfoster1 commented on api/src/opentrons/hardware_control/types.py
> +        """The axes which are used for moving pipettes up and down."""
this is where we'd eventually add `Z_G`

2022-03-15 15:10 UTC, sfoster1 commented on api/src/opentrons/hardware_control/types.py
> +    def to_kind(cls, inst: "OT3Axis") -> OT3AxisKind:
why make this change? the place it is used would work just fine as an instance method

2022-03-15 15:10 UTC, sfoster1 commented on api/src/opentrons/hardware_control/types.py
> +    def home_position(cls) -> Dict["OT3Axis", float]:
not used, and I think this is a layering violation - these positions are in machine coordinates, and this is an external type. these values should be elsewhere, if they're used at all.

2022-03-15 15:10 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/backends/test_ot3_controller.py
> +async def test_home(controller: OT3Controller, mock_move_group_run):
let's test this with
- Every supported axis as a single element, so `[OT3Axis.X]`, `[OT3Axis.Y]`, etc
- one call with a more-than-one-element list

So something like
```
supported_axes_calls = tuple([ax] for ax in OT3Axis) # probably not _all_ since there's some we don't support, but can cut down from here)
pytest.mark.parametrize('axes', supported_axes_calls + ([OT3Axis.X, OT3Axis.Y],)
async def test_home(controller: OT3Controller, mock_move_group_run, axes: List[Axis])`

2022-03-15 15:10 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/test_moves.py
> +    with mock.patch("opentrons.hardware_control.ot3api.deck_from_machine") as dfm_mock:
should test what happens when `home` is called without arguments (i.e. it passes all the axes to the mocked backend)

2022-03-15 15:10 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/move_group_runner.py
> +            # if self._stop_condition[
remove or uncomment

2022-03-16 18:07 UTC, sfoster1 requested changes

2022-03-16 18:07 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        # breakpoint()
remove commented out code

2022-03-16 18:07 UTC, sfoster1 commented on api/src/opentrons/hardware_control/scripts/repl.py
> +# import os
uncomment

2022-03-16 18:07 UTC, sfoster1 commented on api/src/opentrons/hardware_control/scripts/repl.py
> +    # stop_server()
un comment

2022-03-16 18:07 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/test_moves.py
> +    # mount2 = types.Mount.LEFT
uncomment

2022-03-16 18:07 UTC, sfoster1 commented on hardware/main.py
> +# This is a sample Python script.
remove, i think

2022-03-16 18:07 UTC, sfoster1 commented on shared-data/LICENSE
> +
definitely gotta remove

2022-03-16 20:48 UTC, sfoster1 requested changes
Looking great! Couple tiny things

2022-03-16 20:48 UTC, sfoster1 commented on api/src/opentrons/hardware_control/scripts/repl.py
> +    print("Running wth OT3 HC. If you dont want this, " 'set an env var named "OT2"')
```suggestion
    print("Running with OT3 HC. If you dont want this, set an env var named 'OT2'")
```

2022-03-16 20:48 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/backends/test_ot3_controller.py
> +    # assert home_pos[OT3Axis.X] == 0
remove or uncomment

2022-03-16 20:48 UTC, sfoster1 commented on api/tests/opentrons/hardware_control/test_moves.py
> +    abs_position = types.Point(30, 20, 0)
This test should not be changed - this is an OT2 test

2022-03-16 21:01 UTC, Laura-Danielle requested changes
Some tiny change requests and one large question:

Are we planning to control the sequence of homing in a follow-up PR or this one?

2022-03-16 21:01 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            target_position: Map of axis to position.
These args aren't correct for the `home` function.

2022-03-16 21:01 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/scripts/repl.py
> +    print("Running wth OT3 HC. If you dont want this, " 'set an env var named "OT2"')
I think we should probably remove any changes to repl script in this PR

2022-03-16 21:01 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/ot3api.py
> +        """Worker function to apply robot motion."""
Where are we planning on separating out the sequence of axes to be homed?

Ideally there should be at least two "home" groups -- homing BCAZ (pipettes/mounts) and then homing the XY.

2022-03-16 21:06 UTC, sfoster1 commented
> Some tiny change requests and one large question:
> 
> Are we planning to control the sequence of homing in a follow-up PR or this one?

yeah we should do that in a followup

2022-03-16 21:09 UTC, caila-marashaj commented on api/src/opentrons/hardware_control/scripts/repl.py
> +    print("Running wth OT3 HC. If you dont want this, " 'set an env var named "OT2"')
yeah that was just from the linter freaking out about my local branch earlier today. I'll get rid of that

2022-03-16 21:28 UTC, caila-marashaj commented on api/src/opentrons/hardware_control/ot3api.py
> +        """Worker function to apply robot motion."""
Do you mean that should exist in two different functions?

2022-03-17 13:36 UTC, sfoster1 commented on api/src/opentrons/hardware_control/ot3api.py
> +        """Worker function to apply robot motion."""
let's do this in a followup - the idea is that we always home the Z carriers before the gantry (so attached tools are out of the way). the pipettes can happen basically any time.

2022-03-17 13:37 UTC, sfoster1 approved these changes
Great! Soon as we get those lint checks fixed we're good

2022-03-17 15:46 UTC, Laura-Danielle approved these changes
Once lint is good, we are good to go

2022-03-17 21:05 UTC, merged