Head tool detection
OpenTrons/opentrons-api pull request #9592
Opened 2022-03-01 14:49 UTC by sotaoverride

A class to help keep track of tools (type of pipettes) attached to head. 

Will test on hw before final merge.

2022-03-01 16:00 UTC, sfoster1 requested changes
Looks good overall, I think there's a change or two we should make though (inline)

2022-03-01 16:00 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tools/detector.py
> +                yield self._attached_tools
this kind of goes against the idea of using an async generator here. It's fine to have a different number of yields than iterations:
```
from typing import Iterator

def filter_evens(values: Iterator[int]) -> Iterator[int]:
    for value in iterator:
        if value % 2:
            pass
        else:
            yield value

for value in filter_evens(range(10)): print(value)  # 0 2 4 6 8
```

So we just don't really need this `else` clause

2022-03-01 16:00 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tools/detector.py
> +        async for message in driver:
I don't think we get much value out of the dictionary diffing thing here - I think only the upper layers need to care about detecting changes, this can just massage data types and push updates

2022-03-01 16:00 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tools/detector.py
> +        """Detect tool changes continuoulsy."""
```suggestion
        """Detect tool changes continuously."""
```

2022-03-01 16:00 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tools/detector.py
> +        """Detect tool changes continuoulsy."""
Also I might be reading this wrong, but I don't think this actually continuously detects tool changes - it looks like it detects it precisely _once_, right?

2022-03-01 16:00 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tools/detector.py
> +            driver = self._messenger._drive
looks like a typo? should be `self._messenger._driver`? add a test for sure

2022-03-01 16:00 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tools/detector.py
> +    async def detect(
is this intended to be used by callers outside this class? if it's not, it should start with an `_`, like `async def _detect`

2022-03-01 16:00 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tools/types.py
> +    LEFT = enum.auto()
might as well add `GRIPPER` now, right? and maybe make these have the same values as in the firmware?

2022-03-01 16:34 UTC, amitlissack requested changes

2022-03-01 16:34 UTC, amitlissack commented on hardware/opentrons_hardware/hardware_control/tools/detector.py
> +        if driver is None:
Why do we pass a driver in to this function if this object is constructed with a `CanMessenger`?

Why aren't we using the `CanMessenger` ? It's a much better tool for interacting with CAN.

2022-03-01 16:34 UTC, amitlissack commented on hardware/tests/conftest.py
> +    """Mock can driver."""
The `conftest` file is for reusable fixtures. 

This fixture should not be here. It's confusingly named a `mock_driver` when it is really a fixture for the tools detection test.

2022-03-02 04:15 UTC, sotaoverride commented on hardware/opentrons_hardware/hardware_control/tools/detector.py
> +    async def detect(
that was the intention, use by callers outside of this class.

2022-03-02 04:15 UTC, sotaoverride commented on hardware/tests/conftest.py
> +    """Mock can driver."""
leaving conftest as is

2022-03-02 04:15 UTC, sotaoverride commented on hardware/opentrons_hardware/hardware_control/tools/types.py
> +    LEFT = enum.auto()
added

2022-03-02 04:15 UTC, sotaoverride commented on hardware/opentrons_hardware/hardware_control/tools/detector.py
> +            driver = self._messenger._drive
fixed (in hardware/opentrons_hardware/drivers/can_bus/can_messenger.py)

2022-03-02 04:15 UTC, sotaoverride commented on hardware/opentrons_hardware/hardware_control/tools/detector.py
> +        if driver is None:
At the time seemed like an easier way of mocking __aiter__ / __anext__ for AbstractCanDriver(ABC). Have figured a more straight fwd way now that seems to work fine.

2022-03-02 04:15 UTC, sotaoverride commented on hardware/opentrons_hardware/hardware_control/tools/detector.py
> +        """Detect tool changes continuoulsy."""
Correct.

2022-03-02 04:15 UTC, sotaoverride commented on hardware/opentrons_hardware/hardware_control/tools/detector.py
> +        async for message in driver:
makes sense, getting rid of the diffing.

2022-03-02 04:15 UTC, sotaoverride commented on hardware/opentrons_hardware/hardware_control/tools/detector.py
> +                yield self._attached_tools
got rid of else.

2022-03-02 14:11 UTC, sfoster1 requested changes
Couple things in addition to some typos.

First, I don't really get the use case for `ToolDetector.run_detect` and `ToolDetector.run`. When would we call them? Why? Why don't they return anything? How should they be used? If they're really just for being used in the added script, let's just put them in the script field.

Second, remember, the idea here is that this can be a sort of black box implementation for the hardware controller to completely solve the problem of detecting what's attached. The hardware controller can make one and iterate through it to get tools, nice and easy. As currently implemented, it catches incoming asynchronous notifications while active - this is good - but it doesn't establish initial state. Maybe before `detect` goes into its loop it should send a get tool status message once?

I also don't really get what's going on with the internal dictionary cache. It doesn't have a defined way to query it (I mean, you always _can_, it's python, but by convention instance variables whose names start with `_` are private and shouldn't be used from outside the class); it gets provided from above when you build the class but I'm not sure why - we don't need that for testing since it's python. 

Finally, we really should have a direct test method for `ToolDetector.detect`.

2022-03-02 14:11 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tools/detector.py
> +        log.info(f"Detection, Tool: {tool}")
so this function doesn't do anything, it just logs?

2022-03-02 14:11 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tools/errors.py
> +class ToolDetectionFailiure(ToolDetectionException):
```suggestion
class ToolDetectionFailure(ToolDetectionException):
```

2022-03-02 14:11 UTC, sfoster1 commented on hardware/opentrons_hardware/hardware_control/tools/detector.py
> +                    raise ToolDetectionFailiure()
```suggestion
                    raise ToolDetectionFailure()
```

2022-03-07 20:31 UTC, sotaoverride commented
moved on to https://github.com/Opentrons/opentrons/pull/9641

2022-03-07 20:31 UTC, closed without merging