feat(pd): add schema v6 migration support
OpenTrons/opentrons-api pull request #9595
Opened 2022-03-01 20:07 UTC by jerader

closes #9542 

# Overview

this protocol adds schema v6 migration support to PD

# Changelog

- creates `6_0_0` migration component, test and snapshot

# Review requests

make sure all the AC are included. This includes

- generate all necessary load commands (`loadPipette`, `loadLabware`, `loadModule`) commands by analyzing the v5 protocol's pipettes, labware, and modules keys (skipping `loadLiquid` for now
- modify pipette access parameter pipette keys to be `pipetteId`
- modify labware access parameter labware keys to be `labwareId`
- rename `airGap` to `aspirate`
- remove all temporal properties from the labware, pipettes, and modules keys
- rename `command` to `commandType`
- add `deckId` to `robot`
- rename `well` to `wellName`

# Risk assessment

low

2022-03-08 16:51 UTC, shlokamin requested changes
Looking really good y'all. It's super impressive y'all took this task head on, migrations can be tough, but they're very important. Left some comments but this is coming along really nicely!

2022-03-08 16:51 UTC, shlokamin commented on protocol-designer/src/load-file/migration/6_0_0.ts
> +    const removeMount = omit(pipettes, 'mount')
the name `removeMount` makes it seem like this is a function, it's really a new pipettes object without the mount key. but we can side step this altogether bu removing the variable name 😄 

```js
const migratePipettes = (
  appData: Record<string, any>
): Record<string, any> =>
  mapValues(appData, pipettes => omit(pipettes, 'mount'))

```

2022-03-08 16:51 UTC, shlokamin commented on protocol-designer/src/load-file/migration/6_0_0.ts
> +export const migratePipettes = (
i dont think this needs to be exported

2022-03-08 16:51 UTC, shlokamin commented on protocol-designer/src/load-file/migration/6_0_0.ts
> +    const removeMount = omit(pipettes, 'mount')
(same thing applies to the other functions below)

2022-03-08 16:51 UTC, shlokamin commented on protocol-designer/src/load-file/migration/6_0_0.ts
> +export const migratePipettes = (
(same thing applies to the other functions below)

2022-03-08 16:51 UTC, shlokamin commented on protocol-designer/src/load-file/migration/6_0_0.ts
> +export const migrateFile = (appData: any): any => {
can this be typed to accept a v5 protocol and return a v6 protocol?

2022-03-08 16:51 UTC, shlokamin commented on protocol-designer/src/load-file/migration/6_0_0.ts
> +      deckId: 'ot2_standard',
can we put these string into constants? maybe even in shared-data

2022-03-08 16:51 UTC, shlokamin commented on protocol-designer/src/load-file/migration/6_0_0.ts
> +      deckId: 'ot2_standard',
can we put these string into constants? maybe even in shared-data

2022-03-08 16:51 UTC, shlokamin commented on protocol-designer/src/load-file/migration/__tests__/6_0_0.test.ts
> +  it('removed mount from pipettes', () => {
`removed` => `removes`

2022-03-08 16:51 UTC, shlokamin commented on protocol-designer/src/load-file/migration/__tests__/6_0_0.test.ts
> +  it('removed mount from pipettes', () => {
`removed` => `removes`

2022-03-08 16:51 UTC, shlokamin commented on protocol-designer/src/load-file/migration/__tests__/6_0_0.test.ts
> +    })
while this is fine, it would be less brittle to do a find on `commandType === 'loadModule'` so that we don't rely on a specific command index

2022-03-08 16:51 UTC, shlokamin commented on protocol-designer/src/load-file/migration/__tests__/6_0_0.test.ts
> +    })
while this is fine, it would be less brittle to do a find on `commandType === 'loadModule'` so that we don't rely on a specific command index

2022-03-08 16:51 UTC, shlokamin commented on protocol-designer/src/load-file/migration/__tests__/6_0_0.test.ts
> +    })
(same thing applies to other tests in this file)

2022-03-08 16:51 UTC, shlokamin commented on protocol-designer/src/load-file/migration/__tests__/6_0_0.test.ts
> +    })
(same thing applies to other tests in this file)

2022-03-08 17:08 UTC, jerader commented on protocol-designer/src/load-file/migration/6_0_0.ts
> +export const migrateFile = (appData: any): any => {
When I do that, I get an error in `index.ts` saying

`Type '(appData: ProtocolFileV5<{}>) => ProtocolFile<{}>' is not assignable to type '(arg0: Record<string, any>) => Record<string, any>'.
  Types of parameters 'appData' and 'arg0' are incompatible.
    Type 'Record<string, any>' is missing the following properties from type 'ProtocolFile<{}>': $otSharedSchema, schemaVersion, modules, commands, and 5 more.`

2022-03-16 20:46 UTC, shlokamin commented on shared-data/protocol/types/schemaV6/index.ts
> +}
ping @mcous @sanni-t @TamarZanzouri @SyntaxColoring

2022-03-16 21:00 UTC, shlokamin commented on protocol-designer/src/load-file/migration/__tests__/6_0_0.test.ts
> -    expect('moduleId' in migratedFile.commands).not.toBeNull()
@jerader @sakibh this actually does not do what we expect: 

`migratedFile.commands` is a list, so the following assertion: 

```js
expect('loadModule' in migratedFile.commands).not.toBeNull()
```

is sort of asking "does the key 'loadModule' exist in the array `commands`?"  which is sort of a confusing question, because arrays are not supposed to have keys (they do, but thats a technicality we can get into later). It would be like asking "does the list `[]` have a property called `loadModule`?". It does not, so the answer will be false. 

So we have: 

```js
expect('loadModule' in migratedFile.commands).not.toBeNull()
// which resolves to
expect(false).not.toBeNull()
```

which is technically true, because `false !== null`, which is why the test passes.

2022-03-16 21:01 UTC, shlokamin commented on protocol-designer/src/load-file/migration/__tests__/6_0_0.test.ts
> -    expect('moduleId' in migratedFile.commands).not.toBeNull()
so these tests were not actually testing anything, they just happened to also not throw any errors because JS is lenient

2022-03-16 21:15 UTC, jerader commented on protocol-designer/src/load-file/migration/__tests__/6_0_0.test.ts
> -    expect('moduleId' in migratedFile.commands).not.toBeNull()
this makes a lot of sense to me. Thanks for explaining it!

2022-03-18 18:42 UTC, shlokamin approved these changes
😄

2022-03-21 17:47 UTC, smb2268 approved these changes
This looks good! Thanks for updating all of this @jerader @shlokamin  @sakibh 🚀

2022-03-21 21:47 UTC, b-cooper approved these changes
👍  The migrations look sound. Way to go!

2022-03-22 16:43 UTC, merged