feat(app): slideout and functionality to heater shaker overflow menu
OpenTrons/opentrons-api pull request #9682
Opened 2022-03-11 17:24 UTC by jerader

closes #9304 #9303 #9302

# Overview

This PR creates a slideout that handles both the set shake and set temp of the heater shaker, where the button to set the setting is disabled unless you input a value in the field.

This also hooks up the `See how to attach to a deck` button and the heater shaker wizard launches

This also hooks up the latch button, where it is disabled if the heater shaker shaking status is not `idle`

<img width="311" alt="Screen Shot 2022-03-11 at 12 18 12 PM" src="https://user-images.githubusercontent.com/66035149/157915642-29a6e856-1cb3-4055-9f15-a9329e986250.png">

<img width="306" alt="Screen Shot 2022-03-11 at 12 18 42 PM" src="https://user-images.githubusercontent.com/66035149/157915731-56612563-9979-40be-847e-93d618e9a893.png">

# Changelog

- creates `heaterShakerSlideout` 
- a bit of refactoring in `moduleOverflowMenu`

# Review requests

- when selecting the dropdown menu for the heater shaker, pressing the `set shake speed` button should open the slideout.
- when pressing the `set temperature` button, it should open the temp slideout.
- when clicking on the labware latch button, the title of the button should change since the command is hooked up
- when clicking on the `see how to attach to deck` button, the heater shaker wizard should be launched

# Risk assessment

low, behind ff

2022-03-16 13:36 UTC, jerader commented on app/src/atoms/InputField/index.tsx
> +export function InputField(props: InputFieldProps): JSX.Element {
is it ok that I name this `InputField`? It is an identical name to the one I deprecated. The reason why I deprecated the old one instead of updating it is because PD still uses the old input field designs

2022-03-16 13:36 UTC, jerader commented on app/src/organisms/Devices/ModuleCard/ModuleOverflowMenu.tsx
> +          return console.log('Deactivate shake')
What is the status for deactivating the shake?

2022-03-16 13:36 UTC, jerader commented on app/src/organisms/Devices/ModuleCard/TemperatureModuleSlideout.tsx
> +          min={4}
Should I add these as constants? The temp module, TC block, and h-s temp all have the same range from 4-99 C

2022-03-16 13:36 UTC, jerader commented on components/src/ui-style-constants/colors.ts
> +export const medGreyHover = '#b8b8b8'
I got confirmation from Mel that there is a medium-grey/hover color

2022-03-16 20:17 UTC, sakibh requested changes, later dismissed
Looks good, lots of great additions. Left a few comments to consider.

2022-03-16 20:17 UTC, sakibh commented on app/src/organisms/Devices/ModuleCard/ModuleOverflowMenu.tsx
> +  const [isLatchClosed, setIsLatchClosed] = React.useState<boolean>(true)
Would it be more accurate to determine whether the latch is open or closed based on `labwareLatchStatus` versus setting state? Is the latch always closed by default?

2022-03-16 20:17 UTC, sakibh commented on app/src/atoms/InputField/index.tsx
> +  min?: number
This is awesome. Since we take in the min/max and can use `error` to pass in an out of range message, do we still need to clamp the value to the min/max? cc @shlokamin

2022-03-16 20:17 UTC, sakibh commented on app/src/organisms/Devices/ModuleCard/__tests__/ModuleOverflowMenu.test.tsx
> +const mockMovingHeaterShaker = {
Super cool! This seems very handy for testing without the backend hooked up.

2022-03-16 20:17 UTC, sakibh commented on app/src/organisms/Devices/ModuleCard/HeaterShakerSlideout.tsx
> +          caption={isSetShake ? t('between_200_to_1800') : t('between_4_to_99')}
nit: Should there be something like `"module_range_details": "Between {{min}} {{units}} to {{max}} {{units}}"`, so we can do something like `t('module_range_details', {max: max_value, min: min_value, units: unit})`. I've been seeing ranges like this used all over for the captions so this may be one way to go about it and also if the ranges ever change we can update it in one place.

2022-03-16 20:17 UTC, sakibh commented on app/src/organisms/Devices/ModuleCard/MagneticModuleSlideout.tsx
> +import { parseInt } from 'lodash'
Any reason this is being used over the built in `parseInt`?

2022-03-16 20:17 UTC, sakibh commented on app/src/organisms/Devices/ModuleCard/ModuleOverflowMenu.tsx
> +          return console.log('Deactivate shake')
Based on the types we have for `SpeedStatus` you could deactivate it if it is `holding at target` or `speeding up`. Not sure how `slowing down` factors into this because does sending a deactivate command trigger that status and then eventually it becomes `idle` once it is stopped?

2022-03-16 20:17 UTC, sakibh commented on app/src/organisms/Devices/ModuleCard/ModuleOverflowMenu.tsx
> +    if (module.type === THERMOCYCLER_MODULE_TYPE) {
nit: this outer if statement can be replaced by a switch statement and you can switch on `module.type` to make this more readable.

2022-03-16 20:17 UTC, sakibh commented on app/src/organisms/Devices/ModuleCard/ThermocyclerModuleSlideout.tsx
> +      //  how do we get volume?
I think the volume is meant as an input from PD?

2022-03-16 20:17 UTC, sakibh commented on app/src/organisms/Devices/ModuleCard/__tests__/TemperatureModuleSlideout.test.tsx
> +const mocUseLiveCommandMutation = useCreateLiveCommandMutation as jest.MockedFunction<
`mocUseLiveCommandMutation` should be `mockUseLiveCommandMutation`

2022-03-16 20:52 UTC, smb2268 commented on app/src/atoms/InputField/index.tsx
> +export function InputField(props: InputFieldProps): JSX.Element {
I think this is fine, I remember discussing that we can keep the names the same as long as they are imported from different places (ie components vs atoms) which `InputField` is.

2022-03-16 21:04 UTC, smb2268 approved these changes
I only reviewed the `InputField` additions, but they look good! I added a few styling variable nits.

2022-03-16 21:04 UTC, smb2268 commented on app/src/atoms/InputField/index.tsx
> +    font-size: 11px;
We have the border size and style in `BORDERS.ts` and this font size in `TYPOGRAPHY.ts` that you can use here and for the below borders

2022-03-16 21:04 UTC, smb2268 commented on app/src/atoms/InputField/index.tsx
> +        fontSize={SPACING.spacingSM}
let's use `TYPOGRAPHY.fontSizeH6` for this instead of the equivalent spacing value

2022-03-16 21:04 UTC, smb2268 commented on app/src/atoms/InputField/index.tsx
> +      fontSize="11px"
Another font size here that can be `TYPOGRAPHY.fontSizeP`

2022-03-16 21:07 UTC, jerader commented on app/src/organisms/Devices/ModuleCard/ThermocyclerModuleSlideout.tsx
> +      //  how do we get volume?
oh yeah, I forgot I put this placeholder comment in. But that would make sense! I'll dig into it a little bit.

2022-03-16 21:09 UTC, jerader commented on app/src/organisms/Devices/ModuleCard/HeaterShakerSlideout.tsx
> +          caption={isSetShake ? t('between_200_to_1800') : t('between_4_to_99')}
oh yup, that makes a ton of sense to me. Good catch. Then you only need the 1 i18n.

2022-03-16 21:10 UTC, jerader commented on app/src/organisms/Devices/ModuleCard/ModuleOverflowMenu.tsx
> +  const [isLatchClosed, setIsLatchClosed] = React.useState<boolean>(true)
Oh ya, good point. The latch probably isn't always closed by default. I will change this.

2022-03-16 21:20 UTC, jerader commented on app/src/atoms/InputField/index.tsx
> +        fontSize={SPACING.spacingSM}
whoops good catch.

2022-03-16 21:33 UTC, jerader commented on app/src/organisms/Devices/ModuleCard/MagneticModuleSlideout.tsx
> +import { parseInt } from 'lodash'
oh idk why that's there. it must have automatically added when i was typing in `parseInt`

2022-03-16 21:36 UTC, smb2268 commented on app/src/atoms/InputField/index.tsx
> +          max={props.max ?? undefined}
Instead of listing out each prop that's the same as those being passed to `InputField`, can you spread them? So remove `id={props.id}` and the rest that are the same and add {...props}

2022-03-17 12:47 UTC, jerader commented on app/src/organisms/Devices/ModuleCard/ModuleOverflowMenu.tsx
> +    if (module.type === THERMOCYCLER_MODULE_TYPE) {
I was thinking about this more and I think that once this Pr and your Pr merges, we should do a final clean up PR that refactors `ModuleOverflowMenu`, perhaps making a hook to clean up this component since it does a lot. I think a good PR that can encompass the refactor is the one that will close ticket #9289

2022-03-17 12:49 UTC, jerader commented on app/src/atoms/InputField/index.tsx
> +  min?: number
You're right! the min/max is redundant here I think. Good catch.

2022-03-17 22:32 UTC, shlokamin requested changes
looking good so far, great work @jerader this was a monster task. 

left some comments, also i think it would be a good exercise for us all to go through `ModuleOverflowMenu` and do a refactor at some point soon. theres a lot going on there and would probably be easier to discuss over video

2022-03-17 22:32 UTC, shlokamin commented on app/src/organisms/Devices/ModuleCard/HeaterShakerSlideout.tsx
> +    commandType: 'heaterShakerModule/awaitTemperature',
this should be set temp not await temp

2022-03-17 22:32 UTC, shlokamin commented on app/src/atoms/InputField/index.tsx
> +export const INPUT_TYPE_PASSWORD: 'password' = 'password'
this is totally valid, but doing a `as const` will do the same thing: 

```js
export const INPUT_TYPE_NUMBER = 'number' as const
```

2022-03-17 22:32 UTC, shlokamin commented on app/src/atoms/InputField/index.tsx
> +      color={props.error ? '#9e5e00' : COLORS.darkBlack}
this can be `COLOR_WARNING_DARK`

2022-03-17 22:32 UTC, shlokamin commented on app/src/atoms/InputField/index.tsx
> +    flex: 1 1;
is the flex: ` 1 1` necessary?

2022-03-17 22:32 UTC, shlokamin commented on app/src/atoms/InputField/index.tsx
> +          onChange={props.disabled ? undefined : props.onChange}
i dont think you need to include these ternaties, i think if an input field gets passed a disabled prop it automatically blocks click, blur, and onchange events: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled

2022-03-17 22:32 UTC, shlokamin commented on app/src/atoms/InputField/index.tsx
> +            flex="1 0"
is this ` flex="1 0"` necessary?

2022-03-17 22:32 UTC, shlokamin commented on app/src/organisms/Devices/ModuleCard/HeaterShakerSlideout.tsx
> +import { getModuleDisplayName, RPM, CELSIUS } from '@opentrons/shared-data'
this import should be moved up

2022-03-17 22:32 UTC, shlokamin commented on app/src/organisms/Devices/ModuleCard/HeaterShakerSlideout.tsx
> +  const inputMin = isSetShake ? 200 : 4
can we have these be constants imported from shared data?

2022-03-17 22:32 UTC, shlokamin commented on app/src/organisms/Devices/ModuleCard/HeaterShakerSlideout.tsx
> +          data-testid={`Hs_set_value_${module.model}`}
we have a bunch of scattered patterns (😢 ) but we normally prefix ids and data test ids with the component name right? i.e. ` data-testid={`HeaterShakerSlideout_${module.model}`}`

also, these ids should be unique, and if there are 2 H/S modules then there will be two ids that will be the same!

2022-03-17 22:32 UTC, shlokamin commented on app/src/organisms/Devices/ModuleCard/TemperatureModuleSlideout.tsx
> +const MAX = 99
i think these should exist in shared data somewhere... if not we should add them and import from there

2022-03-17 22:32 UTC, shlokamin commented on app/src/organisms/Devices/ModuleCard/TemperatureModuleSlideout.tsx
> +      })
something i need to go back into LPC and fix too, but all of these calls to `createLiveCommand ` should catch rejected promises in the event there is a server error of some sort. something like this: 
```js
const handleDeactivation = (): void => {
    createLiveCommand({
      command: deactivateCommand,
    }).catch((e: Error) => {
      console.error(`error deactivating module with command type ${deactivateCommand.commandType}: ${e.message}`)
    })
  }
```

2022-03-17 22:32 UTC, shlokamin commented on app/src/organisms/Devices/ModuleCard/TemperatureModuleSlideout.tsx
> +    (parseInt(temperatureValue) < 4 || parseInt(temperatureValue) > 99)
can these be replaces with constants (the 4 and 99)?

2022-03-17 22:32 UTC, shlokamin commented on app/src/organisms/Devices/ModuleCard/TemperatureModuleSlideout.tsx
> +              parseInt(temperatureValue) > MAX)
this is `valueOutOfRange ` right?

2022-03-17 22:32 UTC, shlokamin commented on app/src/organisms/Devices/ModuleCard/ThermocyclerModuleSlideout.tsx
> +      temperature: tempValue != null ? parseInt(tempValue) : 0,
hmm, i know this should never happen but i dont love this. i wonder if there is a way to construct the command right before we issue the request (rather than on every single render at the top level), that way if the field is disabled we ignore it altogether or something so TS will be happy

2022-03-17 22:32 UTC, shlokamin commented on app/src/organisms/Devices/ModuleCard/ThermocyclerModuleSlideout.tsx
> +      temperature: tempValue != null ? parseInt(tempValue) : 0,
i.e construct these commands inside `handleSubmitTemp`

2022-03-18 12:27 UTC, jerader commented on app/src/organisms/Devices/ModuleCard/HeaterShakerSlideout.tsx
> +  const inputMin = isSetShake ? 200 : 4
yup, i was debating about doing so. Will definitely add them

2022-03-18 12:28 UTC, jerader commented on app/src/organisms/Devices/ModuleCard/HeaterShakerSlideout.tsx
> +          data-testid={`Hs_set_value_${module.model}`}
I was never taught the data test id pattern. I'll change all of them to match this.

2022-03-18 17:31 UTC, b-cooper commented on app/src/atoms/InputField/index.tsx
> +export function InputField(props: InputFieldProps): JSX.Element {
I'd prefer this InputField's functionality be broken out a bit to specialize the fact that it's a number input.  min and max only make sense as props if the input is a number,  and `input` tags in general don't always operate on numbers.  Maybe `NumberInputField`?

2022-03-18 18:14 UTC, shlokamin approved these changes
Code looks good! Left some comments but once they're addressed i think this is ready to merge!

2022-03-18 18:14 UTC, shlokamin commented on app/src/organisms/Devices/ModuleCard/MagneticModuleSlideout.tsx
> +          data-testid={`MagneticSlideout_btn_${module.model}`}
small nit, the component name is `MagneticModuleSlideout`, so i think we want the id to be prefixed with that rather than `MagneticSlideout`.

also, if there are 2 magnetic modules, this will generate two buttons with the same data test id which isn't great, but tbh im not sure of a good way around this. since the `data-testid` attribute is already dubious and not very standardized i think this is okay, but if this were an `id` field i would say we should change it

2022-03-18 18:14 UTC, shlokamin commented on app/src/organisms/Devices/ModuleCard/ModuleOverflowMenu.tsx
> +  let typeOfCommand: CreateCommand['commandType']
nit, since we call this a `commandType` in schema v6, why not call it the same thing here?

2022-03-18 18:14 UTC, shlokamin commented on app/src/organisms/Devices/ModuleCard/ModuleOverflowMenu.tsx
> +
this is a boolean, why is it called `latchDisabledReason`?

2022-03-18 18:14 UTC, shlokamin commented on app/src/organisms/Devices/ModuleCard/ThermocyclerModuleSlideout.tsx
> +          data-testid={`ThermocyclerSlideout_btn_${module.model}_${isSecondaryTemp}`}
hmm can we come up with a more semantic selector? `ThermocyclerSlideout_btn_heaterShakerModulev1_false` is sort of hard to reason about. i guess it's really just the `_false` or `_true` that is confusing

2022-03-18 18:14 UTC, shlokamin commented on shared-data/js/constants.ts
> +export const TEMP_MAX = 99
can these be renamed to more clearly reflect the module? so something like: 

```js
export const TEMP_MODULE__MIN_TEMPERATURE = 4
```

just cuz other modules also have temperature/lid controls

2022-03-18 18:14 UTC, shlokamin commented on shared-data/js/constants.ts
> +export const RPM_MAX = 1800
same thing here

2022-03-18 18:19 UTC, jerader commented on app/src/organisms/Devices/ModuleCard/ModuleOverflowMenu.tsx
> +
oh whoops its because its the reason why the latch button would be disabled

2022-03-18 18:20 UTC, jerader commented on shared-data/js/constants.ts
> +export const TEMP_MAX = 99
all the temperature ranges for temp, TC, and hs is 4-99. The only different range is the TC lid

2022-03-18 21:26 UTC, merged