feat(api): add list to ot3utils for homing axes in order
OpenTrons/opentrons-api pull request #9709
Opened 2022-03-17 20:24 UTC by caila-marashaj

I added a little method in ot3utils containing a list of the axes in the correct order for homing. This could also go in types- is there a preference for location?

2022-03-17 20:30 UTC, Laura-Danielle requested changes
This won't work in the way that you expect for two reasons.

1. move groups are actually dictionaries which _do not_ have guaranteed order
2. You are still sending this all as 1 move group which means that it will try to execute this move group _simultaneously_.

What you need to do is make sure you have at least 2 move groups (1 for the Z/A (pip mounts) and 1 for the rest of the axes).

2022-03-17 20:37 UTC, caila-marashaj commented
> 

ohhh ok I understand. On it chief

2022-03-18 14:58 UTC, Laura-Danielle requested changes
Almost there!

Also, we should add a test for this to make sure that the move runner is receiving the two move groups in the correct order.

2022-03-18 14:58 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        if (OT3Axis.Z_L or OT3Axis.Z_R) in axes:
We can use the `OT3Axis.pipette_axes` or `OT3Axis.mount_axes` for this.

2022-03-18 14:58 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +            move_group.append(group_z)
The move group will execute in index order, so the z move would happen after the other one. Also, we're not filtering beforehand so the z axes might still be in the first move

2022-03-18 14:58 UTC, Laura-Danielle commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +
better to just create two different distance/velocity dicts right off the bat. We can use the `OT3Axis.pipette_axes` or `OT3Axis.mount_axes` to filter out or grab the Mount axes.

2022-03-22 13:37 UTC, sfoster1 requested changes
We should home any attached pipettes too. Doesn't really matter when we do it, on the ot2 it's during the Z phase tho

2022-03-22 13:41 UTC, sfoster1 commented
> We should home any attached pipettes too. Doesn't really matter when we do it, on the ot2 it's during the Z phase tho

You know, unlike the OT2 we have the capability to do far more independent movement commands and a much more easily shareable bus. Because a list of movegroups fed to a single movegrouprunner instance will execute in sequence because the host won't issue an execute of the second until the first have all completed, we could in fact basically fully parallelize the following:

```
sequence 1  |   sequence 2
home z/a     |   home pipettes
then             |
home xy      |
```
by creating _two_ `MoveGroupRunner`s, one for za then xy and the other for pipettes. Make sure that the z/a and x/y homes - unlike all other move groups - do _not_ contain `SingleAxisStep`s for the pipettes. Make sure that the pipettes move group uses a different move group index than za/xy. Then `asyncio.gather` the two `MoveGroupRunner` executions.

You could even _extend_ this parallelization by making sequence 2 also contain the move-to-bottom for the pipettes. This could be really cool!

2022-03-22 14:33 UTC, caila-marashaj commented
> > We should home any attached pipettes too. Doesn't really matter when we do it, on the ot2 it's during the Z phase tho
> 
> You know, unlike the OT2 we have the capability to do far more independent movement commands and a much more easily shareable bus. Because a list of movegroups fed to a single movegrouprunner instance will execute in sequence because the host won't issue an execute of the second until the first have all completed, we could in fact basically fully parallelize the following:
> 
> ```
> sequence 1  |   sequence 2
> home z/a    |   home pipettes
> then        |
> home xy     |
> ```
> 
> by creating _two_ `MoveGroupRunner`s, one for za then xy and the other for pipettes. Make sure that the z/a and x/y homes - unlike all other move groups - do _not_ contain `SingleAxisStep`s for the pipettes. Make sure that the pipettes move group uses a different move group index than za/xy. Then `asyncio.gather` the two `MoveGroupRunner` executions.
> 
> You could even _extend_ this parallelization by making sequence 2 also contain the move-to-bottom for the pipettes. This could be really cool!

This does sound like a great opportunity- what do you mean when you say the move-to-bottom? Is that part of the homing routine?

2022-03-23 19:34 UTC, sfoster1 requested changes
Use asyncio.gather instead of running in sequence, and we should test on a robot

2022-03-23 19:34 UTC, sfoster1 commented on api/src/opentrons/hardware_control/backends/ot3controller.py
> +        await runner_gantry_z.run(can_messenger=self._messenger)
these will run in sequence. if you instead use [asyncio.gather](https://docs.python.org/3/library/asyncio-task.html#asyncio.gather), they will run concurrently.

2022-03-25 15:11 UTC, sfoster1 approved these changes
Nice! Watched it work on a machine, code and tests look good.

2022-03-25 15:14 UTC, Laura-Danielle approved these changes
looks great to me! Nice tests :)

2022-03-28 14:43 UTC, merged