(api): Analyze v6 json protocols and translate v6 commands to protocol engine
OpenTrons/opentrons-api pull request #9772
Opened 2022-03-24 14:36 UTC by TamarZanzouri

# Overview

Analyze a Json v6 protocol in the protocol engine

# Changelog

- Implemented _load_json methon in protocol_runner.py to accept a Json v6 protocol
- Implemented a translation layer from Json v6 command to the protocol engine commands

# Review requests

Please take a look at test_json_command_translator.py INVALID_TEST_PARAMS. Feels redundancy or not implemented correctly. Would love to have feedback!

# Risk assessment

Make sure this works on a robot and legacy protocols work as well

2022-03-24 19:05 UTC, mcous requested changes
Looking pretty good! Little batch of comments from just reading the code, looks like there's still some debugging code to remove

2022-03-24 19:05 UTC, mcous commented on api/src/opentrons/protocol_runner/json_command_translator.py
> +        exclude_commands = [
Can we link to the #9553 epic for these exclusions?

2022-03-24 19:05 UTC, mcous commented on api/src/opentrons/protocol_runner/json_command_translator.py
> +                print(dict_command)
This print should be removed

2022-03-24 19:05 UTC, mcous commented on api/src/opentrons/protocol_runner/json_command_translator.py
> +                continue
Why does the labware command logic behave differently than the pipette and module logic? I think we should pick one of the two approaches and use it consistently

1. Modify command params, pass it to regular translation (used by loadPipette and loadModule)
2. Construct a new command and add it to the list, bypassing regular translation (used by loadLabware)

2022-03-24 19:05 UTC, mcous commented on api/src/opentrons/protocol_runner/json_command_translator.py
> +                continue
I find `continue` to be hard to follow in general. Can this be refactored to avoid `continue`?

2022-03-24 19:05 UTC, mcous commented on api/src/opentrons/protocol_runner/json_command_translator.py
> +                assert pipette_id is not None
Can we add TODO's on these asserts that explain how they're needed because out Pydantic model for JSONv6 isn't strict enough to differentiate between the different command payload types?

2022-03-24 19:05 UTC, mcous commented on api/src/opentrons/protocol_runner/json_command_translator.py
> +def _get_labware_command(
Do our tests cover this logic? Codecov doesn't seem to think so

2022-03-24 19:05 UTC, mcous commented on api/src/opentrons/protocol_runner/json_file_reader.py
> +    def read(protocol_source: ProtocolSource) -> ProtocolSchemaV6:
We should add smoke tests for this using the fixtures

2022-03-24 19:05 UTC, mcous commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +        allow_population_by_field_name = True
Why did we add this?

2022-03-24 20:22 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +        allow_population_by_field_name = True
If memory serves, then bizarrely, without this, this is an error:

```python
my_protocol = ProtocolSchemaV6(
    otSharedSchema="#/protocol/schemas/6",
    ...
)
```

Because Pydantic expects us to use the alias `$otSharedSchema` (which is impossible because of the dollar sign) instead of the field name `otSharedSchema`.

2022-03-24 20:27 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +        allow_population_by_field_name = True
In other words, from what I can tell, Pydantic has it totally backwards.

* If you do `model.dict()` or `model.json()`, you're probably trying to serialize a Python object into JSON. So you probably want to use field aliases. But this isn't the default; you have to do `.model.json(by_alias=True)`.
* If you do `model = Model(some_field=123, ...)`, you're constructing a Python object from other Python objects. So you probably want to use Python field names. But this isn't the default; you have to do `allow_population_by_field_name=True`.

🙃

2022-03-24 20:28 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/json_command_translator.py
> +                continue
I personally favor (2).

2022-03-25 14:11 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/json_command_translator.py
> +                continue
totally agree! I will change them all to the second approach

2022-03-25 14:12 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/json_command_translator.py
> +def _get_labware_command(
just added a test for this! Thank you!

2022-03-25 15:10 UTC, mcous commented on shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py
> +        allow_population_by_field_name = True
🤦

2022-03-25 15:19 UTC, mcous reviewed
Comments about the Tavern tests

2022-03-25 15:19 UTC, mcous commented on robot-server/tests/integration/protocols/simpleV6.json
> +{
Can we symlink this in from `shared-data` instead of duplicating it?

2022-03-25 15:19 UTC, mcous commented on robot-server/tests/integration/http_api/protocols/test_v6_json_protocol.tavern.yaml
> +              createdAt: '2022-03-24T20:20:13.507775+00:00'
`id`, `createdAt`, `key` (for now) will not be stable across different analysis runs, nor are they intended to be. I don't think this test as written can pass

2022-03-25 17:22 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/json_command_translator.py
> +                continue
The prob I have with the second approach is that we are losing all auto mapping capabilities. If I convert it all to the second approach I need to map each field manually.

2022-03-25 17:56 UTC, TamarZanzouri commented on robot-server/tests/integration/protocols/simpleV6.json
> +{
@y3rsh we spoke about this! @mcous we wanted to import it but we can only import from the python folder?

2022-03-25 17:56 UTC, TamarZanzouri commented on robot-server/tests/integration/http_api/protocols/test_v6_json_protocol.tavern.yaml
> +              createdAt: '2022-03-24T20:20:13.507775+00:00'
I removed their value to support any string! thank you!

2022-03-25 19:03 UTC, mcous commented on robot-server/tests/integration/protocols/simpleV6.json
> +{
I was suggesting creating a symbolic link via `ln -s` rather than copying the file. For example:

```shell
cd robot-server/tests/integration/protocols
ln -sf ../../../../shared-data/protocol/fixtures/6/simpleV6.json simpleV6.json
```

But it turns out, I think **this is unnecessary**. This test yaml worked fine for me, no symbolic link or file duplication required:

```yaml
stages:
  - name: Upload simple v6 protocol
    request:
      url: '{host:s}:{port:d}/protocols'
      method: POST
      files:
        files: '../shared-data/protocol/fixtures/6/simpleV6.json'
```

2022-03-28 15:32 UTC, mcous commented on robot-server/tests/integration/http_api/protocols/test_v6_json_protocol.tavern.yaml
> +        files: 'tests/integration/protocols/simpleV6.json'
Let's not duplicate the fixture file unnecessarily

```suggestion
        files: '../shared-data/protocol/fixtures/6/simpleV6.json'
```

2022-03-28 17:30 UTC, SyntaxColoring reviewed
Some final comments, but otherwise looks good to me!

-----

I can't leave a comment on the file because it's empty, but It looks like the `test.txt` file might have been committed accidentally?

2022-03-28 17:30 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/json_command_translator.py
> +def _get_labware_command(
Naming nitpick, feel free to ignore for this PR:

I might have called these `_translate_labware_command()`, etc. instead of `_get_labware_command()`, etc.

"Get," to me, implies retrieving something that already exists, rather than creating something.

2022-03-28 17:30 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/json_command_translator.py
> +def _get_command(command: Command) -> pe_commands.CommandCreate:
Naming nitpick, feel free to ignore for this PR:

I might rename this to `_get_other_command()` (or `_translate_other_command()`—see my other comment) and move it below the other 3 helper functions.

2022-03-28 17:30 UTC, SyntaxColoring commented on api/src/opentrons/protocol_runner/json_command_translator.py
> +    # error in case they do not exist in the v6 model
Nitpick, feel free to ignore for this PR:

I think the fact that this raises an error if these fields don't exist in the v6 model is self-evident from the code, and this comment should instead explain more about why we need to do this.

Namely: by JSON v6 specification, `command` *must* contain these fields. But, because of limitations in how we've modeled `params`, the type-checker doesn't know that; it thinks the fields might be `None`. And also, nothing before this `assert` has actually validated that the client provided a file that conforms to the spec in this way.

2022-03-28 17:30 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_runner/test_json_command_translator.py
> +            commandType="loadPipette",  # used to be delay but is expecting pause
There's a few of these comments on commands unrelated to pausing/delaying. Maybe they're left over from a copy-paste?

2022-03-28 17:30 UTC, SyntaxColoring commented on api/tests/opentrons/protocol_runner/test_json_command_translator.py
> +    with pytest.raises(AssertionError):
I think this is fine for now, but in general:

1. If a test tests that a function raises something, it's *usually* because the fact that it raises that thing is part of the function's public, documented interface. (Otherwise, why would we be testing it?)
2. If a function raises something as part of its interface, it should do `raise MyException()` instead of `assert`. `assert` statements [get disabled with optimizations](https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement). That makes them good for debugging, but not good for reporting actual cases where the function is miscalled.

I'd argue that this holds true for `JsonCommandTranslator`. It's given untrusted input, and part of its job is to flag when that input is wrong, instead of letting the problem propagate forward. But since we know [we shouldn't have to do this, anyway](https://github.com/Opentrons/opentrons/issues/9803), I'm fine leaving it as-is in this PR, if we don't want to go to the trouble of making a new exception type to raise.

2022-03-28 17:30 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/protocol/models/__init__.py
>  ]
No action needed for this PR, just thinking aloud:

I think re-exporting all these models indiscriminately is going to make things a bit confusing for calling code. What does `opentrons_shared_data.protocol.models.Robot` mean? It is, in fact, a `Robot` object as seen in JSON schema v6—but the import path makes it seem much broader than that.

Maybe we should reorganize things like:

* `opentrons_shared_data.protocol.models.v6.Protocol`
* `opentrons_shared_data.protocol.models.v6.Robot`
* etc.

Or even:

* `opentrons_shared_data.protocol.v6.Protocol`
* `opentrons_shared_data.protocol.v6.Robot`
* etc.

2022-03-28 17:41 UTC, TamarZanzouri commented on shared-data/python/opentrons_shared_data/protocol/models/__init__.py
>  ]
I can change the name to 'MachineDetails' or 'RobotDetails'. I agree this name is expected to have much broader details then it actually has.

2022-03-28 17:43 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/json_command_translator.py
> +def _get_command(command: Command) -> pe_commands.CommandCreate:
I changed this to _translate_simple_command()

2022-03-28 17:50 UTC, TamarZanzouri commented on api/src/opentrons/protocol_runner/json_command_translator.py
> +    # error in case they do not exist in the v6 model
I totally agree! I will change it!

2022-03-28 17:54 UTC, SyntaxColoring commented on shared-data/python/opentrons_shared_data/protocol/models/__init__.py
>  ]
I don't think that will help, because there are `MachineDetails` or `RobotDetails` for v5 protocols, too, which aren't necessarily the same model. In other words, I'm saying the class name `Robot` is perfectly fine—it's the *package name*, `models`, that's potentially ambiguous.

2022-03-28 18:05 UTC, mcous reviewed
Looks like `robot-server/tests/integration/http_api/protocols/test.txt` still needs to be removed, and I agree with Max's comment on the module exports from shared data.

I think these are the last two things I see for this PR, so we should be good to go shortly

2022-03-28 18:05 UTC, mcous commented on shared-data/python/opentrons_shared_data/protocol/models/__init__.py
>  ]
It looks like most of these re-exports aren't being used, and I agree with Max's comment. I know we've got some weirdness still to sort out in `opentrons_shared_data.protocols`, so let's do this for now:

```suggestion
from . import protocol_schema_v6
from .protocol_schema_v6 import ProtocolSchemeV6

__all__ = [
    "ProtocolSchemaV6",
    "protocol_schema_v6",
]
```

Export the main model (`ProtocolSchemaV6`) at the top level, but also re-export the entire `protocol_schema_v6` module for explicitly public access to all the subtypes

2022-03-28 18:08 UTC, TamarZanzouri commented on shared-data/python/opentrons_shared_data/protocol/models/__init__.py
>  ]
I can do that but don't we want to change the Robot class name anyway? @mcous it does feel too robust to what's in it

2022-03-28 18:29 UTC, TamarZanzouri commented on shared-data/python/opentrons_shared_data/protocol/models/__init__.py
>  ]
after reading this again I understand your point. thank you for pointing that

2022-03-28 19:02 UTC, SyntaxColoring approved these changes
Thanks for the changes.

It looks like CI is failing because of a formatting/linting problem. Once that's fixed and CI is passing, this looks good to me to merge. ✨

2022-03-28 19:58 UTC, mcous approved these changes

2022-03-28 20:54 UTC, merged