G code testing refactor
OpenTrons/opentrons-api pull request #9802
Opened 2022-03-28 16:18 UTC by DerekMaggio

# Overview

# Changelog

# Review requests

# Risk assessment

2022-03-28 19:17 UTC, sfoster1 requested changes
Nits: typos in some of the names - they're `master_comparision_files`, but there's an extra i, should be `master_comparison_files` for the dirname, variable constants, and test file please.

Couple tiny python changes we could make, but overall this looks good and it'll be a lot easier to run locally now, nice!

2022-03-28 19:17 UTC, sfoster1 commented on g-code-testing/g_code_test_data/g_code_configuration.py
> +        file_path = os.path.join(MASTER_FILES_FOLDER_PATH, self.get_master_file_path())
```python
with open(os.path.join(MASTER_FILES_FOLDER_PATH, self.get_master_file_path()), 'w') as master_file:
    master_file.write(self.execute())
```
?

2022-03-28 19:17 UTC, sfoster1 commented on g-code-testing/g_code_test_data/g_code_configuration.py
> +        file.write(self.self.execute())
`self.self`?

2022-03-28 20:08 UTC, DerekMaggio commented
I also update the Github Action filters for the project to match the other projects in the monorepo

2022-03-29 12:49 UTC, sfoster1 requested changes
Couple more typos (inline comments) but the code looks good

2022-03-29 12:49 UTC, sfoster1 commented on g-code-testing/README.md
> +To update comparison files override files in `g-code-testing/g_code_test_data/comparison_comparision_files` with the output of
```suggestion
To update comparison files override files in `g-code-testing/g_code_test_data/comparison_comparison_files` with the output of
```

2022-03-29 12:49 UTC, sfoster1 commented on g-code-testing/README.md
> +You can do this by using `make update-g-code-configuration-comparision name=<comparision_name>`
```suggestion
You can do this by using `make update-g-code-configuration-comparison name=<comparison_name>`
```

2022-03-29 12:49 UTC, sfoster1 commented on g-code-testing/Makefile
> +.PHONY: load-g-code-configuration-comparision
```suggestion
.PHONY: load-g-code-configuration-comparison
```

2022-03-29 12:49 UTC, sfoster1 commented on g-code-testing/Makefile
> +load-g-code-configuration-comparision:
```suggestion
load-g-code-configuration-comparison:
```

2022-03-29 12:49 UTC, sfoster1 commented on g-code-testing/Makefile
> +.PHONY: update-g-code-configuration-comparision
```suggestion
.PHONY: update-g-code-configuration-comparison
```

2022-03-29 12:49 UTC, sfoster1 commented on g-code-testing/Makefile
> +update-g-code-configuration-comparision:
```suggestion
update-g-code-configuration-comparison:
```

2022-03-29 12:49 UTC, sfoster1 commented on g-code-testing/tests/test_g_code_comparision.py
>      [conf.generate_pytest_param() for conf in HTTP_CONFIGURATIONS],
Please change the name of this file to `test_g_code_comparison.py` (one fewer i)

2022-03-29 12:49 UTC, sfoster1 commented on g-code-testing/README.md
> +## Uploading new comparison files
```suggestion
## Saving new comparison files
```

2022-04-04 15:03 UTC, sfoster1 approved these changes
nice!

2022-04-04 15:03 UTC, merged