WIP(api): faster simulation
OpenTrons/opentrons-api pull request #9821
Opened 2022-03-29 20:33 UTC by amitlissack

# Overview

These changes apply both to fast simulation and slow simulation.

# Changelog

# Review requests

# Risk assessment

2022-03-31 12:48 UTC, amitlissack commented on api/src/opentrons/hardware_control/instrument_handler.py
>          mm_per_s = ul_per_s / instr.ul_per_mm(instr.config.max_volume, action)
`ul_per_mm` calls `piecewise_volume_conversion` which does a decent bit of math.

These `plunger_X` methods can be called thousands of times with very small variance in inputs. The config values are immutable so caching seems like a save move.

2022-03-31 12:50 UTC, amitlissack commented on api/src/opentrons/protocols/geometry/planning.py
> -    if any([isinstance(item, ThermocyclerGeometry) for item in deck.values()]):
This method is called in each `plan_moves` which is called in each `move_to`. A needless search for a value that can be cached.

2022-03-31 13:50 UTC, sfoster1 requested changes
`InstrumentHandler` has the same lifetime as the hardware control api object and takes the attached instruments as inputs. That means that we need to clear the caches on the plunger position/speed/flowrate when the attached instruments change. 

What might be a better idea is adding an LRU cache on `hardware_control.pipettes.Pipette.ul_per_mm`. Since that has the lifetime of an instrument, and it gets replaced when you change instruments, it won't need cache clearing, and it's where all the work happens.

I also think we could change the cache location for the deck slot key checking, but reasonable people can disagree.

2022-03-31 13:50 UTC, sfoster1 commented on api/src/opentrons/protocols/geometry/deck.py
> +    @functools.lru_cache(20)
I wonder if it might be better to apply this to `_check_name`, which appears to be the only caller of `_assure_int` and does at least some more work - in the worst case, it'll do both an `_assure_int` call and a `__contains__` call which does a set op and so on and so on. I guess we'd need to invalidate the cache whenever `self.data` changes though.

2022-03-31 13:58 UTC, amitlissack commented on api/src/opentrons/protocols/geometry/deck.py
> +    @functools.lru_cache(20)
> `InstrumentHandler` has the same lifetime as the hardware control api object and takes the attached instruments as inputs. That means that we need to clear the caches on the plunger position/speed/flowrate when the attached instruments change.
> 
> What might be a better idea is adding an LRU cache on `hardware_control.pipettes.Pipette.ul_per_mm`. Since that has the lifetime of an instrument, and it gets replaced when you change instruments, it won't need cache clearing, and it's where all the work happens.
> 
> I also think we could change the cache location for the deck slot key checking, but reasonable people can disagree.

Thanks

2022-03-31 14:07 UTC, amitlissack commented
> `InstrumentHandler` has the same lifetime as the hardware control api object and takes the attached instruments as inputs. That means that we need to clear the caches on the plunger position/speed/flowrate when the attached instruments change.
> 
> What might be a better idea is adding an LRU cache on `hardware_control.pipettes.Pipette.ul_per_mm`. Since that has the lifetime of an instrument, and it gets replaced when you change instruments, it won't need cache clearing, and it's where all the work happens.
> 
> I also think we could change the cache location for the deck slot key checking, but reasonable people can disagree.

That's good to know. Thanks.

I was hoping to do exactly what you suggested, but lru cache requires hashable arguments. `ul_per_mm` and `_check_names` fail that test. I will continue working on this.

2022-04-05 13:47 UTC, amitlissack commented
> > `InstrumentHandler` has the same lifetime as the hardware control api object and takes the attached instruments as inputs. That means that we need to clear the caches on the plunger position/speed/flowrate when the attached instruments change.
> > What might be a better idea is adding an LRU cache on `hardware_control.pipettes.Pipette.ul_per_mm`. Since that has the lifetime of an instrument, and it gets replaced when you change instruments, it won't need cache clearing, and it's where all the work happens.
> > I also think we could change the cache location for the deck slot key checking, but reasonable people can disagree.
> 
> I'm not sure I understand you regarding `InstrumentHandler`. If the attached instruments change won't the `instr` arg to the plunger methods be different hence creating a new cache entry?
> 
> I was hoping to do exactly what you suggested, but lru cache requires hashable arguments. `ul_per_mm` and `_check_names` fail that test. I will continue working on this.

I was wrong. It's `piecewise_volume_conversion` whose args cannot be hashed. Moving cache to `ul_per_mm`

2022-04-05 13:48 UTC, mcous reviewed
Caching on a `Deck` method while the state of `Deck` can mutate underneath it makes me a little anxious. Is it necessary given the addition of the `thermocycler_preset` property?

2022-04-05 13:48 UTC, mcous commented on api/src/opentrons/protocols/geometry/deck.py
> +    @functools.lru_cache(20)
Is this safe? It looks like `self.data` will mutate without busting the cache

2022-04-05 13:48 UTC, mcous commented on api/src/opentrons/protocols/geometry/deck.py
> +        return id(self)
This feels iffy for the same reason the cache above feels iffy

2022-04-05 14:03 UTC, amitlissack commented
> Caching on a `Deck` method while the state of `Deck` can mutate underneath it makes me a little anxious. Is it necessary given the addition of the `thermocycler_preset` property?

I had initially put the lru_cache on `_assure_int` which is static, potentially called thousands of times, and harmless to cache. I moved the cache to `_check_names` without thinking it through.

2022-04-06 16:39 UTC, mcous approved these changes

2022-04-06 17:41 UTC, sfoster1 approved these changes
Looks great to me!

2022-04-06 18:01 UTC, merged