feat(update-server): add OE related capabilities
OpenTrons/opentrons-api pull request #9830
Opened 2022-03-30 15:04 UTC by sotaoverride

# Overview

Update root filesystem using .xz compression for update file. Function added to deal with the decompression and writing to inactive partition. An additional http request would be added to upload checksum for the .xz file, and make checksum validation possible. Can't really slap on the checksum on to a .xz. Commentary in code explains a few of the factors involved behind choosing .xz

# Changelog

A lot of the common update functions are not being implemented for openembedded updates currently. As validation, and
signing process gets implemented they might get actual implementations. 

# Review requests

Just trying to merge this into the feature branch for now. 

# Risk assessment
Tested using ethernet. No partition corruptions.

2022-03-30 15:30 UTC, sfoster1 requested changes
This makes sense to me. It's awesome that xz gives us that much better of a compression ratio, and I totally get why can't just make it `ot3_update.xz` and keep the same file structure. This seems like a solid intermediate step.

In terms of the pr code itself, the decompose and write stuff looks good, though there are some inline comments.

Let's not add a bunch of unused code, it just ends up being confusing. If we're not doing anything in `otupdate.openembedded.updater.Updater.validate_update`, let's just keep it as a `pass`, a `raise NotImplemented`, or a dummy return code so the update sequencing doesn't break.

Finally, I think we're maybe making the switch to lzma-compressed filesystems harder than we necessarily need to. What if our update bundles look like this:
```
ot3_update.zip # keep it as a zip so it looks the same to users, but we're really just using it as a container
|- rootfs.ext4.xz.hash
|- rootfs.ext4.xz.hash.sig
|- rootfs.ext4.xz
```
At that point, your `decomp_and_write` really is just `write_file`. we're hashing (and signing the hash of) the xz compression instead of the uncompressed version, which is fine and works exactly the same way. As long as we update the names of the update file components, we get most if not all of the rest of the functionality for free.

2022-03-30 15:30 UTC, sfoster1 commented on update-server/oe_upload.py
> +async def do_update(update_file: str, host: str, kind: UPDATE_KIND,
we definitely don't need to keep support for migration - that was the process that moved ot-2s from balena to buildroot and isn't applicable here.

2022-03-30 15:30 UTC, sfoster1 commented on update-server/otupdate/common/straight_fwd_update.py
> +        LOG.warning(f"header being currently read ===> {part.headers} in file_upload")
let's normalize info mesages to `info` level please

2022-03-30 15:30 UTC, sfoster1 commented on update-server/otupdate/common/update.py
> +            # LOG.warning("Stuck in _save_file?")
remove commented-out code

2022-03-30 15:30 UTC, sfoster1 commented on update-server/otupdate/openembedded/updater.py
> +        which = subprocess.check_output(["fw_printenv", "-n", "root_part"])
could keep the `.strip()` and we wouldn't need the newlines

2022-03-30 15:30 UTC, sfoster1 commented on update-server/otupdate/openembedded/updater.py
> +            with lzma.open(rootfs_filepath, "rb") as fsrc:
`with lzma.open(...) as fsrc, open(part.path, ...) as fdst:`?

2022-03-30 15:30 UTC, sfoster1 commented on update-server/otupdate/openembedded/updater.py
> +                        written_size += 1024
```suggestion
                        written_size += chunk_size
```

2022-03-30 15:30 UTC, sfoster1 commented on update-server/otupdate/openembedded/updater.py
> +        :return str: Path to the rootfs file ti update
```suggestion
        :return str: Path to the rootfs file to update
```

2022-03-30 15:30 UTC, sfoster1 commented on update-server/otupdate/openembedded/updater.py
> +        self.part_mngr.switch_partition()
Let's not do this. Instead, implement it in `commit_update` - let's take advantage of the task sequencing that exists.

2022-03-30 15:30 UTC, sfoster1 commented on update-server/otupdate/openembedded/updater.py
> +    def decomp_and_write(
This makes sense; ultimately, I think this function can just be reused in its entirety as `write_update`.

2022-03-30 15:30 UTC, sfoster1 commented on update-server/otupdate/common/update_actions.py
> +    def decomp_and_write(
If we just put the xz implementation in `write_file`, we don't need to add this or the dummy implementation in the ot2 actions.

2022-04-01 16:43 UTC, sfoster1 requested changes
Some inline stuff.

Definitely need to have tests for all the stuff that's added or modified here, though. That includes the validate/hashcheck and sigcheck. 

One way to avoid that might be refactoring them into using the same code as the ot2 version with different parameters - really, the only things that changed here are
- the name of the outer zip
- the way you write the update
- the name of the update files
Seems like they could be fed in to the rest of the code pretty easily.

2022-04-01 16:43 UTC, sfoster1 commented on update-server/otupdate/common/straight_fwd_update.py
> +        if part.name != "ot3_update.zip":
this is kind of a nitpick but could we keep this as similar to the ot2 as we can, so call this `ot3-system.zip`

2022-04-01 16:43 UTC, sfoster1 commented on update-server/otupdate/common/straight_fwd_update.py
> +        os.path.join(session.download_path, "ot3_update.zip"),
```suggestion
        os.path.join(session.download_path, "ot3-system.zip"),
```
and maybe drop the string literal in a constant somewhere

2022-04-01 16:43 UTC, sfoster1 commented on update-server/otupdate/common/update.py
> +            print(f"file written, {file} to path, {path}")
```suggestion
```
no prints please

2022-04-01 16:43 UTC, sfoster1 commented on update-server/otupdate/openembedded/updater.py
> +ROOTFS_SIG_NAME = "rootfs.ext4.hash.sig"
```suggestion
ROOTFS_SIG_NAME = "rootfs.xz.hash.sig"
```
?

2022-04-01 16:43 UTC, sfoster1 commented on update-server/otupdate/openembedded/updater.py
> +        As this method is currently not performing validation
this comment is out of date now I believe - it doesn't validate because the validation already happened.

2022-04-01 16:43 UTC, sfoster1 commented on update-server/otupdate/openembedded/updater.py
> +        with .xz rootfs size comes out at 223M,
this probably isn't a good comment content; the compressed rootfs size is going to vary with content over time

2022-04-01 16:43 UTC, sfoster1 commented on update-server/otupdate/openembedded/updater.py
> +        gz compression makes things slightly different from zip.
similarly, this is true but not quite relevant - we're still using zip as an outer wrapper, the xz compression is actually replacing the no-compression (or, well, zip compression, but only as a part of the archive).

2022-04-06 17:27 UTC, amitlissack commented on update-server/otupdate/common/straight_fwd_update.py
> +import asyncio
What does "straight forward" mean?

2022-04-06 17:27 UTC, amitlissack commented on update-server/otupdate/common/straight_fwd_update.py
> +    LOG.info(f"file path, " f"{downloaded_update_path}, in _begin_unzip_update_package")
These logging statements don't look right

2022-04-06 17:27 UTC, amitlissack commented on update-server/otupdate/common/straight_fwd_update.py
> +    LOG.info("In _begin_straight_fwd_decomp_and_write")
Logging statements are redundant

2022-04-06 17:27 UTC, amitlissack commented on update-server/otupdate/common/straight_fwd_update.py
> +    body called.
This function looks nearly identical to `file_upload` in `update.py`. Why do we need both?  There is a way to just use one.

2022-04-06 17:27 UTC, amitlissack commented on update-server/otupdate/common/update.py
> +        LOG.info(f"_save_file trying to write at ===> {path}")
Feels like a lot of these `info` level messages are really `debug`.

2022-04-07 13:53 UTC, sfoster1 requested changes
I think we should have tests on parity with the OT-2 side using mocked updater images to temporary files.

We should definitely tighten up the logging; most of these log entries should really be at debug level. 

I think there can be more commonization of some of these functions - a lot of them are very similar to oens in the ot-2 or in common.

Finally, just sticking with the same hash algo as the ot-2 side saves some complexity and an argument; I don't really see a benefit in changing the hash algorithm that oe uses, let's stick with what we have.

2022-04-07 13:53 UTC, sfoster1 commented on update-server/otupdate/common/straight_fwd_update.py
> +import asyncio
Yeah at this point you've done enough that this isn't a prototype anymore - maybe just `update.py`?

2022-04-07 13:53 UTC, sfoster1 commented on update-server/otupdate/openembedded/updater.py
> +        LOG.warning("Entering write_update of Updater class!")
this definitely shouldn't be `warning`, looks more like debug to me

2022-04-07 13:53 UTC, sfoster1 commented on update-server/tests/openembedded/test_updater.py
> +# test valid partition switch
We should definitely have more in-depth tests checking at least that we're using `lzma` correctly (we can locally make and check in an xz) and ideally a full updater zip file like exists for the ot2 implementation

2022-04-12 15:08 UTC, sotaoverride commented on update-server/tests/openembedded/test_updater.py
> +# test valid partition switch
github doesn't like the size for .xz when I try checking it in, so Im figuring something out for that..

2022-04-12 16:02 UTC, amitlissack commented on update-server/oe_upload.py
> +""" oe_update.py: client script for running OE updates
Why would this be in common if it's oe?

2022-04-12 17:08 UTC, amitlissack requested changes

2022-04-12 17:08 UTC, amitlissack commented on update-server/tests/openembedded/test_updater.py
> +    updater.decomp_and_write("/mmc/blk0p1", fake_callable(24))
Why pass `None` instead of a callback? What is 24?

2022-04-12 17:08 UTC, amitlissack commented on update-server/tests/openembedded/test_updater.py
> +    def fake_callable(fake_val: float):
If you don't care about the callback perhaps just use a lambda.

2022-04-12 17:08 UTC, amitlissack commented on update-server/tests/openembedded/test_updater.py
> +    cb = mock.Mock()
What is this test doing?

2022-04-12 17:08 UTC, amitlissack commented on update-server/tests/openembedded/test_updater.py
> +    if calls * 1024 != size_of_rootfs:
Why don't you use a multiple of 1024?

2022-04-12 17:08 UTC, amitlissack commented on update-server/otupdate/openembedded/updater.py
> +        total_size = 1436978176
Where does this number come from?

2022-04-12 17:08 UTC, amitlissack commented on update-server/otupdate/common/update.py
> +from .oe_update import _begin_unzip_update_package
Sure about this?

2022-04-12 17:08 UTC, amitlissack commented on update-server/otupdate/common/update.py
> +    if part.name == "ot2-system.zip":
I don't understand this approach. Why is ot2 and ot3 stuff getting into the common code? We have the `UpdateActionsInterface` for this.

2022-04-12 17:31 UTC, sotaoverride commented on update-server/otupdate/openembedded/updater.py
> +        total_size = 1436978176
this would come from a text file in the zipped update package because there is no other easy way of getting the decompressed size of a .xz. Initially the [thought](https://github.com/Opentrons/opentrons/pull/9830#discussion_r845162145) was just to check in an actual rootfs file for such tests, but that doesn't work. Trying to find a work around

2022-04-12 17:32 UTC, sotaoverride commented on update-server/otupdate/common/update.py
> +    if part.name == "ot2-system.zip":
Will take this out of common

2022-04-18 15:08 UTC, sfoster1 approved these changes
Looks good to me for now - let's get this merged!

2022-04-18 15:26 UTC, amitlissack approved these changes

2022-04-18 15:31 UTC, merged