refactor(app): wire up heater shaker wizard TestShake page
OpenTrons/opentrons-api pull request #9833
Opened 2022-03-30 17:09 UTC by sakibh

# Overview

This PR wires up the buttons and input for the testshake page of the heater shaker wizard. closes #9613 

# Changelog

- Wire up `TestShake.tsx` 
- Add test coverage

# Review requests

- Check that the design matches the Figma and the buttons/input are wired correctly.
 
# Risk assessment

low

2022-03-30 20:03 UTC, jerader requested changes
Overall looking pretty good! great job! Left a few comments.

Overall, I think we should be consistent on what `idle_unknown` means for the latch status. I remember discussing in the past that it means we should default to the latch being opened since we always wants to make sure the latch is closed before proceeding to use it.

2022-03-30 20:03 UTC, jerader commented on app/src/organisms/Devices/ModuleCard/HeaterShakerModuleData.tsx
> +                  size={'1rem'}
should we make the `1 rem` size a constant somewhere?

2022-03-30 20:03 UTC, jerader commented on app/src/organisms/Devices/HeaterShakerWizard/TestShake.tsx
> +
I thought we also wanted `idle_unknown` status to default to the latch being opened because we want to always ensure the latch is closed before the heater shaker is shaking/heating

2022-03-30 20:03 UTC, jerader commented on app/src/organisms/Devices/HeaterShakerWizard/TestShake.tsx
> +  const setLatchCommand:
you can use the `useLatchCommand` hook for this!

2022-03-30 20:03 UTC, jerader commented on app/src/organisms/Devices/HeaterShakerWizard/__tests__/TestShake.test.tsx
> +    props = {
You can add another test case here for when clicking on the button when the it is shaking will stop the shake.

2022-03-30 20:03 UTC, jerader commented on app/src/organisms/Devices/ModuleCard/HeaterShakerModuleData.tsx
> +  latchStatus: LatchStatus
since these all come from `module.data`, you could decrease the number of props and just have it take in `module.data` - looks like `HeaterShakerData` is an importable type.

2022-04-05 19:09 UTC, sakibh commented on app/src/organisms/Devices/ModuleCard/HeaterShakerModuleData.tsx
> +                  size={'1rem'}
Looks like we do have layout constants `components/src/styles/layout.ts`.

2022-04-05 19:12 UTC, sakibh commented on app/src/organisms/Devices/ModuleCard/HeaterShakerModuleData.tsx
> +  latchStatus: LatchStatus
We can totally do that. I decided to stick with this since other modules with similar components do it this way and it describes the component better.

2022-04-05 19:13 UTC, sakibh commented on app/src/atoms/InputField/index.tsx
> +    }
This additional css hides the up/down arrows when the `InputField` component strictly takes in numbers.

2022-04-05 20:17 UTC, shlokamin approved these changes
code LGTM! once we get specs for disabling module card CTAs  when there is an active run we'll have to come back and conditionally use `createLiveCommand` or `createCommand` depending on whether or not there is an active run, but we can worry about that later!

2022-04-05 20:17 UTC, shlokamin commented on app/src/atoms/InputField/index.tsx
> +    }
why do we want to hide arrows when the input field only takes numbers? wouldn't we want the opposite? 

also do we need two lines with `input[type='number']::-webkit-inner-spin-button`?

2022-04-07 13:02 UTC, sakibh commented on app/src/atoms/InputField/index.tsx
> +    }
It looks like we need to put both for the inner and one for the outer to hide the arrows.

2022-04-07 13:20 UTC, jerader approved these changes
LGTM!

2022-04-07 13:24 UTC, merged