feat(robot-server): Persist protocols across reboots in a configurable directory
OpenTrons/opentrons-api pull request #9864
Opened 2022-04-01 21:49 UTC by SyntaxColoring

# Overview

# Changelog

# Review requests

# Risk assessment

2022-04-05 22:27 UTC, SyntaxColoring commented on robot-server/robot_server/settings.py
> +        # get_settings().
Specifically, making this non-defaultable, the way I want, breaks two tests:

* `tests/service/notifications/test_handle_subscriber.py::test_create_subscriber`
* `tests/service/notifications/test_router.py::test_integration`

Because `robot_server.service.notifications.handle_subscriber.handle_socket()` does a raw call to `get_settings()`, and the unit tests are running without this `OT_ROBOT_SERVER_persistence_directory` variable in their environments, so the `get_settings()` fails.

It wasn't clear to me how to fix this.

* Change those unit tests to run with some explicit `OT_ROBOT_SERVER_persistence_directory` in their environment?
* Change *all* unit tests to run with some explicit `OT_ROBOT_SERVER_persistence_directory`?
* Replace the raw `get_settings()` call with something more granular?
* Mock the `get_settings()` call?

2022-04-06 14:15 UTC, mcous requested changes
Some naming and re-org requests

2022-04-06 14:15 UTC, mcous commented on robot-server/dev.env
> +OT_ROBOT_SERVER_persistence_directory=automatically_make_temporary
I'm not sure about using a magic string for this. A minor typo could result in persistence and the creation of a weird directory in a weird place. Can we use an empty string (and/or undefined env var) instead?

2022-04-06 14:15 UTC, mcous commented on robot-server/opentrons-robot-server.service
> +Environment=OT_ROBOT_SERVER_persistence_directory=/data/robot_server
I think this directory name should include `opentrons` as a prefix. Users are told they may put arbitrary data in `/data`, so we should mark "opentrons stuff" pretty explicitly.

I wonder if a dot-directory makes more sense; it might be nice for us to (eventually) sequester all our stuff in `/data/.opentrons` or something that suggests clearly "hey don't mess with this unless you know what you're doing"

2022-04-06 14:15 UTC, mcous commented on robot-server/robot_server/protocols/dependencies.py
> +            persistence_dir = Path(gettempdir())
A quick perusal of the contents of `gettempdir` on my computer shows a lot of directories prefixed by vendor. I think we should do the same. See above comment about naming the persistence directory `opentrons` or `.opentrons` by default.

I don't think it's good behavior to dump stuff into the bare system tempdir

2022-04-06 14:15 UTC, mcous commented on robot-server/robot_server/protocols/dependencies.py
> +async def _get_persistence_directory(
Can we move the persistence directory and DB initialization stuff to `robot_server.db`, if another PR hasn't done so already?

2022-04-06 14:15 UTC, mcous commented on robot-server/robot_server/settings.py
> +        # get_settings().
Setting aside the question of mocking (you're right, unit tests should be isolated and never hit actual `get_settings`), I disagree that this setting should not have a default.

Related to my comment above, I think this should be optional with a default of `None`. In this context, `None` means "temporary directory, so no persistence across reboots", which IMO is easier to explain and use than a magic string value

2022-04-06 14:15 UTC, mcous commented on robot-server/tests/protocols/test_protocol_store.py
> +    return subdirectory
Is this fixture necessary rather than just using `tmp_path`?

2022-04-06 14:18 UTC, mcous commented on robot-server/robot_server/app_setup.py
> +    get_settings()
Seems like code smell. If we have initialization to do, let's have an explicit `initialize_settings` function to call. Personally, I would be inclined to:

- Ditch the `lru_cache`
- Have an `initialize_settings` function that explicitly stores settings on the app state, like everything else
- Have a `get_settings` usable via `FastAPI` dependency

This gets at your mocking comment below, and may be too difficult and/or touch too many things for this PR, so feel free to disregard this comment for now

2022-04-06 14:59 UTC, TamarZanzouri reviewed
Looks good overall! just a few comments would love to understand

2022-04-06 14:59 UTC, TamarZanzouri commented on robot-server/robot_server/protocols/dependencies.py
>          add_protocol_store_tables_to_db(sql_engine)
this will change will my branch but overall looks good!

2022-04-06 14:59 UTC, TamarZanzouri commented on robot-server/robot_server/protocols/dependencies.py
> +async def get_protocol_directory(
why does this need to be in app_state? cant this live in the .env file? 
if this lives in the env file we wont need to deploy every path change?

2022-04-06 14:59 UTC, TamarZanzouri commented on robot-server/robot_server/settings.py
> +        # get_settings().
I think would mock get_settings()

2022-04-06 14:59 UTC, TamarZanzouri commented on robot-server/robot_server/protocols/dependencies.py
> +async def _get_persistence_directory(
I am taking care of it in the runs PR. Not the persistence path but I moved all db logic outside the dependency files. I will take care of the persistence path as well once this is merged into edge

2022-04-06 14:59 UTC, TamarZanzouri commented on robot-server/robot_server/settings.py
> +        # get_settings().
I like @mcous approach. So if its not set it won't persist across reboots? 
we still need to solve app_settings hitting real settings dont we?

2022-04-06 15:22 UTC, SyntaxColoring commented on robot-server/tests/protocols/test_protocol_store.py
> +    return subdirectory
It is, I think. `ProtocolStore` expects to be able to delete all files from the protocol directory. So, the `.db` file can't live in that same directory.

In other words, it can't be this:

* `some_temp_dir/`
    * `main.py`
    * `labware.json`
    * `database.db`

But this is okay:

* `some_temp_dir/`
    * `main.py`
    * `labware.json`
* `a_different_temp_dir/`
    * `database.db`

2022-04-06 15:40 UTC, SyntaxColoring commented on robot-server/opentrons-robot-server.service
> +Environment=OT_ROBOT_SERVER_persistence_directory=/data/robot_server
> I think this directory name should include opentrons as a prefix

I'm not sure about this. As far as I can tell, nothing else in `/data` (`labware/`, `robot/`, `tip_lengths/`, `pipettes/`) has had that prefix, except for the old `opentrons.db`.

> Users are told they may put arbitrary data in `/data`, so we should mark "opentrons stuff" pretty explicitly.

Are they? If they are, I think the solution is to have them stop doing that. I've personally always tried to steer people to `/data/user_storage` instead. Having to coexist with arbitrary user stuff in `/data`, our main persistence location, seems untenable.

2022-04-06 15:42 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/dependencies.py
> +            persistence_dir = Path(gettempdir())
Oops, this is me being dumb. I thought `gettempdir()` gave us a private subdirectory within the system tempdir.

I'll switch this to `mkdtemp()` or something with a prefix.

2022-04-06 15:43 UTC, SyntaxColoring commented on robot-server/robot_server/app_setup.py
> +    get_settings()
Totally agreed.

2022-04-06 17:26 UTC, mcous commented on robot-server/tests/protocols/test_protocol_store.py
> +    return subdirectory
Oh duh, thanks

2022-04-06 19:33 UTC, SyntaxColoring commented on robot-server/robot_server/settings.py
> +        # get_settings().
Supposing we can fix the test stuff, here's my thinking behind *not* having a default.

1. If I were reading a .env file or a command line that explicitly wants the server to use a temp dir, and I were unfamiliar with these settings, I'd find the string literal meaningfully more clear than an unset variable, empty-string, or `None` value.
1. Between the dev server and emulation and production, there wouldn't be any clear single use-case that the defaults would favor. Some variables would be unset to mean "do what the production server does," and other variables would be unset to mean "do what the dev server does." I think that would make it difficult to correctly maintain environment configurations and compare them with each other.
1. Typo safety. Sort of the same reasons that @mcous brought up in [his other comment](https://github.com/Opentrons/opentrons/pull/9864/files#r843983011), actually.

   @mcous correctly identified that, as written, if you typo the string `automatically_make_temporary`, you'll accidentally get actual persistence in a weird location. This is a good point that I hadn't considered. But if we make this setting defaultable by @mcous's suggestion, we get the same problem in the other direction. Specifically, if you typo the name `OT_ROBOT_SERVER_persistence_directory`, it will look like that variable is unset, and you'll get a temp dir by default. This seems equally subtle and confusing and bad, to me.

   You could catch the variable name typo by manual testing and paying attention. But that sword cuts both ways; you could also catch the `automatically_make_temporary` typo the same way.

-----

What if we split this into two variables?

* `persist_resources: bool` -- `true` if the server should save things somewhere persistent, `false` otherwise. Required.
* `persistence_directory: Path` -- Where to store stuff. Required if `persist_resources` is `true`, disallowed if `persist_resources` is `false`. 

If `persist_resources` is `true`, the server puts stuff under `persistence_directory`. If `persist_resources` is `false`, it puts stuff in an autogenerated temporary directory.

2022-04-06 19:36 UTC, SyntaxColoring commented on robot-server/dev.env
> +OT_ROBOT_SERVER_persistence_directory=automatically_make_temporary
Good catch. Replying in [the other thread.](https://github.com/Opentrons/opentrons/pull/9864/files#r843311709)

2022-04-06 21:14 UTC, mcous approved these changes
Changes to include `opentrons` in temp directory name look good. Additional thoughts on remaining threads, but no blockers

2022-04-06 21:14 UTC, mcous commented on robot-server/opentrons-robot-server.service
> +Environment=OT_ROBOT_SERVER_persistence_directory=/data/robot_server
I would propose that everything else gets moved into `.opentrons` or `opentrons`, too. It's pretty bike-sheddy, so don't super care, but my brain is looking for symmetry between running on a dev machine

- Dev machine: data stored in `~/.opentrons`, user stuff stored in `~`
- Prod machine: data stored in `/data/.opentrons`, user stuff stored in `/data`, maybe?

If this isn't compelling to you, I think I'd also be satisfied with `/data/opentrons_robot_server` as a compromise, to match the pacakage / service name

2022-04-06 21:14 UTC, mcous commented on robot-server/robot_server/protocols/dependencies.py
> +            persistence_dir = Path(mkdtemp(prefix=_TEMP_PERSISTENCE_DIR_PREFIX))
Could do something like this to have less blocking IO:

```python
import tempfile
...

if ...:
    persistence_dir = Path(tempfile.tempdir()) / _TEMP_PERSISTENCE_DIR_PREFIX
    _log.debug(f"Using temporary directory {persistence_dir} for persistence.")
else:
    persistence_dir = setting

await AsyncPath(persistence_dir).mkdir(parents=True, exist_ok=True)
_log.info(f"Using directory {persistence_dir} for persistence.")
```

2022-04-06 21:14 UTC, mcous commented on robot-server/robot_server/settings.py
> +        # get_settings().
Let's not do two variables, I think that makes the situation more confusing.

My comment came more from a place of disliking magic string values. Potential typo confusion is a symptom rather than the root of my dislike, so I don't want to over-index on resolving config typos, which I don't think is an actual problem worth solving.

To really sum up my thinking, it's:

1. We've got this setting that may be a `Path`, or it may be "something else"
2. What should that "something else" be?
3. `None` is the natural choice for "something else"
    - Makes sense in context: `None` == "no persistence"
    - No parsing / Pydantic gotchas, because can't be mistaken for a `Path`

That way, we don't end up with magic string checks floating around our code (or some obscure constant variable to do the same job). At the end of the day, leaning on `None` feels a lot more conventional to me than any other pattern.

This is such a tiny part of the code / PR, so I'm not trying to die on this hill. The comments and TODOs jumped out at me as a little needlessly complex when a `typing.Optional` seems good enough for the task. If you feel a strong preference for `automatically_make_temporary`, feel free to keep it

2022-04-06 22:02 UTC, y3rsh approved these changes
## This test passes.
> More to come.
```python
def test_dev_server(server_temp_directory: str) -> None:
    server = DevServer(server_temp_directory)
    robot = HttpRobot()
    if robot.alive():
        assert False, "A dev robot may NOT already be running when this test runs."
    server.start()
    assert robot.wait_until_alive(6), "Dev Robot never became available."
    protocols_to_create = 13
    for _ in range(protocols_to_create):
        time.sleep(0.5)
        file = create_protocol()
        robot.post_protocol([Path(file.name)])
        file.close()
    server.stop()
    assert robot.wait_until_dead(12), "Dev Robot did not stop."
    server.start()
    assert robot.wait_until_alive(6), "Dev Robot never became available."
    response = robot.get_protocols()
    # THE actual test step!
    assert len(response.json()["data"]) == protocols_to_create
    server.stop()
```

2022-04-07 01:21 UTC, SyntaxColoring commented on robot-server/opentrons-robot-server.service
> +Environment=OT_ROBOT_SERVER_persistence_directory=/data/robot_server
Hm interesting.

Moving forward with `/data/opentrons_robot_server` for now.

2022-04-07 02:12 UTC, SyntaxColoring commented on robot-server/robot_server/settings.py
> +        # get_settings().
Hm, okay, I see where you're coming from. I'm going to keep the string literal for now. We'll see how we feel about it in time, I guess.

2022-04-07 17:14 UTC, merged