Add sensor binding
OpenTrons/opentrons-api pull request #9872
Opened 2022-04-04 20:25 UTC by caila-marashaj

added additional values to `SensorOutputBinding` enum

2022-04-04 21:12 UTC, sfoster1 requested changes
One small change, but thanks!

2022-04-04 21:12 UTC, sfoster1 commented on hardware/opentrons_hardware/firmware_bindings/messages/fields.py
> +            binding_val = SensorOutputBinding(self.value).name
this won't work because it's possible for the value to be `3`, right. I think you can just take the `__repr__` implementation from `VersionFlagsField`:
```python
   def __repr__(self) -> str:
        """Print version flags."""
        flags_list = [
            flag.name for flag in SensorOutputBinding if bool(self.value & flag.value)
        ]
return f"{self.__class__.__name__}(value={','.join(flags_list)})"
```

2022-04-06 21:19 UTC, Laura-Danielle approved these changes

2022-04-11 14:56 UTC, sfoster1 approved these changes
Nice, thanks!

2022-04-11 14:56 UTC, merged