test(app): adding connect to IP slideout e2e tests
OpenTrons/opentrons-api pull request #9895
Opened 2022-04-06 17:29 UTC by reachojhaneha

Wrtiting the e2e testcase for connect to IP address

closes: [e2e ticket](https://app.zenhub.com/workspaces/app--ui-5f6248dba845b000139aa767/issues/opentrons/opentrons/9838)

2022-04-06 22:05 UTC, koji commented on app-testing/tests/app_settings_v5dot1_test.py
> +        app_settings.enter_hostname("AKNA")
This should be string[] instead of `string`

2022-04-07 01:47 UTC, koji commented
@reachojhaneha Sarah's latest PR has been merged into `edge`, so slideout would be okay.
I checked it manually.

2022-04-13 22:17 UTC, koji requested changes
`app_settings_v5dot1_test.py` requires a small change (L90).

```
app_settings.enter_hostname(["AKNA"])
```

2022-04-15 12:39 UTC, reachojhaneha commented
@koji your comment has been addressed

2022-04-15 12:56 UTC, koji approved these changes
Looks good to me!

2022-04-19 14:50 UTC, merged