feat (robot-server): persist runs and action runs in sql db
OpenTrons/opentrons-api pull request #9914
Opened 2022-04-07 19:30 UTC by TamarZanzouri

# Overview

Continuing work on issue #8468
Persist runs and run actions in SQLite DB instead of in memory store. 

# Changelog

- Changed upserting a run in the run store to insert\update in DB depending on the scenario 
- Inserting run actions to db table
- deleting a run
- changed data access structure. moved all tables into a models.py. moved all common functions into data_access.py.
- moved sql initialization from dependencies.py into common file data_access.py

# Review requests

Would love to decide about the structure of files\directory we want to keep.
I created a data_access directory that contains a models.py for the DB tables and a data_access.py for the common methods. We also have the db.py we can wither merge into data_access.py or the opposite way.

2022-04-07 19:34 UTC, TamarZanzouri commented on robot-server/robot_server/data_access/data_access.py
> +def get(sql_engine: sqlalchemy.engine.Engine, statement: sqlalchemy.sql.Select) -> Any: #sqlalchemy.engine.Row:
I am not sure about this implementation. Maybe we should keep duplicates for each table? feels like I am forcing it to be generic or maybe there is a better approach for this.

2022-04-07 19:34 UTC, TamarZanzouri commented on robot-server/robot_server/data_access/data_access.py
> +def get_all(sql_engine: sqlalchemy.engine.Engine, query_table: sqlalchemy.Table) -> Any: #Dict[str, object]:
I am not sure about this implementation. Maybe we should keep duplicates for each table? feels like I am forcing it to be generic or maybe there is a better approach for this.

2022-04-07 20:39 UTC, SyntaxColoring reviewed
Overall, this work in progress is looking good. ✨  Here are some thoughts on organizational and DB schema stuff. There are also some nitty-gritty code things that we'll get to later, I think.

2022-04-07 20:39 UTC, SyntaxColoring commented on robot-server/robot_server/data_access/models.py
> +        sqlalchemy.ForeignKey("protocol.id"),
A "fun" quirk of SQLite is that foreign key constraints are not actually enforced, by default. To enable them through SQLAlchemy, we need to do [this](https://docs.sqlalchemy.org/en/14/dialects/sqlite.html#foreign-key-support). We can attempt that in this PR if you want, but I think it's also okay if we want to leave a `# TODO` and defer it.

2022-04-07 20:39 UTC, SyntaxColoring commented on robot-server/robot_server/data_access/models.py
> +    "protocol_run",
I would call this table `"run"`, not `"protocol_run"`. The way we've defined it at the HTTP level, a run doesn't necessarily have an associated protocol. (Though it usually does.)

2022-04-07 20:39 UTC, SyntaxColoring commented on robot-server/robot_server/data_access/models.py
> +    )
I wonder if it actually makes sense to persist this.

I think after a reboot, no run should be active. It's not like the client could continue using the active run the same way it had before. The hardware state has been reset.

-----

A totally different point: in general, I think we should avoid default values in the data store layer. I think it should be the higher layers' responsibility to provide us with every single field. That way, we should make it impossible for ourselves to make silly mistakes like forgetting to specify a field somewhere and accidentally letting it take the default value.

This doesn't matter if we delete this column entirely, of course.

2022-04-07 20:39 UTC, SyntaxColoring commented on robot-server/robot_server/data_access/models.py
> +    ),
I think we need something here to retain the order in which actions were added.

As a hack, we might try to `SORT BY created_at`. But `created_at` is a non-monotonic wall clock timestamp, so we really shouldn't.

I guess we could give every action an integer `sequence_number`, or something?

And we *might* need to consider the same thing for run resources and protocol resources, too.

We don't have to address all of this in this PR, but we should plan out an approach, I think.

2022-04-07 20:39 UTC, SyntaxColoring commented on robot-server/robot_server/data_access/data_access.py
> +    return row_run
The `except ... raise` here isn't doing anything, so this is basically equivalent to:

```python
def get(sql_engine: sqlalchemy.engine.Engine, statement: sqlalchemy.sql.Select) -> Any: #sqlalchemy.engine.Row:
    with sql_engine.begin() as transaction:
        return transaction.execute(statement).one()
```

And at that point, I don't know if it's worth having a function for this. I think the caller may as well just execute the statement directly.

I could see this being helpful for more complicated recurring patterns like "delete this ID and return the state before it was deleted, or raise an error if that ID wasn't present."

Also note that putting transactions inside helper functions like this might make it easy to accidentally do nested transactions, as if we had written:

```python
with sql_engine.begin() as t1:
    with sql_engine.begin() as t2:
        ...
```

Which the SQLAlchemy docs call [an antipattern](https://docs.sqlalchemy.org/en/14/core/connections.html#arbitrary-transaction-nesting-as-an-antipattern) and which [may not be supported in SQLite anyway](https://www.sqlite.org/lang_transaction.html).

2022-04-07 20:41 UTC, SyntaxColoring commented on robot-server/robot_server/data_access/data_access.py
> +def get(sql_engine: sqlalchemy.engine.Engine, statement: sqlalchemy.sql.Select) -> Any: #sqlalchemy.engine.Row:
I agree, I think we should just duplicate this.

The `except ... raise` here isn't doing anything, so this is basically equivalent to:

```python
def get(sql_engine: sqlalchemy.engine.Engine, statement: sqlalchemy.sql.Select) -> Any: #sqlalchemy.engine.Row:
    with sql_engine.begin() as transaction:
        return transaction.execute(statement).one()
```

And at that point, I don't know if it's worth having a function for this. I think the caller may as well just execute the statement directly.

I could see this being helpful for more complicated recurring patterns like "delete this ID and return the state before it was deleted, or raise an error if that ID wasn't present." Maybe, not sure.

Also note that putting transactions inside helper functions like this might make it easy to accidentally do nested transactions, as if we had written:

```python
with sql_engine.begin() as t1:
    with sql_engine.begin() as t2:
        ...
```

Which the SQLAlchemy docs call [an antipattern](https://docs.sqlalchemy.org/en/14/core/connections.html#arbitrary-transaction-nesting-as-an-antipattern) and which [may not be supported in SQLite anyway](https://www.sqlite.org/lang_transaction.html).

2022-04-08 13:38 UTC, mcous commented on robot-server/tests/runs/router/test_actions_router.py
> +        yield sql_engine
This fixture should be removed. We should mock out all dependencies in router tests

2022-04-08 13:38 UTC, mcous commented on robot-server/tests/runs/router/test_actions_router.py
> +    return RunStore(sql_engine=in_memory_sql_engine)
The name `subject` is a "reserved" word we use for the "subjuct under test". This file contains tests for the action router methods, so a `RunStore` is not a test subject but a dependency.

For these tests, we need a `decoy.mock(cls=RunStore)`, not a real run store with a fake database. A fixture to do this already exists in `tests/runs/router/conftest.py`, so this fixture should be removed and renames from `run_store` to `subject` should be reverted.

2022-04-08 15:50 UTC, TamarZanzouri commented on robot-server/robot_server/data_access/models.py
> +        sqlalchemy.ForeignKey("protocol.id"),
interesting! I will add a todo for that. Thank you for the heads up!

2022-04-08 15:54 UTC, TamarZanzouri commented on robot-server/robot_server/data_access/models.py
> +    )
sure! That makes sense to me. I will removed the default value. Related to the `active_run` column, when we are inserting\updating a run and the run is marked as active we are checking to see if there are any current runs that are marked active. if there are we are setting them as not active.

2022-04-08 16:00 UTC, TamarZanzouri commented on robot-server/robot_server/data_access/models.py
> +    )
@SyntaxColoring get_runs for example in `runs/router/base_router.py` is getting all runs and looping through all runs and checking if they are active.

2022-04-08 16:02 UTC, TamarZanzouri commented on robot-server/robot_server/data_access/models.py
> +    ),
we defiantly need an 'order' field or something to maintain the order of actions. can we relay on the list order for that?

2022-04-08 16:03 UTC, TamarZanzouri commented on robot-server/tests/runs/router/test_actions_router.py
> +    return RunStore(sql_engine=in_memory_sql_engine)
Thank you for the explanation @mcous! this is much more understood now and I changed the names to contain mock

2022-04-08 16:20 UTC, TamarZanzouri commented on robot-server/robot_server/data_access/models.py
> +    ),
I added a todo for now

2022-04-08 20:44 UTC, SyntaxColoring requested changes

2022-04-08 20:44 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/dependencies.py
> -from anyio import Path as AsyncPath
Style nitpick: let's keep the empty line here, to separate standard library imports (`logging`) from 3rd-party imports (`fastapi`).

2022-04-08 20:44 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/dependencies.py
> +from ..data_access.data_access import get_sql_engine
Style nitpick for consistency:

Can we make this an absolute import statement, like `from robot_server.data_access.data_access import sql_engine`, and move it up next to the `from robot_server.app_state import ...` line, above? 

-----

Organization and naming note:

As a general rule of thumb, I think it's an organizational red flag if an `import` statement has to repeat things like `data_access` here.

Personally, I'd group all the `data_access` stuff into a single flat module. So, here, we'd do `from robot_server.data_access import get_sql_engine`. I'd also name the module `persistence` instead of `data_access` because `data_access` feels vaguer to me, but that's pure personal preference.

2022-04-08 20:44 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/protocol_models.py
> -
Looks like a stray whitespace change from the merge conflict resolution.

2022-04-08 20:44 UTC, SyntaxColoring commented on robot-server/robot_server/data_access/models.py
> +action_runs_table = sqlalchemy.Table(
I think we should rename this Python object to `run_action_table` to match the SQL name, and the pattern used by other tables.

2022-04-08 20:44 UTC, SyntaxColoring commented on robot-server/robot_server/data_access/models.py
> +        nullable=True,
Why is this nullable? I could be misreading things, but I thought every run action is associated with exactly 1 run.

2022-04-08 20:44 UTC, SyntaxColoring commented on robot-server/robot_server/protocols/router.py
> +from ..data_access.data_access import get_protocol_directory
Style nitpick for consistency: let's make this an absolute import (`from robot_server.data_access ...`) and move it up with the other absolute `from robot_server ...` imports.

2022-04-08 20:44 UTC, SyntaxColoring commented on robot-server/robot_server/runs/dependencies.py
> +from sqlalchemy.engine import Engine as SQLEngine
Style nitpick: Let's move this `sqlalchemy` import next to the `fastapi` import, to group the 3rd-party libraries together (following [this PEP8 guideline](https://peps.python.org/pep-0008/#imports)).

2022-04-08 20:44 UTC, SyntaxColoring commented on robot-server/robot_server/data_access/data_access.py
> +    """
Outdated docstring:

```suggestion
    """Create the necessary database tables to back all data stores.

    Params:
        sql_engine: An engine for a blank SQL database, to put the tables in.
    """
```

2022-04-08 20:44 UTC, SyntaxColoring commented on robot-server/robot_server/data_access/data_access.py
> +    """
I would write this like:

```suggestion
    """Return a singleton SQL engine referring to a ready-to-use database."""
```

* Given the myriad things that a `SQLEngine` could refer to, I think it's important for the caller to know that this one refers to a database that's actually ready-to-use (not an empty database), and that it's a singleton.
* The fact that this sets something on `app_state` is an implementation detail that callers don't need to know about.

2022-04-08 20:44 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_store.py
> +                print(e)
Stray `print()` statement.

2022-04-08 20:44 UTC, SyntaxColoring commented on robot-server/tests/runs/test_run_store.py
> +def test_update_run(subject: RunStore) -> None:
It looks like we're missing tests for:

* `.update()`, when passed a bad `run_id`.
* `.update_actions()` in the happy case.
* `.update_actions()` when passed a bad `run_id`.

These cases never existed before, because it used to be `upsert()`.

2022-04-08 20:44 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_store.py
> +            raise e
For a few reasons, I don't think this `try ... except` is meaningful.

1. It's re-raising the thing that it caught (`raise e`), which is a no-op.
2. Nothing in the `try` block will raise `NoResultFound`. Note that the `execute()` call will simply affect 0 rows if we're provided a bad `run_id`, not raise `NoResultFound`.
3. If I'm reading this right, it's *expected* for the result set to affect 0 rows sometimes, because a valid run may have 0 actions attached to it.

2022-04-08 20:44 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_store.py
> +        self.insert_actions(run_id, actions)
It looks like this:

1. Enters a transaction to delete the old actions
2. Leaves the transaction
3. Starts a new transaction to insert new actions

Which opens up a window to race conditions in between steps 2 and 3.

As you've found already, SQLite doesn't support nested transactions. (And even if it did, they're sometimes considered bad practice.) So, if we don't want to duplicate the `insert_actions` code here, our only option is to factor it out like this:

* `update_actions()`
    * in a transaction...
        * delete old actions
        * `self._insert_actions_no_transaction()` (not a great name)
* `insert_actions()`
    * in a transaction...
        * `self._insert_actions_no_transaction()`
* `_insert_actions_no_transaction(transaction)`:
    * Insert actions *given a transaction that's already running.*

2022-04-08 20:44 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_store.py
> +            insert_actions.append(_convert_action_to_sql_values(action, run_id))
Stylistically, we generally prefer list comprehensions over procedurally building up a list element-by-element.

```suggestion
        actions_to_insert = [
            _convert_action_to_sql_values(action, run_id) for action in actions
        ]
```

2022-04-08 20:44 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_store.py
> +    action_id = sql_row.id_1
Do we know why this is `sql_row.id_1` instead of `sql_row.id`?

2022-04-08 20:44 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_store.py
> +        except sqlalchemy.exc.NoResultFound as e:
As a general rule, we should aim for `try` blocks to cover the absolute minimum code that we actually expect to raise the thing that `except` is catching. 

We should also aim for `with` blocks to not be much bigger than they have to be.

So, for example, this becomes roughly:

```python
with self._sql_engine.begin() as transaction:
    try:
        run_row = transaction.execute(statement).one()
        run = _convert_sql_row_to_run(run_row)
    except sqlalchemy.exc.NoResultFound as e:
        raise RunNotFoundError(run.id) from e

for action in actions:
    if action.id_1:
        run.actions.append(_convert_sql_row_to_action(action))
```

Note that the `try` block gets moved inside the `with` block to demonstrate that we're expecting the exception to come from the `.execute()` statement, *not* from entering the `with` block or exiting the `with` block. And both the `try` and `with` block in general cover less logic.

2022-04-08 20:49 UTC, SyntaxColoring commented on robot-server/robot_server/data_access/models.py
> +    )
OK. I think we should maintain that boolean active state in-memory, outside of the database. As a plain Python dict of run IDs to `bool`s, for example.

2022-04-09 13:45 UTC, TamarZanzouri commented on robot-server/robot_server/protocols/dependencies.py
> +from ..data_access.data_access import get_sql_engine
I changed the name to persistence. I called it initially data_access bc the purpose of this file was to access the data from the persistence layer. It ended up being initialization of the persistence layer so this naming change makes sense to me

2022-04-09 13:59 UTC, TamarZanzouri commented on robot-server/robot_server/runs/run_store.py
> +    action_id = sql_row.id_1
I printed the columns with a join. This might changed now. I will check.

2022-04-10 14:21 UTC, TamarZanzouri commented on robot-server/robot_server/runs/run_store.py
> +            raise e
Do we want to raise an error if the affected rows is 0? or return a boolean to mark a successful action?

2022-04-12 16:25 UTC, TamarZanzouri commented on robot-server/robot_server/runs/router/actions_router.py
> +    run_store.update(run=next_run)
should change this to run_store.insert_actions()

2022-04-12 16:58 UTC, mcous reviewed
Re-org looks really good. Leaving the comments that we discussed in person. Mostly at this point I think we just need to remove what we don't need / use and this will be good to go

2022-04-12 16:58 UTC, mcous commented on robot-server/robot_server/persistence.py
> +# convert these to return an async engine.
```suggestion
# TODO(mm, 2022-03-29): convert these to return an async engine.
```

(OT-2 has `SQLAlchemy@1.4`, so we can simplify this TODO)

2022-04-12 16:58 UTC, mcous commented on robot-server/robot_server/persistence.py
> +    """Like `create_in_memory_db()`, except without automatic cleanup."""
I think this docstring is out of date. Is this what it's trying to say?

```suggestion
    """Create a database engine for performing transactions."""
```

2022-04-12 16:58 UTC, mcous commented on robot-server/robot_server/persistence.py
> +async def get_protocol_directory(
We may want to  move this back into `robot_server.protocols`, since its an implementation detail of protocol storage and nothing else

2022-04-12 16:58 UTC, mcous commented on robot-server/robot_server/persistence.py
> +def opened_db(db_file_path: Path) -> Generator[SQLEngine, None, None]:
It looks like this function is only used in tests. If so, I think it should be a test fixture and not a public part of the `robot_server.persistence` API. That's not to say this won't be useful in the public API in the future, just that I would like us to be really militant about keeping our APIs pared down to what we actually use

2022-04-12 16:58 UTC, mcous commented on robot-server/robot_server/runs/router/actions_router.py
> +    run_store.update(run=next_run)
As discussed, let's add a new `run_store.add_action` method that simply adds an action to the actions table. From there, we should be able to simplify this handler by removing the `run_view.with_action` method, which was only there to support the old, in-memory dict storage method

2022-04-12 16:58 UTC, mcous commented on robot-server/robot_server/runs/router/base_router.py
> +        run_store.update(run)
I think we might want to pass the `RunUpdate` in here directly. If the `RunStore` then returns the updated run resource, then we can ditch `run_view.with_update` above, too

2022-04-12 16:58 UTC, mcous commented on robot-server/robot_server/runs/run_store.py
> +            transaction.execute(update_statement)
As discussed, let's remove this unused SQL update for now, since `current` is the only field that gets updated, and it stays entirely in memory

2022-04-12 18:23 UTC, SyntaxColoring commented on robot-server/robot_server/persistence.py
> +def opened_db(db_file_path: Path) -> Generator[SQLEngine, None, None]:
Yeah.

My thinking behind this was that `opened_db()` is the "right" API, and `open_db_no_cleanup()` is a concession to work with FastAPI.

* We historically have had, and continue to have, resource management problems.
* The easiest way to solve these problems, in general, is to structure our resource management around context managers. (Or things equivalent to context managers, like Pytest's `yield` fixtures and FastAPI's `yield` dependencies.)

    I hypothesize that if we make a habit of starting with context managers, we'll automatically get things right more frequently than if we start with `open()`/`close()` pairs and build context managers atop them. It's way easier to see that something should be cleaned up if it's primarily exposed as a context manager.
* FastAPI is the odd man out. In some cases, it makes it unusually clunky to do normal, clean, Pythonic resource management. As a concession to keep the code minimal, at the cost of code cleanliness, we have things like `open_db_no_cleanup()` as an alternative to the primary context manager interface to interface with FastAPII.

I can see where you're coming from about not keeping around APIs that the production code isn't actually using. If it were my code, I'd still keep `opened_db()`. But I wouldn't mind if it were removed, if the above isn't convincing.

2022-04-13 15:40 UTC, SyntaxColoring commented on robot-server/robot_server/persistence.py
> +def opened_db(db_file_path: Path) -> Generator[SQLEngine, None, None]:
Discussed with @TamarZanzouri: we'll move this to be test-only.

2022-04-13 18:34 UTC, TamarZanzouri commented on robot-server/robot_server/runs/run_store.py
> +    def update_active_run(self, run_id: str, is_current: bool) -> RunResource:
Debating if to add a check if the run exists in the DB before setting this prop (it will cause en exception at the end when we get the run but the prop will still be set). I did not add it bc everywhere this method is being called we check existence of the run before. that said, it feels bad not checking before assigning.

2022-04-13 18:47 UTC, mcous approved these changes
Pretty quick review from me, so I'd wait for another 👍 from someone else before moving forward, but based on our conversation yesterday and the latest code, I think this is good!

A few minor cleanup comments below.

2022-04-13 18:47 UTC, mcous commented on robot-server/robot_server/persistence.py
> +    sqlalchemy.Column(
Does this column need `nullable=False`?

2022-04-13 18:47 UTC, mcous commented on robot-server/robot_server/runs/router/actions_router.py
> -    action, next_run = run_view.with_action(
The `run_view` dependency should also be removed from this route handler

2022-04-13 18:47 UTC, mcous commented on robot-server/robot_server/runs/router/base_router.py
> -from ..run_view import RunView
Is `RunView` used anywhere anymore? Can the file be deleted?

2022-04-13 18:48 UTC, TamarZanzouri commented on robot-server/robot_server/persistence.py
> +    sqlalchemy.Column(
I added it :-) Thank you for noticing!

2022-04-13 18:51 UTC, TamarZanzouri commented on robot-server/robot_server/runs/router/base_router.py
> -from ..run_view import RunView
I think I can remove it completely!

2022-04-13 20:52 UTC, SyntaxColoring approved these changes
Nice! 🚀 

Here are a bunch of little things. If these fixups turn out to not be quick, feel free to merge this PR as-is and defer them to follow-up PRs. As long as we keep track of the open items via `# TODO` comments or unresolved GitHub threads or something.

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/robot_server/persistence.py
> +actions_table = sqlalchemy.Table(
Naming nitpick, feel free to ignore: should this be `action_table` to match the existing convention?

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/tests/runs/router/test_actions_router.py
> +        mock_run_store.insert_action(run_id=next_run.run_id, action=action),
Since we're not doing `run_store.upsert()` anymore, we can now simplify this test by:

1. Deleting the `next_run` variable.
2. Using `run_id=prev_run.run_id` here instead of `run_id=next_run.run_id`.

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/tests/runs/router/test_actions_router.py
> +        mock_run_store.insert_action(run_id=next_run.run_id, action=action),
See other comment about deleting `next_run`.

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/tests/runs/router/test_actions_router.py
> +    )
This makes sense to me; I think you can remove this `# TODO`.

If you want, you could also make it like this:

```suggestion
    decoy.verify(
        mock_run_store.insert_action(
            run_id=matchers.Anything(), action=matchers.Anything()
        ),
        times=0,
    )
```

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/tests/runs/router/test_actions_router.py
> +        mock_run_store.insert_action(run_id=next_run.run_id, action=action),
See other comment about deleting `next_run`.

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/tests/runs/router/test_actions_router.py
> +        mock_run_store.insert_action(run_id=next_run.run_id, action=action),
See other comment about deleting `next_run`.

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/robot_server/runs/router/base_router.py
> +            is_current=update.current if update.current is not None else run.is_current,
What's the intent of this `update.current if update.current is not None else run.is_current` expression? This whole thing is in an `elif update.current is False: ...` block, so I don't see any way of this evaluating to something other than `False`.

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/tests/runs/router/test_base_router.py
> +    )
I would simplify this to:

```suggestion
    decoy.verify(
        mock_run_store.update_active_run(
            run_id=matchers.Anything(),
            is_current=matchers.Anything()
        ),
        times=0,
    )
```

The intent of this test, according to the docstring, is that the router shouldn't do anything when a client tries to `PATCH {"current": true}` for a run that's already current. So if the router calls `run_store.update_active_run()` with *any* arguments, that's probably a mistake that this test should catch.

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/tests/protocols/test_protocol_store.py
> +        sql_engine.dispose()
Minor tweak:

```suggestion
    db_file_path = tmp_path / "test.db"
    sql_engine = open_db_no_cleanup(db_file_path=db_file_path)
    try:
        add_tables_to_db(sql_engine)
        yield sql_engine
    finally:
        sql_engine.dispose()
```

Because if `add_tables_to_db()` raises an exception, `sql_engine` still needs to be cleaned up.

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/tests/runs/test_run_store.py
> +        sql_engine.dispose()
See my note in `test_protocol_store.py` about putting `add_tables_to_db()` inside the `try` block.

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_store.py
> +        self._active_run = ""
When no run is active, let's designate that with `None` instead of an empty string.

```suggestion
        self._active_run: Optional[str] = None
```

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_store.py
> +            self._active_run = ""
```suggestion
            self._active_run = None
```

(Matching my other comment about using `None` when no run is current.)

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_store.py
> +    def update_active_run(self, run_id: str, is_current: bool) -> RunResource:
Yeah, I think if `run_id` is invalid, `update_active_run()` would ideally raise `RunNotFoundError` and act as if nothing happened.

Mostly for refactor safety. Those external checks suffice for now, but it's easier to be confident when using a unit like this if it can defend itself against mistakes.

For this PR, I think a `# TODO` would be fine.

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_store.py
> +    assert isinstance(is_current, bool)
I think we can delete this `isinstance()` check. The other ones are guarding against type-unsafe data from SQLAlchemy, so they're worth keeping. But this one is just a simple `==` expression between two values that are already type-safe.

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_store.py
> +        ]
This looks like we're getting the run and its actions in two separate transactions. I think they need to be in a single transaction to provide a consistent snapshot view of everything.

(In practice, this probably doesn't actually matter right now because we're the only thing accessing this table, and all of these methods are synchronous. But I think it will matter more when they become `async`.)

We could restructure this like:

```suggestion
        statement = sqlalchemy.select(run_table)
        with self._sql_engine.begin() as transaction:
            runs = transaction.execute(statement).all()
            return [
                _convert_sql_row_to_run(
                    sql_row=row,
                    actions=self._get_no_transaction(row.id,  transaction),
                    current_run_id=self._active_run,
                )
                for row in runs
            ]
```

And then you could delete `self._get_actions()`, since this was the last thing using it.

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_store.py
> +        delete_statement = sqlalchemy.delete(run_table).where(run_table.c.id == run_id)
Do we also need a second `DELETE` statement for the run's actions?

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/robot_server/runs/run_store.py
> +        return _convert_sql_row_to_run(row_to_delete, [], self._active_run)
I'd expect the returned `RunResource` to be the run as it existed just before deletion—including all of its actions. But this returns it with an empty list of actions.

In this same transaction, I think we need to fetch all actions for `row_to_delete`, and return them here.

This could use a test case, too.

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/tests/runs/test_run_store.py
> +    """Should not be able to insert an action with a run id the does not exist."""
```suggestion
    """Should not be able to insert an action with a run id that does not exist."""
```

2022-04-13 20:52 UTC, SyntaxColoring commented on robot-server/tests/runs/test_run_store.py
> +def test_add_run_current_run_deactivates(subject: RunStore) -> None:
It might also be good to test that other runs are marked non-current when you do an `update_active_run()`.

2022-04-14 00:49 UTC, TamarZanzouri commented on robot-server/robot_server/runs/run_store.py
> +        delete_statement = sqlalchemy.delete(run_table).where(run_table.c.id == run_id)
good catch! I will add it!

2022-04-14 00:59 UTC, TamarZanzouri commented on robot-server/tests/runs/test_run_store.py
> +def test_add_run_current_run_deactivates(subject: RunStore) -> None:
I agree!

2022-04-14 01:03 UTC, TamarZanzouri commented on robot-server/robot_server/runs/router/base_router.py
> +            is_current=update.current if update.current is not None else run.is_current,
I agree. This is old code that didnt make sense to me also but I didnt want to change it too much. It will only get into this block if the current is false so its never None and will always be False.

2022-04-14 01:04 UTC, TamarZanzouri commented on robot-server/robot_server/runs/router/base_router.py
> +            is_current=update.current if update.current is not None else run.is_current,
I will change it

2022-04-14 19:53 UTC, SyntaxColoring approved these changes
Looks good to me to merge. Thanks! 🏃 :shipit:

2022-04-14 19:54 UTC, merged