feat(protocol-designer): add tooltips to H-S stepform
OpenTrons/opentrons-api pull request #9944
Opened 2022-04-12 18:15 UTC by jerader

closes #9733

# Overview

This adds tooltips to H-S stepform and updates the `tooltip` component in shared components to reflect the new designs in UI overhaul. 

<img width="309" alt="Screen Shot 2022-04-12 at 2 02 46 PM" src="https://user-images.githubusercontent.com/66035149/163026755-1919caa9-984d-4cad-b684-dd2704833d5b.png">

<img width="168" alt="Screen Shot 2022-04-12 at 2 02 38 PM" src="https://user-images.githubusercontent.com/66035149/163026767-cc59ad65-437f-4d85-93f9-22944938b983.png">

# Changelog

- adds tooltips to `heaterShakerForm`
- changes designs of `tooltip`

# Review requests

- does it match designs? Do the tooltips appear when they are expected to?

# Risk assessment

low, behind ff

2022-04-12 19:06 UTC, shlokamin reviewed
Code changes look good!

In terms of design, just smoke tested and found some stuff
- the path selection fields in the transfer form need to be provided with a bigger width or else the gifs get cut off 
- the font size of the tooltips now looks pretty small

I'll let @howisthisnamenottakenyet provide more in depth design feedback

2022-04-13 20:31 UTC, shlokamin commented on components/src/tooltips/Tooltip.tsx
> +  backgroundColor?: string
these should already be included in `StyleProps` so we shouldn't actually need these!

2022-04-13 20:33 UTC, b-cooper commented on components/src/tooltips/Tooltip.tsx
> +  border-radius: ${spacingS};
I believe we have a border radius constant in the borders section. We shouldn't be putting spacing constants in anything but margin and padding.

2022-04-13 20:34 UTC, b-cooper commented on components/src/tooltips/Tooltip.tsx
> +    width = '8.75rem',
is this default width necessary?

2022-04-13 20:37 UTC, b-cooper commented on protocol-designer/src/components/StepEditForm/StepEditForm.css
> +.toggle_form_group_no_bottom_margin {
this class name goes against our conventions by baking in style concerns "no_bottom_margin". Can we name this based on the use-case. I believe this is only for the "set plate latch" control, so maybe something like "set_plate_latch_form_group"?

2022-04-13 20:38 UTC, b-cooper commented on protocol-designer/src/components/StepEditForm/fields/PathField/Path.tsx
> +    <Tooltip width="59.5%" {...tooltipProps}>
Do we really want this tooltip's width to be a percentage of its parent?

2022-04-13 20:42 UTC, jerader commented on components/src/tooltips/Tooltip.tsx
> +    width = '8.75rem',
I assumed the tooltips have a default width now: https://www.figma.com/file/l7BAJAGICr10ELsSqQD0Sr/UI-Overhaul?node-id=2345%3A87088

2022-04-13 20:45 UTC, shlokamin requested changes
path selection tooltips in PD are still off: 
![Screen Shot 2022-04-13 at 4 34 54 PM](https://user-images.githubusercontent.com/5788529/163266375-d6101f3a-a1e3-4e60-9c1d-2ab8e46ab30d.png)

looks like the `Tooltip` component is also used in dropdowns in labware creator, just checked and the font size looks pretty small (same thing as in PD since its the same component), but I'll defer to @howisthisnamenottakenyet:

![Screen Shot 2022-04-13 at 4 42 54 PM](https://user-images.githubusercontent.com/5788529/163267366-620591ee-c686-462a-b2a9-28a50936a4df.png)

2022-04-14 14:19 UTC, howisthisnamenottakenyet commented
> path selection tooltips in PD are still off: ![Screen Shot 2022-04-13 at 4 34 54 PM](https://user-images.githubusercontent.com/5788529/163266375-d6101f3a-a1e3-4e60-9c1d-2ab8e46ab30d.png)
> 
> looks like the `Tooltip` component is also used in dropdowns in labware creator, just checked and the font size looks pretty small (same thing as in PD since its the same component), but I'll defer to @howisthisnamenottakenyet:
> 
> ![Screen Shot 2022-04-13 at 4 42 54 PM](https://user-images.githubusercontent.com/5788529/163267366-620591ee-c686-462a-b2a9-28a50936a4df.png)

Sorry just catching up! What am I meant to weigh in on? Whether the font is too small?

2022-04-14 14:28 UTC, shlokamin commented
yep, give the tooltips a look in PD and LC and if they look fine to you we should be good!

2022-04-14 15:26 UTC, jerader commented
Going to make a tooltip component for in app tooltips in this follow up ticket: https://github.com/Opentrons/opentrons/issues/9962

2022-04-14 16:07 UTC, shlokamin approved these changes
code changes look good to me, would be great to get a designer's approval before merging though

2022-04-14 17:29 UTC, jerader commented
<img width="513" alt="Screen Shot 2022-04-14 at 1 27 45 PM" src="https://user-images.githubusercontent.com/66035149/163441928-0db3ead9-00d8-4bf3-bead-91a42833b78b.png">

@shlokamin, got feedback from @howisthisnamenottakenyet to keep font size the same as production.

2022-04-14 18:49 UTC, merged