test(robot-server): test for analyses and persistence of protocol upload
OpenTrons/opentrons-api pull request #9950
Opened 2022-04-12 20:29 UTC by y3rsh

# Overview

Upload a python protocol (POST /protocols) with 2 custom labware files.  Make sure the analysis has no errors and that the protocol is persisted on restart but the analysis is not.

# Risk assessment

None, test only.

2022-04-12 20:31 UTC, y3rsh commented on robot-server/tests/integration/http_api/persistence/test_protocol_persistence.py
> +async def test_protocol_and_labware_upload_persistance() -> None:
```suggestion
async def test_protocol_with_laware_upload_persistence() -> None:
```

2022-04-12 21:38 UTC, y3rsh commented
## Please wait to review, want to have [PR](https://github.com/Opentrons/opentrons/pull/9948) in first.
- [ ] merge Max's [PR](https://github.com/Opentrons/opentrons/pull/9948) into branch once on edge. 
- [ ] add get nonexistent protocol id test
- [ ] add delete nonexistent protocol id test
- [ ] manually test missing protocol file
- [ ] manually test extra protocol file

2022-04-20 14:48 UTC, aptrons22 requested changes
I just glanced over this.  I will review once completed.

2022-04-20 15:58 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/persistence/test_protocol_persistence.py
> +                6
Can we pull the timeouts for startup and shutdown up to a shared constant somewhere (probably shared between tests), and also bump it to something like `15`? 6 is slightly too optimistic for my poor MacBook Air.

2022-04-26 16:59 UTC, SyntaxColoring approved these changes
One typo, but looks good to merge. Thanks!

2022-04-26 16:59 UTC, SyntaxColoring commented on robot-server/tests/integration/http_api/protocols/test_persistence.py
> +async def test_protocol_with_laware_upload_persistence() -> None:
```suggestion
async def test_protocol_with_labware_upload_persistence() -> None:
```

2022-04-27 14:24 UTC, aptrons22 approved these changes
I tested and confirm all looks good.

2022-04-27 14:39 UTC, merged