feat(app): wire up firmware update banner in Module Cards
OpenTrons/opentrons-api pull request #9953
Opened 2022-04-13 19:38 UTC by jerader

closes #9155

# Overview

This PR wires up the firmware update banner when an update is available on a module. It follows the [figma flow](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=1297%3A87906)

<img width="289" alt="Screen Shot 2022-04-13 at 1 08 57 PM" src="https://user-images.githubusercontent.com/66035149/163256329-e4755ae1-dac3-44fd-9f25-d2c8361f422e.png">

<img width="594" alt="Screen Shot 2022-04-13 at 1 09 43 PM" src="https://user-images.githubusercontent.com/66035149/163256374-a068a556-6474-4f15-8ade-f33537aff2f5.png">

# Changelog

- adds logic to `moduleCard` and creates a modal for when the firmware update fails.

# Review requests

- when a firmware update is available on the module card, click on `update now`. That should start the update immedately. And the module card should have 50% opacity and the port and module name should be replaced with a spinner icon and the text "updating now". When the update is complete, a success toast should render at the bottom right of the viewport.

# Risk assessment

low, behind ff

2022-04-15 20:22 UTC, shlokamin commented on app/src/organisms/Devices/ModuleCard/index.tsx
> +  }
having this be triggered by a static timeout seems brittle. can we not just show aa success when the new firmware version is greater than the last firmware version?

2022-04-15 20:24 UTC, jerader commented on app/src/organisms/Devices/ModuleCard/index.tsx
> +  }
oooh i really like that idea. Will do!

2022-04-21 17:09 UTC, b-cooper commented on app/src/organisms/Devices/ModuleCard/FirmwareUpdateFailedModal.tsx
> +      <Text marginLeft={SPACING.spacing3}>{t('firmware_update_failed')}</Text>
All of the `Text`'s here can probably be replaced by `StyledText`'s. That way we can also take out the `fontSize={TYPOGRAPHY.fontSizeP}` from the wrapping `Flex` below

2022-04-21 17:10 UTC, b-cooper commented on app/src/organisms/Devices/ModuleCard/FirmwareUpdateFailedModal.tsx
> +        <Flex textTransform={TEXT_TRANSFORM_CAPITALIZE}>
I think this inner flex is unnecessary.  Can we move the `textTransform={TEXT_TRANSFORM_CAPITALIZE}` onto the `PrimaryButton` ?

2022-04-21 17:24 UTC, b-cooper commented on app/src/organisms/Devices/ModuleCard/index.tsx
> +    if (latestRequest?.status === SUCCESS) {
Looking below, i'm curious if we need the `fwVersion` react state at all. It seems like our source of truth about the module's version status should be read directly from the `module.hasAvailableUpdate` which is calculated on the robot by comparing the installed module firmware version with that of any new available module firmware.

In order to show a success toast when the module updates `hasAvailableUpdate` from true -> false, we could make use of a `React.useEffect` with a single dependency on `hasAvailableUpdate`

2022-04-21 17:27 UTC, b-cooper requested changes
Overall the designs look right, but the data-layer doesn't seem to be wired to the robot's source of truth effectively. We should be using the robot's concept of `hasAvailableUpdate` as a basis for determining whether to show "update module fw" or "up to date"

2022-04-21 17:28 UTC, jerader commented on app/src/organisms/Devices/ModuleCard/index.tsx
> +    if (latestRequest?.status === SUCCESS) {
Oh yeah, that makes sense to me! I'll change that now

2022-04-26 14:58 UTC, b-cooper approved these changes
✅   the changes look good!

2022-04-26 15:05 UTC, merged