feat(heater-shaker): add deactivate_heater method
OpenTrons/opentrons-api pull request #9955
Opened 2022-04-13 20:02 UTC by pmoegenburg

Currently, we only have a `deactivate` hardware controller class method. This PR adds `deactivate_heater` and `deactivate_shaker` methods for more granular control. To deactivate the heater, the `deactivate_heater` gcode is now used instead of `set_temperature(0)`, which disables heatpad power output instead of setting the temperature setpoint to 0. To properly update temperature status, the target temperature is set to None after heater is deactivated.

2022-04-13 20:37 UTC, sfoster1 requested changes
Looks good but let's add tests!

2022-04-14 21:51 UTC, sanni-t requested changes
Thanks for adding this! Some small change requests

2022-04-14 21:51 UTC, sanni-t commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +        self._listener.state.temperature.target = None
We shouldn't update the state here like this. Only the listener should update the state by reading from the module (I think that's what the listener is intended for). Besides, I believe the target will be overridden upon the next poll and set to the value that the target in `M105` response is. Will this value be `None`?

We should instead do a `self.wait_next_poll()` here to ensure that the target temperature is updated by reading from the poller's response.

2022-04-14 21:51 UTC, sanni-t commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +        self._listener.state.temperature.target = None
Same comment as above

2022-04-14 21:51 UTC, sanni-t commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
>          await self._driver.home()
Should do a `self.wait_next_poll()` here too to ensure that the state is updated correctly before returning.

2022-04-14 21:53 UTC, sanni-t commented on api/tests/opentrons/hardware_control/modules/test_hc_heatershaker.py
> +    await simulating_module.wait_next_poll()
Might not need to wait for next poll here if we add the wait to deactivate itself

2022-04-14 21:55 UTC, sanni-t commented on api/tests/opentrons/hardware_control/modules/test_hc_heatershaker.py
> +    await simulating_module.close_labware_latch()
I think instead of closing the latch, which does not affect deactivation in any way, this test can assert that the state has a target temperature & speed before deactivating, and then has no target temperature or speed after deactivating.

2022-04-15 23:35 UTC, pmoegenburg commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +        self._listener.state.temperature.target = None
I made the deactivate_heater gcode set the temperature setpoint to 0 in firmware, as we can't set setpoint to None in C++, and setting setpoint to 0 works with the current control logic. Currently a setpoint of 0 will occur if the heater is idle or in error, but the hardware control class does not differentiate between the two states. We don't currently have any firmware methods to `get_state`, and I see error checking is a TODO in the hardware control class.

2022-04-18 15:12 UTC, sanni-t commented on api/src/opentrons/hardware_control/modules/heater_shaker.py
> +        self._listener.state.temperature.target = None
I understand that a setpoint can't be set to None. But we can stop the PID from running, in which case the setpoint won't be in use and whenever the PID is not being used we can return a target of `None`. Or have a 'deactivated' flag decide whether to return a target of `None`. 

If the deactivate gcode is still doing the same thing as `set_temperature(celsius=0)`, then the target temperature is still going to be 0 degree celsius after a deactivate is issued. You might say that we can have the target temperature getter to check if target is 0 and return None if it is, but that's again a patchwork that doesn't need to happen when we haven't released the heatershaker api & firmware yet.

Treating 0 as a magic number and masking that number in status inside hardware_control can lead to a lot of confusion. One case I can think of right away is that it'll be tough to debug by looking at logs since the responses from the module will say target is 0 for both deactivated module as well as when the target is somehow actually set to 0.

2022-04-18 15:19 UTC, sanni-t commented on api/tests/opentrons/hardware_control/modules/test_hc_heatershaker.py
> +            "targetTemp": not None,
I'm surprised this test is passing. The `not "idle"` doesn't mean that it checks if the status is "idle" or something else. It simply does a `not True`. So this test is checking if the initial `live_data` is:
```
           "labwareLatchStatus": "idle_closed",
            "speedStatus": False,
            "temperatureStatus": False,
            "targetSpeed": True,
            "targetTemp": True,
```

2022-04-18 15:23 UTC, sanni-t commented on api/tests/opentrons/hardware_control/modules/test_hc_heatershaker.py
> +            "targetTemp": not None,
Since the initial state and the post-deactivation state of the heater-shaker is going to be the same, we will have to do something like:
- set a temperature and speed
- assert live_data has target temp & speed and appropriate temp & speed statuses
- deactivate heater-shaker
- assert live_data doesn't have target temp & speed and the statuses are `"idle"`

2022-04-28 13:21 UTC, sfoster1 approved these changes
Looks good to me!

2022-05-05 15:18 UTC, sanni-t approved these changes
🙌
Thanks for making all the changes. This looks good!

2022-05-09 17:07 UTC, merged