debt (robot-server): Enforce sqlite FK constraint
OpenTrons/opentrons-api pull request #9995
Opened 2022-04-18 18:42 UTC by TamarZanzouri

# Overview

Override default SqlAlchemy settings and force sqlite FK constraint. 

# Changelog

- override _set_sqlite_pragma to force support for foreign keys
- Removed redundant select statements to raise KF exceptions 
- Added tests to check for FK constraints

2022-04-18 19:45 UTC, TamarZanzouri commented on robot-server/robot_server/persistence.py
> +@event.listens_for(SQLEngine, "connect")  # type: ignore
is the #type: ignore explanatory? should I add description?

2022-04-18 19:47 UTC, TamarZanzouri commented on robot-server/tests/runs/test_run_store.py
> +    with pytest.raises(sqlalchemy.exc.IntegrityError, match="missing-run-id"):
Do we want to catch this error and raise instead RunNotFound?

2022-04-18 19:47 UTC, TamarZanzouri commented on robot-server/tests/runs/test_run_store.py
> +    with pytest.raises(sqlalchemy.exc.IntegrityError, match="missing-protocol-id"):
Do we want to catch this error and raise instead RunNotFound?

2022-04-20 13:15 UTC, mcous requested changes
- Little import naming request to avoid repeated `from sqlalchemy` imports
- We need to make the change you already called out; the `RunStore` should not emit `sqlalchemy.exc.IntegrityError`
    - Downstream users of the `RunStore` (the routers) do not understand how to handle these exceptions
    - They are already expecting `RunNotFoundError`
- I think we need to verify this change on actual hardware
    - Looks like support for this will be dependent on how Buildroot is set up to compile SQLite
    - I didn't see any red flags in the BR repo, so I can verify on my Rasp. Pi and approve if it all checks out

2022-04-20 13:15 UTC, mcous commented on robot-server/robot_server/runs/run_store.py
> -        raise RunNotFoundError(run_id) from e
Per your comment below, we still need this `raise`

2022-04-20 13:15 UTC, mcous commented on robot-server/tests/runs/test_run_store.py
> +    with pytest.raises(sqlalchemy.exc.IntegrityError, match="missing-run-id"):
Yes we do; SQLAlchemy details should not leak out of the store

2022-04-20 13:15 UTC, mcous commented on robot-server/robot_server/persistence.py
> +@event.listens_for(SQLEngine, "connect")  # type: ignore
We should be more specific and attach the specific error code as reported by mypy

```py
# type ignore[whatever-error-code-this-is-throwing]
```

Once that's on there, I don't think you need the comments about what mypy is expecting

2022-04-20 13:15 UTC, mcous commented on robot-server/robot_server/persistence.py
> +from sqlalchemy import event
Given that we've already done `import sqlalchemy` above, I would not separately import `create_engine` nor `event`. I think the code will be more readable if we use `sqlalchemy.create_engine` and `sqlalchemy.event`, since those terms are pretty generic and used elsewhere in run stuff! Scoping them to the `sqlalchemy` namespace gives the reader important context

2022-04-20 16:57 UTC, SyntaxColoring commented on robot-server/robot_server/persistence.py
> +@event.listens_for(SQLEngine, "connect")  # type: ignore
As written, I think this will apply this `PRAGMA` to *every SQLAlchemy engine in the whole process.* This is functionally fine because we're only creating SQLAlchemy engines here, anyway, but it feels a bit overreaching to me.

From https://docs.sqlalchemy.org/en/14/core/event.html#targets, I *think* we can restructure this like this:

```python
def open_db_no_cleanup(db_file_path: Path) -> SQLEngine:
    engine = create_engine(...)

    @event.listens_for(engine, "connect")  # type: ignore[error-code]
    def _set_sqlite_pragma(...) -> None:
        ...

    return engine
```

Notice that we pass in a `SQLEngine` *instance* to `listen`, instead of the `SQLEngine` class.

This will only apply the `PRAGMA` to engines created through this module.

2022-04-20 18:29 UTC, TamarZanzouri commented on robot-server/robot_server/persistence.py
> +@event.listens_for(SQLEngine, "connect")  # type: ignore
Love this! Thank you!

2022-04-20 19:41 UTC, TamarZanzouri commented on robot-server/robot_server/runs/run_store.py
> +from robot_server.protocols.protocol_store import ProtocolNotFoundError
Should I move ProtocolNotFound to a shared location?

2022-04-21 14:57 UTC, mcous reviewed
Still need to add a catch to the `runs/routers/base_router.py` for the `ProtocolNotFoundError` on run insert. Currently the endpoint will 500. This code path is quite difficult to hit regularly, but could conceivably be hit by concurrent `DELETE /protocols/:id` and `POST /runs` calls

2022-04-21 14:57 UTC, mcous commented on robot-server/robot_server/runs/run_store.py
> +from robot_server.protocols.protocol_store import ProtocolNotFoundError
It's already a public part of the `robot_server.protocols` module's interface. Import it from there instead of doing a deep import from `protocol_store`

```suggestion
from robot_server.protocols import ProtocolNotFoundError
```

2022-04-21 14:57 UTC, mcous commented on robot-server/robot_server/runs/run_store.py
> +                assert run.protocol_id is not None
This strikes me as a little iffy; is there any way we can pull out the specific integrity error rather than raise a 500 due to an AssertionError

2022-04-21 18:20 UTC, TamarZanzouri commented on robot-server/robot_server/runs/run_store.py
> +                assert run.protocol_id is not None
We can remove the FK constraint and add the logic ourselves like the has implementation you add in the analysis PR. One more way is to convert the assert to an if and raise ProtocolNotFoundError else raise a different exception

2022-04-21 18:31 UTC, TamarZanzouri commented on robot-server/robot_server/runs/run_store.py
> +                assert run.protocol_id is not None
> Still need to add a catch to the `runs/routers/base_router.py` for the `ProtocolNotFoundError` on run insert. Currently the endpoint will 500. This code path is quite difficult to hit regularly, but could conceivably be hit by concurrent `DELETE /protocols/:id` and `POST /runs` calls

We don't want to propagate this exception to the client? what is expected to happen in the catch block?

2022-04-21 18:50 UTC, mcous commented on robot-server/robot_server/runs/run_store.py
> +                assert run.protocol_id is not None
Discussed in person!

- Catch `ProtocolNotFoundError` from `run_store.insert` in the router to respond with a 404
- Add an assertion message to this assert to make the code a little easier to read and follow, but otherwise the 500 is actually what we want here

2022-04-21 19:37 UTC, mcous approved these changes
Changes look good, appears to work with real hardware!

2022-04-25 17:25 UTC, SyntaxColoring approved these changes
Code looks good to merge. Thanks!

2022-04-25 17:32 UTC, merged